{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a46-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zzwrv7bhbfgvlhoshhgo5ogf5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a46-android-0.2.3.aar",
          "url": "ble-characteristic-u2a46-android-0.2.3.aar",
          "size": 2957,
          "sha512": "918968479e331c9a83a98d52a97b28de58d66d1243017043c58648f2f4c71a5e6ea227bbec068b48950072055bff0785b5fb037cf2a2d1acca45ce972d094407",
          "sha256": "084154a32e0e7c65ace4e542684790a207e631044202ff27751134ae3fbc5a53",
          "sha1": "6f2579771f1f383dde4a930ba3bcb92ff113d785",
          "md5": "00958e11347924e4e935c38e4a9fa640"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a46-android-0.2.3.aar",
          "url": "ble-characteristic-u2a46-android-0.2.3.aar",
          "size": 2957,
          "sha512": "918968479e331c9a83a98d52a97b28de58d66d1243017043c58648f2f4c71a5e6ea227bbec068b48950072055bff0785b5fb037cf2a2d1acca45ce972d094407",
          "sha256": "084154a32e0e7c65ace4e542684790a207e631044202ff27751134ae3fbc5a53",
          "sha1": "6f2579771f1f383dde4a930ba3bcb92ff113d785",
          "md5": "00958e11347924e4e935c38e4a9fa640"
        }
      ]
    }
  ]
}
