{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290c",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fvvoe34nybbdlbbrzowl64zzta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.2.3.jar",
          "url": "ble-descriptor-u290c-0.2.3.jar",
          "size": 3934,
          "sha512": "099a53bc07c5d3684cc9b8c4e1023633e1be53b0122d8d9f4f9882a29ad0835f687166121c3b5697c4e842759a18730d2acad6c49e479085e0debfe7937126da",
          "sha256": "e13f1860081687931e540a41b9bb580d0633590d18972d48f8590b8781809266",
          "sha1": "5aef57b4c44aabee7dde004fd406784a595e74b0",
          "md5": "11607dcaa119a2158cf43a2f2579ccfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.2.3.jar",
          "url": "ble-descriptor-u290c-0.2.3.jar",
          "size": 3934,
          "sha512": "099a53bc07c5d3684cc9b8c4e1023633e1be53b0122d8d9f4f9882a29ad0835f687166121c3b5697c4e842759a18730d2acad6c49e479085e0debfe7937126da",
          "sha256": "e13f1860081687931e540a41b9bb580d0633590d18972d48f8590b8781809266",
          "sha1": "5aef57b4c44aabee7dde004fd406784a595e74b0",
          "md5": "11607dcaa119a2158cf43a2f2579ccfc"
        }
      ]
    }
  ]
}
