{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a90",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.5.jar",
          "url": "ble-characteristic-u2a90-0.8.5.jar",
          "size": 2290,
          "sha512": "026d2870b31867a7ed7c86523cb16cf9e6fe4eb0f1c76e272e7f31e94a2ebb48925ab1c538ddaf72cca1a3ea48741cb8acbcfa0d67964638c49e912710ad5368",
          "sha256": "1095bf022e3283ee5908338f3a098fd80d4f111af49a5ed610912b518b8d0894",
          "sha1": "ba9e12e2007ee6a85c2637cb94930639f92b087d",
          "md5": "e9dc0e3549b10f28f0ddfb819975c3f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.5.jar",
          "url": "ble-characteristic-u2a90-0.8.5.jar",
          "size": 2290,
          "sha512": "026d2870b31867a7ed7c86523cb16cf9e6fe4eb0f1c76e272e7f31e94a2ebb48925ab1c538ddaf72cca1a3ea48741cb8acbcfa0d67964638c49e912710ad5368",
          "sha256": "1095bf022e3283ee5908338f3a098fd80d4f111af49a5ed610912b518b8d0894",
          "sha1": "ba9e12e2007ee6a85c2637cb94930639f92b087d",
          "md5": "e9dc0e3549b10f28f0ddfb819975c3f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a90-0.8.5-javadoc.jar",
          "size": 107340,
          "sha512": "90d111c7ec905a2638bc83d3e1d2e368292432143785338370d5b3973278b2bb3bcc74ab1f6eb83642a9ee1d0f55683b95f31a0432a00ff135fbc3191df30b2d",
          "sha256": "5cad9ba61d1fd8556c2e9a36cfb063809fef04e8f28cfc9f095b354477465e9b",
          "sha1": "0259f94b4cd4f3021a77435eafa79efb7cc70898",
          "md5": "7111e8b57dcd06ac719b58a5d916a6b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a90-0.8.5-sources.jar",
          "size": 1778,
          "sha512": "fddd379e3b45ca15390a507228ab8ee2f96a935c5fa803c72191a0f51034fad941f5349e0fa6384530587712067bcf3a288854e0fbb29f7078389b5466811052",
          "sha256": "b7c70b9c7aca32936cbc05fec44ed184b91d3cc950cd249dad6c2de8b669498a",
          "sha1": "666d88c60432b81c5c469452c3b3c59f698c6033",
          "md5": "7bcd414fa13e08dc191020a9d199352a"
        }
      ]
    }
  ]
}
