{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b26",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.6.jar",
          "url": "ble-characteristic-u2b26-0.8.6.jar",
          "size": 1454,
          "sha512": "da450142d9c4a148c551b1a1569d139acf12851aef053409e9aa4864129e5a8b462e4f8d429964b23443387e3e8c98c021d7fd69dff9dc11fc1761b4aa1166db",
          "sha256": "71d06fcdaeecc4e895aee4e1e6186fa1f6035d21582e284f4853b369e2254c40",
          "sha1": "d8300aa8203beb5d8169f28974c1da325b1f1ffa",
          "md5": "d99eb48af205fdaf7e811a63c10a228f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.6.jar",
          "url": "ble-characteristic-u2b26-0.8.6.jar",
          "size": 1454,
          "sha512": "da450142d9c4a148c551b1a1569d139acf12851aef053409e9aa4864129e5a8b462e4f8d429964b23443387e3e8c98c021d7fd69dff9dc11fc1761b4aa1166db",
          "sha256": "71d06fcdaeecc4e895aee4e1e6186fa1f6035d21582e284f4853b369e2254c40",
          "sha1": "d8300aa8203beb5d8169f28974c1da325b1f1ffa",
          "md5": "d99eb48af205fdaf7e811a63c10a228f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2b26-0.8.6-javadoc.jar",
          "size": 107172,
          "sha512": "b55f714d28ac315bba00ff0657a08be53370aa234b539315483c8d92f90bb45d1c69f9484228ed07ef48abb27651876c26ab0c9e8630ff0e301d284504fffe8d",
          "sha256": "933d4d1b60cbca3c5878575656a879c55f0b24cc48548fe84429986b5ceb1e27",
          "sha1": "877b443bf7453419f1a4d2a5a136043783c30377",
          "md5": "3ec7ae6c37c3122404d0b188c11991d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b26-0.8.6-sources.jar",
          "size": 1445,
          "sha512": "ba5202e24848e859d053ed120e619b5553cb3675e83e0123f7b061e1358301e45eb3a4ed771d0cac153c94e3500656271482c82df3284ab20884dfffd031c1d3",
          "sha256": "51def42f24ede775feebadf19e6c35439e3a1e8edd1938f594c1301faeed7bec",
          "sha1": "63793e0328de8a7f20ceb9605dff640b6500c1cb",
          "md5": "9885b515e403ea42c00bf1e986677e0f"
        }
      ]
    }
  ]
}
