{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa3",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.0.jar",
          "url": "ble-characteristic-u2aa3-0.8.0.jar",
          "size": 2258,
          "sha512": "f1fc887b61e3a6688425327525fab45358700e26813104eab19630a520158c9f0f987e8575cf0eae70f89e9b55bc4e0d98544e73b94e9b7ff708f5cdd5b1eaff",
          "sha256": "9bcada0e8fc544f5d66100e3b08c7ec7234543143644b7e666860b0eecd945ff",
          "sha1": "a1b1187c9773fe8b3509c7dc37004e2f9094ec1e",
          "md5": "f07901fb3ab2f8f6521b5195acd61e14"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.0.jar",
          "url": "ble-characteristic-u2aa3-0.8.0.jar",
          "size": 2258,
          "sha512": "f1fc887b61e3a6688425327525fab45358700e26813104eab19630a520158c9f0f987e8575cf0eae70f89e9b55bc4e0d98544e73b94e9b7ff708f5cdd5b1eaff",
          "sha256": "9bcada0e8fc544f5d66100e3b08c7ec7234543143644b7e666860b0eecd945ff",
          "sha1": "a1b1187c9773fe8b3509c7dc37004e2f9094ec1e",
          "md5": "f07901fb3ab2f8f6521b5195acd61e14"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.0-javadoc.jar",
          "url": "ble-characteristic-u2aa3-0.8.0-javadoc.jar",
          "size": 112689,
          "sha512": "2bac6facc1a7bd151f831e8e27c576038879094c9e6dae6e48cc6134366e68824f0b523a1e99bd8c0db61070ad2c6fd3b11a8e01ae38b91104e23f01667c7760",
          "sha256": "b5bd68c49f96f51213565cab0ff33119942f54458f123a502b3eaf3db58f753d",
          "sha1": "68adb2e651ea33f9b1d41280183f5a95a4ad7b35",
          "md5": "4660b7fe16734732e9e1f148029f8cd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.0-sources.jar",
          "url": "ble-characteristic-u2aa3-0.8.0-sources.jar",
          "size": 2145,
          "sha512": "5de2dfb269e63ad37fab6d4308c539d843e918ec2f48abba2810426522af794dad0714306ffef34471f8b5855a05a892c190821174e72416d6d61e2cc6f53b01",
          "sha256": "36851902bc2ce322096fd3a80b634c8e481bb8f809f45dc650ac21080cd2d629",
          "sha1": "eaa7e8e79bf4665862de66846e724d40dbca4839",
          "md5": "680555b24f0678cd1e4bc6fe76503b6c"
        }
      ]
    }
  ]
}
