{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1c",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.5.1.jar",
          "url": "ble-characteristic-u2b1c-0.5.1.jar",
          "size": 1791,
          "sha512": "171e6e92c993a3272d8a8da39d835d59c42860d599dcf237993f08dde9126dfe9e8275a7e321a31d987a9556e2cfc753b2a3976f1285f221fe412f348b6350fc",
          "sha256": "4de6bbe5d0f77a494ee11a0bb9c2a7136cdca9b4ee4552b7ccb247d298092dd3",
          "sha1": "329bd1c689a267a98b912f475692ecd16ea27da9",
          "md5": "c57d96bd600dc5be3d7d92ddac8cb66c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.5.1.jar",
          "url": "ble-characteristic-u2b1c-0.5.1.jar",
          "size": 1791,
          "sha512": "171e6e92c993a3272d8a8da39d835d59c42860d599dcf237993f08dde9126dfe9e8275a7e321a31d987a9556e2cfc753b2a3976f1285f221fe412f348b6350fc",
          "sha256": "4de6bbe5d0f77a494ee11a0bb9c2a7136cdca9b4ee4552b7ccb247d298092dd3",
          "sha1": "329bd1c689a267a98b912f475692ecd16ea27da9",
          "md5": "c57d96bd600dc5be3d7d92ddac8cb66c"
        }
      ]
    }
  ]
}
