{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a23-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zzwrv7bhbfgvlhoshhgo5ogf5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a23",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a23-android-0.2.3.aar",
          "url": "ble-characteristic-u2a23-android-0.2.3.aar",
          "size": 2926,
          "sha512": "de53a40c557320294d3b03747070275d6ee85a365023edb1c71b23b730cd42ddb1344d28a327aa791886b4444ef7a51590e59bab514de8717cb078e9c9ed9095",
          "sha256": "a3efc70cf29753d487060f24127944ecbb7f2eca870b72f20a5f39f5db772c69",
          "sha1": "e2c177d134dc8b21bb252f6c4cce1e0687fbc682",
          "md5": "14e6b8412603e6569285cef3c9ed2210"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a23",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a23-android-0.2.3.aar",
          "url": "ble-characteristic-u2a23-android-0.2.3.aar",
          "size": 2926,
          "sha512": "de53a40c557320294d3b03747070275d6ee85a365023edb1c71b23b730cd42ddb1344d28a327aa791886b4444ef7a51590e59bab514de8717cb078e9c9ed9095",
          "sha256": "a3efc70cf29753d487060f24127944ecbb7f2eca870b72f20a5f39f5db772c69",
          "sha1": "e2c177d134dc8b21bb252f6c4cce1e0687fbc682",
          "md5": "14e6b8412603e6569285cef3c9ed2210"
        }
      ]
    }
  ]
}
