{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core",
    "version": "0.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ok53hul7zjdznoaoe7p5sj5cvi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-0.3.1.jar",
          "url": "ble-core-0.3.1.jar",
          "size": 74868,
          "sha512": "383174015270f7f57318d735dbaa93726186c5616b3440dd45a5a7e8108e7f70e5fbb8274193bff65d2fcdff7447a962c4b6ee6e34f8c0f51da6477354d0991b",
          "sha256": "da72c91ee4a1fb12a00a8b11628ae543003b441ec74dbd13d4ba391a46cc8d11",
          "sha1": "ca9e07e7748b8a10a2e866af69243e46822c63b4",
          "md5": "e95cd5f524c4e3cae666e849a8088e20"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-0.3.1.jar",
          "url": "ble-core-0.3.1.jar",
          "size": 74868,
          "sha512": "383174015270f7f57318d735dbaa93726186c5616b3440dd45a5a7e8108e7f70e5fbb8274193bff65d2fcdff7447a962c4b6ee6e34f8c0f51da6477354d0991b",
          "sha256": "da72c91ee4a1fb12a00a8b11628ae543003b441ec74dbd13d4ba391a46cc8d11",
          "sha1": "ca9e07e7748b8a10a2e866af69243e46822c63b4",
          "md5": "e95cd5f524c4e3cae666e849a8088e20"
        }
      ]
    }
  ]
}
