{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a66",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a66-0.8.7.jar",
          "url": "ble-characteristic-u2a66-0.8.7.jar",
          "size": 5682,
          "sha512": "fa54ceff631c8c0c0e19798414eddfb903634ba90a43439755ee61f4f6c0e2c2f46057691f23fdee0a3213987a4761fe81c43353b6d7f1a541a52afb1474924c",
          "sha256": "33d18e1dba2b7d879cd7f91f1dfa90878626a1781c52dd43ecb3d407ca225212",
          "sha1": "4586f7cdbb892a60db71972760dd9263cb8452f3",
          "md5": "5c4958a7cb33bf91084e4ac49acaf525"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a66-0.8.7.jar",
          "url": "ble-characteristic-u2a66-0.8.7.jar",
          "size": 5682,
          "sha512": "fa54ceff631c8c0c0e19798414eddfb903634ba90a43439755ee61f4f6c0e2c2f46057691f23fdee0a3213987a4761fe81c43353b6d7f1a541a52afb1474924c",
          "sha256": "33d18e1dba2b7d879cd7f91f1dfa90878626a1781c52dd43ecb3d407ca225212",
          "sha1": "4586f7cdbb892a60db71972760dd9263cb8452f3",
          "md5": "5c4958a7cb33bf91084e4ac49acaf525"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a66-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a66-0.8.7-javadoc.jar",
          "size": 120451,
          "sha512": "b56243a8340fc8031ae16b9eece9b05de2025c21e07dc9b2f8c4f4ae0466d2220145a19746b41595584a8be90991275a11bc6d402af778f4503cf67648f9b157",
          "sha256": "810d1d7e0f73262f26401b222e7304d10069318477c8171fb0cb07f5ca686139",
          "sha1": "a83d2934f1da33659736c9b6024800c77c0d9fd1",
          "md5": "c7dcc144ce4eb2d3d5253e01cd898629"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a66-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a66-0.8.7-sources.jar",
          "size": 5236,
          "sha512": "bbf5ef3eba0f14e3a1e916206a688b645ec66b03f68128ee82350682814ad83778d27699cf0a7832edcb241186e8c1ba2c7bbe71ddf6640961ddf1f587e67197",
          "sha256": "16a808c48a0782fdec755bfe620f3b685ba17806b31c06fa222241e7fcf9723f",
          "sha1": "0fca87fbfd12425520bd31f13d272f819605ca8b",
          "md5": "6ed5ed4a77878aa54b1ef1875549e504"
        }
      ]
    }
  ]
}
