{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aad",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "4rcxyhsfnnaxpc6k4tjdzk6t5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.1.0.jar",
          "url": "ble-characteristic-u2aad-0.1.0.jar",
          "size": 1725,
          "sha512": "68409e2929f49fb8789b8f750a8fc2ac5b937c137e726690c8257ebd2a7eec8449828102f6cc0dc0392e8ffabd52e3231bea08feae846110aa05ed608fd31bde",
          "sha256": "7f523e9a893b4db5e8c2a093464109b07885e88f121ea8f9420ce94de3f3d0ed",
          "sha1": "bc738efa3a6e769bcb4e8fb8e1b4609179f77d1",
          "md5": "8ba9f711b703335c621acc34cb8cd776"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.1.0.jar",
          "url": "ble-characteristic-u2aad-0.1.0.jar",
          "size": 1725,
          "sha512": "68409e2929f49fb8789b8f750a8fc2ac5b937c137e726690c8257ebd2a7eec8449828102f6cc0dc0392e8ffabd52e3231bea08feae846110aa05ed608fd31bde",
          "sha256": "7f523e9a893b4db5e8c2a093464109b07885e88f121ea8f9420ce94de3f3d0ed",
          "sha1": "bc738efa3a6e769bcb4e8fb8e1b4609179f77d1",
          "md5": "8ba9f711b703335c621acc34cb8cd776"
        }
      ]
    }
  ]
}
