{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a34",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.7.jar",
          "url": "ble-characteristic-u2a34-0.8.7.jar",
          "size": 1482,
          "sha512": "8229de86e5693c7a4482d457f83126d836c90d799e35b4f0be975211e0e6f6f37203e4fb870db8ac215e43f84268cc1bb116f3d372507e32223f4be0ed0d68d3",
          "sha256": "02d632252723761b42e7f50ec8e226ceded46fe51e63bfcce3b3e216198a8574",
          "sha1": "22f94dda6d285dda6492cfd1adf561031ed0ffa5",
          "md5": "a96e640607c094ab4bc4c2a84d958d63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.7.jar",
          "url": "ble-characteristic-u2a34-0.8.7.jar",
          "size": 1482,
          "sha512": "8229de86e5693c7a4482d457f83126d836c90d799e35b4f0be975211e0e6f6f37203e4fb870db8ac215e43f84268cc1bb116f3d372507e32223f4be0ed0d68d3",
          "sha256": "02d632252723761b42e7f50ec8e226ceded46fe51e63bfcce3b3e216198a8574",
          "sha1": "22f94dda6d285dda6492cfd1adf561031ed0ffa5",
          "md5": "a96e640607c094ab4bc4c2a84d958d63"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a34-0.8.7-javadoc.jar",
          "size": 107226,
          "sha512": "34b69da6aebef2828ebdef0c27b8cd7d614d0305cb3b574d26b97913b671a9b31e1e54f7b4083ba98db834871484f45a58c76c87e152a0f17d790868878f7b74",
          "sha256": "87edd307a7351d65c4c5d0a45d3fd9c44d015ac4b4503b2e922a1ef20c3b71ea",
          "sha1": "a18b08929ffc4ca8f77e17caf4266bf571c52b50",
          "md5": "706c432def4b72e373b9d13f0c80c3d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a34-0.8.7-sources.jar",
          "size": 1487,
          "sha512": "d8eac13de7c7376cfa491c82a4e7e53a0af516edaebdcb5fdf446692a2f348cb042d3c7c284ef45ab4adde5bddc7a3598be835cb88dc6a3f57543a020be28cb9",
          "sha256": "2d1d14905219a1e5ba773da803973054ba28d2072bb7a7aa063dd2a1c1631643",
          "sha1": "13bb6b528d47054e57b4046ad85c7d1c6c8ce765",
          "md5": "3b6ade100549a9a72becd0b182b0ad3e"
        }
      ]
    }
  ]
}
