{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a0d",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0d-0.8.6.jar",
          "url": "ble-characteristic-u2a0d-0.8.6.jar",
          "size": 1749,
          "sha512": "8207ff595ed35e32049f2affeef9ea42b2cf33adffd8cf6021d462d87809fbb4d18789b03a59909d9bf9f6ff8220efea672a0cd43b19dc57749b95f1f774d5d7",
          "sha256": "a0fb32a0b168d2ab7ed1bb9f393da86d92d119f12a4ab26b944b0ae6c08169cb",
          "sha1": "b946e01f5c314c02482b111231b3f7b5e83d83da",
          "md5": "5dfb9a7e7a69a04174611586488b6c24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0d-0.8.6.jar",
          "url": "ble-characteristic-u2a0d-0.8.6.jar",
          "size": 1749,
          "sha512": "8207ff595ed35e32049f2affeef9ea42b2cf33adffd8cf6021d462d87809fbb4d18789b03a59909d9bf9f6ff8220efea672a0cd43b19dc57749b95f1f774d5d7",
          "sha256": "a0fb32a0b168d2ab7ed1bb9f393da86d92d119f12a4ab26b944b0ae6c08169cb",
          "sha1": "b946e01f5c314c02482b111231b3f7b5e83d83da",
          "md5": "5dfb9a7e7a69a04174611586488b6c24"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a0d-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a0d-0.8.6-javadoc.jar",
          "size": 107321,
          "sha512": "2cc0a13963529767d4d363d73bfd19145b96bd4be84e9714ec5b0a2ef489ae59e8750663886f8841b89cc7c1d7332b25809381ebd06b009a14356d66d8f65fe1",
          "sha256": "f18bc25f58b9c9b199695357a3da27eb095b83c6c1efe0c22801776bc4a0256e",
          "sha1": "678b1fac76232c4c7c77b9a00288d4aaeee34621",
          "md5": "b7e1cfdc9ae1f0817d2c0da150b4b128"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a0d-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a0d-0.8.6-sources.jar",
          "size": 1589,
          "sha512": "721d48024d9ccc4e8b3930fc309fe5acd9ee300ab7ca84b03859cf043162cda2988420ee5908a8495572448980e68ce8a0e797802aa229e6cdadcc70ca3578c6",
          "sha256": "92ae79221751ee4128ce2a8b38091914d1290397483746765e40851e36d004db",
          "sha1": "9086accda65ab45982c39a2c53ce249ea61f5986",
          "md5": "f296d598650bb17d0e18a8c1c556e25f"
        }
      ]
    }
  ]
}
