{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a90-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.2.4.aar",
          "url": "ble-characteristic-u2a90-android-0.2.4.aar",
          "size": 2954,
          "sha512": "3d7c7c324fdbbafba1bf5a602a8f2d4ae6c3c5fe291d74386677ffc5dec62e021dad1ab674611f72720f6e25fbd6136ce383580cfc4baa3a476332af64ae5f9c",
          "sha256": "526d04eff68f6a6052497f376910914c69a1694105fe762b94296ceafcd14931",
          "sha1": "4a69c988297a38ea9cc1a533589b02195dc6e374",
          "md5": "cc5df7ffdb639b4f6fedd4f6d2b7a65a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.2.4.aar",
          "url": "ble-characteristic-u2a90-android-0.2.4.aar",
          "size": 2954,
          "sha512": "3d7c7c324fdbbafba1bf5a602a8f2d4ae6c3c5fe291d74386677ffc5dec62e021dad1ab674611f72720f6e25fbd6136ce383580cfc4baa3a476332af64ae5f9c",
          "sha256": "526d04eff68f6a6052497f376910914c69a1694105fe762b94296ceafcd14931",
          "sha1": "4a69c988297a38ea9cc1a533589b02195dc6e374",
          "md5": "cc5df7ffdb639b4f6fedd4f6d2b7a65a"
        }
      ]
    }
  ]
}
