{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6a-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.1.6.aar",
          "url": "ble-characteristic-u2a6a-android-0.1.6.aar",
          "size": 3017,
          "sha512": "0d46fd6f5aa592b89f76f7cb07e412d21e6d421c61c848ab820e799df5202bfa804627ed71900445cf5bd813ef946692d6c2912650813419a7e5be08533e0f59",
          "sha256": "b3461724d257bd1fcb38ed7b7e73095fa989902994effe350eab66fc5860b5c5",
          "sha1": "f07965b8453344c14165cc1107d9333916c539ca",
          "md5": "ff6a53b38c4a0702b747d378ea354897"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.1.6.aar",
          "url": "ble-characteristic-u2a6a-android-0.1.6.aar",
          "size": 3017,
          "sha512": "0d46fd6f5aa592b89f76f7cb07e412d21e6d421c61c848ab820e799df5202bfa804627ed71900445cf5bd813ef946692d6c2912650813419a7e5be08533e0f59",
          "sha256": "b3461724d257bd1fcb38ed7b7e73095fa989902994effe350eab66fc5860b5c5",
          "sha1": "f07965b8453344c14165cc1107d9333916c539ca",
          "md5": "ff6a53b38c4a0702b747d378ea354897"
        }
      ]
    }
  ]
}
