{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab2-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab2",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab2-android-0.8.6.aar",
          "url": "ble-characteristic-u2ab2-android-0.8.6.aar",
          "size": 3075,
          "sha512": "27d2fe6c4d9af1db39d195a225d1f0b55f3c2733bce607bbfa253d364f27d42f9ca89480d4932284f8786b59021f3c30a4d259eda66d12c452addfeeaa50ceaa",
          "sha256": "935f5dc4e9a196c45403bb00f20cd27710ce9b7ff1fe82d746867b92b808b499",
          "sha1": "c49aaf79ceaff570740bd1b584c3c8e9cbad817d",
          "md5": "873388a4b8bb0921d22291ca7b70817e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab2",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab2-android-0.8.6.aar",
          "url": "ble-characteristic-u2ab2-android-0.8.6.aar",
          "size": 3075,
          "sha512": "27d2fe6c4d9af1db39d195a225d1f0b55f3c2733bce607bbfa253d364f27d42f9ca89480d4932284f8786b59021f3c30a4d259eda66d12c452addfeeaa50ceaa",
          "sha256": "935f5dc4e9a196c45403bb00f20cd27710ce9b7ff1fe82d746867b92b808b499",
          "sha1": "c49aaf79ceaff570740bd1b584c3c8e9cbad817d",
          "md5": "873388a4b8bb0921d22291ca7b70817e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab2-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ab2-android-0.8.6-sources.jar",
          "size": 2156,
          "sha512": "28dfc6221b2c9f3311102db8e7b892f63f73964767ed2754508f8c23fe879ae436cd4bf65b03ebce58f0373fd346f83931fa628e79eb74007cfc80b809257d4b",
          "sha256": "43b4c1c9973804ce0f0709a0c718421842dcf1cd2c4eaa353345474dfdbcf424",
          "sha1": "e56fbebbb61e7a52e696d1bbcd6ecc1541685149",
          "md5": "a4275e255c908ea8703a2a9eab771477"
        }
      ]
    }
  ]
}
