{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-hrs-central-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hrs-central-android-0.1.0.aar",
          "url": "ble-service-hrs-central-android-0.1.0.aar",
          "size": 5926,
          "sha512": "cf876a563db23b55226b7f5142a04283b12ebfdc030afe8c457b9661e71768bfedf6b48bfe47c15303f330c54f2d66ddeb579e146a9eb43efc14d5bde69ce5d7",
          "sha256": "40c79413b504cd6eeffa07b91d4a39f79513a24afffca9010d8b61fc51ad8e2a",
          "sha1": "57125b32e0b6fd0ff8cb2cbd09c61c997cbf29e8",
          "md5": "95164d9311bfa9425da6297050073b21"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hrs-central-android-0.1.0.aar",
          "url": "ble-service-hrs-central-android-0.1.0.aar",
          "size": 5926,
          "sha512": "cf876a563db23b55226b7f5142a04283b12ebfdc030afe8c457b9661e71768bfedf6b48bfe47c15303f330c54f2d66ddeb579e146a9eb43efc14d5bde69ce5d7",
          "sha256": "40c79413b504cd6eeffa07b91d4a39f79513a24afffca9010d8b61fc51ad8e2a",
          "sha1": "57125b32e0b6fd0ff8cb2cbd09c61c997cbf29e8",
          "md5": "95164d9311bfa9425da6297050073b21"
        }
      ]
    }
  ]
}
