{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-hrs-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-hrs-android-0.8.13.aar",
          "url": "ble-service-central-hrs-android-0.8.13.aar",
          "size": 6334,
          "sha512": "521c3e8c7cf3665127f4bfc561c34cfdf76681edf038330a4b1d4565e5f970b3f6d161717b2ec97edc82d3f38166e4ba190d17dd2aad37a0bc4062f362f71d86",
          "sha256": "9dd943f0710346ecda3b23a07ddc669e03b9409c3ea7d0f42e4d483ee6ded984",
          "sha1": "c26733bf2c4383b3fa30fde1c728004d941a9cb5",
          "md5": "d51fb6a15a711f69f30e1d2ae1d4a42b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-hrs-android-0.8.13.aar",
          "url": "ble-service-central-hrs-android-0.8.13.aar",
          "size": 6334,
          "sha512": "521c3e8c7cf3665127f4bfc561c34cfdf76681edf038330a4b1d4565e5f970b3f6d161717b2ec97edc82d3f38166e4ba190d17dd2aad37a0bc4062f362f71d86",
          "sha256": "9dd943f0710346ecda3b23a07ddc669e03b9409c3ea7d0f42e4d483ee6ded984",
          "sha1": "c26733bf2c4383b3fa30fde1c728004d941a9cb5",
          "md5": "d51fb6a15a711f69f30e1d2ae1d4a42b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-hrs-android-0.8.13-sources.jar",
          "url": "ble-service-central-hrs-android-0.8.13-sources.jar",
          "size": 5431,
          "sha512": "aed8b920c1024454c602322b59002c51d77ce9beb33b620eaf91d13a2050fa74c873aa6b22f9d289dd819187a8824298657388dcc4bc3de0881b2348b9c78a1c",
          "sha256": "045f7bfc8d770b8f22474f5da720eb5bab0416627170d7adef0374e777f20494",
          "sha1": "33840895a8f73391c05af4be0bc018ee3e420516",
          "md5": "898133976a4b7dfe147a4aab022f7551"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-hrs-android-0.8.13-javadoc.jar",
          "url": "ble-service-central-hrs-android-0.8.13-javadoc.jar",
          "size": 284119,
          "sha512": "e958a48686469edf26fe34d528dd79514c82c4cd006d92458b2e45c880956798f1a2d498b9b23f9f489337089b4107f44586535d89ffc461ffa08fbcae012c6c",
          "sha256": "c51895a7d30dcebb1c1d98c7c0cf8516b006e3f6a573adb84799172f973a74ab",
          "sha1": "005868e6c6bfd4edb2a0a190e56dd09120953cd2",
          "md5": "e4bc997b50b690df33ee84109ee46d85"
        }
      ]
    }
  ]
}
