{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b25",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.7.jar",
          "url": "ble-characteristic-u2b25-0.8.7.jar",
          "size": 1473,
          "sha512": "f4ea171524d027d1052b35a8a4150f1a1d2d2b6af90764847dcfb98e6aa2d11da1e04f358ce695cf2288f9c44a737b612ec17b2d9c2a62243a2d1a669cf040cb",
          "sha256": "b10023c20a67451d1aae0a8aba0d6f22af348a8685ff0b31ac6b3b93767abe0d",
          "sha1": "4f45eae5f515e6b057c00f279864d1b3dcf813fe",
          "md5": "70b8528ad656fcbfb4a998b0696f1dbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.7.jar",
          "url": "ble-characteristic-u2b25-0.8.7.jar",
          "size": 1473,
          "sha512": "f4ea171524d027d1052b35a8a4150f1a1d2d2b6af90764847dcfb98e6aa2d11da1e04f358ce695cf2288f9c44a737b612ec17b2d9c2a62243a2d1a669cf040cb",
          "sha256": "b10023c20a67451d1aae0a8aba0d6f22af348a8685ff0b31ac6b3b93767abe0d",
          "sha1": "4f45eae5f515e6b057c00f279864d1b3dcf813fe",
          "md5": "70b8528ad656fcbfb4a998b0696f1dbb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b25-0.8.7-javadoc.jar",
          "size": 107244,
          "sha512": "7e3205e0f83f30fe0bde7fda03d7edb5d558109cf5db0f5e4a82003a73610c671564907880094d4f980c2011b08f1971843fdca9cc86d6e7de8e63e7c1aa0648",
          "sha256": "e70896b84a3e1441f6ee01e1870b5c8da142585a342a17d6268ccce078d87bc6",
          "sha1": "ba468d0a1e2495750e5e10fd622f13b0b4d6045c",
          "md5": "290cc256adbf20ddf8ed0c8ec86b3715"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b25-0.8.7-sources.jar",
          "size": 1467,
          "sha512": "fa1672bc7f48848f8dffeb546add666736095c298946ce1d9e5709fa08eeeb06719b8d648b3bfe09f2cdd98a8a71e6e80372994a577f309758383dd13f479ce5",
          "sha256": "82d4d11a52ba56b1594b1268939df982572c52173ad46bca39e124844902b902",
          "sha1": "9dbd739bbde449fd2cfb7d04a99e6f5782d95751",
          "md5": "83a6537020fcd2244a7d8e88308db3b0"
        }
      ]
    }
  ]
}
