{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6a",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-0.8.12.jar",
          "url": "ble-characteristic-u2a6a-0.8.12.jar",
          "size": 4100,
          "sha512": "996517ec693a748f658708ba29afc80183cfbfc59fceb0384654a89e108b436e5873ab12664731c4200c06f371be22d0950ff9dd1e496245ce8bd7bb47fdecb8",
          "sha256": "bb3a05b6e14447c410db7eb729703023458d27070c443563e7d91fa54b847443",
          "sha1": "e73fcab916a04fb182a4d350bae00178a9af845c",
          "md5": "1d8f9e55b3911dfe2f5d78900e169660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-0.8.12.jar",
          "url": "ble-characteristic-u2a6a-0.8.12.jar",
          "size": 4100,
          "sha512": "996517ec693a748f658708ba29afc80183cfbfc59fceb0384654a89e108b436e5873ab12664731c4200c06f371be22d0950ff9dd1e496245ce8bd7bb47fdecb8",
          "sha256": "bb3a05b6e14447c410db7eb729703023458d27070c443563e7d91fa54b847443",
          "sha1": "e73fcab916a04fb182a4d350bae00178a9af845c",
          "md5": "1d8f9e55b3911dfe2f5d78900e169660"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6a-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a6a-0.8.12-javadoc.jar",
          "size": 118956,
          "sha512": "1881dc231c827ac015ee75477790ad39f03bf7fc2ebfbcf6e9e8a2ccc2f0c70c7441aa94d817196360d4bcda48cbcbcbfe38386388c6b3fb4dd9bc085419961b",
          "sha256": "687420de9446205e8ef66e0c0d6762c81d5412e8dff789365319fefbd8f85001",
          "sha1": "973affa9442cf738075f5eeadc15ad3be7b2f290",
          "md5": "ee83c61dcc5bf5883da10dc774f4cc5d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6a-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a6a-0.8.12-sources.jar",
          "size": 4669,
          "sha512": "f90d9d4c1e44619923c529078d5bb5c796c6f1f973fac211eb881e3e3aa29aaddaaf9b0758103d0e454e68521bb5c6fddc67f8f8f99a24c037f4ce360471a8eb",
          "sha256": "d387e76a0cb799b79e92cd2861c05c411bcddf5c4311ffd98377e2f572d19d94",
          "sha1": "aa799d15b1a38f844bbc02de73941a0bc0fe5080",
          "md5": "f94f7668be1cf7322a9b398c15cbfaf0"
        }
      ]
    }
  ]
}
