{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd2-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd2",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd2-android-0.8.9.aar",
          "url": "ble-characteristic-u2bd2-android-0.8.9.aar",
          "size": 3272,
          "sha512": "3b9109a4c4cdae6a6c84129669da511c4a4bdd9f56c6db761eb64cecd8ff812c97b6ce637f97a4c63fbe27ab9414ebfe7ffe937c121f0269d591d22be9d2ec23",
          "sha256": "37492af4168ea0d9739edca7b47a9063277eb1c3cddbea2fe579839d7aad0bd6",
          "sha1": "cdfa0aedd314017e860febc87aebc4b8a330138c",
          "md5": "8fc80c7e7f6212c040a93ffedf782338"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd2",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd2-android-0.8.9.aar",
          "url": "ble-characteristic-u2bd2-android-0.8.9.aar",
          "size": 3272,
          "sha512": "3b9109a4c4cdae6a6c84129669da511c4a4bdd9f56c6db761eb64cecd8ff812c97b6ce637f97a4c63fbe27ab9414ebfe7ffe937c121f0269d591d22be9d2ec23",
          "sha256": "37492af4168ea0d9739edca7b47a9063277eb1c3cddbea2fe579839d7aad0bd6",
          "sha1": "cdfa0aedd314017e860febc87aebc4b8a330138c",
          "md5": "8fc80c7e7f6212c040a93ffedf782338"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd2-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2bd2-android-0.8.9-sources.jar",
          "size": 2256,
          "sha512": "14ee34f2611970a6878aa192d03f3cca97d7eee02ad25b3e8c4c29c956b0b05e1cdfc5c45fbfc9131d8605beeb2c5a6aec329e2399d2061b1fa93024ed1f572b",
          "sha256": "f0b10cf7f5f8280fe43df4c44f4df13ed73532cddc26745dc34ca5b3cefb2002",
          "sha1": "83c7f27e3333f4d679b961d6c98de48a1db1e299",
          "md5": "73438623136e329b89e57599d9dd0d92"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd2-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2bd2-android-0.8.9-javadoc.jar",
          "size": 272530,
          "sha512": "4a634768d70f5a72adee95265dc47ad49a551d5564d19e7adbd82a0cb3b85efd5c79407c7f68877249608144586fd26051e1d009d6ff4bc4c7181a79ccf85127",
          "sha256": "22a5be587de34b200990bf8d084413d221d8a1855130ccd96e4caafeebdf2325",
          "sha1": "96ba2ef814a7df4e062e669567f351ba092ecf70",
          "md5": "782b4acfde239701e1392be9884a82cf"
        }
      ]
    }
  ]
}
