{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afa-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afa",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afa-android-0.8.10.aar",
          "url": "ble-characteristic-u2afa-android-0.8.10.aar",
          "size": 3215,
          "sha512": "0695f541d69b4365bee6cf65d1a5e1a977311c2e8516f15e4aca5d97fe2f7122e7ca3af4bd27f783f95d393b219337a3eb94a4a10a2d3e73b75278ad27963aa0",
          "sha256": "f6f9ab07d655f48bd6468a971aeb9da07108cf91506c71a7f7e7c73b03f45651",
          "sha1": "f459f0610e868ddb81c59c03a7accd146d0a591b",
          "md5": "10e0d8a86827e3a3ab5f9ae7db7f7db2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afa",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afa-android-0.8.10.aar",
          "url": "ble-characteristic-u2afa-android-0.8.10.aar",
          "size": 3215,
          "sha512": "0695f541d69b4365bee6cf65d1a5e1a977311c2e8516f15e4aca5d97fe2f7122e7ca3af4bd27f783f95d393b219337a3eb94a4a10a2d3e73b75278ad27963aa0",
          "sha256": "f6f9ab07d655f48bd6468a971aeb9da07108cf91506c71a7f7e7c73b03f45651",
          "sha1": "f459f0610e868ddb81c59c03a7accd146d0a591b",
          "md5": "10e0d8a86827e3a3ab5f9ae7db7f7db2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afa-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2afa-android-0.8.10-sources.jar",
          "size": 2204,
          "sha512": "402bd5a2427f46bc4d462108f6181dacdc6499e30b1ab17390efa279f839515909b83e0366d05d7a91aa874e3e73292e8714fcd6fa4483977180ef3fa839cb19",
          "sha256": "36992813c125396472ac7d2f18eb01a5b2a25c4dee4ed333e2cf12e4059222b6",
          "sha1": "315a58b91352ac492de33b3a9074ba277c2d03e4",
          "md5": "6db19d7569552ac10f4f371d869a669f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afa-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2afa-android-0.8.10-javadoc.jar",
          "size": 270736,
          "sha512": "29ad4a573172ab72ea1bce387def42bd57afa9c2fbed0a735c1e0de4cdbe903a29334a44b8d418bce01c4d9dbef05d13c683b19f28678b3bf6aac8a2ff886f2d",
          "sha256": "e01284a49c0ead1bdefbab16637c339cad006b5be600e8fb229a9bcb97943357",
          "sha1": "b85d43056a29f66d71878a65194bc1398ba3e858",
          "md5": "4736a20968a52f16a18111eaf32bbcb0"
        }
      ]
    }
  ]
}
