{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b04-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b04",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b04-android-0.8.8.aar",
          "url": "ble-characteristic-u2b04-android-0.8.8.aar",
          "size": 3174,
          "sha512": "a3dfdca0d28df03590ed0b35e7e5097749c6cb4d742bbed0dabfde030ebdbc1a75d801b767787444579803b07478d5685c26287ccda1279c4034a3ca66d2a876",
          "sha256": "a734b46209ae130c71d6884f02fbcdd5c8579eb9a1fe28726ebf4a764c39fd03",
          "sha1": "7e7f2c0ff3f2253155991bb6bc0df61457594d80",
          "md5": "934c70eca83506b8469ce1482925a284"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b04",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b04-android-0.8.8.aar",
          "url": "ble-characteristic-u2b04-android-0.8.8.aar",
          "size": 3174,
          "sha512": "a3dfdca0d28df03590ed0b35e7e5097749c6cb4d742bbed0dabfde030ebdbc1a75d801b767787444579803b07478d5685c26287ccda1279c4034a3ca66d2a876",
          "sha256": "a734b46209ae130c71d6884f02fbcdd5c8579eb9a1fe28726ebf4a764c39fd03",
          "sha1": "7e7f2c0ff3f2253155991bb6bc0df61457594d80",
          "md5": "934c70eca83506b8469ce1482925a284"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b04-android-0.8.8-sources.jar",
          "url": "ble-characteristic-u2b04-android-0.8.8-sources.jar",
          "size": 2156,
          "sha512": "84f14e8c5a8ed655e53c2311ba23525755d6417a796f1064ac52876fc42ddfad0cedfeb4c3caed7921218b89174ed63825dbde48d0a9e8038d5094ffa4c84ab0",
          "sha256": "744288a681a237cf8860e4aa96815573a1ac73a20e73fdae78a760da4e6362e7",
          "sha1": "aafd649e2c64ce292de814d3a35e4fbe59e43649",
          "md5": "279d517f14d6705d33b74ee48a1b5b46"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b04-android-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2b04-android-0.8.8-javadoc.jar",
          "size": 270608,
          "sha512": "d587c82fc52c43af293837681c533b29c07b20109485d73cb3931159480b4e25cca72bcac9ca1c1bba9ffb3cf6dbbcc23d89566456f2cf1256915c9889f20d05",
          "sha256": "4e2bdf09b9f04b96384538369be07f12818eedf434cf4338f636a9e9c3159049",
          "sha1": "599e528d95321b40a244cb687602484d1a040bc2",
          "md5": "dff5ecd1fd6c05ad16b3019401fd8013"
        }
      ]
    }
  ]
}
