{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a65-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.6.aar",
          "url": "ble-characteristic-u2a65-android-0.1.6.aar",
          "size": 3062,
          "sha512": "e5fb8f8d7e16fb33c37887e8326cdcf820c4ca93444201e70b452c98c938cd832446adcb8c1e505eff0a34aeb35b1edd75a4023609c0ca46ef18021bddfc9610",
          "sha256": "f13fbf198faa17fd53ec309bf9a165633582e759e15aa5ea02e5febee02b900c",
          "sha1": "efbd83b2d755c3fc15c42a0ebe3c49c6d101e1e7",
          "md5": "bf35a105087adc74f1cd17b12af6403a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.6.aar",
          "url": "ble-characteristic-u2a65-android-0.1.6.aar",
          "size": 3062,
          "sha512": "e5fb8f8d7e16fb33c37887e8326cdcf820c4ca93444201e70b452c98c938cd832446adcb8c1e505eff0a34aeb35b1edd75a4023609c0ca46ef18021bddfc9610",
          "sha256": "f13fbf198faa17fd53ec309bf9a165633582e759e15aa5ea02e5febee02b900c",
          "sha1": "efbd83b2d755c3fc15c42a0ebe3c49c6d101e1e7",
          "md5": "bf35a105087adc74f1cd17b12af6403a"
        }
      ]
    }
  ]
}
