{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-rtus-peripheral-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-peripheral-android-0.1.2.aar",
          "url": "ble-service-rtus-peripheral-android-0.1.2.aar",
          "size": 3971,
          "sha512": "8b5c28913d0c2aa9e472cadb780e81f12c91443153a3ef2d54e7f9ab0941317ed7a992c67497904011ebaf1940a5242296e2988bb8a2ae659ebfe5be1a5e5217",
          "sha256": "9f3d0ac4402e4ce9856e98d9b3139a291f64926ccbbbb7a26d2a1d00ea849057",
          "sha1": "c30e1dcb3b65dd70de64b4720a279947189178e1",
          "md5": "c7d045bfc6542f01cc3ef92af2a60ad2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-peripheral-android-0.1.2.aar",
          "url": "ble-service-rtus-peripheral-android-0.1.2.aar",
          "size": 3971,
          "sha512": "8b5c28913d0c2aa9e472cadb780e81f12c91443153a3ef2d54e7f9ab0941317ed7a992c67497904011ebaf1940a5242296e2988bb8a2ae659ebfe5be1a5e5217",
          "sha256": "9f3d0ac4402e4ce9856e98d9b3139a291f64926ccbbbb7a26d2a1d00ea849057",
          "sha1": "c30e1dcb3b65dd70de64b4720a279947189178e1",
          "md5": "c7d045bfc6542f01cc3ef92af2a60ad2"
        }
      ]
    }
  ]
}
