{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8b-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fxrmxjl6szatjaovsgygwi5l4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.2.4.aar",
          "url": "ble-characteristic-u2a8b-android-0.2.4.aar",
          "size": 3206,
          "sha512": "217ad48b6bfa10a0f312869c77c82a7c61c150e79bbf902d8685eda527dcd502823c249cb52ed1d6f15df7d83b622ef13d59fedf04ea44abd6780bd56b618eba",
          "sha256": "36fae65d8337ce15d35e1784f1a6e6db0e37df0e7aad1ea6135c10c3f785133d",
          "sha1": "121d96e01db9cb4fa025445669ee04ccbc6ce920",
          "md5": "8969a76cee5835590463cb5ec2992be4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.2.4.aar",
          "url": "ble-characteristic-u2a8b-android-0.2.4.aar",
          "size": 3206,
          "sha512": "217ad48b6bfa10a0f312869c77c82a7c61c150e79bbf902d8685eda527dcd502823c249cb52ed1d6f15df7d83b622ef13d59fedf04ea44abd6780bd56b618eba",
          "sha256": "36fae65d8337ce15d35e1784f1a6e6db0e37df0e7aad1ea6135c10c3f785133d",
          "sha1": "121d96e01db9cb4fa025445669ee04ccbc6ce920",
          "md5": "8969a76cee5835590463cb5ec2992be4"
        }
      ]
    }
  ]
}
