{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a53",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.12.jar",
          "url": "ble-characteristic-u2a53-0.8.12.jar",
          "size": 2951,
          "sha512": "17399abb9a2d7c4b0eac1e3ad6d9ed6c1128099d5c0a1af2cfa06c1f6e69dfc3eeac262268563e8ca03915049147174751233fba0f455e69cb7d6eb84924fdbb",
          "sha256": "bcc16115c81517cfe5032f326dbc4c12cdf19b3e0b0407f78658f861ffe13107",
          "sha1": "71feaf784023fb437b8d160d7aa6ad1b7d2f519d",
          "md5": "c2ca97f452a7da302ccf296cda45f421"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.12.jar",
          "url": "ble-characteristic-u2a53-0.8.12.jar",
          "size": 2951,
          "sha512": "17399abb9a2d7c4b0eac1e3ad6d9ed6c1128099d5c0a1af2cfa06c1f6e69dfc3eeac262268563e8ca03915049147174751233fba0f455e69cb7d6eb84924fdbb",
          "sha256": "bcc16115c81517cfe5032f326dbc4c12cdf19b3e0b0407f78658f861ffe13107",
          "sha1": "71feaf784023fb437b8d160d7aa6ad1b7d2f519d",
          "md5": "c2ca97f452a7da302ccf296cda45f421"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a53-0.8.12-javadoc.jar",
          "size": 111863,
          "sha512": "1303ec64d701106982129bcc1d8e0252ecddf7096509098bbcab92488c00a3ce3326467f4eb0b7436a7073fc47d81e5202a376265423549d45ac0a85b26ac5c1",
          "sha256": "7dc39570744423a81646d616421fc69730751a05a479cdb7cc26bb68e2a05dd6",
          "sha1": "2a8074fe126e44c5b847895e633dea4acef2b140",
          "md5": "1ed1a882a66474b8cf4d4fcb7d585191"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a53-0.8.12-sources.jar",
          "size": 2728,
          "sha512": "5a8dfb43598a87146454eb662b386afbe5d14169988b3d99158fb3f8e657650a06c55ef6e0764253b3680cae04f58badb78d94308f1d2c88f60705958ca8fdc0",
          "sha256": "8416221340756124cd297588ed1b577842685180a55642adcd88bc4389cd227d",
          "sha1": "de3439c4838ec651d33827357034bed90ee11cf6",
          "md5": "4fdd4b1542db8259e080c8f32fdcc061"
        }
      ]
    }
  ]
}
