{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ans-peripheral-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "swq2gxvgereszma3nz5hc5y3xq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-peripheral-android-0.1.0.aar",
          "url": "ble-service-ans-peripheral-android-0.1.0.aar",
          "size": 21598,
          "sha512": "ffffe929d9df8c0d2030147b5ce776421570476d89c2ed398e8e0aff429267c838bfa133faee771c2f4657d5faa472eb4aca9076bce847d365ae1c06e9c4969a",
          "sha256": "9a9165e9ff1a809d2ba893cd6fd08966c36b4a7ec3051acd70e3f29fc1571e26",
          "sha1": "1d63c4a722346af9563546b675d4cbab0530dde7",
          "md5": "33f0a344f4668a0b0b45b49f36cdf919"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-peripheral-android-0.1.0.aar",
          "url": "ble-service-ans-peripheral-android-0.1.0.aar",
          "size": 21598,
          "sha512": "ffffe929d9df8c0d2030147b5ce776421570476d89c2ed398e8e0aff429267c838bfa133faee771c2f4657d5faa472eb4aca9076bce847d365ae1c06e9c4969a",
          "sha256": "9a9165e9ff1a809d2ba893cd6fd08966c36b4a7ec3051acd70e3f29fc1571e26",
          "sha1": "1d63c4a722346af9563546b675d4cbab0530dde7",
          "md5": "33f0a344f4668a0b0b45b49f36cdf919"
        }
      ]
    }
  ]
}
