{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b37",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b37-0.8.6.jar",
          "url": "ble-characteristic-u2b37-0.8.6.jar",
          "size": 2721,
          "sha512": "8aad3befac8ecb0e38e4d776111c60bd79e74c47c44bbe7d19f8a4cb7874261831b08098727dcc3fb2024160ada74b0ed13083462f71f05437c19b0731298048",
          "sha256": "45b1c2678bbefca0bd72fe4b0e66fb3feccb34aa3c7134854c1736b65241810b",
          "sha1": "2a8329a4706f8e82068639eeb0b051adf74983ba",
          "md5": "56bf96df017b0d65586ba53eec759006"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b37-0.8.6.jar",
          "url": "ble-characteristic-u2b37-0.8.6.jar",
          "size": 2721,
          "sha512": "8aad3befac8ecb0e38e4d776111c60bd79e74c47c44bbe7d19f8a4cb7874261831b08098727dcc3fb2024160ada74b0ed13083462f71f05437c19b0731298048",
          "sha256": "45b1c2678bbefca0bd72fe4b0e66fb3feccb34aa3c7134854c1736b65241810b",
          "sha1": "2a8329a4706f8e82068639eeb0b051adf74983ba",
          "md5": "56bf96df017b0d65586ba53eec759006"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b37-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2b37-0.8.6-javadoc.jar",
          "size": 111578,
          "sha512": "63075942690b92b92210008ff5e130e76220c48cfeddbf6754b2ac8ac80a85a45d9ee7b90586f48de5d0e8008c4aa45b39bffdfe92bc948a9743bba9f27be63c",
          "sha256": "38521060de5bb8244359317349244df5f5bb795f6130002a903eb860930044fa",
          "sha1": "6336fe3427453f752610b8cf2f00e2dd12c3bd23",
          "md5": "7ddc6a299e8dfdb88e5dd8f8cd6f1693"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b37-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b37-0.8.6-sources.jar",
          "size": 2618,
          "sha512": "df3b4028f351e0b7f02f6db4b0107740a4febe017caa336566139adeb523d31823844f099526773645644827e509d45b4a61dd7e0e3fd17b3b25f5469c01f30e",
          "sha256": "b52433bd7b58f25d87a9fce3b20575b5baa06c545634a75fe677ef1951b8c3ef",
          "sha1": "97263c4a0836607198402b7d961b10fa6259a6b3",
          "md5": "6ebaa6b66a6f3c82e497bf2a084a3fb8"
        }
      ]
    }
  ]
}
