{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8a",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.5.jar",
          "url": "ble-characteristic-u2a8a-0.8.5.jar",
          "size": 2288,
          "sha512": "bae11380e1db670ded4614c5ce3ba52518a109c61649da586380724807e4202541466c99da4350181716163ffd10053def57ef197961463419c977a5af33427b",
          "sha256": "03ae37b13729309c3af9bb6e74683a2fa650f32dba047d99d0acd36e701e0a66",
          "sha1": "855f46f66a66e77125a435550858dc11154bafd2",
          "md5": "3090cde96dcbfb1542cb4728d54f676a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.5.jar",
          "url": "ble-characteristic-u2a8a-0.8.5.jar",
          "size": 2288,
          "sha512": "bae11380e1db670ded4614c5ce3ba52518a109c61649da586380724807e4202541466c99da4350181716163ffd10053def57ef197961463419c977a5af33427b",
          "sha256": "03ae37b13729309c3af9bb6e74683a2fa650f32dba047d99d0acd36e701e0a66",
          "sha1": "855f46f66a66e77125a435550858dc11154bafd2",
          "md5": "3090cde96dcbfb1542cb4728d54f676a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a8a-0.8.5-javadoc.jar",
          "size": 107338,
          "sha512": "548ce3f2c192cfb7af00864fa1f048e29b04b25e4dd52cdbf004c8d08df2672db288c7cd3c71e25d14f103e29d1e77dbf5d84a2a6befe0788b301b1ec06ca266",
          "sha256": "c8a2cc563e1380c2b7fd5367c8013e5f4c625572384fae81af14c4b11fac897f",
          "sha1": "3ef10a872b5d19a5b43ee943d211b95bfd50640d",
          "md5": "116c2d968c7d4323207f2efd84f8aa8d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a8a-0.8.5-sources.jar",
          "size": 1781,
          "sha512": "7c5dc74ea493ccd7bdbf8320a4e86da4e3e0c076b21856ae70267db25db957ddde3b8ec82c1548bba2f0a206fa90a1e03098e41b6afa7483258f0a1398823646",
          "sha256": "74165ea752cf09988a813a743f23f76bf9b47b8c85090e73d5ef1131ce5c9181",
          "sha1": "08979cffd713f2b578e84df26f756a0d1076659d",
          "md5": "b08c93590b6be15085062b760a85725c"
        }
      ]
    }
  ]
}
