{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a48-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.0.aar",
          "url": "ble-characteristic-u2a48-android-0.2.0.aar",
          "size": 3015,
          "sha512": "49074e8a3486fbc16caeb5517031adcb3e0d85764359e84a2fc1ab2253e4ed22911d1f093678d086dfc4e13637d2c1a33d09d642cc6b9fd3843d38afad2dbf51",
          "sha256": "c17d9cac21240a93331645198a6d9aaa2affed577b16172a55043cf8c2230dcf",
          "sha1": "cf751a23734dd12dc876f0060357a79a089c70cb",
          "md5": "81a0d9223cf91e192d657fd752740297"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.0.aar",
          "url": "ble-characteristic-u2a48-android-0.2.0.aar",
          "size": 3015,
          "sha512": "49074e8a3486fbc16caeb5517031adcb3e0d85764359e84a2fc1ab2253e4ed22911d1f093678d086dfc4e13637d2c1a33d09d642cc6b9fd3843d38afad2dbf51",
          "sha256": "c17d9cac21240a93331645198a6d9aaa2affed577b16172a55043cf8c2230dcf",
          "sha1": "cf751a23734dd12dc876f0060357a79a089c70cb",
          "md5": "81a0d9223cf91e192d657fd752740297"
        }
      ]
    }
  ]
}
