{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad9-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad9-android-0.2.4.aar",
          "url": "ble-characteristic-u2ad9-android-0.2.4.aar",
          "size": 3220,
          "sha512": "584faab09eb8c4f8c6c3ec437c0875958bbb49b7553a6175a4d84a525c221832f65bcc07692b6740dc90e45c3a062be71d2917732e4abefd6ea3c99410efbd0b",
          "sha256": "619aaddfaa933566da5f7ec0003271e3bbb8a64a5205af93c9e3323280830f9a",
          "sha1": "b4e829dbfff3628e34f883b8849da75978386787",
          "md5": "b5428e3ba0aa2b1f73475cb5794380ab"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad9-android-0.2.4.aar",
          "url": "ble-characteristic-u2ad9-android-0.2.4.aar",
          "size": 3220,
          "sha512": "584faab09eb8c4f8c6c3ec437c0875958bbb49b7553a6175a4d84a525c221832f65bcc07692b6740dc90e45c3a062be71d2917732e4abefd6ea3c99410efbd0b",
          "sha256": "619aaddfaa933566da5f7ec0003271e3bbb8a64a5205af93c9e3323280830f9a",
          "sha1": "b4e829dbfff3628e34f883b8849da75978386787",
          "md5": "b5428e3ba0aa2b1f73475cb5794380ab"
        }
      ]
    }
  ]
}
