{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bcb",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bcb-0.8.12.jar",
          "url": "ble-characteristic-u2bcb-0.8.12.jar",
          "size": 1437,
          "sha512": "a937e944361f6150ce527d166f1ddec00e03c2a86cc5fab2c7db19823421d6194c622a79180febc353655d0f2e9da6504513b738207e4887048eb8b3344e5c67",
          "sha256": "ea7ecb6324d0d8913879a749d31c16d2b5c69d902a77aa9a7657f6819bc9e40e",
          "sha1": "94d04a843680f284447c40b9eb729226d2c31e29",
          "md5": "8de6ab0a39854a24ef5073eaaefee524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bcb-0.8.12.jar",
          "url": "ble-characteristic-u2bcb-0.8.12.jar",
          "size": 1437,
          "sha512": "a937e944361f6150ce527d166f1ddec00e03c2a86cc5fab2c7db19823421d6194c622a79180febc353655d0f2e9da6504513b738207e4887048eb8b3344e5c67",
          "sha256": "ea7ecb6324d0d8913879a749d31c16d2b5c69d902a77aa9a7657f6819bc9e40e",
          "sha1": "94d04a843680f284447c40b9eb729226d2c31e29",
          "md5": "8de6ab0a39854a24ef5073eaaefee524"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bcb-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2bcb-0.8.12-javadoc.jar",
          "size": 107106,
          "sha512": "17ea3f3bf9b7a854f150e03f690460e96f9f21218cfd42a671832be885647abe3e4bb73afed71997ac4b9550cf6d337c4ee77dba91b2367ca0cc49564bc01f6a",
          "sha256": "41c3cc560d8d6f9f0d5c83bff5ca154fa5dab8f410b07f403cbd70d037fc3152",
          "sha1": "8c8d8b9947e32e6c74d378aadef04d5a20d8a892",
          "md5": "85858f47aece804d4e5502021354d32b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bcb-0.8.12-sources.jar",
          "url": "ble-characteristic-u2bcb-0.8.12-sources.jar",
          "size": 1416,
          "sha512": "37466535be9a58927ee5ba7e5324540bc44aa21afb506c0a5f7c8ab789f314a0016af8aeb5bdd1b8a704650a054c25d61e09ab3488a31117ead138adf7ee7d13",
          "sha256": "e84c6e1f1607388f3ac653b6c6f11ec04182d63330f40411687e667660482793",
          "sha1": "d49953269b7117b3d7d7e9229e56aaf3efeb83c7",
          "md5": "69c345ff27c11b396c1772b27180729b"
        }
      ]
    }
  ]
}
