{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad1-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad1-android-0.2.3.aar",
          "url": "ble-characteristic-u2ad1-android-0.2.3.aar",
          "size": 5292,
          "sha512": "a4872e19192396f4974835ae06de7be0586a00fbb772ef52d8bf7998073eb4dd2bb6180c6faaeb6ce150faf71c0198b566f08855ff93ba73ae78e4c733aebcf7",
          "sha256": "178ac2891c30475f331616829b05e55ce760667e2d72d10206825546fb865107",
          "sha1": "cb9f6659e1d29e1fe05f9d2b83c3f14cac6712b1",
          "md5": "b141a8a29f0b21e74b88ab017a9b16db"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad1-android-0.2.3.aar",
          "url": "ble-characteristic-u2ad1-android-0.2.3.aar",
          "size": 5292,
          "sha512": "a4872e19192396f4974835ae06de7be0586a00fbb772ef52d8bf7998073eb4dd2bb6180c6faaeb6ce150faf71c0198b566f08855ff93ba73ae78e4c733aebcf7",
          "sha256": "178ac2891c30475f331616829b05e55ce760667e2d72d10206825546fb865107",
          "sha1": "cb9f6659e1d29e1fe05f9d2b83c3f14cac6712b1",
          "md5": "b141a8a29f0b21e74b88ab017a9b16db"
        }
      ]
    }
  ]
}
