{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af2-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af2",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af2-android-0.4.4.aar",
          "url": "ble-characteristic-u2af2-android-0.4.4.aar",
          "size": 3066,
          "sha512": "dc09dc6b5dc89b4dcfd85014db39852772a5cf951b289ebc99127d4913696bb07a89253371c5ed4bc32b6fc99339d5ed7f9c90ddd15d39b06486127815cb1865",
          "sha256": "8871a065d90192f6f9ed21961d79b7bcc939ccbff22f029b35b699a888dd596c",
          "sha1": "dd54f087b7bedc26cccd3bf2e1a10062ff0d815a",
          "md5": "ebe1b0a928644a3a5d447cd16b3f0889"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af2",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af2-android-0.4.4.aar",
          "url": "ble-characteristic-u2af2-android-0.4.4.aar",
          "size": 3066,
          "sha512": "dc09dc6b5dc89b4dcfd85014db39852772a5cf951b289ebc99127d4913696bb07a89253371c5ed4bc32b6fc99339d5ed7f9c90ddd15d39b06486127815cb1865",
          "sha256": "8871a065d90192f6f9ed21961d79b7bcc939ccbff22f029b35b699a888dd596c",
          "sha1": "dd54f087b7bedc26cccd3bf2e1a10062ff0d815a",
          "md5": "ebe1b0a928644a3a5d447cd16b3f0889"
        }
      ]
    }
  ]
}
