{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2906",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2906-0.8.7.jar",
          "url": "ble-descriptor-u2906-0.8.7.jar",
          "size": 2136,
          "sha512": "ed903c27813968d369a091d0d27318409cd45eae2f3dc106a4e7e2cb789742b49239b310d6b8a5ccef83efe9e6c1a4d4a5321ee64dd9a58a735c3baf249d2a49",
          "sha256": "cbe32ba05eb438ae5328454609a3ee2569d712c7a00081f9d420d615275cc7d2",
          "sha1": "60c138157a3ad7c49baf19c78f45bc2694b0e94c",
          "md5": "84d8b922a789f95063535bfb1d1fae57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2906-0.8.7.jar",
          "url": "ble-descriptor-u2906-0.8.7.jar",
          "size": 2136,
          "sha512": "ed903c27813968d369a091d0d27318409cd45eae2f3dc106a4e7e2cb789742b49239b310d6b8a5ccef83efe9e6c1a4d4a5321ee64dd9a58a735c3baf249d2a49",
          "sha256": "cbe32ba05eb438ae5328454609a3ee2569d712c7a00081f9d420d615275cc7d2",
          "sha1": "60c138157a3ad7c49baf19c78f45bc2694b0e94c",
          "md5": "84d8b922a789f95063535bfb1d1fae57"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2906-0.8.7-javadoc.jar",
          "url": "ble-descriptor-u2906-0.8.7-javadoc.jar",
          "size": 108727,
          "sha512": "4aab2f1b799f556d4b9a8176c9a87ac102e1f588cce5c9e9ed77bada79015aacdbd8b30dec782c9bfe2c7c3bfe7dc11a24fb597a011f08a30ea78dfb2687b4f3",
          "sha256": "a8f5f9be50a50d3fd34b30d500e3b22c3a31d543421a12381bfb401b129a640d",
          "sha1": "af8bd2bb4c2a34bad25375ccd9422b8620162281",
          "md5": "06527420d339fec63a69e936b8646b05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2906-0.8.7-sources.jar",
          "url": "ble-descriptor-u2906-0.8.7-sources.jar",
          "size": 2187,
          "sha512": "f014114148a02bfed3a98fcf4b32f0b2a8539ee443f2dd81897dced1850cbd50b62177a20784cb3e0eb95c44f5879a9171e2d9df111c202b62267f530b525f67",
          "sha256": "29f6f06be709ee76bf22b72ea29c4e64c9637751b239653c5caec4adae368133",
          "sha1": "be30473a1d1c41834daf235be2034d0700035a53",
          "md5": "5b011990bee2a354656ca59a21696583"
        }
      ]
    }
  ]
}
