{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac9",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.6.jar",
          "url": "ble-characteristic-u2ac9-0.8.6.jar",
          "size": 1881,
          "sha512": "98ab1cccd952e8fda3df828729f0ea7d12ea42cd6b76ab09da23d1e65390158be8ceb36ca277b742a4c7019247c073604fea00d86701e4599d7756d90172f24d",
          "sha256": "437dbcd9ef33a6e5bf9e8b3980c4ba6f78f2dc5feca7c53020fd807e88c18fee",
          "sha1": "7772c08aeb63b189abb6cc949eac9b207063a03a",
          "md5": "dfa583a275cdf93325b801e9d9d55709"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.6.jar",
          "url": "ble-characteristic-u2ac9-0.8.6.jar",
          "size": 1881,
          "sha512": "98ab1cccd952e8fda3df828729f0ea7d12ea42cd6b76ab09da23d1e65390158be8ceb36ca277b742a4c7019247c073604fea00d86701e4599d7756d90172f24d",
          "sha256": "437dbcd9ef33a6e5bf9e8b3980c4ba6f78f2dc5feca7c53020fd807e88c18fee",
          "sha1": "7772c08aeb63b189abb6cc949eac9b207063a03a",
          "md5": "dfa583a275cdf93325b801e9d9d55709"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2ac9-0.8.6-javadoc.jar",
          "size": 109585,
          "sha512": "052871acd0b7afa1fe635b2eeaf016f6a37632805867ed7e781df6f14c9fac54f7144b9182944c8b02b963a9d78a7fff516875a30d5befa423cca19e6dcf28ac",
          "sha256": "8d55681a64f1d94b3d8e41d8f231da72a8ecfc92120a4b717bf1b8d502cb403b",
          "sha1": "56717cbd12147acf46ea510b1a6407549747af4f",
          "md5": "348530214fa8b8de02ba171f4336ab59"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ac9-0.8.6-sources.jar",
          "size": 1741,
          "sha512": "a59e6bdbda723733b3724e710a894c505e404d1d00797e8ffd1c95b92e6a8cccc246f4f4cd21efd35d2c677c455a4a8c7c798ff7f385eb0c6d61ce2c63291885",
          "sha256": "82d59f9e1df06377c7d6d17ff2853fd428308cd71ab63ffe20fc05de0c528a8c",
          "sha1": "ee2ebf522eb00d3e61034de2fa7bb6c269d9a112",
          "md5": "8baf6ae5922fd8c62f83b1d55083eab6"
        }
      ]
    }
  ]
}
