{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a96",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jy7ixesazfhqnmjb55547uywfu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a96-0.1.0.jar",
          "url": "ble-characteristic-u2a96-0.1.0.jar",
          "size": 1662,
          "sha512": "24f1fffa7a46a6ad90661a35ee57c63b8b259f8fe3470e194b11a7eaad1e18f3bb2787f4607b306674517e6b300cb2716b38d402722b5f299c6182243b6cf368",
          "sha256": "cfcd3d5c7b47b7da2f34374816492f35c033be570931ae9c1a051772236717c7",
          "sha1": "fc468b9ab7054045e13ce2185219aacbbfbe0e5d",
          "md5": "5229821392e7298a6f06c9ef3930d0cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a96-0.1.0.jar",
          "url": "ble-characteristic-u2a96-0.1.0.jar",
          "size": 1662,
          "sha512": "24f1fffa7a46a6ad90661a35ee57c63b8b259f8fe3470e194b11a7eaad1e18f3bb2787f4607b306674517e6b300cb2716b38d402722b5f299c6182243b6cf368",
          "sha256": "cfcd3d5c7b47b7da2f34374816492f35c033be570931ae9c1a051772236717c7",
          "sha1": "fc468b9ab7054045e13ce2185219aacbbfbe0e5d",
          "md5": "5229821392e7298a6f06c9ef3930d0cd"
        }
      ]
    }
  ]
}
