{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a90",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.7.jar",
          "url": "ble-characteristic-u2a90-0.8.7.jar",
          "size": 2290,
          "sha512": "01ec9ad8546c9d14024ab43e4ade11f8bf12dd5c3a755ddd55dfabdd9179debccb4238a89a8345467ac3bac8e82d0be673aa0f456e61251820ffd8736aff7445",
          "sha256": "6d48b746408e50a58c89b7fb6270a2030b71570f7f07dd6409df695589e4e8b7",
          "sha1": "d401d9eaa6e4607c141b7c99791f8e63f42704f0",
          "md5": "9cfe8632922d31b4778d4f957d69a8f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.7.jar",
          "url": "ble-characteristic-u2a90-0.8.7.jar",
          "size": 2290,
          "sha512": "01ec9ad8546c9d14024ab43e4ade11f8bf12dd5c3a755ddd55dfabdd9179debccb4238a89a8345467ac3bac8e82d0be673aa0f456e61251820ffd8736aff7445",
          "sha256": "6d48b746408e50a58c89b7fb6270a2030b71570f7f07dd6409df695589e4e8b7",
          "sha1": "d401d9eaa6e4607c141b7c99791f8e63f42704f0",
          "md5": "9cfe8632922d31b4778d4f957d69a8f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a90-0.8.7-javadoc.jar",
          "size": 107340,
          "sha512": "a05837a445758252e9a386f8c03a25b4b7423ba789c2c1fac9b0ec11ca767ddd90bed842d3213965a71e8c163ef564858166968bd85a9daa4104a3dd625599cf",
          "sha256": "1a2462ce2695272fdffc95cc739f68be3611514df3389e52d22eb0b663d54895",
          "sha1": "b4b554d18e26cd502b94fbc75bedd1fd8e5675de",
          "md5": "0ca013861bd730a58c3d488622d30149"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a90-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a90-0.8.7-sources.jar",
          "size": 1778,
          "sha512": "496fa6f407415d8949ce7274e341c844d2065aaa8f16d33ef8116d1fd76e33f8bf165969aa6430e10e9e8ee1f07cc721fa2638950ebfadddb542f24c8b0af6ed",
          "sha256": "8cffcdec9904937e089492d02fd8a48d2003a31eb023f0c735f1426cac0aac38",
          "sha1": "219854372877c6ee51b823c30368da07b347c09b",
          "md5": "f3ce6c4645f04f71156543c58bdd0805"
        }
      ]
    }
  ]
}
