{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-rtus-central-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-central-android-0.1.1.aar",
          "url": "ble-service-rtus-central-android-0.1.1.aar",
          "size": 3729,
          "sha512": "09a9d4a98229184a060b030e66abb804b9d08c79c1e3e35d9c71336edddd3c7540602ca38a27152663fd470777395cc2603f859bf4bf013c81f3dd9f1332bd87",
          "sha256": "590c3e257e1a2700c7c96cd2bbbff803ff324b83d65d3aa107b41d9dac917730",
          "sha1": "db4538ed7cb9ee586077b83000e96fc56860ce7f",
          "md5": "a2255e9061738da4dd34fe932ee6688d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-central-android-0.1.1.aar",
          "url": "ble-service-rtus-central-android-0.1.1.aar",
          "size": 3729,
          "sha512": "09a9d4a98229184a060b030e66abb804b9d08c79c1e3e35d9c71336edddd3c7540602ca38a27152663fd470777395cc2603f859bf4bf013c81f3dd9f1332bd87",
          "sha256": "590c3e257e1a2700c7c96cd2bbbff803ff324b83d65d3aa107b41d9dac917730",
          "sha1": "db4538ed7cb9ee586077b83000e96fc56860ce7f",
          "md5": "a2255e9061738da4dd34fe932ee6688d"
        }
      ]
    }
  ]
}
