{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab8",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "bo2m2bzyvfgbjfmoy4levvs3tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-0.2.1.jar",
          "url": "ble-characteristic-u2ab8-0.2.1.jar",
          "size": 2296,
          "sha512": "abc4b2dd76054545172bf5de39b91a2efb7427a600c862d4700605bdd78de96368e9918f5cd51681b401f4a75cb7d80680885f881d6beb37432e0d626c01fe6a",
          "sha256": "a109e5d8e83f33fae1522b12ce989138746ef9593fba3f3831b6d98364a63ca4",
          "sha1": "ddd9e78353f937fd1f40e6f8ebcddebc87105e7f",
          "md5": "45e4f7a93e17823f0cef3c70a6c25429"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-0.2.1.jar",
          "url": "ble-characteristic-u2ab8-0.2.1.jar",
          "size": 2296,
          "sha512": "abc4b2dd76054545172bf5de39b91a2efb7427a600c862d4700605bdd78de96368e9918f5cd51681b401f4a75cb7d80680885f881d6beb37432e0d626c01fe6a",
          "sha256": "a109e5d8e83f33fae1522b12ce989138746ef9593fba3f3831b6d98364a63ca4",
          "sha1": "ddd9e78353f937fd1f40e6f8ebcddebc87105e7f",
          "md5": "45e4f7a93e17823f0cef3c70a6c25429"
        }
      ]
    }
  ]
}
