{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9e-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.2.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.2.aar",
          "size": 2881,
          "sha512": "dda6967480f0a0f4f75bc44f984ab86152e971d6c4d8bdc89ec2f906d736d5823ec01cc10483be5ed76f7d571b342e886e6eb1427864d2c129a50c601e0debb9",
          "sha256": "d19d5ccb4dfac516b0dcadc0b2c5cf11c30679b14042ac294bddd55fbf05ab15",
          "sha1": "2851342b16d5a82d6b63645a17502cbcf8e4d85b",
          "md5": "4c6e64b564635974a8432fa686ae3fe5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.2.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.2.aar",
          "size": 2881,
          "sha512": "dda6967480f0a0f4f75bc44f984ab86152e971d6c4d8bdc89ec2f906d736d5823ec01cc10483be5ed76f7d571b342e886e6eb1427864d2c129a50c601e0debb9",
          "sha256": "d19d5ccb4dfac516b0dcadc0b2c5cf11c30679b14042ac294bddd55fbf05ab15",
          "sha1": "2851342b16d5a82d6b63645a17502cbcf8e4d85b",
          "md5": "4c6e64b564635974a8432fa686ae3fe5"
        }
      ]
    }
  ]
}
