{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afb",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afb-0.8.12.jar",
          "url": "ble-characteristic-u2afb-0.8.12.jar",
          "size": 1771,
          "sha512": "5fb524a168fa5fe0735ad979ba8008df761b7d03287ad36e4003a791292f82cec4c2fa99e148e96ddd7c40805239cea53a5f377ee28440d9fe6699b36b2ef579",
          "sha256": "73bba8f1b003c727782ca4a08552155c0df643fecda2aa200e0c4093035b5073",
          "sha1": "019011a46fd2e0a8297a80af6465792f570a955d",
          "md5": "2ecf253e739e5513120815e48c5da90b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afb-0.8.12.jar",
          "url": "ble-characteristic-u2afb-0.8.12.jar",
          "size": 1771,
          "sha512": "5fb524a168fa5fe0735ad979ba8008df761b7d03287ad36e4003a791292f82cec4c2fa99e148e96ddd7c40805239cea53a5f377ee28440d9fe6699b36b2ef579",
          "sha256": "73bba8f1b003c727782ca4a08552155c0df643fecda2aa200e0c4093035b5073",
          "sha1": "019011a46fd2e0a8297a80af6465792f570a955d",
          "md5": "2ecf253e739e5513120815e48c5da90b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afb-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2afb-0.8.12-javadoc.jar",
          "size": 107301,
          "sha512": "97e3fcef6233089d41591c0eab75a4028f21743f5e343f4f1eb356d5a24891578ecdf155446a1b4d7de0df8b7b59975f7df9e6106a3e2eccd31d7b38c1d29722",
          "sha256": "cd32faed747420b69198f543afa02738a1a7de59e79a1379c2bf104d36bc284a",
          "sha1": "f63d9f950014811f04a25632d471cce7ea74bf71",
          "md5": "59c5752f97ab32e025d2e56dcdb9a929"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afb-0.8.12-sources.jar",
          "url": "ble-characteristic-u2afb-0.8.12-sources.jar",
          "size": 1608,
          "sha512": "2477a6818751384feefcee8f4f805a97f21c296041e113a1bb3bffafd3bcd20cc5f2a240bbd54c339fe6001c7932bc8ed1380a59050b3a8c70c5b91a983331a2",
          "sha256": "46d749e0b032ba098a8493e4108ea8b6319e7abdf38ce23b91bd165ee625a899",
          "sha1": "6012c5a8428c5c4650b8bcfd31c54f2760575e83",
          "md5": "93ee73d70aa56d22a5aaabaafca2b963"
        }
      ]
    }
  ]
}
