{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8a",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.10.jar",
          "url": "ble-characteristic-u2a8a-0.8.10.jar",
          "size": 2288,
          "sha512": "2a2741acdfc011c341c905184b9ffcb2ecab591f65ca735423d7862031fa55c6293c4e7cdbdae719d35b429bf0bdf4142ec942cf0a7d984361d3d27403e9db24",
          "sha256": "2eeebf8543b92eddf1f094cd803455797365737be89fff8e5385219dd3861c1d",
          "sha1": "30891c550a02402b794af1e8d6a881268326c8ab",
          "md5": "098488aad428c6a97771e89dadd0d980"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.10.jar",
          "url": "ble-characteristic-u2a8a-0.8.10.jar",
          "size": 2288,
          "sha512": "2a2741acdfc011c341c905184b9ffcb2ecab591f65ca735423d7862031fa55c6293c4e7cdbdae719d35b429bf0bdf4142ec942cf0a7d984361d3d27403e9db24",
          "sha256": "2eeebf8543b92eddf1f094cd803455797365737be89fff8e5385219dd3861c1d",
          "sha1": "30891c550a02402b794af1e8d6a881268326c8ab",
          "md5": "098488aad428c6a97771e89dadd0d980"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2a8a-0.8.10-javadoc.jar",
          "size": 107338,
          "sha512": "03f3360421386888480868107d2a37083034466ff63e6444ce501571edb52e963ca84ff46683bfcb817b0dc3f4c18b4c3468ccab86ecca848d6540bb4c172340",
          "sha256": "442aa25534855df58b10d3c41584070053a36d36f137e9942fddcd0c74f516af",
          "sha1": "e809fea2d011a75e96aab752b097d1e3c6d9f1cd",
          "md5": "77f28cdd628bb4c38018b020a63f8467"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8a-0.8.10-sources.jar",
          "url": "ble-characteristic-u2a8a-0.8.10-sources.jar",
          "size": 1781,
          "sha512": "e17075714338c9a53611122d7c21c260be2ad0b300cd74dfd9cc745d7eefc560759302fee6700cb8fdd22508da763f0642220a776524215a90c72da09379fa3b",
          "sha256": "c83a42e2cee52c8c5fc4355613731a18276d0799cb18492c4b5cdb4712ce1e20",
          "sha1": "415d0cd40ef151fc9ddd5d6d2cbf8ed39ff8baee",
          "md5": "0d8ee95cb448ad6f178402f9327f4ac8"
        }
      ]
    }
  ]
}
