{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a35-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a35",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a35-android-0.2.2.aar",
          "url": "ble-characteristic-u2a35-android-0.2.2.aar",
          "size": 3243,
          "sha512": "11e07ac20dbdcba6a535e8bf87d28d77c98989e3c6cac1642c78c2de15f0508340a0703c3b07a66947f70d615bedbf3ac09157735434bbb733b022b0ed97b64c",
          "sha256": "836779572e9ed284599639019498faf51f9ffbfbdc882769b45aa56b0dc0160e",
          "sha1": "f55b4414bb8afecef0b5920cd8806a07a24bc89d",
          "md5": "daebc1cd619e05891655e1038abe7c7f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a35",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a35-android-0.2.2.aar",
          "url": "ble-characteristic-u2a35-android-0.2.2.aar",
          "size": 3243,
          "sha512": "11e07ac20dbdcba6a535e8bf87d28d77c98989e3c6cac1642c78c2de15f0508340a0703c3b07a66947f70d615bedbf3ac09157735434bbb733b022b0ed97b64c",
          "sha256": "836779572e9ed284599639019498faf51f9ffbfbdc882769b45aa56b0dc0160e",
          "sha1": "f55b4414bb8afecef0b5920cd8806a07a24bc89d",
          "md5": "daebc1cd619e05891655e1038abe7c7f"
        }
      ]
    }
  ]
}
