{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a06",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.5.jar",
          "url": "ble-characteristic-u2a06-0.8.5.jar",
          "size": 1889,
          "sha512": "5fef1f882eee90cfd1c196e414e9ca3d6145e6f1d20810555c3c5472b7d55289db72cd2949145fe9f2e2af7a4f32090ac90853cb06a1b67de3c5d3ac61775391",
          "sha256": "b1d6cec594d1db6157639e9cfbade4908ace55228fd5ec4ff6b273b5277e950e",
          "sha1": "bfa5d72c78c80de2c4ac02fc44bd56e2d809c78e",
          "md5": "428df4e338b05bb716e4f7da3637be21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.5.jar",
          "url": "ble-characteristic-u2a06-0.8.5.jar",
          "size": 1889,
          "sha512": "5fef1f882eee90cfd1c196e414e9ca3d6145e6f1d20810555c3c5472b7d55289db72cd2949145fe9f2e2af7a4f32090ac90853cb06a1b67de3c5d3ac61775391",
          "sha256": "b1d6cec594d1db6157639e9cfbade4908ace55228fd5ec4ff6b273b5277e950e",
          "sha1": "bfa5d72c78c80de2c4ac02fc44bd56e2d809c78e",
          "md5": "428df4e338b05bb716e4f7da3637be21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a06-0.8.5-javadoc.jar",
          "size": 109683,
          "sha512": "c3331b37cc54341cbbe14a081a5363c12c6e601775d25c4c65bec560d6d99934a5260c4158dad21d4676cd38827996433711641fe09a466ddf0c42326527650d",
          "sha256": "54babf13db31a4e4e7f7f4c44dd8b8c65d793eae1c96fec6b25dcc9de1d3099d",
          "sha1": "ccdcd37e1748e95e709c31a5e8b1743ec01e386b",
          "md5": "1d2264daee480703c6d7417d84924dc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a06-0.8.5-sources.jar",
          "size": 1733,
          "sha512": "20facbe29be71387b14d9515ad0459382d81a7c9317abdf184ce762f9618d35563c7d79c4a1eed13980fc673aac59a046b4f993039b7f6fc082febef8492df14",
          "sha256": "bb29a866b243a4dd39733937c8bc0e020dc468e3143eaaf6fdaaecd8f6f15400",
          "sha1": "92985a01f1f43ecb16e55a156c3727c26c97425b",
          "md5": "c4c3f330a1146e3ec731fb9567838df2"
        }
      ]
    }
  ]
}
