{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8a-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sipxf3vz2bcx5mgcg6vcjbnlti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8a",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8a-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8a-android-0.2.1.aar",
          "size": 2764,
          "sha512": "29b08f164e884eb480652f3b2937f29230a36e1e23133e87654ba3a5c1c737f9fd7f33d270ef3be61fe7187b7ebd8dff4ea7400ec2ca4cbd70ea9caab60934b8",
          "sha256": "08707622f60aaedb699115dff021e8f8714d907186e1f67025e57279d98a1fdd",
          "sha1": "776db9d3c561a417b50057234f2acaee3abddc50",
          "md5": "10f08483a462d973e0290f451c2afae2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8a",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8a-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8a-android-0.2.1.aar",
          "size": 2764,
          "sha512": "29b08f164e884eb480652f3b2937f29230a36e1e23133e87654ba3a5c1c737f9fd7f33d270ef3be61fe7187b7ebd8dff4ea7400ec2ca4cbd70ea9caab60934b8",
          "sha256": "08707622f60aaedb699115dff021e8f8714d907186e1f67025e57279d98a1fdd",
          "sha1": "776db9d3c561a417b50057234f2acaee3abddc50",
          "md5": "10f08483a462d973e0290f451c2afae2"
        }
      ]
    }
  ]
}
