{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acb-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acb",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acb-android-0.8.12.aar",
          "url": "ble-characteristic-u2acb-android-0.8.12.aar",
          "size": 3141,
          "sha512": "4611629ecddf5cf7913b6a1f9e1e639c728e74454dd9bc2e16d1c535db01b97f321d5c281db3f61f1cdd33ab1fadce3249201c0188024602420d6500bb41bfc9",
          "sha256": "671095f5b0c622b972b8efcac86dec9174812ab0f879879c5bbf4821656b68b8",
          "sha1": "08af10e542cd64881f1a0ab95af2dcebd3e2864d",
          "md5": "eda2067d0872bb6632cc9aa95fc7be8c"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acb",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acb-android-0.8.12.aar",
          "url": "ble-characteristic-u2acb-android-0.8.12.aar",
          "size": 3141,
          "sha512": "4611629ecddf5cf7913b6a1f9e1e639c728e74454dd9bc2e16d1c535db01b97f321d5c281db3f61f1cdd33ab1fadce3249201c0188024602420d6500bb41bfc9",
          "sha256": "671095f5b0c622b972b8efcac86dec9174812ab0f879879c5bbf4821656b68b8",
          "sha1": "08af10e542cd64881f1a0ab95af2dcebd3e2864d",
          "md5": "eda2067d0872bb6632cc9aa95fc7be8c"
        }
      ]
    }
  ]
}
