{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9d-android",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9d",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-android-0.8.5.aar",
          "url": "ble-characteristic-u2b9d-android-0.8.5.aar",
          "size": 3045,
          "sha512": "9ea3ee47a28490082c6dfd2fb227f955f73417e61749469da0de7a37cb5aa9360eb028aa571a57021ce81fbd61448ad8599f2faccff1499e8b33f1761e90c428",
          "sha256": "5f40e4bbe26d68e484e198c771097286d0cb0d61ab015fc904f917fd858826bb",
          "sha1": "89ed7401c99ba5c708804d9b01f181905bb1ccae",
          "md5": "333a57125b25ddd500bd67dad6686f12"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9d",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-android-0.8.5.aar",
          "url": "ble-characteristic-u2b9d-android-0.8.5.aar",
          "size": 3045,
          "sha512": "9ea3ee47a28490082c6dfd2fb227f955f73417e61749469da0de7a37cb5aa9360eb028aa571a57021ce81fbd61448ad8599f2faccff1499e8b33f1761e90c428",
          "sha256": "5f40e4bbe26d68e484e198c771097286d0cb0d61ab015fc904f917fd858826bb",
          "sha1": "89ed7401c99ba5c708804d9b01f181905bb1ccae",
          "md5": "333a57125b25ddd500bd67dad6686f12"
        }
      ]
    }
  ]
}
