{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac9",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.7.jar",
          "url": "ble-characteristic-u2ac9-0.8.7.jar",
          "size": 1881,
          "sha512": "7535d7f1cc754474129613125948101115caddb80ad97963ccea7495ff4d9666c0bc2983881beda0ebbeb9c19af0838e77de37ee6f1c64dca21190ff13edb15d",
          "sha256": "bf172cbcef1b88f5e62e2415242e7fba538c70ed12692758fc744cbd42b204a5",
          "sha1": "001af6d8db705b3f491509143bc240aa4ea3cbf9",
          "md5": "3d1c1a2a9efa5f3b2c253f00d3a7ce44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.7.jar",
          "url": "ble-characteristic-u2ac9-0.8.7.jar",
          "size": 1881,
          "sha512": "7535d7f1cc754474129613125948101115caddb80ad97963ccea7495ff4d9666c0bc2983881beda0ebbeb9c19af0838e77de37ee6f1c64dca21190ff13edb15d",
          "sha256": "bf172cbcef1b88f5e62e2415242e7fba538c70ed12692758fc744cbd42b204a5",
          "sha1": "001af6d8db705b3f491509143bc240aa4ea3cbf9",
          "md5": "3d1c1a2a9efa5f3b2c253f00d3a7ce44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2ac9-0.8.7-javadoc.jar",
          "size": 109585,
          "sha512": "0e173562682603c5c470b2948819b186cc2298158b0f1fddd882f6fece844b5facd4e07dc3c3b95db1e18aeeb0cdfaf22ed5dfd6f1b403905529191120acb6d0",
          "sha256": "4a443759d560663a39c42e1c5244e67bcabb7b9dae3a626ea80759d09238ce4c",
          "sha1": "8798e561037c348781f40bc0f5286f85d23c457b",
          "md5": "0962d51fd82b6e2d9bb09c121791b1ac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ac9-0.8.7-sources.jar",
          "url": "ble-characteristic-u2ac9-0.8.7-sources.jar",
          "size": 1741,
          "sha512": "d523012d0c59fdd9a8717dec4582c3ee9bcd893ac8c5bc69cc77ba6c288947e05519e3b6899f174cb8b510107373311c2808e048d2d612ba5bb502f0a30ac4fe",
          "sha256": "dac8b350ee2c763d452543bec9407c7a1e9b435f085d0879a0f3a7dd1cc2c48a",
          "sha1": "557a5893d1e1b4543ad36438e5b32f52adf8f803",
          "md5": "09397165fc223868b63ee680c50e3a4c"
        }
      ]
    }
  ]
}
