{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acd-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acd-android-0.8.13.aar",
          "url": "ble-characteristic-u2acd-android-0.8.13.aar",
          "size": 5537,
          "sha512": "5a25cd8b715008660de4e6cd00bf695dc9307dfb289a0aaec9d86f53dfa67f34cbb29ddb32fd432104a5a19d7a7bf735bfb6f1269a3d250c31e9473903486d5e",
          "sha256": "4c11aebe4320fd4b5adb2b748b17b45d8d517d117d6becaf789cf2ca1ef06eb2",
          "sha1": "d7f6a739cfeacf3b5863248cd0f9a85bf6def5b2",
          "md5": "2192801fd68f2b5f5284ec94faa1f1f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acd-android-0.8.13.aar",
          "url": "ble-characteristic-u2acd-android-0.8.13.aar",
          "size": 5537,
          "sha512": "5a25cd8b715008660de4e6cd00bf695dc9307dfb289a0aaec9d86f53dfa67f34cbb29ddb32fd432104a5a19d7a7bf735bfb6f1269a3d250c31e9473903486d5e",
          "sha256": "4c11aebe4320fd4b5adb2b748b17b45d8d517d117d6becaf789cf2ca1ef06eb2",
          "sha1": "d7f6a739cfeacf3b5863248cd0f9a85bf6def5b2",
          "md5": "2192801fd68f2b5f5284ec94faa1f1f0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acd-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2acd-android-0.8.13-sources.jar",
          "size": 3871,
          "sha512": "20ad7888cf91dc7174bb7c60e910dc471d5c9db91a10726c6402a5808a571cfce981b00921f113b68a57dad3875deaedd5e107c78b604f56a446900f9a939929",
          "sha256": "4d8d9cb613f90f5ae3a3efa5316606b59d1cbb2dc74d089d659b9b1aab45e967",
          "sha1": "4a0c33ab66a88fd99b79ffacda17492e7493df64",
          "md5": "cec91001620af28ebbec696b281fb4a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acd-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2acd-android-0.8.13-javadoc.jar",
          "size": 276274,
          "sha512": "0de3c2b4dc154ed397a756fc272f785a5c92e83ecc077a43d8b96b9d18f1172f8cdd16f5e0045ec34a5b9e2d6e04c726db1350c488d6a4e03c4cbba0378ef36c",
          "sha256": "9602aaa309449af47499f1dda9faff1e8007454e2931f017f604ce952a214508",
          "sha1": "c936a2f8ba208952780a6f1afe0d13871a657be0",
          "md5": "bb469f58de76a8d174e62d54aece37ce"
        }
      ]
    }
  ]
}
