{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9d",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.6.1.jar",
          "url": "ble-characteristic-u2b9d-0.6.1.jar",
          "size": 1468,
          "sha512": "beb9c23915c8077da68ce7ce9fa4478c15510539c8bdf3d675d8bb0706d987721cff95e081e8fe45e256d094bd4db23c30f442901a3e98bcd0cb960419fab919",
          "sha256": "91ecc36ac96367ed37d164e846bdd7c73b577e9fccacb78373065b0728205029",
          "sha1": "8f9b8ada4f94e73aa3ab9f6f4ef1497df45b952d",
          "md5": "c28961cae4eb1c946ee9308ed90e83c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.6.1.jar",
          "url": "ble-characteristic-u2b9d-0.6.1.jar",
          "size": 1468,
          "sha512": "beb9c23915c8077da68ce7ce9fa4478c15510539c8bdf3d675d8bb0706d987721cff95e081e8fe45e256d094bd4db23c30f442901a3e98bcd0cb960419fab919",
          "sha256": "91ecc36ac96367ed37d164e846bdd7c73b577e9fccacb78373065b0728205029",
          "sha1": "8f9b8ada4f94e73aa3ab9f6f4ef1497df45b952d",
          "md5": "c28961cae4eb1c946ee9308ed90e83c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.6.1-javadoc.jar",
          "url": "ble-characteristic-u2b9d-0.6.1-javadoc.jar",
          "size": 109940,
          "sha512": "fd66a95058222754be4feb341341cc3378981fcd5f121005cb31e37ec4b77328b8f1a52ae8c67643103466457548c6835da0cb09cb2ec63b33cd4e607713fb5c",
          "sha256": "ba5295f11457b6f8601a7320853dd2be5c88b2303a15f40b4d14b20a27ed92ae",
          "sha1": "5e439f5af3eae1968cf1ebe66ccb1bbb9295d26c",
          "md5": "c024edfe717b5e4173df1f6009de49cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.6.1-sources.jar",
          "url": "ble-characteristic-u2b9d-0.6.1-sources.jar",
          "size": 1449,
          "sha512": "6ca9e0f8fe6b365b81a72278c8cf1d1566c5b96fbe37fa6ac736077eae634852f5d521ca11f896f8cfbb698d53231570020c174fd1a57194f451c1c103d1c92b",
          "sha256": "67ed9dbbe8d2fff45d709de41130445d5baf98eb8dbc3ed59f6cf884eb40ffc5",
          "sha1": "329ed8ede076f82f0418b6a8ca30ba02d90e5f40",
          "md5": "aaef12353a49c85d7d30df1dce307b59"
        }
      ]
    }
  ]
}
