{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bca",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bca-0.8.6.jar",
          "url": "ble-characteristic-u2bca-0.8.6.jar",
          "size": 1461,
          "sha512": "67701af6b422dfebcf22012edac27cad1aebaf435f19722abda08cb3dbbcb86ba69c454ddfeae54c8787098ed5dc63f7be1b7fe9de82173723e087fb0a7ffe13",
          "sha256": "35779f6a0c6b3c6d56291fdc2a07a5f07e0f01a891d4b2fb7913661fe0ed6f3a",
          "sha1": "f6c353c0e98851002915cbfd3e0d26fd64b24cc3",
          "md5": "a4bf10aae84384708de59a0d763c3145"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bca-0.8.6.jar",
          "url": "ble-characteristic-u2bca-0.8.6.jar",
          "size": 1461,
          "sha512": "67701af6b422dfebcf22012edac27cad1aebaf435f19722abda08cb3dbbcb86ba69c454ddfeae54c8787098ed5dc63f7be1b7fe9de82173723e087fb0a7ffe13",
          "sha256": "35779f6a0c6b3c6d56291fdc2a07a5f07e0f01a891d4b2fb7913661fe0ed6f3a",
          "sha1": "f6c353c0e98851002915cbfd3e0d26fd64b24cc3",
          "md5": "a4bf10aae84384708de59a0d763c3145"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bca-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2bca-0.8.6-javadoc.jar",
          "size": 107182,
          "sha512": "f24fb276e69c1b68bc3428e48d81fd3d701f76024cb0f934c8ce9238f0548abd677636120bac1e9b40b3fb9bd108b4030d51b298bb104d9a26b1d31f644cca5c",
          "sha256": "e7b064f57e2971b49987eb520ffcc3e80ff09d30d1f157aa8acfb8b7397870d7",
          "sha1": "b1c3ed3c5a55d81eb80640913b8b64c6fa73cf3e",
          "md5": "1ff8686f72d09824f24059635c120c69"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bca-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bca-0.8.6-sources.jar",
          "size": 1440,
          "sha512": "ea70d6bda9c0255ef6ad912976169a8591c2c76af37676fe05fae3bdf98649c4da3045c650f60e1e4a9ef5e5e2a0cf19c3a6271a7ec028e604c8e98f47f308dc",
          "sha256": "dab7cc5bd628ad9d8a463931854f0474049e81b08157f56261bc29ca093c7b3f",
          "sha1": "8696e278f73cf18698a3d852b8219ab8810dc7b2",
          "md5": "26d2ab470cdb3fa9d00c6da83b25658d"
        }
      ]
    }
  ]
}
