{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0c-android",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0c",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-android-0.5.0.aar",
          "url": "ble-characteristic-u2b0c-android-0.5.0.aar",
          "size": 3164,
          "sha512": "fc4b7db56f11acd97f341bb731b0443e84398dd7a12615d37f613634d58b39efb249c2f0ad75abb52ce219277005b971b3ec59b068adaf2dd5cbe5d1a6dad9f1",
          "sha256": "f184208ace4ecb56c14a242f63a3aa60a7bf60529fc0abf87ccde57843121704",
          "sha1": "a35e290c23e3a3872abfce45e5cd3fcfe49b7723",
          "md5": "c8169fd1de912d241c0e2b9139167add"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0c",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-android-0.5.0.aar",
          "url": "ble-characteristic-u2b0c-android-0.5.0.aar",
          "size": 3164,
          "sha512": "fc4b7db56f11acd97f341bb731b0443e84398dd7a12615d37f613634d58b39efb249c2f0ad75abb52ce219277005b971b3ec59b068adaf2dd5cbe5d1a6dad9f1",
          "sha256": "f184208ace4ecb56c14a242f63a3aa60a7bf60529fc0abf87ccde57843121704",
          "sha1": "a35e290c23e3a3872abfce45e5cd3fcfe49b7723",
          "md5": "c8169fd1de912d241c0e2b9139167add"
        }
      ]
    }
  ]
}
