{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290f",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290f-0.8.3.jar",
          "url": "ble-descriptor-u290f-0.8.3.jar",
          "size": 1514,
          "sha512": "a65979c426a303725a0138efd6a7af2cc594495407db05e67f9207ac37bdad152137ce6a2b68107cd501d88800aedb6dcc1f84260a1542759f266019f841c1c4",
          "sha256": "0e46226b958b0adb431d2f84e2a8205bff74afb741a5ce19aae3dada4b7c1c01",
          "sha1": "fd8b73ca65d06380cea372e5736d16038ee4a8c9",
          "md5": "95cec2d72f765fff5884769f4a71fee9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290f-0.8.3.jar",
          "url": "ble-descriptor-u290f-0.8.3.jar",
          "size": 1514,
          "sha512": "a65979c426a303725a0138efd6a7af2cc594495407db05e67f9207ac37bdad152137ce6a2b68107cd501d88800aedb6dcc1f84260a1542759f266019f841c1c4",
          "sha256": "0e46226b958b0adb431d2f84e2a8205bff74afb741a5ce19aae3dada4b7c1c01",
          "sha1": "fd8b73ca65d06380cea372e5736d16038ee4a8c9",
          "md5": "95cec2d72f765fff5884769f4a71fee9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290f-0.8.3-javadoc.jar",
          "url": "ble-descriptor-u290f-0.8.3-javadoc.jar",
          "size": 110022,
          "sha512": "cff44abe4d0fe30b1fbe1fbc08f5d9955bba181f5540250b9125ead3fe05b87436dea32832401829748d7db38a85f2e6a7cb4c07d023860997703252517810ea",
          "sha256": "bfb5503b961c9c504ab7689deadd82b4c76c165903b2c04484df14a25499dcb1",
          "sha1": "846523aa3517e5505af27c1d4f26b12275b9cb73",
          "md5": "269b1d5ccc17211637d5cd15942714a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290f-0.8.3-sources.jar",
          "url": "ble-descriptor-u290f-0.8.3-sources.jar",
          "size": 1480,
          "sha512": "6500890018bb6ea2656f544de7a387b6d4e5daab8ec493b87ad25a1069f227c780a1519eb77e9b9a8d0f596b62701f0795436219c82077d67e7272e3bdcfcebf",
          "sha256": "50e25d1cdaa9dd8ef4f7117ba21241027e55114f7c1b3dc6152364926cbae2eb",
          "sha1": "62a4877d6cbf9249fe222dece9a1f24eb70980ec",
          "md5": "26d160dba27c4dd11775aee807954c89"
        }
      ]
    }
  ]
}
