{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290a-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290a",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290a-android-0.2.6.aar",
          "url": "ble-descriptor-u290a-android-0.2.6.aar",
          "size": 3171,
          "sha512": "97cec6b12da635f06dc4974b9bf2971fc5a0c2c297bc55186d3907b8194d9b35819d934b1ff7606691cd1094b5429fd26fcdff5587e169fe686c1fb2f2215767",
          "sha256": "e78ebab47ebf1a3c65ca5b3b82e29523f1ec0bd501855d32b9610dc96b6add94",
          "sha1": "25714982e37006d7f35d6b35f49b63d9de2c2723",
          "md5": "41797c96080249c9f7a97339311d76b1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290a",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290a-android-0.2.6.aar",
          "url": "ble-descriptor-u290a-android-0.2.6.aar",
          "size": 3171,
          "sha512": "97cec6b12da635f06dc4974b9bf2971fc5a0c2c297bc55186d3907b8194d9b35819d934b1ff7606691cd1094b5429fd26fcdff5587e169fe686c1fb2f2215767",
          "sha256": "e78ebab47ebf1a3c65ca5b3b82e29523f1ec0bd501855d32b9610dc96b6add94",
          "sha1": "25714982e37006d7f35d6b35f49b63d9de2c2723",
          "md5": "41797c96080249c9f7a97339311d76b1"
        }
      ]
    }
  ]
}
