{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bbd",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbd-0.8.4.jar",
          "url": "ble-characteristic-u2bbd-0.8.4.jar",
          "size": 1439,
          "sha512": "dfb9abf7c528e90035ac78a2f87bc39b93b8f10a2f77b459b64fd32bb3a3c0576d430e0eafb7be5eb5820c71ba78ee656be52d89b7cc1bd9619124eefd3e9f87",
          "sha256": "4be546a6fd9be2c382dd888d09d0aca6e6fe86aabd1e8e8ec325c9ccd4173202",
          "sha1": "7a428748f16052391a6ddd718798185171686aec",
          "md5": "7c785324a2927c5a2179307a29b08562"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbd-0.8.4.jar",
          "url": "ble-characteristic-u2bbd-0.8.4.jar",
          "size": 1439,
          "sha512": "dfb9abf7c528e90035ac78a2f87bc39b93b8f10a2f77b459b64fd32bb3a3c0576d430e0eafb7be5eb5820c71ba78ee656be52d89b7cc1bd9619124eefd3e9f87",
          "sha256": "4be546a6fd9be2c382dd888d09d0aca6e6fe86aabd1e8e8ec325c9ccd4173202",
          "sha1": "7a428748f16052391a6ddd718798185171686aec",
          "md5": "7c785324a2927c5a2179307a29b08562"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbd-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2bbd-0.8.4-javadoc.jar",
          "size": 109820,
          "sha512": "6edc2caf3891930207921f39dcb796033b4639230240efa92dd582b9efbaa4af19337983658ca995a7013a5b63e592e9e5d1e4d5cf746e6cbfbdb14c32275f62",
          "sha256": "837d8954850bbdffb1fbfc367c79bae6f96fc8d4512547c852aa459b07b3df22",
          "sha1": "2947d6f087ff92db8eea0c58a9426c3e4acb7120",
          "md5": "0e2d70eb2962a11af38d4db79191f2d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbd-0.8.4-sources.jar",
          "url": "ble-characteristic-u2bbd-0.8.4-sources.jar",
          "size": 1431,
          "sha512": "73356a0c6ce8ae0ca9ac6378d546888b36942b2f10ae7a36cef067c1921649f2f52ea6f4730f24ab81b9a4d5b8643447158853617fff1a27098142d6d3d3841e",
          "sha256": "385372c011106156df30ed5ba0da556e057126fdcfa4192c9716303919d50c59",
          "sha1": "80fd98db680dbc77d56148b3c83822943c4a6473",
          "md5": "e6f3796ffce05930bfbbfcb120aa027e"
        }
      ]
    }
  ]
}
