{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a69-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-android-0.4.5.aar",
          "url": "ble-characteristic-u2a69-android-0.4.5.aar",
          "size": 3062,
          "sha512": "338b03958b62e069d159b3f22ba939a477505bb920f0274a5159e305620e2bb7b5221a476439ef8e8862d68e4c84fab4174446cdbb267f5b63eda35ae32f8eb2",
          "sha256": "bba331ca9cb3d06bc3d76e373054f6a0d085ad2e45189dbfff9a37b8e232af8b",
          "sha1": "299162874d8fbd590582b18dbabeb4896c81d5bf",
          "md5": "72c81c87583c4fbc86e2d474505f0e57"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-android-0.4.5.aar",
          "url": "ble-characteristic-u2a69-android-0.4.5.aar",
          "size": 3062,
          "sha512": "338b03958b62e069d159b3f22ba939a477505bb920f0274a5159e305620e2bb7b5221a476439ef8e8862d68e4c84fab4174446cdbb267f5b63eda35ae32f8eb2",
          "sha256": "bba331ca9cb3d06bc3d76e373054f6a0d085ad2e45189dbfff9a37b8e232af8b",
          "sha1": "299162874d8fbd590582b18dbabeb4896c81d5bf",
          "md5": "72c81c87583c4fbc86e2d474505f0e57"
        }
      ]
    }
  ]
}
