{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b83",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b83-0.8.2.jar",
          "url": "ble-characteristic-u2b83-0.8.2.jar",
          "size": 1475,
          "sha512": "f412c47b26e8ad764a203070a88bf8de5b4af6e898af2622ea1c22ce9d475df9479d574d8934045ef742373f52be1d02d8c6c399d76507e4183d040b68d6a2d5",
          "sha256": "fed17f68808ddf4ab0d7d99576d78729f32075c8803d8ef1246e84be2d406fb6",
          "sha1": "124f64893f46e395e9473626316f3f704607482d",
          "md5": "1529b6e37bd11b9d4ca4e39d66a67bb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b83-0.8.2.jar",
          "url": "ble-characteristic-u2b83-0.8.2.jar",
          "size": 1475,
          "sha512": "f412c47b26e8ad764a203070a88bf8de5b4af6e898af2622ea1c22ce9d475df9479d574d8934045ef742373f52be1d02d8c6c399d76507e4183d040b68d6a2d5",
          "sha256": "fed17f68808ddf4ab0d7d99576d78729f32075c8803d8ef1246e84be2d406fb6",
          "sha1": "124f64893f46e395e9473626316f3f704607482d",
          "md5": "1529b6e37bd11b9d4ca4e39d66a67bb6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b83-0.8.2-javadoc.jar",
          "url": "ble-characteristic-u2b83-0.8.2-javadoc.jar",
          "size": 109929,
          "sha512": "1a182abebc1fc0c2af08cceb98071736bb9113eee445f9c57bc8eeb0f9da549d6e75e80e421a23a138343670746f6c6512a40b580cf10a667ae5b618e5950172",
          "sha256": "a8d6a80483116c1e6083e9627572cafa13ce1939fd13fa434e35a6e491b37aa4",
          "sha1": "dec0dc620a463e8fce9537b78f8251a17d8e9c67",
          "md5": "275c0f46a3563510e5085abcd7e1c48c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b83-0.8.2-sources.jar",
          "url": "ble-characteristic-u2b83-0.8.2-sources.jar",
          "size": 1452,
          "sha512": "569e3d50492b140539df2c1b03c92817f8c03a5c3344f2ab006595ab76a33af2f85dc87207cfa214c1b285b7cec761ee596b41952c30be272ba5117344ef5574",
          "sha256": "944974b367ab695c43e8df6758ccdcfef7b37329e5d64f08993ca31b82004dee",
          "sha1": "f828a306dfa4685dbb7f60b3440db661f474a8fe",
          "md5": "30a4f20219f74ceb89841d5a13e54bd1"
        }
      ]
    }
  ]
}
