{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-android",
    "version": "0.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-central-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-android-0.1.16.aar",
          "url": "ble-service-android-0.1.16.aar",
          "size": 1195,
          "sha512": "68a547718b873011319c8fad4b920ab95306b46f3d4f863289fd74d303cdf63d6a8acc0f0ef8f18210c5a05299400ac4635ea0ab117063cb6ad024bb58d427f3",
          "sha256": "51c5cf1404075ce41f98d66ba243304586a0e15b0c2d022a5234c1027aa5bb0c",
          "sha1": "fe20e592a50c725260c292d4a77117f1338001db",
          "md5": "4921212d5f3d8ca671a79c0ca4f26b9c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-central-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-android-0.1.16.aar",
          "url": "ble-service-android-0.1.16.aar",
          "size": 1195,
          "sha512": "68a547718b873011319c8fad4b920ab95306b46f3d4f863289fd74d303cdf63d6a8acc0f0ef8f18210c5a05299400ac4635ea0ab117063cb6ad024bb58d427f3",
          "sha256": "51c5cf1404075ce41f98d66ba243304586a0e15b0c2d022a5234c1027aa5bb0c",
          "sha1": "fe20e592a50c725260c292d4a77117f1338001db",
          "md5": "4921212d5f3d8ca671a79c0ca4f26b9c"
        }
      ]
    }
  ]
}
