{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bas-peripheral-android",
    "version": "0.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bas-peripheral-android-0.1.15.aar",
          "url": "ble-service-bas-peripheral-android-0.1.15.aar",
          "size": 4939,
          "sha512": "fe55e592af484b7a73cec65292bb6ff92088422146bd08dfaa0a543f954de3b5029833f5610d499d5f1c03f1385f15b79648d078b1e576fde7916cd70eb6cb3d",
          "sha256": "876906209853106a163181063d908c4be46873d03e45cf9bc50120ecb49c18b0",
          "sha1": "114e99cadf286f8a528bdec4b6e255a924fb467c",
          "md5": "18c3e6a2ac17c8808c253080018f6394"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bas-peripheral-android-0.1.15.aar",
          "url": "ble-service-bas-peripheral-android-0.1.15.aar",
          "size": 4939,
          "sha512": "fe55e592af484b7a73cec65292bb6ff92088422146bd08dfaa0a543f954de3b5029833f5610d499d5f1c03f1385f15b79648d078b1e576fde7916cd70eb6cb3d",
          "sha256": "876906209853106a163181063d908c4be46873d03e45cf9bc50120ecb49c18b0",
          "sha1": "114e99cadf286f8a528bdec4b6e255a924fb467c",
          "md5": "18c3e6a2ac17c8808c253080018f6394"
        }
      ]
    }
  ]
}
