{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba7-android",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba7",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-android-0.8.3.aar",
          "url": "ble-characteristic-u2ba7-android-0.8.3.aar",
          "size": 3041,
          "sha512": "e15773a3c5f5e8bcb7c6a76135fddcd88d0c28fce8e93c84ae841df1798b66b3ffe1cbe8eeeeeb4abc66c0b4dc92a343f1ef1254069813cf667a40a250adb31a",
          "sha256": "46ff27c2a2645e8b60f775e560ee6710e3a1c77cd4b37e9cf90605ab136f89e0",
          "sha1": "e72ad5c4927038312f41614d4af96429e54bb471",
          "md5": "a29cdc5660db10dedcc26d045a52c3fe"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba7",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-android-0.8.3.aar",
          "url": "ble-characteristic-u2ba7-android-0.8.3.aar",
          "size": 3041,
          "sha512": "e15773a3c5f5e8bcb7c6a76135fddcd88d0c28fce8e93c84ae841df1798b66b3ffe1cbe8eeeeeb4abc66c0b4dc92a343f1ef1254069813cf667a40a250adb31a",
          "sha256": "46ff27c2a2645e8b60f775e560ee6710e3a1c77cd4b37e9cf90605ab136f89e0",
          "sha1": "e72ad5c4927038312f41614d4af96429e54bb471",
          "md5": "a29cdc5660db10dedcc26d045a52c3fe"
        }
      ]
    }
  ]
}
