{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7e",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.12.jar",
          "url": "ble-characteristic-u2a7e-0.8.12.jar",
          "size": 1762,
          "sha512": "37bb3d81fb5c7e4ac0e34fae7e21fec097460c0f4925b2dbc950d726db265a2da1e1baf581f18acd3e79647ce70a8e44bec6928322a1bd8ee2603bae3bb0a367",
          "sha256": "209bb074501d2f9ded529d51bb3d1bbe6c0f479b4d1ef62b922342e49518cf92",
          "sha1": "8dfac7fb9a982357a1b123c4571ff1553e2da170",
          "md5": "846ff54a2d7bc4ccdbc229f7496cba89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.12.jar",
          "url": "ble-characteristic-u2a7e-0.8.12.jar",
          "size": 1762,
          "sha512": "37bb3d81fb5c7e4ac0e34fae7e21fec097460c0f4925b2dbc950d726db265a2da1e1baf581f18acd3e79647ce70a8e44bec6928322a1bd8ee2603bae3bb0a367",
          "sha256": "209bb074501d2f9ded529d51bb3d1bbe6c0f479b4d1ef62b922342e49518cf92",
          "sha1": "8dfac7fb9a982357a1b123c4571ff1553e2da170",
          "md5": "846ff54a2d7bc4ccdbc229f7496cba89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a7e-0.8.12-javadoc.jar",
          "size": 107489,
          "sha512": "fd21775cc984ed5708add0bce8cc23872aaac25c51aeab3431191d5514c4311b708e44a696d13eddfa58d4b05c0c8858e502f744fcf216104de8da13c88ac837",
          "sha256": "484501793f707b85c25de61ed0456528b832ba7823be2ccb7a241cd7fb60be37",
          "sha1": "efaf6a4b86936f2034e29c224a854cc400d6262e",
          "md5": "48452fce4d56bab16f9291c716ad1c2a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a7e-0.8.12-sources.jar",
          "size": 1632,
          "sha512": "30970e0ebda3476b64f2adcfbe0ce34c1831d74448f5859652c6b595bc0b7b1c177c7f63cee25e2be2437223de377d66c53805cc8fd30a59177a4fdda29840ad",
          "sha256": "ea32822a34331eab8aeaaad7c04dfeba3cfc57071bea5700c1a2320b8a68dc2b",
          "sha1": "54aafc2c95d223d2c44cd03a3a1541ee81906205",
          "md5": "59981d626f6ecce469157e782496439f"
        }
      ]
    }
  ]
}
