{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2baa",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.13.jar",
          "url": "ble-characteristic-u2baa-0.8.13.jar",
          "size": 1477,
          "sha512": "72a705a527b54f67ac39c814a7cd9b832926d05eb33ffdc427ee4d61fd731e13bd60a02f5897bb5a2b3abe1978664bebc3fdd288229ec7da2c4f3a4a8bda56ce",
          "sha256": "f6a37242e305981487d046bea2ab8ab21900bd0ee4898ba2752eeb98a069fbf5",
          "sha1": "6f18d453b4cc4838489f73687edba19bb511eef8",
          "md5": "5ea73dffb3c7d01924bb911971342d79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.13.jar",
          "url": "ble-characteristic-u2baa-0.8.13.jar",
          "size": 1477,
          "sha512": "72a705a527b54f67ac39c814a7cd9b832926d05eb33ffdc427ee4d61fd731e13bd60a02f5897bb5a2b3abe1978664bebc3fdd288229ec7da2c4f3a4a8bda56ce",
          "sha256": "f6a37242e305981487d046bea2ab8ab21900bd0ee4898ba2752eeb98a069fbf5",
          "sha1": "6f18d453b4cc4838489f73687edba19bb511eef8",
          "md5": "5ea73dffb3c7d01924bb911971342d79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2baa-0.8.13-javadoc.jar",
          "size": 86039,
          "sha512": "4ccee70e5eb8e4d8b0b559f5335d423267ed8d8c7bb55f781a3da4f9d594cf49e36dd95461bb772b94040665b79e631712516cd75dc705f859918d62ff457e1c",
          "sha256": "eb044fa2e2c04d8414c389033e1b9bd6943541ab0efe937211dcda8802358ea9",
          "sha1": "9c5350fad710ce204df0f885050296158dabf746",
          "md5": "dc2a6840994b4289a5ae9c5e029d5e51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.13-sources.jar",
          "url": "ble-characteristic-u2baa-0.8.13-sources.jar",
          "size": 1472,
          "sha512": "3af95683d1131e010fd2debfa602f0e8d554a9bda6cddbc8b1ee11a8bb89c8a7fde5be7f7740ecaa3c558a4ee15a6fb9224ca00ccdf7c826da772fd425973f5c",
          "sha256": "443aa6f6bcf354bd23d44a580496219a73d0440e82fcfa759aa94b6e902f15f3",
          "sha1": "28cbcb6a5448c9afd55b81303c60feba98335527",
          "md5": "6b1db69ab24dd9192c3cb24e5c19ec58"
        }
      ]
    }
  ]
}
