{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a69",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-0.8.5.jar",
          "url": "ble-characteristic-u2a69-0.8.5.jar",
          "size": 3793,
          "sha512": "400c1bc7580e7c7645068e9652bfcbaee245e8318a91b84c97215cdd0fafc4375d114979260e98f86666c960bf0ba265794502da52d725b877334151612dfc06",
          "sha256": "f97c8568effb67e3a35dbf5ff4523b522559f536234f0f1ad33707cebb7f1fc5",
          "sha1": "f47479c5ee802227c8d24ab323df46c6f9dcebf6",
          "md5": "a58bd7fd62a8649dd5002b42b5210bfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-0.8.5.jar",
          "url": "ble-characteristic-u2a69-0.8.5.jar",
          "size": 3793,
          "sha512": "400c1bc7580e7c7645068e9652bfcbaee245e8318a91b84c97215cdd0fafc4375d114979260e98f86666c960bf0ba265794502da52d725b877334151612dfc06",
          "sha256": "f97c8568effb67e3a35dbf5ff4523b522559f536234f0f1ad33707cebb7f1fc5",
          "sha1": "f47479c5ee802227c8d24ab323df46c6f9dcebf6",
          "md5": "a58bd7fd62a8649dd5002b42b5210bfb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a69-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a69-0.8.5-javadoc.jar",
          "size": 114529,
          "sha512": "d8fae2340aaa19ae1779b4540662bcbcd6a3670a23bd26b897266f53656ad22d13879c2a8bf882669433c7a81ea781edfa21735184e05ee39102e4411fafce87",
          "sha256": "e24c22b4e9299f9480018e6cb3979e7166ad53ca405cf2b9d2c157c9e1e46cb8",
          "sha1": "b38b62373c695700b407b954829644f745d16fbc",
          "md5": "224b4f532f514483d0ab69fa62523423"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a69-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a69-0.8.5-sources.jar",
          "size": 3529,
          "sha512": "062504023e590ece9f9e26554fe1951c6251394a1ea544ae33296631aceadef3ba2de3680a523e1f643e18040f1d87298c0594a7eefdcb83ffd2ac63a78e77b6",
          "sha256": "9b9496992536caf7018c65d2fa62dab830165b87ce3530cdfc570ba5823ace3d",
          "sha1": "0e7b3c5702e3b53b4efc291d71f9703c2c46eeda",
          "md5": "983c14d9d25061215d521b376d0bce88"
        }
      ]
    }
  ]
}
