{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-company",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-company-0.4.4.jar",
          "url": "ble-core-constants-company-0.4.4.jar",
          "size": 78057,
          "sha512": "965991bd118b66575f94a773505f8d1259f06883ba177ecef8de067b02db3a69f15567ef7c46100c2e2ac7c020d6c71111f1bf622db522613872988dc1f8b476",
          "sha256": "b308c6e2bae2f334d98bf92fa1e0a884b895f24e88fb50433fbe0e2b52693ceb",
          "sha1": "df4f2878d2d6b8e7035da52118c56c549238051e",
          "md5": "747e0eda5c74203bb1324d404a09f563"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-company-0.4.4.jar",
          "url": "ble-core-constants-company-0.4.4.jar",
          "size": 78057,
          "sha512": "965991bd118b66575f94a773505f8d1259f06883ba177ecef8de067b02db3a69f15567ef7c46100c2e2ac7c020d6c71111f1bf622db522613872988dc1f8b476",
          "sha256": "b308c6e2bae2f334d98bf92fa1e0a884b895f24e88fb50433fbe0e2b52693ceb",
          "sha1": "df4f2878d2d6b8e7035da52118c56c549238051e",
          "md5": "747e0eda5c74203bb1324d404a09f563"
        }
      ]
    }
  ]
}
