{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc7-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc7",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc7-android-0.8.6.aar",
          "url": "ble-characteristic-u2bc7-android-0.8.6.aar",
          "size": 3100,
          "sha512": "c384ea7c829e55b7b584ce13135bc795c513db66917f77249e7a9215f2fa079a8f946031100306a87a5e790d66709b386e9695e719864c42a832c90bd0d04f09",
          "sha256": "3bcb17e049e0d098d9f15df406005f0b48d2211d5b9105cc084cd7e55f089acb",
          "sha1": "ba8b9b2faba87c5c9b619796edf8f83bb3ec59ec",
          "md5": "99b9b18a57d6f1900825b697199028f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc7",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc7-android-0.8.6.aar",
          "url": "ble-characteristic-u2bc7-android-0.8.6.aar",
          "size": 3100,
          "sha512": "c384ea7c829e55b7b584ce13135bc795c513db66917f77249e7a9215f2fa079a8f946031100306a87a5e790d66709b386e9695e719864c42a832c90bd0d04f09",
          "sha256": "3bcb17e049e0d098d9f15df406005f0b48d2211d5b9105cc084cd7e55f089acb",
          "sha1": "ba8b9b2faba87c5c9b619796edf8f83bb3ec59ec",
          "md5": "99b9b18a57d6f1900825b697199028f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc7-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bc7-android-0.8.6-sources.jar",
          "size": 2218,
          "sha512": "5d1e186126247891f95e09aad6eaa599b597565294456ccf3fe83d6af9504d197e672539f0286a1d229093abcae0013bfec0a865bc909724ddba5f06e4d442ee",
          "sha256": "b49e30e767a38e5a9181034ae93efcc1a70af5b7150403c0f9d8a6e0c43c5c11",
          "sha1": "2d67574e031cc357702e0caaf063d6359d189d45",
          "md5": "c8d7545b9ad14430a97758e0249f083e"
        }
      ]
    }
  ]
}
