{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8c-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-android-0.2.0.aar",
          "url": "ble-characteristic-u2a8c-android-0.2.0.aar",
          "size": 2877,
          "sha512": "e4830037b7bb4c95a2e1441c801163c01ca0f123f108bc422d13790f74af1d1ae59d96872341b1c43ee1365852afc99124592d00c2cf5de41b4bdd79cb44e9cb",
          "sha256": "e46d307db735f913a5298edb14ea111d66911e0a9224da24c9928e250a87f633",
          "sha1": "e949d26c11a2ebfae35b72386245d487a44dc9d8",
          "md5": "fd46a0924a7e5f7da50a779a9bea40bb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-android-0.2.0.aar",
          "url": "ble-characteristic-u2a8c-android-0.2.0.aar",
          "size": 2877,
          "sha512": "e4830037b7bb4c95a2e1441c801163c01ca0f123f108bc422d13790f74af1d1ae59d96872341b1c43ee1365852afc99124592d00c2cf5de41b4bdd79cb44e9cb",
          "sha256": "e46d307db735f913a5298edb14ea111d66911e0a9224da24c9928e250a87f633",
          "sha1": "e949d26c11a2ebfae35b72386245d487a44dc9d8",
          "md5": "fd46a0924a7e5f7da50a779a9bea40bb"
        }
      ]
    }
  ]
}
