{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5a",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xnyhilluxvgr3nzweyacpeoi5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5a-0.1.2.jar",
          "url": "ble-characteristic-u2a5a-0.1.2.jar",
          "size": 1743,
          "sha512": "34f330eb56803fb1a83154acc1ea161be0f07b91d6ce06f1b09386eef2598512e1c3684b7aead231c28f78711b7b288b951289b086b0ab1b78826dcb7d83aad2",
          "sha256": "21d2f75f8f5a09bf0819135621125b256c1655a107f9bdadd5efda542c04c86f",
          "sha1": "6b7a3266f7fec7696fcb410e13476bc98e843ac4",
          "md5": "b8c5ab524c86fa10e4398cac740f93aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5a-0.1.2.jar",
          "url": "ble-characteristic-u2a5a-0.1.2.jar",
          "size": 1743,
          "sha512": "34f330eb56803fb1a83154acc1ea161be0f07b91d6ce06f1b09386eef2598512e1c3684b7aead231c28f78711b7b288b951289b086b0ab1b78826dcb7d83aad2",
          "sha256": "21d2f75f8f5a09bf0819135621125b256c1655a107f9bdadd5efda542c04c86f",
          "sha1": "6b7a3266f7fec7696fcb410e13476bc98e843ac4",
          "md5": "b8c5ab524c86fa10e4398cac740f93aa"
        }
      ]
    }
  ]
}
