{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b15-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b15",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b15-android-0.8.6.aar",
          "url": "ble-characteristic-u2b15-android-0.8.6.aar",
          "size": 3109,
          "sha512": "e9a3f08b89f6008975253b9bb4c13c9f9632b01e754209bbbb0f6cfbb302eb91143b5104749414ebbceee7d9d1f3ef46d1433b5c06da50568c88fa3e561c7b00",
          "sha256": "f8d9914932b8f3c30121e054e7324c911a1d84ab90c5bc5628dc2a4b2cc9eab5",
          "sha1": "69ed7fab92d72f0477ec18439405e70794926e80",
          "md5": "2e22c2b07550ce675d7e886cfd6f4ce6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b15",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b15-android-0.8.6.aar",
          "url": "ble-characteristic-u2b15-android-0.8.6.aar",
          "size": 3109,
          "sha512": "e9a3f08b89f6008975253b9bb4c13c9f9632b01e754209bbbb0f6cfbb302eb91143b5104749414ebbceee7d9d1f3ef46d1433b5c06da50568c88fa3e561c7b00",
          "sha256": "f8d9914932b8f3c30121e054e7324c911a1d84ab90c5bc5628dc2a4b2cc9eab5",
          "sha1": "69ed7fab92d72f0477ec18439405e70794926e80",
          "md5": "2e22c2b07550ce675d7e886cfd6f4ce6"
        }
      ]
    }
  ]
}
