{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1c-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-android-0.2.9.aar",
          "url": "ble-characteristic-u2a1c-android-0.2.9.aar",
          "size": 3346,
          "sha512": "03bb783ab3d7c88cca087bff969606c7f5bde09713279154a3d3a167f787ec699a28773859942af9573bf784a0161242c7f2cecca0d339c51814cb004dd5b902",
          "sha256": "37c7f7fb6dceb48c3ef363be134c48ba5ba929d52dbfee8b37b008224a64db2e",
          "sha1": "2c04b7548012a93234bc2c34a48049cf0fb5b816",
          "md5": "a2210dd65ca22380ea94b63b0c8ba236"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-android-0.2.9.aar",
          "url": "ble-characteristic-u2a1c-android-0.2.9.aar",
          "size": 3346,
          "sha512": "03bb783ab3d7c88cca087bff969606c7f5bde09713279154a3d3a167f787ec699a28773859942af9573bf784a0161242c7f2cecca0d339c51814cb004dd5b902",
          "sha256": "37c7f7fb6dceb48c3ef363be134c48ba5ba929d52dbfee8b37b008224a64db2e",
          "sha1": "2c04b7548012a93234bc2c34a48049cf0fb5b816",
          "md5": "a2210dd65ca22380ea94b63b0c8ba236"
        }
      ]
    }
  ]
}
