{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acd",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acd-0.6.0.jar",
          "url": "ble-characteristic-u2acd-0.6.0.jar",
          "size": 7278,
          "sha512": "78c17272c9bef94f785cf442cefe54e896d65f7db868d39567f1b6f573a104039031213f08058cab056be4486390447cbb496b508caf9dcfb26f8b40a6cb9d0c",
          "sha256": "09f91b12431963e6fb8ddfe2a2a7d4e7b88b47525737d560ad7872a1c73601d2",
          "sha1": "ece4b606ac0bf0bc631d8140685e5ebbb0cadf9d",
          "md5": "3193e3cedb2a0e652659cef45011d7fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acd-0.6.0.jar",
          "url": "ble-characteristic-u2acd-0.6.0.jar",
          "size": 7278,
          "sha512": "78c17272c9bef94f785cf442cefe54e896d65f7db868d39567f1b6f573a104039031213f08058cab056be4486390447cbb496b508caf9dcfb26f8b40a6cb9d0c",
          "sha256": "09f91b12431963e6fb8ddfe2a2a7d4e7b88b47525737d560ad7872a1c73601d2",
          "sha1": "ece4b606ac0bf0bc631d8140685e5ebbb0cadf9d",
          "md5": "3193e3cedb2a0e652659cef45011d7fd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acd-0.6.0-javadoc.jar",
          "url": "ble-characteristic-u2acd-0.6.0-javadoc.jar",
          "size": 116267,
          "sha512": "7e1c5c27cefc45ca7a574b63b3b95a2695e60d1c53dffd0c61a45d144372e9da82a007bb9f9435a1591bebbc5985356a10d6bfcb9d98853bcd4db5717b78c0d9",
          "sha256": "cb71b06ffc7d0abfbdb317547dce61fed497973cdfb4adfa40bd6c68afed75ed",
          "sha1": "da9ada8c721f1ea0e2bbae0608643cb17ccc245f",
          "md5": "368239c0ead877c49329c005c2eecc77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acd-0.6.0-sources.jar",
          "url": "ble-characteristic-u2acd-0.6.0-sources.jar",
          "size": 5511,
          "sha512": "e41a9c700f4c596f4f32bdfc05fdaaf69757545ddca05a102f969b34bbcf9e90c1cbfab6d17e47595b0cabf25399aa9e8b21ce6ebd8846b8ecc05bee345e265e",
          "sha256": "5258b3581c0f1b43671814cbd0da5acd0ef7d9310bcd9898839fa9711d887640",
          "sha1": "9386504f6c0d752ee5018431a337de3f97bb3240",
          "md5": "1a925c83dba565f459df6be0639df1f9"
        }
      ]
    }
  ]
}
