{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5b-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.2.2.aar",
          "url": "ble-characteristic-u2a5b-android-0.2.2.aar",
          "size": 3000,
          "sha512": "c563bc0e3f53d054a6046f89007813a42a852f711e0378bbdfd5fbd614b33b9fac5c94a6afb4be907ac13b1b40500f7c37f2f434537220e88075c9abd4339334",
          "sha256": "ae5b578a010953f5d396faed78266d10af6cc50fa994680c791c29da246cf836",
          "sha1": "8e36d23d205fac7166169a6ef756da450fd178b1",
          "md5": "518c3507293239a547ffaac2545711e2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.2.2.aar",
          "url": "ble-characteristic-u2a5b-android-0.2.2.aar",
          "size": 3000,
          "sha512": "c563bc0e3f53d054a6046f89007813a42a852f711e0378bbdfd5fbd614b33b9fac5c94a6afb4be907ac13b1b40500f7c37f2f434537220e88075c9abd4339334",
          "sha256": "ae5b578a010953f5d396faed78266d10af6cc50fa994680c791c29da246cf836",
          "sha1": "8e36d23d205fac7166169a6ef756da450fd178b1",
          "md5": "518c3507293239a547ffaac2545711e2"
        }
      ]
    }
  ]
}
