{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afc-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afc",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afc-android-0.8.6.aar",
          "url": "ble-characteristic-u2afc-android-0.8.6.aar",
          "size": 3102,
          "sha512": "1d9e3e1551be3268c9325743ef8caa939a25bdfa0e8826d07f6b180709fc821298c11bb3bcac3535aa4fdb06d184f41fd6ff9f406a4c86467f3c26529a43ad46",
          "sha256": "4cd74bcca1904f00967abc88006380319c7d1758cd4a2a5459a35ea3fde4a30f",
          "sha1": "9710bf774c14cee7e0979e530c89ea14d1543153",
          "md5": "440691b5b974b0675b0e4db1193d5953"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afc",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afc-android-0.8.6.aar",
          "url": "ble-characteristic-u2afc-android-0.8.6.aar",
          "size": 3102,
          "sha512": "1d9e3e1551be3268c9325743ef8caa939a25bdfa0e8826d07f6b180709fc821298c11bb3bcac3535aa4fdb06d184f41fd6ff9f406a4c86467f3c26529a43ad46",
          "sha256": "4cd74bcca1904f00967abc88006380319c7d1758cd4a2a5459a35ea3fde4a30f",
          "sha1": "9710bf774c14cee7e0979e530c89ea14d1543153",
          "md5": "440691b5b974b0675b0e4db1193d5953"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afc-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2afc-android-0.8.6-sources.jar",
          "size": 2178,
          "sha512": "daf3b286c923b3d6bf76abcc4ae667a81fb5c0c271024ebeedd6fc1e201deeda27657800b938ad6ee4932eee303a8c62f6e19434ed98da6f0af5dfd5b525b007",
          "sha256": "788be357a9c0882ed4247234f341a0b54510484c661cbca046b4cf880c72a0df",
          "sha1": "92cc2219362347c12c60bded8c1163ec7b7e1831",
          "md5": "3027bf58d1c5ef2709ecaf8f276d1877"
        }
      ]
    }
  ]
}
