{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af3-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af3",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af3-android-0.4.4.aar",
          "url": "ble-characteristic-u2af3-android-0.4.4.aar",
          "size": 3175,
          "sha512": "dececcf8638b123b51987ff8270ff98b58f1354cadf7db9910a09d2cda6067dd3782f832c0776f3271e8f79658d6f0f39aa62bcf19475cf2b9bd0a2f749d48e2",
          "sha256": "342957468fb611df539db7f7d660612395146bbca7f99cd30914cc1343e9ba61",
          "sha1": "92df43e2d27ec8e10a818255d218dc64380215aa",
          "md5": "f83b5fcd2507d26065b8ef66f909c1a6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af3",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af3-android-0.4.4.aar",
          "url": "ble-characteristic-u2af3-android-0.4.4.aar",
          "size": 3175,
          "sha512": "dececcf8638b123b51987ff8270ff98b58f1354cadf7db9910a09d2cda6067dd3782f832c0776f3271e8f79658d6f0f39aa62bcf19475cf2b9bd0a2f749d48e2",
          "sha256": "342957468fb611df539db7f7d660612395146bbca7f99cd30914cc1343e9ba61",
          "sha1": "92df43e2d27ec8e10a818255d218dc64380215aa",
          "md5": "f83b5fcd2507d26065b8ef66f909c1a6"
        }
      ]
    }
  ]
}
