{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aff-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aff",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aff-android-0.4.4.aar",
          "url": "ble-characteristic-u2aff-android-0.4.4.aar",
          "size": 3057,
          "sha512": "dc4b6d3be16a472edc9f13c734662d8d936988230c9286ef39e6e218ace941a8b5ca99bc82cf7a3f813072f3ba19453e27620d90ba5d1a11e1069a62b0ae2420",
          "sha256": "4dfa4cdbb2cb32e1d3e46ef7b9c9f89541a940baa350866dc389a8d0e67c04c3",
          "sha1": "1734fd2d84d23107e599cdf0b9f7ca9b465ec516",
          "md5": "faec47aa105634d6d4114222b9a1d985"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aff",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aff-android-0.4.4.aar",
          "url": "ble-characteristic-u2aff-android-0.4.4.aar",
          "size": 3057,
          "sha512": "dc4b6d3be16a472edc9f13c734662d8d936988230c9286ef39e6e218ace941a8b5ca99bc82cf7a3f813072f3ba19453e27620d90ba5d1a11e1069a62b0ae2420",
          "sha256": "4dfa4cdbb2cb32e1d3e46ef7b9c9f89541a940baa350866dc389a8d0e67c04c3",
          "sha1": "1734fd2d84d23107e599cdf0b9f7ca9b465ec516",
          "md5": "faec47aa105634d6d4114222b9a1d985"
        }
      ]
    }
  ]
}
