{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lns-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a67-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b-android",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-android-0.1.4.aar",
          "url": "ble-service-lns-android-0.1.4.aar",
          "size": 1203,
          "sha512": "a0cc71e2debf53822b14b1ddca19072827f9cac193fb81ebe79effa2fc84bf50cc750bc6a8cada985ac8fb00c28dba7c77392ebcb1ae775704c9469f39c9075c",
          "sha256": "36bf73109d354d760a4bae869c42741b7dab966046b1dcd1823ecf4edfd707f2",
          "sha1": "1905d21ae0970ecff9777d56983efbf0b25118da",
          "md5": "e7e02a15fc56d0bbacced93a95ff3a54"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a67-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b-android",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-android-0.1.4.aar",
          "url": "ble-service-lns-android-0.1.4.aar",
          "size": 1203,
          "sha512": "a0cc71e2debf53822b14b1ddca19072827f9cac193fb81ebe79effa2fc84bf50cc750bc6a8cada985ac8fb00c28dba7c77392ebcb1ae775704c9469f39c9075c",
          "sha256": "36bf73109d354d760a4bae869c42741b7dab966046b1dcd1823ecf4edfd707f2",
          "sha1": "1905d21ae0970ecff9777d56983efbf0b25118da",
          "md5": "e7e02a15fc56d0bbacced93a95ff3a54"
        }
      ]
    }
  ]
}
