{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a74",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a74-0.8.12.jar",
          "url": "ble-characteristic-u2a74-0.8.12.jar",
          "size": 1813,
          "sha512": "2a627e8e1dcc588ee73bd1311abebe53c6cb1a093473fbcec5f24d8d07cde90930118ab9199794a4abddf70a9e4e1aa499e6646732a045f9b6ff7ea0058f6254",
          "sha256": "8b01a0283cb4584479197b8ca3a6378d1ef535c8f6408074673aefbb04199dca",
          "sha1": "5f94e62f448adbd074650116a87828f78514e1cc",
          "md5": "7d59551b397b623197600a38a9813d58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a74-0.8.12.jar",
          "url": "ble-characteristic-u2a74-0.8.12.jar",
          "size": 1813,
          "sha512": "2a627e8e1dcc588ee73bd1311abebe53c6cb1a093473fbcec5f24d8d07cde90930118ab9199794a4abddf70a9e4e1aa499e6646732a045f9b6ff7ea0058f6254",
          "sha256": "8b01a0283cb4584479197b8ca3a6378d1ef535c8f6408074673aefbb04199dca",
          "sha1": "5f94e62f448adbd074650116a87828f78514e1cc",
          "md5": "7d59551b397b623197600a38a9813d58"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a74-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a74-0.8.12-javadoc.jar",
          "size": 109304,
          "sha512": "61209a2e1586df3e1694253ae09593709a28ecbc955879cceca6ec9a1051c2a80c541f83583ff677ee9f03770842b576eeb98c3f187751337952397f14dbe071",
          "sha256": "841cefe703bc23ac224d3689afe13921d8df78e4788ffa00a75ec4fb1c5fb59a",
          "sha1": "f6278f9a73e05a076384694bfb88f419b216efb6",
          "md5": "3740170cfad032188759bb4df2810a5e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a74-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a74-0.8.12-sources.jar",
          "size": 1650,
          "sha512": "ebc4e7c23cb722ec0e9b7c4fd36f4da2f1804e4a8ccec74d4a9729e28e4b1577cd77a683f23c60490dba65befc993c3bae6d6be2f965846d5417b4ae45f25172",
          "sha256": "4a24e158752598c58b2705599f08e66fad1551138098964e99bbc2889db88581",
          "sha1": "70b7a177e2b34f7042259d50e75a6dab52445336",
          "md5": "95fae7fd8481874741e87a382c419d5b"
        }
      ]
    }
  ]
}
