{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.8.11.aar",
          "url": "ble-profile-peripheral-android-0.8.11.aar",
          "size": 2454,
          "sha512": "ada4b274b2958885006bedd06a47434b1441096679042f18825d2367ec18cd1f24c4dad3c5941a465f3ceb030259fcbba6a4d0c638ba832568a21681b00384c9",
          "sha256": "ad2829155ab309b11fb817625f8c4f83dda94fd3c5834cbdaf0ff3dc23bb33b9",
          "sha1": "58d498d2ee8ca5353af2f1c830d312452e505f1b",
          "md5": "f3f66298f9c5ee72b65aae3a363d9de1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.8.11.aar",
          "url": "ble-profile-peripheral-android-0.8.11.aar",
          "size": 2454,
          "sha512": "ada4b274b2958885006bedd06a47434b1441096679042f18825d2367ec18cd1f24c4dad3c5941a465f3ceb030259fcbba6a4d0c638ba832568a21681b00384c9",
          "sha256": "ad2829155ab309b11fb817625f8c4f83dda94fd3c5834cbdaf0ff3dc23bb33b9",
          "sha1": "58d498d2ee8ca5353af2f1c830d312452e505f1b",
          "md5": "f3f66298f9c5ee72b65aae3a363d9de1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.8.11-sources.jar",
          "url": "ble-profile-peripheral-android-0.8.11-sources.jar",
          "size": 2122,
          "sha512": "3026c90f1a1a6e0af9ce9eb2854641d713225fe669cb31b7c4b90136feae7f89a5a03f708a6e0523ee3ecb8d047a12a7127df3764a9203a564f201d3c71e6dd6",
          "sha256": "52473d99f1f748024f65e8fcfcc583a5fe5432bfa9874f31aa5aeb837973b12d",
          "sha1": "ad700b8aa0b91033f8856d9a9d88a0d311d9095a",
          "md5": "13d2ded4ac57fc3cfb2b76c087e4e2eb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.8.11-javadoc.jar",
          "url": "ble-profile-peripheral-android-0.8.11-javadoc.jar",
          "size": 272266,
          "sha512": "ea7acf24581f8507e99e2e801a872ce2c051ca1ab50398cdbeca82cdf3c1e653a3d983fe2cb24f7a56b6d84f04ece674801a3350ced78a315257460042fef1b1",
          "sha256": "51a5e97261b0baafc704ad6cbe7e8cc470dd920b314ae16ae6054ae914839001",
          "sha1": "e832837f93ddbd574f352961ff8de3216fc68e12",
          "md5": "6af3e8bf05d8233b55cd2ac8d6530afb"
        }
      ]
    }
  ]
}
