{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-wsp-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-wss-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-uds-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bcs-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bas-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-cts-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-wsp-android-0.4.6.aar",
          "url": "ble-profile-central-wsp-android-0.4.6.aar",
          "size": 8683,
          "sha512": "5ed68dff40252f3bfd47d64582ca9d90dcdb95060c8a3177d1ff67b8d4febb86392d49d3084bde76e9a5abe944e53c16c518a25c0d86d599527e0f46d3211e67",
          "sha256": "7d491e202ce2fc92e014ac298c29e8382d6f197b41a67d9a3aae33391be1ee79",
          "sha1": "38adfd2a078226020791fc0a4251f23a26d0e53a",
          "md5": "ba67a81f2104ee17403723366d15ad87"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-wss-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-uds-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bcs-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bas-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-cts-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-wsp-android-0.4.6.aar",
          "url": "ble-profile-central-wsp-android-0.4.6.aar",
          "size": 8683,
          "sha512": "5ed68dff40252f3bfd47d64582ca9d90dcdb95060c8a3177d1ff67b8d4febb86392d49d3084bde76e9a5abe944e53c16c518a25c0d86d599527e0f46d3211e67",
          "sha256": "7d491e202ce2fc92e014ac298c29e8382d6f197b41a67d9a3aae33391be1ee79",
          "sha1": "38adfd2a078226020791fc0a4251f23a26d0e53a",
          "md5": "ba67a81f2104ee17403723366d15ad87"
        }
      ]
    }
  ]
}
