{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aea",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.7.jar",
          "url": "ble-characteristic-u2aea-0.8.7.jar",
          "size": 1742,
          "sha512": "7fd5da8596d23a92ee85da0292d992e5d7c6614cc93f2b1aee5de8680a522d92c88e89c0c2b105ab61fb035ed81980e7ecb2789d40b7cb5c4df2f3a8d993d674",
          "sha256": "a5ea873122c00814e7bd1e7c5b083fcbc7ca2c2255ba73202e6ef6a492096bfd",
          "sha1": "a7e2debb92c7d56603d000816e3f9e5922e0621d",
          "md5": "4ad08eff570fa5d21f6ec9a16ef873fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.7.jar",
          "url": "ble-characteristic-u2aea-0.8.7.jar",
          "size": 1742,
          "sha512": "7fd5da8596d23a92ee85da0292d992e5d7c6614cc93f2b1aee5de8680a522d92c88e89c0c2b105ab61fb035ed81980e7ecb2789d40b7cb5c4df2f3a8d993d674",
          "sha256": "a5ea873122c00814e7bd1e7c5b083fcbc7ca2c2255ba73202e6ef6a492096bfd",
          "sha1": "a7e2debb92c7d56603d000816e3f9e5922e0621d",
          "md5": "4ad08eff570fa5d21f6ec9a16ef873fc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2aea-0.8.7-javadoc.jar",
          "size": 107274,
          "sha512": "c6786b69cbd69088a2071773f88a1fbe4324b142341e667699d417241a27919ed77f2168cfaf54b377c120f744c1f7f8702c84de19eaf706715cbabc86e09bb4",
          "sha256": "547162589e3fa1de9d7725baf53b13090358c3f3ab39c92ada7abb8de5e49730",
          "sha1": "e459e1535adeb16abb658a00dde6edf9664225eb",
          "md5": "05b0ae50ec1a84f7cc4169523a524925"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.7-sources.jar",
          "url": "ble-characteristic-u2aea-0.8.7-sources.jar",
          "size": 1582,
          "sha512": "e3b83b8bdb4739adea225678e3679e528deb108be10dcf8fc9c04a690b832208b005e0cd2d1997c91896eed6b1ee23a3b28bf1eae930cc04ea765d7c356b42b0",
          "sha256": "4e39a10579af0ba43edd1d1dafd88ef1ae18364c3cfa0024ff8d8cbb220ca37a",
          "sha1": "93e2bcb192df3886cc14313db7fe2f245c0162a8",
          "md5": "0039d90dd2b265a60b140af422e5ca9c"
        }
      ]
    }
  ]
}
