{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2909",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2909-0.8.0.jar",
          "url": "ble-descriptor-u2909-0.8.0.jar",
          "size": 1707,
          "sha512": "95ffbe13dc9410722cc192b5e273a5e02f79881437511e03b1757b2dffb4d4e17f475da539c332d285a6988a55a461b779cf57eecef46a6dc7962610ecd514a0",
          "sha256": "b43b1d0845a1fe2a7674e507136a5cb9236cc210205e3e2880614cc7cb274761",
          "sha1": "e365646493ba1e9343eaa9fc97742b3a019c2de1",
          "md5": "bc051998b678756a0e54160d21fc83ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2909-0.8.0.jar",
          "url": "ble-descriptor-u2909-0.8.0.jar",
          "size": 1707,
          "sha512": "95ffbe13dc9410722cc192b5e273a5e02f79881437511e03b1757b2dffb4d4e17f475da539c332d285a6988a55a461b779cf57eecef46a6dc7962610ecd514a0",
          "sha256": "b43b1d0845a1fe2a7674e507136a5cb9236cc210205e3e2880614cc7cb274761",
          "sha1": "e365646493ba1e9343eaa9fc97742b3a019c2de1",
          "md5": "bc051998b678756a0e54160d21fc83ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2909-0.8.0-javadoc.jar",
          "url": "ble-descriptor-u2909-0.8.0-javadoc.jar",
          "size": 109971,
          "sha512": "be214277174913966e46d3c995d8f9685bcd54ecf92384409fc2d6a26e2b72c6c44b7914b03c07d70a83d9e1cbbfb70f6bd2cb6a1b8d00cb3436eaceb6f1105f",
          "sha256": "0b472825779d2f37ad75cb062b9b8328870d1fc0348d13c3e0a5f439d25ba275",
          "sha1": "dcddf232def7d311b9d1135ef4e84394ec3b4d9f",
          "md5": "39bae1b3e69ab611a44bda6817923d73"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2909-0.8.0-sources.jar",
          "url": "ble-descriptor-u2909-0.8.0-sources.jar",
          "size": 1568,
          "sha512": "5603edd491bdb727cccc37df93a18d90858caab34fa80647dc60a737caef5d114f0687a81d77cceb780ffc6f32ebce3b7af50829797118cfdc0e92c6ffdcaa59",
          "sha256": "7ebf6a9bf3c2d6066666808a15be5e03462e2cb7110b43c3e52cb91717dc6da0",
          "sha1": "3a4c34de99f6871f32c5f332d937a08f0129c9c2",
          "md5": "2b1cbbf02349343a1cf3dcd9c4bcf42b"
        }
      ]
    }
  ]
}
