{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3a",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.7.jar",
          "url": "ble-characteristic-u2b3a-0.8.7.jar",
          "size": 2726,
          "sha512": "a6df48c974b6a86a79090c3b0775cac363d4025823141a82354b23fb15812dfedddc826e3e6ae1bdacef0d8080bd7509ab3c73d12dab2954e515fad554e78e67",
          "sha256": "40136718ebdd095ef47d3a7663f7e939723a9a51a3e6ac568f2299aa712452eb",
          "sha1": "93828ff7d0023820dc3afa870265c3addf467754",
          "md5": "75f465702dc4c87c7424366d0b299e55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.7.jar",
          "url": "ble-characteristic-u2b3a-0.8.7.jar",
          "size": 2726,
          "sha512": "a6df48c974b6a86a79090c3b0775cac363d4025823141a82354b23fb15812dfedddc826e3e6ae1bdacef0d8080bd7509ab3c73d12dab2954e515fad554e78e67",
          "sha256": "40136718ebdd095ef47d3a7663f7e939723a9a51a3e6ac568f2299aa712452eb",
          "sha1": "93828ff7d0023820dc3afa870265c3addf467754",
          "md5": "75f465702dc4c87c7424366d0b299e55"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b3a-0.8.7-javadoc.jar",
          "size": 108023,
          "sha512": "9144d8f62fc1aed053dfd497e121d74d832a711f0358bd6f04eb862886f5e52e405012cd2066dc492cce89392692e03a317e9c244649fd152ffd4611297ff987",
          "sha256": "f2137c0bbc0070d479334442feb798697cb014a61c403c11d1b738bfd5c78d52",
          "sha1": "551322cf270edfbf46587a018d71345d192b83be",
          "md5": "2c821da32ed2904e257fa5b3fb9a5442"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b3a-0.8.7-sources.jar",
          "size": 2049,
          "sha512": "34d0d47e1408b4485e40653d5f7f82ac71fb6bc9b1474c8a9c38adba6824ea8d442713a7672b839d6b3c8cadb69d5485848349fa36833bb401cc69651a3febf5",
          "sha256": "a9a02d45413adcf153aa6fd6e1867b5f52d797429e141127c6750844234d037e",
          "sha1": "a27744668f5dd4cf6fbd5855dae60f588c05ac7d",
          "md5": "2299bd1bcac16567108c96a53d37a274"
        }
      ]
    }
  ]
}
