{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a74-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a74",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a74-android-0.8.12.aar",
          "url": "ble-characteristic-u2a74-android-0.8.12.aar",
          "size": 3170,
          "sha512": "381bfc97c6bb06f1d2ef5daeeb5b345c6ba037cbbe9df69359733858151f9e1cce84030ab743b4e89b997acd6a4dac767d272e61653d8579e5755d63858d5288",
          "sha256": "2568483ee7e7489d1f87f6172a68e93d9990d52cce2d0822e6d70ccd0877524c",
          "sha1": "5be59aaf11e2466a8f1469b09b552e927d20e247",
          "md5": "bb08a8477eeaa2bea31dbde1c1c3ee2e"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a74",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a74-android-0.8.12.aar",
          "url": "ble-characteristic-u2a74-android-0.8.12.aar",
          "size": 3170,
          "sha512": "381bfc97c6bb06f1d2ef5daeeb5b345c6ba037cbbe9df69359733858151f9e1cce84030ab743b4e89b997acd6a4dac767d272e61653d8579e5755d63858d5288",
          "sha256": "2568483ee7e7489d1f87f6172a68e93d9990d52cce2d0822e6d70ccd0877524c",
          "sha1": "5be59aaf11e2466a8f1469b09b552e927d20e247",
          "md5": "bb08a8477eeaa2bea31dbde1c1c3ee2e"
        }
      ]
    }
  ]
}
