{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-peripheral",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-advertising-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-handler",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-peripheral-0.3.0.aar",
          "url": "ble-peripheral-0.3.0.aar",
          "size": 40952,
          "sha512": "e2e0ecd8ce0f5dadfbc2524898020b8c094aa66d94efcf7bbaa55262c919214148de9aa8741a6cce6a1a46bdc82fd9fd2b2e511cc99def0e2b9642956dc9b84b",
          "sha256": "0f7c584a48c14233be272040b8a4a6c99bd9950e07529a18703abd378410ecdb",
          "sha1": "c662b7b8de4d8924c60acd77740f81684ba95ef9",
          "md5": "f3a122f2e086ff5147717e5ebb7dffcf"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-advertising-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-handler",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-peripheral-0.3.0.aar",
          "url": "ble-peripheral-0.3.0.aar",
          "size": 40952,
          "sha512": "e2e0ecd8ce0f5dadfbc2524898020b8c094aa66d94efcf7bbaa55262c919214148de9aa8741a6cce6a1a46bdc82fd9fd2b2e511cc99def0e2b9642956dc9b84b",
          "sha256": "0f7c584a48c14233be272040b8a4a6c99bd9950e07529a18703abd378410ecdb",
          "sha1": "c662b7b8de4d8924c60acd77740f81684ba95ef9",
          "md5": "f3a122f2e086ff5147717e5ebb7dffcf"
        }
      ]
    }
  ]
}
