{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-ftmp-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-ftms-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-uds-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-ftmp-android-0.8.6.aar",
          "url": "ble-profile-central-ftmp-android-0.8.6.aar",
          "size": 10671,
          "sha512": "30365e372dad85885aead319ac9a4b3056d4006df1896fd70e4d224dca3e546f5d8f900aa18b514e5d4a7f7dda52d618000e9a2c777e3a9a251f37bda444bfa8",
          "sha256": "11ca2ab6af729171bf3f16416223a4567c4fdfb1be0ebf48f474720850663ac3",
          "sha1": "ddfb1e6862888657aaef165a626a1cea977a3145",
          "md5": "28b74ba0771d5c44f0e5586895f37281"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-ftms-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-uds-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-ftmp-android-0.8.6.aar",
          "url": "ble-profile-central-ftmp-android-0.8.6.aar",
          "size": 10671,
          "sha512": "30365e372dad85885aead319ac9a4b3056d4006df1896fd70e4d224dca3e546f5d8f900aa18b514e5d4a7f7dda52d618000e9a2c777e3a9a251f37bda444bfa8",
          "sha256": "11ca2ab6af729171bf3f16416223a4567c4fdfb1be0ebf48f474720850663ac3",
          "sha1": "ddfb1e6862888657aaef165a626a1cea977a3145",
          "md5": "28b74ba0771d5c44f0e5586895f37281"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-central-ftmp-android-0.8.6-sources.jar",
          "url": "ble-profile-central-ftmp-android-0.8.6-sources.jar",
          "size": 8372,
          "sha512": "0371ae072d03c174a161985974b9e119fb78e9d137c24e313df22c4d855117a4102c9febc43edca4dbb5c23c94c28df504c7b37977831e51afb5fdcd235354cd",
          "sha256": "e5df6f90a1d5ab1e3dfff6d9e1c39890199f59e9041c1de76bb569fcf7fd4704",
          "sha1": "f419a73f50adad22ac0d6befa43871d554f617fe",
          "md5": "79dbd1a320b8289c6f5c61bf43e1c575"
        }
      ]
    }
  ]
}
