{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9d",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.7.jar",
          "url": "ble-characteristic-u2b9d-0.8.7.jar",
          "size": 1468,
          "sha512": "1f07048b34511d3542edaf22f179c18b447111d7a0b0940ac17b6e924729a4a1da78a75bbb37d2c43dc06415d47ff4fe13da5a6f6ca25c9e1f9f2c9a82ce6bdc",
          "sha256": "e26f2b125a7c3693a92aedfef7c882cd0653acf384aa02015d9345069d85d888",
          "sha1": "5b580e9ca854c2421e8f2f7e8905cf96d82dbcd2",
          "md5": "8206038eca202ccfbdb5e70da667c9b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.7.jar",
          "url": "ble-characteristic-u2b9d-0.8.7.jar",
          "size": 1468,
          "sha512": "1f07048b34511d3542edaf22f179c18b447111d7a0b0940ac17b6e924729a4a1da78a75bbb37d2c43dc06415d47ff4fe13da5a6f6ca25c9e1f9f2c9a82ce6bdc",
          "sha256": "e26f2b125a7c3693a92aedfef7c882cd0653acf384aa02015d9345069d85d888",
          "sha1": "5b580e9ca854c2421e8f2f7e8905cf96d82dbcd2",
          "md5": "8206038eca202ccfbdb5e70da667c9b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b9d-0.8.7-javadoc.jar",
          "size": 107213,
          "sha512": "e00df6c23612c6f773a1bcafdcdea8c117f7d04ad3641cc2e8d2af7294adf51c5848b877001c52d7316567312d3bddee49f350b83473d64521e7d8344bb2b54c",
          "sha256": "5ee29f839988218c1370d4d704adcd3605b0d3b74f4c6f1054fd02b73cf65e3b",
          "sha1": "83702f7e8c760a45a30bb86786f0a7f4e38280b2",
          "md5": "fa098ce49cce6c17cc3076c73c727788"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b9d-0.8.7-sources.jar",
          "size": 1466,
          "sha512": "70f20622aeb987a37953afced67abff81260c440276afa3ef9e7f7a6f6fbe8fb935244126db28a06b1193f8372f4aefdf8cba7b3511e7d1766788cd559945fe2",
          "sha256": "2cadff74c46dda225d79f9fc5bbba5359f380f16f03ee64bf357bf996da0db14",
          "sha1": "27040d42a56b02b5326374c57dc835c973d3275e",
          "md5": "6aefea1564ca3ebdfdd5728f8927c0af"
        }
      ]
    }
  ]
}
