{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd3-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd3",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd3-android-0.8.6.aar",
          "url": "ble-characteristic-u2bd3-android-0.8.6.aar",
          "size": 3250,
          "sha512": "598d15e74fe0836581ca7c10c97eb7cdaac99a05f604aca3d33c0466fd9866d7356a4163776f00be7fc62220ac3a10e4051b668af7d256d245f3c13c19b0d2f6",
          "sha256": "df7fa1cf50b5222426e9385c8367ae9cbd8c385f31884a8aa937d92eb7756bf6",
          "sha1": "35d232e63867320801d9502075351eb5f738f06c",
          "md5": "69356d153ca448596f714c4cef310936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd3",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd3-android-0.8.6.aar",
          "url": "ble-characteristic-u2bd3-android-0.8.6.aar",
          "size": 3250,
          "sha512": "598d15e74fe0836581ca7c10c97eb7cdaac99a05f604aca3d33c0466fd9866d7356a4163776f00be7fc62220ac3a10e4051b668af7d256d245f3c13c19b0d2f6",
          "sha256": "df7fa1cf50b5222426e9385c8367ae9cbd8c385f31884a8aa937d92eb7756bf6",
          "sha1": "35d232e63867320801d9502075351eb5f738f06c",
          "md5": "69356d153ca448596f714c4cef310936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd3-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bd3-android-0.8.6-sources.jar",
          "size": 2340,
          "sha512": "5a936eb1cd875743abece206d62111c06aac6983b7367e5e0428cf062fe24d874f69c461ef2dcec42372cc44aaf930fd40a3c946b9a5dc20ec67d7015493844b",
          "sha256": "89555bb3471b88c7d38c02695badb5d3c712901d70d46e9ab8d4e9e69fef32a6",
          "sha1": "efa53564c5e47efafc28b7ab1500f51fdb654b1d",
          "md5": "3422800e17a9236e7efc25ee5df7959c"
        }
      ]
    }
  ]
}
