{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2b-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b2b",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2b-android-0.4.3.aar",
          "url": "ble-characteristic-u2b2b-android-0.4.3.aar",
          "size": 3062,
          "sha512": "48d14aaaedb393c6e44ea32edbd347ea648f229f9ccd611349efbe8171c12eea76b7c260b8e7976cd7d52e8e1dc85e2c8b896ddad9ec7716c4535d78c0723bb7",
          "sha256": "3cc408dccdd6d4eb5f6aa8fdaa0f42d03b5fbd38b455eab02941093d420e167f",
          "sha1": "b90d9cf9608e8dbeecc6befd1722cb0177a05953",
          "md5": "99236e6093be94ca3d3d1d4b76010a3c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b2b",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2b-android-0.4.3.aar",
          "url": "ble-characteristic-u2b2b-android-0.4.3.aar",
          "size": 3062,
          "sha512": "48d14aaaedb393c6e44ea32edbd347ea648f229f9ccd611349efbe8171c12eea76b7c260b8e7976cd7d52e8e1dc85e2c8b896ddad9ec7716c4535d78c0723bb7",
          "sha256": "3cc408dccdd6d4eb5f6aa8fdaa0f42d03b5fbd38b455eab02941093d420e167f",
          "sha1": "b90d9cf9608e8dbeecc6befd1722cb0177a05953",
          "md5": "99236e6093be94ca3d3d1d4b76010a3c"
        }
      ]
    }
  ]
}
