{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a93",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-0.8.7.jar",
          "url": "ble-characteristic-u2a93-0.8.7.jar",
          "size": 2358,
          "sha512": "276345a55885b125580d6f22217f2bd0b77b74a7bff4e4e46da06c34d4724ec8d45495d72c95ff802507a881f141a70b4d9ee0815afbbc2a012c044a8e76248d",
          "sha256": "b48cd8fa03de421c9c06899abe5fc2bcc51ab104858e378499603fecbad59441",
          "sha1": "a2137bcd455d99d16229ac033d45f33107b62ab8",
          "md5": "4688942c5db28a84e2ffcf541b98fdd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-0.8.7.jar",
          "url": "ble-characteristic-u2a93-0.8.7.jar",
          "size": 2358,
          "sha512": "276345a55885b125580d6f22217f2bd0b77b74a7bff4e4e46da06c34d4724ec8d45495d72c95ff802507a881f141a70b4d9ee0815afbbc2a012c044a8e76248d",
          "sha256": "b48cd8fa03de421c9c06899abe5fc2bcc51ab104858e378499603fecbad59441",
          "sha1": "a2137bcd455d99d16229ac033d45f33107b62ab8",
          "md5": "4688942c5db28a84e2ffcf541b98fdd7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a93-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a93-0.8.7-javadoc.jar",
          "size": 111833,
          "sha512": "3fb953090533843ef1946bdcc4d1c14f7a537521be842955178c558db4a54e848e92ed4486e44d8f632f409bc576cc692cd58d67d69f0bfc04fb03eb20fe710f",
          "sha256": "b4b84285f64f111c390a7894fb55287022ce7b1421c219282e1adef9f70b95ff",
          "sha1": "36c0b0f1220b1e291a6e8d5b36bd19e1ea24a8d4",
          "md5": "07ca4396ac551f082cd1cd03dad1d43f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a93-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a93-0.8.7-sources.jar",
          "size": 2285,
          "sha512": "ebbbdfa19508fbee902e404a7631c576a2cd66fecd4a30e487389fa2720d67ea06f924016fef8a94b1cec8f41336392a49278e15c1e5a9605bc0f0f1cce14590",
          "sha256": "96772d57f03ba872f134a67f8f6629a8430f3d9433c98204bef5d6455e3763de",
          "sha1": "12fbae122e3ed8cec151cb57acff164fc662504d",
          "md5": "525702128fad5cf87be700d48e3934b2"
        }
      ]
    }
  ]
}
