{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a2c",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2c-0.8.12.jar",
          "url": "ble-characteristic-u2a2c-0.8.12.jar",
          "size": 1886,
          "sha512": "85887dbcffc6d77ced34f139253bdf0709651fc1646fac99e45005a8a93549d50ed4df3eebb98d100569241fc629d5ed6a6a9e5c19558c687584ad1f77d10cb8",
          "sha256": "0e765c70e33f79225f9cc59e1c7e13e6070fefca9045af399c5cd703ac3000cd",
          "sha1": "b4a81763035a42e57cfc916305af386d376b2f5c",
          "md5": "42ed3af2f59d8a14dacf0f0817a236a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2c-0.8.12.jar",
          "url": "ble-characteristic-u2a2c-0.8.12.jar",
          "size": 1886,
          "sha512": "85887dbcffc6d77ced34f139253bdf0709651fc1646fac99e45005a8a93549d50ed4df3eebb98d100569241fc629d5ed6a6a9e5c19558c687584ad1f77d10cb8",
          "sha256": "0e765c70e33f79225f9cc59e1c7e13e6070fefca9045af399c5cd703ac3000cd",
          "sha1": "b4a81763035a42e57cfc916305af386d376b2f5c",
          "md5": "42ed3af2f59d8a14dacf0f0817a236a2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a2c-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a2c-0.8.12-javadoc.jar",
          "size": 109414,
          "sha512": "a27268b897d9f48cadaec72768a822619ac370e1bd7f43389aa167084682d913a0d76a1882d8e362c55914a3e646c3ff41cd876d9569ee376d3dca77dbd54da7",
          "sha256": "8c1e10d14bd15c526634a38230f55a8d3ee7493d1f2b210086ed0d742984c829",
          "sha1": "2f3fb98ec9364818ece0c59f0d6936abf927bbdc",
          "md5": "c6ca93bb10a8816aa14f686050d23a94"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a2c-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a2c-0.8.12-sources.jar",
          "size": 1702,
          "sha512": "c7b67a458a193e91f883978bccdbaeff9898ec5d69b1aed476f637f37833d72c4e9838faadfd88277ca7412410eb567733d4cfa289cbfd4534102c57bcecb5b4",
          "sha256": "bd27444b5e07d34c97d8e836a6f6c1eb14267f45c62e0381e937518232ca08e9",
          "sha1": "83f55b2de0d8b97f004458aa42962bf95c412f74",
          "md5": "9ef98016498cfabd57704939dbc3c63d"
        }
      ]
    }
  ]
}
