{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a00",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-0.8.6.jar",
          "url": "ble-characteristic-u2a00-0.8.6.jar",
          "size": 1569,
          "sha512": "a3aeaa147881ed3b17b853efe3f939b9692f347c492de8f89438f2e13e3b7fe12d494c77d7669ecfdd698daccd3d6887048d3ee33232d4dc0d61758e5441b427",
          "sha256": "f59c5fcc9b1e4e931aac63987dca6933c8849f2178723627af4d700bc876985d",
          "sha1": "820b7b1674fb8530f6ec10f6f13456360bb8123d",
          "md5": "a5e41882033c2248059808130b984f62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-0.8.6.jar",
          "url": "ble-characteristic-u2a00-0.8.6.jar",
          "size": 1569,
          "sha512": "a3aeaa147881ed3b17b853efe3f939b9692f347c492de8f89438f2e13e3b7fe12d494c77d7669ecfdd698daccd3d6887048d3ee33232d4dc0d61758e5441b427",
          "sha256": "f59c5fcc9b1e4e931aac63987dca6933c8849f2178723627af4d700bc876985d",
          "sha1": "820b7b1674fb8530f6ec10f6f13456360bb8123d",
          "md5": "a5e41882033c2248059808130b984f62"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a00-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a00-0.8.6-javadoc.jar",
          "size": 107354,
          "sha512": "4bacebcc8a35c59b96c4381eeb94b196d6adb0c5cdfd8cd08aa77100f3200e82b954f6ebaf56ab62370b21e44ef15f4d6cb9dff683e30923e4b16867a0513ffd",
          "sha256": "fa9966aea46bac5ee1a09c8d6b3e0c290995415520d5240392a0188fbb9af174",
          "sha1": "59a1ce3bfc39b0ee0acff37f9664a44d6800ebc6",
          "md5": "b162d123d195eb487d72186c65bd5f1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a00-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a00-0.8.6-sources.jar",
          "size": 1478,
          "sha512": "77f6965d1e1f4e209ef336a9343ffe12bd2f0d6193c99b76f3a431d386b8f876f25cfb106183a4a25d3beb03f84db314c7a78db6b645fdd34536d109a4817483",
          "sha256": "34596c3ae6c1ec4bfb485318ade49b71e3b849e45dabf36e37a385a549e9d0a7",
          "sha1": "30d8290ba2a86055ac4867c910b523c56503ee27",
          "md5": "1f1ddbbab49e5323a568415a754fab6c"
        }
      ]
    }
  ]
}
