{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9c-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rwz5w2a4ijg27poploejtwndhi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.2.0.aar",
          "url": "ble-characteristic-u2a9c-android-0.2.0.aar",
          "size": 5341,
          "sha512": "753a03bbcf0a4c6a53e26c4e624454142b40d50e9b6e5b626064202171cccbb2af5c1b72f7ee61c07a0817af495e55ba4da47f903714f1d150e5fdcd21282a1b",
          "sha256": "b66b18cd0a38121977ab54f70e8e6881bb516fd9628246b0de729963e812b83b",
          "sha1": "66e288c9b0796721d82be64db8b161f462faaa10",
          "md5": "f00c18d6de2d7538c7c03799bc150f30"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.2.0.aar",
          "url": "ble-characteristic-u2a9c-android-0.2.0.aar",
          "size": 5341,
          "sha512": "753a03bbcf0a4c6a53e26c4e624454142b40d50e9b6e5b626064202171cccbb2af5c1b72f7ee61c07a0817af495e55ba4da47f903714f1d150e5fdcd21282a1b",
          "sha256": "b66b18cd0a38121977ab54f70e8e6881bb516fd9628246b0de729963e812b83b",
          "sha1": "66e288c9b0796721d82be64db8b161f462faaa10",
          "md5": "f00c18d6de2d7538c7c03799bc150f30"
        }
      ]
    }
  ]
}
