{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ftms-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acc-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ace-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acf-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad0-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad4-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad5-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad7-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ada-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ftms-android-0.8.13.aar",
          "url": "ble-service-ftms-android-0.8.13.aar",
          "size": 1299,
          "sha512": "2076a80d1c902970494b0367c4b7a44b2b06cf659ce48e01ca4874df011ea42acb38904762bafc2e1eed7f79d29f32fd6719295ff76ac02ab638790fa8247bc5",
          "sha256": "38acc25ace88e3a4322f8834734b2ac68cb06ce001f64c6cad60c2eb9b475047",
          "sha1": "e3308f300738bd8026dee12784954cc0f2615904",
          "md5": "84dbd45ebe131fc2f23f598c06ca289c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acc-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ace-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acf-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad0-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad4-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad5-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad7-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ada-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ftms-android-0.8.13.aar",
          "url": "ble-service-ftms-android-0.8.13.aar",
          "size": 1299,
          "sha512": "2076a80d1c902970494b0367c4b7a44b2b06cf659ce48e01ca4874df011ea42acb38904762bafc2e1eed7f79d29f32fd6719295ff76ac02ab638790fa8247bc5",
          "sha256": "38acc25ace88e3a4322f8834734b2ac68cb06ce001f64c6cad60c2eb9b475047",
          "sha1": "e3308f300738bd8026dee12784954cc0f2615904",
          "md5": "84dbd45ebe131fc2f23f598c06ca289c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-ftms-android-0.8.13-sources.jar",
          "url": "ble-service-ftms-android-0.8.13-sources.jar",
          "size": 1198,
          "sha512": "45306fba0b120626dadb284ba5b1c515c22d5bc813274a80dfd3f827cd6ca466f771a007efcd7e7326000f6d5f828b420386ba71dd15189ea397264d8fb3c7ed",
          "sha256": "70a10ea6abb8abf2c10825368d7f91f2d81e5a540a4439d6a923fc88bb7519b6",
          "sha1": "ef3b891aa603b2b2089d23d6f4b5272faa869ec2",
          "md5": "c0c3484e663738562bfa8eca98c5a9a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-ftms-android-0.8.13-javadoc.jar",
          "url": "ble-service-ftms-android-0.8.13-javadoc.jar",
          "size": 259963,
          "sha512": "eed188a6a4f40b7052c591f88eaf96df4e8e0b067eb1e3787d72c5e4ed6fbfd58d9f7359c370b7051bcfabd954bf80b91e49c9eb94037b88d647cd82c909ea13",
          "sha256": "b197608963fa808880dc024c8dd3ee8c83bf21d92c68a5664d610c3a0eda58ab",
          "sha1": "7d06ff07df984cc0de7aaaf94cb5040741170bd1",
          "md5": "d51a2c2f6aa08110015a891c0adb580a"
        }
      ]
    }
  ]
}
