{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b43",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b43-0.8.5.jar",
          "url": "ble-characteristic-u2b43-0.8.5.jar",
          "size": 1512,
          "sha512": "115e2748414e21e81a63f2d950c57af81c6e093fd9cb034846f3ee375057c2e651cf599eb542b44888c799982db4e3349cd7aa7f20b3b0b6f8bea63c4302a6ac",
          "sha256": "8ad32c4c0277882f06a90eeab21e8fc9eb8c3904ed4092f46e69f6d3bada181a",
          "sha1": "965a58ed3fc639fc66f0992dbec60c1b07289770",
          "md5": "a84c6be917e2631b689d3d7d413f56ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b43-0.8.5.jar",
          "url": "ble-characteristic-u2b43-0.8.5.jar",
          "size": 1512,
          "sha512": "115e2748414e21e81a63f2d950c57af81c6e093fd9cb034846f3ee375057c2e651cf599eb542b44888c799982db4e3349cd7aa7f20b3b0b6f8bea63c4302a6ac",
          "sha256": "8ad32c4c0277882f06a90eeab21e8fc9eb8c3904ed4092f46e69f6d3bada181a",
          "sha1": "965a58ed3fc639fc66f0992dbec60c1b07289770",
          "md5": "a84c6be917e2631b689d3d7d413f56ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b43-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b43-0.8.5-javadoc.jar",
          "size": 107368,
          "sha512": "d7b9aeb354f73aa121841d0ccb0f29c24ee451f9467ea1c2c53db30554b899a102f114c8c036fcb09473ecb7c0bae168f7df2f9cd3959ecb4961a31644cb56c1",
          "sha256": "5f5a02131ef2d9fecab9cb7415b0bb5c62b66c608956f424aca01cf6510ac42d",
          "sha1": "c8fbbc4cff1d29f1aa6b7b6188420ba850bca4e3",
          "md5": "c8074301425d45117749ce3770232fc7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b43-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b43-0.8.5-sources.jar",
          "size": 1503,
          "sha512": "c0119267c09c23a8311106eabbab2662512e3d53f806bb50dd75a7700641a424ac3d3dc417ff7b62f02bf1be30d4e0d9c62426043e221bcc12a64436d2c3896a",
          "sha256": "263bf2392d06ae14d60cecb01d42f64e7d84806d4c35a210cff1df1d4fdef9c1",
          "sha1": "c40ce08483bf7e9dbbe648e1bc391ac2c5fe1d0d",
          "md5": "1138d164f746d0678770d1a2bfcaa33b"
        }
      ]
    }
  ]
}
