{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6b-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "swq2gxvgereszma3nz5hc5y3xq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.2.5.aar",
          "url": "ble-characteristic-u2a6b-android-0.2.5.aar",
          "size": 3176,
          "sha512": "0e4c697d744b1b44a47cc871beac00578afd221937aa15fde56b405c158644165c5226d2eeed3ac8940dfb4e2b8120af36d399b13aff998caa8430bf8af87e23",
          "sha256": "30913ebc9b8072294bf8116c4caa97d704538f4056044053f4cff32a900c6966",
          "sha1": "a7fcc613029e7d02cd5566b758fe72dcfc1a6219",
          "md5": "121ce6d886ad8bef3650a831015ff2cd"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.2.5.aar",
          "url": "ble-characteristic-u2a6b-android-0.2.5.aar",
          "size": 3176,
          "sha512": "0e4c697d744b1b44a47cc871beac00578afd221937aa15fde56b405c158644165c5226d2eeed3ac8940dfb4e2b8120af36d399b13aff998caa8430bf8af87e23",
          "sha256": "30913ebc9b8072294bf8116c4caa97d704538f4056044053f4cff32a900c6966",
          "sha1": "a7fcc613029e7d02cd5566b758fe72dcfc1a6219",
          "md5": "121ce6d886ad8bef3650a831015ff2cd"
        }
      ]
    }
  ]
}
