{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a58-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a58",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a58-android-0.1.3.aar",
          "url": "ble-characteristic-u2a58-android-0.1.3.aar",
          "size": 3006,
          "sha512": "c4bdd599f8741c4402bd3a9e2db2529d647b3fe30ca5a9f604bdc5e1c464e0a20c5d30b0cd9a2fd6436f11507e5ec4eb92e505b2a1da4d280ae747aa99d86549",
          "sha256": "0a7084ceadbdc4ce606be66215b2bef05f94597144163bba7932be08e9209df8",
          "sha1": "ada18d00bc6859cc7c88015415d8488679dfb07e",
          "md5": "0ad73ad8fae9f4f05350c6c924f1f838"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a58",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a58-android-0.1.3.aar",
          "url": "ble-characteristic-u2a58-android-0.1.3.aar",
          "size": 3006,
          "sha512": "c4bdd599f8741c4402bd3a9e2db2529d647b3fe30ca5a9f604bdc5e1c464e0a20c5d30b0cd9a2fd6436f11507e5ec4eb92e505b2a1da4d280ae747aa99d86549",
          "sha256": "0a7084ceadbdc4ce606be66215b2bef05f94597144163bba7932be08e9209df8",
          "sha1": "ada18d00bc6859cc7c88015415d8488679dfb07e",
          "md5": "0ad73ad8fae9f4f05350c6c924f1f838"
        }
      ]
    }
  ]
}
