{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1b",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.1.jar",
          "url": "ble-characteristic-u2b1b-0.8.1.jar",
          "size": 2070,
          "sha512": "5bbedb94e886e3072be775aa18c88cd2861c926bb154b40034c73fd2cbd606eb8fd9599b64ab8660f57ab566ab29128812551edb7afb76309ecdcde92b376f3a",
          "sha256": "93b21a5f40fc74514f91aaadb22ce31fd3dd06877ca509a41b6e8818cf4012af",
          "sha1": "ac9b14b52d3723545454bf829c25ebecfa1ee044",
          "md5": "0fcdb0bf39d2adb623f68844583e8a59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.1.jar",
          "url": "ble-characteristic-u2b1b-0.8.1.jar",
          "size": 2070,
          "sha512": "5bbedb94e886e3072be775aa18c88cd2861c926bb154b40034c73fd2cbd606eb8fd9599b64ab8660f57ab566ab29128812551edb7afb76309ecdcde92b376f3a",
          "sha256": "93b21a5f40fc74514f91aaadb22ce31fd3dd06877ca509a41b6e8818cf4012af",
          "sha1": "ac9b14b52d3723545454bf829c25ebecfa1ee044",
          "md5": "0fcdb0bf39d2adb623f68844583e8a59"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.1-javadoc.jar",
          "url": "ble-characteristic-u2b1b-0.8.1-javadoc.jar",
          "size": 111439,
          "sha512": "3db336fd9d9ab4002bf3de994736a0b1bcd9dbbbcc9a48ed9206d1b50cb898c337e2cc911b476d15c9c64ac790a856eae972de2ab64e06d98f5585f97ccc5322",
          "sha256": "de3aae36ed62566bbdbf08fa0c784ab24079656511ef6c7a70d9c6a3303dec46",
          "sha1": "6fc426db53e2fce5130fe2f03d942c22ade88381",
          "md5": "29fa9ccf4a0fbb9f746133b17b445256"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.1-sources.jar",
          "url": "ble-characteristic-u2b1b-0.8.1-sources.jar",
          "size": 1937,
          "sha512": "618d35e61ae41e11ecd22002040a6f243b70e1858461916af102b3733e9e9b6846de7c42f5fecf3bd5aa3b49b745024a896b6c421390a6cc44d74a572bc0aacf",
          "sha256": "2242e4cb528c52f46048df66f27fad794db7b715c6af79540b2a77a45585c2dc",
          "sha1": "5fa3b4e774a2ceed972614cbf97852f79f78debf",
          "md5": "c49878e12fdfe36d6bdc10ceba14937e"
        }
      ]
    }
  ]
}
