{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad7-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad7",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad7-android-0.8.6.aar",
          "url": "ble-characteristic-u2ad7-android-0.8.6.aar",
          "size": 3165,
          "sha512": "36ebc0dedbc2a5ed008603a7a89871d0e63506f57d3b7920928c6ba1eb9a4bdce81e26ab9a22741b4d36f9d49b63353ea8d82d2c2c5f90c4aaf2f7518bf1ded2",
          "sha256": "2dd4dbfb535bc724fdfc481891ef9ffbdbde1696fdea28cabfbebeacd3d0bc90",
          "sha1": "86e3c5d7f54ad41ed0889b948774d0be7d7a61c6",
          "md5": "929d7fa7fbab3392e0e941b28c7fd1bc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad7",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad7-android-0.8.6.aar",
          "url": "ble-characteristic-u2ad7-android-0.8.6.aar",
          "size": 3165,
          "sha512": "36ebc0dedbc2a5ed008603a7a89871d0e63506f57d3b7920928c6ba1eb9a4bdce81e26ab9a22741b4d36f9d49b63353ea8d82d2c2c5f90c4aaf2f7518bf1ded2",
          "sha256": "2dd4dbfb535bc724fdfc481891ef9ffbdbde1696fdea28cabfbebeacd3d0bc90",
          "sha1": "86e3c5d7f54ad41ed0889b948774d0be7d7a61c6",
          "md5": "929d7fa7fbab3392e0e941b28c7fd1bc"
        }
      ]
    }
  ]
}
