{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-wsp-peripheral-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "didsxcdw7raejas3g75ob27utq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-wsp-peripheral-android-0.1.3.aar",
          "url": "ble-profile-wsp-peripheral-android-0.1.3.aar",
          "size": 13692,
          "sha512": "fce39e24d3ddc36ee6626a46ddd27e65975d6f6ceead453ecacefbccbf2221267ba2200f8997c6e9217f7490b00e7b8671ec5ccf53b3bf3f3ed37de8a1683b1f",
          "sha256": "b342ae6ae83670fc2fb6cec47c836e1c41c3b3f35805dcf1100b2a82a962249b",
          "sha1": "5d31ee457ceb60b3d8ea455c86b950caec44bc94",
          "md5": "b60ba105fed09ee6a205f0aaff31adcf"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-wsp-peripheral-android-0.1.3.aar",
          "url": "ble-profile-wsp-peripheral-android-0.1.3.aar",
          "size": 13692,
          "sha512": "fce39e24d3ddc36ee6626a46ddd27e65975d6f6ceead453ecacefbccbf2221267ba2200f8997c6e9217f7490b00e7b8671ec5ccf53b3bf3f3ed37de8a1683b1f",
          "sha256": "b342ae6ae83670fc2fb6cec47c836e1c41c3b3f35805dcf1100b2a82a962249b",
          "sha1": "5d31ee457ceb60b3d8ea455c86b950caec44bc94",
          "md5": "b60ba105fed09ee6a205f0aaff31adcf"
        }
      ]
    }
  ]
}
