{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b7e",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7e-0.8.7.jar",
          "url": "ble-characteristic-u2b7e-0.8.7.jar",
          "size": 1464,
          "sha512": "9163e619fee78380284c4deb6b1199907de41f0f684d3ab7991abd47eb2a7ee66c665b94a05da5e8c4454e70c67a035bcb7800ce0ad7967097015f4d5af7cc70",
          "sha256": "035c90e1fae69c465101303d1206dc50b2d70ea34501a6831803026ba6c87027",
          "sha1": "4c1fdbb2456882b19319008f708ede1b48c12db8",
          "md5": "e1857099350de5ea45b59ea8070f3e92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7e-0.8.7.jar",
          "url": "ble-characteristic-u2b7e-0.8.7.jar",
          "size": 1464,
          "sha512": "9163e619fee78380284c4deb6b1199907de41f0f684d3ab7991abd47eb2a7ee66c665b94a05da5e8c4454e70c67a035bcb7800ce0ad7967097015f4d5af7cc70",
          "sha256": "035c90e1fae69c465101303d1206dc50b2d70ea34501a6831803026ba6c87027",
          "sha1": "4c1fdbb2456882b19319008f708ede1b48c12db8",
          "md5": "e1857099350de5ea45b59ea8070f3e92"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7e-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b7e-0.8.7-javadoc.jar",
          "size": 107185,
          "sha512": "4857a4dc3b99b15dcc99124eeec3623f45726e2c283879185665fb4db27df4fc835b44b52f177d50e3baa75897ec61efe08945452d08ad372841ad28e9e8d2d7",
          "sha256": "024e8a7e8ca532ddeef447e55403c00d4f84d48afd39b4846b6d9b144dcce64a",
          "sha1": "b10777cbac3ac6915f6620b32425751c6d0df3ed",
          "md5": "86c394b08f40693c2d4115c6c45bb067"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7e-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b7e-0.8.7-sources.jar",
          "size": 1448,
          "sha512": "f6534d5d11d428e5c22024458396700f315eecd78d7f6e308d48f2287dcbe009eae34891d5758d475e8857013dfa7d482347b937149ea9ff82679e5b239070fa",
          "sha256": "25fbdb6ade7a04da9cc027d9c47c495e97cfe20e683031da6d5eeffa2c483347",
          "sha1": "d201d6a938370f66b664ea08c8cb3dcc511ee463",
          "md5": "f7eb285eb61926f9cfb1edf47990c95f"
        }
      ]
    }
  ]
}
