{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-test-central",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-test",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-test-central-0.4.4.aar",
          "url": "ble-test-central-0.4.4.aar",
          "size": 4304,
          "sha512": "cf7b2bddd9050891ebf6aed5546b4745537a96dbf314472a2fd86d01cb96bd57147f54e1a382cb45ce854785e758ef250390c6c84288975379937e454b3dea41",
          "sha256": "dafabb475312a19189a795304b2bfa6a3c89f02d704bf0b0a69c812d516018e6",
          "sha1": "3c11620e2a74bfe017ab17911baea8cca6915071",
          "md5": "042c2c2fc09f59922a62d9fa23234e87"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-test",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-test-central-0.4.4.aar",
          "url": "ble-test-central-0.4.4.aar",
          "size": 4304,
          "sha512": "cf7b2bddd9050891ebf6aed5546b4745537a96dbf314472a2fd86d01cb96bd57147f54e1a382cb45ce854785e758ef250390c6c84288975379937e454b3dea41",
          "sha256": "dafabb475312a19189a795304b2bfa6a3c89f02d704bf0b0a69c812d516018e6",
          "sha1": "3c11620e2a74bfe017ab17911baea8cca6915071",
          "md5": "042c2c2fc09f59922a62d9fa23234e87"
        }
      ]
    }
  ]
}
