{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-lns-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-lns-android-0.8.10.aar",
          "url": "ble-service-peripheral-lns-android-0.8.10.aar",
          "size": 13285,
          "sha512": "faa2d60ec669c0ead30c336d51295415d670ad62fcbe7416b200d2f932388feffbf943336ccdfa2c932d1aff2b3ceaa44c0ed29426c7ccc62c45a288f6b5f064",
          "sha256": "b73aea71ca8355805ad1105892a7497ef7eec6001352cca4bf2fdd75a78439da",
          "sha1": "e502163c606d7e7dd08b3840d5292c35b01f4a27",
          "md5": "baa9e92d53494ac50117bf5bd36ee61c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-lns-android-0.8.10.aar",
          "url": "ble-service-peripheral-lns-android-0.8.10.aar",
          "size": 13285,
          "sha512": "faa2d60ec669c0ead30c336d51295415d670ad62fcbe7416b200d2f932388feffbf943336ccdfa2c932d1aff2b3ceaa44c0ed29426c7ccc62c45a288f6b5f064",
          "sha256": "b73aea71ca8355805ad1105892a7497ef7eec6001352cca4bf2fdd75a78439da",
          "sha1": "e502163c606d7e7dd08b3840d5292c35b01f4a27",
          "md5": "baa9e92d53494ac50117bf5bd36ee61c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-peripheral-lns-android-0.8.10-sources.jar",
          "url": "ble-service-peripheral-lns-android-0.8.10-sources.jar",
          "size": 8920,
          "sha512": "7af54a7e42b60a0c755a651a6c173efc281c71c85fab49cfcd3eacc6c42bf8d4e37cdc9d945617b52a85f19b823d077406dd06b19f83bf38910cdbbb2e4c8433",
          "sha256": "2677db15990840c9e02ef591db299ec0c704980499ea8c7f039a939355325649",
          "sha1": "e95f207107ffa72abfcf407f835039d5f352e0e4",
          "md5": "3613892fce7bc93f74713f1f75c76a03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-peripheral-lns-android-0.8.10-javadoc.jar",
          "url": "ble-service-peripheral-lns-android-0.8.10-javadoc.jar",
          "size": 302607,
          "sha512": "b4c0d8f2fbc6ac44a3b3e3576aead269b6bedd1d0ce75b7bf3fe1832fdf9bb5e87ca530481ebdfcdf4bafbdf6efb98a2b2123849472481b6f495d797e20e366a",
          "sha256": "8924b3d475cd8f0ca8aac1914ae40477692d763a34900de69b0240ac821cf432",
          "sha1": "4b3dda27944f9e28312f1563e521978f46f72c29",
          "md5": "339258893f06c89e8fb9011aaf884e80"
        }
      ]
    }
  ]
}
