{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9a",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "o6dnfu2lrvfy5pvyifi2ex2xay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9a-0.2.6.jar",
          "url": "ble-characteristic-u2a9a-0.2.6.jar",
          "size": 1712,
          "sha512": "1f8d100671af202c983646a8ac9ff321e284c6b879443c8bfa73163948a68f5a2165def3494ccf7dccf769626afe43a64ba147553c4fd5b550a7e3de56a18fb5",
          "sha256": "f0f03fd90d7a46f190a38073604347df2b6aac296987f382c560ab837a54bb33",
          "sha1": "af925911ad954ff2783ed67bac2710efc784424c",
          "md5": "fc6e31b798de8b562d5cdc6fa4aa9d86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9a-0.2.6.jar",
          "url": "ble-characteristic-u2a9a-0.2.6.jar",
          "size": 1712,
          "sha512": "1f8d100671af202c983646a8ac9ff321e284c6b879443c8bfa73163948a68f5a2165def3494ccf7dccf769626afe43a64ba147553c4fd5b550a7e3de56a18fb5",
          "sha256": "f0f03fd90d7a46f190a38073604347df2b6aac296987f382c560ab837a54bb33",
          "sha1": "af925911ad954ff2783ed67bac2710efc784424c",
          "md5": "fc6e31b798de8b562d5cdc6fa4aa9d86"
        }
      ]
    }
  ]
}
