{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a92-android",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.4.aar",
          "url": "ble-characteristic-u2a92-android-0.8.4.aar",
          "size": 3069,
          "sha512": "4948d879549208ec8669c15c86baf01ebda04a3557bd50ec14094ab865d186a80c66b172b91ead5b3037b1e7f4ae08dd13c1c3052eb1529dd731aea3a98d6247",
          "sha256": "d3b8f806c5a9ab97c269337e1de0aac56cfd83246287b7ae2412a75d44d75f71",
          "sha1": "b821d8c02e7e842d61284fa4b50467b8bb055637",
          "md5": "7b2ef7de778ad1fecc85119bef3c2374"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.4.aar",
          "url": "ble-characteristic-u2a92-android-0.8.4.aar",
          "size": 3069,
          "sha512": "4948d879549208ec8669c15c86baf01ebda04a3557bd50ec14094ab865d186a80c66b172b91ead5b3037b1e7f4ae08dd13c1c3052eb1529dd731aea3a98d6247",
          "sha256": "d3b8f806c5a9ab97c269337e1de0aac56cfd83246287b7ae2412a75d44d75f71",
          "sha1": "b821d8c02e7e842d61284fa4b50467b8bb055637",
          "md5": "7b2ef7de778ad1fecc85119bef3c2374"
        }
      ]
    }
  ]
}
