{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a07-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.8.6.aar",
          "url": "ble-characteristic-u2a07-android-0.8.6.aar",
          "size": 3087,
          "sha512": "b61d65abb4a53f569088099cfc30769bf1a28e4ba74232f64b7add248a9a4e0a23c196f5e2477d68c7cfbf04591736caaf6589c302f0209fa73f4dc29b480ccc",
          "sha256": "3bdfc1aaeeade8cf608b052ce83064aa9c002b9a8b57cd454aa45f9b761ec84f",
          "sha1": "bf37c02abea375bc9908ccb38a7a3f72f027d2fe",
          "md5": "ab60ed1c45d19e3bc33a6f3e004de3ab"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.8.6.aar",
          "url": "ble-characteristic-u2a07-android-0.8.6.aar",
          "size": 3087,
          "sha512": "b61d65abb4a53f569088099cfc30769bf1a28e4ba74232f64b7add248a9a4e0a23c196f5e2477d68c7cfbf04591736caaf6589c302f0209fa73f4dc29b480ccc",
          "sha256": "3bdfc1aaeeade8cf608b052ce83064aa9c002b9a8b57cd454aa45f9b761ec84f",
          "sha1": "bf37c02abea375bc9908ccb38a7a3f72f027d2fe",
          "md5": "ab60ed1c45d19e3bc33a6f3e004de3ab"
        }
      ]
    }
  ]
}
