{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-tps-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-tps-android-0.8.14.aar",
          "url": "ble-service-central-tps-android-0.8.14.aar",
          "size": 3318,
          "sha512": "7d91bb45ac7664ceec1b539e24e5d441ba43d8d13c38b7c2c10d750c1f2e17277ea292b39f49477b81a7c88267e9cc1f40987c57e5f9fb3bbb8ab9ecc2ebc77a",
          "sha256": "1347feeaa99263f142ea868ef39312b4f0ac9ce90466a5a261f8c0eb361c824a",
          "sha1": "62bbada6c4919d4fd8fb600387875863542b92c0",
          "md5": "52901394d66703183cfb69e0f78b2438"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-tps-android-0.8.14.aar",
          "url": "ble-service-central-tps-android-0.8.14.aar",
          "size": 3318,
          "sha512": "7d91bb45ac7664ceec1b539e24e5d441ba43d8d13c38b7c2c10d750c1f2e17277ea292b39f49477b81a7c88267e9cc1f40987c57e5f9fb3bbb8ab9ecc2ebc77a",
          "sha256": "1347feeaa99263f142ea868ef39312b4f0ac9ce90466a5a261f8c0eb361c824a",
          "sha1": "62bbada6c4919d4fd8fb600387875863542b92c0",
          "md5": "52901394d66703183cfb69e0f78b2438"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-tps-android-0.8.14-sources.jar",
          "url": "ble-service-central-tps-android-0.8.14-sources.jar",
          "size": 3450,
          "sha512": "addec1f99008cf99b88ecc6a72434386d3649774b32af0b16d096586cf8d55ff639f50f4e33561de11f0aca1dbda00abf432a321248bae51a997eba26f62c96f",
          "sha256": "5fe5e026f573b80a5cb1b5940d68bcefd87d97b74e969e1bbdfb2d8f48a2acc6",
          "sha1": "5d1e337844b552b2fbdb79b24ede8d0c85a74239",
          "md5": "a5dc7377d46571323d1ff375fa844d64"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-tps-android-0.8.14-javadoc.jar",
          "url": "ble-service-central-tps-android-0.8.14-javadoc.jar",
          "size": 277325,
          "sha512": "6ab9284ae91b22dffad62a66aebded7fe64bcd95183a0078dfa2facdc6d56fc84f43eb8c73f3ed0e09f3f489104272ae8c778ba759b5725d0a046cdf0be3e585",
          "sha256": "f30bd384a78fcfb6223c0af1c3bbd1a1381f92f24dcf4cc8e2190170a2aed2e9",
          "sha1": "e192b817f21eb3d7ebe8e39c1ebd2bc677d88627",
          "md5": "5286b23dd962b382249de751ed6c48a2"
        }
      ]
    }
  ]
}
