{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab0-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.2.9.aar",
          "url": "ble-characteristic-u2ab0-android-0.2.9.aar",
          "size": 3144,
          "sha512": "489405efd34cdf86dc9b32cb3f5a454210e1348a21efe85e7e5e053d05d8079f5a83e8e5ec05d7ee56b51e3cc1ef3c276c4abf05af30e75cdb0262fec056a422",
          "sha256": "1ebbf1c6ab579b04f791ff9ea86688eaffc6134b833c03052087115f47852bf0",
          "sha1": "94a01fa1c4ff5887eb5549efbc0e17e1affde2dc",
          "md5": "4a352e2304186afeccf4a31b5776e401"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.2.9.aar",
          "url": "ble-characteristic-u2ab0-android-0.2.9.aar",
          "size": 3144,
          "sha512": "489405efd34cdf86dc9b32cb3f5a454210e1348a21efe85e7e5e053d05d8079f5a83e8e5ec05d7ee56b51e3cc1ef3c276c4abf05af30e75cdb0262fec056a422",
          "sha256": "1ebbf1c6ab579b04f791ff9ea86688eaffc6134b833c03052087115f47852bf0",
          "sha1": "94a01fa1c4ff5887eb5549efbc0e17e1affde2dc",
          "md5": "4a352e2304186afeccf4a31b5776e401"
        }
      ]
    }
  ]
}
