{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b20-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b20",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b20-android-0.8.6.aar",
          "url": "ble-characteristic-u2b20-android-0.8.6.aar",
          "size": 3055,
          "sha512": "4ecd9167e9e7c08862afca672a62b917f9b14b927ead03403b677a96e08a0b7571a17682ac72ff560319df48168590f0657c028450628189664f987ad5e4428f",
          "sha256": "859ce3d62fbc074c2f63aa9b13de684f14ff03171747ed42fe5b3ee0d776be50",
          "sha1": "af28edc0f9a2898ee7e2f89e6909bb79e90e98cb",
          "md5": "9b5984317ce691ef534c9b7bed6ecfdd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b20",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b20-android-0.8.6.aar",
          "url": "ble-characteristic-u2b20-android-0.8.6.aar",
          "size": 3055,
          "sha512": "4ecd9167e9e7c08862afca672a62b917f9b14b927ead03403b677a96e08a0b7571a17682ac72ff560319df48168590f0657c028450628189664f987ad5e4428f",
          "sha256": "859ce3d62fbc074c2f63aa9b13de684f14ff03171747ed42fe5b3ee0d776be50",
          "sha1": "af28edc0f9a2898ee7e2f89e6909bb79e90e98cb",
          "md5": "9b5984317ce691ef534c9b7bed6ecfdd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b20-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b20-android-0.8.6-sources.jar",
          "size": 2154,
          "sha512": "47852a8dfc82f750b000d3b17972d4014e1a644504fa7ba690e2bb0ba9c7c63674d5d8e9e319f116ea7e5dd7dfedcff90177a48383c4cae5582cc570ae7559b1",
          "sha256": "53a7e06ef09a8766e031a69dfd70893b21b21bf4bf1a8de1249ad2d301d8551b",
          "sha1": "96f77ed245bac0c3cf77a7dfc01328590bb84ad9",
          "md5": "6e3e41ac4bf8b75b8af3835ad3db6bc9"
        }
      ]
    }
  ]
}
