{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8d-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8d-android-0.2.1.aar",
          "size": 2902,
          "sha512": "415edeb80d7fcc22228f3f6470e29faf72c55fa27cf3d526dee8dca50ca11c098c53a474e5295e91aa17e0682463cf15baa2524a773aae3b6580526d0d5c229c",
          "sha256": "bc3497d9d98fef809ee892fe18c63d796a69a3c3ad8a28437c6c2d385a7323f8",
          "sha1": "2fc97f8239bd4f04a4e363c0d6eda0b8d1461788",
          "md5": "167b99ca169ab1f93e59819a17a862c4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8d-android-0.2.1.aar",
          "size": 2902,
          "sha512": "415edeb80d7fcc22228f3f6470e29faf72c55fa27cf3d526dee8dca50ca11c098c53a474e5295e91aa17e0682463cf15baa2524a773aae3b6580526d0d5c229c",
          "sha256": "bc3497d9d98fef809ee892fe18c63d796a69a3c3ad8a28437c6c2d385a7323f8",
          "sha1": "2fc97f8239bd4f04a4e363c0d6eda0b8d1461788",
          "md5": "167b99ca169ab1f93e59819a17a862c4"
        }
      ]
    }
  ]
}
