{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab9",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.6.jar",
          "url": "ble-characteristic-u2ab9-0.8.6.jar",
          "size": 1585,
          "sha512": "04d03f418952db20c5aa963bc1cc4a3ec03ea2f54b72f2e3246642266b550282dd3797261cf74da823ca349ec70e153af2b8033bc41289e22746ff45ddb21eb0",
          "sha256": "cd01dbf1c2bb0463eea549c2353aec0323bb3ef2846b3ae04614172e9894085b",
          "sha1": "37ec64af286e28692eb8f0ba36fd29c17f81c96c",
          "md5": "b62c41ee51040ba8a4fbf9d44707d723"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.6.jar",
          "url": "ble-characteristic-u2ab9-0.8.6.jar",
          "size": 1585,
          "sha512": "04d03f418952db20c5aa963bc1cc4a3ec03ea2f54b72f2e3246642266b550282dd3797261cf74da823ca349ec70e153af2b8033bc41289e22746ff45ddb21eb0",
          "sha256": "cd01dbf1c2bb0463eea549c2353aec0323bb3ef2846b3ae04614172e9894085b",
          "sha1": "37ec64af286e28692eb8f0ba36fd29c17f81c96c",
          "md5": "b62c41ee51040ba8a4fbf9d44707d723"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2ab9-0.8.6-javadoc.jar",
          "size": 107428,
          "sha512": "68f37073c4d9d5eeaea779ad7807e3f0156761004b0703caedc3d9d2dc97f5b2ad659c5b24b182d671eca346df3eeb9a9bc4cffe423a26376919edc61283b5b8",
          "sha256": "693cf942046c3b6a1266e333b70ed356750dcdbd270d3a21211fdb7dce979a8b",
          "sha1": "0ad9b54e3807b53c1c4e552e5f354b51d4580000",
          "md5": "5c35fa34afdfff2e910464198971f9e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ab9-0.8.6-sources.jar",
          "size": 1505,
          "sha512": "d391156efd9cb6cf00371a380381c0644d11bc2f9d3a3195d52a3c995b66f10f8c710395ba06cf2cb5d3a4dca4093c7ed040b83164d8945626b2770e3ce05fb0",
          "sha256": "572d4950002ce2379918cbcc67c80e35ce81543fad375e33fd8ff66049e64c9a",
          "sha1": "181e10fa817fa1b4ed83376df167894a737bd75a",
          "md5": "f4718d6c7480a49325b202555ce715ad"
        }
      ]
    }
  ]
}
