{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aed",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aed-0.8.7.jar",
          "url": "ble-characteristic-u2aed-0.8.7.jar",
          "size": 1861,
          "sha512": "52dfa9eb8434ae490401ff209f683c940cb9aa63ad4ba727bc006d4ee1833bbe154c8f81e1730c1a7fe4a1a8dfe1ebd36e935d3d639fe786785ea70ca213cead",
          "sha256": "4f3a44edaa72076212c048184b80d9629acf7aa838b2b02b64c03165032c13b5",
          "sha1": "f2d57fb83340a995bd704f657e73d7aaf7e51bc0",
          "md5": "95e53b0140d37b60e65cf8fe595888e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aed-0.8.7.jar",
          "url": "ble-characteristic-u2aed-0.8.7.jar",
          "size": 1861,
          "sha512": "52dfa9eb8434ae490401ff209f683c940cb9aa63ad4ba727bc006d4ee1833bbe154c8f81e1730c1a7fe4a1a8dfe1ebd36e935d3d639fe786785ea70ca213cead",
          "sha256": "4f3a44edaa72076212c048184b80d9629acf7aa838b2b02b64c03165032c13b5",
          "sha1": "f2d57fb83340a995bd704f657e73d7aaf7e51bc0",
          "md5": "95e53b0140d37b60e65cf8fe595888e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aed-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2aed-0.8.7-javadoc.jar",
          "size": 109348,
          "sha512": "8ab7cf2592b9a4565b007624e036927e9983b550b901a18d7fb548a5c11719ae0b735f6cbb79123eafcc03446f7161a23ed8f2d2a3a8b3e454af7bce83df654a",
          "sha256": "54b806e6d601e26dc58a4a7605d8484eaeeeceafec5fd50bcac1762c49d44dd7",
          "sha1": "089f6bfed0b454e897d13653a40358f3e41500b7",
          "md5": "815313b88b2304f7cc29891fa582a40e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aed-0.8.7-sources.jar",
          "url": "ble-characteristic-u2aed-0.8.7-sources.jar",
          "size": 1713,
          "sha512": "8e824de551b1bed1b295cdae5a608729694005d92e78d49b4d7d89cc7bf83253d04c6b68c2e5ea50ca65580eb29d2674bd8e981a8d3f7c52fcae04a9c692d98f",
          "sha256": "8135f19e8c772f30be88d929bbe2af591d5667b23a686fcc05b8e00ec1d1eb58",
          "sha1": "58cd556eea2c267a8ef7386a16081ccf542f91ba",
          "md5": "585761f9eab39e460b0b56ee933319b7"
        }
      ]
    }
  ]
}
