{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-core",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2904",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-core-0.4.3.jar",
          "url": "ble-characteristic-core-0.4.3.jar",
          "size": 33391,
          "sha512": "588ec5da85bfc24181be5ab85207495a484ea13e2d0e9946bc2327366fc47d5413a651bd91e53052372461de16fb9fc3885951a8ce2f6310417e331c43422440",
          "sha256": "a5302f9c7f640b09ebf919efd3be1f3f5dc4da2f8816291650285b9a896dba60",
          "sha1": "be7bfe83552a2c48823f93a64789e55a8bb9a6c1",
          "md5": "0093805481d6a141bf9348c87fc98f3b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2904",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-core-0.4.3.jar",
          "url": "ble-characteristic-core-0.4.3.jar",
          "size": 33391,
          "sha512": "588ec5da85bfc24181be5ab85207495a484ea13e2d0e9946bc2327366fc47d5413a651bd91e53052372461de16fb9fc3885951a8ce2f6310417e331c43422440",
          "sha256": "a5302f9c7f640b09ebf919efd3be1f3f5dc4da2f8816291650285b9a896dba60",
          "sha1": "be7bfe83552a2c48823f93a64789e55a8bb9a6c1",
          "md5": "0093805481d6a141bf9348c87fc98f3b"
        }
      ]
    }
  ]
}
