{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a99-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a99",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a99-android-0.4.4.aar",
          "url": "ble-characteristic-u2a99-android-0.4.4.aar",
          "size": 3151,
          "sha512": "9679fd11adecbf8c4f93c8d8ff4347b8d8651536f2de3429f33133124442ac2270d418ce86ee25bf3f80d5fca0671d9fd59e91c194fd3b909e581ad95ba006dc",
          "sha256": "ecc3e9a29e7800f0e1d0b7141b03040776a360de852476e5352ed817f6c62ef6",
          "sha1": "52e7469a3e0c29c9a7054a3a022935a62462ee3f",
          "md5": "3ad0065dd53d62a0e9ac5b5b4ee7713f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a99",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a99-android-0.4.4.aar",
          "url": "ble-characteristic-u2a99-android-0.4.4.aar",
          "size": 3151,
          "sha512": "9679fd11adecbf8c4f93c8d8ff4347b8d8651536f2de3429f33133124442ac2270d418ce86ee25bf3f80d5fca0671d9fd59e91c194fd3b909e581ad95ba006dc",
          "sha256": "ecc3e9a29e7800f0e1d0b7141b03040776a360de852476e5352ed817f6c62ef6",
          "sha1": "52e7469a3e0c29c9a7054a3a022935a62462ee3f",
          "md5": "3ad0065dd53d62a0e9ac5b5b4ee7713f"
        }
      ]
    }
  ]
}
