{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7f-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smp7vu2g4jdlfelcafoemcahhe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.2.8.aar",
          "url": "ble-characteristic-u2a7f-android-0.2.8.aar",
          "size": 3093,
          "sha512": "86c3a1368e9866fcbc178430e7e8c670fce6b1c69e476d951a0d230ce1ec1303d13e480e1cd92d4b62118640110c3459dc31619fee03dae331f0dc739255896e",
          "sha256": "4b443b7b5896b1ff2c5d07f1e3fe8c3d9d9bba7e08218c3ac62c26f039a8aa9e",
          "sha1": "1bbddb3862ec3f380cd8c32aeaedbe013289a8b4",
          "md5": "9879163a2465f58d9b9599edb8aa753b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.2.8.aar",
          "url": "ble-characteristic-u2a7f-android-0.2.8.aar",
          "size": 3093,
          "sha512": "86c3a1368e9866fcbc178430e7e8c670fce6b1c69e476d951a0d230ce1ec1303d13e480e1cd92d4b62118640110c3459dc31619fee03dae331f0dc739255896e",
          "sha256": "4b443b7b5896b1ff2c5d07f1e3fe8c3d9d9bba7e08218c3ac62c26f039a8aa9e",
          "sha1": "1bbddb3862ec3f380cd8c32aeaedbe013289a8b4",
          "md5": "9879163a2465f58d9b9599edb8aa753b"
        }
      ]
    }
  ]
}
