{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bas-central-android",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bas-central-android-0.1.12.aar",
          "url": "ble-service-bas-central-android-0.1.12.aar",
          "size": 6794,
          "sha512": "44d7cbe85374011600799fb9e117030eae64b937b3d0b74b280bd0845b7fd9e4a00678ecb77e75efa9eb6a8c1fbe66577e080eb94ea6da604140c9ff04d226cb",
          "sha256": "778e8663137185c7c1f3ee041f2d293a3d67f2ba5c3f66402e9b1127d9e18d3d",
          "sha1": "6bc3d44d8a5a3c07f490a961113de1cac1825de8",
          "md5": "c4afbdbaf7f0c587430855f2edae972f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bas-central-android-0.1.12.aar",
          "url": "ble-service-bas-central-android-0.1.12.aar",
          "size": 6794,
          "sha512": "44d7cbe85374011600799fb9e117030eae64b937b3d0b74b280bd0845b7fd9e4a00678ecb77e75efa9eb6a8c1fbe66577e080eb94ea6da604140c9ff04d226cb",
          "sha256": "778e8663137185c7c1f3ee041f2d293a3d67f2ba5c3f66402e9b1127d9e18d3d",
          "sha1": "6bc3d44d8a5a3c07f490a961113de1cac1825de8",
          "md5": "c4afbdbaf7f0c587430855f2edae972f"
        }
      ]
    }
  ]
}
