{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad3-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad3-android-0.8.14.aar",
          "url": "ble-characteristic-u2ad3-android-0.8.14.aar",
          "size": 3192,
          "sha512": "992ea380c02d74c3e219732f4a1f1c2f40ce4f1a29d8d1372e0fd6c0345b4e6dbd070604c0a122364a6f5af1373770af96bd31a3af3c590c117f26d0a9ea15e8",
          "sha256": "36191b8bb8908265b93ff99584c6c72ebba7ea4cd58fcfd1fb8b953afe0efbb6",
          "sha1": "a13d6f9805eb76bc7d4cf001bcf01ee35d9879fa",
          "md5": "f59b4594cf7a1a8e413f37d68484b35c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad3-android-0.8.14.aar",
          "url": "ble-characteristic-u2ad3-android-0.8.14.aar",
          "size": 3192,
          "sha512": "992ea380c02d74c3e219732f4a1f1c2f40ce4f1a29d8d1372e0fd6c0345b4e6dbd070604c0a122364a6f5af1373770af96bd31a3af3c590c117f26d0a9ea15e8",
          "sha256": "36191b8bb8908265b93ff99584c6c72ebba7ea4cd58fcfd1fb8b953afe0efbb6",
          "sha1": "a13d6f9805eb76bc7d4cf001bcf01ee35d9879fa",
          "md5": "f59b4594cf7a1a8e413f37d68484b35c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad3-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2ad3-android-0.8.14-sources.jar",
          "size": 2236,
          "sha512": "1b5f6fa1ae3b5199237a6383de6f05adb0030981ea7c3ce55409282d651259a55cb837aca460d24ebd58531c7b69c3797a3c4167b40ce8af54dbaa905f752274",
          "sha256": "4dc7aa9085e8f59f0f30149daa7776d145ca26bfb6edbc5b1108ce520c547d7c",
          "sha1": "8ed93f7eb0093c736609c6f772858678bb08cc33",
          "md5": "ee2054e3df324376c798816382ce684c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad3-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2ad3-android-0.8.14-javadoc.jar",
          "size": 273407,
          "sha512": "ed201e304fbf3c371ba1b2af83f8310da20f0ba6d6b220ed92a41559fd966e8889ceafb24582d9f440a5b2a5e7e622cbc6e9a3c2b15c088b58b2da9028aa2fdc",
          "sha256": "ee1198342de4408d50f6755aca23b9c591fdf0148f1cb3552cfaceba0737f81b",
          "sha1": "51836933b376e3350937d6fd7cd207e92a7e03cf",
          "md5": "ead4d4281e481bc1da371e2516f0fa99"
        }
      ]
    }
  ]
}
