{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2908-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2908",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2908-android-0.2.4.aar",
          "url": "ble-descriptor-u2908-android-0.2.4.aar",
          "size": 3095,
          "sha512": "06d4102a27d100784c4f4f4883e40f770bba438c2aeb8a80dd37c461a0c8093d7b77ad412aad45fb1b53e4bf65d153b1692529866a43859a5e0d560fbaeca55f",
          "sha256": "2f6aa7287f68e8f479ada34fad3886268e2fee1b3442a37132153d993b766edd",
          "sha1": "0cf4fab1e3c43ca66ccb379fe03742d7c1505b24",
          "md5": "c630faf11454cc989a81a1220ee7f164"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2908",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2908-android-0.2.4.aar",
          "url": "ble-descriptor-u2908-android-0.2.4.aar",
          "size": 3095,
          "sha512": "06d4102a27d100784c4f4f4883e40f770bba438c2aeb8a80dd37c461a0c8093d7b77ad412aad45fb1b53e4bf65d153b1692529866a43859a5e0d560fbaeca55f",
          "sha256": "2f6aa7287f68e8f479ada34fad3886268e2fee1b3442a37132153d993b766edd",
          "sha1": "0cf4fab1e3c43ca66ccb379fe03742d7c1505b24",
          "md5": "c630faf11454cc989a81a1220ee7f164"
        }
      ]
    }
  ]
}
