{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290d",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "q4z4jr7cefarnmzk7t6opnz4hq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-0.2.5.jar",
          "url": "ble-descriptor-u290d-0.2.5.jar",
          "size": 2357,
          "sha512": "d2467ba2aa58b7f65a599b66f3ea77980f89dab47695bbc2ee6d89afc698f39f768dfc8665f7ce18ae5e43294028e7359575f24e57960e6ccafa9abe667521cb",
          "sha256": "43b48162c3ded41a12deb56aead370823155d254c515498986cd96f666d9d272",
          "sha1": "61be8c7b6f160743f009d47dfd5c9f6b0d3e2e9e",
          "md5": "4014498fe372b925a482e27d5cb9deed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-0.2.5.jar",
          "url": "ble-descriptor-u290d-0.2.5.jar",
          "size": 2357,
          "sha512": "d2467ba2aa58b7f65a599b66f3ea77980f89dab47695bbc2ee6d89afc698f39f768dfc8665f7ce18ae5e43294028e7359575f24e57960e6ccafa9abe667521cb",
          "sha256": "43b48162c3ded41a12deb56aead370823155d254c515498986cd96f666d9d272",
          "sha1": "61be8c7b6f160743f009d47dfd5c9f6b0d3e2e9e",
          "md5": "4014498fe372b925a482e27d5cb9deed"
        }
      ]
    }
  ]
}
