{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lns-peripheral-android",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "735raps6mncdtbga6dxzxb3udy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-peripheral-android-0.1.8.aar",
          "url": "ble-service-lns-peripheral-android-0.1.8.aar",
          "size": 11601,
          "sha512": "1c4c80dc001285f14f5dd1b9a4797fd1f85838e66108d850f6b5f37aa75487cc3ebf70dc8602aedc31e43f415215793d1377959c1d2f7d0af091c581cedeb07c",
          "sha256": "84f408266c53fc412411ac2a15a604caa10ecfa1dfb8650297e7b1a8d73943d4",
          "sha1": "243e496ce67e01cc1eafe6f8a34da4544cf6229b",
          "md5": "54fb292237ac38becd540805078f2fcb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-peripheral-android-0.1.8.aar",
          "url": "ble-service-lns-peripheral-android-0.1.8.aar",
          "size": 11601,
          "sha512": "1c4c80dc001285f14f5dd1b9a4797fd1f85838e66108d850f6b5f37aa75487cc3ebf70dc8602aedc31e43f415215793d1377959c1d2f7d0af091c581cedeb07c",
          "sha256": "84f408266c53fc412411ac2a15a604caa10ecfa1dfb8650297e7b1a8d73943d4",
          "sha1": "243e496ce67e01cc1eafe6f8a34da4544cf6229b",
          "md5": "54fb292237ac38becd540805078f2fcb"
        }
      ]
    }
  ]
}
