{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8c",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.7.jar",
          "url": "ble-characteristic-u2a8c-0.8.7.jar",
          "size": 1882,
          "sha512": "9c8a2f589d9c60be109f589272f7d9b903b393cee3bff44984404347e6bdd176591a191275925520afe22e88be4f5e5b4636379b05721623a5548c7a6e79d8a4",
          "sha256": "4ea6a889a0eb34166e03063106f1fb966f418593ac4bc8573717b3e14aac89b7",
          "sha1": "7415e9c4abb932b98a7a5f27e46bfcfa767457b7",
          "md5": "e07f78aca3979987813b8ab6c800b95a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.7.jar",
          "url": "ble-characteristic-u2a8c-0.8.7.jar",
          "size": 1882,
          "sha512": "9c8a2f589d9c60be109f589272f7d9b903b393cee3bff44984404347e6bdd176591a191275925520afe22e88be4f5e5b4636379b05721623a5548c7a6e79d8a4",
          "sha256": "4ea6a889a0eb34166e03063106f1fb966f418593ac4bc8573717b3e14aac89b7",
          "sha1": "7415e9c4abb932b98a7a5f27e46bfcfa767457b7",
          "md5": "e07f78aca3979987813b8ab6c800b95a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a8c-0.8.7-javadoc.jar",
          "size": 109597,
          "sha512": "a68204626f10ae7c286bd79a81fb94fbcd0f00cb71dfbe719b1e724389d8046c1aca4ddb39f24480c6a6ab3a94f73193630ac60f3d36659f73bc726282658b02",
          "sha256": "1d52c967d0688cae289c38c41135f8fc9687a614c1ca340356efdcca76f05a00",
          "sha1": "b9cd6d7709ee383e7a9756272284ce95a12798e2",
          "md5": "e81acfc9af77fb245f6a85abe6ef8b4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a8c-0.8.7-sources.jar",
          "size": 1715,
          "sha512": "7424448530e5944d56f68977e1a8b3f8ba6845a7343df5fe52507f6ad191f81595eba29873b96e4eb4ab4494cdcdd3a0b6dd34d0b94159da37f945f810e17843",
          "sha256": "4ee062dc5cf16f289ce0b2a9978cfe45b4ba203f5c23d0abcabccf7b48f7f377",
          "sha1": "732416de3073b05ccdab68d53395380df1f81277",
          "md5": "c847d6ff24f2dd32b040e1da7cb99d73"
        }
      ]
    }
  ]
}
