{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0a-android",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0a",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0a-android-0.8.1.aar",
          "url": "ble-characteristic-u2b0a-android-0.8.1.aar",
          "size": 3171,
          "sha512": "efa43e9a482c2268866aa4a58f9fc655c38e457ad8bf7c5ef5227fe00a92f35f925881f8abc9136a1bfdb8a58964fe8ebc32d1be0a5b5ff0a899c375dcffc4fb",
          "sha256": "737254e73cd1349c6fcdd3d3be4f0c60f7207dda8e6033bd708a2ffbb508bb20",
          "sha1": "c7c0f4008543d704b9fd047e10b10b76b202d5bf",
          "md5": "57d0789ead329268b71251c0ac0ccf9b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0a",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0a-android-0.8.1.aar",
          "url": "ble-characteristic-u2b0a-android-0.8.1.aar",
          "size": 3171,
          "sha512": "efa43e9a482c2268866aa4a58f9fc655c38e457ad8bf7c5ef5227fe00a92f35f925881f8abc9136a1bfdb8a58964fe8ebc32d1be0a5b5ff0a899c375dcffc4fb",
          "sha256": "737254e73cd1349c6fcdd3d3be4f0c60f7207dda8e6033bd708a2ffbb508bb20",
          "sha1": "c7c0f4008543d704b9fd047e10b10b76b202d5bf",
          "md5": "57d0789ead329268b71251c0ac0ccf9b"
        }
      ]
    }
  ]
}
