{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa2-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa2",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa2-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa2-android-0.8.6.aar",
          "size": 3068,
          "sha512": "bbf6772640afd29b7f1068dab1790172749b32d93678a65c697d9a5dbd7b152a38227613c37ca5f00897d91680dd9fb8d55da09f1207f7497d7f7c780df46e7b",
          "sha256": "cfe480e838e4bbfe245950f2867777dfc6a8bef88f2e6fd439309450aae4c4a5",
          "sha1": "829a0246552f68ba344554d1702aaf48091746a5",
          "md5": "e25255aa3f4436bcbf1c352c83937b42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa2",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa2-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa2-android-0.8.6.aar",
          "size": 3068,
          "sha512": "bbf6772640afd29b7f1068dab1790172749b32d93678a65c697d9a5dbd7b152a38227613c37ca5f00897d91680dd9fb8d55da09f1207f7497d7f7c780df46e7b",
          "sha256": "cfe480e838e4bbfe245950f2867777dfc6a8bef88f2e6fd439309450aae4c4a5",
          "sha1": "829a0246552f68ba344554d1702aaf48091746a5",
          "md5": "e25255aa3f4436bcbf1c352c83937b42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa2-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2aa2-android-0.8.6-sources.jar",
          "size": 2139,
          "sha512": "8e72683aecb124b28292cd2a429e2e7359230312d36a82eb26e5cace0d8c32a1c105abef7958249effa4b25664400ed7e742b3746507b2db032270c7be0bd438",
          "sha256": "4d9d7169a73cd7bbcd5b37d64639f5da0f5bd7948436f74971d68a8a6afe21b1",
          "sha1": "42444a4f5c193267da533c5f6283997bac86e5dd",
          "md5": "e2a3f5edbb0d1932bdd59d0f0a42fb4c"
        }
      ]
    }
  ]
}
