{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-wss-peripheral-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-peripheral-android-0.1.3.aar",
          "url": "ble-service-wss-peripheral-android-0.1.3.aar",
          "size": 4602,
          "sha512": "cce2d440be446a8f0e2081c14f76ed7a428ed9de03e6db371a17075a3387c547dd6d5971f2f3e16c7576d2d066b78f493db20c734aed0a45e2f952157997d50a",
          "sha256": "8513d1632003fe2e86e1c2cc519582ac63a03f00c99b9a2e0df5a84a17ce5b34",
          "sha1": "9ea1bf3afb251b72cf362f3f93fb8fc214828dea",
          "md5": "a6fd4c0499d08181dad30182fe3c3ab6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-peripheral-android-0.1.3.aar",
          "url": "ble-service-wss-peripheral-android-0.1.3.aar",
          "size": 4602,
          "sha512": "cce2d440be446a8f0e2081c14f76ed7a428ed9de03e6db371a17075a3387c547dd6d5971f2f3e16c7576d2d066b78f493db20c734aed0a45e2f952157997d50a",
          "sha256": "8513d1632003fe2e86e1c2cc519582ac63a03f00c99b9a2e0df5a84a17ce5b34",
          "sha1": "9ea1bf3afb251b72cf362f3f93fb8fc214828dea",
          "md5": "a6fd4c0499d08181dad30182fe3c3ab6"
        }
      ]
    }
  ]
}
