{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-dis-peripheral-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "qg6th4z35jb3vdxorhhy6cdiw4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-dis-peripheral-android-0.1.0.aar",
          "url": "ble-service-dis-peripheral-android-0.1.0.aar",
          "size": 5751,
          "sha512": "84a4af5b4a6617b8cffa420b070d15815024521f1d8936e9f5381bd1e01579e333fa39b1b06e4a0163b2aeced880ce0cfee0bb76cf67c5e81d6d700bd212c156",
          "sha256": "47b2fcd5b941ee8be561a5b9c4f0cd8a5e50e8c1cd80ba48c6301bf61d62a9f8",
          "sha1": "67182d9c3ce54d965d87691212b2c9aac88ff329",
          "md5": "8675f786c3e42129a82e44eb991ad36c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-dis-peripheral-android-0.1.0.aar",
          "url": "ble-service-dis-peripheral-android-0.1.0.aar",
          "size": 5751,
          "sha512": "84a4af5b4a6617b8cffa420b070d15815024521f1d8936e9f5381bd1e01579e333fa39b1b06e4a0163b2aeced880ce0cfee0bb76cf67c5e81d6d700bd212c156",
          "sha256": "47b2fcd5b941ee8be561a5b9c4f0cd8a5e50e8c1cd80ba48c6301bf61d62a9f8",
          "sha1": "67182d9c3ce54d965d87691212b2c9aac88ff329",
          "md5": "8675f786c3e42129a82e44eb991ad36c"
        }
      ]
    }
  ]
}
