{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa7",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa7-0.8.12.jar",
          "url": "ble-characteristic-u2aa7-0.8.12.jar",
          "size": 1453,
          "sha512": "ac344d13c94ceb45415c40892133e0327df7eb4c1c55e60535c67ac94975514053d20a289e2088e612032bdaf636133f422b97cdb9297ab8cec9c50291d0aeda",
          "sha256": "7e290e0f673781b083f9b613a0d494e6a88e30ca51fe32deca35cfea029c24f9",
          "sha1": "e58471fbdb7623a02e25860cee9ff48a70e424c4",
          "md5": "f1a377679c461a5aae80210e8492be4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa7-0.8.12.jar",
          "url": "ble-characteristic-u2aa7-0.8.12.jar",
          "size": 1453,
          "sha512": "ac344d13c94ceb45415c40892133e0327df7eb4c1c55e60535c67ac94975514053d20a289e2088e612032bdaf636133f422b97cdb9297ab8cec9c50291d0aeda",
          "sha256": "7e290e0f673781b083f9b613a0d494e6a88e30ca51fe32deca35cfea029c24f9",
          "sha1": "e58471fbdb7623a02e25860cee9ff48a70e424c4",
          "md5": "f1a377679c461a5aae80210e8492be4b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa7-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2aa7-0.8.12-javadoc.jar",
          "size": 107148,
          "sha512": "b3b7487c28a7fa615fc6924d814c2f7a7bccfaf66d54692451d285f7c52a9a8c395015503ff0632e29c534c5e03ac99bdee358ea12968cee95cb0f3af0698e56",
          "sha256": "637ba86c943a4e03bd24868aef96db17f5635e0ec3282bc43a436905b54f2bbf",
          "sha1": "17ab4434e172d0f6038807227d83b1222ab24b1e",
          "md5": "a957c2e3bdde1f598a48476389b3e932"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa7-0.8.12-sources.jar",
          "url": "ble-characteristic-u2aa7-0.8.12-sources.jar",
          "size": 1455,
          "sha512": "4212a857f3cc00e854a02ee1ab36eb4ebc623b21825d2ad4c3c2e70aee7ab3782a27f71d95fd310ab108416064b331b26c845b10816d7c1b3bf6d0597228aafa",
          "sha256": "bfe82e1ecdb91e00a566a820e39d9243132b891cefe937ed11c78ac99f53f67f",
          "sha1": "e5cc81c18609715d8cddfed753bc03d0703a25f3",
          "md5": "99bdaeac833669d27253b7c3c026c632"
        }
      ]
    }
  ]
}
