{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a72-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a72",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a72-android-0.2.8.aar",
          "url": "ble-characteristic-u2a72-android-0.2.8.aar",
          "size": 3099,
          "sha512": "c36ee59661356fa23f729256bce526b44be6930a6f912a1786af4d7c0108b795b7e847e7dc9b1382110db8d7811d1e21f9ff0a5495f299640d9ab94d23f3c622",
          "sha256": "4f8a9fdd99d168a23b3d41115629af3dd5c5a6ca6e76f65f6dc89006e83356b6",
          "sha1": "68615d7ddca3ac6dcb77c90574b8ff61779ed6ab",
          "md5": "0e90d1c23b27b2e8050032a0bc3e2c8d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a72",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a72-android-0.2.8.aar",
          "url": "ble-characteristic-u2a72-android-0.2.8.aar",
          "size": 3099,
          "sha512": "c36ee59661356fa23f729256bce526b44be6930a6f912a1786af4d7c0108b795b7e847e7dc9b1382110db8d7811d1e21f9ff0a5495f299640d9ab94d23f3c622",
          "sha256": "4f8a9fdd99d168a23b3d41115629af3dd5c5a6ca6e76f65f6dc89006e83356b6",
          "sha1": "68615d7ddca3ac6dcb77c90574b8ff61779ed6ab",
          "md5": "0e90d1c23b27b2e8050032a0bc3e2c8d"
        }
      ]
    }
  ]
}
