{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-blp-peripheral-android",
    "version": "0.1.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-blp-peripheral-android-0.1.17.aar",
          "url": "ble-profile-blp-peripheral-android-0.1.17.aar",
          "size": 4521,
          "sha512": "08a1339753bef40a0b245d995fe92c36a25b813983072ae93ce8cd8b62f042f146053ae3dd47b89ba7ece160eb71adb900a11ca19b143484e849cb228e3a8e3a",
          "sha256": "17f4015318a11c8d4268b2601fc576bc188ad35279662fee8911e081d79d7b9a",
          "sha1": "03fbc099f72c31355e0965f44a4741a52b7b53c5",
          "md5": "405e72e9ef6e2d029590ef97dcc7d763"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-blp-peripheral-android-0.1.17.aar",
          "url": "ble-profile-blp-peripheral-android-0.1.17.aar",
          "size": 4521,
          "sha512": "08a1339753bef40a0b245d995fe92c36a25b813983072ae93ce8cd8b62f042f146053ae3dd47b89ba7ece160eb71adb900a11ca19b143484e849cb228e3a8e3a",
          "sha256": "17f4015318a11c8d4268b2601fc576bc188ad35279662fee8911e081d79d7b9a",
          "sha1": "03fbc099f72c31355e0965f44a4741a52b7b53c5",
          "md5": "405e72e9ef6e2d029590ef97dcc7d763"
        }
      ]
    }
  ]
}
