{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290e",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290e-0.8.7.jar",
          "url": "ble-descriptor-u290e-0.8.7.jar",
          "size": 2577,
          "sha512": "2e2f48e89dc429bc3f980fca5f7d17f53e32c97136c8f6376725eebb6d5b08dd6b5b0b273be4d5bdc716cbdb94c2a4ba8e499fe3fe80b2f870a95d4ea256cf1f",
          "sha256": "52f017ea7c22dd5c2204d518fbad1a240dc2e7e0539ee776981b46ef8d138c5f",
          "sha1": "0a3a7d04509768578c4e42f1a272f26be7e12e36",
          "md5": "271c4f6fa2552d8b9962d305b10a1273"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290e-0.8.7.jar",
          "url": "ble-descriptor-u290e-0.8.7.jar",
          "size": 2577,
          "sha512": "2e2f48e89dc429bc3f980fca5f7d17f53e32c97136c8f6376725eebb6d5b08dd6b5b0b273be4d5bdc716cbdb94c2a4ba8e499fe3fe80b2f870a95d4ea256cf1f",
          "sha256": "52f017ea7c22dd5c2204d518fbad1a240dc2e7e0539ee776981b46ef8d138c5f",
          "sha1": "0a3a7d04509768578c4e42f1a272f26be7e12e36",
          "md5": "271c4f6fa2552d8b9962d305b10a1273"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290e-0.8.7-javadoc.jar",
          "url": "ble-descriptor-u290e-0.8.7-javadoc.jar",
          "size": 110762,
          "sha512": "487a0569dbdbf0d8c5617f8061d0b9c7bb7973ef7e17fa98c542c20f86de0ab2cc2bae8619ceda7520c5b4a22ef174ab085a3b1ce0c75f94a887c63ab80e9814",
          "sha256": "976cd54d9f04ca038effb5fb8af58cc9314f86f8d6498ce74976a54d0f902120",
          "sha1": "01575b6f6c50784bbc9285a34102bc7573efb1e9",
          "md5": "465a9614d85c8296e10a7acb021cc63d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290e-0.8.7-sources.jar",
          "url": "ble-descriptor-u290e-0.8.7-sources.jar",
          "size": 2335,
          "sha512": "edd3486ad201f2a462673c04f489abff2fb3899e7832905059df9287857d140c629ef296ce253017182b7c4ca0f1e46fe79d3e7488bafd1d678362d42821c0b4",
          "sha256": "1d70673dbd285d24580524c79a1804d3a65524173d5eac15ea5d64ecca4de914",
          "sha1": "1853d53020f684361f6ee756a18264e0c9bd9e5d",
          "md5": "a6e37f82e634d25f7bbf76cb3180eca6"
        }
      ]
    }
  ]
}
