{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-hts-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-hts-android-0.8.8.aar",
          "url": "ble-service-central-hts-android-0.8.8.aar",
          "size": 8227,
          "sha512": "117729db974cff285d9d2ac0ab2643d4489ea5f851f586964a90e407b20dbec475aa4e80884b2ea6d740f77c1e1b8fc00a0d4e12c4c8d0dbfa6746d1a64c0306",
          "sha256": "b4ca2f64bf736e2ad8f8a1dc8a9cd3af3189816fbb0da482573abf22cbecc50e",
          "sha1": "b60605fd8adb421f414915215a59ae40711df2c0",
          "md5": "9beb0ab912363bb7de3f0bf39434f342"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-hts-android-0.8.8.aar",
          "url": "ble-service-central-hts-android-0.8.8.aar",
          "size": 8227,
          "sha512": "117729db974cff285d9d2ac0ab2643d4489ea5f851f586964a90e407b20dbec475aa4e80884b2ea6d740f77c1e1b8fc00a0d4e12c4c8d0dbfa6746d1a64c0306",
          "sha256": "b4ca2f64bf736e2ad8f8a1dc8a9cd3af3189816fbb0da482573abf22cbecc50e",
          "sha1": "b60605fd8adb421f414915215a59ae40711df2c0",
          "md5": "9beb0ab912363bb7de3f0bf39434f342"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-hts-android-0.8.8-sources.jar",
          "url": "ble-service-central-hts-android-0.8.8-sources.jar",
          "size": 6967,
          "sha512": "255c1ff84d4b051fa658948e80c824d3fd72d3874e02e310b878194d3a5c1a825498108b3d0df752445c1c14c61882768aa240eba7e5770759a5a9e64a100ee0",
          "sha256": "a28e2a1e38f86755d7bf6e1c1f4998f459e258d96f5659c996c2fce7eb187c9a",
          "sha1": "c04571a2655accc3e8f8f4a69a392d0fe67d8df6",
          "md5": "7bb01a763ed062eed91de210656830d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-hts-android-0.8.8-javadoc.jar",
          "url": "ble-service-central-hts-android-0.8.8-javadoc.jar",
          "size": 289841,
          "sha512": "d5b45b8f5e5541e46eb328a444cb9efa60b7e4532742559dca39f0419c44172f083d1bac131ba22f8b426afe9a7369dce3374f883ba57dedd03835339c22f88c",
          "sha256": "f1a91e590bfa8a456c29fb8eeb13e2dd566aed531393fbc07cc57f5b8fc37f6e",
          "sha1": "ababd94109da963500e29adc3c5b6c4a242d7631",
          "md5": "e07e1e00cf903bab509971f1a8a77eb9"
        }
      ]
    }
  ]
}
