{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-android-0.4.3.aar",
          "url": "ble-characteristic-android-0.4.3.aar",
          "size": 1192,
          "sha512": "0604a8c47cd73307fe21ccbe0d8333b6743ea226f01f582a89ded4d27240551183a4cc679b84c2401972a163ab8ea39bd7afb6699791dbf3f1269d4af3c7f2fb",
          "sha256": "1865a668f8bface919020114e84f980b5f1c037c72e718ef7f36256bb80b7614",
          "sha1": "f7657916710bdf992bda9ead250b71de96dcf674",
          "md5": "718d405016635d0021d59f0d544e1b90"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-characteristic-android-0.4.3.aar",
          "url": "ble-characteristic-android-0.4.3.aar",
          "size": 1192,
          "sha512": "0604a8c47cd73307fe21ccbe0d8333b6743ea226f01f582a89ded4d27240551183a4cc679b84c2401972a163ab8ea39bd7afb6699791dbf3f1269d4af3c7f2fb",
          "sha256": "1865a668f8bface919020114e84f980b5f1c037c72e718ef7f36256bb80b7614",
          "sha1": "f7657916710bdf992bda9ead250b71de96dcf674",
          "md5": "718d405016635d0021d59f0d544e1b90"
        }
      ]
    }
  ]
}
