{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1c",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-0.8.6.jar",
          "url": "ble-characteristic-u2a1c-0.8.6.jar",
          "size": 3042,
          "sha512": "7774ecff5399bd179d3be65575d02c797f01aefbd2d0b6d04e074e7d1b9c33d8fb7c50b8c1a0e05228b8aa16e31e7ef15620ca9c49f060f1047103878eb06857",
          "sha256": "c4c13716283c26bddf04e02bc99f1623b7ecaf61fc5244603e3037b3d405c55a",
          "sha1": "52c0a4e0bd109c6d4e39fea9ba2fd83840a05895",
          "md5": "bbd47ae6ee40577e32722c29178ea663"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-0.8.6.jar",
          "url": "ble-characteristic-u2a1c-0.8.6.jar",
          "size": 3042,
          "sha512": "7774ecff5399bd179d3be65575d02c797f01aefbd2d0b6d04e074e7d1b9c33d8fb7c50b8c1a0e05228b8aa16e31e7ef15620ca9c49f060f1047103878eb06857",
          "sha256": "c4c13716283c26bddf04e02bc99f1623b7ecaf61fc5244603e3037b3d405c55a",
          "sha1": "52c0a4e0bd109c6d4e39fea9ba2fd83840a05895",
          "md5": "bbd47ae6ee40577e32722c29178ea663"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a1c-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a1c-0.8.6-javadoc.jar",
          "size": 108379,
          "sha512": "8bcd8e163712e67df04518814c57bbe552497d614d73e734bf01de42dea26f1954654c09db0deb51d66e678d2be3d0e899fd339f12927b456e7b0682c6cfebda",
          "sha256": "91f281f5b04fa0918a30ba517e20bda1778c873fbe6767062c9acc56bad79553",
          "sha1": "4221b491aebd1255b17e2aebeb718cf6fee55b30",
          "md5": "635414628ab727d2d37571d3956a0598"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a1c-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a1c-0.8.6-sources.jar",
          "size": 2521,
          "sha512": "646d38113e823822d84f659bc37d865975aab46a95a9fc81d88c9b5615d8c99534c5e4b29459536beaba988886cd19a0ce5fadf2948e88238cec85e2f15bc286",
          "sha256": "b8df22267f0246602fe3407e218dd96f5a7bb12e7e9a43ae84261aca4c4278e4",
          "sha1": "57cfbd10d142ed7cff440e20a7efabc06bf111bb",
          "md5": "85aeb44b9bad008855fddec051692df8"
        }
      ]
    }
  ]
}
