{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a99-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a99",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a99-android-0.4.1.aar",
          "url": "ble-characteristic-u2a99-android-0.4.1.aar",
          "size": 3151,
          "sha512": "9ab68ef4e999651a8fe4f0bbc0fec8f29fa7aaf433700bc0b23347c4f6e78a8ea941844363c5b45a1d9b44c31a2c0ff602fbf0b99dc984b057208d1e54a4d516",
          "sha256": "79334253cf127fc960999d6fc96e641d690fa639069b131f640ccc1f158a2496",
          "sha1": "90f9567cf24932f4b138c640cabf0b366b5a921e",
          "md5": "a5da9a2fe14db451bc47379e3e67c1ef"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a99",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a99-android-0.4.1.aar",
          "url": "ble-characteristic-u2a99-android-0.4.1.aar",
          "size": 3151,
          "sha512": "9ab68ef4e999651a8fe4f0bbc0fec8f29fa7aaf433700bc0b23347c4f6e78a8ea941844363c5b45a1d9b44c31a2c0ff602fbf0b99dc984b057208d1e54a4d516",
          "sha256": "79334253cf127fc960999d6fc96e641d690fa639069b131f640ccc1f158a2496",
          "sha1": "90f9567cf24932f4b138c640cabf0b366b5a921e",
          "md5": "a5da9a2fe14db451bc47379e3e67c1ef"
        }
      ]
    }
  ]
}
