{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a0d-android",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a0d",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0d-android-0.8.3.aar",
          "url": "ble-characteristic-u2a0d-android-0.8.3.aar",
          "size": 3047,
          "sha512": "47495057799bff6887a4111933e1c7acc65298fff2b698bcfde7992a73c96e81edbbb315b68dc8d7c16c555d1576072bd95ab07566a3ec8a74c30190177432a9",
          "sha256": "21af2844445925e3cd276f88c0c492495e88f023124fa52ba9cde445f56d7871",
          "sha1": "71b9b7b54e07c476c660d49fd91ded20891504a7",
          "md5": "5d8c3f99cbf39a5b4e43f3e3e2bd8080"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a0d",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0d-android-0.8.3.aar",
          "url": "ble-characteristic-u2a0d-android-0.8.3.aar",
          "size": 3047,
          "sha512": "47495057799bff6887a4111933e1c7acc65298fff2b698bcfde7992a73c96e81edbbb315b68dc8d7c16c555d1576072bd95ab07566a3ec8a74c30190177432a9",
          "sha256": "21af2844445925e3cd276f88c0c492495e88f023124fa52ba9cde445f56d7871",
          "sha1": "71b9b7b54e07c476c660d49fd91ded20891504a7",
          "md5": "5d8c3f99cbf39a5b4e43f3e3e2bd8080"
        }
      ]
    }
  ]
}
