{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc1",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc1-0.8.7.jar",
          "url": "ble-characteristic-u2bc1-0.8.7.jar",
          "size": 1447,
          "sha512": "cd8666fef96180365b60e471442a6a2b4e8cbe5f6fab1bdd5cca99f58b7993ebf28dfa58fa7b6fa013cc41bbc7dc2e2ce28d494513a374b910c76f04786de86e",
          "sha256": "def0c00baf787860ee00170975ef3a5df6aadc05ae1c1fba04b2220006d2c8c1",
          "sha1": "33acc45fc6dde45ccd57eb828d41849f71a9a835",
          "md5": "b101972c030b0c207869a574a36fb109"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc1-0.8.7.jar",
          "url": "ble-characteristic-u2bc1-0.8.7.jar",
          "size": 1447,
          "sha512": "cd8666fef96180365b60e471442a6a2b4e8cbe5f6fab1bdd5cca99f58b7993ebf28dfa58fa7b6fa013cc41bbc7dc2e2ce28d494513a374b910c76f04786de86e",
          "sha256": "def0c00baf787860ee00170975ef3a5df6aadc05ae1c1fba04b2220006d2c8c1",
          "sha1": "33acc45fc6dde45ccd57eb828d41849f71a9a835",
          "md5": "b101972c030b0c207869a574a36fb109"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc1-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bc1-0.8.7-javadoc.jar",
          "size": 107128,
          "sha512": "8fcd020d4bb8f296828893ebed4376e929699904ecbded162456551cd9fbef4043e850a7df6d48f06eff72444f91aecc01a4ac48914bb816c266424fae699833",
          "sha256": "c13db468bd9388f3ebb0ee5bc87131d7f17fa32583062c5b48dc5fe88c1d5131",
          "sha1": "38b944661b5114f52b86836fe697e9646a256b8b",
          "md5": "f5a4805c4b7c4019a99c14191df4fe2e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc1-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bc1-0.8.7-sources.jar",
          "size": 1440,
          "sha512": "7ed865e9c3d4df2202da12909b3bdd18887f919208018498d2efd620f8dca88e00aac5933858cefd02f4dc963fc698138aae02cba92ac012c746b14b1b6443f2",
          "sha256": "adbc3c34b7856756e184c2184bfb4ae9482669b62a55e44f6dc121902bb82d65",
          "sha1": "d0202ade087f06db5c665961f6a59a1b69ed728c",
          "md5": "cbc9862e2ff0730594d5e37d65516d78"
        }
      ]
    }
  ]
}
