{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bae-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bae",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bae-android-0.8.12.aar",
          "url": "ble-characteristic-u2bae-android-0.8.12.aar",
          "size": 3259,
          "sha512": "9e753a582dad075d1dd1557aa671e543f3f2809461304200997a327977fceb72fbb4fbb4cd26988cde5a5566a74a2d060adbfa451a20d93512d17b81ddd1489c",
          "sha256": "289ea44ff7930bcdef2fbf035f38c50513fe037ae305ef2b5c5230457f282cb7",
          "sha1": "e2bcf6ab55a05de7485074382fa85576f3084e57",
          "md5": "c0fcaa533ad6e36f57bb81e992f33233"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bae",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bae-android-0.8.12.aar",
          "url": "ble-characteristic-u2bae-android-0.8.12.aar",
          "size": 3259,
          "sha512": "9e753a582dad075d1dd1557aa671e543f3f2809461304200997a327977fceb72fbb4fbb4cd26988cde5a5566a74a2d060adbfa451a20d93512d17b81ddd1489c",
          "sha256": "289ea44ff7930bcdef2fbf035f38c50513fe037ae305ef2b5c5230457f282cb7",
          "sha1": "e2bcf6ab55a05de7485074382fa85576f3084e57",
          "md5": "c0fcaa533ad6e36f57bb81e992f33233"
        }
      ]
    }
  ]
}
