{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a98-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a98",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-android-0.2.6.aar",
          "url": "ble-characteristic-u2a98-android-0.2.6.aar",
          "size": 3058,
          "sha512": "f4c9b30bfd6f6461bf4575e6586f9ccf64c7d19f9800c84f1b88b35be89a0bff441e4e8cb86b2bd9419cdecd4e323706fc48b582d120cfdd65c36bf570d778bf",
          "sha256": "1c8620e9f83c1ba42f28b756285850326172b3baa9b510dd87bac7371b8be631",
          "sha1": "83030589a2a67ee5241fd5a0a073f9591893f341",
          "md5": "a280829518809ff71ed8802742aa26b1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a98",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-android-0.2.6.aar",
          "url": "ble-characteristic-u2a98-android-0.2.6.aar",
          "size": 3058,
          "sha512": "f4c9b30bfd6f6461bf4575e6586f9ccf64c7d19f9800c84f1b88b35be89a0bff441e4e8cb86b2bd9419cdecd4e323706fc48b582d120cfdd65c36bf570d778bf",
          "sha256": "1c8620e9f83c1ba42f28b756285850326172b3baa9b510dd87bac7371b8be631",
          "sha1": "83030589a2a67ee5241fd5a0a073f9591893f341",
          "md5": "a280829518809ff71ed8802742aa26b1"
        }
      ]
    }
  ]
}
