{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-scheme",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-scheme-0.8.0.jar",
          "url": "ble-core-constants-scheme-0.8.0.jar",
          "size": 9014,
          "sha512": "836269e428f95bd2b6e8d86b95cdcca8076405c3e2f83edd1da249fae476911e354197fb1541b535b875c3205483d804a5a2cc22674733f3c13ea3fc3bc3fd95",
          "sha256": "d6374cfd3c2fad0c2c7dc54baaf846ed8b0607afc24d56bb77cb29b4b6f9b659",
          "sha1": "6088d0567e38cd50b0052d6ec68d49bdbf788762",
          "md5": "2db0cac57159bac02ae07f9c30cb10d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-scheme-0.8.0.jar",
          "url": "ble-core-constants-scheme-0.8.0.jar",
          "size": 9014,
          "sha512": "836269e428f95bd2b6e8d86b95cdcca8076405c3e2f83edd1da249fae476911e354197fb1541b535b875c3205483d804a5a2cc22674733f3c13ea3fc3bc3fd95",
          "sha256": "d6374cfd3c2fad0c2c7dc54baaf846ed8b0607afc24d56bb77cb29b4b6f9b659",
          "sha1": "6088d0567e38cd50b0052d6ec68d49bdbf788762",
          "md5": "2db0cac57159bac02ae07f9c30cb10d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-scheme-0.8.0-javadoc.jar",
          "url": "ble-core-constants-scheme-0.8.0-javadoc.jar",
          "size": 122299,
          "sha512": "4be9445307deef7124c7e1896f2f961c7a7c5c6ceff32f37209f65a886adc4acc0fd9eed44d60acfdcff87b5fc11abab85c89b4bcf6898ecd7a91f2dd739c91b",
          "sha256": "bb37f4cf9e9685cb9163ab5cf554ec2c410f1c596cfe4d4d519176a27ad0411d",
          "sha1": "c2ebb4f586204dd6be80057ad96d09227a1bf684",
          "md5": "c048488c239a3244900871a2ee620131"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-scheme-0.8.0-sources.jar",
          "url": "ble-core-constants-scheme-0.8.0-sources.jar",
          "size": 5486,
          "sha512": "d2be98d8a378b15a32c8f16a53bd3337a12c8327d61002fbd9facfc12d8a3bfad11f9e46bad1b6e53a286d0b51ffe577e863f4c69c033c719214598961ef4e9d",
          "sha256": "01fbc834657a116f10734d97bed30db527b1f1bf9bd4f4520c14ffa3800b027e",
          "sha1": "8684a98441096179e8a02d57d5964d08528c93fe",
          "md5": "cee1f0a64730b26d5d16e123fcc4bfb7"
        }
      ]
    }
  ]
}
