{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a2a-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2a",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2a-android-0.8.12.aar",
          "url": "ble-characteristic-u2a2a-android-0.8.12.aar",
          "size": 3268,
          "sha512": "6980f96c615c96ffc3bbbc3c82ecc30e2b6ea32cd99bbacc44afb730ab23f9b9ce2c755ea768e218b641171c5507ae8c39f0eb2c8b7e9a61065645d59fe75147",
          "sha256": "3c32ccab3b352490b7fad3b3c8435c6d27e49a84f5f43a78c24b03ce29fc27a6",
          "sha1": "972aefb10a1d117e061f5672b311953f8edaaebb",
          "md5": "ae50f12b973990c695b6e95058a6f821"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2a",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2a-android-0.8.12.aar",
          "url": "ble-characteristic-u2a2a-android-0.8.12.aar",
          "size": 3268,
          "sha512": "6980f96c615c96ffc3bbbc3c82ecc30e2b6ea32cd99bbacc44afb730ab23f9b9ce2c755ea768e218b641171c5507ae8c39f0eb2c8b7e9a61065645d59fe75147",
          "sha256": "3c32ccab3b352490b7fad3b3c8435c6d27e49a84f5f43a78c24b03ce29fc27a6",
          "sha1": "972aefb10a1d117e061f5672b311953f8edaaebb",
          "md5": "ae50f12b973990c695b6e95058a6f821"
        }
      ]
    }
  ]
}
