{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-characteristic",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.1.jar",
          "url": "ble-core-constants-characteristic-0.8.1.jar",
          "size": 26425,
          "sha512": "b8bae75e435b26450ef9164129007b587da706e4f6caab415ba327ebd074d5ccbb7b3da4477b90e6dfff5fac152c0f8128a711e8da6125593b94785a15b542aa",
          "sha256": "f1e416365651b4e3a034f5a002d481e1719828fa6288c7ed7f264eab46dcd038",
          "sha1": "772e77746147e69d974ab578c31329d3dc0d78ac",
          "md5": "45c80900a9b679e43587bd2dcea7f218"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.1.jar",
          "url": "ble-core-constants-characteristic-0.8.1.jar",
          "size": 26425,
          "sha512": "b8bae75e435b26450ef9164129007b587da706e4f6caab415ba327ebd074d5ccbb7b3da4477b90e6dfff5fac152c0f8128a711e8da6125593b94785a15b542aa",
          "sha256": "f1e416365651b4e3a034f5a002d481e1719828fa6288c7ed7f264eab46dcd038",
          "sha1": "772e77746147e69d974ab578c31329d3dc0d78ac",
          "md5": "45c80900a9b679e43587bd2dcea7f218"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.1-javadoc.jar",
          "url": "ble-core-constants-characteristic-0.8.1-javadoc.jar",
          "size": 147847,
          "sha512": "2d5aa2df113c5bc54f03448cb91bbb3e54d87dff9d6de4394ebb8345f5e3c7f9b35a36809197806dfed7da2561f62aac951198d88e222f2aae7b630db757a522",
          "sha256": "9c4773b7db267a35d8d0893bf198a6b7705e452c749f2e17882a76ffc6914cc4",
          "sha1": "0f593345c438a4521f76084f4758aeb9356e09eb",
          "md5": "c4e694a80efc3a29d9735d83a93bca0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.1-sources.jar",
          "url": "ble-core-constants-characteristic-0.8.1-sources.jar",
          "size": 15688,
          "sha512": "55bb0b3a957814801a9556ebef8f4c5617beac63c8c0d59a5e3cc6ee550d9e4e3705a6b786ad3a0eb21badc4ae909d6461218b6eaae16e2070160f5f1054e1cd",
          "sha256": "8b3790d663ca5b5ada71261dc51f1e533c3368acb7a355e5c24e7508d99b4bdf",
          "sha1": "748ac1b70abacbc1a5bf8cb9d950be1ce6812438",
          "md5": "595a6a0746d2d947cdfac6ab1301cfd5"
        }
      ]
    }
  ]
}
