{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ftms-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgm5345lfvewjajsd7sfgyhu7u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ftms-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ftms-central-android-0.1.4.aar",
          "url": "ble-service-ftms-central-android-0.1.4.aar",
          "size": 13017,
          "sha512": "0689d80858f08bb74b0cb2bc79dc34baf7ab5656492e94f086e8f57974adcac1d2e07af0cefbddc24782ee7a8c398bb27eba7cc13d1778f1dc050acae51c4095",
          "sha256": "735e74dea3e2dbc0577c0923a427415e218ee31a947edd7826dae4177f70af2c",
          "sha1": "c0aceb4d3b3cdd07fbea8695847f1a0d344e43c6",
          "md5": "5bf8ff669e9271c7b6c71c7042478eb9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ftms-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ftms-central-android-0.1.4.aar",
          "url": "ble-service-ftms-central-android-0.1.4.aar",
          "size": 13017,
          "sha512": "0689d80858f08bb74b0cb2bc79dc34baf7ab5656492e94f086e8f57974adcac1d2e07af0cefbddc24782ee7a8c398bb27eba7cc13d1778f1dc050acae51c4095",
          "sha256": "735e74dea3e2dbc0577c0923a427415e218ee31a947edd7826dae4177f70af2c",
          "sha1": "c0aceb4d3b3cdd07fbea8695847f1a0d344e43c6",
          "md5": "5bf8ff669e9271c7b6c71c7042478eb9"
        }
      ]
    }
  ]
}
