{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b41",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b41-0.8.4.jar",
          "url": "ble-characteristic-u2b41-0.8.4.jar",
          "size": 1496,
          "sha512": "94dd59e4914f8f71b91f3c2a7019b2648e08755eea3f328a36aca182e5c56a22492f8ad9a71e201319bedff69952e9eccc4aedc546c7c9fe30f02efa85290a06",
          "sha256": "52f3fa095f32b7278090c4108438ac587316a6f8adf36a902f8f50616d6d2fa3",
          "sha1": "953bb0329e73ae562a51f32bdee0e6bea8fcc7ce",
          "md5": "b3517810b6c0a3d5d7fffc576f42665d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b41-0.8.4.jar",
          "url": "ble-characteristic-u2b41-0.8.4.jar",
          "size": 1496,
          "sha512": "94dd59e4914f8f71b91f3c2a7019b2648e08755eea3f328a36aca182e5c56a22492f8ad9a71e201319bedff69952e9eccc4aedc546c7c9fe30f02efa85290a06",
          "sha256": "52f3fa095f32b7278090c4108438ac587316a6f8adf36a902f8f50616d6d2fa3",
          "sha1": "953bb0329e73ae562a51f32bdee0e6bea8fcc7ce",
          "md5": "b3517810b6c0a3d5d7fffc576f42665d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b41-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2b41-0.8.4-javadoc.jar",
          "size": 110030,
          "sha512": "a7ee91412c0478b16da39bdd234ef18b9ff91b8d033ce62ac6e14a1d1cfab8509ebf6bd6e54bb8b7bffa504d9c2f15c06c74577a1a6ee630a2c17eae30abb9a7",
          "sha256": "3109442fe7c6073074c436d346c304de524811aef2dd040b33e2ae41a7a89751",
          "sha1": "eb0d0eb6cdfb25814ee642008fc2a7a86ab66d50",
          "md5": "f8888434bfb3c99eb9888d093eb3bbc2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b41-0.8.4-sources.jar",
          "url": "ble-characteristic-u2b41-0.8.4-sources.jar",
          "size": 1499,
          "sha512": "1b0dff749a4765fcb1b846c0990197cc1138f055188b51136c4b296c81708e3143bc7525893ab0fcaba0b95b6365eb3ef8f279ad93a6a8f88426a02f6f1d356a",
          "sha256": "640b28a465ebbfbfb0c322c5932d36023941682f09757903b2e84becb3764831",
          "sha1": "4781ae36dbff74d582c553b16d2ee96d4d026786",
          "md5": "26d784b670f2051c28267918539819e4"
        }
      ]
    }
  ]
}
