{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a00-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.2.4.aar",
          "url": "ble-characteristic-u2a00-android-0.2.4.aar",
          "size": 3083,
          "sha512": "15ef8e80a2bb57c7ee3ff9021d786d97d4acbacf44c61a972681c5b380b68552d35b659c68962985932e516d597e86fe5ef25215a4135777d28be9b07b1e3924",
          "sha256": "4ef2b7ae24516926a939d5d4c064ffce365287be7545231b183c8e6a59c9e1e7",
          "sha1": "cff6f500881976603d19ca0d4c1a2b042dd4397d",
          "md5": "1cbf5d8103b639b5f31b00e3a09c99a1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.2.4.aar",
          "url": "ble-characteristic-u2a00-android-0.2.4.aar",
          "size": 3083,
          "sha512": "15ef8e80a2bb57c7ee3ff9021d786d97d4acbacf44c61a972681c5b380b68552d35b659c68962985932e516d597e86fe5ef25215a4135777d28be9b07b1e3924",
          "sha256": "4ef2b7ae24516926a939d5d4c064ffce365287be7545231b183c8e6a59c9e1e7",
          "sha1": "cff6f500881976603d19ca0d4c1a2b042dd4397d",
          "md5": "1cbf5d8103b639b5f31b00e3a09c99a1"
        }
      ]
    }
  ]
}
