{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a00-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.2.4.aar",
          "url": "ble-characteristic-u2a00-android-0.2.4.aar",
          "size": 3082,
          "sha512": "23d2112fca09af10e6ac6c062c2a8b91f63dcb9ad20cb92a727dba19f077d60a33256d0b8d1a4d3928389bb089b7390bd01b180801f9f50ac23a21a6cabd4e0e",
          "sha256": "d460d6af5b520ced0f604bf8002278951be89497c198e369501741d662de337b",
          "sha1": "87d8229b7c4b15349e11b25914bc5f9fccd0045c",
          "md5": "76ad5e273a0225c418f513a12cd32021"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.2.4.aar",
          "url": "ble-characteristic-u2a00-android-0.2.4.aar",
          "size": 3082,
          "sha512": "23d2112fca09af10e6ac6c062c2a8b91f63dcb9ad20cb92a727dba19f077d60a33256d0b8d1a4d3928389bb089b7390bd01b180801f9f50ac23a21a6cabd4e0e",
          "sha256": "d460d6af5b520ced0f604bf8002278951be89497c198e369501741d662de337b",
          "sha1": "87d8229b7c4b15349e11b25914bc5f9fccd0045c",
          "md5": "76ad5e273a0225c418f513a12cd32021"
        }
      ]
    }
  ]
}
