{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a54",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-0.8.6.jar",
          "url": "ble-characteristic-u2a54-0.8.6.jar",
          "size": 2437,
          "sha512": "9a39c6dcf7d7165052dc5a5d7578b2d97f726798869dbcf20070cfd8b0f4b2605c2862c646b49a035297627e25aaff36deeb20b49f8c3ef0be253bfe9219a7c4",
          "sha256": "2cfdf6e43c281aa89f9eb63c27aac695f848df098b23f5bb9ba3974a5c04267a",
          "sha1": "109f2b7bea2f8e6b167bc1cbaac98a87905f5255",
          "md5": "0cc975be47107aa17c079c4c9a694e80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-0.8.6.jar",
          "url": "ble-characteristic-u2a54-0.8.6.jar",
          "size": 2437,
          "sha512": "9a39c6dcf7d7165052dc5a5d7578b2d97f726798869dbcf20070cfd8b0f4b2605c2862c646b49a035297627e25aaff36deeb20b49f8c3ef0be253bfe9219a7c4",
          "sha256": "2cfdf6e43c281aa89f9eb63c27aac695f848df098b23f5bb9ba3974a5c04267a",
          "sha1": "109f2b7bea2f8e6b167bc1cbaac98a87905f5255",
          "md5": "0cc975be47107aa17c079c4c9a694e80"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a54-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a54-0.8.6-javadoc.jar",
          "size": 111754,
          "sha512": "eab78dcf587871762624d0775ef3cfadc5e82add853fce38a2283853b5c55ccee52d60ae7672f7af4b57892f6853ed4f4762e3642c912117d8487de3ff9fd9e9",
          "sha256": "341442849282a7016454435751545d8bb5dfa717f21104887ffa0e8fcbf5cb28",
          "sha1": "0fa5f15822e53105378fe591496036315deaafb8",
          "md5": "c3d866108672729aa75a2197996a0bb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a54-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a54-0.8.6-sources.jar",
          "size": 2434,
          "sha512": "20b9c11b80abaa558a71d69d9f1108c9a7f533a249f953f8379b03cb10ee947f89d688fd9707eb5ff9893abb685fc74afda3988f101ee91e8d82898d716093bd",
          "sha256": "6fcdc677a609aa24b0d9df706fee7d377c5cd8d8dc47006165f77faaa7f2bc55",
          "sha1": "0bedca215e9ed3ac13d17f94f936868d1fde37e3",
          "md5": "1e6855f6714683dc530d9bf9faafe37e"
        }
      ]
    }
  ]
}
