{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba7",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.3.jar",
          "url": "ble-characteristic-u2ba7-0.8.3.jar",
          "size": 1464,
          "sha512": "8630836471056031154c093adea6d8cdeac96838ccc4367e68430000486fbccc0ff11abbcba6f4da7fc79bfc8ce9228f6bbb9fedf8a8aac89a619ff390ee0b9a",
          "sha256": "97764f36ea2323b4678cbe24c4b6eb3129bf88a26e437c5db1d614fbfb3afdc8",
          "sha1": "000db2ad8ccab1beaf56ff79a41d84ca2eeeb896",
          "md5": "b28b85b9278b5509c9b31b82fa745460"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.3.jar",
          "url": "ble-characteristic-u2ba7-0.8.3.jar",
          "size": 1464,
          "sha512": "8630836471056031154c093adea6d8cdeac96838ccc4367e68430000486fbccc0ff11abbcba6f4da7fc79bfc8ce9228f6bbb9fedf8a8aac89a619ff390ee0b9a",
          "sha256": "97764f36ea2323b4678cbe24c4b6eb3129bf88a26e437c5db1d614fbfb3afdc8",
          "sha1": "000db2ad8ccab1beaf56ff79a41d84ca2eeeb896",
          "md5": "b28b85b9278b5509c9b31b82fa745460"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2ba7-0.8.3-javadoc.jar",
          "size": 109892,
          "sha512": "e8a158b54c4e03c6cc90a842f5c4aaa247d5eef71c5056321ecf05392d596c95cca4510b242c2b067b9dc7740f339d81b263f6121b0cab94dc74377b6c1418eb",
          "sha256": "75402847acb5c116178d82dbc7800b9cb330f6c34d9266fdb6d4f8b1e8d94dd5",
          "sha1": "46edc0fa2a526363d85696e05eea569027e345c4",
          "md5": "92452281440d0c62b1ff207d4a61efb5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.3-sources.jar",
          "url": "ble-characteristic-u2ba7-0.8.3-sources.jar",
          "size": 1441,
          "sha512": "1c31de6b868e5516e5483ab2b2c0e49bc87945d989c509cf2b3b0e6bdc9270185222fff7f37e75cc703839d4d2be5ca23b43e021b39cb16d16ddd4a4ec60e0f5",
          "sha256": "71e540e24ebd238ba61f2b96e047d4da18c06a88168813721fd0d85a6b71a6a1",
          "sha1": "d61e1ac5c0a24ce28e6d5ecbeb3e5518cce6f9e1",
          "md5": "5925f4e56f6cabf924adcf5e66a96a37"
        }
      ]
    }
  ]
}
