{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa9-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa9",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa9-android-0.4.6.aar",
          "url": "ble-characteristic-u2aa9-android-0.4.6.aar",
          "size": 3035,
          "sha512": "33559e5ee389a12ac156fe22e11af1c7d6fe7ac47cc6a817f3f56240568866896977f84bff42b967f507f641e22cd6b3f3f23a8ab866b988c6d9823d8ea0ca10",
          "sha256": "60f5c80f7c81e6853cebc4d2e7a7cb00db6b713769be49aa7a70ff78fefafe42",
          "sha1": "a6a743c6c575e4c4643435c141bc75cc59c1355e",
          "md5": "96ebfff2132d5d2d607181d346b5ebfb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa9",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa9-android-0.4.6.aar",
          "url": "ble-characteristic-u2aa9-android-0.4.6.aar",
          "size": 3035,
          "sha512": "33559e5ee389a12ac156fe22e11af1c7d6fe7ac47cc6a817f3f56240568866896977f84bff42b967f507f641e22cd6b3f3f23a8ab866b988c6d9823d8ea0ca10",
          "sha256": "60f5c80f7c81e6853cebc4d2e7a7cb00db6b713769be49aa7a70ff78fefafe42",
          "sha1": "a6a743c6c575e4c4643435c141bc75cc59c1355e",
          "md5": "96ebfff2132d5d2d607181d346b5ebfb"
        }
      ]
    }
  ]
}
