{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a23-android",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a23",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a23-android-0.8.5.aar",
          "url": "ble-characteristic-u2a23-android-0.8.5.aar",
          "size": 3085,
          "sha512": "4841a0f8ac63fb54a361b35f22ce12b88dc911ffbe69f46856e9d8f01db5cf7409ada19a42a66505c16bf8140120c95f8e9ab3b3805cb85dbcc548980476f299",
          "sha256": "c1aff942a42824b23c0df7746a00dd99622f36143d6261d3590e25faf491a372",
          "sha1": "cc60d135dfd42cef368dbc7bcdf9f8a590753cf5",
          "md5": "4c4e2ce91b8d773d1c4a03ed59bd2513"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a23",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a23-android-0.8.5.aar",
          "url": "ble-characteristic-u2a23-android-0.8.5.aar",
          "size": 3085,
          "sha512": "4841a0f8ac63fb54a361b35f22ce12b88dc911ffbe69f46856e9d8f01db5cf7409ada19a42a66505c16bf8140120c95f8e9ab3b3805cb85dbcc548980476f299",
          "sha256": "c1aff942a42824b23c0df7746a00dd99622f36143d6261d3590e25faf491a372",
          "sha1": "cc60d135dfd42cef368dbc7bcdf9f8a590753cf5",
          "md5": "4c4e2ce91b8d773d1c4a03ed59bd2513"
        }
      ]
    }
  ]
}
