{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-esp-peripheral-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ess-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-esp-peripheral-android-0.1.1.aar",
          "url": "ble-profile-esp-peripheral-android-0.1.1.aar",
          "size": 14336,
          "sha512": "551b15372101e3004060c753a2e61eaddecc09b8a702e605d01cdd2d61169bad92e2b822af3a10ad24763ae3f6fb6f10077cc0dd4954460a43707bf8aad8175e",
          "sha256": "3991b3353bdc63c604b6cc759f497167b4788d7ce85cfc2bac24b4e250117916",
          "sha1": "e97c5e2994d1ebfbffe4dcad3843c02a0beb2646",
          "md5": "833880e0040175d83704fcf7b2e70349"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ess-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-esp-peripheral-android-0.1.1.aar",
          "url": "ble-profile-esp-peripheral-android-0.1.1.aar",
          "size": 14336,
          "sha512": "551b15372101e3004060c753a2e61eaddecc09b8a702e605d01cdd2d61169bad92e2b822af3a10ad24763ae3f6fb6f10077cc0dd4954460a43707bf8aad8175e",
          "sha256": "3991b3353bdc63c604b6cc759f497167b4788d7ce85cfc2bac24b4e250117916",
          "sha1": "e97c5e2994d1ebfbffe4dcad3843c02a0beb2646",
          "md5": "833880e0040175d83704fcf7b2e70349"
        }
      ]
    }
  ]
}
