{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4b-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4b",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4b-android-0.8.7.aar",
          "url": "ble-characteristic-u2b4b-android-0.8.7.aar",
          "size": 3205,
          "sha512": "d58d50027045d53d3a1600898ee1e3c3519d9407ba43357eb668ccf1493050f55ca18a975406b4cbac78b73a149143e63df96fae26258f038c441e43aabc1069",
          "sha256": "f0bbc0134c8c70abe2b9f474cc947f5a50c5bd2e9085cb0110754da0714f9fa0",
          "sha1": "dcca493cd06ceaf598425d385e08592b4bfe29c7",
          "md5": "d81b5ad680d4a0b2d9c35d6c59172482"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4b",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4b-android-0.8.7.aar",
          "url": "ble-characteristic-u2b4b-android-0.8.7.aar",
          "size": 3205,
          "sha512": "d58d50027045d53d3a1600898ee1e3c3519d9407ba43357eb668ccf1493050f55ca18a975406b4cbac78b73a149143e63df96fae26258f038c441e43aabc1069",
          "sha256": "f0bbc0134c8c70abe2b9f474cc947f5a50c5bd2e9085cb0110754da0714f9fa0",
          "sha1": "dcca493cd06ceaf598425d385e08592b4bfe29c7",
          "md5": "d81b5ad680d4a0b2d9c35d6c59172482"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4b-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b4b-android-0.8.7-sources.jar",
          "size": 2196,
          "sha512": "646ee801ef647c95b4986f9fad0e00a860a4f60fc17dbd161d00919a778a9d37c7e4f2910c805968dfb6a9c031de02d1f64eb6dbadf714b1cd5a232e1fc8d5db",
          "sha256": "0f25c28394bdc2f1759eca9f94bcf1d4de0b759db662a86da40aa71434aef25d",
          "sha1": "4748d88c42a8fb4ec4a1ebbeadd29a62b4604add",
          "md5": "68a03ee1f7d59f0ce94b8858086a6267"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4b-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b4b-android-0.8.7-javadoc.jar",
          "size": 271535,
          "sha512": "d527d42d983d62d48d3da9e1a95e894aa45f24a2fa6b719f2853fc283747328e7fbd3e71c5c2eeb3113160381e8161f6eebd7925a04c17cc9671417ddecfaf0f",
          "sha256": "268fe5a39d78b2750d40661a877996d78b422c44f62afa64af68c5570501dff2",
          "sha1": "09b3dd37816b0f71dbd76be05cdaaefb0ae24132",
          "md5": "dcadf6a6c080312012b857f61c6f00bb"
        }
      ]
    }
  ]
}
