{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-android-0.8.6.aar",
          "url": "ble-core-android-0.8.6.aar",
          "size": 1207,
          "sha512": "0964279e5c21a80241a56159dc16dd7db3753e3384ab132d17d72a05c5820e22d1f3d43f228962a3a32fb39533ce4c84b0c163c194d066f89bdf3d02ab41851c",
          "sha256": "cbe813df7d132408733c49ba2d41a8fe02e848aca02b1bb0196a7e8590eaec16",
          "sha1": "58a6a5cbfa5a9f4080170b47c91e393b45b10543",
          "md5": "51317caf3373d95cde467c0ab1252c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-android-0.8.6.aar",
          "url": "ble-core-android-0.8.6.aar",
          "size": 1207,
          "sha512": "0964279e5c21a80241a56159dc16dd7db3753e3384ab132d17d72a05c5820e22d1f3d43f228962a3a32fb39533ce4c84b0c163c194d066f89bdf3d02ab41851c",
          "sha256": "cbe813df7d132408733c49ba2d41a8fe02e848aca02b1bb0196a7e8590eaec16",
          "sha1": "58a6a5cbfa5a9f4080170b47c91e393b45b10543",
          "md5": "51317caf3373d95cde467c0ab1252c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-android-0.8.6-sources.jar",
          "url": "ble-core-android-0.8.6-sources.jar",
          "size": 1028,
          "sha512": "dbcd33941a19f3b10946637e262e37028e45518c54943b82ba8b357446d3585affc8275c43bd697db4d7a7f2430b10113287053468a7333ff2d7661f7bc894fc",
          "sha256": "10c0b572833479879d0a9e4a762e60ff65b67945fd80214655767265b5062546",
          "sha1": "2b4fa692c3a32e8b10b8a1ec0ed30d96e8497d79",
          "md5": "07cf7f656fd295fe59b43adad4189eec"
        }
      ]
    }
  ]
}
