{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1c-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-android-0.4.4.aar",
          "url": "ble-characteristic-u2a1c-android-0.4.4.aar",
          "size": 3445,
          "sha512": "b3624bc467aa39f414913b2c7248584190ad312b85abdd39e9d6870ca8fad46f1f963b0bbbdad8bc53c5a049dfc99eac190428abb8f1fe14c4c477314f135a5e",
          "sha256": "ec8c3fa2a86a0fa8121ba6f7df83b369c988d9cf838a042a708774ccabf4f9d5",
          "sha1": "cd105abac767ba6522d12bca56146267229c3dc0",
          "md5": "9800f8a51d79c0c7a91a2d7f37805587"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-android-0.4.4.aar",
          "url": "ble-characteristic-u2a1c-android-0.4.4.aar",
          "size": 3445,
          "sha512": "b3624bc467aa39f414913b2c7248584190ad312b85abdd39e9d6870ca8fad46f1f963b0bbbdad8bc53c5a049dfc99eac190428abb8f1fe14c4c477314f135a5e",
          "sha256": "ec8c3fa2a86a0fa8121ba6f7df83b369c988d9cf838a042a708774ccabf4f9d5",
          "sha1": "cd105abac767ba6522d12bca56146267229c3dc0",
          "md5": "9800f8a51d79c0c7a91a2d7f37805587"
        }
      ]
    }
  ]
}
