{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aee-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aee",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aee-android-0.4.4.aar",
          "url": "ble-characteristic-u2aee-android-0.4.4.aar",
          "size": 3100,
          "sha512": "c3fc2c9cb695288b173ad21655b8956175d72e5f56fba478a1d61bb9f26e6daa25170c8ef74da81fcd4b7d4d35f85d2675f22a5649ebe041350e2f37c2674dea",
          "sha256": "58a8566f58a18c75c38f3c0eb18fb50faa7d02173c3305cd186b43cee8604aac",
          "sha1": "0012d03e1b6b425c43cf434c0ce4668c19296645",
          "md5": "270e7b734a3ee0b4a229a120ad0ca206"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aee",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aee-android-0.4.4.aar",
          "url": "ble-characteristic-u2aee-android-0.4.4.aar",
          "size": 3100,
          "sha512": "c3fc2c9cb695288b173ad21655b8956175d72e5f56fba478a1d61bb9f26e6daa25170c8ef74da81fcd4b7d4d35f85d2675f22a5649ebe041350e2f37c2674dea",
          "sha256": "58a8566f58a18c75c38f3c0eb18fb50faa7d02173c3305cd186b43cee8604aac",
          "sha1": "0012d03e1b6b425c43cf434c0ce4668c19296645",
          "md5": "270e7b734a3ee0b4a229a120ad0ca206"
        }
      ]
    }
  ]
}
