{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-rtus-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-rtus-android-0.4.2.aar",
          "url": "ble-service-central-rtus-android-0.4.2.aar",
          "size": 3836,
          "sha512": "84231456b406daec358352ba602347e65578e093f6cc8fd133bc21d0ffb9fcc70b3b13ec42764f707f17f5254f16467eff75500f755d645025edb7f2e09386ce",
          "sha256": "2d767735fd57df877215d84e3f3060be1d2e697b82915a69aee0ac9bd7e71854",
          "sha1": "4f7233da60aa7540c448bb32764d5d67db5eda6a",
          "md5": "a19f0092d7bbc6f888551b0de27a9c43"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-rtus-android-0.4.2.aar",
          "url": "ble-service-central-rtus-android-0.4.2.aar",
          "size": 3836,
          "sha512": "84231456b406daec358352ba602347e65578e093f6cc8fd133bc21d0ffb9fcc70b3b13ec42764f707f17f5254f16467eff75500f755d645025edb7f2e09386ce",
          "sha256": "2d767735fd57df877215d84e3f3060be1d2e697b82915a69aee0ac9bd7e71854",
          "sha1": "4f7233da60aa7540c448bb32764d5d67db5eda6a",
          "md5": "a19f0092d7bbc6f888551b0de27a9c43"
        }
      ]
    }
  ]
}
