{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8c-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-android-0.4.6.aar",
          "url": "ble-characteristic-u2a8c-android-0.4.6.aar",
          "size": 3070,
          "sha512": "fc9b4fc8e0c083b004eff841b0d44f24a845aaf380ee3fd2537c9dd0d63dae984e7306662627058fce5878ed1fe3e5a6f2b8c2de3be2eb3f1e8dad215f8e2c44",
          "sha256": "b44d796b7e542d37bf2ae518688f34405bb937356c5077fdf91322d99da77881",
          "sha1": "3779ded4d19ab9b073f186352401527ed311b6c6",
          "md5": "f1e5b596b50faa1b547dd304c412e504"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-android-0.4.6.aar",
          "url": "ble-characteristic-u2a8c-android-0.4.6.aar",
          "size": 3070,
          "sha512": "fc9b4fc8e0c083b004eff841b0d44f24a845aaf380ee3fd2537c9dd0d63dae984e7306662627058fce5878ed1fe3e5a6f2b8c2de3be2eb3f1e8dad215f8e2c44",
          "sha256": "b44d796b7e542d37bf2ae518688f34405bb937356c5077fdf91322d99da77881",
          "sha1": "3779ded4d19ab9b073f186352401527ed311b6c6",
          "md5": "f1e5b596b50faa1b547dd304c412e504"
        }
      ]
    }
  ]
}
