{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2903",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2903-0.8.6.jar",
          "url": "ble-descriptor-u2903-0.8.6.jar",
          "size": 1902,
          "sha512": "b97ee700f5b59ed423ca2a0833017611df9305ad6eebb2366f17ce3d70fac1b5e62fe61c033b6c335bfe916495afede1187e15a76036dcfb39cb43caf7d8be96",
          "sha256": "9ccd7210d11f1921f6d28d607e6f51e803a54fb226c6950bd42891825456a209",
          "sha1": "dc6f6946cb3a9e3b247a5016034b8fd9781a5a28",
          "md5": "19e4bc1aa08cb83123d358cb6415e2d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2903-0.8.6.jar",
          "url": "ble-descriptor-u2903-0.8.6.jar",
          "size": 1902,
          "sha512": "b97ee700f5b59ed423ca2a0833017611df9305ad6eebb2366f17ce3d70fac1b5e62fe61c033b6c335bfe916495afede1187e15a76036dcfb39cb43caf7d8be96",
          "sha256": "9ccd7210d11f1921f6d28d607e6f51e803a54fb226c6950bd42891825456a209",
          "sha1": "dc6f6946cb3a9e3b247a5016034b8fd9781a5a28",
          "md5": "19e4bc1aa08cb83123d358cb6415e2d8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2903-0.8.6-javadoc.jar",
          "url": "ble-descriptor-u2903-0.8.6-javadoc.jar",
          "size": 109638,
          "sha512": "ad4b645e1754160f09848a31c521215589fdfd111f0cf6cd737a778b1fca7620d4ca8fc4afa18b99dbb62cef83b99e65561771aea856f92b8218e6c69ee97d64",
          "sha256": "ee7330d9ae39fa046e90e510251e2898bac1f9dd59c02a5d8cad2e5b8334d783",
          "sha1": "d8c124df8338b8a0285f006c4835ea5d3c16e0b3",
          "md5": "a9322d77482454bf67a4e455880775ce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2903-0.8.6-sources.jar",
          "url": "ble-descriptor-u2903-0.8.6-sources.jar",
          "size": 1760,
          "sha512": "d0208e94d935eb891ff62973b72808549bbc1e6b7dc080e987093e5118d6477731bc4247a7352c2e2102093d22d95d3d7d774f1c818660841da5b2712d131cac",
          "sha256": "e7844cb3fa1424638b06d971e1efd6a468633645b51118d06805dd65447cd052",
          "sha1": "0ad9401c96d2d6b3364106391881bc496f34f7f3",
          "md5": "8cdd692dc22fbf7838faf8d762e32110"
        }
      ]
    }
  ]
}
