{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0c",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.12.jar",
          "url": "ble-characteristic-u2b0c-0.8.12.jar",
          "size": 1948,
          "sha512": "4870c8fc111d7b1607c64afe3e43cb30bf201cbc5dc3cae8ebfb39642de519230ec66537822b9420769e3f5f07a433bb147b444cef398f8bee89c791fdf98a93",
          "sha256": "8be0e330a8889de1eae6afe36aeac7176bf739710881c88dc59ec77b7fc60126",
          "sha1": "7b6f6a7d227777ce13a2f0f9f2f2a696aaaa32cf",
          "md5": "1b0179ffcc2045df02e7e1289b47b249"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.12.jar",
          "url": "ble-characteristic-u2b0c-0.8.12.jar",
          "size": 1948,
          "sha512": "4870c8fc111d7b1607c64afe3e43cb30bf201cbc5dc3cae8ebfb39642de519230ec66537822b9420769e3f5f07a433bb147b444cef398f8bee89c791fdf98a93",
          "sha256": "8be0e330a8889de1eae6afe36aeac7176bf739710881c88dc59ec77b7fc60126",
          "sha1": "7b6f6a7d227777ce13a2f0f9f2f2a696aaaa32cf",
          "md5": "1b0179ffcc2045df02e7e1289b47b249"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b0c-0.8.12-javadoc.jar",
          "size": 107744,
          "sha512": "0b9007df7352bcba874cb64920a1ff24f13db97dc4232832eebd1d353d34312cfe74bb31fb73e4036ab16f94034fde6956eefcca82a87c95be69333c968bc75e",
          "sha256": "6386e7c921b6df07d2ee626cd30eaf400c76fd8f90e4cff4ec2c721198a1f08a",
          "sha1": "115aa06cca25aac7f76b057841257f486c700993",
          "md5": "9a3ad00a612edb65c121d6130ccf85f7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b0c-0.8.12-sources.jar",
          "size": 1780,
          "sha512": "ef2d93c643d24bc1845c9e0a04f21ea252e38ef6ffa4a540b0ca9520094d494742503efe0607cf9ba3a2afdf4a1654b565dd62fef7c987f1a00cc9d564718f0c",
          "sha256": "88dd680dcc6e7f74b7f7ed3bd1dbf6f0bef698547b3ac76a95ad5759572fbce7",
          "sha1": "b6be18700397a0596656c9fa36a1c8f23b4e9b4b",
          "md5": "3d3cfe75c58575d655d8051519047e37"
        }
      ]
    }
  ]
}
