{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad3-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zckqgxv52jertg33sctsfjorzm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad3-android-0.2.2.aar",
          "url": "ble-characteristic-u2ad3-android-0.2.2.aar",
          "size": 2965,
          "sha512": "2d1490c5689a2ff88c479e260a64943b1c1112e4f980ca282add7466482733cc986f07d5569760d583d8ab3ffd4535b282353a85c656a7f7c1f31e4be9775a5a",
          "sha256": "d0ab2bd32b18a260a8493aa7c726d234af74f712008f163e535d4efd7691bf42",
          "sha1": "ffc0e8991a3bc1ca3e7f77590cbb2e1517c19e88",
          "md5": "d8ebcfc403ccb1bc6e61fe847270667f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad3-android-0.2.2.aar",
          "url": "ble-characteristic-u2ad3-android-0.2.2.aar",
          "size": 2965,
          "sha512": "2d1490c5689a2ff88c479e260a64943b1c1112e4f980ca282add7466482733cc986f07d5569760d583d8ab3ffd4535b282353a85c656a7f7c1f31e4be9775a5a",
          "sha256": "d0ab2bd32b18a260a8493aa7c726d234af74f712008f163e535d4efd7691bf42",
          "sha1": "ffc0e8991a3bc1ca3e7f77590cbb2e1517c19e88",
          "md5": "d8ebcfc403ccb1bc6e61fe847270667f"
        }
      ]
    }
  ]
}
