{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab4-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.4.0.aar",
          "url": "ble-characteristic-u2ab4-android-0.4.0.aar",
          "size": 3092,
          "sha512": "a4acf983da459790b37e8acbfcd6478a7c53e17b8139f5a198de9df762a476bf7c94e916d19924db0b4509d2243056ff8a1ef831869fa52d0406c0b3c9462e24",
          "sha256": "2c150bff5052f676bfc4ee284c534f3d94cb37f2f1077f371f8a635b7238b215",
          "sha1": "68ba26c25d4bec36b68d133939a6ef3847da91c4",
          "md5": "54d9770f06c7723f36f8dd09446b6100"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.4.0.aar",
          "url": "ble-characteristic-u2ab4-android-0.4.0.aar",
          "size": 3092,
          "sha512": "a4acf983da459790b37e8acbfcd6478a7c53e17b8139f5a198de9df762a476bf7c94e916d19924db0b4509d2243056ff8a1ef831869fa52d0406c0b3c9462e24",
          "sha256": "2c150bff5052f676bfc4ee284c534f3d94cb37f2f1077f371f8a635b7238b215",
          "sha1": "68ba26c25d4bec36b68d133939a6ef3847da91c4",
          "md5": "54d9770f06c7723f36f8dd09446b6100"
        }
      ]
    }
  ]
}
