{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afe-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afe",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afe-android-0.4.1.aar",
          "url": "ble-characteristic-u2afe-android-0.4.1.aar",
          "size": 3068,
          "sha512": "1120eed75ba4083ef1407df8c0ec5e856fd463e990a6f3d5a6fc96be20995772b76d82e41dc49d75a0b8da35715201cda828d6d99af483a98c476939fc8cc0eb",
          "sha256": "81ff2a58fdc25ed6cf8d17a23ed70a4712eb7beeac02c72d6b521fc8376c571f",
          "sha1": "6f7a06d5d103e944e6e714026776c9b80fdd54ef",
          "md5": "9288c087cf333b4198bd1dbbe6db42a3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afe",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afe-android-0.4.1.aar",
          "url": "ble-characteristic-u2afe-android-0.4.1.aar",
          "size": 3068,
          "sha512": "1120eed75ba4083ef1407df8c0ec5e856fd463e990a6f3d5a6fc96be20995772b76d82e41dc49d75a0b8da35715201cda828d6d99af483a98c476939fc8cc0eb",
          "sha256": "81ff2a58fdc25ed6cf8d17a23ed70a4712eb7beeac02c72d6b521fc8376c571f",
          "sha1": "6f7a06d5d103e944e6e714026776c9b80fdd54ef",
          "md5": "9288c087cf333b4198bd1dbbe6db42a3"
        }
      ]
    }
  ]
}
