{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3b",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3b-0.8.6.jar",
          "url": "ble-characteristic-u2b3b-0.8.6.jar",
          "size": 1501,
          "sha512": "a6cb1416bc4ad6cdc2d85f601331271d6f38ecac4ea9432dcfe40fef62b7f34e0a95d382a2f91e54d9c05fb99ae44497cbdf914fd8372360dd2dab3c3790677a",
          "sha256": "6c3ff1352d4136613c1c521549e469461a8c974753e1868984e146b32e1c7f01",
          "sha1": "89584885ad853c97f5b97d179d43e79398e500c6",
          "md5": "71a4c610618bdfbe2ef38a4781372f17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3b-0.8.6.jar",
          "url": "ble-characteristic-u2b3b-0.8.6.jar",
          "size": 1501,
          "sha512": "a6cb1416bc4ad6cdc2d85f601331271d6f38ecac4ea9432dcfe40fef62b7f34e0a95d382a2f91e54d9c05fb99ae44497cbdf914fd8372360dd2dab3c3790677a",
          "sha256": "6c3ff1352d4136613c1c521549e469461a8c974753e1868984e146b32e1c7f01",
          "sha1": "89584885ad853c97f5b97d179d43e79398e500c6",
          "md5": "71a4c610618bdfbe2ef38a4781372f17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3b-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2b3b-0.8.6-javadoc.jar",
          "size": 107323,
          "sha512": "a3e33db1e5466fc71420254b0f77a643a85578fbf1d68b77891a0f5cf82b852ce4cc2d7c82580bd41c305fc9e946d32cbdaa822bac14a27d8d0f8b07d28530f0",
          "sha256": "1d1bc4938db1d2478081b9da0458cd6698da6c96bb0085a8c19f6474d63d7dbe",
          "sha1": "e5216ea589a7e49ee71951aa20ecbfb6807c7da1",
          "md5": "35c3ed3952f82ed02c35927e27e17ada"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3b-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b3b-0.8.6-sources.jar",
          "size": 1489,
          "sha512": "8252fc36d0b25742d30fcc8d7e0bc15a23a923e6b76c3c86aa6e7ce7e964d4fbf923e25edb9daf323cdf71350d28820da70b21a1e2c174039898f320299bc168",
          "sha256": "c952f0f582ac8a82f7216b5aa193f8a437cbc4d01fc16ccebe3186b1ab824eda",
          "sha1": "32eb1971a386ee7d4b49078df6d359bc9bcb8e0f",
          "md5": "6eb765f11043b2d769100980e5e9f24f"
        }
      ]
    }
  ]
}
