{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a63",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6exsxox6gvho3e4ayov5pi6vnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a63-0.2.6.jar",
          "url": "ble-characteristic-u2a63-0.2.6.jar",
          "size": 5202,
          "sha512": "86bf1367ceb05ade368aa67121a4dd6b0e5702910960e6b2603b5284c73d2da8ef894714adb95d68b54788eb3a0d8ee4605df3048b55cda9df7c4f72ef67199c",
          "sha256": "8c0776186ee71314c6ae3f291fed8bfc41e21ee35f4528e305a4f08d0511c8a3",
          "sha1": "a8f88ea22eec356835c3e47028fc97fbe9f5ca1f",
          "md5": "4bb4c564442a4c7c8a2ec546c747527b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a63-0.2.6.jar",
          "url": "ble-characteristic-u2a63-0.2.6.jar",
          "size": 5202,
          "sha512": "86bf1367ceb05ade368aa67121a4dd6b0e5702910960e6b2603b5284c73d2da8ef894714adb95d68b54788eb3a0d8ee4605df3048b55cda9df7c4f72ef67199c",
          "sha256": "8c0776186ee71314c6ae3f291fed8bfc41e21ee35f4528e305a4f08d0511c8a3",
          "sha1": "a8f88ea22eec356835c3e47028fc97fbe9f5ca1f",
          "md5": "4bb4c564442a4c7c8a2ec546c747527b"
        }
      ]
    }
  ]
}
