{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-pasp-peripheral-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pasp-peripheral-android-0.1.5.aar",
          "url": "ble-profile-pasp-peripheral-android-0.1.5.aar",
          "size": 3640,
          "sha512": "f4eeb89e5edae74fbb6dc21fcf9ebf208b5b1703b35a6f6b783461f411307d87a27fb20a15473c08e3ebb32dcd0f36742ca980e96279ed8c64ad3d24ef021d2c",
          "sha256": "0146c2ac3a46a24f5b16af5a438a594878c7a049ac4e011c2fefa1ecd571531d",
          "sha1": "9a2d12f3c96a9e9d8136f19d093c8c911843a04a",
          "md5": "3aad1cebe8be2474339abe3d1d3dd328"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pasp-peripheral-android-0.1.5.aar",
          "url": "ble-profile-pasp-peripheral-android-0.1.5.aar",
          "size": 3640,
          "sha512": "f4eeb89e5edae74fbb6dc21fcf9ebf208b5b1703b35a6f6b783461f411307d87a27fb20a15473c08e3ebb32dcd0f36742ca980e96279ed8c64ad3d24ef021d2c",
          "sha256": "0146c2ac3a46a24f5b16af5a438a594878c7a049ac4e011c2fefa1ecd571531d",
          "sha1": "9a2d12f3c96a9e9d8136f19d093c8c911843a04a",
          "md5": "3aad1cebe8be2474339abe3d1d3dd328"
        }
      ]
    }
  ]
}
