{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7b",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7b-0.8.6.jar",
          "url": "ble-characteristic-u2a7b-0.8.6.jar",
          "size": 1745,
          "sha512": "e4673599b876b29a21ddaf1065a7fe6a3c707ba601df72c7643dc88505a5d59c9feb39eb0af930f2a03771cf041f1bf5b26107b935da2c203bd4207204906ff5",
          "sha256": "a58e1d9d02d9e9b4dc17729a3bed02115f7c6ab298fed481ddda6eb36d5b8262",
          "sha1": "f564ec6235152cac9102ee8977e8f760f27d0556",
          "md5": "6ce73b708cc2aa73e6ee9debe4503612"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7b-0.8.6.jar",
          "url": "ble-characteristic-u2a7b-0.8.6.jar",
          "size": 1745,
          "sha512": "e4673599b876b29a21ddaf1065a7fe6a3c707ba601df72c7643dc88505a5d59c9feb39eb0af930f2a03771cf041f1bf5b26107b935da2c203bd4207204906ff5",
          "sha256": "a58e1d9d02d9e9b4dc17729a3bed02115f7c6ab298fed481ddda6eb36d5b8262",
          "sha1": "f564ec6235152cac9102ee8977e8f760f27d0556",
          "md5": "6ce73b708cc2aa73e6ee9debe4503612"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7b-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a7b-0.8.6-javadoc.jar",
          "size": 107296,
          "sha512": "1f0860a283803c9d30d29b66150151ab54d68784cae30a3d4264f6da3b5cd0dc5891922a45864c2f3332e98ab15f49db74b8240811fa5ce8f590f647f7b559a8",
          "sha256": "c3deecaf9c7b11af9883378376bef533af8aa5e096af03ae0e338082ac8e556a",
          "sha1": "2d911a80678d15b5359c1ba56485f90c4c3e25bc",
          "md5": "dd5c51919667739b473f894333ba2aee"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7b-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a7b-0.8.6-sources.jar",
          "size": 1585,
          "sha512": "5acc3501e35e90d2e3c9f4eca4d6be872e2d94f0193e0d2c89401cee6ed83d6145efe1769877932e6b35323d75c52a86813dfc1e25800a91bde498a82ff345a2",
          "sha256": "0058c57ab6ab15d515f91a0a2bd9709948075ef6cd404093f6f49ae419edc9fb",
          "sha1": "7521e18e24cec1f310398b8ca903dcd761ab3da3",
          "md5": "dd1f85da8db48342f59ac3005deba9e1"
        }
      ]
    }
  ]
}
