{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1a",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1a-0.8.1.jar",
          "url": "ble-characteristic-u2b1a-0.8.1.jar",
          "size": 2090,
          "sha512": "8bd4c6780fdb1f6d271ab149d152f33a34a7140cc6ebbd6f2946f3a5bea66a5a2454c9e5d9c560e5ce43139ae09ba57b4e3696bdf85c0b7e6f0eb8ae46b39ee8",
          "sha256": "4bc160569d1c88b0503af1a6cfd91e0343f12b4a4e259e115a173a4d976ce721",
          "sha1": "624367c65aa7ab24c371ee3dee76d15bec74cbdc",
          "md5": "6330f7c491f4d15fb39f0708284f78c9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1a-0.8.1.jar",
          "url": "ble-characteristic-u2b1a-0.8.1.jar",
          "size": 2090,
          "sha512": "8bd4c6780fdb1f6d271ab149d152f33a34a7140cc6ebbd6f2946f3a5bea66a5a2454c9e5d9c560e5ce43139ae09ba57b4e3696bdf85c0b7e6f0eb8ae46b39ee8",
          "sha256": "4bc160569d1c88b0503af1a6cfd91e0343f12b4a4e259e115a173a4d976ce721",
          "sha1": "624367c65aa7ab24c371ee3dee76d15bec74cbdc",
          "md5": "6330f7c491f4d15fb39f0708284f78c9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1a-0.8.1-javadoc.jar",
          "url": "ble-characteristic-u2b1a-0.8.1-javadoc.jar",
          "size": 110489,
          "sha512": "e368bba0cd692f63aca2c55cadf06ce7f9792df528fc0b1613508c769d273dfdfafa5cbcfed04bdb71a4a3ca98ae9b2a176f4a06ccefd2179a41942adfe75a36",
          "sha256": "b6fa13bb216ef501d26ce6564674cd0f7c2a8a7ec55fde3d0c034853c0fc2796",
          "sha1": "a258d80afd292daf78902177b97cf1fff9aa5c72",
          "md5": "f6709e19e119af2b4ac9021cf2c22890"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1a-0.8.1-sources.jar",
          "url": "ble-characteristic-u2b1a-0.8.1-sources.jar",
          "size": 1878,
          "sha512": "e57ad9eae7bb9d86659f33a54e4c67c24a177651518d7a99787b6bcbebebd8cb2e97b8e23fd920ff1a2badf6156a687807a61748b271d4e7e7a845dc98c293f5",
          "sha256": "743a7e5abb1ed519e780a0096e6d22f643bfbd7899a2eaafae145d08051c079d",
          "sha1": "95ec613c69e2282585838cf267083f6a5812da9e",
          "md5": "ab301f63b2fee100004b1cf16cc8bcba"
        }
      ]
    }
  ]
}
