{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2baf",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.4.jar",
          "url": "ble-characteristic-u2baf-0.8.4.jar",
          "size": 1558,
          "sha512": "b70ae91fd38895015d6756da252c4ca3eada77947cff5d98e3554f179a8e4e62ad6d7caeea203a4d59f14b9332d33d2391fe1898255c81a9af7fa1a9a014a6bc",
          "sha256": "ddc6f2cc59b5388fb2186dc2648a25824d58567b5a9eb7037939e4c7e65f71e5",
          "sha1": "2310fe85dda09f99c678b24c58232e99e962c0cd",
          "md5": "a74fb2f52ebe48294329bfba765eb4a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.4.jar",
          "url": "ble-characteristic-u2baf-0.8.4.jar",
          "size": 1558,
          "sha512": "b70ae91fd38895015d6756da252c4ca3eada77947cff5d98e3554f179a8e4e62ad6d7caeea203a4d59f14b9332d33d2391fe1898255c81a9af7fa1a9a014a6bc",
          "sha256": "ddc6f2cc59b5388fb2186dc2648a25824d58567b5a9eb7037939e4c7e65f71e5",
          "sha1": "2310fe85dda09f99c678b24c58232e99e962c0cd",
          "md5": "a74fb2f52ebe48294329bfba765eb4a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2baf-0.8.4-javadoc.jar",
          "size": 110235,
          "sha512": "ba3468770b5b057534e7338871d51e6d491f3f6377edd0a7331d7666fc9a4d5b249ade6d512024f83acc99ed2179911db511a334a92cd13187652fae097af5b8",
          "sha256": "54e75ffaa07bf4ae03c1392deb1457c93d1e92df7bc2e0e225541cc0dc950023",
          "sha1": "31bea59f05b8b69237e12591e4b96d789d953337",
          "md5": "655174f5c5433988d086e60ceeba177a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.4-sources.jar",
          "url": "ble-characteristic-u2baf-0.8.4-sources.jar",
          "size": 1553,
          "sha512": "b1aaf24a7178ec12401677c621ecab7ce5f28c55686a71c9fef733e0698fbd2e1e46cd9a3e309f178abbd443212ecca6f293f8310b4dbd77a63422a02354d16a",
          "sha256": "2a3cdb18935f0f9dd6de3c339de14f8a40f0b13800a51819fd833f9af0876b4f",
          "sha1": "06823067c88f8bed8f64b22d68ccfa28b23a24d2",
          "md5": "e11eb61c88f1fbf6c3e1c5e4d25ef512"
        }
      ]
    }
  ]
}
