{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8c",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.14.jar",
          "url": "ble-characteristic-u2a8c-0.8.14.jar",
          "size": 1882,
          "sha512": "46df3e955cb2bb7a9624118e23554b973e76f34ff9e14220a580fb8bbf8a5ca3da12be4a26812ed8aed7b26fe563b45f38f9a940d8b9ea41e57a2219d937ed19",
          "sha256": "a1eb3758d401efdd19f65fd7c53268f18868d9206e5c28fe119a19ac42940911",
          "sha1": "a90a4e57c70ec0d9aee29a4dec88619641c93f75",
          "md5": "f2dc8b6dfa28e4724d2471e3631ccfd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.14.jar",
          "url": "ble-characteristic-u2a8c-0.8.14.jar",
          "size": 1882,
          "sha512": "46df3e955cb2bb7a9624118e23554b973e76f34ff9e14220a580fb8bbf8a5ca3da12be4a26812ed8aed7b26fe563b45f38f9a940d8b9ea41e57a2219d937ed19",
          "sha256": "a1eb3758d401efdd19f65fd7c53268f18868d9206e5c28fe119a19ac42940911",
          "sha1": "a90a4e57c70ec0d9aee29a4dec88619641c93f75",
          "md5": "f2dc8b6dfa28e4724d2471e3631ccfd6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2a8c-0.8.14-javadoc.jar",
          "size": 88528,
          "sha512": "10de4f2200dd2faaf023814a561b11345ee911a37d1b7633e8829d95494c81b74fe8ed45d807a5ae8b435159f94010d6eb43a3bdee1cdf487a51a87aa8c10aab",
          "sha256": "2473d00452ff8faf022f4c2f9f97f929f2a4944b0738a18fa0adaccebeda36de",
          "sha1": "af737fd88a3203a93704d217d972eb5ab61116d2",
          "md5": "d43cfba20ff0a0749f91d0920728d547"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a8c-0.8.14-sources.jar",
          "url": "ble-characteristic-u2a8c-0.8.14-sources.jar",
          "size": 1715,
          "sha512": "1ee79fd609240cc402faa594da98f7dcdd203c0965fe7b4c23ba8caa2035272328a6a69cc1318ae1ecdd2aa4e5615b972503fc28e5466155f8509db263124242",
          "sha256": "0436017c7e732fa36b658b4e95b7d0ba30f7f3db1465887c6d89d23ed683577d",
          "sha1": "382be7d7f090f983a6041b1349662dced8e98f57",
          "md5": "ca7d50735144dde09c5eb8493ad41962"
        }
      ]
    }
  ]
}
