{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3f-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3f",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-android-0.8.6.aar",
          "url": "ble-characteristic-u2b3f-android-0.8.6.aar",
          "size": 3138,
          "sha512": "9017895d8c97bce1ce15393c83a003d789de6da8f9a633175965d0b75b400641ecc1746d0016594a9f9e10c418b5d3e9339ea858ae69d07ef8b2fe1495baa33b",
          "sha256": "187c7ab0775ebacc59089d69f7df809375bcbe2b207ee617644cdd9f125351a1",
          "sha1": "30a297d60730a062a79e3953183b9600a21e9651",
          "md5": "572d48996bc00858bf68701810115675"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3f",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-android-0.8.6.aar",
          "url": "ble-characteristic-u2b3f-android-0.8.6.aar",
          "size": 3138,
          "sha512": "9017895d8c97bce1ce15393c83a003d789de6da8f9a633175965d0b75b400641ecc1746d0016594a9f9e10c418b5d3e9339ea858ae69d07ef8b2fe1495baa33b",
          "sha256": "187c7ab0775ebacc59089d69f7df809375bcbe2b207ee617644cdd9f125351a1",
          "sha1": "30a297d60730a062a79e3953183b9600a21e9651",
          "md5": "572d48996bc00858bf68701810115675"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3f-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b3f-android-0.8.6-sources.jar",
          "size": 2237,
          "sha512": "269dc260798a81f4cd22afb32f56d10762161a11115d6c953dcf789694bf60fb86e1398ce3e49b44a7362aebd3ee08d432c898bedb2a9e3c0a8000a05efdec8e",
          "sha256": "3402e7b3e0e6d00e97c013311c2eedf54e3359450e77ed99f0b163cfaa11b590",
          "sha1": "7257a9005b9e39092a3f593cea13df95d2c32b5f",
          "md5": "f0837c99095c5dd7159069628efdabb3"
        }
      ]
    }
  ]
}
