{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a92-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.6.aar",
          "url": "ble-characteristic-u2a92-android-0.8.6.aar",
          "size": 3089,
          "sha512": "5e044a6322d998bbe177e0446e2b8b211a326e78a460ed793e9a1255bd1986ec7da774ef9e8d73333e0500447f2948ee5aa93660838a49738f203f43a8246cf2",
          "sha256": "d9b4235753a45093782c13c7706cf10aabb8c3b95736c73a0f39f803f35b359a",
          "sha1": "c16aa49b45ec318b869a03c7fcb95b6401c0d13d",
          "md5": "9e7c302c2e5b631a49938bf7dd8e96a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.6.aar",
          "url": "ble-characteristic-u2a92-android-0.8.6.aar",
          "size": 3089,
          "sha512": "5e044a6322d998bbe177e0446e2b8b211a326e78a460ed793e9a1255bd1986ec7da774ef9e8d73333e0500447f2948ee5aa93660838a49738f203f43a8246cf2",
          "sha256": "d9b4235753a45093782c13c7706cf10aabb8c3b95736c73a0f39f803f35b359a",
          "sha1": "c16aa49b45ec318b869a03c7fcb95b6401c0d13d",
          "md5": "9e7c302c2e5b631a49938bf7dd8e96a6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a92-android-0.8.6-sources.jar",
          "size": 2174,
          "sha512": "248e6b5bb33def52dec7f5fbbbb4cc9bb53478371bca570122fbfe42b9decc13b4ac63dfeecf6437a0ab0495c2f8bbac0deceff43d04e8a90cae7085b9eb33e1",
          "sha256": "1d5b88167c32f943982075408fb2452976ec74fa4e5799f3832b1ab39a0a69a4",
          "sha1": "801f3274f92ab207aadcd2808d7043660502ce10",
          "md5": "914b5e666a79c19172c36f31d6b423ae"
        }
      ]
    }
  ]
}
