{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab1",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-0.8.3.jar",
          "url": "ble-characteristic-u2ab1-0.8.3.jar",
          "size": 1781,
          "sha512": "43fc779213015499eaa75379378ee0a1fb4fd00dd16d229f55eba593be5bfb0cda28704690e550ba96c372940cc6153832ca02a859052d412e60ae3762eb9e40",
          "sha256": "3fd35c47c14c935f5fb195e1f1a50c446a8503b5f50335b00d2b92db3e769a9a",
          "sha1": "b60a71f5cce65412b2f059f94dd09b3abb3d8d98",
          "md5": "8f0b35f7fa9c37eb97f3b01699c317f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-0.8.3.jar",
          "url": "ble-characteristic-u2ab1-0.8.3.jar",
          "size": 1781,
          "sha512": "43fc779213015499eaa75379378ee0a1fb4fd00dd16d229f55eba593be5bfb0cda28704690e550ba96c372940cc6153832ca02a859052d412e60ae3762eb9e40",
          "sha256": "3fd35c47c14c935f5fb195e1f1a50c446a8503b5f50335b00d2b92db3e769a9a",
          "sha1": "b60a71f5cce65412b2f059f94dd09b3abb3d8d98",
          "md5": "8f0b35f7fa9c37eb97f3b01699c317f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab1-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2ab1-0.8.3-javadoc.jar",
          "size": 110117,
          "sha512": "fd8d4b00ed64aaa855e2be491b38ddeb1d0cf7524ad7f286ef99f5ef8b65df7ba429f9317d37c335e4f28a932e0868285e31437b8bef77fe32fa2d65af03578e",
          "sha256": "8d11cfd1d1fb6458e1f9570966461c64d360dc028d16b23f4785a35f8456e603",
          "sha1": "346413f90194b553c8e93dcbc06c3a01fb19bfb9",
          "md5": "52c804ab09660d149f950408372c09ea"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab1-0.8.3-sources.jar",
          "url": "ble-characteristic-u2ab1-0.8.3-sources.jar",
          "size": 1625,
          "sha512": "cf53d1a772270b4d61d9fe4d7e5d0c01ea7b0dffa2510748a3325d80f3165491fe9cb464ea42ef6374cbe8504698be8821ba4c60e7a81b70be670e75cf0e54bd",
          "sha256": "3cf2cd48bee93fb60af24b8198d6fb807defb5164d7edbca1d751a88b7e5ce13",
          "sha1": "81c47895a0626ce1f7f0a93f42c57a9c4af59418",
          "md5": "9b2d5ebff9b9f9d5980b1989427dc98f"
        }
      ]
    }
  ]
}
