{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab9-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2kquscs33vaubks6hlnwqdrbne"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab9",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-android-0.2.2.aar",
          "url": "ble-characteristic-u2ab9-android-0.2.2.aar",
          "size": 2935,
          "sha512": "e0c44bdbd75c3318e9c787c21bd37007090521ac319c0c4c98c2b98168476043e2ae0c72fc71adc1012334040f2e6442160ba58519a81324217ebe828635c238",
          "sha256": "f3d6daa8878d44e08e1ba7729c13cbf0e145cfc95d575f61c2712e8e6cdd763c",
          "sha1": "c48208e951f461edab41d97b6140d3e1ba28361a",
          "md5": "f29f40ec40e55f5901f2b4fe66b03cfa"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab9",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-android-0.2.2.aar",
          "url": "ble-characteristic-u2ab9-android-0.2.2.aar",
          "size": 2935,
          "sha512": "e0c44bdbd75c3318e9c787c21bd37007090521ac319c0c4c98c2b98168476043e2ae0c72fc71adc1012334040f2e6442160ba58519a81324217ebe828635c238",
          "sha256": "f3d6daa8878d44e08e1ba7729c13cbf0e145cfc95d575f61c2712e8e6cdd763c",
          "sha1": "c48208e951f461edab41d97b6140d3e1ba28361a",
          "md5": "f29f40ec40e55f5901f2b4fe66b03cfa"
        }
      ]
    }
  ]
}
