{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-gatt-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-gatt-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-gatt-android-0.4.6.aar",
          "url": "ble-service-central-gatt-android-0.4.6.aar",
          "size": 6713,
          "sha512": "3bafb34330d27454044829a478d99165fe8593d1c8ad5d105b8633de70b06bc9b164f1a892f295b1a9bc77246af901ad6d5f3f716c6c2ca0c4de976c0835fb78",
          "sha256": "93be8e1b5b5b7f89995b15fe5f8ea486f28b81e72f53718aa1f1ba24bfc2f312",
          "sha1": "3ffad045e1c4bcb7355b3218c2776c379cc804c9",
          "md5": "82949da0550a1f7bc086335a2233e555"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-gatt-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-gatt-android-0.4.6.aar",
          "url": "ble-service-central-gatt-android-0.4.6.aar",
          "size": 6713,
          "sha512": "3bafb34330d27454044829a478d99165fe8593d1c8ad5d105b8633de70b06bc9b164f1a892f295b1a9bc77246af901ad6d5f3f716c6c2ca0c4de976c0835fb78",
          "sha256": "93be8e1b5b5b7f89995b15fe5f8ea486f28b81e72f53718aa1f1ba24bfc2f312",
          "sha1": "3ffad045e1c4bcb7355b3218c2776c379cc804c9",
          "md5": "82949da0550a1f7bc086335a2233e555"
        }
      ]
    }
  ]
}
