{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1d-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "x6nyasohnvdrtpp4affpidlfoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1d",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1d-android-0.2.6.aar",
          "url": "ble-characteristic-u2b1d-android-0.2.6.aar",
          "size": 3083,
          "sha512": "5a5455735d4dc2c44bf2dc80ae819c9db2a474b1d062323da2f5d0cef90f9b0357af09219dbc262074a7fbe3067c0336161f05d291f4e8c00241d53937236bb6",
          "sha256": "f91115dd563e315bfb14e8ff94f384360ab74470cc145788dcaa40a9d20933be",
          "sha1": "b9a0ee840910e2d268f3836af34fa65b078621be",
          "md5": "7b6b2d25cd46661660196eee13e5693b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1d",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1d-android-0.2.6.aar",
          "url": "ble-characteristic-u2b1d-android-0.2.6.aar",
          "size": 3083,
          "sha512": "5a5455735d4dc2c44bf2dc80ae819c9db2a474b1d062323da2f5d0cef90f9b0357af09219dbc262074a7fbe3067c0336161f05d291f4e8c00241d53937236bb6",
          "sha256": "f91115dd563e315bfb14e8ff94f384360ab74470cc145788dcaa40a9d20933be",
          "sha1": "b9a0ee840910e2d268f3836af34fa65b078621be",
          "md5": "7b6b2d25cd46661660196eee13e5693b"
        }
      ]
    }
  ]
}
