{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-android",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ne3pcejtrrhfvmmkle32bx6bti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-central",
          "version": {
            "requires": "0.5.22"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-android-0.1.10.aar",
          "url": "ble-service-central-android-0.1.10.aar",
          "size": 4564,
          "sha512": "88ba5a8c2b44b282839654cdaef059f1f5a08e1f4a5c454fcfcf9c5c2b96e2a62a5971f3052ec5feb4660b5c7a94128295987cb9885e59bf7d757ed735464db5",
          "sha256": "f428f4d5b971293b8501dd2f7cff95f4f0a6f7b826cadfb98d482ce79fb7e0e5",
          "sha1": "8ed7504da976af00ec79d126cdf6868975831809",
          "md5": "581084fcf2fb3c6d34e377ca2b39ac5a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-central",
          "version": {
            "requires": "0.5.22"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-android-0.1.10.aar",
          "url": "ble-service-central-android-0.1.10.aar",
          "size": 4564,
          "sha512": "88ba5a8c2b44b282839654cdaef059f1f5a08e1f4a5c454fcfcf9c5c2b96e2a62a5971f3052ec5feb4660b5c7a94128295987cb9885e59bf7d757ed735464db5",
          "sha256": "f428f4d5b971293b8501dd2f7cff95f4f0a6f7b826cadfb98d482ce79fb7e0e5",
          "sha1": "8ed7504da976af00ec79d126cdf6868975831809",
          "md5": "581084fcf2fb3c6d34e377ca2b39ac5a"
        }
      ]
    }
  ]
}
