{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-android",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "stacklog",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-android-0.1.9.aar",
          "url": "ble-core-android-0.1.9.aar",
          "size": 3071,
          "sha512": "a46ef18bac47662f485a205bf0c96fe043f5bf84e36ee079056e7d909d085987f3a1175154665fa226df47f591af535d78ec6384340a0178b1e1256f3b026dd6",
          "sha256": "5861dcb697474b7ab0afef41ebcb5176953fb0502301a41a00a20b6abaf92cae",
          "sha1": "58cd852ece0cf7c1c607a16efa92ab45e1f8ed14",
          "md5": "4ccfabf48a1f31f15da9852275b8a9ba"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "stacklog",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-android-0.1.9.aar",
          "url": "ble-core-android-0.1.9.aar",
          "size": 3071,
          "sha512": "a46ef18bac47662f485a205bf0c96fe043f5bf84e36ee079056e7d909d085987f3a1175154665fa226df47f591af535d78ec6384340a0178b1e1256f3b026dd6",
          "sha256": "5861dcb697474b7ab0afef41ebcb5176953fb0502301a41a00a20b6abaf92cae",
          "sha1": "58cd852ece0cf7c1c607a16efa92ab45e1f8ed14",
          "md5": "4ccfabf48a1f31f15da9852275b8a9ba"
        }
      ]
    }
  ]
}
