{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1d",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1d-0.6.0.jar",
          "url": "ble-characteristic-u2a1d-0.6.0.jar",
          "size": 1739,
          "sha512": "bd1f3966e52a1188a6038fc3562b084939a9f85d63642e755d956c5064beefd966c2050ba9e1a6585608e9aabacd807872da7a86ebbe425ca001c303f5b344b1",
          "sha256": "47480f8ab6031956cd86ecc2f9f9e638bb1be1214f7b3d898454e367ead3bcf5",
          "sha1": "df8319682a05c48d471ec5426a41bc89284e2c09",
          "md5": "e497e2455bdcc425f8dee71b21a9c8a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1d-0.6.0.jar",
          "url": "ble-characteristic-u2a1d-0.6.0.jar",
          "size": 1739,
          "sha512": "bd1f3966e52a1188a6038fc3562b084939a9f85d63642e755d956c5064beefd966c2050ba9e1a6585608e9aabacd807872da7a86ebbe425ca001c303f5b344b1",
          "sha256": "47480f8ab6031956cd86ecc2f9f9e638bb1be1214f7b3d898454e367ead3bcf5",
          "sha1": "df8319682a05c48d471ec5426a41bc89284e2c09",
          "md5": "e497e2455bdcc425f8dee71b21a9c8a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a1d-0.6.0-javadoc.jar",
          "url": "ble-characteristic-u2a1d-0.6.0-javadoc.jar",
          "size": 110082,
          "sha512": "88f297eb10702e09d0bb7e0ed732515fd48e8a86b9ab5ea2ad8e75b98c881fabfa9ffdbbef65a873b2653ad3eaad48c4c5b4d6abb8e647a0fa98842b65f6d3b8",
          "sha256": "3c3945beabc4bf74562c52fad1db58c8aba82bac962244f6d89f104f3130a044",
          "sha1": "d438af4a858dc28398ea19c2a4e5807cce2ed0e3",
          "md5": "b6c0b97ed8fb5816a3c8db8fa173ad2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a1d-0.6.0-sources.jar",
          "url": "ble-characteristic-u2a1d-0.6.0-sources.jar",
          "size": 1598,
          "sha512": "53d6751dddef70235a7ccfa2ad1b3a86948f74c91f0b4f53d5f390147cc1a33d4f7982bcc69de1819c597204220730e530f8e12874a685d87124f1ab1c30a28b",
          "sha256": "369fabcb9a4364287988f3f67510083bf8979169632fd3213c02a25f084499d9",
          "sha1": "43be911712e22bb58959a16fe034f006a3f6c547",
          "md5": "9d6315c04b5a571b9d9c049d4787a40b"
        }
      ]
    }
  ]
}
