{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ans-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48-android",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-android-0.1.2.aar",
          "url": "ble-service-ans-android-0.1.2.aar",
          "size": 1650,
          "sha512": "be2f5b380d295435a480c5573694a511ad471cd59e375f47325a29f33efe8dda4831712779ac50d169c05b8d4b67a520c6bb99b0b7afba590af589683d89ee45",
          "sha256": "75474eb1ae18a23bc0ef461d9e1a920b918cad7545c52c1ae442d029500a49bb",
          "sha1": "ac5bced25b4b422ea81be1a260de80e883423925",
          "md5": "ef7d1fb4d7b300543a9217017ec6a5aa"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47-android",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48-android",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-android-0.1.2.aar",
          "url": "ble-service-ans-android-0.1.2.aar",
          "size": 1650,
          "sha512": "be2f5b380d295435a480c5573694a511ad471cd59e375f47325a29f33efe8dda4831712779ac50d169c05b8d4b67a520c6bb99b0b7afba590af589683d89ee45",
          "sha256": "75474eb1ae18a23bc0ef461d9e1a920b918cad7545c52c1ae442d029500a49bb",
          "sha1": "ac5bced25b4b422ea81be1a260de80e883423925",
          "md5": "ef7d1fb4d7b300543a9217017ec6a5aa"
        }
      ]
    }
  ]
}
