{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6e-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6e",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6e-android-0.4.4.aar",
          "url": "ble-characteristic-u2a6e-android-0.4.4.aar",
          "size": 3090,
          "sha512": "167d615197ab338ce0555cb55f32aaee6af4befeb035b5336faa0affe239d94ecf5d6dee0bb087d786626d346908ebbf2a20888628cdf28045ff74cc36dc7b01",
          "sha256": "ecad11a1398a7878efd5a69ebfa1c7636fb668576008ce36555cfe4b08e7a473",
          "sha1": "204e6bf2ca8f17393a0b950627b449fbd9082928",
          "md5": "e539fe3490a9cc7f5bd736e2baf77d99"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6e",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6e-android-0.4.4.aar",
          "url": "ble-characteristic-u2a6e-android-0.4.4.aar",
          "size": 3090,
          "sha512": "167d615197ab338ce0555cb55f32aaee6af4befeb035b5336faa0affe239d94ecf5d6dee0bb087d786626d346908ebbf2a20888628cdf28045ff74cc36dc7b01",
          "sha256": "ecad11a1398a7878efd5a69ebfa1c7636fb668576008ce36555cfe4b08e7a473",
          "sha1": "204e6bf2ca8f17393a0b950627b449fbd9082928",
          "md5": "e539fe3490a9cc7f5bd736e2baf77d99"
        }
      ]
    }
  ]
}
