{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae2-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae2",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae2-android-0.4.2.aar",
          "url": "ble-characteristic-u2ae2-android-0.4.2.aar",
          "size": 3031,
          "sha512": "e203dc592682a67cab29d3307251bf9b6f4b2c1cea0b759154e7a5a148f9de3c17939d11eee6dc46ad4df7edebc4c3df4e735e97d9c6dbbd117854145b5c917b",
          "sha256": "03291189dc0cf72487b69d253d12f50646291e3b300284bb789b815c414a827f",
          "sha1": "e1a69d4aff462e6db27717ec22ba661fe9deeb26",
          "md5": "ba8cc007da75e19c8c17685da646ad27"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae2",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae2-android-0.4.2.aar",
          "url": "ble-characteristic-u2ae2-android-0.4.2.aar",
          "size": 3031,
          "sha512": "e203dc592682a67cab29d3307251bf9b6f4b2c1cea0b759154e7a5a148f9de3c17939d11eee6dc46ad4df7edebc4c3df4e735e97d9c6dbbd117854145b5c917b",
          "sha256": "03291189dc0cf72487b69d253d12f50646291e3b300284bb789b815c414a827f",
          "sha1": "e1a69d4aff462e6db27717ec22ba661fe9deeb26",
          "md5": "ba8cc007da75e19c8c17685da646ad27"
        }
      ]
    }
  ]
}
