{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab9",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.13.jar",
          "url": "ble-characteristic-u2ab9-0.8.13.jar",
          "size": 1585,
          "sha512": "5bdcc780e037aaf2e28d0941f179b88b4f4085b648ad1a79904783f27461e0a7bcd78b8ab6d7a920816eae87a2daa377cbdaac52703f530633e2f308a8437927",
          "sha256": "ab3a91eb8b4c7f049fd0ad2bfc535c27c5120cd06c2acc9f210317f51a3758f7",
          "sha1": "51cd9e4ab503bfafe369757437ef463c184288ab",
          "md5": "0fe0df451d4df33decfb293564086018"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.13.jar",
          "url": "ble-characteristic-u2ab9-0.8.13.jar",
          "size": 1585,
          "sha512": "5bdcc780e037aaf2e28d0941f179b88b4f4085b648ad1a79904783f27461e0a7bcd78b8ab6d7a920816eae87a2daa377cbdaac52703f530633e2f308a8437927",
          "sha256": "ab3a91eb8b4c7f049fd0ad2bfc535c27c5120cd06c2acc9f210317f51a3758f7",
          "sha1": "51cd9e4ab503bfafe369757437ef463c184288ab",
          "md5": "0fe0df451d4df33decfb293564086018"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2ab9-0.8.13-javadoc.jar",
          "size": 86235,
          "sha512": "84a19418e05ad6d89cdee7a7f0d43d56ccf06c617e04280a17a1560cff7c46641217940ba8876e8de3f19dc36d18fc3036c5a592632a4c4433582070b8b2e960",
          "sha256": "8ad49e34dbb089f883b23127063cd9e619c4ab6ddf5bad13be8cd60c0f72ed19",
          "sha1": "120f4bd69b0ab2ddf00b81f82ae303877d946e44",
          "md5": "a3ec132053a59893a626c6a96f0ee1fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab9-0.8.13-sources.jar",
          "url": "ble-characteristic-u2ab9-0.8.13-sources.jar",
          "size": 1505,
          "sha512": "f9fde401f07fb1ad2b21f36f2f50f6bb6ec9f22d82bcb5ea8490c14e7ae7e597f1b040f7134a6fcad2cd6c96dbf88b008788d3fc003edc476f1720604bd65b1d",
          "sha256": "8bc1671a7342e138ecc52b36cd0ebfa5a91a487842a2e2b9f04339c8d1744966",
          "sha1": "246b95e320cdf5e0dc67fd481a393bdcb56b8fda",
          "md5": "5ae341bb4c8e87800770e8e43776b0c2"
        }
      ]
    }
  ]
}
