{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-ftmp-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ftms-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-uds-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.14.aar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.14.aar",
          "size": 15136,
          "sha512": "891a80f6dcc6c1fb0392b81a9f2ce7b820e03ae90a897d52a4c6c83e37788b757fe4b424de924b0ba3b5a26bddd8ad28d19a846ffef992ea3dac37909e90766c",
          "sha256": "46e4cb3f7d19a109f48207bbd918cde17bea10e99aed036a65175ccb608a84f2",
          "sha1": "2e0577a207a2fd1edc78cd7e6c750886e6bb9c3a",
          "md5": "8a0f919c2738d713aea5a5bf3e187cee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ftms-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-uds-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.14.aar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.14.aar",
          "size": 15136,
          "sha512": "891a80f6dcc6c1fb0392b81a9f2ce7b820e03ae90a897d52a4c6c83e37788b757fe4b424de924b0ba3b5a26bddd8ad28d19a846ffef992ea3dac37909e90766c",
          "sha256": "46e4cb3f7d19a109f48207bbd918cde17bea10e99aed036a65175ccb608a84f2",
          "sha1": "2e0577a207a2fd1edc78cd7e6c750886e6bb9c3a",
          "md5": "8a0f919c2738d713aea5a5bf3e187cee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.14-sources.jar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.14-sources.jar",
          "size": 8958,
          "sha512": "b5929f060d8ae0d298937c10ee47dd5461fd734ad4381c9f89f4facfbec62be4483c2a45a414a3a93c9b877afc5968517240184c68019673ae35374b323e3e33",
          "sha256": "b3db03330baae81723605a99e9744254527c438e635608126f3166064159eec8",
          "sha1": "cb455af8680c39659b1b2b8082dcaa0414dc1765",
          "md5": "16606527a8501e61612fe223ffc54ada"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.14-javadoc.jar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.14-javadoc.jar",
          "size": 318715,
          "sha512": "7fbfc6b114cbe56a9a048c796ba73bfc6b1aae06c6835c4cba935a8b5a1297a4f28a14970fa7315803e0856c2a826115d747fc212012cb909d4110d1e0d5bb79",
          "sha256": "e82763c144ad564189e280a30dcc5d9d2dca0fc55e272b81a361803e9672fccb",
          "sha1": "6f64d603128969e66a5ea1d4fdeeb7e3c016f9a7",
          "md5": "0600000671acbe141c6f74e4381ec519"
        }
      ]
    }
  ]
}
