{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-rtus-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-rtus-android-0.4.0.aar",
          "url": "ble-service-peripheral-rtus-android-0.4.0.aar",
          "size": 3991,
          "sha512": "4c0b0f1acf0e6f29d791248ece1974278d813f64f7db441169be7416df08e28598fbedf62245fb07bb2113f7dc678c7a2b77856117e620dc693f580ee299b872",
          "sha256": "3c2f3ed03c87dcf77d11acbafa2c73fc207a62a0431f4418b5fd1aa52e406958",
          "sha1": "770aad6e3417671492427a7cbfb82cb92f08151d",
          "md5": "8894a0757596850f8dd3fb82483f3d6b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-rtus-android-0.4.0.aar",
          "url": "ble-service-peripheral-rtus-android-0.4.0.aar",
          "size": 3991,
          "sha512": "4c0b0f1acf0e6f29d791248ece1974278d813f64f7db441169be7416df08e28598fbedf62245fb07bb2113f7dc678c7a2b77856117e620dc693f580ee299b872",
          "sha256": "3c2f3ed03c87dcf77d11acbafa2c73fc207a62a0431f4418b5fd1aa52e406958",
          "sha1": "770aad6e3417671492427a7cbfb82cb92f08151d",
          "md5": "8894a0757596850f8dd3fb82483f3d6b"
        }
      ]
    }
  ]
}
