{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a82",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jy7ixesazfhqnmjb55547uywfu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a82-0.1.0.jar",
          "url": "ble-characteristic-u2a82-0.1.0.jar",
          "size": 1723,
          "sha512": "38c9b268e1b86ece8300f49e02b18bb989a2684bde0d54efc00eeab8a53669605a6ca96290b0d3e5cc56f50bc315ffb4484e35fa631f9feb885e3c4ee51e2151",
          "sha256": "f0633657b4f5e2c303607db099c023426c55530157d92e82a95220add9649f77",
          "sha1": "eaa9792358d41f6d642b1a949ad857b663866d77",
          "md5": "b936a48169aa7bcbe3d7494e02ff6871"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a82-0.1.0.jar",
          "url": "ble-characteristic-u2a82-0.1.0.jar",
          "size": 1723,
          "sha512": "38c9b268e1b86ece8300f49e02b18bb989a2684bde0d54efc00eeab8a53669605a6ca96290b0d3e5cc56f50bc315ffb4484e35fa631f9feb885e3c4ee51e2151",
          "sha256": "f0633657b4f5e2c303607db099c023426c55530157d92e82a95220add9649f77",
          "sha1": "eaa9792358d41f6d642b1a949ad857b663866d77",
          "md5": "b936a48169aa7bcbe3d7494e02ff6871"
        }
      ]
    }
  ]
}
