{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8b-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8b-android-0.2.1.aar",
          "size": 3023,
          "sha512": "c4c18e5379c3b082a908ac9c9eeef0092d488a810cff7b7b6eb7a5339fa53ff33036c41690ebcff3410584f04e0484f81af75693e981d2613b05f5f60ca12135",
          "sha256": "5cbd41e28321a4c0fa016ba664b2f1895e1c4cfbb1d9f70d76286cd8c7f5da56",
          "sha1": "4b5e5673de73e72cc5737c5bd1de4e60d7122a76",
          "md5": "95099dd8aab6c9eefb9e8b11e5433f8a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8b-android-0.2.1.aar",
          "size": 3023,
          "sha512": "c4c18e5379c3b082a908ac9c9eeef0092d488a810cff7b7b6eb7a5339fa53ff33036c41690ebcff3410584f04e0484f81af75693e981d2613b05f5f60ca12135",
          "sha256": "5cbd41e28321a4c0fa016ba664b2f1895e1c4cfbb1d9f70d76286cd8c7f5da56",
          "sha1": "4b5e5673de73e72cc5737c5bd1de4e60d7122a76",
          "md5": "95099dd8aab6c9eefb9e8b11e5433f8a"
        }
      ]
    }
  ]
}
