{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa3-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa3",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa3-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa3-android-0.8.6.aar",
          "size": 3119,
          "sha512": "18ad91d0abf08fa68d0c74b45ea45113dc9ebf2d4038c767ba5565d844d9f0ff29c766fb92984fb6a79e72565904a4f4f7a771c350a3d89d33f9b470302c3b59",
          "sha256": "daa694d491daad74ec09c974aafdf964b47ba91e91e42bd002ef3b36ea15b5d1",
          "sha1": "d9b2c0f376a1cb449cb58c17c431ab4e5d9af52e",
          "md5": "023b483ea5dbbec2721cb9f697545021"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa3",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa3-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa3-android-0.8.6.aar",
          "size": 3119,
          "sha512": "18ad91d0abf08fa68d0c74b45ea45113dc9ebf2d4038c767ba5565d844d9f0ff29c766fb92984fb6a79e72565904a4f4f7a771c350a3d89d33f9b470302c3b59",
          "sha256": "daa694d491daad74ec09c974aafdf964b47ba91e91e42bd002ef3b36ea15b5d1",
          "sha1": "d9b2c0f376a1cb449cb58c17c431ab4e5d9af52e",
          "md5": "023b483ea5dbbec2721cb9f697545021"
        }
      ]
    }
  ]
}
