{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ess-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290c-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2c-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6c-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6d-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6e-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6f-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a70-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a72-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a73-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a74-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a75-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a76-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a77-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a78-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a79-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7a-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7b-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7d-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa0-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa1-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa3-android",
          "version": {
            "requires": "0.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ess-android-0.1.3.aar",
          "url": "ble-service-ess-android-0.1.3.aar",
          "size": 1184,
          "sha512": "935837e4ef661bb6d1267d14e157ae33cf9602ed47197750eacd6355c1779ddf2533fca80e0920edb88aa7b012019d45b91fa5a9cd36c6eafdbe10f639b63aa5",
          "sha256": "7541449f3eeeb54ec7cf350f726ea69d56160a8c70af9b0936a7f74525e5fb2d",
          "sha1": "86fbf669cb854406597e895bc81770bdc43c5cb2",
          "md5": "3eb4b6059a82521aabdc7a3b5cbd6073"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290c-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2c-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6c-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6d-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6e-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6f-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a70-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a72-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a73-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a74-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a75-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a76-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a77-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a78-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a79-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7a-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7b-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7d-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa0-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa1-android",
          "version": {
            "requires": "0.2.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa3-android",
          "version": {
            "requires": "0.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ess-android-0.1.3.aar",
          "url": "ble-service-ess-android-0.1.3.aar",
          "size": 1184,
          "sha512": "935837e4ef661bb6d1267d14e157ae33cf9602ed47197750eacd6355c1779ddf2533fca80e0920edb88aa7b012019d45b91fa5a9cd36c6eafdbe10f639b63aa5",
          "sha256": "7541449f3eeeb54ec7cf350f726ea69d56160a8c70af9b0936a7f74525e5fb2d",
          "sha1": "86fbf669cb854406597e895bc81770bdc43c5cb2",
          "md5": "3eb4b6059a82521aabdc7a3b5cbd6073"
        }
      ]
    }
  ]
}
