{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab8-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab8",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-android-0.8.10.aar",
          "url": "ble-characteristic-u2ab8-android-0.8.10.aar",
          "size": 3199,
          "sha512": "404c80436d481c508b98e96bb5b6fcda3a6307348a4cee80a7d9942cc8d4aacc5bc30148c466d3a7a14d50933b9a7d883f032a016ca9e1c6258ba6d77d44ae8b",
          "sha256": "d884976273bcc07b4b31980fc30071d9d6ad47cddbbeea7867053cc82f536c9e",
          "sha1": "e52dd216c8b46e7aa165240954922d5f2fa6f42d",
          "md5": "1ccf1c082ee4d1a6c8abcec7b2052a48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab8",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-android-0.8.10.aar",
          "url": "ble-characteristic-u2ab8-android-0.8.10.aar",
          "size": 3199,
          "sha512": "404c80436d481c508b98e96bb5b6fcda3a6307348a4cee80a7d9942cc8d4aacc5bc30148c466d3a7a14d50933b9a7d883f032a016ca9e1c6258ba6d77d44ae8b",
          "sha256": "d884976273bcc07b4b31980fc30071d9d6ad47cddbbeea7867053cc82f536c9e",
          "sha1": "e52dd216c8b46e7aa165240954922d5f2fa6f42d",
          "md5": "1ccf1c082ee4d1a6c8abcec7b2052a48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab8-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2ab8-android-0.8.10-sources.jar",
          "size": 2186,
          "sha512": "ef2e371e17d4482f7fe03585719f7d55da011abb3e66413de214a16a9763ea3f81d745eeb5a18ffe303a87fc82f4c067a93ea439f3d83f16f846bd569d65d4ca",
          "sha256": "b92c74d9f8c1715da7ad0ce99da817cff574ae5ba84dbaa7e2168824cb0c2bdc",
          "sha1": "425afa8084b12750929faba59e85225fad979209",
          "md5": "b460f9fe57bf8e92f3d9e34bd8b8a80f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab8-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2ab8-android-0.8.10-javadoc.jar",
          "size": 272546,
          "sha512": "d2f3b7f61e2592de4f435287d021f3bd382fb10dedd5a07afbfc78dc4aa9d71237dfd412e061e6a6251809594556a0545386e035667f735772cbad9b1db64c3b",
          "sha256": "2a7ffe7e4a8bf368e2a077a2af938ff0c955f636add97024707abc28343c2e2a",
          "sha1": "930edebc99b3170eb0e98a19e690ea76d15be66b",
          "md5": "ae9d0671b7c761ccf5012355ad532e49"
        }
      ]
    }
  ]
}
