{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af6",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af6-0.4.6.jar",
          "url": "ble-characteristic-u2af6-0.4.6.jar",
          "size": 1647,
          "sha512": "3ced9e0a1039885e95a9ecf9c359e705a53485878607e3b2b32383627fc79103a3506a9a5e096cc9642abfb5ef28f65d07d0b1c76afc5e1c593ca7a29a353215",
          "sha256": "7de09f120d22f5b841f56cbac1abab0652d06b95a9a6ae295a1995ec7b510382",
          "sha1": "14b957bff2d7b05f9261b0805873559428dd8fc3",
          "md5": "422cd91b378abf36433fd2df2a1943d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af6-0.4.6.jar",
          "url": "ble-characteristic-u2af6-0.4.6.jar",
          "size": 1647,
          "sha512": "3ced9e0a1039885e95a9ecf9c359e705a53485878607e3b2b32383627fc79103a3506a9a5e096cc9642abfb5ef28f65d07d0b1c76afc5e1c593ca7a29a353215",
          "sha256": "7de09f120d22f5b841f56cbac1abab0652d06b95a9a6ae295a1995ec7b510382",
          "sha1": "14b957bff2d7b05f9261b0805873559428dd8fc3",
          "md5": "422cd91b378abf36433fd2df2a1943d2"
        }
      ]
    }
  ]
}
