{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acb-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acb",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acb-android-0.4.2.aar",
          "url": "ble-characteristic-u2acb-android-0.4.2.aar",
          "size": 3066,
          "sha512": "2de78c0cf6e8e863b8bd96ba51d6e3b2ce9c49194103f99d8905eeba86dd916f4f49fc87d49a1337b51dfef55bf2f373d8393f4a74b3b6c71949376347b7dce7",
          "sha256": "6af2c6cf4c1a0c01c6514ccf9199103424a967b705ed197c320326ff11db4a73",
          "sha1": "12148bd3c0a08d48b4b821cc8f6eada9c3a5ac75",
          "md5": "aedd9d6ecf3f4a8d6bc44a4c84df475f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acb",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acb-android-0.4.2.aar",
          "url": "ble-characteristic-u2acb-android-0.4.2.aar",
          "size": 3066,
          "sha512": "2de78c0cf6e8e863b8bd96ba51d6e3b2ce9c49194103f99d8905eeba86dd916f4f49fc87d49a1337b51dfef55bf2f373d8393f4a74b3b6c71949376347b7dce7",
          "sha256": "6af2c6cf4c1a0c01c6514ccf9199103424a967b705ed197c320326ff11db4a73",
          "sha1": "12148bd3c0a08d48b4b821cc8f6eada9c3a5ac75",
          "md5": "aedd9d6ecf3f4a8d6bc44a4c84df475f"
        }
      ]
    }
  ]
}
