{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a71-android",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-android-0.6.0.aar",
          "url": "ble-characteristic-u2a71-android-0.6.0.aar",
          "size": 3076,
          "sha512": "a27e3fedac6af49b8fa3f1105a2d3bcc8fc705ec021c61d27881e96865da42054c4d58326eb1900a7b32de9d160bb3c926e274b547b05c3c6b99925600c59986",
          "sha256": "def95391b26122e29350c653fe150f95c583224e18d1ce081a935c400e79c251",
          "sha1": "0ddb9f718936a1e2f5b77285807cfe588264fc68",
          "md5": "09ccd532a2bfd6fe0cfdd52852f6d052"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-android-0.6.0.aar",
          "url": "ble-characteristic-u2a71-android-0.6.0.aar",
          "size": 3076,
          "sha512": "a27e3fedac6af49b8fa3f1105a2d3bcc8fc705ec021c61d27881e96865da42054c4d58326eb1900a7b32de9d160bb3c926e274b547b05c3c6b99925600c59986",
          "sha256": "def95391b26122e29350c653fe150f95c583224e18d1ce081a935c400e79c251",
          "sha1": "0ddb9f718936a1e2f5b77285807cfe588264fc68",
          "md5": "09ccd532a2bfd6fe0cfdd52852f6d052"
        }
      ]
    }
  ]
}
