{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2903-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2904-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2905-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2907-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2908-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2909-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290a-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290c-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290e-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-android-0.8.10.aar",
          "url": "ble-descriptor-android-0.8.10.aar",
          "size": 1276,
          "sha512": "00ffdab255651e7b8fcbb3d7bf5171ad89242d542e3d6df80c895486cc8a52185fcf8034bf055e1947ed14fb2f396fbccff3c6c175508dc5ae7858147978e177",
          "sha256": "72ec968b029bdd2a627b1470a580dc329ce3b8dc5dfd0b6dcd4dedf7de17c187",
          "sha1": "77479c4cfc6d25e377ef1291408b3d08c880330a",
          "md5": "1c5e0dcdc0597e7ce7872c92c4f4b1e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2903-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2904-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2905-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2907-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2908-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2909-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290a-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290c-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290e-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-android-0.8.10.aar",
          "url": "ble-descriptor-android-0.8.10.aar",
          "size": 1276,
          "sha512": "00ffdab255651e7b8fcbb3d7bf5171ad89242d542e3d6df80c895486cc8a52185fcf8034bf055e1947ed14fb2f396fbccff3c6c175508dc5ae7858147978e177",
          "sha256": "72ec968b029bdd2a627b1470a580dc329ce3b8dc5dfd0b6dcd4dedf7de17c187",
          "sha1": "77479c4cfc6d25e377ef1291408b3d08c880330a",
          "md5": "1c5e0dcdc0597e7ce7872c92c4f4b1e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-android-0.8.10-sources.jar",
          "url": "ble-descriptor-android-0.8.10-sources.jar",
          "size": 1060,
          "sha512": "1fa6f64c5e3223678e3a4af331384f49c8022d28f4ef18b7e0eb1fba109fc8a853bf612d08277469ced3711a5d127a4e2f44ec17f1f1501f5f4f8dc56cb3a92b",
          "sha256": "ce76f208453ca9da6566d98f71d3364955f1cf3710fcd883629bd37fd6c3507b",
          "sha1": "b27fbbabcc4c66b1f563dc5581b50afde8cdd4f1",
          "md5": "437eabd0574bc1446f2747198b12e338"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-android-0.8.10-javadoc.jar",
          "url": "ble-descriptor-android-0.8.10-javadoc.jar",
          "size": 259772,
          "sha512": "dbf16b296bfbc0eb3e954bdafca4c1e5610cbd5a78575a37dbf530ba755670256a5a841817702d03790ea85e4ebf34225a84f772009f2f603f0d73d0607ce3cc",
          "sha256": "ffb37add6f50fa2da3d14275ac01b19e61ba91653b0e10aeaeab32fed3773e04",
          "sha1": "0e1244c06213ae4e6ae5d6df8084023bce2ae10c",
          "md5": "d4021bafe55647ea844d33afce8237ee"
        }
      ]
    }
  ]
}
