{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290c",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.5.jar",
          "url": "ble-descriptor-u290c-0.8.5.jar",
          "size": 3934,
          "sha512": "cc8d25c9e386ee2d74c3838ce80158906de3c84d618c78cd982bef30d7f7069cefbc3448ece4c73527817f03825b329785ee109057885458510ab9e57726e6bf",
          "sha256": "7a4434cbe231ed872f0dd4fd11b21916b0c938903e97ec179becfc342cc5a417",
          "sha1": "1fd67246bbf3f2b3690abe2158cdb3d44f1a7058",
          "md5": "8522dbe3f19618d5240a01a249ac10f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.5.jar",
          "url": "ble-descriptor-u290c-0.8.5.jar",
          "size": 3934,
          "sha512": "cc8d25c9e386ee2d74c3838ce80158906de3c84d618c78cd982bef30d7f7069cefbc3448ece4c73527817f03825b329785ee109057885458510ab9e57726e6bf",
          "sha256": "7a4434cbe231ed872f0dd4fd11b21916b0c938903e97ec179becfc342cc5a417",
          "sha1": "1fd67246bbf3f2b3690abe2158cdb3d44f1a7058",
          "md5": "8522dbe3f19618d5240a01a249ac10f6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.5-javadoc.jar",
          "url": "ble-descriptor-u290c-0.8.5-javadoc.jar",
          "size": 118414,
          "sha512": "bae9790d05517a7abd6d06bba6fc8a9a2934fc520a85aed680fffa3e9db63848559e3889ba504613fce15aaf10139e1d535c0896f31a849220a826993944d7e2",
          "sha256": "0cec67df0ec708e955628a1aad1f7d6de525f61fd4e94c7e339951bbb106699f",
          "sha1": "5ad5189a40c9e9fd6721bb9d8e1201badb953d64",
          "md5": "3b04c524b56259998d8865d279023ae8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.5-sources.jar",
          "url": "ble-descriptor-u290c-0.8.5-sources.jar",
          "size": 3947,
          "sha512": "fed8c4bfe19fe2552de390bee80471746eff796656870b0dcabb6213eaebd18101e30b624610fc6e02011e1d667fc93c4b97de98ce1eb36b94ecabc31b182867",
          "sha256": "6e8a9e6a595762752878ec508416ac164dc1dc8c55f7e4d4483fcf16a7f40703",
          "sha1": "fe8b95caf0e32c7e67d91720b62f191409ec6c0b",
          "md5": "e5dcca128b69b0be3af61b2b505414c9"
        }
      ]
    }
  ]
}
