{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a0f-android",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a0f",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0f-android-0.5.0.aar",
          "url": "ble-characteristic-u2a0f-android-0.5.0.aar",
          "size": 3100,
          "sha512": "2fce41f5266fa89166f69d6be496ec9edf81329dddd8f2b0807b9d86573d8c9da3787a7562bf1300145bdfaefd5925611fd23ce55a6c60f499d7eb7ff8c3133f",
          "sha256": "5f8d264f5c6602f547fdb0f70abf9359d7ac7db5128c3898bd517e00200f33d2",
          "sha1": "c6e3a1667c2216117ff0838e673303467eca8b07",
          "md5": "9259e69834cdb2bdf181cc1e8a6b94af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a0f",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0f-android-0.5.0.aar",
          "url": "ble-characteristic-u2a0f-android-0.5.0.aar",
          "size": 3100,
          "sha512": "2fce41f5266fa89166f69d6be496ec9edf81329dddd8f2b0807b9d86573d8c9da3787a7562bf1300145bdfaefd5925611fd23ce55a6c60f499d7eb7ff8c3133f",
          "sha256": "5f8d264f5c6602f547fdb0f70abf9359d7ac7db5128c3898bd517e00200f33d2",
          "sha1": "c6e3a1667c2216117ff0838e673303467eca8b07",
          "md5": "9259e69834cdb2bdf181cc1e8a6b94af"
        }
      ]
    }
  ]
}
