{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a80-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a80-android-0.2.9.aar",
          "url": "ble-characteristic-u2a80-android-0.2.9.aar",
          "size": 3071,
          "sha512": "bf0d17c719dca854a60362692fa409b750472a41473b7300274055503b6f7e04d7217c4ff2fd2225d81a4e189fc88d9868cfa9b6476a01f519be55e5dacd2a20",
          "sha256": "94d40112ebcc4850fb7eeab97780110cf01e9509aee9353b831b46a62168c550",
          "sha1": "72545a7a7201453e482862cc2987bb51016f1991",
          "md5": "5f089df17f35bafcaece147bc6698f3f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a80-android-0.2.9.aar",
          "url": "ble-characteristic-u2a80-android-0.2.9.aar",
          "size": 3071,
          "sha512": "bf0d17c719dca854a60362692fa409b750472a41473b7300274055503b6f7e04d7217c4ff2fd2225d81a4e189fc88d9868cfa9b6476a01f519be55e5dacd2a20",
          "sha256": "94d40112ebcc4850fb7eeab97780110cf01e9509aee9353b831b46a62168c550",
          "sha1": "72545a7a7201453e482862cc2987bb51016f1991",
          "md5": "5f089df17f35bafcaece147bc6698f3f"
        }
      ]
    }
  ]
}
