{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.1.1.aar",
          "url": "ble-profile-peripheral-android-0.1.1.aar",
          "size": 2108,
          "sha512": "6e82fee65a7acca23a2531d45afdf9eafd6967477503e959a8231392a154525164358769a69a2c1f85ba34e5b0d1d0f6b0fed64c304eacf58503e6c31ca8f8f2",
          "sha256": "1460c9dbbe9138f5371d03d25fb73227ca5794a2e6c7d8cc03abc623faccef67",
          "sha1": "00878dcc2133e877657aea3b02b382cf12e31664",
          "md5": "0625e3052d91235fc9c8b30436057cd3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.1.1.aar",
          "url": "ble-profile-peripheral-android-0.1.1.aar",
          "size": 2108,
          "sha512": "6e82fee65a7acca23a2531d45afdf9eafd6967477503e959a8231392a154525164358769a69a2c1f85ba34e5b0d1d0f6b0fed64c304eacf58503e6c31ca8f8f2",
          "sha256": "1460c9dbbe9138f5371d03d25fb73227ca5794a2e6c7d8cc03abc623faccef67",
          "sha1": "00878dcc2133e877657aea3b02b382cf12e31664",
          "md5": "0625e3052d91235fc9c8b30436057cd3"
        }
      ]
    }
  ]
}
