{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a64",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a64-0.8.0.jar",
          "url": "ble-characteristic-u2a64-0.8.0.jar",
          "size": 3772,
          "sha512": "3aa7f61ebb18a6c49addfa8ef38b4c190ade71588f4448e0ea718eff882f368ae9801419e6dbf70e2788cdc480a4a336584edce745552e262e4700c0141b34f3",
          "sha256": "a02e10f26519bfc7718423c9eb03240f471af8de2a714ddcf8aae1c78423f300",
          "sha1": "791ce8d23235857cdc66e14d71d875793437f3f7",
          "md5": "17d45b0f395df25738f0e9d83bda36f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a64-0.8.0.jar",
          "url": "ble-characteristic-u2a64-0.8.0.jar",
          "size": 3772,
          "sha512": "3aa7f61ebb18a6c49addfa8ef38b4c190ade71588f4448e0ea718eff882f368ae9801419e6dbf70e2788cdc480a4a336584edce745552e262e4700c0141b34f3",
          "sha256": "a02e10f26519bfc7718423c9eb03240f471af8de2a714ddcf8aae1c78423f300",
          "sha1": "791ce8d23235857cdc66e14d71d875793437f3f7",
          "md5": "17d45b0f395df25738f0e9d83bda36f4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a64-0.8.0-javadoc.jar",
          "url": "ble-characteristic-u2a64-0.8.0-javadoc.jar",
          "size": 115304,
          "sha512": "84b6f4c6a2105769d1ce79a7326bccd0fc67697ff93fa547bb24a2f9534347d429758eea36fa1f566ef631772f2ca9b997ccf6a4acca157aed76d7ab8bde48e6",
          "sha256": "4832fe78ed1a81fb90ce49bfd23fccb5c3af271e52723bf41d8a30068e9fa7bf",
          "sha1": "1407f620f052be3fa7c8a290cf76b8c58de60629",
          "md5": "98685637bfdcf71f55c5ef43348f932a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a64-0.8.0-sources.jar",
          "url": "ble-characteristic-u2a64-0.8.0-sources.jar",
          "size": 3432,
          "sha512": "bbcc227945e2464264a5cd0dd8dab225a5d92beb58a9ef7a139b7c7c4072f8a128274451a806a853bc801bee03476f5435a627681fe739acf120cbbb44955f93",
          "sha256": "1446f389c23de0de904a87c70bcc7c1f5def91e90c53c9e2d65241bbda673311",
          "sha1": "a06f737c6035e63732d41055b736c581a18abd1f",
          "md5": "d4e00425a2cb439c5cd9decebe874c57"
        }
      ]
    }
  ]
}
