{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a07-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.2.2.aar",
          "url": "ble-characteristic-u2a07-android-0.2.2.aar",
          "size": 2910,
          "sha512": "ea60caacf37363d1f0ba1b7573031370394ba962cf4e35f67dc81957a1de965fd897c2345b942c9d8e6743a4c41c033ef88eb3fd190801c0328fa6d38a9dfc44",
          "sha256": "db0a1fb040481d47266e1edec6e31687be29088e6066b0f82ffc2a03c8311de3",
          "sha1": "fc2c9320c426d1396db8db4e0a2c7ea986f24515",
          "md5": "3024b983f212a754c09673c2944dd5ae"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.2.2.aar",
          "url": "ble-characteristic-u2a07-android-0.2.2.aar",
          "size": 2910,
          "sha512": "ea60caacf37363d1f0ba1b7573031370394ba962cf4e35f67dc81957a1de965fd897c2345b942c9d8e6743a4c41c033ef88eb3fd190801c0328fa6d38a9dfc44",
          "sha256": "db0a1fb040481d47266e1edec6e31687be29088e6066b0f82ffc2a03c8311de3",
          "sha1": "fc2c9320c426d1396db8db4e0a2c7ea986f24515",
          "md5": "3024b983f212a754c09673c2944dd5ae"
        }
      ]
    }
  ]
}
