{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-pasp-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-pasp-android-0.1.1.aar",
          "url": "ble-profile-pasp-android-0.1.1.aar",
          "size": 1206,
          "sha512": "b6e7e4eed8c8268dceb91793bc5a3abf456d94e8db82144a4f58780832ee68fcf9769cb7159dd7c41ccc6b05cec699e954876828e761683fc67cb091cc57194d",
          "sha256": "7edb11ee1d94a30dbfcfb83b5ab5fa02c7da789a965eb11f26f95d0dede182af",
          "sha1": "f3b067cd629f2dea476c9d11486145888f7f00d2",
          "md5": "17ad6a61029f99ccd0c7d4f5e7e5520b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-pasp-android-0.1.1.aar",
          "url": "ble-profile-pasp-android-0.1.1.aar",
          "size": 1206,
          "sha512": "b6e7e4eed8c8268dceb91793bc5a3abf456d94e8db82144a4f58780832ee68fcf9769cb7159dd7c41ccc6b05cec699e954876828e761683fc67cb091cc57194d",
          "sha256": "7edb11ee1d94a30dbfcfb83b5ab5fa02c7da789a965eb11f26f95d0dede182af",
          "sha1": "f3b067cd629f2dea476c9d11486145888f7f00d2",
          "md5": "17ad6a61029f99ccd0c7d4f5e7e5520b"
        }
      ]
    }
  ]
}
