{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8d",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xnyhilluxvgr3nzweyacpeoi5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-0.2.2.jar",
          "url": "ble-characteristic-u2a8d-0.2.2.jar",
          "size": 1722,
          "sha512": "1564d1f38dbbcacda351a0c544f08c8ca4beafa1931d4e96933a877ac168137a24429deb83713867afac2b9b3e5dde2da10be7b6da4d7828dff7eb0fa9934763",
          "sha256": "aac0db0b5429cd980267a1b83fd73c0a789e05f1caea964890d3c9220ae009d7",
          "sha1": "399a5899f103d30b67507b5ae5e37cd08eda4a23",
          "md5": "8dafcfcda6621922b11cb390bd4fd718"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-0.2.2.jar",
          "url": "ble-characteristic-u2a8d-0.2.2.jar",
          "size": 1722,
          "sha512": "1564d1f38dbbcacda351a0c544f08c8ca4beafa1931d4e96933a877ac168137a24429deb83713867afac2b9b3e5dde2da10be7b6da4d7828dff7eb0fa9934763",
          "sha256": "aac0db0b5429cd980267a1b83fd73c0a789e05f1caea964890d3c9220ae009d7",
          "sha1": "399a5899f103d30b67507b5ae5e37cd08eda4a23",
          "md5": "8dafcfcda6621922b11cb390bd4fd718"
        }
      ]
    }
  ]
}
