{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-pxp-peripheral-android",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "didsxcdw7raejas3g75ob27utq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pxp-peripheral-android-0.1.7.aar",
          "url": "ble-profile-pxp-peripheral-android-0.1.7.aar",
          "size": 3742,
          "sha512": "9f1afd7f243019cf9dedb82df6f6e95a0ab91d31a5150d447954f2c6a2b4c001c1471e1c42f2ed1aed97b056b194093a70e5f46f977f4be0fbd8e6bef10e5393",
          "sha256": "1bd52c63db713f6db6a739366af89e38352ef1b56d2e516b3c0468e879de5226",
          "sha1": "5fffec922d9be03a90853615e87bdcab1e11993d",
          "md5": "0fc390978de0d606071c733c07ac7479"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pxp-peripheral-android-0.1.7.aar",
          "url": "ble-profile-pxp-peripheral-android-0.1.7.aar",
          "size": 3742,
          "sha512": "9f1afd7f243019cf9dedb82df6f6e95a0ab91d31a5150d447954f2c6a2b4c001c1471e1c42f2ed1aed97b056b194093a70e5f46f977f4be0fbd8e6bef10e5393",
          "sha256": "1bd52c63db713f6db6a739366af89e38352ef1b56d2e516b3c0468e879de5226",
          "sha1": "5fffec922d9be03a90853615e87bdcab1e11993d",
          "md5": "0fc390978de0d606071c733c07ac7479"
        }
      ]
    }
  ]
}
