{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bbf-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bbf",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbf-android-0.8.14.aar",
          "url": "ble-characteristic-u2bbf-android-0.8.14.aar",
          "size": 3148,
          "sha512": "624f209e9a19799af6421d489bee5e61a12508201a5e60d1da3ba023eb1d57ae944f61111e4ff881cd388020c7a3a6781ca0d5515ab77482d63bbd6d6c919e2b",
          "sha256": "c3e52cc29280b2d740567187b8d419072544fae78436fa91a03ad898ad8d7562",
          "sha1": "47d817117445dd4a4ffda029a32d4e165999d33f",
          "md5": "67210be0e34317678f8c2a02cc38379b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bbf",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbf-android-0.8.14.aar",
          "url": "ble-characteristic-u2bbf-android-0.8.14.aar",
          "size": 3148,
          "sha512": "624f209e9a19799af6421d489bee5e61a12508201a5e60d1da3ba023eb1d57ae944f61111e4ff881cd388020c7a3a6781ca0d5515ab77482d63bbd6d6c919e2b",
          "sha256": "c3e52cc29280b2d740567187b8d419072544fae78436fa91a03ad898ad8d7562",
          "sha1": "47d817117445dd4a4ffda029a32d4e165999d33f",
          "md5": "67210be0e34317678f8c2a02cc38379b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbf-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2bbf-android-0.8.14-sources.jar",
          "size": 2226,
          "sha512": "0b9f79e3612e80a2959370fb5ec8f476a75cc3333b5d9ed9657ee99faf965a3221f43a79c1a4dbe3ee2fb924783ca81a7851604e59330013653dd356a0bc340a",
          "sha256": "a55af39a69eb7fad568364a6077b6be98c5a4ab0a326b2e2586c3b750afcb18b",
          "sha1": "a17560a0adcdf7940bc891c0c4a7f37cd856effd",
          "md5": "40a6cd725007faae2e43a2246109b11a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbf-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2bbf-android-0.8.14-javadoc.jar",
          "size": 271179,
          "sha512": "7824ff96e75baf536378fb0230c433b79a0b405f62837fe6c3c75fd924ec55a5581f02ee52b4bb182e2d42a4da9d6171f3bc5b76e71ab8ba105966e8119e1f3c",
          "sha256": "b8a252d49ae9cbecdd4eda584489414930a6e39906b9ecf9d5ea2dc41db46a31",
          "sha1": "9f98d151fc00efeeb0fd6321a076bf907006a686",
          "md5": "e63e1e9650fa563b4b07b2779cfa5214"
        }
      ]
    }
  ]
}
