{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a76-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zckqgxv52jertg33sctsfjorzm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a76",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a76-android-0.2.2.aar",
          "url": "ble-characteristic-u2a76-android-0.2.2.aar",
          "size": 2882,
          "sha512": "35440a00709e39d11afe62929afc9e1004e010b67f8e61b20c75d265eac5319ccce0c6b2c3074f2f3667c193a0df45f1e9ce46d78f93288c46010322d286df13",
          "sha256": "4c40cd5639a7c18709e446747888856b21df6d23baec6b657aedae53172179c2",
          "sha1": "01b5572a77f2b45da9537cecb1063befeef72bea",
          "md5": "9f5874fd3a5a9d3f5eeee667b2a4a844"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a76",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a76-android-0.2.2.aar",
          "url": "ble-characteristic-u2a76-android-0.2.2.aar",
          "size": 2882,
          "sha512": "35440a00709e39d11afe62929afc9e1004e010b67f8e61b20c75d265eac5319ccce0c6b2c3074f2f3667c193a0df45f1e9ce46d78f93288c46010322d286df13",
          "sha256": "4c40cd5639a7c18709e446747888856b21df6d23baec6b657aedae53172179c2",
          "sha1": "01b5572a77f2b45da9537cecb1063befeef72bea",
          "md5": "9f5874fd3a5a9d3f5eeee667b2a4a844"
        }
      ]
    }
  ]
}
