{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lns-central-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-central-android-0.1.2.aar",
          "url": "ble-service-lns-central-android-0.1.2.aar",
          "size": 7391,
          "sha512": "ee09af87630ff04ef53d0f77be7753ffa85363d0767296bd2a48a8964d1b8956d1a45aeae14e7e6f5957d0dc4c753d51537e4901c005320042574c1c27880a4e",
          "sha256": "9b086deecbef1a7e05ce361d67a791b7023fce3cce0996e6a8bc0152b9bde6fa",
          "sha1": "d7703f3a5c01bee511f091f0868e7520f4851dc7",
          "md5": "9d1a0d40fe0c845e805366db545de1ae"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-central-android-0.1.2.aar",
          "url": "ble-service-lns-central-android-0.1.2.aar",
          "size": 7391,
          "sha512": "ee09af87630ff04ef53d0f77be7753ffa85363d0767296bd2a48a8964d1b8956d1a45aeae14e7e6f5957d0dc4c753d51537e4901c005320042574c1c27880a4e",
          "sha256": "9b086deecbef1a7e05ce361d67a791b7023fce3cce0996e6a8bc0152b9bde6fa",
          "sha1": "d7703f3a5c01bee511f091f0868e7520f4851dc7",
          "md5": "9d1a0d40fe0c845e805366db545de1ae"
        }
      ]
    }
  ]
}
