{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a43-android",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a43",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a43-android-0.6.2.aar",
          "url": "ble-characteristic-u2a43-android-0.6.2.aar",
          "size": 3059,
          "sha512": "a6be60b0cc4f0ce79b35939503efd019ffd9cd685018474670ef0afc3b306cecc093230a25c7ad6317cc6c2498b1413eed14d5ca27d0253b570ba5c5f00a73a9",
          "sha256": "894f36b924591655bdb776d815004b6513600fba3cb16b3ffeeb9792577ed385",
          "sha1": "aa1663e4558f28a133c1d8177645ca0c796fea38",
          "md5": "0f7465b2f78e8349cbcd912282c09c41"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a43",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a43-android-0.6.2.aar",
          "url": "ble-characteristic-u2a43-android-0.6.2.aar",
          "size": 3059,
          "sha512": "a6be60b0cc4f0ce79b35939503efd019ffd9cd685018474670ef0afc3b306cecc093230a25c7ad6317cc6c2498b1413eed14d5ca27d0253b570ba5c5f00a73a9",
          "sha256": "894f36b924591655bdb776d815004b6513600fba3cb16b3ffeeb9792577ed385",
          "sha1": "aa1663e4558f28a133c1d8177645ca0c796fea38",
          "md5": "0f7465b2f78e8349cbcd912282c09c41"
        }
      ]
    }
  ]
}
