{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-gatt-central-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-gatt-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-gatt-central-android-0.1.3.aar",
          "url": "ble-service-gatt-central-android-0.1.3.aar",
          "size": 6755,
          "sha512": "51680df7711a688762ddfd9857fcc113648e8dc1641c0a6f98abe2e1469794b9e3031752ce14f7acf85cf239c2dfa6b30c1fad7ebaa711465271032cf144a92c",
          "sha256": "af557ce5e515da0381b01f69eaf64cb890097af4f39d050cab6d1f3f0825961c",
          "sha1": "c1976ba8a5d59b0a28347f3c335a529dbff3a7ae",
          "md5": "243d5aeea204738f6949805e97141c1d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-gatt-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-gatt-central-android-0.1.3.aar",
          "url": "ble-service-gatt-central-android-0.1.3.aar",
          "size": 6755,
          "sha512": "51680df7711a688762ddfd9857fcc113648e8dc1641c0a6f98abe2e1469794b9e3031752ce14f7acf85cf239c2dfa6b30c1fad7ebaa711465271032cf144a92c",
          "sha256": "af557ce5e515da0381b01f69eaf64cb890097af4f39d050cab6d1f3f0825961c",
          "sha1": "c1976ba8a5d59b0a28347f3c335a529dbff3a7ae",
          "md5": "243d5aeea204738f6949805e97141c1d"
        }
      ]
    }
  ]
}
