{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a91-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a91-android-0.8.6.aar",
          "url": "ble-characteristic-u2a91-android-0.8.6.aar",
          "size": 3141,
          "sha512": "e22aec2fba30c702d302017de36a9346265921e92e5f4e21cc8c0257ef814a7e61f32d6e4c4428bd8f5050dd4fc3a0a4ff5b23ecb787caadcd7858188dd9b16b",
          "sha256": "44d6f96095e447c7e923f9a695aee2d8bf93c27757aca0380c524d56558bd913",
          "sha1": "7481f327264d9fe1eeb32f3479e5720bc3a72246",
          "md5": "e958182712f4415a32814c36b4a82563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a91-android-0.8.6.aar",
          "url": "ble-characteristic-u2a91-android-0.8.6.aar",
          "size": 3141,
          "sha512": "e22aec2fba30c702d302017de36a9346265921e92e5f4e21cc8c0257ef814a7e61f32d6e4c4428bd8f5050dd4fc3a0a4ff5b23ecb787caadcd7858188dd9b16b",
          "sha256": "44d6f96095e447c7e923f9a695aee2d8bf93c27757aca0380c524d56558bd913",
          "sha1": "7481f327264d9fe1eeb32f3479e5720bc3a72246",
          "md5": "e958182712f4415a32814c36b4a82563"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a91-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a91-android-0.8.6-sources.jar",
          "size": 2229,
          "sha512": "acfec0bae21caf74030047c1311f7c54c48c1129c8aed827588933fa64b0210354be6cee85952aeee2773f9518f42d24d1727664d8663a4fdee379c09a4a8323",
          "sha256": "4abf03747acfdcadc3768013e2ef7192ebf05a3b311cf6f0b24a5868d6134cec",
          "sha1": "3ae5ca081644ac731629a14f2e5fd65010d12b14",
          "md5": "95b733f7465240d5c6f6345e8a6afbc7"
        }
      ]
    }
  ]
}
