{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b21",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.7.jar",
          "url": "ble-characteristic-u2b21-0.8.7.jar",
          "size": 1439,
          "sha512": "1b1f9e32529341761ec8741c6b4832473da54c22f58fa2450c5991c2dc1b71f2f48bd18bd9c0bd6f5a7669295bd325b189e8a90781cce66d7f294e08204e9cab",
          "sha256": "bc3eb246d83ca4fde36860329abd6aac9efc13bcd7fd7a93cd2251cffccb29e0",
          "sha1": "22f44813e7141c08d1092178ba95a897dc8df38f",
          "md5": "fd33e8790852468f2ca6283dfa1dc001"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.7.jar",
          "url": "ble-characteristic-u2b21-0.8.7.jar",
          "size": 1439,
          "sha512": "1b1f9e32529341761ec8741c6b4832473da54c22f58fa2450c5991c2dc1b71f2f48bd18bd9c0bd6f5a7669295bd325b189e8a90781cce66d7f294e08204e9cab",
          "sha256": "bc3eb246d83ca4fde36860329abd6aac9efc13bcd7fd7a93cd2251cffccb29e0",
          "sha1": "22f44813e7141c08d1092178ba95a897dc8df38f",
          "md5": "fd33e8790852468f2ca6283dfa1dc001"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b21-0.8.7-javadoc.jar",
          "size": 107116,
          "sha512": "620fd44f006334531693a4a01c9d615c31170702dfffeb4e753c513b38737cd69a41e78e80e8912eecb32ca0cb41cbce7aba8956d40c4dbd4d305b79dead26c8",
          "sha256": "fbd176334109eb698a439fd7a1fd80e13fcfd6eae67d3fc7257ae288d2c5dac4",
          "sha1": "8409d9bb53278368f77a0711ce59242c24317c4f",
          "md5": "8123f4fcc4d650a1952c413427d286cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b21-0.8.7-sources.jar",
          "size": 1428,
          "sha512": "b0b5acb792d6e897db4d470b99b56cce02bd0ec24efa4f09bb34d2f490561f14f317c9b3b55f681ad0735add3415dd1d3be12a5458259fa19dcec59f3b7aab19",
          "sha256": "b9fac7afd7229aa2a98eb39ba62d62f97fcdb7fcc677aa4c8439eb96e6f5895b",
          "sha1": "c2ca55ff26cf1056ce303d92ec2615cd091ecf17",
          "md5": "7ff635a0c919599cb541b84f96284f17"
        }
      ]
    }
  ]
}
