{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b25",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.9.jar",
          "url": "ble-characteristic-u2b25-0.8.9.jar",
          "size": 1473,
          "sha512": "d2e37938cc03bd9b467a25fb122924e260cda144b40dedbb9f635e1fdd51870969425833608bdf51cb290fccf3e3017d0f7645fe68d3f0d063eaeba689af355c",
          "sha256": "24f9e9d1b1bb5bfd40c18f3a176187a22b0625b1246b850aaa00daa2172da4b1",
          "sha1": "cbc129746e884f5542d702eefe87e63874b5a76d",
          "md5": "83e2e8cc259e6f9f3cde04506afc1104"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.9.jar",
          "url": "ble-characteristic-u2b25-0.8.9.jar",
          "size": 1473,
          "sha512": "d2e37938cc03bd9b467a25fb122924e260cda144b40dedbb9f635e1fdd51870969425833608bdf51cb290fccf3e3017d0f7645fe68d3f0d063eaeba689af355c",
          "sha256": "24f9e9d1b1bb5bfd40c18f3a176187a22b0625b1246b850aaa00daa2172da4b1",
          "sha1": "cbc129746e884f5542d702eefe87e63874b5a76d",
          "md5": "83e2e8cc259e6f9f3cde04506afc1104"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2b25-0.8.9-javadoc.jar",
          "size": 107244,
          "sha512": "471186657810797e68f678dbe3ef00093d7a35d048677c047c68c80ac879d7cf8ee8b540b6f40336fb07944b65c57f07b9c064ac356ce45f7c755d504cc76c80",
          "sha256": "2c5832b88ba664e1cc5edb6bc4ca46e0a08dc487f4be06a40867c31094be0d6e",
          "sha1": "636f9de69a41382e7d51daad877d976646f61fc2",
          "md5": "2f677ca3b16e9cee7e566d01b5364df8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.9-sources.jar",
          "url": "ble-characteristic-u2b25-0.8.9-sources.jar",
          "size": 1467,
          "sha512": "c649ae4f84a259783603b4b1e904e3113762079b72f35fc71d51d9d3a737f67bbb69bed567db1e56d628b7412750bc10d22f48ac586658c8ddf9fe9a0ab97758",
          "sha256": "3bb50cf8abd29d9bded4b20fdc4edbb684822abdc34a9a3c8af861e302e1e63d",
          "sha1": "1fef18ef7255cda018561b568a5596833fb63268",
          "md5": "f5811f803e2856b231e4f5c09a05a927"
        }
      ]
    }
  ]
}
