{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0f",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.14.jar",
          "url": "ble-characteristic-u2b0f-0.8.14.jar",
          "size": 2077,
          "sha512": "3c7e4e0098c7a08a9cb3ad7d357af82c03258dc0338f238352ac13d002251fe10d9f5dec72976a3ecbd1a5bd3c36471cdc9f9232f99b8b29a8195a4773f9780e",
          "sha256": "8a0d973e454069f594129b62799f9d54a6021a8e37ccb59235ca66cbc1c9f219",
          "sha1": "27f2ae3ad6bb236db8413a281de116973daf2040",
          "md5": "3e66681754015172fdc71763bb532ac6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.14.jar",
          "url": "ble-characteristic-u2b0f-0.8.14.jar",
          "size": 2077,
          "sha512": "3c7e4e0098c7a08a9cb3ad7d357af82c03258dc0338f238352ac13d002251fe10d9f5dec72976a3ecbd1a5bd3c36471cdc9f9232f99b8b29a8195a4773f9780e",
          "sha256": "8a0d973e454069f594129b62799f9d54a6021a8e37ccb59235ca66cbc1c9f219",
          "sha1": "27f2ae3ad6bb236db8413a281de116973daf2040",
          "md5": "3e66681754015172fdc71763bb532ac6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2b0f-0.8.14-javadoc.jar",
          "size": 86631,
          "sha512": "98b32ebaec39024644ded9c75ea2b0cf2fd7654443f9a8efc91c2fb738ef548adf357ed6821fc8339eeeffb9bea87c0386f2047085d07eb8e9bf6d7da86c77a5",
          "sha256": "54a69e1f18703d0a06c7f9a4938bbae0a903fcc5b5723e15316e78c1b310d002",
          "sha1": "ccbb97c479c3719e97193b8abff02ee5de61c4a2",
          "md5": "149e8e2b35886286bb771925bcda2c92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.14-sources.jar",
          "url": "ble-characteristic-u2b0f-0.8.14-sources.jar",
          "size": 1876,
          "sha512": "18cdecced3da66f10ffa5e42ac608c6ce8b518e81f199a5aaab9794aa5c154a4795194fae18d55dcea45f93392a3ef2d14da4c025ebd8b165f3010e73134c556",
          "sha256": "2b4851e9674f783dc9257334b712fdb158d15228cc52ddfedc362ae40a88fed1",
          "sha1": "932b52dda7e7d0622c6e5390dad11a43f8f56119",
          "md5": "a0a259e0af7b9f71f3f89228cbe172de"
        }
      ]
    }
  ]
}
