{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-cps-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-cps-android-0.4.4.aar",
          "url": "ble-service-peripheral-cps-android-0.4.4.aar",
          "size": 18568,
          "sha512": "58a5c04c5512c8e2c2c1fe8f131e9cfc0c5efe34750a70116ef95e08394772d161a28b533c98dbbc95b5edc1b0175a2300d916401983091bdf88164c4f5cb1e4",
          "sha256": "d1607c281299fa46f10392f3a25f36eea36f52a839a008879a430edb3382359d",
          "sha1": "ae7314991f83780a1ef305c453c3a4bbdc23d39a",
          "md5": "c57812ed2ae9d18896836d94889e0e07"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-cps-android-0.4.4.aar",
          "url": "ble-service-peripheral-cps-android-0.4.4.aar",
          "size": 18568,
          "sha512": "58a5c04c5512c8e2c2c1fe8f131e9cfc0c5efe34750a70116ef95e08394772d161a28b533c98dbbc95b5edc1b0175a2300d916401983091bdf88164c4f5cb1e4",
          "sha256": "d1607c281299fa46f10392f3a25f36eea36f52a839a008879a430edb3382359d",
          "sha1": "ae7314991f83780a1ef305c453c3a4bbdc23d39a",
          "md5": "c57812ed2ae9d18896836d94889e0e07"
        }
      ]
    }
  ]
}
