{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4d-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a4d-android-0.8.6.aar",
          "size": 3008,
          "sha512": "d35fa98736bc34ef70014a4e2bdbd063f6c2eadc410a09b32e6759056a98c7ba36946b31ee68d477d49f38c3049122795f421f4dff781dba4dd6175e8a4e3916",
          "sha256": "2554566166c10100682dea81a7dbb949958ce518ba0fe5883b06886109505695",
          "sha1": "e9907d2ceccef02790ba8200c9d9c4e9dd19216a",
          "md5": "19af6249227fd84f861e9fb73fb37289"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a4d-android-0.8.6.aar",
          "size": 3008,
          "sha512": "d35fa98736bc34ef70014a4e2bdbd063f6c2eadc410a09b32e6759056a98c7ba36946b31ee68d477d49f38c3049122795f421f4dff781dba4dd6175e8a4e3916",
          "sha256": "2554566166c10100682dea81a7dbb949958ce518ba0fe5883b06886109505695",
          "sha1": "e9907d2ceccef02790ba8200c9d9c4e9dd19216a",
          "md5": "19af6249227fd84f861e9fb73fb37289"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a4d-android-0.8.6-sources.jar",
          "size": 2102,
          "sha512": "84643ab1878dfa84ab0c2ef0f14f8ef2c1264daf69b32edd3bfebd28cc5a602b16cb4c026d25e2f767d64e07d92778cd2a56687f670db48f4b101fc9cb25cc11",
          "sha256": "41cd1db5556223c8fc037f3f06a1d0bd98d6d69209d80696fa4a3f5fb6661fea",
          "sha1": "60257571588bbe6f1672fe13da688bd0209048e6",
          "md5": "075f0e24476cd632eb24eb66abffe53b"
        }
      ]
    }
  ]
}
