{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bcs-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bbm5joczcbdv3lahen7alio5fa"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c-android",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-android-0.1.1.aar",
          "url": "ble-service-bcs-android-0.1.1.aar",
          "size": 1205,
          "sha512": "c9d90e43a3a8248e3b43f1c37f5d651f3df41a57ac50baa99dcde705a3511084b4ed4b2bec3b546518d0507017405b2d9d306cf3373089c37037f42ced2755d0",
          "sha256": "773719b4f7747e86f0452d1c6ee97769bd155de222778b16f4616b4320653f63",
          "sha1": "de4f0ee7bf2c32657476e9f08e046bfee4b30115",
          "md5": "8b955c3434efe9158a183ada84c12924"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c-android",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-android-0.1.1.aar",
          "url": "ble-service-bcs-android-0.1.1.aar",
          "size": 1205,
          "sha512": "c9d90e43a3a8248e3b43f1c37f5d651f3df41a57ac50baa99dcde705a3511084b4ed4b2bec3b546518d0507017405b2d9d306cf3373089c37037f42ced2755d0",
          "sha256": "773719b4f7747e86f0452d1c6ee97769bd155de222778b16f4616b4320653f63",
          "sha1": "de4f0ee7bf2c32657476e9f08e046bfee4b30115",
          "md5": "8b955c3434efe9158a183ada84c12924"
        }
      ]
    }
  ]
}
