{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-central",
          "version": {
            "requires": "0.7.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-android-0.4.5.aar",
          "url": "ble-service-central-android-0.4.5.aar",
          "size": 4861,
          "sha512": "ad4b7cfa058f792ca7b7070e245aced0dcb727e407c158aa712765e594e42eec6b881bf755c7606a33a037aaded3331c430ad1cd28f76c72761a0e79d2c4b88a",
          "sha256": "f4037b40936d75e67456d1aa182182a29ba2e21eebf909d1aafad46b6f4f2ca3",
          "sha1": "f869cf7d431dd7fbf1bdab2c5fa1a4e5bfe0cd6a",
          "md5": "eafbf6a90973e7de14bd7628d8b64cd3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-central",
          "version": {
            "requires": "0.7.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-android-0.4.5.aar",
          "url": "ble-service-central-android-0.4.5.aar",
          "size": 4861,
          "sha512": "ad4b7cfa058f792ca7b7070e245aced0dcb727e407c158aa712765e594e42eec6b881bf755c7606a33a037aaded3331c430ad1cd28f76c72761a0e79d2c4b88a",
          "sha256": "f4037b40936d75e67456d1aa182182a29ba2e21eebf909d1aafad46b6f4f2ca3",
          "sha1": "f869cf7d431dd7fbf1bdab2c5fa1a4e5bfe0cd6a",
          "md5": "eafbf6a90973e7de14bd7628d8b64cd3"
        }
      ]
    }
  ]
}
