{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9d",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.13.jar",
          "url": "ble-characteristic-u2b9d-0.8.13.jar",
          "size": 1468,
          "sha512": "1a71cf212b0229e9236ba62f3af706c4629ee8618da56822369e3344e6f0940f7630f54f95bb48957f3488fe0827ff725709ae4f3bcf905933fbcc00a962e9ba",
          "sha256": "c839460753dfb260352edfb7c701fd8bac484c706247eb639b83bbe444887595",
          "sha1": "27c51f47169a2e03a64c96e049fa9bb20b9f463d",
          "md5": "f801461e398f55911d90eb6083d5f5ee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.13.jar",
          "url": "ble-characteristic-u2b9d-0.8.13.jar",
          "size": 1468,
          "sha512": "1a71cf212b0229e9236ba62f3af706c4629ee8618da56822369e3344e6f0940f7630f54f95bb48957f3488fe0827ff725709ae4f3bcf905933fbcc00a962e9ba",
          "sha256": "c839460753dfb260352edfb7c701fd8bac484c706247eb639b83bbe444887595",
          "sha1": "27c51f47169a2e03a64c96e049fa9bb20b9f463d",
          "md5": "f801461e398f55911d90eb6083d5f5ee"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2b9d-0.8.13-javadoc.jar",
          "size": 86032,
          "sha512": "f735ea3a8fae187650aaeae1aad5306d9f1bbc0bf8e63f100cd975cf99258d0fd9092ed76e0a55c8400805adc5d0d41a9532ecd4b15cdedfd25876a84ba2440c",
          "sha256": "7710defad90fd97e04562d6da29f52e0b03f1dfcbbb3d0c00da6346033653ed2",
          "sha1": "7d06df2891ef55ebd4eee7d370c2218994facea8",
          "md5": "50832744749ccb084c66613f544aa4f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9d-0.8.13-sources.jar",
          "url": "ble-characteristic-u2b9d-0.8.13-sources.jar",
          "size": 1466,
          "sha512": "ef3194126355ea019fd90345fe474fee374c526b8171488e9dd39fed2527adf9dda2fd793ccd11552e39a9229e7e03894c47fe1d8cb3be823f21af00bc0b2528",
          "sha256": "cf90adf010ee57b5c43218d822236f5b8f379182e28b428750051e8988772f2d",
          "sha1": "9e918c0701b4cf2885f6be796e33b0f248857af1",
          "md5": "7aa90cbe274275fe7e72b5199be61031"
        }
      ]
    }
  ]
}
