{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd9",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.6.jar",
          "url": "ble-characteristic-u2bd9-0.8.6.jar",
          "size": 1943,
          "sha512": "ab3083e4b3fa9c82da43c79e2a77b542509e83fa09a655907e8ae98974def067c75cbd5c5ba74a05054fb6578fe5ebcec1f1d0f53fe6ebab3d1837eccfca08cd",
          "sha256": "cfc80039b2680cd7241d1c4e5bb5ab707bd1c5134b96bff23df6961833a8c108",
          "sha1": "d1536b0eb8cff132dd3ea88bbf08bb0432e9a50f",
          "md5": "9eb7a544473f433e9c01b45e4c8d6e0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.6.jar",
          "url": "ble-characteristic-u2bd9-0.8.6.jar",
          "size": 1943,
          "sha512": "ab3083e4b3fa9c82da43c79e2a77b542509e83fa09a655907e8ae98974def067c75cbd5c5ba74a05054fb6578fe5ebcec1f1d0f53fe6ebab3d1837eccfca08cd",
          "sha256": "cfc80039b2680cd7241d1c4e5bb5ab707bd1c5134b96bff23df6961833a8c108",
          "sha1": "d1536b0eb8cff132dd3ea88bbf08bb0432e9a50f",
          "md5": "9eb7a544473f433e9c01b45e4c8d6e0d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2bd9-0.8.6-javadoc.jar",
          "size": 107968,
          "sha512": "52470288f719f81a041123f947bd1cf5155c35d022788c07e60cfb79a04d4042d1da9395e434a2dad1cbb11c3eb6ac854258c2ec8fb00f05ac05450a6f3a48bb",
          "sha256": "91628bba63c1388ad4d8cb9e7a8a24962811a789f6d5106606835bd62d95180f",
          "sha1": "97a2be2a9b1c59b3cc21683f4a323de87206b32b",
          "md5": "750b4d41a724f67ac5dd02996c05da7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bd9-0.8.6-sources.jar",
          "size": 1952,
          "sha512": "d6bb74a1cd2cde68d010f6690daecb6651001a3f7c6003f709993fdd6053088585a18de13f8ddc4df39c80945dfc8fa8d68d1586c1bb5fdbfbb608a85b376711",
          "sha256": "ccfbd70aba3b8bb69ad70ea10d4bae15d585522cc05fee293149b3321f0437cd",
          "sha1": "5ca4ca8f65826fc99232c4203df91d508d410044",
          "md5": "3d7687344bce3e47e4726e65d9882d5b"
        }
      ]
    }
  ]
}
