{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a98",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-0.8.7.jar",
          "url": "ble-characteristic-u2a98-0.8.7.jar",
          "size": 1833,
          "sha512": "094a0260b061d71fc1c53c84881958fd640cdc9e698fe47154fb478a9624d16787f1b03057b8c4be8aaba77bbae08f7d33c2506fef3dedbcde7d6388d17e7286",
          "sha256": "f4b871108d2354379f817b5ec964dc0c0db37e1d055eb24dc2fd2a6045fbb6cf",
          "sha1": "35395042950dce97fb4c83f0d3f3e38d17bedaae",
          "md5": "4778bf795f8764bff922c248ac2fb273"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-0.8.7.jar",
          "url": "ble-characteristic-u2a98-0.8.7.jar",
          "size": 1833,
          "sha512": "094a0260b061d71fc1c53c84881958fd640cdc9e698fe47154fb478a9624d16787f1b03057b8c4be8aaba77bbae08f7d33c2506fef3dedbcde7d6388d17e7286",
          "sha256": "f4b871108d2354379f817b5ec964dc0c0db37e1d055eb24dc2fd2a6045fbb6cf",
          "sha1": "35395042950dce97fb4c83f0d3f3e38d17bedaae",
          "md5": "4778bf795f8764bff922c248ac2fb273"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a98-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a98-0.8.7-javadoc.jar",
          "size": 109251,
          "sha512": "ea606dbb6726ca568217054c4d6c806d53c42451b165c001171d818ed7f7850249dc9686d623e08a482c2a7a3ba6a7bbf3564e1926471859d4c164783f730292",
          "sha256": "e1f3e03c75107f63810225445359c1e1b269556f3aa2d31149fff37bc8ae63d5",
          "sha1": "8705060f9c7dab36e4fc9b0768e29e664f5ca26f",
          "md5": "49dfe3757186bc068ceb0f786a6bd701"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a98-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a98-0.8.7-sources.jar",
          "size": 1653,
          "sha512": "b4d7840938a577cafd0f2df2968250569ecfb27ea1a6c243755110c516cde13deb5f6eca7821bb85d6b77febf933873031659e85c94ffe4d8d82c9919a84c26a",
          "sha256": "a2fa1ae9a0b98f515caae38eeffd916a678acb7aa288d4e066f473fa725d8baa",
          "sha1": "47c7d9d2576cd32ceb0173f546c80745628a4525",
          "md5": "ee7afd6231963be7525b381f924df469"
        }
      ]
    }
  ]
}
