{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba5-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba5",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba5-android-0.8.12.aar",
          "url": "ble-characteristic-u2ba5-android-0.8.12.aar",
          "size": 3224,
          "sha512": "05eed0da7702f4ed0f6bd8f8a28ee9f9e59f5dde415b62fa41ac68d6e6924219b109178dd43ec60f9f896d7f3c8015f82d1e8c64c382a931fca9f10b21be0c88",
          "sha256": "16e2457059e9902e63004d4563deeb0e15aa54164d29fc8678a16253a6b614ea",
          "sha1": "4026f775b3dfe9f74dc6fca8ece0001ffdfdeda2",
          "md5": "60bf3c4b2002b718c896577d77dbb36b"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba5",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba5-android-0.8.12.aar",
          "url": "ble-characteristic-u2ba5-android-0.8.12.aar",
          "size": 3224,
          "sha512": "05eed0da7702f4ed0f6bd8f8a28ee9f9e59f5dde415b62fa41ac68d6e6924219b109178dd43ec60f9f896d7f3c8015f82d1e8c64c382a931fca9f10b21be0c88",
          "sha256": "16e2457059e9902e63004d4563deeb0e15aa54164d29fc8678a16253a6b614ea",
          "sha1": "4026f775b3dfe9f74dc6fca8ece0001ffdfdeda2",
          "md5": "60bf3c4b2002b718c896577d77dbb36b"
        }
      ]
    }
  ]
}
