{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a92-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.7.aar",
          "url": "ble-characteristic-u2a92-android-0.8.7.aar",
          "size": 3190,
          "sha512": "87aa546b34ac6bf85430295f2123f9e7f712abeaa2dbeafc84e90f9f0cca9e3246cd6952024e4f86018a72acb18d1377951acc537661fe964514c2e83720df1f",
          "sha256": "e2c4df487d2afad24640c633785a78e00db9815caa93a619c750d321887dcc6b",
          "sha1": "2495de021bf96390ea2f438bab428c21e41bfdb8",
          "md5": "b95c223207f43d904411c15874aaa4d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.7.aar",
          "url": "ble-characteristic-u2a92-android-0.8.7.aar",
          "size": 3190,
          "sha512": "87aa546b34ac6bf85430295f2123f9e7f712abeaa2dbeafc84e90f9f0cca9e3246cd6952024e4f86018a72acb18d1377951acc537661fe964514c2e83720df1f",
          "sha256": "e2c4df487d2afad24640c633785a78e00db9815caa93a619c750d321887dcc6b",
          "sha1": "2495de021bf96390ea2f438bab428c21e41bfdb8",
          "md5": "b95c223207f43d904411c15874aaa4d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a92-android-0.8.7-sources.jar",
          "size": 2174,
          "sha512": "1ec6f7db44f2ecc9faffd227e4f0a7104eb5cb61e5c4070231ebcb0c764e501455b547fe01b354fb5673f28ea2d29d668b712e1c86cd5c197d46e72ce30ed9a2",
          "sha256": "edebebc52d0b42c3d9672cf31efe7c6425a625595de954667144c5b4b4171b59",
          "sha1": "c4f2129170721847ffd9312ef05bafcd978fce9a",
          "md5": "5ef46603d8c7ba0661889b94a8a7623f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a92-android-0.8.7-javadoc.jar",
          "size": 270635,
          "sha512": "27aafcfc022f7ce72a4ea6d25a920a7bc43ea97a6faed8bf9918a0004e7992d8df44ed8ff2931dc1bf94b9c806d3a7af8fb87e17b817faabf1dd0eb038a58a9f",
          "sha256": "01ae36e13f9ed84b3ea5263fad53bcbaa826984c1bcee928429c3d2c14ba89a8",
          "sha1": "fa79deb67a9aa89a7a1f4094bcdbac4ef280a7a6",
          "md5": "a0d3ccbde7733455fc24de261f9a3c1f"
        }
      ]
    }
  ]
}
