{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a49",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a49-0.8.12.jar",
          "url": "ble-characteristic-u2a49-0.8.12.jar",
          "size": 2947,
          "sha512": "3ca1431a6854669863733e34045f2691fdea93ac859170066461722d64f654d300fc5d15fa4f4bd1dc214b5bc489c62e043ebe14f4bf3a78962664accdd98d04",
          "sha256": "08920b26850956142cdf30bb5daf11b306f1c0874c3863b1579d5a77b17976ab",
          "sha1": "79ba2748102d725845fae33dcf3b31e20d15f7b1",
          "md5": "6c4fc196b084a313c5ceeedb8cd32eb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a49-0.8.12.jar",
          "url": "ble-characteristic-u2a49-0.8.12.jar",
          "size": 2947,
          "sha512": "3ca1431a6854669863733e34045f2691fdea93ac859170066461722d64f654d300fc5d15fa4f4bd1dc214b5bc489c62e043ebe14f4bf3a78962664accdd98d04",
          "sha256": "08920b26850956142cdf30bb5daf11b306f1c0874c3863b1579d5a77b17976ab",
          "sha1": "79ba2748102d725845fae33dcf3b31e20d15f7b1",
          "md5": "6c4fc196b084a313c5ceeedb8cd32eb7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a49-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a49-0.8.12-javadoc.jar",
          "size": 92554,
          "sha512": "c92a39f4da305da8bc603662bf6b3ea3c4fe2e1a77edfd1c9aee01b83721563e3e2196482684a1df783fff4c711f6f2e0c1b203cd01bc8a4211aa65376710f19",
          "sha256": "8692f6009a39c10b36a44522bf1c117bdaef4c147250d74a72e89d199de6619d",
          "sha1": "fd217ab9d2f927df2a98c5056f1cd0bce6ae9210",
          "md5": "77b88e583040619ef43decfce5871909"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a49-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a49-0.8.12-sources.jar",
          "size": 3192,
          "sha512": "5492b7b0b803dbc1db1a88f3cb0da5562ef8ea2d2567747d22604af3bbc605b8d5e4083ef484da7d03854aca7bfb057a4f3a1697dca779ce3bb7755cba05acea",
          "sha256": "febf8e3f6687cf6f318e4414247b0a0e27a94bf311adbc3979a39a89295457c7",
          "sha1": "96de4f4ef06ab27ae7c5b3495fd5659fdba94a69",
          "md5": "99c83ea2b495f53ed3ffd279ef2f3764"
        }
      ]
    }
  ]
}
