{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a52",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a52-0.8.3.jar",
          "url": "ble-characteristic-u2a52-0.8.3.jar",
          "size": 4253,
          "sha512": "21bb3796bdc2b24192dfb6f37247affd229e430b86fa0cf2e65eba03f363022d132e2c9e7f584c4f1025b52acabc46df06986732071ffa00f1840df478d629d7",
          "sha256": "9077aec133dc286f89e72c3c0fc782c7ed7449c82d62443c9021d9ae0766e307",
          "sha1": "61d78deafe92b5d03b0da5cbc2eb22cf5da4474b",
          "md5": "55b0f53d7947e778381fbaa4a7b17926"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a52-0.8.3.jar",
          "url": "ble-characteristic-u2a52-0.8.3.jar",
          "size": 4253,
          "sha512": "21bb3796bdc2b24192dfb6f37247affd229e430b86fa0cf2e65eba03f363022d132e2c9e7f584c4f1025b52acabc46df06986732071ffa00f1840df478d629d7",
          "sha256": "9077aec133dc286f89e72c3c0fc782c7ed7449c82d62443c9021d9ae0766e307",
          "sha1": "61d78deafe92b5d03b0da5cbc2eb22cf5da4474b",
          "md5": "55b0f53d7947e778381fbaa4a7b17926"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a52-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2a52-0.8.3-javadoc.jar",
          "size": 118016,
          "sha512": "f498a624eab71798fa6d374471f4ee1e77ac7ee15249155a40f9ee076a0455b408e1e25ce1af9271c83248f86a755494bc5e5699ee4bf39263edf42d8904f79f",
          "sha256": "4911b60ac2bd1e7fee746ba8285c76d5f5e6dd09eedb760b6a18aa8b1269bfa8",
          "sha1": "78fc04bbb4f0960ceb98d00af0eeabc6189534e2",
          "md5": "81a869dd92417dc4bc86639b50c62a54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a52-0.8.3-sources.jar",
          "url": "ble-characteristic-u2a52-0.8.3-sources.jar",
          "size": 3682,
          "sha512": "8c3d7ce404bff357924e21285e5c7dd05f93fc3efcad7cf6b0c4eebaa81eb1ccfd986066a4d3c35d92d0ded0a3823c3041f3180d6706ff3b148af70461ea761b",
          "sha256": "51c6650fea089dd1b27f94057e51042e830fb2325757815aeeb9e6c898204863",
          "sha1": "6778ff01eeaff25a829b36960994d2c840c71a12",
          "md5": "2c9640883017b335b648a4ceebf67b1b"
        }
      ]
    }
  ]
}
