{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a92-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.2.2.aar",
          "url": "ble-characteristic-u2a92-android-0.2.2.aar",
          "size": 2914,
          "sha512": "4cfd4b7f97449f4a0db4db3370f4f381475298dc47cd06b8745f617f713e59a8bb2f385e8cd5481c821f68d51117310991afd8a9b18a424ab31fbe08c39a22e3",
          "sha256": "7f644b965d346b43755389c16357a341b3f163283023cc5b73464dfc0920accc",
          "sha1": "0fe2e73241956e22de6609f9d9fcc6430e7b42be",
          "md5": "2cb39d68ff8fd247e2fdc81ae7b982a3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.2.2.aar",
          "url": "ble-characteristic-u2a92-android-0.2.2.aar",
          "size": 2914,
          "sha512": "4cfd4b7f97449f4a0db4db3370f4f381475298dc47cd06b8745f617f713e59a8bb2f385e8cd5481c821f68d51117310991afd8a9b18a424ab31fbe08c39a22e3",
          "sha256": "7f644b965d346b43755389c16357a341b3f163283023cc5b73464dfc0920accc",
          "sha1": "0fe2e73241956e22de6609f9d9fcc6430e7b42be",
          "md5": "2cb39d68ff8fd247e2fdc81ae7b982a3"
        }
      ]
    }
  ]
}
