{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a36",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ufyqgw2bwjavffyv4q7eapomny"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a36-0.2.7.jar",
          "url": "ble-characteristic-u2a36-0.2.7.jar",
          "size": 3484,
          "sha512": "9955fccd85e8ee7a30ee0188eed05604377551c9614d9b359e05d6303c0ba8c1bf32e4e5e45294b8a31617be2f480923e797aeb35c8b0816d073ab5d231fa7b4",
          "sha256": "382ca91f69921a9d802904333adb498f759ab3701fbb22d1aab97ad2ba9cc40b",
          "sha1": "dfc6bb21d1f5d75327ca946a7a7a262b83a9f170",
          "md5": "91e333fe049d91798c3abb204f475824"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a36-0.2.7.jar",
          "url": "ble-characteristic-u2a36-0.2.7.jar",
          "size": 3484,
          "sha512": "9955fccd85e8ee7a30ee0188eed05604377551c9614d9b359e05d6303c0ba8c1bf32e4e5e45294b8a31617be2f480923e797aeb35c8b0816d073ab5d231fa7b4",
          "sha256": "382ca91f69921a9d802904333adb498f759ab3701fbb22d1aab97ad2ba9cc40b",
          "sha1": "dfc6bb21d1f5d75327ca946a7a7a262b83a9f170",
          "md5": "91e333fe049d91798c3abb204f475824"
        }
      ]
    }
  ]
}
