{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae7",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae7-0.5.0.jar",
          "url": "ble-characteristic-u2ae7-0.5.0.jar",
          "size": 1888,
          "sha512": "bd96dc8c69fd16cff523db7170843c38c944f84d08e45f519639872e463259b465f074490ed19d6b70c1897b9185e9ebfac719ba3baf1fafeefebde8109352e5",
          "sha256": "980d6aa23b14a1410eecf8aa36415cfd078de88c55b794c9b7310b4c89b16580",
          "sha1": "12c752f1d0bf861fc8c3c78c2753bc8037a0f46a",
          "md5": "7ddc6a4a1edc69d3504d9f2eb12b17dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae7-0.5.0.jar",
          "url": "ble-characteristic-u2ae7-0.5.0.jar",
          "size": 1888,
          "sha512": "bd96dc8c69fd16cff523db7170843c38c944f84d08e45f519639872e463259b465f074490ed19d6b70c1897b9185e9ebfac719ba3baf1fafeefebde8109352e5",
          "sha256": "980d6aa23b14a1410eecf8aa36415cfd078de88c55b794c9b7310b4c89b16580",
          "sha1": "12c752f1d0bf861fc8c3c78c2753bc8037a0f46a",
          "md5": "7ddc6a4a1edc69d3504d9f2eb12b17dc"
        }
      ]
    }
  ]
}
