{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9e-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sipxf3vz2bcx5mgcg6vcjbnlti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.1.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.1.aar",
          "size": 2878,
          "sha512": "f1fd7cfe01ddaa585999a942281f36a0fa214cae6f48ab4a0cd86a935e214ab4b372f148725da40c35e60e3e7f98b778e5b08335cd2692d67937052557224662",
          "sha256": "f3468950ffa1592111d779da062fb1a77ae1ad91285c35ba710710d690fedfda",
          "sha1": "53c9b6ec5a419ca62826834fdffc8f4e001027e4",
          "md5": "2b73d495486fc93d809af386cb117f0b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.1.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.1.aar",
          "size": 2878,
          "sha512": "f1fd7cfe01ddaa585999a942281f36a0fa214cae6f48ab4a0cd86a935e214ab4b372f148725da40c35e60e3e7f98b778e5b08335cd2692d67937052557224662",
          "sha256": "f3468950ffa1592111d779da062fb1a77ae1ad91285c35ba710710d690fedfda",
          "sha1": "53c9b6ec5a419ca62826834fdffc8f4e001027e4",
          "md5": "2b73d495486fc93d809af386cb117f0b"
        }
      ]
    }
  ]
}
