{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a81-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a81",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-android-0.2.4.aar",
          "url": "ble-characteristic-u2a81-android-0.2.4.aar",
          "size": 3152,
          "sha512": "4c236fb6e74566ade57668ae35006fabba678771564ae8325d8719811c9ddb3b89ad90e30400d94a3b58a77340af3a7d60e975f77d09b5fc5789521215190c13",
          "sha256": "32b3c986b7f5f917984735bfb8eb1f67192fef09327d3401d3313b3985d15362",
          "sha1": "80352b7066e1cb09039708f99f59caa7edc73e9d",
          "md5": "169f1b9b7d36d3e54607c0f19872a4c8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a81",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-android-0.2.4.aar",
          "url": "ble-characteristic-u2a81-android-0.2.4.aar",
          "size": 3152,
          "sha512": "4c236fb6e74566ade57668ae35006fabba678771564ae8325d8719811c9ddb3b89ad90e30400d94a3b58a77340af3a7d60e975f77d09b5fc5789521215190c13",
          "sha256": "32b3c986b7f5f917984735bfb8eb1f67192fef09327d3401d3313b3985d15362",
          "sha1": "80352b7066e1cb09039708f99f59caa7edc73e9d",
          "md5": "169f1b9b7d36d3e54607c0f19872a4c8"
        }
      ]
    }
  ]
}
