{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-declaration",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-declaration-0.8.6.jar",
          "url": "ble-core-constants-declaration-0.8.6.jar",
          "size": 2677,
          "sha512": "bf1800e30482107eb450eaa8d7d743460d1b13ae20b617de5babe0dc15decd066af806ff7051e4482f4924d6ac4242e359cfa88932218b566eec039313c9718f",
          "sha256": "793e32e8ef82c1c5e09228aa2bde95f1f0e9c2b1c960caabe4d63cd50bfb1d66",
          "sha1": "3ccd9bf83a11aa525c0b0b177075c0df678a7472",
          "md5": "52afe4855bad68f037848bb4b1741dd7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-declaration-0.8.6.jar",
          "url": "ble-core-constants-declaration-0.8.6.jar",
          "size": 2677,
          "sha512": "bf1800e30482107eb450eaa8d7d743460d1b13ae20b617de5babe0dc15decd066af806ff7051e4482f4924d6ac4242e359cfa88932218b566eec039313c9718f",
          "sha256": "793e32e8ef82c1c5e09228aa2bde95f1f0e9c2b1c960caabe4d63cd50bfb1d66",
          "sha1": "3ccd9bf83a11aa525c0b0b177075c0df678a7472",
          "md5": "52afe4855bad68f037848bb4b1741dd7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-declaration-0.8.6-javadoc.jar",
          "url": "ble-core-constants-declaration-0.8.6-javadoc.jar",
          "size": 106888,
          "sha512": "d763cb2e53763e891f47b0e32e6a32e395e62885e6b66ad6a08be763c3491566256a8d993cb27a2983b3cdb3bf12ca3d238e18c4c042a4ddca40316941806287",
          "sha256": "43b05e8743af120c0aee7d2140126c4f51e9f327a94877868c21393c37ebf3ec",
          "sha1": "9d8eafdb9936d42435d657dca4928ab1e926ef2f",
          "md5": "c5a0834de84c7ddb2b6dfa421d3f0ed7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-declaration-0.8.6-sources.jar",
          "url": "ble-core-constants-declaration-0.8.6-sources.jar",
          "size": 1407,
          "sha512": "326fc36b2a2360ca8b4f05928646bb2cf0a7d179e405a51c9e809cec06d4cdebfb5449b1fbaeab25dce6e8e1f12e58cb177072054b2173e85d4bb094c5cef75d",
          "sha256": "072f5f79395117369b2426f1ecb33791db239ca4678701569d453235d9521edd",
          "sha1": "9214dd1a48fd2e6206401c2fa001f3900a7d7cc3",
          "md5": "d745326e07c88b38ece95dbaea5f34ef"
        }
      ]
    }
  ]
}
