{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1c-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-android-0.8.6.aar",
          "url": "ble-characteristic-u2a1c-android-0.8.6.aar",
          "size": 3409,
          "sha512": "0700ec67a0d4dcef989d76d0b5eb5c3707cc8bbfc5a98401c599d967c8f684f7094b449060676758565134cd141571f8255f8826753a362a19eb42f20b52efe1",
          "sha256": "fc396b707a0727d0642eeb26e32ff3981a1f12156b3679522a622436dfc4d115",
          "sha1": "495946026233c0767fac0445d09da9fcf2149ede",
          "md5": "d18993c2290c41561092cb6d62149425"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1c-android-0.8.6.aar",
          "url": "ble-characteristic-u2a1c-android-0.8.6.aar",
          "size": 3409,
          "sha512": "0700ec67a0d4dcef989d76d0b5eb5c3707cc8bbfc5a98401c599d967c8f684f7094b449060676758565134cd141571f8255f8826753a362a19eb42f20b52efe1",
          "sha256": "fc396b707a0727d0642eeb26e32ff3981a1f12156b3679522a622436dfc4d115",
          "sha1": "495946026233c0767fac0445d09da9fcf2149ede",
          "md5": "d18993c2290c41561092cb6d62149425"
        }
      ]
    }
  ]
}
