{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290d",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "3gjypjraujf5fc32spdlwmtq74"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-0.1.0.jar",
          "url": "ble-descriptor-u290d-0.1.0.jar",
          "size": 2303,
          "sha512": "47258649f17351038e929bbab5572da9def516b9623ef149c4c0328c20d7803c72d0b7c609bb8c9c84aa6eeddf460aa098eb3882312502c64000fc5f6f63818e",
          "sha256": "92d345921e0b8139350ea02072606d9ece9e751bfe277d2e63c070b662c09215",
          "sha1": "cda7c0b7c1ffba7d4124d80584b02e69c4806bd",
          "md5": "a713e81624305e48588b14ed846f601"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-0.1.0.jar",
          "url": "ble-descriptor-u290d-0.1.0.jar",
          "size": 2303,
          "sha512": "47258649f17351038e929bbab5572da9def516b9623ef149c4c0328c20d7803c72d0b7c609bb8c9c84aa6eeddf460aa098eb3882312502c64000fc5f6f63818e",
          "sha256": "92d345921e0b8139350ea02072606d9ece9e751bfe277d2e63c070b662c09215",
          "sha1": "cda7c0b7c1ffba7d4124d80584b02e69c4806bd",
          "md5": "a713e81624305e48588b14ed846f601"
        }
      ]
    }
  ]
}
