{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a39",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.12.jar",
          "url": "ble-characteristic-u2a39-0.8.12.jar",
          "size": 1885,
          "sha512": "940f21b672869f34e8a4dc5e514413dfe1316359ab18e920a63e8a36f7ddf4c6708f35722d9e2c698cac2a26e65312ae0e7849bc1f541e7b57e4e12bff4df790",
          "sha256": "bf73f2ed960957bc1eaa573b977d9d99034b1ae5fcd1db93804b698ab09dd65c",
          "sha1": "d82a2477c9d75a87544c5cd83acae28f2d14cff1",
          "md5": "0f4185adcca3f450e073b34b4622e101"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.12.jar",
          "url": "ble-characteristic-u2a39-0.8.12.jar",
          "size": 1885,
          "sha512": "940f21b672869f34e8a4dc5e514413dfe1316359ab18e920a63e8a36f7ddf4c6708f35722d9e2c698cac2a26e65312ae0e7849bc1f541e7b57e4e12bff4df790",
          "sha256": "bf73f2ed960957bc1eaa573b977d9d99034b1ae5fcd1db93804b698ab09dd65c",
          "sha1": "d82a2477c9d75a87544c5cd83acae28f2d14cff1",
          "md5": "0f4185adcca3f450e073b34b4622e101"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a39-0.8.12-javadoc.jar",
          "size": 109676,
          "sha512": "68375edec97586974cc13290174cd8416fbb6d4993f029bfe138703d745f4aedcfd2a04214522cac685adf41046765e7a2575ea500899f9cc7283b594ef7e859",
          "sha256": "0119f7d494324b3e008b2102e83de8ca75f37542193585098213261bb638bed1",
          "sha1": "1dfa03dc8cebdb63f3158a8e92fd5ade8d143337",
          "md5": "7838107b1ced475e19652cd5b93a2fc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a39-0.8.12-sources.jar",
          "size": 1769,
          "sha512": "149293c8ab00385855b08a5c180290746af9241808e664ca975b2a241add8d0d5c88bb5a98128fc96cef776d79e29e3ecf9c9a4d3f2cdfb93aaee7d2f6e8d8c0",
          "sha256": "fb558240f4ab460ddb1e0865c70e6ba0b49449a19239d84c2795fbeb3d86313a",
          "sha1": "03558f0787632fab33f20309ab9e6db8bd6558c3",
          "md5": "683f38e9017d507766112afdf17c6f24"
        }
      ]
    }
  ]
}
