{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2adb-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2adb",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2adb-android-0.8.11.aar",
          "url": "ble-characteristic-u2adb-android-0.8.11.aar",
          "size": 3175,
          "sha512": "72b421548265199e881ec9e7a528bc6339aedcfde316766d13adff190294e111f4ccda8b9f1430ee469fc2e4f8703d07f6b2fdf71c8d8f8aa9bd53bdc7fa29d3",
          "sha256": "8b438a694eff70ee7bbe9bdd002722bc022bb2e6b66e1e71abd9d00d5f6f2136",
          "sha1": "af286f7ac9951916e8456764d64f35c503728030",
          "md5": "6b492a3ef247df894a0d42cca998aa57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2adb",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2adb-android-0.8.11.aar",
          "url": "ble-characteristic-u2adb-android-0.8.11.aar",
          "size": 3175,
          "sha512": "72b421548265199e881ec9e7a528bc6339aedcfde316766d13adff190294e111f4ccda8b9f1430ee469fc2e4f8703d07f6b2fdf71c8d8f8aa9bd53bdc7fa29d3",
          "sha256": "8b438a694eff70ee7bbe9bdd002722bc022bb2e6b66e1e71abd9d00d5f6f2136",
          "sha1": "af286f7ac9951916e8456764d64f35c503728030",
          "md5": "6b492a3ef247df894a0d42cca998aa57"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2adb-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2adb-android-0.8.11-sources.jar",
          "size": 2181,
          "sha512": "b1c6c889e19ec31919cc2c8bb33e95ee15f189c742924507497445ce9c4f87646b8b4043f2d0a1329e7cb3325dc4d83719b6f159859850ddb65cc8e7db8df27d",
          "sha256": "62400d3f3728140b8531ea07c6eb6f04b08d22f1fed207ed2a7d1c1ac8061305",
          "sha1": "cb00e01adca09d6909479eccd5898a22e67685a8",
          "md5": "33a62e567f01dd42cfbd59f20c5ca3f2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2adb-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2adb-android-0.8.11-javadoc.jar",
          "size": 270624,
          "sha512": "58d74a419364948a0c73da46fb8832c6718588f5c33cd2268ef972949b01003b91af2720e1cf71aebd15436c1f89d38bb3acd87de66775d8b29c912364ec65d9",
          "sha256": "6c1837555bec411c5344df69e0ee86844965e72a2894a0ac295a91dc4554fcdc",
          "sha1": "b6f10eb1c1c1b4a58d9b39f8afc55811dad1ef12",
          "md5": "75b98e54cb03ea7d72a930f86993e5fb"
        }
      ]
    }
  ]
}
