{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b35",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b35-0.8.7.jar",
          "url": "ble-characteristic-u2b35-0.8.7.jar",
          "size": 2957,
          "sha512": "2e8790ffa8fd6a2a19f9f6ff7e6db88d4df102baf941699ae72511973a68b84a82b8027326c63c74d7865dc228f6bc46251429e95a68dab3b3d90f14d1e5bb6b",
          "sha256": "6107be575c2e99fbc4ef16f00e0fca0778bcd37525c0ab2dd8156f8dfcef9495",
          "sha1": "a5abe6bdac317057ce246a7ab5011ea9b72f1e3f",
          "md5": "ce6f9504e02bf0ce6e6a50e816bb641e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b35-0.8.7.jar",
          "url": "ble-characteristic-u2b35-0.8.7.jar",
          "size": 2957,
          "sha512": "2e8790ffa8fd6a2a19f9f6ff7e6db88d4df102baf941699ae72511973a68b84a82b8027326c63c74d7865dc228f6bc46251429e95a68dab3b3d90f14d1e5bb6b",
          "sha256": "6107be575c2e99fbc4ef16f00e0fca0778bcd37525c0ab2dd8156f8dfcef9495",
          "sha1": "a5abe6bdac317057ce246a7ab5011ea9b72f1e3f",
          "md5": "ce6f9504e02bf0ce6e6a50e816bb641e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b35-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b35-0.8.7-javadoc.jar",
          "size": 108424,
          "sha512": "3e0486b79d4cc51a8f93fd3d12ef1f95850f5e1243f9782c2b5b23d230b4f351d6684c0ebf6b1036aba739d5f1f17daccb9e20b99e91c0e22555e2a172ebb396",
          "sha256": "d27c7c7f89dee7a6c87c8d59b2028987895fb55111f8a8c98f4cb5f2d192608a",
          "sha1": "1892778dd73acd8013b8996afe18b63b35b231f5",
          "md5": "7229cbb22cf6201269911388827933ff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b35-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b35-0.8.7-sources.jar",
          "size": 2503,
          "sha512": "a5b2ba8f716ca1dd51b93a2750110d48e54f4d53b829dbfd156c0ec364b3bee33acfb61b9ed45fde9cfde19119aac099e2cd76f9d847db95590e883f9f6ff7e4",
          "sha256": "d38629da35fa0536552c8db50cb0c2e33807359a929adc0bdd0451007a35ec9c",
          "sha1": "0e30be0fb88af6b1d6f9e3b2095b5aa372d593f6",
          "md5": "237c186a202a82af489ac179528d69d6"
        }
      ]
    }
  ]
}
