{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a35",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a35-0.5.1.jar",
          "url": "ble-characteristic-u2a35-0.5.1.jar",
          "size": 3475,
          "sha512": "35ff17d9ca104b5b8f09c6474a544a6d2960efb4aa0a8a6bae32d396d120893b70b9603214a43eb35b565d2f6fa0a4eea0aeb3b97bbd4643ecaf5f3e6d9be398",
          "sha256": "26a6919b9dd7e23d6a5878835d1771dfc5f407b3a7bf1aac2de4b448974317f0",
          "sha1": "eccd1b792bf618f7e7ee6233db200e516cffcaa2",
          "md5": "40ebfa330958e0af85e38848c442071e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a35-0.5.1.jar",
          "url": "ble-characteristic-u2a35-0.5.1.jar",
          "size": 3475,
          "sha512": "35ff17d9ca104b5b8f09c6474a544a6d2960efb4aa0a8a6bae32d396d120893b70b9603214a43eb35b565d2f6fa0a4eea0aeb3b97bbd4643ecaf5f3e6d9be398",
          "sha256": "26a6919b9dd7e23d6a5878835d1771dfc5f407b3a7bf1aac2de4b448974317f0",
          "sha1": "eccd1b792bf618f7e7ee6233db200e516cffcaa2",
          "md5": "40ebfa330958e0af85e38848c442071e"
        }
      ]
    }
  ]
}
