{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b44-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b44",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b44-android-0.8.8.aar",
          "url": "ble-characteristic-u2b44-android-0.8.8.aar",
          "size": 3175,
          "sha512": "446a2c7678c386340f382a7ffc5f76ee9895fbab2894c81ec3c2682417c2c82309d88ec48e638413ebaf7740bd78ac5fb096748c2b996331dcde8dddacb69677",
          "sha256": "90396975da73b7146baab79bfee0262db447a8cfad1d15907d843be0cd03385d",
          "sha1": "8d9781bbad6dc12d373bea4ee65d3c55cd1365a1",
          "md5": "8f7ec89313096de260258c4dfae34c87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b44",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b44-android-0.8.8.aar",
          "url": "ble-characteristic-u2b44-android-0.8.8.aar",
          "size": 3175,
          "sha512": "446a2c7678c386340f382a7ffc5f76ee9895fbab2894c81ec3c2682417c2c82309d88ec48e638413ebaf7740bd78ac5fb096748c2b996331dcde8dddacb69677",
          "sha256": "90396975da73b7146baab79bfee0262db447a8cfad1d15907d843be0cd03385d",
          "sha1": "8d9781bbad6dc12d373bea4ee65d3c55cd1365a1",
          "md5": "8f7ec89313096de260258c4dfae34c87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b44-android-0.8.8-sources.jar",
          "url": "ble-characteristic-u2b44-android-0.8.8-sources.jar",
          "size": 2179,
          "sha512": "753f8f4c178483c3abab8e2db37649259499c0882925db5b90442bd8686c4ce381dc7a17c1130fa68055d92d7e5d40734b0dafc2ee8fb3150cde31e605901a58",
          "sha256": "0e7a5c53632ebf5ec54d504df892763ec91d9c03f584df025c38cb8eb843b787",
          "sha1": "97fbc7b89c1c8d3426cfc385939494e063126799",
          "md5": "a03d8fbc57bbb00245d354e47af14262"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b44-android-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2b44-android-0.8.8-javadoc.jar",
          "size": 270596,
          "sha512": "09d3939f338de2d3853576311e8f793f39b2a363e7b08452ea3663c84008edd4fff018ea4a8304f29cfde602f5961ed6f69180769f9a39871fda90a42302ad0f",
          "sha256": "70f59566b910f3221d52aa3def45926aac6e85732b4397fa4f80a43caeaf22e2",
          "sha1": "b08596e7878d707f8480c9eb48facd61ffee279e",
          "md5": "88facecbd609ed33349d44a9c7237e37"
        }
      ]
    }
  ]
}
