{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a35-android",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a35",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a35-android-0.8.3.aar",
          "url": "ble-characteristic-u2a35-android-0.8.3.aar",
          "size": 3402,
          "sha512": "69065db4140ada25f8398d375711fb58cf160ba62138d9c719508b997861c8887e380c738bf53c2fbc44a90e2bd9ebfc995187434c55c39185685a71a9fe5f90",
          "sha256": "77cc8cc0aeee25cd3747a047e274e278dc4c97ccb7f1d04261da96f68d4fd40e",
          "sha1": "31af920ac2aaeefdd0e433b2de7574cae0051657",
          "md5": "6feeaec2bd8f985e38af6bf3ab589daf"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a35",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a35-android-0.8.3.aar",
          "url": "ble-characteristic-u2a35-android-0.8.3.aar",
          "size": 3402,
          "sha512": "69065db4140ada25f8398d375711fb58cf160ba62138d9c719508b997861c8887e380c738bf53c2fbc44a90e2bd9ebfc995187434c55c39185685a71a9fe5f90",
          "sha256": "77cc8cc0aeee25cd3747a047e274e278dc4c97ccb7f1d04261da96f68d4fd40e",
          "sha1": "31af920ac2aaeefdd0e433b2de7574cae0051657",
          "md5": "6feeaec2bd8f985e38af6bf3ab589daf"
        }
      ]
    }
  ]
}
