{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6d",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "bo2m2bzyvfgbjfmoy4levvs3tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-0.2.1.jar",
          "url": "ble-characteristic-u2a6d-0.2.1.jar",
          "size": 1828,
          "sha512": "693cc25fd04575eee2fd3a3a5c5602369b85d69eec820c040525ba8dcf56d16a2df1b985175e1d6dc13b9c65f83ce08dd3374506630d2080c1b2aedb7285f66c",
          "sha256": "c9f76afccaa48024b0783c45f9cf11a38e737f1b3974643aa95b231ffcd27e9d",
          "sha1": "7b999e602de443fb680023328b6fe0076f831725",
          "md5": "589ffa970522aead1c7b1d7c846a233f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-0.2.1.jar",
          "url": "ble-characteristic-u2a6d-0.2.1.jar",
          "size": 1828,
          "sha512": "693cc25fd04575eee2fd3a3a5c5602369b85d69eec820c040525ba8dcf56d16a2df1b985175e1d6dc13b9c65f83ce08dd3374506630d2080c1b2aedb7285f66c",
          "sha256": "c9f76afccaa48024b0783c45f9cf11a38e737f1b3974643aa95b231ffcd27e9d",
          "sha1": "7b999e602de443fb680023328b6fe0076f831725",
          "md5": "589ffa970522aead1c7b1d7c846a233f"
        }
      ]
    }
  ]
}
