{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a32-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.1.0.aar",
          "url": "ble-characteristic-u2a32-android-0.1.0.aar",
          "size": 2917,
          "sha512": "15347f36b1d6e2dcd781420070957f4f9e8370af78f70f427574617cd36bd740420675e7372febfdc78b9022ca10b313cc483fb1114c57ac0b4577b84402e21f",
          "sha256": "73b8655214741896804b3ac6e3f8ec3249ffca8b2374df471f88c4d492ebdc1f",
          "sha1": "6f1610a383704c0f302804c18181c534d2899e36",
          "md5": "d6bdf078c28a70413755f9bfccea3416"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.1.0.aar",
          "url": "ble-characteristic-u2a32-android-0.1.0.aar",
          "size": 2917,
          "sha512": "15347f36b1d6e2dcd781420070957f4f9e8370af78f70f427574617cd36bd740420675e7372febfdc78b9022ca10b313cc483fb1114c57ac0b4577b84402e21f",
          "sha256": "73b8655214741896804b3ac6e3f8ec3249ffca8b2374df471f88c4d492ebdc1f",
          "sha1": "6f1610a383704c0f302804c18181c534d2899e36",
          "md5": "d6bdf078c28a70413755f9bfccea3416"
        }
      ]
    }
  ]
}
