{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a68-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a68-android-0.8.12.aar",
          "url": "ble-characteristic-u2a68-android-0.8.12.aar",
          "size": 3270,
          "sha512": "1daa23e09b2302d07c4d9ddfd1a363005e6aa4a170348251618a93c5c0fe0b443c1b87a2db3e2f0b9f462f8f2f198610629865b931c6d82b5911b8ce4b21280f",
          "sha256": "c192184d2c7a7b2772d608f950621b3b2400bc1328fc4abce35044b1764b7395",
          "sha1": "d7e7be9f4c31fbc6a741a297bf050f776cc1a047",
          "md5": "416967b5728a5dc2c558f32809a206fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a68-android-0.8.12.aar",
          "url": "ble-characteristic-u2a68-android-0.8.12.aar",
          "size": 3270,
          "sha512": "1daa23e09b2302d07c4d9ddfd1a363005e6aa4a170348251618a93c5c0fe0b443c1b87a2db3e2f0b9f462f8f2f198610629865b931c6d82b5911b8ce4b21280f",
          "sha256": "c192184d2c7a7b2772d608f950621b3b2400bc1328fc4abce35044b1764b7395",
          "sha1": "d7e7be9f4c31fbc6a741a297bf050f776cc1a047",
          "md5": "416967b5728a5dc2c558f32809a206fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a68-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a68-android-0.8.12-sources.jar",
          "size": 2349,
          "sha512": "fe12d124e16d5978d835940cf6ae5090412f82b6a6fb9e8c65d8593c14fb06fc17bb6a96a25e32db3e371d6da124f0cfb729cdfeadb367bf5ae576d2f2860d3f",
          "sha256": "50727bd1e159a09e85d40f53f64204e2a63d2034c5d49c43680be97835c591d9",
          "sha1": "c14bff1506e5170ebb5b58e113ddf1a04a242c17",
          "md5": "7f16b0f8a0a50dc4effadfedbb567ce6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a68-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a68-android-0.8.12-javadoc.jar",
          "size": 273638,
          "sha512": "bc0309b0d182bc6c3cdf8330851a71f3ac25f267596400a42155b462d8df49490d8b3c19df6911913c0223612af8ee99324a613150a6a6d9c2d70ab8964da0a7",
          "sha256": "fc1569616dfeca792c7225317eb1cf3a59c701d60de65d5e2ee5b62edc2d9f28",
          "sha1": "8f24efa15b15935fd516ad2e0b2746a08c4e2572",
          "md5": "6e78d3a38307dbf060a18278a9c85ed7"
        }
      ]
    }
  ]
}
