{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa5-android",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa5-android-0.8.2.aar",
          "url": "ble-characteristic-u2aa5-android-0.8.2.aar",
          "size": 3049,
          "sha512": "832171d6aaffe590583d2546cd4888383ce9d13e103af4351b906f00aa6f9976454742d989cdfde6212251d1502752925477720793018edacf7be487a6f1e25d",
          "sha256": "515b914e6899414003451bcea4f75332fb4149da928f367c5e19139c977aac77",
          "sha1": "b4fc811a9ab9f42bc9758e67a87361db11833acb",
          "md5": "f94124b83af79aa5fed90ae116dbe039"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa5-android-0.8.2.aar",
          "url": "ble-characteristic-u2aa5-android-0.8.2.aar",
          "size": 3049,
          "sha512": "832171d6aaffe590583d2546cd4888383ce9d13e103af4351b906f00aa6f9976454742d989cdfde6212251d1502752925477720793018edacf7be487a6f1e25d",
          "sha256": "515b914e6899414003451bcea4f75332fb4149da928f367c5e19139c977aac77",
          "sha1": "b4fc811a9ab9f42bc9758e67a87361db11833acb",
          "md5": "f94124b83af79aa5fed90ae116dbe039"
        }
      ]
    }
  ]
}
