{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9d-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a9d-android-0.8.6.aar",
          "size": 3254,
          "sha512": "27084a5e5a107ecbbc0507350c6bc46b48f260d053f77488bb719220599cfe710d5a68c5cea9785c2a4e04e4bb69ecd838a100dd94cc4940a18a4d06cebe2512",
          "sha256": "74535ecf8cf9ef4aa70aeb082368fea18174219aa7f1f9ec842bbd993839e6a4",
          "sha1": "1423f9acd6faaff50e495c9e05d793954e974115",
          "md5": "d7338519fd12f3ff0afac5ce0181f3bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a9d-android-0.8.6.aar",
          "size": 3254,
          "sha512": "27084a5e5a107ecbbc0507350c6bc46b48f260d053f77488bb719220599cfe710d5a68c5cea9785c2a4e04e4bb69ecd838a100dd94cc4940a18a4d06cebe2512",
          "sha256": "74535ecf8cf9ef4aa70aeb082368fea18174219aa7f1f9ec842bbd993839e6a4",
          "sha1": "1423f9acd6faaff50e495c9e05d793954e974115",
          "md5": "d7338519fd12f3ff0afac5ce0181f3bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9d-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a9d-android-0.8.6-sources.jar",
          "size": 2371,
          "sha512": "be2d75156a1b2029ea783b85ba44db8315e3bab8357b034e3699dc0c4276b48542aa430b41ddfc59c07c08a052303c063e18a5c6e7f6921bcfab9f5385240fcc",
          "sha256": "e5f21c37198e066df45d4ba77c68c98414fff61d162f4047fc5b6424dbcc941b",
          "sha1": "0af4bb2bedb35460b0ebbb0543acfe151a634242",
          "md5": "4423d620acd2118dfbb1d813e58f7bf4"
        }
      ]
    }
  ]
}
