{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a40-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a40",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a40-android-0.2.0.aar",
          "url": "ble-characteristic-u2a40-android-0.2.0.aar",
          "size": 2926,
          "sha512": "71a097f25348fae72d3a67e7391a3a665884040deee2638010459381c13b6a10e60d06385e89e128b7297f2ca757bbc41195fb25d729ba6d4be20b072ac76270",
          "sha256": "134cfb4630ab1ed99c3d453861803dd340f1e041c19627e5904738410187fe8e",
          "sha1": "12b6262554a9cd3b92d11f3e7941ce7566bf78de",
          "md5": "adca02e64f2bab93abf26ac07bd6d90e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a40",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a40-android-0.2.0.aar",
          "url": "ble-characteristic-u2a40-android-0.2.0.aar",
          "size": 2926,
          "sha512": "71a097f25348fae72d3a67e7391a3a665884040deee2638010459381c13b6a10e60d06385e89e128b7297f2ca757bbc41195fb25d729ba6d4be20b072ac76270",
          "sha256": "134cfb4630ab1ed99c3d453861803dd340f1e041c19627e5904738410187fe8e",
          "sha1": "12b6262554a9cd3b92d11f3e7941ce7566bf78de",
          "md5": "adca02e64f2bab93abf26ac07bd6d90e"
        }
      ]
    }
  ]
}
