{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afa",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afa-0.8.12.jar",
          "url": "ble-characteristic-u2afa-0.8.12.jar",
          "size": 2137,
          "sha512": "8090c6424b87c06488976b44fe988024413627fe41685aafce158af63694e297dfbfcf5cfeb1050968e4edcc949f3ffc98790cb40512deb67fbf041b7bd9fd31",
          "sha256": "af1610ed9d89da747f99a1e2c82fe54aa73b131896778c08ad96bbdc8d5f27fb",
          "sha1": "1ebcc36a99f189917df7f7687aab2cff60a49818",
          "md5": "dfbfbac8764a5c1b0bccb3d57970fc21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afa-0.8.12.jar",
          "url": "ble-characteristic-u2afa-0.8.12.jar",
          "size": 2137,
          "sha512": "8090c6424b87c06488976b44fe988024413627fe41685aafce158af63694e297dfbfcf5cfeb1050968e4edcc949f3ffc98790cb40512deb67fbf041b7bd9fd31",
          "sha256": "af1610ed9d89da747f99a1e2c82fe54aa73b131896778c08ad96bbdc8d5f27fb",
          "sha1": "1ebcc36a99f189917df7f7687aab2cff60a49818",
          "md5": "dfbfbac8764a5c1b0bccb3d57970fc21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afa-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2afa-0.8.12-javadoc.jar",
          "size": 107575,
          "sha512": "d5d64523c92ca77caf4fc11c9b3f70cc96658206e4240b50e020c34f741046f37b70a910ff526cad22cd0ed32983c2997e5c9759d1e57686164ed51637f8f7da",
          "sha256": "8d17fa75d4277698d9e954a444f1727586982fd86f420defac88c83ddb355312",
          "sha1": "c80b848389b63c34959b0aba37fee8bba6305665",
          "md5": "a9b19d28bc01c01a9301b6d89e7cc692"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afa-0.8.12-sources.jar",
          "url": "ble-characteristic-u2afa-0.8.12-sources.jar",
          "size": 1856,
          "sha512": "d189ee72b6af4205f786ee183e396372a6c39c49908686054a7be981c7d0f3405980d0ea1ee57945e1999b6f03bf77d05719b4a41317f6e59a10530858755038",
          "sha256": "d1ca721d2cc7522bf512cff7d8c59ffc40134f52fac6e187a79709c1b758ce0b",
          "sha1": "974ddfbeb807fa088234c78b99a21113c9e9cc7e",
          "md5": "c3f4d0d44b09fa7b5e029dde1091df34"
        }
      ]
    }
  ]
}
