{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b98",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b98-0.5.0.jar",
          "url": "ble-characteristic-u2b98-0.5.0.jar",
          "size": 1449,
          "sha512": "974e90f3543061e0d4ea577f60d2508c6b364b5351c49a1f71b537b2d28ba0dadb8e4132ab94cf1fce5397d765147eaf698110ef404fd8e84d3ce2e0a4d5b5ec",
          "sha256": "22e4de07bc52fe62489dd14ee60f9c670c895b30e5530cd18d0b356336d34a87",
          "sha1": "abcf1f797e186e48d0f53a08e30c7984abcd2360",
          "md5": "fb5d70a3a788dd87cbea6d960b8a8423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b98-0.5.0.jar",
          "url": "ble-characteristic-u2b98-0.5.0.jar",
          "size": 1449,
          "sha512": "974e90f3543061e0d4ea577f60d2508c6b364b5351c49a1f71b537b2d28ba0dadb8e4132ab94cf1fce5397d765147eaf698110ef404fd8e84d3ce2e0a4d5b5ec",
          "sha256": "22e4de07bc52fe62489dd14ee60f9c670c895b30e5530cd18d0b356336d34a87",
          "sha1": "abcf1f797e186e48d0f53a08e30c7984abcd2360",
          "md5": "fb5d70a3a788dd87cbea6d960b8a8423"
        }
      ]
    }
  ]
}
