{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aac-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aac",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aac-android-0.8.12.aar",
          "url": "ble-characteristic-u2aac-android-0.8.12.aar",
          "size": 3137,
          "sha512": "436654f131d6047929f76405cac606039265325d17e9cd1001cccc1f409d4a1245a19fa33012a5e4e38e92bec1de02ed7d679b12cda6066adca405b669782ca3",
          "sha256": "2023d63efd1f3c46dcb8681315d6b875e4d43bd369ed079fadd2d5c71af0f704",
          "sha1": "8a0a94aaa3095548a08e554741b3f5abfa96bb24",
          "md5": "b28e5e9a1952034b85c6aabbf7ee3a26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aac",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aac-android-0.8.12.aar",
          "url": "ble-characteristic-u2aac-android-0.8.12.aar",
          "size": 3137,
          "sha512": "436654f131d6047929f76405cac606039265325d17e9cd1001cccc1f409d4a1245a19fa33012a5e4e38e92bec1de02ed7d679b12cda6066adca405b669782ca3",
          "sha256": "2023d63efd1f3c46dcb8681315d6b875e4d43bd369ed079fadd2d5c71af0f704",
          "sha1": "8a0a94aaa3095548a08e554741b3f5abfa96bb24",
          "md5": "b28e5e9a1952034b85c6aabbf7ee3a26"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aac-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2aac-android-0.8.12-sources.jar",
          "size": 2212,
          "sha512": "0ef05ee43aaa44636124250639be1c3ff668d495d9ed945c6172de4e622774e64b9d79f7ac390e2138de744b923bd58236f66575749b4b78ec7f8ddc10b57691",
          "sha256": "b635086a941e8c1a42b98670e37ca48134d2b1b10cc4956e5ec314c754b557a2",
          "sha1": "b7d13a6965d40ff4ceb52a950c8386a0745e6ba7",
          "md5": "1b459faebbd84b5f8117ea7a17c3e119"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aac-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2aac-android-0.8.12-javadoc.jar",
          "size": 271136,
          "sha512": "738a4b5c93b28a33d9e8fe7436b878611b649513386d871aaf555c0c6d8930bdebbc431b075f8e91972811a857795f7235df00af618d59f5b94082ada4b78b0d",
          "sha256": "e6d2516fbfbe3c4e01f7f002713637d9a09c4b679b29abe40a3ac0b707b26a26",
          "sha1": "0f7400f6a0c4ee37d1a3af176bc9a4b40dc87b8e",
          "md5": "dccd23c8d789650136090f66f7e916ee"
        }
      ]
    }
  ]
}
