{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a87-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a87",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a87-android-0.2.3.aar",
          "url": "ble-characteristic-u2a87-android-0.2.3.aar",
          "size": 2966,
          "sha512": "8bcbf490d38f1543b16ca093054c8442ab2259453a944b1157c1873b3c1cf4f11426eac98c9bee23f1de89c8edd43c8c8e11c1cc67287aebbf3bf6cd72a80475",
          "sha256": "d4c7d2922f956293acdf57fc2e0156f51ebd5cc09df9a4a214b1b17a7162ef43",
          "sha1": "005ff8719f45c235cf781f5a40c693bfaafdb4e6",
          "md5": "5855b4daf3099fd66aa3f8f61bc80653"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a87",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a87-android-0.2.3.aar",
          "url": "ble-characteristic-u2a87-android-0.2.3.aar",
          "size": 2966,
          "sha512": "8bcbf490d38f1543b16ca093054c8442ab2259453a944b1157c1873b3c1cf4f11426eac98c9bee23f1de89c8edd43c8c8e11c1cc67287aebbf3bf6cd72a80475",
          "sha256": "d4c7d2922f956293acdf57fc2e0156f51ebd5cc09df9a4a214b1b17a7162ef43",
          "sha1": "005ff8719f45c235cf781f5a40c693bfaafdb4e6",
          "md5": "5855b4daf3099fd66aa3f8f61bc80653"
        }
      ]
    }
  ]
}
