{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5f-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5f",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5f-android-0.8.6.aar",
          "url": "ble-characteristic-u2a5f-android-0.8.6.aar",
          "size": 3090,
          "sha512": "3655561b7fc491593d74b1f3428dbdc742c3a793bdccc6eec55fe6db6877505ebda80402a1f2b7d50d8229947a3f747ffd6df9ac7f33e1431a04593ff6c683cc",
          "sha256": "072f6ae4242d341c2c72c5f18be6ce79094a8e8626261a83b01f01c4855e1b70",
          "sha1": "1819835ceadc6cfadd3eae7c2ac293b8755953bd",
          "md5": "037b2a07863c0ce59cc94cedd0551dd4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5f",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5f-android-0.8.6.aar",
          "url": "ble-characteristic-u2a5f-android-0.8.6.aar",
          "size": 3090,
          "sha512": "3655561b7fc491593d74b1f3428dbdc742c3a793bdccc6eec55fe6db6877505ebda80402a1f2b7d50d8229947a3f747ffd6df9ac7f33e1431a04593ff6c683cc",
          "sha256": "072f6ae4242d341c2c72c5f18be6ce79094a8e8626261a83b01f01c4855e1b70",
          "sha1": "1819835ceadc6cfadd3eae7c2ac293b8755953bd",
          "md5": "037b2a07863c0ce59cc94cedd0551dd4"
        }
      ]
    }
  ]
}
