{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lns-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a67-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b-android",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-android-0.1.2.aar",
          "url": "ble-service-lns-android-0.1.2.aar",
          "size": 1022,
          "sha512": "8fae7d990696c7b697dcef38544042739040ab2b79af017552ea536aca3d77d48446f3e7fac917faa6a787df4acd91aa832872e8864abed75868b352d3c97c39",
          "sha256": "d5117cd9bba97914f25a91baa083464b5ec0a829e03b8c987a6190519b2bb33b",
          "sha1": "df08d90c7ac6aa5fd9561df45f8d6367f1928614",
          "md5": "62bccec8820a017856992e1f003d27ac"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a67-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b-android",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-android-0.1.2.aar",
          "url": "ble-service-lns-android-0.1.2.aar",
          "size": 1022,
          "sha512": "8fae7d990696c7b697dcef38544042739040ab2b79af017552ea536aca3d77d48446f3e7fac917faa6a787df4acd91aa832872e8864abed75868b352d3c97c39",
          "sha256": "d5117cd9bba97914f25a91baa083464b5ec0a829e03b8c987a6190519b2bb33b",
          "sha1": "df08d90c7ac6aa5fd9561df45f8d6367f1928614",
          "md5": "62bccec8820a017856992e1f003d27ac"
        }
      ]
    }
  ]
}
