{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc2",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc2-0.8.6.jar",
          "url": "ble-characteristic-u2bc2-0.8.6.jar",
          "size": 1458,
          "sha512": "719efa8a7e564ad750dc66804ce9539d71b05019cbad766bd21071b4c1b325e9dc4c5bea7b19214a1979d90175b5eafd571024b002f9fc37b960ad3868739cbe",
          "sha256": "495f03722faf33b1bda5fefe0160b2068957312f064f97f65a0bb961aae02f95",
          "sha1": "a85d7c2b4d4a09bbe81dd67fef775f8aca1ac6fa",
          "md5": "5afe99f789752bd9a8a0c0f118f61c04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc2-0.8.6.jar",
          "url": "ble-characteristic-u2bc2-0.8.6.jar",
          "size": 1458,
          "sha512": "719efa8a7e564ad750dc66804ce9539d71b05019cbad766bd21071b4c1b325e9dc4c5bea7b19214a1979d90175b5eafd571024b002f9fc37b960ad3868739cbe",
          "sha256": "495f03722faf33b1bda5fefe0160b2068957312f064f97f65a0bb961aae02f95",
          "sha1": "a85d7c2b4d4a09bbe81dd67fef775f8aca1ac6fa",
          "md5": "5afe99f789752bd9a8a0c0f118f61c04"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc2-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2bc2-0.8.6-javadoc.jar",
          "size": 107170,
          "sha512": "8973ff187a7f9896c99cf3a749ddc11bfeae975d0d1693b2aa9e64123cda842937253a336fae28953856db6d199bdb71142a47b01b071d3559b2c795f8d4d926",
          "sha256": "b377293acbb95159d5723f50beb19afbd35c6d5cd5b36397be4c3cd21117a5d1",
          "sha1": "641fc6e58730678326359bb2ce4d3659c336422f",
          "md5": "6d642f04103e56c9e53253c0a002d56e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc2-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bc2-0.8.6-sources.jar",
          "size": 1453,
          "sha512": "92259ab1ed1899b8bfa24047f868eb05fd5229a567527eccf7085ff50b3c529a46989265ed68bda157dad6206c78826ed08e670d34735513bcc657c7135cf40a",
          "sha256": "b41d39a55ffd036e302ee70f6b66b66bc0bdc1bf5b6e78fee8de651ceadcdbb5",
          "sha1": "6fbf95f0d3b9b8a9952064d2071c5272e6758a21",
          "md5": "da5500fe752ef1e478f08ae5b959233e"
        }
      ]
    }
  ]
}
