{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9b-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9b-android-0.8.6.aar",
          "url": "ble-characteristic-u2a9b-android-0.8.6.aar",
          "size": 3074,
          "sha512": "aef8840864093bf8fb83558b6b13c9125559a4b608473acc5fe4fc0c5cc5b8136db2ec92dfa7ea4273049147a4d3d7ad1b9a8ece1d100cda10669c9705177013",
          "sha256": "f53295c2a2deb61196a55abc5b15980f0c8ca2a7b68059932199e4ec9673abec",
          "sha1": "a519b9a42976795cddb9f5ab13521f2be708165c",
          "md5": "d7d1c22b6e60ad4e05863434b244c2e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9b-android-0.8.6.aar",
          "url": "ble-characteristic-u2a9b-android-0.8.6.aar",
          "size": 3074,
          "sha512": "aef8840864093bf8fb83558b6b13c9125559a4b608473acc5fe4fc0c5cc5b8136db2ec92dfa7ea4273049147a4d3d7ad1b9a8ece1d100cda10669c9705177013",
          "sha256": "f53295c2a2deb61196a55abc5b15980f0c8ca2a7b68059932199e4ec9673abec",
          "sha1": "a519b9a42976795cddb9f5ab13521f2be708165c",
          "md5": "d7d1c22b6e60ad4e05863434b244c2e6"
        }
      ]
    }
  ]
}
