{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab8",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-0.6.1.jar",
          "url": "ble-characteristic-u2ab8-0.6.1.jar",
          "size": 2315,
          "sha512": "48fa1e0be3d5ae24c59d6fc2e44fbbaf193d48e2083c5cb6b6ebf4ac9b2221b376a1ef750bdb13de723d114321123fdc1b49ca145b4b378b2617cb1bc873d0d2",
          "sha256": "4ac74476e378bf00c334e079c18ffb47cbfdc57994bdd6e9ac14443ea3450155",
          "sha1": "79bb01ffd9622cc16c4e9429d3b3ba8e29bcd866",
          "md5": "694c8316111d67f299b648630d65647d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-0.6.1.jar",
          "url": "ble-characteristic-u2ab8-0.6.1.jar",
          "size": 2315,
          "sha512": "48fa1e0be3d5ae24c59d6fc2e44fbbaf193d48e2083c5cb6b6ebf4ac9b2221b376a1ef750bdb13de723d114321123fdc1b49ca145b4b378b2617cb1bc873d0d2",
          "sha256": "4ac74476e378bf00c334e079c18ffb47cbfdc57994bdd6e9ac14443ea3450155",
          "sha1": "79bb01ffd9622cc16c4e9429d3b3ba8e29bcd866",
          "md5": "694c8316111d67f299b648630d65647d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab8-0.6.1-javadoc.jar",
          "url": "ble-characteristic-u2ab8-0.6.1-javadoc.jar",
          "size": 112667,
          "sha512": "2551b7703299eab227fa646a8510e6005724c42f5e11cd06cc268bc55218e1bd8e53a1a8d63018e75ea17ba48b241d1d6b9dbaa032dd5dc2f2225bfbc499deb1",
          "sha256": "d9e6d665d17e0bd03a5e30960b135829429e4305df136548af346fdd51bd09ba",
          "sha1": "ae11bf7cd145fbca7190ce0a484be3518228fb00",
          "md5": "64117fd5f71a20b58f79c1e6f70edec7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab8-0.6.1-sources.jar",
          "url": "ble-characteristic-u2ab8-0.6.1-sources.jar",
          "size": 2383,
          "sha512": "c1f54fe9cfb835772bd6f54788c2dae6b7047441a1e1bd1eade2914e0b251aeaf9f8bac35cc89201340c761faab0ca3c2c300f7f2654fd64470defca2b48867a",
          "sha256": "7e50567c2f7b3e25f1ebd7063217038579e1f259fb2f625d8d1ececccf5b9e95",
          "sha1": "944aa8b0925b3b494052a0ebd52b1491c516438b",
          "md5": "e3f65ae2282f458181a405cdef25bd08"
        }
      ]
    }
  ]
}
