{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b42-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b42",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b42-android-0.4.6.aar",
          "url": "ble-characteristic-u2b42-android-0.4.6.aar",
          "size": 3109,
          "sha512": "4e027cac11f6724e495143d82a962ab4994501a4a9aaf3ca2834f3bb0b827030c05f8f27c27794ac929518f97bdad9279b53106493021b4bc065028df6eb5ed2",
          "sha256": "19108cf773b94b561da056a7963683585e5930ebc5718d11aa83376baa2b8fa4",
          "sha1": "899ca8d730347f786d12ae420439be14a6276242",
          "md5": "d03299b188c1da305ce6afb45d860135"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b42",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b42-android-0.4.6.aar",
          "url": "ble-characteristic-u2b42-android-0.4.6.aar",
          "size": 3109,
          "sha512": "4e027cac11f6724e495143d82a962ab4994501a4a9aaf3ca2834f3bb0b827030c05f8f27c27794ac929518f97bdad9279b53106493021b4bc065028df6eb5ed2",
          "sha256": "19108cf773b94b561da056a7963683585e5930ebc5718d11aa83376baa2b8fa4",
          "sha1": "899ca8d730347f786d12ae420439be14a6276242",
          "md5": "d03299b188c1da305ce6afb45d860135"
        }
      ]
    }
  ]
}
