{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aff",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aff-0.8.5.jar",
          "url": "ble-characteristic-u2aff-0.8.5.jar",
          "size": 1767,
          "sha512": "3cb9f403aea58afd64e53c4cf84a0ae403b21ca35f427e43def097eb099e33e0bf6b8e6496fccf281f1472dc719f212a8b583cb47bfd8489c1f98544fc4030be",
          "sha256": "918dd598027ace0acace309f16863acf3979cf646a5ddbc519d1dbaecce15a54",
          "sha1": "2cb84dffc16fa6e896a4e397cf497ebe471b90a9",
          "md5": "debd7c641c54ddd23d6f1cab6063c6ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aff-0.8.5.jar",
          "url": "ble-characteristic-u2aff-0.8.5.jar",
          "size": 1767,
          "sha512": "3cb9f403aea58afd64e53c4cf84a0ae403b21ca35f427e43def097eb099e33e0bf6b8e6496fccf281f1472dc719f212a8b583cb47bfd8489c1f98544fc4030be",
          "sha256": "918dd598027ace0acace309f16863acf3979cf646a5ddbc519d1dbaecce15a54",
          "sha1": "2cb84dffc16fa6e896a4e397cf497ebe471b90a9",
          "md5": "debd7c641c54ddd23d6f1cab6063c6ea"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aff-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2aff-0.8.5-javadoc.jar",
          "size": 107337,
          "sha512": "658bc590e6e1c0cc7667024dadae91c96556e01a253b7384ca8b018596fc84456f1a4565451cfacbe3e9cf8877b8481ba75b8b6e40986b336c7b3701f8626e6f",
          "sha256": "b4ceb99c80d0ff075bd731e33a7ff1f4ba919108ecf17b569d5a807d4a423aa8",
          "sha1": "a87d5a432c9d9592ff730a302d7f76934bc2cde0",
          "md5": "70c86adb210b751b368a4de33d5a4850"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aff-0.8.5-sources.jar",
          "url": "ble-characteristic-u2aff-0.8.5-sources.jar",
          "size": 1609,
          "sha512": "c8ef8365f6582c363ed4417f39abecc25f44287b0e56c9b21c374c6c01535af797989021ff54c441ed317539923c7d94cfd360004d484bae75255fec640ba9b5",
          "sha256": "3fea81f61232294c7858ecde62a4e2ec8bee19dba369ea60ce03083ad4059778",
          "sha1": "30075e314feccb213ebc1ee3a425de9d44b9cc78",
          "md5": "a9e548b614fc358d6f5c1ff9a33b18e7"
        }
      ]
    }
  ]
}
