{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-hts-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-hts-android-0.8.12.aar",
          "url": "ble-service-peripheral-hts-android-0.8.12.aar",
          "size": 9058,
          "sha512": "48d5efc1a42003436ea5ff4f3319062c7233ed8136e6cfc9b0d90609782982dd1202ce34b96c5bb27487a77da8e8126c91775900b643ed27f48db63642a53f55",
          "sha256": "86ea45ca997a40b2516f7814ef01b81db048ba467fa8e88d5cde5e6fa5149e9a",
          "sha1": "60789fc41aa699b43adf5ff610ffc7dbcb612aec",
          "md5": "6582412461782e9775e6efe6eaea2f7f"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-hts-android-0.8.12.aar",
          "url": "ble-service-peripheral-hts-android-0.8.12.aar",
          "size": 9058,
          "sha512": "48d5efc1a42003436ea5ff4f3319062c7233ed8136e6cfc9b0d90609782982dd1202ce34b96c5bb27487a77da8e8126c91775900b643ed27f48db63642a53f55",
          "sha256": "86ea45ca997a40b2516f7814ef01b81db048ba467fa8e88d5cde5e6fa5149e9a",
          "sha1": "60789fc41aa699b43adf5ff610ffc7dbcb612aec",
          "md5": "6582412461782e9775e6efe6eaea2f7f"
        }
      ]
    }
  ]
}
