{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a44-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.4.0.aar",
          "url": "ble-characteristic-u2a44-android-0.4.0.aar",
          "size": 3182,
          "sha512": "f9909fa40517b44bbd500d3fb1961d78ab0acee834c8bdbd08be38ff9cc1487e1b6f390111cb2effc9f35e79c9db3717ff78514955117de438f41631959497a1",
          "sha256": "907dd346c9d3f61cbefe57207668ef71a822730c5a06d6ee10efce71b190dab2",
          "sha1": "eedb1061c6e51bfd9bee9e3d7804db96efdb041d",
          "md5": "73ecf23a2692235ddaa81b3016c9756e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.4.0.aar",
          "url": "ble-characteristic-u2a44-android-0.4.0.aar",
          "size": 3182,
          "sha512": "f9909fa40517b44bbd500d3fb1961d78ab0acee834c8bdbd08be38ff9cc1487e1b6f390111cb2effc9f35e79c9db3717ff78514955117de438f41631959497a1",
          "sha256": "907dd346c9d3f61cbefe57207668ef71a822730c5a06d6ee10efce71b190dab2",
          "sha1": "eedb1061c6e51bfd9bee9e3d7804db96efdb041d",
          "md5": "73ecf23a2692235ddaa81b3016c9756e"
        }
      ]
    }
  ]
}
