{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac6",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac6-0.8.14.jar",
          "url": "ble-characteristic-u2ac6-0.8.14.jar",
          "size": 3728,
          "sha512": "80fd5c155365baebdb595073b28c46866ca4e081db0c675af915173c0bf22d5fdcb33f598274dc06a190ac81bdd3879db5f3fd25f20fa2520a3dce665a30c8c5",
          "sha256": "c3911e62621b863f4d9526f4c2e1a8d63ebd5eafcc1c284a4c7c9cd3750b0d8f",
          "sha1": "410b763b718d1ab7c06545f2304f2171d8f156f9",
          "md5": "7d130fb244a63d878919af880bb23de2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac6-0.8.14.jar",
          "url": "ble-characteristic-u2ac6-0.8.14.jar",
          "size": 3728,
          "sha512": "80fd5c155365baebdb595073b28c46866ca4e081db0c675af915173c0bf22d5fdcb33f598274dc06a190ac81bdd3879db5f3fd25f20fa2520a3dce665a30c8c5",
          "sha256": "c3911e62621b863f4d9526f4c2e1a8d63ebd5eafcc1c284a4c7c9cd3750b0d8f",
          "sha1": "410b763b718d1ab7c06545f2304f2171d8f156f9",
          "md5": "7d130fb244a63d878919af880bb23de2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ac6-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2ac6-0.8.14-javadoc.jar",
          "size": 93999,
          "sha512": "420550904cc7edbc47e325b0290d24a1ba61072529c267ff8a8ff96bbdb4f93f84e455fb36e7a0923f26aeb5ba71e7e94c42b6ebb4df8f7308c60c948e6021aa",
          "sha256": "8c13557b3a60526c4e2d267128603466b4d79f751850bec9d757d0f86a401518",
          "sha1": "f1e1b8f1aee7627a8e4e7891c38a795537958b94",
          "md5": "b7f382cd4022227c98a35967f8012c2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ac6-0.8.14-sources.jar",
          "url": "ble-characteristic-u2ac6-0.8.14-sources.jar",
          "size": 3393,
          "sha512": "655a36fd5ab642dfd1b90eafb8f6357d4db1ee4fc85a03326187a2053fc05f78bd3e0aa3ecab06eae21c595bd2e9b449f986e66049db4b170e965c7f5345e3fd",
          "sha256": "011073b61216fb9d99bf9e0986b2249ed250e8b541cbc9cab2977e8e703d1a8d",
          "sha1": "cccea8a55c526f788a268d586fcda623a55da0c8",
          "md5": "98819f759be7b1f073e88273036c5a35"
        }
      ]
    }
  ]
}
