{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ans-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-central-android-0.1.4.aar",
          "url": "ble-service-ans-central-android-0.1.4.aar",
          "size": 6389,
          "sha512": "1b3c1da7022980a229096b9ef7d87c4dd5d2fb96d72bd02865bf1ac13f0396c8c346e8f5079942b3f0883b7c3ba489a1a9412dc9ecd929aac9b991e26d4cd013",
          "sha256": "f3a0e3f30d0529d46175526c1f2bec0feadb99927ec08ee546c973d90b6869d5",
          "sha1": "a4f1e7c32e12dbf5f19ddd4d6a94c8f59cc55078",
          "md5": "c3e4dea4daaeeb77d921749e8cd07753"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-central-android-0.1.4.aar",
          "url": "ble-service-ans-central-android-0.1.4.aar",
          "size": 6389,
          "sha512": "1b3c1da7022980a229096b9ef7d87c4dd5d2fb96d72bd02865bf1ac13f0396c8c346e8f5079942b3f0883b7c3ba489a1a9412dc9ecd929aac9b991e26d4cd013",
          "sha256": "f3a0e3f30d0529d46175526c1f2bec0feadb99927ec08ee546c973d90b6869d5",
          "sha1": "a4f1e7c32e12dbf5f19ddd4d6a94c8f59cc55078",
          "md5": "c3e4dea4daaeeb77d921749e8cd07753"
        }
      ]
    }
  ]
}
