{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5b-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fxrmxjl6szatjaovsgygwi5l4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.2.4.aar",
          "url": "ble-characteristic-u2a5b-android-0.2.4.aar",
          "size": 3175,
          "sha512": "2b3e13d3e893570e1fbfd9ce7decf326dd03ad26cf9b8e550562daa48716e0e21c1ea4e68bb22ef6798b72b7260029b5200cc9d864d633a4101514338b60d541",
          "sha256": "48356ff901bead9b6d766848381c268634d976dd7286d0040e65f1d49642b1fa",
          "sha1": "7e1500663c90b3486c1f1710d13f854a2ea4e7e0",
          "md5": "776ebbf941bfbfb1099647753a4a935b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.2.4.aar",
          "url": "ble-characteristic-u2a5b-android-0.2.4.aar",
          "size": 3175,
          "sha512": "2b3e13d3e893570e1fbfd9ce7decf326dd03ad26cf9b8e550562daa48716e0e21c1ea4e68bb22ef6798b72b7260029b5200cc9d864d633a4101514338b60d541",
          "sha256": "48356ff901bead9b6d766848381c268634d976dd7286d0040e65f1d49642b1fa",
          "sha1": "7e1500663c90b3486c1f1710d13f854a2ea4e7e0",
          "md5": "776ebbf941bfbfb1099647753a4a935b"
        }
      ]
    }
  ]
}
