{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-hrp-central-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tjm7btukizgyjma4dor3p6vgce"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-cental-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-hrp-central-android-0.1.0.aar",
          "url": "ble-profile-hrp-central-android-0.1.0.aar",
          "size": 5635,
          "sha512": "69f10136de3260f3856ffa1c823d3b993d4dc3c511536680c9909e71272e36d8a4061d5bf92e718f642d0f80249b0f0ff761f8afcf41be25384fde1e5d961b21",
          "sha256": "426a575b2d999ab8fa44cc512eb1d56b1ecd4599db16b4eb088404b3a334ad1e",
          "sha1": "b71252be3237c0980661d6316ca3672b6ba2d38e",
          "md5": "3175962a4084cc23c7a413d4c52cf205"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-cental-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-hrp-central-android-0.1.0.aar",
          "url": "ble-profile-hrp-central-android-0.1.0.aar",
          "size": 5635,
          "sha512": "69f10136de3260f3856ffa1c823d3b993d4dc3c511536680c9909e71272e36d8a4061d5bf92e718f642d0f80249b0f0ff761f8afcf41be25384fde1e5d961b21",
          "sha256": "426a575b2d999ab8fa44cc512eb1d56b1ecd4599db16b4eb088404b3a334ad1e",
          "sha1": "b71252be3237c0980661d6316ca3672b6ba2d38e",
          "md5": "3175962a4084cc23c7a413d4c52cf205"
        }
      ]
    }
  ]
}
