{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b39-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b39",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b39-android-0.8.12.aar",
          "url": "ble-characteristic-u2b39-android-0.8.12.aar",
          "size": 3143,
          "sha512": "5ba187927036e851c1757d161170c59ae9fdbfe8ad5adf8e1b6c85cd8e0107bfe720bf5861387735c1af6b57c4cde9260149d2c1fc4e40d4f8069c23046fb123",
          "sha256": "4b21240056fa24082807483f2d59bda49bc8443d89ff8834dc7b7fe950fc07dc",
          "sha1": "82f1ea9297c52be95f58a9779523ab76bc29a2db",
          "md5": "bf58ef4c4977b3de8ad706e06e3f6c0b"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b39",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b39-android-0.8.12.aar",
          "url": "ble-characteristic-u2b39-android-0.8.12.aar",
          "size": 3143,
          "sha512": "5ba187927036e851c1757d161170c59ae9fdbfe8ad5adf8e1b6c85cd8e0107bfe720bf5861387735c1af6b57c4cde9260149d2c1fc4e40d4f8069c23046fb123",
          "sha256": "4b21240056fa24082807483f2d59bda49bc8443d89ff8834dc7b7fe950fc07dc",
          "sha1": "82f1ea9297c52be95f58a9779523ab76bc29a2db",
          "md5": "bf58ef4c4977b3de8ad706e06e3f6c0b"
        }
      ]
    }
  ]
}
