{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab4-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.2.6.aar",
          "url": "ble-characteristic-u2ab4-android-0.2.6.aar",
          "size": 3077,
          "sha512": "e2c4e9a5f49942474c6da26b02acfe6936a6d4e097237cfb8f7b7fec347c38f9bf9f23e8ee5e23984d1310801fd76ae38220683de6376d5f84baf224ecf4851c",
          "sha256": "442c829a56f0c1b85a20ff3e9164041c54aa9bebf2161fea60f8f46ebb68c33d",
          "sha1": "b56188268fe2f92156dbe511d6f0962e5bb2244e",
          "md5": "4e194485bcf5f383330ac072c6eb1070"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.2.6.aar",
          "url": "ble-characteristic-u2ab4-android-0.2.6.aar",
          "size": 3077,
          "sha512": "e2c4e9a5f49942474c6da26b02acfe6936a6d4e097237cfb8f7b7fec347c38f9bf9f23e8ee5e23984d1310801fd76ae38220683de6376d5f84baf224ecf4851c",
          "sha256": "442c829a56f0c1b85a20ff3e9164041c54aa9bebf2161fea60f8f46ebb68c33d",
          "sha1": "b56188268fe2f92156dbe511d6f0962e5bb2244e",
          "md5": "4e194485bcf5f383330ac072c6eb1070"
        }
      ]
    }
  ]
}
