{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-profile",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-profile-0.8.7.jar",
          "url": "ble-core-constants-profile-0.8.7.jar",
          "size": 4340,
          "sha512": "9244c5ae67f4ed252df8dd2f202a9aaa7c74225163e496da3d3e381554dbdc61a1f1c493a85aafb8ebc2359c4e6746a8df1d8e25df07d4ea45d0bc63821cdbdd",
          "sha256": "447d27ff7676d5ad95b8ac0399207438b22b3640293ed2e3246ee4b1d7e2a214",
          "sha1": "c5614585e6b476ac98942f59d54694c57a8de3a0",
          "md5": "70db12a893396781e8ee9b3b3e250187"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-profile-0.8.7.jar",
          "url": "ble-core-constants-profile-0.8.7.jar",
          "size": 4340,
          "sha512": "9244c5ae67f4ed252df8dd2f202a9aaa7c74225163e496da3d3e381554dbdc61a1f1c493a85aafb8ebc2359c4e6746a8df1d8e25df07d4ea45d0bc63821cdbdd",
          "sha256": "447d27ff7676d5ad95b8ac0399207438b22b3640293ed2e3246ee4b1d7e2a214",
          "sha1": "c5614585e6b476ac98942f59d54694c57a8de3a0",
          "md5": "70db12a893396781e8ee9b3b3e250187"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-profile-0.8.7-javadoc.jar",
          "url": "ble-core-constants-profile-0.8.7-javadoc.jar",
          "size": 106336,
          "sha512": "ac7a46d651c1a114ea5a6d6ff14e47c2d7cba0ede45d82be2e90446e1f4e2e0ee1dfb34c9d9eca09905ea29ae6a2f12bd78f326c6b02df0e46cbc65aef2403a7",
          "sha256": "b37486b34771abd9a791f1b39f9cfb23085bf0beb46cba73f671aed9bfce4d2c",
          "sha1": "3b55d4e37f753f81066e7255f54d06ba124383b7",
          "md5": "38a56e978d10f4e60080082e773ff8b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-profile-0.8.7-sources.jar",
          "url": "ble-core-constants-profile-0.8.7-sources.jar",
          "size": 2125,
          "sha512": "89c0c6fa476aa0cc778dc5cd64f3f919e5834df3f8359b9aa772507faea92ffaa92ab3f327a1cfbf794007b946343a7fbeb9cf2565c3435ea56b22d2a30c9334",
          "sha256": "da307cdef3b49209666ab32de1cded846ddebdfe2127151f175dae715d164426",
          "sha1": "9a88f40f56d33661d1602a01ff954585f26466ee",
          "md5": "948c819dae2b1ee505975713bc9f85e7"
        }
      ]
    }
  ]
}
