{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-hts-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "onm7oav7y5gufewzovq4jjg3iy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-central-android-0.1.4.aar",
          "url": "ble-service-hts-central-android-0.1.4.aar",
          "size": 7931,
          "sha512": "a67c9b70fda1feb68ce9e4cb04a654a012aba3d1297a89c34ea6e1893dc7b9a8bf754d4870a9b8b4d753bd400e6f8c1306f7369207b965ba36efaf6267cffd32",
          "sha256": "4eab9b8a0410b0e0fc0d03b2e876b62a909fc63426313df364d8a12cfeaf8db6",
          "sha1": "ab719ebff644a4cedddebf61ce87d8b99c911ea0",
          "md5": "57bf7948fe485a2b0d0ef06c388dacae"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-central-android-0.1.4.aar",
          "url": "ble-service-hts-central-android-0.1.4.aar",
          "size": 7931,
          "sha512": "a67c9b70fda1feb68ce9e4cb04a654a012aba3d1297a89c34ea6e1893dc7b9a8bf754d4870a9b8b4d753bd400e6f8c1306f7369207b965ba36efaf6267cffd32",
          "sha256": "4eab9b8a0410b0e0fc0d03b2e876b62a909fc63426313df364d8a12cfeaf8db6",
          "sha1": "ab719ebff644a4cedddebf61ce87d8b99c911ea0",
          "md5": "57bf7948fe485a2b0d0ef06c388dacae"
        }
      ]
    }
  ]
}
