{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-lns-android",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-lns-android-0.6.1.aar",
          "url": "ble-service-peripheral-lns-android-0.6.1.aar",
          "size": 10928,
          "sha512": "3f589e0720867e198320fb810ea5b3ae4fe73fd931681129e49b346f48cdee60dab32c2f35b27141209096a5c055826a4d379e897ddffe17aec25c48e0b0b656",
          "sha256": "3a284cbaf8283ac1af514a5bc66863a10c37e10e28e3033cf5ff216c98a0541f",
          "sha1": "f530658230c4ac347bd1c181ef3b035d33c6931f",
          "md5": "4ed5be18633dcffec15b78d096c610d1"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-lns-android-0.6.1.aar",
          "url": "ble-service-peripheral-lns-android-0.6.1.aar",
          "size": 10928,
          "sha512": "3f589e0720867e198320fb810ea5b3ae4fe73fd931681129e49b346f48cdee60dab32c2f35b27141209096a5c055826a4d379e897ddffe17aec25c48e0b0b656",
          "sha256": "3a284cbaf8283ac1af514a5bc66863a10c37e10e28e3033cf5ff216c98a0541f",
          "sha1": "f530658230c4ac347bd1c181ef3b035d33c6931f",
          "md5": "4ed5be18633dcffec15b78d096c610d1"
        }
      ]
    }
  ]
}
