{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc6-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc6",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-android-0.8.9.aar",
          "url": "ble-characteristic-u2bc6-android-0.8.9.aar",
          "size": 3149,
          "sha512": "e8ec9a6c91c977742a7f4db6b3834a0bca37667ef55da49cd4a7260702b44a76e5267a08d1c52572144c0553fb037bfc729fe1dc9ce02e3244e012012a972cf3",
          "sha256": "c0812a3e956a1d63656936848a2aeaf90b2d032d6398d431d71ad4bb05ecff17",
          "sha1": "2b12e4544b1e4e5cefe1a8e8daf31276e7c3b12f",
          "md5": "7f7e56bab4b69c7f128a4ea7f45f6ccd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc6",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-android-0.8.9.aar",
          "url": "ble-characteristic-u2bc6-android-0.8.9.aar",
          "size": 3149,
          "sha512": "e8ec9a6c91c977742a7f4db6b3834a0bca37667ef55da49cd4a7260702b44a76e5267a08d1c52572144c0553fb037bfc729fe1dc9ce02e3244e012012a972cf3",
          "sha256": "c0812a3e956a1d63656936848a2aeaf90b2d032d6398d431d71ad4bb05ecff17",
          "sha1": "2b12e4544b1e4e5cefe1a8e8daf31276e7c3b12f",
          "md5": "7f7e56bab4b69c7f128a4ea7f45f6ccd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2bc6-android-0.8.9-sources.jar",
          "size": 2152,
          "sha512": "29b5d1a690192044da5e12204c140376e6fffcbfd6468a6a712eed760ffa9be2f64c3b26aca2d2ce777b4356017ae568df748336a015c2ea6fb0b217bac0b26b",
          "sha256": "6c198d164d736734bc1b00a9bda980a651825c06eb6c46acaf2f23afc87d4127",
          "sha1": "2f54c29646ac638f9e85c1fd20927a4a381bd522",
          "md5": "c395e1ce54de9ebec187d35d80370d31"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2bc6-android-0.8.9-javadoc.jar",
          "size": 270515,
          "sha512": "1678495640c805f5418145bd5e9fe7edf9edc9a428e73251461ad9d9ce3e48b933bc90989d3f4675af9f6400cf83e44f909c5ec031b00a12d2f4178d2ab34b97",
          "sha256": "d52c11fb9905784fcff7bb724f7aa9597c0152ae578c67ccf6857dbafbd9f1ca",
          "sha1": "f13e38a12fc6b64555b847a70c64bc57ca571d65",
          "md5": "48515b93bd88102d201b74953c9378ed"
        }
      ]
    }
  ]
}
