{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a98",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "pb2nsyt4f5arfmm5vvi2kskfq4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-0.2.5.jar",
          "url": "ble-characteristic-u2a98-0.2.5.jar",
          "size": 1833,
          "sha512": "670ab09985325b0b492b2692aaa1229363aff2fe9601db32ce921351d991412c01594f3ae49b7a5fd447eceff235f8ce26eda8f7b8b664eec7648e7c03274a79",
          "sha256": "2ec7b8752fee0bd7ad38ecdb77656679c238834d1c9955c7af0fbf5691c5d541",
          "sha1": "acc65d552a61489fb2209292236b0ab20c742ef5",
          "md5": "2d818260a9ed2e534e70e33085889ae9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-0.2.5.jar",
          "url": "ble-characteristic-u2a98-0.2.5.jar",
          "size": 1833,
          "sha512": "670ab09985325b0b492b2692aaa1229363aff2fe9601db32ce921351d991412c01594f3ae49b7a5fd447eceff235f8ce26eda8f7b8b664eec7648e7c03274a79",
          "sha256": "2ec7b8752fee0bd7ad38ecdb77656679c238834d1c9955c7af0fbf5691c5d541",
          "sha1": "acc65d552a61489fb2209292236b0ab20c742ef5",
          "md5": "2d818260a9ed2e534e70e33085889ae9"
        }
      ]
    }
  ]
}
