{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-aios-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-android",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-aios-android-0.4.3.aar",
          "url": "ble-service-central-aios-android-0.4.3.aar",
          "size": 16530,
          "sha512": "33e9124cd5e3db66375297b63b272000ae5450cec026899b5ce759e33336d660338cb975dac518803667c0b5d3045a8c174b0b20d4861a2441af5745b202d712",
          "sha256": "7f003b77d3a43f2c474a54b36d577791a5f9c8ed29ca000d8cfb25d491ede3f9",
          "sha1": "3da3bfbb73d4af42dd8cba7ade5155a99b963280",
          "md5": "4514984264bf8b30a5928a3354418ff5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-android",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-aios-android-0.4.3.aar",
          "url": "ble-service-central-aios-android-0.4.3.aar",
          "size": 16530,
          "sha512": "33e9124cd5e3db66375297b63b272000ae5450cec026899b5ce759e33336d660338cb975dac518803667c0b5d3045a8c174b0b20d4861a2441af5745b202d712",
          "sha256": "7f003b77d3a43f2c474a54b36d577791a5f9c8ed29ca000d8cfb25d491ede3f9",
          "sha1": "3da3bfbb73d4af42dd8cba7ade5155a99b963280",
          "md5": "4514984264bf8b30a5928a3354418ff5"
        }
      ]
    }
  ]
}
