{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a73-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a73",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a73-android-0.2.2.aar",
          "url": "ble-characteristic-u2a73-android-0.2.2.aar",
          "size": 2937,
          "sha512": "7cb066f815c55a72921144a097678671eed99be7b637936c814299f940c0413473b10bb892cc1577ecb080f062553e2e30cde95317df2c3ba045219dfa8fee1f",
          "sha256": "8e4de0e1a16fb0407ae0f53746fefb066a9576ceab94975118dd894f87c77889",
          "sha1": "210824f5b915261dfae49295f7d543524ddba5ad",
          "md5": "99daaea3b4dc9b5e7710fc367ab049fa"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a73",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a73-android-0.2.2.aar",
          "url": "ble-characteristic-u2a73-android-0.2.2.aar",
          "size": 2937,
          "sha512": "7cb066f815c55a72921144a097678671eed99be7b637936c814299f940c0413473b10bb892cc1577ecb080f062553e2e30cde95317df2c3ba045219dfa8fee1f",
          "sha256": "8e4de0e1a16fb0407ae0f53746fefb066a9576ceab94975118dd894f87c77889",
          "sha1": "210824f5b915261dfae49295f7d543524ddba5ad",
          "md5": "99daaea3b4dc9b5e7710fc367ab049fa"
        }
      ]
    }
  ]
}
