{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-rscs-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rscs-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-rscs-android-0.8.7.aar",
          "url": "ble-service-peripheral-rscs-android-0.8.7.aar",
          "size": 13921,
          "sha512": "6271a5bc24ef2619849e45c4be9072b5d74934ee812c63ed2908e2e005d37be0c81777e17010732f3ea061919230386df4544eb2aa16becf074a9273bb847505",
          "sha256": "b26b1b216c7a2430842ce3461ddf4c8e1433b0615502baf4a0c0c711adb21337",
          "sha1": "8dae51b37d72f0916dc238ccb1d7ff9adf7f40be",
          "md5": "cc6f4be5ee387d007902c134b9e379cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rscs-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-rscs-android-0.8.7.aar",
          "url": "ble-service-peripheral-rscs-android-0.8.7.aar",
          "size": 13921,
          "sha512": "6271a5bc24ef2619849e45c4be9072b5d74934ee812c63ed2908e2e005d37be0c81777e17010732f3ea061919230386df4544eb2aa16becf074a9273bb847505",
          "sha256": "b26b1b216c7a2430842ce3461ddf4c8e1433b0615502baf4a0c0c711adb21337",
          "sha1": "8dae51b37d72f0916dc238ccb1d7ff9adf7f40be",
          "md5": "cc6f4be5ee387d007902c134b9e379cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-peripheral-rscs-android-0.8.7-sources.jar",
          "url": "ble-service-peripheral-rscs-android-0.8.7-sources.jar",
          "size": 8785,
          "sha512": "2e391243f25f0469a49ae469d6315dbbaa519a12b1a5f649891c495038cae899f17878c2ec406d677094e9b258d636eddb837da3c4147ba8ca56b60d02c8e9ff",
          "sha256": "442c3cac471d4ee742fc969ec974fca2f2a092bffa7cff32d2189f0c18829a54",
          "sha1": "322b706b60838ffccf908c2db2a9dae6e1ebb788",
          "md5": "c025d746fcf5be6fcd6f9235c8e0fe33"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-peripheral-rscs-android-0.8.7-javadoc.jar",
          "url": "ble-service-peripheral-rscs-android-0.8.7-javadoc.jar",
          "size": 299865,
          "sha512": "f61c2a57f80f18c3630e51a76469e4d300f34bc31a989f721d883c6d613f4eb56dc437984e4580b8c4a53e10b9e69057979e33781c3e323630c4f1799d807548",
          "sha256": "156d9836e4aa0d6b534abc241e7eec4e9dda6215448b8af9e0cfe07f979f00a3",
          "sha1": "a21c9a8e56db81a5e128e441e9d1fd58256848ef",
          "md5": "09abaf65a5640e8411289eb7506091a0"
        }
      ]
    }
  ]
}
