{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a83-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fxrmxjl6szatjaovsgygwi5l4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a83",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a83-android-0.2.4.aar",
          "url": "ble-characteristic-u2a83-android-0.2.4.aar",
          "size": 3107,
          "sha512": "3a2c710f7521d017d1a1f148decfea1227a96afc3ed283f00703ad8dcc2eac3d9546a0a2da662198cc81e12874aa5899710c0973f3b6a61fcf4bb15e8bc0817f",
          "sha256": "989aa5383943cc10a3a3292584345870b204875c76862bf9b368805d7cbcea5e",
          "sha1": "cdd593cc652b0e950a4415ee6f6709bd1d92b2f1",
          "md5": "092a27c57fe075e7a0b71b335251d440"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a83",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a83-android-0.2.4.aar",
          "url": "ble-characteristic-u2a83-android-0.2.4.aar",
          "size": 3107,
          "sha512": "3a2c710f7521d017d1a1f148decfea1227a96afc3ed283f00703ad8dcc2eac3d9546a0a2da662198cc81e12874aa5899710c0973f3b6a61fcf4bb15e8bc0817f",
          "sha256": "989aa5383943cc10a3a3292584345870b204875c76862bf9b368805d7cbcea5e",
          "sha1": "cdd593cc652b0e950a4415ee6f6709bd1d92b2f1",
          "md5": "092a27c57fe075e7a0b71b335251d440"
        }
      ]
    }
  ]
}
