{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad8-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-android-0.4.6.aar",
          "url": "ble-characteristic-u2ad8-android-0.4.6.aar",
          "size": 3182,
          "sha512": "ca8e676ff6af4cf3bc6aae934bcef31069844438824bd484c3a535eab730a9b31d43c32f8d3931556f491122f32bbc07dbaf21d4d2d8be59027a8f3f5f7bda85",
          "sha256": "5218011155f7902e27f5e54519efcfd5ef890b350459003acb19a7f440d3662c",
          "sha1": "81b96fb98c06774c4e25d380584b7d4ab8d1e578",
          "md5": "d7de124d10bbb758ac7c795adb03bff0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-android-0.4.6.aar",
          "url": "ble-characteristic-u2ad8-android-0.4.6.aar",
          "size": 3182,
          "sha512": "ca8e676ff6af4cf3bc6aae934bcef31069844438824bd484c3a535eab730a9b31d43c32f8d3931556f491122f32bbc07dbaf21d4d2d8be59027a8f3f5f7bda85",
          "sha256": "5218011155f7902e27f5e54519efcfd5ef890b350459003acb19a7f440d3662c",
          "sha1": "81b96fb98c06774c4e25d380584b7d4ab8d1e578",
          "md5": "d7de124d10bbb758ac7c795adb03bff0"
        }
      ]
    }
  ]
}
