{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-aiop-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-aios-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-aiop-android-0.8.10.aar",
          "url": "ble-profile-peripheral-aiop-android-0.8.10.aar",
          "size": 6640,
          "sha512": "cc8cd893da32fab50fd1dc3564148eb3fc431deff2ebb19d6f17c0cb706518e173cec56a3777dcdbeae15a8b58fffde1fd5fa1a786ee9f6d4ff026105c081ab5",
          "sha256": "52521c2b974b3fe672695faaf354d265da3fac14ec2abb619fefaa36415b1241",
          "sha1": "98344e37c580da8201d91b68152811a64ee8cff3",
          "md5": "fec721ba99af5fc5a180e08398bf3c14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-aios-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-aiop-android-0.8.10.aar",
          "url": "ble-profile-peripheral-aiop-android-0.8.10.aar",
          "size": 6640,
          "sha512": "cc8cd893da32fab50fd1dc3564148eb3fc431deff2ebb19d6f17c0cb706518e173cec56a3777dcdbeae15a8b58fffde1fd5fa1a786ee9f6d4ff026105c081ab5",
          "sha256": "52521c2b974b3fe672695faaf354d265da3fac14ec2abb619fefaa36415b1241",
          "sha1": "98344e37c580da8201d91b68152811a64ee8cff3",
          "md5": "fec721ba99af5fc5a180e08398bf3c14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-aiop-android-0.8.10-sources.jar",
          "url": "ble-profile-peripheral-aiop-android-0.8.10-sources.jar",
          "size": 4123,
          "sha512": "4b521478627dd61a2a3cebbfd8ee42e95f5ccbe61ab87de8d3e1b351d1acd88ab77d8b45f258f5d8258df88e8561ea58fab0264eeb25846f8e5a6ee4ea5df2c4",
          "sha256": "45f22da0292c080e0639be8dd5c38af4355b52bf8406dd96ca7ee3417621b23b",
          "sha1": "942473f384b30943094056110552859b0aa121d8",
          "md5": "13f0cd113d039556ceeb05f1e327dec2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-aiop-android-0.8.10-javadoc.jar",
          "url": "ble-profile-peripheral-aiop-android-0.8.10-javadoc.jar",
          "size": 292497,
          "sha512": "64fd849d8b46d2deacd4d3292b88be6e92853af1296924593bf81f9e07f8cde7eff7a901a8aacdcf08613f5b2f76d4210fcf05ba37f96ae900902b6d1b754d66",
          "sha256": "9f3affd0b1380522e6050efee067dc9ed194a630abdac353bdf2e676d23a15e1",
          "sha1": "ac4d0793e1f7f2180c777725160ed0a8078d5546",
          "md5": "5d306b0704e90d5ecbfd1aa5561848a0"
        }
      ]
    }
  ]
}
