{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a25-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.8.13.aar",
          "url": "ble-characteristic-u2a25-android-0.8.13.aar",
          "size": 3146,
          "sha512": "3d2f99a8a3688410aa5f89a9e1615a6c53dbc7919ae1af32b9732604f10490e9d91ff1fe5950f7a77946f53a5b7fe8a1619e9a0391292da65a1c993b98ebffa9",
          "sha256": "f00bfe6a8d45dd4007fba7bc8786befe7b5beb5ff1ebad482046db6ba6800e8b",
          "sha1": "09a4e561ffe9bd5ddfd39a6fff59a075a7a02784",
          "md5": "332f55867c52c531aad353fd07d9f6b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.8.13.aar",
          "url": "ble-characteristic-u2a25-android-0.8.13.aar",
          "size": 3146,
          "sha512": "3d2f99a8a3688410aa5f89a9e1615a6c53dbc7919ae1af32b9732604f10490e9d91ff1fe5950f7a77946f53a5b7fe8a1619e9a0391292da65a1c993b98ebffa9",
          "sha256": "f00bfe6a8d45dd4007fba7bc8786befe7b5beb5ff1ebad482046db6ba6800e8b",
          "sha1": "09a4e561ffe9bd5ddfd39a6fff59a075a7a02784",
          "md5": "332f55867c52c531aad353fd07d9f6b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2a25-android-0.8.13-sources.jar",
          "size": 2206,
          "sha512": "ecdd0fa016b15c1805373eef8c610321a4dfc3a56cafec4ea9c03c7ffb1398f706ea534df407af4b5aff178b46a08eb26e489f9b6114c61557428ef5ebc93c58",
          "sha256": "0c4213e08d92a96db710cc75f38c21d57cad044ac70986ed4b4eb3a81f2a0c75",
          "sha1": "8635b6c78f60bdb582e94200c67c5fec14c1c8db",
          "md5": "b72deea307f0c5faea7404d4bf315ec6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2a25-android-0.8.13-javadoc.jar",
          "size": 271150,
          "sha512": "3060125fdf6c08678b9a47d7feaa28c7649b6cf819dfd2eaf7d595c561301578eac17ba19c137078a82d20fb5851b9b003ac2eab623dfaad9ab70a901e98c832",
          "sha256": "e9a9843124ac2daf8b31b2e3313d468859e6e089d049863e0edd8e421dba0818",
          "sha1": "3626e71031a775a2a98b53600bd50106ba90cf4c",
          "md5": "3635df01f5dee00c70f242801697443e"
        }
      ]
    }
  ]
}
