{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-errorcode-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-errorcode-android-0.4.5.aar",
          "url": "ble-core-constants-errorcode-android-0.4.5.aar",
          "size": 1552,
          "sha512": "c704b57c85c287ece1f55c1a8e3927d6a86f65ac53d1e026a394ab19339fbc8c7b67515a08a712c4b9f4ebdc054be9c8e0cc26823bd2feda01bd01050a81f058",
          "sha256": "c7e9382c4a8f7933700ef7a764e4afc2c8344416b427876bd113f3aaccd258e8",
          "sha1": "3fe7ecde5b31573007b4b7fa962317c7107f4f18",
          "md5": "2c47dd784e5f7059b9311185f3e6d45e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-errorcode-android-0.4.5.aar",
          "url": "ble-core-constants-errorcode-android-0.4.5.aar",
          "size": 1552,
          "sha512": "c704b57c85c287ece1f55c1a8e3927d6a86f65ac53d1e026a394ab19339fbc8c7b67515a08a712c4b9f4ebdc054be9c8e0cc26823bd2feda01bd01050a81f058",
          "sha256": "c7e9382c4a8f7933700ef7a764e4afc2c8344416b427876bd113f3aaccd258e8",
          "sha1": "3fe7ecde5b31573007b4b7fa962317c7107f4f18",
          "md5": "2c47dd784e5f7059b9311185f3e6d45e"
        }
      ]
    }
  ]
}
