{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb1-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb1",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb1-android-0.8.14.aar",
          "url": "ble-characteristic-u2bb1-android-0.8.14.aar",
          "size": 3183,
          "sha512": "60a8eee1a0b755c4b12e9791c3e635a20740937507db835d3ec788846c01ec98d3f172b38a0b3d19a087652a25435d3928115bf4b497dde5d6ecba363483d146",
          "sha256": "4637da7d9c685c9db587643de77f12841aa65aa3c6fcab21e43b5c97b423db50",
          "sha1": "4da890766fe877782457d6549ded9be53ce78736",
          "md5": "d7032f2dc9f222bb6f4734d0f6191f96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb1",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb1-android-0.8.14.aar",
          "url": "ble-characteristic-u2bb1-android-0.8.14.aar",
          "size": 3183,
          "sha512": "60a8eee1a0b755c4b12e9791c3e635a20740937507db835d3ec788846c01ec98d3f172b38a0b3d19a087652a25435d3928115bf4b497dde5d6ecba363483d146",
          "sha256": "4637da7d9c685c9db587643de77f12841aa65aa3c6fcab21e43b5c97b423db50",
          "sha1": "4da890766fe877782457d6549ded9be53ce78736",
          "md5": "d7032f2dc9f222bb6f4734d0f6191f96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb1-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2bb1-android-0.8.14-sources.jar",
          "size": 2251,
          "sha512": "9a9f9238a48ac561cd41530fdccb4930b08dd193555c18a4d04104218444b4668d908506d97b10ff6010feaa6478c3a3c4e04c0a8e728d84339c4691cbadbea5",
          "sha256": "a51e3408a04dd585239cd439345ca9d0b3c1bebf77190d586617e734c2d122fd",
          "sha1": "351cdf4f1b331f7a87469d018c1d2957c24e382d",
          "md5": "427c9f149204bc3ac05505c6767e372c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb1-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2bb1-android-0.8.14-javadoc.jar",
          "size": 271278,
          "sha512": "4b41674a59359aab02eda58ed3d39c47cd41119f00b002924c72192ded556fe59edd7ee790860cd6f60f4e340722aef51c661e99159b53e3a61bf7ec19205354",
          "sha256": "68a837d90ad85509db73e8682d9b70cff37ca10d1ea6e1e1f31a0aad724fb67a",
          "sha1": "494d57512cec390aab52daa01a62343523bc07e6",
          "md5": "d0fca3e69ecaad0dd20b2a77ef03770b"
        }
      ]
    }
  ]
}
