{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0d",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0d-0.8.9.jar",
          "url": "ble-characteristic-u2b0d-0.8.9.jar",
          "size": 1757,
          "sha512": "f613240538bfe5ba8b065f80b4d484dbcafb02bb859bf5580f51cb02e6a27e65aa8887a0394f642b323fe31b3fe59cc1db21f740b9187bf21f51684809830d7e",
          "sha256": "f022814df61f46c29275ecd24da17a84c8698438266c52ce9c32914d123dfdb1",
          "sha1": "6dd0e933cde5436765cd4c9329b57f1d61f27eff",
          "md5": "d8994627c5394d819af66e83f6fad22c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0d-0.8.9.jar",
          "url": "ble-characteristic-u2b0d-0.8.9.jar",
          "size": 1757,
          "sha512": "f613240538bfe5ba8b065f80b4d484dbcafb02bb859bf5580f51cb02e6a27e65aa8887a0394f642b323fe31b3fe59cc1db21f740b9187bf21f51684809830d7e",
          "sha256": "f022814df61f46c29275ecd24da17a84c8698438266c52ce9c32914d123dfdb1",
          "sha1": "6dd0e933cde5436765cd4c9329b57f1d61f27eff",
          "md5": "d8994627c5394d819af66e83f6fad22c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0d-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2b0d-0.8.9-javadoc.jar",
          "size": 107325,
          "sha512": "372eb7b9f54507c674b2cf7e8195b1236e0b9d034e422923d392dbb1ef1f7090fe4d8a373736a7da34230a71d48827d660f74bab32c52f375b3bf1399b72cd11",
          "sha256": "c24b54bae2a7f246329b0f363482e5a56fb3ca21679e705780bbab5317c63a3c",
          "sha1": "7f3049ea788b1d7d4d4e7eff664ee0e1c79e444a",
          "md5": "01d7b68a0681fd969fd5aa7d517b0450"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0d-0.8.9-sources.jar",
          "url": "ble-characteristic-u2b0d-0.8.9-sources.jar",
          "size": 1596,
          "sha512": "bdf60512819f093c48d6c88d582f94fb026a4e553a74edb4f951abb65a8ed48df0d7b9cd42af58ef2f7e1d7d654da68169740282429a36a3174ce14095837633",
          "sha256": "8ed9c12893b9069de86fde30576e58c7b980d09b07d76ff7be7f6e155a32247f",
          "sha1": "5934e7fe59dd8b644fe8e36d3abc98c82d532660",
          "md5": "da9e47d27fa5ace263474f887f0dedad"
        }
      ]
    }
  ]
}
