{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b25",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.6.jar",
          "url": "ble-characteristic-u2b25-0.8.6.jar",
          "size": 1473,
          "sha512": "2afce852a0fd67989888e5c3742ba6e3be1382e27e24feee6761b58b3183802855e6f9f4e89a78f56d0cc7a353167a6d4ca02ca7807ea9b5ed932f4e6246cc19",
          "sha256": "4b8bac04225fd5374f584704eb2579fac0ad8331b493f45a239ccf7504755f62",
          "sha1": "7f66d884aaa95557c594fe94dc5a18605729f318",
          "md5": "a6de723607be9dd7644c40ae5dda6be5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.6.jar",
          "url": "ble-characteristic-u2b25-0.8.6.jar",
          "size": 1473,
          "sha512": "2afce852a0fd67989888e5c3742ba6e3be1382e27e24feee6761b58b3183802855e6f9f4e89a78f56d0cc7a353167a6d4ca02ca7807ea9b5ed932f4e6246cc19",
          "sha256": "4b8bac04225fd5374f584704eb2579fac0ad8331b493f45a239ccf7504755f62",
          "sha1": "7f66d884aaa95557c594fe94dc5a18605729f318",
          "md5": "a6de723607be9dd7644c40ae5dda6be5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2b25-0.8.6-javadoc.jar",
          "size": 107244,
          "sha512": "ee1e2245298e7d6827d81d9219c7ec159083376d9b011fd16fc043682b82507cd5d3b8d8766e88ffd390e86a9c9c082d26ed9063dc27746f1bc2e34214b21d93",
          "sha256": "6d8a16391a817d7b763107b50b98022008552441dda6e447850cd052d0d66122",
          "sha1": "84b1af0c3fa42bd5c4b6d86fd1aba771bbad88da",
          "md5": "71e6c47408a57f56c8fef2e4fc059597"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b25-0.8.6-sources.jar",
          "size": 1467,
          "sha512": "5357aa1671d2bbcbe6071c290dc2a22e9ad608123995e70e1127d49902e3bb6607191eb5b378106f20a8e16f06582d994b9f5443c20aa3833780994da3dc7048",
          "sha256": "6572a4784c5f0648b5c83ac01f75e80596fe4b71b2d697221c1916684f4fbb42",
          "sha1": "04e34c2bda7ca228ed15669ef60530df9dcc534e",
          "md5": "a2f1bdadfe4d2e76fd5cd7e0ccc31d47"
        }
      ]
    }
  ]
}
