{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a89",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "6exsxox6gvho3e4ayov5pi6vnu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-0.2.5.jar",
          "url": "ble-characteristic-u2a89-0.2.5.jar",
          "size": 1764,
          "sha512": "d5e1cb8ffccd3e7f2273d98bc4744e731e7fa75e97cf1016f0107ed7f275bf6a3123eab13db6693436c61276ad69f1e4e56a57dd205d47d7949325d635fc75c7",
          "sha256": "f661d7133b73f2d3765832dbd9bd278a92c77c47f2b5d6419278a93751876d1e",
          "sha1": "dc634d692205b79f7b021f94dda54fea105a13bf",
          "md5": "85f34bb8d95fcb0984d94bb6063f3346"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-0.2.5.jar",
          "url": "ble-characteristic-u2a89-0.2.5.jar",
          "size": 1764,
          "sha512": "d5e1cb8ffccd3e7f2273d98bc4744e731e7fa75e97cf1016f0107ed7f275bf6a3123eab13db6693436c61276ad69f1e4e56a57dd205d47d7949325d635fc75c7",
          "sha256": "f661d7133b73f2d3765832dbd9bd278a92c77c47f2b5d6419278a93751876d1e",
          "sha1": "dc634d692205b79f7b021f94dda54fea105a13bf",
          "md5": "85f34bb8d95fcb0984d94bb6063f3346"
        }
      ]
    }
  ]
}
