{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-aios-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-android",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-aios-android-0.8.14.aar",
          "url": "ble-service-central-aios-android-0.8.14.aar",
          "size": 16641,
          "sha512": "1bf88923ecc8c0d611cc0c586dcc2c75af6707a561ecf0029e34f095360fd50f4376c571d6c7ae84fbbb193f5cdeaa9115dfa7ecfb33bb0cf3cdb6807bade467",
          "sha256": "162ac653a57b394404082a4d0ffc7ddb9180e965faad73edc32863ff0ee9b1eb",
          "sha1": "cc3e37160c321318d9e5801548ad54a6f9f22b2f",
          "md5": "828e560bc5adbaf50021baf6be6b7c96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-android",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-aios-android-0.8.14.aar",
          "url": "ble-service-central-aios-android-0.8.14.aar",
          "size": 16641,
          "sha512": "1bf88923ecc8c0d611cc0c586dcc2c75af6707a561ecf0029e34f095360fd50f4376c571d6c7ae84fbbb193f5cdeaa9115dfa7ecfb33bb0cf3cdb6807bade467",
          "sha256": "162ac653a57b394404082a4d0ffc7ddb9180e965faad73edc32863ff0ee9b1eb",
          "sha1": "cc3e37160c321318d9e5801548ad54a6f9f22b2f",
          "md5": "828e560bc5adbaf50021baf6be6b7c96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-aios-android-0.8.14-sources.jar",
          "url": "ble-service-central-aios-android-0.8.14-sources.jar",
          "size": 14631,
          "sha512": "453ce25c4e6fad6f40853d7e6bdc4875dcfcfad8a5e46f11c7ec6f286054feca0e8ecf7c82fe9742f0bd851df8a4bd81fab6e099d8c9ffcb07491c8c2b0e4cc8",
          "sha256": "1a52d594deef9910a818d73eb107c3c743d2b251a95935b066803fc0f6243b60",
          "sha1": "6c40970dc463d6b956adf090703ca713d5b9afa8",
          "md5": "cb901bd7460ca1394596041f98e14714"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-aios-android-0.8.14-javadoc.jar",
          "url": "ble-service-central-aios-android-0.8.14-javadoc.jar",
          "size": 316006,
          "sha512": "92df8cb2b7750c39c6b9cefc146cb6fdc869eb3cbcba1c0d119dfe7faf4ec644eb52d54d112d071d9f7b97ce55fab8dd9d8c05afc6edc59c715489fb86f878f3",
          "sha256": "224993fbc1a791aefeca8a9e274fe9a7b936eef6ac39fbec050105f6e9e6cf71",
          "sha1": "49ce9f5245c79e3a717c4f42167ee838f6187174",
          "md5": "49bea7251e22d4289e6af68f4ad3187c"
        }
      ]
    }
  ]
}
