{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba4-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba4-android-0.8.6.aar",
          "url": "ble-characteristic-u2ba4-android-0.8.6.aar",
          "size": 3061,
          "sha512": "f99483a01f9417c87c75a660e78dc5d9ca6421e91acabe151c488d43efb24791627f7339c2e8a100f689c583f31b8effbf224d4386b7d5009e08ff4491a06996",
          "sha256": "a6f74b40400f384f323449a4ab049f446306f674bf8aeb124236b648bf8accee",
          "sha1": "adbe7c4f64a0a0bea1309a17a062639d15e1871f",
          "md5": "507671a2060d5ee7ce9c696ef68f192e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba4-android-0.8.6.aar",
          "url": "ble-characteristic-u2ba4-android-0.8.6.aar",
          "size": 3061,
          "sha512": "f99483a01f9417c87c75a660e78dc5d9ca6421e91acabe151c488d43efb24791627f7339c2e8a100f689c583f31b8effbf224d4386b7d5009e08ff4491a06996",
          "sha256": "a6f74b40400f384f323449a4ab049f446306f674bf8aeb124236b648bf8accee",
          "sha1": "adbe7c4f64a0a0bea1309a17a062639d15e1871f",
          "md5": "507671a2060d5ee7ce9c696ef68f192e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba4-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ba4-android-0.8.6-sources.jar",
          "size": 2161,
          "sha512": "6f27f5d043cdb593994fbd4f962f07dbe70892573ea8a86b14689a3751a673ea3765c2d00bb1231f4275e39ea69f8e101100ce8fb7284309f1d6565f5d79d7f1",
          "sha256": "f1610fc670654dd6d1c1ed8444bb1ac3f24594d26693355a9be080165e157250",
          "sha1": "1b7815f01e5512347b35a2f2f1404cefd1b9515d",
          "md5": "73486ac3731612c6f642eada629d91e1"
        }
      ]
    }
  ]
}
