{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-htp-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-hts-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-htp-android-0.8.7.aar",
          "url": "ble-profile-central-htp-android-0.8.7.aar",
          "size": 6898,
          "sha512": "24ba3a8ba2be951f417e5ba9019e7e82e61275da014de23d7e4ecc5db0c84160a009064472eac20bb7001e1ebdd4f30a2c8a95fb536cb9fb7bfd74931b1a60fb",
          "sha256": "adcd1dbeb39fc0a82c7a2688342789dbf849ac8197fa409059e36dc80f3b7036",
          "sha1": "b42bc4bfcba36dd52a4be0322838203bd715afad",
          "md5": "e3e40164eae6c48bfdf0a11e2a2cf0fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-hts-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-htp-android-0.8.7.aar",
          "url": "ble-profile-central-htp-android-0.8.7.aar",
          "size": 6898,
          "sha512": "24ba3a8ba2be951f417e5ba9019e7e82e61275da014de23d7e4ecc5db0c84160a009064472eac20bb7001e1ebdd4f30a2c8a95fb536cb9fb7bfd74931b1a60fb",
          "sha256": "adcd1dbeb39fc0a82c7a2688342789dbf849ac8197fa409059e36dc80f3b7036",
          "sha1": "b42bc4bfcba36dd52a4be0322838203bd715afad",
          "md5": "e3e40164eae6c48bfdf0a11e2a2cf0fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-central-htp-android-0.8.7-sources.jar",
          "url": "ble-profile-central-htp-android-0.8.7-sources.jar",
          "size": 6105,
          "sha512": "4a17eb8bed5ac35e3dcb528918ff4fb27aab2cdbcabccc2d0e9fe9fe375d6ab3c49816183dc5db139016c569f53d686f14390c360e96e6caf97fe6bbc715a92c",
          "sha256": "bc2588e5cf0e9356eebb0eacc730d8628ecf6c98019199fae6e04a4383770c43",
          "sha1": "c35dad5903ea736abb3eea94347cff55706013b0",
          "md5": "e0f0890c6a9c8632e9c954a686e8bc81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-central-htp-android-0.8.7-javadoc.jar",
          "url": "ble-profile-central-htp-android-0.8.7-javadoc.jar",
          "size": 305110,
          "sha512": "7d0cbb165530714b7da2bb94637577545ea0d8b4c2fd1d6eb0440acf793c425db2f782a7e788a222fe20a6747bec19c4880dc5f22b752e58ebf17c4c11f9a628",
          "sha256": "d81499a25f3fb7c05e8183c722d6ce3fe5990acc5a1be29f0b099a20219fb1df",
          "sha1": "b5369e8cd351a64833a40f48359b3da59e23c726",
          "md5": "218db40e5458a36092508ab1ddcd14ca"
        }
      ]
    }
  ]
}
