{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a86-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a86",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a86-android-0.2.6.aar",
          "url": "ble-characteristic-u2a86-android-0.2.6.aar",
          "size": 3161,
          "sha512": "947cf2c06556403901967bdec5b064de8a2a4d2f0397225c52386ab02972b5cc18d1eb64a225cf91fb538dab60e12ed5c8b6087d3a052ba3c09a9b66a212eb4e",
          "sha256": "f6750d9e06cef0903588d50daaef09f2f7101742c82ed4309b3957cb88d22899",
          "sha1": "adc3d8e5a50e0e890db0c0516f65bd511c574469",
          "md5": "4ef973082f2896307061bed0aa139e48"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a86",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a86-android-0.2.6.aar",
          "url": "ble-characteristic-u2a86-android-0.2.6.aar",
          "size": 3161,
          "sha512": "947cf2c06556403901967bdec5b064de8a2a4d2f0397225c52386ab02972b5cc18d1eb64a225cf91fb538dab60e12ed5c8b6087d3a052ba3c09a9b66a212eb4e",
          "sha256": "f6750d9e06cef0903588d50daaef09f2f7101742c82ed4309b3957cb88d22899",
          "sha1": "adc3d8e5a50e0e890db0c0516f65bd511c574469",
          "md5": "4ef973082f2896307061bed0aa139e48"
        }
      ]
    }
  ]
}
