{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a29-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.4.aar",
          "url": "ble-characteristic-u2a29-android-0.2.4.aar",
          "size": 3128,
          "sha512": "5ac6c129375e0f38da8ae36066f369de4c1bb7380d11f48197ac09107800d3061860ac027f4393e6a22bec8db5ce6d56718187a264505ccff7d36ef6ef82e0b3",
          "sha256": "4d2394cf4cfcda59cfdc9e5f13bc2a2fb0e7dd08a159aaf57c9b26283496ffa0",
          "sha1": "3229e033f31bdce5f347876905fad7fdd6825e79",
          "md5": "1a332c63843a668fd09d02d8c822fb9e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.4.aar",
          "url": "ble-characteristic-u2a29-android-0.2.4.aar",
          "size": 3128,
          "sha512": "5ac6c129375e0f38da8ae36066f369de4c1bb7380d11f48197ac09107800d3061860ac027f4393e6a22bec8db5ce6d56718187a264505ccff7d36ef6ef82e0b3",
          "sha256": "4d2394cf4cfcda59cfdc9e5f13bc2a2fb0e7dd08a159aaf57c9b26283496ffa0",
          "sha1": "3229e033f31bdce5f347876905fad7fdd6825e79",
          "md5": "1a332c63843a668fd09d02d8c822fb9e"
        }
      ]
    }
  ]
}
