{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9c-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.2.1.aar",
          "url": "ble-characteristic-u2a9c-android-0.2.1.aar",
          "size": 5345,
          "sha512": "f787141f84df84a17996a7ab35ef96b38818f40a8ef8f9bdb218c6a1b0eb944771e2b3d815142219fc7624c6e4b854151906a3732b099bc739b1afa1de801db3",
          "sha256": "c62146bc95c5929290e2ccce308496b249a73172a023d08cf773d35851ebb6af",
          "sha1": "590e74cdfd3c304a4a59bf620ba4e88184c15591",
          "md5": "38ec8ea8adab038aef296a8d9846ccec"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.2.1.aar",
          "url": "ble-characteristic-u2a9c-android-0.2.1.aar",
          "size": 5345,
          "sha512": "f787141f84df84a17996a7ab35ef96b38818f40a8ef8f9bdb218c6a1b0eb944771e2b3d815142219fc7624c6e4b854151906a3732b099bc739b1afa1de801db3",
          "sha256": "c62146bc95c5929290e2ccce308496b249a73172a023d08cf773d35851ebb6af",
          "sha1": "590e74cdfd3c304a4a59bf620ba4e88184c15591",
          "md5": "38ec8ea8adab038aef296a8d9846ccec"
        }
      ]
    }
  ]
}
