{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-scpp-peripheral-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-scps-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-scpp-peripheral-android-0.1.0.aar",
          "url": "ble-profile-scpp-peripheral-android-0.1.0.aar",
          "size": 3433,
          "sha512": "53ce418951a6d8994e317032161995e6ee44219c545fb4832550d5b34c2ac26144e71ef3d1aafce54e9b0849412269005ed23bbff31db04e1dd13fc10f1c4965",
          "sha256": "ecb76e1a80cef02d6c083ee85757f96ff0c61a921c978a562729ddd5203b8214",
          "sha1": "ac173f7d250ce47035e10b75c1e1fb5db0927009",
          "md5": "3e1f37ab3541e75de1990a22ed82c3a5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-scps-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-scpp-peripheral-android-0.1.0.aar",
          "url": "ble-profile-scpp-peripheral-android-0.1.0.aar",
          "size": 3433,
          "sha512": "53ce418951a6d8994e317032161995e6ee44219c545fb4832550d5b34c2ac26144e71ef3d1aafce54e9b0849412269005ed23bbff31db04e1dd13fc10f1c4965",
          "sha256": "ecb76e1a80cef02d6c083ee85757f96ff0c61a921c978a562729ddd5203b8214",
          "sha1": "ac173f7d250ce47035e10b75c1e1fb5db0927009",
          "md5": "3e1f37ab3541e75de1990a22ed82c3a5"
        }
      ]
    }
  ]
}
