{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-cental-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-cental-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-central-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-android-0.1.5.aar",
          "url": "ble-service-android-0.1.5.aar",
          "size": 1009,
          "sha512": "310008f04151af56ffb15ee62506911a6e85b9e4c6792a3e84036035544d22181e58261de6943c8b4524f25c5ae40ab7f7605d350a515b3763e11212d9fcc755",
          "sha256": "44ac1cbe5dc3998f75c4c34072d91da8a3e5804b5da5286b948a4fe0aa131cf5",
          "sha1": "bcb674369370ed29a8d2b55af12e906654c33be4",
          "md5": "f169e676c635b1eea6b8de23f1e9f0bd"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-cental-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-cental-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-central-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-android-0.1.5.aar",
          "url": "ble-service-android-0.1.5.aar",
          "size": 1009,
          "sha512": "310008f04151af56ffb15ee62506911a6e85b9e4c6792a3e84036035544d22181e58261de6943c8b4524f25c5ae40ab7f7605d350a515b3763e11212d9fcc755",
          "sha256": "44ac1cbe5dc3998f75c4c34072d91da8a3e5804b5da5286b948a4fe0aa131cf5",
          "sha1": "bcb674369370ed29a8d2b55af12e906654c33be4",
          "md5": "f169e676c635b1eea6b8de23f1e9f0bd"
        }
      ]
    }
  ]
}
