{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4d-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.1.6.aar",
          "url": "ble-characteristic-u2a4d-android-0.1.6.aar",
          "size": 3013,
          "sha512": "3b680507a97530df3f63882f8564af94d28fdc7891f959e15c0c3e2abf61f764283b572a2266745ccadd168163f4e0fe01b54f82f499706325cd1e97e7059bea",
          "sha256": "9622ce1dbfe913c689baf5648bf0cbbaecfa223ed4f5fa34f43738f3606f1271",
          "sha1": "b1d3cae7d9f320cb2240130df0d9eeb481884eb5",
          "md5": "6d5ebe41b8522486af99ba7bacdc3605"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.1.6.aar",
          "url": "ble-characteristic-u2a4d-android-0.1.6.aar",
          "size": 3013,
          "sha512": "3b680507a97530df3f63882f8564af94d28fdc7891f959e15c0c3e2abf61f764283b572a2266745ccadd168163f4e0fe01b54f82f499706325cd1e97e7059bea",
          "sha256": "9622ce1dbfe913c689baf5648bf0cbbaecfa223ed4f5fa34f43738f3606f1271",
          "sha1": "b1d3cae7d9f320cb2240130df0d9eeb481884eb5",
          "md5": "6d5ebe41b8522486af99ba7bacdc3605"
        }
      ]
    }
  ]
}
