{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.12.jar",
          "url": "ble-characteristic-u2a04-0.8.12.jar",
          "size": 2207,
          "sha512": "fff4286ea5f222ad0caa6b9cc3699272632bd3793bf922f36a6593994efbb9d049e2a9324847f983b845625abc65fc41446915835a34a8598e26b661cf9fc5c8",
          "sha256": "a63d99b4fe4f3b4c204004fd4e7f1b96bf8f94aca04ca138d7fd5e0f5bfe8fee",
          "sha1": "07fb4924b51e778adb9202d0a8abd0e1ceec4585",
          "md5": "73c8b8ca026416f9727462f2794f1a67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.12.jar",
          "url": "ble-characteristic-u2a04-0.8.12.jar",
          "size": 2207,
          "sha512": "fff4286ea5f222ad0caa6b9cc3699272632bd3793bf922f36a6593994efbb9d049e2a9324847f983b845625abc65fc41446915835a34a8598e26b661cf9fc5c8",
          "sha256": "a63d99b4fe4f3b4c204004fd4e7f1b96bf8f94aca04ca138d7fd5e0f5bfe8fee",
          "sha1": "07fb4924b51e778adb9202d0a8abd0e1ceec4585",
          "md5": "73c8b8ca026416f9727462f2794f1a67"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a04-0.8.12-javadoc.jar",
          "size": 89197,
          "sha512": "6d627df74a0072c5a99375359b05d9f98ac5751635fa2c76f3b08dbcfc98385e1660885e9b41c81e49a45b049297ea70b1ee90fdfb8e2215ae7e7e93a722572b",
          "sha256": "eb22abeb5eea9449dafaa31352fb6ce0ee2772d84ba4f47dbac1eac0030c591b",
          "sha1": "1665a4545208024fb9c455394cdbbdf413f715b6",
          "md5": "c9fdf1d35dd281f52e37bc5a62f53242"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a04-0.8.12-sources.jar",
          "size": 2002,
          "sha512": "35c0dc5819601dc4b685cd2918b021cebe302faa94a5cefa498939ad1a609b73ca0bd2fe38bf5eb3a93aca5f536a51acf2c0ee15141d38ff1c32f1a93df6d348",
          "sha256": "6d39a24a93ea63928dadeb561472f8cd897efa819f3ce5e76de700cfaef9a9fb",
          "sha1": "f16ed12c4d78f626a627798006366ecdd1b983c1",
          "md5": "6f9aad1b3ff318c684f1447b20723764"
        }
      ]
    }
  ]
}
