{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae8",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae8-0.8.11.jar",
          "url": "ble-characteristic-u2ae8-0.8.11.jar",
          "size": 2216,
          "sha512": "23733d537e569094a914a87c6e2486ef5ee6a5dddc72b5f7fb8104f427ca6734c469b1cdc1b105f5ff303c4bf843c0c6849220efb53a43490c34190a8fedaf0c",
          "sha256": "52d7797c44868e2dd2cbc7e311f57a86a183ef21110350f7e52b99b632c45ee2",
          "sha1": "42326aac07eb42151c1907e86fccfba57d663939",
          "md5": "3b96418579afdaf0ace9d004f006c9de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae8-0.8.11.jar",
          "url": "ble-characteristic-u2ae8-0.8.11.jar",
          "size": 2216,
          "sha512": "23733d537e569094a914a87c6e2486ef5ee6a5dddc72b5f7fb8104f427ca6734c469b1cdc1b105f5ff303c4bf843c0c6849220efb53a43490c34190a8fedaf0c",
          "sha256": "52d7797c44868e2dd2cbc7e311f57a86a183ef21110350f7e52b99b632c45ee2",
          "sha1": "42326aac07eb42151c1907e86fccfba57d663939",
          "md5": "3b96418579afdaf0ace9d004f006c9de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae8-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2ae8-0.8.11-javadoc.jar",
          "size": 107588,
          "sha512": "23a74ecf3438b89bcfde54686b484e3f6f858a8cfbc1af420932fcb96f78546f04c001516dc4c17ca833ef523529704d21ee12aea44b7cba6d3a7763c12c54c4",
          "sha256": "8f01d8a02a1b213945224e6e45a1f281121cfb8e05c9a0bfb36e670be8942132",
          "sha1": "3c1a88987d2ec643782bfca79e7dce21869f375d",
          "md5": "8c548d4b13be60ad9fed507249b596c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae8-0.8.11-sources.jar",
          "url": "ble-characteristic-u2ae8-0.8.11-sources.jar",
          "size": 1916,
          "sha512": "9a124c7a748446a5f45759eec4d021d502b65241024a9bc6557cea213a550d4553458633caecb33da253f19b7eaf608da5b5090168ffe046ad67ddd85a83d6a4",
          "sha256": "15bf9895690b22d0b24f14df9b2577375d2f11d54de32829969582d8f659ee92",
          "sha1": "ebc34f4de5db646bf9c7be1a9c196265fa28c4a0",
          "md5": "b2ddd17aa6d2db6ba78fdf587a384b9e"
        }
      ]
    }
  ]
}
