{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0c",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.14.jar",
          "url": "ble-characteristic-u2b0c-0.8.14.jar",
          "size": 1948,
          "sha512": "4870c8fc111d7b1607c64afe3e43cb30bf201cbc5dc3cae8ebfb39642de519230ec66537822b9420769e3f5f07a433bb147b444cef398f8bee89c791fdf98a93",
          "sha256": "8be0e330a8889de1eae6afe36aeac7176bf739710881c88dc59ec77b7fc60126",
          "sha1": "7b6f6a7d227777ce13a2f0f9f2f2a696aaaa32cf",
          "md5": "1b0179ffcc2045df02e7e1289b47b249"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.14.jar",
          "url": "ble-characteristic-u2b0c-0.8.14.jar",
          "size": 1948,
          "sha512": "4870c8fc111d7b1607c64afe3e43cb30bf201cbc5dc3cae8ebfb39642de519230ec66537822b9420769e3f5f07a433bb147b444cef398f8bee89c791fdf98a93",
          "sha256": "8be0e330a8889de1eae6afe36aeac7176bf739710881c88dc59ec77b7fc60126",
          "sha1": "7b6f6a7d227777ce13a2f0f9f2f2a696aaaa32cf",
          "md5": "1b0179ffcc2045df02e7e1289b47b249"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2b0c-0.8.14-javadoc.jar",
          "size": 86554,
          "sha512": "b97c6beadfdcd0226a17dab3caa8beabf5c4b32a54ebd0abacfb10ee2dbbb29ab8f329014956c44334e3eddddd8017af3375f33c4ebc6811dbca21ac6fe4dbc1",
          "sha256": "75ac62c12d27eab5c9c5f9cc53b1511ae42a288f3d2c7724e742b5209a046de4",
          "sha1": "0441d80060e124d5856d761d1e1c4842b9469f6e",
          "md5": "731761e173bda341e8e6de4d64a9a271"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0c-0.8.14-sources.jar",
          "url": "ble-characteristic-u2b0c-0.8.14-sources.jar",
          "size": 1780,
          "sha512": "ef2d93c643d24bc1845c9e0a04f21ea252e38ef6ffa4a540b0ca9520094d494742503efe0607cf9ba3a2afdf4a1654b565dd62fef7c987f1a00cc9d564718f0c",
          "sha256": "88dd680dcc6e7f74b7f7ed3bd1dbf6f0bef698547b3ac76a95ad5759572fbce7",
          "sha1": "b6be18700397a0596656c9fa36a1c8f23b4e9b4b",
          "md5": "3d3cfe75c58575d655d8051519047e37"
        }
      ]
    }
  ]
}
