{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a16",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.8.10.jar",
          "url": "ble-characteristic-u2a16-0.8.10.jar",
          "size": 1931,
          "sha512": "5535079fded0f998fbd3aef0c190d6c6ef7e8e4f0f3a2b88660ff6c745ddba6b8cb7bd419d4b4804e1a0fe418abb94603e87aac7cb9b710331ab02ca9d85e7c4",
          "sha256": "cf23bbdd9f9ac6083c89b5d2d1aa57f2382eec9c4858b6ff340e1abd75810bae",
          "sha1": "db081c86d2f6c7c0681320bc99c706f8d2b6326e",
          "md5": "18b6749612d028ebe79aa6723465a4ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.8.10.jar",
          "url": "ble-characteristic-u2a16-0.8.10.jar",
          "size": 1931,
          "sha512": "5535079fded0f998fbd3aef0c190d6c6ef7e8e4f0f3a2b88660ff6c745ddba6b8cb7bd419d4b4804e1a0fe418abb94603e87aac7cb9b710331ab02ca9d85e7c4",
          "sha256": "cf23bbdd9f9ac6083c89b5d2d1aa57f2382eec9c4858b6ff340e1abd75810bae",
          "sha1": "db081c86d2f6c7c0681320bc99c706f8d2b6326e",
          "md5": "18b6749612d028ebe79aa6723465a4ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2a16-0.8.10-javadoc.jar",
          "size": 109780,
          "sha512": "229a54d7174ee8db03fbdc1497556177f7f2a1a9d12d6ee4822062a0a75be94d73ca31ca02783b24e09894c2da4909b34fef09490058f4ea20569e74f4e27060",
          "sha256": "b32c633a58d7bcd075e3af3c5e1ddff96922e304497292e2728ed46f5a63e28f",
          "sha1": "7ccb2c02513b5a5fbed93582dc077206303fca70",
          "md5": "0cc69093cfdc924d525d75a839a56ba7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.8.10-sources.jar",
          "url": "ble-characteristic-u2a16-0.8.10-sources.jar",
          "size": 1768,
          "sha512": "532dc8767d339e1dbcb6236645caaf8873394ecbb0c1d01c392a0b7da88caf29e2da0c95e338a46046fea10fc4740c75693cf6fc8f95357678c7235d9a905ddb",
          "sha256": "ec031fe1391bb6c945719591024f78ea7cec5d3ce3abca3fef7aab4809f94e7e",
          "sha1": "c2c35ecdc263763cc2b9062f95ab0472954b9deb",
          "md5": "210466a811478e113f42cb77e12ba6a9"
        }
      ]
    }
  ]
}
