{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b15-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b15",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b15-android-0.8.14.aar",
          "url": "ble-characteristic-u2b15-android-0.8.14.aar",
          "size": 3143,
          "sha512": "51dff4e7b62b1de3eb6e338a28785dc4189b975cf14fe237494cd0d824f4451893a233136a2fe8bd28913498886c1e5f2796d043c8f6af2a832e8cd06eb71e7f",
          "sha256": "d34696c49c768edeb432ff27f0b0dee0076af7147d6acd29865f7557e7162d60",
          "sha1": "52d040ae32eee8fbf5264cddfdea6a2e6ef3a88c",
          "md5": "ab0d15f52d7ba49fdaddf5d84c01017c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b15",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b15-android-0.8.14.aar",
          "url": "ble-characteristic-u2b15-android-0.8.14.aar",
          "size": 3143,
          "sha512": "51dff4e7b62b1de3eb6e338a28785dc4189b975cf14fe237494cd0d824f4451893a233136a2fe8bd28913498886c1e5f2796d043c8f6af2a832e8cd06eb71e7f",
          "sha256": "d34696c49c768edeb432ff27f0b0dee0076af7147d6acd29865f7557e7162d60",
          "sha1": "52d040ae32eee8fbf5264cddfdea6a2e6ef3a88c",
          "md5": "ab0d15f52d7ba49fdaddf5d84c01017c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b15-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2b15-android-0.8.14-sources.jar",
          "size": 2206,
          "sha512": "a80cd21c0d7d530d19f2db58a5d3739da8dc08edc1a606c359624b5f831578bff74a43532842370a29fc0746da59f3ec998d0342104535ca841f19bf34c0d46f",
          "sha256": "8fd288a65673872572f987f0b5ff049099856e00e4213d521f329af4486334e8",
          "sha1": "303ba069bdc019eb7f8f00a7685e0e9fe9bca488",
          "md5": "23d4122129ac36a7494e71ea4d1f402c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b15-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2b15-android-0.8.14-javadoc.jar",
          "size": 272911,
          "sha512": "8ef83910a2414348bec5f7f844ba05f8f94a03c599beee003f13850515a756dfd087aa9edf2ed5a6971b085e7500d0aade65c43fb87e27fef3c6287511ec0f47",
          "sha256": "c20dc0eef6875bc1ef81a3fcb29b14ac38872973fab58b4f4b4705ad5d948e2b",
          "sha1": "6d28a6b1fc355f835b0a12c5a4e23737b745add9",
          "md5": "124ec4e56585111e8ae7cc882c758282"
        }
      ]
    }
  ]
}
