{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1d-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a1d-android-0.8.6.aar",
          "size": 3097,
          "sha512": "7541daf1551587fa595e734f0e755d9af6977604e3274dd318f943f547176c8829d17d36bdfc737dab4e39dee20e6ba148fe764e52a9b6e4e33a435a38759433",
          "sha256": "fe1a687d2df48ae158a6067273819e4ad363862ea71e3f17fcaea0f738bc9434",
          "sha1": "e7c84ca4cc15ac908f53ea5fcda1ded4a1af4f71",
          "md5": "e1ba5c7575ad6fb860ff0a82d6eeb2e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a1d-android-0.8.6.aar",
          "size": 3097,
          "sha512": "7541daf1551587fa595e734f0e755d9af6977604e3274dd318f943f547176c8829d17d36bdfc737dab4e39dee20e6ba148fe764e52a9b6e4e33a435a38759433",
          "sha256": "fe1a687d2df48ae158a6067273819e4ad363862ea71e3f17fcaea0f738bc9434",
          "sha1": "e7c84ca4cc15ac908f53ea5fcda1ded4a1af4f71",
          "md5": "e1ba5c7575ad6fb860ff0a82d6eeb2e2"
        }
      ]
    }
  ]
}
