{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a77-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a77",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-android-0.2.9.aar",
          "url": "ble-characteristic-u2a77-android-0.2.9.aar",
          "size": 3101,
          "sha512": "2ad521d4affabc702fce854cfa7d9d1ab04a17913e2507255c542aa98244c2e155b28eb5bd32ca8564583afc66a21247ad158c85b08dbcda33f8fce80d43a944",
          "sha256": "806bd5db942547e6953d7b07d1aebbce1b8c4b9039ed29b6ca9628bd5ad144b7",
          "sha1": "d4d029acb8cbee958f97dc7f1b611644b6bae46b",
          "md5": "d33de4b5f91c5f3c9bb08c6e840db40a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a77",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-android-0.2.9.aar",
          "url": "ble-characteristic-u2a77-android-0.2.9.aar",
          "size": 3101,
          "sha512": "2ad521d4affabc702fce854cfa7d9d1ab04a17913e2507255c542aa98244c2e155b28eb5bd32ca8564583afc66a21247ad158c85b08dbcda33f8fce80d43a944",
          "sha256": "806bd5db942547e6953d7b07d1aebbce1b8c4b9039ed29b6ca9628bd5ad144b7",
          "sha1": "d4d029acb8cbee958f97dc7f1b611644b6bae46b",
          "md5": "d33de4b5f91c5f3c9bb08c6e840db40a"
        }
      ]
    }
  ]
}
