{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acc",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.5.jar",
          "url": "ble-characteristic-u2acc-0.8.5.jar",
          "size": 4687,
          "sha512": "47546e5b88ca11a23c07d892c9db4135c4a7cef2bb4ed74aca745012dcdab24c0f79ff6a31d66f63b8c5d2c4ee895b7a4886a69cb1387652869930902a977ea9",
          "sha256": "44b7793465c9141082c34bedc011dbae2bffa3c71a929ac8ea2574fed479a3fd",
          "sha1": "b5bf4b7214b9cc892d5fc31802770a16af47bb82",
          "md5": "904ba1fc5665dfeb7837d957aba527ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.5.jar",
          "url": "ble-characteristic-u2acc-0.8.5.jar",
          "size": 4687,
          "sha512": "47546e5b88ca11a23c07d892c9db4135c4a7cef2bb4ed74aca745012dcdab24c0f79ff6a31d66f63b8c5d2c4ee895b7a4886a69cb1387652869930902a977ea9",
          "sha256": "44b7793465c9141082c34bedc011dbae2bffa3c71a929ac8ea2574fed479a3fd",
          "sha1": "b5bf4b7214b9cc892d5fc31802770a16af47bb82",
          "md5": "904ba1fc5665dfeb7837d957aba527ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2acc-0.8.5-javadoc.jar",
          "size": 124526,
          "sha512": "ffcc5889137c245a3d219ea079290f2dd817a3045d2ee8e65f0ba7b612383ed71cd5b98d900d260849f75916f70a4ca07497ec61399bede74b4a507270a45b9f",
          "sha256": "37fce92ec607a4f1bbe2823685ee4fdcf192a608362a2ee39097adc9f8c4dc50",
          "sha1": "8202291cf306389ac00b70d74be8c7dc5ab8f44d",
          "md5": "72da0f76383a9ceada32ac5b33f52f87"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.5-sources.jar",
          "url": "ble-characteristic-u2acc-0.8.5-sources.jar",
          "size": 5470,
          "sha512": "cd5f6df7c73917826af763d96d2c87984ec73ff707472d8d2e55f40806af45189d74091b128eb321ea8d6100aac69c6b7dd9f8927f4ff5d090fa89bf30252890",
          "sha256": "b9c15f468e41630f8ba0767dd47f0b37d9b53e44ff00e8b2f037b42091cf40a5",
          "sha1": "5c5318e484c047a7fa90f4d9378711d1e7d4ae0d",
          "md5": "106a98251843ef1d0a87ca80923079c4"
        }
      ]
    }
  ]
}
