{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a81",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "l4elwkmcvrhitpkmkzxnxaimhi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-0.2.3.jar",
          "url": "ble-characteristic-u2a81-0.2.3.jar",
          "size": 1770,
          "sha512": "3abe4b36b28942568dcf7246dd3edf32bb63294538938d763aac7a8cfb186f147e1340448d9ab6a5f9d8d0f8e6b6d497aff2031d9655efd5d00339fb2783e739",
          "sha256": "98837fa9531719de0d76c4899eb68eea6fcabffde189f3040d7c71878156949d",
          "sha1": "0afedab36451e82a149629ae02e5544e3e131133",
          "md5": "8a34d3da368266b84276d38ea7c9b309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-0.2.3.jar",
          "url": "ble-characteristic-u2a81-0.2.3.jar",
          "size": 1770,
          "sha512": "3abe4b36b28942568dcf7246dd3edf32bb63294538938d763aac7a8cfb186f147e1340448d9ab6a5f9d8d0f8e6b6d497aff2031d9655efd5d00339fb2783e739",
          "sha256": "98837fa9531719de0d76c4899eb68eea6fcabffde189f3040d7c71878156949d",
          "sha1": "0afedab36451e82a149629ae02e5544e3e131133",
          "md5": "8a34d3da368266b84276d38ea7c9b309"
        }
      ]
    }
  ]
}
