{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1f",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1f-0.4.0.jar",
          "url": "ble-characteristic-u2b1f-0.4.0.jar",
          "size": 7597,
          "sha512": "c934a343cd24f10936b65b3d3facde79f9e7e27309081ab0cbfb16b386d02f587422f8d94d07198012a108d997c8c585a8a85965df4981f2590ccd5e970ec286",
          "sha256": "907ec2e7df8dfd31247c3e2366ea3e9295dc0a2707714373dc198b2fb3ffddf3",
          "sha1": "d710b101640116187b7efa166e2cecc8e97a731f",
          "md5": "9fa7553ef5128ae345a83208d72b884d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1f-0.4.0.jar",
          "url": "ble-characteristic-u2b1f-0.4.0.jar",
          "size": 7597,
          "sha512": "c934a343cd24f10936b65b3d3facde79f9e7e27309081ab0cbfb16b386d02f587422f8d94d07198012a108d997c8c585a8a85965df4981f2590ccd5e970ec286",
          "sha256": "907ec2e7df8dfd31247c3e2366ea3e9295dc0a2707714373dc198b2fb3ffddf3",
          "sha1": "d710b101640116187b7efa166e2cecc8e97a731f",
          "md5": "9fa7553ef5128ae345a83208d72b884d"
        }
      ]
    }
  ]
}
