{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-datatype",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-datatype-0.8.12.jar",
          "url": "ble-core-constants-datatype-0.8.12.jar",
          "size": 4419,
          "sha512": "2054dc21c99dc8e1cc7159450af0bf66a56879ff4f0e8c7b9f8c83921f26b2fe20c8807dc9e34d5f241d29d16f952f11e50d1c041650b92e9bb9b27d30b6b25b",
          "sha256": "f4653721c65040856d6f68e273000942ef94c96f7da48ee84fdb5972ddc54227",
          "sha1": "df14ac331877fc8d6cc96e0aa26dd2245013472c",
          "md5": "8e9a9ec6e43a057eccfec7ca9f66e943"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-datatype-0.8.12.jar",
          "url": "ble-core-constants-datatype-0.8.12.jar",
          "size": 4419,
          "sha512": "2054dc21c99dc8e1cc7159450af0bf66a56879ff4f0e8c7b9f8c83921f26b2fe20c8807dc9e34d5f241d29d16f952f11e50d1c041650b92e9bb9b27d30b6b25b",
          "sha256": "f4653721c65040856d6f68e273000942ef94c96f7da48ee84fdb5972ddc54227",
          "sha1": "df14ac331877fc8d6cc96e0aa26dd2245013472c",
          "md5": "8e9a9ec6e43a057eccfec7ca9f66e943"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-datatype-0.8.12-javadoc.jar",
          "url": "ble-core-constants-datatype-0.8.12-javadoc.jar",
          "size": 94328,
          "sha512": "26d72018b87f750260154cbad6cbb332fdab1bdf8fd734c38a5ecd719ad24715f2b04b76f7471a6264d80eb81df866c8e263d3e03fb23c67efe840fa5a301349",
          "sha256": "2cdc90f49182713446fd6dc61114cd420abacf52f30235190bd754049fded63a",
          "sha1": "5968681b8f8be76abe5446eba35fb69e53a88664",
          "md5": "851631f4b52c00988b8024007e8c2cc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-datatype-0.8.12-sources.jar",
          "url": "ble-core-constants-datatype-0.8.12-sources.jar",
          "size": 3051,
          "sha512": "0d39e41dbcfe9c349e50ac2d5b1857c8816dc3946e1ea74e6b6f53af20ee58ccf2ae1f6c5c3f0f2248031cd4228542f08713c8554b15c265e809c5e347296f56",
          "sha256": "ac7fd3528fd1a5a1a5b346c955307c81ac0bdaf481fb061bd5724d220ce71cf6",
          "sha1": "1cd12180d68e30bb2920110621ca3091175d594d",
          "md5": "c016ab853ba314c0569fe2c9552627e7"
        }
      ]
    }
  ]
}
