{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-gatt-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-gatt-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-gatt-android-0.4.4.aar",
          "url": "ble-service-peripheral-gatt-android-0.4.4.aar",
          "size": 5234,
          "sha512": "3d191bbb08845b72c5d3723f19bb773de39b80cea3340d7b0917269adb0bafdd9e728dc7fa4b6c1c6066aff25df62f31196483d97151b05c6fc4f5254957ef5d",
          "sha256": "c5e3e45c297f2ce0f13264cf33366e1f553b20e1dc924c1e22498897b38559ce",
          "sha1": "e5e253f75dd3637078c76c0099d6cec6dc123f74",
          "md5": "5cdb9ea53e103bc8e5aeffd7fbc8b068"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-gatt-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-gatt-android-0.4.4.aar",
          "url": "ble-service-peripheral-gatt-android-0.4.4.aar",
          "size": 5234,
          "sha512": "3d191bbb08845b72c5d3723f19bb773de39b80cea3340d7b0917269adb0bafdd9e728dc7fa4b6c1c6066aff25df62f31196483d97151b05c6fc4f5254957ef5d",
          "sha256": "c5e3e45c297f2ce0f13264cf33366e1f553b20e1dc924c1e22498897b38559ce",
          "sha1": "e5e253f75dd3637078c76c0099d6cec6dc123f74",
          "md5": "5cdb9ea53e103bc8e5aeffd7fbc8b068"
        }
      ]
    }
  ]
}
