{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-aiop-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-aiop-android-0.1.0.aar",
          "url": "ble-profile-aiop-android-0.1.0.aar",
          "size": 1205,
          "sha512": "4f723e322f6fe39c2b82e568a45ab6c10253b4c184b4b630b5b6dfbb063271210dcd52bb3a35a67774e69239b3c8ff38bc28425ab44b09d572ff0cdeab5dd6ff",
          "sha256": "39c1aa2d7086da6346be181638110f7f4b19921d4fba2051ac0dda89a4a23f5f",
          "sha1": "c4fff19862d69ad979a2014fb0218a7e0023d870",
          "md5": "d0bb252de92cdc500b7bb1d212611395"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-aiop-android-0.1.0.aar",
          "url": "ble-profile-aiop-android-0.1.0.aar",
          "size": 1205,
          "sha512": "4f723e322f6fe39c2b82e568a45ab6c10253b4c184b4b630b5b6dfbb063271210dcd52bb3a35a67774e69239b3c8ff38bc28425ab44b09d572ff0cdeab5dd6ff",
          "sha256": "39c1aa2d7086da6346be181638110f7f4b19921d4fba2051ac0dda89a4a23f5f",
          "sha1": "c4fff19862d69ad979a2014fb0218a7e0023d870",
          "md5": "d0bb252de92cdc500b7bb1d212611395"
        }
      ]
    }
  ]
}
