{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-aiop-peripheral-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ne3pcejtrrhfvmmkle32bx6bti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-aiop-peripheral-android-0.1.3.aar",
          "url": "ble-profile-aiop-peripheral-android-0.1.3.aar",
          "size": 4043,
          "sha512": "572afd998a63bd162ccc54f46403a256617ce55b08e21e6dbc3eceb47ca369e351f9bed7f774c79e44484d13a3afbda0334d2b61d7615ef7a55849ff10943fd6",
          "sha256": "942d0f1e399c61c98b2e40383ccd03ffe30768a0900c90343b2c544ef813b982",
          "sha1": "822c9efb7129a3b932969d77e182ad14eb13b11e",
          "md5": "cab4d10b09f9b2a5137d7de79cd10c1a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-aios-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-aiop-peripheral-android-0.1.3.aar",
          "url": "ble-profile-aiop-peripheral-android-0.1.3.aar",
          "size": 4043,
          "sha512": "572afd998a63bd162ccc54f46403a256617ce55b08e21e6dbc3eceb47ca369e351f9bed7f774c79e44484d13a3afbda0334d2b61d7615ef7a55849ff10943fd6",
          "sha256": "942d0f1e399c61c98b2e40383ccd03ffe30768a0900c90343b2c544ef813b982",
          "sha1": "822c9efb7129a3b932969d77e182ad14eb13b11e",
          "md5": "cab4d10b09f9b2a5137d7de79cd10c1a"
        }
      ]
    }
  ]
}
