{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2900-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-android-0.1.4.aar",
          "url": "ble-descriptor-u2900-android-0.1.4.aar",
          "size": 3183,
          "sha512": "83a51289c2dbebf66740cb0ee4e5a30a951fa84aa3e3a54038a78be473e613f1af5500668d4a13e2dd2e728666f857cfa8b1d369b9c8b0f63b77c4f8057aa3f5",
          "sha256": "3de7c6109baac6b57b0587037e847a15020b2c973ec43e3663afa3092013be69",
          "sha1": "827eac6b83a04951a188403776a58b41e06610c9",
          "md5": "0d91f606356989e011a43df9e5a4ef6e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-android-0.1.4.aar",
          "url": "ble-descriptor-u2900-android-0.1.4.aar",
          "size": 3183,
          "sha512": "83a51289c2dbebf66740cb0ee4e5a30a951fa84aa3e3a54038a78be473e613f1af5500668d4a13e2dd2e728666f857cfa8b1d369b9c8b0f63b77c4f8057aa3f5",
          "sha256": "3de7c6109baac6b57b0587037e847a15020b2c973ec43e3663afa3092013be69",
          "sha1": "827eac6b83a04951a188403776a58b41e06610c9",
          "md5": "0d91f606356989e011a43df9e5a4ef6e"
        }
      ]
    }
  ]
}
