{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4a-android",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4a",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4a-android-0.8.5.aar",
          "url": "ble-characteristic-u2b4a-android-0.8.5.aar",
          "size": 3051,
          "sha512": "2959c676816f5076173217b839479df0691f9129b1ed85383f2f809e6927b14e48d346373b2ae812ff7fd378bfde9ab499760b179c65a1cec60ad84ceaea3360",
          "sha256": "cbd51ecccf12ba59975e3fa5d2ca2cdc77160a2947b4202b7a78fbeb9e1bd685",
          "sha1": "35a5a6ed4beebff2893965caea4635a58b0d6d09",
          "md5": "1088a51dfcea048bbb75194174504435"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4a",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4a-android-0.8.5.aar",
          "url": "ble-characteristic-u2b4a-android-0.8.5.aar",
          "size": 3051,
          "sha512": "2959c676816f5076173217b839479df0691f9129b1ed85383f2f809e6927b14e48d346373b2ae812ff7fd378bfde9ab499760b179c65a1cec60ad84ceaea3360",
          "sha256": "cbd51ecccf12ba59975e3fa5d2ca2cdc77160a2947b4202b7a78fbeb9e1bd685",
          "sha1": "35a5a6ed4beebff2893965caea4635a58b0d6d09",
          "md5": "1088a51dfcea048bbb75194174504435"
        }
      ]
    }
  ]
}
