{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd4-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd4",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd4-android-0.8.12.aar",
          "url": "ble-characteristic-u2bd4-android-0.8.12.aar",
          "size": 3238,
          "sha512": "09489ef7c9dd7b90e5f6d8e4dba66a168a332aca6b5b35df8e30c280a443f415130075f3de917241e0fb334a5dc3b47bb451956f195508e30e8822f48a418c20",
          "sha256": "a9ce5b9a0a6e6cd51d41348261dc9a96fdf6b90ea1c0d7e6d4025467d7abee20",
          "sha1": "64803e1ce632fbe16b634b8e8ed17d4be63e970b",
          "md5": "526fa05ba1e4795b0770bb4f92134885"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd4",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd4-android-0.8.12.aar",
          "url": "ble-characteristic-u2bd4-android-0.8.12.aar",
          "size": 3238,
          "sha512": "09489ef7c9dd7b90e5f6d8e4dba66a168a332aca6b5b35df8e30c280a443f415130075f3de917241e0fb334a5dc3b47bb451956f195508e30e8822f48a418c20",
          "sha256": "a9ce5b9a0a6e6cd51d41348261dc9a96fdf6b90ea1c0d7e6d4025467d7abee20",
          "sha1": "64803e1ce632fbe16b634b8e8ed17d4be63e970b",
          "md5": "526fa05ba1e4795b0770bb4f92134885"
        }
      ]
    }
  ]
}
