{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-lnp-peripheral-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "gfz7h7bqhjcszkcizgkq3qmgva"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-lnp-peripheral-android-0.1.2.aar",
          "url": "ble-profile-lnp-peripheral-android-0.1.2.aar",
          "size": 5266,
          "sha512": "0eae47a03e6228d4e52171693b8759a9fbb9ac50fd48b199c1f4d5e0ba342c43b971fb63b3261fd3a30db14ce07b760ef93d3116855c979aefb3047796ad6dea",
          "sha256": "c34261d19811848ae09c3beb7f763f96e2d40684d40028f53bc199d63185dca2",
          "sha1": "d7bdf1e3b5ad3d89254f9516ba53fca33b879222",
          "md5": "a09796a8d0145c9572be6fd71c6ef913"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-lnp-peripheral-android-0.1.2.aar",
          "url": "ble-profile-lnp-peripheral-android-0.1.2.aar",
          "size": 5266,
          "sha512": "0eae47a03e6228d4e52171693b8759a9fbb9ac50fd48b199c1f4d5e0ba342c43b971fb63b3261fd3a30db14ce07b760ef93d3116855c979aefb3047796ad6dea",
          "sha256": "c34261d19811848ae09c3beb7f763f96e2d40684d40028f53bc199d63185dca2",
          "sha1": "d7bdf1e3b5ad3d89254f9516ba53fca33b879222",
          "md5": "a09796a8d0145c9572be6fd71c6ef913"
        }
      ]
    }
  ]
}
