{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b12",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.5.jar",
          "url": "ble-characteristic-u2b12-0.8.5.jar",
          "size": 1761,
          "sha512": "2da64f086a88ef3bfa986b0ce706083cc9144d34769c9445f087b0b3a647e8ed5fbd3b554cf00abe26f758c2cff24c750a0dde27b8b8b7c9bb6acdfb8f69a2eb",
          "sha256": "a04d6e90ca48e84d0f213e05bf223e33b9f49c6564b733f45d00d537bfe4620b",
          "sha1": "d17b9bb57d5e7aaaba36e6147cd4f7b7590a2d4b",
          "md5": "b25ba1d7f6a46e8f68378b1e2b5d1e1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.5.jar",
          "url": "ble-characteristic-u2b12-0.8.5.jar",
          "size": 1761,
          "sha512": "2da64f086a88ef3bfa986b0ce706083cc9144d34769c9445f087b0b3a647e8ed5fbd3b554cf00abe26f758c2cff24c750a0dde27b8b8b7c9bb6acdfb8f69a2eb",
          "sha256": "a04d6e90ca48e84d0f213e05bf223e33b9f49c6564b733f45d00d537bfe4620b",
          "sha1": "d17b9bb57d5e7aaaba36e6147cd4f7b7590a2d4b",
          "md5": "b25ba1d7f6a46e8f68378b1e2b5d1e1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b12-0.8.5-javadoc.jar",
          "size": 107348,
          "sha512": "9b3cbcbb337582c408750f83e638d302e00a168cecbc7cfaeffd784cec4da51b1b346cc027ac6f23396d1f721482884934bbee7182af6a06a4a06320a0ef61d3",
          "sha256": "6552750db33cf1f604c09c5bf1dd48cdf7e4a8dd3dd35f9f9550d0d110026d0e",
          "sha1": "dbbbbbbe6498f82a4bf008aff6239e0a1e2aade3",
          "md5": "e12de7564a6c6823e020da1c43ce3751"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b12-0.8.5-sources.jar",
          "size": 1603,
          "sha512": "ea357377accc8e3d936dd8fa7515c9631e3386f50d82c37ef31770f25d29e1340ca2b43c97ceb0cc49d426267e41a168b5eed235591567a38d33467b087532fe",
          "sha256": "7b0e7ac7ac58c4c5d7b4683204bdc00d96eef00c6dddd3d608effe4f8551469a",
          "sha1": "045a2bbd5d9b6ce7534fb695f0651fe666259a19",
          "md5": "c1620e9f8d14c166ce7c6f1506be017a"
        }
      ]
    }
  ]
}
