{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4c",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4c-0.8.4.jar",
          "url": "ble-characteristic-u2b4c-0.8.4.jar",
          "size": 1951,
          "sha512": "d04a2c6d10fd397e35480b7cb2daaef3d954e1f195d04ae6cdafed2903d2de2a61cf56e45ec12baee02b64aca6a878b574369981a23447119d8fef10c20dcc1c",
          "sha256": "cd6316ca8709cccd3e13ccca05c9fb2ed35bfa251f5bec588d2857f2593af347",
          "sha1": "097ca99267d9383e826d247bae94f527ec1dffaa",
          "md5": "fcbe3df839e1b80473a3e6df27e964cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4c-0.8.4.jar",
          "url": "ble-characteristic-u2b4c-0.8.4.jar",
          "size": 1951,
          "sha512": "d04a2c6d10fd397e35480b7cb2daaef3d954e1f195d04ae6cdafed2903d2de2a61cf56e45ec12baee02b64aca6a878b574369981a23447119d8fef10c20dcc1c",
          "sha256": "cd6316ca8709cccd3e13ccca05c9fb2ed35bfa251f5bec588d2857f2593af347",
          "sha1": "097ca99267d9383e826d247bae94f527ec1dffaa",
          "md5": "fcbe3df839e1b80473a3e6df27e964cb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4c-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2b4c-0.8.4-javadoc.jar",
          "size": 110467,
          "sha512": "bc94f37d37c496e0d9af3875eeb2b7715ae79c8cf56ffd700ff22f98df86951c92dba8973ff89289938665c83ddf532e4f5d912435bc4fcaf2bb4cc3538c2ebb",
          "sha256": "f7edae3813ac9374843adb5164958093b148a83ec64a6008cd7cbea844e9b6b2",
          "sha1": "23873d7b340a3c57089f776d269cdb2f48749aa3",
          "md5": "a39936e71127d578eea86d94923a2851"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4c-0.8.4-sources.jar",
          "url": "ble-characteristic-u2b4c-0.8.4-sources.jar",
          "size": 1821,
          "sha512": "db14ecb24e749e43e119028ed099c9a22b1aad559cd8e67dddb82334a502da4f4983dd24b63f1286f15ae873286347fdcb2d5400077f123e140a7465a7a6ebb5",
          "sha256": "5dd1dd4a9daf974ef1b2cac1da0a295d7b7e242e4723718c1f63dbbdda1528f1",
          "sha1": "eca819aee06ce3acb1e753130ce1a1ea8316f802",
          "md5": "09266caf643f1548a951eccee926fa8c"
        }
      ]
    }
  ]
}
