{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a01",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "bo2m2bzyvfgbjfmoy4levvs3tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-0.1.1.jar",
          "url": "ble-characteristic-u2a01-0.1.1.jar",
          "size": 1810,
          "sha512": "ef097d6976d871b6b6920996ad0f3bff25db19072a8212c63047774dc9fe99c4c1f1fc4894d9f39cd2b164315b7cccdf139ebe19d0eae4b9333b8bba87c6c1ca",
          "sha256": "ac759f61f01bd82ce618c0d3f724dd97c91c9494595e4711329f6daba2a50f09",
          "sha1": "f30e10b27a1e9e3681c55b3407f317cf6c4a4a37",
          "md5": "59e0e5f7cb5bd7a3d5e561903d162e55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-0.1.1.jar",
          "url": "ble-characteristic-u2a01-0.1.1.jar",
          "size": 1810,
          "sha512": "ef097d6976d871b6b6920996ad0f3bff25db19072a8212c63047774dc9fe99c4c1f1fc4894d9f39cd2b164315b7cccdf139ebe19d0eae4b9333b8bba87c6c1ca",
          "sha256": "ac759f61f01bd82ce618c0d3f724dd97c91c9494595e4711329f6daba2a50f09",
          "sha1": "f30e10b27a1e9e3681c55b3407f317cf6c4a4a37",
          "md5": "59e0e5f7cb5bd7a3d5e561903d162e55"
        }
      ]
    }
  ]
}
