{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lns-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a67-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-android-0.8.12.aar",
          "url": "ble-service-lns-android-0.8.12.aar",
          "size": 1295,
          "sha512": "184c5d1b2cb5a225d6f82189be5da38a60c6a510db514026d4e469a04518dd8a2a7ac810db2f2a38e81d3efbaa140a26a75b6a8855139992b212c261f23f6c30",
          "sha256": "a1ef9975bfb6dec5536bf3e970c194ea417f61470dcf1b576a7f69a3c5927eb5",
          "sha1": "e1b5227a3a6edf431f5b883e916d15d47e6c5223",
          "md5": "f55b2535a0ea7b72df69daabfbf76746"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a67-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-android-0.8.12.aar",
          "url": "ble-service-lns-android-0.8.12.aar",
          "size": 1295,
          "sha512": "184c5d1b2cb5a225d6f82189be5da38a60c6a510db514026d4e469a04518dd8a2a7ac810db2f2a38e81d3efbaa140a26a75b6a8855139992b212c261f23f6c30",
          "sha256": "a1ef9975bfb6dec5536bf3e970c194ea417f61470dcf1b576a7f69a3c5927eb5",
          "sha1": "e1b5227a3a6edf431f5b883e916d15d47e6c5223",
          "md5": "f55b2535a0ea7b72df69daabfbf76746"
        }
      ]
    }
  ]
}
