{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a63",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a63-0.8.3.jar",
          "url": "ble-characteristic-u2a63-0.8.3.jar",
          "size": 5202,
          "sha512": "20eb21c6f7e607ec82e8e4219576146d715467ff8682bca7b98ce6e2570852c90a01e637cb5a1f12786ddbbf61dcbb561eda96023b148c0ef21f0692038cb8cd",
          "sha256": "9a193e10b5e42f42f9c4031ddfe2c52becc98dc673815399c6bc94b902bfe53b",
          "sha1": "dd7397db9c3a72f2935a42390b15f12aeae12ff6",
          "md5": "03069a53b015e6e248a4bcacb042f655"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a63-0.8.3.jar",
          "url": "ble-characteristic-u2a63-0.8.3.jar",
          "size": 5202,
          "sha512": "20eb21c6f7e607ec82e8e4219576146d715467ff8682bca7b98ce6e2570852c90a01e637cb5a1f12786ddbbf61dcbb561eda96023b148c0ef21f0692038cb8cd",
          "sha256": "9a193e10b5e42f42f9c4031ddfe2c52becc98dc673815399c6bc94b902bfe53b",
          "sha1": "dd7397db9c3a72f2935a42390b15f12aeae12ff6",
          "md5": "03069a53b015e6e248a4bcacb042f655"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a63-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2a63-0.8.3-javadoc.jar",
          "size": 120748,
          "sha512": "d29a401cf64966122251cb0956d55ba6f94cdb84a10619636ff67eacd1412ab60f74803c347783465ae1227170811f1be7f0d413682fdb807a4b2f8d4c31b3c6",
          "sha256": "ead415a024c033170a556a38ed23dd3083a5a02ce10152b01491c8492b59b711",
          "sha1": "a3bc66817dfd0ae3454456e2747a995b56e81be6",
          "md5": "daccaaa3950f8bd7683f641603af2b80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a63-0.8.3-sources.jar",
          "url": "ble-characteristic-u2a63-0.8.3-sources.jar",
          "size": 5035,
          "sha512": "5c484b1bd8564444d4a97d5b3c246307d8435770a3cb41aadd14aca1968d6eea9b43135030380594d5063341f293c5492ffe7e0f5fa376bb88755b9a42587526",
          "sha256": "bf306107db6c805330eca19e31f727d66b7dc3e8410ec7cc479748c045349fb5",
          "sha1": "7507d452f95438c8d366fbf44f102866bc9a406b",
          "md5": "9d073e867d00872c024e11c9c4e34c94"
        }
      ]
    }
  ]
}
