{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-wss-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-wss-android-0.4.0.aar",
          "url": "ble-service-central-wss-android-0.4.0.aar",
          "size": 5187,
          "sha512": "20abeacd4493f0313404de289a9b8aaacd1815db8a1ffbf3e33417bd42adf372995c51266db6398e6f53f1ef8e0412ec6ef649fcf493dc489a41252b2bc07481",
          "sha256": "388b27119d19b86e32d950937182485085b6feac17b5de63744eb8f1190d0c17",
          "sha1": "10e19f983a0e33817ab017cd8c1fd15f5d818b6e",
          "md5": "2254b624a622020d981ec9c5ec9d845a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-wss-android-0.4.0.aar",
          "url": "ble-service-central-wss-android-0.4.0.aar",
          "size": 5187,
          "sha512": "20abeacd4493f0313404de289a9b8aaacd1815db8a1ffbf3e33417bd42adf372995c51266db6398e6f53f1ef8e0412ec6ef649fcf493dc489a41252b2bc07481",
          "sha256": "388b27119d19b86e32d950937182485085b6feac17b5de63744eb8f1190d0c17",
          "sha1": "10e19f983a0e33817ab017cd8c1fd15f5d818b6e",
          "md5": "2254b624a622020d981ec9c5ec9d845a"
        }
      ]
    }
  ]
}
