{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.snksoft",
          "module": "crc",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-appearance",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-company",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-datatype",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-declaration",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-scheme",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-member",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-profile",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-protocol",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-sdo",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-unit",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-0.8.12.jar",
          "url": "ble-core-constants-0.8.12.jar",
          "size": 4222,
          "sha512": "7fb3b33b3c5cfb823787d50f495fe3e5e816d29a871246db7a12a107cf59f04097171c1e399401439f574248211c51503ff7312030fc3655cf0149811b260dc1",
          "sha256": "d7c67848084f9fa80ab571fdd483b6b2228016302107ba7ab072837f94b214ea",
          "sha1": "a82bc7fafd30a876d09d953f360e763a16ba7319",
          "md5": "954c4956467e7baa3067e50d1cca2096"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.snksoft",
          "module": "crc",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-appearance",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-company",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-datatype",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-declaration",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-scheme",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-member",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-profile",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-protocol",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-sdo",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-unit",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-0.8.12.jar",
          "url": "ble-core-constants-0.8.12.jar",
          "size": 4222,
          "sha512": "7fb3b33b3c5cfb823787d50f495fe3e5e816d29a871246db7a12a107cf59f04097171c1e399401439f574248211c51503ff7312030fc3655cf0149811b260dc1",
          "sha256": "d7c67848084f9fa80ab571fdd483b6b2228016302107ba7ab072837f94b214ea",
          "sha1": "a82bc7fafd30a876d09d953f360e763a16ba7319",
          "md5": "954c4956467e7baa3067e50d1cca2096"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-0.8.12-javadoc.jar",
          "url": "ble-core-constants-0.8.12-javadoc.jar",
          "size": 126885,
          "sha512": "648a837007c1a07888a5cfd36526516d504a50e374d75df58bf0c94a48d55dda9f8abf750b7b1244f392398b3e05c4313437e8f5ba850ba68f916eece38a35d4",
          "sha256": "c13d43f06695fb268d96a08737a0c3439749e87918f2e45d6d315d1ca29b7e17",
          "sha1": "c05d4a64f4c5ee9fcc8130eebf6d7471c76c4091",
          "md5": "3f4d516a75bb879aaf07271df7138243"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-0.8.12-sources.jar",
          "url": "ble-core-constants-0.8.12-sources.jar",
          "size": 1547,
          "sha512": "742983671489af708074842f7a372f116b42b2905d9d30ad34e924f81f381e4a351eee545624b2a3d3b9e7afb832c722b7dfdf8ab1479612517496e14b78783e",
          "sha256": "f3cf0466f285699fa0f65c6289cb7901136dd796c9790a440fbc3bca34c44355",
          "sha1": "3f4b09ed4c47f4ec4f17eda28375dec0d1652745",
          "md5": "0a5d0bc4af9f9b23b98358e681334167"
        }
      ]
    }
  ]
}
