{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b07",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b07-0.8.9.jar",
          "url": "ble-characteristic-u2b07-0.8.9.jar",
          "size": 1972,
          "sha512": "d5365479e9ab4386254009f9535f2fe6e052be4c5ddf4f03770cfdc814ac272c0b37b65687bdb4ec0e0bc68cb5953995ffe6835135293e649a34cbb069639c15",
          "sha256": "0a8fe335b791ada8758a9bca993c060bf90d2d6fb710bd2899cb1fb9eab72675",
          "sha1": "0bb4edf5edccd20b69295ac96d7f23d1f79d7fb2",
          "md5": "fd9eae4b94c5b4647093aba3853dedb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b07-0.8.9.jar",
          "url": "ble-characteristic-u2b07-0.8.9.jar",
          "size": 1972,
          "sha512": "d5365479e9ab4386254009f9535f2fe6e052be4c5ddf4f03770cfdc814ac272c0b37b65687bdb4ec0e0bc68cb5953995ffe6835135293e649a34cbb069639c15",
          "sha256": "0a8fe335b791ada8758a9bca993c060bf90d2d6fb710bd2899cb1fb9eab72675",
          "sha1": "0bb4edf5edccd20b69295ac96d7f23d1f79d7fb2",
          "md5": "fd9eae4b94c5b4647093aba3853dedb8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b07-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2b07-0.8.9-javadoc.jar",
          "size": 107741,
          "sha512": "de0abcd8241148a854b071ab6364ceda78172d6f920e8a4f7f80a8c23280430c696debae7f28bf1fb01a1e2ed080ac898f38653255332234f07d3b9717a7199f",
          "sha256": "e1512706997d9c75f25cebaec16e0b7575c76a117d9bdb6291a5c2b09ade88d9",
          "sha1": "8a618a01959d68ad9bb3c971df863f0af09fa4ae",
          "md5": "93c76cd6685909b52236840a8bd9b829"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b07-0.8.9-sources.jar",
          "url": "ble-characteristic-u2b07-0.8.9-sources.jar",
          "size": 1798,
          "sha512": "c6d9a58e0117c07c60378fa1aa2064d82ea55c27c9b1a77e16dba97defd28f279d9c95bf33159efb8604333e8185371d45264cdf8863ab93e1584d73a2875b3e",
          "sha256": "2978778ed5fa15fce2f048d52a1e108cc3b5b2e34202990e573ab163217ce9f4",
          "sha1": "5ba83884fd25ce3f0ad78487ae63acccbb4a3ce6",
          "md5": "c302215ed8f49423256741c75b277780"
        }
      ]
    }
  ]
}
