{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6d-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6d",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-android-0.2.7.aar",
          "url": "ble-characteristic-u2a6d-android-0.2.7.aar",
          "size": 3066,
          "sha512": "0d8fd17fef9281b16a44d837b366d04ac4fc6844a60da351607ed85a9e7cdbe826faa114bb6c53f5b5230a0943a6660a75957bd2f0005f466fdd4c3edf973d82",
          "sha256": "dca4568df4309c9c40d554107b8dc03181cf7b5d4bc52d465f046a6afba9fbe9",
          "sha1": "4915aee4736029a284c4243327a0dd9fd540de7d",
          "md5": "63cf81dc6401b755fe59cabfd9358779"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6d",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-android-0.2.7.aar",
          "url": "ble-characteristic-u2a6d-android-0.2.7.aar",
          "size": 3066,
          "sha512": "0d8fd17fef9281b16a44d837b366d04ac4fc6844a60da351607ed85a9e7cdbe826faa114bb6c53f5b5230a0943a6660a75957bd2f0005f466fdd4c3edf973d82",
          "sha256": "dca4568df4309c9c40d554107b8dc03181cf7b5d4bc52d465f046a6afba9fbe9",
          "sha1": "4915aee4736029a284c4243327a0dd9fd540de7d",
          "md5": "63cf81dc6401b755fe59cabfd9358779"
        }
      ]
    }
  ]
}
