{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b86",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b86-0.8.5.jar",
          "url": "ble-characteristic-u2b86-0.8.5.jar",
          "size": 1901,
          "sha512": "97bad5dcabbe23daf9c0ff83c2e8575c8ccd612230c84898b386a1e9b613988a97a6ad9373d1efb17608efeeed00018c081c39150d290d9b9333f7e9a05dffd0",
          "sha256": "26fa8d9ddfda0cd378eb704b210554b79c5bd14e7da782fdbf05e62269186315",
          "sha1": "966917d514e539a0267d7909fd29729d8e141d84",
          "md5": "c3b3941023c98cf53c41a31e4ff322c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b86-0.8.5.jar",
          "url": "ble-characteristic-u2b86-0.8.5.jar",
          "size": 1901,
          "sha512": "97bad5dcabbe23daf9c0ff83c2e8575c8ccd612230c84898b386a1e9b613988a97a6ad9373d1efb17608efeeed00018c081c39150d290d9b9333f7e9a05dffd0",
          "sha256": "26fa8d9ddfda0cd378eb704b210554b79c5bd14e7da782fdbf05e62269186315",
          "sha1": "966917d514e539a0267d7909fd29729d8e141d84",
          "md5": "c3b3941023c98cf53c41a31e4ff322c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b86-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b86-0.8.5-javadoc.jar",
          "size": 109468,
          "sha512": "c3d0da3e194f7e2fa98ccf981501fbd1c0cb74fa3c591943cc59552a23c17d20e648386e0685d9e5afd35c5e446dc76b62fd8c0adb5f9b6f2ba2aab06c38e016",
          "sha256": "301349bd36d3112748ab65785fdf928fb1e49a36c37bc0131f83133a223aaf22",
          "sha1": "69a4c2cac49c6e15bddb8c990ca95eec898a0ca7",
          "md5": "f607338af009d8994c1d266d6609c12b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b86-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b86-0.8.5-sources.jar",
          "size": 1715,
          "sha512": "fb8e1f08e65798969571a2382667313d286a3fd42dd249eb03202f1fc07eb27635e1a829f11ae5576acd2d91dfb87101335a8a15de7beb00069adeb341ee9160",
          "sha256": "389d94af7286e87477f1782fbce401cb7cade2156d573ba2cd9f2a638d6e9235",
          "sha1": "95d2e4959c0dff62b90b5161a8b03ffc3114fccb",
          "md5": "822bb9ae12f95e90ca882aa78b4c14ea"
        }
      ]
    }
  ]
}
