{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa4-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa4-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa4-android-0.8.6.aar",
          "size": 3177,
          "sha512": "1b9fbd46d69ace4505f9e6d0ad8dda9006b4e6f683aa6aff22dc4305e1941323d49563ad009f7a13c06281c610d2e1ef3c315691e6bfec758a40c89289eb6fb9",
          "sha256": "b129d0207184d696783f7a23dd7a5d28ae72655c3c94a48ca487cd420100eec0",
          "sha1": "b4b8617a02dadb53cd1fa0ef427baeef9773dba6",
          "md5": "751a189095d0dc57b690fbc0b5940d87"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa4-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa4-android-0.8.6.aar",
          "size": 3177,
          "sha512": "1b9fbd46d69ace4505f9e6d0ad8dda9006b4e6f683aa6aff22dc4305e1941323d49563ad009f7a13c06281c610d2e1ef3c315691e6bfec758a40c89289eb6fb9",
          "sha256": "b129d0207184d696783f7a23dd7a5d28ae72655c3c94a48ca487cd420100eec0",
          "sha1": "b4b8617a02dadb53cd1fa0ef427baeef9773dba6",
          "md5": "751a189095d0dc57b690fbc0b5940d87"
        }
      ]
    }
  ]
}
