{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-cps-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2903-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a63-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a64-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a66-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-android-0.8.12.aar",
          "url": "ble-service-cps-android-0.8.12.aar",
          "size": 1295,
          "sha512": "e8eb075c07a8c1cab2898056e9369145fe78dbcc80fa89dc9dcf2acc44dad1922bf66f96c2ae63f360e7b3595179450457bdc87a085dec81f00dd85fd3e276d8",
          "sha256": "78a567a947dd9e2a44053eded4092a4ef501a2b3f9a732095bc11dff96403d88",
          "sha1": "2365e0a84e7768d876ae69ed9a0d5830d0af086c",
          "md5": "6edd5d3b0c2d19fc2b42ef23d27b30c2"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2903-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a63-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a64-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a66-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-android-0.8.12.aar",
          "url": "ble-service-cps-android-0.8.12.aar",
          "size": 1295,
          "sha512": "e8eb075c07a8c1cab2898056e9369145fe78dbcc80fa89dc9dcf2acc44dad1922bf66f96c2ae63f360e7b3595179450457bdc87a085dec81f00dd85fd3e276d8",
          "sha256": "78a567a947dd9e2a44053eded4092a4ef501a2b3f9a732095bc11dff96403d88",
          "sha1": "2365e0a84e7768d876ae69ed9a0d5830d0af086c",
          "md5": "6edd5d3b0c2d19fc2b42ef23d27b30c2"
        }
      ]
    }
  ]
}
