{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b31",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b31-0.8.13.jar",
          "url": "ble-characteristic-u2b31-0.8.13.jar",
          "size": 1459,
          "sha512": "68b5f92fa08b350dc4a0def264bfc6898e982704bcba70ea6b9edf816bc337b5c3cb454c144f4450635fc4c4aacbd8e0a6c363d96cbb5b02c18db0f9642b4b67",
          "sha256": "31e385883f6d2aa003bff77aa84f9a02e85527c4778edce8376e9e1882f9fceb",
          "sha1": "abc5c2f303fae0892149da73e7847729be7700cd",
          "md5": "1f348ded7d97a182f6e2906cf4b95b0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b31-0.8.13.jar",
          "url": "ble-characteristic-u2b31-0.8.13.jar",
          "size": 1459,
          "sha512": "68b5f92fa08b350dc4a0def264bfc6898e982704bcba70ea6b9edf816bc337b5c3cb454c144f4450635fc4c4aacbd8e0a6c363d96cbb5b02c18db0f9642b4b67",
          "sha256": "31e385883f6d2aa003bff77aa84f9a02e85527c4778edce8376e9e1882f9fceb",
          "sha1": "abc5c2f303fae0892149da73e7847729be7700cd",
          "md5": "1f348ded7d97a182f6e2906cf4b95b0c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b31-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2b31-0.8.13-javadoc.jar",
          "size": 86021,
          "sha512": "12aedd2d8c700e92d255df865aa44c5eb152fcaf6de7ce878447e223d35669596ecea974a80b2d7aeff65c51adc4a672275f768d413920554dc9947a52887cfc",
          "sha256": "9e4044e3cb92d9e494ef9c3d342d5c5812515d88d58585157f1e2867e103423f",
          "sha1": "a00749e076086320e3b18cb23e4c79629a25df29",
          "md5": "4ebbfe3bb17387ac23518c72d0f8d009"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b31-0.8.13-sources.jar",
          "url": "ble-characteristic-u2b31-0.8.13-sources.jar",
          "size": 1441,
          "sha512": "187bb9c172cb76c8b046593eb6e5b6291d2bc74d241dec9a31b16d7c87dbe1e57b83893029f73646a06ce87b9d0a1be8786e8e0fd927e56ac549d600f9bb06fa",
          "sha256": "0fd530cc1f7f61e5633b84e98da0cc766364c04f58eda5f2e6a4b64c28ce9903",
          "sha1": "4d26c14210c6e5d6a760ab345b285cf705c57962",
          "md5": "48d908df861fe1c2aa43b4b9d615f905"
        }
      ]
    }
  ]
}
