{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a24-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a24",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-android-0.2.0.aar",
          "url": "ble-characteristic-u2a24-android-0.2.0.aar",
          "size": 2930,
          "sha512": "a89cb6ed4f824834c91aa83da7156cd722dfd7dca2c1a4c3c13fb9955e02157b2dd8bea3625fd49a0a8c6d280a551db500847f1834feee811495a234593b1eef",
          "sha256": "c66e58cc1c820197f723c28ddf1fa57d55f7e702e4572b662e92fc49d1c07a41",
          "sha1": "a278dd3673aae2871c5be1fb3befaa439a411e14",
          "md5": "bcf210763405876bf1d99cb7e30aa192"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a24",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-android-0.2.0.aar",
          "url": "ble-characteristic-u2a24-android-0.2.0.aar",
          "size": 2930,
          "sha512": "a89cb6ed4f824834c91aa83da7156cd722dfd7dca2c1a4c3c13fb9955e02157b2dd8bea3625fd49a0a8c6d280a551db500847f1834feee811495a234593b1eef",
          "sha256": "c66e58cc1c820197f723c28ddf1fa57d55f7e702e4572b662e92fc49d1c07a41",
          "sha1": "a278dd3673aae2871c5be1fb3befaa439a411e14",
          "md5": "bcf210763405876bf1d99cb7e30aa192"
        }
      ]
    }
  ]
}
