{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aad",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.6.jar",
          "url": "ble-characteristic-u2aad-0.8.6.jar",
          "size": 1772,
          "sha512": "83c18320bc6b9720483d514941230d39e1666d46721c6f2ff5d6875c9a3fd36c55b848799033b2d9d383ce2edfc57b690e0e107b3a6610ab3beee2fa84b99c8e",
          "sha256": "23714290c5f410a1bb69f37013d6daeae0a4f1daea39fc1273d17d70f2a09207",
          "sha1": "ad3caa9c6f6a3ce5d5fb92753792b84caefb20de",
          "md5": "81ace44f85900427367ee7e5bd42b4b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.6.jar",
          "url": "ble-characteristic-u2aad-0.8.6.jar",
          "size": 1772,
          "sha512": "83c18320bc6b9720483d514941230d39e1666d46721c6f2ff5d6875c9a3fd36c55b848799033b2d9d383ce2edfc57b690e0e107b3a6610ab3beee2fa84b99c8e",
          "sha256": "23714290c5f410a1bb69f37013d6daeae0a4f1daea39fc1273d17d70f2a09207",
          "sha1": "ad3caa9c6f6a3ce5d5fb92753792b84caefb20de",
          "md5": "81ace44f85900427367ee7e5bd42b4b5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2aad-0.8.6-javadoc.jar",
          "size": 107484,
          "sha512": "1285cff7139f25bc89c198a7308167e5c255fa140991783adc287555e5ebf29a33fca7fc58ca249950830e1e0a8f56c399aae421ae434200e6d0feee2214bef2",
          "sha256": "17a6704f7726b70ae1786d3ef5859a7458a04e8a4d515e3c235f72c9c6d39704",
          "sha1": "8d7d45c182ffc93f36234f19173d55e3252c67c0",
          "md5": "9b541c126b09ffab9949fb11b15e515e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.6-sources.jar",
          "url": "ble-characteristic-u2aad-0.8.6-sources.jar",
          "size": 1636,
          "sha512": "7f0c9b883ef4bcb20fcb9d9655c6b24bfaf32f7b600780848fd22b981a1ab0eebbaaab9dbcdcbf4f7128ee794ba90e246333783adffc6c5ce84c797f3dc00bde",
          "sha256": "80a38b1cdd93e9640f0446bec98c6a3f958ce07efe04da9071045a6f54e0caf2",
          "sha1": "d920e7e834c3d1ba6c4250e72a13ebaafd3b20ff",
          "md5": "728b2a79b7bd00e63cb02398664d78d8"
        }
      ]
    }
  ]
}
