{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9f",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-0.5.1.jar",
          "url": "ble-characteristic-u2a9f-0.5.1.jar",
          "size": 3196,
          "sha512": "6e2fc3c90544d5da2b52a31f98f4e6d6332befa338be897c75704b4f5caa3a614a5acadf4814660d3426d16acdbccfb2263c6145567fb37a6eb99e9fe1ccca75",
          "sha256": "e190da4b6abe4acecb482543016dc14cc2715c920768773d92d7ab8da7fb3170",
          "sha1": "bb832b41e13bb45e1c404a952cd9f566efeb384a",
          "md5": "a6e20157cb24c87c77c0ed8c94b3454b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-0.5.1.jar",
          "url": "ble-characteristic-u2a9f-0.5.1.jar",
          "size": 3196,
          "sha512": "6e2fc3c90544d5da2b52a31f98f4e6d6332befa338be897c75704b4f5caa3a614a5acadf4814660d3426d16acdbccfb2263c6145567fb37a6eb99e9fe1ccca75",
          "sha256": "e190da4b6abe4acecb482543016dc14cc2715c920768773d92d7ab8da7fb3170",
          "sha1": "bb832b41e13bb45e1c404a952cd9f566efeb384a",
          "md5": "a6e20157cb24c87c77c0ed8c94b3454b"
        }
      ]
    }
  ]
}
