{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a71-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "md2hzulcvrbjbp3omyeiu4n5fi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-android-0.2.3.aar",
          "url": "ble-characteristic-u2a71-android-0.2.3.aar",
          "size": 2923,
          "sha512": "773e95b8e3287246a4f3eac2d8d6f9bb6c46f1d577c000236ec8b9ac1d146ec817636417d7b63afc7f49d2ef77e7aeb8740c62df9f1ed7992bb66463fbd177d0",
          "sha256": "0878ac045edb095e6b32ae90e80a9cfcf21ae615b0d30f16a63f110b1ba29855",
          "sha1": "11e15c0c74401c5ed1fa61dc5197f6e3a4e228e7",
          "md5": "d6025a1766e26b94e575a9c6189359a0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-android-0.2.3.aar",
          "url": "ble-characteristic-u2a71-android-0.2.3.aar",
          "size": 2923,
          "sha512": "773e95b8e3287246a4f3eac2d8d6f9bb6c46f1d577c000236ec8b9ac1d146ec817636417d7b63afc7f49d2ef77e7aeb8740c62df9f1ed7992bb66463fbd177d0",
          "sha256": "0878ac045edb095e6b32ae90e80a9cfcf21ae615b0d30f16a63f110b1ba29855",
          "sha1": "11e15c0c74401c5ed1fa61dc5197f6e3a4e228e7",
          "md5": "d6025a1766e26b94e575a9c6189359a0"
        }
      ]
    }
  ]
}
