{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a77",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.8.12.jar",
          "url": "ble-characteristic-u2a77-0.8.12.jar",
          "size": 1859,
          "sha512": "86c46762ec2ccb9269f067c058fd23d2d9ccecd83f662831ed439f6d710f926a662b50fe938ee5a7ae9056e52b3c6b883a3605ea2a142b53e8e30c2f676b9e9f",
          "sha256": "d12b8dc4f59d1542d6a9e09169a91350bb6463ec0f8c6c630dc41e198b5ccbe4",
          "sha1": "30093827f3d6a6b5d2dac6790f1dd5cb45728ac6",
          "md5": "bec9f8b094ed5afcf1195005ebbab771"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.8.12.jar",
          "url": "ble-characteristic-u2a77-0.8.12.jar",
          "size": 1859,
          "sha512": "86c46762ec2ccb9269f067c058fd23d2d9ccecd83f662831ed439f6d710f926a662b50fe938ee5a7ae9056e52b3c6b883a3605ea2a142b53e8e30c2f676b9e9f",
          "sha256": "d12b8dc4f59d1542d6a9e09169a91350bb6463ec0f8c6c630dc41e198b5ccbe4",
          "sha1": "30093827f3d6a6b5d2dac6790f1dd5cb45728ac6",
          "md5": "bec9f8b094ed5afcf1195005ebbab771"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a77-0.8.12-javadoc.jar",
          "size": 109332,
          "sha512": "418355eabc83f952d571e761544060d52f27bf4a5500f1b28adcb134863a9e18b93c569f04b7a04dfc4cccbc62e6e9b3edd8c69e562fec2743cbf5ccba0960dd",
          "sha256": "6b767471630e1b973a9d47d3769f3dd68aff5a360fbaeaea58b79548d4add3a1",
          "sha1": "edbdbd4dd6a78a225afca20985f888cc3ee6b384",
          "md5": "2285423c8cb08617ff5cfee52231c1fa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a77-0.8.12-sources.jar",
          "size": 1682,
          "sha512": "c4a5e40f0b1895de19619353007983af78bf9afe8d7a247b7cbea70298901faf227ad865cf3e69782aef7ac4c3c494f8e85651a06c60bc008712085d834e6b98",
          "sha256": "86c51c81c5be1d2c924024d28e2347bdc0516271fa64800aed4719168fe29b32",
          "sha1": "066c12d308a1cdda3e3980ecc4e45286918b9098",
          "md5": "2d1844650403425cc652fe34de64eb47"
        }
      ]
    }
  ]
}
