{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba6-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba6",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba6-android-0.8.11.aar",
          "url": "ble-characteristic-u2ba6-android-0.8.11.aar",
          "size": 3171,
          "sha512": "c6d8cd35886b77bc3126290d18e8d9a95a9940608f947549ef76b3d840ac02783d9c3b795e644f6b578df708c898621dd32d72dfab02a4778579f21058f98c52",
          "sha256": "54cc47210c340030c4df8eabc2d8291bc5f78ab5bdd1a25bc0408216ce6cbd34",
          "sha1": "230d1d9fa1f1e11a21898e2f186c59c82876da2b",
          "md5": "70f349a69b429ebc922c25be01004bef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba6",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba6-android-0.8.11.aar",
          "url": "ble-characteristic-u2ba6-android-0.8.11.aar",
          "size": 3171,
          "sha512": "c6d8cd35886b77bc3126290d18e8d9a95a9940608f947549ef76b3d840ac02783d9c3b795e644f6b578df708c898621dd32d72dfab02a4778579f21058f98c52",
          "sha256": "54cc47210c340030c4df8eabc2d8291bc5f78ab5bdd1a25bc0408216ce6cbd34",
          "sha1": "230d1d9fa1f1e11a21898e2f186c59c82876da2b",
          "md5": "70f349a69b429ebc922c25be01004bef"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba6-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2ba6-android-0.8.11-sources.jar",
          "size": 2180,
          "sha512": "f6884be90c1d898993158ae5487e39a464f9721d10e04839b63b8e6acc8705e1bdbf3173a071bd6d8232f59c3b3678779e5107837ee2e1d18da1c2d6198c658e",
          "sha256": "56d5d26373bec089d7956a131bf0f93c7908756870ed812a47a9076420651609",
          "sha1": "b33841f29943f0f5d4a9a4dcb15b3e875bd93090",
          "md5": "77d31157c60d55e8cccc316dcef5426c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba6-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2ba6-android-0.8.11-javadoc.jar",
          "size": 270572,
          "sha512": "1b7c35cc53c2169c905a02514862a588596c82e97b42f849362d7789723bb34c8e99cd9a577537ca2e31074fe6d9673772a328b52809b1035b4e4f8b0ad62e77",
          "sha256": "ae4b5858db85c0c1dcbafc76090e50767a65354bd60afd90e13f1e45d2ad48cd",
          "sha1": "4e8b890bec1f4a64a6faddba57e9c5eec524e131",
          "md5": "35c364afc4ae9fef94c5b0498223d536"
        }
      ]
    }
  ]
}
