{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a24-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a24",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-android-0.8.12.aar",
          "url": "ble-characteristic-u2a24-android-0.8.12.aar",
          "size": 3213,
          "sha512": "918b463a2fbba94b0d77db79ddcfb799b40dbe9d1f1eae93f8a2a67320a966601daefc328fcf0ec7d924d47f79a6dc8cfa17fc1b039988e6e1ea48fb256ee61e",
          "sha256": "b0dcb45a82247ba39273b13ef972ff598bb09b113bb47b4a9e9b378db8667dc4",
          "sha1": "ae654e74f83d7a91a83d5baf34e3c807a8d3297c",
          "md5": "1f4a37da55e2738d69116e08d3a4867e"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a24",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-android-0.8.12.aar",
          "url": "ble-characteristic-u2a24-android-0.8.12.aar",
          "size": 3213,
          "sha512": "918b463a2fbba94b0d77db79ddcfb799b40dbe9d1f1eae93f8a2a67320a966601daefc328fcf0ec7d924d47f79a6dc8cfa17fc1b039988e6e1ea48fb256ee61e",
          "sha256": "b0dcb45a82247ba39273b13ef972ff598bb09b113bb47b4a9e9b378db8667dc4",
          "sha1": "ae654e74f83d7a91a83d5baf34e3c807a8d3297c",
          "md5": "1f4a37da55e2738d69116e08d3a4867e"
        }
      ]
    }
  ]
}
