{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a32-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kupq6qdcq5dovle6dw5m7myoyy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.1.3.aar",
          "url": "ble-characteristic-u2a32-android-0.1.3.aar",
          "size": 3097,
          "sha512": "259d971a46a2d2c9264076c0c6f5f871cb1f7b2c3997307a22b0582f5aa0f93312610a30257f510d9a7024af2a96adb53499da78bc750e1955001e65accf2072",
          "sha256": "00681f8623af4ebaa38656370f65f25d0ad8f2a2b74c2feb835fad0cf650d8e8",
          "sha1": "2ce1e60704de415c1e5f934dfe48c74c1773688e",
          "md5": "a13463a1d87494d194506acb00aa0767"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.1.3.aar",
          "url": "ble-characteristic-u2a32-android-0.1.3.aar",
          "size": 3097,
          "sha512": "259d971a46a2d2c9264076c0c6f5f871cb1f7b2c3997307a22b0582f5aa0f93312610a30257f510d9a7024af2a96adb53499da78bc750e1955001e65accf2072",
          "sha256": "00681f8623af4ebaa38656370f65f25d0ad8f2a2b74c2feb835fad0cf650d8e8",
          "sha1": "2ce1e60704de415c1e5f934dfe48c74c1773688e",
          "md5": "a13463a1d87494d194506acb00aa0767"
        }
      ]
    }
  ]
}
