{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3c",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.4.2.jar",
          "url": "ble-characteristic-u2b3c-0.4.2.jar",
          "size": 1501,
          "sha512": "efc59db2672ebcd12344299e16a549be6a5a8e2d7ecbf8ac32d904ca3b391923e08600f667a9e624ec035f97c680e8a816c2a8aa08b096f455f980ade9997616",
          "sha256": "7502b5898b0f32d50707471e74c76b58634f2e847a65855c29b89906793d4857",
          "sha1": "63e1a08485a799152c646e770b511fc5b0a9f92e",
          "md5": "5367a31645096d6756efe78682e325fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.4.2.jar",
          "url": "ble-characteristic-u2b3c-0.4.2.jar",
          "size": 1501,
          "sha512": "efc59db2672ebcd12344299e16a549be6a5a8e2d7ecbf8ac32d904ca3b391923e08600f667a9e624ec035f97c680e8a816c2a8aa08b096f455f980ade9997616",
          "sha256": "7502b5898b0f32d50707471e74c76b58634f2e847a65855c29b89906793d4857",
          "sha1": "63e1a08485a799152c646e770b511fc5b0a9f92e",
          "md5": "5367a31645096d6756efe78682e325fb"
        }
      ]
    }
  ]
}
