{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad2-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad2-android-0.2.7.aar",
          "url": "ble-characteristic-u2ad2-android-0.2.7.aar",
          "size": 5308,
          "sha512": "0a2ffc3a41b26d4bbe604ff2ffde925a6e9b762843ce719da868302b9c5099a97d516342207297434ec07f5f2995bcb070bd9efcc8feb1dfa1428d67cd1ae1ed",
          "sha256": "e673b26bcbcd56cbb3f884455aaaeb82b417aac1032e0abcb95d095130f7ef54",
          "sha1": "d6fccdbf96e3fee8a1d61c24cc8ae44bd3ed255d",
          "md5": "7ddfdb26d995e0be56986d0c1df8484b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad2-android-0.2.7.aar",
          "url": "ble-characteristic-u2ad2-android-0.2.7.aar",
          "size": 5308,
          "sha512": "0a2ffc3a41b26d4bbe604ff2ffde925a6e9b762843ce719da868302b9c5099a97d516342207297434ec07f5f2995bcb070bd9efcc8feb1dfa1428d67cd1ae1ed",
          "sha256": "e673b26bcbcd56cbb3f884455aaaeb82b417aac1032e0abcb95d095130f7ef54",
          "sha1": "d6fccdbf96e3fee8a1d61c24cc8ae44bd3ed255d",
          "md5": "7ddfdb26d995e0be56986d0c1df8484b"
        }
      ]
    }
  ]
}
