{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba3-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba3",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba3-android-0.4.6.aar",
          "url": "ble-characteristic-u2ba3-android-0.4.6.aar",
          "size": 3042,
          "sha512": "075944c500fc2e7231da26159c165c6d4979f3b608dddba3a5146eab238330cd31ddafa2aa98a96da1f4d3864a0b710401e4df04e95f3f8b7f784cbc29bad0e2",
          "sha256": "9dc0151b26d3cc798b010e7cc976941fa27495199ca0ad03393094aa9f89299f",
          "sha1": "2a9023a4c3b680b9f26ad300d35f19213ebe548a",
          "md5": "6b79bfec152859e7989d9e38c85328f9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba3",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba3-android-0.4.6.aar",
          "url": "ble-characteristic-u2ba3-android-0.4.6.aar",
          "size": 3042,
          "sha512": "075944c500fc2e7231da26159c165c6d4979f3b608dddba3a5146eab238330cd31ddafa2aa98a96da1f4d3864a0b710401e4df04e95f3f8b7f784cbc29bad0e2",
          "sha256": "9dc0151b26d3cc798b010e7cc976941fa27495199ca0ad03393094aa9f89299f",
          "sha1": "2a9023a4c3b680b9f26ad300d35f19213ebe548a",
          "md5": "6b79bfec152859e7989d9e38c85328f9"
        }
      ]
    }
  ]
}
