{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae7",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae7-0.8.3.jar",
          "url": "ble-characteristic-u2ae7-0.8.3.jar",
          "size": 1888,
          "sha512": "bd96dc8c69fd16cff523db7170843c38c944f84d08e45f519639872e463259b465f074490ed19d6b70c1897b9185e9ebfac719ba3baf1fafeefebde8109352e5",
          "sha256": "980d6aa23b14a1410eecf8aa36415cfd078de88c55b794c9b7310b4c89b16580",
          "sha1": "12c752f1d0bf861fc8c3c78c2753bc8037a0f46a",
          "md5": "7ddc6a4a1edc69d3504d9f2eb12b17dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae7-0.8.3.jar",
          "url": "ble-characteristic-u2ae7-0.8.3.jar",
          "size": 1888,
          "sha512": "bd96dc8c69fd16cff523db7170843c38c944f84d08e45f519639872e463259b465f074490ed19d6b70c1897b9185e9ebfac719ba3baf1fafeefebde8109352e5",
          "sha256": "980d6aa23b14a1410eecf8aa36415cfd078de88c55b794c9b7310b4c89b16580",
          "sha1": "12c752f1d0bf861fc8c3c78c2753bc8037a0f46a",
          "md5": "7ddc6a4a1edc69d3504d9f2eb12b17dc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae7-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2ae7-0.8.3-javadoc.jar",
          "size": 111075,
          "sha512": "74ed5aeb3b4f9cd1c4c89d9eac88ad8fdf9d01f2b62aac7ae3814bbe40982b84a335b2b79360925b7550e997bec700acb172391d228ce989df30bddfca926a73",
          "sha256": "d604196454d0bd8a20a19fda4e6088137f5d77ab02035a4ea03ff82b56f7c5b8",
          "sha1": "15974f7b3409e48956e2a4ea9dc8c77cad9539a1",
          "md5": "918003d94a4a22fc1241d9809b779192"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae7-0.8.3-sources.jar",
          "url": "ble-characteristic-u2ae7-0.8.3-sources.jar",
          "size": 1738,
          "sha512": "5ce738c032f1cd1aa96a90a68ae4ef657c5df5a9a2e26ba7d77ae9de59c3b904967cadea8f8926089ce3a1927aab284dbd10b7b4e011d8661a311258312d4e9f",
          "sha256": "331ef601c74311ba8a6a8b7f96233df02e5ab0570d599d963085f82896e6473a",
          "sha1": "090b44ed2adec9a0b38abea5c89471872bd6856d",
          "md5": "09ebb4f6873444272aa9ed26f17fe57c"
        }
      ]
    }
  ]
}
