{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6b",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fvvoe34nybbdlbbrzowl64zzta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.2.4.jar",
          "url": "ble-characteristic-u2a6b-0.2.4.jar",
          "size": 4305,
          "sha512": "3d6e699be2d7718733cbea0daf1fc7e2a22f525ead285e740c27228ea5ac671c9504f38a8f01ef2b725bcf7d7606da2324494b2767768a861e4b270ac9cbd1d5",
          "sha256": "e92c252c89834788e4cae7ab4d694bb49487cf448937408ec179cb7a1015c838",
          "sha1": "03af883d63001a88982cf8df1ea86c3db72782a9",
          "md5": "880c251d71a49d47460d283049773f74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.2.4.jar",
          "url": "ble-characteristic-u2a6b-0.2.4.jar",
          "size": 4305,
          "sha512": "3d6e699be2d7718733cbea0daf1fc7e2a22f525ead285e740c27228ea5ac671c9504f38a8f01ef2b725bcf7d7606da2324494b2767768a861e4b270ac9cbd1d5",
          "sha256": "e92c252c89834788e4cae7ab4d694bb49487cf448937408ec179cb7a1015c838",
          "sha1": "03af883d63001a88982cf8df1ea86c3db72782a9",
          "md5": "880c251d71a49d47460d283049773f74"
        }
      ]
    }
  ]
}
