{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bac",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bac-0.8.7.jar",
          "url": "ble-characteristic-u2bac-0.8.7.jar",
          "size": 1455,
          "sha512": "275b2fc08cb5c517eebe4e32e19b81d0a53ff0541efdcefdc58e380dc35b59e716440ef89490a00ed3be64fd23f68ea593fb65e43dc302726a202e935823bfc9",
          "sha256": "b7e7cf6e98d4426a5eafa103042d50b209e816161db3ecfed50979bf639f6eae",
          "sha1": "9641a21fd29e51ae2e6fd9791f208349db40611d",
          "md5": "767dc27ecab0f8edd3ccc4a9bb9dc7ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bac-0.8.7.jar",
          "url": "ble-characteristic-u2bac-0.8.7.jar",
          "size": 1455,
          "sha512": "275b2fc08cb5c517eebe4e32e19b81d0a53ff0541efdcefdc58e380dc35b59e716440ef89490a00ed3be64fd23f68ea593fb65e43dc302726a202e935823bfc9",
          "sha256": "b7e7cf6e98d4426a5eafa103042d50b209e816161db3ecfed50979bf639f6eae",
          "sha1": "9641a21fd29e51ae2e6fd9791f208349db40611d",
          "md5": "767dc27ecab0f8edd3ccc4a9bb9dc7ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bac-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bac-0.8.7-javadoc.jar",
          "size": 107135,
          "sha512": "6de642f35da16159d7fdc0ded8a6ff3af98c08ecff42758263e0ae049e41d02091f928f7976f48c1d396f6639d5f4d6bb4a2254f3cc2fa2cbf58e105b89b9851",
          "sha256": "4b0fe8cd96e3b49cdd943b4a844592089659889562b21e2efad8e7e578e04838",
          "sha1": "fa2bb85eff53bca35f03e38006b2e2cc06c3c266",
          "md5": "fd7ebb49e7279cb24e93f6c2d07fd4f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bac-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bac-0.8.7-sources.jar",
          "size": 1449,
          "sha512": "30e838de8545bad128d810146a2a26ca0384fb945eb765f1f4bf145b60514c0dd9326630530486b89d2f8a110e0d133be04612198239bdfc3c40e881538a87b9",
          "sha256": "940d9c8fa6d853df3c3e92dac7dec2541974d590e5b5d72723a159586b24cffb",
          "sha1": "2a1be2a9ba17552c16ff8c2f22429bb8844729ce",
          "md5": "d238d5674930dda85060a64290420d6a"
        }
      ]
    }
  ]
}
