{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-cps-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-central-android-0.1.4.aar",
          "url": "ble-service-cps-central-android-0.1.4.aar",
          "size": 7653,
          "sha512": "d221a27d9de013d26ed31fe4f9590b120ba4481924d6a371fe3f108e47236b0989b9831a07853d214d877e3d73e88198a3a577dde6113ab6d42c727ccfba722f",
          "sha256": "9f5a441b768cdcee1f7c340f00142f1cbf2baf2069635fbd9feaed658b4f8d4a",
          "sha1": "16d98312dcd2ca5e83c2f32727d4de0c05fd3641",
          "md5": "920093fe87c6e5d55ea07d0d411a006e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-central-android-0.1.4.aar",
          "url": "ble-service-cps-central-android-0.1.4.aar",
          "size": 7653,
          "sha512": "d221a27d9de013d26ed31fe4f9590b120ba4481924d6a371fe3f108e47236b0989b9831a07853d214d877e3d73e88198a3a577dde6113ab6d42c727ccfba722f",
          "sha256": "9f5a441b768cdcee1f7c340f00142f1cbf2baf2069635fbd9feaed658b4f8d4a",
          "sha1": "16d98312dcd2ca5e83c2f32727d4de0c05fd3641",
          "md5": "920093fe87c6e5d55ea07d0d411a006e"
        }
      ]
    }
  ]
}
