{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acc",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.6.jar",
          "url": "ble-characteristic-u2acc-0.8.6.jar",
          "size": 4687,
          "sha512": "8c9f3fedf0c4fd264d7827b0b36bff34a1073ac11fee7520e7f9f9c6aeb964668985f87455d6b26d9d12ebeb1dd5ef8324a38247e16de67fb08cb1b0241f9837",
          "sha256": "42e2baf1ae08e1cc82438db3b9a0d3668448ef4713c5b9dfcd48631b0a07707d",
          "sha1": "be32355e17382b6cd253e59019a3ac6433443e35",
          "md5": "224001771fdb8a2bb14bf71773a9033d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.6.jar",
          "url": "ble-characteristic-u2acc-0.8.6.jar",
          "size": 4687,
          "sha512": "8c9f3fedf0c4fd264d7827b0b36bff34a1073ac11fee7520e7f9f9c6aeb964668985f87455d6b26d9d12ebeb1dd5ef8324a38247e16de67fb08cb1b0241f9837",
          "sha256": "42e2baf1ae08e1cc82438db3b9a0d3668448ef4713c5b9dfcd48631b0a07707d",
          "sha1": "be32355e17382b6cd253e59019a3ac6433443e35",
          "md5": "224001771fdb8a2bb14bf71773a9033d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2acc-0.8.6-javadoc.jar",
          "size": 124526,
          "sha512": "a136e52120ee02db1da3f3c6a7fce700eb2c555e064aac58ed663410a44ee1b8685ba2aefb7ebe27eb042116e13f8076dae7f0921de724b67e71e4555d8a189e",
          "sha256": "1de2e239f5f7076b2f0ca03db8f14fbcde965ccc60c6102107be4b0e6ced3640",
          "sha1": "312ce818f88b1a33eddd9d21972e5b0bbf952afc",
          "md5": "858de61568ce12a70ed375355a346a20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.6-sources.jar",
          "url": "ble-characteristic-u2acc-0.8.6-sources.jar",
          "size": 5470,
          "sha512": "d3ee3cf17a12170e6384d4aeb8bfb7e0bf76ee952280b3aec339abfd40ccf7413a1417701216785597319c1626782f85de54f62696a08d90424d38b0c8593770",
          "sha256": "d5caa0d3bad2b04e6b34f599a5141f4fd2a78b31f847dec0db5e466fce4b22c3",
          "sha1": "7200c5dbaee70f567eb8580ff17f4c31631765ec",
          "md5": "c147cc62e6330c4c040359e8ceac158a"
        }
      ]
    }
  ]
}
