{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6b-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.2.6.aar",
          "url": "ble-characteristic-u2a6b-android-0.2.6.aar",
          "size": 3176,
          "sha512": "54bf807cf3e6b1845df06de1ac739ddbaa6e8b4154f02c29ea07bc4716056d4062908f2a99985f28c8197d1bcd6f1ef5db965fa1b90bda8e88fc517e30b829f7",
          "sha256": "9fedee6c2a54bbb3f82e231f41f6c2d3c7e662f0b14df69874fed96dc6e3960d",
          "sha1": "92d76e93592bebe1ef4254a6943d489390944f71",
          "md5": "9925fb2823f5535f49c35eeef5db4b42"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.2.6.aar",
          "url": "ble-characteristic-u2a6b-android-0.2.6.aar",
          "size": 3176,
          "sha512": "54bf807cf3e6b1845df06de1ac739ddbaa6e8b4154f02c29ea07bc4716056d4062908f2a99985f28c8197d1bcd6f1ef5db965fa1b90bda8e88fc517e30b829f7",
          "sha256": "9fedee6c2a54bbb3f82e231f41f6c2d3c7e662f0b14df69874fed96dc6e3960d",
          "sha1": "92d76e93592bebe1ef4254a6943d489390944f71",
          "md5": "9925fb2823f5535f49c35eeef5db4b42"
        }
      ]
    }
  ]
}
