{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af1",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af1-0.8.14.jar",
          "url": "ble-characteristic-u2af1-0.8.14.jar",
          "size": 2016,
          "sha512": "0f4159fef173a7f1818a1813575c0e3ee905dd86693ca4844ad66dd69b0be3a7f80f02657c9a23fd70acea7799527026447fda44ce8fa9de75c453956c60d0b2",
          "sha256": "264515db82bea091a7a42bf6c64099c7788b49389d99fad4a003b59222358002",
          "sha1": "1924280c370d88eb41919b22aab8c451be0d17b5",
          "md5": "e07a7a8205a90d5e263a1625bc23ac88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af1-0.8.14.jar",
          "url": "ble-characteristic-u2af1-0.8.14.jar",
          "size": 2016,
          "sha512": "0f4159fef173a7f1818a1813575c0e3ee905dd86693ca4844ad66dd69b0be3a7f80f02657c9a23fd70acea7799527026447fda44ce8fa9de75c453956c60d0b2",
          "sha256": "264515db82bea091a7a42bf6c64099c7788b49389d99fad4a003b59222358002",
          "sha1": "1924280c370d88eb41919b22aab8c451be0d17b5",
          "md5": "e07a7a8205a90d5e263a1625bc23ac88"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af1-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2af1-0.8.14-javadoc.jar",
          "size": 86581,
          "sha512": "96208bd3f26a34dc51aa67ef5c42c2a5447631812e833a752509a3c8382929ff1998d78913aa31cc1c4c4bf6fc56c2130869d233ac9c6021df7dd283533bb19b",
          "sha256": "f1cdc0457aa536b546d67d63c36ba4f0c0d6065d8f377afed7886e6778176c5b",
          "sha1": "ab235313228012c2c951f7e2f3031e57916c32c4",
          "md5": "a031faef83918982f8039a650cbecc5a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af1-0.8.14-sources.jar",
          "url": "ble-characteristic-u2af1-0.8.14-sources.jar",
          "size": 1840,
          "sha512": "58ea0c69ac876b0b5bbb4163dafc5d224f968d9838c59c8e02c3bf45428bd7558a2895ba768066ff18af05fb37e9723948b1ccda4e8c64cd0bdd33d262816977",
          "sha256": "93a6df3240c1d5b40e144ddb8e357ce61767d75c60891409f028f55894082718",
          "sha1": "49e8a3f903803327455963c4c5131a16cc98b6c7",
          "md5": "9e3a2c755f80ebb83ca697575c3f62a2"
        }
      ]
    }
  ]
}
