{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa9-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa9",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa9-android-0.8.12.aar",
          "url": "ble-characteristic-u2aa9-android-0.8.12.aar",
          "size": 3126,
          "sha512": "2e009c19c76dbc9abfde5d424dcc984d95f17303f21faf9d97a8e73f42e8896e8f4255ef2892044f210d13b0e854fd46583cbd0677484d7361ea5a780388efc1",
          "sha256": "3480dc4c10c74ed3e860e310865e91d2eddcc4817b7121b69bb803f6e5bf50da",
          "sha1": "1d9818b461b40d7e318b791547c395e52187335e",
          "md5": "2fb699d48fbf5d0e6e9c912836424a03"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa9",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa9-android-0.8.12.aar",
          "url": "ble-characteristic-u2aa9-android-0.8.12.aar",
          "size": 3126,
          "sha512": "2e009c19c76dbc9abfde5d424dcc984d95f17303f21faf9d97a8e73f42e8896e8f4255ef2892044f210d13b0e854fd46583cbd0677484d7361ea5a780388efc1",
          "sha256": "3480dc4c10c74ed3e860e310865e91d2eddcc4817b7121b69bb803f6e5bf50da",
          "sha1": "1d9818b461b40d7e318b791547c395e52187335e",
          "md5": "2fb699d48fbf5d0e6e9c912836424a03"
        }
      ]
    }
  ]
}
