{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4e-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4e",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-android-0.2.7.aar",
          "url": "ble-characteristic-u2a4e-android-0.2.7.aar",
          "size": 3082,
          "sha512": "ccf056a6e8199e2c9ec614c01d99bdd419cd4a15a53e7bef7c258ef29918d559d0fd6883be32b605b99247781723264579927cc62ad49615bd6dcb69d1d16322",
          "sha256": "68edfd29bcd4251b6bab46ca623e86eb7572481e5fc39e6f31812f2bb586fb9c",
          "sha1": "44a7acff2f16a2655d78007b2c8a37a9a2e8c9ef",
          "md5": "4413d53b196ebf459f274c5e81a4e669"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4e",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-android-0.2.7.aar",
          "url": "ble-characteristic-u2a4e-android-0.2.7.aar",
          "size": 3082,
          "sha512": "ccf056a6e8199e2c9ec614c01d99bdd419cd4a15a53e7bef7c258ef29918d559d0fd6883be32b605b99247781723264579927cc62ad49615bd6dcb69d1d16322",
          "sha256": "68edfd29bcd4251b6bab46ca623e86eb7572481e5fc39e6f31812f2bb586fb9c",
          "sha1": "44a7acff2f16a2655d78007b2c8a37a9a2e8c9ef",
          "md5": "4413d53b196ebf459f274c5e81a4e669"
        }
      ]
    }
  ]
}
