{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb2-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb2",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb2-android-0.8.7.aar",
          "url": "ble-characteristic-u2bb2-android-0.8.7.aar",
          "size": 3226,
          "sha512": "53182ec0e11eab3d81f9aeca809abb9df7a2bb645f600a2c34dbb3889a31ebeb4946372c0748cbbdb82a8b274ad07a798a88bf35e25fe8847cad7c0ab382bc17",
          "sha256": "1383e5ec6d8aed34c083791bc9ed1ba49ac683b7cebedda2a4f6f09cf0a2ec8e",
          "sha1": "fc8483fc0187671acba1284b239a2a7642a35e77",
          "md5": "874135434116d1ab26750772ee14063c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb2",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb2-android-0.8.7.aar",
          "url": "ble-characteristic-u2bb2-android-0.8.7.aar",
          "size": 3226,
          "sha512": "53182ec0e11eab3d81f9aeca809abb9df7a2bb645f600a2c34dbb3889a31ebeb4946372c0748cbbdb82a8b274ad07a798a88bf35e25fe8847cad7c0ab382bc17",
          "sha256": "1383e5ec6d8aed34c083791bc9ed1ba49ac683b7cebedda2a4f6f09cf0a2ec8e",
          "sha1": "fc8483fc0187671acba1284b239a2a7642a35e77",
          "md5": "874135434116d1ab26750772ee14063c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb2-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bb2-android-0.8.7-sources.jar",
          "size": 2230,
          "sha512": "39c456a21ea6e8d7791f07282a016ae3194edb3fae1c7dba002db830bfe5193fd468a156e31e024b945a622fad5b2160206da533c3fca0f5056426e44520bd20",
          "sha256": "2cffec0eea89af188996a642048a752dc78f76f2008d44082dc35d61c98d7614",
          "sha1": "314e77272e1ad2a7f659b9aee6dddc43729cd384",
          "md5": "ae513f71424379b0149e07b4b13d7ba6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb2-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bb2-android-0.8.7-javadoc.jar",
          "size": 270756,
          "sha512": "491a7c413ccd2ac09ca7a6f0fdb80f0bda24bb13ad9fda4831a941d2535a3c5be7d73a1d60ced93a0b0ef74a8ecccfeaa95ae23748b6c4a107217878f1fe3ae7",
          "sha256": "3cd768d2b515af6f6aa68c29f6b78e47c3685ea52c09763773671c366fd7bc09",
          "sha1": "c81593cb74ec6300af8d8b32316a6389feb5fcb3",
          "md5": "580948bc13a11615034b46d48562b5ba"
        }
      ]
    }
  ]
}
