{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc4",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.7.jar",
          "url": "ble-characteristic-u2bc4-0.8.7.jar",
          "size": 1435,
          "sha512": "0ab0e2aa70f3d57c8867449c242d89caf994b6708c7c87c93e4a68a48e69040764090ac9faf06f2e158143faf5843ea00090b4fd0da6814e86c5701de3393390",
          "sha256": "74edc8e15f564169649b04f5e6643abbe7874aaeb1b6d0b65f2f4e0314b27973",
          "sha1": "70dd6b9d9a143ec3b735dd67be565a9a5ca3cb89",
          "md5": "5f4654df3cbf181cee9968dec15a006e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.7.jar",
          "url": "ble-characteristic-u2bc4-0.8.7.jar",
          "size": 1435,
          "sha512": "0ab0e2aa70f3d57c8867449c242d89caf994b6708c7c87c93e4a68a48e69040764090ac9faf06f2e158143faf5843ea00090b4fd0da6814e86c5701de3393390",
          "sha256": "74edc8e15f564169649b04f5e6643abbe7874aaeb1b6d0b65f2f4e0314b27973",
          "sha1": "70dd6b9d9a143ec3b735dd67be565a9a5ca3cb89",
          "md5": "5f4654df3cbf181cee9968dec15a006e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bc4-0.8.7-javadoc.jar",
          "size": 107092,
          "sha512": "04def4ffce66730bf04f6a7d4feb5c5b42bd547ad231bb08013706cfe2cfeba0040bdec25549d51c89371e874de8b1a367a3ae612cc7a97e7b0a9ea0a79876c4",
          "sha256": "ccf0db5be6cfb0c109883d66224b59272fb93657b6e8c636a6b6373c4be0af6d",
          "sha1": "e4b954b99be4ca785c51143cbe7022281012be18",
          "md5": "496b7cda29520cde8afc7100114d4c6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bc4-0.8.7-sources.jar",
          "size": 1412,
          "sha512": "c2d99edd3a5cb10215be4c39289e990eb54cb0668fe9fc606f46dd4c0a86157e00142d54dc4274df287de58ead7953ce24e8154d36f5f115135a5af05b57d0d8",
          "sha256": "6a2c8f34070a6f2bc3cee4a3d73ecdeeb57a198a3c71177d0819bec319936fdc",
          "sha1": "5ba089a30c23412f686ef219e15e9f503b22cb89",
          "md5": "48d93b31ec780b8ff12bdbc07b6e0fac"
        }
      ]
    }
  ]
}
