{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a22-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a22",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a22-android-0.4.4.aar",
          "url": "ble-characteristic-u2a22-android-0.4.4.aar",
          "size": 3104,
          "sha512": "b5d63ea36abfc471bb00e47a7cdae8e28927fb59553bca159d39528c0806f18f89b254dea8f08d0750e46b27672208c2746817eb5ebff03505b5e96157117fec",
          "sha256": "23c11a44036e4aa4a62493333b3823a045b2aa09057e555413b97709ce3b2e06",
          "sha1": "92ea891146236926c9da2a5d015db4a437a88780",
          "md5": "246b0f9d64bac2e25c2df7d0a9589789"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a22",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a22-android-0.4.4.aar",
          "url": "ble-characteristic-u2a22-android-0.4.4.aar",
          "size": 3104,
          "sha512": "b5d63ea36abfc471bb00e47a7cdae8e28927fb59553bca159d39528c0806f18f89b254dea8f08d0750e46b27672208c2746817eb5ebff03505b5e96157117fec",
          "sha256": "23c11a44036e4aa4a62493333b3823a045b2aa09057e555413b97709ce3b2e06",
          "sha1": "92ea891146236926c9da2a5d015db4a437a88780",
          "md5": "246b0f9d64bac2e25c2df7d0a9589789"
        }
      ]
    }
  ]
}
