{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a17-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.2.9.aar",
          "url": "ble-characteristic-u2a17-android-0.2.9.aar",
          "size": 3153,
          "sha512": "2aa85f6bf3f60e7dd2bcb14f1488ca46d5c8669b7f61500f0387fb8e14df1380fb49b252718326cf3c12d8db3503152c0ad7d4bc3d67d6ea8269fd49c9e1c16d",
          "sha256": "86bab29e343110de4aab940fd7925d6d9a71621a0b1061af758a98dc583bc3ba",
          "sha1": "1316803cc912e10a36b4abf76b04ccd79013aa6d",
          "md5": "d757f58bbfdbedf8dbf7ab4f4f48000c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.2.9.aar",
          "url": "ble-characteristic-u2a17-android-0.2.9.aar",
          "size": 3153,
          "sha512": "2aa85f6bf3f60e7dd2bcb14f1488ca46d5c8669b7f61500f0387fb8e14df1380fb49b252718326cf3c12d8db3503152c0ad7d4bc3d67d6ea8269fd49c9e1c16d",
          "sha256": "86bab29e343110de4aab940fd7925d6d9a71621a0b1061af758a98dc583bc3ba",
          "sha1": "1316803cc912e10a36b4abf76b04ccd79013aa6d",
          "md5": "d757f58bbfdbedf8dbf7ab4f4f48000c"
        }
      ]
    }
  ]
}
