{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a93-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.4.4.aar",
          "url": "ble-characteristic-u2a93-android-0.4.4.aar",
          "size": 3209,
          "sha512": "8106e79306bb90cc9afc0525d419e38572d89303e8ac0c3f281aa315324a843742018615b6d625acb21019ac85331107bdbdc1d0f7768c1b1dc4b37b8e5ab8c2",
          "sha256": "d0be14c131ed6cddf6600baf48a60c7cad689329941e33540ce5ebabbd084dd0",
          "sha1": "4122a11dd7982b02711169af36d8a50c0163f528",
          "md5": "52af7d0cb1ee8bf474af9816eb4067d4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.4.4.aar",
          "url": "ble-characteristic-u2a93-android-0.4.4.aar",
          "size": 3209,
          "sha512": "8106e79306bb90cc9afc0525d419e38572d89303e8ac0c3f281aa315324a843742018615b6d625acb21019ac85331107bdbdc1d0f7768c1b1dc4b37b8e5ab8c2",
          "sha256": "d0be14c131ed6cddf6600baf48a60c7cad689329941e33540ce5ebabbd084dd0",
          "sha1": "4122a11dd7982b02711169af36d8a50c0163f528",
          "md5": "52af7d0cb1ee8bf474af9816eb4067d4"
        }
      ]
    }
  ]
}
