{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-sdo",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.12.jar",
          "url": "ble-core-constants-sdo-0.8.12.jar",
          "size": 2682,
          "sha512": "4da673d03c29463fa67876ed976c62b2b99daab91ca46b3bb58ff5a9d1da28a305a7dbe1e76cf63567704667303b01749cad239ae1dad8e0c9106d5a56071758",
          "sha256": "f4490ad7822df14aa399d2a221bddbe3ea7ac2bd9d5aa74121c0359fd8565b9a",
          "sha1": "c661673a7df31e426f58fe877f5d68411120439a",
          "md5": "cc3fa246fc6c949e8514d4dde4b8d241"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.12.jar",
          "url": "ble-core-constants-sdo-0.8.12.jar",
          "size": 2682,
          "sha512": "4da673d03c29463fa67876ed976c62b2b99daab91ca46b3bb58ff5a9d1da28a305a7dbe1e76cf63567704667303b01749cad239ae1dad8e0c9106d5a56071758",
          "sha256": "f4490ad7822df14aa399d2a221bddbe3ea7ac2bd9d5aa74121c0359fd8565b9a",
          "sha1": "c661673a7df31e426f58fe877f5d68411120439a",
          "md5": "cc3fa246fc6c949e8514d4dde4b8d241"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.12-javadoc.jar",
          "url": "ble-core-constants-sdo-0.8.12-javadoc.jar",
          "size": 106346,
          "sha512": "aa841b990c9b5a1b5ace022212fd40b0b4f1c5fe817c80fb753a9ca3bb26c5ba84bc6399d90789cfb5062b7a5aa2bb384c381eb28bf0b23e6ed331891d6cca6d",
          "sha256": "9a48d8c37644ae7074f697c3a2355e5bd32e0c1da5b882aa3af10ca917fba19b",
          "sha1": "290bfcc020f185ac4b2d130381cf2ad75eaff8ae",
          "md5": "b0012bb24f26afc0e64a1f936d522bcb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.12-sources.jar",
          "url": "ble-core-constants-sdo-0.8.12-sources.jar",
          "size": 1520,
          "sha512": "c7907d7dc1c30f35dc8b4a5e020b85cb92b91c6db90d3563a4a024d4955363d2befb521894091c58e0ac4884d0135d11eea9dc31ef53727d17f10222b7cc398f",
          "sha256": "d4a91143f0dfa5999fea0fa90490539558768e47c92873c17a4404e6a5e64759",
          "sha1": "6c392ea7e2b87f46fd4771e3d0efb6895dc34fd7",
          "md5": "df883333761e5fb7a16a3f9306916cb8"
        }
      ]
    }
  ]
}
