{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a70-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a70",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a70-android-0.2.7.aar",
          "url": "ble-characteristic-u2a70-android-0.2.7.aar",
          "size": 3089,
          "sha512": "fe19d2340b2055e05f506686842a47d9d817603ea9f935b2f8dc9e82e61bde1395d1fc19fe34f4d9e62b8c5203df65caf25ef53e2da53c73c7c7e2d69278ff03",
          "sha256": "4a440b29fd6b5a260379f8a56bd9b6ce776769f50bdd73e253d1dbd793cbeabb",
          "sha1": "8c80cd206c2a056e77ee5fd0d9ecadce10adee8f",
          "md5": "02fbd737b60db5b395c3ccdc9a1e64d0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a70",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a70-android-0.2.7.aar",
          "url": "ble-characteristic-u2a70-android-0.2.7.aar",
          "size": 3089,
          "sha512": "fe19d2340b2055e05f506686842a47d9d817603ea9f935b2f8dc9e82e61bde1395d1fc19fe34f4d9e62b8c5203df65caf25ef53e2da53c73c7c7e2d69278ff03",
          "sha256": "4a440b29fd6b5a260379f8a56bd9b6ce776769f50bdd73e253d1dbd793cbeabb",
          "sha1": "8c80cd206c2a056e77ee5fd0d9ecadce10adee8f",
          "md5": "02fbd737b60db5b395c3ccdc9a1e64d0"
        }
      ]
    }
  ]
}
