{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2beb",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2beb-0.8.12.jar",
          "url": "ble-characteristic-u2beb-0.8.12.jar",
          "size": 1478,
          "sha512": "829fc4c4636f9d6f4f9e536be19919949fb70d8de0f4bda04d45a0c7bf6c3f03756329f75d0b40c68f3b6e81765d64b70733cb2775403968a60e3327988b61a6",
          "sha256": "aac9ca71dd84461a226cd9d4ceb8384dd9cf373556d009ae418f259c40c98c62",
          "sha1": "dae700786d3cd12d439a75351745304a8e72b455",
          "md5": "3555815e9cac9ea06029ef3e4f25c0cd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2beb-0.8.12.jar",
          "url": "ble-characteristic-u2beb-0.8.12.jar",
          "size": 1478,
          "sha512": "829fc4c4636f9d6f4f9e536be19919949fb70d8de0f4bda04d45a0c7bf6c3f03756329f75d0b40c68f3b6e81765d64b70733cb2775403968a60e3327988b61a6",
          "sha256": "aac9ca71dd84461a226cd9d4ceb8384dd9cf373556d009ae418f259c40c98c62",
          "sha1": "dae700786d3cd12d439a75351745304a8e72b455",
          "md5": "3555815e9cac9ea06029ef3e4f25c0cd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2beb-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2beb-0.8.12-javadoc.jar",
          "size": 86049,
          "sha512": "8d8fcaa90a95f730933ba0089034e43b7b115b226d966f143140be5c9968277c3b3b49000c25b85837730164d28bedd6b5e7b158812596017236abd3bd4a6313",
          "sha256": "11c2f9e2dd98f4f380ec2a32cdcbe5f92b950c7f91af20b62c7638c325fa5908",
          "sha1": "6ebb4c973160b7d825279790d9d61dc704b6cec9",
          "md5": "d87cd9d0e3fdd15b1b2e8775a94ed92e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2beb-0.8.12-sources.jar",
          "url": "ble-characteristic-u2beb-0.8.12-sources.jar",
          "size": 1458,
          "sha512": "50c80f939777ab9646dfc7a9ed3484af1732648ef754a7846178992b6965b11c0120c79af1e92da388159c9d52f2ef3027f02b78881c628e65a79d1dd7c84427",
          "sha256": "03e3d0900bc29d510d32763c49d3f164e05d64b4f2a791369f5fc786c78380d3",
          "sha1": "f1fb725a54cb6178eea9381378e8a34aa19154e1",
          "md5": "1467844d40cb399882706a81a62a583b"
        }
      ]
    }
  ]
}
