{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac8-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac8",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac8-android-0.8.12.aar",
          "url": "ble-characteristic-u2ac8-android-0.8.12.aar",
          "size": 3191,
          "sha512": "54a40aa0c7bd16dddf67742807de135d344f931da5d9ed5f11cc3767f2b557b72fd8c626d89e9410839042e7337c0b5ecfcd6130a89e6f6322517a0a1965c65a",
          "sha256": "fcb91c78ee5bbcca07511c7c932814c3e2df480c9daca9b2d6d3027b511ff090",
          "sha1": "2e2b20e9956304648aeabac358ca356fb339a665",
          "md5": "413e025cd4b7b16fdf123b5c89aed5f0"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac8",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac8-android-0.8.12.aar",
          "url": "ble-characteristic-u2ac8-android-0.8.12.aar",
          "size": 3191,
          "sha512": "54a40aa0c7bd16dddf67742807de135d344f931da5d9ed5f11cc3767f2b557b72fd8c626d89e9410839042e7337c0b5ecfcd6130a89e6f6322517a0a1965c65a",
          "sha256": "fcb91c78ee5bbcca07511c7c932814c3e2df480c9daca9b2d6d3027b511ff090",
          "sha1": "2e2b20e9956304648aeabac358ca356fb339a665",
          "md5": "413e025cd4b7b16fdf123b5c89aed5f0"
        }
      ]
    }
  ]
}
