{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b8f-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "url": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "size": 3113,
          "sha512": "f224612662f9d1e6d3d4b79909aef5c5db3d40d6616e41bda0f2ca789a5b01e08101e4f729bc663129ecee9844014695ed77f3ca1622b673f4893422e02c1b04",
          "sha256": "8dadedea0362d0238694a8bbdc5bbfc6051b2f1f4ca058ea1d1bfcd7bfe2c682",
          "sha1": "295783a578815a38c06783dc949b583f08073b15",
          "md5": "fd04ee57d2c9f33907754591cc8c70b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "url": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "size": 3113,
          "sha512": "f224612662f9d1e6d3d4b79909aef5c5db3d40d6616e41bda0f2ca789a5b01e08101e4f729bc663129ecee9844014695ed77f3ca1622b673f4893422e02c1b04",
          "sha256": "8dadedea0362d0238694a8bbdc5bbfc6051b2f1f4ca058ea1d1bfcd7bfe2c682",
          "sha1": "295783a578815a38c06783dc949b583f08073b15",
          "md5": "fd04ee57d2c9f33907754591cc8c70b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b8f-android-0.8.12-sources.jar",
          "size": 2186,
          "sha512": "edbb95dcfb9f6b2ccd2ba39edf2fca91851b16476587316a8aead90dfddc4cd6d1e7d2d18fc2def35104189309a7502decdf0b6fd8d8ab497ed083b7e58a638a",
          "sha256": "ec4b825c8b77cb0e38d1c6aa7f6d69d7f5ce9710be59f3e2bb941b75b5f9cb5a",
          "sha1": "9aa065a3240fbb7b2336da169031536ac3d42507",
          "md5": "795ae0e5f201356b5b2031c5c8c11f44"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b8f-android-0.8.12-javadoc.jar",
          "size": 269401,
          "sha512": "1b885c13d57e00d0a2d4da731a5bd444c4470a4307e639251fc6f884d3454c35999f616322ba21fb2b7c3d787aa7a4d75e8a4129676830532c06555271a77476",
          "sha256": "9a91d3537a023311fff5954ddfd33a9e0a82a71a9c0c7704c90da46ad1399d0d",
          "sha1": "cd8103301822e531fa2eb15cf40f1ff6c4b4acb4",
          "md5": "16f13f7b890c779ed672eb017aaf4147"
        }
      ]
    }
  ]
}
