{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b8f-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "url": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "size": 3155,
          "sha512": "9726a0808dc2445540064739bc9919f7b33aa1b93a7f3eaedef2b024e5d26aa8bb97364311752612627c283902c3f6843b3b8e7b4603de93f6f2b517762a7745",
          "sha256": "47bdcfeb50569848c7bc71a6ab4ad76347d1d7053784f9659d6e2da4bccef2b0",
          "sha1": "80801e8ec76767ab7d9b38527e986577a6d5ac78",
          "md5": "79321b23559d4dbfd268f2074e402362"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "url": "ble-characteristic-u2b8f-android-0.8.12.aar",
          "size": 3155,
          "sha512": "9726a0808dc2445540064739bc9919f7b33aa1b93a7f3eaedef2b024e5d26aa8bb97364311752612627c283902c3f6843b3b8e7b4603de93f6f2b517762a7745",
          "sha256": "47bdcfeb50569848c7bc71a6ab4ad76347d1d7053784f9659d6e2da4bccef2b0",
          "sha1": "80801e8ec76767ab7d9b38527e986577a6d5ac78",
          "md5": "79321b23559d4dbfd268f2074e402362"
        }
      ]
    }
  ]
}
