{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-lnp-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tgigj2sc2ba7vcxsvkfplwux5u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-lnp-android-0.1.3.aar",
          "url": "ble-profile-lnp-android-0.1.3.aar",
          "size": 1022,
          "sha512": "5d9bfd6dcb46a1f0f30aca7df4f37ff45dca049a209619634806ef18aeb420cb81f8fafe9396d7dbe4b8fc5d5d5f732e13f1c635398ddc5fdde1a7cef65cd635",
          "sha256": "c325559203d02cdcf35a69587fbe106796b9654887ab4b1ae1f1029b77160fd3",
          "sha1": "ef28d761fbf45264392d12ad3bd3b15ce906a780",
          "md5": "60b90e7936451457819e4e413bf37442"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-lnp-android-0.1.3.aar",
          "url": "ble-profile-lnp-android-0.1.3.aar",
          "size": 1022,
          "sha512": "5d9bfd6dcb46a1f0f30aca7df4f37ff45dca049a209619634806ef18aeb420cb81f8fafe9396d7dbe4b8fc5d5d5f732e13f1c635398ddc5fdde1a7cef65cd635",
          "sha256": "c325559203d02cdcf35a69587fbe106796b9654887ab4b1ae1f1029b77160fd3",
          "sha1": "ef28d761fbf45264392d12ad3bd3b15ce906a780",
          "md5": "60b90e7936451457819e4e413bf37442"
        }
      ]
    }
  ]
}
