{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a0a",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0a-0.4.1.jar",
          "url": "ble-characteristic-u2a0a-0.4.1.jar",
          "size": 1445,
          "sha512": "058a793fbd9e37f05d9f103535ef86aace57c0f73299cd5550e2256e2e19b6fa9e5abb5047a7f63bb295aed29d9c59d744846e89e144c35868897817a99136b5",
          "sha256": "384a0368dfe1e23ff33556002e2b706828b2ed3324cba63370de1a08404d3607",
          "sha1": "8ffcc6a2161d250fb220ce62d40de574f9b4ac18",
          "md5": "89306c6474d8e63a3a76f05a0ad5613e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0a-0.4.1.jar",
          "url": "ble-characteristic-u2a0a-0.4.1.jar",
          "size": 1445,
          "sha512": "058a793fbd9e37f05d9f103535ef86aace57c0f73299cd5550e2256e2e19b6fa9e5abb5047a7f63bb295aed29d9c59d744846e89e144c35868897817a99136b5",
          "sha256": "384a0368dfe1e23ff33556002e2b706828b2ed3324cba63370de1a08404d3607",
          "sha1": "8ffcc6a2161d250fb220ce62d40de574f9b4ac18",
          "md5": "89306c6474d8e63a3a76f05a0ad5613e"
        }
      ]
    }
  ]
}
