{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aed-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aed",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aed-android-0.4.6.aar",
          "url": "ble-characteristic-u2aed-android-0.4.6.aar",
          "size": 3071,
          "sha512": "6223b31af55e7b02fdffb887d34c0ee771707921a107ee95707556aa837b6670439ef042ce5ed8069c0547258217751db7ec2266623a5dc7ecbe3d1a822c91df",
          "sha256": "cbfbd65e7325db410faac744cc031e662177f71bd4ca004a449b5b222dc4dce7",
          "sha1": "fb3804d856dfc614a153f19e3967acbedfadd9ee",
          "md5": "b0cbbec74ef28459d3ebce1649b8e152"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aed",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aed-android-0.4.6.aar",
          "url": "ble-characteristic-u2aed-android-0.4.6.aar",
          "size": 3071,
          "sha512": "6223b31af55e7b02fdffb887d34c0ee771707921a107ee95707556aa837b6670439ef042ce5ed8069c0547258217751db7ec2266623a5dc7ecbe3d1a822c91df",
          "sha256": "cbfbd65e7325db410faac744cc031e662177f71bd4ca004a449b5b222dc4dce7",
          "sha1": "fb3804d856dfc614a153f19e3967acbedfadd9ee",
          "md5": "b0cbbec74ef28459d3ebce1649b8e152"
        }
      ]
    }
  ]
}
