{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a79",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.12.jar",
          "url": "ble-characteristic-u2a79-0.8.12.jar",
          "size": 1747,
          "sha512": "f5db67655c473b69436c50337c475c6964ea7d7f1c2e9e8f06352d56ffd32ac4c5a132124ce1d62b0b04e9facfc8c06cf66c4c09112cc52f346e48c6ac6e9b4e",
          "sha256": "99b2f779012734043061a48350f3a9bc60f1e1aa591a47c56574bd19f725f88b",
          "sha1": "715c36e816957201e212bb17671a14258021b48b",
          "md5": "17cb59d6d094eb0ae9e9cc05a14d04b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.12.jar",
          "url": "ble-characteristic-u2a79-0.8.12.jar",
          "size": 1747,
          "sha512": "f5db67655c473b69436c50337c475c6964ea7d7f1c2e9e8f06352d56ffd32ac4c5a132124ce1d62b0b04e9facfc8c06cf66c4c09112cc52f346e48c6ac6e9b4e",
          "sha256": "99b2f779012734043061a48350f3a9bc60f1e1aa591a47c56574bd19f725f88b",
          "sha1": "715c36e816957201e212bb17671a14258021b48b",
          "md5": "17cb59d6d094eb0ae9e9cc05a14d04b5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a79-0.8.12-javadoc.jar",
          "size": 107308,
          "sha512": "2c8a1a7aff8ee7af91cbf1e163261c53fba80a7cb00cf16ee1c35ae05ab10f4ef5a65f9b8acd791b5eaaae8707ee13bf517f39ec8678150adb2c0be578a89438",
          "sha256": "aaaf50e89d19100241a52f4c1a40d984da8858778624ce77eeabd0a97507316f",
          "sha1": "7adae0d664f0fd900d8979c2d3f376b51ef2e58f",
          "md5": "fd81b0a5577ccbbb00895fa48d0ff938"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a79-0.8.12-sources.jar",
          "size": 1589,
          "sha512": "0ec716b65c5a4316b70746b7dc452a20ca4319d06985bd30ff4431a3b820768d61b7fff076f18a7889b335fff0f98ffb0aa661a48e715bda18886be90b3b4cc8",
          "sha256": "07e2a6b5d7d2cf483b6fc51744c8c1e4e20d24294f63323e5a5834386fb72a39",
          "sha1": "28e5500476f65f66f21f42ba69a9aaccf55ad38b",
          "md5": "f02742dd12d6dcf0a93d7add2003493a"
        }
      ]
    }
  ]
}
