{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1b",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.7.jar",
          "url": "ble-characteristic-u2b1b-0.8.7.jar",
          "size": 2070,
          "sha512": "296d250f4d04e3fb0f60ea3e333dc930a3f3fea05558c119a8369df1f60ef9b478b26575292ad695f072d60fc43e5f9423382fd570e673e585eee26372234058",
          "sha256": "e0ab42801a53bb70934d7d3fe7816f42aed363b528d4383c7f1f46528809c398",
          "sha1": "6dc033173901ef8868268a8bd903ed13fb5cee53",
          "md5": "87d4eb19ff43153bac83c1769d90a766"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.7.jar",
          "url": "ble-characteristic-u2b1b-0.8.7.jar",
          "size": 2070,
          "sha512": "296d250f4d04e3fb0f60ea3e333dc930a3f3fea05558c119a8369df1f60ef9b478b26575292ad695f072d60fc43e5f9423382fd570e673e585eee26372234058",
          "sha256": "e0ab42801a53bb70934d7d3fe7816f42aed363b528d4383c7f1f46528809c398",
          "sha1": "6dc033173901ef8868268a8bd903ed13fb5cee53",
          "md5": "87d4eb19ff43153bac83c1769d90a766"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b1b-0.8.7-javadoc.jar",
          "size": 110034,
          "sha512": "1a0e89d10cff8f70909dd56261fa22fe0d0392ade4a6b2b4f0f8d26501ca373e3849294d9e6be26954bf4c9c7c7d9f95ff8bc57f97c4678c18477e885fc5d06f",
          "sha256": "ac77857ab9edee57a17f5b264c02554463d7fa2a9c3715c7de0b981b8ad04cf2",
          "sha1": "57610cfca759f060e2486563aa851d7216a7221f",
          "md5": "957efdfb2f370f1394dcf139f583ca47"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1b-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b1b-0.8.7-sources.jar",
          "size": 1937,
          "sha512": "cd3811477e341415aa0b5da2f72392dd8787d7d55c3c160428b65d4b98bd6fc088eaf2f7f171ddce0d33ccf2bb9f2473fe943712421bcec4b4f7e1e4e5f469af",
          "sha256": "d64c50ffc5a7dae375b9e7144cd8ee1a5c391260151b5912e0398da94c008bdc",
          "sha1": "0a17b3c32a79054d7cb1f8c39dfacb3634991ed6",
          "md5": "192c0c7a51ea34cf8b83f251912e3316"
        }
      ]
    }
  ]
}
