{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2add",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2add-0.6.0.jar",
          "url": "ble-characteristic-u2add-0.6.0.jar",
          "size": 1456,
          "sha512": "4fb34ef40741fd43603ea2e1ea14fec398f12ea170350e5933804f3ffd74ab74f94ed7c1b77071b572fb6d311595e0864db00c14462e7436ff7cfe1473213051",
          "sha256": "2e66b6e9614d5c872fc47efcf834d08f27bccdf9d702ee804c8cd86456cee943",
          "sha1": "e616ea5c8bfa482559faae7146665d3aa7bf592a",
          "md5": "5734139ac6ace77090dddd9dcf40c1e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2add-0.6.0.jar",
          "url": "ble-characteristic-u2add-0.6.0.jar",
          "size": 1456,
          "sha512": "4fb34ef40741fd43603ea2e1ea14fec398f12ea170350e5933804f3ffd74ab74f94ed7c1b77071b572fb6d311595e0864db00c14462e7436ff7cfe1473213051",
          "sha256": "2e66b6e9614d5c872fc47efcf834d08f27bccdf9d702ee804c8cd86456cee943",
          "sha1": "e616ea5c8bfa482559faae7146665d3aa7bf592a",
          "md5": "5734139ac6ace77090dddd9dcf40c1e4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2add-0.6.0-javadoc.jar",
          "url": "ble-characteristic-u2add-0.6.0-javadoc.jar",
          "size": 109896,
          "sha512": "8bf954b88f709078042a3240c4607c5c130878efeff416f1ab559ed771e0786096eb3e53d617c381b8c1364cbf6b71b8e1f2116ed8ef7ab1cf48fc11afe03420",
          "sha256": "cb2bbc5466bbf5b2d36bce97bd10ceda512a05d6421c1b0721b8a0344894c771",
          "sha1": "022576fcbde5c972fbed3d24a314dca77a90db0c",
          "md5": "400d5634e253a75ea7698a632a6120de"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2add-0.6.0-sources.jar",
          "url": "ble-characteristic-u2add-0.6.0-sources.jar",
          "size": 1437,
          "sha512": "49adbed1d6b45f1367fbb414c5a77a43a8a4148dd8677d3a8593e455f8252875c47389e25b35a90b4bb37ba23c5178b75514668e073ba87c82261929a70ce8d7",
          "sha256": "54f3dd0bd752a039c72704b0cd4b5a8937452c82eb3284dbba8ba883e8b27951",
          "sha1": "cf72e7d53e5bf71710aeba2573be5a9a25a3d61f",
          "md5": "f1092a1affb2792945cb0f59bc1cd682"
        }
      ]
    }
  ]
}
