{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-ans-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-ans-android-0.4.0.aar",
          "url": "ble-service-central-ans-android-0.4.0.aar",
          "size": 6567,
          "sha512": "e6e0f74bbaeaec95c7f3183a7753e3a90f7b7822295393403ce56888a839d3da2c3288dc35d7a7ea98971bac2d1a2855c1a847256d70ce479fa7e91236e5843d",
          "sha256": "da9b0761eded3238154a3d85bedacdf2139146b1edd590f0e58c6ef55c6d33f1",
          "sha1": "1024cf7f023374e19d81f113cb6691cfda3df74c",
          "md5": "99a75af2fbba330b23d0539f57a722e3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-ans-android-0.4.0.aar",
          "url": "ble-service-central-ans-android-0.4.0.aar",
          "size": 6567,
          "sha512": "e6e0f74bbaeaec95c7f3183a7753e3a90f7b7822295393403ce56888a839d3da2c3288dc35d7a7ea98971bac2d1a2855c1a847256d70ce479fa7e91236e5843d",
          "sha256": "da9b0761eded3238154a3d85bedacdf2139146b1edd590f0e58c6ef55c6d33f1",
          "sha1": "1024cf7f023374e19d81f113cb6691cfda3df74c",
          "md5": "99a75af2fbba330b23d0539f57a722e3"
        }
      ]
    }
  ]
}
