{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abd",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abd-0.8.8.jar",
          "url": "ble-characteristic-u2abd-0.8.8.jar",
          "size": 3399,
          "sha512": "14bd85895d764a72dbecc00bca57db1bca97c7b7fb873bf5920b6d8e316640fef03bc909347aec2a9f01c8342047fb05679dab285e97ffa217bbe2d093384ebf",
          "sha256": "0c1eb1dd67912e21125cd89186fcf80595456b8c139a77f5b751a342c494ceac",
          "sha1": "20c1b2b5b615bbae7c2a622543cd96e0a5ee7645",
          "md5": "d06de95c03d35d01a52ed09ca2ba96bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abd-0.8.8.jar",
          "url": "ble-characteristic-u2abd-0.8.8.jar",
          "size": 3399,
          "sha512": "14bd85895d764a72dbecc00bca57db1bca97c7b7fb873bf5920b6d8e316640fef03bc909347aec2a9f01c8342047fb05679dab285e97ffa217bbe2d093384ebf",
          "sha256": "0c1eb1dd67912e21125cd89186fcf80595456b8c139a77f5b751a342c494ceac",
          "sha1": "20c1b2b5b615bbae7c2a622543cd96e0a5ee7645",
          "md5": "d06de95c03d35d01a52ed09ca2ba96bd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2abd-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2abd-0.8.8-javadoc.jar",
          "size": 115835,
          "sha512": "85cf4871aac9dd4aa2e15d417246ada1356ce60ad89bec4a18e18013f8b83b5e7fc6c80076bac14ab29c2afc0c110fcd5d66f2e9112fea66d4fa1f9a61a6408f",
          "sha256": "2a43a33bae24ce5920e55b6052dc401a727260c0f60ee7c4782e72ca51aea00a",
          "sha1": "9f142864e37ed28d4dae2d0c81ab26a7542c1e08",
          "md5": "ddbbc41f108561a7c658cb0513720e0e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2abd-0.8.8-sources.jar",
          "url": "ble-characteristic-u2abd-0.8.8-sources.jar",
          "size": 3873,
          "sha512": "1f79b3ab753b7937feb751b69fc378a5a194d37fb58861c492b05c7116a463b95555ef83c3462439589b4c16339019d2a1cc6030ff388349e149bd0f0c30e452",
          "sha256": "c01140b1c04c58090ca37fc35d60f7a0e9602c5c4fa34fbdecb45080a869ccac",
          "sha1": "99ed3b1c9a7f97984afc3794223ebf245093c59e",
          "md5": "e98629d670a47ab24b6be826f953c338"
        }
      ]
    }
  ]
}
