{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-hts-central-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-central-android-0.1.6.aar",
          "url": "ble-service-hts-central-android-0.1.6.aar",
          "size": 7924,
          "sha512": "b8b36f2734f7afa7f5c1fd56ed6d8dce84d03527248ca573209a953e61ce4c80c0e3069f43af8676a99e27f6941028f50df47435fc31395d0f95824e581c73e1",
          "sha256": "fb2f827bc926693d70bf0b505ad93225528943693475eabf468d78b687bd3582",
          "sha1": "35725ff036e9f7e36b6196c6e595cf7115f21b2c",
          "md5": "643f354b47e53f61a5b12936f1c8ecba"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-central-android-0.1.6.aar",
          "url": "ble-service-hts-central-android-0.1.6.aar",
          "size": 7924,
          "sha512": "b8b36f2734f7afa7f5c1fd56ed6d8dce84d03527248ca573209a953e61ce4c80c0e3069f43af8676a99e27f6941028f50df47435fc31395d0f95824e581c73e1",
          "sha256": "fb2f827bc926693d70bf0b505ad93225528943693475eabf468d78b687bd3582",
          "sha1": "35725ff036e9f7e36b6196c6e595cf7115f21b2c",
          "md5": "643f354b47e53f61a5b12936f1c8ecba"
        }
      ]
    }
  ]
}
