{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b8e-android",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8e",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8e-android-0.6.2.aar",
          "url": "ble-characteristic-u2b8e-android-0.6.2.aar",
          "size": 3030,
          "sha512": "3466cc5cd3cdeb2cef65461c6244ef1e61b93ceecab708d79fca887fffa1d7c39844f17a59bd805f17f604be8264c8dbf894cb2138ac4c93e7a0f5ab2c368987",
          "sha256": "ec68dfd349e385664ec1b5872fbd7bbe94f6446199bb01e32c015c62fcc42569",
          "sha1": "ec13a4a6477d174fafa1e1f7f30e4331088e9359",
          "md5": "7d12d5e01a45de9b7667d8f4711be486"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8e",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8e-android-0.6.2.aar",
          "url": "ble-characteristic-u2b8e-android-0.6.2.aar",
          "size": 3030,
          "sha512": "3466cc5cd3cdeb2cef65461c6244ef1e61b93ceecab708d79fca887fffa1d7c39844f17a59bd805f17f604be8264c8dbf894cb2138ac4c93e7a0f5ab2c368987",
          "sha256": "ec68dfd349e385664ec1b5872fbd7bbe94f6446199bb01e32c015c62fcc42569",
          "sha1": "ec13a4a6477d174fafa1e1f7f30e4331088e9359",
          "md5": "7d12d5e01a45de9b7667d8f4711be486"
        }
      ]
    }
  ]
}
