{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5f",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.6.jar",
          "url": "ble-characteristic-u2a5f-0.8.6.jar",
          "size": 1480,
          "sha512": "bca52dbe4b648ea0d80b0c83e73a9dd18fb25662dbb003e7be0db714abb20cfe3ca67b484cb31e15f61de6b16edbcec3b6a5b702117812541f9dbcc0e390e2fa",
          "sha256": "c9139e1eb5e5662c8155d7e3340e1380e735c0790f7235d04bb6882ab3deb6be",
          "sha1": "5e4540d0cea4e5bf2197e179fc6fbfc13c275956",
          "md5": "c5e1858b6486f8a3a4445f08267a380e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.6.jar",
          "url": "ble-characteristic-u2a5f-0.8.6.jar",
          "size": 1480,
          "sha512": "bca52dbe4b648ea0d80b0c83e73a9dd18fb25662dbb003e7be0db714abb20cfe3ca67b484cb31e15f61de6b16edbcec3b6a5b702117812541f9dbcc0e390e2fa",
          "sha256": "c9139e1eb5e5662c8155d7e3340e1380e735c0790f7235d04bb6882ab3deb6be",
          "sha1": "5e4540d0cea4e5bf2197e179fc6fbfc13c275956",
          "md5": "c5e1858b6486f8a3a4445f08267a380e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a5f-0.8.6-javadoc.jar",
          "size": 107249,
          "sha512": "1646016020cac5c346ac7e70b8eb98c39a3a3d61c8e63d61d8fe47b0192e864b29ce5d21c9f635b9f238389e25a03c34bf493f8e501e0d684cfc9c0f99226afc",
          "sha256": "fb35a675e45138da69771560cef0d6a9823955583d1819dbf4972d3a9f97cbb1",
          "sha1": "e8f921ead0ed7f67e5626271c338702054dfbfd1",
          "md5": "9ba1ce256196b1f3648fcb1ac1079e92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a5f-0.8.6-sources.jar",
          "size": 1477,
          "sha512": "20b552309885b4f1e5a798405ce252854c1c42c3648f0479007da1eb1ff462211ef4831366db32d6e944badbf82d93d8260f84051807140ac1d53afdee8c6d42",
          "sha256": "791740ac83d1ada7b401c260561e60989e2cd7fe8b2f29866509877987b1f5d1",
          "sha1": "22233800bfdfca737715f5b8e8ba7fc61abed3a3",
          "md5": "43bd60c7e8be184f81e46a809a802845"
        }
      ]
    }
  ]
}
