{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-rtus-central-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-central-android-0.1.2.aar",
          "url": "ble-service-rtus-central-android-0.1.2.aar",
          "size": 3730,
          "sha512": "2847b490a1071b7890b81bd439f3b51f18e44dc94d4007fbe7d7a2c56e454e7c0da8cfc64dddef8c6d6d1ac64d12d4dc3ef89a04bc9954375a66c38754c32878",
          "sha256": "1773bb1c01be21c2280b31748ede60a29b311928df6ee962f6b456cb47e7f6c9",
          "sha1": "88e3b72d582b3adce3a69df6421a6c42ee1f6450",
          "md5": "d06aae82dcd243ac3b9afaee4f8303d9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-central-android-0.1.2.aar",
          "url": "ble-service-rtus-central-android-0.1.2.aar",
          "size": 3730,
          "sha512": "2847b490a1071b7890b81bd439f3b51f18e44dc94d4007fbe7d7a2c56e454e7c0da8cfc64dddef8c6d6d1ac64d12d4dc3ef89a04bc9954375a66c38754c32878",
          "sha256": "1773bb1c01be21c2280b31748ede60a29b311928df6ee962f6b456cb47e7f6c9",
          "sha1": "88e3b72d582b3adce3a69df6421a6c42ee1f6450",
          "md5": "d06aae82dcd243ac3b9afaee4f8303d9"
        }
      ]
    }
  ]
}
