{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-anp-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ans-android",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-anp-android-0.8.11.aar",
          "url": "ble-profile-peripheral-anp-android-0.8.11.aar",
          "size": 6820,
          "sha512": "b6f11d2ef2e9f2e7fc879657a55b6272a2018edcf8ddeef12f8e02d654ed1917f525aed69e240a8e9779140a1fee80959783e4db2060d1c40fe596e70182832d",
          "sha256": "dad935b946dcbde524ba4e4a96940a4b4e528dd2da3099a2bdac744ddc52162c",
          "sha1": "253d21700dd137ef03a03812dad1efa09b415a3a",
          "md5": "901eb7a4ebdf33f99720ead89d8812e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ans-android",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-anp-android-0.8.11.aar",
          "url": "ble-profile-peripheral-anp-android-0.8.11.aar",
          "size": 6820,
          "sha512": "b6f11d2ef2e9f2e7fc879657a55b6272a2018edcf8ddeef12f8e02d654ed1917f525aed69e240a8e9779140a1fee80959783e4db2060d1c40fe596e70182832d",
          "sha256": "dad935b946dcbde524ba4e4a96940a4b4e528dd2da3099a2bdac744ddc52162c",
          "sha1": "253d21700dd137ef03a03812dad1efa09b415a3a",
          "md5": "901eb7a4ebdf33f99720ead89d8812e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-anp-android-0.8.11-sources.jar",
          "url": "ble-profile-peripheral-anp-android-0.8.11-sources.jar",
          "size": 4258,
          "sha512": "b20951e59fe4496b5e7a4110db57427363d78a82666ba39bf415453ab8844ae8037729511d1f98f5d955ab901e2f832a0f45c46bdbca0fc607e2396b390ddf29",
          "sha256": "32032893dc2b455b36c5cac7e033990914162d4cbeeff9fc564a6e8d859fe834",
          "sha1": "61dae1b454f6b5c7a6552e7e671949db2f7a70f4",
          "md5": "3d1da8c93c6fe1eda5f0c109788af60e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-anp-android-0.8.11-javadoc.jar",
          "url": "ble-profile-peripheral-anp-android-0.8.11-javadoc.jar",
          "size": 290832,
          "sha512": "4fa5d8265d759b536953674ffd5cfb56198f4b8c629501ee7602b0e4b07d2467ca50382d3cb46041c82ac39f6a9b4f1f5df127088ee56e005adc97c8de7afe5d",
          "sha256": "e712a8e6f87b1961eba8ea298e4417773571ff258109207bb37f783060480c9f",
          "sha1": "576f6604f485ee5457af1390b257f61da1dfee99",
          "md5": "78a00a79f1dec05e324279bbf7e65a9a"
        }
      ]
    }
  ]
}
