{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab7-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab7",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-android-0.4.2.aar",
          "url": "ble-characteristic-u2ab7-android-0.4.2.aar",
          "size": 3116,
          "sha512": "24d10be1f0571ccde337a2fe4711353a5b5d2ec2c7e39bbce8fbc8706485145440c41edf2a35a3a54592d29f63e6852fb92c4de8ea561c50792fd8af8295891f",
          "sha256": "bfac64d1b97b0bd1030d296d06fe38050dffac5fdd874544699d1ecb5ac1f883",
          "sha1": "c4024355ad46e12f3b4d421720654c56e006c37c",
          "md5": "050a6a29f0dd22544de1716aa504e461"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab7",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-android-0.4.2.aar",
          "url": "ble-characteristic-u2ab7-android-0.4.2.aar",
          "size": 3116,
          "sha512": "24d10be1f0571ccde337a2fe4711353a5b5d2ec2c7e39bbce8fbc8706485145440c41edf2a35a3a54592d29f63e6852fb92c4de8ea561c50792fd8af8295891f",
          "sha256": "bfac64d1b97b0bd1030d296d06fe38050dffac5fdd874544699d1ecb5ac1f883",
          "sha1": "c4024355ad46e12f3b4d421720654c56e006c37c",
          "md5": "050a6a29f0dd22544de1716aa504e461"
        }
      ]
    }
  ]
}
