{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc6",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.6.jar",
          "url": "ble-characteristic-u2bc6-0.8.6.jar",
          "size": 1456,
          "sha512": "92e230567c5df45fc6d879c80208df9478317e676cafa609d9a81114396f786f08f78e56c73241b2d4de9a354fe54273e4e00dac1e1b73725f200c5f12775fde",
          "sha256": "5125215c9c420e20c57fb8878842d5e9c1ed00b6d1e143495eddbf17ddf5a8cc",
          "sha1": "bb4173fb5f15a5a35aec8166b8d2330f6c30f6c0",
          "md5": "4074c17b6124f9f939914cfd9e919cc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.6.jar",
          "url": "ble-characteristic-u2bc6-0.8.6.jar",
          "size": 1456,
          "sha512": "92e230567c5df45fc6d879c80208df9478317e676cafa609d9a81114396f786f08f78e56c73241b2d4de9a354fe54273e4e00dac1e1b73725f200c5f12775fde",
          "sha256": "5125215c9c420e20c57fb8878842d5e9c1ed00b6d1e143495eddbf17ddf5a8cc",
          "sha1": "bb4173fb5f15a5a35aec8166b8d2330f6c30f6c0",
          "md5": "4074c17b6124f9f939914cfd9e919cc0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2bc6-0.8.6-javadoc.jar",
          "size": 107166,
          "sha512": "d5c432bba951ad0fc7021630e38b13fb9a5bea890c7c5c7739056351f634e23563494ab87570e36a3eca3bbb42ab2b9f343172651baf5be438e79697de04d0f5",
          "sha256": "b573bfce25510e5b0a8608b0c1ffc83f188a63f16dd6612e434ee6254e8c8be4",
          "sha1": "c531e8d7a4563e7797ba87cd43139467db241e6f",
          "md5": "2295206dabd474e968c66a06fbea72ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bc6-0.8.6-sources.jar",
          "size": 1435,
          "sha512": "2d3ac17d692ec15564756136bc13d62d8ad54f29930eb990367ec7e7bbf8cef0b82f2216a9d69ec692874d19d220993ec84965e3f4b70b93b7679dedca5e6bd6",
          "sha256": "fbb8e4eddac6bb01ea02e6e1480cc7cacb1c52b49441ca3eb5c86e0bf6392809",
          "sha1": "3b8f0d57ef9133b2b36b795b33435d3fa6383f46",
          "md5": "f321c4521b958eac4a31bef698295c98"
        }
      ]
    }
  ]
}
