{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9c-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.2.5.aar",
          "url": "ble-characteristic-u2a9c-android-0.2.5.aar",
          "size": 5519,
          "sha512": "4e9604e0e974f84d03953fd5f9217786dfc9cfbc395b25b475b5e98f6638f3effc27693cff1f0a2b841e3baccd55d238bf6ed2dc94e3ed21629ac3c1a91d34cb",
          "sha256": "e92740d1263d57b943db3c86acab09cd649d113e9be62fc11b1880e013cd2b8c",
          "sha1": "c7f335eadb855e8a63e03439a6ae311be886367f",
          "md5": "00225d66b93b86bc82b597e1995eec4d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.2.5.aar",
          "url": "ble-characteristic-u2a9c-android-0.2.5.aar",
          "size": 5519,
          "sha512": "4e9604e0e974f84d03953fd5f9217786dfc9cfbc395b25b475b5e98f6638f3effc27693cff1f0a2b841e3baccd55d238bf6ed2dc94e3ed21629ac3c1a91d34cb",
          "sha256": "e92740d1263d57b943db3c86acab09cd649d113e9be62fc11b1880e013cd2b8c",
          "sha1": "c7f335eadb855e8a63e03439a6ae311be886367f",
          "md5": "00225d66b93b86bc82b597e1995eec4d"
        }
      ]
    }
  ]
}
