{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9e-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.4.2.aar",
          "url": "ble-characteristic-u2a9e-android-0.4.2.aar",
          "size": 3240,
          "sha512": "5f9045762bb0ea0127763de17f39eaeaabe3e4754300b083f5bddfd8e6e7709023fe0bbbf9bb7372d7d20ab037644fc8435069fd5072742e0a848743d63ed7bf",
          "sha256": "74f74a421affe02061ced3de5b8a4dfaf05624a0556552b7727504ef009dc758",
          "sha1": "023733398a95018026407c01f1c0da8d550c8111",
          "md5": "9352ae95850723c1342714aabd63efaa"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.4.2.aar",
          "url": "ble-characteristic-u2a9e-android-0.4.2.aar",
          "size": 3240,
          "sha512": "5f9045762bb0ea0127763de17f39eaeaabe3e4754300b083f5bddfd8e6e7709023fe0bbbf9bb7372d7d20ab037644fc8435069fd5072742e0a848743d63ed7bf",
          "sha256": "74f74a421affe02061ced3de5b8a4dfaf05624a0556552b7727504ef009dc758",
          "sha1": "023733398a95018026407c01f1c0da8d550c8111",
          "md5": "9352ae95850723c1342714aabd63efaa"
        }
      ]
    }
  ]
}
