{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-uds-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7e-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a81-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a82-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a83-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a84-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a86-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a87-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a88-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8a-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8e-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8f-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a94-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a95-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a96-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a97-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a98-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a99-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9a-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa2-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-uds-android-0.1.1.aar",
          "url": "ble-service-uds-android-0.1.1.aar",
          "size": 1203,
          "sha512": "d21a409ae6b3b04ced868f0abe3b8fa8f6b613c25081b563a6ca071c065c0f250a01cb91f68d7cd74485a34a54fa810499ee19cfc98d70f1206e288d9f20cb8e",
          "sha256": "daca533ce3d3867f69a4bdd3c970af020fbe50276242e6c7d6ec1bb46c1ccb84",
          "sha1": "ac8620e4bf2e268422b7e92b7ced280c8525634a",
          "md5": "ffebe917a45aec823173ac8c0580ff0b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7e-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a81-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a82-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a83-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a84-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a86-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a87-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a88-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8a-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8e-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8f-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a94-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a95-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a96-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a97-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a98-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a99-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9a-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa2-android",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-uds-android-0.1.1.aar",
          "url": "ble-service-uds-android-0.1.1.aar",
          "size": 1203,
          "sha512": "d21a409ae6b3b04ced868f0abe3b8fa8f6b613c25081b563a6ca071c065c0f250a01cb91f68d7cd74485a34a54fa810499ee19cfc98d70f1206e288d9f20cb8e",
          "sha256": "daca533ce3d3867f69a4bdd3c970af020fbe50276242e6c7d6ec1bb46c1ccb84",
          "sha1": "ac8620e4bf2e268422b7e92b7ced280c8525634a",
          "md5": "ffebe917a45aec823173ac8c0580ff0b"
        }
      ]
    }
  ]
}
