{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-cts-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-cts-android-0.4.6.aar",
          "url": "ble-service-peripheral-cts-android-0.4.6.aar",
          "size": 9850,
          "sha512": "c1abe098cecded4556bff42541bf64694d99f58e4aecbfcdcabcdbbc822ebb4c6c84cb50debe53fda4ec2790d323488a706d701bfacad77b561992f81f81fa8c",
          "sha256": "93fda374a2751b112df5dc5a0821b6e080cbd7581a76d1ac40286651b03856a6",
          "sha1": "b4a58b7ce338602349ab04330e97183b192220b2",
          "md5": "5a5f5e370fa7606f3af04319eeb732e5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-cts-android-0.4.6.aar",
          "url": "ble-service-peripheral-cts-android-0.4.6.aar",
          "size": 9850,
          "sha512": "c1abe098cecded4556bff42541bf64694d99f58e4aecbfcdcabcdbbc822ebb4c6c84cb50debe53fda4ec2790d323488a706d701bfacad77b561992f81f81fa8c",
          "sha256": "93fda374a2751b112df5dc5a0821b6e080cbd7581a76d1ac40286651b03856a6",
          "sha1": "b4a58b7ce338602349ab04330e97183b192220b2",
          "md5": "5a5f5e370fa7606f3af04319eeb732e5"
        }
      ]
    }
  ]
}
