{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-protocol",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-protocol-0.6.2.jar",
          "url": "ble-core-constants-protocol-0.6.2.jar",
          "size": 2873,
          "sha512": "0258311cf23a4e822ababfc18fe714d43553b691fc4624858e1020860bd55188cf7e038a2bab513ee52482ae0c3c655cc422e36204c2fa59b97196ef347ba855",
          "sha256": "b7cb6701af2ce65ff7b9ffe0b5a88ceb8a35ceddacb621a596703fff4972f7b5",
          "sha1": "df1dd4e07ee1097e8e32ed6bb94e99cc9b7d2dc7",
          "md5": "cc7eaf9874f028b0851701f84bb97732"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-protocol-0.6.2.jar",
          "url": "ble-core-constants-protocol-0.6.2.jar",
          "size": 2873,
          "sha512": "0258311cf23a4e822ababfc18fe714d43553b691fc4624858e1020860bd55188cf7e038a2bab513ee52482ae0c3c655cc422e36204c2fa59b97196ef347ba855",
          "sha256": "b7cb6701af2ce65ff7b9ffe0b5a88ceb8a35ceddacb621a596703fff4972f7b5",
          "sha1": "df1dd4e07ee1097e8e32ed6bb94e99cc9b7d2dc7",
          "md5": "cc7eaf9874f028b0851701f84bb97732"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-protocol-0.6.2-javadoc.jar",
          "url": "ble-core-constants-protocol-0.6.2-javadoc.jar",
          "size": 108945,
          "sha512": "500a75413da148da1876726719fb4d36e0967136124d9b7a9b26e58dc3242ea529ffea9a8cadbee9d3aeb050a63e72f24c88ef7c3e0fb6ff479e9ea2c3eab2b7",
          "sha256": "c5c037e5b73bbd3eb92d6e84f43fc8bf2ffe4f5d3a3e779b41c130ac505a5b12",
          "sha1": "20edc012db020e08cf7393bac2952a3ee473295a",
          "md5": "ae494a3b4fedfdd72af60c36db9c0011"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-protocol-0.6.2-sources.jar",
          "url": "ble-core-constants-protocol-0.6.2-sources.jar",
          "size": 1476,
          "sha512": "8bb35b332aee9a8510ebd677531e8e69d664b80d92a3f18e6ebca263cb550f9f4e299bbc6b5961db0d762b1ddc0521b649a32c809940211d49d82c3d4d45f3a3",
          "sha256": "3e0e40605221ecd184dca508cb7decdaaf0fe193d846423d3e7217fe425310fc",
          "sha1": "a5ce94b9a6cafa5234b534eb4f3ad8331648fc37",
          "md5": "09cb97aa7584b02a82cb213c87e2302c"
        }
      ]
    }
  ]
}
