{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b85-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b85",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b85-android-0.8.7.aar",
          "url": "ble-characteristic-u2b85-android-0.8.7.aar",
          "size": 3177,
          "sha512": "6c84b4e8dab7bb10dea5a792f289ae5c6aab5e9a7219a5f35d5311db8ad3894f235cc0adbfb73f41e1417d92a512fccfe5ab37e169888b32e2134d41085cf4e3",
          "sha256": "5a34869685bb2956950bd528340870b61f2964a4ad002ee4eae392352a5ba181",
          "sha1": "4704cfd94b213d0505c51310a47b665650fa21b5",
          "md5": "0795fce10c56571bca2fffa6c89df50b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b85",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b85-android-0.8.7.aar",
          "url": "ble-characteristic-u2b85-android-0.8.7.aar",
          "size": 3177,
          "sha512": "6c84b4e8dab7bb10dea5a792f289ae5c6aab5e9a7219a5f35d5311db8ad3894f235cc0adbfb73f41e1417d92a512fccfe5ab37e169888b32e2134d41085cf4e3",
          "sha256": "5a34869685bb2956950bd528340870b61f2964a4ad002ee4eae392352a5ba181",
          "sha1": "4704cfd94b213d0505c51310a47b665650fa21b5",
          "md5": "0795fce10c56571bca2fffa6c89df50b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b85-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b85-android-0.8.7-sources.jar",
          "size": 2175,
          "sha512": "6e537c95c88a35599cce5bf5f38b0146a24a1d2229ce72c510ea593b0f7622994b873e8543fee0faef8ebd2a54ad918157f4da979ef927caecc6f50a33a5d492",
          "sha256": "6b5960559b905bcb51852168054a9b1d4e220725eb45342d20c89009e444a3ce",
          "sha1": "b4ef4633b41e9f664b017efa542445b4f7db7376",
          "md5": "867cdffc5dd0558adde037d60733742e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b85-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b85-android-0.8.7-javadoc.jar",
          "size": 270612,
          "sha512": "1ebb882ce2948d077a474139882ef8130d6f98fe0d76e7660129aad2c32f04395b746799af7ffee2a63eb2da26cad995c709bd607c2be2aa44a6238c43ccc8bd",
          "sha256": "3fb22b7d7571aaf67c60ca61520aba133cc68d6fa7f0bbd3186d254b88fb4417",
          "sha1": "daae906eb19f1d2715825f4a9f778145963c3c32",
          "md5": "0d6b53fd81e5af62ee635219ac016310"
        }
      ]
    }
  ]
}
