{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a3f-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a3f",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a3f-android-0.2.7.aar",
          "url": "ble-characteristic-u2a3f-android-0.2.7.aar",
          "size": 3076,
          "sha512": "7a161cdbc9dcd6d101c6c7f78bd140e4d4416bca52c4204663ec845f3eda0cf85c4f0d81d7d54231f3a554f5757696761cbf5ff26c8a3cc403b5eb1f4a511648",
          "sha256": "4106ad4ecd11e80edfd849d60d5ff00255e0764c9118729538a158368c6f680f",
          "sha1": "d73ad4ce04ceaf96d6d63922505a4ebbb0126c10",
          "md5": "926f96e03336d5ad30f1c26d0963a056"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a3f",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a3f-android-0.2.7.aar",
          "url": "ble-characteristic-u2a3f-android-0.2.7.aar",
          "size": 3076,
          "sha512": "7a161cdbc9dcd6d101c6c7f78bd140e4d4416bca52c4204663ec845f3eda0cf85c4f0d81d7d54231f3a554f5757696761cbf5ff26c8a3cc403b5eb1f4a511648",
          "sha256": "4106ad4ecd11e80edfd849d60d5ff00255e0764c9118729538a158368c6f680f",
          "sha1": "d73ad4ce04ceaf96d6d63922505a4ebbb0126c10",
          "md5": "926f96e03336d5ad30f1c26d0963a056"
        }
      ]
    }
  ]
}
