{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2904",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2904-0.8.6.jar",
          "url": "ble-descriptor-u2904-0.8.6.jar",
          "size": 3299,
          "sha512": "eb28a363b99933661379bb68542ddb120c909da5c952262e1cb978520b20dd9af8b4a2ec051a1c0393d6e1c08e8f3159a8b5f5b547bb4dfe993ef2e88d1bddf6",
          "sha256": "94878cc1a9cbb6c83de9390fcc5048597539d45ef6870f95981c359371ba5a2b",
          "sha1": "b442fbf3d11afbba534e050d48dc3b7bed4bde21",
          "md5": "b569dbdced26348dc9e9333afee118bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2904-0.8.6.jar",
          "url": "ble-descriptor-u2904-0.8.6.jar",
          "size": 3299,
          "sha512": "eb28a363b99933661379bb68542ddb120c909da5c952262e1cb978520b20dd9af8b4a2ec051a1c0393d6e1c08e8f3159a8b5f5b547bb4dfe993ef2e88d1bddf6",
          "sha256": "94878cc1a9cbb6c83de9390fcc5048597539d45ef6870f95981c359371ba5a2b",
          "sha1": "b442fbf3d11afbba534e050d48dc3b7bed4bde21",
          "md5": "b569dbdced26348dc9e9333afee118bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2904-0.8.6-javadoc.jar",
          "url": "ble-descriptor-u2904-0.8.6-javadoc.jar",
          "size": 114531,
          "sha512": "1a0f1eb6f31298d1c3a381d26f43077f765435699db97e48cf0025711cf2f8a63dcc8adbd01ba33d8a7d04308789009caecc283221a79b34c4df97e61004f013",
          "sha256": "f57bec5696133535047b9942e96a4222f78b235d10affc789a652c594f67445c",
          "sha1": "5140a8a302a68417ce9b763b6c907a5167cc5753",
          "md5": "66914890cbbef7d12b5328fe29e4ecf6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2904-0.8.6-sources.jar",
          "url": "ble-descriptor-u2904-0.8.6-sources.jar",
          "size": 3023,
          "sha512": "f5153c450b473389791c36e7a8489769ce390951bf4df5fec5aa313862847155d7664b197020a7bfef6d2c71ff726c90539b2bbdc4ddf7d78d5a6204fbb66297",
          "sha256": "263397d29eeb90bc70d4617d57af860ea0adc74da5f405fd2c6190d615c76da6",
          "sha1": "d6276659922d0357505114a3540ba042dc6772f4",
          "md5": "ff931ac2300985c18ce5554f792c5dad"
        }
      ]
    }
  ]
}
