{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa7-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa7",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa7-android-0.8.8.aar",
          "url": "ble-characteristic-u2aa7-android-0.8.8.aar",
          "size": 3138,
          "sha512": "668c6870a83d12c314332cad783afb5ee5185072619a31e66c82f72869d83a007e3dd19092b8adce6188b8cacd1e797671f4af90866b8513e45841027c5d9881",
          "sha256": "7fcb8a0a5808b4a44c02f032dfe6d344ff107a75cb69fa46dbf48650754707b1",
          "sha1": "60f024f0dd6e5dbb16f834b388e7c0849a9d5e81",
          "md5": "2e786a4d8da1575dc8588ed68549883d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa7",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa7-android-0.8.8.aar",
          "url": "ble-characteristic-u2aa7-android-0.8.8.aar",
          "size": 3138,
          "sha512": "668c6870a83d12c314332cad783afb5ee5185072619a31e66c82f72869d83a007e3dd19092b8adce6188b8cacd1e797671f4af90866b8513e45841027c5d9881",
          "sha256": "7fcb8a0a5808b4a44c02f032dfe6d344ff107a75cb69fa46dbf48650754707b1",
          "sha1": "60f024f0dd6e5dbb16f834b388e7c0849a9d5e81",
          "md5": "2e786a4d8da1575dc8588ed68549883d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa7-android-0.8.8-sources.jar",
          "url": "ble-characteristic-u2aa7-android-0.8.8-sources.jar",
          "size": 2142,
          "sha512": "4de9eedf5201595673b42c67bb5765ab3ef907ee703992378b24f6600257d8674cf298c936b0fd0f247557826adf7cfacbc62c1826a30c118b381bffc6103144",
          "sha256": "322d5ecd703651acb40bb6d85dceee05a4a4a956599633dd13fd3c7c7ad6ce64",
          "sha1": "fc8a9e26432920c91c91d5c4b8f24e033a51c727",
          "md5": "dc1ddd5609654477eb7240abfe00ae7e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa7-android-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2aa7-android-0.8.8-javadoc.jar",
          "size": 270503,
          "sha512": "28dbd2a91c684e09830737403e2459d679eb489be1cd1f7a3e21695efdcc241ef71d9c268a5591724dbcb8f23921492a7736268b3467537e1a674325ff80d676",
          "sha256": "14941be7f175ac77864c286115eb30f6228803dcdb83855e4def5988a6400b63",
          "sha1": "014160de58c9c9596ea6bf121b944421f3e4e322",
          "md5": "c72a337dc1ce40b853e9fcfcea155373"
        }
      ]
    }
  ]
}
