{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-htp-peripheral-android",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-htp-peripheral-android-0.1.10.aar",
          "url": "ble-profile-htp-peripheral-android-0.1.10.aar",
          "size": 5140,
          "sha512": "6777c4e7610a4a974f5dc739a01c09b8442347cdedb60c68783e0428084a61fd9f7917f245333c261bd7427b2721391aac14163da5f8a5a06d74034be82500ce",
          "sha256": "15d1e25cb6a59585213d1985cacbb9850dc10f76e1fa969644465897b72853cd",
          "sha1": "8d69d58f8577a36a23777452a5784205786339d5",
          "md5": "7089bd7ccb3eb68c24ff5f381dab935a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-htp-peripheral-android-0.1.10.aar",
          "url": "ble-profile-htp-peripheral-android-0.1.10.aar",
          "size": 5140,
          "sha512": "6777c4e7610a4a974f5dc739a01c09b8442347cdedb60c68783e0428084a61fd9f7917f245333c261bd7427b2721391aac14163da5f8a5a06d74034be82500ce",
          "sha256": "15d1e25cb6a59585213d1985cacbb9850dc10f76e1fa969644465897b72853cd",
          "sha1": "8d69d58f8577a36a23777452a5784205786339d5",
          "md5": "7089bd7ccb3eb68c24ff5f381dab935a"
        }
      ]
    }
  ]
}
