{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a77",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "bo2m2bzyvfgbjfmoy4levvs3tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.2.1.jar",
          "url": "ble-characteristic-u2a77-0.2.1.jar",
          "size": 1845,
          "sha512": "1b926752d8cfcd3d976336e0e30daec9dde78dab33e05f077950b390c06a35542b25d9adbff9c72599207c5dc8986cdcd471b778820429d24da8651c983e3b22",
          "sha256": "68c193929bd4c9abd77a35a172e035d3655627ab90ff5b91acf0f08b84e273be",
          "sha1": "b15a3a69c27ea37108e644788c0310ef66cc740b",
          "md5": "63199d2728626c3e4abb44e7bae5d16c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.2.1.jar",
          "url": "ble-characteristic-u2a77-0.2.1.jar",
          "size": 1845,
          "sha512": "1b926752d8cfcd3d976336e0e30daec9dde78dab33e05f077950b390c06a35542b25d9adbff9c72599207c5dc8986cdcd471b778820429d24da8651c983e3b22",
          "sha256": "68c193929bd4c9abd77a35a172e035d3655627ab90ff5b91acf0f08b84e273be",
          "sha1": "b15a3a69c27ea37108e644788c0310ef66cc740b",
          "md5": "63199d2728626c3e4abb44e7bae5d16c"
        }
      ]
    }
  ]
}
