{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3f",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.8.6.jar",
          "url": "ble-characteristic-u2b3f-0.8.6.jar",
          "size": 1515,
          "sha512": "fb5edf1375d81a12576904a9fdb5cc968f6e506f86f6c3f595e4eca3c1d13f0222506530ad0446db4d26d452018438fc382ec57033a7759bb30257df911aee59",
          "sha256": "040c2205354dff7c033b905db111af1e0787fc98b30b8685ee5448d3f7705e26",
          "sha1": "60beb53b3c3815ea5174d33712fe9ea8a98e08d9",
          "md5": "cc2f57276b294683445618c499c74b17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.8.6.jar",
          "url": "ble-characteristic-u2b3f-0.8.6.jar",
          "size": 1515,
          "sha512": "fb5edf1375d81a12576904a9fdb5cc968f6e506f86f6c3f595e4eca3c1d13f0222506530ad0446db4d26d452018438fc382ec57033a7759bb30257df911aee59",
          "sha256": "040c2205354dff7c033b905db111af1e0787fc98b30b8685ee5448d3f7705e26",
          "sha1": "60beb53b3c3815ea5174d33712fe9ea8a98e08d9",
          "md5": "cc2f57276b294683445618c499c74b17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2b3f-0.8.6-javadoc.jar",
          "size": 107342,
          "sha512": "4667294d28c594aa260b6bf697fc8f61313e77da0544bda25b801a8a799b336dff1e8ec7698d81d37278ccbfbadbb0cac01b5e959430983a82de2fd4c6f2c779",
          "sha256": "607fa2d0cab6b9af098b055e9ef181c32c1ae53debf6d78ac8c3c84621576e07",
          "sha1": "a342d5729ad056ee9674ec64fd179aa6829a994c",
          "md5": "99dac3be9fb1adcdc6e9baebc72941a9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b3f-0.8.6-sources.jar",
          "size": 1515,
          "sha512": "090253c9d8c0efdba4f9c2e652f9741ea1dee0d6e87e99273d22384088de9cc2666f3d05288775ecf63fdb7fe4aa90812a7e950a8a5bb03d76db01c65984acb1",
          "sha256": "7eb51a8ac8a7eee26998bd363f3d9ad07a13724855b737d7f23c871722bd875d",
          "sha1": "f921d8db8ba86d436704af8b99dccc197d27a0dd",
          "md5": "a8c838e4ece8335644f3f03eefe4fb1d"
        }
      ]
    }
  ]
}
