{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8d-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-android-0.4.4.aar",
          "url": "ble-characteristic-u2a8d-android-0.4.4.aar",
          "size": 3103,
          "sha512": "9d7d38f5fdc1b0868fbea969ff0caa4853e31e4de6fcc5cf36bf29ec1e44f8b78701194175d7502b314101aac65cf4ef4ca52d779104cb3d6df570f039cf1ee3",
          "sha256": "9790039d9ef23d3a9b673c5aee210eea4a066684e9c482b50db367a58b009edc",
          "sha1": "cf85a6f2cceab085543032486a60c8fa6061ae56",
          "md5": "f28a64813154338134fbb82fc8a7ff54"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-android-0.4.4.aar",
          "url": "ble-characteristic-u2a8d-android-0.4.4.aar",
          "size": 3103,
          "sha512": "9d7d38f5fdc1b0868fbea969ff0caa4853e31e4de6fcc5cf36bf29ec1e44f8b78701194175d7502b314101aac65cf4ef4ca52d779104cb3d6df570f039cf1ee3",
          "sha256": "9790039d9ef23d3a9b673c5aee210eea4a066684e9c482b50db367a58b009edc",
          "sha1": "cf85a6f2cceab085543032486a60c8fa6061ae56",
          "md5": "f28a64813154338134fbb82fc8a7ff54"
        }
      ]
    }
  ]
}
