{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6d-android",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6d",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-android-0.8.2.aar",
          "url": "ble-characteristic-u2a6d-android-0.8.2.aar",
          "size": 3046,
          "sha512": "3e99775a7b5b2f4c3ef7a1cb3900dd3a52e76c2a6c933ee330ee5e8a43a7a48ddce0d4f90221fb1bb51dbcd5c9143c6155492d0c52a0ee95c10653da0a8b39ff",
          "sha256": "e21a2375661b112232b7242d9ee901afa157806a91b76cbe6195fa682b64ecee",
          "sha1": "dce585c4f275b89af35a33580956dcbb6b553fd6",
          "md5": "3011249865c3aaf6df2c68274901c66f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6d",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-android-0.8.2.aar",
          "url": "ble-characteristic-u2a6d-android-0.8.2.aar",
          "size": 3046,
          "sha512": "3e99775a7b5b2f4c3ef7a1cb3900dd3a52e76c2a6c933ee330ee5e8a43a7a48ddce0d4f90221fb1bb51dbcd5c9143c6155492d0c52a0ee95c10653da0a8b39ff",
          "sha256": "e21a2375661b112232b7242d9ee901afa157806a91b76cbe6195fa682b64ecee",
          "sha1": "dce585c4f275b89af35a33580956dcbb6b553fd6",
          "md5": "3011249865c3aaf6df2c68274901c66f"
        }
      ]
    }
  ]
}
