{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad4",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad4-0.8.7.jar",
          "url": "ble-characteristic-u2ad4-0.8.7.jar",
          "size": 2092,
          "sha512": "dbbf57ff89fcc6b1e90844d757bc8c602f757350638082a538bd3b6e2902207431bac4ba03de45552be9fd6e8d8fd627a3e55965f15b91523335ebb257a27bb0",
          "sha256": "0ecad1822e722f83b26041fd2c3d352e7fd10465701c2a3ef4a3ed3ceff512ee",
          "sha1": "2c31aad553100fd707c533f8c86da71f161ba26e",
          "md5": "ff93571c581a5532305a0021b548e51c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad4-0.8.7.jar",
          "url": "ble-characteristic-u2ad4-0.8.7.jar",
          "size": 2092,
          "sha512": "dbbf57ff89fcc6b1e90844d757bc8c602f757350638082a538bd3b6e2902207431bac4ba03de45552be9fd6e8d8fd627a3e55965f15b91523335ebb257a27bb0",
          "sha256": "0ecad1822e722f83b26041fd2c3d352e7fd10465701c2a3ef4a3ed3ceff512ee",
          "sha1": "2c31aad553100fd707c533f8c86da71f161ba26e",
          "md5": "ff93571c581a5532305a0021b548e51c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad4-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2ad4-0.8.7-javadoc.jar",
          "size": 110070,
          "sha512": "c2a300e9ba1949ad9153fe2c29b8f95ad1d2b47b54275d4e25422951c190b2a76e41b5a5acdf136fa51e0a46fb4a0b7f94ace6d9b0ae3365f11ed90bd96930ba",
          "sha256": "c9fb30720532078eab2465bb8f1cad49a7b49611ac83cf970f222544ffc0ee14",
          "sha1": "89bf165db194d8053ad39f00d4d91a0d01a72041",
          "md5": "86041cd4872b0710b208df14818a713c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad4-0.8.7-sources.jar",
          "url": "ble-characteristic-u2ad4-0.8.7-sources.jar",
          "size": 1914,
          "sha512": "5d2fe52ff9b79e9bdc0440e630c3d2b36f3787a315fc8f0dce40eb07166cacedfa955e981c898b9f6252e7da23cdc930260e84570ecb4443e5d7e729b9c9b0bb",
          "sha256": "db412ff323bd2435a08999c213ed73314dfc618e9f2581920cb48ec89d8bca60",
          "sha1": "bb0fd81663a579e5cd58668d854c0bd265494f48",
          "md5": "b65cfd84f0f0f833a46c727e6e9ae125"
        }
      ]
    }
  ]
}
