{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aca",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aca-0.8.7.jar",
          "url": "ble-characteristic-u2aca-0.8.7.jar",
          "size": 1445,
          "sha512": "737edbc7552779baa09f405886f4c41c4c4323c6d25dc8fe575637c9f1425669bee581d4ced6cd016c52ae1504f59d2a78b2b47988393bbea927807ee8c8b03c",
          "sha256": "2ec91e2bf36c9f4619c67d751d62911168081ac03c4516d61c20996ccaae5fc1",
          "sha1": "46d1fdc08d95495be268c1711b87e4685018b8e4",
          "md5": "328ae9dc3999e3167b8f83ad0f3c3dbb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aca-0.8.7.jar",
          "url": "ble-characteristic-u2aca-0.8.7.jar",
          "size": 1445,
          "sha512": "737edbc7552779baa09f405886f4c41c4c4323c6d25dc8fe575637c9f1425669bee581d4ced6cd016c52ae1504f59d2a78b2b47988393bbea927807ee8c8b03c",
          "sha256": "2ec91e2bf36c9f4619c67d751d62911168081ac03c4516d61c20996ccaae5fc1",
          "sha1": "46d1fdc08d95495be268c1711b87e4685018b8e4",
          "md5": "328ae9dc3999e3167b8f83ad0f3c3dbb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aca-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2aca-0.8.7-javadoc.jar",
          "size": 107102,
          "sha512": "131697accfaf68061a2aa4d8d3614c03306c13fb2686f45c388b591bdb9a5fa574de4a971a09daf337163ea969873ef979e067659eee8ebef265aa3d973522c1",
          "sha256": "865eea6b75aba54218918cb7437ba1e03d22d95eacd0c4f81963e8212d166a2b",
          "sha1": "1147569bb1295bfe8e87c11597ee04a94ab20f6f",
          "md5": "b8ac6ac0ba5bb3dc3e3863c960f6467b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aca-0.8.7-sources.jar",
          "url": "ble-characteristic-u2aca-0.8.7-sources.jar",
          "size": 1414,
          "sha512": "f744cf399d939d81540f51ec63e77077daa5c7ed723b177a36903c2c752ae54d074a6b0b1998cb89b966bad0f5b677962e56cd6944fb3127453deb9e92e14fda",
          "sha256": "c89746193b6cfaf7d52710a4b8ea2ceb09925518109135764381fa13931c0c1e",
          "sha1": "32743cfeacc3aaf1c03e71dfe91efc1df9c079dd",
          "md5": "a237c11a58db2d4fd8a0bf00ad5d56a9"
        }
      ]
    }
  ]
}
