{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a47-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgm5345lfvewjajsd7sfgyhu7u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.9.aar",
          "url": "ble-characteristic-u2a47-android-0.2.9.aar",
          "size": 3278,
          "sha512": "87b6d28b7137e23f474580118588605076d4253f64a551754419070357cf9309901d806185d6ca24109e07ae209c712009257010b512db9348191d62b5b7efa3",
          "sha256": "31d01b2156064653489a2b584a2c910abe009de66cf27980dc37325233676d97",
          "sha1": "c7364f7cce48ad1b03e496002d81118a61333f7a",
          "md5": "efce48acb440539d9161638776adb86f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.9.aar",
          "url": "ble-characteristic-u2a47-android-0.2.9.aar",
          "size": 3278,
          "sha512": "87b6d28b7137e23f474580118588605076d4253f64a551754419070357cf9309901d806185d6ca24109e07ae209c712009257010b512db9348191d62b5b7efa3",
          "sha256": "31d01b2156064653489a2b584a2c910abe009de66cf27980dc37325233676d97",
          "sha1": "c7364f7cce48ad1b03e496002d81118a61333f7a",
          "md5": "efce48acb440539d9161638776adb86f"
        }
      ]
    }
  ]
}
