{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae1-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae1",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-android-0.4.3.aar",
          "url": "ble-characteristic-u2ae1-android-0.4.3.aar",
          "size": 3130,
          "sha512": "907fa1023d6b1df5ce79114f78662c1fb866cf1555b2eb58145a22f186e59b5c1a8576f0d1923955f7ee33b8415d064a4f36d21fa3dd116a98bf139a9d314d3c",
          "sha256": "c4fecc19fd8d1680037810046ce2a15cd486691c49194c1dc0f5d25022b343db",
          "sha1": "7a01f9926f144438dcffaa1284a0313667394d16",
          "md5": "87053bb5a5d1086be80398dc765961df"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae1",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-android-0.4.3.aar",
          "url": "ble-characteristic-u2ae1-android-0.4.3.aar",
          "size": 3130,
          "sha512": "907fa1023d6b1df5ce79114f78662c1fb866cf1555b2eb58145a22f186e59b5c1a8576f0d1923955f7ee33b8415d064a4f36d21fa3dd116a98bf139a9d314d3c",
          "sha256": "c4fecc19fd8d1680037810046ce2a15cd486691c49194c1dc0f5d25022b343db",
          "sha1": "7a01f9926f144438dcffaa1284a0313667394d16",
          "md5": "87053bb5a5d1086be80398dc765961df"
        }
      ]
    }
  ]
}
