{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab3",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "b5siun65pvf3xbu2ctcp5sxnw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab3-0.2.0.jar",
          "url": "ble-characteristic-u2ab3-0.2.0.jar",
          "size": 1742,
          "sha512": "a8b17d574c75673a360a66a930aa2e85da81e63fd82e397cccfde57ea3e05d5c743a95000082189f57d889f028bdf13286eaa428f00b41533c7844755140ca02",
          "sha256": "66aeee6469d82a6e87c8d121f75e28c0518442a45a3588bd5a67133bece08d85",
          "sha1": "d0ddbd21853ae8364a4c6e4c2ae0350a79fdf21b",
          "md5": "54be24f7276ae844c16c470dd8e3926b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab3-0.2.0.jar",
          "url": "ble-characteristic-u2ab3-0.2.0.jar",
          "size": 1742,
          "sha512": "a8b17d574c75673a360a66a930aa2e85da81e63fd82e397cccfde57ea3e05d5c743a95000082189f57d889f028bdf13286eaa428f00b41533c7844755140ca02",
          "sha256": "66aeee6469d82a6e87c8d121f75e28c0518442a45a3588bd5a67133bece08d85",
          "sha1": "d0ddbd21853ae8364a4c6e4c2ae0350a79fdf21b",
          "md5": "54be24f7276ae844c16c470dd8e3926b"
        }
      ]
    }
  ]
}
