{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a27",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a27-0.8.1.jar",
          "url": "ble-characteristic-u2a27-0.8.1.jar",
          "size": 1599,
          "sha512": "231f64d26a11a620ad49bbba90cd5f56622fb443b4378682807a6a3715e489a19f5c115adfd8571551c0dafe03392dd38934ad26f9c7e32b78cffd460eb0b850",
          "sha256": "5b8179f70b0578d5fca89107a1b170bb812621f7b70ce297c22b801bfcd721d1",
          "sha1": "f468b49ace0bd21f213b24292cbe9a742f9bcc49",
          "md5": "b88d88144907d80405e4f4debe472395"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a27-0.8.1.jar",
          "url": "ble-characteristic-u2a27-0.8.1.jar",
          "size": 1599,
          "sha512": "231f64d26a11a620ad49bbba90cd5f56622fb443b4378682807a6a3715e489a19f5c115adfd8571551c0dafe03392dd38934ad26f9c7e32b78cffd460eb0b850",
          "sha256": "5b8179f70b0578d5fca89107a1b170bb812621f7b70ce297c22b801bfcd721d1",
          "sha1": "f468b49ace0bd21f213b24292cbe9a742f9bcc49",
          "md5": "b88d88144907d80405e4f4debe472395"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a27-0.8.1-javadoc.jar",
          "url": "ble-characteristic-u2a27-0.8.1-javadoc.jar",
          "size": 110164,
          "sha512": "da1b50606a38e2cb82b0d5955e75177bfbb1c16e076a4e2ee3ba7b988805f3b5a536ce8ec070c67ff5ce6c0c1639dd8bcfe3dd85a0b11daac693792776b811ee",
          "sha256": "ae986791c109af4740d97ebacb83128c9032b5a14def98861f619a9e90fe9389",
          "sha1": "2b76dd9cd07f41ec52df2587939f2f7990562ba6",
          "md5": "ab5b3adfa5743e6f2f7e5e47c358fe9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a27-0.8.1-sources.jar",
          "url": "ble-characteristic-u2a27-0.8.1-sources.jar",
          "size": 1517,
          "sha512": "538cf9afe5fbcb9371c352e60ac337665ce87de5586cea22f5613310093977204d0762894ed75fca9d1f747b99564ef8eda9eff5ae2dfa0d9964a71b0d261ea2",
          "sha256": "b9774a0595b5350122460a60b137ca7abe5047caa26d0033e6d20ebeb6439a11",
          "sha1": "0bb48bf2d457a2b6c083968a78d94e3bfa0fd0b5",
          "md5": "3d582e5a1528746385b6f116f6c0bbb7"
        }
      ]
    }
  ]
}
