{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6b-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.8.11.aar",
          "url": "ble-characteristic-u2a6b-android-0.8.11.aar",
          "size": 3269,
          "sha512": "d1a226d6932a11504dbdfba7ab87eedc8ba60b1b876823aeea27cac42ffef3ce3713ee10def29b77e554bb6fcf3456adbb1a2a49e6a0d379f96341bef2d0f1c1",
          "sha256": "f23def57b2fc727ad40659bc191d1822838ef5b989d6f555a5e3dac6f8d541ec",
          "sha1": "3c3bfc7de9c9b90e85f835a94502624aa99caec8",
          "md5": "0c91991f464190ff561d7899bb6647e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6b",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.8.11.aar",
          "url": "ble-characteristic-u2a6b-android-0.8.11.aar",
          "size": 3269,
          "sha512": "d1a226d6932a11504dbdfba7ab87eedc8ba60b1b876823aeea27cac42ffef3ce3713ee10def29b77e554bb6fcf3456adbb1a2a49e6a0d379f96341bef2d0f1c1",
          "sha256": "f23def57b2fc727ad40659bc191d1822838ef5b989d6f555a5e3dac6f8d541ec",
          "sha1": "3c3bfc7de9c9b90e85f835a94502624aa99caec8",
          "md5": "0c91991f464190ff561d7899bb6647e2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2a6b-android-0.8.11-sources.jar",
          "size": 2253,
          "sha512": "703aceb999c6d5fdcf275b36054e9fd9d34631fa3202cabb2940a9f2fc5a7b2d2b33842ca94ffdb8cc03d55920b265ece4f34b431b64c1658a81845cc207abe2",
          "sha256": "339b6a2835245300a05ad4f9aa7ced8a350bc9ffd3b1867ee7ef4070c3ba2d27",
          "sha1": "b15357b2fe9d2201ee80cd6086ccd93ac965f9b8",
          "md5": "8accec82504934fd75f450342504c767"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6b-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2a6b-android-0.8.11-javadoc.jar",
          "size": 273412,
          "sha512": "e2644f3299d2618079a40d54e6c8e4d40290d9e7940bf8ba88c535a04315f27e1ec74ad4640ed2ae3cbb7865dd286db667d508ecaeae77efa44c2d3b82fb5a82",
          "sha256": "6a1212a054b144f1228845e3ec4b2ba797bf7e236eb55c99358a36c5acdb0dff",
          "sha1": "c1ebac6c0245e24bbe9d7c51b04a8205fa752472",
          "md5": "445cd91c294a3341f31c7d4ed66a185f"
        }
      ]
    }
  ]
}
