{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4e-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4e",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-android-0.2.6.aar",
          "url": "ble-characteristic-u2a4e-android-0.2.6.aar",
          "size": 3082,
          "sha512": "90e152abcf0fcf4d190b92ee8a4beeac407e40834c589c49022fa2515390a2dc96f9ec14ac615579e8ea70c7910b46251135654d24d4dbc6bb2313c3bdd7abd7",
          "sha256": "ed6b7a961e69f55b5395d411f1f568d0389c0672e39d8cec80c7e4bc2e87bd8e",
          "sha1": "3cd2a1af59e93050666a63655743deec0373973e",
          "md5": "8a988896513a73d1afa0bad11baf172a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4e",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-android-0.2.6.aar",
          "url": "ble-characteristic-u2a4e-android-0.2.6.aar",
          "size": 3082,
          "sha512": "90e152abcf0fcf4d190b92ee8a4beeac407e40834c589c49022fa2515390a2dc96f9ec14ac615579e8ea70c7910b46251135654d24d4dbc6bb2313c3bdd7abd7",
          "sha256": "ed6b7a961e69f55b5395d411f1f568d0389c0672e39d8cec80c7e4bc2e87bd8e",
          "sha1": "3cd2a1af59e93050666a63655743deec0373973e",
          "md5": "8a988896513a73d1afa0bad11baf172a"
        }
      ]
    }
  ]
}
