{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b47",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.2.jar",
          "url": "ble-characteristic-u2b47-0.8.2.jar",
          "size": 1873,
          "sha512": "708a59dfb3e605bccb71e7857f13d84aaa23e7ad717359d9f7bf6e467b038a7ce71ffba8afaaec6493d9b050e9135ce8c93d5ea5ed8fbc8f926752bc42fb2822",
          "sha256": "54d39f08d3b0ba42a592c7d89c90afa7127399a19626914c7485cfd00f78d81e",
          "sha1": "02b8d6b5967c892cd78d1cf420e2faed2264336d",
          "md5": "6dae7fa4eaffde82f20f80bad61dc0cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.2.jar",
          "url": "ble-characteristic-u2b47-0.8.2.jar",
          "size": 1873,
          "sha512": "708a59dfb3e605bccb71e7857f13d84aaa23e7ad717359d9f7bf6e467b038a7ce71ffba8afaaec6493d9b050e9135ce8c93d5ea5ed8fbc8f926752bc42fb2822",
          "sha256": "54d39f08d3b0ba42a592c7d89c90afa7127399a19626914c7485cfd00f78d81e",
          "sha1": "02b8d6b5967c892cd78d1cf420e2faed2264336d",
          "md5": "6dae7fa4eaffde82f20f80bad61dc0cc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.2-javadoc.jar",
          "url": "ble-characteristic-u2b47-0.8.2-javadoc.jar",
          "size": 110823,
          "sha512": "081a1c5410b4b3c39afe65bb321ff8ebbca1479206831226276390f8a08f3038410c41b10202b1f97b995ae6425f53f33fd4b650da88d8d634ed816e268788d4",
          "sha256": "c04593236a6c0596f5b2803645dfe731b0b5df497801f559028380371b8dc045",
          "sha1": "de75854ef6424a98e0a35a6ae29df4da9edc0491",
          "md5": "c817109b15ce14fad69af25f9dcda698"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.2-sources.jar",
          "url": "ble-characteristic-u2b47-0.8.2-sources.jar",
          "size": 1692,
          "sha512": "3b380d6313f19e6af01bf3a3e42e6075d14e50cf0762ccf89dbe708673345f70de6008256449f35ec44cc3e3be23b8eff4b76d0ac2061fbbaf666368ee12f69f",
          "sha256": "4db2b223323c623b4ef4addf5019d5c7261283cd27477fe2d198a6ecead86933",
          "sha1": "37517db41c207449f7d50be854735348c82345a2",
          "md5": "6c0217440177cb0c0d04b78b6d57c8bf"
        }
      ]
    }
  ]
}
