{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.snksoft",
          "module": "crc",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-appearance",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-company",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-datatype",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-declaration",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-scheme",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-member",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-profile",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-protocol",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-sdo",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-unit",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-0.6.0.jar",
          "url": "ble-core-constants-0.6.0.jar",
          "size": 4142,
          "sha512": "90082b9264f643d872fa68fceb65c439d70b88e2e095a24678bb7d2b5fd06378c266617a19e597755a41e5885851c43f92ebec33d2f22d421b4f196404656e8f",
          "sha256": "32c4b46d79d9f60e2f88a464a9c14eaec98f66a8470581ce308f28d029afe3c9",
          "sha1": "8371094a44f95f6b3d084163d8783e23d55c3109",
          "md5": "be8afac57ae494b5df574f6d077de995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.github.snksoft",
          "module": "crc",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-appearance",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-company",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-datatype",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-declaration",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-scheme",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-member",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-profile",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-protocol",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-sdo",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-unit",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-0.6.0.jar",
          "url": "ble-core-constants-0.6.0.jar",
          "size": 4142,
          "sha512": "90082b9264f643d872fa68fceb65c439d70b88e2e095a24678bb7d2b5fd06378c266617a19e597755a41e5885851c43f92ebec33d2f22d421b4f196404656e8f",
          "sha256": "32c4b46d79d9f60e2f88a464a9c14eaec98f66a8470581ce308f28d029afe3c9",
          "sha1": "8371094a44f95f6b3d084163d8783e23d55c3109",
          "md5": "be8afac57ae494b5df574f6d077de995"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-0.6.0-javadoc.jar",
          "url": "ble-core-constants-0.6.0-javadoc.jar",
          "size": 125441,
          "sha512": "b3b45c1fc520fedf814dd81a853b9a0f6320ec126cb4d0eef46ba07a2f46ca3b73c1561926eb5e5a543054923d7d86f9640335269c7fd24a4382cb3783d5dedb",
          "sha256": "276f82f31856a57174500625d0a4e9552f34cebfabae87ce33b44dc176e19a42",
          "sha1": "908f7992202db8c19ee40562f527eb53a6a8098b",
          "md5": "5a115ee8db8ba10d95bf6e77723ebce2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-0.6.0-sources.jar",
          "url": "ble-core-constants-0.6.0-sources.jar",
          "size": 1565,
          "sha512": "dd9aac12628e1dcb6f0026d76412edce77c67a0fe0a8260dc9d255ec1247c14709fe77623e03cb24592284b69ea58cec45d3cff44cd7993a3a88effc5d32960b",
          "sha256": "89b93aa5973973aeb48a88e1d2ad2af02dd3ed56ed5ae4ba9c7ade20a66eb78b",
          "sha1": "68e6605625dca97caf57c13c20f1ba2800832281",
          "md5": "aadd318e50d30ac03d80888992c5b454"
        }
      ]
    }
  ]
}
