{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b23",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b23-0.8.12.jar",
          "url": "ble-characteristic-u2b23-0.8.12.jar",
          "size": 1446,
          "sha512": "c544b98e084c705925219482fa0c0e6ef793c610f5a6f3bd4cb7bd0ce1c8b069b658183542478e8dc2fd3da1e7b1f741c0629a06843132c7c20a07a5b058c585",
          "sha256": "bae29d51f6711969490f62efa18174b090e9e3433c7edc20cd34971b75abc5cf",
          "sha1": "7987ae7a2245a8c81d9d4bcfb18ff002f496d11e",
          "md5": "1da750c86eca66aab89261d7580f7d06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b23-0.8.12.jar",
          "url": "ble-characteristic-u2b23-0.8.12.jar",
          "size": 1446,
          "sha512": "c544b98e084c705925219482fa0c0e6ef793c610f5a6f3bd4cb7bd0ce1c8b069b658183542478e8dc2fd3da1e7b1f741c0629a06843132c7c20a07a5b058c585",
          "sha256": "bae29d51f6711969490f62efa18174b090e9e3433c7edc20cd34971b75abc5cf",
          "sha1": "7987ae7a2245a8c81d9d4bcfb18ff002f496d11e",
          "md5": "1da750c86eca66aab89261d7580f7d06"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b23-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b23-0.8.12-javadoc.jar",
          "size": 85952,
          "sha512": "636943c72463d242c149024fd3dbbb07f610220924f14212b57cbbf9997534b451d38333a70ee0c00007e229e9eeb67413feb4886a84b09b1bd4dc86027df392",
          "sha256": "3ca23159bc133de65fb424dd2df2da3955ccf89f172576a3cebeb0d6fa75c38b",
          "sha1": "578ce55a36a59119778741818bc47e403cc4a286",
          "md5": "038eae16874ccffd92bfafc1b32c5de3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b23-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b23-0.8.12-sources.jar",
          "size": 1435,
          "sha512": "f66cfd76a9b8cad6b632a4a2ecc03b5d9725e0e2504411709b97bd333c4d0cf935fd3e67d98715e1851b3a618f205e484b85fafe914fa046398a5f3f3864dc77",
          "sha256": "f84fb929a4186516137f9f290a1ffc21d7c13551bc24907513fa8293e2a368f7",
          "sha1": "4c71aea2cb34685cf1836de749c89122daf4be53",
          "md5": "84bca5e767661cb73145ad53120c6e60"
        }
      ]
    }
  ]
}
