{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bda",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bda-0.8.12.jar",
          "url": "ble-characteristic-u2bda-0.8.12.jar",
          "size": 1463,
          "sha512": "f09a10991e557df88ec52b5a08cf3be26e653cf348d1241fcca2ddf848e28cdc2bebba0c3a6677282360d36e4e611d2aeb1614fb2ea2239b82c91495914df770",
          "sha256": "53292ad62ae9135679a6e945d7bbd34f813a8532faafd2a33e16f68ceefaa4b6",
          "sha1": "e7b098f3b9491d0736680bbf345b3cb21b7e8be7",
          "md5": "820596ffc2e868ac8a2b468d7233383a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bda-0.8.12.jar",
          "url": "ble-characteristic-u2bda-0.8.12.jar",
          "size": 1463,
          "sha512": "f09a10991e557df88ec52b5a08cf3be26e653cf348d1241fcca2ddf848e28cdc2bebba0c3a6677282360d36e4e611d2aeb1614fb2ea2239b82c91495914df770",
          "sha256": "53292ad62ae9135679a6e945d7bbd34f813a8532faafd2a33e16f68ceefaa4b6",
          "sha1": "e7b098f3b9491d0736680bbf345b3cb21b7e8be7",
          "md5": "820596ffc2e868ac8a2b468d7233383a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bda-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2bda-0.8.12-javadoc.jar",
          "size": 86007,
          "sha512": "45fbd3f05cbb56a93bdc143ad9fc30315a2b203363ba649075d1dcb80f16cd508eadf810baa1d78723d3bd9659d45ff180d356fea8e67b5934a69e3cb4c70337",
          "sha256": "ac1c050afbe55b61684ef6200feb91a980cf1802e96c1fe43348e2a3d7b95114",
          "sha1": "af65cba74d7e501f5acb9288aad24f6694a33c5a",
          "md5": "e2d9df46d0c5c105e89018481f48e6fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bda-0.8.12-sources.jar",
          "url": "ble-characteristic-u2bda-0.8.12-sources.jar",
          "size": 1440,
          "sha512": "5452635681061f9a593db5d4039c582a67c80eee1e69cf4c90e3658e3b591e68c0148f8f7bc0bafeeb25e26c295a612fa912c19acfe4dd9e2ff2bed2e58e25c6",
          "sha256": "9461625053c3c8664ef8285e480059b891fd938c5b35b66768030313b5b929dd",
          "sha1": "9334c1ffabb895104484297e4e4cca21e87a9892",
          "md5": "75729b51d7c2c1f2f51b7853beba1e4a"
        }
      ]
    }
  ]
}
