{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a24-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zzwrv7bhbfgvlhoshhgo5ogf5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a24",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-android-0.2.3.aar",
          "url": "ble-characteristic-u2a24-android-0.2.3.aar",
          "size": 2933,
          "sha512": "37c6ae4a19c493304ccce14ff24167fb1c541b7f6d6ca793b6699822a4460f40b143a95a41bc555b2f6d68255e86dbed2ad25404b67e65856e8cef042412d6cb",
          "sha256": "34f7451e7b60308788d5c2272143a711422137d2bfdd083a79f688dada7ad533",
          "sha1": "752f07a2da1556d379c5a6842eebf7802cbfc2be",
          "md5": "8f12895c21fa8acbe8277c2cf21b765a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a24",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-android-0.2.3.aar",
          "url": "ble-characteristic-u2a24-android-0.2.3.aar",
          "size": 2933,
          "sha512": "37c6ae4a19c493304ccce14ff24167fb1c541b7f6d6ca793b6699822a4460f40b143a95a41bc555b2f6d68255e86dbed2ad25404b67e65856e8cef042412d6cb",
          "sha256": "34f7451e7b60308788d5c2272143a711422137d2bfdd083a79f688dada7ad533",
          "sha1": "752f07a2da1556d379c5a6842eebf7802cbfc2be",
          "md5": "8f12895c21fa8acbe8277c2cf21b765a"
        }
      ]
    }
  ]
}
