{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a69-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-android-0.2.7.aar",
          "url": "ble-characteristic-u2a69-android-0.2.7.aar",
          "size": 3043,
          "sha512": "740814316a6ed8d1fdd90b7b5a4fbe12989515dd5401610284d8bd07b637c3a69657c54e367f5c565d2774d18bce9934f6434c0a3a009942fd9afedcb0d5e56b",
          "sha256": "aa06f59a537caaf0a4bc1595a1181d586d5d6a45e2fd4102f0585b6221625d46",
          "sha1": "184c9dfe712c23362179b38529e8e0f6b5374c9c",
          "md5": "450670734f79d3d56bd163a776132309"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-android-0.2.7.aar",
          "url": "ble-characteristic-u2a69-android-0.2.7.aar",
          "size": 3043,
          "sha512": "740814316a6ed8d1fdd90b7b5a4fbe12989515dd5401610284d8bd07b637c3a69657c54e367f5c565d2774d18bce9934f6434c0a3a009942fd9afedcb0d5e56b",
          "sha256": "aa06f59a537caaf0a4bc1595a1181d586d5d6a45e2fd4102f0585b6221625d46",
          "sha1": "184c9dfe712c23362179b38529e8e0f6b5374c9c",
          "md5": "450670734f79d3d56bd163a776132309"
        }
      ]
    }
  ]
}
