{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abb-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ne3pcejtrrhfvmmkle32bx6bti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abb",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abb-android-0.2.5.aar",
          "url": "ble-characteristic-u2abb-android-0.2.5.aar",
          "size": 3092,
          "sha512": "5ae7e84dcb903cafd4ca53a6728a06eba3b660a9078ffca66e2298fe129472ff20db545f9e77526e236c88fc42844ba029581fbc0108226de3cd235496cef17a",
          "sha256": "5933e66f51fc457ba1efa84896a633051f20f12145ed2c782b129ab419a77754",
          "sha1": "a4269f223cc393a962f189deeec7daf67274796c",
          "md5": "cf232489fda19fd89eab05c528189795"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abb",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abb-android-0.2.5.aar",
          "url": "ble-characteristic-u2abb-android-0.2.5.aar",
          "size": 3092,
          "sha512": "5ae7e84dcb903cafd4ca53a6728a06eba3b660a9078ffca66e2298fe129472ff20db545f9e77526e236c88fc42844ba029581fbc0108226de3cd235496cef17a",
          "sha256": "5933e66f51fc457ba1efa84896a633051f20f12145ed2c782b129ab419a77754",
          "sha1": "a4269f223cc393a962f189deeec7daf67274796c",
          "md5": "cf232489fda19fd89eab05c528189795"
        }
      ]
    }
  ]
}
