{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a16",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "e3ikqwiwsbdaddptppumhoyem4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.1.0.jar",
          "url": "ble-characteristic-u2a16-0.1.0.jar",
          "size": 1877,
          "sha512": "75dfe86983bc9da9aeb072b77682dc7797b066a83d46749314739c975b940ce6cca90bf0a7b126adc38d79f581f6e685847720dfd69e02565f795f73a9272e1a",
          "sha256": "9686ad485303d8f7953df514f7f81950f70aa12539c2907e4146d70c7b73977c",
          "sha1": "be410e75151c119fc13e28a20ae751ff7f621213",
          "md5": "3e4a5ca52ae130599d4a0b85586ed3cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.1.0.jar",
          "url": "ble-characteristic-u2a16-0.1.0.jar",
          "size": 1877,
          "sha512": "75dfe86983bc9da9aeb072b77682dc7797b066a83d46749314739c975b940ce6cca90bf0a7b126adc38d79f581f6e685847720dfd69e02565f795f73a9272e1a",
          "sha256": "9686ad485303d8f7953df514f7f81950f70aa12539c2907e4146d70c7b73977c",
          "sha1": "be410e75151c119fc13e28a20ae751ff7f621213",
          "md5": "3e4a5ca52ae130599d4a0b85586ed3cb"
        }
      ]
    }
  ]
}
