{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aca-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aca",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aca-android-0.8.12.aar",
          "url": "ble-characteristic-u2aca-android-0.8.12.aar",
          "size": 3131,
          "sha512": "2384f873dcbccbddc4700b5f23ac2beed4425de4b0ceb23ee55705495c0dbe81880f5d731a5388183e539434e1e8754ee07db203f7f217df56556d8a64534d85",
          "sha256": "df21c310d42cee5642f87cb788c45c71445c1c347e8b03922cbe10071164865e",
          "sha1": "114f057aed1786c418ed18bc3d0afd9f68489c0a",
          "md5": "e2c03e779e7ed9985e72cbc145c96efa"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aca",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aca-android-0.8.12.aar",
          "url": "ble-characteristic-u2aca-android-0.8.12.aar",
          "size": 3131,
          "sha512": "2384f873dcbccbddc4700b5f23ac2beed4425de4b0ceb23ee55705495c0dbe81880f5d731a5388183e539434e1e8754ee07db203f7f217df56556d8a64534d85",
          "sha256": "df21c310d42cee5642f87cb788c45c71445c1c347e8b03922cbe10071164865e",
          "sha1": "114f057aed1786c418ed18bc3d0afd9f68489c0a",
          "md5": "e2c03e779e7ed9985e72cbc145c96efa"
        }
      ]
    }
  ]
}
