{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-lnp-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bas-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-lns-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-lnp-android-0.4.0.aar",
          "url": "ble-profile-central-lnp-android-0.4.0.aar",
          "size": 6742,
          "sha512": "e9e87090d9a56bcdfa149b1f98b5c531b529f502f2eb51e46e47e9e517e3cbf903d21bb30c1306b43dcb8d05b6f4975149b66ced6223c1839705a5270342002d",
          "sha256": "02cdfddf247cb939573726016c35e180cf2a7fddaee35c0b4c65c7a0c6f4ebf8",
          "sha1": "84923a59b61a1026d4c3f0183f952bf03aacb2db",
          "md5": "0a27f85ef91064e85d242324298318cd"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bas-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-lns-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-lnp-android-0.4.0.aar",
          "url": "ble-profile-central-lnp-android-0.4.0.aar",
          "size": 6742,
          "sha512": "e9e87090d9a56bcdfa149b1f98b5c531b529f502f2eb51e46e47e9e517e3cbf903d21bb30c1306b43dcb8d05b6f4975149b66ced6223c1839705a5270342002d",
          "sha256": "02cdfddf247cb939573726016c35e180cf2a7fddaee35c0b4c65c7a0c6f4ebf8",
          "sha1": "84923a59b61a1026d4c3f0183f952bf03aacb2db",
          "md5": "0a27f85ef91064e85d242324298318cd"
        }
      ]
    }
  ]
}
