{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2adc",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.6.jar",
          "url": "ble-characteristic-u2adc-0.8.6.jar",
          "size": 1478,
          "sha512": "8df59d51b14c946efcf69f5af803d4e1e216370271a05107094eb592640d75d5e49421c4582f9c5ea458639bd2ee69aafef174959070c3b310fd0ada96aa088d",
          "sha256": "ee147fe2779931e67b6e801fb10a14165f8c7a3bc3ffd80faae3567f58bd94e4",
          "sha1": "ec9d5c9cfeb53bbd1dfb7605ce1aa7b794ece4c6",
          "md5": "9baa2c6805d06769747ea20789b4145e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.6.jar",
          "url": "ble-characteristic-u2adc-0.8.6.jar",
          "size": 1478,
          "sha512": "8df59d51b14c946efcf69f5af803d4e1e216370271a05107094eb592640d75d5e49421c4582f9c5ea458639bd2ee69aafef174959070c3b310fd0ada96aa088d",
          "sha256": "ee147fe2779931e67b6e801fb10a14165f8c7a3bc3ffd80faae3567f58bd94e4",
          "sha1": "ec9d5c9cfeb53bbd1dfb7605ce1aa7b794ece4c6",
          "md5": "9baa2c6805d06769747ea20789b4145e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2adc-0.8.6-javadoc.jar",
          "size": 107238,
          "sha512": "644aa6596627a85fa44dcbe69e98a5c3e3944436832a31a2d6bc8da7bfbd6cac0ff964cc3ff20c711b8d7bbe75b226330a974453f6a42358511fbce08d9b10f3",
          "sha256": "c54e77ef30213deba58db9f56d349b07f0337fcb37dcbc3ab76765830715c824",
          "sha1": "8b7700941e0178357e4d9a227cdf60bd281c5ff9",
          "md5": "ee20db4c7ec74a92f9bc65fc98498af5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.6-sources.jar",
          "url": "ble-characteristic-u2adc-0.8.6-sources.jar",
          "size": 1464,
          "sha512": "edf4cadabb5939fd3b93e662418abcacbf7e491e6895d386eccb70d29d4d77c87d0c3d31277d9911891e109d043a33a537bdb3b6841e02d227e5a5822bd45252",
          "sha256": "b8efb7243b9cafcb7286a25cc0461aac134ae51bcc5ed730c0f5699a4a169552",
          "sha1": "de17b3329f0a9720df6fa0efb9604a692fd31dec",
          "md5": "de4abb5ebd9b4859935676fd5c654b79"
        }
      ]
    }
  ]
}
