{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1c",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.11.jar",
          "url": "ble-characteristic-u2b1c-0.8.11.jar",
          "size": 1791,
          "sha512": "7e92a748389eb9d4c3ef73263c6f928354f8431a438e66e790eee3902940ed465951c45840970284b4f94d7c247058f4a7f93ed7bf2761d78d9f83cbaf4d6c7c",
          "sha256": "41eb57c60e7ced2e23399d88e467526a52c1bb6b51b2207b97f8749bd0ca6584",
          "sha1": "bfc5ad806fa958ae75de7eb3a5ebd876bf3f0800",
          "md5": "9a7e6f74143dcebb81385aed4239adf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.11.jar",
          "url": "ble-characteristic-u2b1c-0.8.11.jar",
          "size": 1791,
          "sha512": "7e92a748389eb9d4c3ef73263c6f928354f8431a438e66e790eee3902940ed465951c45840970284b4f94d7c247058f4a7f93ed7bf2761d78d9f83cbaf4d6c7c",
          "sha256": "41eb57c60e7ced2e23399d88e467526a52c1bb6b51b2207b97f8749bd0ca6584",
          "sha1": "bfc5ad806fa958ae75de7eb3a5ebd876bf3f0800",
          "md5": "9a7e6f74143dcebb81385aed4239adf2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2b1c-0.8.11-javadoc.jar",
          "size": 107414,
          "sha512": "67cbae21a714bdaa8514b64fe988e16d68efbf1d065adca1f6def93ee9c708558d482b432ff92c80c7c34b3933ec03111426f13d0159918b8ca7eaa77e8440e6",
          "sha256": "c70b8e4a40fceb7252f43a691e15828730aadc799e75b658fbe7add0a1619f28",
          "sha1": "6c2cf4847acedaaa4821b31c73bf43039fa834bd",
          "md5": "886d0c2b64ad078a8aafaa0bee103324"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.11-sources.jar",
          "url": "ble-characteristic-u2b1c-0.8.11-sources.jar",
          "size": 1632,
          "sha512": "9db4e8417c6578d9288d1e950290521b85d66f481e2ba74e248816453d6672d50ee5e8a31bc38cc35834a14d394f71a9bd9ba5a44b70ffb5f815ce5ac4ed0a3b",
          "sha256": "c1b348f51d059ba15b725a80938adb874e418f117671071fd198014432f1a691",
          "sha1": "d429909efbb01eba863b06fd866a67edec944ac7",
          "md5": "79e7ee90fcfc948d264c2f9f9766c846"
        }
      ]
    }
  ]
}
