{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af6-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af6",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af6-android-0.8.11.aar",
          "url": "ble-characteristic-u2af6-android-0.8.11.aar",
          "size": 3207,
          "sha512": "8732a911646db65427f922f6b36189f8d8d81764e8a90a40730a23b553c6310c1511ec1d0b5c79e2486efc2b864c71f591873a3cf0f9542f3d1acf02757fa029",
          "sha256": "bb9e196d0f8287d21322b3fdb9fede2aaedf7e2e69a6f276b4ed81db4905dda2",
          "sha1": "e6f406d0f73e8f6bfd53e723d289dcc8724ce835",
          "md5": "d78500665f85cc98c884002b374dff74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af6",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af6-android-0.8.11.aar",
          "url": "ble-characteristic-u2af6-android-0.8.11.aar",
          "size": 3207,
          "sha512": "8732a911646db65427f922f6b36189f8d8d81764e8a90a40730a23b553c6310c1511ec1d0b5c79e2486efc2b864c71f591873a3cf0f9542f3d1acf02757fa029",
          "sha256": "bb9e196d0f8287d21322b3fdb9fede2aaedf7e2e69a6f276b4ed81db4905dda2",
          "sha1": "e6f406d0f73e8f6bfd53e723d289dcc8724ce835",
          "md5": "d78500665f85cc98c884002b374dff74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af6-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2af6-android-0.8.11-sources.jar",
          "size": 2169,
          "sha512": "35899afa7850e2d3ed3ff7e8ef312dca0edfc2f9f7cbbe2e5e91f348c9b7cc29469d32eb325e33f57c55a78da0233769418a0b06d77d5462680b7d4aeb6ff98e",
          "sha256": "4271cf7f5cb0cb255df8e73fbf44361a1a9254aac8c62ae93affa2e82a1fa984",
          "sha1": "ce504ff79bb654bcc16c04026fc5b0ece4cb771f",
          "md5": "371f412b8a96dc4287ca36a1129a081b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af6-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2af6-android-0.8.11-javadoc.jar",
          "size": 270619,
          "sha512": "1542c082a48f1f7ee0b5a6bf87c25a41f4289d8c40fd912a51758faa566e6d98036670ff8a3cff749714c889ac8404bf4e0bd47b993d9f752b364ef3094fbe76",
          "sha256": "4113bcb58beef1309b0e35d9f7b81c74f01b8122ad5025238648748a93ad5655",
          "sha1": "48d8b07774bf1236f3a93715ce97bf0ddb794431",
          "md5": "c9d3befb268861f4f74917ed9f602852"
        }
      ]
    }
  ]
}
