{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b47",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.12.jar",
          "url": "ble-characteristic-u2b47-0.8.12.jar",
          "size": 1873,
          "sha512": "87227021ac56e7743cf7e954b36292bc2b34a1365e4a9673cd542558e1605e82171fc270350e687a5a3cbdb9916870f106b0fd295fd715f57f9b241a628360eb",
          "sha256": "6ea8d564bf9dd1b62653d79d47fa8635564880641981a777d22f7043e7bceb70",
          "sha1": "07185bfa413966e1ae28bdf80da9443ed933b272",
          "md5": "28fd319241f169bd923d30398783e225"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.12.jar",
          "url": "ble-characteristic-u2b47-0.8.12.jar",
          "size": 1873,
          "sha512": "87227021ac56e7743cf7e954b36292bc2b34a1365e4a9673cd542558e1605e82171fc270350e687a5a3cbdb9916870f106b0fd295fd715f57f9b241a628360eb",
          "sha256": "6ea8d564bf9dd1b62653d79d47fa8635564880641981a777d22f7043e7bceb70",
          "sha1": "07185bfa413966e1ae28bdf80da9443ed933b272",
          "md5": "28fd319241f169bd923d30398783e225"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b47-0.8.12-javadoc.jar",
          "size": 109400,
          "sha512": "ca01bfd5e267618e2b933c1b2e043d8aaa5317ba90923072503a7f62c23a3715185baa5fefbfa128035b0631d39eac8ee302897df677be986015f6e1b015a4b9",
          "sha256": "6fa2deb70605b0f5ddd7d7fe6ad1363aa11c5faed05cc071515e0fdabfb1c700",
          "sha1": "80d7f7a31b2eeabe1d87584c0c6f71fac7213e4c",
          "md5": "989867a1ad3626916e1c13c3fd310ff7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b47-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b47-0.8.12-sources.jar",
          "size": 1692,
          "sha512": "56f7285947f587df0c159dccabe72ed4ef3da6f7bd035c134a13cf44940d5fdfb5d5a608ed9ed20f17abf7bad88c3abb58f51149b495c4beffb3f2108b1cbc23",
          "sha256": "5b0d4171d8043799c557013ae16d89c04b24d75a1565b22d887e1f8227b989b2",
          "sha1": "0a7eec2f160896a8ced2a025b77c43f8ab1f3351",
          "md5": "e8ad39a3d70133086621c16154b3116c"
        }
      ]
    }
  ]
}
