{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2904",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "dhnodpmkbjgkzff4ltm3gds6mq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2904-0.2.1.jar",
          "url": "ble-descriptor-u2904-0.2.1.jar",
          "size": 3267,
          "sha512": "8e1a0402d8bd990f25a6e83829245b6e883ba973449c563086683066e0af9e8015d16525328ac1d0e4b70fe1d97af810869766173731d2789a78450db9bf8f94",
          "sha256": "87f75b88edd68a05514c2370ff89d63398600be5a096e19f10e14dfeef8eab2c",
          "sha1": "486a02cc1605a4e1c5c80dd9a012a5465e805c03",
          "md5": "dea2fc5d720715da838e28b31915a721"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2904-0.2.1.jar",
          "url": "ble-descriptor-u2904-0.2.1.jar",
          "size": 3267,
          "sha512": "8e1a0402d8bd990f25a6e83829245b6e883ba973449c563086683066e0af9e8015d16525328ac1d0e4b70fe1d97af810869766173731d2789a78450db9bf8f94",
          "sha256": "87f75b88edd68a05514c2370ff89d63398600be5a096e19f10e14dfeef8eab2c",
          "sha1": "486a02cc1605a4e1c5c80dd9a012a5465e805c03",
          "md5": "dea2fc5d720715da838e28b31915a721"
        }
      ]
    }
  ]
}
