{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acc",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "biofsw5nmzdz7guktmkptg7lje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.1.0.jar",
          "url": "ble-characteristic-u2acc-0.1.0.jar",
          "size": 4599,
          "sha512": "785db0db01b4970a3d865d7fe37f5fa835fd5cef8cae7c3d89cca2da5e7b96d06f6fb279f7c941f7094e44d6baaf5ba71ecc439aec3d9b5af75204bc5d217d5d",
          "sha256": "d0f81fd396f20feeee3b5c4a26df6034594c115a52623a1d6f358e411257b062",
          "sha1": "c01b190002c387cc0454116192161daba33ba4a2",
          "md5": "8b24d6a6f61c823bcbd7870b01f452df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.1.0.jar",
          "url": "ble-characteristic-u2acc-0.1.0.jar",
          "size": 4599,
          "sha512": "785db0db01b4970a3d865d7fe37f5fa835fd5cef8cae7c3d89cca2da5e7b96d06f6fb279f7c941f7094e44d6baaf5ba71ecc439aec3d9b5af75204bc5d217d5d",
          "sha256": "d0f81fd396f20feeee3b5c4a26df6034594c115a52623a1d6f358e411257b062",
          "sha1": "c01b190002c387cc0454116192161daba33ba4a2",
          "md5": "8b24d6a6f61c823bcbd7870b01f452df"
        }
      ]
    }
  ]
}
