{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-fmp-android",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-fmp-android-0.1.9.aar",
          "url": "ble-profile-fmp-android-0.1.9.aar",
          "size": 1184,
          "sha512": "8493b706a32ffb508be599c2e32e0570c95a9dcbbbd04f3cbd4b2153dae5af3f2680b70e47a932c9e4057be0d4f539e2f6d44eed8cb7962ca7c054beb5d4e259",
          "sha256": "eaf49d12c92e067b9311c270dda178d2f03a660ac0ea3ea569a6757e9e5f1f95",
          "sha1": "bbe866ae5f5a4fcb8b85dc34441e3fb3a7dc42af",
          "md5": "027b2751f5fe6227ba0c4b36b1bd9f0b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-fmp-android-0.1.9.aar",
          "url": "ble-profile-fmp-android-0.1.9.aar",
          "size": 1184,
          "sha512": "8493b706a32ffb508be599c2e32e0570c95a9dcbbbd04f3cbd4b2153dae5af3f2680b70e47a932c9e4057be0d4f539e2f6d44eed8cb7962ca7c054beb5d4e259",
          "sha256": "eaf49d12c92e067b9311c270dda178d2f03a660ac0ea3ea569a6757e9e5f1f95",
          "sha1": "bbe866ae5f5a4fcb8b85dc34441e3fb3a7dc42af",
          "md5": "027b2751f5fe6227ba0c4b36b1bd9f0b"
        }
      ]
    }
  ]
}
