{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a84-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a84",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a84-android-0.8.12.aar",
          "url": "ble-characteristic-u2a84-android-0.8.12.aar",
          "size": 3231,
          "sha512": "7bc4e9a028daff67939f48dd71f6da5037173c95fcfe4f65e9a9a32a7c0ef35d3f5edf9cff6aed741a9522edbd7d5fc040d943703feaec64e7938b24afd3b3e7",
          "sha256": "52e07a141aa1e86aeb69931af640d3f58bde9ecf783acc9ea9468bfb104b7fc9",
          "sha1": "03df90472cd6d6d851bfd25ed15a74ef7437a739",
          "md5": "c5aec607bfdbdbe3d9e75e72dd1bef57"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a84",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a84-android-0.8.12.aar",
          "url": "ble-characteristic-u2a84-android-0.8.12.aar",
          "size": 3231,
          "sha512": "7bc4e9a028daff67939f48dd71f6da5037173c95fcfe4f65e9a9a32a7c0ef35d3f5edf9cff6aed741a9522edbd7d5fc040d943703feaec64e7938b24afd3b3e7",
          "sha256": "52e07a141aa1e86aeb69931af640d3f58bde9ecf783acc9ea9468bfb104b7fc9",
          "sha1": "03df90472cd6d6d851bfd25ed15a74ef7437a739",
          "md5": "c5aec607bfdbdbe3d9e75e72dd1bef57"
        }
      ]
    }
  ]
}
