{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae1",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.6.jar",
          "url": "ble-characteristic-u2ae1-0.8.6.jar",
          "size": 1871,
          "sha512": "58d6160080caa6e88af9a515adc81af280c99aa2554796050488cbfbd20be3bfc876f4718a187e1570fe1635807971ec6883a9d9310c048f05a207fcf8984a85",
          "sha256": "2d697f605b0fbcd3b0c03821790a57ac9251eb727038543f5fe726d484adac18",
          "sha1": "451cac8fbaeb09e4d0609ceb5d8fe3651316c45c",
          "md5": "07eed9aed94e46276ad85311ddbcc4a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.6.jar",
          "url": "ble-characteristic-u2ae1-0.8.6.jar",
          "size": 1871,
          "sha512": "58d6160080caa6e88af9a515adc81af280c99aa2554796050488cbfbd20be3bfc876f4718a187e1570fe1635807971ec6883a9d9310c048f05a207fcf8984a85",
          "sha256": "2d697f605b0fbcd3b0c03821790a57ac9251eb727038543f5fe726d484adac18",
          "sha1": "451cac8fbaeb09e4d0609ceb5d8fe3651316c45c",
          "md5": "07eed9aed94e46276ad85311ddbcc4a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2ae1-0.8.6-javadoc.jar",
          "size": 107473,
          "sha512": "db9f67ff50d4182c302b801b892e5584ac0ccd90d70bd554471410da617b1f89e60c7edd0f978c3c489cee04532cd0b7c2152dd6934cdfa9c192d98153e22400",
          "sha256": "470bb870d173177fd3fb1c69976d84ad2e86aaac27208c9789896ef9c0f522ae",
          "sha1": "26d955299022149b2afc40de97ad68f8e7ae9a60",
          "md5": "32bd5275c649c7aa60941b19296b2a1e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ae1-0.8.6-sources.jar",
          "size": 1687,
          "sha512": "fd08facd2f7e9eac45d1b786b241033b0a23aa48093309df9636e9c35caf08a82a70fed3e99299ce326ee3de431bc123fee998234f624e44207c2cfb9dd12be1",
          "sha256": "a4a102fc4584ff9866779d80c8685672fbe461f237cafd16e3e13e1b79d4e9d4",
          "sha1": "d0eee62ac1e9b0e4e2a18fb8406b931048b7a03a",
          "md5": "71d8e850db6b1b3b540d23678e20124e"
        }
      ]
    }
  ]
}
