{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smp7vu2g4jdlfelcafoemcahhe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.8.aar",
          "url": "ble-characteristic-u2a04-android-0.2.8.aar",
          "size": 3244,
          "sha512": "ea1b8e8fc61945085db19a6ef2463c0966213a530f819d8aaaa989ab9ce2ca4d5143653a76bcaf639a6ebf3f577745327bf298e87781f6b88f7c2e4312307ddf",
          "sha256": "d3d5c0bf6152525d370ecbcf2f0295af79ece1292e6391a3a1622e7d4a5c07cd",
          "sha1": "4b57a71ef5eb9d956143e7fbbc8c7282094ec254",
          "md5": "2a6362b4f70617c4ad80729321eb0b2a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.8.aar",
          "url": "ble-characteristic-u2a04-android-0.2.8.aar",
          "size": 3244,
          "sha512": "ea1b8e8fc61945085db19a6ef2463c0966213a530f819d8aaaa989ab9ce2ca4d5143653a76bcaf639a6ebf3f577745327bf298e87781f6b88f7c2e4312307ddf",
          "sha256": "d3d5c0bf6152525d370ecbcf2f0295af79ece1292e6391a3a1622e7d4a5c07cd",
          "sha1": "4b57a71ef5eb9d956143e7fbbc8c7282094ec254",
          "md5": "2a6362b4f70617c4ad80729321eb0b2a"
        }
      ]
    }
  ]
}
