{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad6-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.2.8.aar",
          "url": "ble-characteristic-u2ad6-android-0.2.8.aar",
          "size": 3205,
          "sha512": "ca7fb35a3aaa545e77be933080c429c3b31fb88964720be1bc07acaef52e1ed601eefe8a01e90747b14fcd3fe4fdd2cbec5f1d96036ecb2ec9fea7a17c5d6703",
          "sha256": "fa0072c23d60639395d74fd7ba2906d4447422d77fe285e71b90efcc98f75e83",
          "sha1": "80a1cd1af06e375768eecb7ea443b962304ac382",
          "md5": "0ca41fe15ccc616187830202870e9051"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.2.8.aar",
          "url": "ble-characteristic-u2ad6-android-0.2.8.aar",
          "size": 3205,
          "sha512": "ca7fb35a3aaa545e77be933080c429c3b31fb88964720be1bc07acaef52e1ed601eefe8a01e90747b14fcd3fe4fdd2cbec5f1d96036ecb2ec9fea7a17c5d6703",
          "sha256": "fa0072c23d60639395d74fd7ba2906d4447422d77fe285e71b90efcc98f75e83",
          "sha1": "80a1cd1af06e375768eecb7ea443b962304ac382",
          "md5": "0ca41fe15ccc616187830202870e9051"
        }
      ]
    }
  ]
}
