{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd8-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd8",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd8-android-0.8.6.aar",
          "url": "ble-characteristic-u2bd8-android-0.8.6.aar",
          "size": 3179,
          "sha512": "2cc3c4222c8256509676a839fba1c3048718c63f4370207d18dff3147810941042bca4b1b08703976cefd80707688f3c1d0ff51510eaefe817e572d91ef2a592",
          "sha256": "ebe51b5656c9ec53c9baf2742dc7a7e0a2316432785688832ca03489f7f48cc2",
          "sha1": "e8c83b8a4e0544aca1b2e3d32210110ebb5d44c8",
          "md5": "41f3b3cdda77e46cb59614f60e837f19"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd8",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd8-android-0.8.6.aar",
          "url": "ble-characteristic-u2bd8-android-0.8.6.aar",
          "size": 3179,
          "sha512": "2cc3c4222c8256509676a839fba1c3048718c63f4370207d18dff3147810941042bca4b1b08703976cefd80707688f3c1d0ff51510eaefe817e572d91ef2a592",
          "sha256": "ebe51b5656c9ec53c9baf2742dc7a7e0a2316432785688832ca03489f7f48cc2",
          "sha1": "e8c83b8a4e0544aca1b2e3d32210110ebb5d44c8",
          "md5": "41f3b3cdda77e46cb59614f60e837f19"
        }
      ]
    }
  ]
}
