{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a84",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a84-0.8.6.jar",
          "url": "ble-characteristic-u2a84-0.8.6.jar",
          "size": 1764,
          "sha512": "56b1f11bd55aa7ec3009ab41bd78ed28f98f0bc25da34d3f4e37e173891dd6cb7071c59c62350d56b787df7b99e06e1e8ce11699578981a545297ce974cb5d44",
          "sha256": "f12c3aab8e7bc5bc7b31c7b57398edf2c26e5ea54f2bb4e25ee0885c1d457579",
          "sha1": "7c277eb4993d57703cf606034e45fbe99fdd55c5",
          "md5": "a2c50055ab452c4a3ee1e4ca9a0b4eb8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a84-0.8.6.jar",
          "url": "ble-characteristic-u2a84-0.8.6.jar",
          "size": 1764,
          "sha512": "56b1f11bd55aa7ec3009ab41bd78ed28f98f0bc25da34d3f4e37e173891dd6cb7071c59c62350d56b787df7b99e06e1e8ce11699578981a545297ce974cb5d44",
          "sha256": "f12c3aab8e7bc5bc7b31c7b57398edf2c26e5ea54f2bb4e25ee0885c1d457579",
          "sha1": "7c277eb4993d57703cf606034e45fbe99fdd55c5",
          "md5": "a2c50055ab452c4a3ee1e4ca9a0b4eb8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a84-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a84-0.8.6-javadoc.jar",
          "size": 107497,
          "sha512": "0d916ecc671e1c890a19128a2110718bce93473e6bf2dee4ca38a69f9c0c9fda2e3dd87c6362ca544dfb2f91efccc4fc6679497ed18bf5a8ab5f251613283473",
          "sha256": "0e7ce7c560a86b6e201076b6334749bd99edb45cb8d6e5e533028fdd57b56e95",
          "sha1": "03430dac9268a49e8272da89e919c0d18cd10f97",
          "md5": "cd7f75feb5b195800bfeaa2396dab9a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a84-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a84-0.8.6-sources.jar",
          "size": 1634,
          "sha512": "7d60b04b73ec6d69b8706670492b11aef4bc9c768c6f560298794952f98feae69cfb063f498d2d9cbd2176bf046a1e36fe4cb864bb67ceed7694a6dd329fcf4e",
          "sha256": "3f1b0b88982116ba3a720ad9addaf3595b3b52d26bd05222603bcb1300dd7245",
          "sha1": "0caeec5f492554dd8327859b51a59650e2a3122c",
          "md5": "13459764c54fd15ef7d117d56f31fb63"
        }
      ]
    }
  ]
}
