{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4e",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.13.jar",
          "url": "ble-characteristic-u2b4e-0.8.13.jar",
          "size": 3560,
          "sha512": "21b9f2591d08c8abc68ba685e122b66fdec4331af8242a5489b92c963a02fcc9e52bc297d9d79ee466ec2294498660e43b23f559bbc82012d31682f00b9757be",
          "sha256": "850c8a409aaea94c0620aef1bde3b40207bd8f0fb542d1cc211f5e7726308f87",
          "sha1": "7ec9ff2c90a8b8b3ae475d6c5103ecd65684b54b",
          "md5": "09059292d5283a94b4587d20c737a55a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.13.jar",
          "url": "ble-characteristic-u2b4e-0.8.13.jar",
          "size": 3560,
          "sha512": "21b9f2591d08c8abc68ba685e122b66fdec4331af8242a5489b92c963a02fcc9e52bc297d9d79ee466ec2294498660e43b23f559bbc82012d31682f00b9757be",
          "sha256": "850c8a409aaea94c0620aef1bde3b40207bd8f0fb542d1cc211f5e7726308f87",
          "sha1": "7ec9ff2c90a8b8b3ae475d6c5103ecd65684b54b",
          "md5": "09059292d5283a94b4587d20c737a55a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2b4e-0.8.13-javadoc.jar",
          "size": 92153,
          "sha512": "97d73d9e5ad2615b98f979fedbd7ef7b6f1bbce5d9adea15e95f2b075937623c61a71c1f2345800c725b72a32ec1e70dce11699dc9a66a98f4a13634aaaf3b9e",
          "sha256": "1bed511cc1489cb277edce4e69d7b6027ca10da712cfb858308df50ba6238ecd",
          "sha1": "b00d37ba59c5dbb6ecc00a077518361568cb2e18",
          "md5": "bc0128d0db3d5e685d89ab1eceb3ecc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.13-sources.jar",
          "url": "ble-characteristic-u2b4e-0.8.13-sources.jar",
          "size": 3339,
          "sha512": "7f7edcc9863b43ed8b1ea8a7407fb3e5430701394d0b49a7a90f4d12af3ceaebdd07914fbc83bf38edcd9764b121a5618e54299328181290fbbf76d2c00b4959",
          "sha256": "5de70ab7f616d58bec6d2049016603364ed0a0785b9d55c24f8c3d47f8b615a0",
          "sha1": "6c0d7a3de4d8de8cdb525000a6f716f9898b554d",
          "md5": "abd623e4eeada6f695dd7971b72bc376"
        }
      ]
    }
  ]
}
