{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb5",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.5.jar",
          "url": "ble-characteristic-u2bb5-0.8.5.jar",
          "size": 1458,
          "sha512": "cbfe0898ba4e55dba9e327e37dc3ebd28a0c6e908d019673a8753b6d030fdb7722865b9a93102fd26729ba403218bd348c78f8f027cbf33b66a92ee60ed5223f",
          "sha256": "3cd433fc646c8d964aa3396e6d417b8644f4bc51c9004935dd449149201ec630",
          "sha1": "50744107ffa35d0d7221e160f3a491bd1444db0d",
          "md5": "2074f52d6facef4b8286836cb43ba85e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.5.jar",
          "url": "ble-characteristic-u2bb5-0.8.5.jar",
          "size": 1458,
          "sha512": "cbfe0898ba4e55dba9e327e37dc3ebd28a0c6e908d019673a8753b6d030fdb7722865b9a93102fd26729ba403218bd348c78f8f027cbf33b66a92ee60ed5223f",
          "sha256": "3cd433fc646c8d964aa3396e6d417b8644f4bc51c9004935dd449149201ec630",
          "sha1": "50744107ffa35d0d7221e160f3a491bd1444db0d",
          "md5": "2074f52d6facef4b8286836cb43ba85e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2bb5-0.8.5-javadoc.jar",
          "size": 107165,
          "sha512": "71b45470dcdea2299304285fd4a4b7fd2c3501b0ec8a0bb800f9e862ff41dd177a24a86004d5b77adc722a088bd87fb6e3f9a210dbea0c464bc3d008e84bfe4c",
          "sha256": "e42c6774904dde442b69a77cc26ce01ace87d28b95a6112d5eb63a8ab7660deb",
          "sha1": "b61bfde3127790a19fecf830533c3f7fe0b50e11",
          "md5": "fdb3ff22e8d1e8483e17067d1dce57c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.5-sources.jar",
          "url": "ble-characteristic-u2bb5-0.8.5-sources.jar",
          "size": 1449,
          "sha512": "468054436716aaecacb04556057dbce9cbf0926496d4edcf068d3e899da06fe04b953aaec0a2b573a263b97d99b1dbd0789c5820d392c5e33cab9068eb4236e7",
          "sha256": "13780a70e43b768dd963ea38d28762c0adc6ddfbd2eca942c28c958a5cd7e7f9",
          "sha1": "07cbed5cfcdbcf29412cfdd532337ef61b6483d0",
          "md5": "a7f5ccdec3ce937b1ef5e69ce964a3c5"
        }
      ]
    }
  ]
}
