{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a43",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a43-0.8.6.jar",
          "url": "ble-characteristic-u2a43-0.8.6.jar",
          "size": 1765,
          "sha512": "ceffbcfafd36be0bf1c5570b8d985e18dc50af09884c635eb5dfae560864ecca888e9f8bcbe6247736ead18f2cc7772d00249713b7ef524ec67048a0dc226f10",
          "sha256": "6faa3a10ebcc2a0a182a5430354d5b8a9149d5cdea11c5caa757763d41e0ec06",
          "sha1": "832c8c4832e1ad6ab5c5764378f578621637582c",
          "md5": "bc594a57b44adf36d242b0e7addf9866"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a43-0.8.6.jar",
          "url": "ble-characteristic-u2a43-0.8.6.jar",
          "size": 1765,
          "sha512": "ceffbcfafd36be0bf1c5570b8d985e18dc50af09884c635eb5dfae560864ecca888e9f8bcbe6247736ead18f2cc7772d00249713b7ef524ec67048a0dc226f10",
          "sha256": "6faa3a10ebcc2a0a182a5430354d5b8a9149d5cdea11c5caa757763d41e0ec06",
          "sha1": "832c8c4832e1ad6ab5c5764378f578621637582c",
          "md5": "bc594a57b44adf36d242b0e7addf9866"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a43-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a43-0.8.6-javadoc.jar",
          "size": 107374,
          "sha512": "3b89f239b1eda9b8c1749f802415f29366d9a1072cef3f664f6d55dbca321e87d541c6b51ad24c516206fb363af092f9c1e6edede9e47b2fb4d1026f5eb60a5b",
          "sha256": "793abb6df4f3c641533b223402a3a099c7c3719aae8c35abc941203f1894b256",
          "sha1": "adb0f0f58ac38d7e83fbdceb9c940867a8169e9f",
          "md5": "4f276df69382e78adb548963e54ace6e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a43-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a43-0.8.6-sources.jar",
          "size": 1609,
          "sha512": "a7f8587a5254f9932ecb285cbc1c87e6ea5dd2f4d6d496325c71d964fc61dc1438144c01af0ca95201e129656db973b404c8085195eb457f46e167c806b3f4b7",
          "sha256": "b8b62935e57fed4687a639920f27d6019930d8aff46713aca9455284312e3352",
          "sha1": "21ab244e8d6ebb6a5827980f3736ff2181748618",
          "md5": "b463cb52dfa9999aa965f35856f78cb3"
        }
      ]
    }
  ]
}
