{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3f",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.6.1.jar",
          "url": "ble-characteristic-u2b3f-0.6.1.jar",
          "size": 1515,
          "sha512": "73f353f910b0082cf30efc803643e0fb68815d2800a424aa3e3bed043f3b8ab83111cfcf4a71d77ce1b0a18dd296d3a044448811700e7f1be56d9ca045376cc5",
          "sha256": "2314d334944bc8b0b97ab94b1e6c323393f1c3258699b096cfba073b1311053a",
          "sha1": "34031149acd6a6fa34ccc3b0e1ff39df22196a4d",
          "md5": "6d41571ea9c2434a26bcf9c2cc7fba49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.6.1.jar",
          "url": "ble-characteristic-u2b3f-0.6.1.jar",
          "size": 1515,
          "sha512": "73f353f910b0082cf30efc803643e0fb68815d2800a424aa3e3bed043f3b8ab83111cfcf4a71d77ce1b0a18dd296d3a044448811700e7f1be56d9ca045376cc5",
          "sha256": "2314d334944bc8b0b97ab94b1e6c323393f1c3258699b096cfba073b1311053a",
          "sha1": "34031149acd6a6fa34ccc3b0e1ff39df22196a4d",
          "md5": "6d41571ea9c2434a26bcf9c2cc7fba49"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.6.1-javadoc.jar",
          "url": "ble-characteristic-u2b3f-0.6.1-javadoc.jar",
          "size": 110061,
          "sha512": "2315685b13ed03399e7bda4c2dd159485dfe118a9d404baaeefb9a87004a2972a2fe14f0be3fb4e14ea74801a34a42c943ee7ba825b27bbfc4c15d91f48a3b34",
          "sha256": "8e15e3cbb53e5f868906e10f91725d12e8ea98535cf875451acad69ff5e343d6",
          "sha1": "c79168f910bfdb90acb86b1f6bcfd6c73bc033d9",
          "md5": "f7da1f1d35384bd57b98f4e24d1ef312"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3f-0.6.1-sources.jar",
          "url": "ble-characteristic-u2b3f-0.6.1-sources.jar",
          "size": 1495,
          "sha512": "420c94690d398aa89169a143d34c743fbeb4316cfbf6c2ea7a7f8c7c86f93e0f7e7e20fcb35a2f9e968f6e3f3dc7a16353494d2a0dc6e05a8c558caf7636b01e",
          "sha256": "8857e33b76d1c36ef41ab0db65b163950153a5ba46956fda6e0b5a4ac59d6d1e",
          "sha1": "ec43939b8ebf3b13b64d56207d3bdd9691ee3738",
          "md5": "e6bb2f5d36dc2a533bf7e991c5655289"
        }
      ]
    }
  ]
}
