{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae5",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.9.jar",
          "url": "ble-characteristic-u2ae5-0.8.9.jar",
          "size": 1921,
          "sha512": "7c8e413d6166182d2d922648ba1085d606a71ddcabf6137eaa26709f57651787237960519f66634b7441739d5039daca211e28425e226db38d848f3350725ca6",
          "sha256": "1c19bd9ea9749fa6f78cfe6420e902572d884e8a3c8a20d03ce7371562fd7c61",
          "sha1": "1d0c06b60453a2c4f0024c2e4effe22b502c4272",
          "md5": "3d3004d20294f7aebb441eebe589d808"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.9.jar",
          "url": "ble-characteristic-u2ae5-0.8.9.jar",
          "size": 1921,
          "sha512": "7c8e413d6166182d2d922648ba1085d606a71ddcabf6137eaa26709f57651787237960519f66634b7441739d5039daca211e28425e226db38d848f3350725ca6",
          "sha256": "1c19bd9ea9749fa6f78cfe6420e902572d884e8a3c8a20d03ce7371562fd7c61",
          "sha1": "1d0c06b60453a2c4f0024c2e4effe22b502c4272",
          "md5": "3d3004d20294f7aebb441eebe589d808"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2ae5-0.8.9-javadoc.jar",
          "size": 107737,
          "sha512": "4a984c69079b0ae33bd94cefb02e57299b8d287f6b9d615273a4ed203643e34bd0cd652583d23ef98d9856da951a8c76dceb1517ef22bb3fafba9f55885ef16f",
          "sha256": "02624437522ec74eb32c8612f6accd45d8fcb52ea2e2a236f5e0fd6507f8d5b4",
          "sha1": "493cfefb88748493de202b859dd9fd91df12c8fe",
          "md5": "d4c11872bbce7fbdf225602388aee376"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.9-sources.jar",
          "url": "ble-characteristic-u2ae5-0.8.9-sources.jar",
          "size": 1764,
          "sha512": "e8ab82be43b1f2e8865e2dbc3c0bc7dd4af594695b3031e8b9c4cbf3e2be1a49efd23d7720897dac71b6550ff8387c2e10414c869fe64e197600707b54c58f95",
          "sha256": "bdbcf6a1ea2cca16f6f922953152ac01c42aca7bd4fa19d55b7a1f6712ff50cd",
          "sha1": "ed4870f59f0a4f5682ad237ec8567f42e0c08aa4",
          "md5": "fa586c73cfb5bd4aa9b81b5b0f819aa9"
        }
      ]
    }
  ]
}
