{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd8",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.2.jar",
          "url": "ble-characteristic-u2bd8-0.8.2.jar",
          "size": 1486,
          "sha512": "65088b3af64daebb4ff5abcb45f07a731ec8cf2e9ddcd89da980c8ddea318d92f9ea5ba9888ee8473815e9916c17a97a2f0dbac66b81c7164bc696cd3ea56a3d",
          "sha256": "e94e7ed437ac4ebc4b77561761abc102502a25ca2d6a97c341a84f97fe6516e3",
          "sha1": "7efab96e3db98db3b56f135e52ec1d405072e030",
          "md5": "1c46943e6930729b6c8bd8dad42e5f12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.2.jar",
          "url": "ble-characteristic-u2bd8-0.8.2.jar",
          "size": 1486,
          "sha512": "65088b3af64daebb4ff5abcb45f07a731ec8cf2e9ddcd89da980c8ddea318d92f9ea5ba9888ee8473815e9916c17a97a2f0dbac66b81c7164bc696cd3ea56a3d",
          "sha256": "e94e7ed437ac4ebc4b77561761abc102502a25ca2d6a97c341a84f97fe6516e3",
          "sha1": "7efab96e3db98db3b56f135e52ec1d405072e030",
          "md5": "1c46943e6930729b6c8bd8dad42e5f12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.2-javadoc.jar",
          "url": "ble-characteristic-u2bd8-0.8.2-javadoc.jar",
          "size": 109975,
          "sha512": "83743ce4f767e17cb0069388336fe9c2e6330ff26d398cde19b3c6c4b350731f579075e52b72906903b174554693f8a603d97b97ee4e1cdcc35d804594a029d6",
          "sha256": "882a97f34023bebf8dad358d9f3ed47d20adbb21ff093c207cf150085d588254",
          "sha1": "85184286c971fec5856a4cecfa369f0945e73431",
          "md5": "9e50c1ef5c1218bc73f4003a1986af9d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.2-sources.jar",
          "url": "ble-characteristic-u2bd8-0.8.2-sources.jar",
          "size": 1488,
          "sha512": "fa101458cd1a2d60f2d9217e8b3625c29a75c0cbe110f2d73ad00f63989ef55f098be65787afbb04c91b4aa9ffcdbf2a26cd7148fe2bcae103de68562609737e",
          "sha256": "abfd30ee09cbbec9299e8c046eb2626b9fd6adcca997eb9fcdc9a0773aa567b2",
          "sha1": "3f330d643c5923fc7306d808df9d1da4883c122e",
          "md5": "1a00f80cc90a8dd1f2b162b4062b22e4"
        }
      ]
    }
  ]
}
