{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc1-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc1",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc1-android-0.8.11.aar",
          "url": "ble-characteristic-u2bc1-android-0.8.11.aar",
          "size": 3141,
          "sha512": "67caf7e8ce4ad86d7d4ebc9660f4e410981cfb4f115f73e82c817649b59a954281851f6b3c668ebb6366ab65e9abefb5dd010db754dfbeb31395e1e558c86a78",
          "sha256": "0acd403c3293012f338155ab004f4d3396bf85125920fafc8ed42728d3e7ea32",
          "sha1": "ccb097b6bdc644984d0b241266ca0c38d0f1e81e",
          "md5": "4c4bc47fe0d4011a6b38af263bafb6bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc1",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc1-android-0.8.11.aar",
          "url": "ble-characteristic-u2bc1-android-0.8.11.aar",
          "size": 3141,
          "sha512": "67caf7e8ce4ad86d7d4ebc9660f4e410981cfb4f115f73e82c817649b59a954281851f6b3c668ebb6366ab65e9abefb5dd010db754dfbeb31395e1e558c86a78",
          "sha256": "0acd403c3293012f338155ab004f4d3396bf85125920fafc8ed42728d3e7ea32",
          "sha1": "ccb097b6bdc644984d0b241266ca0c38d0f1e81e",
          "md5": "4c4bc47fe0d4011a6b38af263bafb6bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc1-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2bc1-android-0.8.11-sources.jar",
          "size": 2136,
          "sha512": "7bf579cfaa15dbee3d445409a02cd2ea78cbe4cb02b4b6fe5bb13f5ae43cb193918a4e7eb01845a97faf1ab422b7b3521203ea7d09d2daaf1817dba5f8199d89",
          "sha256": "1716b89fdedb70193dce678cefead569cb48997fb77cdc3e05a866f9f688f7b3",
          "sha1": "b0c9df2670762630308866da0092b5cc10614c45",
          "md5": "a3ef8a698377c9c2123ac445346ed001"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc1-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2bc1-android-0.8.11-javadoc.jar",
          "size": 270487,
          "sha512": "169dc46444591eb8394bb61fae32f77a54f892318ac853e2989ebc9b3f5aa8922bf55ccc0c8cd13f63754641425b4ca856025f20b4cc80b1488381b48d90d104",
          "sha256": "450c2ee287a7b8bec3667e598dbc39a5a372a882e11b943c04c0493eb09eaf6a",
          "sha1": "5aa204314b806c0d8eefb36664a8e8c039c81030",
          "md5": "8c848463d4907ba4c4b70819fcdde296"
        }
      ]
    }
  ]
}
