{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290a",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "e3ikqwiwsbdaddptppumhoyem4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290a-0.1.0.jar",
          "url": "ble-descriptor-u290a-0.1.0.jar",
          "size": 2296,
          "sha512": "d96abe5e663603bd6c6f5aafc652c2a33dad61cb6ae85b103db452dc3cad919f23bbad2fc327edc21a55d3653032379e48df6dbe5816d1e7aaf6e1981c129bc9",
          "sha256": "4646faa7757e14461ac85bb8b9db9642affd9cca997ba2565ac4125e30fbb2bf",
          "sha1": "66071c0b53cdbcde01634441d7dbaf3f4e14d3b9",
          "md5": "6551e41e848b646e9d6ff19777f96dd4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290a-0.1.0.jar",
          "url": "ble-descriptor-u290a-0.1.0.jar",
          "size": 2296,
          "sha512": "d96abe5e663603bd6c6f5aafc652c2a33dad61cb6ae85b103db452dc3cad919f23bbad2fc327edc21a55d3653032379e48df6dbe5816d1e7aaf6e1981c129bc9",
          "sha256": "4646faa7757e14461ac85bb8b9db9642affd9cca997ba2565ac4125e30fbb2bf",
          "sha1": "66071c0b53cdbcde01634441d7dbaf3f4e14d3b9",
          "md5": "6551e41e848b646e9d6ff19777f96dd4"
        }
      ]
    }
  ]
}
