{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b16-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b16",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b16-android-0.8.6.aar",
          "url": "ble-characteristic-u2b16-android-0.8.6.aar",
          "size": 3084,
          "sha512": "521f7786f81eb8ff95db711c80ce4bfa32f1a6368a05df0568fbfa37460457b30ad362bdfdf3729751a4551f6fbd82af8bd12f051d45a3d057e9ae500e3588cb",
          "sha256": "8802c9c5a5aebf0d36d4cbd2c71310821626d5b7ede913423cc94fcd94c48939",
          "sha1": "2a5a630b70e8dc38ab58e637af170b34a64d360e",
          "md5": "b55866384a75bc5847e28d9b25ec6920"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b16",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b16-android-0.8.6.aar",
          "url": "ble-characteristic-u2b16-android-0.8.6.aar",
          "size": 3084,
          "sha512": "521f7786f81eb8ff95db711c80ce4bfa32f1a6368a05df0568fbfa37460457b30ad362bdfdf3729751a4551f6fbd82af8bd12f051d45a3d057e9ae500e3588cb",
          "sha256": "8802c9c5a5aebf0d36d4cbd2c71310821626d5b7ede913423cc94fcd94c48939",
          "sha1": "2a5a630b70e8dc38ab58e637af170b34a64d360e",
          "md5": "b55866384a75bc5847e28d9b25ec6920"
        }
      ]
    }
  ]
}
