{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b8f-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8f",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.8.aar",
          "url": "ble-characteristic-u2b8f-android-0.8.8.aar",
          "size": 3150,
          "sha512": "1cc3d0e71eaa0d397730bbdc0d3c2ca8c06ca3ff876dc8e574ae0c5901d52e7f607018c33f842e01e23bacb6269eabc400a55d44bd4ee296eb98dd8861d06130",
          "sha256": "6ac9f4bc62d2280a4638dacc653fbc773696f754344610dc4f56f956d395fc8f",
          "sha1": "ded32cd29468dbc8a133f0924a2532ec021b2d9f",
          "md5": "00361d06bf859b763ee80b46c1a3252d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b8f",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.8.aar",
          "url": "ble-characteristic-u2b8f-android-0.8.8.aar",
          "size": 3150,
          "sha512": "1cc3d0e71eaa0d397730bbdc0d3c2ca8c06ca3ff876dc8e574ae0c5901d52e7f607018c33f842e01e23bacb6269eabc400a55d44bd4ee296eb98dd8861d06130",
          "sha256": "6ac9f4bc62d2280a4638dacc653fbc773696f754344610dc4f56f956d395fc8f",
          "sha1": "ded32cd29468dbc8a133f0924a2532ec021b2d9f",
          "md5": "00361d06bf859b763ee80b46c1a3252d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.8-sources.jar",
          "url": "ble-characteristic-u2b8f-android-0.8.8-sources.jar",
          "size": 2167,
          "sha512": "c655ac497613d50fe5b25d3c8eaf585054b2b2ec11c3319f7f9d1b114a90b61291f7062bf91d0a1dfa01f28fd3d50b9fe00d11ab9746590d553ac4e79f61ab4f",
          "sha256": "421a579b6e299cb68c6723145bc0e53f955eeaa8fa4b5388fe25ce2aeafd8423",
          "sha1": "b7915934d7e99a2e47a0cbde5887cb292587f3ed",
          "md5": "ecbde1313a883906e2403cca0cd391c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8f-android-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2b8f-android-0.8.8-javadoc.jar",
          "size": 268905,
          "sha512": "b98a758b42d950f67a67d8f90e946177a1699a179013bbe01f8187667f5000dee2176a89cdb8726163ee8e6900302ed1da67b42c08961f57c4a96dd3da89e79d",
          "sha256": "0c695ec25222ddd0cad80dfea917b4745ac95a96f452981da5f996074085d1d8",
          "sha1": "6de3fb49c0c93843597c2c481978c50ebfe5103f",
          "md5": "1fc585d52d5d73dc50e5e0afcc00f066"
        }
      ]
    }
  ]
}
