{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acd-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acd-android-0.8.12.aar",
          "url": "ble-characteristic-u2acd-android-0.8.12.aar",
          "size": 5550,
          "sha512": "3b9cff34f3f7be281880ca826cef0cda9bd7dde1fb3c166d1b4788c70ca680e75fb216011adf494ba1f864d08821ae5b31352e9f935508a269c78d901e062af9",
          "sha256": "1278f831fb64e5f83ce516df935b8db0067c45639e39ba50993618f2197f0c89",
          "sha1": "bf2c3216e1984b2e2938dd5275ee51a531a4d1e0",
          "md5": "ba93b957e2a5140e18f5aafedda0fb76"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acd-android-0.8.12.aar",
          "url": "ble-characteristic-u2acd-android-0.8.12.aar",
          "size": 5550,
          "sha512": "3b9cff34f3f7be281880ca826cef0cda9bd7dde1fb3c166d1b4788c70ca680e75fb216011adf494ba1f864d08821ae5b31352e9f935508a269c78d901e062af9",
          "sha256": "1278f831fb64e5f83ce516df935b8db0067c45639e39ba50993618f2197f0c89",
          "sha1": "bf2c3216e1984b2e2938dd5275ee51a531a4d1e0",
          "md5": "ba93b957e2a5140e18f5aafedda0fb76"
        }
      ]
    }
  ]
}
