{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bad",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.4.jar",
          "url": "ble-characteristic-u2bad-0.8.4.jar",
          "size": 1488,
          "sha512": "3f35621d43aa452f24dc6cd1fb8377197df39b17444842f0a159d2e1a94219c612b3c9b83180298954528bcb5d219eff0284dceee9be93c322b3f11c35434ebd",
          "sha256": "bdf29cf3d7de68a33155353d870bc4b1633605faaa386fdb13035590d079f227",
          "sha1": "c50f47b161604d46ec9e9b7acf2d2426abcd9120",
          "md5": "aed50bfcf0017434179c68dc4403617e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.4.jar",
          "url": "ble-characteristic-u2bad-0.8.4.jar",
          "size": 1488,
          "sha512": "3f35621d43aa452f24dc6cd1fb8377197df39b17444842f0a159d2e1a94219c612b3c9b83180298954528bcb5d219eff0284dceee9be93c322b3f11c35434ebd",
          "sha256": "bdf29cf3d7de68a33155353d870bc4b1633605faaa386fdb13035590d079f227",
          "sha1": "c50f47b161604d46ec9e9b7acf2d2426abcd9120",
          "md5": "aed50bfcf0017434179c68dc4403617e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2bad-0.8.4-javadoc.jar",
          "size": 109969,
          "sha512": "aa4f0c1349a8f9836c9d4a3114423efa1602c5f593752d83000c621a0a511744d78434dd937847fcc07b914ca6e1f16addcb3ca047f57456e29d02e098fcb1a2",
          "sha256": "1d1e63cc74c5c2afce3ff6eb2e8763f31c0dbc84e3207a032d24f7b4bc2b2ddb",
          "sha1": "c2a4eb930adfb9208785fb7e6367a4adc590359c",
          "md5": "883a5b982c4cc25363757cc96fcb9ebb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.4-sources.jar",
          "url": "ble-characteristic-u2bad-0.8.4-sources.jar",
          "size": 1474,
          "sha512": "98dfb82ece6b39452d3d145f3f862b6b0fff9302c20aeef60a4bacf8d0a1727555d5eab508da609450631340fd2a2286a94a966812bdac3b4a6301e65f97a7ed",
          "sha256": "5f81ed4824a1efd0360ce5d350e7037a03a421fc603e5f55dc5ef7e67cef721a",
          "sha1": "0046125345b75453fab5345b3892679573be14ce",
          "md5": "4a19bc7eeb9fb8768d584349f1650805"
        }
      ]
    }
  ]
}
