{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-rtus-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a16-android",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17-android",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-android-0.1.1.aar",
          "url": "ble-service-rtus-android-0.1.1.aar",
          "size": 1207,
          "sha512": "c22d15f39f79eb7627de4fb9d95691929f1f145ffd950ae4d6ad0c106c391013f2336ed521b02ba2748346a47b81c5a72cc2eaf834d20d0a4c614486436e32eb",
          "sha256": "504d2029efcc2b28f45e4df2f472f0597a501dc108ecd11637879cfb7a292596",
          "sha1": "022aa820039964a0b82d296bb2f43bb7f43b107c",
          "md5": "3132e507b1c08270e37b11027e0f6823"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a16-android",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17-android",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-android-0.1.1.aar",
          "url": "ble-service-rtus-android-0.1.1.aar",
          "size": 1207,
          "sha512": "c22d15f39f79eb7627de4fb9d95691929f1f145ffd950ae4d6ad0c106c391013f2336ed521b02ba2748346a47b81c5a72cc2eaf834d20d0a4c614486436e32eb",
          "sha256": "504d2029efcc2b28f45e4df2f472f0597a501dc108ecd11637879cfb7a292596",
          "sha1": "022aa820039964a0b82d296bb2f43bb7f43b107c",
          "md5": "3132e507b1c08270e37b11027e0f6823"
        }
      ]
    }
  ]
}
