{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290b-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290b-android-0.4.0.aar",
          "url": "ble-descriptor-u290b-android-0.4.0.aar",
          "size": 3164,
          "sha512": "ba873895fe2c6eb1b04525d800fca54212733e321bb01abf5d115bbc4d46b404e352f5bf55e3cab75b6d253d2e6d1df74864c9d2d6286dac52abfe20c3f624e4",
          "sha256": "17288714a166bbeb11655b255276e560defe466acf06636c364dbe215e6eed9f",
          "sha1": "a1a66340d62e60a090cb201c8b8cc11006196c0f",
          "md5": "be624c47b2c84d9fc5e5917c777feff8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290b-android-0.4.0.aar",
          "url": "ble-descriptor-u290b-android-0.4.0.aar",
          "size": 3164,
          "sha512": "ba873895fe2c6eb1b04525d800fca54212733e321bb01abf5d115bbc4d46b404e352f5bf55e3cab75b6d253d2e6d1df74864c9d2d6286dac52abfe20c3f624e4",
          "sha256": "17288714a166bbeb11655b255276e560defe466acf06636c364dbe215e6eed9f",
          "sha1": "a1a66340d62e60a090cb201c8b8cc11006196c0f",
          "md5": "be624c47b2c84d9fc5e5917c777feff8"
        }
      ]
    }
  ]
}
