{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bls-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "didsxcdw7raejas3g75ob27utq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a35-android",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a36-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a49-android",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bls-android-0.1.5.aar",
          "url": "ble-service-bls-android-0.1.5.aar",
          "size": 1199,
          "sha512": "0da0f0660fce23d142f0cd2d38f326890fc9a063dcbb474ff31655c8b8faa7658eb65a27bc76371b4d01393b736d130fbdaa4a33555af26ea4b13b149633db9f",
          "sha256": "472c67cd0314e193e6a724d076e8f61e314581124fbcaff3691f42f86fade18a",
          "sha1": "6a00057c51adce68000ca9e0261a6d5d16d8c44d",
          "md5": "0d4e757ac0a135c7e80b9f7dad39198a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a35-android",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a36-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a49-android",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bls-android-0.1.5.aar",
          "url": "ble-service-bls-android-0.1.5.aar",
          "size": 1199,
          "sha512": "0da0f0660fce23d142f0cd2d38f326890fc9a063dcbb474ff31655c8b8faa7658eb65a27bc76371b4d01393b736d130fbdaa4a33555af26ea4b13b149633db9f",
          "sha256": "472c67cd0314e193e6a724d076e8f61e314581124fbcaff3691f42f86fade18a",
          "sha1": "6a00057c51adce68000ca9e0261a6d5d16d8c44d",
          "md5": "0d4e757ac0a135c7e80b9f7dad39198a"
        }
      ]
    }
  ]
}
