{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6d",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-0.8.12.jar",
          "url": "ble-characteristic-u2a6d-0.8.12.jar",
          "size": 1841,
          "sha512": "51adbe31963d9b2c41b69a58f7e816e5b416b266b753f5fbc75d6fb1c47ee1afb669c796cee1fc428c9f088b5a1c1d340ef0f28c14d74ad8e9aee6887b0c904b",
          "sha256": "a4ae179b073335e995c0960afff8781199d8f5b08ea276abfe9990efeeeb0661",
          "sha1": "2ddec514bc0fe186dcd489ad9a6ad996c5a5df81",
          "md5": "4320f22c74461dcebed7f39e7f86171d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6d-0.8.12.jar",
          "url": "ble-characteristic-u2a6d-0.8.12.jar",
          "size": 1841,
          "sha512": "51adbe31963d9b2c41b69a58f7e816e5b416b266b753f5fbc75d6fb1c47ee1afb669c796cee1fc428c9f088b5a1c1d340ef0f28c14d74ad8e9aee6887b0c904b",
          "sha256": "a4ae179b073335e995c0960afff8781199d8f5b08ea276abfe9990efeeeb0661",
          "sha1": "2ddec514bc0fe186dcd489ad9a6ad996c5a5df81",
          "md5": "4320f22c74461dcebed7f39e7f86171d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6d-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a6d-0.8.12-javadoc.jar",
          "size": 109264,
          "sha512": "6dc4dd15d265c792b6dc5ca808c3b86d7084ffec3cd61b9c728b362509f2a386fe3dc73a34af490321e199d572d4e555c22b18092ef453da7b1557497a12a795",
          "sha256": "d2a46e5a023b424a63c3db2c14d9e56bb7befc3e20541eacd54f3f3fb47e9909",
          "sha1": "0d13d024bfedb5a482ca0ed95ffc4ef2111243e6",
          "md5": "121063d51ad10a30d96963ca0a218b97"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6d-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a6d-0.8.12-sources.jar",
          "size": 1655,
          "sha512": "3ee673139436cb18c13a5c23a0d903b62e2ad1b704d9d6b95cd988227e1d249bc612d8feb3358176bc8096d2c7d4e9ff85342b4295faf6a5c7dc519f21fd5b6f",
          "sha256": "791247b366702bd3686bf06899d193fc473cc3a001228cb330677c521921ebdc",
          "sha1": "ab3b8800a3560fefa8751861778bd77fec2eb26b",
          "md5": "92af4d73743ce7a7766b7eae88355cde"
        }
      ]
    }
  ]
}
