{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4d",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-0.8.9.jar",
          "url": "ble-characteristic-u2a4d-0.8.9.jar",
          "size": 1468,
          "sha512": "240a1f4b7c0415d3f043b41f759f6c76ea06c8e7fb4b25e02f9ed01a921ad98a5f9c08cccf698564b4647a72b45ca1c150f2f29fdce45388958b9762c69b81f0",
          "sha256": "300e5bb631a92c4b804f9300731eef2f7ded9a49046660a13a4f94def105a052",
          "sha1": "f31f371fc1a027ccd2e6422ce4c5f9e27ea742af",
          "md5": "cf7e51dbd48581d5df53f4c577b274bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-0.8.9.jar",
          "url": "ble-characteristic-u2a4d-0.8.9.jar",
          "size": 1468,
          "sha512": "240a1f4b7c0415d3f043b41f759f6c76ea06c8e7fb4b25e02f9ed01a921ad98a5f9c08cccf698564b4647a72b45ca1c150f2f29fdce45388958b9762c69b81f0",
          "sha256": "300e5bb631a92c4b804f9300731eef2f7ded9a49046660a13a4f94def105a052",
          "sha1": "f31f371fc1a027ccd2e6422ce4c5f9e27ea742af",
          "md5": "cf7e51dbd48581d5df53f4c577b274bc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4d-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2a4d-0.8.9-javadoc.jar",
          "size": 107163,
          "sha512": "c675018558a597d7b984f357deb58502508808df471edee4f689b9e98b724e40107250902fc1c9dde1ecc8d28e286eec57a20feee2c9f9e0d3465aec5e9a54cd",
          "sha256": "c9aea3227431fac60ee0fbea295f376f1a062d8b2d076d4e7a5d3cc7d9749daf",
          "sha1": "5e049458066e4c853fff516b9d9ca28c9493148d",
          "md5": "b8bf579282dd4521d9b4fbbbcee73dbe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4d-0.8.9-sources.jar",
          "url": "ble-characteristic-u2a4d-0.8.9-sources.jar",
          "size": 1424,
          "sha512": "517abc13ef39e55375b21b70798c0b00f23b1434ff7d03cd60ae683efa6485df4f4fa9ed838de1ab538a8aae0f95026da22fe34ccde1ec19d12beb70eb9ebc69",
          "sha256": "5cf4c71f178d9567b21cda6c8642a5cfd58a8b23fd5817db90426a7ddd01b3e8",
          "sha1": "5e97d35034a57cf5fe0677a6b8a11b57df8c0747",
          "md5": "0f9dde4b69d082ce5ffb4b6b158f3e0a"
        }
      ]
    }
  ]
}
