{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab4-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.8.14.aar",
          "url": "ble-characteristic-u2ab4-android-0.8.14.aar",
          "size": 3125,
          "sha512": "306140443bfdf1e74dfbf39781506ab41c57cf5a0f7936a44a59295620638e066880bca7f44b0a39336acef617e6edabe9adc01a32119f97dab38fc7b21d87ff",
          "sha256": "e36f7416337c57ad8993c47ade41d2488616dc6e93c0fa8669c820da0ae61f01",
          "sha1": "498da51ff1018a1656330e84a2fe03636da666a4",
          "md5": "6fed81335a482a30836792a547a3d25a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.8.14.aar",
          "url": "ble-characteristic-u2ab4-android-0.8.14.aar",
          "size": 3125,
          "sha512": "306140443bfdf1e74dfbf39781506ab41c57cf5a0f7936a44a59295620638e066880bca7f44b0a39336acef617e6edabe9adc01a32119f97dab38fc7b21d87ff",
          "sha256": "e36f7416337c57ad8993c47ade41d2488616dc6e93c0fa8669c820da0ae61f01",
          "sha1": "498da51ff1018a1656330e84a2fe03636da666a4",
          "md5": "6fed81335a482a30836792a547a3d25a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2ab4-android-0.8.14-sources.jar",
          "size": 2177,
          "sha512": "ea8669de64cd40d4acb6cf4455a04dc7acc9f938e6dcc73982451f836766a52482fd0ddaeca5e23b213b4a163c7d8b1cdd7d7c94acc0ecde1b27432b5d21dda8",
          "sha256": "d0fa63bc798ba9d826bff075bfde884fa793f7d7a516f50b8b5ea5878c34a7ad",
          "sha1": "b9720a523e6a651233c7874d3843641aee691361",
          "md5": "0220505bc3302c89ec98ba0bab337213"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2ab4-android-0.8.14-javadoc.jar",
          "size": 271042,
          "sha512": "bdb0d49847bf9fa0798afba4c3e5b8f58074c8df13665365f7fad5947b8ce09ffbe20745a00183fbc64ba6e33bc458405059f9ecad46033f023d00f247e459d8",
          "sha256": "6179ae63ccbe1f5b116cf5527502946fbff4e224254ad252a6d52746493be770",
          "sha1": "a0ed0a11f8a2c2de2bcf52560eaec270ba162367",
          "md5": "045492582a1aeaafe0461baa6a61b01a"
        }
      ]
    }
  ]
}
