{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a53",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.6.jar",
          "url": "ble-characteristic-u2a53-0.8.6.jar",
          "size": 2951,
          "sha512": "b7e3d0520c5a4b9e7a0f0a152b02cb9f3df0fecd7a77ea60bee796914a37be5eec91a2c21867d6175451dd15e993e1029b91ffc5c89348c492d9844c5a38ab3e",
          "sha256": "6c6815aeef4683cae1921fe11c781e9cd03bd470c2ddb990ca238079b414f33c",
          "sha1": "4d9f8f34fb5e94cd256f8c3bdcb2b7068b82bcfe",
          "md5": "c2d67443b1d68fa8851f8209930cb50c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.6.jar",
          "url": "ble-characteristic-u2a53-0.8.6.jar",
          "size": 2951,
          "sha512": "b7e3d0520c5a4b9e7a0f0a152b02cb9f3df0fecd7a77ea60bee796914a37be5eec91a2c21867d6175451dd15e993e1029b91ffc5c89348c492d9844c5a38ab3e",
          "sha256": "6c6815aeef4683cae1921fe11c781e9cd03bd470c2ddb990ca238079b414f33c",
          "sha1": "4d9f8f34fb5e94cd256f8c3bdcb2b7068b82bcfe",
          "md5": "c2d67443b1d68fa8851f8209930cb50c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a53-0.8.6-javadoc.jar",
          "size": 111863,
          "sha512": "75dc1b24208c14f183716dfd424c31521ad12aa355491eea8e7b57e45216bc4b82c0b927ad36002f5e187cb874e8192f91abdc409f4d99a0a7175011fc43850f",
          "sha256": "742e2a78e4dce069229304be546638aa11bc81980554423bd1492a653aeb391b",
          "sha1": "396dcac8631378f5ff7a160cb65242e020d6e8bf",
          "md5": "7373a021a2f9f1e10c84ecc3e2e5966f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a53-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a53-0.8.6-sources.jar",
          "size": 2728,
          "sha512": "ada865a3cee6282d53bcfdad85d5fdbc6d9bc72f8b092449ad29d6686b23d52517232a030702e718552e2c0d60e421785149d0d0865b818a4be7486ff473ab20",
          "sha256": "187adb5840712b79cceb47ca23b6695e7e179dc805edf3010e12df05291e5aef",
          "sha1": "881c0a371f1cf797361ed587d3638506767639f0",
          "md5": "3bfe2ebc480327b5ef5c0afd7a5324b3"
        }
      ]
    }
  ]
}
