{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2c-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b2c",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2c-android-0.8.9.aar",
          "url": "ble-characteristic-u2b2c-android-0.8.9.aar",
          "size": 3125,
          "sha512": "6b3e7de684e0fcd3b699af55bad853ed6fc00305c27edbf9701b02a0485321af452436239437be17eb6311a36969b3215c0df45e4abf56c27ac3ed7ad4d0cb7b",
          "sha256": "36e7c49e18bdbcba0d64b26a2575b5c2dc87d1877a5b00b0d1e19de05fb7ca3f",
          "sha1": "6ed16231226f10fa17f540cb493ae5aca48b0b08",
          "md5": "fa89d51a409b4abe69d85ebee70e2221"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b2c",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2c-android-0.8.9.aar",
          "url": "ble-characteristic-u2b2c-android-0.8.9.aar",
          "size": 3125,
          "sha512": "6b3e7de684e0fcd3b699af55bad853ed6fc00305c27edbf9701b02a0485321af452436239437be17eb6311a36969b3215c0df45e4abf56c27ac3ed7ad4d0cb7b",
          "sha256": "36e7c49e18bdbcba0d64b26a2575b5c2dc87d1877a5b00b0d1e19de05fb7ca3f",
          "sha1": "6ed16231226f10fa17f540cb493ae5aca48b0b08",
          "md5": "fa89d51a409b4abe69d85ebee70e2221"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2c-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2b2c-android-0.8.9-sources.jar",
          "size": 2130,
          "sha512": "687a4d5c58a5b2e2bca0172197cf15c98b39e4c31eb749717cf2a2f37e1b0352a3fffbbcca04deb46662d9f8876993dcfbd1c3ed208c8048010d062cc3c1f591",
          "sha256": "5ff121af4b7e47e7fc6be0b4968ffc4d8bcbdd2344be7dfb35d640c0a95eb36f",
          "sha1": "daa5ca0d8469fa9f5754f8dee70680bce683da56",
          "md5": "eafa9e3b4a698a87df04f02ef968dac6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2c-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2b2c-android-0.8.9-javadoc.jar",
          "size": 268823,
          "sha512": "c6a0073ffbad7da4323de21a4918c59c1319cef0812846462da87ffb19849f791d55da705eb8d02384002c92f786e6d3e02e069e20e477e178003c2b0a1265f5",
          "sha256": "676abca5035b9d11ed9a9906641898df254b4a1a09e00b94939b43813b579912",
          "sha1": "0f9c22d093be5017bddaac193b2ee4c9862abf1a",
          "md5": "9c6135bcb55429187ce8b741108d8fdb"
        }
      ]
    }
  ]
}
