{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a90-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zckqgxv52jertg33sctsfjorzm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.2.2.aar",
          "url": "ble-characteristic-u2a90-android-0.2.2.aar",
          "size": 2766,
          "sha512": "d146aa80393687e014e8ecb7a1aaa38992f8bde22c0ddf9e32243d0e11592791716302bd7d179f2d2126d4a1c3887d3ce1d1496ecfbb8e0ab9a16cc97958733d",
          "sha256": "9c6a658e562de9892fc581843542c8ab542a1002527614759181076346b22aae",
          "sha1": "f59e65803f15566d566d94321aa4b0b4b7e6beeb",
          "md5": "7830d0ad0572d221d145afd63a5072a4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.2.2.aar",
          "url": "ble-characteristic-u2a90-android-0.2.2.aar",
          "size": 2766,
          "sha512": "d146aa80393687e014e8ecb7a1aaa38992f8bde22c0ddf9e32243d0e11592791716302bd7d179f2d2126d4a1c3887d3ce1d1496ecfbb8e0ab9a16cc97958733d",
          "sha256": "9c6a658e562de9892fc581843542c8ab542a1002527614759181076346b22aae",
          "sha1": "f59e65803f15566d566d94321aa4b0b4b7e6beeb",
          "md5": "7830d0ad0572d221d145afd63a5072a4"
        }
      ]
    }
  ]
}
