{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2b",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2b-0.8.7.jar",
          "url": "ble-characteristic-u2b2b-0.8.7.jar",
          "size": 1455,
          "sha512": "47812e0631654deaaeb398d30467ac5b89c70fc957fce5bbdb559c769451ab413a00af6908b252c877fe24450b78b28f38fb172eb4afba3fcc24265678ed1a4d",
          "sha256": "d834c2611f2c83d2b69098fdf52a406021651eaf13c5cef6fe37518562a280c6",
          "sha1": "b36602f48c8604f787ae51e9f7f32c9f2ab55f01",
          "md5": "3f00740b97297c8d58dc85cd81ae7f5b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2b-0.8.7.jar",
          "url": "ble-characteristic-u2b2b-0.8.7.jar",
          "size": 1455,
          "sha512": "47812e0631654deaaeb398d30467ac5b89c70fc957fce5bbdb559c769451ab413a00af6908b252c877fe24450b78b28f38fb172eb4afba3fcc24265678ed1a4d",
          "sha256": "d834c2611f2c83d2b69098fdf52a406021651eaf13c5cef6fe37518562a280c6",
          "sha1": "b36602f48c8604f787ae51e9f7f32c9f2ab55f01",
          "md5": "3f00740b97297c8d58dc85cd81ae7f5b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2b-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b2b-0.8.7-javadoc.jar",
          "size": 107166,
          "sha512": "399aa4165402de672c03293f97e6bcc8c6d56b7ab74f8def12ccae642e21da1d732e54d8ddc43117a75339ce9989c7ba66b2b6ffb53f73927d58a3d7add129e2",
          "sha256": "86c41eae9581a561071e2db3f919cdb296c354c3c0ffe17ceceaaf6e22f72691",
          "sha1": "ade5b4666e1930f7c6a4d2876a759ba42b0c0fa5",
          "md5": "dde099b172472c7f7346c7a267cdb745"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2b-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b2b-0.8.7-sources.jar",
          "size": 1449,
          "sha512": "d96025a1f7d36f567a970e7bb6960ba800af4fe28cef194f318f8f81360a2f54b4e29a121b9d12f8b4f596860e9ef532746bf37f02b93a4828bcd5fdab7588e9",
          "sha256": "9dff90af2499a16d2514f25869f62213c898e4ddae74cd44968ed915d413e782",
          "sha1": "2ea233f467c751a7ada425d48d03741ffdb509bd",
          "md5": "65c941919f958a4390bf8c67a1a79d08"
        }
      ]
    }
  ]
}
