{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-wss-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-android-0.4.6.aar",
          "url": "ble-service-wss-android-0.4.6.aar",
          "size": 1186,
          "sha512": "44d01fce16350d788e9183494e414249286bb47c307c643185781b08f2ea01b1dda92daf8c5bba7ac086a30f8f2dd36d5b38b036cc593c34877f2e37756f8fa0",
          "sha256": "12bc5e52c76a3cd735d94afc1a14d68aacaed6671a7c9338560517ba39797c85",
          "sha1": "1e4cfd78ef22a24fcfc3c952c5263704097c9c72",
          "md5": "ee80d69fa9bedc1ac69a6bc2204f8ce1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-android-0.4.6.aar",
          "url": "ble-service-wss-android-0.4.6.aar",
          "size": 1186,
          "sha512": "44d01fce16350d788e9183494e414249286bb47c307c643185781b08f2ea01b1dda92daf8c5bba7ac086a30f8f2dd36d5b38b036cc593c34877f2e37756f8fa0",
          "sha256": "12bc5e52c76a3cd735d94afc1a14d68aacaed6671a7c9338560517ba39797c85",
          "sha1": "1e4cfd78ef22a24fcfc3c952c5263704097c9c72",
          "md5": "ee80d69fa9bedc1ac69a6bc2204f8ce1"
        }
      ]
    }
  ]
}
