{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a90-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.2.8.aar",
          "url": "ble-characteristic-u2a90-android-0.2.8.aar",
          "size": 2949,
          "sha512": "c4f0e1afdf799ed1c5c3b194857d5483be4b0006064f72894e92d7cb235cefa47c7b7ad430f264286293912ef62eda7afe35e14ee1e4c2d821c33dc9172dfb32",
          "sha256": "8a560198fdeed154442a0eeb749c1a929574128cf71b37501b5485cfe53ceb65",
          "sha1": "adae7c848f9eda366b4c18e80ac0ac0a4a25bc94",
          "md5": "39697e51a0a76212d4e79398cdf1adc9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.2.8.aar",
          "url": "ble-characteristic-u2a90-android-0.2.8.aar",
          "size": 2949,
          "sha512": "c4f0e1afdf799ed1c5c3b194857d5483be4b0006064f72894e92d7cb235cefa47c7b7ad430f264286293912ef62eda7afe35e14ee1e4c2d821c33dc9172dfb32",
          "sha256": "8a560198fdeed154442a0eeb749c1a929574128cf71b37501b5485cfe53ceb65",
          "sha1": "adae7c848f9eda366b4c18e80ac0ac0a4a25bc94",
          "md5": "39697e51a0a76212d4e79398cdf1adc9"
        }
      ]
    }
  ]
}
