{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a68",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "e3ikqwiwsbdaddptppumhoyem4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a68-0.1.0.jar",
          "url": "ble-characteristic-u2a68-0.1.0.jar",
          "size": 3730,
          "sha512": "c0960171143fdd235dd441859c283558772960ab18e825cf29e1d9f5c062c7e0c3ce4731da2203d124bd16ffdbeb1479371101176c793a61528eb15739400f87",
          "sha256": "7e4b5a1e7fefd42853f3a5e5512f04968baaf3c9247f13ce714e4925dbee2dcb",
          "sha1": "620b79cd32b0a2549f2106011a89b67989e53db5",
          "md5": "b33a769a2c0999b1192691112d4b1204"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a68-0.1.0.jar",
          "url": "ble-characteristic-u2a68-0.1.0.jar",
          "size": 3730,
          "sha512": "c0960171143fdd235dd441859c283558772960ab18e825cf29e1d9f5c062c7e0c3ce4731da2203d124bd16ffdbeb1479371101176c793a61528eb15739400f87",
          "sha256": "7e4b5a1e7fefd42853f3a5e5512f04968baaf3c9247f13ce714e4925dbee2dcb",
          "sha1": "620b79cd32b0a2549f2106011a89b67989e53db5",
          "md5": "b33a769a2c0999b1192691112d4b1204"
        }
      ]
    }
  ]
}
