{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290b",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "zqydvf7ydfc6dl7zaoiukqttgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290b-0.1.0.jar",
          "url": "ble-descriptor-u290b-0.1.0.jar",
          "size": 1852,
          "sha512": "a57947ecb5a700f5df56d5173e04b1584a87cac4330ae8bea9b45392c923e7a69bfbf81a6e4a767881752f49bded7e9f602c51fa273b64b883396a576bbfc807",
          "sha256": "9bb8edf7eb92edc43e9a32268b554f5a270edb559bbe1939e15a99515ead3ef0",
          "sha1": "631fc93d0801b88c71c96cb51767f3f23b95be3d",
          "md5": "5ab0d565209bbdd9aa884c83f178e15e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290b-0.1.0.jar",
          "url": "ble-descriptor-u290b-0.1.0.jar",
          "size": 1852,
          "sha512": "a57947ecb5a700f5df56d5173e04b1584a87cac4330ae8bea9b45392c923e7a69bfbf81a6e4a767881752f49bded7e9f602c51fa273b64b883396a576bbfc807",
          "sha256": "9bb8edf7eb92edc43e9a32268b554f5a270edb559bbe1939e15a99515ead3ef0",
          "sha1": "631fc93d0801b88c71c96cb51767f3f23b95be3d",
          "md5": "5ab0d565209bbdd9aa884c83f178e15e"
        }
      ]
    }
  ]
}
