{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-htp-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-hts-android",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-htp-android-0.4.1.aar",
          "url": "ble-profile-central-htp-android-0.4.1.aar",
          "size": 5462,
          "sha512": "d37f030d5e8cd3ca987c98970b4c27cd6e0c9f2e02a56d660468d880a37020deb037a15d313aeef93c2b42dd9c0a7acdd965565d6c331d81e46a05a0bf0c4f5c",
          "sha256": "1aef024ff7264f7af047279dbee20a94bf59aeb47a5d43fcb9fc9a33bde37df0",
          "sha1": "ae5739f92186715dc02ced296d8e480d76e9df31",
          "md5": "0932508431751d24c3ac141060bf59d0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-hts-android",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-htp-android-0.4.1.aar",
          "url": "ble-profile-central-htp-android-0.4.1.aar",
          "size": 5462,
          "sha512": "d37f030d5e8cd3ca987c98970b4c27cd6e0c9f2e02a56d660468d880a37020deb037a15d313aeef93c2b42dd9c0a7acdd965565d6c331d81e46a05a0bf0c4f5c",
          "sha256": "1aef024ff7264f7af047279dbee20a94bf59aeb47a5d43fcb9fc9a33bde37df0",
          "sha1": "ae5739f92186715dc02ced296d8e480d76e9df31",
          "md5": "0932508431751d24c3ac141060bf59d0"
        }
      ]
    }
  ]
}
