{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a65-android",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.8.aar",
          "url": "ble-characteristic-u2a65-android-0.1.8.aar",
          "size": 3062,
          "sha512": "a6df3ac1c532989a5925f552f753cbace08c37f3fbe2641c2dcbfce87fa4e69317dc60193304c1b65c5cb94c373b87f83b950035188be354f1a43f7edbf460f2",
          "sha256": "584796a523d9bb5ac60e9806b644132ea34e64db830443d0fe35d4023c5b7a56",
          "sha1": "cc200e5b70de9fff48c31678b6a641e66f10c04d",
          "md5": "765c34773e27cf87ee5d918fe5a328a1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.8.aar",
          "url": "ble-characteristic-u2a65-android-0.1.8.aar",
          "size": 3062,
          "sha512": "a6df3ac1c532989a5925f552f753cbace08c37f3fbe2641c2dcbfce87fa4e69317dc60193304c1b65c5cb94c373b87f83b950035188be354f1a43f7edbf460f2",
          "sha256": "584796a523d9bb5ac60e9806b644132ea34e64db830443d0fe35d4023c5b7a56",
          "sha1": "cc200e5b70de9fff48c31678b6a641e66f10c04d",
          "md5": "765c34773e27cf87ee5d918fe5a328a1"
        }
      ]
    }
  ]
}
