{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "tgigj2sc2ba7vcxsvkfplwux5u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-peripheral",
          "version": {
            "requires": "0.2.23"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-android-0.1.5.aar",
          "url": "ble-service-peripheral-android-0.1.5.aar",
          "size": 2020,
          "sha512": "3b6f921b46b9f7a9a79ef3910c1dcbeb37d7c896056be2fb488f59328d3e092ae88aa1cf7375fc674b10e811fcde3b7f03e9fd720597afe6871c51564af6d5f7",
          "sha256": "b07e028de3f6de47c081e3ccb591076c03dcc0a57f04c10355857fd484261c6e",
          "sha1": "78743ac9d841eabbbea78929e4502bac04e6cee9",
          "md5": "527cc87da61a4ff39f36f2daea93a370"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-peripheral",
          "version": {
            "requires": "0.2.23"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-android-0.1.5.aar",
          "url": "ble-service-peripheral-android-0.1.5.aar",
          "size": 2020,
          "sha512": "3b6f921b46b9f7a9a79ef3910c1dcbeb37d7c896056be2fb488f59328d3e092ae88aa1cf7375fc674b10e811fcde3b7f03e9fd720597afe6871c51564af6d5f7",
          "sha256": "b07e028de3f6de47c081e3ccb591076c03dcc0a57f04c10355857fd484261c6e",
          "sha1": "78743ac9d841eabbbea78929e4502bac04e6cee9",
          "md5": "527cc87da61a4ff39f36f2daea93a370"
        }
      ]
    }
  ]
}
