{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b38",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b38-0.8.9.jar",
          "url": "ble-characteristic-u2b38-0.8.9.jar",
          "size": 1463,
          "sha512": "6aa51cc89717cb69e7b3ada3462450c2246e3fedbacdb528a3e5f6edc9d8403e6df04084729d0f56d64ef8740d4ee0d281486756e8c1befa046521df228aa321",
          "sha256": "66981ea8e82632d573011302ef8ed32659908567f856c6684d04b2d99b35f457",
          "sha1": "e2f1065e54561fc5a06cdd867eb55768ada382ce",
          "md5": "92b76f782e25132cf568da8b3b471e1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b38-0.8.9.jar",
          "url": "ble-characteristic-u2b38-0.8.9.jar",
          "size": 1463,
          "sha512": "6aa51cc89717cb69e7b3ada3462450c2246e3fedbacdb528a3e5f6edc9d8403e6df04084729d0f56d64ef8740d4ee0d281486756e8c1befa046521df228aa321",
          "sha256": "66981ea8e82632d573011302ef8ed32659908567f856c6684d04b2d99b35f457",
          "sha1": "e2f1065e54561fc5a06cdd867eb55768ada382ce",
          "md5": "92b76f782e25132cf568da8b3b471e1b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b38-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2b38-0.8.9-javadoc.jar",
          "size": 107209,
          "sha512": "b61aa7c6f57cac8d9b732b50c3f71bbf657af27da199d862f422b499673949aff598ca66ae91e4a9062889c09572b60a71e8e20c6c4e0f7f2d17ff1835144027",
          "sha256": "3ca557a49a7d45ab943925e4318b0c89f850b50a49d6f9a543f3c3b4d6230831",
          "sha1": "e5211faa8a955748d5d2d3258de77eafb1417fab",
          "md5": "e9db9f828dd6ac23d5a52a6413c91c54"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b38-0.8.9-sources.jar",
          "url": "ble-characteristic-u2b38-0.8.9-sources.jar",
          "size": 1464,
          "sha512": "001cbb0dcdf9eead7b8fb5dd21e375c7e38f7912844c80d71d034e698ec5ab1bf7a302d632b2b05297671af6dfa329410919d93c5e88b6547ffd8860b3c1865a",
          "sha256": "16c80efd0816d11db09cf138966f51f730cdc433141ed974a1aebf0a13f8078f",
          "sha1": "5d4beef2a53d4ec4627366736eea7c2ca958bcc9",
          "md5": "84d8d187391ce8576b8ba8c9a07dddd0"
        }
      ]
    }
  ]
}
