{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9e-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.4.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.4.aar",
          "size": 3204,
          "sha512": "184c2fbc1bcd50eb5243d1b53d646ae082cc63ef93de9827b845e5b9e4294f390b9fa8318ba93f74a22f1f6eb84f82a856d8130250d1aad14e9bbc5f7163db72",
          "sha256": "7997c363c41f3a8bd707e6dad4d2f6d854f104cff37058e903fa003cafbf766f",
          "sha1": "f23f8c6bd88f2c8fc3d999d53a022a4dbe328049",
          "md5": "4a02293d65bd4875d4441dbaeec5f664"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.4.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.4.aar",
          "size": 3204,
          "sha512": "184c2fbc1bcd50eb5243d1b53d646ae082cc63ef93de9827b845e5b9e4294f390b9fa8318ba93f74a22f1f6eb84f82a856d8130250d1aad14e9bbc5f7163db72",
          "sha256": "7997c363c41f3a8bd707e6dad4d2f6d854f104cff37058e903fa003cafbf766f",
          "sha1": "f23f8c6bd88f2c8fc3d999d53a022a4dbe328049",
          "md5": "4a02293d65bd4875d4441dbaeec5f664"
        }
      ]
    }
  ]
}
