{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b78",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.12.jar",
          "url": "ble-characteristic-u2b78-0.8.12.jar",
          "size": 1471,
          "sha512": "fa97d6cd843c160c4c28b9f719e5fd860f9b52d266df1298a2cb3e6457f3c48eae4a24c1fc5c80b760ad9b2866291c5ea2cbcab4b107e50b285b8c136076b2c1",
          "sha256": "9eb16dbd94306a535c1ba76b027db48acc2bdc04ed067fa57d3ceff259e88d68",
          "sha1": "a2779aeb6ba9e6a708659bfea6608ab2388ecfd8",
          "md5": "49d1ea5c1bb6898a1b6b1efbbddf9202"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.12.jar",
          "url": "ble-characteristic-u2b78-0.8.12.jar",
          "size": 1471,
          "sha512": "fa97d6cd843c160c4c28b9f719e5fd860f9b52d266df1298a2cb3e6457f3c48eae4a24c1fc5c80b760ad9b2866291c5ea2cbcab4b107e50b285b8c136076b2c1",
          "sha256": "9eb16dbd94306a535c1ba76b027db48acc2bdc04ed067fa57d3ceff259e88d68",
          "sha1": "a2779aeb6ba9e6a708659bfea6608ab2388ecfd8",
          "md5": "49d1ea5c1bb6898a1b6b1efbbddf9202"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b78-0.8.12-javadoc.jar",
          "size": 86021,
          "sha512": "6792486706285f3a15724096cb0f1e7ad5a4ed3e7ff719450d64d81446c7b57eaf426880530e92beb856d92fc0c753a9bb714fedf0a236e7a8b9a3ce80a826ec",
          "sha256": "4d1185f913f4998580ed5e58641856d0f15c32a6af3b4c8c4904b16e27d1eff6",
          "sha1": "2c007966acee18a5334046fb2f503ea713cc06a7",
          "md5": "ab4c7b2c9561208a7503541a76eaabcf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b78-0.8.12-sources.jar",
          "size": 1478,
          "sha512": "01bbccac034a7ddb2493bf49b950e66e853391805a2950124263814abc4a8521024d649a83aa2168160af60a9fe07f6c33567be4830589606218096f8d7ab0a6",
          "sha256": "80f9a1e8e39f3ca8f226a7eb03e2bc5174a9e8ea990c77af7e934a94a39bd20a",
          "sha1": "fba4d79238a8ef360a22db2bbf511bb6396db5fa",
          "md5": "624a540c4aaa20d6075bcddc5082d222"
        }
      ]
    }
  ]
}
