{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b08",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b08-0.4.6.jar",
          "url": "ble-characteristic-u2b08-0.4.6.jar",
          "size": 1984,
          "sha512": "4db59da6a58bf5835e0f42c543ad9e351e797da676e27beb2443a73f933435eeee92cc635b03722a2e05cafef5191e60d62c8a02316e4d9eb38c22f207ade52e",
          "sha256": "aaa0e249ce9a84f0ffa9ec2e80351d871bc45580f9ea6fb83a740d73edcd63ea",
          "sha1": "615fc168095f7fa7fb1ca67181011a0480d5fb92",
          "md5": "060ea2f5590a50ab522617d8db9e9930"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b08-0.4.6.jar",
          "url": "ble-characteristic-u2b08-0.4.6.jar",
          "size": 1984,
          "sha512": "4db59da6a58bf5835e0f42c543ad9e351e797da676e27beb2443a73f933435eeee92cc635b03722a2e05cafef5191e60d62c8a02316e4d9eb38c22f207ade52e",
          "sha256": "aaa0e249ce9a84f0ffa9ec2e80351d871bc45580f9ea6fb83a740d73edcd63ea",
          "sha1": "615fc168095f7fa7fb1ca67181011a0480d5fb92",
          "md5": "060ea2f5590a50ab522617d8db9e9930"
        }
      ]
    }
  ]
}
