{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a97-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a97",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a97-android-0.4.5.aar",
          "url": "ble-characteristic-u2a97-android-0.4.5.aar",
          "size": 3119,
          "sha512": "eadb9ec7ebad68afaf799e7224f94987193699a8c0f300178cfaf4cf2465ce1160ee95f87e1b839a73d0ba1218a84ad022fefa68e18e7578ff8af419195f84fd",
          "sha256": "250ec83abf977123d846ceff23343d969ebba292fe6411b9fbf0212d6d5a26e3",
          "sha1": "da7082c8fc53b8aeb1145bbff73081a7624e9ced",
          "md5": "0b0f7d18942ed9a01f51745bac13c55e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a97",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a97-android-0.4.5.aar",
          "url": "ble-characteristic-u2a97-android-0.4.5.aar",
          "size": 3119,
          "sha512": "eadb9ec7ebad68afaf799e7224f94987193699a8c0f300178cfaf4cf2465ce1160ee95f87e1b839a73d0ba1218a84ad022fefa68e18e7578ff8af419195f84fd",
          "sha256": "250ec83abf977123d846ceff23343d969ebba292fe6411b9fbf0212d6d5a26e3",
          "sha1": "da7082c8fc53b8aeb1145bbff73081a7624e9ced",
          "md5": "0b0f7d18942ed9a01f51745bac13c55e"
        }
      ]
    }
  ]
}
