{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bac-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bac",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bac-android-0.8.10.aar",
          "url": "ble-characteristic-u2bac-android-0.8.10.aar",
          "size": 3146,
          "sha512": "bc8f729fd013392c22f4a18a3038deb686caa564684cbbc37fee7b5cc20d763b4860fb9025c76a4d6be4238b5c91369e302b498571778dc1d7eb079ccf60048f",
          "sha256": "48083ef3b5e5fcf5c2874c29c46498bbc757eba877b183d74c6ab2cf368bb7a0",
          "sha1": "8e45f8e262284e632be817df3f4014c238f99e93",
          "md5": "baa1ba4b3da7d85e92572f2a934735d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bac",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bac-android-0.8.10.aar",
          "url": "ble-characteristic-u2bac-android-0.8.10.aar",
          "size": 3146,
          "sha512": "bc8f729fd013392c22f4a18a3038deb686caa564684cbbc37fee7b5cc20d763b4860fb9025c76a4d6be4238b5c91369e302b498571778dc1d7eb079ccf60048f",
          "sha256": "48083ef3b5e5fcf5c2874c29c46498bbc757eba877b183d74c6ab2cf368bb7a0",
          "sha1": "8e45f8e262284e632be817df3f4014c238f99e93",
          "md5": "baa1ba4b3da7d85e92572f2a934735d4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bac-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2bac-android-0.8.10-sources.jar",
          "size": 2152,
          "sha512": "7a34bf9b15d6efb380ae3e6d3969c6cea42033cbd46671f3426b413eb0beabfa82b6c3bdb2be5e59936bfc4de2b262e5cb394095b57c724757cc0d7a3df2899e",
          "sha256": "0e54d20093c3175872d52874bd117875ad0a8627ebca937fc3f20c950b8e860c",
          "sha1": "9aeb155752938485f8d6eb5c9f494315b74c1c21",
          "md5": "1da8771fb490cbb80ab4af3ba50e3251"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bac-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2bac-android-0.8.10-javadoc.jar",
          "size": 268855,
          "sha512": "83c0e9aa8ea56c14e1bcb65b282d107f9b35b46481a710be677a37632dcc772a2e518862cf385d87d8909849e197b8eb716dc60eb8c0888acd81117b75662235",
          "sha256": "99229ccc68aca0a9ddc6cbd92a2bff8fea44db06bd6e6091ee430318a2b2e43a",
          "sha1": "7473903a927acddc5251bf664a8380aebf8d1255",
          "md5": "8aff6fe68b1e9edb846be16a1d888301"
        }
      ]
    }
  ]
}
