{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5a-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5a",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5a-android-0.8.14.aar",
          "url": "ble-characteristic-u2a5a-android-0.8.14.aar",
          "size": 3082,
          "sha512": "6630094c26e06036e1ddac5db732dc540c31c3137b0785e5368caf08f1a42fb3c3aba6d5107725f6582e7d5856c644bc3e51140b85afc8968e21b663e2633865",
          "sha256": "ac03d81ceb541e64b9529f2ea1a830459021fc62278d8c1f717df69225a16f69",
          "sha1": "3fbff3037c1fd81dae58258c11b78f90a7656e93",
          "md5": "11864a6d58d93cc048bd53a03d0c2f55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5a",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5a-android-0.8.14.aar",
          "url": "ble-characteristic-u2a5a-android-0.8.14.aar",
          "size": 3082,
          "sha512": "6630094c26e06036e1ddac5db732dc540c31c3137b0785e5368caf08f1a42fb3c3aba6d5107725f6582e7d5856c644bc3e51140b85afc8968e21b663e2633865",
          "sha256": "ac03d81ceb541e64b9529f2ea1a830459021fc62278d8c1f717df69225a16f69",
          "sha1": "3fbff3037c1fd81dae58258c11b78f90a7656e93",
          "md5": "11864a6d58d93cc048bd53a03d0c2f55"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5a-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2a5a-android-0.8.14-sources.jar",
          "size": 2145,
          "sha512": "a576c7565b498369a62aca9f25f962b671bd70ebca582e98a9b5a9ec34bc260ca968da006ade8c09c625b6c0920e83aba572bd86f4526974f7faaa245f61e1fc",
          "sha256": "27e8b1d0f7ef8d33a1ceb92af7f3c6d48fc73bfa58fb379020d7a663272c5e93",
          "sha1": "a454b4652571588988ea1430c51a8c2344c19437",
          "md5": "2c76417e84dc41f2e6fcf2943c454a90"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5a-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2a5a-android-0.8.14-javadoc.jar",
          "size": 270987,
          "sha512": "820ed48ca9ec8b81c89c12458587bf86357a5328d2d847b839189d3610a4e65d8c91b506831ae6986c65b19021bdd75e5ea14e659b3b058c94439cfb40e57a31",
          "sha256": "5a31a97964af553f1d0b556a029619b7dfbfc60082e5b85262206f81cea35b7b",
          "sha1": "f726cb56010296e745886817cba75ec6981fdbb3",
          "md5": "5e234d62ee342b2ca98de1c019e7acf1"
        }
      ]
    }
  ]
}
