{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-test",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-test-0.8.13.jar",
          "url": "ble-test-0.8.13.jar",
          "size": 1936,
          "sha512": "c53c3967caf020a8785653ebbefbcc4aa6850d17282f106e191cb9f58bd7205555b4f49ac2516e68e083be1ee6743d562f908dda56de3c263c9681a8d5bafa1b",
          "sha256": "8f0a39fbb9a3ce6bf070aded5d552cd8c9d60e2164de9d6a4ac8729ab5a470ae",
          "sha1": "1c79065ba26d9b5d8a486d514e67f637cf787710",
          "md5": "9a6e72c741183e829f508788652129d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-test-0.8.13.jar",
          "url": "ble-test-0.8.13.jar",
          "size": 1936,
          "sha512": "c53c3967caf020a8785653ebbefbcc4aa6850d17282f106e191cb9f58bd7205555b4f49ac2516e68e083be1ee6743d562f908dda56de3c263c9681a8d5bafa1b",
          "sha256": "8f0a39fbb9a3ce6bf070aded5d552cd8c9d60e2164de9d6a4ac8729ab5a470ae",
          "sha1": "1c79065ba26d9b5d8a486d514e67f637cf787710",
          "md5": "9a6e72c741183e829f508788652129d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-test-0.8.13-javadoc.jar",
          "url": "ble-test-0.8.13-javadoc.jar",
          "size": 84961,
          "sha512": "30328238f81626d147329fc36957612c4ddd0bd2f8e0040ddfcc9d65031d93e811078e983c321633265dafb5125d0ee685bf2f132a6a2ba4397fb683bfe4588f",
          "sha256": "ba73bc9c3901336b52c47cb2e0224b0ddc4a79f69e97dafeedc4f916c2f9151c",
          "sha1": "f699c6ce73f54b8f241c18cde4fdb4770ead6ba7",
          "md5": "9f72b9c5f3196ede9799ea2f0cb7502d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-test-0.8.13-sources.jar",
          "url": "ble-test-0.8.13-sources.jar",
          "size": 1320,
          "sha512": "48f6697059d70fd6d06d89ba45a7d8c80cddaa8852ef65aa5697ba7d1035bc9970af2a823ff75ed49ed6c2700e9ab119c8937d86a1895ad13ca8ed50594147df",
          "sha256": "da7c851145e5a219af79baa508c8c7d36384531cf61100ea4d86e898b692e05d",
          "sha1": "768a74ce27942f1666f212bd01117b5a497fd906",
          "md5": "54b357994f8bf45c639031dc3881e889"
        }
      ]
    }
  ]
}
