{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a85-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.8.14.aar",
          "url": "ble-characteristic-u2a85-android-0.8.14.aar",
          "size": 3163,
          "sha512": "d6c81bc211bea849eff12d9ba650ad33e0245c1dc53f3abc47b6709854d181ee7ddb3f6d81e7bb03bd4481cc9ad6409950b6c1ac67eeccb80072446732fbc873",
          "sha256": "8d93df0583bbcb0f59d3c3ef06b1ae1ee050d1d298a3037a77d4eebf96b436f0",
          "sha1": "116fe719391e7dc235d6049e2efac9265186d242",
          "md5": "322f9a5328fab0db64ebe9c1fbd0f880"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.8.14.aar",
          "url": "ble-characteristic-u2a85-android-0.8.14.aar",
          "size": 3163,
          "sha512": "d6c81bc211bea849eff12d9ba650ad33e0245c1dc53f3abc47b6709854d181ee7ddb3f6d81e7bb03bd4481cc9ad6409950b6c1ac67eeccb80072446732fbc873",
          "sha256": "8d93df0583bbcb0f59d3c3ef06b1ae1ee050d1d298a3037a77d4eebf96b436f0",
          "sha1": "116fe719391e7dc235d6049e2efac9265186d242",
          "md5": "322f9a5328fab0db64ebe9c1fbd0f880"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2a85-android-0.8.14-sources.jar",
          "size": 2213,
          "sha512": "975d723b5142318dcc5954d3c3674c12f7e55ae73d604e5b5513ef9a3aa26df0ff982c1c24e610ce04cad615bf2ba4e017739cb8c3bad1d23fc9f815903b3c09",
          "sha256": "0db78f8641722c06157fdecf9bcaf3d04ff5e7a0d8d6605cd40481a9880646dc",
          "sha1": "588f81c2f52bd7e43806ee6315a3e0b0e1c23188",
          "md5": "e1d7d3a0f6fcb1482e7aa3f801ff60c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2a85-android-0.8.14-javadoc.jar",
          "size": 269506,
          "sha512": "7d2aa31efc3731563f6add3312874809dfd5b57dba5d2e7e58b4e24da846028f9d7fc18d46ec3df37f89a442b288b0f9edcef6155cfcf50908f8d68b27f02815",
          "sha256": "614c5dcb6380ecd69b2872b3fb5ac693b25a743b9976bbbae91945ad47b8e878",
          "sha1": "43f83621621a7fedf92bc2884ae7761f18cc9def",
          "md5": "a342c8eb54aef4d6503077904d79997f"
        }
      ]
    }
  ]
}
