{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-android",
    "version": "0.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "didsxcdw7raejas3g75ob27utq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-blp-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-blp-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-lnp-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-lnp-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-fmp-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-fmp-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-pxp-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-pxp-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-hrp-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-hrp-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-htp-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-htp-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-wsp-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-wsp-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-aiop-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-aiop-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-anp-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-anp-central-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-tip-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-tip-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-android-0.1.13.aar",
          "url": "ble-profile-android-0.1.13.aar",
          "size": 1195,
          "sha512": "0b62ce45b95f2d49ae905f999313344bea4df670e1f7c3088b3d86ec2873ce739c281e452e638318f53306180c0bf0d16cc5d8a0af611c1592a36a218bd4662d",
          "sha256": "716484951785e400c5998d91f9fa11c179cbc1075774ff21bb02579082a09cd6",
          "sha1": "e2434bdef70b15fa07ae3780436d403e597dcced",
          "md5": "1a74f323eb86f22e2892dfc95ebc73ed"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-blp-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-blp-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-lnp-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-lnp-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-fmp-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-fmp-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-pxp-peripheral-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-pxp-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-hrp-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-hrp-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-htp-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-htp-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-wsp-peripheral-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-wsp-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-aiop-peripheral-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-aiop-central-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-anp-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-anp-central-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-tip-peripheral-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-profile-tip-central-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-android-0.1.13.aar",
          "url": "ble-profile-android-0.1.13.aar",
          "size": 1195,
          "sha512": "0b62ce45b95f2d49ae905f999313344bea4df670e1f7c3088b3d86ec2873ce739c281e452e638318f53306180c0bf0d16cc5d8a0af611c1592a36a218bd4662d",
          "sha256": "716484951785e400c5998d91f9fa11c179cbc1075774ff21bb02579082a09cd6",
          "sha1": "e2434bdef70b15fa07ae3780436d403e597dcced",
          "md5": "1a74f323eb86f22e2892dfc95ebc73ed"
        }
      ]
    }
  ]
}
