{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a95-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a95",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a95-android-0.8.13.aar",
          "url": "ble-characteristic-u2a95-android-0.8.13.aar",
          "size": 3168,
          "sha512": "4a536d080bcc622ad36ae6e3c0cd5ac8d046a2f6ed4c5c225061e9c73b168df1439bcc107a5bd5e3b77fc98c29f022dc845860cb26a817596192bdd75ef018c9",
          "sha256": "53738e089bfd0344f647af29db5cc28406418b64271d34828bb188724837e0f1",
          "sha1": "3a1b2576787c25eca65738e0015061c9aeeddb16",
          "md5": "e59e5702173a9b06419dbc7ee7f03102"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a95",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a95-android-0.8.13.aar",
          "url": "ble-characteristic-u2a95-android-0.8.13.aar",
          "size": 3168,
          "sha512": "4a536d080bcc622ad36ae6e3c0cd5ac8d046a2f6ed4c5c225061e9c73b168df1439bcc107a5bd5e3b77fc98c29f022dc845860cb26a817596192bdd75ef018c9",
          "sha256": "53738e089bfd0344f647af29db5cc28406418b64271d34828bb188724837e0f1",
          "sha1": "3a1b2576787c25eca65738e0015061c9aeeddb16",
          "md5": "e59e5702173a9b06419dbc7ee7f03102"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a95-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2a95-android-0.8.13-sources.jar",
          "size": 2249,
          "sha512": "0a8e1149dfa82150279d24d3734812a3561fe6e6c394117c1ef1f7a581a4ae168cb7063e77a56f53c2a0e337ecaed2eb029826263d50377ce40ac12423e152d0",
          "sha256": "52aa7e243db9eb84bdb56bb847749e29704ef64571a2fc0390c43eda5b46dbca",
          "sha1": "0600844c03ada584b2710c05df8ec2cee0c3b88d",
          "md5": "8480553b2b0cd90c81db7a98d43477f6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a95-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2a95-android-0.8.13-javadoc.jar",
          "size": 271262,
          "sha512": "ab3ebdf74e352917e3f14841d90fb53c38ed4d56ebde65d9ea7172d57e2b4bea6f4e7373e0f96504669a29ed84778e82a7d495e27043934a50d2781540371c16",
          "sha256": "582974b8a94accde50642d44067dc015ab883f251ed5162db1befc4279db552a",
          "sha1": "d1202978b57c99417669c94c19dff21f174f04f0",
          "md5": "8fa5f0d84176379cdb4c35fd62891860"
        }
      ]
    }
  ]
}
