{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-tps-central-android",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-tps-central-android-0.1.7.aar",
          "url": "ble-service-tps-central-android-0.1.7.aar",
          "size": 3217,
          "sha512": "fc6b5db37905936e4ba895a53ae3cb98d6f7631a818d35fc2bf2715008916f6464e3081fe1e041cca0b30fdaa290e9c360ad9212b2c2c1ffd1d133a31d3d9037",
          "sha256": "ac36d51359e8721596910e828dc49d7af9afe641b49792e7b54f23fdeb812247",
          "sha1": "44b4fe6cb809cc82537b795ca9c770a5427856e2",
          "md5": "66dd94ce77bc8aadbce090f8a5446ca5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-tps-central-android-0.1.7.aar",
          "url": "ble-service-tps-central-android-0.1.7.aar",
          "size": 3217,
          "sha512": "fc6b5db37905936e4ba895a53ae3cb98d6f7631a818d35fc2bf2715008916f6464e3081fe1e041cca0b30fdaa290e9c360ad9212b2c2c1ffd1d133a31d3d9037",
          "sha256": "ac36d51359e8721596910e828dc49d7af9afe641b49792e7b54f23fdeb812247",
          "sha1": "44b4fe6cb809cc82537b795ca9c770a5427856e2",
          "md5": "66dd94ce77bc8aadbce090f8a5446ca5"
        }
      ]
    }
  ]
}
