{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-gatt-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a02-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa6-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac9-android",
          "version": {
            "requires": "0.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-gatt-android-0.1.0.aar",
          "url": "ble-service-gatt-android-0.1.0.aar",
          "size": 1205,
          "sha512": "e4c6ae40341df567a312575b14625da431ccc65514267b8227511a2be67886f19180dc0d9d47336c47361dcbcb2fb7fdea0ea78ad0ac3d9fdf12d709970ba0e9",
          "sha256": "4aa2fef2d56a81ae08bcf2dbcfa5fee5f4c5ff0d4c03cad42a1ddf92cb1c7e90",
          "sha1": "3a1f472f603decf7d234276221cd9dc858ab0df2",
          "md5": "2044eb2993e45b6b4e6580c133bbafbd"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a02-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa6-android",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac9-android",
          "version": {
            "requires": "0.2.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-gatt-android-0.1.0.aar",
          "url": "ble-service-gatt-android-0.1.0.aar",
          "size": 1205,
          "sha512": "e4c6ae40341df567a312575b14625da431ccc65514267b8227511a2be67886f19180dc0d9d47336c47361dcbcb2fb7fdea0ea78ad0ac3d9fdf12d709970ba0e9",
          "sha256": "4aa2fef2d56a81ae08bcf2dbcfa5fee5f4c5ff0d4c03cad42a1ddf92cb1c7e90",
          "sha1": "3a1f472f603decf7d234276221cd9dc858ab0df2",
          "md5": "2044eb2993e45b6b4e6580c133bbafbd"
        }
      ]
    }
  ]
}
