{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1d",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "zntzl6h5ifdqnivyseqzz436ba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1d-0.2.0.jar",
          "url": "ble-characteristic-u2a1d-0.2.0.jar",
          "size": 1733,
          "sha512": "f9307cb60d193208489a0622d61668c1c988d516e33766e9d4ccbe5f8be3d3ce0f4fdc36b34b6a551ed73c5c6ad437c476f95eaf1924037ebca49100e8336291",
          "sha256": "b9aa9352a1ea6228804027cddf4a71e1918fa3e623c4468f1c58183c64902e65",
          "sha1": "4b9c81dd866a83a1e59e06ac05e7b3e229beb033",
          "md5": "3401b4eb10e68e57e3136bf433467e33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1d-0.2.0.jar",
          "url": "ble-characteristic-u2a1d-0.2.0.jar",
          "size": 1733,
          "sha512": "f9307cb60d193208489a0622d61668c1c988d516e33766e9d4ccbe5f8be3d3ce0f4fdc36b34b6a551ed73c5c6ad437c476f95eaf1924037ebca49100e8336291",
          "sha256": "b9aa9352a1ea6228804027cddf4a71e1918fa3e623c4468f1c58183c64902e65",
          "sha1": "4b9c81dd866a83a1e59e06ac05e7b3e229beb033",
          "md5": "3401b4eb10e68e57e3136bf433467e33"
        }
      ]
    }
  ]
}
