{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b99-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b99",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b99-android-0.8.14.aar",
          "url": "ble-characteristic-u2b99-android-0.8.14.aar",
          "size": 3091,
          "sha512": "26c968c72cf1c5c494a85124a5673cc8c8b721fa35220f867f2fc8fd90b64c29ead6e16eb3fb13a00874405b1e923a402da7cd90d94b035a4d534fbef2c5bf0a",
          "sha256": "4293a7ab4e5ffd4168515b11b27679019efd9fb83a08eb8b40e598e419fcd84f",
          "sha1": "5192be9fbaf3c9f633dce9cffc8756edb3cc3c05",
          "md5": "a4f0c97837b72264fddb7a93ae25e5a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b99",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b99-android-0.8.14.aar",
          "url": "ble-characteristic-u2b99-android-0.8.14.aar",
          "size": 3091,
          "sha512": "26c968c72cf1c5c494a85124a5673cc8c8b721fa35220f867f2fc8fd90b64c29ead6e16eb3fb13a00874405b1e923a402da7cd90d94b035a4d534fbef2c5bf0a",
          "sha256": "4293a7ab4e5ffd4168515b11b27679019efd9fb83a08eb8b40e598e419fcd84f",
          "sha1": "5192be9fbaf3c9f633dce9cffc8756edb3cc3c05",
          "md5": "a4f0c97837b72264fddb7a93ae25e5a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b99-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2b99-android-0.8.14-sources.jar",
          "size": 2163,
          "sha512": "30a9563ce97e28baaa64dc56321e22a87e57af30ecddf38984c275a1823ad145eda56c61dc4e26ffb37ae5de0ca67f1bd28ce77f83eb836833716ae6b96ae86f",
          "sha256": "0f22a677c0c86a78cfe8eab8d17da694b08572084014789a25e54791d7ea8f32",
          "sha1": "a15727308021c1dedd61cb890b763b89f950ae02",
          "md5": "241c10b2f75cdff65b5a7e4587cb9857"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b99-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2b99-android-0.8.14-javadoc.jar",
          "size": 270985,
          "sha512": "37ec5e4ad6d6bd48a697f2834de47d01e537ef3c8d8066f1a335341912c956955867cd303217b08a1e22593db45ea2dc372392f681ef15a3a42d1ebf238a523e",
          "sha256": "a5d08ed17d47ed956193a7df68b9d26684dc981fc81397f840315fb7d1984139",
          "sha1": "cdadaf7ce38e2813b104d8ad6eff0f7652c6f745",
          "md5": "cd54f2f0149c118767e23b98ed388773"
        }
      ]
    }
  ]
}
