{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290b-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290b-android-0.2.6.aar",
          "url": "ble-descriptor-u290b-android-0.2.6.aar",
          "size": 3138,
          "sha512": "dc2781d94817c81f1e11eda4d480aaaf00cffd30ba10834c3966a3c8f2d7123b2b7752ae363ca4f183c7a10ddefe102b82d980fa37d2fc5df360e1780ef49d52",
          "sha256": "251d6b597dba5978b6d5ceb16e5cf2d6ba21b833f975e9304043871b21bb128a",
          "sha1": "eb48e377a3d3d1316751ca9474b686b5efafb74b",
          "md5": "37343349ff52fec76a7b88a653493f6f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290b",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290b-android-0.2.6.aar",
          "url": "ble-descriptor-u290b-android-0.2.6.aar",
          "size": 3138,
          "sha512": "dc2781d94817c81f1e11eda4d480aaaf00cffd30ba10834c3966a3c8f2d7123b2b7752ae363ca4f183c7a10ddefe102b82d980fa37d2fc5df360e1780ef49d52",
          "sha256": "251d6b597dba5978b6d5ceb16e5cf2d6ba21b833f975e9304043871b21bb128a",
          "sha1": "eb48e377a3d3d1316751ca9474b686b5efafb74b",
          "md5": "37343349ff52fec76a7b88a653493f6f"
        }
      ]
    }
  ]
}
