{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a93-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.2.9.aar",
          "url": "ble-characteristic-u2a93-android-0.2.9.aar",
          "size": 3228,
          "sha512": "06d1230cde296b68ce84746b4d0df534ac0ba7248419a093eec87a7dbd78d5c8cc0889d13673fe924488d5cb50707d3d8e5120710c5f6b4b84ad0e4289a779ed",
          "sha256": "ce08179d423967daa13229156442a0534a5d6954c8d5051eb43d33f95c471b03",
          "sha1": "a06be5b764ffd59033da95c9d0474d6ea2963eae",
          "md5": "41a174c8586b5b7ae2f9008681da4ec8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.2.9.aar",
          "url": "ble-characteristic-u2a93-android-0.2.9.aar",
          "size": 3228,
          "sha512": "06d1230cde296b68ce84746b4d0df534ac0ba7248419a093eec87a7dbd78d5c8cc0889d13673fe924488d5cb50707d3d8e5120710c5f6b4b84ad0e4289a779ed",
          "sha256": "ce08179d423967daa13229156442a0534a5d6954c8d5051eb43d33f95c471b03",
          "sha1": "a06be5b764ffd59033da95c9d0474d6ea2963eae",
          "md5": "41a174c8586b5b7ae2f9008681da4ec8"
        }
      ]
    }
  ]
}
