{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a01-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-android-0.1.4.aar",
          "url": "ble-characteristic-u2a01-android-0.1.4.aar",
          "size": 3022,
          "sha512": "ff04153e19d657b0cbb7a71cd02d6ec9d56fb1ddc348c0ad287eb04dbd51843a48117a9ddf00431fd4196655a8497942cc1cf9741f7b51c5a663a39ac48da217",
          "sha256": "f09e55cb80789380436c041f6f9bf31da5faf8c0c11e81c8c13ed66fecfdb4ab",
          "sha1": "b95de364cd82db46d1a41288c580b91432c71c02",
          "md5": "85892c86d3d56502dd7a64bb5347def6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-android-0.1.4.aar",
          "url": "ble-characteristic-u2a01-android-0.1.4.aar",
          "size": 3022,
          "sha512": "ff04153e19d657b0cbb7a71cd02d6ec9d56fb1ddc348c0ad287eb04dbd51843a48117a9ddf00431fd4196655a8497942cc1cf9741f7b51c5a663a39ac48da217",
          "sha256": "f09e55cb80789380436c041f6f9bf31da5faf8c0c11e81c8c13ed66fecfdb4ab",
          "sha1": "b95de364cd82db46d1a41288c580b91432c71c02",
          "md5": "85892c86d3d56502dd7a64bb5347def6"
        }
      ]
    }
  ]
}
