{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bbe",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbe-0.8.14.jar",
          "url": "ble-characteristic-u2bbe-0.8.14.jar",
          "size": 1457,
          "sha512": "23ac3d1be16181d6c819d99b71e52a78e1730eb638267c05afc9fb0efbde4b824707cde34e236da88d6ad331a3dcc9099e9c9b0061cd4c9ef2da7f9726e98f97",
          "sha256": "9e9c317a22b237093d4a40246ec7fa99fc4022b22be208dd1e3524fa303aaa0a",
          "sha1": "4ff1b8e9dacc643a0f71c9e0a2ff9df683ad9f58",
          "md5": "1ff82bf6ea3383ab946731fee7335d6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbe-0.8.14.jar",
          "url": "ble-characteristic-u2bbe-0.8.14.jar",
          "size": 1457,
          "sha512": "23ac3d1be16181d6c819d99b71e52a78e1730eb638267c05afc9fb0efbde4b824707cde34e236da88d6ad331a3dcc9099e9c9b0061cd4c9ef2da7f9726e98f97",
          "sha256": "9e9c317a22b237093d4a40246ec7fa99fc4022b22be208dd1e3524fa303aaa0a",
          "sha1": "4ff1b8e9dacc643a0f71c9e0a2ff9df683ad9f58",
          "md5": "1ff82bf6ea3383ab946731fee7335d6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbe-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2bbe-0.8.14-javadoc.jar",
          "size": 85972,
          "sha512": "41899ceeddd205ea3438d2f5ca373e44853012680ec8c544383700c2230246d2d97f0ec4ab7965547c1b1a8ce711a2e06fb0eceeaf902aa9f335d2bc29ec72d9",
          "sha256": "cb3f765ebabd6134aa945798d63e8c870619dba4350cc3ef31ec84ea1b282f37",
          "sha1": "cde27c54ba8b435485ed6b720fdec8bffa7fd79b",
          "md5": "6582b98725b881da5e649e05dfeeae78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbe-0.8.14-sources.jar",
          "url": "ble-characteristic-u2bbe-0.8.14-sources.jar",
          "size": 1452,
          "sha512": "fe925eb5cbf6f1c9bc4529c44494bbd37123fc9916064de22f91d2b6515492787c69248a0cc916e866f7cbc336068c9590c074e2c4c13f80f472f9f3f8e73b8b",
          "sha256": "34e45b9a11e0af4f50b19434f2b2cc12ae62132e245f58aab05cce78a319e15e",
          "sha1": "69cf55f23913a07449d1433165c2282425b58f15",
          "md5": "40a2aee965f3e7e7edd320c2ed83f3b9"
        }
      ]
    }
  ]
}
