{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4e-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4e",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-android-0.4.1.aar",
          "url": "ble-characteristic-u2a4e-android-0.4.1.aar",
          "size": 3106,
          "sha512": "c0e5a524a3ff5888d75edeaf3c4197b444ecc0d1c9e509c5fdc6d2a08107fc8e3019c65237fbe7f4e7d56d2152b70f1995df75733c3088b7044b13880260085b",
          "sha256": "5cf31f7abc7bd07302bba6a50af45c41886c797f80bb6f091ad8ae576b530100",
          "sha1": "e99559ea1ff0dc1ff6d09c5ffccddf979fd86fda",
          "md5": "53db4c17a2c0e674906c06b71543d282"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4e",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-android-0.4.1.aar",
          "url": "ble-characteristic-u2a4e-android-0.4.1.aar",
          "size": 3106,
          "sha512": "c0e5a524a3ff5888d75edeaf3c4197b444ecc0d1c9e509c5fdc6d2a08107fc8e3019c65237fbe7f4e7d56d2152b70f1995df75733c3088b7044b13880260085b",
          "sha256": "5cf31f7abc7bd07302bba6a50af45c41886c797f80bb6f091ad8ae576b530100",
          "sha1": "e99559ea1ff0dc1ff6d09c5ffccddf979fd86fda",
          "md5": "53db4c17a2c0e674906c06b71543d282"
        }
      ]
    }
  ]
}
