{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8e",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xnyhilluxvgr3nzweyacpeoi5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8e-0.2.2.jar",
          "url": "ble-characteristic-u2a8e-0.2.2.jar",
          "size": 1835,
          "sha512": "4d6239957a5d6ea33208bfe2308b97287f2ab76f201588f9ff02343661b08cb1af9937070e17dcd25da5bec76583bc39663a43d5776c35ffeaf4fe6980bc8211",
          "sha256": "f33e094a8b61501496f947aaead088019955d1c1858941b5ac1159eb1ac5b9ac",
          "sha1": "9f00c1f5d972fa9d97f04f797eee0a11186ec69d",
          "md5": "04110987026871b23e1c8bef3a34df74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8e-0.2.2.jar",
          "url": "ble-characteristic-u2a8e-0.2.2.jar",
          "size": 1835,
          "sha512": "4d6239957a5d6ea33208bfe2308b97287f2ab76f201588f9ff02343661b08cb1af9937070e17dcd25da5bec76583bc39663a43d5776c35ffeaf4fe6980bc8211",
          "sha256": "f33e094a8b61501496f947aaead088019955d1c1858941b5ac1159eb1ac5b9ac",
          "sha1": "9f00c1f5d972fa9d97f04f797eee0a11186ec69d",
          "md5": "04110987026871b23e1c8bef3a34df74"
        }
      ]
    }
  ]
}
