{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8f-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8f-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8f-android-0.2.1.aar",
          "size": 2921,
          "sha512": "7ba1c30083cf6cdf1dc5e32cf0a7fa9ca235dcddef0a3c5dc165950ad698c6c60b7c0303bd4dd39f5ffb5e5acc75eaaf86a188a39ef8d85241f5776010bc2283",
          "sha256": "c49038ff1a4362842cb4e214acb692be66b32c8046f4fca5a90de6500b6ef5e1",
          "sha1": "12cc326055df0475482a7fce35a1c663788ba1e0",
          "md5": "a652593f66c75ca9c9cd3f818681e133"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8f-android-0.2.1.aar",
          "url": "ble-characteristic-u2a8f-android-0.2.1.aar",
          "size": 2921,
          "sha512": "7ba1c30083cf6cdf1dc5e32cf0a7fa9ca235dcddef0a3c5dc165950ad698c6c60b7c0303bd4dd39f5ffb5e5acc75eaaf86a188a39ef8d85241f5776010bc2283",
          "sha256": "c49038ff1a4362842cb4e214acb692be66b32c8046f4fca5a90de6500b6ef5e1",
          "sha1": "12cc326055df0475482a7fce35a1c663788ba1e0",
          "md5": "a652593f66c75ca9c9cd3f818681e133"
        }
      ]
    }
  ]
}
