{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b46-android",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b46",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b46-android-0.5.1.aar",
          "url": "ble-characteristic-u2b46-android-0.5.1.aar",
          "size": 3025,
          "sha512": "e85e2bb4b84e603950658c61bc62e203c79bc40ebf23ea76532fed2f29e84589ab1285821c28e47b545869298a4134e28cc71427865cbe13fd33979c60b32767",
          "sha256": "5cca584c55108219cd6e8edac66d1610cc1623cbec0df788a9b22b644dda6cf9",
          "sha1": "96ec361f5c32d96f5fda38b0b760b9bb0c8a8496",
          "md5": "79ffaa280b9561b78088ce6b0e90c005"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b46",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b46-android-0.5.1.aar",
          "url": "ble-characteristic-u2b46-android-0.5.1.aar",
          "size": 3025,
          "sha512": "e85e2bb4b84e603950658c61bc62e203c79bc40ebf23ea76532fed2f29e84589ab1285821c28e47b545869298a4134e28cc71427865cbe13fd33979c60b32767",
          "sha256": "5cca584c55108219cd6e8edac66d1610cc1623cbec0df788a9b22b644dda6cf9",
          "sha1": "96ec361f5c32d96f5fda38b0b760b9bb0c8a8496",
          "md5": "79ffaa280b9561b78088ce6b0e90c005"
        }
      ]
    }
  ]
}
