{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-dis-cental-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6uyyqcjfwraxlgosc2npgw5y5q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-dis-cental-android-0.1.5.aar",
          "url": "ble-service-dis-cental-android-0.1.5.aar",
          "size": 5569,
          "sha512": "d29c4154fc93817a233893a85b2c0c4dd4790ca51151444ddb139988e1433cf2bbb1757923915aba139a557628d53c21e45529cac4f59833d4df26770c1e938f",
          "sha256": "42e7a5edae61f9f8fc7b8af111a5f547d7056658cfad9b9fd1a4dc98495a591e",
          "sha1": "a462b5b94e9e977bc86b2b5847559cacea1d6ce9",
          "md5": "01ac63e7a8419845f36246ad3967def2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-dis-cental-android-0.1.5.aar",
          "url": "ble-service-dis-cental-android-0.1.5.aar",
          "size": 5569,
          "sha512": "d29c4154fc93817a233893a85b2c0c4dd4790ca51151444ddb139988e1433cf2bbb1757923915aba139a557628d53c21e45529cac4f59833d4df26770c1e938f",
          "sha256": "42e7a5edae61f9f8fc7b8af111a5f547d7056658cfad9b9fd1a4dc98495a591e",
          "sha1": "a462b5b94e9e977bc86b2b5847559cacea1d6ce9",
          "md5": "01ac63e7a8419845f36246ad3967def2"
        }
      ]
    }
  ]
}
