{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a2b-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2b",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2b-android-0.2.9.aar",
          "url": "ble-characteristic-u2a2b-android-0.2.9.aar",
          "size": 3251,
          "sha512": "fbcdfbd1ed2817ce87512ee4b91296f949772c9ea78876cff88deff3d1f70c829ca48eb3ef7ec59259d12eefefba8c7fb878f179c9269a6c8f5480529acb574e",
          "sha256": "8872cfe3644982348d05003e09885203d02039a9e57790659b294f3e7cedefd7",
          "sha1": "ce09636aadc6f4e0245b16e4b2815a1ec0b7e896",
          "md5": "b68d3d2818439d6f51a1640e9ce6323f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2b",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2b-android-0.2.9.aar",
          "url": "ble-characteristic-u2a2b-android-0.2.9.aar",
          "size": 3251,
          "sha512": "fbcdfbd1ed2817ce87512ee4b91296f949772c9ea78876cff88deff3d1f70c829ca48eb3ef7ec59259d12eefefba8c7fb878f179c9269a6c8f5480529acb574e",
          "sha256": "8872cfe3644982348d05003e09885203d02039a9e57790659b294f3e7cedefd7",
          "sha1": "ce09636aadc6f4e0245b16e4b2815a1ec0b7e896",
          "md5": "b68d3d2818439d6f51a1640e9ce6323f"
        }
      ]
    }
  ]
}
