{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb0-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb0",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb0-android-0.8.14.aar",
          "url": "ble-characteristic-u2bb0-android-0.8.14.aar",
          "size": 3201,
          "sha512": "1618a9850b23e37a97ab07b5d4850ac80a7dfb992dae59249d314ecddbfe475cba4a47dcfe8f30bdcb3ea94c20f29a2fe70a7727544b981f72096cd33e71d7da",
          "sha256": "303de141d49f56e395146abb57ad670c570fcd2a8388b55b56e252dace97c127",
          "sha1": "3806d1ae78b1eea25608a8f65d6c47353080ca0a",
          "md5": "6fe86fdb54db1e86aee9ce038c8ca253"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb0",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb0-android-0.8.14.aar",
          "url": "ble-characteristic-u2bb0-android-0.8.14.aar",
          "size": 3201,
          "sha512": "1618a9850b23e37a97ab07b5d4850ac80a7dfb992dae59249d314ecddbfe475cba4a47dcfe8f30bdcb3ea94c20f29a2fe70a7727544b981f72096cd33e71d7da",
          "sha256": "303de141d49f56e395146abb57ad670c570fcd2a8388b55b56e252dace97c127",
          "sha1": "3806d1ae78b1eea25608a8f65d6c47353080ca0a",
          "md5": "6fe86fdb54db1e86aee9ce038c8ca253"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb0-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2bb0-android-0.8.14-sources.jar",
          "size": 2277,
          "sha512": "b93fabaf01a8c3e83b4beaa9eb090ec26c0b701023bdd585f0c40e151640d4efabc5eacbebbe81413ea98dec2826b20059e7aceb4715c3b950325ea4845e7a56",
          "sha256": "fd560adb85a189df1f9151ec14940ffca9e165e2e2bdfe4ce6c0c71bc8387e4e",
          "sha1": "4eb1ed4207d03308fced88aeff9afaf554830d4a",
          "md5": "8417c8252d2aecb66583269ceaf53f14"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb0-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2bb0-android-0.8.14-javadoc.jar",
          "size": 271360,
          "sha512": "132f03b8c7979108c51f5e0e78f7f5d413e30b2f3bbea1d164400d6aae518a924d7b206f76a8ac3652127274904befe4f8ab85bb17953127247a9cecd06762eb",
          "sha256": "0e61db6bbc95b3d67f006f6edbc0b18cabfb8b343e19cdf2a35aade8ff6408f7",
          "sha1": "6d5c14990b4364e9e2e8264394fc51906dec43ad",
          "md5": "ab9ba4cf33a54b4dce3627375918306b"
        }
      ]
    }
  ]
}
