{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7e",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.13.jar",
          "url": "ble-characteristic-u2a7e-0.8.13.jar",
          "size": 1762,
          "sha512": "37bb3d81fb5c7e4ac0e34fae7e21fec097460c0f4925b2dbc950d726db265a2da1e1baf581f18acd3e79647ce70a8e44bec6928322a1bd8ee2603bae3bb0a367",
          "sha256": "209bb074501d2f9ded529d51bb3d1bbe6c0f479b4d1ef62b922342e49518cf92",
          "sha1": "8dfac7fb9a982357a1b123c4571ff1553e2da170",
          "md5": "846ff54a2d7bc4ccdbc229f7496cba89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.13.jar",
          "url": "ble-characteristic-u2a7e-0.8.13.jar",
          "size": 1762,
          "sha512": "37bb3d81fb5c7e4ac0e34fae7e21fec097460c0f4925b2dbc950d726db265a2da1e1baf581f18acd3e79647ce70a8e44bec6928322a1bd8ee2603bae3bb0a367",
          "sha256": "209bb074501d2f9ded529d51bb3d1bbe6c0f479b4d1ef62b922342e49518cf92",
          "sha1": "8dfac7fb9a982357a1b123c4571ff1553e2da170",
          "md5": "846ff54a2d7bc4ccdbc229f7496cba89"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2a7e-0.8.13-javadoc.jar",
          "size": 86303,
          "sha512": "cc84f4ccd0000f12e748e3f3359bf41d63529e35f41441482b3b827517166ab3d628248113a204b312f5e492aa83b2f8501650e20ca0879b3786ee62b5208c6e",
          "sha256": "8682181878d89c96c33585fa76241417db530c6fc4c348b4abb1f0e13fd68607",
          "sha1": "32bfb44a294e1788e233b6be5436162c2ef31525",
          "md5": "8dea6468f171022b7655a4fcbd8cfbff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.8.13-sources.jar",
          "url": "ble-characteristic-u2a7e-0.8.13-sources.jar",
          "size": 1632,
          "sha512": "30970e0ebda3476b64f2adcfbe0ce34c1831d74448f5859652c6b595bc0b7b1c177c7f63cee25e2be2437223de377d66c53805cc8fd30a59177a4fdda29840ad",
          "sha256": "ea32822a34331eab8aeaaad7c04dfeba3cfc57071bea5700c1a2320b8a68dc2b",
          "sha1": "54aafc2c95d223d2c44cd03a3a1541ee81906205",
          "md5": "59981d626f6ecce469157e782496439f"
        }
      ]
    }
  ]
}
