{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-ftmp-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ftms-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-uds-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.12.aar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.12.aar",
          "size": 15136,
          "sha512": "891a80f6dcc6c1fb0392b81a9f2ce7b820e03ae90a897d52a4c6c83e37788b757fe4b424de924b0ba3b5a26bddd8ad28d19a846ffef992ea3dac37909e90766c",
          "sha256": "46e4cb3f7d19a109f48207bbd918cde17bea10e99aed036a65175ccb608a84f2",
          "sha1": "2e0577a207a2fd1edc78cd7e6c750886e6bb9c3a",
          "md5": "8a0f919c2738d713aea5a5bf3e187cee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ftms-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-uds-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.12.aar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.12.aar",
          "size": 15136,
          "sha512": "891a80f6dcc6c1fb0392b81a9f2ce7b820e03ae90a897d52a4c6c83e37788b757fe4b424de924b0ba3b5a26bddd8ad28d19a846ffef992ea3dac37909e90766c",
          "sha256": "46e4cb3f7d19a109f48207bbd918cde17bea10e99aed036a65175ccb608a84f2",
          "sha1": "2e0577a207a2fd1edc78cd7e6c750886e6bb9c3a",
          "md5": "8a0f919c2738d713aea5a5bf3e187cee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.12-sources.jar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.12-sources.jar",
          "size": 8958,
          "sha512": "b5929f060d8ae0d298937c10ee47dd5461fd734ad4381c9f89f4facfbec62be4483c2a45a414a3a93c9b877afc5968517240184c68019673ae35374b323e3e33",
          "sha256": "b3db03330baae81723605a99e9744254527c438e635608126f3166064159eec8",
          "sha1": "cb455af8680c39659b1b2b8082dcaa0414dc1765",
          "md5": "16606527a8501e61612fe223ffc54ada"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-ftmp-android-0.8.12-javadoc.jar",
          "url": "ble-profile-peripheral-ftmp-android-0.8.12-javadoc.jar",
          "size": 318737,
          "sha512": "314fa4984567c1bcf9da9ced1bd366af79e4d406fa6d0030dcfecdc6199505b424b9ac37ac8561b12d7e6ce7f6a8759a3fed34f4fbb06cc11a1c492f358e5f9b",
          "sha256": "9de46258b0feba7730d63f2017fd3011789fac432bbf410507a539c5749996bc",
          "sha1": "248936bc56cbbff5614d0b7aa8d759634c51ceb8",
          "md5": "b3f2c6d8ee7aa8d6b7bb9d6830514b0e"
        }
      ]
    }
  ]
}
