{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1e-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-android-0.4.4.aar",
          "url": "ble-characteristic-u2a1e-android-0.4.4.aar",
          "size": 3463,
          "sha512": "b0d562b793874ea07a264ea55c4428f60a098d5c821673862ffb835d4ea1980c3b6d4885b085fde1dd72bd04e1fb44f0f939eaab7c26ed2f0a321568a7ae92dc",
          "sha256": "3c5aaaae3d1a894af1457e3d43aba56b3913c03319d212d07ecfb354e798e8a7",
          "sha1": "a8e87e472d24f99aa59a981fab4e8cb64f7522a9",
          "md5": "3e55f4a755d9a220d5d5bbda383ad659"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-android-0.4.4.aar",
          "url": "ble-characteristic-u2a1e-android-0.4.4.aar",
          "size": 3463,
          "sha512": "b0d562b793874ea07a264ea55c4428f60a098d5c821673862ffb835d4ea1980c3b6d4885b085fde1dd72bd04e1fb44f0f939eaab7c26ed2f0a321568a7ae92dc",
          "sha256": "3c5aaaae3d1a894af1457e3d43aba56b3913c03319d212d07ecfb354e798e8a7",
          "sha1": "a8e87e472d24f99aa59a981fab4e8cb64f7522a9",
          "md5": "3e55f4a755d9a220d5d5bbda383ad659"
        }
      ]
    }
  ]
}
