{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb1",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.14.jar",
          "url": "ble-characteristic-u2bb1-0.8.14.jar",
          "size": 1522,
          "sha512": "bf54860654d9ae2a4fd924215d5dcd744bcca6ab1c19f54bc60a3499045e4438a48ecd63bda33f2da6abbe947b3dfd2250d34b583a681da72b192bed4cb774fe",
          "sha256": "d7b0fa398a3054670dbc6d1d3c7ee08b47f57787d470cc1eae64ed09b91df3e5",
          "sha1": "db3f94c953137c9b16e697a1bb5e1ba6f6d2df98",
          "md5": "045e3cc34d10f5fe068d5ea6fa3034d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.14.jar",
          "url": "ble-characteristic-u2bb1-0.8.14.jar",
          "size": 1522,
          "sha512": "bf54860654d9ae2a4fd924215d5dcd744bcca6ab1c19f54bc60a3499045e4438a48ecd63bda33f2da6abbe947b3dfd2250d34b583a681da72b192bed4cb774fe",
          "sha256": "d7b0fa398a3054670dbc6d1d3c7ee08b47f57787d470cc1eae64ed09b91df3e5",
          "sha1": "db3f94c953137c9b16e697a1bb5e1ba6f6d2df98",
          "md5": "045e3cc34d10f5fe068d5ea6fa3034d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2bb1-0.8.14-javadoc.jar",
          "size": 86206,
          "sha512": "dba72ba8b30207bee30ab42cb660fc73197bb2811bb3e4650696f5fbcd08850aabda1ecb4a53665dfc3dab186a09334bde3996336f3e97215b892b632a4bf664",
          "sha256": "c8033f5c931eae75a00c41ed5ec6040ac545478a89cc400c71eb03085c97584c",
          "sha1": "dfc9e660da95d4ac52fd716e801464c3b34d20b5",
          "md5": "97801b597f898066e1c2ae9eff626b44"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.14-sources.jar",
          "url": "ble-characteristic-u2bb1-0.8.14-sources.jar",
          "size": 1510,
          "sha512": "7f8f0f54eafbe3e4d17d778bf2d4b7ef50e73f6df6df41b97aa9b53325903cdc24fe7519bbe53b9279b78cabd74160fb66bde0900464b2498f47e6ca19c89967",
          "sha256": "d60fad14570c16b550ebfc2af3184dffaafa0e6fd74691c44d2c955da24b6d73",
          "sha1": "890130d9c20f964c9ae2e6fcf596b476958f44d9",
          "md5": "9a7656413b0cafd7b2176a42797adf40"
        }
      ]
    }
  ]
}
