{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a55-android",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a55",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-android-0.6.0.aar",
          "url": "ble-characteristic-u2a55-android-0.6.0.aar",
          "size": 3167,
          "sha512": "1a2767bc883b9a0ae610901c4b8b074fa711d2a5af9b26b54d89b66c24d660a9d9583b9e0ea95da2e3a6253eb237e6a86a7ac95ccc8c824ff0a15b5c8916332a",
          "sha256": "78f5eca7041fca4627f4a571f1575518aeeec9874dfb08fb596bb9a665a6e443",
          "sha1": "6444eeb6bf690b0356c90d0eb9d91e6620c0cb6d",
          "md5": "10b5b33e49c1fc54e9074db198f9280e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a55",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-android-0.6.0.aar",
          "url": "ble-characteristic-u2a55-android-0.6.0.aar",
          "size": 3167,
          "sha512": "1a2767bc883b9a0ae610901c4b8b074fa711d2a5af9b26b54d89b66c24d660a9d9583b9e0ea95da2e3a6253eb237e6a86a7ac95ccc8c824ff0a15b5c8916332a",
          "sha256": "78f5eca7041fca4627f4a571f1575518aeeec9874dfb08fb596bb9a665a6e443",
          "sha1": "6444eeb6bf690b0356c90d0eb9d91e6620c0cb6d",
          "md5": "10b5b33e49c1fc54e9074db198f9280e"
        }
      ]
    }
  ]
}
