{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a95",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jy7ixesazfhqnmjb55547uywfu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a95-0.1.0.jar",
          "url": "ble-characteristic-u2a95-0.1.0.jar",
          "size": 1717,
          "sha512": "24f45fb429a22b4df330b9e4aa061817d0ad2620aacce2b7ae6afca0af2602fe50477aec24d801ecfac48a12110cb26bf0cf4f116d9a2783010be7165261e85a",
          "sha256": "f954521a60cc63b0a580512fe9c9886a54b06c5e8a89cb27ecdebdb770c9cea6",
          "sha1": "4aadcc8f7706fe66ed457455587ca90aff5b374e",
          "md5": "f7d6587ab948e8565732fa55593ededf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a95-0.1.0.jar",
          "url": "ble-characteristic-u2a95-0.1.0.jar",
          "size": 1717,
          "sha512": "24f45fb429a22b4df330b9e4aa061817d0ad2620aacce2b7ae6afca0af2602fe50477aec24d801ecfac48a12110cb26bf0cf4f116d9a2783010be7165261e85a",
          "sha256": "f954521a60cc63b0a580512fe9c9886a54b06c5e8a89cb27ecdebdb770c9cea6",
          "sha1": "4aadcc8f7706fe66ed457455587ca90aff5b374e",
          "md5": "f7d6587ab948e8565732fa55593ededf"
        }
      ]
    }
  ]
}
