{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-appearance",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-appearance-0.8.12.jar",
          "url": "ble-core-constants-appearance-0.8.12.jar",
          "size": 15196,
          "sha512": "b00892bbb6bb40431702f8ed853967e8ab6f2781df3dca0cf7d41c423f6412fe82a8cf138065062c455588cd4ac8f265a49013a98fc2ff38e5f4a6e5634a7624",
          "sha256": "d1731e2d5654eb27445dfc2696aa61c6076678f1c20dcc0bdf615f164c05030e",
          "sha1": "d4c1e8cdde536ed7c330d76d9e4c93e60b950e8b",
          "md5": "dd71a7194f79981ce0ce6f65108f4b87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-appearance-0.8.12.jar",
          "url": "ble-core-constants-appearance-0.8.12.jar",
          "size": 15196,
          "sha512": "b00892bbb6bb40431702f8ed853967e8ab6f2781df3dca0cf7d41c423f6412fe82a8cf138065062c455588cd4ac8f265a49013a98fc2ff38e5f4a6e5634a7624",
          "sha256": "d1731e2d5654eb27445dfc2696aa61c6076678f1c20dcc0bdf615f164c05030e",
          "sha1": "d4c1e8cdde536ed7c330d76d9e4c93e60b950e8b",
          "md5": "dd71a7194f79981ce0ce6f65108f4b87"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-appearance-0.8.12-javadoc.jar",
          "url": "ble-core-constants-appearance-0.8.12-javadoc.jar",
          "size": 150041,
          "sha512": "2fedfdeac06982139eb2661478d7bb3b7e1817f9e31aec57d08765686d98a73cc2ac47bf94ef5e6c80b60c289d5064eb58d8a4beb61406766d3d29dbf5ee5e28",
          "sha256": "82f75fc7378f8d84f8dfa166720a8005f8fd5bd4f5d7d50365079fc8d86fafb8",
          "sha1": "0779c7add96769bb18c9cd05e214aa02b99ae277",
          "md5": "c0dcfdcfdfcd6b59a1bcf10b6f4bcca3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-appearance-0.8.12-sources.jar",
          "url": "ble-core-constants-appearance-0.8.12-sources.jar",
          "size": 12182,
          "sha512": "059f5f97815f7f72e0e4c86577cc10e724db30de031efdc52559ef141b5095df1cb1a855ffa848f8774ef3079034d5f9ec7658e871c779ad0edb14fed148836b",
          "sha256": "60a6b619b47c7f7bf19bfdbe6c7331224ce05188e47dbd50451985c4ebadf30b",
          "sha1": "6f4d7230d014a3ec41fe3b5a943b56fe1d8754cb",
          "md5": "7c56bf4ec15aeb82f44ed9a2fe5c5c37"
        }
      ]
    }
  ]
}
