{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a17-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "md2hzulcvrbjbp3omyeiu4n5fi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.2.3.aar",
          "url": "ble-characteristic-u2a17-android-0.2.3.aar",
          "size": 2933,
          "sha512": "eedff4fea1bdd44b4566e50604554d1a1254ae025393d35718c78f1ef91c39cd8aa2edb0c2fd275e1f99fb33871fd1520f0777053fba0a5607e2e3cd5d04da9c",
          "sha256": "523aecf603d73f77cf766adef94cf29f0404e72a11188562d4e6320fc1176c8b",
          "sha1": "91cf64013c120c1ef5d5c860b26fcb505b6b182d",
          "md5": "c42901b7860f05b3a82d2b7ff669b3fa"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.2.3.aar",
          "url": "ble-characteristic-u2a17-android-0.2.3.aar",
          "size": 2933,
          "sha512": "eedff4fea1bdd44b4566e50604554d1a1254ae025393d35718c78f1ef91c39cd8aa2edb0c2fd275e1f99fb33871fd1520f0777053fba0a5607e2e3cd5d04da9c",
          "sha256": "523aecf603d73f77cf766adef94cf29f0404e72a11188562d4e6320fc1176c8b",
          "sha1": "91cf64013c120c1ef5d5c860b26fcb505b6b182d",
          "md5": "c42901b7860f05b3a82d2b7ff669b3fa"
        }
      ]
    }
  ]
}
