{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab3-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zckqgxv52jertg33sctsfjorzm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab3",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab3-android-0.2.2.aar",
          "url": "ble-characteristic-u2ab3-android-0.2.2.aar",
          "size": 2886,
          "sha512": "ed4708f7d55e288247e5eb2ec8e16604d18c0d7a7e6abf643a50f5c6f8f600496aa4b65f70029f0d27cf989af019dd686cd7de40df1d05abbfac3360007af813",
          "sha256": "9b3c0649500e86e1dd6aac1db12769cad480a69e9e379441cec3fc62b9a1c71e",
          "sha1": "70ac4919cb2f18c1977ba3a397de937d10a7de68",
          "md5": "0979e47489e97818f08023edfcfa2f8f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab3",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab3-android-0.2.2.aar",
          "url": "ble-characteristic-u2ab3-android-0.2.2.aar",
          "size": 2886,
          "sha512": "ed4708f7d55e288247e5eb2ec8e16604d18c0d7a7e6abf643a50f5c6f8f600496aa4b65f70029f0d27cf989af019dd686cd7de40df1d05abbfac3360007af813",
          "sha256": "9b3c0649500e86e1dd6aac1db12769cad480a69e9e379441cec3fc62b9a1c71e",
          "sha1": "70ac4919cb2f18c1977ba3a397de937d10a7de68",
          "md5": "0979e47489e97818f08023edfcfa2f8f"
        }
      ]
    }
  ]
}
