{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abc-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgm5345lfvewjajsd7sfgyhu7u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abc",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abc-android-0.2.9.aar",
          "url": "ble-characteristic-u2abc-android-0.2.9.aar",
          "size": 5074,
          "sha512": "dd8d7611babba05ed92679ab037d90d645802e6eb264703baea43541b1d81a77fb2f4decbffecb1d01728a8bd719bc04ac194f397f19421ad38b69d35d26e734",
          "sha256": "50f07be580bd59ff60a1038dbb7a75a7ff0c5e8b820763d4bfb7440a622be961",
          "sha1": "9ca3ac3f07ba57dad3668c681abcadfa707d8f09",
          "md5": "cfd619938396bd2e5acc62ffbe9b4abf"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abc",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abc-android-0.2.9.aar",
          "url": "ble-characteristic-u2abc-android-0.2.9.aar",
          "size": 5074,
          "sha512": "dd8d7611babba05ed92679ab037d90d645802e6eb264703baea43541b1d81a77fb2f4decbffecb1d01728a8bd719bc04ac194f397f19421ad38b69d35d26e734",
          "sha256": "50f07be580bd59ff60a1038dbb7a75a7ff0c5e8b820763d4bfb7440a622be961",
          "sha1": "9ca3ac3f07ba57dad3668c681abcadfa707d8f09",
          "md5": "cfd619938396bd2e5acc62ffbe9b4abf"
        }
      ]
    }
  ]
}
