{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-rcp-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-rcp-android-0.8.10.aar",
          "url": "ble-profile-rcp-android-0.8.10.aar",
          "size": 1292,
          "sha512": "9cda71976b7147521eddd1be236e0b31a3b7a6b4f7d84b98f1d6f41d85e4d94869b00293b4905630a4c89a92475214a4894b94e4e84d58ea43943235f65557be",
          "sha256": "e175cb2d759a24929eea9687e235aa5bca8290dfda232f4f3473e15144f286c2",
          "sha1": "76857f72629f68eee7e21467dffd13f29bf2c5e2",
          "md5": "8a9ad6be859174b32942615afd9a2e37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-rcp-android-0.8.10.aar",
          "url": "ble-profile-rcp-android-0.8.10.aar",
          "size": 1292,
          "sha512": "9cda71976b7147521eddd1be236e0b31a3b7a6b4f7d84b98f1d6f41d85e4d94869b00293b4905630a4c89a92475214a4894b94e4e84d58ea43943235f65557be",
          "sha256": "e175cb2d759a24929eea9687e235aa5bca8290dfda232f4f3473e15144f286c2",
          "sha1": "76857f72629f68eee7e21467dffd13f29bf2c5e2",
          "md5": "8a9ad6be859174b32942615afd9a2e37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-rcp-android-0.8.10-sources.jar",
          "url": "ble-profile-rcp-android-0.8.10-sources.jar",
          "size": 1191,
          "sha512": "7b788a6bdb7ddd4f6442a1cba4357b86cec7d3e10c074b066a59e45d527dc73069043634ca46375d860d3c27ee40123b7718a896985e17b5f66203ea9e50a7fa",
          "sha256": "78d5a1d521d546d1a745b0e382fdebc1965928677333296c25e5abdfc72ddc6f",
          "sha1": "a53d5b5e22facc8b38f9b9c86d6a54f259855718",
          "md5": "e7b3d71cd8d36a96ab8ecb3294eb03a4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-rcp-android-0.8.10-javadoc.jar",
          "url": "ble-profile-rcp-android-0.8.10-javadoc.jar",
          "size": 259943,
          "sha512": "13edd2ecf169660b1ef8c8f77dc1e413a6bb3dc886965e64bdd791931934d8d8a0e25af916d0220525b6bef679a5a532c4d0544e94085a9004434323aef827f1",
          "sha256": "cfe9faf81ba8c46dc4ca78da51ffd45446ea98501614e92a0b998579516a4882",
          "sha1": "07aeb4c3616a1ca8d7f4d9593c97d972d9f337c9",
          "md5": "49450bb2ea052b379ed701a092f8158b"
        }
      ]
    }
  ]
}
