{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd9",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.1.jar",
          "url": "ble-characteristic-u2bd9-0.8.1.jar",
          "size": 1500,
          "sha512": "d95723ac6f194964badc572bd2497a6c5fdd96e598ee13c43a2bd496f3e8de518563ffba524f826f70c10151586df6f7fbc36a69b13e68f1650c4e3c76cd5965",
          "sha256": "604196fa08c12f892f6181ae5449e888fc5b78b38c86fddb537b078450b05c9f",
          "sha1": "22ec78517fa470df12b36ff1c1f93acd5da23a96",
          "md5": "9e1704fd36134e58d521aaae8d1ebb09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.1.jar",
          "url": "ble-characteristic-u2bd9-0.8.1.jar",
          "size": 1500,
          "sha512": "d95723ac6f194964badc572bd2497a6c5fdd96e598ee13c43a2bd496f3e8de518563ffba524f826f70c10151586df6f7fbc36a69b13e68f1650c4e3c76cd5965",
          "sha256": "604196fa08c12f892f6181ae5449e888fc5b78b38c86fddb537b078450b05c9f",
          "sha1": "22ec78517fa470df12b36ff1c1f93acd5da23a96",
          "md5": "9e1704fd36134e58d521aaae8d1ebb09"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.1-javadoc.jar",
          "url": "ble-characteristic-u2bd9-0.8.1-javadoc.jar",
          "size": 110016,
          "sha512": "b2a7bb9c9b19b3c04e5bb9202dddb960360c9281d823eb2d8f03b8cb55452f59e157787bb4a592ad477ab5ffa9dc337722fee19a96e0e03a9eecdb8fe5f66365",
          "sha256": "7f8efc92d58767bb8dc9489da430d794b9820ce7eb984ad7761fa988cdc1fb8a",
          "sha1": "48eca92e15e4d54407c55c9dd3367fef7f55c7a5",
          "md5": "f3c51afc1301fb9efc908b0ed0ffa6b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd9-0.8.1-sources.jar",
          "url": "ble-characteristic-u2bd9-0.8.1-sources.jar",
          "size": 1477,
          "sha512": "d4818b96071e6218630841db6177c51ef84d1e597cb248dc82f08d4fbd83ad97a10fe3935cde7653598f5104a3bc1472194f6cd739de8315fedf7d3eca696c44",
          "sha256": "7c9bd83b87864d7ff62b04eec29f051bee4cbca6fcf2390cacd89c7060cfe0ad",
          "sha1": "5d25cfdfde1eaca8440c495c2aa445c3cb8e4674",
          "md5": "b0232a8554b5a2fd7dc575f7fca50f65"
        }
      ]
    }
  ]
}
