{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b39",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.7.jar",
          "url": "ble-characteristic-u2b39-0.8.7.jar",
          "size": 1459,
          "sha512": "7d496662d66f20f84bde875d3ce04ca19f6b80187446c6ee36e3bc04aee1a4e3e40d20bf340f61b03a7a840bac13bb4a8d85633017f4ea109db5fac3ab0cf0a8",
          "sha256": "6c4f067c97cb6994a33aa35494d13f6c73021565149bbfbd7efd6b8c86ddb1bb",
          "sha1": "240f80925770d1afb4648b7005eb8e6312cb6b81",
          "md5": "5a5e2621d0750e0e2dec4e821f11f4ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.7.jar",
          "url": "ble-characteristic-u2b39-0.8.7.jar",
          "size": 1459,
          "sha512": "7d496662d66f20f84bde875d3ce04ca19f6b80187446c6ee36e3bc04aee1a4e3e40d20bf340f61b03a7a840bac13bb4a8d85633017f4ea109db5fac3ab0cf0a8",
          "sha256": "6c4f067c97cb6994a33aa35494d13f6c73021565149bbfbd7efd6b8c86ddb1bb",
          "sha1": "240f80925770d1afb4648b7005eb8e6312cb6b81",
          "md5": "5a5e2621d0750e0e2dec4e821f11f4ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b39-0.8.7-javadoc.jar",
          "size": 107185,
          "sha512": "18ac7853e7d75324e2289b9ddbe225866930adc5b7e10aefaef0b2933f9a169c46246c6188923b77ba88420dae4722e3332715882139832fe4541802a795d408",
          "sha256": "f3c588a6f2792bbe0ebdf2891600eec568cea17fd673b0df539a8afb73b2cd78",
          "sha1": "4746720bb02524bbfc7e35808fc57285f8ae182c",
          "md5": "9cb2c7cfa2dd2658c2afee64061487e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b39-0.8.7-sources.jar",
          "size": 1453,
          "sha512": "414d73c683ff1e22ecca8dab57f77421333f4421cbdc5ab3cd2a0ecbccd138a2b5c42235fb08f811df93ae572a4f0c62fa40a064458becbe370ecf3fbcd4a1cf",
          "sha256": "16903e0faf9dae01b2b1e3ca01b8beb7b48d3583e96dc7aaf106ed54182ce398",
          "sha1": "11a939be32f8248228e611d2a944fbe40d26b9a3",
          "md5": "179995a622b39dba7ecce338ad8279c6"
        }
      ]
    }
  ]
}
