{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a01-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-android-0.1.5.aar",
          "url": "ble-characteristic-u2a01-android-0.1.5.aar",
          "size": 3030,
          "sha512": "ade300aa0256d4b5be2c6b6d878f0bf383541c8938521ce7f24b0b5bcc54d9505ce281bcdc8576407ac0c6f0b1f54d5e1ea06b09f1fe402fd56849056d831459",
          "sha256": "ca9798aba33a5c5818e012ac27ca8e07505760ca4f5240afd6ddd68c21a9bcee",
          "sha1": "cafced13e975677aa22f6dabc81f2f322877e1e2",
          "md5": "affa9ce6f88651dbcdeb9a34394b86c8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-android-0.1.5.aar",
          "url": "ble-characteristic-u2a01-android-0.1.5.aar",
          "size": 3030,
          "sha512": "ade300aa0256d4b5be2c6b6d878f0bf383541c8938521ce7f24b0b5bcc54d9505ce281bcdc8576407ac0c6f0b1f54d5e1ea06b09f1fe402fd56849056d831459",
          "sha256": "ca9798aba33a5c5818e012ac27ca8e07505760ca4f5240afd6ddd68c21a9bcee",
          "sha1": "cafced13e975677aa22f6dabc81f2f322877e1e2",
          "md5": "affa9ce6f88651dbcdeb9a34394b86c8"
        }
      ]
    }
  ]
}
