{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab9-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab9",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-android-0.8.6.aar",
          "url": "ble-characteristic-u2ab9-android-0.8.6.aar",
          "size": 3105,
          "sha512": "2d21f9454daca74f40ad7c557c06153bc29851cf193ae5bec1cc3c3279a6119b400cc2ebc037762702d7ee67249d143aa623ad68be61d625c0d5220b3fc25399",
          "sha256": "22b679f9b9b165250976f6f60b8189eedaaef323dcc2e2b62687a378a51498d6",
          "sha1": "10be3ddf5839cb95efacf46c494901871f2acfcd",
          "md5": "13ca834faf1a2ca7313d89b7ca9f478e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab9",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-android-0.8.6.aar",
          "url": "ble-characteristic-u2ab9-android-0.8.6.aar",
          "size": 3105,
          "sha512": "2d21f9454daca74f40ad7c557c06153bc29851cf193ae5bec1cc3c3279a6119b400cc2ebc037762702d7ee67249d143aa623ad68be61d625c0d5220b3fc25399",
          "sha256": "22b679f9b9b165250976f6f60b8189eedaaef323dcc2e2b62687a378a51498d6",
          "sha1": "10be3ddf5839cb95efacf46c494901871f2acfcd",
          "md5": "13ca834faf1a2ca7313d89b7ca9f478e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab9-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ab9-android-0.8.6-sources.jar",
          "size": 2176,
          "sha512": "e24b2e9f742b1bde893323083f15492170a57b9f5e0be63d22c9c3dfd8597721c84bbb5c0303bcfdd3a4d8d4b5da64d2767322cd319e3ec5fc130a23a7cf5e3c",
          "sha256": "c9aab6e8a93ad781cdbdb09d46e0d6225d639a301352a291ec3c6c020802362f",
          "sha1": "cabf9ce08faca2e1aaf9543473be0076f0a4e3eb",
          "md5": "a723f88cfb27ed19adbcb01a2c0daaf6"
        }
      ]
    }
  ]
}
