{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4c-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4c",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4c-android-0.8.12.aar",
          "url": "ble-characteristic-u2b4c-android-0.8.12.aar",
          "size": 3280,
          "sha512": "12d209dad018298976d34c8ebd810b4a89c8e059a4758c7396dbe3ff41973fc750d447c1e74815fcc38e34b271495ab49ce8eb3d52167e6c0369bae9c779fb71",
          "sha256": "7115ba748a0259c1a06bb1a8f7155635755e902c75b73071cc34ebd08f40f7ed",
          "sha1": "0c332bcaca27b453b132451e8b43ff29d952a8da",
          "md5": "aab33ed6a36c72fccde9e1d71d671640"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4c",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4c-android-0.8.12.aar",
          "url": "ble-characteristic-u2b4c-android-0.8.12.aar",
          "size": 3280,
          "sha512": "12d209dad018298976d34c8ebd810b4a89c8e059a4758c7396dbe3ff41973fc750d447c1e74815fcc38e34b271495ab49ce8eb3d52167e6c0369bae9c779fb71",
          "sha256": "7115ba748a0259c1a06bb1a8f7155635755e902c75b73071cc34ebd08f40f7ed",
          "sha1": "0c332bcaca27b453b132451e8b43ff29d952a8da",
          "md5": "aab33ed6a36c72fccde9e1d71d671640"
        }
      ]
    }
  ]
}
