{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0d-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0d",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0d-android-0.8.12.aar",
          "url": "ble-characteristic-u2b0d-android-0.8.12.aar",
          "size": 3175,
          "sha512": "43699934b512c628a97ae9ead49f785007a9770ab35e18cab3e80307680082e785448ac77cc89e2a293d80a27d012334cc30a9da0f56b30d461fe918053f8725",
          "sha256": "f27063a0bcc7d6085a365cc924a2faa3a3ecbfdbc9bb4acdf6ccdc718f6ff56f",
          "sha1": "4d2a6d4321b8709cef95f2dc47449e734540b782",
          "md5": "8afd1ef9e6ae3dae39fbbe763b4dd627"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0d",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0d-android-0.8.12.aar",
          "url": "ble-characteristic-u2b0d-android-0.8.12.aar",
          "size": 3175,
          "sha512": "43699934b512c628a97ae9ead49f785007a9770ab35e18cab3e80307680082e785448ac77cc89e2a293d80a27d012334cc30a9da0f56b30d461fe918053f8725",
          "sha256": "f27063a0bcc7d6085a365cc924a2faa3a3ecbfdbc9bb4acdf6ccdc718f6ff56f",
          "sha1": "4d2a6d4321b8709cef95f2dc47449e734540b782",
          "md5": "8afd1ef9e6ae3dae39fbbe763b4dd627"
        }
      ]
    }
  ]
}
