{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-cscp-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-cscs-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-cscp-android-0.4.6.aar",
          "url": "ble-profile-central-cscp-android-0.4.6.aar",
          "size": 6050,
          "sha512": "85afa638f97b92e1e8be1edd756f46b8c51ddd98398f244e15d6a9b3123645f24aa9bf8fc019906a1da9af88266cf029629c03f7eb36f9b76e4b3063f5384a1c",
          "sha256": "e19b6520adda228eefcaa43c19e67657fcf1055f2ee9e02734be3865210bf796",
          "sha1": "656a4f2c03be70208171731207271ba05c3046e8",
          "md5": "44c45eb4ef8db03237af8808b817582e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-cscs-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-cscp-android-0.4.6.aar",
          "url": "ble-profile-central-cscp-android-0.4.6.aar",
          "size": 6050,
          "sha512": "85afa638f97b92e1e8be1edd756f46b8c51ddd98398f244e15d6a9b3123645f24aa9bf8fc019906a1da9af88266cf029629c03f7eb36f9b76e4b3063f5384a1c",
          "sha256": "e19b6520adda228eefcaa43c19e67657fcf1055f2ee9e02734be3865210bf796",
          "sha1": "656a4f2c03be70208171731207271ba05c3046e8",
          "md5": "44c45eb4ef8db03237af8808b817582e"
        }
      ]
    }
  ]
}
