{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a68-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a68-android-0.2.3.aar",
          "url": "ble-characteristic-u2a68-android-0.2.3.aar",
          "size": 3222,
          "sha512": "97be28b470bcba7ab195550343328554fe3e8af7fc26a6c58907ba04f55356dedf90c8322fbcbbcb01a352a9a1df779f5db937440be5988b9141a09b9feead26",
          "sha256": "9aa7d67103ea30cd3442be83f2805270a760627eaed4bf2869b5a1de3d6ac917",
          "sha1": "4380e85cfe03b3ca3e3217b8c199caff6cce0f04",
          "md5": "f85d3676cfbdfae9896c5b5f4e0f7da8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a68",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a68-android-0.2.3.aar",
          "url": "ble-characteristic-u2a68-android-0.2.3.aar",
          "size": 3222,
          "sha512": "97be28b470bcba7ab195550343328554fe3e8af7fc26a6c58907ba04f55356dedf90c8322fbcbbcb01a352a9a1df779f5db937440be5988b9141a09b9feead26",
          "sha256": "9aa7d67103ea30cd3442be83f2805270a760627eaed4bf2869b5a1de3d6ac917",
          "sha1": "4380e85cfe03b3ca3e3217b8c199caff6cce0f04",
          "md5": "f85d3676cfbdfae9896c5b5f4e0f7da8"
        }
      ]
    }
  ]
}
