{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290d-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-android-0.8.10.aar",
          "url": "ble-descriptor-u290d-android-0.8.10.aar",
          "size": 3243,
          "sha512": "c41b71c90477be1a1bf3673e9727c772ae7566400ae51b1078aca71ca5b3f383e0e9bf3dacc96277aa7662a9e037846c72d595f95514bee4f49b319706694e75",
          "sha256": "e1d4631df40bee8731eeddb4421bf818112a0b0dd6a43a497240a6f90538bf32",
          "sha1": "db37dc4041ecd50c3459b6211585a89f8876640d",
          "md5": "069c5c53777988588b5a13967ad76e54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-android-0.8.10.aar",
          "url": "ble-descriptor-u290d-android-0.8.10.aar",
          "size": 3243,
          "sha512": "c41b71c90477be1a1bf3673e9727c772ae7566400ae51b1078aca71ca5b3f383e0e9bf3dacc96277aa7662a9e037846c72d595f95514bee4f49b319706694e75",
          "sha256": "e1d4631df40bee8731eeddb4421bf818112a0b0dd6a43a497240a6f90538bf32",
          "sha1": "db37dc4041ecd50c3459b6211585a89f8876640d",
          "md5": "069c5c53777988588b5a13967ad76e54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290d-android-0.8.10-sources.jar",
          "url": "ble-descriptor-u290d-android-0.8.10-sources.jar",
          "size": 2207,
          "sha512": "f91b50c95f268f44a4ed95b663c3f270386baf246793898ca7df1cc5c290bff330cc0b12dbdde1f78bc0ee813e5f6a62e6ec9b8aaae8b36b66bea38d56d2c82a",
          "sha256": "7872522ef1c10e720fe97b117d82c9c4fb5246b12aecac0e30441ec0c19f56a7",
          "sha1": "25d8a712ef8c4e8a9b934275318d32b6a7f74e1b",
          "md5": "4626d88ddfdad4c62264a2a27a2bcb1d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290d-android-0.8.10-javadoc.jar",
          "url": "ble-descriptor-u290d-android-0.8.10-javadoc.jar",
          "size": 272807,
          "sha512": "fc681a4f71357d0e0ee3d3a90b7adfb038e768bcff3dbd384b5e71a2d9fe5fa6072515c2535cb626cd61b9b468918efabf0f554ab70c0dc7e8892c1301f43adc",
          "sha256": "b5a182959ca7f1409e311aa6fcd4d6c68f0017d7299c8b502a64ddb164686a30",
          "sha1": "f93bacb4a79980f5b4cc410f9b1865d830508fc4",
          "md5": "04ed6c4cf07bffc5a22a0e3903e7906b"
        }
      ]
    }
  ]
}
