{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae1",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.8.jar",
          "url": "ble-characteristic-u2ae1-0.8.8.jar",
          "size": 1871,
          "sha512": "83c2025927fbddfaa006d9076fb362a0560e53075c0f43108cb5d869453dbf0e30633034c91f989e66a8132f852ae96beadbe55d5014d2790041b76b34817dcd",
          "sha256": "727fa88eb6306e4c9756a1d7d52ba708ead712081a8ad36dde35a92dc3472986",
          "sha1": "316c3c6486e7c24c553eb5c70a3422c45f79afc6",
          "md5": "0f9924da62b7a8145effdd5e43a5f253"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.8.jar",
          "url": "ble-characteristic-u2ae1-0.8.8.jar",
          "size": 1871,
          "sha512": "83c2025927fbddfaa006d9076fb362a0560e53075c0f43108cb5d869453dbf0e30633034c91f989e66a8132f852ae96beadbe55d5014d2790041b76b34817dcd",
          "sha256": "727fa88eb6306e4c9756a1d7d52ba708ead712081a8ad36dde35a92dc3472986",
          "sha1": "316c3c6486e7c24c553eb5c70a3422c45f79afc6",
          "md5": "0f9924da62b7a8145effdd5e43a5f253"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2ae1-0.8.8-javadoc.jar",
          "size": 107473,
          "sha512": "ccf454d9ee6afcb81259c4ea99befe03f707743c5e800dae601a1da4a55618ad26cb9d3b963234edc0e646e08c55f7f6328f682fd84373012e6bd4bebdbb8e5f",
          "sha256": "b3b24a0d029e8273b45fa66a64bc8f4f12b7a4805cf85251d82bfaea2c799659",
          "sha1": "ca85274aa113749ffa5c5807aed12969a4bb553e",
          "md5": "551a3ddbdcb249e3b3156210b63af07e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae1-0.8.8-sources.jar",
          "url": "ble-characteristic-u2ae1-0.8.8-sources.jar",
          "size": 1687,
          "sha512": "4b945eab57954324986a9781cc8fd03260c1f91d68c2bb0e567ea4ca22f2d4510d2dc2efd482b24501e899a0456471b60c32da46fa42653d83c01b3eeedbac49",
          "sha256": "3b251c002f5eaa7dec15e4dc5df6bc5f648da2ab8ca41b94e6daf1c62efd0996",
          "sha1": "3eed52e2674b9a6d0b8c2bbbb1f514591ea54ae8",
          "md5": "9c5a852789316c31f4229ef2f9f8bed0"
        }
      ]
    }
  ]
}
