{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2baa",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.5.jar",
          "url": "ble-characteristic-u2baa-0.8.5.jar",
          "size": 1477,
          "sha512": "470bfac7455d9ca1f79b335ea41d37f306ddd423cb29b858389d37cd897be1f635309673044a11502a62cf8c3105306bf55c8f86fa6d775bb7ca305e5df68f18",
          "sha256": "b81960b2515e285e91607427a25db240f79cd8a106d0ac756b7bf685abc7e2c8",
          "sha1": "9af05730d34645ce6f67d0f549d95c39c5cbbe61",
          "md5": "527e4da6263152b3b4fb7fb264925c70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.5.jar",
          "url": "ble-characteristic-u2baa-0.8.5.jar",
          "size": 1477,
          "sha512": "470bfac7455d9ca1f79b335ea41d37f306ddd423cb29b858389d37cd897be1f635309673044a11502a62cf8c3105306bf55c8f86fa6d775bb7ca305e5df68f18",
          "sha256": "b81960b2515e285e91607427a25db240f79cd8a106d0ac756b7bf685abc7e2c8",
          "sha1": "9af05730d34645ce6f67d0f549d95c39c5cbbe61",
          "md5": "527e4da6263152b3b4fb7fb264925c70"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2baa-0.8.5-javadoc.jar",
          "size": 107220,
          "sha512": "eb56459f24413f1ff45eac764e0bbfc6ba2bfb4ec7b34b6a4972e609de69eaac3625c51f090d32e914f2cc13249af7d2789c79fa30e7bbcbe5ef29965e90eafe",
          "sha256": "eb240e8d2ee41379be21f95bf860d2d0a49965cbcc0f8f1f838dd64d95d48177",
          "sha1": "84b09e7f30352bf09373631c6ae224de269252b9",
          "md5": "bdca23890cf811b5521d6c3b5c7dd854"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baa-0.8.5-sources.jar",
          "url": "ble-characteristic-u2baa-0.8.5-sources.jar",
          "size": 1472,
          "sha512": "cce983a067f3e83bc6f661fe1bcc1614331c245e0db9c6c34083fe9b8a245eb8d4088303b2e1f58549dc68a7c55f2a03ea69890e89018c7749b7f37ddf38a5ef",
          "sha256": "559bb7bb41b00000c060d11c43ce84f0cb5786e602b5a3848bb36529815f1a7f",
          "sha1": "b482266e05d3c6659daa28c581d4e57dcbb5cce8",
          "md5": "ab3b43aac76823c268e4dbef18ae64a9"
        }
      ]
    }
  ]
}
