{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b06",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b06-0.8.10.jar",
          "url": "ble-characteristic-u2b06-0.8.10.jar",
          "size": 1955,
          "sha512": "236895d5825a76bce682c97c61736e2259cb1c6cc6aefba78ff5e1a10e2f0a7191c2ddc99d4f414301f4329dc1e6b109c0fa062daa95d620b46544ac3acdd142",
          "sha256": "44c1731f99587c0c1c877106394039309117c312b1b416750733948abb38d890",
          "sha1": "57165662a094f65f98e009c65269fadb28342cfd",
          "md5": "eb71b19fd76f83ede04a3371dbbd14de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b06-0.8.10.jar",
          "url": "ble-characteristic-u2b06-0.8.10.jar",
          "size": 1955,
          "sha512": "236895d5825a76bce682c97c61736e2259cb1c6cc6aefba78ff5e1a10e2f0a7191c2ddc99d4f414301f4329dc1e6b109c0fa062daa95d620b46544ac3acdd142",
          "sha256": "44c1731f99587c0c1c877106394039309117c312b1b416750733948abb38d890",
          "sha1": "57165662a094f65f98e009c65269fadb28342cfd",
          "md5": "eb71b19fd76f83ede04a3371dbbd14de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b06-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2b06-0.8.10-javadoc.jar",
          "size": 107601,
          "sha512": "211155b00eff86ee452df023d133d4114195ec510111fbb2e3adbca836397867496c332edbd1c6fd449a5992f3e048b4a3adab377f9f0140718a8be7b069574e",
          "sha256": "52f83e40e7cff43391fd6754178a095e5c494ccfc2e23297413f86270bfd16fe",
          "sha1": "2f6d2b20f3c6006f1e017f0d219d7461b8fa5f01",
          "md5": "a07d01c952202ebcbf5de4dbe9bb9897"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b06-0.8.10-sources.jar",
          "url": "ble-characteristic-u2b06-0.8.10-sources.jar",
          "size": 1774,
          "sha512": "92fd8e4373ed32cf1c7af979755b6666b06fc8cb46907cc189ec84321d767cce43603af532447acc0d6e06321a1df6b962c9c8ca54445fda50dbf1be3b07be9a",
          "sha256": "57981b9b4888c3cbd14584072792a04910cbf986469d3a8eafea4962a8d77a16",
          "sha1": "945e792b4fd5267a3f4b3c681aa1f145f4a22d53",
          "md5": "fda9d61e427c846430bea0b32c2e743c"
        }
      ]
    }
  ]
}
