{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2a",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.5.jar",
          "url": "ble-characteristic-u2b2a-0.8.5.jar",
          "size": 1749,
          "sha512": "a867e0cb03ac265816fdc9e939fd332f9111ba05648d1c58cd972ce5204603f75c33eea625b1cb03b2bbbff05bef2fc7ffaccff5850e70c920d078ddf6e25eee",
          "sha256": "5a445c97aee8c377b3a7b9d71db5944ba1d6a070cd85cec06175f9dfb379d782",
          "sha1": "6a213192ca0992c07a09f00737a6dc6478987a8a",
          "md5": "8e5957d77f9a79d9288d9f5e39efee7f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.5.jar",
          "url": "ble-characteristic-u2b2a-0.8.5.jar",
          "size": 1749,
          "sha512": "a867e0cb03ac265816fdc9e939fd332f9111ba05648d1c58cd972ce5204603f75c33eea625b1cb03b2bbbff05bef2fc7ffaccff5850e70c920d078ddf6e25eee",
          "sha256": "5a445c97aee8c377b3a7b9d71db5944ba1d6a070cd85cec06175f9dfb379d782",
          "sha1": "6a213192ca0992c07a09f00737a6dc6478987a8a",
          "md5": "8e5957d77f9a79d9288d9f5e39efee7f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b2a-0.8.5-javadoc.jar",
          "size": 107345,
          "sha512": "29cca2e23020aff9b4f4760351d38c4319619bf622f46fa0cfe4a8cbbf3bda0eadc549f4b721bd195dfb07bc8f480400bdc3ce529dbeebd5da6f0ae462cd9230",
          "sha256": "d80d40a776bde4dd4ba18a41a4c4bea614793f02d27ff0c0533659a0d0eeec4e",
          "sha1": "fbe9d518167acbe7781b6246af8634a8b1e1b4b1",
          "md5": "4df78c0c4473cce4c31d6e21238189da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b2a-0.8.5-sources.jar",
          "size": 1603,
          "sha512": "3ad6a7951a9f23b4ae55b8c58cae27eb7f534611c4f5801a0a0d690d260db7f04276fd4dcdeb0afd29cbfaeb18563314c000949711efde9ac77f7e5d7d6226e3",
          "sha256": "87fe39f1374f1cee50f38d0aab2f041450ec8e02ce9e257f5522c9fa6357a3a4",
          "sha1": "91bf3316dfab0af41427b0525a00c460c3bf37f3",
          "md5": "99643e1132fec8b23f89b9d30fc80976"
        }
      ]
    }
  ]
}
