{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-htp-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-htp-android-0.8.6.aar",
          "url": "ble-profile-htp-android-0.8.6.aar",
          "size": 1220,
          "sha512": "358d449facbb9c37f5afd6df967c6305e24c75d3018661f70e8836f0d6f274d5195cce113676616adf5250bdff19673c68bf5d538d74c0cec8b5201fddb33455",
          "sha256": "f2fc6a22912b8299af97a35c71a990d54b0797fad620e9e4ce29ef7796c4bfcd",
          "sha1": "1a6e3e3f97d79c181e5fc4535a5fa9b3cddb840a",
          "md5": "3da43d45def5bfb18ae9a92300189c48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-htp-android-0.8.6.aar",
          "url": "ble-profile-htp-android-0.8.6.aar",
          "size": 1220,
          "sha512": "358d449facbb9c37f5afd6df967c6305e24c75d3018661f70e8836f0d6f274d5195cce113676616adf5250bdff19673c68bf5d538d74c0cec8b5201fddb33455",
          "sha256": "f2fc6a22912b8299af97a35c71a990d54b0797fad620e9e4ce29ef7796c4bfcd",
          "sha1": "1a6e3e3f97d79c181e5fc4535a5fa9b3cddb840a",
          "md5": "3da43d45def5bfb18ae9a92300189c48"
        }
      ]
    }
  ]
}
