{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-peripheral",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-android-0.4.3.aar",
          "url": "ble-service-peripheral-android-0.4.3.aar",
          "size": 2192,
          "sha512": "7e2c6a17d49275e8756445baab083a2bebf356f048f00a4c43172bdf74b8f192179fc6239706fd7f5ac8d8ba10860d2a1655f042c524f92d39066770a60bc1f9",
          "sha256": "7ffc4d3e1330efa3af19dce2d3e6d3d326163810476ae7c8d5b46115c0688e61",
          "sha1": "8c56ff77c341fe4074624e4a9cb103daa8bdb5bf",
          "md5": "0dba9aba058d6a4a3d61fbb6e42437d3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-peripheral",
          "version": {
            "requires": "0.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-android-0.4.3.aar",
          "url": "ble-service-peripheral-android-0.4.3.aar",
          "size": 2192,
          "sha512": "7e2c6a17d49275e8756445baab083a2bebf356f048f00a4c43172bdf74b8f192179fc6239706fd7f5ac8d8ba10860d2a1655f042c524f92d39066770a60bc1f9",
          "sha256": "7ffc4d3e1330efa3af19dce2d3e6d3d326163810476ae7c8d5b46115c0688e61",
          "sha1": "8c56ff77c341fe4074624e4a9cb103daa8bdb5bf",
          "md5": "0dba9aba058d6a4a3d61fbb6e42437d3"
        }
      ]
    }
  ]
}
