{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a44-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.8.10.aar",
          "url": "ble-characteristic-u2a44-android-0.8.10.aar",
          "size": 3257,
          "sha512": "f3c478add89516188177cf07d77840e3d13227eeb2fbe7ac9c5302da3372b72e90f2104b839d936d3b54c04eb59d333d7873190dbd49d51951b48c224a8bfaac",
          "sha256": "dcdde92ca0d7730879cbe94fda3736a1553bc56306718f779c4d99518631c4c6",
          "sha1": "987309ce46ccb9e5ed34cb66ee2220fda1f83ced",
          "md5": "b8925f22fb45597e843c92f7b1176f71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.8.10.aar",
          "url": "ble-characteristic-u2a44-android-0.8.10.aar",
          "size": 3257,
          "sha512": "f3c478add89516188177cf07d77840e3d13227eeb2fbe7ac9c5302da3372b72e90f2104b839d936d3b54c04eb59d333d7873190dbd49d51951b48c224a8bfaac",
          "sha256": "dcdde92ca0d7730879cbe94fda3736a1553bc56306718f779c4d99518631c4c6",
          "sha1": "987309ce46ccb9e5ed34cb66ee2220fda1f83ced",
          "md5": "b8925f22fb45597e843c92f7b1176f71"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2a44-android-0.8.10-sources.jar",
          "size": 2259,
          "sha512": "8b8be777b26e2d82dea5d0f648b8d7d32b6912ee647db1e5eb829cc12c41cd51ee2ea9e774a99f0f5dab9d0100f12c83f7193f4c89c4d3a717200b933fefac9c",
          "sha256": "1616a4edbfa096ebc98758419bf55a943ac369e6220bef31f513c78fc6ca6cb6",
          "sha1": "cfebaf5850fd7175f88efd1debdd73789715f1f2",
          "md5": "882f9bb6ffbb5c271f07981a826ee045"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2a44-android-0.8.10-javadoc.jar",
          "size": 272728,
          "sha512": "63030c25dd63c64795fe503f44a94d1a79ab1c2507c9dd72c8725e7d663b7b8a43e934430af397ec806830dab3bace35c0f2c5263ad39573ea01097ac64c4a30",
          "sha256": "d4af6fb3f273682517a94246aae4c6d89f60aa301ed59a863dc5bae5b79f66aa",
          "sha1": "1936a33db58e21235f588a9b6eeec6b74aa5f186",
          "md5": "9ac5e62c712cc717e472558552d1b89f"
        }
      ]
    }
  ]
}
