{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab4-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.2.9.aar",
          "url": "ble-characteristic-u2ab4-android-0.2.9.aar",
          "size": 3113,
          "sha512": "8c88bce64a4587060da6fbbfb3902433ab1566e1120c07f38898f93c52cc14fe5894a2a9552eecf64447542ae9af431ef4161f311f104c070613d82d4f546a5f",
          "sha256": "52537f6102558c25422184f86b4a7ba303bbb3ae44685e43c4a48ce537ed98e1",
          "sha1": "c3e77d5ec87dd740a26929f1f7b502a1587d4d51",
          "md5": "1621e8cf1b6e2c5e6808016d760655c0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.2.9.aar",
          "url": "ble-characteristic-u2ab4-android-0.2.9.aar",
          "size": 3113,
          "sha512": "8c88bce64a4587060da6fbbfb3902433ab1566e1120c07f38898f93c52cc14fe5894a2a9552eecf64447542ae9af431ef4161f311f104c070613d82d4f546a5f",
          "sha256": "52537f6102558c25422184f86b4a7ba303bbb3ae44685e43c4a48ce537ed98e1",
          "sha1": "c3e77d5ec87dd740a26929f1f7b502a1587d4d51",
          "md5": "1621e8cf1b6e2c5e6808016d760655c0"
        }
      ]
    }
  ]
}
