{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad9-android",
    "version": "0.2.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad9-android-0.2.10.aar",
          "url": "ble-characteristic-u2ad9-android-0.2.10.aar",
          "size": 3247,
          "sha512": "f545396baeffda9d824af729e4b68ac0af70df79a7eb87cdc8493df6a1cba899952d6e24963b982bc9481e772f7227ddbd8fc9109cb08cef9d64e4d120be0e84",
          "sha256": "9361645848dd89c0bb0ab1650ca3ee73d54c1d0bcb14f14fa5b8ef022bc26745",
          "sha1": "ee7841477249e44aa490da8edfbb0e5bf41b3317",
          "md5": "95104dce40b3eca8bedb34eb428b8f3f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9",
          "version": {
            "requires": "0.2.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad9-android-0.2.10.aar",
          "url": "ble-characteristic-u2ad9-android-0.2.10.aar",
          "size": 3247,
          "sha512": "f545396baeffda9d824af729e4b68ac0af70df79a7eb87cdc8493df6a1cba899952d6e24963b982bc9481e772f7227ddbd8fc9109cb08cef9d64e4d120be0e84",
          "sha256": "9361645848dd89c0bb0ab1650ca3ee73d54c1d0bcb14f14fa5b8ef022bc26745",
          "sha1": "ee7841477249e44aa490da8edfbb0e5bf41b3317",
          "md5": "95104dce40b3eca8bedb34eb428b8f3f"
        }
      ]
    }
  ]
}
