{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3c",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.8.jar",
          "url": "ble-characteristic-u2b3c-0.8.8.jar",
          "size": 1501,
          "sha512": "41dc81a03c9f79a3f2cb6e1b26fda3f1621f99cc877702cd50cdee2425984598c26186909359ef38af9fade1e97999f51c3571662f51518c3f7c2cd21d98ae7b",
          "sha256": "b6e43cac101f247967ca5d2586d3b5fb8421b8376d6a7521dbbde36582187f15",
          "sha1": "9eabc78dc10b5d787e2bdfc7149b02469fe4ef07",
          "md5": "0b95cc16737e9ac0dd6dcdfae7c1d2e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.8.jar",
          "url": "ble-characteristic-u2b3c-0.8.8.jar",
          "size": 1501,
          "sha512": "41dc81a03c9f79a3f2cb6e1b26fda3f1621f99cc877702cd50cdee2425984598c26186909359ef38af9fade1e97999f51c3571662f51518c3f7c2cd21d98ae7b",
          "sha256": "b6e43cac101f247967ca5d2586d3b5fb8421b8376d6a7521dbbde36582187f15",
          "sha1": "9eabc78dc10b5d787e2bdfc7149b02469fe4ef07",
          "md5": "0b95cc16737e9ac0dd6dcdfae7c1d2e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2b3c-0.8.8-javadoc.jar",
          "size": 107291,
          "sha512": "7ccff99a910744c789e5de11c703b229ef40416b63cacb5a3362e4446e966b976b7c5c627731ba1ed06ac39b4f57a931e6346f987e6a905a405696ecb2cf87a4",
          "sha256": "605ab06ce8a1dac3de684921050e45a48359c069d43eb5728082c767ef3a78f8",
          "sha1": "14c19f30cb0cb14457aec146d42cd9af50b29914",
          "md5": "b91c09c64e15f2ca12a9dad6acc72052"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.8-sources.jar",
          "url": "ble-characteristic-u2b3c-0.8.8-sources.jar",
          "size": 1500,
          "sha512": "e98bc17a4154b2faea52b5eae67b4244f344074753229d95601e61f928874d3bb7a2f8a75473c097b76ab2e4b248290aaf9a0b34855384c2ec64eaa3933f45a4",
          "sha256": "e28a59fbfdb27873c93bf4f56f58a165fa17a3894dd49d8cc08b92a29b72f545",
          "sha1": "bdf35378669fe5cb9f9d3cf87fe48888f7c74693",
          "md5": "ec66d1b523b7d9610008fb91fc78df20"
        }
      ]
    }
  ]
}
