{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a45-android",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a45-android-0.8.4.aar",
          "url": "ble-characteristic-u2a45-android-0.8.4.aar",
          "size": 3090,
          "sha512": "dc71708122087e1d051e15cef370481347339b7544f09792ed0330136a00fa7a6b7ce970c939c376acfb4eff2fde62d7a8d433c92f28da52e7abb062f76f322c",
          "sha256": "0ae523188f80ae6d1f3dbd67ce6a9240c59b9a0d757b8151d668af4a608e76ee",
          "sha1": "60270cee246ce8d3bf16dbba19d2d931cbbd9292",
          "md5": "acba1b19842d47a1b4c5c4bf6102c07e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45",
          "version": {
            "requires": "0.8.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a45-android-0.8.4.aar",
          "url": "ble-characteristic-u2a45-android-0.8.4.aar",
          "size": 3090,
          "sha512": "dc71708122087e1d051e15cef370481347339b7544f09792ed0330136a00fa7a6b7ce970c939c376acfb4eff2fde62d7a8d433c92f28da52e7abb062f76f322c",
          "sha256": "0ae523188f80ae6d1f3dbd67ce6a9240c59b9a0d757b8151d668af4a608e76ee",
          "sha1": "60270cee246ce8d3bf16dbba19d2d931cbbd9292",
          "md5": "acba1b19842d47a1b4c5c4bf6102c07e"
        }
      ]
    }
  ]
}
