{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afd",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.5.jar",
          "url": "ble-characteristic-u2afd-0.8.5.jar",
          "size": 2090,
          "sha512": "42314a0014253784ca47334d2c3da1b5f03a7da21ae5857ce61be572d180ffbdde592afd3a23d43be139bb4d79faca06a070e4c08d410d9a4fbf9e68bfbf3322",
          "sha256": "0afd7ad899cee6091f5ca474081d4a118cd37f5abcd0df7ccd3fdb466c564631",
          "sha1": "4973947a73e107fdea909c2d8409225847f31061",
          "md5": "0ade788fc2ab564640ff2211cb3ecaa2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.5.jar",
          "url": "ble-characteristic-u2afd-0.8.5.jar",
          "size": 2090,
          "sha512": "42314a0014253784ca47334d2c3da1b5f03a7da21ae5857ce61be572d180ffbdde592afd3a23d43be139bb4d79faca06a070e4c08d410d9a4fbf9e68bfbf3322",
          "sha256": "0afd7ad899cee6091f5ca474081d4a118cd37f5abcd0df7ccd3fdb466c564631",
          "sha1": "4973947a73e107fdea909c2d8409225847f31061",
          "md5": "0ade788fc2ab564640ff2211cb3ecaa2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2afd-0.8.5-javadoc.jar",
          "size": 110083,
          "sha512": "03f5772da059f9c85d8a84a244e53783e9940891f7dd2961a311e8196656b25ea22d484e0cf611d8d8825e4eef3900d27656db71ef388a1e586c02744a4cdfd2",
          "sha256": "f7d00706e422b2b4ee1886351a7bc0d7a98cfb9e2feab0c661a5eb609a0538f9",
          "sha1": "a575f4cc0fb1e0f686f9a22d56bd2c3f82ff75e1",
          "md5": "28894c78f0bfbaf0e4c9f64d3bbf0990"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.5-sources.jar",
          "url": "ble-characteristic-u2afd-0.8.5-sources.jar",
          "size": 1965,
          "sha512": "7ad75c464a79fd9122e2e5e585d567d94f8ccefecc7009deca7e4c3a95d59dd7507f7b6b9b3c58af854e97dfd602d164ff446cdf29e181dfde68fdd59b326bb2",
          "sha256": "1c4a53ae5c62e652460c870909a4350c17932694f3fed6f07369640e26ec3428",
          "sha1": "f1a9be082b2e2354dbc6ad321514c0d7a9315cd4",
          "md5": "457c5f33cbaef412822f9226a4f343f3"
        }
      ]
    }
  ]
}
