{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-tip-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-tip-android-0.4.6.aar",
          "url": "ble-profile-tip-android-0.4.6.aar",
          "size": 1184,
          "sha512": "c11ef7b28aa2442d5c9acc3257f64dc7697af4cc09ee5782b6e466e95ded905a4cb08a2a704f8f95388fc6a2e4d49ce793f97710200dfe614ba36ff01fb0c39a",
          "sha256": "27921807f1ef18367b7ad60a5312b863a66295c81eee15461e9b34765bef7080",
          "sha1": "e58d11ee027ec58115920ab9ea7f4c3eda3205e0",
          "md5": "eb39d491d2a5f52ae00f5df34980292f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-tip-android-0.4.6.aar",
          "url": "ble-profile-tip-android-0.4.6.aar",
          "size": 1184,
          "sha512": "c11ef7b28aa2442d5c9acc3257f64dc7697af4cc09ee5782b6e466e95ded905a4cb08a2a704f8f95388fc6a2e4d49ce793f97710200dfe614ba36ff01fb0c39a",
          "sha256": "27921807f1ef18367b7ad60a5312b863a66295c81eee15461e9b34765bef7080",
          "sha1": "e58d11ee027ec58115920ab9ea7f4c3eda3205e0",
          "md5": "eb39d491d2a5f52ae00f5df34980292f"
        }
      ]
    }
  ]
}
