{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a89-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.8.12.aar",
          "url": "ble-characteristic-u2a89-android-0.8.12.aar",
          "size": 3238,
          "sha512": "12485c34e55f28b0d29725d1dc71441e73dc2cd483599ed749ba7fd837bbef1eae7a4d4eccd6a61238ca4327116cbc00baf70eef267830076cc5566c1747ef19",
          "sha256": "6cfca28479c5955f01d90519ea601665febab8189c8bff7a2111b7b5f079eedd",
          "sha1": "98f005cfb747f3fbbe3447431ec99e6a71fd6c2b",
          "md5": "10e8c8ed0c35d926d34800bcfc8bd442"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.8.12.aar",
          "url": "ble-characteristic-u2a89-android-0.8.12.aar",
          "size": 3238,
          "sha512": "12485c34e55f28b0d29725d1dc71441e73dc2cd483599ed749ba7fd837bbef1eae7a4d4eccd6a61238ca4327116cbc00baf70eef267830076cc5566c1747ef19",
          "sha256": "6cfca28479c5955f01d90519ea601665febab8189c8bff7a2111b7b5f079eedd",
          "sha1": "98f005cfb747f3fbbe3447431ec99e6a71fd6c2b",
          "md5": "10e8c8ed0c35d926d34800bcfc8bd442"
        }
      ]
    }
  ]
}
