{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a89-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.8.12.aar",
          "url": "ble-characteristic-u2a89-android-0.8.12.aar",
          "size": 3172,
          "sha512": "7ffbd47aa65f51f7ef26069ad9b75dbe55601f202e7c446c1774478530f0d87b0b32a4eda477df8d076fcdeaebec4a19b9de5480c7990782509b5997a31d203c",
          "sha256": "8a6132e660ee3c183a0979ab9246c96847114699488aab6800ee57695941128a",
          "sha1": "68d3a32eaba0065544f4be28ed7ac32a162ca33d",
          "md5": "62dbec5383aa62df273581656766e514"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.8.12.aar",
          "url": "ble-characteristic-u2a89-android-0.8.12.aar",
          "size": 3172,
          "sha512": "7ffbd47aa65f51f7ef26069ad9b75dbe55601f202e7c446c1774478530f0d87b0b32a4eda477df8d076fcdeaebec4a19b9de5480c7990782509b5997a31d203c",
          "sha256": "8a6132e660ee3c183a0979ab9246c96847114699488aab6800ee57695941128a",
          "sha1": "68d3a32eaba0065544f4be28ed7ac32a162ca33d",
          "md5": "62dbec5383aa62df273581656766e514"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a89-android-0.8.12-sources.jar",
          "size": 2239,
          "sha512": "f043eb6ff8e042a0461f9d806854a58af429766a0a440bb64c140654e5fef25204a33194774d83e3ddfa96d39390df9b68501424290b74973fd3daa31e09da2a",
          "sha256": "5fab80ce55fc30a883110ec4490d0dfc735d7fb0a6a9a025635a1c7008c01591",
          "sha1": "3daa00592ba20b48c33a3ca2859bf9e27c95c917",
          "md5": "bade540a018bcb47511742db4dc0dd58"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a89-android-0.8.12-javadoc.jar",
          "size": 271273,
          "sha512": "c4cf5994888301afe04a12d02d66d207082c37d8be714ae0b1c9233691ebdd83dc05c988e6d37418c735a6e7d2de1b0c8d120e5e8e2c3a1cab17a313e6a5fd59",
          "sha256": "1a2ed20ef6c19325bb00f057c4689966b28d3812365be15de7326e2a7ea2b0c0",
          "sha1": "295ee69c8cf4f144ffc64174d99a149db1494fcc",
          "md5": "abd07dc0a1c81bee69317e5d9b62bfbe"
        }
      ]
    }
  ]
}
