{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a78-android",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a78",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-android-0.6.0.aar",
          "url": "ble-characteristic-u2a78-android-0.6.0.aar",
          "size": 3033,
          "sha512": "dd55e87c1dee4210cab8f566889ce8e87c6bde139fd4993ccb9f144b8f4b86cc046d19c3c58aabe7b80f42060bd7e21bc59ca3f71b7ae9eff8f646d3c6dd4f8b",
          "sha256": "753fdfb923b5d1f5784e4c5a3f1584ec38a99c780d0b142620c673e8ea8318cb",
          "sha1": "532c98a0fd62f8740921b419acb237e481c1adf0",
          "md5": "718bdaf8fb7eba638296bf0e38a01c76"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a78",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-android-0.6.0.aar",
          "url": "ble-characteristic-u2a78-android-0.6.0.aar",
          "size": 3033,
          "sha512": "dd55e87c1dee4210cab8f566889ce8e87c6bde139fd4993ccb9f144b8f4b86cc046d19c3c58aabe7b80f42060bd7e21bc59ca3f71b7ae9eff8f646d3c6dd4f8b",
          "sha256": "753fdfb923b5d1f5784e4c5a3f1584ec38a99c780d0b142620c673e8ea8318cb",
          "sha1": "532c98a0fd62f8740921b419acb237e481c1adf0",
          "md5": "718bdaf8fb7eba638296bf0e38a01c76"
        }
      ]
    }
  ]
}
