{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-cscp-central-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-cscp-central-android-0.1.3.aar",
          "url": "ble-profile-cscp-central-android-0.1.3.aar",
          "size": 6055,
          "sha512": "dc4897d0acd6ed52b7a1758521a7e85b738fda9a308e4f0123be8ad68d80a437be4e32ac2fe92e5b05d7e45722faff2536976cdc8c644c9b20d503d520ccf5ba",
          "sha256": "8585713eb93074b2bced7a12564d57860bf4f9b3075c9d782d5105ccee022ab0",
          "sha1": "b3b7157dc532edf6738db7514656e43a444393ab",
          "md5": "af79a7522eea894eb71b0c720a03d5a0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-cscp-central-android-0.1.3.aar",
          "url": "ble-profile-cscp-central-android-0.1.3.aar",
          "size": 6055,
          "sha512": "dc4897d0acd6ed52b7a1758521a7e85b738fda9a308e4f0123be8ad68d80a437be4e32ac2fe92e5b05d7e45722faff2536976cdc8c644c9b20d503d520ccf5ba",
          "sha256": "8585713eb93074b2bced7a12564d57860bf4f9b3075c9d782d5105ccee022ab0",
          "sha1": "b3b7157dc532edf6738db7514656e43a444393ab",
          "md5": "af79a7522eea894eb71b0c720a03d5a0"
        }
      ]
    }
  ]
}
