{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9e",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9e-0.8.12.jar",
          "url": "ble-characteristic-u2b9e-0.8.12.jar",
          "size": 1460,
          "sha512": "9b5a4adcb4ebbc71989019b9242f73613d702ef171c84036b06f67e1e536bfb4c55f4973228f6c9bdbf46e376d05ff4a4a5603b35d7e27f1b9e6bc98e21f5a06",
          "sha256": "615a072a27fe869e64fe379469a337a627101e54c4b3adb20b1f8374221b5dbf",
          "sha1": "1fd8309a784bb53bdc14726ec937cd9331e09181",
          "md5": "87794e0f47d2ff2cb1c06cf2d5602111"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9e-0.8.12.jar",
          "url": "ble-characteristic-u2b9e-0.8.12.jar",
          "size": 1460,
          "sha512": "9b5a4adcb4ebbc71989019b9242f73613d702ef171c84036b06f67e1e536bfb4c55f4973228f6c9bdbf46e376d05ff4a4a5603b35d7e27f1b9e6bc98e21f5a06",
          "sha256": "615a072a27fe869e64fe379469a337a627101e54c4b3adb20b1f8374221b5dbf",
          "sha1": "1fd8309a784bb53bdc14726ec937cd9331e09181",
          "md5": "87794e0f47d2ff2cb1c06cf2d5602111"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9e-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b9e-0.8.12-javadoc.jar",
          "size": 86012,
          "sha512": "3869ba84531965808e2d363eb28ec379aacd6babc768aaa407c5ff7cfb9c9fdcef92e1608b151f6654aafc37dc3fdcbd2064edf2d3494817f40bcb589b4d7b58",
          "sha256": "fc6be7fd0fb6aa3a4966aa63cab149e68a6af2f722e1930ed63b14655fb4c014",
          "sha1": "3b3da7021fe1e128c2d37bfd1fa447ce98eb1827",
          "md5": "717339c39305e1d670f92f48181a61ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9e-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b9e-0.8.12-sources.jar",
          "size": 1457,
          "sha512": "6fa08e753f9e2fda95041e093bda4182145abdec8e1c040e1effaf1968b51cd01b32f70b02d1aa9ea2f6b24ffef942dd101fb89d881a5b2a625d3271af072dc7",
          "sha256": "c044d1d2db1bb18535ab54925b62e9dfb174b0bd0c39cb2e6fe0ac0bf322f019",
          "sha1": "97e28947902a576557d1e88b60e5f06872440cdf",
          "md5": "28488da37318ac3cce9290b762de2e83"
        }
      ]
    }
  ]
}
