{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aad",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.10.jar",
          "url": "ble-characteristic-u2aad-0.8.10.jar",
          "size": 1772,
          "sha512": "71577da98c6e5b8d7e8214cffc195b9a6bc249aa9a6fb2a61c233dae09709da914acd5096a6582f9c35b5edd69eb7c03fa7ddf31ceec124c59839d56af4fb5f9",
          "sha256": "d19411ec9bb0e800f72a15bbdcb9b75e6bcbf3e432f1a92cba04f7159762e37b",
          "sha1": "cb32e8d6e60fe8b95d4023813228d4eaffb5d815",
          "md5": "748a1c151abf9c28c4280384b2518e91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.10.jar",
          "url": "ble-characteristic-u2aad-0.8.10.jar",
          "size": 1772,
          "sha512": "71577da98c6e5b8d7e8214cffc195b9a6bc249aa9a6fb2a61c233dae09709da914acd5096a6582f9c35b5edd69eb7c03fa7ddf31ceec124c59839d56af4fb5f9",
          "sha256": "d19411ec9bb0e800f72a15bbdcb9b75e6bcbf3e432f1a92cba04f7159762e37b",
          "sha1": "cb32e8d6e60fe8b95d4023813228d4eaffb5d815",
          "md5": "748a1c151abf9c28c4280384b2518e91"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2aad-0.8.10-javadoc.jar",
          "size": 107484,
          "sha512": "a2ad317625d18df56d9765058a75e572480e34e0f0357a5e6a144ada597398d4b9ca0d2390cdde1a117a572f486176b4888c4b7a05c0d08fa879a57abe72fb8f",
          "sha256": "22d9dd151d9c9892cdbd641bb239f81c6210567c7ea618f509a9a699ab03491f",
          "sha1": "164dc6d2d3144cb30a37ac393d9c2923de52262f",
          "md5": "11a4e0a9510302f07ba989454260e2ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.10-sources.jar",
          "url": "ble-characteristic-u2aad-0.8.10-sources.jar",
          "size": 1636,
          "sha512": "bf8f5871a9572bd1fb4146cfed80fd2e1a79abd64181df5764a7eb08943028401fc8e9ca07ae0c51414c6660aa84a93fa0b134f47fc034c0fa7f1465a410cec0",
          "sha256": "ae980fc0b88e06823b51611e9b05b44b92154d6dbfd6221fa7c2ad14d284f160",
          "sha1": "b6096aed4eeedf9b9a006090cfb1d69047050816",
          "md5": "7ea2f194bfefbcac4499c6cafdabc831"
        }
      ]
    }
  ]
}
