{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-characteristic",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.11.jar",
          "url": "ble-core-constants-characteristic-0.8.11.jar",
          "size": 29059,
          "sha512": "d68e947e3d9df13707aec985849a225b2c4ffff1fd6d8bffea08c684b56feba85bfe64ecbebbd5501f7d2574a3de195e700c2bff70e38f0f51c27e7a214a8e59",
          "sha256": "252f4b2c62d3503e824c95151a6cc30c65a1a4c82875a2de70fa516d68d5f3c4",
          "sha1": "d0642b3aff68df1ff4041e96af793529ac201e75",
          "md5": "3496c31a36e1c21a774833dd2035a837"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.11.jar",
          "url": "ble-core-constants-characteristic-0.8.11.jar",
          "size": 29059,
          "sha512": "d68e947e3d9df13707aec985849a225b2c4ffff1fd6d8bffea08c684b56feba85bfe64ecbebbd5501f7d2574a3de195e700c2bff70e38f0f51c27e7a214a8e59",
          "sha256": "252f4b2c62d3503e824c95151a6cc30c65a1a4c82875a2de70fa516d68d5f3c4",
          "sha1": "d0642b3aff68df1ff4041e96af793529ac201e75",
          "md5": "3496c31a36e1c21a774833dd2035a837"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.11-javadoc.jar",
          "url": "ble-core-constants-characteristic-0.8.11-javadoc.jar",
          "size": 151676,
          "sha512": "ea430a4c7b96323bd17e1eb2fa53f87e6d013c8a5a14bce241ced99ddb2995e06f23bd18d696ee92a4958164d7b91be1dc79fb53f6e764f6acb3ee9f87187770",
          "sha256": "50a45f9e01758d3285cb715befdc66fb28bc5c54d708b77655ec13e4d79d451e",
          "sha1": "05911107e2712761bbb498fa3250d8be5eb90e61",
          "md5": "f911ac674b637a2359a8391f8baf4464"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-characteristic-0.8.11-sources.jar",
          "url": "ble-core-constants-characteristic-0.8.11-sources.jar",
          "size": 17358,
          "sha512": "bc4b977c5a583b2a99fb9c716cc1d9a88056cfdc61a7e892cb6b8adb59b6fed0b9613347c66c2cba07821f2a6770e708748bdec89ab91f4790e3bc3c4ce83342",
          "sha256": "d10f0da142b469b0de25f3f28076242ef2cc540c4f271789c0cec2630f40bb63",
          "sha1": "7d21ebe32ffa3700bd3451749e0cbb74189299bb",
          "md5": "d4686430edf6298684205d5eda5b0a72"
        }
      ]
    }
  ]
}
