{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5d-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.2.0.aar",
          "url": "ble-characteristic-u2a5d-android-0.2.0.aar",
          "size": 2900,
          "sha512": "eac5cc09009b22f74d3865f69a624685d02249d5ca3e35d452736532bdcd80a9911833d37e5d92015ac8c2c5df55c3e7caa0a313ed249981b5eb0de808f05559",
          "sha256": "0e3769976def6a6fc8beaabb21594cb8356ed2e27621a090f4f7288e83f6da4d",
          "sha1": "e19394bfdfd168ec6467c66d711dff2d76a79aa7",
          "md5": "a7944b7507d2f718c95cf920d77b503f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.2.0.aar",
          "url": "ble-characteristic-u2a5d-android-0.2.0.aar",
          "size": 2900,
          "sha512": "eac5cc09009b22f74d3865f69a624685d02249d5ca3e35d452736532bdcd80a9911833d37e5d92015ac8c2c5df55c3e7caa0a313ed249981b5eb0de808f05559",
          "sha256": "0e3769976def6a6fc8beaabb21594cb8356ed2e27621a090f4f7288e83f6da4d",
          "sha1": "e19394bfdfd168ec6467c66d711dff2d76a79aa7",
          "md5": "a7944b7507d2f718c95cf920d77b503f"
        }
      ]
    }
  ]
}
