{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd8",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.6.jar",
          "url": "ble-characteristic-u2bd8-0.8.6.jar",
          "size": 1928,
          "sha512": "0ed611cf78ef1ecd9153dc74ccd78342547cc56d9e029edeb09ce2af5d65fed922dd50fbd897cffa867cdcdd692f560f10f9ec22c91dfdedfe3d74eda6f62489",
          "sha256": "75209abf824556b66a86fe7cc4abdaf630396e7771af1c2c66676cbb109cd058",
          "sha1": "3a3d92447dcba33d72ffd47f9e6e832c6e34757d",
          "md5": "162e8325b4447c3aedff673af8c61188"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.6.jar",
          "url": "ble-characteristic-u2bd8-0.8.6.jar",
          "size": 1928,
          "sha512": "0ed611cf78ef1ecd9153dc74ccd78342547cc56d9e029edeb09ce2af5d65fed922dd50fbd897cffa867cdcdd692f560f10f9ec22c91dfdedfe3d74eda6f62489",
          "sha256": "75209abf824556b66a86fe7cc4abdaf630396e7771af1c2c66676cbb109cd058",
          "sha1": "3a3d92447dcba33d72ffd47f9e6e832c6e34757d",
          "md5": "162e8325b4447c3aedff673af8c61188"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2bd8-0.8.6-javadoc.jar",
          "size": 107928,
          "sha512": "529284941ec49769f538569613e10f5914bc67055050b8c2f5bdee6b85391e08120ba7ee87c4e6ea29c120b741758df45f9ce2031c1934f56e231216b4302e3d",
          "sha256": "4637e1cf38c07da469cef97b71dc384b83dd4c92bb763b29a56fc665e0ac2a97",
          "sha1": "d753ca2209f07fa94c54bfdf761ce256a76f8233",
          "md5": "4562ed098582e6e97908b98b700b838f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd8-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bd8-0.8.6-sources.jar",
          "size": 1939,
          "sha512": "a50d06974af00c4a1d98a6a1e72e74a727a6526714ffeb1df647228d72d8668ec74cd22ddf1e8f93843978fb6b5bf7119a230f31557434e6b39ce951e4b24af8",
          "sha256": "2e7970106a7d8887d06873411c08c0a7b8d361220d90b92c82739aa41000d861",
          "sha1": "f465bb27a127f97baf11e58b96160ebabd1907dc",
          "md5": "6131d07ef271d608450808a5f227df02"
        }
      ]
    }
  ]
}
