{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-wsp-android",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-wss-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-uds-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-bas-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-cts-android",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-wsp-android-0.8.5.aar",
          "url": "ble-profile-peripheral-wsp-android-0.8.5.aar",
          "size": 12782,
          "sha512": "fc093e0c963c5fae2fb9f80404276e9e93897a8008020e6acb9870195a6bfa42b668de6d33eef647d23771eddac9cc79c06184570bd3292dd36d02e211f337a0",
          "sha256": "e8fdc7b00e8c17e4e95e51f794f11810bf2a3f084dc39031159c1939a0d1fe00",
          "sha1": "10b81d669f9701a73e0dea6619c2507ded7f9e59",
          "md5": "1d2ac82ba238d59c9e030bd8ef7d9c8d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-wss-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-uds-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-bas-android",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-cts-android",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-wsp-android-0.8.5.aar",
          "url": "ble-profile-peripheral-wsp-android-0.8.5.aar",
          "size": 12782,
          "sha512": "fc093e0c963c5fae2fb9f80404276e9e93897a8008020e6acb9870195a6bfa42b668de6d33eef647d23771eddac9cc79c06184570bd3292dd36d02e211f337a0",
          "sha256": "e8fdc7b00e8c17e4e95e51f794f11810bf2a3f084dc39031159c1939a0d1fe00",
          "sha1": "10b81d669f9701a73e0dea6619c2507ded7f9e59",
          "md5": "1d2ac82ba238d59c9e030bd8ef7d9c8d"
        }
      ]
    }
  ]
}
