{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b90-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b90",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b90-android-0.8.6.aar",
          "url": "ble-characteristic-u2b90-android-0.8.6.aar",
          "size": 3034,
          "sha512": "2366903599831ed8cc1e890517d2e09397a4c20fe45e3229f6f23d777068466827ef16739f60ad4f14d77da8223c803cbac381cc81bf5d1db7dde1afcfca534f",
          "sha256": "834e9d0ab6c809ba0057dc1b52c5749af21369c0cb284bff90a045db343aa195",
          "sha1": "4021c321d353874a27af821ebe89af2ab26bf18a",
          "md5": "1fc703783be924bd00368f93d9f36ff3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b90",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b90-android-0.8.6.aar",
          "url": "ble-characteristic-u2b90-android-0.8.6.aar",
          "size": 3034,
          "sha512": "2366903599831ed8cc1e890517d2e09397a4c20fe45e3229f6f23d777068466827ef16739f60ad4f14d77da8223c803cbac381cc81bf5d1db7dde1afcfca534f",
          "sha256": "834e9d0ab6c809ba0057dc1b52c5749af21369c0cb284bff90a045db343aa195",
          "sha1": "4021c321d353874a27af821ebe89af2ab26bf18a",
          "md5": "1fc703783be924bd00368f93d9f36ff3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b90-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b90-android-0.8.6-sources.jar",
          "size": 2128,
          "sha512": "5e1a456ffc84b36223502ac561d429254ae82244673bca0b80ded2733611af49b10a25ef36a59bb021ad2a260e4aa9be890f80fe6808fab32ba17de4502a2e33",
          "sha256": "9e70b9b4ecbce9754e7516635ab15002e0bad58df85c32257fc64db96707526b",
          "sha1": "d7f3b8c2a542495fc77619c7fcdae782a6e1a8a2",
          "md5": "d50c3526bd828af686c611f8773b853e"
        }
      ]
    }
  ]
}
