{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba7",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.6.jar",
          "url": "ble-characteristic-u2ba7-0.8.6.jar",
          "size": 1464,
          "sha512": "6238a598225ab64d0dc6a1d345ce3cf881dec1d239fd3b49442af0621110a62caf6df222c648156e01d77847210e98f30a51bfd0f82b4333424b1ca10918d984",
          "sha256": "fd1feb8593a50c025f03aa0fecca9ba13e39d5e38eadf1c7b4679efd3deee20e",
          "sha1": "f198da187ac104f0d8e5553c48b67b31eb5eaf91",
          "md5": "fd61c82b15ac413ca631b92676912497"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.6.jar",
          "url": "ble-characteristic-u2ba7-0.8.6.jar",
          "size": 1464,
          "sha512": "6238a598225ab64d0dc6a1d345ce3cf881dec1d239fd3b49442af0621110a62caf6df222c648156e01d77847210e98f30a51bfd0f82b4333424b1ca10918d984",
          "sha256": "fd1feb8593a50c025f03aa0fecca9ba13e39d5e38eadf1c7b4679efd3deee20e",
          "sha1": "f198da187ac104f0d8e5553c48b67b31eb5eaf91",
          "md5": "fd61c82b15ac413ca631b92676912497"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2ba7-0.8.6-javadoc.jar",
          "size": 107172,
          "sha512": "55e1d33914a94c416ff12e7c08d087f36f44234a134f3faa1c73e74a5c43a4b85e3008f23bed84bdf048f41708ee1ff2d96ca3e78641ad5977785f6418f9df46",
          "sha256": "7cf030da75d8d24579b580b11b45e1849be86688007aec5d65a7277c284dbba7",
          "sha1": "70da2bac91b5dcf2bbe30dbfac071d23be833b87",
          "md5": "da89a7f15aaf1e1596d4d7b5ae093293"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba7-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ba7-0.8.6-sources.jar",
          "size": 1453,
          "sha512": "b2f2e01fad06423d35f94b8da68ebd51405160acc9a8265d3fbb4680c9f8a71dc6531b44a103c5319c1dfc876a3634709a46628d0ace22952e29be85ba7789b9",
          "sha256": "d3013c2fa992e98cecea83b6d5d822191bf10303af96489cff72a3163c4bbd96",
          "sha1": "3858fce35eccd7a8fecb37d435662abc7cd5f86b",
          "md5": "0205ca44ca55bd07cfcdde9545557d1e"
        }
      ]
    }
  ]
}
