{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2902-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.1.2.aar",
          "url": "ble-descriptor-u2902-android-0.1.2.aar",
          "size": 2908,
          "sha512": "2ee16cae9f231b8aa814cde96f08ecb8a3f2ee33437861e71aa21a2102760ebfc97f860a0ffaf2cf85c314e4300e2e896c26f5119b27b501325c3393673465d9",
          "sha256": "95ce99ef8e0807a1f8f8dbc2a689c80a4add26f5fc5e3ca930a9a0f98156c0f1",
          "sha1": "86b2c1a8ca2971ecb05e96a051273fd21485e7d1",
          "md5": "3ed8ecda1fe268c559719df2fce3a1ec"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.1.2.aar",
          "url": "ble-descriptor-u2902-android-0.1.2.aar",
          "size": 2908,
          "sha512": "2ee16cae9f231b8aa814cde96f08ecb8a3f2ee33437861e71aa21a2102760ebfc97f860a0ffaf2cf85c314e4300e2e896c26f5119b27b501325c3393673465d9",
          "sha256": "95ce99ef8e0807a1f8f8dbc2a689c80a4add26f5fc5e3ca930a9a0f98156c0f1",
          "sha1": "86b2c1a8ca2971ecb05e96a051273fd21485e7d1",
          "md5": "3ed8ecda1fe268c559719df2fce3a1ec"
        }
      ]
    }
  ]
}
