{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a0f",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0f-0.8.7.jar",
          "url": "ble-characteristic-u2a0f-0.8.7.jar",
          "size": 1849,
          "sha512": "519056db638a410d0bb9a5879e9aa0b0b7b603f6fa3882b879d87acde98dd368944942994a509eb2a53c486c4dba765a276574a5f933d6a80a6d2a23beb65919",
          "sha256": "3b428683b1aed0eb7104f6274dc895caa19cb83dcbf637b49af2f87af84cd3d5",
          "sha1": "a08f3ba5a6c2880290e51cce7cc5af8fb79c9414",
          "md5": "c24fe8814b78086fa85f2e491ae9cfec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0f-0.8.7.jar",
          "url": "ble-characteristic-u2a0f-0.8.7.jar",
          "size": 1849,
          "sha512": "519056db638a410d0bb9a5879e9aa0b0b7b603f6fa3882b879d87acde98dd368944942994a509eb2a53c486c4dba765a276574a5f933d6a80a6d2a23beb65919",
          "sha256": "3b428683b1aed0eb7104f6274dc895caa19cb83dcbf637b49af2f87af84cd3d5",
          "sha1": "a08f3ba5a6c2880290e51cce7cc5af8fb79c9414",
          "md5": "c24fe8814b78086fa85f2e491ae9cfec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a0f-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a0f-0.8.7-javadoc.jar",
          "size": 107539,
          "sha512": "82a8581de609c82e6c59eb831f54fb86a1dbf0e33db6aa1af4c3a83f7699858001cb6820283dd8f3d62758fbd18ef5413a815f4de7bd2c291bdc9ed923b10039",
          "sha256": "497a0101dd83fc3c007b8dff272de49c46b737f031d79f23a67cc207de470cac",
          "sha1": "3b5b6ec9a324b71381d7b6ef45c590eb371f73d0",
          "md5": "ff18dcb0110d1fccabe4a5584b138fb4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a0f-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a0f-0.8.7-sources.jar",
          "size": 1696,
          "sha512": "6a97e85c67b3fef67113ce58cededce618c1fb0d79aa95a2e0b0af9a55b4c3a07b9d0299679c1e956bf983f2dabaadf5909c2343a0894014d060f7d7d04c1706",
          "sha256": "ec879517d1167ae3f77896ccd4bc49f6fec0910e7d92814453be1f30840259eb",
          "sha1": "a16ddb1f82f5049cce751c454c36800c6d6e7526",
          "md5": "703b165018862db902a1eb128cf78406"
        }
      ]
    }
  ]
}
