{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a78",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "7cy2idx3u5f2th5ykjl4sg3gyy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-0.1.0.jar",
          "url": "ble-characteristic-u2a78-0.1.0.jar",
          "size": 1801,
          "sha512": "8a4c0c7c97bdd138f9f9ebaee8fc9b2e39245f9b779fcae5318fdf9de16e2d05a10efbfc85e3d480c7df2ec938d20e8e5f9b24cac32078d0c5dd0b4616d9ff49",
          "sha256": "74640b813b9e9ce621e7b377875cf24d7e895fe7f6c3ed00d650752a7b52552c",
          "sha1": "d153799374d72e0fc093f23204eb361a94669eb1",
          "md5": "71c0b196d0febd1bd225e1d3ca2847c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-0.1.0.jar",
          "url": "ble-characteristic-u2a78-0.1.0.jar",
          "size": 1801,
          "sha512": "8a4c0c7c97bdd138f9f9ebaee8fc9b2e39245f9b779fcae5318fdf9de16e2d05a10efbfc85e3d480c7df2ec938d20e8e5f9b24cac32078d0c5dd0b4616d9ff49",
          "sha256": "74640b813b9e9ce621e7b377875cf24d7e895fe7f6c3ed00d650752a7b52552c",
          "sha1": "d153799374d72e0fc093f23204eb361a94669eb1",
          "md5": "71c0b196d0febd1bd225e1d3ca2847c4"
        }
      ]
    }
  ]
}
