{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a93-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.2.4.aar",
          "url": "ble-characteristic-u2a93-android-0.2.4.aar",
          "size": 3199,
          "sha512": "65593c6e432bb57ee6683138445b1854184acb8e4d9ce8b577f2773554e35fbf7ef94aca90bc34e1343888a91f51de6aa9a871aecf5086e6330139e56026d627",
          "sha256": "9c80b4be92943c63672d87c49849831c9b594a3389fdb5d693325c18b63c3ab4",
          "sha1": "c326411e0563200dd645d20f4111d645e2ab9a6f",
          "md5": "52b6e7abe08e1ef8feedead037c55d26"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.2.4.aar",
          "url": "ble-characteristic-u2a93-android-0.2.4.aar",
          "size": 3199,
          "sha512": "65593c6e432bb57ee6683138445b1854184acb8e4d9ce8b577f2773554e35fbf7ef94aca90bc34e1343888a91f51de6aa9a871aecf5086e6330139e56026d627",
          "sha256": "9c80b4be92943c63672d87c49849831c9b594a3389fdb5d693325c18b63c3ab4",
          "sha1": "c326411e0563200dd645d20f4111d645e2ab9a6f",
          "md5": "52b6e7abe08e1ef8feedead037c55d26"
        }
      ]
    }
  ]
}
