{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a55",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "dhnodpmkbjgkzff4ltm3gds6mq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-0.2.1.jar",
          "url": "ble-characteristic-u2a55-0.2.1.jar",
          "size": 3130,
          "sha512": "ccdd2794eb7b63b1b08cf9d0321bd44e5b3f6ce464539ce6134db807ddb08e726dd108d9890126606297357803d2237ebd8c9b71bbfe4d163cdead1aacd9386a",
          "sha256": "27ffa2105a59327a1ccd5906f21e689fea29c1c82ba07fb4ff6f8cfa5970afc5",
          "sha1": "4a7bbc349c2f72ec3875c98b894877b61b83a143",
          "md5": "3c31326fd3c99f2ec9751cf764be29ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-0.2.1.jar",
          "url": "ble-characteristic-u2a55-0.2.1.jar",
          "size": 3130,
          "sha512": "ccdd2794eb7b63b1b08cf9d0321bd44e5b3f6ce464539ce6134db807ddb08e726dd108d9890126606297357803d2237ebd8c9b71bbfe4d163cdead1aacd9386a",
          "sha256": "27ffa2105a59327a1ccd5906f21e689fea29c1c82ba07fb4ff6f8cfa5970afc5",
          "sha1": "4a7bbc349c2f72ec3875c98b894877b61b83a143",
          "md5": "3c31326fd3c99f2ec9751cf764be29ca"
        }
      ]
    }
  ]
}
