{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab5-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab5",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab5-android-0.4.2.aar",
          "url": "ble-characteristic-u2ab5-android-0.4.2.aar",
          "size": 3106,
          "sha512": "48825f771c97611e896127e048d746d50e270c53db3dc4506ad5b9481b81eb1275b53534fd9946ff25a9491cc6a76790f1f2350bb0f1baa4cc9e5117e180ee4b",
          "sha256": "851bf0567cf4e0343e9f678e435ced16262774e461274788dec22979e88e0533",
          "sha1": "30c5fc8ff11af04a14a71a803ab9fba2b26055b4",
          "md5": "717a2c07b5422de85f870b235a143797"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab5",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab5-android-0.4.2.aar",
          "url": "ble-characteristic-u2ab5-android-0.4.2.aar",
          "size": 3106,
          "sha512": "48825f771c97611e896127e048d746d50e270c53db3dc4506ad5b9481b81eb1275b53534fd9946ff25a9491cc6a76790f1f2350bb0f1baa4cc9e5117e180ee4b",
          "sha256": "851bf0567cf4e0343e9f678e435ced16262774e461274788dec22979e88e0533",
          "sha1": "30c5fc8ff11af04a14a71a803ab9fba2b26055b4",
          "md5": "717a2c07b5422de85f870b235a143797"
        }
      ]
    }
  ]
}
