{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a28-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a28",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-android-0.8.12.aar",
          "url": "ble-characteristic-u2a28-android-0.8.12.aar",
          "size": 3232,
          "sha512": "2ccdb6b6c86ea3af0d785152d0cf668edec486d370c9282745b78274c5432fc8cead6482462b0e5bc73d73189f0323656aa5700eb32aa588e63c5df0ca6ad18f",
          "sha256": "469def9b862b1c7c27baeb4c37a0e2b415657a4d26bed665163b0f20b7e16ac4",
          "sha1": "d03865cff7cc4996c3bc2d4c19a8fd077eeb4716",
          "md5": "0f3ea7815c5d1243737d16b1a7ff750a"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a28",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-android-0.8.12.aar",
          "url": "ble-characteristic-u2a28-android-0.8.12.aar",
          "size": 3232,
          "sha512": "2ccdb6b6c86ea3af0d785152d0cf668edec486d370c9282745b78274c5432fc8cead6482462b0e5bc73d73189f0323656aa5700eb32aa588e63c5df0ca6ad18f",
          "sha256": "469def9b862b1c7c27baeb4c37a0e2b415657a4d26bed665163b0f20b7e16ac4",
          "sha1": "d03865cff7cc4996c3bc2d4c19a8fd077eeb4716",
          "md5": "0f3ea7815c5d1243737d16b1a7ff750a"
        }
      ]
    }
  ]
}
