{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-hts-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-hts-android-0.4.5.aar",
          "url": "ble-service-peripheral-hts-android-0.4.5.aar",
          "size": 8996,
          "sha512": "cc99ccf7a9445b243373daf977d3b1e54f853867f911248895935e6db530ecbc154a38c92b68d875dc25a1e1668a3cb2a505ced81bb62ff9a529ab89e00d482f",
          "sha256": "22e16787e1b1075b925748026a2faf84543a1d3a4cb54d35b57b62faf0f1fc57",
          "sha1": "34d429520c51d66d1830f1d79273b649b69eebae",
          "md5": "b161c3c4c5e8b5a132e7070953d43b92"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-android",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-hts-android-0.4.5.aar",
          "url": "ble-service-peripheral-hts-android-0.4.5.aar",
          "size": 8996,
          "sha512": "cc99ccf7a9445b243373daf977d3b1e54f853867f911248895935e6db530ecbc154a38c92b68d875dc25a1e1668a3cb2a505ced81bb62ff9a529ab89e00d482f",
          "sha256": "22e16787e1b1075b925748026a2faf84543a1d3a4cb54d35b57b62faf0f1fc57",
          "sha1": "34d429520c51d66d1830f1d79273b649b69eebae",
          "md5": "b161c3c4c5e8b5a132e7070953d43b92"
        }
      ]
    }
  ]
}
