{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-pxp-central-android",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-central-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pxp-central-android-0.1.7.aar",
          "url": "ble-profile-pxp-central-android-0.1.7.aar",
          "size": 6761,
          "sha512": "1825bd9ed31e65d69d8f735c93374f45510cb4ae2c90cfcaef73d537d1544a0d023d665b34db2ea3c7e09f62981e4b323492d510e7e85cc2eee4da08421eb1b1",
          "sha256": "1eb6b87455e730a6ee38f8c3b8ad4ad893133495d29dba0957ccbd4c45cc22de",
          "sha1": "77cb8b1cbae008efc2c99024f6a676506d78edd5",
          "md5": "0ee20ce7756e68b5209acf24b3222e56"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-central-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pxp-central-android-0.1.7.aar",
          "url": "ble-profile-pxp-central-android-0.1.7.aar",
          "size": 6761,
          "sha512": "1825bd9ed31e65d69d8f735c93374f45510cb4ae2c90cfcaef73d537d1544a0d023d665b34db2ea3c7e09f62981e4b323492d510e7e85cc2eee4da08421eb1b1",
          "sha256": "1eb6b87455e730a6ee38f8c3b8ad4ad893133495d29dba0957ccbd4c45cc22de",
          "sha1": "77cb8b1cbae008efc2c99024f6a676506d78edd5",
          "md5": "0ee20ce7756e68b5209acf24b3222e56"
        }
      ]
    }
  ]
}
