{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a83",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a83-0.8.10.jar",
          "url": "ble-characteristic-u2a83-0.8.10.jar",
          "size": 1739,
          "sha512": "fdc3c96588af88b4ac5fd8deda464f1dcc02fa42316521ee8abc03c2baf7c3d91f05f723bdb2fe73ce01c550b5893f503936a1da9bbd83651dfbe18d9765df5c",
          "sha256": "687739cad24c14c1330118e83ee70d0abb3aad056e74cc8b32951f88498ab24e",
          "sha1": "11cbc131cd50e9b29e2a9d2b503f3124305a4a8c",
          "md5": "4819c1f0f406b8a201239ad0207c7164"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a83-0.8.10.jar",
          "url": "ble-characteristic-u2a83-0.8.10.jar",
          "size": 1739,
          "sha512": "fdc3c96588af88b4ac5fd8deda464f1dcc02fa42316521ee8abc03c2baf7c3d91f05f723bdb2fe73ce01c550b5893f503936a1da9bbd83651dfbe18d9765df5c",
          "sha256": "687739cad24c14c1330118e83ee70d0abb3aad056e74cc8b32951f88498ab24e",
          "sha1": "11cbc131cd50e9b29e2a9d2b503f3124305a4a8c",
          "md5": "4819c1f0f406b8a201239ad0207c7164"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a83-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2a83-0.8.10-javadoc.jar",
          "size": 107384,
          "sha512": "29444e835787eb079afc8a80faf07c06ae0ece4197ac79b1d4d451bc4966e8df3d8d66029765ba00e30e353b70323d3a151a8632f1a03b0542db0f8eeb4f79e1",
          "sha256": "be9190ed7ebafc26f0829ed9544114a129c57720cf4b8b1f094e465453ac8357",
          "sha1": "96c7fa7b6cd7906df514343af47b5de88cc03318",
          "md5": "16f92fd681b90a799c528a8b2f294272"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a83-0.8.10-sources.jar",
          "url": "ble-characteristic-u2a83-0.8.10-sources.jar",
          "size": 1600,
          "sha512": "405bef8bc719625e6d87b61af3e933ac15ac61af310d8e2020f6ee41cbec3b064164120d03626577be30aa639be5455ac3d0967a19e9f0b3a0f00f4451a260c4",
          "sha256": "ef45d5d2950fd94a8a71dc60f0fec39976485ff931d608ab5671ea9e94e2b05a",
          "sha1": "059c8e74184e27cb804402c95f105c37486c1454",
          "md5": "d04afc3f327c821d6234bd245ee449a3"
        }
      ]
    }
  ]
}
