{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4d-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.14.aar",
          "url": "ble-characteristic-u2a4d-android-0.8.14.aar",
          "size": 3079,
          "sha512": "a52e61ff98fdab21ca2ef219f4c30e32762e3fc8fe93fce70f09ff3c298891b9f00df2c3624cccb0fc082373c6d406e3f109554a271b97c17a834e058724535a",
          "sha256": "0d52029455b25d3cd0ee4695114de5c7a1780fdc699eff2ce2bf6687a2b96d41",
          "sha1": "edf9414b07ca9f9b3558130c19017afdd930d3d4",
          "md5": "a97fdce7030c21378749f41986bdc356"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.14.aar",
          "url": "ble-characteristic-u2a4d-android-0.8.14.aar",
          "size": 3079,
          "sha512": "a52e61ff98fdab21ca2ef219f4c30e32762e3fc8fe93fce70f09ff3c298891b9f00df2c3624cccb0fc082373c6d406e3f109554a271b97c17a834e058724535a",
          "sha256": "0d52029455b25d3cd0ee4695114de5c7a1780fdc699eff2ce2bf6687a2b96d41",
          "sha1": "edf9414b07ca9f9b3558130c19017afdd930d3d4",
          "md5": "a97fdce7030c21378749f41986bdc356"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2a4d-android-0.8.14-sources.jar",
          "size": 2136,
          "sha512": "9a741fdc134bf2f6188d60a6d5ab8fdfa9f9fc8779139eacea3e013beecd7813e8a10c71a77e8a7d6b49026397e1ec29c37a841a3cf7a5d6b6ccd3aa9d22aedd",
          "sha256": "785302f2f7f6af8d7d57c074485cffdb47c724e2bffed69111bb7928745aebc5",
          "sha1": "532323e0664a5336e0a329f880ffc0b845a5d292",
          "md5": "b4c012fe4d4124f17c11965c5a105393"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2a4d-android-0.8.14-javadoc.jar",
          "size": 270925,
          "sha512": "6e0ddac52f467d3135bd0d829157e279ce75a74a10a0e0573abb1e028029d0651df935f7e010e899163abb8948879e5796df1380fed8d24a1e6d0baa219a45e0",
          "sha256": "f4d8ce50f188ab39457f9b4fd74ee0ac5aabb294625485d3f791a14fdaefab20",
          "sha1": "c88d3c8c5310d8cad4f6d0075bca57e62a81dc2a",
          "md5": "5f4fe72029b4a09ef49ecc5a766fa2a1"
        }
      ]
    }
  ]
}
