{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2901-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2901-android-0.4.4.aar",
          "url": "ble-descriptor-u2901-android-0.4.4.aar",
          "size": 3082,
          "sha512": "e591127b83782d914cf829c7c000a85e486818512cfcc412543d57c5a1eca9edb2142871c97bb9324941dd08f510071f1c14d2cc62b7be84e05a3272d73fe1dc",
          "sha256": "4a0ef659cdd32fa70e5a0f7646cfa3bf863b0e8b9b49e23d846d6442930df370",
          "sha1": "9221e321b1f5373328b8694e05cb43138f53ea1c",
          "md5": "c0b0930031cdfb82a926462d479cf893"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2901-android-0.4.4.aar",
          "url": "ble-descriptor-u2901-android-0.4.4.aar",
          "size": 3082,
          "sha512": "e591127b83782d914cf829c7c000a85e486818512cfcc412543d57c5a1eca9edb2142871c97bb9324941dd08f510071f1c14d2cc62b7be84e05a3272d73fe1dc",
          "sha256": "4a0ef659cdd32fa70e5a0f7646cfa3bf863b0e8b9b49e23d846d6442930df370",
          "sha1": "9221e321b1f5373328b8694e05cb43138f53ea1c",
          "md5": "c0b0930031cdfb82a926462d479cf893"
        }
      ]
    }
  ]
}
