{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acc",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.7.jar",
          "url": "ble-characteristic-u2acc-0.8.7.jar",
          "size": 4687,
          "sha512": "dc231e348ac650c60839761a68f1c478b3d01ab949d7669825240941d16b3905ed3843bf5ac986806a7009f95d0a511d30bc6809988aac0bae508c7c54b7bdd1",
          "sha256": "9758a32f1b3d78f9a2885de8e32218d52f8dc29847926772723f658ae8a409f4",
          "sha1": "6540669c15cdc66422a1dc4385735e06b2bfbe72",
          "md5": "4f839539130460d88eeb5277a8b2b9dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.7.jar",
          "url": "ble-characteristic-u2acc-0.8.7.jar",
          "size": 4687,
          "sha512": "dc231e348ac650c60839761a68f1c478b3d01ab949d7669825240941d16b3905ed3843bf5ac986806a7009f95d0a511d30bc6809988aac0bae508c7c54b7bdd1",
          "sha256": "9758a32f1b3d78f9a2885de8e32218d52f8dc29847926772723f658ae8a409f4",
          "sha1": "6540669c15cdc66422a1dc4385735e06b2bfbe72",
          "md5": "4f839539130460d88eeb5277a8b2b9dd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2acc-0.8.7-javadoc.jar",
          "size": 124526,
          "sha512": "aaaa5b2fb12529a7762dc983d10cb8087c5e2d554b5f729103501f8e7d7325777acb5945b5732a6368e4a4bf244015309cc8e4be7f13ffe34c4c5253f4c2519b",
          "sha256": "b665566660c9c3b7776ec64f37c44cece4abd074ee65e2f63c72e23ab7bfc4ad",
          "sha1": "99a3fb6975acb88f740c49ef0099029815695a52",
          "md5": "15b392f944351ae2cd5d5831c09d1e8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2acc-0.8.7-sources.jar",
          "url": "ble-characteristic-u2acc-0.8.7-sources.jar",
          "size": 5470,
          "sha512": "5b5cc7792b18a11972ef806bc8bfbfe1dcf3b82a7f152496ba34400adc28b451f8885718a7e99cd85f85e5ec7f85e60afb8f7226d859fd8140585b4bea86fc4e",
          "sha256": "29288078c6eed68e000ff638fb4eccb5c0124f176700e2402fbe706bcc8a9bea",
          "sha1": "6826c4b1ac8423339c69414a0d1a1c5686f5fe38",
          "md5": "24c8673871fbe2ede83741c90b1ad838"
        }
      ]
    }
  ]
}
