{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a76",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a76-0.8.5.jar",
          "url": "ble-characteristic-u2a76-0.8.5.jar",
          "size": 1705,
          "sha512": "b3d85d560e7f38ef11cd71356e09b76e6d527272a835645a681d30c36515015aed927ad2939aa38160f260458140b56963523cc2470d8268b4b893decb08d9c9",
          "sha256": "e2c3d8f22120676e7248610e4f4737f5ccb11c8e8d8b22a80cf7c29f1cab8ffb",
          "sha1": "8791d975cba7079fa71d08b5098818d589bb374b",
          "md5": "23a109abea1034056bddf350a6698928"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a76-0.8.5.jar",
          "url": "ble-characteristic-u2a76-0.8.5.jar",
          "size": 1705,
          "sha512": "b3d85d560e7f38ef11cd71356e09b76e6d527272a835645a681d30c36515015aed927ad2939aa38160f260458140b56963523cc2470d8268b4b893decb08d9c9",
          "sha256": "e2c3d8f22120676e7248610e4f4737f5ccb11c8e8d8b22a80cf7c29f1cab8ffb",
          "sha1": "8791d975cba7079fa71d08b5098818d589bb374b",
          "md5": "23a109abea1034056bddf350a6698928"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a76-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a76-0.8.5-javadoc.jar",
          "size": 107282,
          "sha512": "00c189459ff7b3e83f780720be5edd8ad01ab5854fb1f56d9673a57a4e7e9331715c2934be37a2e29c3af6454d56fef74e79d3b972c40373ebfe903b9e91a14c",
          "sha256": "fc0d06829b9cfa8ace4aab4f7a308b5c051229cbe304014031f45dd541230df2",
          "sha1": "c775a97e0e73dd834f5c9aac93a86b60b9da4a67",
          "md5": "2de77c8578368f243b6951e43c5f5d56"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a76-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a76-0.8.5-sources.jar",
          "size": 1562,
          "sha512": "d8d1d856e699656588fe22f1c00ff9b5c136a61ab5d99c6fd53febfb58756beaede5821a9399aebd4b46400ec5623d20b689b4288c6d51e5742199959ba8ad53",
          "sha256": "b201cdf18891ea15fbc2f60d77844af78591968bf7c0bf477070e49208e76327",
          "sha1": "1f9b4e2c07ecda6a908970ecb22378f26adc8088",
          "md5": "05a16d3802f63879e03bbd70296e5b85"
        }
      ]
    }
  ]
}
