{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0f-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0f",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-android-0.4.1.aar",
          "url": "ble-characteristic-u2b0f-android-0.4.1.aar",
          "size": 3083,
          "sha512": "5a6455e987620edb0592f4e70bf1acb5d3ea8301cb945819ea9c23251ea03816fc28fc80b89d0577e7112f142e3b945ab7d5d972f7c7165a3f74c96a4de0b36e",
          "sha256": "5fec715a25bc2aa926eed1e85e9c1f49a07e55e0f12a69f7e78b7ebe071012f3",
          "sha1": "b299eca45ecf9528d2b2d82d55e2818122cca6f0",
          "md5": "b80326b64acc8b67635c9c326e91a846"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0f",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-android-0.4.1.aar",
          "url": "ble-characteristic-u2b0f-android-0.4.1.aar",
          "size": 3083,
          "sha512": "5a6455e987620edb0592f4e70bf1acb5d3ea8301cb945819ea9c23251ea03816fc28fc80b89d0577e7112f142e3b945ab7d5d972f7c7165a3f74c96a4de0b36e",
          "sha256": "5fec715a25bc2aa926eed1e85e9c1f49a07e55e0f12a69f7e78b7ebe071012f3",
          "sha1": "b299eca45ecf9528d2b2d82d55e2818122cca6f0",
          "md5": "b80326b64acc8b67635c9c326e91a846"
        }
      ]
    }
  ]
}
