{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2907",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2907-0.2.6.jar",
          "url": "ble-descriptor-u2907-0.2.6.jar",
          "size": 1999,
          "sha512": "b88b6c9282a5b98558911c5c8ea3de3eece57cc392d329eab75a6de2ddfa979466dc782a345486804c12e6a16f879693ff1aa952a915d08823ae2e42b804410e",
          "sha256": "7f69badd4ba93b7a696f6f03458b73e6c67fffab83e35394647ff88f3e6344a5",
          "sha1": "dc0d9bc58cfcd1a478ba67cd06194d240541c172",
          "md5": "da38879a5467c92dbe41aba9e5218705"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2907-0.2.6.jar",
          "url": "ble-descriptor-u2907-0.2.6.jar",
          "size": 1999,
          "sha512": "b88b6c9282a5b98558911c5c8ea3de3eece57cc392d329eab75a6de2ddfa979466dc782a345486804c12e6a16f879693ff1aa952a915d08823ae2e42b804410e",
          "sha256": "7f69badd4ba93b7a696f6f03458b73e6c67fffab83e35394647ff88f3e6344a5",
          "sha1": "dc0d9bc58cfcd1a478ba67cd06194d240541c172",
          "md5": "da38879a5467c92dbe41aba9e5218705"
        }
      ]
    }
  ]
}
