{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a89-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.2.2.aar",
          "url": "ble-characteristic-u2a89-android-0.2.2.aar",
          "size": 2967,
          "sha512": "9a099ea8939bf19f50b2da2df380cb9c091b709e55a88b4a46214ed6bedc7c0cb9cd799b5c87935a93c6baa066c37eb8ded097edc518076a44aa0e84ba6f9e69",
          "sha256": "ece40c72cee303fb57acd12f540312037394c315be58dbe2e31f01733b8c18e2",
          "sha1": "183ea6f8da9138c591294224c435eaa36f9f80f7",
          "md5": "26498e44cbf0b671810b8367d20db0d9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a89",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-android-0.2.2.aar",
          "url": "ble-characteristic-u2a89-android-0.2.2.aar",
          "size": 2967,
          "sha512": "9a099ea8939bf19f50b2da2df380cb9c091b709e55a88b4a46214ed6bedc7c0cb9cd799b5c87935a93c6baa066c37eb8ded097edc518076a44aa0e84ba6f9e69",
          "sha256": "ece40c72cee303fb57acd12f540312037394c315be58dbe2e31f01733b8c18e2",
          "sha1": "183ea6f8da9138c591294224c435eaa36f9f80f7",
          "md5": "26498e44cbf0b671810b8367d20db0d9"
        }
      ]
    }
  ]
}
