{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa2-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa2",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa2-android-0.8.12.aar",
          "url": "ble-characteristic-u2aa2-android-0.8.12.aar",
          "size": 3122,
          "sha512": "c644cc0204cfaca0a63cf8039bcb3e7252ccc6ba7fbccaef87c848abd0f4f9f359ee32ec52e674ab91b138be18792773c90bd788a112e9f6fdae232542460114",
          "sha256": "cb4a47730b5ded50bf727ad3f4b8a333ae2823acbaa40698894792623f2b01da",
          "sha1": "7d8c5515a6869f5db385dea43664ca67c566e826",
          "md5": "049e5269ae5e2c0adbc8e9da77c85514"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa2",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa2-android-0.8.12.aar",
          "url": "ble-characteristic-u2aa2-android-0.8.12.aar",
          "size": 3122,
          "sha512": "c644cc0204cfaca0a63cf8039bcb3e7252ccc6ba7fbccaef87c848abd0f4f9f359ee32ec52e674ab91b138be18792773c90bd788a112e9f6fdae232542460114",
          "sha256": "cb4a47730b5ded50bf727ad3f4b8a333ae2823acbaa40698894792623f2b01da",
          "sha1": "7d8c5515a6869f5db385dea43664ca67c566e826",
          "md5": "049e5269ae5e2c0adbc8e9da77c85514"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa2-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2aa2-android-0.8.12-sources.jar",
          "size": 2169,
          "sha512": "9cd06bca3c06b218b6c9b32b6565659a49d43acdc92314308c578f46d0267aa3c47d669a1bdab41345e1a8584de25ccfb9e003f36a2e7e0e709c8df701dedb35",
          "sha256": "5d7d86d48a5bff312d1e1f0d6a1ad5a38e0513155cac24476662e2a7755edb69",
          "sha1": "2d4724aa87dde0608d5be57d07624f07d20e9a94",
          "md5": "ad7b61b16e063042efeabe068d637015"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa2-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2aa2-android-0.8.12-javadoc.jar",
          "size": 271027,
          "sha512": "ca4a84a815ce9bfdc04d6f940f0575cbdd2b63146dd1785cc4a74579d9cc61e795dc83cdeb1142245f3b4a4607bdf849eb2ed7e0c10ff9198c4647b62c481b26",
          "sha256": "d0e19ca1e34e84a7aa6d432fc400ab858b1c5d0294917f71b00e1b030da8580f",
          "sha1": "06f6ac175a3dd79d3ac359d7ee6f67c4c0384bf2",
          "md5": "1d9727bd5eaf5c66422057d78e265213"
        }
      ]
    }
  ]
}
