{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-ess-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ess-android",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-ess-android-0.4.5.aar",
          "url": "ble-service-central-ess-android-0.4.5.aar",
          "size": 50433,
          "sha512": "629e3ad1a1a3235cb75d17ae645dacdbb9e0c3c03aef3493c1d922a3134436e082287a05910c731217aec5e27541d59a663bd2e893d86964d604f276cb5cffa4",
          "sha256": "15bea8488ecc372c860276288becec99a6fe54749fb2d82c31b99979928c0cfc",
          "sha1": "462ef28e7d1d8120ce84273800faeefa7376da5f",
          "md5": "7cd5d241ce6c897f9c2d66beb813533b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ess-android",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-ess-android-0.4.5.aar",
          "url": "ble-service-central-ess-android-0.4.5.aar",
          "size": 50433,
          "sha512": "629e3ad1a1a3235cb75d17ae645dacdbb9e0c3c03aef3493c1d922a3134436e082287a05910c731217aec5e27541d59a663bd2e893d86964d604f276cb5cffa4",
          "sha256": "15bea8488ecc372c860276288becec99a6fe54749fb2d82c31b99979928c0cfc",
          "sha1": "462ef28e7d1d8120ce84273800faeefa7376da5f",
          "md5": "7cd5d241ce6c897f9c2d66beb813533b"
        }
      ]
    }
  ]
}
