{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2902-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.8.13.aar",
          "url": "ble-descriptor-u2902-android-0.8.13.aar",
          "size": 3127,
          "sha512": "d3f556e79bac2a548a862db3c2fff2ba406adbb4dd06d3f903873663b11b58c107b6c005668b739caf7c42a94161078ff5a49479829bd71d40f8b10b6882c3fd",
          "sha256": "413c59233fe6a17b344c8d2e857f4daf9f9e71e80018383f0508dd78a7bfe644",
          "sha1": "c53ca21f8f490aac0bfb30daec24fee0ebbc427e",
          "md5": "cf1f69f3801c202039a928fa590df726"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.8.13.aar",
          "url": "ble-descriptor-u2902-android-0.8.13.aar",
          "size": 3127,
          "sha512": "d3f556e79bac2a548a862db3c2fff2ba406adbb4dd06d3f903873663b11b58c107b6c005668b739caf7c42a94161078ff5a49479829bd71d40f8b10b6882c3fd",
          "sha256": "413c59233fe6a17b344c8d2e857f4daf9f9e71e80018383f0508dd78a7bfe644",
          "sha1": "c53ca21f8f490aac0bfb30daec24fee0ebbc427e",
          "md5": "cf1f69f3801c202039a928fa590df726"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.8.13-sources.jar",
          "url": "ble-descriptor-u2902-android-0.8.13-sources.jar",
          "size": 2179,
          "sha512": "f83a55b0129472cac469d272e88d19373b31b3f9b324d151749f42a2f8697889658f501f2f21a47ffcc2f8a1301411a6416ccbb5f36e10e385fd1084619e5f45",
          "sha256": "5582da7dfdca3b4861451045c31d2438c3d31053a969ac74dfb2fe3965a935f7",
          "sha1": "9fa3e4a83997e6c21c51b6327c171b679802029d",
          "md5": "23a06b0be277313cec4e82401d292835"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.8.13-javadoc.jar",
          "url": "ble-descriptor-u2902-android-0.8.13-javadoc.jar",
          "size": 272908,
          "sha512": "c1b388bcd904f26a7cf941638db2a5ef22f8c07b716fc0f3033b6287f6d0823f564e5409d8f4e9927f8390b4f548f061dbc05d1b4d8470918a9f716f87ccf871",
          "sha256": "14d580339fe5b8307f2e1181568e0f74d404fd94b3b774428a943b9cd3ebd03c",
          "sha1": "da45c76085aaa4f09f3cfb5eee8b8efa872e7b67",
          "md5": "91efcafeee2c8fbcdeda68ce8e562d6d"
        }
      ]
    }
  ]
}
