{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b00-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b00",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b00-android-0.8.12.aar",
          "url": "ble-characteristic-u2b00-android-0.8.12.aar",
          "size": 3224,
          "sha512": "8a8aa5ecadc505f1b07bec7afa7e1f53f0a3db87c9e429ff2b0fdc6a6bd382b780526d7881ffacf4b9ad204ee6584de1354b234447e7fdcfbb1352b7e701e707",
          "sha256": "3fbe1effa170a6d704d41530a0932564a5a6d8525607c35a30041691e00b4a42",
          "sha1": "61cb31efc6c3d4ae666b638f6946927b4c3a6301",
          "md5": "94bf01a5adca3a15effae52c0324df08"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b00",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b00-android-0.8.12.aar",
          "url": "ble-characteristic-u2b00-android-0.8.12.aar",
          "size": 3224,
          "sha512": "8a8aa5ecadc505f1b07bec7afa7e1f53f0a3db87c9e429ff2b0fdc6a6bd382b780526d7881ffacf4b9ad204ee6584de1354b234447e7fdcfbb1352b7e701e707",
          "sha256": "3fbe1effa170a6d704d41530a0932564a5a6d8525607c35a30041691e00b4a42",
          "sha1": "61cb31efc6c3d4ae666b638f6946927b4c3a6301",
          "md5": "94bf01a5adca3a15effae52c0324df08"
        }
      ]
    }
  ]
}
