{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2d",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.5.jar",
          "url": "ble-characteristic-u2b2d-0.8.5.jar",
          "size": 1521,
          "sha512": "75a78ccc01b0ec5c79f688e1ec4c4703d86611b142ef61a928689fae2ec0929059cbe7fd814fc1ec2f0ea8ac636915712c5fde76b10b315ca74fabf0464ffee6",
          "sha256": "d738dde366be1548210adcd95aca58ee87d5971f5f11c1b92b06d6e15f47cbb6",
          "sha1": "d0ed855514e0459adeed131b78b6bc87e0eb760d",
          "md5": "2802010ddf01381ff2d50d8e5e6a39bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.5.jar",
          "url": "ble-characteristic-u2b2d-0.8.5.jar",
          "size": 1521,
          "sha512": "75a78ccc01b0ec5c79f688e1ec4c4703d86611b142ef61a928689fae2ec0929059cbe7fd814fc1ec2f0ea8ac636915712c5fde76b10b315ca74fabf0464ffee6",
          "sha256": "d738dde366be1548210adcd95aca58ee87d5971f5f11c1b92b06d6e15f47cbb6",
          "sha1": "d0ed855514e0459adeed131b78b6bc87e0eb760d",
          "md5": "2802010ddf01381ff2d50d8e5e6a39bf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b2d-0.8.5-javadoc.jar",
          "size": 107218,
          "sha512": "7c6948623d743b1890a7157ff4c561552c45aa8f6bc7b8e32630e7198de2dcfc4a5057f550c9f7cf28699ba48b7882c532c8efa943cbbc549dbf0669122bf8e8",
          "sha256": "6883f00dcb091e23cc2991670f5099c3c4c20ddbeaff361d74bd51aac3630810",
          "sha1": "ff1ed0cfd4b5d3fdca8e032fda02f6661eb0e150",
          "md5": "59c33599a4952a97d9bcd2dbecfa6ef5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b2d-0.8.5-sources.jar",
          "size": 1473,
          "sha512": "30e816e55a491b536917b10733763446d6abc168e2782f3aa5997853d03b19a99d2b5b111a643bbda330765147b7cfdb4177fa41edff832223c7a37359e67c30",
          "sha256": "b12a5725ed8bc3f5756c4716c37576a020f2a63bd2f7f667d3d76d4aa9587507",
          "sha1": "c5df3599ba734170b1ac3bafeb9ee2bc7980f853",
          "md5": "2b843dd6a4b93905d7304d89d855a4d3"
        }
      ]
    }
  ]
}
