{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a11-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a11",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a11-android-0.8.12.aar",
          "url": "ble-characteristic-u2a11-android-0.8.12.aar",
          "size": 3266,
          "sha512": "72ff4c2e04cc36491f9809422e1602c8066caa8b49c37b0bfc96e480f88f0f7fb7d6b54b3e7866692caa5314cdc532707598073365d945816a7f82391f9bbbaa",
          "sha256": "752df9fa0b3ed6b718f63d9ea7e15dd13693bdf8cd6cb1abf08380f38656b85b",
          "sha1": "770185d011b0dd9d813ca91e0b2cd41374ce18a3",
          "md5": "d575a12bb207f0e325bab1c0cd2db84c"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a11",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a11-android-0.8.12.aar",
          "url": "ble-characteristic-u2a11-android-0.8.12.aar",
          "size": 3266,
          "sha512": "72ff4c2e04cc36491f9809422e1602c8066caa8b49c37b0bfc96e480f88f0f7fb7d6b54b3e7866692caa5314cdc532707598073365d945816a7f82391f9bbbaa",
          "sha256": "752df9fa0b3ed6b718f63d9ea7e15dd13693bdf8cd6cb1abf08380f38656b85b",
          "sha1": "770185d011b0dd9d813ca91e0b2cd41374ce18a3",
          "md5": "d575a12bb207f0e325bab1c0cd2db84c"
        }
      ]
    }
  ]
}
