{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae1-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae1",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-android-0.8.6.aar",
          "url": "ble-characteristic-u2ae1-android-0.8.6.aar",
          "size": 3098,
          "sha512": "9e7b7df0f9e5e003d862953ed0f57f62d9ecbe2e27a27aec48110f882b4697155855b73f646338d158b1d76f636f85800649f99bfdf94fe221586ccb8c6229cb",
          "sha256": "2a28b1eb7181f33e44578765b6dd5c6cb743001fc086988783a6114a16b57e6c",
          "sha1": "9950e7fab4edc1b08f74fbb6f7524f4a01db708d",
          "md5": "687bb32e1e619d3cf563db2016377cf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae1",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae1-android-0.8.6.aar",
          "url": "ble-characteristic-u2ae1-android-0.8.6.aar",
          "size": 3098,
          "sha512": "9e7b7df0f9e5e003d862953ed0f57f62d9ecbe2e27a27aec48110f882b4697155855b73f646338d158b1d76f636f85800649f99bfdf94fe221586ccb8c6229cb",
          "sha256": "2a28b1eb7181f33e44578765b6dd5c6cb743001fc086988783a6114a16b57e6c",
          "sha1": "9950e7fab4edc1b08f74fbb6f7524f4a01db708d",
          "md5": "687bb32e1e619d3cf563db2016377cf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae1-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ae1-android-0.8.6-sources.jar",
          "size": 2191,
          "sha512": "2e22e20654f0fbbd3b1a0c2e8218728518585f970e14d408243e8e22d820d08263f5537d74a50ce68be8bf8115924625caea4a874331434b96b2ce45b9797e3d",
          "sha256": "df2a4b050789f5d777b45faeeed703ee057e26a2c1f73a498b55488549123b1a",
          "sha1": "1338e7d022afc8f26153a7c5985a961a2f012d97",
          "md5": "1eed4c8ced70315532e825778fc43c21"
        }
      ]
    }
  ]
}
