{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a88-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a88",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a88-android-0.2.8.aar",
          "url": "ble-characteristic-u2a88-android-0.2.8.aar",
          "size": 3142,
          "sha512": "3a1124a4820579286c1d7f09da4f006c89b5d18ae8de06d4e271922175fed165260d70502b3d66c35c7613e57575359b56e3b91d4dd25b6aa79a99ca78d47eea",
          "sha256": "6b55bfe413bfbaef419fce5d7398829fdf6f13a511570762e57633c9eec51db0",
          "sha1": "e007365acb5d97cbfd661019d73b37445f6910bc",
          "md5": "b69031bf6744a9c6cafb9645c766709e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a88",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a88-android-0.2.8.aar",
          "url": "ble-characteristic-u2a88-android-0.2.8.aar",
          "size": 3142,
          "sha512": "3a1124a4820579286c1d7f09da4f006c89b5d18ae8de06d4e271922175fed165260d70502b3d66c35c7613e57575359b56e3b91d4dd25b6aa79a99ca78d47eea",
          "sha256": "6b55bfe413bfbaef419fce5d7398829fdf6f13a511570762e57633c9eec51db0",
          "sha1": "e007365acb5d97cbfd661019d73b37445f6910bc",
          "md5": "b69031bf6744a9c6cafb9645c766709e"
        }
      ]
    }
  ]
}
