{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5d-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.2.5.aar",
          "url": "ble-characteristic-u2a5d-android-0.2.5.aar",
          "size": 3080,
          "sha512": "99961b496963fab83fb7f8284d2aaba89fecda29046c8e931d474bd895a5906e859f4d6c376f7d2b475fb0ad79ce9960b1d5ad437b64ef8a927e173143de0d39",
          "sha256": "5d8d5772cec96a921c4cb6261e309974f4982180ed36d895492ba3e522b63edc",
          "sha1": "412197a470b5f4a3e71996ffb42ecbd7d235fdf5",
          "md5": "2c2e4656ba237f8e9c0975cab46838ab"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.2.5.aar",
          "url": "ble-characteristic-u2a5d-android-0.2.5.aar",
          "size": 3080,
          "sha512": "99961b496963fab83fb7f8284d2aaba89fecda29046c8e931d474bd895a5906e859f4d6c376f7d2b475fb0ad79ce9960b1d5ad437b64ef8a927e173143de0d39",
          "sha256": "5d8d5772cec96a921c4cb6261e309974f4982180ed36d895492ba3e522b63edc",
          "sha1": "412197a470b5f4a3e71996ffb42ecbd7d235fdf5",
          "md5": "2c2e4656ba237f8e9c0975cab46838ab"
        }
      ]
    }
  ]
}
