{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc0",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc0-0.8.7.jar",
          "url": "ble-characteristic-u2bc0-0.8.7.jar",
          "size": 1458,
          "sha512": "9419f79efbcbf6082a0786866066632eee9bc3acd185782a1e69f8a369fdd9d4c1c6a96c737020a98a70fb66a53cff032f5f3dbb6b636437ebdc0080c7343de7",
          "sha256": "32550270027951594d397b95c8ed55ab32e777435a90b75aa0a52ce0244a5d6d",
          "sha1": "25360fc7a2350fd6ce643e56059a82f9f55411ab",
          "md5": "6c9414eb4914e141f0db0cde2cb7ae3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc0-0.8.7.jar",
          "url": "ble-characteristic-u2bc0-0.8.7.jar",
          "size": 1458,
          "sha512": "9419f79efbcbf6082a0786866066632eee9bc3acd185782a1e69f8a369fdd9d4c1c6a96c737020a98a70fb66a53cff032f5f3dbb6b636437ebdc0080c7343de7",
          "sha256": "32550270027951594d397b95c8ed55ab32e777435a90b75aa0a52ce0244a5d6d",
          "sha1": "25360fc7a2350fd6ce643e56059a82f9f55411ab",
          "md5": "6c9414eb4914e141f0db0cde2cb7ae3c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc0-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bc0-0.8.7-javadoc.jar",
          "size": 107164,
          "sha512": "432e8963c697c05974f0c4e6da9ced8edbfc5b901218cb3f72a9ea5e56c12e1c5350419a689914da08d32c9db20a230bc22c2b35d53f5b5433155c03ab7fa621",
          "sha256": "ac5739c8bdd09111578c1850d95cfba0823ca5ec766e601e09d9767563c728de",
          "sha1": "e9e48b5a666bf17ef89680aeb452f23e0ca19026",
          "md5": "5fd5f58cdd41a9f15c3f54d58aa2ee79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc0-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bc0-0.8.7-sources.jar",
          "size": 1450,
          "sha512": "bcbf957c814cdf792a7d59e126f2e0c9ae68f521f15ff28f5173ae9cc98f26c45af21eb717bab67626e5acecc9fb6c2811b48268cbabeb94834dfee1e60b50af",
          "sha256": "441382838bdc20a6b08d92ad4b0cfbf6e32771c4d83db070b2a8b00d8e2d7481",
          "sha1": "9765f4fe556732bf71f4e59ce0b220fcd24c4d0f",
          "md5": "a0f5fc246e500614d87aa4378e19bfa9"
        }
      ]
    }
  ]
}
