{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b77-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b77",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b77-android-0.4.1.aar",
          "url": "ble-characteristic-u2b77-android-0.4.1.aar",
          "size": 3064,
          "sha512": "46c0da392945fb257cbc2389c4b3d02905f037a4e6516447052d16f3c09a55f25a25247c7704f500e8e2f4265c915af439f156942979a58cc8f37bfaa72dc83d",
          "sha256": "56370d83c5e1f973722e3b9d2d06832532dcf7a3ac9d0163a166e26f19d8fc06",
          "sha1": "00a1eb2c317189163d8f5899b6b9afdae7b05feb",
          "md5": "218001fb72a907d9eea94b8ad4895377"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b77",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b77-android-0.4.1.aar",
          "url": "ble-characteristic-u2b77-android-0.4.1.aar",
          "size": 3064,
          "sha512": "46c0da392945fb257cbc2389c4b3d02905f037a4e6516447052d16f3c09a55f25a25247c7704f500e8e2f4265c915af439f156942979a58cc8f37bfaa72dc83d",
          "sha256": "56370d83c5e1f973722e3b9d2d06832532dcf7a3ac9d0163a166e26f19d8fc06",
          "sha1": "00a1eb2c317189163d8f5899b6b9afdae7b05feb",
          "md5": "218001fb72a907d9eea94b8ad4895377"
        }
      ]
    }
  ]
}
