{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9f-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "url": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "size": 3002,
          "sha512": "486cf7356e33e559ca15bf7ef9dd1c1f1936109819a798f1c54f056f6bc122899f21bd1d1612c889282eb2494f0d4438d7eb0553172851dda05b838f4253255b",
          "sha256": "fdf23a68830c0f3917890ae6b58bd0f60b58a1857a0d1ef17bbe5a953aab8fa1",
          "sha1": "0393afa6b86870fb0dd221d12c8d81dd8b1cb275",
          "md5": "9245ef2aa429be07ab8ce9cc59f942dd"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "url": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "size": 3002,
          "sha512": "486cf7356e33e559ca15bf7ef9dd1c1f1936109819a798f1c54f056f6bc122899f21bd1d1612c889282eb2494f0d4438d7eb0553172851dda05b838f4253255b",
          "sha256": "fdf23a68830c0f3917890ae6b58bd0f60b58a1857a0d1ef17bbe5a953aab8fa1",
          "sha1": "0393afa6b86870fb0dd221d12c8d81dd8b1cb275",
          "md5": "9245ef2aa429be07ab8ce9cc59f942dd"
        }
      ]
    }
  ]
}
