{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9f-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "url": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "size": 3002,
          "sha512": "26beb8335a35e64a1c5250643c1f54f0ce37c2d782732cab6e33801ad8cef07b8113371fbd938e87d268cf14beda8fe9e11588447718e4183314d1896c1e28f2",
          "sha256": "ced06b976a934b1709fb0f0ecae090e3b64aab96d0a787cd6bff3d6287ac2a72",
          "sha1": "67559bd9f5351cf812efff75c6a2570cf17a7cb5",
          "md5": "1b990d4cca9c567a5d669420bdbbbdb7"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "url": "ble-characteristic-u2a9f-android-0.2.2.aar",
          "size": 3002,
          "sha512": "26beb8335a35e64a1c5250643c1f54f0ce37c2d782732cab6e33801ad8cef07b8113371fbd938e87d268cf14beda8fe9e11588447718e4183314d1896c1e28f2",
          "sha256": "ced06b976a934b1709fb0f0ecae090e3b64aab96d0a787cd6bff3d6287ac2a72",
          "sha1": "67559bd9f5351cf812efff75c6a2570cf17a7cb5",
          "md5": "1b990d4cca9c567a5d669420bdbbbdb7"
        }
      ]
    }
  ]
}
