{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd5",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.6.1.jar",
          "url": "ble-characteristic-u2bd5-0.6.1.jar",
          "size": 1503,
          "sha512": "618ff13a4b02fb38bc21e2f54c349b9eebb933298f8a1dc50ec7373c4bd39cdbbbd644759a5019b2d0e7d0b595c5ac123102f90c201661432b9d1e7487c5630b",
          "sha256": "dd22fed2540398758dbbd8ad295b636124873b04ed18c494cdaa8fbc60004397",
          "sha1": "be663c6e287255f2494dc4352009e2d2d4b305d8",
          "md5": "3ef550cc70a15c806428ee162a2ae463"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.6.1.jar",
          "url": "ble-characteristic-u2bd5-0.6.1.jar",
          "size": 1503,
          "sha512": "618ff13a4b02fb38bc21e2f54c349b9eebb933298f8a1dc50ec7373c4bd39cdbbbd644759a5019b2d0e7d0b595c5ac123102f90c201661432b9d1e7487c5630b",
          "sha256": "dd22fed2540398758dbbd8ad295b636124873b04ed18c494cdaa8fbc60004397",
          "sha1": "be663c6e287255f2494dc4352009e2d2d4b305d8",
          "md5": "3ef550cc70a15c806428ee162a2ae463"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.6.1-javadoc.jar",
          "url": "ble-characteristic-u2bd5-0.6.1-javadoc.jar",
          "size": 110045,
          "sha512": "751053593ee9945e334d547979057fc1ac87e71603b74a3d7db0a0063cd03a1464ad08cf2d35535edada65859bb10c62281cd04ef453658139945866f7ca09c8",
          "sha256": "fa79cb4260601c9e52060518e3e7dfe8e4150a2e94ad9f9ef0981aafd1f046c6",
          "sha1": "a8cddf66f8150eca6d8e69f402511cd51f26d33b",
          "md5": "8d46bd5c0b86f81f6540d65e36a18a09"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.6.1-sources.jar",
          "url": "ble-characteristic-u2bd5-0.6.1-sources.jar",
          "size": 1487,
          "sha512": "ae3fda8b8872dc02f393ffcef7ed8af695a8c7845f1a413c2f100ab4b681905225161e235ba3c6cd607e8f7fecfcabdefac69335e53d8bd473ba4b2508e05aa7",
          "sha256": "17e7bf247ab4f5c5ed8d7f27b735a69d6b94e0fec37a83eab152c29c929c575a",
          "sha1": "0ee2238b3cb8093d95af359d127a699bc0f88a13",
          "md5": "379681dc8eb099f0bfa8e04d32e252c6"
        }
      ]
    }
  ]
}
