{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a12",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a12-0.8.5.jar",
          "url": "ble-characteristic-u2a12-0.8.5.jar",
          "size": 1959,
          "sha512": "9f7bda8bb12f2fc21d0a7956eb147cafbef7cdebfea442726acc4222585d38e58b2fa996fdc62a74a1d49499efb04f464969287f990daf4ab419ada141514bf9",
          "sha256": "9a548a6c0d0a499a66ea08b6a4e231891e392960bc090896910ccea458941025",
          "sha1": "fadbdd431ce5097e8721ae8554ed2037bd570427",
          "md5": "5531cae312bc7ed213c79bf588bd916a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a12-0.8.5.jar",
          "url": "ble-characteristic-u2a12-0.8.5.jar",
          "size": 1959,
          "sha512": "9f7bda8bb12f2fc21d0a7956eb147cafbef7cdebfea442726acc4222585d38e58b2fa996fdc62a74a1d49499efb04f464969287f990daf4ab419ada141514bf9",
          "sha256": "9a548a6c0d0a499a66ea08b6a4e231891e392960bc090896910ccea458941025",
          "sha1": "fadbdd431ce5097e8721ae8554ed2037bd570427",
          "md5": "5531cae312bc7ed213c79bf588bd916a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a12-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a12-0.8.5-javadoc.jar",
          "size": 109835,
          "sha512": "641bdf04d871faa0ea1f21ede151c61aef8194549b1f9f03b8c18f90ee2897641f7e294445892ab1878eca6025a5b5173b57ac60950d9caa294d21b04c27f12e",
          "sha256": "43400d9820b72ed2f29c56a650b5fbe44183b9651fa6af3810bd4ef234863de0",
          "sha1": "109fade2a6d8d0a5d1ce2fca3486c61ebd5a1525",
          "md5": "109665e8a0f057843aea3ff10fd52bf3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a12-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a12-0.8.5-sources.jar",
          "size": 1806,
          "sha512": "32ff8e3b2192b1e9f171b7c8f6c1ad73028852b844d8b22da1f2510e195fcb768a96200735645213fd86948671843e204e736ee3d654c2945aed876a40eb4601",
          "sha256": "f0b4d315ba744a5ec00118358fae900758908917a01c1a3fd6bf3b20a32946b0",
          "sha1": "1b03e53fe9d43248a4cb7767a6d53b92a5f9919a",
          "md5": "bf5f75a05bd2c9b7a03837475233b22b"
        }
      ]
    }
  ]
}
