{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa7-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa7",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa7-android-0.4.2.aar",
          "url": "ble-characteristic-u2aa7-android-0.4.2.aar",
          "size": 3061,
          "sha512": "30aba13d927dfdbff4747f4c580b29a48713ed2a27320c29340491a21b319fb69f356ad21aab6d96d99bb40154c04d6d1d00082f9f96c81bf850f91b362470be",
          "sha256": "73e5ec991d155a66a566bb957583fc9b360828fff3c483421ec1046200203a3d",
          "sha1": "214667b5e37e389bfa0171f2bce9e83c9e624210",
          "md5": "95b1655f6c5b012cc334605ba9c1264a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa7",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa7-android-0.4.2.aar",
          "url": "ble-characteristic-u2aa7-android-0.4.2.aar",
          "size": 3061,
          "sha512": "30aba13d927dfdbff4747f4c580b29a48713ed2a27320c29340491a21b319fb69f356ad21aab6d96d99bb40154c04d6d1d00082f9f96c81bf850f91b362470be",
          "sha256": "73e5ec991d155a66a566bb957583fc9b360828fff3c483421ec1046200203a3d",
          "sha1": "214667b5e37e389bfa0171f2bce9e83c9e624210",
          "md5": "95b1655f6c5b012cc334605ba9c1264a"
        }
      ]
    }
  ]
}
