{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab1-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab1",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-android-0.4.3.aar",
          "url": "ble-characteristic-u2ab1-android-0.4.3.aar",
          "size": 3123,
          "sha512": "047697e6a5677f1fe8c64335b0c8bc7bb1a1ee26e1dbaa474bae7186ffa2382bfb64b258704eb7d1aa86a4938d5846278470dee5a0697cddd94cf465fe361ad2",
          "sha256": "25d4e4c8fe525160a2c11d32a8fff5284e4966b7e93135263d7be7fb47a3c9bc",
          "sha1": "aa9e061ba5fb97585bc162857a628f11b2621676",
          "md5": "66ed3bc3ace1978c5180639be5ea9038"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab1",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-android-0.4.3.aar",
          "url": "ble-characteristic-u2ab1-android-0.4.3.aar",
          "size": 3123,
          "sha512": "047697e6a5677f1fe8c64335b0c8bc7bb1a1ee26e1dbaa474bae7186ffa2382bfb64b258704eb7d1aa86a4938d5846278470dee5a0697cddd94cf465fe361ad2",
          "sha256": "25d4e4c8fe525160a2c11d32a8fff5284e4966b7e93135263d7be7fb47a3c9bc",
          "sha1": "aa9e061ba5fb97585bc162857a628f11b2621676",
          "md5": "66ed3bc3ace1978c5180639be5ea9038"
        }
      ]
    }
  ]
}
