{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad3",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "bo2m2bzyvfgbjfmoy4levvs3tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad3-0.2.1.jar",
          "url": "ble-characteristic-u2ad3-0.2.1.jar",
          "size": 3057,
          "sha512": "62cbcea230f76f5301548046968ce04da25da76040db33a80d5b36aa50275f325c70bb4eb305d3a74dbc44990bc56c3b162fb3eca581d6c927145d69896f56f4",
          "sha256": "6a91b9cc687540af566500fa4d14b9f216b05650aa86ddfc1a1c563602cab8e8",
          "sha1": "46f3de114967d62798ac9e41932ae044f9f74d48",
          "md5": "d9cd62a2f5364a2dcd3a6173b4b613b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad3-0.2.1.jar",
          "url": "ble-characteristic-u2ad3-0.2.1.jar",
          "size": 3057,
          "sha512": "62cbcea230f76f5301548046968ce04da25da76040db33a80d5b36aa50275f325c70bb4eb305d3a74dbc44990bc56c3b162fb3eca581d6c927145d69896f56f4",
          "sha256": "6a91b9cc687540af566500fa4d14b9f216b05650aa86ddfc1a1c563602cab8e8",
          "sha1": "46f3de114967d62798ac9e41932ae044f9f74d48",
          "md5": "d9cd62a2f5364a2dcd3a6173b4b613b6"
        }
      ]
    }
  ]
}
