{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b23-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b23",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b23-android-0.4.1.aar",
          "url": "ble-characteristic-u2b23-android-0.4.1.aar",
          "size": 3042,
          "sha512": "1812296408246ebe6a702e6af3b511e8c3d6a0df3cd94fc99c2a941ed478570b05e16b16a7718f19b60514b4a8e880a6c934435f8052a67cd5206ba9c6207c12",
          "sha256": "7b88dec11ca8b6656954a72ab560e0f8a16e070ce02f69aeab7ac52ffc790d41",
          "sha1": "21e5b9fffcf974b8037d6770b27c555415b806e6",
          "md5": "f269459ce8e2bc606c301fd72cc46406"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b23",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b23-android-0.4.1.aar",
          "url": "ble-characteristic-u2b23-android-0.4.1.aar",
          "size": 3042,
          "sha512": "1812296408246ebe6a702e6af3b511e8c3d6a0df3cd94fc99c2a941ed478570b05e16b16a7718f19b60514b4a8e880a6c934435f8052a67cd5206ba9c6207c12",
          "sha256": "7b88dec11ca8b6656954a72ab560e0f8a16e070ce02f69aeab7ac52ffc790d41",
          "sha1": "21e5b9fffcf974b8037d6770b27c555415b806e6",
          "md5": "f269459ce8e2bc606c301fd72cc46406"
        }
      ]
    }
  ]
}
