{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a91-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6cu2oomv2fb67ivu2iebxgsxbm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a91-android-0.2.0.aar",
          "url": "ble-characteristic-u2a91-android-0.2.0.aar",
          "size": 2963,
          "sha512": "eaccf6db599a303dbc91af9ac330f7b7110ccd1ff909abb01c9708b596e5e7d2705707be90b93cdd612f6ce83250ff8b72d200b434eebad1cdc80af1fadc0c5f",
          "sha256": "36121d74c2e7b0466780a303c806fa644b6725a05c3c36ca7287b68779783a08",
          "sha1": "2d157a0e41721c112b5115c27baf5d7e5ab58c2c",
          "md5": "395c33d84edab5dec1e4cc609a47bcc4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a91-android-0.2.0.aar",
          "url": "ble-characteristic-u2a91-android-0.2.0.aar",
          "size": 2963,
          "sha512": "eaccf6db599a303dbc91af9ac330f7b7110ccd1ff909abb01c9708b596e5e7d2705707be90b93cdd612f6ce83250ff8b72d200b434eebad1cdc80af1fadc0c5f",
          "sha256": "36121d74c2e7b0466780a303c806fa644b6725a05c3c36ca7287b68779783a08",
          "sha1": "2d157a0e41721c112b5115c27baf5d7e5ab58c2c",
          "md5": "395c33d84edab5dec1e4cc609a47bcc4"
        }
      ]
    }
  ]
}
