{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a25-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.4.aar",
          "url": "ble-characteristic-u2a25-android-0.2.4.aar",
          "size": 3106,
          "sha512": "a28a8ce164cce773a93a47e189e1e3b65dc00c4fea6066420d914ab8e8291d2e7530799c6b2138b77e7684acbc350de65e299bb1afaf8abfb16b096734c82f3e",
          "sha256": "c432ac43c7180d176f3220144fdf7571782e24204df91279a22b9ac908c97fbb",
          "sha1": "1cb8514a9643db152b54a1b54a0cd8f67b00a015",
          "md5": "8592d005f31d8d2676fc5a24cce2b96a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.4.aar",
          "url": "ble-characteristic-u2a25-android-0.2.4.aar",
          "size": 3106,
          "sha512": "a28a8ce164cce773a93a47e189e1e3b65dc00c4fea6066420d914ab8e8291d2e7530799c6b2138b77e7684acbc350de65e299bb1afaf8abfb16b096734c82f3e",
          "sha256": "c432ac43c7180d176f3220144fdf7571782e24204df91279a22b9ac908c97fbb",
          "sha1": "1cb8514a9643db152b54a1b54a0cd8f67b00a015",
          "md5": "8592d005f31d8d2676fc5a24cce2b96a"
        }
      ]
    }
  ]
}
