{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bcs-central-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "g5qe3gxy7fadji6k656wemu774"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-central-android-0.1.0.aar",
          "url": "ble-service-bcs-central-android-0.1.0.aar",
          "size": 5047,
          "sha512": "9513941d9d2ee69f43ce8fc7b018409ff6feafce5ebb48eefd92ecdd706ab6b3bdde7dc016383126f6ff08785954eac6c647b3a1cb9323f87531ca0fd4c94bca",
          "sha256": "b8692501aa8dd2ee77edf34d3eeff4687039a073beb9b5390abd180415f28fa5",
          "sha1": "4dbf82216a17c404f196508b8618ddb43436d430",
          "md5": "2d1466a50239868d0892c9fac9e151b1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-central-android-0.1.0.aar",
          "url": "ble-service-bcs-central-android-0.1.0.aar",
          "size": 5047,
          "sha512": "9513941d9d2ee69f43ce8fc7b018409ff6feafce5ebb48eefd92ecdd706ab6b3bdde7dc016383126f6ff08785954eac6c647b3a1cb9323f87531ca0fd4c94bca",
          "sha256": "b8692501aa8dd2ee77edf34d3eeff4687039a073beb9b5390abd180415f28fa5",
          "sha1": "4dbf82216a17c404f196508b8618ddb43436d430",
          "md5": "2d1466a50239868d0892c9fac9e151b1"
        }
      ]
    }
  ]
}
