{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9d",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9d-0.8.9.jar",
          "url": "ble-characteristic-u2a9d-0.8.9.jar",
          "size": 3658,
          "sha512": "94799f82d11b7c37fa325a60f5d08b338a41f9a3c3b2bdd92cbf6600e882ac8a4b779e7393b64eef7d1fa40718f250d0e4aa6c2d4015b59c34d63367f2a533a0",
          "sha256": "a0e97d5a5806b785d1aca57fbd42f2e0596252f4e73cf3cef1eac313bbd7739d",
          "sha1": "fc434d6c21f54ec57c37e5c73f8a6778b1e54131",
          "md5": "76470d6dd4673252b54f3c43363f813c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9d-0.8.9.jar",
          "url": "ble-characteristic-u2a9d-0.8.9.jar",
          "size": 3658,
          "sha512": "94799f82d11b7c37fa325a60f5d08b338a41f9a3c3b2bdd92cbf6600e882ac8a4b779e7393b64eef7d1fa40718f250d0e4aa6c2d4015b59c34d63367f2a533a0",
          "sha256": "a0e97d5a5806b785d1aca57fbd42f2e0596252f4e73cf3cef1eac313bbd7739d",
          "sha1": "fc434d6c21f54ec57c37e5c73f8a6778b1e54131",
          "md5": "76470d6dd4673252b54f3c43363f813c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9d-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2a9d-0.8.9-javadoc.jar",
          "size": 113017,
          "sha512": "1968db0d1aa5a3dedf1a757ffee0563f04b3e0f0075eb688f54eb29833ab9aca5139e5bab80f5b67be230ca278650ade7d33d2d186223787c6bc3d982301555d",
          "sha256": "4b0d6ef24a6a48bcb0781d63d886c662052d84bad89117818f8c450528aa63ce",
          "sha1": "3d6d304b3004acfab90d36612875d7b7db5af1b9",
          "md5": "f5871c1abd0cb08db0b584254a57a4df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9d-0.8.9-sources.jar",
          "url": "ble-characteristic-u2a9d-0.8.9-sources.jar",
          "size": 3413,
          "sha512": "2a6d58fb292bc7f4eff083c8e0c3e8d9a966c6cb42d659d995fd253a53b162ab26b8489cb49a049c494e440279b429664d43158e2786b43cb3c906d3c7d1b743",
          "sha256": "49bc7c6cb889bd6a78b9c9f47f902942430f7f2e56a1214193fe8498b087a60d",
          "sha1": "33454e5f5e51dbdd95b4cc651c4b6a62dda95c74",
          "md5": "cd4a71d1a54b80004e96051b91e93da7"
        }
      ]
    }
  ]
}
