{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a48-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sipxf3vz2bcx5mgcg6vcjbnlti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.1.aar",
          "url": "ble-characteristic-u2a48-android-0.2.1.aar",
          "size": 3014,
          "sha512": "99762cce5d315492ae1cc842869fbcf540a02ab25be633dcdb1a6c7d057e0588fd51b3e5bc6f48a166fc460227c7596bd92351fafc71c34fd5c7eeffbc1bb148",
          "sha256": "6f9fe52fe9e687cca128e261d6715b728157a2bdce56ac6f6e316668fa55bc2d",
          "sha1": "c5d621b2be471852e1510b9198811d066b18fdc1",
          "md5": "9317eb92de03da73bf55581dabf56998"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.1.aar",
          "url": "ble-characteristic-u2a48-android-0.2.1.aar",
          "size": 3014,
          "sha512": "99762cce5d315492ae1cc842869fbcf540a02ab25be633dcdb1a6c7d057e0588fd51b3e5bc6f48a166fc460227c7596bd92351fafc71c34fd5c7eeffbc1bb148",
          "sha256": "6f9fe52fe9e687cca128e261d6715b728157a2bdce56ac6f6e316668fa55bc2d",
          "sha1": "c5d621b2be471852e1510b9198811d066b18fdc1",
          "md5": "9317eb92de03da73bf55581dabf56998"
        }
      ]
    }
  ]
}
