{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a24",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-0.8.6.jar",
          "url": "ble-characteristic-u2a24-0.8.6.jar",
          "size": 1584,
          "sha512": "d62173910a56e0dd7b4dde9c10c8dc783ace56a96bd72bbf7c82989327ff00e71f6d329e6b1cc8aaa7552ad296108c95f68d6a22bb0f406dc95446384f4f4657",
          "sha256": "152bca2a60b7309fa2833f2bcde08a512612e4d6b3e7be4acf79a3a25693070b",
          "sha1": "5ddbe188be92f3b3805bc5a0c8ec410e8ffc08c6",
          "md5": "1710d6197a3ff5e0f31bc5af761cffe3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-0.8.6.jar",
          "url": "ble-characteristic-u2a24-0.8.6.jar",
          "size": 1584,
          "sha512": "d62173910a56e0dd7b4dde9c10c8dc783ace56a96bd72bbf7c82989327ff00e71f6d329e6b1cc8aaa7552ad296108c95f68d6a22bb0f406dc95446384f4f4657",
          "sha256": "152bca2a60b7309fa2833f2bcde08a512612e4d6b3e7be4acf79a3a25693070b",
          "sha1": "5ddbe188be92f3b3805bc5a0c8ec410e8ffc08c6",
          "md5": "1710d6197a3ff5e0f31bc5af761cffe3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a24-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a24-0.8.6-javadoc.jar",
          "size": 107429,
          "sha512": "c07894b5a5fcfecbf8c4b4a4e65e7f83e3b8fedd15cdb7d8b5d96c8d17d07398aea80bd186a5768552e18f427ce64731a862044de42e13d739e2f9179516e4ac",
          "sha256": "72e022fae2e4dbec031575ad4ed4f8026a0140269337cfc89e9e777d04065133",
          "sha1": "5555bfe02785e4b257eee2279165bed479247805",
          "md5": "4e81c0ee6c2bfecee10f0ca8103ea29c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a24-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a24-0.8.6-sources.jar",
          "size": 1504,
          "sha512": "63236116920131157469d2d77921b87b2de4b04154f1e2245faabb38432d53323b4030ee5ca27100cbdfe85c644b0aad70b49f061b3065a0e6b70097d33ba0a5",
          "sha256": "400cd09b0a34ec823518897cb6bd7fc35252e983e140e84772daeae455285a1f",
          "sha1": "a37d57fc0a0e213a9c044ac24723647576cd987f",
          "md5": "22a0ccdf6a72c104affe1011301e546d"
        }
      ]
    }
  ]
}
