{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7e",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "zntzl6h5ifdqnivyseqzz436ba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.2.0.jar",
          "url": "ble-characteristic-u2a7e-0.2.0.jar",
          "size": 1759,
          "sha512": "611dcd6a06289d9b814cee0d6af98d9bcf17bb158f7e81a5e7719d64906db294f839b2ba0d60f9a39f6dc4f515e55ae4b3276943e0eaba1b341e1b0990638a66",
          "sha256": "c2038865cb4fd685175b12a33e05a73be8a4fdb5a8315e79cdd6686bea04a789",
          "sha1": "dc28536785a7f99e050d7dc5df4c437be1fdb641",
          "md5": "c71925c790540e92cd300d1dac8cd8e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-0.2.0.jar",
          "url": "ble-characteristic-u2a7e-0.2.0.jar",
          "size": 1759,
          "sha512": "611dcd6a06289d9b814cee0d6af98d9bcf17bb158f7e81a5e7719d64906db294f839b2ba0d60f9a39f6dc4f515e55ae4b3276943e0eaba1b341e1b0990638a66",
          "sha256": "c2038865cb4fd685175b12a33e05a73be8a4fdb5a8315e79cdd6686bea04a789",
          "sha1": "dc28536785a7f99e050d7dc5df4c437be1fdb641",
          "md5": "c71925c790540e92cd300d1dac8cd8e0"
        }
      ]
    }
  ]
}
