{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290c",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.6.jar",
          "url": "ble-descriptor-u290c-0.8.6.jar",
          "size": 3934,
          "sha512": "635bd4c7cf20e1143eb3a14f4b5d6ae170f89e3cca717481e3718f78e9771d48c39aa454e0f408c08ef3033e55e16a37340400a3e0d280f957d24ac3a05d65ab",
          "sha256": "7c6da503f98b0704c320dd86ada5180cc519d3335810e116caaf966a046a0226",
          "sha1": "07cbdd1769a848dfae8d405af22842054ad19666",
          "md5": "9dd1ce09c07172dcb33324e5b1b75a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.6.jar",
          "url": "ble-descriptor-u290c-0.8.6.jar",
          "size": 3934,
          "sha512": "635bd4c7cf20e1143eb3a14f4b5d6ae170f89e3cca717481e3718f78e9771d48c39aa454e0f408c08ef3033e55e16a37340400a3e0d280f957d24ac3a05d65ab",
          "sha256": "7c6da503f98b0704c320dd86ada5180cc519d3335810e116caaf966a046a0226",
          "sha1": "07cbdd1769a848dfae8d405af22842054ad19666",
          "md5": "9dd1ce09c07172dcb33324e5b1b75a0b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.6-javadoc.jar",
          "url": "ble-descriptor-u290c-0.8.6-javadoc.jar",
          "size": 118414,
          "sha512": "9cc2eea4264d88487781c526fcb4dc50a97028506dc0b6f1508437940141a95552f4099ee22893134ebdd5bbe2c0efc6d6de04ec5c48a3927f215d2d09f7864a",
          "sha256": "b270b9825e2b3382cc6d2c7f588ee9aabd7d9f7db6bd69ad43b817edb7f0f158",
          "sha1": "a3696838878e790fd34698a5dc057f35bb3d8681",
          "md5": "da46617738aebd8072fb0edada57366c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u290c-0.8.6-sources.jar",
          "url": "ble-descriptor-u290c-0.8.6-sources.jar",
          "size": 3947,
          "sha512": "51d79580918cf081747baffbf7c3de12ed5772114f088e284288b38bba2618c71f499aec38fd7aa3ebaaf62d0c030f09724369f2678fd7d1192b487fd65b5c01",
          "sha256": "faea8dfa9ff62d69cf7a7bb105c4667de6656a5585b1c8c7263047af899bf1ec",
          "sha1": "6e3d24f69bc88994e82a6ba650ae1373832cb6f4",
          "md5": "a75083fbe2d544cb2762797b028f516d"
        }
      ]
    }
  ]
}
