{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4e",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-0.6.0.jar",
          "url": "ble-characteristic-u2a4e-0.6.0.jar",
          "size": 1884,
          "sha512": "566b3e2b750d94cdf4ebd297425fde27b94f315bb409f983cade2c9e5258a4ab74be55e135d6f120df7427c85b11f7c7884bf904a99f2141f9d443c0d699a844",
          "sha256": "ca28a4330fb709bd97da0d53245e9499628f6f07aea980763b54c55b1addde78",
          "sha1": "f6d1f3bd1aadef14bc9dd66a890a36c16792b8d3",
          "md5": "f7291cec3bb83a281d42c02949413658"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-0.6.0.jar",
          "url": "ble-characteristic-u2a4e-0.6.0.jar",
          "size": 1884,
          "sha512": "566b3e2b750d94cdf4ebd297425fde27b94f315bb409f983cade2c9e5258a4ab74be55e135d6f120df7427c85b11f7c7884bf904a99f2141f9d443c0d699a844",
          "sha256": "ca28a4330fb709bd97da0d53245e9499628f6f07aea980763b54c55b1addde78",
          "sha1": "f6d1f3bd1aadef14bc9dd66a890a36c16792b8d3",
          "md5": "f7291cec3bb83a281d42c02949413658"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4e-0.6.0-javadoc.jar",
          "url": "ble-characteristic-u2a4e-0.6.0-javadoc.jar",
          "size": 111006,
          "sha512": "66b0d12bfec23fbf5ca8c651fae01e4c0e5c65ec5a6eab08cc8e046fa5178a6e70f500e110aa528c42677c94dbbb5eaf4c1cb9d0a94826906055c8bb85158605",
          "sha256": "172406260e7213965feb0df7199964ae518f0e21cea9561dd37086c270f71149",
          "sha1": "c99fdcd97438cfb4b0cd6dd0fd62ea75388124a1",
          "md5": "838ab29363013beeca36b4252aad52ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4e-0.6.0-sources.jar",
          "url": "ble-characteristic-u2a4e-0.6.0-sources.jar",
          "size": 1721,
          "sha512": "412dc785e3fa5bce49843488cf96d6016bc4af628de55ae9c9bff8a841c7d341eef24b369d4e9f2d0401c3876c2bb017d06cf7c403d2353f061b44a9d9d7320e",
          "sha256": "a539da3391318e5b7ac62e760fd14b88ded7dcb88f6e585906036d9fa3bb793c",
          "sha1": "cdce836a4d37a949b40e918e417ba122f0dcd45e",
          "md5": "bcfb35329478159797199adfab3d0186"
        }
      ]
    }
  ]
}
