{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab6-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sipxf3vz2bcx5mgcg6vcjbnlti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab6",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab6-android-0.2.1.aar",
          "url": "ble-characteristic-u2ab6-android-0.2.1.aar",
          "size": 2868,
          "sha512": "91b7e437b4d622741b4ee24e04be2bc37be48789e2f6fc646b3cb101fe3a11fb4dfda66d1245344b87f7ccbef8c6eab0f1725089554c57592e7de9cedcdfcc5c",
          "sha256": "9cb23724d8230e99c3819c1097c0f248fda4133283d0ad3ec668de4111a3a386",
          "sha1": "aa2036239acf1edc89dce3a4d46fa711fdf9810a",
          "md5": "9901a7881cff39898c367228caadc044"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab6",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab6-android-0.2.1.aar",
          "url": "ble-characteristic-u2ab6-android-0.2.1.aar",
          "size": 2868,
          "sha512": "91b7e437b4d622741b4ee24e04be2bc37be48789e2f6fc646b3cb101fe3a11fb4dfda66d1245344b87f7ccbef8c6eab0f1725089554c57592e7de9cedcdfcc5c",
          "sha256": "9cb23724d8230e99c3819c1097c0f248fda4133283d0ad3ec668de4111a3a386",
          "sha1": "aa2036239acf1edc89dce3a4d46fa711fdf9810a",
          "md5": "9901a7881cff39898c367228caadc044"
        }
      ]
    }
  ]
}
