{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afa-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afa",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afa-android-0.8.12.aar",
          "url": "ble-characteristic-u2afa-android-0.8.12.aar",
          "size": 3210,
          "sha512": "7d025dd3bed71444151848fab99e96900fe695c7d0ad3e5e21bf9b8ae024fa90dad08d964d50abec8850528917be748a9a04e5ddf068391c0355be2db03dd475",
          "sha256": "f04b66563359ba515b15a66f93ece4e5bf9ca60205ff83bcd251dc6d5f91c9d5",
          "sha1": "5adc929c4a044c811746f32533d19a6369c1cf58",
          "md5": "d0722b712654164facca0563a27826ca"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afa",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afa-android-0.8.12.aar",
          "url": "ble-characteristic-u2afa-android-0.8.12.aar",
          "size": 3210,
          "sha512": "7d025dd3bed71444151848fab99e96900fe695c7d0ad3e5e21bf9b8ae024fa90dad08d964d50abec8850528917be748a9a04e5ddf068391c0355be2db03dd475",
          "sha256": "f04b66563359ba515b15a66f93ece4e5bf9ca60205ff83bcd251dc6d5f91c9d5",
          "sha1": "5adc929c4a044c811746f32533d19a6369c1cf58",
          "md5": "d0722b712654164facca0563a27826ca"
        }
      ]
    }
  ]
}
