{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aea-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aea",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aea-android-0.8.11.aar",
          "url": "ble-characteristic-u2aea-android-0.8.11.aar",
          "size": 3151,
          "sha512": "b5751c4a399f3044f323a29e18c190321fae99076e16b7c1c9e23499e3dc4ff2041f0908b0cae74bfd55e97e118d51855372ee53ca23fc2e17eaf156fd155fd1",
          "sha256": "d496110cb00c449df67dac12f9ecc344e0a2f438e4eb4448e926a0d2f7bd7f14",
          "sha1": "fa0c6687a207f3cfdfd3e6824b98c517aefc90e7",
          "md5": "01538a36783aba18ddf05fbf3034e2bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aea",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aea-android-0.8.11.aar",
          "url": "ble-characteristic-u2aea-android-0.8.11.aar",
          "size": 3151,
          "sha512": "b5751c4a399f3044f323a29e18c190321fae99076e16b7c1c9e23499e3dc4ff2041f0908b0cae74bfd55e97e118d51855372ee53ca23fc2e17eaf156fd155fd1",
          "sha256": "d496110cb00c449df67dac12f9ecc344e0a2f438e4eb4448e926a0d2f7bd7f14",
          "sha1": "fa0c6687a207f3cfdfd3e6824b98c517aefc90e7",
          "md5": "01538a36783aba18ddf05fbf3034e2bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aea-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2aea-android-0.8.11-sources.jar",
          "size": 2144,
          "sha512": "9ac58346114e38f251fb8be867b8e6a21c3f8c59bbda6e8ff59dee0cd7fe870822368699dbb688c15d2934e27bc0f39e9a299787218cfd3c6ebaee6c40026077",
          "sha256": "b234c0eccada0bf11245e7ea22b45a172f61bf822252593e1e12a55379273a72",
          "sha1": "87bdc6b776740ce5a2e19990b1e0669678458ef2",
          "md5": "e6dd99a7aa4934049a25c74de7bf9db5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aea-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2aea-android-0.8.11-javadoc.jar",
          "size": 270523,
          "sha512": "5faf44f2ab5e6928797c898924e1bf5910f73a528778d5aef6827ed94f7dd77c8382cb059aad479002e03d7a64cdfbc2b27e1ee69e82c23629b4d4d92cf0958d",
          "sha256": "e99ab8c34d4d37b4cf05359962da75c12c3c406c8d124215ccf0f1066d877013",
          "sha1": "d5d3deaaab00c13f182d371622cb28434958c65e",
          "md5": "579f3a5d2696568e4d52d8e0fce87606"
        }
      ]
    }
  ]
}
