{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a98-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a98",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-android-0.8.7.aar",
          "url": "ble-characteristic-u2a98-android-0.8.7.aar",
          "size": 3154,
          "sha512": "11221ab0bea4709352c0dcf5a8ea27b4e8deea99352c860b370215b91002664c68417646ab49b581ef7694f66bb6f54819a7b6fea067f893a0cceb5c43d68043",
          "sha256": "4ea8045170cd4d93c03b592d6c95c2a225d1ff332b58665fbf73f546f08b2041",
          "sha1": "348ce114d77efa23d255a6b581e9ffcf1cffd003",
          "md5": "a2ea1bfc68cf9d554bc10611b4bd2d3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a98",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a98-android-0.8.7.aar",
          "url": "ble-characteristic-u2a98-android-0.8.7.aar",
          "size": 3154,
          "sha512": "11221ab0bea4709352c0dcf5a8ea27b4e8deea99352c860b370215b91002664c68417646ab49b581ef7694f66bb6f54819a7b6fea067f893a0cceb5c43d68043",
          "sha256": "4ea8045170cd4d93c03b592d6c95c2a225d1ff332b58665fbf73f546f08b2041",
          "sha1": "348ce114d77efa23d255a6b581e9ffcf1cffd003",
          "md5": "a2ea1bfc68cf9d554bc10611b4bd2d3f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a98-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a98-android-0.8.7-sources.jar",
          "size": 2130,
          "sha512": "7564b6001a642599c15784ebe4ac955eb60a734cae382f0b6f7471f4bf4ca8f2203490f095e2f552c3a9545d94baa48cc93c8256604619989e813c6d3c8e596e",
          "sha256": "00014d3a0d1614f04003a349d7791c5f4686270e4a7b4f3d6ecf1f4d16ed8600",
          "sha1": "3e711452ac0f40d0cb437fba0f10439e5d5a3510",
          "md5": "c4e27e76a32e1d2856c0c8fc96b5ad97"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a98-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a98-android-0.8.7-javadoc.jar",
          "size": 268886,
          "sha512": "1b61f844d9774f26ea260fe923abcebfd964ec59fa52eaabca03b88f9109616dad9a47d93c33550132c91381feadb0e0fe4c97e52ecceaae5f1c741a2eb16e38",
          "sha256": "345838da293f6af3889b53e1b82fb2d3b7402452670030c4c1055d002270607d",
          "sha1": "921fd1a7fb77423a6146e780006caeed92e0234b",
          "md5": "857ad37b32bef18f16543e52617fe98f"
        }
      ]
    }
  ]
}
