{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aaf-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aaf",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aaf-android-0.2.9.aar",
          "url": "ble-characteristic-u2aaf-android-0.2.9.aar",
          "size": 3101,
          "sha512": "943b18c2540fb3fa1d6acb8203ea0a2cf2d9764461701b980ba819e2a0fa86dfbceb256426f3e0e546fb4c8598f5adb7ca856593cf1c243cbd41f814234a59b3",
          "sha256": "758c5ee3be850e516b327aaf44e9d09fd09905aeeed87ed89b5b1d35c636171d",
          "sha1": "7faba488a28229981aad6939a300968eb8041d90",
          "md5": "a5e94fcd41c72eefbddf864b73df3703"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aaf",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aaf-android-0.2.9.aar",
          "url": "ble-characteristic-u2aaf-android-0.2.9.aar",
          "size": 3101,
          "sha512": "943b18c2540fb3fa1d6acb8203ea0a2cf2d9764461701b980ba819e2a0fa86dfbceb256426f3e0e546fb4c8598f5adb7ca856593cf1c243cbd41f814234a59b3",
          "sha256": "758c5ee3be850e516b327aaf44e9d09fd09905aeeed87ed89b5b1d35c636171d",
          "sha1": "7faba488a28229981aad6939a300968eb8041d90",
          "md5": "a5e94fcd41c72eefbddf864b73df3703"
        }
      ]
    }
  ]
}
