{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.snksoft",
          "module": "crc",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-appearance",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-company",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-datatype",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-declaration",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-scheme",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-member",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-profile",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-protocol",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-sdo",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-unit",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-0.8.14.jar",
          "url": "ble-core-constants-0.8.14.jar",
          "size": 4222,
          "sha512": "7fb3b33b3c5cfb823787d50f495fe3e5e816d29a871246db7a12a107cf59f04097171c1e399401439f574248211c51503ff7312030fc3655cf0149811b260dc1",
          "sha256": "d7c67848084f9fa80ab571fdd483b6b2228016302107ba7ab072837f94b214ea",
          "sha1": "a82bc7fafd30a876d09d953f360e763a16ba7319",
          "md5": "954c4956467e7baa3067e50d1cca2096"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.github.snksoft",
          "module": "crc",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-appearance",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-company",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-datatype",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-declaration",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-errorcode",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-scheme",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-member",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-profile",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-protocol",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-sdo",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-service",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-unit",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-0.8.14.jar",
          "url": "ble-core-constants-0.8.14.jar",
          "size": 4222,
          "sha512": "7fb3b33b3c5cfb823787d50f495fe3e5e816d29a871246db7a12a107cf59f04097171c1e399401439f574248211c51503ff7312030fc3655cf0149811b260dc1",
          "sha256": "d7c67848084f9fa80ab571fdd483b6b2228016302107ba7ab072837f94b214ea",
          "sha1": "a82bc7fafd30a876d09d953f360e763a16ba7319",
          "md5": "954c4956467e7baa3067e50d1cca2096"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-0.8.14-javadoc.jar",
          "url": "ble-core-constants-0.8.14-javadoc.jar",
          "size": 106617,
          "sha512": "3562c204355743dbb9105563aa2a660d7df10b97e18f9d9e1ad99a2f981400ca0d5862293351c7ac86ee63ea0f784b9438b815c0cda7a006e5dca0c474b16eeb",
          "sha256": "f463d5f90452fbb0c6e7f031f65bdb6e035678c8a7c746bb1039682572d80b11",
          "sha1": "5d1196b513419b890e41639ea132cf14ad5e8659",
          "md5": "d3ddb6ed10a618fb9838b130f5820bec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-0.8.14-sources.jar",
          "url": "ble-core-constants-0.8.14-sources.jar",
          "size": 1547,
          "sha512": "742983671489af708074842f7a372f116b42b2905d9d30ad34e924f81f381e4a351eee545624b2a3d3b9e7afb832c722b7dfdf8ab1479612517496e14b78783e",
          "sha256": "f3cf0466f285699fa0f65c6289cb7901136dd796c9790a440fbc3bca34c44355",
          "sha1": "3f4b09ed4c47f4ec4f17eda28375dec0d1652745",
          "md5": "0a5d0bc4af9f9b23b98358e681334167"
        }
      ]
    }
  ]
}
