{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-tip-android",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-cts-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-ndcs-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-rtus-android",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-tip-android-0.5.0.aar",
          "url": "ble-profile-central-tip-android-0.5.0.aar",
          "size": 6199,
          "sha512": "cc3dacf5ce321607e67c81596f5b9072519ac15e73719415ce66b85907420cafe1f6b077510ec9ef8f51993ce01fc468203f613966d3444dd3012d5abc300293",
          "sha256": "0c6fe247e0e8762f7868df5d9e58904b436dbf07283a7371833c006a05ca10a5",
          "sha1": "80ed1a30a793d2be731e57eeb7b5d1dafe481a39",
          "md5": "8d9d9c4b404d85c5e1198fcef8a2613a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-cts-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-ndcs-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-rtus-android",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-tip-android-0.5.0.aar",
          "url": "ble-profile-central-tip-android-0.5.0.aar",
          "size": 6199,
          "sha512": "cc3dacf5ce321607e67c81596f5b9072519ac15e73719415ce66b85907420cafe1f6b077510ec9ef8f51993ce01fc468203f613966d3444dd3012d5abc300293",
          "sha256": "0c6fe247e0e8762f7868df5d9e58904b436dbf07283a7371833c006a05ca10a5",
          "sha1": "80ed1a30a793d2be731e57eeb7b5d1dafe481a39",
          "md5": "8d9d9c4b404d85c5e1198fcef8a2613a"
        }
      ]
    }
  ]
}
