{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a44-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.2.0.aar",
          "url": "ble-characteristic-u2a44-android-0.2.0.aar",
          "size": 2984,
          "sha512": "a16bed03be354ccb7bcefe95ae221493f049230899a7d49a4b1493ddbcb4defbd5359a5e31dd3a73de96e7dcd93d36261eada1728eb0596e2ac9f7e0ef58e290",
          "sha256": "1d7f7e8cc5a8198de48678b196df0b8e940245caa33faae4858cc15d009ed491",
          "sha1": "dc44d10b915afd680b55237d758fafbfd8edac57",
          "md5": "ace3f184d54e8bdd3a922c0e400791a3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.2.0.aar",
          "url": "ble-characteristic-u2a44-android-0.2.0.aar",
          "size": 2984,
          "sha512": "a16bed03be354ccb7bcefe95ae221493f049230899a7d49a4b1493ddbcb4defbd5359a5e31dd3a73de96e7dcd93d36261eada1728eb0596e2ac9f7e0ef58e290",
          "sha256": "1d7f7e8cc5a8198de48678b196df0b8e940245caa33faae4858cc15d009ed491",
          "sha1": "dc44d10b915afd680b55237d758fafbfd8edac57",
          "md5": "ace3f184d54e8bdd3a922c0e400791a3"
        }
      ]
    }
  ]
}
