{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aea",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.4.jar",
          "url": "ble-characteristic-u2aea-0.8.4.jar",
          "size": 1742,
          "sha512": "dec94a8358468340cd04edd27320c3c54e2f41342148175d4e86f8411a53754a98f16fe5614d11557190bf9ddceb55aa02e6ca18cff4a13e5d452d31f7764741",
          "sha256": "717265c44d9dcc1fe4a6c42937a4782782b76953210a8dc5c98317f872ff6312",
          "sha1": "9bdcf88d9933100adde746ebc97a91ac667db1e4",
          "md5": "c488518100071dbe50d1e1d8aca9d1a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.4.jar",
          "url": "ble-characteristic-u2aea-0.8.4.jar",
          "size": 1742,
          "sha512": "dec94a8358468340cd04edd27320c3c54e2f41342148175d4e86f8411a53754a98f16fe5614d11557190bf9ddceb55aa02e6ca18cff4a13e5d452d31f7764741",
          "sha256": "717265c44d9dcc1fe4a6c42937a4782782b76953210a8dc5c98317f872ff6312",
          "sha1": "9bdcf88d9933100adde746ebc97a91ac667db1e4",
          "md5": "c488518100071dbe50d1e1d8aca9d1a9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2aea-0.8.4-javadoc.jar",
          "size": 109986,
          "sha512": "dfc1aef47e0b572ff3fd43fc83f2afb59812eca4911c882193fbf7adbd12e93a8861eb2cebc0be09ae9e38138157a8a26ba6a3e4fb6e9b6d2f8773b4789fd84c",
          "sha256": "016c9184178a4c20298e8af52c0374799c569f080b12d24fd13c35e9235dabd7",
          "sha1": "421d17733031fdb7c4913193ec86c7a16fa22c28",
          "md5": "dd7130656af8c3e92f270ae832e2981a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aea-0.8.4-sources.jar",
          "url": "ble-characteristic-u2aea-0.8.4-sources.jar",
          "size": 1582,
          "sha512": "aee285b7fbb82008de4f0b028cbae6fcc02ef4087388a1c124774f957a47313127a9dc54c08a8c042de635dc8b63fa86cb032c2088e999bdf7a7c552061bef82",
          "sha256": "8c47ba444f5e63c5af1723c5934c380077b33a1f8f1fbaaeb0150dad052e3391",
          "sha1": "1eac8ecb8b65aadef338249b78b453ff33984666",
          "md5": "08ef835a50f1b77659b2ca68f2abe303"
        }
      ]
    }
  ]
}
