{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a89",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-0.8.5.jar",
          "url": "ble-characteristic-u2a89-0.8.5.jar",
          "size": 1764,
          "sha512": "dfeb4c30191fe69a06e43e965b06a634ce6f825ee79dab80a555bcaf194e41029de317c1a64eff5d33cb091e42074375a6d6f93a040ff6de8b9e682ef4987338",
          "sha256": "d2b907e738889852528ae6ce19e75529b608a58885b5c1be24897726eaa52743",
          "sha1": "49cd4b8152669d71599d508cb770c3ad65d52a2e",
          "md5": "1aad5bb72fc1e5825d95323360753430"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a89-0.8.5.jar",
          "url": "ble-characteristic-u2a89-0.8.5.jar",
          "size": 1764,
          "sha512": "dfeb4c30191fe69a06e43e965b06a634ce6f825ee79dab80a555bcaf194e41029de317c1a64eff5d33cb091e42074375a6d6f93a040ff6de8b9e682ef4987338",
          "sha256": "d2b907e738889852528ae6ce19e75529b608a58885b5c1be24897726eaa52743",
          "sha1": "49cd4b8152669d71599d508cb770c3ad65d52a2e",
          "md5": "1aad5bb72fc1e5825d95323360753430"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a89-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a89-0.8.5-javadoc.jar",
          "size": 107511,
          "sha512": "58421816020df2766b89a2584b83ebec810f52dff756db23b492fd13cd21978f488d7c980dc7fa66bc327a75a5e5b6973893689ba3115499560808016c2bb265",
          "sha256": "784188d4ea74b69ec6950d7b397c1e2bc265ab1a86cad829560d037ddb3f2c5b",
          "sha1": "37dec67f91d59e88ce707352ae6d2e60124ad41c",
          "md5": "294dd960802dec31a27fc2369e99ad30"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a89-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a89-0.8.5-sources.jar",
          "size": 1636,
          "sha512": "369fad0bb4d36b927ea407326954c4d6fda4416d8aa1644c1a1d9d411114ea671eb37368ebacc55c0248bc702fe97e4fa7aec0edebda5f33f2bacc5fdbf8efb5",
          "sha256": "9d621d373d831abdbee2574294eaf73786291b4660fc7d19b36439175ae5ad3b",
          "sha1": "70f41d2eb800c25b8889ae5a665345d5b33d206b",
          "md5": "85683e16192485762dd5a1a2c2eb8179"
        }
      ]
    }
  ]
}
