{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a03-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-android-0.2.8.aar",
          "url": "ble-characteristic-u2a03-android-0.2.8.aar",
          "size": 3109,
          "sha512": "8bc01d195872fc489cc3d478e83d980bd5e7aa99e662b4480c921c63f8d6216ceaed7741dd53516358fedb971ca2df1f651199792e33dc26f68dc55fbb4822f1",
          "sha256": "e31a6f91fb676fde21478efd7a3547c4a8d87ef2dbc3cb07c78a55c3b14eb75a",
          "sha1": "817052fbddced02eb5ebae70c0f124456e84e3bf",
          "md5": "2896a7c05e3d6a74a2e4a497f5d78fb8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-android-0.2.8.aar",
          "url": "ble-characteristic-u2a03-android-0.2.8.aar",
          "size": 3109,
          "sha512": "8bc01d195872fc489cc3d478e83d980bd5e7aa99e662b4480c921c63f8d6216ceaed7741dd53516358fedb971ca2df1f651199792e33dc26f68dc55fbb4822f1",
          "sha256": "e31a6f91fb676fde21478efd7a3547c4a8d87ef2dbc3cb07c78a55c3b14eb75a",
          "sha1": "817052fbddced02eb5ebae70c0f124456e84e3bf",
          "md5": "2896a7c05e3d6a74a2e4a497f5d78fb8"
        }
      ]
    }
  ]
}
