{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-pasp-central-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-central-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pasp-central-android-0.1.1.aar",
          "url": "ble-profile-pasp-central-android-0.1.1.aar",
          "size": 5018,
          "sha512": "d167596006e0a300b412ad9ca46b967035fad2c442a73f90923436cf95e69405876c5359ef8ab0305de6dcd4bdf92fecb2ee7ead9494c15a69f3788c77197612",
          "sha256": "eab51a95910e04a342bb1a89137aef782e0cb296730274ae0600441903b51775",
          "sha1": "ff812f462f25b2ead04aecbcbee337192a3dfa98",
          "md5": "2f21e03cd633c4eee386d6eecff34c41"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-central-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pasp-central-android-0.1.1.aar",
          "url": "ble-profile-pasp-central-android-0.1.1.aar",
          "size": 5018,
          "sha512": "d167596006e0a300b412ad9ca46b967035fad2c442a73f90923436cf95e69405876c5359ef8ab0305de6dcd4bdf92fecb2ee7ead9494c15a69f3788c77197612",
          "sha256": "eab51a95910e04a342bb1a89137aef782e0cb296730274ae0600441903b51775",
          "sha1": "ff812f462f25b2ead04aecbcbee337192a3dfa98",
          "md5": "2f21e03cd633c4eee386d6eecff34c41"
        }
      ]
    }
  ]
}
