{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab7-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab7",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-android-0.2.6.aar",
          "url": "ble-characteristic-u2ab7-android-0.2.6.aar",
          "size": 3096,
          "sha512": "6ba4a8cc38110e8318ea14512bdb861414259221e26c9b8b52bea51cb1c7a4aa228d546070ca78323416499752d4030079bfee296185faca6e5791a2f52ebc44",
          "sha256": "1ccbf147ff9df563947f657aa5f7bae220d4a4da721e90ba38c11e8e3cb1a310",
          "sha1": "d3002d4e28567c4f9275a0a90f475c9250dedb1b",
          "md5": "985694543c94835fcec22ed405d79bc6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab7",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-android-0.2.6.aar",
          "url": "ble-characteristic-u2ab7-android-0.2.6.aar",
          "size": 3096,
          "sha512": "6ba4a8cc38110e8318ea14512bdb861414259221e26c9b8b52bea51cb1c7a4aa228d546070ca78323416499752d4030079bfee296185faca6e5791a2f52ebc44",
          "sha256": "1ccbf147ff9df563947f657aa5f7bae220d4a4da721e90ba38c11e8e3cb1a310",
          "sha1": "d3002d4e28567c4f9275a0a90f475c9250dedb1b",
          "md5": "985694543c94835fcec22ed405d79bc6"
        }
      ]
    }
  ]
}
