{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-lnp-peripheral-android",
    "version": "0.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-lnp-peripheral-android-0.1.15.aar",
          "url": "ble-profile-lnp-peripheral-android-0.1.15.aar",
          "size": 5852,
          "sha512": "02de7632db85c81722942f942ac2666e16a6d413c1ecdbf2e0730e745263f45e3f5c239290df890c65da3bad0a6f3ffa84f69d628e2d9edc23924dad3187c29d",
          "sha256": "81a5ff78de8c34821269caf889687cdb26d0ebc5a07ef028563394b47845f664",
          "sha1": "c18a7b407c2aab2da11435f87abb9924e7f6fd1c",
          "md5": "e0067f7e34ed11337bcca931a091a727"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-lnp-peripheral-android-0.1.15.aar",
          "url": "ble-profile-lnp-peripheral-android-0.1.15.aar",
          "size": 5852,
          "sha512": "02de7632db85c81722942f942ac2666e16a6d413c1ecdbf2e0730e745263f45e3f5c239290df890c65da3bad0a6f3ffa84f69d628e2d9edc23924dad3187c29d",
          "sha256": "81a5ff78de8c34821269caf889687cdb26d0ebc5a07ef028563394b47845f664",
          "sha1": "c18a7b407c2aab2da11435f87abb9924e7f6fd1c",
          "md5": "e0067f7e34ed11337bcca931a091a727"
        }
      ]
    }
  ]
}
