{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a60-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a60",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a60-android-0.8.9.aar",
          "url": "ble-characteristic-u2a60-android-0.8.9.aar",
          "size": 3141,
          "sha512": "e58aad4d43f8d56135eeb492e21f316dd3a88c273bea0bd95148594b9dba4e2448621bb55f24c2f28c1533af1b2ba8ce1cb1aa26cfeba7027ac7d335cbbaa3d3",
          "sha256": "05eb0b76a437ffd4ef8ac56963f8e02d1b12e4dcec6f89f9223f76f347036a5c",
          "sha1": "684fd3020831cbfe410da7896a7994e72175f0e6",
          "md5": "151bd988eb9435d8cb34924d1fcafc80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a60",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a60-android-0.8.9.aar",
          "url": "ble-characteristic-u2a60-android-0.8.9.aar",
          "size": 3141,
          "sha512": "e58aad4d43f8d56135eeb492e21f316dd3a88c273bea0bd95148594b9dba4e2448621bb55f24c2f28c1533af1b2ba8ce1cb1aa26cfeba7027ac7d335cbbaa3d3",
          "sha256": "05eb0b76a437ffd4ef8ac56963f8e02d1b12e4dcec6f89f9223f76f347036a5c",
          "sha1": "684fd3020831cbfe410da7896a7994e72175f0e6",
          "md5": "151bd988eb9435d8cb34924d1fcafc80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a60-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2a60-android-0.8.9-sources.jar",
          "size": 2133,
          "sha512": "b073cf1efd345d50a50d67515ff9bf0530ef9350b7156444cc991185ce7f2f1ae7ae17e5322a8591a3e100ac0f436085a3ba568db06a98da26e3842e9f3c08dc",
          "sha256": "11be467323c069fbbf086cf6e8fe7b92cc8447e448aed270f6f822b72e9b6ca2",
          "sha1": "cac8fd1fc1e9c060868e075fc5f36e9fb373923c",
          "md5": "36c9bd5037e1924b8431d2b8af0c68e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a60-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2a60-android-0.8.9-javadoc.jar",
          "size": 270494,
          "sha512": "2acd58d7dbf6c055fd14eb4dc6b367eb1c1f06097209cfba615d282c06d6ca743709658673fcdf7be780bcc7a0d33c6bac44e4ab6c38610a5eecdc9ea07168f2",
          "sha256": "3119c4ed810007a9f5af35d41ae177323ed52a20debf0ce8ea7b8f3881f58510",
          "sha1": "1d2f142d6d86affe4157ea8354f4c72f9f9b861d",
          "md5": "3fd3ffca249e1ef14e916021929350e2"
        }
      ]
    }
  ]
}
