{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba4-android",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba4",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba4-android-0.5.0.aar",
          "url": "ble-characteristic-u2ba4-android-0.5.0.aar",
          "size": 3038,
          "sha512": "780392c9578e32be5f56b5e3aad2462811aae9d68655c6c6b5976fff943bee75a9a48b9c428f5cecd80ebfb66f343c2459252783bf1e9166b1897e54307036fc",
          "sha256": "2c0da3c41d5fa217a0c5328a72423227b63e2bd0cd765b1ec4adea83cceb3507",
          "sha1": "7ab853256ac37b728994022d23497668705142e9",
          "md5": "1d8f2d475df5671bf5baef4aba9308f8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba4",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba4-android-0.5.0.aar",
          "url": "ble-characteristic-u2ba4-android-0.5.0.aar",
          "size": 3038,
          "sha512": "780392c9578e32be5f56b5e3aad2462811aae9d68655c6c6b5976fff943bee75a9a48b9c428f5cecd80ebfb66f343c2459252783bf1e9166b1897e54307036fc",
          "sha256": "2c0da3c41d5fa217a0c5328a72423227b63e2bd0cd765b1ec4adea83cceb3507",
          "sha1": "7ab853256ac37b728994022d23497668705142e9",
          "md5": "1d8f2d475df5671bf5baef4aba9308f8"
        }
      ]
    }
  ]
}
