{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a82-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a82",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a82-android-0.2.5.aar",
          "url": "ble-characteristic-u2a82-android-0.2.5.aar",
          "size": 3157,
          "sha512": "cca7b2d90b013a8563c13a43974a4ff1e43a681f05d3ada9eaac69c48bb7a18f7d0ae7e1584050fd84cc12e40820126a46be6e9e6e6d26ead46d20d716967a1b",
          "sha256": "44afa224b5f5bbd80f234d0c1e2ca7f2e5b2d7b10901db1d5efb8f21043ccd9e",
          "sha1": "990a690951d70e57009cd24e1eb350fdf8165b95",
          "md5": "06db13c67d3ee1f83257680ca179d933"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a82",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a82-android-0.2.5.aar",
          "url": "ble-characteristic-u2a82-android-0.2.5.aar",
          "size": 3157,
          "sha512": "cca7b2d90b013a8563c13a43974a4ff1e43a681f05d3ada9eaac69c48bb7a18f7d0ae7e1584050fd84cc12e40820126a46be6e9e6e6d26ead46d20d716967a1b",
          "sha256": "44afa224b5f5bbd80f234d0c1e2ca7f2e5b2d7b10901db1d5efb8f21043ccd9e",
          "sha1": "990a690951d70e57009cd24e1eb350fdf8165b95",
          "md5": "06db13c67d3ee1f83257680ca179d933"
        }
      ]
    }
  ]
}
