{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-test-peripheral",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-test",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-test-peripheral-0.4.4.aar",
          "url": "ble-test-peripheral-0.4.4.aar",
          "size": 3360,
          "sha512": "b5e8633b2ac0b637c355894227943777d4fd74ba2c5f88cd4186bbd9aa72b9fc53cd8b995dd644bfb03439a91dd9a530c813b66b161c4eb80faf3c59a93d547b",
          "sha256": "2525f1723bf00fab16ea4d82590c355a0801bde4a5daf02e17d7f95980d74a04",
          "sha1": "98ff5c40ff7771bc532e3212ec760c237a69593f",
          "md5": "b3d633a94f36be8aa0e373223c4277af"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-test",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-test-peripheral-0.4.4.aar",
          "url": "ble-test-peripheral-0.4.4.aar",
          "size": 3360,
          "sha512": "b5e8633b2ac0b637c355894227943777d4fd74ba2c5f88cd4186bbd9aa72b9fc53cd8b995dd644bfb03439a91dd9a530c813b66b161c4eb80faf3c59a93d547b",
          "sha256": "2525f1723bf00fab16ea4d82590c355a0801bde4a5daf02e17d7f95980d74a04",
          "sha1": "98ff5c40ff7771bc532e3212ec760c237a69593f",
          "md5": "b3d633a94f36be8aa0e373223c4277af"
        }
      ]
    }
  ]
}
