{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bms-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa4-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bms-android-0.8.6.aar",
          "url": "ble-service-bms-android-0.8.6.aar",
          "size": 1223,
          "sha512": "379922b89664abdd9cda30cd57aa8364ccfd043a7cb7c15d5ef7e710d85577f82c860ca8aee4abbf4c4f3580b66a745870cff40ad8db300767dc97405b41d8d9",
          "sha256": "188f9f5f04a2bd0a619a60e942eef97ff6446612624d46f782f7bb985ea86c7a",
          "sha1": "1f029dc152bb71fc3f2bb56067e0e6a745a6c17b",
          "md5": "c489b7246b32b670bcf81584f393f111"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa4-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bms-android-0.8.6.aar",
          "url": "ble-service-bms-android-0.8.6.aar",
          "size": 1223,
          "sha512": "379922b89664abdd9cda30cd57aa8364ccfd043a7cb7c15d5ef7e710d85577f82c860ca8aee4abbf4c4f3580b66a745870cff40ad8db300767dc97405b41d8d9",
          "sha256": "188f9f5f04a2bd0a619a60e942eef97ff6446612624d46f782f7bb985ea86c7a",
          "sha1": "1f029dc152bb71fc3f2bb56067e0e6a745a6c17b",
          "md5": "c489b7246b32b670bcf81584f393f111"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-bms-android-0.8.6-sources.jar",
          "url": "ble-service-bms-android-0.8.6-sources.jar",
          "size": 1193,
          "sha512": "f504fe7fd92a55e264524988ef2adc117e88880eece6ecaed3de16922f315a79905e90fe52af5348dd596b40206045b8fb4e0e1c6b01af3dd06958c48d8add31",
          "sha256": "284f6be4434b3f14d71222dfe2e62bfea052425851ff1a6e853014635893a259",
          "sha1": "1d739da66c42609fe24cb997a995d3ee9d1cd791",
          "md5": "d90bf5d9a69eb2a4bbbca1016c6c70e2"
        }
      ]
    }
  ]
}
