{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a76-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smp7vu2g4jdlfelcafoemcahhe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a76",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a76-android-0.2.8.aar",
          "url": "ble-characteristic-u2a76-android-0.2.8.aar",
          "size": 3058,
          "sha512": "b9e0a9490cd055954876d391abb27989be1e1ce963c5ded42cbac0cffb8f1d6d8a2590636796a372ba4e6bda1d81a95d540becba9f3e25c182e80492d414d1a1",
          "sha256": "797ff21d848bfe8395d12c7fa2de0aa0d7364f19dffc30d51752dce1f1350c2f",
          "sha1": "f54af869ac0b5824676c07c1349722192485c3f7",
          "md5": "a2cea0a55612711b153f559649761fb2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a76",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a76-android-0.2.8.aar",
          "url": "ble-characteristic-u2a76-android-0.2.8.aar",
          "size": 3058,
          "sha512": "b9e0a9490cd055954876d391abb27989be1e1ce963c5ded42cbac0cffb8f1d6d8a2590636796a372ba4e6bda1d81a95d540becba9f3e25c182e80492d414d1a1",
          "sha256": "797ff21d848bfe8395d12c7fa2de0aa0d7364f19dffc30d51752dce1f1350c2f",
          "sha1": "f54af869ac0b5824676c07c1349722192485c3f7",
          "md5": "a2cea0a55612711b153f559649761fb2"
        }
      ]
    }
  ]
}
