{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2903-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "ldkg4hvqibct5os24hl54t3ga4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2903",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2903-android-0.1.3.aar",
          "url": "ble-descriptor-u2903-android-0.1.3.aar",
          "size": 2986,
          "sha512": "af11db57a009f774ff58d3dd0fd13009ffef8d1aed947e6239b6f4dec71383abff5efed14f85ad247fcd7aa157e7cd2c114924742f90b77bbba66f1861543824",
          "sha256": "2c089eff27f15e13b72000499b19b66fcbdb9d00357e5f5c0a5930551b1d205f",
          "sha1": "61f445a7622058e98f30eb894ba5220943cef0c2",
          "md5": "257075490d12d807dfc041775642dd72"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2903",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2903-android-0.1.3.aar",
          "url": "ble-descriptor-u2903-android-0.1.3.aar",
          "size": 2986,
          "sha512": "af11db57a009f774ff58d3dd0fd13009ffef8d1aed947e6239b6f4dec71383abff5efed14f85ad247fcd7aa157e7cd2c114924742f90b77bbba66f1861543824",
          "sha256": "2c089eff27f15e13b72000499b19b66fcbdb9d00357e5f5c0a5930551b1d205f",
          "sha1": "61f445a7622058e98f30eb894ba5220943cef0c2",
          "md5": "257075490d12d807dfc041775642dd72"
        }
      ]
    }
  ]
}
