{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a60",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a60-0.8.7.jar",
          "url": "ble-characteristic-u2a60-0.8.7.jar",
          "size": 1446,
          "sha512": "1c8ffa50c0f87926cdb4e3643f65cd8e36b9ab344415d01a51c1044494f6e67b0e553cce0a3cb04c4218e7a9275c0130badb2d649332d2455e281a73a92bbce4",
          "sha256": "5c3c0fea7103dbc59eecd8415c21d6eb42a9a96ab9faa514964f7c0dfc0db7ed",
          "sha1": "aabafe78fa9fc958fff2301b5ee725b63ac360a8",
          "md5": "c6b4276d86e9a6f7389aeaf165d89edf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a60-0.8.7.jar",
          "url": "ble-characteristic-u2a60-0.8.7.jar",
          "size": 1446,
          "sha512": "1c8ffa50c0f87926cdb4e3643f65cd8e36b9ab344415d01a51c1044494f6e67b0e553cce0a3cb04c4218e7a9275c0130badb2d649332d2455e281a73a92bbce4",
          "sha256": "5c3c0fea7103dbc59eecd8415c21d6eb42a9a96ab9faa514964f7c0dfc0db7ed",
          "sha1": "aabafe78fa9fc958fff2301b5ee725b63ac360a8",
          "md5": "c6b4276d86e9a6f7389aeaf165d89edf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a60-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a60-0.8.7-javadoc.jar",
          "size": 107138,
          "sha512": "9b09ed530594887a0d5662d2a6155a31394a8b764231d5f5607ff1cc6de0efd26f7e1d73d204bb68d3f94ed58d51dcdf31c26568e447d90d5a679dfebe910ddd",
          "sha256": "ec8fd5d461a3a600a13b12b7ac6420009af15921b2ce5b0ebed74178f7514139",
          "sha1": "c99fb10604e7bd762b3002363996eafd2e9f507e",
          "md5": "46244901225bff2b23f84d73d03c2932"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a60-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a60-0.8.7-sources.jar",
          "size": 1441,
          "sha512": "f9a402d19824391df4624e70e81aba4506415b0cf594f7e72521a669cedb845891459f9cd790b246fc766985c8d39399d52c081f550281fefe00ef3002aa6bf7",
          "sha256": "aee8c3e78cd1844f6a347f61097ac989c7d3b7bd4bf273b91217b1c4730b0b55",
          "sha1": "381c1f443746a14961d230d9694834a270d5c132",
          "md5": "aedca51b1e8e0448a886161a8bb4c787"
        }
      ]
    }
  ]
}
