{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2adc",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.8.jar",
          "url": "ble-characteristic-u2adc-0.8.8.jar",
          "size": 1478,
          "sha512": "2f093bbd1e94cacfac283ef52d7a94d81855ff7fec548d08690812b9a079aab35f7a4a91315ad9d92a8a7051af9897455f9adc9bb5ccc5e712a63854bef54aa7",
          "sha256": "7de07978d7b900014e4d1cc9739c0c2c39bc86c10f5bffd95a93f497fa570f6b",
          "sha1": "92eebc62600524b623136dd1a18b3e9e9dc03993",
          "md5": "9601462cbf009ea769214aabe5d6b593"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.8.jar",
          "url": "ble-characteristic-u2adc-0.8.8.jar",
          "size": 1478,
          "sha512": "2f093bbd1e94cacfac283ef52d7a94d81855ff7fec548d08690812b9a079aab35f7a4a91315ad9d92a8a7051af9897455f9adc9bb5ccc5e712a63854bef54aa7",
          "sha256": "7de07978d7b900014e4d1cc9739c0c2c39bc86c10f5bffd95a93f497fa570f6b",
          "sha1": "92eebc62600524b623136dd1a18b3e9e9dc03993",
          "md5": "9601462cbf009ea769214aabe5d6b593"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2adc-0.8.8-javadoc.jar",
          "size": 107238,
          "sha512": "9658294193bb78dfb02b763deaae9da27e29e65bb9b3820421f2645b8b0c1a778a5f1f6ccf0efae865a2281a8a106221f7e445bb987f6cae5c3e69514a6ea3eb",
          "sha256": "a895c52f23f9c5bd8d482a4ae8697ef616a2499d8c243b25d6d7afa22d1bdb59",
          "sha1": "a45d5883388e5434d34887af87e31b1ec0cbf733",
          "md5": "400b8d1ddea89beb7b6d1c8537f0b34e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2adc-0.8.8-sources.jar",
          "url": "ble-characteristic-u2adc-0.8.8-sources.jar",
          "size": 1464,
          "sha512": "f1bc3a23cbff15c7faf616123217afc461a0261bafe0ef113bdbe7d801d8abbec1faad5df9c8b3447d959fc517e87ac054a10aea4a8fbf8de81642180758d274",
          "sha256": "2b4908da77c467ef2fedb28ac4b1c083e4d33093d54ec342f6d0765931c18d47",
          "sha1": "51f3e91a121d229dc1acbfe7ba1cd59cf09961f2",
          "md5": "1a8b7749811f40ee0d8fabc9ffc194e4"
        }
      ]
    }
  ]
}
