{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a29-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.2.aar",
          "url": "ble-characteristic-u2a29-android-0.2.2.aar",
          "size": 2946,
          "sha512": "b61bc0aa0de20a31ebb6d0519831374aea88e4ab6900d76d59a38dc4fa2518047b47b8fec7d1c86a4c995dd7f2bf60fd48315f5c5056e5409fb5165edbc00ddc",
          "sha256": "ec8a615ddf98b45284f596ea95a8de201d556cb94a1c87250e01b6519a6f8489",
          "sha1": "a8dcaef55d9553e09c9b5602e1f24f52e0ed9f80",
          "md5": "a07f5a83cc1910edf7cc610d55734150"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.2.aar",
          "url": "ble-characteristic-u2a29-android-0.2.2.aar",
          "size": 2946,
          "sha512": "b61bc0aa0de20a31ebb6d0519831374aea88e4ab6900d76d59a38dc4fa2518047b47b8fec7d1c86a4c995dd7f2bf60fd48315f5c5056e5409fb5165edbc00ddc",
          "sha256": "ec8a615ddf98b45284f596ea95a8de201d556cb94a1c87250e01b6519a6f8489",
          "sha1": "a8dcaef55d9553e09c9b5602e1f24f52e0ed9f80",
          "md5": "a07f5a83cc1910edf7cc610d55734150"
        }
      ]
    }
  ]
}
