{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b12",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.7.jar",
          "url": "ble-characteristic-u2b12-0.8.7.jar",
          "size": 1761,
          "sha512": "1e18a38aa5aeee1f0bbc0b3eed28b79549b4d01cb7d4e73fc69df50fce9c89411c2bb142413707be26398ec063591acdbe2516cba15e36e7c5070e7f85fd4cab",
          "sha256": "926c58ef141f6e835c23e1fad6b11e4743a0edd2dbc7bcc3a3bc8e8b1b0647fa",
          "sha1": "b13256888985058d679830c48dc5064ca3fcbccb",
          "md5": "9bf5d799d46eb5286ed3663057825fa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.7.jar",
          "url": "ble-characteristic-u2b12-0.8.7.jar",
          "size": 1761,
          "sha512": "1e18a38aa5aeee1f0bbc0b3eed28b79549b4d01cb7d4e73fc69df50fce9c89411c2bb142413707be26398ec063591acdbe2516cba15e36e7c5070e7f85fd4cab",
          "sha256": "926c58ef141f6e835c23e1fad6b11e4743a0edd2dbc7bcc3a3bc8e8b1b0647fa",
          "sha1": "b13256888985058d679830c48dc5064ca3fcbccb",
          "md5": "9bf5d799d46eb5286ed3663057825fa5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b12-0.8.7-javadoc.jar",
          "size": 107348,
          "sha512": "766b10d6e0c24ce785c4cc60544f5d207d0c77b9d5b1baa0cec7651dc0994e7b9acf9efc972ab2fa62859ca685b65a1d57b507b708c6a32a618bbd615de5ce09",
          "sha256": "1164229275ed59757429a47e083c6766648a8b73c8111b771fde7ee84f672347",
          "sha1": "dd2cf76a4c02afa89823d94959bdd8552f2b3c00",
          "md5": "6fb6ebb6000dd5430c963d13acd47f76"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b12-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b12-0.8.7-sources.jar",
          "size": 1603,
          "sha512": "e5f30964ae5e99c7187fcb2c3ed051a63b81fd58a79859d51524e719d65c895fd6ff7258e6e0993d42d9f504a19aa3a2d75c6a299a0f769dcd2bc779c8c6946e",
          "sha256": "4637d90083395532655bbf60bd9aa381e4664dcb1e2f3d55b7a781a20400c55f",
          "sha1": "22b7514b830563ea3c26311da0a946ac5e552765",
          "md5": "73bd8116be80fd8c465714943185d95d"
        }
      ]
    }
  ]
}
