{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa4-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa4",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa4-android-0.2.2.aar",
          "url": "ble-characteristic-u2aa4-android-0.2.2.aar",
          "size": 3006,
          "sha512": "45988dd4d8277edbf9d6c12d10866fdb42700e437e439f1f820f783e102cb67dddd41a5b40c33d3a293f64843010e0018dacb8e9769147d8c92559c3ff0f9ae3",
          "sha256": "8f72f9cf76c04d2853879c4aff569b6687797551e3b5ac7750ba90927ee77bc4",
          "sha1": "f86a02edb8056b0f9ee14d81d2d967fe2cb0e7d7",
          "md5": "a9ee3f9000ad72d1aafc4974d5eec1e6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa4",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa4-android-0.2.2.aar",
          "url": "ble-characteristic-u2aa4-android-0.2.2.aar",
          "size": 3006,
          "sha512": "45988dd4d8277edbf9d6c12d10866fdb42700e437e439f1f820f783e102cb67dddd41a5b40c33d3a293f64843010e0018dacb8e9769147d8c92559c3ff0f9ae3",
          "sha256": "8f72f9cf76c04d2853879c4aff569b6687797551e3b5ac7750ba90927ee77bc4",
          "sha1": "f86a02edb8056b0f9ee14d81d2d967fe2cb0e7d7",
          "md5": "a9ee3f9000ad72d1aafc4974d5eec1e6"
        }
      ]
    }
  ]
}
