{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2902",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "3gjypjraujf5fc32spdlwmtq74"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-0.1.0.jar",
          "url": "ble-descriptor-u2902-0.1.0.jar",
          "size": 2097,
          "sha512": "a2fe29b3afb19e5272a534c86927cadf611cfbcb47ff3023a314455df52214c8c0b3f85780d52760fe47e72131eb58f9fef861dbc70fd47923e9984dc416c79f",
          "sha256": "bc81c38f36c03eb21e7b3140f0c84e0e9f2e3bc0f953b064d427b964e2587121",
          "sha1": "30f906b79d796e558992de4066e6f92475d3e45c",
          "md5": "7a132430e36eed7887900cf60dbac997"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-0.1.0.jar",
          "url": "ble-descriptor-u2902-0.1.0.jar",
          "size": 2097,
          "sha512": "a2fe29b3afb19e5272a534c86927cadf611cfbcb47ff3023a314455df52214c8c0b3f85780d52760fe47e72131eb58f9fef861dbc70fd47923e9984dc416c79f",
          "sha256": "bc81c38f36c03eb21e7b3140f0c84e0e9f2e3bc0f953b064d427b964e2587121",
          "sha1": "30f906b79d796e558992de4066e6f92475d3e45c",
          "md5": "7a132430e36eed7887900cf60dbac997"
        }
      ]
    }
  ]
}
