{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad6-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.8.8.aar",
          "url": "ble-characteristic-u2ad6-android-0.8.8.aar",
          "size": 3292,
          "sha512": "f03a3524d180f9165eed982d7813d59ecba786a3b19cf3a14b7596db9c942cde67334df9b2bef4e6f8d4439bbb09430eb20558aac945f8b989f17d880485e70a",
          "sha256": "f24426f93234e5cd6dfc48f6d16098eb6c701bf71b2aba44e1ff6ec855b230fd",
          "sha1": "72f49c87cb1108d22479cbc8eb24c58fc5e80c33",
          "md5": "bdeefe53c17886afcce80a885dc425b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.8.8.aar",
          "url": "ble-characteristic-u2ad6-android-0.8.8.aar",
          "size": 3292,
          "sha512": "f03a3524d180f9165eed982d7813d59ecba786a3b19cf3a14b7596db9c942cde67334df9b2bef4e6f8d4439bbb09430eb20558aac945f8b989f17d880485e70a",
          "sha256": "f24426f93234e5cd6dfc48f6d16098eb6c701bf71b2aba44e1ff6ec855b230fd",
          "sha1": "72f49c87cb1108d22479cbc8eb24c58fc5e80c33",
          "md5": "bdeefe53c17886afcce80a885dc425b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.8.8-sources.jar",
          "url": "ble-characteristic-u2ad6-android-0.8.8-sources.jar",
          "size": 2294,
          "sha512": "d881f448ed027fba944c7f062942f3bf3e0aed3639f65aca239edd99d18e5e2d1cfa14f24ca23d4bbc6cf5743298e716824ba3318a0060072d2ca0105bf5e3bc",
          "sha256": "0677afb1cf37a3b0be04f1ec534a9d40a499ff313c51fbfb00076e3941a50579",
          "sha1": "4bfdacd7360018a3bc9a23d174533ab56abf2cd7",
          "md5": "8279e366f93e00f8b971adb7bcd66863"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2ad6-android-0.8.8-javadoc.jar",
          "size": 270941,
          "sha512": "670b5d70824549858e2a012c03ca4beb4158db7f6dc6f2eb258230584299bccf46d33c9ffa0b15f93896a0bbb76c07f0ebe6cccbcac7ab11df695fd39811afec",
          "sha256": "2abd1eae54223eff28a1bf079102cdccbd7a887a6027afc8636775dc4d58a00f",
          "sha1": "bf991d0935d506683a32ab5fc847bd8e0a8a4766",
          "md5": "131bb8d936dae60c1ec977e731bd5cf5"
        }
      ]
    }
  ]
}
