{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a29-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smp7vu2g4jdlfelcafoemcahhe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.8.aar",
          "url": "ble-characteristic-u2a29-android-0.2.8.aar",
          "size": 3130,
          "sha512": "fd8a30d2d231691a4a26524fdbd9c09280cc170ced7d5ce5f40bfc3d2996625111acd6cd0b403539049e21fab13293ad97f780ee0525b604365fb2bbd0d163ff",
          "sha256": "7f7786cf5c7b23b5ec04421bde32f484c0902941e67db58b26a5c298e64a8836",
          "sha1": "c8350ffedddaaf05ed976945dc5965bb40c5e06e",
          "md5": "be4e83eab130490d86a9201e496c428c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.8.aar",
          "url": "ble-characteristic-u2a29-android-0.2.8.aar",
          "size": 3130,
          "sha512": "fd8a30d2d231691a4a26524fdbd9c09280cc170ced7d5ce5f40bfc3d2996625111acd6cd0b403539049e21fab13293ad97f780ee0525b604365fb2bbd0d163ff",
          "sha256": "7f7786cf5c7b23b5ec04421bde32f484c0902941e67db58b26a5c298e64a8836",
          "sha1": "c8350ffedddaaf05ed976945dc5965bb40c5e06e",
          "md5": "be4e83eab130490d86a9201e496c428c"
        }
      ]
    }
  ]
}
