{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a88",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a88-0.8.1.jar",
          "url": "ble-characteristic-u2a88-0.8.1.jar",
          "size": 1763,
          "sha512": "23e7f536eb7abf555502ae08b562d51b9dd3d7a2666ba19d59634ce3449b02f3e5b1958ef392d531df6f6bb8ab088f29ffedc4fd6f19c6216d5d162dae8a73a7",
          "sha256": "91c32c729339015cfe4fca9e50dcbf7abfd4b758b68f65538635fea5361fd7c4",
          "sha1": "3dd1053672ba1bb61ac16c70475b16d3d70df45e",
          "md5": "2392f8af22f69753482012a0676063b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a88-0.8.1.jar",
          "url": "ble-characteristic-u2a88-0.8.1.jar",
          "size": 1763,
          "sha512": "23e7f536eb7abf555502ae08b562d51b9dd3d7a2666ba19d59634ce3449b02f3e5b1958ef392d531df6f6bb8ab088f29ffedc4fd6f19c6216d5d162dae8a73a7",
          "sha256": "91c32c729339015cfe4fca9e50dcbf7abfd4b758b68f65538635fea5361fd7c4",
          "sha1": "3dd1053672ba1bb61ac16c70475b16d3d70df45e",
          "md5": "2392f8af22f69753482012a0676063b1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a88-0.8.1-javadoc.jar",
          "url": "ble-characteristic-u2a88-0.8.1-javadoc.jar",
          "size": 110222,
          "sha512": "e3e2e9feae2a89cd925f468717d26de9b527e2af5b43cfbe4f028e6d8d60ade9f291730fc1a3d185e30760b894ae1fa722b49831d10e05ef75735d27ffdc2def",
          "sha256": "cb9575a635efb7ecee1bacf5323522b8558868623f9f1cba142726c98074c591",
          "sha1": "9e4092ab992079abd9067280f890044a91ed4286",
          "md5": "b29dcd06e1aad45b6cccf33391aa59da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a88-0.8.1-sources.jar",
          "url": "ble-characteristic-u2a88-0.8.1-sources.jar",
          "size": 1636,
          "sha512": "79339e7650eeea02d454e610c227a2d0ca6d1ffcf4aa556729f781ac804b460c57aa24b7594686abcc1ee4a31fc68673902d41cd863dd56e3e0f9adc2034b01b",
          "sha256": "379bdb574549b356d441bcce4036a4327af1c9ff85f41840410e0a506e50f9a2",
          "sha1": "24aa5eb8afd2f35decff017c80b644050258cd8c",
          "md5": "26c1e0b7f6ca51475d072b620845f28f"
        }
      ]
    }
  ]
}
