{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a55",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-0.8.11.jar",
          "url": "ble-characteristic-u2a55-0.8.11.jar",
          "size": 3151,
          "sha512": "fa2681eefaeb78d1c10faec436719543b8e69021c8f1f632b30bb98315421ccfb8706a60d45eb94076a14d3009c2d7220781c2cf8bb53601dde24bd1e3d91d0f",
          "sha256": "4988cbaf7473673cca9dab412ef18e4e196a5657d406b2b50d285c19cb5eaa48",
          "sha1": "83bcd843eddca017e864e881e13bb4f239ebd815",
          "md5": "8298148a5cb24c7d1b1c80adb8d1a9fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-0.8.11.jar",
          "url": "ble-characteristic-u2a55-0.8.11.jar",
          "size": 3151,
          "sha512": "fa2681eefaeb78d1c10faec436719543b8e69021c8f1f632b30bb98315421ccfb8706a60d45eb94076a14d3009c2d7220781c2cf8bb53601dde24bd1e3d91d0f",
          "sha256": "4988cbaf7473673cca9dab412ef18e4e196a5657d406b2b50d285c19cb5eaa48",
          "sha1": "83bcd843eddca017e864e881e13bb4f239ebd815",
          "md5": "8298148a5cb24c7d1b1c80adb8d1a9fb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a55-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2a55-0.8.11-javadoc.jar",
          "size": 111834,
          "sha512": "31092ccb8e98859daaa4ca5225c499df0a9e7ec3b159ec10e3ee0c5788e5db5618c2f117273990a5cdd3e27d67ab196e0d608074205f63527d115e46ccf14b06",
          "sha256": "4f0aa660289526342b363e570429a4fe6744b3597cb27ac585b2ea8cbca99082",
          "sha1": "8dd2cae250385f45d08985cda196c19ae414ea4c",
          "md5": "ad8518611e3ae3055b7653e49d549330"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a55-0.8.11-sources.jar",
          "url": "ble-characteristic-u2a55-0.8.11-sources.jar",
          "size": 2756,
          "sha512": "983367f104971660040132bfb3e483ca247b0fe42304ba87a1a1c0a68d7d64d5533ac84a2556c141a2679a9b3f234c218aa257cfcd25d59c3d318755850a7ae2",
          "sha256": "9f4cdb279b633e5c2c574b936d127500052ff43e8f0693aaac0c6b03c18043c9",
          "sha1": "da13f5a5be79b20a211cbb4dec2d9bc0f71eca4d",
          "md5": "7d5fe8fc1f828176b1fa294fe05e29d1"
        }
      ]
    }
  ]
}
