{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bed-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bed",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bed-android-0.8.14.aar",
          "url": "ble-characteristic-u2bed-android-0.8.14.aar",
          "size": 3111,
          "sha512": "c4b0538eb8cb01925ce281b6990725ada2a59ffb17bacb98278d982babe2e7c501ec8030c4ce5b3a8ad51f65dd19f3c2e3b4487edc8ae97e112c3a5496506778",
          "sha256": "154b74fbaded19eeccd78fa9236d724cca5eca03ee62c91f7dd919f560c465cb",
          "sha1": "db37a5f8cefc26997366b95bac95cafc4ba5d5f4",
          "md5": "0815d46731a747e994cf7204d0eb0700"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bed",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bed-android-0.8.14.aar",
          "url": "ble-characteristic-u2bed-android-0.8.14.aar",
          "size": 3111,
          "sha512": "c4b0538eb8cb01925ce281b6990725ada2a59ffb17bacb98278d982babe2e7c501ec8030c4ce5b3a8ad51f65dd19f3c2e3b4487edc8ae97e112c3a5496506778",
          "sha256": "154b74fbaded19eeccd78fa9236d724cca5eca03ee62c91f7dd919f560c465cb",
          "sha1": "db37a5f8cefc26997366b95bac95cafc4ba5d5f4",
          "md5": "0815d46731a747e994cf7204d0eb0700"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bed-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2bed-android-0.8.14-sources.jar",
          "size": 2182,
          "sha512": "42da3ebc89451c5ef07e9b5360b4d212a50d8edbfee03d8d76ca2f596890fd2c9e4f54bec4b5a1d9ea18e6d3c5885516f24ab17793a219a63865dcfad3b10be8",
          "sha256": "2320ac1c4184924d173413a53ee4fd00cc787d3ba3b81534a6a7b4cb0a4390d3",
          "sha1": "bf110dd6a914934410e491a8e2f8220160430dc4",
          "md5": "21c3f9b6d183e4cf3e6f0a3b9922fe89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bed-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2bed-android-0.8.14-javadoc.jar",
          "size": 269371,
          "sha512": "4f25f93f5a9f3f02d8db3ae645a5d45f82acd2d6a59bd204178a4c8e16029ec9a38175f72b52a8748a48469ffbeec000d51db5110c9e1701a56d5dfe4fc09a0a",
          "sha256": "1f8a74901fc1d2f56171275ba2807ca9fad1399c54e2f71d21fdb28ad5af067f",
          "sha1": "44617036a7dd471802a1d71971ba1ceec4393ca3",
          "md5": "7519ad42474c0ce7b8f20fec4ccd147e"
        }
      ]
    }
  ]
}
