{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab1",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-0.4.5.jar",
          "url": "ble-characteristic-u2ab1-0.4.5.jar",
          "size": 1781,
          "sha512": "6541caa254435cb12b6b0df140cbb3a174d79e105338906dd81321d53c8dd4cd5839c931aa03a27775431ef96a4e6079b962f6e0458b6689d19fe56c0ed7e6ad",
          "sha256": "1928a14f36ece159d2e3152d83bf0a24e4838a0fbfe7ed4d6c212bc782293896",
          "sha1": "afa3460ddb1e225260f4db87a4fa26ed0cac9417",
          "md5": "a8f667cbfb15449a962b6d49191bcd8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-0.4.5.jar",
          "url": "ble-characteristic-u2ab1-0.4.5.jar",
          "size": 1781,
          "sha512": "6541caa254435cb12b6b0df140cbb3a174d79e105338906dd81321d53c8dd4cd5839c931aa03a27775431ef96a4e6079b962f6e0458b6689d19fe56c0ed7e6ad",
          "sha256": "1928a14f36ece159d2e3152d83bf0a24e4838a0fbfe7ed4d6c212bc782293896",
          "sha1": "afa3460ddb1e225260f4db87a4fa26ed0cac9417",
          "md5": "a8f667cbfb15449a962b6d49191bcd8e"
        }
      ]
    }
  ]
}
