{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lns-central-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sipxf3vz2bcx5mgcg6vcjbnlti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-central-android-0.1.1.aar",
          "url": "ble-service-lns-central-android-0.1.1.aar",
          "size": 7396,
          "sha512": "803076490ba3efded89b6193a0c0a9bb9ea9aea460580ff7c014a4322bfb226d54357c0ff2e6750c75f1a62d988ada9931f50c40a45d1f33653fd4d093f74ba1",
          "sha256": "1652a843ef7ce18a022682811f562a2e88346538da303e0c57aa7f5eb71fbbc8",
          "sha1": "d7a608eda1a87f0020f116cfcdfadc44a9af9431",
          "md5": "af4a835e3cf9e2761ea1e85a9ca3a463"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-central-android-0.1.1.aar",
          "url": "ble-service-lns-central-android-0.1.1.aar",
          "size": 7396,
          "sha512": "803076490ba3efded89b6193a0c0a9bb9ea9aea460580ff7c014a4322bfb226d54357c0ff2e6750c75f1a62d988ada9931f50c40a45d1f33653fd4d093f74ba1",
          "sha256": "1652a843ef7ce18a022682811f562a2e88346538da303e0c57aa7f5eb71fbbc8",
          "sha1": "d7a608eda1a87f0020f116cfcdfadc44a9af9431",
          "md5": "af4a835e3cf9e2761ea1e85a9ca3a463"
        }
      ]
    }
  ]
}
