{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9d",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "b5siun65pvf3xbu2ctcp5sxnw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9d-0.2.0.jar",
          "url": "ble-characteristic-u2a9d-0.2.0.jar",
          "size": 3602,
          "sha512": "c6fb41a0ddff2c25123616e32e3a22f9eeee3dcdf8d29552f4d7e931ca893dc915da7d36d7c74b72f8603cad59459a545f2eceafe12dad2ca9a05b4853fdf851",
          "sha256": "7a0338d4b56b767d5543f292a6019e29e01bfd14dabe738f405011c574281b9f",
          "sha1": "f1ab660f69254031ea34a41c7f633ef9f80afbd0",
          "md5": "c3f7abf391547d722fd244072856cd96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9d-0.2.0.jar",
          "url": "ble-characteristic-u2a9d-0.2.0.jar",
          "size": 3602,
          "sha512": "c6fb41a0ddff2c25123616e32e3a22f9eeee3dcdf8d29552f4d7e931ca893dc915da7d36d7c74b72f8603cad59459a545f2eceafe12dad2ca9a05b4853fdf851",
          "sha256": "7a0338d4b56b767d5543f292a6019e29e01bfd14dabe738f405011c574281b9f",
          "sha1": "f1ab660f69254031ea34a41c7f633ef9f80afbd0",
          "md5": "c3f7abf391547d722fd244072856cd96"
        }
      ]
    }
  ]
}
