{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd9-android",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd9",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd9-android-0.5.0.aar",
          "url": "ble-characteristic-u2bd9-android-0.5.0.aar",
          "size": 3087,
          "sha512": "e388d960bae2996b70683458cf64f03edb28f3847d88d2d6bf7500f495fa31bbe6b16c3b37d042c5e7c1ea708e7b230c28e3c8a751341c50b44432f938e59deb",
          "sha256": "dc6056f7576ad5384e21ed4e9df277cf1d4e072a48ebc867743e42b86e8bfd73",
          "sha1": "842b864a756d45203286f66f2bca112ce801f42b",
          "md5": "8724f5372fb6e6204f112680cbcf6a8c"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bd9",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd9-android-0.5.0.aar",
          "url": "ble-characteristic-u2bd9-android-0.5.0.aar",
          "size": 3087,
          "sha512": "e388d960bae2996b70683458cf64f03edb28f3847d88d2d6bf7500f495fa31bbe6b16c3b37d042c5e7c1ea708e7b230c28e3c8a751341c50b44432f938e59deb",
          "sha256": "dc6056f7576ad5384e21ed4e9df277cf1d4e072a48ebc867743e42b86e8bfd73",
          "sha1": "842b864a756d45203286f66f2bca112ce801f42b",
          "md5": "8724f5372fb6e6204f112680cbcf6a8c"
        }
      ]
    }
  ]
}
