{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab0-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "md2hzulcvrbjbp3omyeiu4n5fi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.2.3.aar",
          "url": "ble-characteristic-u2ab0-android-0.2.3.aar",
          "size": 2930,
          "sha512": "4faa275b8f4d3b294076bc38b0370d12df2aca6a9cf350279849d3552cf90efea2d886af2929495e91755f5e22b1b43365ecf821b9543c26531b9b6ac9c2019f",
          "sha256": "9beff082d9318ddf7d25737fef2202ef039f2e54fd1cf428cbd597b483d8f908",
          "sha1": "98b0358b22d0c9a2a89c67eade1efb9e6f5492da",
          "md5": "44dba85d06778807d0baaa775402e11d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.2.3.aar",
          "url": "ble-characteristic-u2ab0-android-0.2.3.aar",
          "size": 2930,
          "sha512": "4faa275b8f4d3b294076bc38b0370d12df2aca6a9cf350279849d3552cf90efea2d886af2929495e91755f5e22b1b43365ecf821b9543c26531b9b6ac9c2019f",
          "sha256": "9beff082d9318ddf7d25737fef2202ef039f2e54fd1cf428cbd597b483d8f908",
          "sha1": "98b0358b22d0c9a2a89c67eade1efb9e6f5492da",
          "md5": "44dba85d06778807d0baaa775402e11d"
        }
      ]
    }
  ]
}
