{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4a-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vdshvfksofcw3psi6e37oosvcq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4a",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4a-android-0.2.0.aar",
          "url": "ble-characteristic-u2a4a-android-0.2.0.aar",
          "size": 2932,
          "sha512": "4c977c2ec1fbbff3684081042dc129a26d85b0e14807fb5f432f9a44cff5707ac6223f912025ceb5edd93ed83f26335d3414341292b57b54286c6c0ad51cd26d",
          "sha256": "7a846e6395490404ccb0f8e69461b4e07c3450914d1c36b9ad249422ce3b8aaa",
          "sha1": "45504c6e83137bd53a4c8aa2c3509c9e111a18a3",
          "md5": "52afa2c4f0c20b9ea21a7c7a405f3bc4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4a",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4a-android-0.2.0.aar",
          "url": "ble-characteristic-u2a4a-android-0.2.0.aar",
          "size": 2932,
          "sha512": "4c977c2ec1fbbff3684081042dc129a26d85b0e14807fb5f432f9a44cff5707ac6223f912025ceb5edd93ed83f26335d3414341292b57b54286c6c0ad51cd26d",
          "sha256": "7a846e6395490404ccb0f8e69461b4e07c3450914d1c36b9ad249422ce3b8aaa",
          "sha1": "45504c6e83137bd53a4c8aa2c3509c9e111a18a3",
          "md5": "52afa2c4f0c20b9ea21a7c7a405f3bc4"
        }
      ]
    }
  ]
}
