{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b45-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b45",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b45-android-0.8.12.aar",
          "url": "ble-characteristic-u2b45-android-0.8.12.aar",
          "size": 3220,
          "sha512": "569385e85bc701b0f36d5f12bdda095b2c76fc58f1dac813f370528fbd0945d27835a734fb2c85daef150dcc1d319a263491a906d84a246f848e177a259fc25a",
          "sha256": "873f9422fb4b2a0841bc25f992c94967584d76ffa1c31767a22e50974bfa9379",
          "sha1": "77259d72726188e74534a472b93815af92f46a69",
          "md5": "a2075dfa62c560eed84603393371e3c1"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b45",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b45-android-0.8.12.aar",
          "url": "ble-characteristic-u2b45-android-0.8.12.aar",
          "size": 3220,
          "sha512": "569385e85bc701b0f36d5f12bdda095b2c76fc58f1dac813f370528fbd0945d27835a734fb2c85daef150dcc1d319a263491a906d84a246f848e177a259fc25a",
          "sha256": "873f9422fb4b2a0841bc25f992c94967584d76ffa1c31767a22e50974bfa9379",
          "sha1": "77259d72726188e74534a472b93815af92f46a69",
          "md5": "a2075dfa62c560eed84603393371e3c1"
        }
      ]
    }
  ]
}
