{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-test",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "x6nyasohnvdrtpp4affpidlfoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-test-0.0.2.aar",
          "url": "ble-test-0.0.2.aar",
          "size": 1224,
          "sha512": "389261ac43335fd84ba8790aa246018d04073f9064bb2d82d1a8735ddf38e0af81fc4135daedb5aff413207d64c24515cea66b813ae95d82cfe2d14f517cd2c5",
          "sha256": "0aff136557a75724431c181feb31e2c78bf135ff101e529117c04ab8e6d701de",
          "sha1": "b136e05b92acb5bbbf3cdc7501059d96988b111e",
          "md5": "a6afc938f34b5115a97d7642afea84f2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.test",
          "module": "runner",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-test-0.0.2.aar",
          "url": "ble-test-0.0.2.aar",
          "size": 1224,
          "sha512": "389261ac43335fd84ba8790aa246018d04073f9064bb2d82d1a8735ddf38e0af81fc4135daedb5aff413207d64c24515cea66b813ae95d82cfe2d14f517cd2c5",
          "sha256": "0aff136557a75724431c181feb31e2c78bf135ff101e529117c04ab8e6d701de",
          "sha1": "b136e05b92acb5bbbf3cdc7501059d96988b111e",
          "md5": "a6afc938f34b5115a97d7642afea84f2"
        }
      ]
    }
  ]
}
