{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a32-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.1.5.aar",
          "url": "ble-characteristic-u2a32-android-0.1.5.aar",
          "size": 3097,
          "sha512": "3d997daa7b63b2cbb8d8937838f88ec1f93796fa4d577727a0bcec1bf54042bb04842c02e82964feb5db8fa7a3b0fd32844c187b23e42ff6c05a267956b37565",
          "sha256": "4ee8110cbc0cfbb6fc441039cdabf73baed7b7459bb024156468e78486902b4f",
          "sha1": "f85b301eceb613b3e43129d9d5fdcb95176a0a11",
          "md5": "f326a7f34d1b1dc8165611605fc1a1a8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.1.5.aar",
          "url": "ble-characteristic-u2a32-android-0.1.5.aar",
          "size": 3097,
          "sha512": "3d997daa7b63b2cbb8d8937838f88ec1f93796fa4d577727a0bcec1bf54042bb04842c02e82964feb5db8fa7a3b0fd32844c187b23e42ff6c05a267956b37565",
          "sha256": "4ee8110cbc0cfbb6fc441039cdabf73baed7b7459bb024156468e78486902b4f",
          "sha1": "f85b301eceb613b3e43129d9d5fdcb95176a0a11",
          "md5": "f326a7f34d1b1dc8165611605fc1a1a8"
        }
      ]
    }
  ]
}
