{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1b-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1b-android-0.8.6.aar",
          "url": "ble-characteristic-u2b1b-android-0.8.6.aar",
          "size": 3080,
          "sha512": "4ce4f671e310fd8a7a9db9dfa477fdeabdbf2b995c6018f409dd639895e734ea8085b19ed5bb176a18dbc1dac8b46abd2366e2dd14b210fbd9676f29db9794bb",
          "sha256": "00c88ae8c0eab18a272c6ee23a717f38fde54c8c3ca017cf6f9a2187f03133bb",
          "sha1": "88159eb7843e30d798a0ebc7392c78f3efaa7470",
          "md5": "dee5b68ad0aa54f616a4f38c8f1b93f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1b-android-0.8.6.aar",
          "url": "ble-characteristic-u2b1b-android-0.8.6.aar",
          "size": 3080,
          "sha512": "4ce4f671e310fd8a7a9db9dfa477fdeabdbf2b995c6018f409dd639895e734ea8085b19ed5bb176a18dbc1dac8b46abd2366e2dd14b210fbd9676f29db9794bb",
          "sha256": "00c88ae8c0eab18a272c6ee23a717f38fde54c8c3ca017cf6f9a2187f03133bb",
          "sha1": "88159eb7843e30d798a0ebc7392c78f3efaa7470",
          "md5": "dee5b68ad0aa54f616a4f38c8f1b93f3"
        }
      ]
    }
  ]
}
