{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ias-peripheral-android",
    "version": "0.1.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgm5345lfvewjajsd7sfgyhu7u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-peripheral-android-0.1.13.aar",
          "url": "ble-service-ias-peripheral-android-0.1.13.aar",
          "size": 4798,
          "sha512": "624524af1a055dbde81c8d79e1d739b41cdcbd65bede43ea768741a8a8135d519f5cd0937ce37ea5c6c0b9612268dd870d3b33290cc175c7495a68d1f80aee2b",
          "sha256": "ccbd28a1ed4fd88a5ef7574d27a61f939d3591791f006cc6752576bd74cd1ab1",
          "sha1": "87e804c40391c71aa379706d71a91ec6b70a51b5",
          "md5": "628577aab6d8451a2c0ebab22a2ccc37"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-peripheral-android-0.1.13.aar",
          "url": "ble-service-ias-peripheral-android-0.1.13.aar",
          "size": 4798,
          "sha512": "624524af1a055dbde81c8d79e1d739b41cdcbd65bede43ea768741a8a8135d519f5cd0937ce37ea5c6c0b9612268dd870d3b33290cc175c7495a68d1f80aee2b",
          "sha256": "ccbd28a1ed4fd88a5ef7574d27a61f939d3591791f006cc6752576bd74cd1ab1",
          "sha1": "87e804c40391c71aa379706d71a91ec6b70a51b5",
          "md5": "628577aab6d8451a2c0ebab22a2ccc37"
        }
      ]
    }
  ]
}
