{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a06",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.7.jar",
          "url": "ble-characteristic-u2a06-0.8.7.jar",
          "size": 1889,
          "sha512": "8d227e03eff422a58583924fdd804df2705e64344aee55a6e1b1dfc12437ce3737350149c8978bb2a6e27979788a6bbf1584d63cc43e2ec589fc2d894783b5b7",
          "sha256": "0a7b321b13f02d9bdd316ba8c3acdb2271e47c3a49306c66942691734146be0f",
          "sha1": "2c160166fe3ebf300eda88759fede8e75fabe348",
          "md5": "d23899e02c5ac2ff5ef18190febf9fa7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.7.jar",
          "url": "ble-characteristic-u2a06-0.8.7.jar",
          "size": 1889,
          "sha512": "8d227e03eff422a58583924fdd804df2705e64344aee55a6e1b1dfc12437ce3737350149c8978bb2a6e27979788a6bbf1584d63cc43e2ec589fc2d894783b5b7",
          "sha256": "0a7b321b13f02d9bdd316ba8c3acdb2271e47c3a49306c66942691734146be0f",
          "sha1": "2c160166fe3ebf300eda88759fede8e75fabe348",
          "md5": "d23899e02c5ac2ff5ef18190febf9fa7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a06-0.8.7-javadoc.jar",
          "size": 109683,
          "sha512": "813f13af03c6ce302d155bacca36e0fb8c7f7093f21d5fc3f58b53b1658efe55c46ad50e9635e635968f78fd277b8533579d5be7a06015f7950c7cfa53723fe6",
          "sha256": "62eabc55ee4d4c889a85fbb920bd11679d9cf547e0e75ca3b0164907bcb32f58",
          "sha1": "cd61b82be031f828bcad9a72c2ba105c54dba546",
          "md5": "cf49020db9f9a9e05d1c65d820ea75ae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a06-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a06-0.8.7-sources.jar",
          "size": 1733,
          "sha512": "a0002d5f852529101e01611bd8c67d0b302346ade41ef427fe07122ffb87f041aca5d2fdcad6b7615810528f8ba3dbfe2f0bb3775405fa1aa92669e2996ead9c",
          "sha256": "a8447f68370efe50319d9cc6e426b3c0611630cf429a2fa04b94644bb2b89af2",
          "sha1": "de866f35c97b4852aa09825bf65fe8ec1feb710a",
          "md5": "7b24209bd6327cc8f6226266756c7961"
        }
      ]
    }
  ]
}
