{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-rscs-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rscs-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-rscs-android-0.4.2.aar",
          "url": "ble-service-peripheral-rscs-android-0.4.2.aar",
          "size": 11771,
          "sha512": "d30561add81dd23e474fd18edaaa32b25fbac64bda497a68ad9b098e89157606a3a12284b18fc615d81693cdfd0243e5fa3c17b22b12555d34ade838bb526348",
          "sha256": "299b89dece08f4e05aa5e4ddeb5d3d0ab50fa433e2d6bef92df918246360c833",
          "sha1": "cfb94922138aafc9d8c9f9aae98c2817cfb60fc0",
          "md5": "00af818a93c2512a187dd05388479016"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rscs-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-rscs-android-0.4.2.aar",
          "url": "ble-service-peripheral-rscs-android-0.4.2.aar",
          "size": 11771,
          "sha512": "d30561add81dd23e474fd18edaaa32b25fbac64bda497a68ad9b098e89157606a3a12284b18fc615d81693cdfd0243e5fa3c17b22b12555d34ade838bb526348",
          "sha256": "299b89dece08f4e05aa5e4ddeb5d3d0ab50fa433e2d6bef92df918246360c833",
          "sha1": "cfb94922138aafc9d8c9f9aae98c2817cfb60fc0",
          "md5": "00af818a93c2512a187dd05388479016"
        }
      ]
    }
  ]
}
