{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a45-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a45-android-0.2.8.aar",
          "url": "ble-characteristic-u2a45-android-0.2.8.aar",
          "size": 3119,
          "sha512": "95c6fe414433e25e2a9a6dade5237ca85693b13c3e28a82a3e1c7427d49718331418c881c43bc126a0745e060de1e482adcbcdfa6e7fb1cfc8f1f96e11fa5206",
          "sha256": "bd93ba8249502055888e91730dc29925aae08c9f94f604886dd5b3754717f246",
          "sha1": "d961d02b57e9eeacf5ddfd615ee5c0fa9f5e52a3",
          "md5": "11b4ac42db4b7708da2f40216afd588f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a45-android-0.2.8.aar",
          "url": "ble-characteristic-u2a45-android-0.2.8.aar",
          "size": 3119,
          "sha512": "95c6fe414433e25e2a9a6dade5237ca85693b13c3e28a82a3e1c7427d49718331418c881c43bc126a0745e060de1e482adcbcdfa6e7fb1cfc8f1f96e11fa5206",
          "sha256": "bd93ba8249502055888e91730dc29925aae08c9f94f604886dd5b3754717f246",
          "sha1": "d961d02b57e9eeacf5ddfd615ee5c0fa9f5e52a3",
          "md5": "11b4ac42db4b7708da2f40216afd588f"
        }
      ]
    }
  ]
}
