{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a85-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.8.6.aar",
          "url": "ble-characteristic-u2a85-android-0.8.6.aar",
          "size": 3102,
          "sha512": "3edd3310f3c2f01161e48349adb5032ba5afad8dd47e886ab94850a6ab7b0344f743575abc7ff2aa1a419736ffb1d19b8706b0432265b9912680298187c72076",
          "sha256": "f1d1cd719e587540f66afdb618b51f5a714b8a7dd695ce1561d8174bd615e7da",
          "sha1": "c4b756716df0e5be751ad66a77edb5c70aa84967",
          "md5": "94d1e6d8a5840cc02880605a0b792757"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.8.6.aar",
          "url": "ble-characteristic-u2a85-android-0.8.6.aar",
          "size": 3102,
          "sha512": "3edd3310f3c2f01161e48349adb5032ba5afad8dd47e886ab94850a6ab7b0344f743575abc7ff2aa1a419736ffb1d19b8706b0432265b9912680298187c72076",
          "sha256": "f1d1cd719e587540f66afdb618b51f5a714b8a7dd695ce1561d8174bd615e7da",
          "sha1": "c4b756716df0e5be751ad66a77edb5c70aa84967",
          "md5": "94d1e6d8a5840cc02880605a0b792757"
        }
      ]
    }
  ]
}
