{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb8",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb8-0.8.7.jar",
          "url": "ble-characteristic-u2bb8-0.8.7.jar",
          "size": 1516,
          "sha512": "197c03f6d643aa370b697cdad7680c39819dda3e5731b78220592ca8dbf1cca315323c3b9ee74410acabf893eadcac1571f073dbcfb27fdf658a2683b1168169",
          "sha256": "cb623320478030b998bc744ec2fae67029a052154714daf12a111e276c3e53dd",
          "sha1": "ec841e5f7f9367b6eccb2852c1e6e98ccd9011c1",
          "md5": "44d8e534491f7a7173b67dc24bcd0432"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb8-0.8.7.jar",
          "url": "ble-characteristic-u2bb8-0.8.7.jar",
          "size": 1516,
          "sha512": "197c03f6d643aa370b697cdad7680c39819dda3e5731b78220592ca8dbf1cca315323c3b9ee74410acabf893eadcac1571f073dbcfb27fdf658a2683b1168169",
          "sha256": "cb623320478030b998bc744ec2fae67029a052154714daf12a111e276c3e53dd",
          "sha1": "ec841e5f7f9367b6eccb2852c1e6e98ccd9011c1",
          "md5": "44d8e534491f7a7173b67dc24bcd0432"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb8-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bb8-0.8.7-javadoc.jar",
          "size": 107366,
          "sha512": "a0c6660a6928da2c105644cb47c5aeddb259998a5d3dc9285a4f8cd39b7c275f5f96137e195719c731c612f00e5c8d6dc25b69f0220d27e21bfa746d82c2af8d",
          "sha256": "9a0393d754ad0d53a344dc874f803adc66e59a7c14281361afda367217565ee0",
          "sha1": "32c4eb69b77f610d3c6d637c2a97591c3ec1e294",
          "md5": "1d9dad3a45008ef1ff80e5a764afb818"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb8-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bb8-0.8.7-sources.jar",
          "size": 1509,
          "sha512": "84b7791a212be1a81d7a7c7bd6a923dcc93989ad404d96a61e97800bb8037c355ee79aa5257aad0f5dcd63f110a5735738300dcf4d414395e418445964969ed4",
          "sha256": "5a717c90f7f4f8915daa532280337cbfa3330cc42589bd074bf145c7d13d58b3",
          "sha1": "c3f309fe75f567e7dcbf1754149c60ef375d00a8",
          "md5": "1dd4b076b5f9be30564a83b92682f660"
        }
      ]
    }
  ]
}
