{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4a-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "x6nyasohnvdrtpp4affpidlfoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4a",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4a-android-0.2.6.aar",
          "url": "ble-characteristic-u2a4a-android-0.2.6.aar",
          "size": 3109,
          "sha512": "f88cff46d0b0666ac9f21a12c8361f81eb2d66a438d87364a6773e412c255b90728274505c8e7195e1dea639da9e6181608975b7a591a453b4ec325b1e3cf15d",
          "sha256": "d1a1a5d06ff3b32061ef17a3c9f47b56f786ee820dcacb6ae65a50351b3e7a6a",
          "sha1": "1640c329e070aae573d8ec7267cda57295333003",
          "md5": "537b74485755750cc0ba40a80d9f144a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4a",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4a-android-0.2.6.aar",
          "url": "ble-characteristic-u2a4a-android-0.2.6.aar",
          "size": 3109,
          "sha512": "f88cff46d0b0666ac9f21a12c8361f81eb2d66a438d87364a6773e412c255b90728274505c8e7195e1dea639da9e6181608975b7a591a453b4ec325b1e3cf15d",
          "sha256": "d1a1a5d06ff3b32061ef17a3c9f47b56f786ee820dcacb6ae65a50351b3e7a6a",
          "sha1": "1640c329e070aae573d8ec7267cda57295333003",
          "md5": "537b74485755750cc0ba40a80d9f144a"
        }
      ]
    }
  ]
}
