{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2e",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2e-0.8.4.jar",
          "url": "ble-characteristic-u2b2e-0.8.4.jar",
          "size": 1771,
          "sha512": "7cd7e7e79e6446e2e91a7c5898a9978b47135380a055d80afe8a0d5fa19845e3788c09b355f9a9e5314d49af9e6ddff368d758de2e28c29cb24a9c588b0bb2e5",
          "sha256": "d9e9eec5eff24aaf0c8c57b8f9bfd93a23808d5e46073f6ab2a3d5497a10b157",
          "sha1": "7f0373d4597d7ee741d26676dcc910494648884f",
          "md5": "a90d746a0e651ffa7a067d35ad440437"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2e-0.8.4.jar",
          "url": "ble-characteristic-u2b2e-0.8.4.jar",
          "size": 1771,
          "sha512": "7cd7e7e79e6446e2e91a7c5898a9978b47135380a055d80afe8a0d5fa19845e3788c09b355f9a9e5314d49af9e6ddff368d758de2e28c29cb24a9c588b0bb2e5",
          "sha256": "d9e9eec5eff24aaf0c8c57b8f9bfd93a23808d5e46073f6ab2a3d5497a10b157",
          "sha1": "7f0373d4597d7ee741d26676dcc910494648884f",
          "md5": "a90d746a0e651ffa7a067d35ad440437"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2e-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2b2e-0.8.4-javadoc.jar",
          "size": 110658,
          "sha512": "260b2f4943349963b6325e5ab74bc762985083b458058bb54f4a2a6067d0927249253d8bc23d5ccc9fcdb8615a3b821676a72a8224228d108e091e93e8f446c3",
          "sha256": "429056560d03da47dc15cc0b90597e094027bb1c7f4016ce47364ccde16bcdf2",
          "sha1": "62a14fa7c868243dcb75f1ab54663ef711467b72",
          "md5": "bb3d355e5e8ed56a5c88109c1fe14df5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2e-0.8.4-sources.jar",
          "url": "ble-characteristic-u2b2e-0.8.4-sources.jar",
          "size": 1593,
          "sha512": "d2a2d4e263bb8488df1973cd8ed7d0aba675633100781118d652758df4b50ecfac01d546322d2e32a2c5e992aaf0f458956da0cdb97e9e8053a6e736e71f4e55",
          "sha256": "b314c65fab7b315188ac09584afe0b481853f7ca277a90170ae236f039f486dc",
          "sha1": "3ce43bfaec48b7fd6124ca8d38fe106f8a0f2fb8",
          "md5": "628d131e47780d06081b37f13ce73640"
        }
      ]
    }
  ]
}
