{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aaa-android",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aaa",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aaa-android-0.6.2.aar",
          "url": "ble-characteristic-u2aaa-android-0.6.2.aar",
          "size": 3042,
          "sha512": "73184669e391b2c7609b67b623e75594519bbaa8cd34ea623dc5805b0d1fc6752e465127111c585d5ab0c1ad240cc6068dd1712cb89c685d43b0fa0e298f9a3f",
          "sha256": "c59a157962408fd3ea9914f7ff7935e728b9eaecdbebd53c5f2b2ad85ba9e00b",
          "sha1": "0134c494a4a0c9a5305df6fc7307c9722db4d623",
          "md5": "c0cfd0cdbc4d880342c2db3ef8c364af"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aaa",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aaa-android-0.6.2.aar",
          "url": "ble-characteristic-u2aaa-android-0.6.2.aar",
          "size": 3042,
          "sha512": "73184669e391b2c7609b67b623e75594519bbaa8cd34ea623dc5805b0d1fc6752e465127111c585d5ab0c1ad240cc6068dd1712cb89c685d43b0fa0e298f9a3f",
          "sha256": "c59a157962408fd3ea9914f7ff7935e728b9eaecdbebd53c5f2b2ad85ba9e00b",
          "sha1": "0134c494a4a0c9a5305df6fc7307c9722db4d623",
          "md5": "c0cfd0cdbc4d880342c2db3ef8c364af"
        }
      ]
    }
  ]
}
