{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-lnp-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bas-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-lns-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-lnp-android-0.8.7.aar",
          "url": "ble-profile-central-lnp-android-0.8.7.aar",
          "size": 8198,
          "sha512": "0a8fe0cb238a4968695ce2cd5ef4803b4a62fdae4d07218c5ab332b22f384f73d5f0bf28bca06f78bb8696a588d76ed4e755b4b18b5f3cd36928ece97265dbb0",
          "sha256": "1a10922fb610c1db3b0bb7b6b2d8a1d1d69a14a0603bda4ca490ea0214c427bc",
          "sha1": "b20818ef809d41e150beec71d4a41fe3302ae8bd",
          "md5": "88e0be261a56526530c0e48954922e39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-dis-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-bas-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-lns-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-lnp-android-0.8.7.aar",
          "url": "ble-profile-central-lnp-android-0.8.7.aar",
          "size": 8198,
          "sha512": "0a8fe0cb238a4968695ce2cd5ef4803b4a62fdae4d07218c5ab332b22f384f73d5f0bf28bca06f78bb8696a588d76ed4e755b4b18b5f3cd36928ece97265dbb0",
          "sha256": "1a10922fb610c1db3b0bb7b6b2d8a1d1d69a14a0603bda4ca490ea0214c427bc",
          "sha1": "b20818ef809d41e150beec71d4a41fe3302ae8bd",
          "md5": "88e0be261a56526530c0e48954922e39"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-central-lnp-android-0.8.7-sources.jar",
          "url": "ble-profile-central-lnp-android-0.8.7-sources.jar",
          "size": 7212,
          "sha512": "c2a9bf4eab7a9d06247687f314d719549856c1b9be6892d3695d67fb97a51247a7c3477e84f2d6a797f92d6f0a60ff05a1fb8cacac158c89fa390ed6dce7327b",
          "sha256": "f1a29bf006d3d866e47cf8316e4ca64d08be5e833a4b24e3f7727af763c4ac44",
          "sha1": "0b96c487e1edf65c0b6baa0965825a26fa2e8c21",
          "md5": "5bce05c5e7de8352e473d7030fe96899"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-central-lnp-android-0.8.7-javadoc.jar",
          "url": "ble-profile-central-lnp-android-0.8.7-javadoc.jar",
          "size": 309691,
          "sha512": "e4fc436a961dc7ed151acfae6e677354328baa2bcd30beb716fa5530f3d9e06f8eb3d9e8fba0c543135a4e45890ebc142baed1b0e6cc74efda0c86ad7f820476",
          "sha256": "6b6718f705719b22bdb87ac2088b41ecb89d71883c520149b1adde63b5bfa4bf",
          "sha1": "e2aa8a491f4ca2f2dc1494d159bac088fee127b9",
          "md5": "6db3f5f7c5ebff51f18fa24ae2d4dfea"
        }
      ]
    }
  ]
}
