{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9c",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-0.8.12.jar",
          "url": "ble-characteristic-u2a9c-0.8.12.jar",
          "size": 10566,
          "sha512": "a222ff6a630b676fc7b0488c871fdca539466f03492a33d42ba775e0161a112c750bf867633ec3457724467dccb1646f984a0a28b158adde46171e8f30a4113a",
          "sha256": "4a0153bdc43590a6fc266f91c0ea73380f0dae1b863b50747115094ffc9e76ef",
          "sha1": "d2c5e9a5e305413b0f65ece6589fccfa9594c6bd",
          "md5": "af7f038e4f7af97e48cd7e477f3cf0a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-0.8.12.jar",
          "url": "ble-characteristic-u2a9c-0.8.12.jar",
          "size": 10566,
          "sha512": "a222ff6a630b676fc7b0488c871fdca539466f03492a33d42ba775e0161a112c750bf867633ec3457724467dccb1646f984a0a28b158adde46171e8f30a4113a",
          "sha256": "4a0153bdc43590a6fc266f91c0ea73380f0dae1b863b50747115094ffc9e76ef",
          "sha1": "d2c5e9a5e305413b0f65ece6589fccfa9594c6bd",
          "md5": "af7f038e4f7af97e48cd7e477f3cf0a4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9c-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a9c-0.8.12-javadoc.jar",
          "size": 127475,
          "sha512": "0da642696d65e4b85e4032f683832395c0db97e0d6f099444fcf7cd12cc1ab35ed3f0478eebc2652eb24af9becc9abfcdb85c48ba08d1b7c2ea4f425c5a58c63",
          "sha256": "9fa498274c9f765bb048f673c8cdd108e440c000a17f104e93e402386f3cf72d",
          "sha1": "dfb557b4764dd05fb9371cbab447f656f94f997e",
          "md5": "672e83611a034b9ab747835f4d1dbedb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9c-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a9c-0.8.12-sources.jar",
          "size": 9893,
          "sha512": "43c6236fe0552e0196648a6c779ec638e290092fc06a5210d4db41871c7c6c5c07cf434416e1c8d348716a3416dc8695eea4fa60c116104dfea0c6e71f03f7bf",
          "sha256": "0d9d48cb90536220272c62b123fe5990dd1f02b9a3457adb36c5df75af7ad04e",
          "sha1": "20939205fd1f4ad0cf1534e5ce0bfce3e0733092",
          "md5": "0668c1cf269ba9f709614e783068e38c"
        }
      ]
    }
  ]
}
