{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb5",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.9.jar",
          "url": "ble-characteristic-u2bb5-0.8.9.jar",
          "size": 1458,
          "sha512": "30b8fc5db87edb09e320ca40f3795c8ccd0fabea2a5e6fe00b0188e82594fd9d60c89b2bca9141ffb3c7f339a5b11c106b098abf7aa7fa7838ef8761383712a2",
          "sha256": "b0ddb3401d3b648834a1a2b7a97912289af615d1b53fd9f4fa1f8ccee1fbcc54",
          "sha1": "59d53bbe70a91a1599f9ed65cfe0776d93ac3843",
          "md5": "4dc4f9ffe90e66d75947a7728f3c87b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.9.jar",
          "url": "ble-characteristic-u2bb5-0.8.9.jar",
          "size": 1458,
          "sha512": "30b8fc5db87edb09e320ca40f3795c8ccd0fabea2a5e6fe00b0188e82594fd9d60c89b2bca9141ffb3c7f339a5b11c106b098abf7aa7fa7838ef8761383712a2",
          "sha256": "b0ddb3401d3b648834a1a2b7a97912289af615d1b53fd9f4fa1f8ccee1fbcc54",
          "sha1": "59d53bbe70a91a1599f9ed65cfe0776d93ac3843",
          "md5": "4dc4f9ffe90e66d75947a7728f3c87b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2bb5-0.8.9-javadoc.jar",
          "size": 107165,
          "sha512": "d2e5b164442ab9288510fe1aaac3f2731a60b7a9a52e3d16069c2cfebda9e651b229e24615006f3e016645c12c2ad0830e63c6d23a302827ccec7e4d24c652a0",
          "sha256": "0fbdd74dc48cb6b75b0d97d6dbf0cc503deeff2c80944650eb3d5300f47ca37c",
          "sha1": "0ef61c108d2995b9b822551ca55d291eac543de3",
          "md5": "11a38bc18f581690b5c5108ecdd4d357"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb5-0.8.9-sources.jar",
          "url": "ble-characteristic-u2bb5-0.8.9-sources.jar",
          "size": 1449,
          "sha512": "8c8f7eaa013f56eae7ac88bf2191b83657ced2543c291894d4e0cc8463f8daf0f2da03bbdf169ba540f3876a578591c5a9c10388be9fd4249d339f223139021a",
          "sha256": "42f8f9736e0ff2ad59d60bfc8593cf12d83dd2dae0aaffa9d6b3e7bd50702308",
          "sha1": "cdca048822b47ca94e7a0fae181ad7da5221ba29",
          "md5": "16df62640b3797dca6fc12daf56cc620"
        }
      ]
    }
  ]
}
