{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a13-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a13",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a13-android-0.8.12.aar",
          "url": "ble-characteristic-u2a13-android-0.8.12.aar",
          "size": 3160,
          "sha512": "4dd9637517139e0ce7c1ca923cb86786b6fc3f355639b612d29fe23e494ee8b176b0622b904a835b7412839de8476c15e785921f506fa9e2d66d85bb8a1e25e1",
          "sha256": "15c76250ec1c8d7a872653a68fd7e78eac8adbbe2923d71dfabc63c7e48a2db3",
          "sha1": "c2d0aecf86c91eab6065bf64085a2b6555fa508a",
          "md5": "f40944ce7eccd2995b2aca66e3854c81"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a13",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a13-android-0.8.12.aar",
          "url": "ble-characteristic-u2a13-android-0.8.12.aar",
          "size": 3160,
          "sha512": "4dd9637517139e0ce7c1ca923cb86786b6fc3f355639b612d29fe23e494ee8b176b0622b904a835b7412839de8476c15e785921f506fa9e2d66d85bb8a1e25e1",
          "sha256": "15c76250ec1c8d7a872653a68fd7e78eac8adbbe2923d71dfabc63c7e48a2db3",
          "sha1": "c2d0aecf86c91eab6065bf64085a2b6555fa508a",
          "md5": "f40944ce7eccd2995b2aca66e3854c81"
        }
      ]
    }
  ]
}
