{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a71",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "q4z4jr7cefarnmzk7t6opnz4hq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-0.2.6.jar",
          "url": "ble-characteristic-u2a71-0.2.6.jar",
          "size": 1880,
          "sha512": "0ecaff8c7642c906c876828fa8c47312408ac31bb6c4e025dc5525c61601c6dfe1d0e55d26f8ae182751bcdaa38d24f7859d015ed4fbca78e2f7f5aae8500404",
          "sha256": "a14e3362a9fd33622183f1f012cf6709b88fa7f736bbfd437bec32bc98a381aa",
          "sha1": "451828a40709373c55e8f73dbc7560a34c4cf18f",
          "md5": "0a30aaabe80afd3f56119263a0395707"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-0.2.6.jar",
          "url": "ble-characteristic-u2a71-0.2.6.jar",
          "size": 1880,
          "sha512": "0ecaff8c7642c906c876828fa8c47312408ac31bb6c4e025dc5525c61601c6dfe1d0e55d26f8ae182751bcdaa38d24f7859d015ed4fbca78e2f7f5aae8500404",
          "sha256": "a14e3362a9fd33622183f1f012cf6709b88fa7f736bbfd437bec32bc98a381aa",
          "sha1": "451828a40709373c55e8f73dbc7560a34c4cf18f",
          "md5": "0a30aaabe80afd3f56119263a0395707"
        }
      ]
    }
  ]
}
