{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ndcs-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ndcs-central-android-0.1.4.aar",
          "url": "ble-service-ndcs-central-android-0.1.4.aar",
          "size": 3250,
          "sha512": "ebce48e8725e52c976855710385d58777591e8c7007f51d38c68ba5c327f0ada93c4d66e55972229378ee22afd51fd296703f46d9d3613415b4e22db00ad00ff",
          "sha256": "c6b5a3a4c310421282e021e76dc0ca342cd8e13710eaf9e08f402d9e7910a924",
          "sha1": "724b4cbdd32889ed02d3d18e0d4cbcb2ee3c4d9a",
          "md5": "910f0df27803a3a1480540464a5cc756"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ndcs-central-android-0.1.4.aar",
          "url": "ble-service-ndcs-central-android-0.1.4.aar",
          "size": 3250,
          "sha512": "ebce48e8725e52c976855710385d58777591e8c7007f51d38c68ba5c327f0ada93c4d66e55972229378ee22afd51fd296703f46d9d3613415b4e22db00ad00ff",
          "sha256": "c6b5a3a4c310421282e021e76dc0ca342cd8e13710eaf9e08f402d9e7910a924",
          "sha1": "724b4cbdd32889ed02d3d18e0d4cbcb2ee3c4d9a",
          "md5": "910f0df27803a3a1480540464a5cc756"
        }
      ]
    }
  ]
}
