{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b36-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b36",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b36-android-0.8.12.aar",
          "url": "ble-characteristic-u2b36-android-0.8.12.aar",
          "size": 5154,
          "sha512": "5e864716cfc05368d81f6812f82c1cb817ddc324834fda3dda1ce79c10cd39180ec6ed0021720f10ae83ee0d95aaf47791841aeab96644550e151c56e3b8287d",
          "sha256": "36177e8abd9a5f6e1bc916cf2ef1b6b769681a6f0040794e2ed4d99632217b00",
          "sha1": "435566b96f811841dd4eeff20022eb8a52e32e6b",
          "md5": "02a866714dc312ab3ac52c262ddf5f9e"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b36",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b36-android-0.8.12.aar",
          "url": "ble-characteristic-u2b36-android-0.8.12.aar",
          "size": 5154,
          "sha512": "5e864716cfc05368d81f6812f82c1cb817ddc324834fda3dda1ce79c10cd39180ec6ed0021720f10ae83ee0d95aaf47791841aeab96644550e151c56e3b8287d",
          "sha256": "36177e8abd9a5f6e1bc916cf2ef1b6b769681a6f0040794e2ed4d99632217b00",
          "sha1": "435566b96f811841dd4eeff20022eb8a52e32e6b",
          "md5": "02a866714dc312ab3ac52c262ddf5f9e"
        }
      ]
    }
  ]
}
