{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b29-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b29",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b29-android-0.8.6.aar",
          "url": "ble-characteristic-u2b29-android-0.8.6.aar",
          "size": 3088,
          "sha512": "41b10e50eea907dbeac5ac7588022ab586ae91b29ca154ca7df727aa7e8e378f87fcf081d71ad120305ae82163e170c07d18fb57ec37a9a117874508040c1516",
          "sha256": "05ec6cbded04907be810a3fd304d0ff885e7a9600d3ab0c0e46d5d8651a6b706",
          "sha1": "c1e14b8cdb36737f5422f9c06275fb6dc54e62ae",
          "md5": "66617146c83d075523faf3121e26915d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b29",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b29-android-0.8.6.aar",
          "url": "ble-characteristic-u2b29-android-0.8.6.aar",
          "size": 3088,
          "sha512": "41b10e50eea907dbeac5ac7588022ab586ae91b29ca154ca7df727aa7e8e378f87fcf081d71ad120305ae82163e170c07d18fb57ec37a9a117874508040c1516",
          "sha256": "05ec6cbded04907be810a3fd304d0ff885e7a9600d3ab0c0e46d5d8651a6b706",
          "sha1": "c1e14b8cdb36737f5422f9c06275fb6dc54e62ae",
          "md5": "66617146c83d075523faf3121e26915d"
        }
      ]
    }
  ]
}
