{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2909",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "xnyhilluxvgr3nzweyacpeoi5a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2909-0.2.2.jar",
          "url": "ble-descriptor-u2909-0.2.2.jar",
          "size": 1707,
          "sha512": "c1910f4539f3cc2830723f51225adc06cd825a75e52e91da98b2971616c3291ebc3390568f97634eb0a496cb6a403c9ee4c5bc64cc4dd793471cfb6eed5a80f2",
          "sha256": "ed5121d72be4946538b7efa96f188a61aa8da7b39aa092a2a727d4352ab5d92c",
          "sha1": "ea70659b49d90e6bc62ee8d7d09fbfcd94a7034f",
          "md5": "54c516fc7be8e34c5f0b60752eb98025"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2909-0.2.2.jar",
          "url": "ble-descriptor-u2909-0.2.2.jar",
          "size": 1707,
          "sha512": "c1910f4539f3cc2830723f51225adc06cd825a75e52e91da98b2971616c3291ebc3390568f97634eb0a496cb6a403c9ee4c5bc64cc4dd793471cfb6eed5a80f2",
          "sha256": "ed5121d72be4946538b7efa96f188a61aa8da7b39aa092a2a727d4352ab5d92c",
          "sha1": "ea70659b49d90e6bc62ee8d7d09fbfcd94a7034f",
          "md5": "54c516fc7be8e34c5f0b60752eb98025"
        }
      ]
    }
  ]
}
