{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af2-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af2",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af2-android-0.8.12.aar",
          "url": "ble-characteristic-u2af2-android-0.8.12.aar",
          "size": 3108,
          "sha512": "1d185d045fe8118aab88040faea05101f1eb66180a4c62947f56bfa8541d318f45287e7d8b7e0373d17532da06abe5f53c4b437cac70031ba6af15edcd02f587",
          "sha256": "b35d0cb1659dc9d682734698248b7d42028dda8e50efda4bd8f0097bda94d61e",
          "sha1": "6ad81cc59cc96698184dbfacf372ed521af4d6bd",
          "md5": "868e26546478ed2616416a9da6a09318"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af2",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af2-android-0.8.12.aar",
          "url": "ble-characteristic-u2af2-android-0.8.12.aar",
          "size": 3108,
          "sha512": "1d185d045fe8118aab88040faea05101f1eb66180a4c62947f56bfa8541d318f45287e7d8b7e0373d17532da06abe5f53c4b437cac70031ba6af15edcd02f587",
          "sha256": "b35d0cb1659dc9d682734698248b7d42028dda8e50efda4bd8f0097bda94d61e",
          "sha1": "6ad81cc59cc96698184dbfacf372ed521af4d6bd",
          "md5": "868e26546478ed2616416a9da6a09318"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af2-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2af2-android-0.8.12-sources.jar",
          "size": 2160,
          "sha512": "af5324b38c2e8d5f9ac8ff00345f8b6ba3766ba4ed2e98c2c59ec3d9bfc772241f8c0575a072cb1687c43ced468e753174a117fb3faf6562edfb18892e324705",
          "sha256": "ea1703a80a3af56523d4e7852e97cc6e071f894ef4058474319be0083ac50261",
          "sha1": "f20df53d3369cbcc15dfae8b8810a295c80b2674",
          "md5": "3ae67302bfe15cc3c088fd7085b18ab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af2-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2af2-android-0.8.12-javadoc.jar",
          "size": 270994,
          "sha512": "cb19ea454e0301ac42961706497c347c2502f8e64703a2fbb746ab9e8a224c94b460e85c016107b23393f7477ef3e5a567d513e2f3909ca85a9d9819d348849f",
          "sha256": "0ca93ec99cf77e452fe670b9f14d529c1648892a41826e97f19e87fc39bfd01b",
          "sha1": "724bfc4d9906fcb9c27a7f8c3c01ff495b055d65",
          "md5": "a9025af0c74ed5b6d7788d5a6a9b9a46"
        }
      ]
    }
  ]
}
