{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a19-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a19",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a19-android-0.2.2.aar",
          "url": "ble-characteristic-u2a19-android-0.2.2.aar",
          "size": 2896,
          "sha512": "7e784537f6ad16412c322b91f78eb8e891452b262bc3216ef61d1e9b4b49cfb3ce7fbaa60f0f02b4fba5ee5979b7ba55d7754eebf5ccc6cebd3e5680a6506942",
          "sha256": "ef1b59afaf760fb1a744a08101848cc7a377ccbb0acc0b9b5a21ddbf64a1e120",
          "sha1": "a8817d746905cf9bd7f5517167ec02b71b9fbb22",
          "md5": "d171f8eb9991295faa9a75a453d9bab7"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a19",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a19-android-0.2.2.aar",
          "url": "ble-characteristic-u2a19-android-0.2.2.aar",
          "size": 2896,
          "sha512": "7e784537f6ad16412c322b91f78eb8e891452b262bc3216ef61d1e9b4b49cfb3ce7fbaa60f0f02b4fba5ee5979b7ba55d7754eebf5ccc6cebd3e5680a6506942",
          "sha256": "ef1b59afaf760fb1a744a08101848cc7a377ccbb0acc0b9b5a21ddbf64a1e120",
          "sha1": "a8817d746905cf9bd7f5517167ec02b71b9fbb22",
          "md5": "d171f8eb9991295faa9a75a453d9bab7"
        }
      ]
    }
  ]
}
