{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a77",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "fvvoe34nybbdlbbrzowl64zzta"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.2.4.jar",
          "url": "ble-characteristic-u2a77-0.2.4.jar",
          "size": 1859,
          "sha512": "b728576940e3a09b60d93e1462c61571bb6edee21507bd6cf5eede9a048ecae7db01ddbeba55a87921d2f450428265a41e5c68a5579fb9d6628c0e498f6cf3e9",
          "sha256": "0cb46b4f2a02ffc1699aed2a495e726a9ce14672b745432806310ee9259ad20e",
          "sha1": "2f2611e4976654ae662d81e9e13ca72f5cd1b5af",
          "md5": "448a4d606597f4f4f1f8c6df719490c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a77-0.2.4.jar",
          "url": "ble-characteristic-u2a77-0.2.4.jar",
          "size": 1859,
          "sha512": "b728576940e3a09b60d93e1462c61571bb6edee21507bd6cf5eede9a048ecae7db01ddbeba55a87921d2f450428265a41e5c68a5579fb9d6628c0e498f6cf3e9",
          "sha256": "0cb46b4f2a02ffc1699aed2a495e726a9ce14672b745432806310ee9259ad20e",
          "sha1": "2f2611e4976654ae662d81e9e13ca72f5cd1b5af",
          "md5": "448a4d606597f4f4f1f8c6df719490c0"
        }
      ]
    }
  ]
}
