{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aee",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aee-0.8.7.jar",
          "url": "ble-characteristic-u2aee-0.8.7.jar",
          "size": 1769,
          "sha512": "7375bed28fe0cf3eea8a8ab0f3609fbf82edc53d79e489f2443b0b27ab5c876acdd0498647b07aa2ea7d8a0280c62620bd58aa91b37e8fdb650ed15b0e8283a8",
          "sha256": "987ee1cf53a6f6c7785fd27baa394a9ea78dea322a8e3c0d1ec2e77268ad66c7",
          "sha1": "4658b88cf17bb7442b21b7fb56d5424934a17a6b",
          "md5": "9dc73763633d8b053ce5d4d1d83d60d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aee-0.8.7.jar",
          "url": "ble-characteristic-u2aee-0.8.7.jar",
          "size": 1769,
          "sha512": "7375bed28fe0cf3eea8a8ab0f3609fbf82edc53d79e489f2443b0b27ab5c876acdd0498647b07aa2ea7d8a0280c62620bd58aa91b37e8fdb650ed15b0e8283a8",
          "sha256": "987ee1cf53a6f6c7785fd27baa394a9ea78dea322a8e3c0d1ec2e77268ad66c7",
          "sha1": "4658b88cf17bb7442b21b7fb56d5424934a17a6b",
          "md5": "9dc73763633d8b053ce5d4d1d83d60d2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aee-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2aee-0.8.7-javadoc.jar",
          "size": 107336,
          "sha512": "c6f8b85286b144003084d8590f1cbde014e3e011606bec83dacba37051bab7e211656ceffae6f40f7efc9aa6391ac27d810b16dcf19f05d0d5dcccb02ff0a944",
          "sha256": "08e8be5e5244ed12ea92e7f8130fbd499916cace591e2b341891dcfc195652ff",
          "sha1": "ee27fbc29526b3467a89c4d669397183e78f670c",
          "md5": "079fe3601a8e35bdc3ce1c61f380b2f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aee-0.8.7-sources.jar",
          "url": "ble-characteristic-u2aee-0.8.7-sources.jar",
          "size": 1607,
          "sha512": "7a1fcc553a2764aa48b796bc25ea675105553777182539672b07f7609d749b94fd15f5ffafcf00b911d0f2868e7944aca8977bece5f4aa30cd8c0d88b18640df",
          "sha256": "ffb2ac08a9f89a4f7d3d89fa3f89c04632c684c45d4a94211e5bf06f5ccadf98",
          "sha1": "955549cdf4165ac21e43f58889c91e5c76166613",
          "md5": "d970c35afb7ea896a0d8da645ab14f71"
        }
      ]
    }
  ]
}
