{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a07",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-0.8.3.jar",
          "url": "ble-characteristic-u2a07-0.8.3.jar",
          "size": 1758,
          "sha512": "4f732cd026bbc528490c27ebe3cb2f9e2f29f94c4d52c93c00307e72434650c13e4572d09210bbdd626d97a5f3cd10b8e920e56d783d2b839962ddddffea23a5",
          "sha256": "17a78fb884d8e7f6b31eb0b2ba86efb4cb750c5b3edbb0f91abc31d86ae29c3f",
          "sha1": "9aeac689c674690c9e6b5d42c51efc6f7b56ab9e",
          "md5": "bf245d26c43cfc911380b60243504b91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-0.8.3.jar",
          "url": "ble-characteristic-u2a07-0.8.3.jar",
          "size": 1758,
          "sha512": "4f732cd026bbc528490c27ebe3cb2f9e2f29f94c4d52c93c00307e72434650c13e4572d09210bbdd626d97a5f3cd10b8e920e56d783d2b839962ddddffea23a5",
          "sha256": "17a78fb884d8e7f6b31eb0b2ba86efb4cb750c5b3edbb0f91abc31d86ae29c3f",
          "sha1": "9aeac689c674690c9e6b5d42c51efc6f7b56ab9e",
          "md5": "bf245d26c43cfc911380b60243504b91"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a07-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2a07-0.8.3-javadoc.jar",
          "size": 110050,
          "sha512": "ab739b96700714c55d6d3105cfbf60c9b9ebfb898f8eea3b9672d5c0ddfe515df402444a70bcf9bd547118bfd018e87981aee6e3156324095c92d6b7388945e1",
          "sha256": "d752c4887685c11651d75ce4f372ba39e89aef58be79fe00e763cad1958ca1d2",
          "sha1": "edffc75fb354d16662f11f0f27a2caa573fb55a9",
          "md5": "ebddf9cc7bf37cf92d821e2ff4a28f92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a07-0.8.3-sources.jar",
          "url": "ble-characteristic-u2a07-0.8.3-sources.jar",
          "size": 1598,
          "sha512": "6eadc0a257e47c39b8fb7c958b308e8c88bcf6300637e1a876832cd930fb562096c20caed8e80cbfe5401dc873bd0d2e5ad649e3d59cca281e406b0fe6c613ee",
          "sha256": "f6f0e1a38e2e198513d90fb32c8b3c320e77f3652a098e95b33f45c62ffa3ec9",
          "sha1": "157003f1a371a485a112716b2f1e0d5c0862219c",
          "md5": "b5eefdd13d184868a2f7ad047b4eb2cc"
        }
      ]
    }
  ]
}
