{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb1",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.6.jar",
          "url": "ble-characteristic-u2bb1-0.8.6.jar",
          "size": 1522,
          "sha512": "88c42809e8020021dbf40004a772cafc2e803a1e8858070ee223eb73347dbb4a7b17313f69d9c70ed0369bc225f17e51880f080c3fa9ae85bda4ee784f2a030c",
          "sha256": "258b659fd2ae934ebb55699f6fa76ddc8b6371d11b27298bd36e2a85fab00251",
          "sha1": "5bd367295b14ce94a499fd23e473fff41968320a",
          "md5": "f5340afb4cbb8b6eb90ebc366c93b3ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.6.jar",
          "url": "ble-characteristic-u2bb1-0.8.6.jar",
          "size": 1522,
          "sha512": "88c42809e8020021dbf40004a772cafc2e803a1e8858070ee223eb73347dbb4a7b17313f69d9c70ed0369bc225f17e51880f080c3fa9ae85bda4ee784f2a030c",
          "sha256": "258b659fd2ae934ebb55699f6fa76ddc8b6371d11b27298bd36e2a85fab00251",
          "sha1": "5bd367295b14ce94a499fd23e473fff41968320a",
          "md5": "f5340afb4cbb8b6eb90ebc366c93b3ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2bb1-0.8.6-javadoc.jar",
          "size": 107386,
          "sha512": "e9d9f33b9d6cd99ae5f9ab1c2f421aab50b14820f9fbf9834a8889ad22186689fc09abd894b5e490717db7287753f4a5e63fe25549b1ee83acf69731fe6ccd34",
          "sha256": "eec2d769ad30ae1f8ad937fb7350756d81c2c4f087313609a0ec5cd893ae5e6b",
          "sha1": "86ccc02ee36aadc2fc40757c63eae047725fdbf0",
          "md5": "0d1c78a3a2b33517d1270ad4a84168e8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb1-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bb1-0.8.6-sources.jar",
          "size": 1510,
          "sha512": "807be2e75eb5dee9bf22617bffa42fea834fbfecaae51c61fb81a913393fbb91ccae30674ad06d2cb53c14cb2b281fabd31e9213dbab14fe08f300dda94b706f",
          "sha256": "47f48e55fee6791651a3f6476b62c6ba220d9e4c6e0109a457f3d9f789903f66",
          "sha1": "f7be30b0181d72b4eda66a099d2cdeff716b0090",
          "md5": "3b7472d8a6b29e5039f2dd5b62201399"
        }
      ]
    }
  ]
}
