{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b21",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.14.jar",
          "url": "ble-characteristic-u2b21-0.8.14.jar",
          "size": 1439,
          "sha512": "c081790c249dd0f1997e39ed1f5bd297f887cadf7f996970e2d37f0ae7c87047196b83fa0d08b84f58b4a1741f8737c38bb3cc27d5b66e610a61bc4177a3ccab",
          "sha256": "36a1a707eb125c748df31e5eaf07bd7e55ee6ec085b17d44022fffd7d1ed7470",
          "sha1": "6e833ecb7e042ad372d5d02bd9f134dd6ed5dad9",
          "md5": "c3da01dfa40face2e4e834fe8a932a88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.14.jar",
          "url": "ble-characteristic-u2b21-0.8.14.jar",
          "size": 1439,
          "sha512": "c081790c249dd0f1997e39ed1f5bd297f887cadf7f996970e2d37f0ae7c87047196b83fa0d08b84f58b4a1741f8737c38bb3cc27d5b66e610a61bc4177a3ccab",
          "sha256": "36a1a707eb125c748df31e5eaf07bd7e55ee6ec085b17d44022fffd7d1ed7470",
          "sha1": "6e833ecb7e042ad372d5d02bd9f134dd6ed5dad9",
          "md5": "c3da01dfa40face2e4e834fe8a932a88"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2b21-0.8.14-javadoc.jar",
          "size": 85936,
          "sha512": "ac64459cdbadadff3e47b8fed51efe7308c24465b30ffae56f112390bbb65037273711a14cadd7f82065136f378982f8e40fd601b1413b7849c0eed19e61294d",
          "sha256": "cc5ba6acc81a24d02c2557917af1137295b71a591a2d72e5218ef540bba4e86e",
          "sha1": "7de263ae56ed46c7bae6103961da025a945dc7b7",
          "md5": "1c194d2ff1866742e9840bd9cb08a030"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b21-0.8.14-sources.jar",
          "url": "ble-characteristic-u2b21-0.8.14-sources.jar",
          "size": 1428,
          "sha512": "d464becd62a29e99e0b5ce9eec1ff40bdc1acf0ca2900138c409ac9144e489e2f7a66d868b5a445a30f0e277884ee651c709937da782845a4c477230340be878",
          "sha256": "960cee14c991193158a812383dc0dc5dd100ca4bcd80c34fc07f41d0dbf8c543",
          "sha1": "d9dbab4232b437abd1b3a5b37762610b8a0b4c63",
          "md5": "9c91171516869a6db4358b56c75a6ff2"
        }
      ]
    }
  ]
}
