{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a00-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.2.2.aar",
          "url": "ble-characteristic-u2a00-android-0.2.2.aar",
          "size": 2905,
          "sha512": "8afc0430d2b33e852b5a7b021df959e56dc32667b5d8965b5522dbd02753497ee9fd4422652c9e051c9a8b824d2a0ced733b5ee63a44c6173582f8a15b120bce",
          "sha256": "aa05546c10a549d72b75c4f29b8a39a77c492dda7cf44b73c6b770bdd79e237b",
          "sha1": "7b4df06012c45333fe6f59953ddcbeb87da27ede",
          "md5": "a579ee276c0505d7ea239d5a1496f8ab"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.2.2.aar",
          "url": "ble-characteristic-u2a00-android-0.2.2.aar",
          "size": 2905,
          "sha512": "8afc0430d2b33e852b5a7b021df959e56dc32667b5d8965b5522dbd02753497ee9fd4422652c9e051c9a8b824d2a0ced733b5ee63a44c6173582f8a15b120bce",
          "sha256": "aa05546c10a549d72b75c4f29b8a39a77c492dda7cf44b73c6b770bdd79e237b",
          "sha1": "7b4df06012c45333fe6f59953ddcbeb87da27ede",
          "md5": "a579ee276c0505d7ea239d5a1496f8ab"
        }
      ]
    }
  ]
}
