{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b02-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b02",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b02-android-0.8.12.aar",
          "url": "ble-characteristic-u2b02-android-0.8.12.aar",
          "size": 3156,
          "sha512": "c50d1ecde8dd9090c702044aeadd0ab37ec2377cfc78c302f96ff59ac02bd1257437fe78dff9b5fc468535bdec4efde7479c468a269b14001056f45302e5cf8c",
          "sha256": "f970cee8df33cd142031a0fb85617a23dc5288e36fb30697aeaae8be4085e763",
          "sha1": "d23f87b61d245e44df0a24365a239eeb9d19ebb3",
          "md5": "dc3afa5b47a85b05cac30f310d2ada4e"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b02",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b02-android-0.8.12.aar",
          "url": "ble-characteristic-u2b02-android-0.8.12.aar",
          "size": 3156,
          "sha512": "c50d1ecde8dd9090c702044aeadd0ab37ec2377cfc78c302f96ff59ac02bd1257437fe78dff9b5fc468535bdec4efde7479c468a269b14001056f45302e5cf8c",
          "sha256": "f970cee8df33cd142031a0fb85617a23dc5288e36fb30697aeaae8be4085e763",
          "sha1": "d23f87b61d245e44df0a24365a239eeb9d19ebb3",
          "md5": "dc3afa5b47a85b05cac30f310d2ada4e"
        }
      ]
    }
  ]
}
