{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a51",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.14.jar",
          "url": "ble-characteristic-u2a51-0.8.14.jar",
          "size": 1455,
          "sha512": "0c0286ed10af58f277151fc1257674b95682d4364245ec8a0b572f6fbd778712d4c8f84a2c15cf6849a15a7ae458834b53f5c2b19500ab576bf3413508633210",
          "sha256": "2b6651caf345fdcf1729777c2b4111b016583508c0cebb5a62cb58b3be64a435",
          "sha1": "97d3277d6d8116b78e430324492ef8dcdfcc117d",
          "md5": "07b1bf65a7089de14ec52733a9d7251b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.14.jar",
          "url": "ble-characteristic-u2a51-0.8.14.jar",
          "size": 1455,
          "sha512": "0c0286ed10af58f277151fc1257674b95682d4364245ec8a0b572f6fbd778712d4c8f84a2c15cf6849a15a7ae458834b53f5c2b19500ab576bf3413508633210",
          "sha256": "2b6651caf345fdcf1729777c2b4111b016583508c0cebb5a62cb58b3be64a435",
          "sha1": "97d3277d6d8116b78e430324492ef8dcdfcc117d",
          "md5": "07b1bf65a7089de14ec52733a9d7251b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2a51-0.8.14-javadoc.jar",
          "size": 85950,
          "sha512": "7f7626e93ce22c108d9b7a8001b92f356daa62fd33b4cdd669ddf75ad4a736b41f884d45575499d6553aa104ec1965eb2c58e280beef680f63986f16bd4fc5d0",
          "sha256": "aadc52112650d616b80e54bc4465ce72a0d2214a43bdcf46b3cf9b133bfd4ed5",
          "sha1": "e40b14bd8fe50629e922dfe8c97215cfced50897",
          "md5": "50214a1214e9b42b4f9a938db8a1b07a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.14-sources.jar",
          "url": "ble-characteristic-u2a51-0.8.14-sources.jar",
          "size": 1454,
          "sha512": "dbb885389cf41025fa8fa9db141dc94978c5e1373ebef9a7c778ce907f36fb959c00a908e42ec46e81656dbf8a221e8af0047de8ba19581be07bf2ea1bfd68bc",
          "sha256": "dfc6f2e79ad4ea4e6aaf9cb0e5a2c17afd4b4f256f9de891356ac94d167496e8",
          "sha1": "5bbd09e9f797e47eb75429e1d280b6928f7fd22e",
          "md5": "abb1e9891dd1125a31ab88e9c11f9621"
        }
      ]
    }
  ]
}
