{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3b-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3b-android-0.8.6.aar",
          "url": "ble-characteristic-u2b3b-android-0.8.6.aar",
          "size": 3105,
          "sha512": "22facc413c257443cc7f3e010912e3196e68e371f0f016128d1bce8e01c39485f85edb9b1a422e5613a2b2dca469596d22ba3a780763b80ed57c941783ae8f20",
          "sha256": "0d3a2ea26f15fb93a330f00403314e52e67e508d97b5c5313db064146465ec89",
          "sha1": "396fa91aed16fe01a77b0a264b05aaba22afe211",
          "md5": "72c9399680b8a1fc655d8cd8ceb5eaad"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3b-android-0.8.6.aar",
          "url": "ble-characteristic-u2b3b-android-0.8.6.aar",
          "size": 3105,
          "sha512": "22facc413c257443cc7f3e010912e3196e68e371f0f016128d1bce8e01c39485f85edb9b1a422e5613a2b2dca469596d22ba3a780763b80ed57c941783ae8f20",
          "sha256": "0d3a2ea26f15fb93a330f00403314e52e67e508d97b5c5313db064146465ec89",
          "sha1": "396fa91aed16fe01a77b0a264b05aaba22afe211",
          "md5": "72c9399680b8a1fc655d8cd8ceb5eaad"
        }
      ]
    }
  ]
}
