{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a39",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.6.jar",
          "url": "ble-characteristic-u2a39-0.8.6.jar",
          "size": 1885,
          "sha512": "23a5812d88f4c7578fba0a049c8aba028be51d453dec86e5ab4c4d92b02a799a2f73ca65194e2b0cde4585026950da0e8543746a6d00e535dd895e380f7d5757",
          "sha256": "b81f569ef64ca81d62f59efb3fd613dcc39f072de27944ccc47d002418934096",
          "sha1": "af46801abe0110436ebcc8290984d213845dfa7a",
          "md5": "f559c1d3bb74263eb43c3e9531c714f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.6.jar",
          "url": "ble-characteristic-u2a39-0.8.6.jar",
          "size": 1885,
          "sha512": "23a5812d88f4c7578fba0a049c8aba028be51d453dec86e5ab4c4d92b02a799a2f73ca65194e2b0cde4585026950da0e8543746a6d00e535dd895e380f7d5757",
          "sha256": "b81f569ef64ca81d62f59efb3fd613dcc39f072de27944ccc47d002418934096",
          "sha1": "af46801abe0110436ebcc8290984d213845dfa7a",
          "md5": "f559c1d3bb74263eb43c3e9531c714f5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a39-0.8.6-javadoc.jar",
          "size": 109676,
          "sha512": "f08a5c21e814132b6e58aff7ad183f6632b1498a2f70079700775fc4bf3d4294aed6ad9283492989606670488313687cbcc316cee86f12a99ef76715aed1f8b0",
          "sha256": "983ea98a3e98ac9f5e1ee11f8de750d8986522a939efc3c6eb74a0b6c8e2b49c",
          "sha1": "5122e3156cd94a9989427019b1fa0523305dfecc",
          "md5": "ce3dc3b3a698da35e4830d9aefd15704"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a39-0.8.6-sources.jar",
          "size": 1769,
          "sha512": "7c65b6c706464018f4ef4af4ead5ea618dcf8e8e4a50e810c858b721599de26edfc470617fceeff239eb59aebb9f3ec487eeaceb41290bfa0c4b3d069a6472c3",
          "sha256": "328e82a2f6a9abc3a98c1cbf82ad9216514fd0125015adcbc5fe52912fa052e3",
          "sha1": "f2704d0ca1bc6fd23c9a3c897c9e7279e2ac5777",
          "md5": "411cbb512f775cf3984b6d7a8231b525"
        }
      ]
    }
  ]
}
