{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bcs-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c-android",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-android-0.1.3.aar",
          "url": "ble-service-bcs-android-0.1.3.aar",
          "size": 1206,
          "sha512": "264800f30ea00f6363fc1db15aee118ec455e14c918adab4e942e77875b533ef0f49fe950d3f522430074f0638e26504feffa0c0d4196be7879944921bab5639",
          "sha256": "761c217e21a64584e2f308f21ebcd815b5d06b8fdbd4b1ac689052849f221b72",
          "sha1": "e85cd51fd7e6075abe40bd2a54186dad43afe18f",
          "md5": "b5469f71b353d047e49b3df272540de7"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c-android",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-android-0.1.3.aar",
          "url": "ble-service-bcs-android-0.1.3.aar",
          "size": 1206,
          "sha512": "264800f30ea00f6363fc1db15aee118ec455e14c918adab4e942e77875b533ef0f49fe950d3f522430074f0638e26504feffa0c0d4196be7879944921bab5639",
          "sha256": "761c217e21a64584e2f308f21ebcd815b5d06b8fdbd4b1ac689052849f221b72",
          "sha1": "e85cd51fd7e6075abe40bd2a54186dad43afe18f",
          "md5": "b5469f71b353d047e49b3df272540de7"
        }
      ]
    }
  ]
}
