{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac7-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac7",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac7-android-0.4.6.aar",
          "url": "ble-characteristic-u2ac7-android-0.4.6.aar",
          "size": 3053,
          "sha512": "9fcca44a160ff9a7a35357054f3eed24ddad7ccc76d3d88b70c3e37f0a9941c216434913d76dbf98c893dbc067bc85f9212eac924ae0f21b8ebaeaec6c2ec9c5",
          "sha256": "eaae66c049eed555579c51f5ad4b0d0eacd17b95de4687032490159d0be484e2",
          "sha1": "2e8fa9fab44f6204999d500a9e08c9f4a751e45a",
          "md5": "eb6e4a393c30870b665328787811f8ef"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac7",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac7-android-0.4.6.aar",
          "url": "ble-characteristic-u2ac7-android-0.4.6.aar",
          "size": 3053,
          "sha512": "9fcca44a160ff9a7a35357054f3eed24ddad7ccc76d3d88b70c3e37f0a9941c216434913d76dbf98c893dbc067bc85f9212eac924ae0f21b8ebaeaec6c2ec9c5",
          "sha256": "eaae66c049eed555579c51f5ad4b0d0eacd17b95de4687032490159d0be484e2",
          "sha1": "2e8fa9fab44f6204999d500a9e08c9f4a751e45a",
          "md5": "eb6e4a393c30870b665328787811f8ef"
        }
      ]
    }
  ]
}
