{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a84-android",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a84",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a84-android-0.6.1.aar",
          "url": "ble-characteristic-u2a84-android-0.6.1.aar",
          "size": 3115,
          "sha512": "855f3e4cf2476360447c8c3bf1130f7b0fd4f9497eca739d026e860a29fca2ca73375eb0374ad4587eab6729d0138acc9788c88e2a379ae905bee86d96b8d2d8",
          "sha256": "b6b14db4c7ff82975522fadc45332331a7ad96b7c0566265a36bbd69800598eb",
          "sha1": "36f553b1d8a5af8b7a3b7e1de3fb7505fb1d0a20",
          "md5": "b17b6419a8df578f3761e6b87c62f000"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a84",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a84-android-0.6.1.aar",
          "url": "ble-characteristic-u2a84-android-0.6.1.aar",
          "size": 3115,
          "sha512": "855f3e4cf2476360447c8c3bf1130f7b0fd4f9497eca739d026e860a29fca2ca73375eb0374ad4587eab6729d0138acc9788c88e2a379ae905bee86d96b8d2d8",
          "sha256": "b6b14db4c7ff82975522fadc45332331a7ad96b7c0566265a36bbd69800598eb",
          "sha1": "36f553b1d8a5af8b7a3b7e1de3fb7505fb1d0a20",
          "md5": "b17b6419a8df578f3761e6b87c62f000"
        }
      ]
    }
  ]
}
