{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a48-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "md2hzulcvrbjbp3omyeiu4n5fi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.3.aar",
          "url": "ble-characteristic-u2a48-android-0.2.3.aar",
          "size": 3010,
          "sha512": "7ec1fd9eb6d4210945e85fa0072f183b6c4e5f1e1b55807dd35b4fd32a4fd0cadbaed8ca16fcff037f3a98fdaf090b73b496ad16c39ef9ad9b8388e575e05409",
          "sha256": "64840a71e6e222f8f09966119f6f9a52ded93d49009011756f0c8b1da2ef3421",
          "sha1": "57fba086f2e73ac19ce0942b3e710ebe4826446c",
          "md5": "8a366f26a4b7d231d9a8bf9a5a6b4aed"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.3.aar",
          "url": "ble-characteristic-u2a48-android-0.2.3.aar",
          "size": 3010,
          "sha512": "7ec1fd9eb6d4210945e85fa0072f183b6c4e5f1e1b55807dd35b4fd32a4fd0cadbaed8ca16fcff037f3a98fdaf090b73b496ad16c39ef9ad9b8388e575e05409",
          "sha256": "64840a71e6e222f8f09966119f6f9a52ded93d49009011756f0c8b1da2ef3421",
          "sha1": "57fba086f2e73ac19ce0942b3e710ebe4826446c",
          "md5": "8a366f26a4b7d231d9a8bf9a5a6b4aed"
        }
      ]
    }
  ]
}
