{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a78",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-0.8.7.jar",
          "url": "ble-characteristic-u2a78-0.8.7.jar",
          "size": 1845,
          "sha512": "c91ca5056538d05b5891bca99534dc4c8682fe5205d97dde35f97b9c427118a862b2316a1ba23570862f41c89ead656b787b8fcae4a1391eb3007213e3d67381",
          "sha256": "c1b1e5f8f2c07bc576f09ab683d901d0206763db41338a4670b9ba7bda283f0c",
          "sha1": "dbd5d0e9606e2e232a9d61f10bea438159bbaaf9",
          "md5": "a14a6736b2640e872786cf8e0eb84ee2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-0.8.7.jar",
          "url": "ble-characteristic-u2a78-0.8.7.jar",
          "size": 1845,
          "sha512": "c91ca5056538d05b5891bca99534dc4c8682fe5205d97dde35f97b9c427118a862b2316a1ba23570862f41c89ead656b787b8fcae4a1391eb3007213e3d67381",
          "sha256": "c1b1e5f8f2c07bc576f09ab683d901d0206763db41338a4670b9ba7bda283f0c",
          "sha1": "dbd5d0e9606e2e232a9d61f10bea438159bbaaf9",
          "md5": "a14a6736b2640e872786cf8e0eb84ee2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a78-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a78-0.8.7-javadoc.jar",
          "size": 109291,
          "sha512": "9ca6cd2d57ea918d24d3a66a14581486820e7775034927f61aad16da1b8033aa064f36edf6d3f9fa9b122622f1d2dd06047336f8f5ee64ede31eaf32f70fbe5d",
          "sha256": "f2a8b512cf0cc81eddede56e44c35512591b6884818b20931b262b30fab9dcc9",
          "sha1": "e50de40412119f7231d23a142137f5c076f947e2",
          "md5": "33a0f0bd7c624126d512391950397603"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a78-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a78-0.8.7-sources.jar",
          "size": 1666,
          "sha512": "755da5d0bf126d7e9419672ba76bc5dce69d40c815ee587015c83049885c58569b7a149917af5f43175f9e0d4ac1a25609ad116fcf24f80b882a2c4962497313",
          "sha256": "bb71fcaf50aa4da3baac95e334ca3c66bafb3e616fe8fd87efbc4b56ee2f8e11",
          "sha1": "fab59ce98a0feb6e1bedf052152c111a10188ee0",
          "md5": "8a11ab18bee5f7f885c7cb7a42d42da4"
        }
      ]
    }
  ]
}
