{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a39",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.14.jar",
          "url": "ble-characteristic-u2a39-0.8.14.jar",
          "size": 1885,
          "sha512": "940f21b672869f34e8a4dc5e514413dfe1316359ab18e920a63e8a36f7ddf4c6708f35722d9e2c698cac2a26e65312ae0e7849bc1f541e7b57e4e12bff4df790",
          "sha256": "bf73f2ed960957bc1eaa573b977d9d99034b1ae5fcd1db93804b698ab09dd65c",
          "sha1": "d82a2477c9d75a87544c5cd83acae28f2d14cff1",
          "md5": "0f4185adcca3f450e073b34b4622e101"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.14.jar",
          "url": "ble-characteristic-u2a39-0.8.14.jar",
          "size": 1885,
          "sha512": "940f21b672869f34e8a4dc5e514413dfe1316359ab18e920a63e8a36f7ddf4c6708f35722d9e2c698cac2a26e65312ae0e7849bc1f541e7b57e4e12bff4df790",
          "sha256": "bf73f2ed960957bc1eaa573b977d9d99034b1ae5fcd1db93804b698ab09dd65c",
          "sha1": "d82a2477c9d75a87544c5cd83acae28f2d14cff1",
          "md5": "0f4185adcca3f450e073b34b4622e101"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2a39-0.8.14-javadoc.jar",
          "size": 88592,
          "sha512": "275580d5d0bd7782bfe2656769dc8710bc7dc5b89f4baea46c2c286a565af453eb45fac6f82a59b4ed0929f48d2e51f9cebab78430a302ccadbae4519faad589",
          "sha256": "3c15d9ae6e2c38d84bbe5cfe0d4ad001feebb0fbfbedcc0fe56298edc9745d66",
          "sha1": "7641b5fff9ee59681096d81a3c7d93b43be10b01",
          "md5": "6b23963f3e5ae5c6856902a3447bd76a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a39-0.8.14-sources.jar",
          "url": "ble-characteristic-u2a39-0.8.14-sources.jar",
          "size": 1769,
          "sha512": "149293c8ab00385855b08a5c180290746af9241808e664ca975b2a241add8d0d5c88bb5a98128fc96cef776d79e29e3ecf9c9a4d3f2cdfb93aaee7d2f6e8d8c0",
          "sha256": "fb558240f4ab460ddb1e0865c70e6ba0b49449a19239d84c2795fbeb3d86313a",
          "sha1": "03558f0787632fab33f20309ab9e6db8bd6558c3",
          "md5": "683f38e9017d507766112afdf17c6f24"
        }
      ]
    }
  ]
}
