{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-protocol",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-protocol-0.8.7.jar",
          "url": "ble-core-constants-protocol-0.8.7.jar",
          "size": 2874,
          "sha512": "4169ffbf452748edbb652476e0da02bfe1ae94ff18956c5f56d20e5c0771001383f0ceaa37a69246ec4e6c8404e23e6c1b3181744438f3f9072768ca6dae7577",
          "sha256": "0e0385ea3732d5ddb16a3f296e7c8625412bf1adeaba7c1ff4657e6f4ee190cd",
          "sha1": "b2833252c0d634b19c9e0e5dc2367276c2d1320b",
          "md5": "9915acf4a62ce5e6961b78175c8394aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-protocol-0.8.7.jar",
          "url": "ble-core-constants-protocol-0.8.7.jar",
          "size": 2874,
          "sha512": "4169ffbf452748edbb652476e0da02bfe1ae94ff18956c5f56d20e5c0771001383f0ceaa37a69246ec4e6c8404e23e6c1b3181744438f3f9072768ca6dae7577",
          "sha256": "0e0385ea3732d5ddb16a3f296e7c8625412bf1adeaba7c1ff4657e6f4ee190cd",
          "sha1": "b2833252c0d634b19c9e0e5dc2367276c2d1320b",
          "md5": "9915acf4a62ce5e6961b78175c8394aa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-protocol-0.8.7-javadoc.jar",
          "url": "ble-core-constants-protocol-0.8.7-javadoc.jar",
          "size": 106383,
          "sha512": "dcb64049708729c415290743919f29016232e68816f7f8d47702173fb0aa7316fa465b836cd932c800f818722a8caccace2b47aacfdea66d60a3d155e393d4d4",
          "sha256": "aa51ba7894f4c72aad7d6e1663bd51c68fe62ff52f1d0636737c864113bd95f3",
          "sha1": "6ba8bf1318a7d816ac26b9d90da57b4db0729ce6",
          "md5": "691489a0e967c965004b92634cb68f4c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-protocol-0.8.7-sources.jar",
          "url": "ble-core-constants-protocol-0.8.7-sources.jar",
          "size": 1455,
          "sha512": "f14c3d3f17cfa6c34f6e20f6e6fdf0f513db5f81782b51c31edb4e1113158603a21a0975c3178ebb9a76b1d191f0f5e9ba62cf094c19315adefe49063194780f",
          "sha256": "e05dfa7f0822d6f23c40d98cf39d6814d4e241d3846c9f761aa2e673f4cfab13",
          "sha1": "6d06b56f94c05295f855cec959e08cdbb9aaf309",
          "md5": "c62a616fbfeab64d865df24518d39d6f"
        }
      ]
    }
  ]
}
