{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc2",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc2-0.5.1.jar",
          "url": "ble-characteristic-u2bc2-0.5.1.jar",
          "size": 1458,
          "sha512": "d343518d25cf3dbb0a76db786b99bddc7a384a4de859c64ca901b2c25dd0866e451b3a01195cdb6ba5e6fdca6d9cffb6f4eee13a8c4fe03593ddb576a5710922",
          "sha256": "2dd012fbe26b9461d9d9efdd002c91f353726e2eb5368cf9928cac500b274519",
          "sha1": "4de43d6b7b9d18250648d39bf361e2f2fc220ac7",
          "md5": "b4c9bfa0b433490695af5e516a1582e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc2-0.5.1.jar",
          "url": "ble-characteristic-u2bc2-0.5.1.jar",
          "size": 1458,
          "sha512": "d343518d25cf3dbb0a76db786b99bddc7a384a4de859c64ca901b2c25dd0866e451b3a01195cdb6ba5e6fdca6d9cffb6f4eee13a8c4fe03593ddb576a5710922",
          "sha256": "2dd012fbe26b9461d9d9efdd002c91f353726e2eb5368cf9928cac500b274519",
          "sha1": "4de43d6b7b9d18250648d39bf361e2f2fc220ac7",
          "md5": "b4c9bfa0b433490695af5e516a1582e2"
        }
      ]
    }
  ]
}
