{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab9-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab9",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-android-0.8.12.aar",
          "url": "ble-characteristic-u2ab9-android-0.8.12.aar",
          "size": 3214,
          "sha512": "a8d41d8845ae8c9cabb361e09e855490e8224c3a102ee3c3c08d51c6d669256294f3908af38eab1e0ddfc43ed69a49b26e806be7287ebe41d8ea5dafb036b9d5",
          "sha256": "c43410e9b90e48808670127581193b51b31a0074bdafb30015fb7bb2798e608b",
          "sha1": "2f22960e94284c053337e2a53c7f4f728a488eb9",
          "md5": "9b2d8c0fce728297a2a57388d8b2fe79"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab9",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab9-android-0.8.12.aar",
          "url": "ble-characteristic-u2ab9-android-0.8.12.aar",
          "size": 3214,
          "sha512": "a8d41d8845ae8c9cabb361e09e855490e8224c3a102ee3c3c08d51c6d669256294f3908af38eab1e0ddfc43ed69a49b26e806be7287ebe41d8ea5dafb036b9d5",
          "sha256": "c43410e9b90e48808670127581193b51b31a0074bdafb30015fb7bb2798e608b",
          "sha1": "2f22960e94284c053337e2a53c7f4f728a488eb9",
          "md5": "9b2d8c0fce728297a2a57388d8b2fe79"
        }
      ]
    }
  ]
}
