{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a01-android",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-android-0.1.9.aar",
          "url": "ble-characteristic-u2a01-android-0.1.9.aar",
          "size": 3053,
          "sha512": "bed97e3f3e295792a37bb767138c12ad188c9678146cfda263d66cb219333c743853ad597ec721472a94011d5417e4b8c69912d03909b208a38e535cd23a6dc2",
          "sha256": "17a254870f7dbc45761acbcf209b2e5d6ef39c2f2b5ebdc6bd6f07fac48be952",
          "sha1": "f9cbea77e73150fa0b434d9dad202538370645a1",
          "md5": "1dffbd8e521a16bc3f8176568c8c75f0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a01-android-0.1.9.aar",
          "url": "ble-characteristic-u2a01-android-0.1.9.aar",
          "size": 3053,
          "sha512": "bed97e3f3e295792a37bb767138c12ad188c9678146cfda263d66cb219333c743853ad597ec721472a94011d5417e4b8c69912d03909b208a38e535cd23a6dc2",
          "sha256": "17a254870f7dbc45761acbcf209b2e5d6ef39c2f2b5ebdc6bd6f07fac48be952",
          "sha1": "f9cbea77e73150fa0b434d9dad202538370645a1",
          "md5": "1dffbd8e521a16bc3f8176568c8c75f0"
        }
      ]
    }
  ]
}
