{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa3",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.6.jar",
          "url": "ble-characteristic-u2aa3-0.8.6.jar",
          "size": 2258,
          "sha512": "2693f23ffb441b62da5188beece5eec3cc5a02e8c286d6af13d99715f7d1089acfc35d2fe4db1c6d9bbb96fa1f8ec6f7384b303d204048d90cad41b806447d23",
          "sha256": "a49b553df53366f3c176ad41783cdef823adf0b328fc6d9547deb34811f484de",
          "sha1": "387066e1edcf630911f0bcb0a770552531b7c4a3",
          "md5": "6e90bad03ad2177a6d9a91c505857cad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.6.jar",
          "url": "ble-characteristic-u2aa3-0.8.6.jar",
          "size": 2258,
          "sha512": "2693f23ffb441b62da5188beece5eec3cc5a02e8c286d6af13d99715f7d1089acfc35d2fe4db1c6d9bbb96fa1f8ec6f7384b303d204048d90cad41b806447d23",
          "sha256": "a49b553df53366f3c176ad41783cdef823adf0b328fc6d9547deb34811f484de",
          "sha1": "387066e1edcf630911f0bcb0a770552531b7c4a3",
          "md5": "6e90bad03ad2177a6d9a91c505857cad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2aa3-0.8.6-javadoc.jar",
          "size": 111276,
          "sha512": "3eecc0a3900e01a081896945371527f39ee55728ea3aba62c362a1a076befd66fa17aa4152747b28bb98822f0cbf9a24be9aa0b045ad409921057ad9ef310c2f",
          "sha256": "7cb8d20b3f978ffe2804de358068103b8f96a674259eb17bf24bb6f4a5757d9e",
          "sha1": "1134983c91e438ba991f671c093f495b4f5ea87b",
          "md5": "a8e11e15fc3efc2a9ddb262064b8f60f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa3-0.8.6-sources.jar",
          "url": "ble-characteristic-u2aa3-0.8.6-sources.jar",
          "size": 2145,
          "sha512": "2941c16d4a6214c775f0afcc053878741504b4d8c919ce51bccbe1b2289cec6f1eb376950c713bae06af33c4bc9700991ba0f79bd528651808385fabb59ad95e",
          "sha256": "feac92fe3461611b3ae5797afcb979e4b5539ee098ee1863edddfc2289ce0700",
          "sha1": "a3830e92b58877cd3a45a61879852949dc2757d0",
          "md5": "200b0f8afaa8e3f23d07d9ce013a4ef4"
        }
      ]
    }
  ]
}
