{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "imnihwqv65eu7lrkazou3zhih4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.1.3.aar",
          "url": "ble-profile-peripheral-android-0.1.3.aar",
          "size": 2115,
          "sha512": "19acb86c19b6855c85ab32e8f72a47fb69575ed30ed9694556998bedceb2a537397f05d0c0f9313a40c6542f941000b772bdff85b44b9824814872d7be500440",
          "sha256": "562e354e5176ce94868e3f5c3c9f9d474e5bd5497ffcbf3e3a92694732242ff8",
          "sha1": "ea1ff9c2931511a73dd38f522ee0d3bbbe9ab88d",
          "md5": "21628769d30904bb3fd0806560cc21ef"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.1.3.aar",
          "url": "ble-profile-peripheral-android-0.1.3.aar",
          "size": 2115,
          "sha512": "19acb86c19b6855c85ab32e8f72a47fb69575ed30ed9694556998bedceb2a537397f05d0c0f9313a40c6542f941000b772bdff85b44b9824814872d7be500440",
          "sha256": "562e354e5176ce94868e3f5c3c9f9d474e5bd5497ffcbf3e3a92694732242ff8",
          "sha1": "ea1ff9c2931511a73dd38f522ee0d3bbbe9ab88d",
          "md5": "21628769d30904bb3fd0806560cc21ef"
        }
      ]
    }
  ]
}
