{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc4",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.6.jar",
          "url": "ble-characteristic-u2bc4-0.8.6.jar",
          "size": 1435,
          "sha512": "dafc1f199d6ef94c1884579ba642a0a11c69395ca46ed50585cf1ef296b737bbc3205e642d2bbdc737ccbd0b5241775b2b03689b2a4523b924980242943729c3",
          "sha256": "0de422164b7fedfe1dd6af7e66c060e2ec50bb7ba96174a79952894e08694173",
          "sha1": "1d8fab64f7e62f77bec3042b965db2b93d18c6d8",
          "md5": "7acb36bbe1e03415cb988f205df62693"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.6.jar",
          "url": "ble-characteristic-u2bc4-0.8.6.jar",
          "size": 1435,
          "sha512": "dafc1f199d6ef94c1884579ba642a0a11c69395ca46ed50585cf1ef296b737bbc3205e642d2bbdc737ccbd0b5241775b2b03689b2a4523b924980242943729c3",
          "sha256": "0de422164b7fedfe1dd6af7e66c060e2ec50bb7ba96174a79952894e08694173",
          "sha1": "1d8fab64f7e62f77bec3042b965db2b93d18c6d8",
          "md5": "7acb36bbe1e03415cb988f205df62693"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2bc4-0.8.6-javadoc.jar",
          "size": 107092,
          "sha512": "ad61c0e9eb28ce790d84fef4036e12cfcc575f191d5ad97b876f0e2388fe01fc708b87060446663e7592e4a8fdb3391fdc55a914069195c1ad89d0564910d995",
          "sha256": "0a5a23a43f86fa28ce0a1af2b3b6d500f30a3690b03cc676d5d3510bc9b51006",
          "sha1": "1e4fd3c02afec23e1f64151c8c0bcccbd8eca2ec",
          "md5": "a19e4cf428c8af8cc39e2435540adca9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc4-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bc4-0.8.6-sources.jar",
          "size": 1412,
          "sha512": "bbd7c7390f11345ebd844be56b96d77df728e7905847620a09fc4e55bc0df7b3899fccda8749f8ca3f93a37c0cbd5930c92171a067c9ee2bbfc77cc4d348f3e0",
          "sha256": "6c41d0650b94a47d484d1ec2ce9536c6d7e1632e743437892dbd93deffd212c2",
          "sha1": "722b3ff7f5a747027a0f69e2b299f6415df09ca2",
          "md5": "a69d5510ebbc080f2faa851d14604069"
        }
      ]
    }
  ]
}
