{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-lnp-central-android",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "onm7oav7y5gufewzovq4jjg3iy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-central-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-lnp-central-android-0.1.9.aar",
          "url": "ble-profile-lnp-central-android-0.1.9.aar",
          "size": 6698,
          "sha512": "13ff47c170ed42ef56e930f121bb2cfa46a919089afd079818cdf4bb2667c7dc8187ed6ad5de3d6719208cc020abd72f0007653e7f63c353701c222dfcdc0156",
          "sha256": "2b4bba27ed00cf6c6e8b671d44407b18a097ea50395cae8c6aac7c1efefb0669",
          "sha1": "9e2329a54df547fea8836348f8fe58413e0959fa",
          "md5": "2c9515503bee9d62ec65d4cf10a19293"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-central-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-lnp-central-android-0.1.9.aar",
          "url": "ble-profile-lnp-central-android-0.1.9.aar",
          "size": 6698,
          "sha512": "13ff47c170ed42ef56e930f121bb2cfa46a919089afd079818cdf4bb2667c7dc8187ed6ad5de3d6719208cc020abd72f0007653e7f63c353701c222dfcdc0156",
          "sha256": "2b4bba27ed00cf6c6e8b671d44407b18a097ea50395cae8c6aac7c1efefb0669",
          "sha1": "9e2329a54df547fea8836348f8fe58413e0959fa",
          "md5": "2c9515503bee9d62ec65d4cf10a19293"
        }
      ]
    }
  ]
}
