{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a31-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a31",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a31-android-0.2.4.aar",
          "url": "ble-characteristic-u2a31-android-0.2.4.aar",
          "size": 3080,
          "sha512": "39677f639f2781136758226e1a3fd7079615c418832535367cc25049fcebae7d9d54212595ccda392790cc6e845dce2e4096abd7c2bd0d9fcaeec4469b88b3f6",
          "sha256": "bc1795a84397e386d945d9a71f01312b788c65ab7238cd46cf52b63f3e2c730a",
          "sha1": "557aec25c5173d419aaff7e3992af7db7a7a90be",
          "md5": "f40c16cd081164f22bb429da5a14f89b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a31",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a31-android-0.2.4.aar",
          "url": "ble-characteristic-u2a31-android-0.2.4.aar",
          "size": 3080,
          "sha512": "39677f639f2781136758226e1a3fd7079615c418832535367cc25049fcebae7d9d54212595ccda392790cc6e845dce2e4096abd7c2bd0d9fcaeec4469b88b3f6",
          "sha256": "bc1795a84397e386d945d9a71f01312b788c65ab7238cd46cf52b63f3e2c730a",
          "sha1": "557aec25c5173d419aaff7e3992af7db7a7a90be",
          "md5": "f40c16cd081164f22bb429da5a14f89b"
        }
      ]
    }
  ]
}
