{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.4.aar",
          "url": "ble-characteristic-u2a04-android-0.2.4.aar",
          "size": 3242,
          "sha512": "313ff1c4223ca8b4527931d427a288f0574bcdd889c7bd80e6790bc6a0b4dcc78287a13ec9d4fcbd4a0f5d3a2827907a7d09b425d0f2d8b46e5c05a117f7c30f",
          "sha256": "8a2528db63c68bdbe2bd1562138bffe210a9eef7ad71cf5c281d35e07d27da2a",
          "sha1": "f3ad3f3414d1c30a43a537991b56d6806f0f7c57",
          "md5": "cb18ca63ec5d9fd2814803a34e3007a6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.4.aar",
          "url": "ble-characteristic-u2a04-android-0.2.4.aar",
          "size": 3242,
          "sha512": "313ff1c4223ca8b4527931d427a288f0574bcdd889c7bd80e6790bc6a0b4dcc78287a13ec9d4fcbd4a0f5d3a2827907a7d09b425d0f2d8b46e5c05a117f7c30f",
          "sha256": "8a2528db63c68bdbe2bd1562138bffe210a9eef7ad71cf5c281d35e07d27da2a",
          "sha1": "f3ad3f3414d1c30a43a537991b56d6806f0f7c57",
          "md5": "cb18ca63ec5d9fd2814803a34e3007a6"
        }
      ]
    }
  ]
}
