{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.4.aar",
          "url": "ble-characteristic-u2a04-android-0.2.4.aar",
          "size": 3244,
          "sha512": "20516b845e7278dc1e21711fe17e30f49fc9170625055d5fc37f475b7efbfbbb318c7b6919cf51df5be249060b7b764bee1586b08317664b1fd1ddad936428bb",
          "sha256": "6dac4766c0b1817bfd7dbb2b305c66ffbf3126d9c318b83c4e438e9cb30ce695",
          "sha1": "bd790cc9f620661f410fe228b92b0dba1737cbfc",
          "md5": "b53096398b6f340b7162d4135fe5296f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.4.aar",
          "url": "ble-characteristic-u2a04-android-0.2.4.aar",
          "size": 3244,
          "sha512": "20516b845e7278dc1e21711fe17e30f49fc9170625055d5fc37f475b7efbfbbb318c7b6919cf51df5be249060b7b764bee1586b08317664b1fd1ddad936428bb",
          "sha256": "6dac4766c0b1817bfd7dbb2b305c66ffbf3126d9c318b83c4e438e9cb30ce695",
          "sha1": "bd790cc9f620661f410fe228b92b0dba1737cbfc",
          "md5": "b53096398b6f340b7162d4135fe5296f"
        }
      ]
    }
  ]
}
