{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd6",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd6-0.8.7.jar",
          "url": "ble-characteristic-u2bd6-0.8.7.jar",
          "size": 1951,
          "sha512": "4afc4f940f8ff01feeb9d5756014e5572d899f88348a3a8d0728c4f3555c317e03c3dee1413cf526b0ca4ae081cca393134dc6f77b7c418db1ff22842fe6f9a7",
          "sha256": "3432a79e8a72b6793293032b33a84549627834d20bce5cb740da540aac103825",
          "sha1": "2bacd58362d658d02127d314bfc8721511acf9e8",
          "md5": "7f3e95572a633762643278a82552c64e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd6-0.8.7.jar",
          "url": "ble-characteristic-u2bd6-0.8.7.jar",
          "size": 1951,
          "sha512": "4afc4f940f8ff01feeb9d5756014e5572d899f88348a3a8d0728c4f3555c317e03c3dee1413cf526b0ca4ae081cca393134dc6f77b7c418db1ff22842fe6f9a7",
          "sha256": "3432a79e8a72b6793293032b33a84549627834d20bce5cb740da540aac103825",
          "sha1": "2bacd58362d658d02127d314bfc8721511acf9e8",
          "md5": "7f3e95572a633762643278a82552c64e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd6-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bd6-0.8.7-javadoc.jar",
          "size": 108033,
          "sha512": "550143fe24c8a102b9b3214875d9e9ad80e5b37f5998f7e0d49b87f3f2b0499444f27a005998379b2fb098bbf7d54025df93f942644b154e1e8527f767e40435",
          "sha256": "973b1228f555c98b0b3075aa15ab3fe150a8157c4d6019d51bb72eca35bdc3ae",
          "sha1": "e8098ccb4f411a598b9fca7915f5740e0f337488",
          "md5": "8fe014b2398a46798e183af5dbc30360"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd6-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bd6-0.8.7-sources.jar",
          "size": 1979,
          "sha512": "3201704cee32b51f23ac71dd6b2989b6090dc828eb9c7a5eebb8a6bb2f6f38471b9ecad4f26e2ab7f42d64847cde7e803c063ddfbe772c5ffe3c58b84b683efc",
          "sha256": "69699e2063407c206bfa48edbe905381c59b42bc04a74d06c408350c38f35ff3",
          "sha1": "eefba4dd86cd868722be546306495e75ac007a17",
          "md5": "fec09b2ab2cce87dd3fdd1fb1297cd79"
        }
      ]
    }
  ]
}
