{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a54-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a54",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-android-0.1.1.aar",
          "url": "ble-characteristic-u2a54-android-0.1.1.aar",
          "size": 2857,
          "sha512": "0fae6121e39d73776699761fccb6a6227231fa4d6e8cb2048fba571d085178edc55ac8ea47f61ec3f5db7bcf4d99b9307e70912af3e4aeab2c9e8d994fada46c",
          "sha256": "f4ce03fb1a73bb6ad6238b37298f357e71ae910cb4a9e19d4f6466cd72d98055",
          "sha1": "3aefda175a8b5cb71611d856b272700d705a90e1",
          "md5": "1954219ab063b540d45098dd2d6f0ebe"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a54",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-android-0.1.1.aar",
          "url": "ble-characteristic-u2a54-android-0.1.1.aar",
          "size": 2857,
          "sha512": "0fae6121e39d73776699761fccb6a6227231fa4d6e8cb2048fba571d085178edc55ac8ea47f61ec3f5db7bcf4d99b9307e70912af3e4aeab2c9e8d994fada46c",
          "sha256": "f4ce03fb1a73bb6ad6238b37298f357e71ae910cb4a9e19d4f6466cd72d98055",
          "sha1": "3aefda175a8b5cb71611d856b272700d705a90e1",
          "md5": "1954219ab063b540d45098dd2d6f0ebe"
        }
      ]
    }
  ]
}
