{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aec",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aec-0.8.12.jar",
          "url": "ble-characteristic-u2aec-0.8.12.jar",
          "size": 1921,
          "sha512": "151755b040a766b9bd32d028092dcb2ec0abfd642348e1575fc53c8f397be3b48b70c0cc1b9fba7a0bf7dde77f5467efc93b30884165453c2255da8c7d651063",
          "sha256": "4d04d5facfb3cfbb1f5611615c597ad5ddd2540307c90ca192895d9d105bf204",
          "sha1": "8e0820c1b5aee12c6c963f754fa9809b98c41149",
          "md5": "48f38b70f58d982a3f4255b88d55a9c6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aec-0.8.12.jar",
          "url": "ble-characteristic-u2aec-0.8.12.jar",
          "size": 1921,
          "sha512": "151755b040a766b9bd32d028092dcb2ec0abfd642348e1575fc53c8f397be3b48b70c0cc1b9fba7a0bf7dde77f5467efc93b30884165453c2255da8c7d651063",
          "sha256": "4d04d5facfb3cfbb1f5611615c597ad5ddd2540307c90ca192895d9d105bf204",
          "sha1": "8e0820c1b5aee12c6c963f754fa9809b98c41149",
          "md5": "48f38b70f58d982a3f4255b88d55a9c6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aec-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2aec-0.8.12-javadoc.jar",
          "size": 109740,
          "sha512": "ece79f41e224de2a2f1cb23101cd6af512020930748124b1dc00082ef3aec910e09f7b0e044e9668a250574aa83d82401b582cb1b36b82cbfcf89cc0d4969d71",
          "sha256": "24f86e3a3890dc3fd371a85f7dc9d5ecd6e562e836f991d440a90d2466d2d251",
          "sha1": "d49b86a3014cd116ee3131c175074f2ae7436aba",
          "md5": "ee8fb595c4c37d3ce3416fe60dc03633"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aec-0.8.12-sources.jar",
          "url": "ble-characteristic-u2aec-0.8.12-sources.jar",
          "size": 1789,
          "sha512": "c431f6a7f9297677d1ecef54b3b8c04ecaa1d7460c738a58aa446261407c63d72b070c81d459eec45c3a2ea64e05113bf8fb75cba6e24d74bc4a4d5282e45118",
          "sha256": "ef3c6b97489f0b4c2e67c6bf1ab5106db4e3ab9c9446605c753f5cf6697faf4d",
          "sha1": "6ae5d1f7542cd48fb48d101e356b2ccdb26bc9ce",
          "md5": "6713d9ddb0193525ca00e642690e9093"
        }
      ]
    }
  ]
}
