{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3d-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3d-android-0.8.6.aar",
          "url": "ble-characteristic-u2b3d-android-0.8.6.aar",
          "size": 3092,
          "sha512": "833b525fa50a3f4987f1c4a5e995f68ab6668659b95f428e9d59ab33456c9754d1832de7cdd71a05103261d5d7d7af4a495fc7028ed43f4cc6ac38b0b8e8c61d",
          "sha256": "8e02ec365c4794a84de50af158fb9356e51b0568dbe6bdf3c189ebe00daf945d",
          "sha1": "a4dad4d03bdee634152eac2d9f0afd52a73967af",
          "md5": "636fef54b92955dc179720d320e0239f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3d-android-0.8.6.aar",
          "url": "ble-characteristic-u2b3d-android-0.8.6.aar",
          "size": 3092,
          "sha512": "833b525fa50a3f4987f1c4a5e995f68ab6668659b95f428e9d59ab33456c9754d1832de7cdd71a05103261d5d7d7af4a495fc7028ed43f4cc6ac38b0b8e8c61d",
          "sha256": "8e02ec365c4794a84de50af158fb9356e51b0568dbe6bdf3c189ebe00daf945d",
          "sha1": "a4dad4d03bdee634152eac2d9f0afd52a73967af",
          "md5": "636fef54b92955dc179720d320e0239f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3d-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b3d-android-0.8.6-sources.jar",
          "size": 2202,
          "sha512": "de6174fad337a2c3fe648b7079c5023a5a31642014be497b3ea8ec88bcc6179d3b38f2919a979ad049a847b0f1e2f58b9f538227057c4be7a2aeb96a7241957d",
          "sha256": "1a080b65db14acce35e13f40dbfe06fa15931f4fe427f6cbb12ba8ddffbe89ac",
          "sha1": "d0410c5476569502287690bec15ebf64a41164b6",
          "md5": "59e4fcd6092af17f8b938b95a3762c61"
        }
      ]
    }
  ]
}
