{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a54-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fxrmxjl6szatjaovsgygwi5l4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a54",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-android-0.1.4.aar",
          "url": "ble-characteristic-u2a54-android-0.1.4.aar",
          "size": 3032,
          "sha512": "e24474540015713a76fefd670d5d9139465c23c63b83fa9520af1f91fe23b3cfe4f11920cabe6dc367a3bacd0d0b0436c164b5ae0b4f4f56222829a45d307016",
          "sha256": "e0463cbbe6da307e96298e8aeb34521b32a7097cd0a308195095ed89f831fc67",
          "sha1": "e3e87668e25d3a1b3e156df1646f6ff976cfd2df",
          "md5": "fca15c1233e8ff80a8dedd49a153e0e6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a54",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-android-0.1.4.aar",
          "url": "ble-characteristic-u2a54-android-0.1.4.aar",
          "size": 3032,
          "sha512": "e24474540015713a76fefd670d5d9139465c23c63b83fa9520af1f91fe23b3cfe4f11920cabe6dc367a3bacd0d0b0436c164b5ae0b4f4f56222829a45d307016",
          "sha256": "e0463cbbe6da307e96298e8aeb34521b32a7097cd0a308195095ed89f831fc67",
          "sha1": "e3e87668e25d3a1b3e156df1646f6ff976cfd2df",
          "md5": "fca15c1233e8ff80a8dedd49a153e0e6"
        }
      ]
    }
  ]
}
