{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9f-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-android-0.2.4.aar",
          "url": "ble-characteristic-u2a9f-android-0.2.4.aar",
          "size": 3180,
          "sha512": "cb1a8c0bb04875c0bc96d51bd12881fd588b39d71015d8d71d6ccdd031f27dfde10401c69e4a64f74b6f019256575520654feaa8229ab12a9390278c07b6caca",
          "sha256": "925a2fe7192c85061fd8c16e36b7e7692fcb021a52b5ab384655f16afa1db670",
          "sha1": "a7563c3eb3e3d2a991bc128308ad5ecddf3331f8",
          "md5": "2e8d0b41e2d7baf1e060e4d64ff4be0f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9f",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9f-android-0.2.4.aar",
          "url": "ble-characteristic-u2a9f-android-0.2.4.aar",
          "size": 3180,
          "sha512": "cb1a8c0bb04875c0bc96d51bd12881fd588b39d71015d8d71d6ccdd031f27dfde10401c69e4a64f74b6f019256575520654feaa8229ab12a9390278c07b6caca",
          "sha256": "925a2fe7192c85061fd8c16e36b7e7692fcb021a52b5ab384655f16afa1db670",
          "sha1": "a7563c3eb3e3d2a991bc128308ad5ecddf3331f8",
          "md5": "2e8d0b41e2d7baf1e060e4d64ff4be0f"
        }
      ]
    }
  ]
}
