{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b04-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b04",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b04-android-0.8.6.aar",
          "url": "ble-characteristic-u2b04-android-0.8.6.aar",
          "size": 3083,
          "sha512": "564fef6e6e905c6f2fbf129149f20b9d2dd1a34dd20f047c8bea03beefd83d66c527bf3cd1645b632add0914cd81a76cb634830203abf4cca6de3bd0596e427a",
          "sha256": "6a9c0dbf2160ce6d596439d04f56c62d383da140f057a96cf6747838d06b8d5f",
          "sha1": "df93a9232eefa6b9116ccd116769cc7dc414aa26",
          "md5": "bdebf5c59fe774f49046e241c4903cf7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b04",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b04-android-0.8.6.aar",
          "url": "ble-characteristic-u2b04-android-0.8.6.aar",
          "size": 3083,
          "sha512": "564fef6e6e905c6f2fbf129149f20b9d2dd1a34dd20f047c8bea03beefd83d66c527bf3cd1645b632add0914cd81a76cb634830203abf4cca6de3bd0596e427a",
          "sha256": "6a9c0dbf2160ce6d596439d04f56c62d383da140f057a96cf6747838d06b8d5f",
          "sha1": "df93a9232eefa6b9116ccd116769cc7dc414aa26",
          "md5": "bdebf5c59fe774f49046e241c4903cf7"
        }
      ]
    }
  ]
}
