{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b02",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.6.jar",
          "url": "ble-characteristic-u2b02-0.8.6.jar",
          "size": 1919,
          "sha512": "acc72ad7ed047f0bf16154957c702ad93db49a96d7dd49da5e3de4b5a5107d01d72fa1380b3a6e4638b91a3c600bbbffef0a5bf1d128769c353a69eca0d99f6a",
          "sha256": "b58a49d1cb10dc835f4413c4a3f0b0bd20dcf4a2b247d06fc2482e8dbc50f124",
          "sha1": "00db6a530424fc9ebe036c11dacf71569174e8a0",
          "md5": "f08c386f93d8fe3a2f0609b237774c12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.6.jar",
          "url": "ble-characteristic-u2b02-0.8.6.jar",
          "size": 1919,
          "sha512": "acc72ad7ed047f0bf16154957c702ad93db49a96d7dd49da5e3de4b5a5107d01d72fa1380b3a6e4638b91a3c600bbbffef0a5bf1d128769c353a69eca0d99f6a",
          "sha256": "b58a49d1cb10dc835f4413c4a3f0b0bd20dcf4a2b247d06fc2482e8dbc50f124",
          "sha1": "00db6a530424fc9ebe036c11dacf71569174e8a0",
          "md5": "f08c386f93d8fe3a2f0609b237774c12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2b02-0.8.6-javadoc.jar",
          "size": 109721,
          "sha512": "d6ac7c1a30369c24769b68025ec9da8c3a711ee919259db80a59998e74dc587e75046c53790bb824b068cf177601205d079ab06d2edf864010b1e77392ba8707",
          "sha256": "3bdbbf903cf5ac8cb631e3d70ab0e07c2aca57b62aa0c41d5e8c390ce0449b16",
          "sha1": "94366b319cf771847ea208d9fbcf25456b4d267e",
          "md5": "9a7688694ded13018ecf632715dd0290"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b02-0.8.6-sources.jar",
          "size": 1790,
          "sha512": "e58f2ab1bb12345b2872d2a87ec346fc4993929a7c94427e572e299b322e449f14672a02bfd6fc1839ebaa5a3dd66fcc655379d744bfd9ff604e4e08381c26a7",
          "sha256": "96b44be6d777157969656ecdc2642c531ab6a4192c11e17c62a6bb3309f230d3",
          "sha1": "db6ec20504cfcd9f9201a5bb78839e81ec9d2c9c",
          "md5": "00511fb5cd9d999a51f04fbd21b18f4d"
        }
      ]
    }
  ]
}
