{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6c-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ne3pcejtrrhfvmmkle32bx6bti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6c",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6c-android-0.2.5.aar",
          "url": "ble-characteristic-u2a6c-android-0.2.5.aar",
          "size": 3065,
          "sha512": "1493b5df74fbd741a3470589a359a52427635ce764cf032ee00656723b173ea3fc80cf5ca7c92830c8e12db188b692652828d8020b411843301b96267a3e916b",
          "sha256": "9724ce8ff7e3dc396866819bfdf3d022f0e175f5b22c3e7b4d9c23ef8594b53b",
          "sha1": "f7c94786f86e3873f00e23bb7224d4f23af7a96c",
          "md5": "c92972e087638d6b1fe2a45b4599cf35"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6c",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6c-android-0.2.5.aar",
          "url": "ble-characteristic-u2a6c-android-0.2.5.aar",
          "size": 3065,
          "sha512": "1493b5df74fbd741a3470589a359a52427635ce764cf032ee00656723b173ea3fc80cf5ca7c92830c8e12db188b692652828d8020b411843301b96267a3e916b",
          "sha256": "9724ce8ff7e3dc396866819bfdf3d022f0e175f5b22c3e7b4d9c23ef8594b53b",
          "sha1": "f7c94786f86e3873f00e23bb7224d4f23af7a96c",
          "md5": "c92972e087638d6b1fe2a45b4599cf35"
        }
      ]
    }
  ]
}
