{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac6-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac6",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac6-android-0.4.6.aar",
          "url": "ble-characteristic-u2ac6-android-0.4.6.aar",
          "size": 3086,
          "sha512": "7fd73593c11339b436ab246d3533378311001db89a40843f6fa60bdd975b2856385eb940abe0fca38d9a760bc1cd97921fae54e8707876e58c13fd66d5958a83",
          "sha256": "9bec2d32857d9938b694aafde0aa8562df0d19b15078a4033b3a02933df60cfd",
          "sha1": "420b6b7e5c2faffe60096f0bd4befa968f46bc82",
          "md5": "a7853427db8e1e5bfb3faf207b2c845f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac6",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac6-android-0.4.6.aar",
          "url": "ble-characteristic-u2ac6-android-0.4.6.aar",
          "size": 3086,
          "sha512": "7fd73593c11339b436ab246d3533378311001db89a40843f6fa60bdd975b2856385eb940abe0fca38d9a760bc1cd97921fae54e8707876e58c13fd66d5958a83",
          "sha256": "9bec2d32857d9938b694aafde0aa8562df0d19b15078a4033b3a02933df60cfd",
          "sha1": "420b6b7e5c2faffe60096f0bd4befa968f46bc82",
          "md5": "a7853427db8e1e5bfb3faf207b2c845f"
        }
      ]
    }
  ]
}
