{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ans-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48-android",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-android-0.1.0.aar",
          "url": "ble-service-ans-android-0.1.0.aar",
          "size": 1649,
          "sha512": "98ca3c9e26b6d8330995039b167ac48e69fcc1f1dd50fc85a31fa2743d7c110d2b3142fbdb805d8c0f314da1f70a39e7f7f65883d5abbd210073c77517b991e6",
          "sha256": "00cb63c12fca895abfc2612ddd072ac2c1de44ea91a9d9570f2e7c556c876348",
          "sha1": "ad4da97e484e87d109b84d0c40e379bf634ac533",
          "md5": "f0e84735b381b99c209b305959e72ea6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47-android",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48-android",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-android-0.1.0.aar",
          "url": "ble-service-ans-android-0.1.0.aar",
          "size": 1649,
          "sha512": "98ca3c9e26b6d8330995039b167ac48e69fcc1f1dd50fc85a31fa2743d7c110d2b3142fbdb805d8c0f314da1f70a39e7f7f65883d5abbd210073c77517b991e6",
          "sha256": "00cb63c12fca895abfc2612ddd072ac2c1de44ea91a9d9570f2e7c556c876348",
          "sha1": "ad4da97e484e87d109b84d0c40e379bf634ac533",
          "md5": "f0e84735b381b99c209b305959e72ea6"
        }
      ]
    }
  ]
}
