{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b18",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b18-0.4.1.jar",
          "url": "ble-characteristic-u2b18-0.4.1.jar",
          "size": 1434,
          "sha512": "46ecd4e6ee3b049097005f9c66cdbc011c9b9773483884d61f0adb69e5452dbc37d2a12b3a204736953e7790114ac2f1c19cdea892fd331321c36ea35689f448",
          "sha256": "85c1ea46c32b36c9524a83b1efeb7d44320a1741994a30be49e2998d8d9a6443",
          "sha1": "dd4d97896fd54b74ff4fe3acf38054574098deed",
          "md5": "2aa830135631cf35ddd29231cc24ffea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b18-0.4.1.jar",
          "url": "ble-characteristic-u2b18-0.4.1.jar",
          "size": 1434,
          "sha512": "46ecd4e6ee3b049097005f9c66cdbc011c9b9773483884d61f0adb69e5452dbc37d2a12b3a204736953e7790114ac2f1c19cdea892fd331321c36ea35689f448",
          "sha256": "85c1ea46c32b36c9524a83b1efeb7d44320a1741994a30be49e2998d8d9a6443",
          "sha1": "dd4d97896fd54b74ff4fe3acf38054574098deed",
          "md5": "2aa830135631cf35ddd29231cc24ffea"
        }
      ]
    }
  ]
}
