{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-anp-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-anp-android-0.1.2.aar",
          "url": "ble-profile-anp-android-0.1.2.aar",
          "size": 1203,
          "sha512": "0ab1a89169dd9f59d853662fb993c4b1527633049e69c39a793d06c4e727bbcd75e4de83567850481461ff1d945324bd2daac345d783120d2ae39cbf89361cdc",
          "sha256": "d527c423199921ca322b34f95ff4f284b52a0e6dcc41821f7de833486f91f8eb",
          "sha1": "70694b5cfe014b6e2984cc8171db2155ce93c3b4",
          "md5": "13ef34cd8d3299af586b04cacea3dd01"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-anp-android-0.1.2.aar",
          "url": "ble-profile-anp-android-0.1.2.aar",
          "size": 1203,
          "sha512": "0ab1a89169dd9f59d853662fb993c4b1527633049e69c39a793d06c4e727bbcd75e4de83567850481461ff1d945324bd2daac345d783120d2ae39cbf89361cdc",
          "sha256": "d527c423199921ca322b34f95ff4f284b52a0e6dcc41821f7de833486f91f8eb",
          "sha1": "70694b5cfe014b6e2984cc8171db2155ce93c3b4",
          "md5": "13ef34cd8d3299af586b04cacea3dd01"
        }
      ]
    }
  ]
}
