{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-advertising-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "imnihwqv65eu7lrkazou3zhih4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "stacklog",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-advertising",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-advertising-android-0.1.3.aar",
          "url": "ble-advertising-android-0.1.3.aar",
          "size": 100220,
          "sha512": "9b114f2b9f8007fd8cee1fc86e410324f60cacc67d7bfb65f8ed1ab401214a2ac8d043741796e58b226271337ec4883dc06c2190dded8126eb740de6ffaa4aca",
          "sha256": "a10a0fd5a4ceb73ed2e41254d8222ef3e4c8165b1c99d93bb34cc16d9e7423b4",
          "sha1": "c07a1fa60c27e087de2893624b0edaae02a9deb9",
          "md5": "55e621e45f1791e95a3c74edc3ab44a9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "stacklog",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-advertising",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-advertising-android-0.1.3.aar",
          "url": "ble-advertising-android-0.1.3.aar",
          "size": 100220,
          "sha512": "9b114f2b9f8007fd8cee1fc86e410324f60cacc67d7bfb65f8ed1ab401214a2ac8d043741796e58b226271337ec4883dc06c2190dded8126eb740de6ffaa4aca",
          "sha256": "a10a0fd5a4ceb73ed2e41254d8222ef3e4c8165b1c99d93bb34cc16d9e7423b4",
          "sha1": "c07a1fa60c27e087de2893624b0edaae02a9deb9",
          "md5": "55e621e45f1791e95a3c74edc3ab44a9"
        }
      ]
    }
  ]
}
