{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b15",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b15-0.8.12.jar",
          "url": "ble-characteristic-u2b15-0.8.12.jar",
          "size": 2102,
          "sha512": "94e8133e423fb461ae697908f1233e4949ac32a20ab7b426b025970780c99c552bfa6ee8f22e287eef9d4d921be55d407ac10ff6586ac7b675561278e9e45bca",
          "sha256": "e163ccb72f586d558955efe03d7771e9c8596cb54014bdbbf77c5e355e31d468",
          "sha1": "4247b82c41b9d4afda3a8741aab67a270dc160da",
          "md5": "f14fbb81fdc0fd0b311cc0b346b53b6e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b15-0.8.12.jar",
          "url": "ble-characteristic-u2b15-0.8.12.jar",
          "size": 2102,
          "sha512": "94e8133e423fb461ae697908f1233e4949ac32a20ab7b426b025970780c99c552bfa6ee8f22e287eef9d4d921be55d407ac10ff6586ac7b675561278e9e45bca",
          "sha256": "e163ccb72f586d558955efe03d7771e9c8596cb54014bdbbf77c5e355e31d468",
          "sha1": "4247b82c41b9d4afda3a8741aab67a270dc160da",
          "md5": "f14fbb81fdc0fd0b311cc0b346b53b6e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b15-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b15-0.8.12-javadoc.jar",
          "size": 89048,
          "sha512": "e520e45a943ed580b96ca66b8f5c24bd1d7e15951b69846cb86ff3b9782cc465b5f18e855631dfb9b935141c2564bbeb2301571fc49094127c63eead57d2f9f0",
          "sha256": "1aaac56e33e0cec858d569116a9d80bf2f4438374cc993981c1fa202e805d807",
          "sha1": "4c239de601e3cd8bef83a25329ef35ade4669aa0",
          "md5": "4d6cb75b9b13350a5b13015a571d0ced"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b15-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b15-0.8.12-sources.jar",
          "size": 1972,
          "sha512": "ddbe72f3b42130fc7234a4194b50999d42d3fae758dbcc4ef045575f14d79214ce46f083a6951b6672f9bdccd90c49ce35b443e675549f909aa1b6e6a34e124b",
          "sha256": "47d9d4a156e38c4a03f3333c851c1ccee1a53d96614f2ca3163dd67bf285f804",
          "sha1": "88a28e7b43563901171d855c313e589db2772bc2",
          "md5": "4c4a8e3e9101997dc66d0242f9491112"
        }
      ]
    }
  ]
}
