{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290c",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "3gjypjraujf5fc32spdlwmtq74"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.1.0.jar",
          "url": "ble-descriptor-u290c-0.1.0.jar",
          "size": 3769,
          "sha512": "9de80d7677b6861299edb7bcb9a569bbd5ecd8d04daeffecded1044e78150330445ea25ff4af469e411b2c3e7ed77ea4da1554521922b0161af8ce6070138360",
          "sha256": "1f26e3b3a5935f9b84c8b7ecdd227ed26312deca8e375fb3eb5a6f951aaa6eec",
          "sha1": "57e2b6770e1b4ec10541e8258750343502be8ca6",
          "md5": "f0d07200eb9f42ebc3a002cb2b6bfb13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-0.1.0.jar",
          "url": "ble-descriptor-u290c-0.1.0.jar",
          "size": 3769,
          "sha512": "9de80d7677b6861299edb7bcb9a569bbd5ecd8d04daeffecded1044e78150330445ea25ff4af469e411b2c3e7ed77ea4da1554521922b0161af8ce6070138360",
          "sha256": "1f26e3b3a5935f9b84c8b7ecdd227ed26312deca8e375fb3eb5a6f951aaa6eec",
          "sha1": "57e2b6770e1b4ec10541e8258750343502be8ca6",
          "md5": "f0d07200eb9f42ebc3a002cb2b6bfb13"
        }
      ]
    }
  ]
}
