{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a79",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.5.jar",
          "url": "ble-characteristic-u2a79-0.8.5.jar",
          "size": 1747,
          "sha512": "49291ab1c43d41118b11c9ecc9a86bc7efd8711ff4467a63ccfa69fc325b333e739441ecadadbf268a4ad0a31eea2e4ac429e26bc2b5a8cb8988ea1ca3fef833",
          "sha256": "bc75f6804f43ae255f1c419f8a2e7ebf7e7978c057e0ddb96badee7eeda23971",
          "sha1": "dee14c2791fcbfeb8d99e9a79dc72548eb47193d",
          "md5": "fa7711b5654572f946e82282e7ad7564"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.5.jar",
          "url": "ble-characteristic-u2a79-0.8.5.jar",
          "size": 1747,
          "sha512": "49291ab1c43d41118b11c9ecc9a86bc7efd8711ff4467a63ccfa69fc325b333e739441ecadadbf268a4ad0a31eea2e4ac429e26bc2b5a8cb8988ea1ca3fef833",
          "sha256": "bc75f6804f43ae255f1c419f8a2e7ebf7e7978c057e0ddb96badee7eeda23971",
          "sha1": "dee14c2791fcbfeb8d99e9a79dc72548eb47193d",
          "md5": "fa7711b5654572f946e82282e7ad7564"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a79-0.8.5-javadoc.jar",
          "size": 107308,
          "sha512": "e8fb0830de23a15205439433e2db433f62b7a00f9972c0ac92edf882e926647a4c2b419de59cf949e3e7c5ca082ec6315d9fb9862974d6f8ef72db12b947f7d3",
          "sha256": "89bebaab5fd1849c5a174e54ce9216ca01cd98059a9265e7b2fd514fbef6b139",
          "sha1": "e0e0c711fb48cd2b44a95d3d7805e1fba79cfee0",
          "md5": "65abcd15d45c7e8880aae2da07402ecf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a79-0.8.5-sources.jar",
          "size": 1589,
          "sha512": "28776661bfe4b8aa1ee7ed04fb20c8756b6d51d3cb9b5f2cbc497b2c9ec51c65927e500c2677dbe994b1faae0c2a4d0044773c7d9988bb3745022ac59fed6907",
          "sha256": "11af629f1dc347a5ca567a70f2ddd6949c72ccfaf851869fda5eb1e2bd596d33",
          "sha1": "072b200f122eed44e3eafa4360976bbb7ae869ac",
          "md5": "6f17903ba2574f6bbb0abce7a40f1a75"
        }
      ]
    }
  ]
}
