{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lns-central-android",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-central-android-0.1.8.aar",
          "url": "ble-service-lns-central-android-0.1.8.aar",
          "size": 7597,
          "sha512": "656700a55ac3c8ad78562d601ad51af809e966645234b3653b89ff2fdecd96d5d46fd4747cb9700594ab34632d6d0ebdd472c61c07a3106d58f75c7bc106fed7",
          "sha256": "90911727c463b82269475290f5d3628791acd3eb699ce3a0128426dc3a081400",
          "sha1": "97173abdffe715462e84b3a2bf6fe59d0b4e7ce1",
          "md5": "712088cd5fcd5d86b0dca4ac1b1c8592"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lns-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lns-central-android-0.1.8.aar",
          "url": "ble-service-lns-central-android-0.1.8.aar",
          "size": 7597,
          "sha512": "656700a55ac3c8ad78562d601ad51af809e966645234b3653b89ff2fdecd96d5d46fd4747cb9700594ab34632d6d0ebdd472c61c07a3106d58f75c7bc106fed7",
          "sha256": "90911727c463b82269475290f5d3628791acd3eb699ce3a0128426dc3a081400",
          "sha1": "97173abdffe715462e84b3a2bf6fe59d0b4e7ce1",
          "md5": "712088cd5fcd5d86b0dca4ac1b1c8592"
        }
      ]
    }
  ]
}
