{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b02",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.3.jar",
          "url": "ble-characteristic-u2b02-0.8.3.jar",
          "size": 1919,
          "sha512": "c77c8241d1e856beeb40e1ef2c01dd7882a9766d9891d58cbb9b6e48b4cb7eebc0ec4bd1313df6e0bdf0483e090dddefe672ecaa99f35aa0d737c3ba382251e7",
          "sha256": "8bd2259d90414b7e2aadb50d7dcd4544a483646e534a7b638a15cd4fb483e757",
          "sha1": "854669a33f783072ed65c5b5ee8eb8d2a7156ded",
          "md5": "5f39e8f95ecb532f267ea0ef5e75a32e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.3.jar",
          "url": "ble-characteristic-u2b02-0.8.3.jar",
          "size": 1919,
          "sha512": "c77c8241d1e856beeb40e1ef2c01dd7882a9766d9891d58cbb9b6e48b4cb7eebc0ec4bd1313df6e0bdf0483e090dddefe672ecaa99f35aa0d737c3ba382251e7",
          "sha256": "8bd2259d90414b7e2aadb50d7dcd4544a483646e534a7b638a15cd4fb483e757",
          "sha1": "854669a33f783072ed65c5b5ee8eb8d2a7156ded",
          "md5": "5f39e8f95ecb532f267ea0ef5e75a32e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2b02-0.8.3-javadoc.jar",
          "size": 111112,
          "sha512": "b10a1cd2e28522f5a93b46b912b57d7c94f29b5a6c7de1c14a3f44b42870c6570c8177ef52a034f08392478fa2d06357341fb18904a86f48a3ea7ecf1f41fff4",
          "sha256": "d56ebbfc28c16748aed66775d47f3e89ad2aaef1cbffa1537d89efdac4ba0f7f",
          "sha1": "87fc070cc7ce23f249300d5e0043a203e429dbc0",
          "md5": "030c74acfd6e377972f093d88d3ede98"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b02-0.8.3-sources.jar",
          "url": "ble-characteristic-u2b02-0.8.3-sources.jar",
          "size": 1790,
          "sha512": "1dfd2714f52d709ee1b25551badd373a54b0e86e192a8b5e2561d0139d9e72a049fcbb1be6b186bb384267ca0eb34fa99afc2d772d2c85b6c8904e217ef646e3",
          "sha256": "583c09b450036ce9cd4cbfbd48fb65eeebbc1f1fb13416d528f8511e277a9251",
          "sha1": "0e56efb289826681c14cd736c6b567b9840a6b1f",
          "md5": "af86f139a2a98f6ecac27ac8e4fe641b"
        }
      ]
    }
  ]
}
