{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd1",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd1-0.8.12.jar",
          "url": "ble-characteristic-u2bd1-0.8.12.jar",
          "size": 1904,
          "sha512": "78e980a03687caa7c7f46483b0f38095228cfd31b31c421ad71d61c71263f13e368b690f93b923734dd4a58473bc69609323e73cb28953290f5dea8f66c7aece",
          "sha256": "63e8eb040a1d5f208c44dd8f65993f20012f4ef01ea0cfd15272ce9700d79ebf",
          "sha1": "8331aa11caa6917d4b292b5bcb491770a3084438",
          "md5": "977d38a75b259ac619f12a53fb43375e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd1-0.8.12.jar",
          "url": "ble-characteristic-u2bd1-0.8.12.jar",
          "size": 1904,
          "sha512": "78e980a03687caa7c7f46483b0f38095228cfd31b31c421ad71d61c71263f13e368b690f93b923734dd4a58473bc69609323e73cb28953290f5dea8f66c7aece",
          "sha256": "63e8eb040a1d5f208c44dd8f65993f20012f4ef01ea0cfd15272ce9700d79ebf",
          "sha1": "8331aa11caa6917d4b292b5bcb491770a3084438",
          "md5": "977d38a75b259ac619f12a53fb43375e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd1-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2bd1-0.8.12-javadoc.jar",
          "size": 107844,
          "sha512": "2b017b07593ecf782c7d42c2a3f8d2d3844f4f8e783855e41574b27e803ea6e0866e1a210f5064a4d50f12ad32faf999d30e836b355dbb5bc016531652d89508",
          "sha256": "0bd03b00f46a187769232db35c0c37684a7df18b4eefde88ae15d6c87398efcd",
          "sha1": "70b88652903f4a2fd7b5c33caf533fe62b375338",
          "md5": "33a7d7cbf8721346b370c76e533f9111"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd1-0.8.12-sources.jar",
          "url": "ble-characteristic-u2bd1-0.8.12-sources.jar",
          "size": 1917,
          "sha512": "f11575e697990cf57a75cf5d5ae964bc0e8c2f142316f6165b72f98aa95e3c901962d58dba9c51100ac5f82a184bf303ebbfe76eecab0c558fc6dcdb33f56ca6",
          "sha256": "ade733e7bf93c72773a84d0eb0d625e91bef2125b7bb1b867c4828f2d21eb816",
          "sha1": "226e936bbcf1f24810c0d34d62a7502a563b0a8b",
          "md5": "44e0eb854f57d273c1c7b433f77c3078"
        }
      ]
    }
  ]
}
