{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9e-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2kquscs33vaubks6hlnwqdrbne"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.3.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.3.aar",
          "size": 3024,
          "sha512": "b614e71d475d4f64a330c1edd58856d33d55a6f750090dee2a2f1563f0f3d2b029dbd81342de0ac5ec03031467e52e87828c825ed7cf85628ac8645582681fcd",
          "sha256": "1cf6f50f696f42b3acb123bedc6e6fc3ad321ba0cd59604d77987954d2c3d4f1",
          "sha1": "d49e27bd58b72fb77581b893b9b3408aa4b77d94",
          "md5": "3e8822875057f7e23f6dab01ee777cb3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.3.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.3.aar",
          "size": 3024,
          "sha512": "b614e71d475d4f64a330c1edd58856d33d55a6f750090dee2a2f1563f0f3d2b029dbd81342de0ac5ec03031467e52e87828c825ed7cf85628ac8645582681fcd",
          "sha256": "1cf6f50f696f42b3acb123bedc6e6fc3ad321ba0cd59604d77987954d2c3d4f1",
          "sha1": "d49e27bd58b72fb77581b893b9b3408aa4b77d94",
          "md5": "3e8822875057f7e23f6dab01ee777cb3"
        }
      ]
    }
  ]
}
