{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0f",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.2.jar",
          "url": "ble-characteristic-u2b0f-0.8.2.jar",
          "size": 2077,
          "sha512": "2697ce8eb201ac5b86c8673c6daf11fc1a071ec355d7b84bd0f6cee1838720465c4fa433d7596c5c176b893140edcb60f7d3de14fc105718a20b88cb061721f6",
          "sha256": "7a33b8ec1ed09a2d6bfc8cdbba5449715cf6dfd31414c48cc306aa11bacfb146",
          "sha1": "afd148792c49f1f0df2958c4a8bbf6b7e84b617a",
          "md5": "1afc1ac723f0e0513880f10b9b380457"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.2.jar",
          "url": "ble-characteristic-u2b0f-0.8.2.jar",
          "size": 2077,
          "sha512": "2697ce8eb201ac5b86c8673c6daf11fc1a071ec355d7b84bd0f6cee1838720465c4fa433d7596c5c176b893140edcb60f7d3de14fc105718a20b88cb061721f6",
          "sha256": "7a33b8ec1ed09a2d6bfc8cdbba5449715cf6dfd31414c48cc306aa11bacfb146",
          "sha1": "afd148792c49f1f0df2958c4a8bbf6b7e84b617a",
          "md5": "1afc1ac723f0e0513880f10b9b380457"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.2-javadoc.jar",
          "url": "ble-characteristic-u2b0f-0.8.2-javadoc.jar",
          "size": 110527,
          "sha512": "e424e26e61af990b82837a57ae6031aeff5bd279ee6d1b8a1afcce6d69497827e7c1f8e3cded3ad0d5d47675c6a439ab0023edbbf4bab55a9fdf99a0d690d765",
          "sha256": "86f1619e784a330ac34c033ce7031b72be79d45fe1ebbae54551287a7f126e5f",
          "sha1": "0e6556a0306ca4f6599584ebd716c32968a75738",
          "md5": "f7770f8360ddddf224a422650b329e20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0f-0.8.2-sources.jar",
          "url": "ble-characteristic-u2b0f-0.8.2-sources.jar",
          "size": 1876,
          "sha512": "2db6631ca1e5ffebe7fb5df7a397c0bdd1f8396b778a6ab3a5fb87aa962a3eb053f6e18ac422b154113b0df961d9af778455ee3487dfeb4fedd6a1d297c2415c",
          "sha256": "7ed93044dc18a529e74ec7f7a28be57a64f6a985ad6ce1f0daaa12000babf45a",
          "sha1": "73a3d6a3b057ec1784e71a5b3e67ff5c4f2f165f",
          "md5": "01d3ae4f482e1735534de798e2e9ffbc"
        }
      ]
    }
  ]
}
