{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a21-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a21",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a21-android-0.2.2.aar",
          "url": "ble-characteristic-u2a21-android-0.2.2.aar",
          "size": 2923,
          "sha512": "c0ecff846a04997308a8e475165feebc15a4015f27d7f63858b22fde7c7195b8db769f2839d86b64c229de1b9cf54b26613b1163132348730a0ef95f64840bfb",
          "sha256": "7a267fb264af9a107b8a56a701072cd894babe4c7bf56144eebcf785c0c393e0",
          "sha1": "af2836f88c5562db201058219fafacffe719090a",
          "md5": "9ab10b873d9c7378e724264983ea3f83"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a21",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a21-android-0.2.2.aar",
          "url": "ble-characteristic-u2a21-android-0.2.2.aar",
          "size": 2923,
          "sha512": "c0ecff846a04997308a8e475165feebc15a4015f27d7f63858b22fde7c7195b8db769f2839d86b64c229de1b9cf54b26613b1163132348730a0ef95f64840bfb",
          "sha256": "7a267fb264af9a107b8a56a701072cd894babe4c7bf56144eebcf785c0c393e0",
          "sha1": "af2836f88c5562db201058219fafacffe719090a",
          "md5": "9ab10b873d9c7378e724264983ea3f83"
        }
      ]
    }
  ]
}
