{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b26-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b26",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b26-android-0.4.4.aar",
          "url": "ble-characteristic-u2b26-android-0.4.4.aar",
          "size": 3061,
          "sha512": "e3af0045c725e3a389009ebdc9e7f4c6765ed37ae43745c63feec7fb7083dce75a156713d9358952be80b7a8e8d7626327ea2dd84db34eaba7edf1960a22e26a",
          "sha256": "a6f74d3c313918f6fc3feb31a48db8d0f3e62209ab38c1ff0873e59e6b258b35",
          "sha1": "7e72894ed0ce9335b9b9ef48b26b52e3548cad92",
          "md5": "3425447dc62f74ad50242e5b4be11899"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b26",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b26-android-0.4.4.aar",
          "url": "ble-characteristic-u2b26-android-0.4.4.aar",
          "size": 3061,
          "sha512": "e3af0045c725e3a389009ebdc9e7f4c6765ed37ae43745c63feec7fb7083dce75a156713d9358952be80b7a8e8d7626327ea2dd84db34eaba7edf1960a22e26a",
          "sha256": "a6f74d3c313918f6fc3feb31a48db8d0f3e62209ab38c1ff0873e59e6b258b35",
          "sha1": "7e72894ed0ce9335b9b9ef48b26b52e3548cad92",
          "md5": "3425447dc62f74ad50242e5b4be11899"
        }
      ]
    }
  ]
}
