{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a2c-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2c",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2c-android-0.2.9.aar",
          "url": "ble-characteristic-u2a2c-android-0.2.9.aar",
          "size": 3144,
          "sha512": "a934e46917654d6b8170219bb57ced9ee0a89742dbd35a507373dcdd52ae6f6aa6fec7c118c7d39dc2c47366b7da6983cfc93258b0db6f237ddd1ee2026e2d19",
          "sha256": "8123b7f2a43ddc6a03c236de90c34206a29fc29259361ab0ec21de5af9f7eae6",
          "sha1": "ebd0ff361635fd23eb8db7efb1eb665916061920",
          "md5": "43d8cfed810ba2f361b4b227447b0b4f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2c",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2c-android-0.2.9.aar",
          "url": "ble-characteristic-u2a2c-android-0.2.9.aar",
          "size": 3144,
          "sha512": "a934e46917654d6b8170219bb57ced9ee0a89742dbd35a507373dcdd52ae6f6aa6fec7c118c7d39dc2c47366b7da6983cfc93258b0db6f237ddd1ee2026e2d19",
          "sha256": "8123b7f2a43ddc6a03c236de90c34206a29fc29259361ab0ec21de5af9f7eae6",
          "sha1": "ebd0ff361635fd23eb8db7efb1eb665916061920",
          "md5": "43d8cfed810ba2f361b4b227447b0b4f"
        }
      ]
    }
  ]
}
