{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a46-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a46-android-0.8.6.aar",
          "url": "ble-characteristic-u2a46-android-0.8.6.aar",
          "size": 3143,
          "sha512": "2b0de7581e8c4394d680bdc2189a586dbcb45a66946e798030566313fe9d800588de8c0b475620e21377ab22633aba052b898b5d64d28d00a85f7a3dc5f653e9",
          "sha256": "2a5ac07de9392b1da6cc6c613b6132c456c10aa0c873aa15bf05913f8ea0c7a2",
          "sha1": "313567d41ee1c5675317a289cdc5a40801f68043",
          "md5": "ffb704a3ff46392d3649aaa8a31437cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a46-android-0.8.6.aar",
          "url": "ble-characteristic-u2a46-android-0.8.6.aar",
          "size": 3143,
          "sha512": "2b0de7581e8c4394d680bdc2189a586dbcb45a66946e798030566313fe9d800588de8c0b475620e21377ab22633aba052b898b5d64d28d00a85f7a3dc5f653e9",
          "sha256": "2a5ac07de9392b1da6cc6c613b6132c456c10aa0c873aa15bf05913f8ea0c7a2",
          "sha1": "313567d41ee1c5675317a289cdc5a40801f68043",
          "md5": "ffb704a3ff46392d3649aaa8a31437cf"
        }
      ]
    }
  ]
}
