{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9c-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.8.11.aar",
          "url": "ble-characteristic-u2a9c-android-0.8.11.aar",
          "size": 5664,
          "sha512": "e2be33d023ba68fb8ae39ade2e9c181cabe94ea75a4651038ae1edbb84941ae34d708fe32424d7ffc8a054cde3b68fc75bf73d0a2d59b9f88902757ad55596ea",
          "sha256": "44b275f61e904b7c01406021b0093c649e3f223646003b21c85d1363cbec307b",
          "sha1": "793f018f90bd5d2b82e67049ee1f0e9b73d8a104",
          "md5": "f0084cf2fddc23e961d8831126bbc0b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9c",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.8.11.aar",
          "url": "ble-characteristic-u2a9c-android-0.8.11.aar",
          "size": 5664,
          "sha512": "e2be33d023ba68fb8ae39ade2e9c181cabe94ea75a4651038ae1edbb84941ae34d708fe32424d7ffc8a054cde3b68fc75bf73d0a2d59b9f88902757ad55596ea",
          "sha256": "44b275f61e904b7c01406021b0093c649e3f223646003b21c85d1363cbec307b",
          "sha1": "793f018f90bd5d2b82e67049ee1f0e9b73d8a104",
          "md5": "f0084cf2fddc23e961d8831126bbc0b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2a9c-android-0.8.11-sources.jar",
          "size": 4096,
          "sha512": "a0d6e659d6e90bd50c93fcfd4055764a50320bda0ba69d73e85c63979edfdaa9fc77fb7b6d17277677da31d9a25cb787bd44fbd4652981a68f72f3aa53bee1f2",
          "sha256": "aeb0bfa212c3aef1440ee69dfae3c17c8cbbc44a4eed7797aa990e6379967455",
          "sha1": "a49ede142efb1bc7651e130c90f74cc9599aacde",
          "md5": "b6d7aff1766a844295072b6cb9400b93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9c-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2a9c-android-0.8.11-javadoc.jar",
          "size": 278840,
          "sha512": "5916f44cbbab55ae6851e59ef774a90d7d622badf56d9796c0ed2a431aa0734a6b0576ff9064b878862eb9dc6265e8e0328e6375c565ffe735adae750bddbde2",
          "sha256": "36553e0ad0a8e82ed7bce9d926a2d5983a5911c804a682692991d7ce4fc665d0",
          "sha1": "c64c8f15034ccd3a6090028fe9f1b44f3318c411",
          "md5": "698c6e01bd5a1d9588dd8613a0bb993e"
        }
      ]
    }
  ]
}
