{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ndcs-central-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "onm7oav7y5gufewzovq4jjg3iy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ndcs-central-android-0.1.0.aar",
          "url": "ble-service-ndcs-central-android-0.1.0.aar",
          "size": 3244,
          "sha512": "a9798dbfab47bc686570f7bb7be38e7a4637b373031ddfcd588f095539d0333b2d709295c39e7369ba81fae5b54116d7e60f65c3aa118b2b89c3e6c94ee963ab",
          "sha256": "6dbf61722dbbdc49bf6087b6ffc4eb03b036043850ab9792d77a0e43d9953f85",
          "sha1": "6a9dc27044022932c3d8b5ae8d76238756c02ac9",
          "md5": "ca5b33978e1530f45609d53fa18204bb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ndcs-central-android-0.1.0.aar",
          "url": "ble-service-ndcs-central-android-0.1.0.aar",
          "size": 3244,
          "sha512": "a9798dbfab47bc686570f7bb7be38e7a4637b373031ddfcd588f095539d0333b2d709295c39e7369ba81fae5b54116d7e60f65c3aa118b2b89c3e6c94ee963ab",
          "sha256": "6dbf61722dbbdc49bf6087b6ffc4eb03b036043850ab9792d77a0e43d9953f85",
          "sha1": "6a9dc27044022932c3d8b5ae8d76238756c02ac9",
          "md5": "ca5b33978e1530f45609d53fa18204bb"
        }
      ]
    }
  ]
}
