{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b00-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b00",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b00-android-0.4.4.aar",
          "url": "ble-characteristic-u2b00-android-0.4.4.aar",
          "size": 3076,
          "sha512": "e0e65da54ed8b11b20c990691c65645830d1fd62f11ade171ae069973c6dc00fedab7545bb913649db03610878472fbda3c6975079ab2eec1d458f4e51c225a5",
          "sha256": "f0325710444d9a610638c102c8275c33c9bd47eeada0ceb222ca2428af7c910c",
          "sha1": "9b24c51a9567ba31ef4ff4840dc34c4b3cc8738b",
          "md5": "3effd21e296a0ab67437fbd8c96b01e0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b00",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b00-android-0.4.4.aar",
          "url": "ble-characteristic-u2b00-android-0.4.4.aar",
          "size": 3076,
          "sha512": "e0e65da54ed8b11b20c990691c65645830d1fd62f11ade171ae069973c6dc00fedab7545bb913649db03610878472fbda3c6975079ab2eec1d458f4e51c225a5",
          "sha256": "f0325710444d9a610638c102c8275c33c9bd47eeada0ceb222ca2428af7c910c",
          "sha1": "9b24c51a9567ba31ef4ff4840dc34c4b3cc8738b",
          "md5": "3effd21e296a0ab67437fbd8c96b01e0"
        }
      ]
    }
  ]
}
