{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb2",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb2-0.6.0.jar",
          "url": "ble-characteristic-u2bb2-0.6.0.jar",
          "size": 1511,
          "sha512": "c63813f4fc2e6895b65aa1dd85b0586d10678ecb2c805393e98be61beaab94ed1620f10487eff945e60a758c3d3640dd0d258d29254307017044f6c7cc924147",
          "sha256": "0c1cab316fc2380273e21289f54d003e5625d4dbafdb086e797be57c8afd67b6",
          "sha1": "f9a1029c6e810f3b1fc98300a240d6e67bd6464f",
          "md5": "c0e49c93afae9f070ca2796b51509b4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb2-0.6.0.jar",
          "url": "ble-characteristic-u2bb2-0.6.0.jar",
          "size": 1511,
          "sha512": "c63813f4fc2e6895b65aa1dd85b0586d10678ecb2c805393e98be61beaab94ed1620f10487eff945e60a758c3d3640dd0d258d29254307017044f6c7cc924147",
          "sha256": "0c1cab316fc2380273e21289f54d003e5625d4dbafdb086e797be57c8afd67b6",
          "sha1": "f9a1029c6e810f3b1fc98300a240d6e67bd6464f",
          "md5": "c0e49c93afae9f070ca2796b51509b4d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb2-0.6.0-javadoc.jar",
          "url": "ble-characteristic-u2bb2-0.6.0-javadoc.jar",
          "size": 110077,
          "sha512": "1af38fc41d50df6deb381d3d0f1bc0b3ae79e82c80309cf7b051898bc10885edd3c139df49d527681d43c4cb4c00cbc208a892bdc676db42bad11b874d84a060",
          "sha256": "040466b64736674519dde08ca330fc63d85e9912aa66827f99ec087490b3ab4d",
          "sha1": "38c9328cdf84cc88bc35e5d4d9ececed6c547fd0",
          "md5": "35214841149b4c66df0f6c18b0b0ceff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb2-0.6.0-sources.jar",
          "url": "ble-characteristic-u2bb2-0.6.0-sources.jar",
          "size": 1494,
          "sha512": "15c338aabd3e5a9ec83fe2b99b4ed2a0399306e0140465f4b051101f7129b158015c6fc2a97f81cc86ac8dfe09a25f677194099f49483a1f528d97222b0a8607",
          "sha256": "ddd74e702f038666ce976fd17fa3187bd43e22937a332ce4fcd49ed2e0ca2f2b",
          "sha1": "38cf39943aefbc76b3c72c56f42a325866e5ede7",
          "md5": "8d7dc20fdf38fe0175787573ff95dd9c"
        }
      ]
    }
  ]
}
