{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4a-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4a",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4a-android-0.8.6.aar",
          "url": "ble-characteristic-u2b4a-android-0.8.6.aar",
          "size": 3071,
          "sha512": "1e4ecf1cea7e3fdf8e87b941039166d055efcc847ab61e3683f21802ffff061be8f0aadb0035d981fb112a00eea102983292b9ce1a52a49db6a87c26d1fb0393",
          "sha256": "015b0c4d60d002be7e9a400089f1c308bfddf99e72c39afedbe54c2e24caa858",
          "sha1": "aefb72689ccc4bd5a2a0f83c7780e2515198517c",
          "md5": "04626bf967482d8d2bad2ce8b1ba1588"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4a",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4a-android-0.8.6.aar",
          "url": "ble-characteristic-u2b4a-android-0.8.6.aar",
          "size": 3071,
          "sha512": "1e4ecf1cea7e3fdf8e87b941039166d055efcc847ab61e3683f21802ffff061be8f0aadb0035d981fb112a00eea102983292b9ce1a52a49db6a87c26d1fb0393",
          "sha256": "015b0c4d60d002be7e9a400089f1c308bfddf99e72c39afedbe54c2e24caa858",
          "sha1": "aefb72689ccc4bd5a2a0f83c7780e2515198517c",
          "md5": "04626bf967482d8d2bad2ce8b1ba1588"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4a-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b4a-android-0.8.6-sources.jar",
          "size": 2147,
          "sha512": "6dca6013be731b903e98ac9c54492c3f281cac9cb0e4d03cfef7ee00133e13b1aaf568fcb19f9e9cb02bee4686e11a563c7c4eead77da75185135a90ab6d80ad",
          "sha256": "b45fc96c09e7bcf8770c379d4793b08a6c7c02a3a25906cd6f073486f562396c",
          "sha1": "df2db243bf9bffd7a9cd107fe63251c180714a84",
          "md5": "45820b7ff9cbe4eb40903452a9cf9d43"
        }
      ]
    }
  ]
}
