{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9e",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-0.8.6.jar",
          "url": "ble-characteristic-u2a9e-0.8.6.jar",
          "size": 2889,
          "sha512": "e4411cdae4842699063b229ce4e942b59e87d6e0e0f66f073996aa5d65f9319fb09eb1e33490ac801ee4458e174fa6ee58b10d5a033a954cc548e9a59db591e2",
          "sha256": "a73b0fd21d6e9250b8a730c182c1ae3059494e353656a8373baaa63325709965",
          "sha1": "5ebb5b305b220aead61d8ed30352b8b9cdc2defd",
          "md5": "e7d970adc5e2cdf62b713a215aad673f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-0.8.6.jar",
          "url": "ble-characteristic-u2a9e-0.8.6.jar",
          "size": 2889,
          "sha512": "e4411cdae4842699063b229ce4e942b59e87d6e0e0f66f073996aa5d65f9319fb09eb1e33490ac801ee4458e174fa6ee58b10d5a033a954cc548e9a59db591e2",
          "sha256": "a73b0fd21d6e9250b8a730c182c1ae3059494e353656a8373baaa63325709965",
          "sha1": "5ebb5b305b220aead61d8ed30352b8b9cdc2defd",
          "md5": "e7d970adc5e2cdf62b713a215aad673f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9e-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a9e-0.8.6-javadoc.jar",
          "size": 113636,
          "sha512": "9efa8f20932f4507b6958d6f3455fbd3b4bb0f159f66441204db1530b206d49cb364eb07c4db1ca3a0a6dbda8e26157b4402fa0b4797996e9282da63e6152f41",
          "sha256": "d8ac0a169333390261b29a26c2cfacbaa6df6023107817acf2f3e6278f7cbc11",
          "sha1": "5b2c909a51c05ec537668a475d499e4ae522dd7b",
          "md5": "147792b963401772452f5c85efc82621"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a9e-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a9e-0.8.6-sources.jar",
          "size": 3209,
          "sha512": "cf3e6e08eda1878412c0c3497bf40999feb443ddbc93b628819b971bb3cfa2e1bf4856969134ff6f31b9893264d3cc0b89667f1166601412e5b779263f0a9cc8",
          "sha256": "c0ce90b5b80d34706bc8a449bcaf6b482dcb26186a4b993227a6813dda1cd1d2",
          "sha1": "ad6c50397890a0fd80c2ef26bccb5a8bccf56192",
          "md5": "1e09bf4a4f79f603d4e9ec310fe4745f"
        }
      ]
    }
  ]
}
