{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a33-android",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a33",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a33-android-0.1.7.aar",
          "url": "ble-characteristic-u2a33-android-0.1.7.aar",
          "size": 3067,
          "sha512": "2fe6800db648b68157b341214a7d647a1320c32e50d7d3a5fb90079e0a5bb1e79ab1aa734b8c306efa394e136d8d84f5091c3a153432d32d8d50d20eaa4724ab",
          "sha256": "1d7a370b96318cd5845d107f28d3111a352a83a61895520a51446afc4adb7675",
          "sha1": "3e11a4e456f88764413d1f6ecf77325997517c37",
          "md5": "d87bd2c66271323a446a328bc1af5761"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a33",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a33-android-0.1.7.aar",
          "url": "ble-characteristic-u2a33-android-0.1.7.aar",
          "size": 3067,
          "sha512": "2fe6800db648b68157b341214a7d647a1320c32e50d7d3a5fb90079e0a5bb1e79ab1aa734b8c306efa394e136d8d84f5091c3a153432d32d8d50d20eaa4724ab",
          "sha256": "1d7a370b96318cd5845d107f28d3111a352a83a61895520a51446afc4adb7675",
          "sha1": "3e11a4e456f88764413d1f6ecf77325997517c37",
          "md5": "d87bd2c66271323a446a328bc1af5761"
        }
      ]
    }
  ]
}
