{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ias-peripheral-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zzwrv7bhbfgvlhoshhgo5ogf5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-peripheral-android-0.1.3.aar",
          "url": "ble-service-ias-peripheral-android-0.1.3.aar",
          "size": 4696,
          "sha512": "44fe776f1fef8187183b9c76a9c280786b36eb6a5c4acdf193375094bfca3cc909c15fddc4dae35b16436ec9cfe9360cca7c629ed09de62b11d94f7cebfca9c5",
          "sha256": "6f1d12b0c3d6d32f0152cc13b8bbcde208c763ca17fa0c26f3e03669226ec79a",
          "sha1": "ba9495d50ac1c60c7edfcbb2a7e376c15f32e888",
          "md5": "cb67020cee95227cbb8304d992c552c5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-peripheral-android-0.1.3.aar",
          "url": "ble-service-ias-peripheral-android-0.1.3.aar",
          "size": 4696,
          "sha512": "44fe776f1fef8187183b9c76a9c280786b36eb6a5c4acdf193375094bfca3cc909c15fddc4dae35b16436ec9cfe9360cca7c629ed09de62b11d94f7cebfca9c5",
          "sha256": "6f1d12b0c3d6d32f0152cc13b8bbcde208c763ca17fa0c26f3e03669226ec79a",
          "sha1": "ba9495d50ac1c60c7edfcbb2a7e376c15f32e888",
          "md5": "cb67020cee95227cbb8304d992c552c5"
        }
      ]
    }
  ]
}
