{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb5-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb5",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb5-android-0.8.6.aar",
          "url": "ble-characteristic-u2bb5-android-0.8.6.aar",
          "size": 3054,
          "sha512": "742d94684466797db54e3ddffcb8d628d0bb6e4987ab9434797da824fcdab4c635e0803f96b25ccba4a8a8ff83877881f5a650b1b1d57008247705e8b8ccd9ec",
          "sha256": "074ef365f1bc3f989bb28333314c641955a9eca490bf107c552fb1119ecf30ea",
          "sha1": "bfad3c39a4803d4a71ff0c41de669963190e00fd",
          "md5": "03a8024e5d1e0114e705b063567d51ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb5",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb5-android-0.8.6.aar",
          "url": "ble-characteristic-u2bb5-android-0.8.6.aar",
          "size": 3054,
          "sha512": "742d94684466797db54e3ddffcb8d628d0bb6e4987ab9434797da824fcdab4c635e0803f96b25ccba4a8a8ff83877881f5a650b1b1d57008247705e8b8ccd9ec",
          "sha256": "074ef365f1bc3f989bb28333314c641955a9eca490bf107c552fb1119ecf30ea",
          "sha1": "bfad3c39a4803d4a71ff0c41de669963190e00fd",
          "md5": "03a8024e5d1e0114e705b063567d51ee"
        }
      ]
    }
  ]
}
