{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a79",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.6.1.jar",
          "url": "ble-characteristic-u2a79-0.6.1.jar",
          "size": 1747,
          "sha512": "8667ad022a6980fbd2706952a1d2a390a29750a9553a41d50bd91f13698ee46dd989eb2bf6dd2d7d4aa087552e23c765b6a1bc71ac8e0c7163b235e0aa119930",
          "sha256": "f56b0b79fcb86814c50f9a63612375595a1e0dc46121fcc05cb8c9711ca49517",
          "sha1": "660ca23a8e68ce11a77042f18d86a06df4f913eb",
          "md5": "454ea046754e9d686c512715efd55015"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.6.1.jar",
          "url": "ble-characteristic-u2a79-0.6.1.jar",
          "size": 1747,
          "sha512": "8667ad022a6980fbd2706952a1d2a390a29750a9553a41d50bd91f13698ee46dd989eb2bf6dd2d7d4aa087552e23c765b6a1bc71ac8e0c7163b235e0aa119930",
          "sha256": "f56b0b79fcb86814c50f9a63612375595a1e0dc46121fcc05cb8c9711ca49517",
          "sha1": "660ca23a8e68ce11a77042f18d86a06df4f913eb",
          "md5": "454ea046754e9d686c512715efd55015"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.6.1-javadoc.jar",
          "url": "ble-characteristic-u2a79-0.6.1-javadoc.jar",
          "size": 110012,
          "sha512": "4b8363b46faf8d8ef1288b7c77e8c27c8774a6b5501cf4d197943f97584c1f8d27a12ea20b36a5900328cb6d48c2dc1dc7632b2f04fc77123a0b912536f7c0ac",
          "sha256": "7908f398a4d2a8ecf93c84b0022ce2500a6b3199191f0481fa66e5c4879e1abf",
          "sha1": "e1772a68db6fe365aec07e312164426769dadfb0",
          "md5": "3a01738435a60a8dd7a736f24eb6cc9a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a79-0.6.1-sources.jar",
          "url": "ble-characteristic-u2a79-0.6.1-sources.jar",
          "size": 1589,
          "sha512": "f8c3240b243e445c94020f218a0063b148f42958cc37e320c048f0c4b1e0546a916bd49ec770f1a33c7bb206ed11c7c72dcabe091208a68b2c1f10bbfadd2191",
          "sha256": "623e1919f3fe05195bbfaf61e1a33cb626da16a6e523410ae72be2ff81d7f531",
          "sha1": "5a1179f0dfffd7506480c3c06f11f7ca46b49c16",
          "md5": "2e72e91aa9d3a8c4d832cc7f90601282"
        }
      ]
    }
  ]
}
