{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a41-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a41",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a41-android-0.8.6.aar",
          "url": "ble-characteristic-u2a41-android-0.8.6.aar",
          "size": 3082,
          "sha512": "9743218a76f845ffad91cebd017ef4a817b322152fcb77c0e32b606358778a3d20b5826eaa91b133da928d1bdd036a52ba1d5688d5a7f3904dcacc2f82ab49e8",
          "sha256": "88a01d7d4debd68891cea727c78ac69203303b43ed951f9c39a66639f7608e85",
          "sha1": "bdbf7924a781cd30fccb2ef00d8ea4d65d89b90a",
          "md5": "069935019996e67ab93ce035b96b2372"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a41",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a41-android-0.8.6.aar",
          "url": "ble-characteristic-u2a41-android-0.8.6.aar",
          "size": 3082,
          "sha512": "9743218a76f845ffad91cebd017ef4a817b322152fcb77c0e32b606358778a3d20b5826eaa91b133da928d1bdd036a52ba1d5688d5a7f3904dcacc2f82ab49e8",
          "sha256": "88a01d7d4debd68891cea727c78ac69203303b43ed951f9c39a66639f7608e85",
          "sha1": "bdbf7924a781cd30fccb2ef00d8ea4d65d89b90a",
          "md5": "069935019996e67ab93ce035b96b2372"
        }
      ]
    }
  ]
}
