{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa1",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.10.jar",
          "url": "ble-characteristic-u2aa1-0.8.10.jar",
          "size": 2081,
          "sha512": "8fd8f6042499b18bf6f5e67ebdbbf89cf24ea81ef981082374a49cbc2ace59a9a5401216a02be0cd5881e39c1344f69489f1caa18b8ea0f4893d662a091f4d84",
          "sha256": "321e3c4232696719d11dd875a88ae5a4cfba0fe356b032e0f606d2ea4b07afb8",
          "sha1": "429174ae81c96e289477b0166ffce99dd028a57f",
          "md5": "c08bb96d79a2369a51a9ecd93f7933a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.10.jar",
          "url": "ble-characteristic-u2aa1-0.8.10.jar",
          "size": 2081,
          "sha512": "8fd8f6042499b18bf6f5e67ebdbbf89cf24ea81ef981082374a49cbc2ace59a9a5401216a02be0cd5881e39c1344f69489f1caa18b8ea0f4893d662a091f4d84",
          "sha256": "321e3c4232696719d11dd875a88ae5a4cfba0fe356b032e0f606d2ea4b07afb8",
          "sha1": "429174ae81c96e289477b0166ffce99dd028a57f",
          "md5": "c08bb96d79a2369a51a9ecd93f7933a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2aa1-0.8.10-javadoc.jar",
          "size": 109989,
          "sha512": "70661fcd26c2890684d13e215a6f2c1956a190e48602a17d631b2884f316e15b6e186690f61901818d9de8820c2c02010b96b9776aed833a4500ef8b4655c293",
          "sha256": "e4b49bd9ab822470289eca94358a0a8f3d6abb027d1d4ca9c87803070939fa51",
          "sha1": "15fc3a12f18053a997a04c492a2bc1c6c74a7434",
          "md5": "c8ae80454cc39268f54ff37646336bc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.10-sources.jar",
          "url": "ble-characteristic-u2aa1-0.8.10-sources.jar",
          "size": 1894,
          "sha512": "46d28855f992c74c5e9ef0d80196a1298a71de3e6842b4d4bc519fd865f471256233f73f1563dae85f166a012ee96fe6f6198fdd2b7c31078452887ab3c08d29",
          "sha256": "ed1731b0b4512d4170af7c23a80e224d98bb6be0fe088aecebfb82aaf35c864e",
          "sha1": "f44845b36336f673b4efc17744619245096ae4a7",
          "md5": "aa0c6e1d38ecc925ca4bb7e04421e6fb"
        }
      ]
    }
  ]
}
