{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0f-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0f",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-android-0.4.6.aar",
          "url": "ble-characteristic-u2b0f-android-0.4.6.aar",
          "size": 3213,
          "sha512": "8445a8c0cf40e0294d480f12d28ed373def5b42d7e50089903cb6145e6051bce1a54776ce8a5af78cf5dc691cb06b9eef4665c03128aa5af387d9da0e246c2b4",
          "sha256": "fab815aca79b0396dc486e1208b017a023468b54d6c5907d892e52df8ba41d21",
          "sha1": "cb199f141c9365e647b8752e36d83b5f84085bb7",
          "md5": "d340c543ec0107906ff59cb49d4e6af1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0f",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0f-android-0.4.6.aar",
          "url": "ble-characteristic-u2b0f-android-0.4.6.aar",
          "size": 3213,
          "sha512": "8445a8c0cf40e0294d480f12d28ed373def5b42d7e50089903cb6145e6051bce1a54776ce8a5af78cf5dc691cb06b9eef4665c03128aa5af387d9da0e246c2b4",
          "sha256": "fab815aca79b0396dc486e1208b017a023468b54d6c5907d892e52df8ba41d21",
          "sha1": "cb199f141c9365e647b8752e36d83b5f84085bb7",
          "md5": "d340c543ec0107906ff59cb49d4e6af1"
        }
      ]
    }
  ]
}
