{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a49",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "b5siun65pvf3xbu2ctcp5sxnw4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a49-0.2.0.jar",
          "url": "ble-characteristic-u2a49-0.2.0.jar",
          "size": 2443,
          "sha512": "9ec2b8ff8ed8c7a07e8212a1f4f2596917f9001adba4cd6e395d004f9b98046f03859b02db4ca0258af2f623da8e6606713625cea8bf02f9ea6b9ab4af56b86d",
          "sha256": "908601e2bf915903d11a91d25ff5fa53ad9e272ade7c289b5c7192b6b65d2ca2",
          "sha1": "29fcd02635a8eeccb0b5e7745eeae0b7fa873c47",
          "md5": "8bd35b3b09bb77c83cae0f5fcb6f4c72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a49-0.2.0.jar",
          "url": "ble-characteristic-u2a49-0.2.0.jar",
          "size": 2443,
          "sha512": "9ec2b8ff8ed8c7a07e8212a1f4f2596917f9001adba4cd6e395d004f9b98046f03859b02db4ca0258af2f623da8e6606713625cea8bf02f9ea6b9ab4af56b86d",
          "sha256": "908601e2bf915903d11a91d25ff5fa53ad9e272ade7c289b5c7192b6b65d2ca2",
          "sha1": "29fcd02635a8eeccb0b5e7745eeae0b7fa873c47",
          "md5": "8bd35b3b09bb77c83cae0f5fcb6f4c72"
        }
      ]
    }
  ]
}
