{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc3",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc3-0.8.10.jar",
          "url": "ble-characteristic-u2bc3-0.8.10.jar",
          "size": 1900,
          "sha512": "6846561baf1a712804ca74bc311e57804ee710d60ff02740b944904449796642488dd78c32bd6410ccb8ec903795a01a3190732e34d4feaef508481ee009f863",
          "sha256": "4445d1e5ed909b13c98464be052369a117d297a93effa5c9da45276ef14edbe0",
          "sha1": "017179537ace890974876f2a90872d4be5998547",
          "md5": "3998868dfc2afd29fed8f022047480e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc3-0.8.10.jar",
          "url": "ble-characteristic-u2bc3-0.8.10.jar",
          "size": 1900,
          "sha512": "6846561baf1a712804ca74bc311e57804ee710d60ff02740b944904449796642488dd78c32bd6410ccb8ec903795a01a3190732e34d4feaef508481ee009f863",
          "sha256": "4445d1e5ed909b13c98464be052369a117d297a93effa5c9da45276ef14edbe0",
          "sha1": "017179537ace890974876f2a90872d4be5998547",
          "md5": "3998868dfc2afd29fed8f022047480e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc3-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2bc3-0.8.10-javadoc.jar",
          "size": 109535,
          "sha512": "bcfdc5489b860d5448312818adad02e16f4985f3fac8347deced2033b3f7d3aace4cea05709f75f00b793b8f4c03f1f3247a680b9993a403b0bd31a48a3d385c",
          "sha256": "aa982dea840d3c3c9f7a1038b3be7ee0bf07dddd13c2aabb2e8860c55e1e9084",
          "sha1": "3a761ec7af937a1fa5a16e874987a24de2cc795f",
          "md5": "3f29e65e686d96b7ffafe49548266099"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc3-0.8.10-sources.jar",
          "url": "ble-characteristic-u2bc3-0.8.10-sources.jar",
          "size": 1709,
          "sha512": "5aa7ac7343f7ff60ed170c0c46c945c5d395b4a130fdb5a95d70d83160a41c51ca5ed2a75f6710b881acc458eb729641324dbba526cbf4ee87d2db3a06f25c2b",
          "sha256": "cec826be4cb814b725db466f0ba93537cf8c5343c12c6653d72d5ec2c78e107f",
          "sha1": "2185980a7fb6ebf9bdc9bc8ec2559f40652676fa",
          "md5": "928f36b3ae9545c83c3164c709d5babd"
        }
      ]
    }
  ]
}
