{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bbe-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bbe",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbe-android-0.8.12.aar",
          "url": "ble-characteristic-u2bbe-android-0.8.12.aar",
          "size": 3150,
          "sha512": "8bb5712b5680b66f66c6685c2a126ebf62ae6cfe7e28d3edb5380fe28b41e20b1a565153966850d73e752b2858773702081ae18dba6af70e47a59d8a9155eee8",
          "sha256": "69ff63be30f4277e319baed36adf4f7082e1faf8fb5c91f484036be164e5ca36",
          "sha1": "947475d4d0c12eaf438927dff3eb2a306f5ca970",
          "md5": "77669fcac7ab6e59d5a9d26e633cea1a"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bbe",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbe-android-0.8.12.aar",
          "url": "ble-characteristic-u2bbe-android-0.8.12.aar",
          "size": 3150,
          "sha512": "8bb5712b5680b66f66c6685c2a126ebf62ae6cfe7e28d3edb5380fe28b41e20b1a565153966850d73e752b2858773702081ae18dba6af70e47a59d8a9155eee8",
          "sha256": "69ff63be30f4277e319baed36adf4f7082e1faf8fb5c91f484036be164e5ca36",
          "sha1": "947475d4d0c12eaf438927dff3eb2a306f5ca970",
          "md5": "77669fcac7ab6e59d5a9d26e633cea1a"
        }
      ]
    }
  ]
}
