{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad8",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.12.jar",
          "url": "ble-characteristic-u2ad8-0.8.12.jar",
          "size": 1935,
          "sha512": "907a0edf94d6259236b81ce0f88cc37639061ee1fbb62528a2012433583360329e466f716ff46f1e5e4057396a3b29be8733119fd78b4c4a007292a85d1617db",
          "sha256": "4121a0de737735450f7d5d4849fc3eaee8485e9e21255610396618f5df69f773",
          "sha1": "b072a95543fa544504e4aeca546b5473af4177c8",
          "md5": "4c44ce76750097dbb2fc0d31d0a95e7e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.12.jar",
          "url": "ble-characteristic-u2ad8-0.8.12.jar",
          "size": 1935,
          "sha512": "907a0edf94d6259236b81ce0f88cc37639061ee1fbb62528a2012433583360329e466f716ff46f1e5e4057396a3b29be8733119fd78b4c4a007292a85d1617db",
          "sha256": "4121a0de737735450f7d5d4849fc3eaee8485e9e21255610396618f5df69f773",
          "sha1": "b072a95543fa544504e4aeca546b5473af4177c8",
          "md5": "4c44ce76750097dbb2fc0d31d0a95e7e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2ad8-0.8.12-javadoc.jar",
          "size": 107599,
          "sha512": "df8237e03f2a2f2de65c68e583f872b4070c5b9c185514b267ec45d0c67b14ac6555c928a1427fe4f436358413992868b2f66d417b1976e5796c7d595e0be022",
          "sha256": "526d9a52ba6877b77ff497eee992292f575d9a84c64e0c9af3bb8bddf8df4593",
          "sha1": "f42206bcace527509a1b2e3cd3aba71cc1c82957",
          "md5": "0abb7aff7798387073da399a1df245a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.12-sources.jar",
          "url": "ble-characteristic-u2ad8-0.8.12-sources.jar",
          "size": 1752,
          "sha512": "0105676f116a4b913a92007865d2aeace3b7b303a806212df9d3e5d6b13f5a6f721909bcf00582b984b49438afd240ae3b481e1e400f1d74dbf967fd2041133b",
          "sha256": "e4ef71bdc15e891d9b436b4498f286ce8ded959b10170920133d455f4e0df91c",
          "sha1": "e0370dee2b5979c7c7c6fad697c02eb1f1f11e84",
          "md5": "f7de5f90a0b77587089dae9f8d790321"
        }
      ]
    }
  ]
}
