{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a32-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.8.12.aar",
          "url": "ble-characteristic-u2a32-android-0.8.12.aar",
          "size": 3188,
          "sha512": "7ecccac0eba3091cd7b33b8a396f5745d621b2275013db620cdf02cd32025350c45befbfeb0492fbc8668b6137483489c7c79f1800379920a5df95d58b3b449c",
          "sha256": "a6db16827d9c8ebf2af5f68fd4cca5b71c310f4d523b019f27fac4a9fac1b068",
          "sha1": "8ee13e8add8aa18baa4d1b8fb086cec8e75e5cd8",
          "md5": "06a33dba1ab451c56abd98f2e1543f76"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.8.12.aar",
          "url": "ble-characteristic-u2a32-android-0.8.12.aar",
          "size": 3188,
          "sha512": "7ecccac0eba3091cd7b33b8a396f5745d621b2275013db620cdf02cd32025350c45befbfeb0492fbc8668b6137483489c7c79f1800379920a5df95d58b3b449c",
          "sha256": "a6db16827d9c8ebf2af5f68fd4cca5b71c310f4d523b019f27fac4a9fac1b068",
          "sha1": "8ee13e8add8aa18baa4d1b8fb086cec8e75e5cd8",
          "md5": "06a33dba1ab451c56abd98f2e1543f76"
        }
      ]
    }
  ]
}
