{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b90",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.5.jar",
          "url": "ble-characteristic-u2b90-0.8.5.jar",
          "size": 1440,
          "sha512": "46393bc07e7f202b859c90a77c5668333a6c32d715eb7329c1c7b7170fcc986d1b72f57022085bb76e3c965404179e070e5decee8ece5638160dacff1df1ce5b",
          "sha256": "a861e698693863ae6de1b5fb4246d2e8275b47cd96fce998c4ad1e74a984c299",
          "sha1": "3633c7746a510972fd8927a08cbee4951dcbaf02",
          "md5": "c3a10a792fe9ad9b903820695a1dffab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.5.jar",
          "url": "ble-characteristic-u2b90-0.8.5.jar",
          "size": 1440,
          "sha512": "46393bc07e7f202b859c90a77c5668333a6c32d715eb7329c1c7b7170fcc986d1b72f57022085bb76e3c965404179e070e5decee8ece5638160dacff1df1ce5b",
          "sha256": "a861e698693863ae6de1b5fb4246d2e8275b47cd96fce998c4ad1e74a984c299",
          "sha1": "3633c7746a510972fd8927a08cbee4951dcbaf02",
          "md5": "c3a10a792fe9ad9b903820695a1dffab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b90-0.8.5-javadoc.jar",
          "size": 107114,
          "sha512": "9fae8b77bff3c620cc70e5ced16fbf84aab1e52a419217c949e62eb52c46f580e4a7d4d4fe35d2cf8abb3c18e87e49c5dfb542906546600838370d1bd067880e",
          "sha256": "bbf3084968bfd0adda8916378ff87b8624fcee5772b9f839c0fce253328758e8",
          "sha1": "98ea2f3be80895ecf5429be49f1c3f4abc007410",
          "md5": "785185fd65c8ab4b3fc49c375e538ed1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b90-0.8.5-sources.jar",
          "size": 1421,
          "sha512": "569d005eed9e91894a1579ce49a8b2355688bb08fb87a1dc766231fc62471885a7a13a95a427e835987ba09208efb98df3fdbdb886190d024ad2e780c2eaa809",
          "sha256": "bac9351bab7674b50c2a145a695d77ee171005a723cfebbab5d46757e5eb4edb",
          "sha1": "5b4e2d5cc63cfc4097a0d9c2fe7a5d56388f565e",
          "md5": "d0a293ac06b6df8a01207c76bec3ed3d"
        }
      ]
    }
  ]
}
