{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-cps-central-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-central-android-0.1.1.aar",
          "url": "ble-service-cps-central-android-0.1.1.aar",
          "size": 7546,
          "sha512": "24cc8411a233b170391e4b78bbb2858aac652e9c7dda64293974bcc960420ba271d5d10ac6044e1d20ba32dda2d2d5b393781fccef998ea534b71f18307d398b",
          "sha256": "925c7c331a3f3ea0a6d3cc8ec05070fa7d848cd650419889a01c1f796c1bf54f",
          "sha1": "66d5b98eebfcde086f78dffe9966855da1944a6d",
          "md5": "4cabc69b0b76da10d83fae5bc251cf79"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-central-android-0.1.1.aar",
          "url": "ble-service-cps-central-android-0.1.1.aar",
          "size": 7546,
          "sha512": "24cc8411a233b170391e4b78bbb2858aac652e9c7dda64293974bcc960420ba271d5d10ac6044e1d20ba32dda2d2d5b393781fccef998ea534b71f18307d398b",
          "sha256": "925c7c331a3f3ea0a6d3cc8ec05070fa7d848cd650419889a01c1f796c1bf54f",
          "sha1": "66d5b98eebfcde086f78dffe9966855da1944a6d",
          "md5": "4cabc69b0b76da10d83fae5bc251cf79"
        }
      ]
    }
  ]
}
