{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a09",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a09-0.8.9.jar",
          "url": "ble-characteristic-u2a09-0.8.9.jar",
          "size": 1590,
          "sha512": "66dd5a28b61c2c0c996e28c3c5d15a17608547126d6fa180355f4dee649127e085bf66ca338cc94de3ecf605fda909acaed770bd514dccb0e26edef002099d12",
          "sha256": "2a04b4c9a3b629aa39155f8d83cfa8b0c7dbb1e23d871ff58ba42166e040d4a4",
          "sha1": "e141583792a950c2cecb17cd98e8215577f3a3cf",
          "md5": "a49ebcf87396cba3d9286cc0b346a0f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a09-0.8.9.jar",
          "url": "ble-characteristic-u2a09-0.8.9.jar",
          "size": 1590,
          "sha512": "66dd5a28b61c2c0c996e28c3c5d15a17608547126d6fa180355f4dee649127e085bf66ca338cc94de3ecf605fda909acaed770bd514dccb0e26edef002099d12",
          "sha256": "2a04b4c9a3b629aa39155f8d83cfa8b0c7dbb1e23d871ff58ba42166e040d4a4",
          "sha1": "e141583792a950c2cecb17cd98e8215577f3a3cf",
          "md5": "a49ebcf87396cba3d9286cc0b346a0f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a09-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2a09-0.8.9-javadoc.jar",
          "size": 107358,
          "sha512": "53ee46859bfa3e8153b6f3ec85ca508a35bd68bb8e2a6e9adc0228cc94c4b157bc93f9d220c5fda6e2cf4e7d30c103609e9b56ce68208e7dc5accbabdcf700f9",
          "sha256": "7db6fca9a30bc5e3eac750aea67d9328b4bcd337adb532be27cca7598a5472e2",
          "sha1": "b3b8ea1435c461510284653eaa60eb9fb04c5a24",
          "md5": "f6e6cef3fdba65cef4a9d7f62a01b64e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a09-0.8.9-sources.jar",
          "url": "ble-characteristic-u2a09-0.8.9-sources.jar",
          "size": 1543,
          "sha512": "b762ca2eeb333cdb86fcdb3aa982a923724ec24fa37575b616c220eaf7cff35bb8e22fe7f60bf1ae55f373e2b58c92cd0b93f434890bdc12c8dc4f411960fb6d",
          "sha256": "13bdf60a122acaecc06308082c78db4057242c662953fb8150171cf729cfa6ea",
          "sha1": "5b8f2933939b535462d483426521881d553fe572",
          "md5": "f431fc7c148ef2df75982b7ba63975e4"
        }
      ]
    }
  ]
}
