{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a31",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a31-0.4.4.jar",
          "url": "ble-characteristic-u2a31-0.4.4.jar",
          "size": 1855,
          "sha512": "2a030d4cc457cebaaee0cac686eaf4c0ec508ab1574b2b4e3fc611f999577a3ee4d1913d5ca39c92a6fb6c0e405f255cbef8630e50f221d2d8d2006d4b85d491",
          "sha256": "2148b37b6f92c2e7a6704b7f92722891494e0c90da400d9f4ad653adfc35c7ba",
          "sha1": "aad5eb94c8535a2f118324ef8d85798d47fe046b",
          "md5": "eb447670ea9114f824213c5b4b363eca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a31-0.4.4.jar",
          "url": "ble-characteristic-u2a31-0.4.4.jar",
          "size": 1855,
          "sha512": "2a030d4cc457cebaaee0cac686eaf4c0ec508ab1574b2b4e3fc611f999577a3ee4d1913d5ca39c92a6fb6c0e405f255cbef8630e50f221d2d8d2006d4b85d491",
          "sha256": "2148b37b6f92c2e7a6704b7f92722891494e0c90da400d9f4ad653adfc35c7ba",
          "sha1": "aad5eb94c8535a2f118324ef8d85798d47fe046b",
          "md5": "eb447670ea9114f824213c5b4b363eca"
        }
      ]
    }
  ]
}
