{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-blp-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-blp-android-0.4.0.aar",
          "url": "ble-profile-blp-android-0.4.0.aar",
          "size": 1184,
          "sha512": "28e4494ebee94b137104182daae3720664ae7cdcda3d12922202cffc564b2645e6c3827a025d6447f8ffb0cae733e21ce3fa7a67a638cd1954d0810ef923f6ee",
          "sha256": "a3d352cab1f5d725ca46d81c1ed9cab843cabaafb289e4a85147682d6e2459ed",
          "sha1": "9443047d7040e859a570ed6f9b2efcb4a349d853",
          "md5": "ad396263ced34b2337754e2853705142"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-blp-android-0.4.0.aar",
          "url": "ble-profile-blp-android-0.4.0.aar",
          "size": 1184,
          "sha512": "28e4494ebee94b137104182daae3720664ae7cdcda3d12922202cffc564b2645e6c3827a025d6447f8ffb0cae733e21ce3fa7a67a638cd1954d0810ef923f6ee",
          "sha256": "a3d352cab1f5d725ca46d81c1ed9cab843cabaafb289e4a85147682d6e2459ed",
          "sha1": "9443047d7040e859a570ed6f9b2efcb4a349d853",
          "md5": "ad396263ced34b2337754e2853705142"
        }
      ]
    }
  ]
}
