{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4f-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4f",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4f-android-0.2.6.aar",
          "url": "ble-characteristic-u2a4f-android-0.2.6.aar",
          "size": 3117,
          "sha512": "0ab28f8b08b91b0d987421e152f6fb7b16e5ebecd5c6de0d58e008e189f2451fbe9d3793081d6e894aa85beeee00ee294960f791000c5a229f94993b8fb633dc",
          "sha256": "642758ad5b846f060585e21a996d52efe59b88268291acdf023b6268c6413d0c",
          "sha1": "008a044b9b19057fafdd5060e23b633b2d469b91",
          "md5": "a45e91c0f1878373f5f71c3ee8653571"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4f",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4f-android-0.2.6.aar",
          "url": "ble-characteristic-u2a4f-android-0.2.6.aar",
          "size": 3117,
          "sha512": "0ab28f8b08b91b0d987421e152f6fb7b16e5ebecd5c6de0d58e008e189f2451fbe9d3793081d6e894aa85beeee00ee294960f791000c5a229f94993b8fb633dc",
          "sha256": "642758ad5b846f060585e21a996d52efe59b88268291acdf023b6268c6413d0c",
          "sha1": "008a044b9b19057fafdd5060e23b633b2d469b91",
          "md5": "a45e91c0f1878373f5f71c3ee8653571"
        }
      ]
    }
  ]
}
