{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b84",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b84-0.8.5.jar",
          "url": "ble-characteristic-u2b84-0.8.5.jar",
          "size": 2108,
          "sha512": "7637c7eb9db3327ae2913d709bfd1f5298ffa3937bf496ab3a21d73cbc512362d925d5f0e8884514148bf7eb00f259a1cb28380c9063179b2ee14c45bb5fbd8f",
          "sha256": "ca842552bff3b05ae0edb1ed743fd9cc6a49f5869311ab7ef5116aeb4bd1fe9b",
          "sha1": "60ca0a68063bd2ba74430ead69a3c1ee7d3ab9eb",
          "md5": "d87e43917fbe871f98690e7097c33868"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b84-0.8.5.jar",
          "url": "ble-characteristic-u2b84-0.8.5.jar",
          "size": 2108,
          "sha512": "7637c7eb9db3327ae2913d709bfd1f5298ffa3937bf496ab3a21d73cbc512362d925d5f0e8884514148bf7eb00f259a1cb28380c9063179b2ee14c45bb5fbd8f",
          "sha256": "ca842552bff3b05ae0edb1ed743fd9cc6a49f5869311ab7ef5116aeb4bd1fe9b",
          "sha1": "60ca0a68063bd2ba74430ead69a3c1ee7d3ab9eb",
          "md5": "d87e43917fbe871f98690e7097c33868"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b84-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b84-0.8.5-javadoc.jar",
          "size": 109911,
          "sha512": "699c97eeef35f957e04c39f386c2ebe5b4fd5cf2a798ec2ff60b879797beb2240ace6b05f4599b648d75169e2b5878406013648b466997acd75335532d18506e",
          "sha256": "e5b3539c2ee87a8dcc50e22c6c1a7315989decc69cbb31c0aa2f6f2cebb941a2",
          "sha1": "9365a5a56ab1ecc581bb9b6803b76ffbd31943d1",
          "md5": "23eaeb68033eaf5543114deb798f58ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b84-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b84-0.8.5-sources.jar",
          "size": 1870,
          "sha512": "d02bfdb7b499c70d75ba919b4b2ed06f446a8341ad7fb69f7996214c83d9f71224760663714d6718014c8ca313bffddc518e09b850898082ff2ac155b281c925",
          "sha256": "b4d9557f0565d460bbb04974d2ac84cddb7bdecb38b3fc2612f8c03de91912da",
          "sha1": "4c95dd4f68559ba48b2e1e4e6cc51c4a45049053",
          "md5": "0142b3d67fafa00c1330848f764309a1"
        }
      ]
    }
  ]
}
