{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afc-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afc",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afc-android-0.4.5.aar",
          "url": "ble-characteristic-u2afc-android-0.4.5.aar",
          "size": 3116,
          "sha512": "b1ae4fdab4049650990fcdcc2708a3a11846f4f8ad3047ccfcb7f3b8f218ae3e2c102e19bd7eb0212bb342f0f364d557ed9e57f00c8cb236938b27b769f03263",
          "sha256": "ef7133b24e292ece11a87521b99680bdae5f7749c4b17cea9990e08a98d40c37",
          "sha1": "d691d2884fe44bddc4fc8907524cf9818c2c17ca",
          "md5": "18ef2272bc00c7684007324f73b4c8e6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2afc",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afc-android-0.4.5.aar",
          "url": "ble-characteristic-u2afc-android-0.4.5.aar",
          "size": 3116,
          "sha512": "b1ae4fdab4049650990fcdcc2708a3a11846f4f8ad3047ccfcb7f3b8f218ae3e2c102e19bd7eb0212bb342f0f364d557ed9e57f00c8cb236938b27b769f03263",
          "sha256": "ef7133b24e292ece11a87521b99680bdae5f7749c4b17cea9990e08a98d40c37",
          "sha1": "d691d2884fe44bddc4fc8907524cf9818c2c17ca",
          "md5": "18ef2272bc00c7684007324f73b4c8e6"
        }
      ]
    }
  ]
}
