{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a29-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.3.aar",
          "url": "ble-characteristic-u2a29-android-0.2.3.aar",
          "size": 3130,
          "sha512": "587a7f1b23dfbfb05ae38ed4d33d7b00b073fb702c9ee469ca50c821682f03c5f1561b665429b68e577850a8c3a0decf9faad3ed2e0893f68429cb465869538c",
          "sha256": "e4b78ea22b72cef4c9abe154e8b99d247f154c5f6c55a782a7fe4904c03a9d8f",
          "sha1": "95082cca4ed58c586ef33dc7dd669dabfa287da6",
          "md5": "4f20a3cd147028958ce846c722136c5a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.2.3.aar",
          "url": "ble-characteristic-u2a29-android-0.2.3.aar",
          "size": 3130,
          "sha512": "587a7f1b23dfbfb05ae38ed4d33d7b00b073fb702c9ee469ca50c821682f03c5f1561b665429b68e577850a8c3a0decf9faad3ed2e0893f68429cb465869538c",
          "sha256": "e4b78ea22b72cef4c9abe154e8b99d247f154c5f6c55a782a7fe4904c03a9d8f",
          "sha1": "95082cca4ed58c586ef33dc7dd669dabfa287da6",
          "md5": "4f20a3cd147028958ce846c722136c5a"
        }
      ]
    }
  ]
}
