{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b29",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b29-0.8.13.jar",
          "url": "ble-characteristic-u2b29-0.8.13.jar",
          "size": 1897,
          "sha512": "bc923797a0d0876b181886f61ac31e7fe2ab9119470e583b6d78e2a11f9d2070d126a1689a16ad46329f7251fd0fd10731601d02e255b2a9bfe09b091fd50a68",
          "sha256": "221c1882c89d420a4e7fd4294fba8dc476de06221b8e64d92fd4f9a2ad9c4795",
          "sha1": "a00c120ace9c9ef1e84498780935d3a424431bbe",
          "md5": "1c783894670de41b737a885074b7e9c2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b29-0.8.13.jar",
          "url": "ble-characteristic-u2b29-0.8.13.jar",
          "size": 1897,
          "sha512": "bc923797a0d0876b181886f61ac31e7fe2ab9119470e583b6d78e2a11f9d2070d126a1689a16ad46329f7251fd0fd10731601d02e255b2a9bfe09b091fd50a68",
          "sha256": "221c1882c89d420a4e7fd4294fba8dc476de06221b8e64d92fd4f9a2ad9c4795",
          "sha1": "a00c120ace9c9ef1e84498780935d3a424431bbe",
          "md5": "1c783894670de41b737a885074b7e9c2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b29-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2b29-0.8.13-javadoc.jar",
          "size": 88542,
          "sha512": "771bf2033cfab31a46eca5d487b1322b99c9f85314c6168c682cdf7c5596bb3a8c2ed9b935a42dde54f0498c2bbd4a33aeb3ce9d48429dbceee713f7dc6eccd7",
          "sha256": "99ef86c943f6926d11e307daecdf309bb32205782f4a9887118e3d070c6a2dd1",
          "sha1": "c56983f8c0c63e5f2e31eb58571cb53bd951f5be",
          "md5": "b6e5b04bac348c7a931b9290de58d423"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b29-0.8.13-sources.jar",
          "url": "ble-characteristic-u2b29-0.8.13-sources.jar",
          "size": 1772,
          "sha512": "4ec5e2d7b579c928dcbe5153a015c01c82bcd96f13db0bc7b54c3fcf5d549890725056a80a1170e97cd56ae28c254488520911dac549d02c8c885f922d4ce343",
          "sha256": "130567046a67cd86730e332c2c47c5ce2b3dc18b4e4f62346f83def80804306b",
          "sha1": "c312628179fcd2331433bef7ed6517bec0fb0720",
          "md5": "38e7b298605af7365eff2345b10d6943"
        }
      ]
    }
  ]
}
