{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a14-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "didsxcdw7raejas3g75ob27utq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a14",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a14-android-0.2.5.aar",
          "url": "ble-characteristic-u2a14-android-0.2.5.aar",
          "size": 3178,
          "sha512": "01facec403aa5c64a0162c0f0ba73e4fca7b87f4d93d14670bf7d3442ea0461d9f025921b6c759a10f7ec234ad12e572de286686125ac8db7ad9ffeb198848ab",
          "sha256": "434b7b8c819a204d3e5a66026e13ba0de58c0c4cf3ecf21715edc3ec7e381533",
          "sha1": "f9d61cdc4022328a07f6ad14c9a5f8d881d1880b",
          "md5": "156d06f3224b7322621906955ee165d2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a14",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a14-android-0.2.5.aar",
          "url": "ble-characteristic-u2a14-android-0.2.5.aar",
          "size": 3178,
          "sha512": "01facec403aa5c64a0162c0f0ba73e4fca7b87f4d93d14670bf7d3442ea0461d9f025921b6c759a10f7ec234ad12e572de286686125ac8db7ad9ffeb198848ab",
          "sha256": "434b7b8c819a204d3e5a66026e13ba0de58c0c4cf3ecf21715edc3ec7e381533",
          "sha1": "f9d61cdc4022328a07f6ad14c9a5f8d881d1880b",
          "md5": "156d06f3224b7322621906955ee165d2"
        }
      ]
    }
  ]
}
