{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9c-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9c",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9c-android-0.8.11.aar",
          "url": "ble-characteristic-u2b9c-android-0.8.11.aar",
          "size": 3193,
          "sha512": "2b5779688d198d9f42abce1d54640076fa26696a586535630f0f86795e00bbcceaa05875037ffd85e90d94d4234888856e2f21ec0fc2568f4146c610e6004bcf",
          "sha256": "09ec49f79286bbea72fd5e0a4bccda9d2c0eb9ee5e17c034f26b10e7b9de7b70",
          "sha1": "bac5c206ca2168e95ba79f8c7ec5c81e7f76e4f3",
          "md5": "05f5b7ad1e92a8a0c79bc51ecd193340"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9c",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9c-android-0.8.11.aar",
          "url": "ble-characteristic-u2b9c-android-0.8.11.aar",
          "size": 3193,
          "sha512": "2b5779688d198d9f42abce1d54640076fa26696a586535630f0f86795e00bbcceaa05875037ffd85e90d94d4234888856e2f21ec0fc2568f4146c610e6004bcf",
          "sha256": "09ec49f79286bbea72fd5e0a4bccda9d2c0eb9ee5e17c034f26b10e7b9de7b70",
          "sha1": "bac5c206ca2168e95ba79f8c7ec5c81e7f76e4f3",
          "md5": "05f5b7ad1e92a8a0c79bc51ecd193340"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9c-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2b9c-android-0.8.11-sources.jar",
          "size": 2207,
          "sha512": "1df4c9713ec10a6e09d90b193c0228a7120b3824846b89bec0467b9e52faf28d53fa890f4bcbad14854bca688983a54a6b8a1f7b8504b4a4b1704131b468cceb",
          "sha256": "99c55932d8b8ffc2393ff9ac8bb0c3e57353178cf1e18965cfb28878f016fce8",
          "sha1": "cd9ec65bc6aa36b3c227029bc475329b883c6563",
          "md5": "6808f55165037c66d3364c12cee4499a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b9c-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2b9c-android-0.8.11-javadoc.jar",
          "size": 270662,
          "sha512": "8c24980836dfd8d63038d0bdc0692ef4189e0849a380b64cf941d7c36bd006a9f3537a8c0d63b82e7dca3fa0e7246eb6d08adbf4a9039ff7aa7f997e560cde44",
          "sha256": "29683dae93dd31e294f3ed054b786e5ccb86b08e11c84e035556b1c5c08d1139",
          "sha1": "bf47b29e7833b26458f95e27493ee873562d3df9",
          "md5": "ef61390ded3c834122931cbdab84f162"
        }
      ]
    }
  ]
}
