{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4c-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4c",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4c-android-0.4.2.aar",
          "url": "ble-characteristic-u2a4c-android-0.4.2.aar",
          "size": 3121,
          "sha512": "31ade37deec033d5b2c28f75e4c7c8788dcdadaebcaf57524fd4840650b6e9129878b5f77b6c2f245e5f929e6d3d7f79937f79db047ac2659d14cf557219c580",
          "sha256": "6f14eac9af35e07e5edb9d2b4fdc0192370bf68a2b01b1cae93ec5974e8d7754",
          "sha1": "9da913fefb67c29337a1576b38a801c733e7f500",
          "md5": "f7d1221a5059ad35e062d3cdf13887be"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4c",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4c-android-0.4.2.aar",
          "url": "ble-characteristic-u2a4c-android-0.4.2.aar",
          "size": 3121,
          "sha512": "31ade37deec033d5b2c28f75e4c7c8788dcdadaebcaf57524fd4840650b6e9129878b5f77b6c2f245e5f929e6d3d7f79937f79db047ac2659d14cf557219c580",
          "sha256": "6f14eac9af35e07e5edb9d2b4fdc0192370bf68a2b01b1cae93ec5974e8d7754",
          "sha1": "9da913fefb67c29337a1576b38a801c733e7f500",
          "md5": "f7d1221a5059ad35e062d3cdf13887be"
        }
      ]
    }
  ]
}
