{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2909-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2909",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2909-android-0.8.6.aar",
          "url": "ble-descriptor-u2909-android-0.8.6.aar",
          "size": 3073,
          "sha512": "aa8bb7fefe4eaf9e19df3685a379bf46cfcdb6952ed61df0cbf1232d2754dc38f560d3146f13d615caf84a8480a19a02a8e44ef4c7d598d7d1163a247e358229",
          "sha256": "abba485362b06a7223977aa4365013e1376a7e96b51ddef045ce287b7aece7b4",
          "sha1": "5adcc60c2c8756e8bd04c3081f719481bae22d53",
          "md5": "4e5826291706aab2e6f17d7145d583ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2909",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2909-android-0.8.6.aar",
          "url": "ble-descriptor-u2909-android-0.8.6.aar",
          "size": 3073,
          "sha512": "aa8bb7fefe4eaf9e19df3685a379bf46cfcdb6952ed61df0cbf1232d2754dc38f560d3146f13d615caf84a8480a19a02a8e44ef4c7d598d7d1163a247e358229",
          "sha256": "abba485362b06a7223977aa4365013e1376a7e96b51ddef045ce287b7aece7b4",
          "sha1": "5adcc60c2c8756e8bd04c3081f719481bae22d53",
          "md5": "4e5826291706aab2e6f17d7145d583ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2909-android-0.8.6-sources.jar",
          "url": "ble-descriptor-u2909-android-0.8.6-sources.jar",
          "size": 2141,
          "sha512": "37c92e3f100684f8573aa099718ac8a22e8b5cecff386c7b551afbb664e127b9dcbad9a35dab19dc3160aa7d9b32d1c2a2a95a4e5414a4582d2d5f0d8abb92cf",
          "sha256": "126862e56c362f923d7a084e1fa354578216f74ce32aaf6ef5de27de32b311ad",
          "sha1": "d7056aa0a9062730947c8391f3941dc0cf21b52b",
          "md5": "174a82e4056b2ae2358fc057e1cf2372"
        }
      ]
    }
  ]
}
