{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b7d-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7d",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7d-android-0.8.11.aar",
          "url": "ble-characteristic-u2b7d-android-0.8.11.aar",
          "size": 3132,
          "sha512": "64e53abe71bcf58d2da400a9deea7755f2f44a59ab1dd88198bca0947b941d1d26bc023e6186637cc25f4d1421123c20f14738ce58802d5b16825de243c8b8e8",
          "sha256": "9aa49a8d94e08483a0d58370c95b55e363a7635162106926a5bc55ae5c4b1d0f",
          "sha1": "c9e8e030f532f166c0f8ecb33d7dec4796a55a91",
          "md5": "8816c979db7088e88faac1445c6b9bd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7d",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7d-android-0.8.11.aar",
          "url": "ble-characteristic-u2b7d-android-0.8.11.aar",
          "size": 3132,
          "sha512": "64e53abe71bcf58d2da400a9deea7755f2f44a59ab1dd88198bca0947b941d1d26bc023e6186637cc25f4d1421123c20f14738ce58802d5b16825de243c8b8e8",
          "sha256": "9aa49a8d94e08483a0d58370c95b55e363a7635162106926a5bc55ae5c4b1d0f",
          "sha1": "c9e8e030f532f166c0f8ecb33d7dec4796a55a91",
          "md5": "8816c979db7088e88faac1445c6b9bd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7d-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2b7d-android-0.8.11-sources.jar",
          "size": 2133,
          "sha512": "ae1a8112bc02743650fa04210e4364ad2f09fd6faf29d2946147bcf7b7d16df60a9d129e21685abd22db189785ab11e915f6a6290c93b54a7f8f83265e0e600f",
          "sha256": "ae141fe0002f08a145aea501ef18321d8682ff82ef3a1cf82bae7a54bb9f8baf",
          "sha1": "4f36a130ca97ead6f80f06b0b0366f8ad3bd7bd8",
          "md5": "da61046643c27cbc6a11a38f40d0bba6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7d-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2b7d-android-0.8.11-javadoc.jar",
          "size": 270481,
          "sha512": "ac95a42b39bd3628c441ab5cd9bec28171d258adcd88dc2738fc5181b24c5001b23df0ab6e1e04426c46d5015f5708430b744384a336196f1ac7352077835317",
          "sha256": "82fa8f269dad49a57fbbea49d6549148aee98536dac0beb735b167b653f186dc",
          "sha1": "61cb4b5160819e6683b4e4efcb97fec2d9bb8779",
          "md5": "41ba7b63d82cae9bfdcd61a043a70ac3"
        }
      ]
    }
  ]
}
