{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a48-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.9.aar",
          "url": "ble-characteristic-u2a48-android-0.2.9.aar",
          "size": 3291,
          "sha512": "f5eb814533c5131228cbed8807c3a98cabe4cea1094f20300db89169d84a040a3157a5f125c287638375d463de8c25bfe48d369a0d3246317273f5c9371635c4",
          "sha256": "05a0291fba6e9c23b704cc0e77852f1db8e6f9b8ae2de25cc2567218a3b4346f",
          "sha1": "bbb0f8b45cb4fb9e8feb1d965aa479e6cf736308",
          "md5": "e9562ffa3aa227b63daf30b2edad693e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48",
          "version": {
            "requires": "0.2.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-android-0.2.9.aar",
          "url": "ble-characteristic-u2a48-android-0.2.9.aar",
          "size": 3291,
          "sha512": "f5eb814533c5131228cbed8807c3a98cabe4cea1094f20300db89169d84a040a3157a5f125c287638375d463de8c25bfe48d369a0d3246317273f5c9371635c4",
          "sha256": "05a0291fba6e9c23b704cc0e77852f1db8e6f9b8ae2de25cc2567218a3b4346f",
          "sha1": "bbb0f8b45cb4fb9e8feb1d965aa479e6cf736308",
          "md5": "e9562ffa3aa227b63daf30b2edad693e"
        }
      ]
    }
  ]
}
