{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aad",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.7.jar",
          "url": "ble-characteristic-u2aad-0.8.7.jar",
          "size": 1772,
          "sha512": "ee6143e21cc5419d27354d4ae9f5c7fe43c5b3865d8186b12f48500179977cca336fc8cf75eb3794191a7d61cdd1119310d0726daea1d505f65e1c5bf239281d",
          "sha256": "0d742caf428f1ec5cb6ecf72a8fca132f082dc03d129bbe080638cd094f4c9f7",
          "sha1": "ff26b44cb6cf0c5238b28cc1c42b69afa3abe86c",
          "md5": "584fcbbc57c0b74cd7c0e68c041536f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.7.jar",
          "url": "ble-characteristic-u2aad-0.8.7.jar",
          "size": 1772,
          "sha512": "ee6143e21cc5419d27354d4ae9f5c7fe43c5b3865d8186b12f48500179977cca336fc8cf75eb3794191a7d61cdd1119310d0726daea1d505f65e1c5bf239281d",
          "sha256": "0d742caf428f1ec5cb6ecf72a8fca132f082dc03d129bbe080638cd094f4c9f7",
          "sha1": "ff26b44cb6cf0c5238b28cc1c42b69afa3abe86c",
          "md5": "584fcbbc57c0b74cd7c0e68c041536f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2aad-0.8.7-javadoc.jar",
          "size": 107484,
          "sha512": "022b25a40889f35292586445463b1a5f1b69bb46ada90cf1706f54cda091f4534cbfc5b50526a8829542d56d329aa1fc5ef1bfeddacdc4bbc2631a2f99fb1cbe",
          "sha256": "91ce98b5c9be4a81fc1fee1eac584966de003f93c3b528ad20be360d2a135d73",
          "sha1": "09b935b9c19a758696f646f8fc9692da69727bc5",
          "md5": "ee9f0a30dee70c5fdde8013cfaf02d79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aad-0.8.7-sources.jar",
          "url": "ble-characteristic-u2aad-0.8.7-sources.jar",
          "size": 1636,
          "sha512": "9ea51a6e0063add598e282c4f8c4de60afefdc0f885f18f7d2e0cf4ade90f052a5c0453d89e5027f63e58da57221ec5b028f5c102c17f827498a2a25aaf751ed",
          "sha256": "b6372cb129eb50093c89cc15b858d4b7f24719dff23afba226caebe7037797d6",
          "sha1": "c8d691f06ad0353517215072996778ed6b2facbc",
          "md5": "07b699fb05d5546da95f1710a547df74"
        }
      ]
    }
  ]
}
