{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a47",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jy7ixesazfhqnmjb55547uywfu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-0.1.0.jar",
          "url": "ble-characteristic-u2a47-0.1.0.jar",
          "size": 1874,
          "sha512": "4dbf886b527bdf7db7a1b5595e58c4437d6f4f9f04e614dc4891172a794f100d84bd4cf5830c4d48a85abfbbd3efe575508a9d5148dd378b52a0e320fa954683",
          "sha256": "67afd4a9c0d85c526aa35543c7fbefa2f1e07d2cde9c3b80b02e72efc1d4af25",
          "sha1": "39165bcfa1bfe9fdb1045e20037892fb7082a84f",
          "md5": "445ff1da176d0e8c8c7dc5eff7d57a3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-0.1.0.jar",
          "url": "ble-characteristic-u2a47-0.1.0.jar",
          "size": 1874,
          "sha512": "4dbf886b527bdf7db7a1b5595e58c4437d6f4f9f04e614dc4891172a794f100d84bd4cf5830c4d48a85abfbbd3efe575508a9d5148dd378b52a0e320fa954683",
          "sha256": "67afd4a9c0d85c526aa35543c7fbefa2f1e07d2cde9c3b80b02e72efc1d4af25",
          "sha1": "39165bcfa1bfe9fdb1045e20037892fb7082a84f",
          "md5": "445ff1da176d0e8c8c7dc5eff7d57a3d"
        }
      ]
    }
  ]
}
