{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a58-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a58",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a58-android-0.1.6.aar",
          "url": "ble-characteristic-u2a58-android-0.1.6.aar",
          "size": 3006,
          "sha512": "a6e6fb082cc0dc3374b198216c67a8b863430987be1263889900504350699a141beaa9dd21c0c9cab852b4819529db2c91f3173b9a4fe1e1e97f729e690cf9e9",
          "sha256": "35c3b977dbb68c0d20dea58f87adeb7b858570d7af4d01acb75e43a0ac70ef8d",
          "sha1": "07b937c1c092bf7b6ef24e6dfe594888998931a6",
          "md5": "9ec0e427ea22710eaa7b904dc02eec9a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a58",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a58-android-0.1.6.aar",
          "url": "ble-characteristic-u2a58-android-0.1.6.aar",
          "size": 3006,
          "sha512": "a6e6fb082cc0dc3374b198216c67a8b863430987be1263889900504350699a141beaa9dd21c0c9cab852b4819529db2c91f3173b9a4fe1e1e97f729e690cf9e9",
          "sha256": "35c3b977dbb68c0d20dea58f87adeb7b858570d7af4d01acb75e43a0ac70ef8d",
          "sha1": "07b937c1c092bf7b6ef24e6dfe594888998931a6",
          "md5": "9ec0e427ea22710eaa7b904dc02eec9a"
        }
      ]
    }
  ]
}
