{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a81",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "zr6ogsj4gnccripuontv3mz54u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-0.1.0.jar",
          "url": "ble-characteristic-u2a81-0.1.0.jar",
          "size": 1722,
          "sha512": "7a811250de9dc558e78eebd724c5a07afc54cce97a235a2e803433e19ab7afbbaeb3de4aea937004ea8519c7499bc8ef7b7283580fbdae9650938ed04c17449b",
          "sha256": "5ae277d572ab76680054656df01bd26a4558ea4ad070871ecf59d88eed9b1fe",
          "sha1": "e86c56ae9976a62b078abb97d25eef5bb80c5006",
          "md5": "f7bf0a2ddb4229db9a380a439fc6dd3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-0.1.0.jar",
          "url": "ble-characteristic-u2a81-0.1.0.jar",
          "size": 1722,
          "sha512": "7a811250de9dc558e78eebd724c5a07afc54cce97a235a2e803433e19ab7afbbaeb3de4aea937004ea8519c7499bc8ef7b7283580fbdae9650938ed04c17449b",
          "sha256": "5ae277d572ab76680054656df01bd26a4558ea4ad070871ecf59d88eed9b1fe",
          "sha1": "e86c56ae9976a62b078abb97d25eef5bb80c5006",
          "md5": "f7bf0a2ddb4229db9a380a439fc6dd3c"
        }
      ]
    }
  ]
}
