{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a25-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.1.aar",
          "url": "ble-characteristic-u2a25-android-0.2.1.aar",
          "size": 2926,
          "sha512": "210453cee28e6fb6f2bc3c093499cb4550e29e7e99b6e8d67e47352e6c5bfc5a097bac7134a0002c0c7a39cb0af809f9d43c75c5058da4563f2fff4002e0b292",
          "sha256": "370e4ae8424d7f452ada3ffb3ed96cf7550cd026f0120b353de20df9a6050a63",
          "sha1": "e593814174c32bb4449952383a346306daeeb5d9",
          "md5": "98d52f5d86f0c5ee29b4a4d5e4670024"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.1.aar",
          "url": "ble-characteristic-u2a25-android-0.2.1.aar",
          "size": 2926,
          "sha512": "210453cee28e6fb6f2bc3c093499cb4550e29e7e99b6e8d67e47352e6c5bfc5a097bac7134a0002c0c7a39cb0af809f9d43c75c5058da4563f2fff4002e0b292",
          "sha256": "370e4ae8424d7f452ada3ffb3ed96cf7550cd026f0120b353de20df9a6050a63",
          "sha1": "e593814174c32bb4449952383a346306daeeb5d9",
          "md5": "98d52f5d86f0c5ee29b4a4d5e4670024"
        }
      ]
    }
  ]
}
