{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b21-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b21",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b21-android-0.8.6.aar",
          "url": "ble-characteristic-u2b21-android-0.8.6.aar",
          "size": 3025,
          "sha512": "77badff8b22d34cb2b9bfcdfdcc811bd13e3fa94e1132cfab8092c2489d5c4242c606cc3724430ec92c874fe17f3ca42461f0ad7d84bc8aaf343590d455c6584",
          "sha256": "c961c27e79f0a2c98a108ac373cbdf2433468849cbfbdf6b8d89bf3e7d2a782d",
          "sha1": "dbd8f97d7881b957d133213f0206235971ecf8c2",
          "md5": "29dfc76a238cabc2f781e5017e7c438c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b21",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b21-android-0.8.6.aar",
          "url": "ble-characteristic-u2b21-android-0.8.6.aar",
          "size": 3025,
          "sha512": "77badff8b22d34cb2b9bfcdfdcc811bd13e3fa94e1132cfab8092c2489d5c4242c606cc3724430ec92c874fe17f3ca42461f0ad7d84bc8aaf343590d455c6584",
          "sha256": "c961c27e79f0a2c98a108ac373cbdf2433468849cbfbdf6b8d89bf3e7d2a782d",
          "sha1": "dbd8f97d7881b957d133213f0206235971ecf8c2",
          "md5": "29dfc76a238cabc2f781e5017e7c438c"
        }
      ]
    }
  ]
}
