{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd5",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.3.jar",
          "url": "ble-characteristic-u2bd5-0.8.3.jar",
          "size": 1948,
          "sha512": "dc8ce3439ed4fb2d7a2a74b2a2019a444f6d7478391cd7d49365c0663a056f8bf0ce98fb9e457233cdafe3862fec0e8786d083e99f8e535b46fa4cb69769b327",
          "sha256": "01040d893fb0292da27f1c689831f6f50fb4702858370606fc2d51ec8176c908",
          "sha1": "d1f0d2227498e657c0ddbac3b08dacc6356b0aba",
          "md5": "18cd9faf7b554787a103d0009e9c8588"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.3.jar",
          "url": "ble-characteristic-u2bd5-0.8.3.jar",
          "size": 1948,
          "sha512": "dc8ce3439ed4fb2d7a2a74b2a2019a444f6d7478391cd7d49365c0663a056f8bf0ce98fb9e457233cdafe3862fec0e8786d083e99f8e535b46fa4cb69769b327",
          "sha256": "01040d893fb0292da27f1c689831f6f50fb4702858370606fc2d51ec8176c908",
          "sha1": "d1f0d2227498e657c0ddbac3b08dacc6356b0aba",
          "md5": "18cd9faf7b554787a103d0009e9c8588"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2bd5-0.8.3-javadoc.jar",
          "size": 110718,
          "sha512": "2719f5095611c6ede10bb177d77fc2fc84e0bde115fcef6c222905e5a41ac82b521328c961ff1460f2f93ca82b3d467edfc2c57a86c214afb5809aea07a15641",
          "sha256": "d803f97b04d831739148de51ba084b6f3142b593db2f319b28766924475cd0d8",
          "sha1": "57dc33cc9c5a36f1f6982ec89986811bf472c23c",
          "md5": "169a98260d941ec1bf04acce206cadce"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.3-sources.jar",
          "url": "ble-characteristic-u2bd5-0.8.3-sources.jar",
          "size": 1970,
          "sha512": "5005a4a16d77ac34ca9b206a50a5cd2341ff5aecbb2bc962f87749b078560b737eea2c4632c610dd1a841de951861628401923f67bf69abbdf69d3ec89e3451e",
          "sha256": "581a253a502619110c68a1aff57b356ab5ddf3106f9ab11f143622fd9e354269",
          "sha1": "8bbd3b4ef7e84d76fcaa1b880042cd157f4b1b0e",
          "md5": "df669428cb09437898d8844001951fb7"
        }
      ]
    }
  ]
}
