{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7a-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7a",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7a-android-0.2.7.aar",
          "url": "ble-characteristic-u2a7a-android-0.2.7.aar",
          "size": 3066,
          "sha512": "568d5c1575714ee4e0f3bdf8c0a07374d8c868867255cd7a66fbb96463acad240e37caeeac2bd382247d0895ac2ee19455b423ac0a0c72d1381ff5812bb8b732",
          "sha256": "f989b47e8b9b933c699887e33f3e1dd665a2f4c6382d90db73e23f46a28e4981",
          "sha1": "1d5e7ce24ac9e66ab8630e5c532ac4856dd09614",
          "md5": "91cc7fb07ada3244937ee0688d655fa0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7a",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7a-android-0.2.7.aar",
          "url": "ble-characteristic-u2a7a-android-0.2.7.aar",
          "size": 3066,
          "sha512": "568d5c1575714ee4e0f3bdf8c0a07374d8c868867255cd7a66fbb96463acad240e37caeeac2bd382247d0895ac2ee19455b423ac0a0c72d1381ff5812bb8b732",
          "sha256": "f989b47e8b9b933c699887e33f3e1dd665a2f4c6382d90db73e23f46a28e4981",
          "sha1": "1d5e7ce24ac9e66ab8630e5c532ac4856dd09614",
          "md5": "91cc7fb07ada3244937ee0688d655fa0"
        }
      ]
    }
  ]
}
