{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a28",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.12.jar",
          "url": "ble-characteristic-u2a28-0.8.12.jar",
          "size": 1600,
          "sha512": "3f643acf2a8f44c274f54b0d9144163cbfe0d750022cd31865de41e7494421fab409fc502caf998f24b9b845fd06241c89779e19ea003c779dfcd5e9117901be",
          "sha256": "8a83e941184ba0b9d4b7bcfcc5deb55a71fb1e99c3ff901f45d80139547eadcb",
          "sha1": "0a211f38ff20f126140c8d71850b7fd2953a0689",
          "md5": "042cd19bed62f3d99bf5a21901215b61"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.12.jar",
          "url": "ble-characteristic-u2a28-0.8.12.jar",
          "size": 1600,
          "sha512": "3f643acf2a8f44c274f54b0d9144163cbfe0d750022cd31865de41e7494421fab409fc502caf998f24b9b845fd06241c89779e19ea003c779dfcd5e9117901be",
          "sha256": "8a83e941184ba0b9d4b7bcfcc5deb55a71fb1e99c3ff901f45d80139547eadcb",
          "sha1": "0a211f38ff20f126140c8d71850b7fd2953a0689",
          "md5": "042cd19bed62f3d99bf5a21901215b61"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a28-0.8.12-javadoc.jar",
          "size": 86284,
          "sha512": "079dc94d8655a4d9b91a10335342a7609b4d127d162b9bd5830f66015c1616da6b7ce5f71e2ae77a6613e4a3eaaac3861ca26907cf05a94438c493338adba240",
          "sha256": "86defa9ca879add1053ec67bc7883943b5455393ed6a8240d7b7ac44861a2d95",
          "sha1": "d65d62d831f5df280a0331f9d0cabd8e7ad4a6cd",
          "md5": "0981f8085fb8fbf500e5dbc0e1a344c2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a28-0.8.12-sources.jar",
          "size": 1517,
          "sha512": "8e3be3df634671c4c51ef6ed301567ade510e8f9a759d14a84d537c487377827edcb7302bd486a6af6593d56802395ffa5460ebdcc843817eaa7b2df537ad60b",
          "sha256": "331e57cc93bceb62b5c276c0b18aac801ddb53d8ee91f77fd1b21b83933941d3",
          "sha1": "cfed750983bb398bc946e4d595dbb72b4319cd6c",
          "md5": "fa850479a996d64bc1833116e504c114"
        }
      ]
    }
  ]
}
