{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2902-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sipxf3vz2bcx5mgcg6vcjbnlti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.1.1.aar",
          "url": "ble-descriptor-u2902-android-0.1.1.aar",
          "size": 2914,
          "sha512": "a42b9da62fa04487fb9441e3dc8994bce182c7ab77671fca6b5992580732c5cc797f6adb40a032b8a16f6a3adc48d3361109ce412163626097c29548a20c5cf0",
          "sha256": "b1b5043c555568688343a98c89e530bdfa9635414f771b105d2f80dafc95d187",
          "sha1": "e8f07a7bd5f898fce577d8451f8f89f9cc598e6a",
          "md5": "6fe5d0fd866a2d0103c1598a00591015"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.1.1.aar",
          "url": "ble-descriptor-u2902-android-0.1.1.aar",
          "size": 2914,
          "sha512": "a42b9da62fa04487fb9441e3dc8994bce182c7ab77671fca6b5992580732c5cc797f6adb40a032b8a16f6a3adc48d3361109ce412163626097c29548a20c5cf0",
          "sha256": "b1b5043c555568688343a98c89e530bdfa9635414f771b105d2f80dafc95d187",
          "sha1": "e8f07a7bd5f898fce577d8451f8f89f9cc598e6a",
          "md5": "6fe5d0fd866a2d0103c1598a00591015"
        }
      ]
    }
  ]
}
