{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b7a-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7a",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7a-android-0.8.12.aar",
          "url": "ble-characteristic-u2b7a-android-0.8.12.aar",
          "size": 3112,
          "sha512": "b4542cdf28aefeedd22a5e496e15b7484b03091eaeac8964b4bed30bbf0ecbb8b0e9d3dcebdeef7204a177f0ffb0f31d189af93f284705751a67c0595c1dd372",
          "sha256": "97886de28ba197d25c000c0e7d34a53a135e9e2225ab33372818658a17a10240",
          "sha1": "f5ec57d619e20516acc808b1d7611afa5b226401",
          "md5": "9bd69670aad38450f83b8fcad774dd9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7a",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7a-android-0.8.12.aar",
          "url": "ble-characteristic-u2b7a-android-0.8.12.aar",
          "size": 3112,
          "sha512": "b4542cdf28aefeedd22a5e496e15b7484b03091eaeac8964b4bed30bbf0ecbb8b0e9d3dcebdeef7204a177f0ffb0f31d189af93f284705751a67c0595c1dd372",
          "sha256": "97886de28ba197d25c000c0e7d34a53a135e9e2225ab33372818658a17a10240",
          "sha1": "f5ec57d619e20516acc808b1d7611afa5b226401",
          "md5": "9bd69670aad38450f83b8fcad774dd9d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7a-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b7a-android-0.8.12-sources.jar",
          "size": 2176,
          "sha512": "0f65641a7ae7a110f3af955cfbb232eb79f9c2362385e8c9bf8306a73b0f361267755ddc48ccc3eb6929abb6dbbdb7407da99038eb04b6a6fc126f47a83a3f8d",
          "sha256": "ac25c82ee6502015e9c6b76bffcb3d9214acd7be24838cc0231065d99073116f",
          "sha1": "6230834fed0a93c30b2c68ff4b759bfbb5cf2482",
          "md5": "f5b9290c0df24b1b0a49556720fefb06"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7a-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b7a-android-0.8.12-javadoc.jar",
          "size": 271021,
          "sha512": "319805465e725f1a5bc412b892c8e291600cdd11184f53f074768684c19f76b772564811b4f195c182bdecdc2689b8e4dc921b78169860aad92ee0584fd16f09",
          "sha256": "f7f9def0317622b9af16d6b9a8f8c84e16ab183216d366243d8335475adcacc6",
          "sha1": "acaf4a2d2acfbc504941139ee380b4f1541ba75d",
          "md5": "8daa16b33e062e588328a4838e2fecd6"
        }
      ]
    }
  ]
}
