{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2afd",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.9.jar",
          "url": "ble-characteristic-u2afd-0.8.9.jar",
          "size": 2090,
          "sha512": "23b343eafacf6bec1aa1db172c03db0343ce018983fecec5cda7937023ec5ea032b9a684f3e4b337b23884508536a798cdee42f652ba8a7ceab35bde3053eb25",
          "sha256": "9fb5debdd8ddf25167c856eb97e8fea0bed3e49a1715cb0b58ffd08abcfbc705",
          "sha1": "a1922522a92243f7272c81ce1ca755bb7baf6522",
          "md5": "92f9c034e836a9df5f23d4c8b166cd44"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.9.jar",
          "url": "ble-characteristic-u2afd-0.8.9.jar",
          "size": 2090,
          "sha512": "23b343eafacf6bec1aa1db172c03db0343ce018983fecec5cda7937023ec5ea032b9a684f3e4b337b23884508536a798cdee42f652ba8a7ceab35bde3053eb25",
          "sha256": "9fb5debdd8ddf25167c856eb97e8fea0bed3e49a1715cb0b58ffd08abcfbc705",
          "sha1": "a1922522a92243f7272c81ce1ca755bb7baf6522",
          "md5": "92f9c034e836a9df5f23d4c8b166cd44"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2afd-0.8.9-javadoc.jar",
          "size": 110083,
          "sha512": "fcf30b7506a752c9cbd0f72ed955c94970fb80c622a1c397c7180177ecbb2b8e263e2f9d7d681aad3d6cd0be692719e6e9f895b5369c1cd4f25b5ca2ca19d8ff",
          "sha256": "3734ae9e01db77849d35951c88df7f4bc63574426be0f7cf933e483e095cee5f",
          "sha1": "0cdf5deba2ff470162ce8271da6c34ff13b73448",
          "md5": "02f80dad2196a2f773f6b24c408defeb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2afd-0.8.9-sources.jar",
          "url": "ble-characteristic-u2afd-0.8.9-sources.jar",
          "size": 1965,
          "sha512": "a0abe3d496ce0889c3453160ac60b903d54589af4f6e3d6ac015fb811819ce294edac0f74e330e916ccfd0156b1f6ac9b06b1097c5cf8f802e045d147a2dfcb9",
          "sha256": "efdd6019f051a85aa87044f517745eec613d36afc90947ee5d49a5be85adf00c",
          "sha1": "ea8b104df6e14eab83a707d85615cb49d434d098",
          "md5": "2c2a097eef49a672a7c786144d58f3e2"
        }
      ]
    }
  ]
}
