{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae4-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae4",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae4-android-0.4.1.aar",
          "url": "ble-characteristic-u2ae4-android-0.4.1.aar",
          "size": 3090,
          "sha512": "7f56384611e3b81abecd6486655035f947d508de5c4ead6f6e02bda48d778ea4af5eae4e8a103ad8749c236690298cf081340efedd05f08f2bc4acd4be64f170",
          "sha256": "4c950ca136613e07354e598a65e594ba1c9f26b63c16105a99789195d5b38a6b",
          "sha1": "5fbadd4c2b3e23de5ae85ca36e658030bda43e90",
          "md5": "7fe1c74311d2e96d9d6c7b245352997f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae4",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae4-android-0.4.1.aar",
          "url": "ble-characteristic-u2ae4-android-0.4.1.aar",
          "size": 3090,
          "sha512": "7f56384611e3b81abecd6486655035f947d508de5c4ead6f6e02bda48d778ea4af5eae4e8a103ad8749c236690298cf081340efedd05f08f2bc4acd4be64f170",
          "sha256": "4c950ca136613e07354e598a65e594ba1c9f26b63c16105a99789195d5b38a6b",
          "sha1": "5fbadd4c2b3e23de5ae85ca36e658030bda43e90",
          "md5": "7fe1c74311d2e96d9d6c7b245352997f"
        }
      ]
    }
  ]
}
