{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3c",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.12.jar",
          "url": "ble-characteristic-u2b3c-0.8.12.jar",
          "size": 1501,
          "sha512": "91addb24f3dbf2808ab16006f82eac2ad14bd8d95ce69dd246f9a2a87ccf3babd645d0c63d51f0c06fa9909516170d5f52e5a92f1a35932ec25314d0dda8bbee",
          "sha256": "627d72c5cc0695eaae81af17f830ae021d200e0f22819ad2ced77f2ef5a91bd6",
          "sha1": "e970a2f68ffd0da646817ef748649cf93728ba92",
          "md5": "b80a02a9fcd6e37a62c05797222a112f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.12.jar",
          "url": "ble-characteristic-u2b3c-0.8.12.jar",
          "size": 1501,
          "sha512": "91addb24f3dbf2808ab16006f82eac2ad14bd8d95ce69dd246f9a2a87ccf3babd645d0c63d51f0c06fa9909516170d5f52e5a92f1a35932ec25314d0dda8bbee",
          "sha256": "627d72c5cc0695eaae81af17f830ae021d200e0f22819ad2ced77f2ef5a91bd6",
          "sha1": "e970a2f68ffd0da646817ef748649cf93728ba92",
          "md5": "b80a02a9fcd6e37a62c05797222a112f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b3c-0.8.12-javadoc.jar",
          "size": 107291,
          "sha512": "04eecf3e911bc54ec6e0ec1ae45c511e1eb312cdb19acd9b28f4e150b1648454a0fc573a7a1f1d39cc0530333ca47d03c913a37a52d99ab0238f7fc2a4a59876",
          "sha256": "23147b1df0cd381d381e5f8a2aa8ac9c005d46a4325e84e5eff3df46b5bd1924",
          "sha1": "fb313deda9488beced54b06fcd0263f0233e5db3",
          "md5": "882a4d67c7852ceef6dbb15441f7f21c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3c-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b3c-0.8.12-sources.jar",
          "size": 1500,
          "sha512": "8b6b7c2947281200da00f51e1ca10cbb1931837f5a3795bfcc2575f7a93ba7cd5aedcaf5e06600071e85c9ab1ccfd4edd4b2f853ff2f08eb49aedbdc72183521",
          "sha256": "b3e5407c0a41e6113e059f015ca3596fcba400355ef92725bf0543b5074e41a6",
          "sha1": "aee9c8029f50ad3b44835a494c22e2135363972b",
          "md5": "2c5e07a4f93ac6b0ec39230c5941a4ca"
        }
      ]
    }
  ]
}
