{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-cscp-peripheral-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-cscp-peripheral-android-0.1.6.aar",
          "url": "ble-profile-cscp-peripheral-android-0.1.6.aar",
          "size": 4887,
          "sha512": "ec3bc4f1b3c23ab4888b7b5905590748d78ca0923fae6273bcb5fc8fe18812ed1f702bc929e349caf38ead869c1ede4c05d9376f198b8014e70054cc8dc68bab",
          "sha256": "13965dd4a36b3f7607888bb939271fa03a86c93a762c4b8a2c119e07da37c435",
          "sha1": "b54c42b10e6cd06996fae09e93567efa30e60e59",
          "md5": "19637553bd4d67173f3ceab6ae260e53"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cscs-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.17"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-cscp-peripheral-android-0.1.6.aar",
          "url": "ble-profile-cscp-peripheral-android-0.1.6.aar",
          "size": 4887,
          "sha512": "ec3bc4f1b3c23ab4888b7b5905590748d78ca0923fae6273bcb5fc8fe18812ed1f702bc929e349caf38ead869c1ede4c05d9376f198b8014e70054cc8dc68bab",
          "sha256": "13965dd4a36b3f7607888bb939271fa03a86c93a762c4b8a2c119e07da37c435",
          "sha1": "b54c42b10e6cd06996fae09e93567efa30e60e59",
          "md5": "19637553bd4d67173f3ceab6ae260e53"
        }
      ]
    }
  ]
}
