{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4f-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4f",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4f-android-0.8.7.aar",
          "url": "ble-characteristic-u2b4f-android-0.8.7.aar",
          "size": 3237,
          "sha512": "7163611c6ca86b938b95f02d85e338a80482194bd2ea445b55eaab1bdc21d79a3c4b5469dfcbecaf51899f7704f64320f7434176118d002659150d64dc30c219",
          "sha256": "692a20fae892c148a3900142b4cc5bcc061fc5ca86bfdd8b0ea7eead999f600d",
          "sha1": "1a5b4154cb5bc90d4764b46597d24e0c5ba011b5",
          "md5": "a3a45230963648292d69e3b436c314fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4f",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4f-android-0.8.7.aar",
          "url": "ble-characteristic-u2b4f-android-0.8.7.aar",
          "size": 3237,
          "sha512": "7163611c6ca86b938b95f02d85e338a80482194bd2ea445b55eaab1bdc21d79a3c4b5469dfcbecaf51899f7704f64320f7434176118d002659150d64dc30c219",
          "sha256": "692a20fae892c148a3900142b4cc5bcc061fc5ca86bfdd8b0ea7eead999f600d",
          "sha1": "1a5b4154cb5bc90d4764b46597d24e0c5ba011b5",
          "md5": "a3a45230963648292d69e3b436c314fc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4f-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b4f-android-0.8.7-sources.jar",
          "size": 2230,
          "sha512": "b5b4f4dd80a9b15ed10b8e3673e3e8074cfc266a56daee76cbd8a232962c24173502b3a464496b52e55b31d3b2132f92d04a977dd8dddca5d5002218018a3aa0",
          "sha256": "212691f477908847e413aa7ee11efbdec073e24dfa61a9f532c5671f455a40f0",
          "sha1": "277b3fd54a536fd7d619762224380120a3ee87bf",
          "md5": "c22db0bbba5748ef85f82295dcdee20e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4f-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b4f-android-0.8.7-javadoc.jar",
          "size": 272515,
          "sha512": "afef6fd44ca638c0e872262628af1340309e91de8f85052b87d9c5b6596b54b44f39b888365f21706016f2d026c2e4fb0705bb75f57d6a838a9c253800ff3698",
          "sha256": "128598feffc7d6d5477aaf27683783b5a83355e82db697bb3d5cc257423645f6",
          "sha1": "3ff0ffeca03745634d01411ef9d9f16f2072caf5",
          "md5": "133ea4e6198b32323a8a94bed02c80dd"
        }
      ]
    }
  ]
}
