{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a24",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ok53hul7zjdznoaoe7p5sj5cvi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-0.2.2.jar",
          "url": "ble-characteristic-u2a24-0.2.2.jar",
          "size": 1586,
          "sha512": "fb5ecca0e41e82d88323c0f7a1ce5c75ef86759d6ba41c95e7f311c1a74522f3aa49621deb4cf25374f12637669b6b868f7c81131cec639c22d585f86cd81f33",
          "sha256": "34e6566c918f0a651eb0cc2c13b1be7b619beb299661087825241e80da02be22",
          "sha1": "40b591838eb20c654f1fa65c2615dd4ad2e0c56b",
          "md5": "880ebe18c4ec0dcf160b850b8f584961"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a24-0.2.2.jar",
          "url": "ble-characteristic-u2a24-0.2.2.jar",
          "size": 1586,
          "sha512": "fb5ecca0e41e82d88323c0f7a1ce5c75ef86759d6ba41c95e7f311c1a74522f3aa49621deb4cf25374f12637669b6b868f7c81131cec639c22d585f86cd81f33",
          "sha256": "34e6566c918f0a651eb0cc2c13b1be7b619beb299661087825241e80da02be22",
          "sha1": "40b591838eb20c654f1fa65c2615dd4ad2e0c56b",
          "md5": "880ebe18c4ec0dcf160b850b8f584961"
        }
      ]
    }
  ]
}
