{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b8e",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8e-0.8.0.jar",
          "url": "ble-characteristic-u2b8e-0.8.0.jar",
          "size": 1461,
          "sha512": "924bd056d92ca80a7352454e047f357de3f4eef5b84169ec3cfbc381d49e9591b8d6894781934fb718fcbcae8edd1b43366d17a46cd80a92cffd4a8b1539f112",
          "sha256": "316cca308299b74999d575db0759a4c432f8e6d6ce6cad243c20f34b352d9438",
          "sha1": "a2a6f4055de959f041187a6a3e884f70fe0c09b9",
          "md5": "c57ea8d7cf478268668af012a8faaba4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8e-0.8.0.jar",
          "url": "ble-characteristic-u2b8e-0.8.0.jar",
          "size": 1461,
          "sha512": "924bd056d92ca80a7352454e047f357de3f4eef5b84169ec3cfbc381d49e9591b8d6894781934fb718fcbcae8edd1b43366d17a46cd80a92cffd4a8b1539f112",
          "sha256": "316cca308299b74999d575db0759a4c432f8e6d6ce6cad243c20f34b352d9438",
          "sha1": "a2a6f4055de959f041187a6a3e884f70fe0c09b9",
          "md5": "c57ea8d7cf478268668af012a8faaba4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8e-0.8.0-javadoc.jar",
          "url": "ble-characteristic-u2b8e-0.8.0-javadoc.jar",
          "size": 109897,
          "sha512": "c39cec458664f958d821bb72821825a311119fdb6d713e44ce35079035620329fa170b34b1d39bf29929a84517ac29b228fa961379e530a890d1789d1d893aab",
          "sha256": "33d526124531ce96fe70bc9de1dea1eaef748aa5f321e7dee7809f9dc24f8787",
          "sha1": "b4ea84b3aadafc270708d2ff196ae5d48a092617",
          "md5": "8ab31e0f7b18e4d7fa6a2dedb95ad1fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8e-0.8.0-sources.jar",
          "url": "ble-characteristic-u2b8e-0.8.0-sources.jar",
          "size": 1434,
          "sha512": "1ac4acbcbb487c4b02ad061547ec27fce570e4c51690d7288862527671a8238131990dccf8ede2e78e261028cb1dcbedb65da2a00b1f7be12712ac1430a50780",
          "sha256": "faa9d65d5b9abfeb15c8f1076590b3b2e9d048df64bec52852d5029c7b1e1bbb",
          "sha1": "c39f4cb6effaa75593b409226594a5ad7658f439",
          "md5": "bd8340cd832d307755db4b2dbf69f1d4"
        }
      ]
    }
  ]
}
