{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a85-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.2.2.aar",
          "url": "ble-characteristic-u2a85-android-0.2.2.aar",
          "size": 2930,
          "sha512": "0be14fe6d4f1d53ba7885fb8c72601ca0c12fb6929b6c728d6f3b4fbcc1411285f5e80a754ced1da61c151075b5de224d53134359280c98c9754ba4ace6ee268",
          "sha256": "62a4d19c2a1f543d111cdef851a03f89264d1d1988dbc17455558565a9ee6fcd",
          "sha1": "69dd7039524904f67e8c41e51ce22a931816f72e",
          "md5": "d109a88aa408111fd429e5833a7188bc"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a85",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-android-0.2.2.aar",
          "url": "ble-characteristic-u2a85-android-0.2.2.aar",
          "size": 2930,
          "sha512": "0be14fe6d4f1d53ba7885fb8c72601ca0c12fb6929b6c728d6f3b4fbcc1411285f5e80a754ced1da61c151075b5de224d53134359280c98c9754ba4ace6ee268",
          "sha256": "62a4d19c2a1f543d111cdef851a03f89264d1d1988dbc17455558565a9ee6fcd",
          "sha1": "69dd7039524904f67e8c41e51ce22a931816f72e",
          "md5": "d109a88aa408111fd429e5833a7188bc"
        }
      ]
    }
  ]
}
