{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7b-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kupq6qdcq5dovle6dw5m7myoyy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7b",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7b-android-0.2.3.aar",
          "url": "ble-characteristic-u2a7b-android-0.2.3.aar",
          "size": 3063,
          "sha512": "c233221f1dfb23494f0172c5555032a99c04bf99f178cedf0aae8045f4603b6ddd5745674821b65c4a7f709723db581393ddb4250ecfed912f8920b0a0cdd555",
          "sha256": "6312346d27e1238da96c6756cada08f783a409e7501f9a981302290d0b9b6651",
          "sha1": "a1d70a68f4f4332963ebb4abb38502456e54c968",
          "md5": "c3c70622a83c2e1a2c86766ffa06133d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7b",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7b-android-0.2.3.aar",
          "url": "ble-characteristic-u2a7b-android-0.2.3.aar",
          "size": 3063,
          "sha512": "c233221f1dfb23494f0172c5555032a99c04bf99f178cedf0aae8045f4603b6ddd5745674821b65c4a7f709723db581393ddb4250ecfed912f8920b0a0cdd555",
          "sha256": "6312346d27e1238da96c6756cada08f783a409e7501f9a981302290d0b9b6651",
          "sha1": "a1d70a68f4f4332963ebb4abb38502456e54c968",
          "md5": "c3c70622a83c2e1a2c86766ffa06133d"
        }
      ]
    }
  ]
}
