{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a55-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a55",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-android-0.2.4.aar",
          "url": "ble-characteristic-u2a55-android-0.2.4.aar",
          "size": 3187,
          "sha512": "940dd10989b810224556bc9c0075b5dfa2443dd107260eb022903c60e396f16f36e06e18c1bf182c2f45e07cdbd3b5ae9bd40b5a5c91e607f68422c6ade5f15d",
          "sha256": "35c7a83336d750ae74995a6d7e6e4abd967f006e3890f838c9781bc93fd0ae8d",
          "sha1": "dcac45586851a2e35a76e395c7cf31a789a38db0",
          "md5": "111ccd9352786d630db6ceb4b8b38e96"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a55",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a55-android-0.2.4.aar",
          "url": "ble-characteristic-u2a55-android-0.2.4.aar",
          "size": 3187,
          "sha512": "940dd10989b810224556bc9c0075b5dfa2443dd107260eb022903c60e396f16f36e06e18c1bf182c2f45e07cdbd3b5ae9bd40b5a5c91e607f68422c6ade5f15d",
          "sha256": "35c7a83336d750ae74995a6d7e6e4abd967f006e3890f838c9781bc93fd0ae8d",
          "sha1": "dcac45586851a2e35a76e395c7cf31a789a38db0",
          "md5": "111ccd9352786d630db6ceb4b8b38e96"
        }
      ]
    }
  ]
}
