{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bcs-peripheral-android",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-peripheral-android-0.1.11.aar",
          "url": "ble-service-bcs-peripheral-android-0.1.11.aar",
          "size": 4388,
          "sha512": "34c89f7c553d943c35e433c610d623bd731cf4f9020f049cb43b59584a79dc1ef05d8e9c64d7a8b8826b2767f194485b82c1583e798833545ced197b6c58c3f3",
          "sha256": "6ed4fc2976b6dcf890a414eb09f481e1966f94f31043dc62142d29391e182c76",
          "sha1": "33480c786376814301c10ac7b6a0cf6f9b971887",
          "md5": "9190b366f75370c7dd09ad89e5bfb786"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bcs-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bcs-peripheral-android-0.1.11.aar",
          "url": "ble-service-bcs-peripheral-android-0.1.11.aar",
          "size": 4388,
          "sha512": "34c89f7c553d943c35e433c610d623bd731cf4f9020f049cb43b59584a79dc1ef05d8e9c64d7a8b8826b2767f194485b82c1583e798833545ced197b6c58c3f3",
          "sha256": "6ed4fc2976b6dcf890a414eb09f481e1966f94f31043dc62142d29391e182c76",
          "sha1": "33480c786376814301c10ac7b6a0cf6f9b971887",
          "md5": "9190b366f75370c7dd09ad89e5bfb786"
        }
      ]
    }
  ]
}
