{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a05-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a05",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a05-android-0.2.6.aar",
          "url": "ble-characteristic-u2a05-android-0.2.6.aar",
          "size": 3126,
          "sha512": "a692d9911c7fdbbbb7863560e80c34b62d08c9532329a892329bef517bd92265dfbf54f850462d684bba2721cae4c9d5f277cc64cf9428114a84c8ecb415714e",
          "sha256": "d9caeea554a8c160eeb3d8924eb0557fe1f9d2230897d9d326c6b8041d2b1016",
          "sha1": "b7124c2cdf79ae37db73372ee6c45a20ca58756f",
          "md5": "7cfb18ed9946c9ad8d82108ce778bbd2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a05",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a05-android-0.2.6.aar",
          "url": "ble-characteristic-u2a05-android-0.2.6.aar",
          "size": 3126,
          "sha512": "a692d9911c7fdbbbb7863560e80c34b62d08c9532329a892329bef517bd92265dfbf54f850462d684bba2721cae4c9d5f277cc64cf9428114a84c8ecb415714e",
          "sha256": "d9caeea554a8c160eeb3d8924eb0557fe1f9d2230897d9d326c6b8041d2b1016",
          "sha1": "b7124c2cdf79ae37db73372ee6c45a20ca58756f",
          "md5": "7cfb18ed9946c9ad8d82108ce778bbd2"
        }
      ]
    }
  ]
}
