{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b77-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b77",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b77-android-0.4.4.aar",
          "url": "ble-characteristic-u2b77-android-0.4.4.aar",
          "size": 3064,
          "sha512": "eea1046641cf0fbae84f5456b49ca93ce0d3241cac93822e4e6947f00cc5d6031e290f161b2b1f157805c4da1cd1547e64d49db410912f6b790fbf8bfd1e3eca",
          "sha256": "1dfa3a6050c52633ed17b6b35e3946c8bc7984665a1ef98fad754c65950ebf56",
          "sha1": "43a28d79496f9ef84ab1fff2f4964c9a5645cfb4",
          "md5": "ca98811046f0ed4859f2c6c498e20a08"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b77",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b77-android-0.4.4.aar",
          "url": "ble-characteristic-u2b77-android-0.4.4.aar",
          "size": 3064,
          "sha512": "eea1046641cf0fbae84f5456b49ca93ce0d3241cac93822e4e6947f00cc5d6031e290f161b2b1f157805c4da1cd1547e64d49db410912f6b790fbf8bfd1e3eca",
          "sha256": "1dfa3a6050c52633ed17b6b35e3946c8bc7984665a1ef98fad754c65950ebf56",
          "sha1": "43a28d79496f9ef84ab1fff2f4964c9a5645cfb4",
          "md5": "ca98811046f0ed4859f2c6c498e20a08"
        }
      ]
    }
  ]
}
