{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-esp-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-esp-android-0.4.1.aar",
          "url": "ble-profile-esp-android-0.4.1.aar",
          "size": 1182,
          "sha512": "7c5fcda375cc77019891f0b24c01e79681a97e13e7b70de7b09cf0af158b9bbcd376a3d5297f20d1f0a6a34b693c8de1b3a95de376bd34d1dfba324052b3a1b8",
          "sha256": "df1bbb060abbf93518563f7e96ed2edbca059702f9afbf5dcb589c80b62bc2a6",
          "sha1": "5cdde6f5757413912ea97d64638442bfbd551ade",
          "md5": "05788a12bcfec6d9f675ec375feee63c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-esp-android-0.4.1.aar",
          "url": "ble-profile-esp-android-0.4.1.aar",
          "size": 1182,
          "sha512": "7c5fcda375cc77019891f0b24c01e79681a97e13e7b70de7b09cf0af158b9bbcd376a3d5297f20d1f0a6a34b693c8de1b3a95de376bd34d1dfba324052b3a1b8",
          "sha256": "df1bbb060abbf93518563f7e96ed2edbca059702f9afbf5dcb589c80b62bc2a6",
          "sha1": "5cdde6f5757413912ea97d64638442bfbd551ade",
          "md5": "05788a12bcfec6d9f675ec375feee63c"
        }
      ]
    }
  ]
}
