{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad6-android",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.5.0.aar",
          "url": "ble-characteristic-u2ad6-android-0.5.0.aar",
          "size": 3184,
          "sha512": "55a55a47d5c16fd3a8c9d700b6a85fd024235a6fc94fd47327d9c995efb61f9f7ce9ce345058f986ecb93a5e3c414c26b1badebb8ea85f5a88375991915455a4",
          "sha256": "49ad8f3f48ccfd74ae92bee5d1da21ad2bb6a8847dbff3e7ac868e5e17a7f208",
          "sha1": "ef84e2aa4a16ac4c86bd6448c2405223babecaa2",
          "md5": "b2d925dac62da00db3a76da1a99b7522"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.5.0.aar",
          "url": "ble-characteristic-u2ad6-android-0.5.0.aar",
          "size": 3184,
          "sha512": "55a55a47d5c16fd3a8c9d700b6a85fd024235a6fc94fd47327d9c995efb61f9f7ce9ce345058f986ecb93a5e3c414c26b1badebb8ea85f5a88375991915455a4",
          "sha256": "49ad8f3f48ccfd74ae92bee5d1da21ad2bb6a8847dbff3e7ac868e5e17a7f208",
          "sha1": "ef84e2aa4a16ac4c86bd6448c2405223babecaa2",
          "md5": "b2d925dac62da00db3a76da1a99b7522"
        }
      ]
    }
  ]
}
