{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4b",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4b-0.8.3.jar",
          "url": "ble-characteristic-u2b4b-0.8.3.jar",
          "size": 3157,
          "sha512": "6dd2aee2fc9c4ed6383a4c68d1355ea480d16f9cdb0ec663f4dd614b4ab457b6a4d5d6263e17bcc565b683597db81b2d2b486eb5cd7cd0810e7f2a19eb164b26",
          "sha256": "8c777580f7914835573167a213ca0944bcdad4717d6f1db85e30ad4a3ad19ade",
          "sha1": "a52119c279fd769ae225384388cbaaa0dc5d2211",
          "md5": "d046378c8d09889f8343714833828a0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4b-0.8.3.jar",
          "url": "ble-characteristic-u2b4b-0.8.3.jar",
          "size": 3157,
          "sha512": "6dd2aee2fc9c4ed6383a4c68d1355ea480d16f9cdb0ec663f4dd614b4ab457b6a4d5d6263e17bcc565b683597db81b2d2b486eb5cd7cd0810e7f2a19eb164b26",
          "sha256": "8c777580f7914835573167a213ca0944bcdad4717d6f1db85e30ad4a3ad19ade",
          "sha1": "a52119c279fd769ae225384388cbaaa0dc5d2211",
          "md5": "d046378c8d09889f8343714833828a0c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4b-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2b4b-0.8.3-javadoc.jar",
          "size": 117241,
          "sha512": "d800f37a3ca56dbd8e235526d191c23f1a212006b0a94a1d64adec11cb5175ae2d9ec3ad30110a2d9281668fec53593b0301b2ad3459e98ceedc81ee06d5b1c6",
          "sha256": "655a9b4d98af188d5f0630c4df1d1bcc1170e4ddbc3e380f8b20b904972af001",
          "sha1": "e418c40b8813c2de9ca9670e20976313587f9821",
          "md5": "6dad6bfa81ab14a1c19cf33fe9f2ac50"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4b-0.8.3-sources.jar",
          "url": "ble-characteristic-u2b4b-0.8.3-sources.jar",
          "size": 2999,
          "sha512": "172165593041e809741cce153f85cb7424b906023e4ce35f9256b6b0cb824527c2e24e3b706c4808b816feab4154bb47511e08a6ba8abbe7896a56a4d94e7242",
          "sha256": "40f7388ea6a45e0bdd802ea7832b0fd86bc59c8acfd0deaaee56e1c8bc12e4ca",
          "sha1": "a78f479a3921cb331cf103c0e55ed7babc09f1a4",
          "md5": "7f4636072781e867c50ea0da020134c2"
        }
      ]
    }
  ]
}
