{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-central-pasp-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-pass-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-pasp-android-0.4.2.aar",
          "url": "ble-profile-central-pasp-android-0.4.2.aar",
          "size": 5035,
          "sha512": "0ad447c6c153b549cb9015cada8040327fb129be420908145424bc4feac9fa06d16793bf19ba36e896bd9daff31b98390d2d3d26bc9916c37dcb06181928dd89",
          "sha256": "b72a6e166be8734258f7710d378fdd61321b92561c27df23c25443b5281aa76d",
          "sha1": "42c17ba2239e4fc2a89917de03364a909ec82947",
          "md5": "87a703e0e02c20884128c2b8b7fabb17"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-central-pass-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-central-pasp-android-0.4.2.aar",
          "url": "ble-profile-central-pasp-android-0.4.2.aar",
          "size": 5035,
          "sha512": "0ad447c6c153b549cb9015cada8040327fb129be420908145424bc4feac9fa06d16793bf19ba36e896bd9daff31b98390d2d3d26bc9916c37dcb06181928dd89",
          "sha256": "b72a6e166be8734258f7710d378fdd61321b92561c27df23c25443b5281aa76d",
          "sha1": "42c17ba2239e4fc2a89917de03364a909ec82947",
          "md5": "87a703e0e02c20884128c2b8b7fabb17"
        }
      ]
    }
  ]
}
