{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab8-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smp7vu2g4jdlfelcafoemcahhe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab8",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-android-0.2.8.aar",
          "url": "ble-characteristic-u2ab8-android-0.2.8.aar",
          "size": 3096,
          "sha512": "45b65959971a2da4b86ee0a023cb4a278e697b810bd4714d7c576d8d0049df6f323e4270f89d3fa1aaa54adbb3292b3b92fc3011b5ed9d5aa08938f0b47f2500",
          "sha256": "892cc9059261062fa57dc01d8bc11506a52d53a01352b61baf18845c7c668944",
          "sha1": "647849c52cc4f4466a59fae655ad6511fc9aff61",
          "md5": "7b3004441a4fab716d601c0f55407ac9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab8",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab8-android-0.2.8.aar",
          "url": "ble-characteristic-u2ab8-android-0.2.8.aar",
          "size": 3096,
          "sha512": "45b65959971a2da4b86ee0a023cb4a278e697b810bd4714d7c576d8d0049df6f323e4270f89d3fa1aaa54adbb3292b3b92fc3011b5ed9d5aa08938f0b47f2500",
          "sha256": "892cc9059261062fa57dc01d8bc11506a52d53a01352b61baf18845c7c668944",
          "sha1": "647849c52cc4f4466a59fae655ad6511fc9aff61",
          "md5": "7b3004441a4fab716d601c0f55407ac9"
        }
      ]
    }
  ]
}
