{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1d",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "yxv7tu3b6vasbnjlgorebyc6zy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1d-0.2.2.jar",
          "url": "ble-characteristic-u2b1d-0.2.2.jar",
          "size": 3662,
          "sha512": "eceac3210071645ea4b885adced9ab276659b5f2d8a6db7052a88999bbbaf58e13a433954006a5a648c6da7dde4a1b087eb980fc4e0a796321e2378cac4bb6c5",
          "sha256": "1228cd13ca408784556d6f8d1c7bd5b0f1b50a8398c95aecdad02f3b2d7662d2",
          "sha1": "6e9798f636ce7a4b9c434cf3acdfd5fc3d5b9c64",
          "md5": "c46a02e12bd2d4f18a2ba292482023b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1d-0.2.2.jar",
          "url": "ble-characteristic-u2b1d-0.2.2.jar",
          "size": 3662,
          "sha512": "eceac3210071645ea4b885adced9ab276659b5f2d8a6db7052a88999bbbaf58e13a433954006a5a648c6da7dde4a1b087eb980fc4e0a796321e2378cac4bb6c5",
          "sha256": "1228cd13ca408784556d6f8d1c7bd5b0f1b50a8398c95aecdad02f3b2d7662d2",
          "sha1": "6e9798f636ce7a4b9c434cf3acdfd5fc3d5b9c64",
          "md5": "c46a02e12bd2d4f18a2ba292482023b2"
        }
      ]
    }
  ]
}
