{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5b-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.8.6.aar",
          "url": "ble-characteristic-u2a5b-android-0.8.6.aar",
          "size": 3174,
          "sha512": "9b2d321ea298bc06f0a33028392655b374d9e219c9c2fe4849e89516fcf10718745a8504b3dd5ca8ee3b25732381405a39d55b57b39729ff8c59847ebbf5feb9",
          "sha256": "45ad33d9f394a1316baf60cb1c29a5a323227fe4b4a33b9311eb65cddea446a0",
          "sha1": "534b7287b8fe7064c3f75cece7c02dc3a9fd0fa6",
          "md5": "469e929ed09008489d16b808ec4cc7aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.8.6.aar",
          "url": "ble-characteristic-u2a5b-android-0.8.6.aar",
          "size": 3174,
          "sha512": "9b2d321ea298bc06f0a33028392655b374d9e219c9c2fe4849e89516fcf10718745a8504b3dd5ca8ee3b25732381405a39d55b57b39729ff8c59847ebbf5feb9",
          "sha256": "45ad33d9f394a1316baf60cb1c29a5a323227fe4b4a33b9311eb65cddea446a0",
          "sha1": "534b7287b8fe7064c3f75cece7c02dc3a9fd0fa6",
          "md5": "469e929ed09008489d16b808ec4cc7aa"
        }
      ]
    }
  ]
}
