{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-tip-central-android",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qp2r6rwjdvg4fg6cp5ivnzfwny"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-central-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-tip-central-android-0.1.7.aar",
          "url": "ble-profile-tip-central-android-0.1.7.aar",
          "size": 6358,
          "sha512": "896af1f040f00fbb7c95de24a7312919bfc797ff7000d5aadc39ce47f615f7020b8a86884d79392e56c7db7af50ce9379cd582a5307d12ab073f32e39eef22ee",
          "sha256": "07bfc1c5d8c8111763fc2fda1a3123940b63cd0af9baac776468da259b798ccf",
          "sha1": "89546aaf2514afaf81217b8360b222a33d921b69",
          "md5": "391a1a19568af24dba11fa42f920866e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-central-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-tip-central-android-0.1.7.aar",
          "url": "ble-profile-tip-central-android-0.1.7.aar",
          "size": 6358,
          "sha512": "896af1f040f00fbb7c95de24a7312919bfc797ff7000d5aadc39ce47f615f7020b8a86884d79392e56c7db7af50ce9379cd582a5307d12ab073f32e39eef22ee",
          "sha256": "07bfc1c5d8c8111763fc2fda1a3123940b63cd0af9baac776468da259b798ccf",
          "sha1": "89546aaf2514afaf81217b8360b222a33d921b69",
          "md5": "391a1a19568af24dba11fa42f920866e"
        }
      ]
    }
  ]
}
