{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7e-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7e",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-android-0.8.12.aar",
          "url": "ble-characteristic-u2a7e-android-0.8.12.aar",
          "size": 3228,
          "sha512": "5a1dc1fb47f97de93bf13b92ab3bdb4454b8e38e0d1b84303f5f486ef4653ab464f560c227c371676da0fba944c67404981b22ac940a0d3eca742c8d08c85882",
          "sha256": "b8cd5265b7c85390af911f19eb80ffead80ddbe03c2d18da688f0d1c316cd9ed",
          "sha1": "a5d256577bb22fc86d40bd25fa5ef30b255eb2df",
          "md5": "2cdb873d165f72e36e653cf04f1eba80"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7e",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7e-android-0.8.12.aar",
          "url": "ble-characteristic-u2a7e-android-0.8.12.aar",
          "size": 3228,
          "sha512": "5a1dc1fb47f97de93bf13b92ab3bdb4454b8e38e0d1b84303f5f486ef4653ab464f560c227c371676da0fba944c67404981b22ac940a0d3eca742c8d08c85882",
          "sha256": "b8cd5265b7c85390af911f19eb80ffead80ddbe03c2d18da688f0d1c316cd9ed",
          "sha1": "a5d256577bb22fc86d40bd25fa5ef30b255eb2df",
          "md5": "2cdb873d165f72e36e653cf04f1eba80"
        }
      ]
    }
  ]
}
