{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a26",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a26-0.8.11.jar",
          "url": "ble-characteristic-u2a26-0.8.11.jar",
          "size": 1599,
          "sha512": "01c4573644bd749b9096fe3f608b00631446206a98ab2ad4f6cd0c5e20e9354c12d9ba39e3e667c09b9fdcee240d733c09745cbc4a877b1480b447c594229179",
          "sha256": "0f800e640fefd5b94f3e2ccbe8423514c6e714a0c628ce92277d3eae23cdfea6",
          "sha1": "cef5b7fcdb95a6c251a0067e6a309df1f41a0ef8",
          "md5": "93e9856a077f3d58db7d78fa76e5442d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a26-0.8.11.jar",
          "url": "ble-characteristic-u2a26-0.8.11.jar",
          "size": 1599,
          "sha512": "01c4573644bd749b9096fe3f608b00631446206a98ab2ad4f6cd0c5e20e9354c12d9ba39e3e667c09b9fdcee240d733c09745cbc4a877b1480b447c594229179",
          "sha256": "0f800e640fefd5b94f3e2ccbe8423514c6e714a0c628ce92277d3eae23cdfea6",
          "sha1": "cef5b7fcdb95a6c251a0067e6a309df1f41a0ef8",
          "md5": "93e9856a077f3d58db7d78fa76e5442d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a26-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2a26-0.8.11-javadoc.jar",
          "size": 107472,
          "sha512": "b4db8f1cd0b16d9cff75c4576b7f45e6de6b64a725c1abad91813a5788e11d65c706467bdd3ef2ac94abaf5d4553701d8523adf1794eaf068734dfe585d4b200",
          "sha256": "0e9430bab50753c6a5c17b0deb67f12718e51225a7ee981c94901b252b9df280",
          "sha1": "3a9fcd8414fcc4b3f34233c876363fc3da9fb5c3",
          "md5": "7670e1f3592f965f46d97263e7739905"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a26-0.8.11-sources.jar",
          "url": "ble-characteristic-u2a26-0.8.11-sources.jar",
          "size": 1518,
          "sha512": "499cf46b09e5fa4decf530a024ef50f6adf2f99380b2dfbb31f6e18ebf23113b47e47b43c3210eb671547bdf7b969c75dd34cdf9f0bef66718227a5e325df969",
          "sha256": "b0ae3e3c8b258ef117cac10702d0ef10a8ee4834dcdd737a323e2e501ff6fe21",
          "sha1": "f57df72c6f456692918452c562cdcc95cf8313e8",
          "md5": "613f39f429d26c05dab870ef16d6f08c"
        }
      ]
    }
  ]
}
