{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba7-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba7",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-android-0.4.4.aar",
          "url": "ble-characteristic-u2ba7-android-0.4.4.aar",
          "size": 3078,
          "sha512": "3e9c0f97cdeceeea6ef70959c0253ac2fcdf323146dc548d50177a798e0e9312c47b270a565652d91435a02d3989592a040157a9f23b163abb120155277fc625",
          "sha256": "8498306d68ae0632ad06d1d80c4324a83ac04e1bc4077befff66fd66b946dc4e",
          "sha1": "9e05eabd6dd6ba2563f2e1572c943f8e4b2b5866",
          "md5": "791877d16120d4c777fc7f3d46c27aff"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba7",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba7-android-0.4.4.aar",
          "url": "ble-characteristic-u2ba7-android-0.4.4.aar",
          "size": 3078,
          "sha512": "3e9c0f97cdeceeea6ef70959c0253ac2fcdf323146dc548d50177a798e0e9312c47b270a565652d91435a02d3989592a040157a9f23b163abb120155277fc625",
          "sha256": "8498306d68ae0632ad06d1d80c4324a83ac04e1bc4077befff66fd66b946dc4e",
          "sha1": "9e05eabd6dd6ba2563f2e1572c943f8e4b2b5866",
          "md5": "791877d16120d4c777fc7f3d46c27aff"
        }
      ]
    }
  ]
}
