{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b35-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b35",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b35-android-0.4.6.aar",
          "url": "ble-characteristic-u2b35-android-0.4.6.aar",
          "size": 3130,
          "sha512": "44401ae97dd32f240b632c9a592ea75f068d9915580e5347ede4a4837eddfd9ed0cc7344cfefed5f122859dfc19cd4c1b126712f7d4fb4dfcc568d78a2a904ca",
          "sha256": "1fcac0e3e748090adbbe9889a9c088f64442057e519d3a589ac91a19d869f4f0",
          "sha1": "e31ba2a11536ee539ce2a4190981256b26b4abf9",
          "md5": "15f264cef438c8070f621cd160a7ca7a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b35",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b35-android-0.4.6.aar",
          "url": "ble-characteristic-u2b35-android-0.4.6.aar",
          "size": 3130,
          "sha512": "44401ae97dd32f240b632c9a592ea75f068d9915580e5347ede4a4837eddfd9ed0cc7344cfefed5f122859dfc19cd4c1b126712f7d4fb4dfcc568d78a2a904ca",
          "sha256": "1fcac0e3e748090adbbe9889a9c088f64442057e519d3a589ac91a19d869f4f0",
          "sha1": "e31ba2a11536ee539ce2a4190981256b26b4abf9",
          "md5": "15f264cef438c8070f621cd160a7ca7a"
        }
      ]
    }
  ]
}
