{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a28",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.6.jar",
          "url": "ble-characteristic-u2a28-0.8.6.jar",
          "size": 1600,
          "sha512": "8e37155e85d63944b2bc4c782a6d50aa54812a0c7e7e1a339d66ffac5fd06356a5b14ef1c10e703f694a06e41936b6b10584b4e4dd04e428e953c9dcd17e1428",
          "sha256": "23b1558070ae5161e7798daeba935e3bb1e3de1b6b6c6ce5cdc54edceba8fd49",
          "sha1": "6e7f15c64f317dfcf4630d1d0f11ba28b04f3d85",
          "md5": "91f3c5d5fe8e42eb7d2189c37f66ab4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.6.jar",
          "url": "ble-characteristic-u2a28-0.8.6.jar",
          "size": 1600,
          "sha512": "8e37155e85d63944b2bc4c782a6d50aa54812a0c7e7e1a339d66ffac5fd06356a5b14ef1c10e703f694a06e41936b6b10584b4e4dd04e428e953c9dcd17e1428",
          "sha256": "23b1558070ae5161e7798daeba935e3bb1e3de1b6b6c6ce5cdc54edceba8fd49",
          "sha1": "6e7f15c64f317dfcf4630d1d0f11ba28b04f3d85",
          "md5": "91f3c5d5fe8e42eb7d2189c37f66ab4c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a28-0.8.6-javadoc.jar",
          "size": 107469,
          "sha512": "d385acc5c414dff27d480849ba56bf4e152276bc9e937225d14ec770d76726823205a623769e17299d70d4dbde54d5689cd06878d39ddfffe0c7ee942b1bd4fb",
          "sha256": "d7a72fe7b908b78cbcdd284fce92149a8ffde1de1dfeed602b7118565c96054c",
          "sha1": "680f3039285a5b4f9b8fa4c21c7dde78416e7d5f",
          "md5": "c6a139d4cd8c01fe648c81a4570e1574"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a28-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a28-0.8.6-sources.jar",
          "size": 1517,
          "sha512": "31803f551f726aa5195a5c384b3a6535835423d39f123334fc91f56ebe59c45dd75ced1f58c67487f27f581bdd908e3fc3f85baa5d3209211e92791c83ec5c93",
          "sha256": "eccde727977952dd51dd092e24b62bf16deaea19ed28436c5bb03a49e592c5b3",
          "sha1": "aba74e88432bf60f3c2e55927875e2a0853f131a",
          "md5": "82ac75becd0e272b9b862b0d2557f03d"
        }
      ]
    }
  ]
}
