{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a63-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a63",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a63-android-0.2.0.aar",
          "url": "ble-characteristic-u2a63-android-0.2.0.aar",
          "size": 3272,
          "sha512": "4b7caca990df9ba7d690bb0adc7c0e7574b570ac04c0c49357018d82cc9b3e8572fa6c786f9337a7336883d3cc8ad89297a2de8373fa339ceaac97c0ab5ad071",
          "sha256": "de40aeee5ca26c42aba03e46bc395423bb62dc73ae8d180f060de2117b67ca9a",
          "sha1": "08b49516858d74a0ae77688be6c709119a3df650",
          "md5": "67a42b6bd22bd566506210d8c70976e2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a63",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a63-android-0.2.0.aar",
          "url": "ble-characteristic-u2a63-android-0.2.0.aar",
          "size": 3272,
          "sha512": "4b7caca990df9ba7d690bb0adc7c0e7574b570ac04c0c49357018d82cc9b3e8572fa6c786f9337a7336883d3cc8ad89297a2de8373fa339ceaac97c0ab5ad071",
          "sha256": "de40aeee5ca26c42aba03e46bc395423bb62dc73ae8d180f060de2117b67ca9a",
          "sha1": "08b49516858d74a0ae77688be6c709119a3df650",
          "md5": "67a42b6bd22bd566506210d8c70976e2"
        }
      ]
    }
  ]
}
