{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-wss-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "md2hzulcvrbjbp3omyeiu4n5fi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-android-0.1.1.aar",
          "url": "ble-service-wss-android-0.1.1.aar",
          "size": 1026,
          "sha512": "c4d441aef98febe1abc955a3fb470a736e86ce6fb9350fdb841a1638552b90ec6017ecabb47dc2971e715f4ca6e4c803e1c7f606342f43a2b95c7f101f5c1994",
          "sha256": "18f51fb9108afbbc5e62782070eedf9d2b25d3234f0e7cfa3b8be5772e7910e0",
          "sha1": "a3c143d69e14f9b82f8cfe45ddb83cef71406332",
          "md5": "5bffffb7719400d20e0e9af9680e4834"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-android-0.1.1.aar",
          "url": "ble-service-wss-android-0.1.1.aar",
          "size": 1026,
          "sha512": "c4d441aef98febe1abc955a3fb470a736e86ce6fb9350fdb841a1638552b90ec6017ecabb47dc2971e715f4ca6e4c803e1c7f606342f43a2b95c7f101f5c1994",
          "sha256": "18f51fb9108afbbc5e62782070eedf9d2b25d3234f0e7cfa3b8be5772e7910e0",
          "sha1": "a3c143d69e14f9b82f8cfe45ddb83cef71406332",
          "md5": "5bffffb7719400d20e0e9af9680e4834"
        }
      ]
    }
  ]
}
