{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-wss-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kupq6qdcq5dovle6dw5m7myoyy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-android-0.1.1.aar",
          "url": "ble-service-wss-android-0.1.1.aar",
          "size": 1206,
          "sha512": "2e6bdef4f16da4643266a6ee8950f7aa81ec7afcec95e5e3822417dc89641d27295bcce92140346823ae5469c7e717a7ebf9b10c2fbe16b3567477de9d31aef7",
          "sha256": "d9025aa5d56defe33be60d0379a2ec14321868e336801e133c46d494720afb4e",
          "sha1": "4cd7b044388b239290374948fffa0ec4c9a20270",
          "md5": "ea67c96886286b14ea1c1107b8327a2c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9d-android",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-wss-android-0.1.1.aar",
          "url": "ble-service-wss-android-0.1.1.aar",
          "size": 1206,
          "sha512": "2e6bdef4f16da4643266a6ee8950f7aa81ec7afcec95e5e3822417dc89641d27295bcce92140346823ae5469c7e717a7ebf9b10c2fbe16b3567477de9d31aef7",
          "sha256": "d9025aa5d56defe33be60d0379a2ec14321868e336801e133c46d494720afb4e",
          "sha1": "4cd7b044388b239290374948fffa0ec4c9a20270",
          "md5": "ea67c96886286b14ea1c1107b8327a2c"
        }
      ]
    }
  ]
}
