{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b94-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b94",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-android-0.8.12.aar",
          "url": "ble-characteristic-u2b94-android-0.8.12.aar",
          "size": 3184,
          "sha512": "5cb1c6391811a06be9b1b39ec7cf81a0a0896e492a1128efdc91dc0170f18e61ac41940b2aece807ed0e71b4c5e4414e86de2b92cc2208aab943cf4c711f2f0a",
          "sha256": "945e6032abc6dc8625851ff960033a416ec7c9ea95ee0dddb780da2e80f28b30",
          "sha1": "f751f7ca2673192bb958c8ec7e2ca598badf400a",
          "md5": "9f39bdbf9bb6c3784748100b4ef88460"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b94",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-android-0.8.12.aar",
          "url": "ble-characteristic-u2b94-android-0.8.12.aar",
          "size": 3184,
          "sha512": "5cb1c6391811a06be9b1b39ec7cf81a0a0896e492a1128efdc91dc0170f18e61ac41940b2aece807ed0e71b4c5e4414e86de2b92cc2208aab943cf4c711f2f0a",
          "sha256": "945e6032abc6dc8625851ff960033a416ec7c9ea95ee0dddb780da2e80f28b30",
          "sha1": "f751f7ca2673192bb958c8ec7e2ca598badf400a",
          "md5": "9f39bdbf9bb6c3784748100b4ef88460"
        }
      ]
    }
  ]
}
