{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b92",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b92-0.8.4.jar",
          "url": "ble-characteristic-u2b92-0.8.4.jar",
          "size": 1461,
          "sha512": "a4557ab4b867d5ab823dcf44696bb423aa70c27ccbb1ed67fdbb370f4b8558c4e691296b6e42277d23b1d633d800b6fe57574d9b50f6be8420e08c5d5920eef7",
          "sha256": "0bd297fa30522a1e690cc1308fdd62513bb5284c7deff45f7026f61286ba1450",
          "sha1": "d9498b48c40bdc922c2f3744f7a53ca2b13dfc77",
          "md5": "2fd1e278e4da473ff07cb2772a6f74d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b92-0.8.4.jar",
          "url": "ble-characteristic-u2b92-0.8.4.jar",
          "size": 1461,
          "sha512": "a4557ab4b867d5ab823dcf44696bb423aa70c27ccbb1ed67fdbb370f4b8558c4e691296b6e42277d23b1d633d800b6fe57574d9b50f6be8420e08c5d5920eef7",
          "sha256": "0bd297fa30522a1e690cc1308fdd62513bb5284c7deff45f7026f61286ba1450",
          "sha1": "d9498b48c40bdc922c2f3744f7a53ca2b13dfc77",
          "md5": "2fd1e278e4da473ff07cb2772a6f74d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b92-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2b92-0.8.4-javadoc.jar",
          "size": 109925,
          "sha512": "ca18f64ed584caf9bc5b19ef4bc8438a5271dbc652825f5deda2ed0ea039cbc28132cb3ebc573e42f31760f9b07825a733170bc268a6a17dac501a283548e7e1",
          "sha256": "ffccd14a2faab780d465406b4f6ccfb52e053e3142693f856ae1baa2d74f695b",
          "sha1": "d786f1330706908294ffe4d7558ad2c4c50dd183",
          "md5": "b856b249186199e865390606adce9422"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b92-0.8.4-sources.jar",
          "url": "ble-characteristic-u2b92-0.8.4-sources.jar",
          "size": 1454,
          "sha512": "0cbaafe1bae7002065f0bdd9218a388c37737c49b5539128edfe81b5aa727b4bd73dcde329e3e8474ffb943a04bdd0d840892140e87dce4794517b133dd64043",
          "sha256": "c6e5966f66b3e9beb334f2002c6bb53b297f106c91847d8df0fa08eed19cd254",
          "sha1": "2698afd6352321b42f6674a6484f1a65d4422541",
          "md5": "dae3497945abcedb16774adfb1dc10d6"
        }
      ]
    }
  ]
}
