{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad6-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.4.4.aar",
          "url": "ble-characteristic-u2ad6-android-0.4.4.aar",
          "size": 3230,
          "sha512": "b940d3b9f41c2df49c3d4e23afb2292e853dc6aea08def9a58cfb5f47184f232074a7891bd1cd73052bef5e8705b880840a4a64ded8273c2b9dd53e2c54aec88",
          "sha256": "2a40747200b83cd73a677bbc1da8ad9a29040059f636e1ef4183fdd27a195a3d",
          "sha1": "adb27135b955d0bfb0f4fe2f5daebb7019b98761",
          "md5": "750dbbc4ad00bf30105314c060b90587"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-android-0.4.4.aar",
          "url": "ble-characteristic-u2ad6-android-0.4.4.aar",
          "size": 3230,
          "sha512": "b940d3b9f41c2df49c3d4e23afb2292e853dc6aea08def9a58cfb5f47184f232074a7891bd1cd73052bef5e8705b880840a4a64ded8273c2b9dd53e2c54aec88",
          "sha256": "2a40747200b83cd73a677bbc1da8ad9a29040059f636e1ef4183fdd27a195a3d",
          "sha1": "adb27135b955d0bfb0f4fe2f5daebb7019b98761",
          "md5": "750dbbc4ad00bf30105314c060b90587"
        }
      ]
    }
  ]
}
