{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a37",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "bo2m2bzyvfgbjfmoy4levvs3tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a37-0.2.2.jar",
          "url": "ble-characteristic-u2a37-0.2.2.jar",
          "size": 3219,
          "sha512": "512ad7c8955189f61364b04071d54dfc2582e406e5283e78811bd983f6abfe7778c3ce9a63b4f9a8c4d3161a945c91bc2cb240a489b8562931c6380e0b4cd4e2",
          "sha256": "fbbbb24787ad71c9587f8432575870336a48755a41f1e91f9c53df5e6994772d",
          "sha1": "187a76764830879b705a12e41eee2699bb00bfc4",
          "md5": "3534f84b40e42808d44afe87da2242d6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a37-0.2.2.jar",
          "url": "ble-characteristic-u2a37-0.2.2.jar",
          "size": 3219,
          "sha512": "512ad7c8955189f61364b04071d54dfc2582e406e5283e78811bd983f6abfe7778c3ce9a63b4f9a8c4d3161a945c91bc2cb240a489b8562931c6380e0b4cd4e2",
          "sha256": "fbbbb24787ad71c9587f8432575870336a48755a41f1e91f9c53df5e6994772d",
          "sha1": "187a76764830879b705a12e41eee2699bb00bfc4",
          "md5": "3534f84b40e42808d44afe87da2242d6"
        }
      ]
    }
  ]
}
