{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8b-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.2.2.aar",
          "url": "ble-characteristic-u2a8b-android-0.2.2.aar",
          "size": 3029,
          "sha512": "b9d8e3a46089af6e31d657bf6c9c642dfb813cf756eae1741ba3b086d51a7467eb0190db91a305d6ddcd65c7d5f8b7ddfdbf432c9bdd3b127025adfff56b9601",
          "sha256": "81acd27c702e4e0bbcc9dc54c0b610d77236488b68d9a75e2f23f2480dd8ce4e",
          "sha1": "5f941c05f8582f9ff2e8c5e0df2f0000c7b724d6",
          "md5": "fe1be1c0c7793207a1014d98332bad97"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.2.2.aar",
          "url": "ble-characteristic-u2a8b-android-0.2.2.aar",
          "size": 3029,
          "sha512": "b9d8e3a46089af6e31d657bf6c9c642dfb813cf756eae1741ba3b086d51a7467eb0190db91a305d6ddcd65c7d5f8b7ddfdbf432c9bdd3b127025adfff56b9601",
          "sha256": "81acd27c702e4e0bbcc9dc54c0b610d77236488b68d9a75e2f23f2480dd8ce4e",
          "sha1": "5f941c05f8582f9ff2e8c5e0df2f0000c7b724d6",
          "md5": "fe1be1c0c7793207a1014d98332bad97"
        }
      ]
    }
  ]
}
