{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a86-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kupq6qdcq5dovle6dw5m7myoyy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a86",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a86-android-0.2.3.aar",
          "url": "ble-characteristic-u2a86-android-0.2.3.aar",
          "size": 3161,
          "sha512": "d3a70eaddaeddedefe308d58f7f7e572f306370ca9831416c0b60a495928067cc09bc05ed357b19ddfa41e45aedf1a6dc98772084ee67cf5a494983c3037181e",
          "sha256": "dae3e5cb182003eedb266f94d7f82f86a78241e768dea64831634a58423e0bb1",
          "sha1": "41c2543bb4b1b0fdb92f108b983871331f866205",
          "md5": "867a3177506a2139f0c71d59f5700438"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a86",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a86-android-0.2.3.aar",
          "url": "ble-characteristic-u2a86-android-0.2.3.aar",
          "size": 3161,
          "sha512": "d3a70eaddaeddedefe308d58f7f7e572f306370ca9831416c0b60a495928067cc09bc05ed357b19ddfa41e45aedf1a6dc98772084ee67cf5a494983c3037181e",
          "sha256": "dae3e5cb182003eedb266f94d7f82f86a78241e768dea64831634a58423e0bb1",
          "sha1": "41c2543bb4b1b0fdb92f108b983871331f866205",
          "md5": "867a3177506a2139f0c71d59f5700438"
        }
      ]
    }
  ]
}
