{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b31-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b31",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b31-android-0.8.14.aar",
          "url": "ble-characteristic-u2b31-android-0.8.14.aar",
          "size": 3122,
          "sha512": "822804f77bd06520334c5e950ae3712f136dad48e89ef9692df9aa2fb0c9d3a36669a74bc27ed7350f225e5da95b555d3c70c336d15c316ac946a79c60140d28",
          "sha256": "4a45b889d4b8555b4ca5bb742054e5027c3dc05731083d92c8b10ca6b89e7d4c",
          "sha1": "1f9060db2b96396d3e285ca2f5a5e334b5c09f87",
          "md5": "e71f4bb0629270f6cc5b42b13ebf3fcf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b31",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b31-android-0.8.14.aar",
          "url": "ble-characteristic-u2b31-android-0.8.14.aar",
          "size": 3122,
          "sha512": "822804f77bd06520334c5e950ae3712f136dad48e89ef9692df9aa2fb0c9d3a36669a74bc27ed7350f225e5da95b555d3c70c336d15c316ac946a79c60140d28",
          "sha256": "4a45b889d4b8555b4ca5bb742054e5027c3dc05731083d92c8b10ca6b89e7d4c",
          "sha1": "1f9060db2b96396d3e285ca2f5a5e334b5c09f87",
          "md5": "e71f4bb0629270f6cc5b42b13ebf3fcf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b31-android-0.8.14-sources.jar",
          "url": "ble-characteristic-u2b31-android-0.8.14-sources.jar",
          "size": 2183,
          "sha512": "98251ce3a4b268a9b8cc199c12b120c7c87e5aec9991dbe78e338f506c5c04fe1d0c5fef0ff95cd515ade8d481c22110cc8589b25d286117f18275d38c4425c1",
          "sha256": "6ad1a5b3febed4c77b1891844407afcfff258ecc4047ec8b1171d9b68870c7ea",
          "sha1": "5c04cc0b1e38dbcbf97cc3f8d3c79080ea50326d",
          "md5": "54d0e57d7bcf5243a0100a6d4b62b188"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b31-android-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2b31-android-0.8.14-javadoc.jar",
          "size": 271050,
          "sha512": "bcc7d9c5fe34f383c64d13b09deae5c14ef4cf73c3b4fa065f3844a49067d632719fcdda0da74ed31bbf300ad12eab3c61ee1454c191ed3f7bddfc1a369f32e6",
          "sha256": "35aa5328857c6ca99816951f98e28d6a91eded422720a6814f4e683840f690ed",
          "sha1": "e4e9665585c2dfc4fe3bc9bf12b92249f11f574e",
          "md5": "8c5202cadd212fffc418b48b1f8e1e21"
        }
      ]
    }
  ]
}
