{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lls-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a06-android",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lls-android-0.1.4.aar",
          "url": "ble-service-lls-android-0.1.4.aar",
          "size": 1205,
          "sha512": "054398544f716da37066541f535252de56425ea47d78f06aab2a7ffb43214b86901b60e5b5c3f214619c5762b2e4b957a77465ddaed6a6df2685ad8471827d6c",
          "sha256": "fd6f54a9f407b4801b5bb3bf4df59b1e62b227d33db241542280c23401216e87",
          "sha1": "8d46fc0e2dfc3bf2a9b6950be8643dc6d3143ce2",
          "md5": "aa8c95352d3d765851620245f479d867"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a06-android",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lls-android-0.1.4.aar",
          "url": "ble-service-lls-android-0.1.4.aar",
          "size": 1205,
          "sha512": "054398544f716da37066541f535252de56425ea47d78f06aab2a7ffb43214b86901b60e5b5c3f214619c5762b2e4b957a77465ddaed6a6df2685ad8471827d6c",
          "sha256": "fd6f54a9f407b4801b5bb3bf4df59b1e62b227d33db241542280c23401216e87",
          "sha1": "8d46fc0e2dfc3bf2a9b6950be8643dc6d3143ce2",
          "md5": "aa8c95352d3d765851620245f479d867"
        }
      ]
    }
  ]
}
