{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-tps-peripheral-android",
    "version": "0.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-tps-peripheral-android-0.1.14.aar",
          "url": "ble-service-tps-peripheral-android-0.1.14.aar",
          "size": 3860,
          "sha512": "6ecc8ac3bc9972e87d40559f66d8b0c6c8197eb714a8030f43b9f0fc0cc58562196260c06d425e2c4fd1a8dc49ee57be713e7b44944ae61c87b2e5b7f2658af0",
          "sha256": "76ca586b9fed49ede71d10705e9c793fde3f835b22d6c28b2d96227d19f3b81c",
          "sha1": "8bcc78ca23e085de81dc588811043709e857b0b8",
          "md5": "fb83180418a6f9b6ed258448a3835250"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.1.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-tps-peripheral-android-0.1.14.aar",
          "url": "ble-service-tps-peripheral-android-0.1.14.aar",
          "size": 3860,
          "sha512": "6ecc8ac3bc9972e87d40559f66d8b0c6c8197eb714a8030f43b9f0fc0cc58562196260c06d425e2c4fd1a8dc49ee57be713e7b44944ae61c87b2e5b7f2658af0",
          "sha256": "76ca586b9fed49ede71d10705e9c793fde3f835b22d6c28b2d96227d19f3b81c",
          "sha1": "8bcc78ca23e085de81dc588811043709e857b0b8",
          "md5": "fb83180418a6f9b6ed258448a3835250"
        }
      ]
    }
  ]
}
