{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a16-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a16",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-android-0.2.7.aar",
          "url": "ble-characteristic-u2a16-android-0.2.7.aar",
          "size": 3118,
          "sha512": "28ea149709249685923264207d059b0249ef9f9e42843de97fcbddb4253d83286dab23cd94ca8634a534fb5a4c33ab59c54be1522a05413368306272eb4b2d9c",
          "sha256": "0cfa6ca2b08d1679f4431f19b6d2144332f503cd7bde00f73f66a3698cac587d",
          "sha1": "58d6832eea2cc44973d9ba097a114ebcd7b2bba4",
          "md5": "5a93cfd0813aa785539558fdb324b059"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a16",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-android-0.2.7.aar",
          "url": "ble-characteristic-u2a16-android-0.2.7.aar",
          "size": 3118,
          "sha512": "28ea149709249685923264207d059b0249ef9f9e42843de97fcbddb4253d83286dab23cd94ca8634a534fb5a4c33ab59c54be1522a05413368306272eb4b2d9c",
          "sha256": "0cfa6ca2b08d1679f4431f19b6d2144332f503cd7bde00f73f66a3698cac587d",
          "sha1": "58d6832eea2cc44973d9ba097a114ebcd7b2bba4",
          "md5": "5a93cfd0813aa785539558fdb324b059"
        }
      ]
    }
  ]
}
