{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3a",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.12.jar",
          "url": "ble-characteristic-u2b3a-0.8.12.jar",
          "size": 2726,
          "sha512": "e3bc9fd55cc6054b003abf22b06284fbfc2077238919f5349ca97d6713d906269b5b2e9007a0dd3b432fd6f539df601d5e03c826a2d351702b1b8cdbbf0fdd55",
          "sha256": "132a0a6aef7cd99ed281dff2c33f7a29e1c82a6bfc5b118199ffac17868c55c0",
          "sha1": "8df7b4a775c2755f6d4bb47e5c20e859c95382aa",
          "md5": "c5c6eab08feda363d1af8dedfc65afec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.12.jar",
          "url": "ble-characteristic-u2b3a-0.8.12.jar",
          "size": 2726,
          "sha512": "e3bc9fd55cc6054b003abf22b06284fbfc2077238919f5349ca97d6713d906269b5b2e9007a0dd3b432fd6f539df601d5e03c826a2d351702b1b8cdbbf0fdd55",
          "sha256": "132a0a6aef7cd99ed281dff2c33f7a29e1c82a6bfc5b118199ffac17868c55c0",
          "sha1": "8df7b4a775c2755f6d4bb47e5c20e859c95382aa",
          "md5": "c5c6eab08feda363d1af8dedfc65afec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b3a-0.8.12-javadoc.jar",
          "size": 108023,
          "sha512": "5954df0b1a7f6c79acf6d8d26e4174aedb615e9ae623dfb57cdf74276fc10abbee72e0dbeca82b26d45641b26d085d06e51515b866394a311e4e3b18d7928f77",
          "sha256": "b17e528144df4b3d8046ccd63f35769edb6f9f2125c427b6cc69a0fd1958fd9a",
          "sha1": "4c11e48db8fe5c1daa891fb08e9e6c6e234074aa",
          "md5": "886bce3c60eb553f20f95fb36846a6f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3a-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b3a-0.8.12-sources.jar",
          "size": 2049,
          "sha512": "a5892dca97ee7edc462160bb6aadbaec7cb1085e0d1e072242457a002ce3cd7442132b00687fb670fb8b0d57c6674e3e4020c0f960462af965be85cbecf9d87e",
          "sha256": "54bf5a9c0dbff5a138837c857d3418bfb236b532269e13516d2b98717e6b3377",
          "sha1": "928f442adcff5d6eb02d3b6ff0e0cb7d39a002f0",
          "md5": "cc1bb7bc85ee76707928607fe69fa84c"
        }
      ]
    }
  ]
}
