{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba1-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba1",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba1-android-0.4.2.aar",
          "url": "ble-characteristic-u2ba1-android-0.4.2.aar",
          "size": 3050,
          "sha512": "0f4e4eada9ff2609e90814b8a3047291b88293d6925c35da6fd67dde6bd5964cc6ee2412b66c0317b6282ee1bb0a765b39f97d522a05d9df99f3daf32f25a78a",
          "sha256": "f7a0cb8d13e83a90d0b63eef48b56f84afa73c3cc9e06c086d37ee58f555c079",
          "sha1": "58cce7ec81ad0cb8492a3ccace8143ed344a14d6",
          "md5": "334aebdda39351b2fbeb2556ac39a4ba"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba1",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba1-android-0.4.2.aar",
          "url": "ble-characteristic-u2ba1-android-0.4.2.aar",
          "size": 3050,
          "sha512": "0f4e4eada9ff2609e90814b8a3047291b88293d6925c35da6fd67dde6bd5964cc6ee2412b66c0317b6282ee1bb0a765b39f97d522a05d9df99f3daf32f25a78a",
          "sha256": "f7a0cb8d13e83a90d0b63eef48b56f84afa73c3cc9e06c086d37ee58f555c079",
          "sha1": "58cce7ec81ad0cb8492a3ccace8143ed344a14d6",
          "md5": "334aebdda39351b2fbeb2556ac39a4ba"
        }
      ]
    }
  ]
}
