{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd3",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd3-0.8.2.jar",
          "url": "ble-characteristic-u2bd3-0.8.2.jar",
          "size": 1545,
          "sha512": "af2c3ce4652509efbc02d280e7933146823e693146d95cc75a68a84433b197a1cff8b5af493afaa4d57079f790b045cc3bdbd94090f3c18f202637761426fb15",
          "sha256": "33b1640285c64625b7d439c8d467338b7519c8e5c07842068e644c325c520cb5",
          "sha1": "70471b144a28f3142a1710dfb37a39d7d0eca251",
          "md5": "a8c04f55f36f1553ab7db858b16217c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd3-0.8.2.jar",
          "url": "ble-characteristic-u2bd3-0.8.2.jar",
          "size": 1545,
          "sha512": "af2c3ce4652509efbc02d280e7933146823e693146d95cc75a68a84433b197a1cff8b5af493afaa4d57079f790b045cc3bdbd94090f3c18f202637761426fb15",
          "sha256": "33b1640285c64625b7d439c8d467338b7519c8e5c07842068e644c325c520cb5",
          "sha1": "70471b144a28f3142a1710dfb37a39d7d0eca251",
          "md5": "a8c04f55f36f1553ab7db858b16217c5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd3-0.8.2-javadoc.jar",
          "url": "ble-characteristic-u2bd3-0.8.2-javadoc.jar",
          "size": 110182,
          "sha512": "ba425d28bc81fe2b251f63e4924776c4d70098ea8125d1edab113323a09062855ac4ec074f7681fc3f4c1d1bfe9d2fbc98c2c8feeb0ed1578649d5abe9afcee9",
          "sha256": "8619663724e6fdbb4a000e7bc58d5efafaddb9d5656d2d1577de87267631258b",
          "sha1": "a6cc61fc04d24c0de22741a612e94c154ac4a959",
          "md5": "8b657fd9c5aa2fd99636d4e5a11166e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd3-0.8.2-sources.jar",
          "url": "ble-characteristic-u2bd3-0.8.2-sources.jar",
          "size": 1554,
          "sha512": "e11140869f0318b2613d3e434eacca562bd6c82bed85419ab50b32481259d2a33239e825466e73e05d3e0d0dbbdb4bb15ca803ed7593f7e554f209104f01e40d",
          "sha256": "337814b25621c3304722a774ad7ee6d3e57035e9a30f45f9aa7c44d940b71806",
          "sha1": "c0cfc219cc9339dedc0a0433fad47cc12be9efd5",
          "md5": "27476a4fc32b31f58d4fa0281e3cf37b"
        }
      ]
    }
  ]
}
