{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a26-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "smp7vu2g4jdlfelcafoemcahhe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a26",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a26-android-0.2.8.aar",
          "url": "ble-characteristic-u2a26-android-0.2.8.aar",
          "size": 3132,
          "sha512": "4144e4ae9918c4bc8e15824b20ac0c62bd2814bb694832d4ef2d1e25b8c74e0d246d4650b559518199325e1a06cc35c1d62d793e2dcf516820a27dc0b929fca8",
          "sha256": "5677127c3225786fb824031a825a27cf228774333c66ee88fed02aa4ed4ea996",
          "sha1": "8356ea7f6dbbab477c1ed74da8b02f6ed2b50198",
          "md5": "e569702aeb2fdde36403254680546a5c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a26",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a26-android-0.2.8.aar",
          "url": "ble-characteristic-u2a26-android-0.2.8.aar",
          "size": 3132,
          "sha512": "4144e4ae9918c4bc8e15824b20ac0c62bd2814bb694832d4ef2d1e25b8c74e0d246d4650b559518199325e1a06cc35c1d62d793e2dcf516820a27dc0b929fca8",
          "sha256": "5677127c3225786fb824031a825a27cf228774333c66ee88fed02aa4ed4ea996",
          "sha1": "8356ea7f6dbbab477c1ed74da8b02f6ed2b50198",
          "md5": "e569702aeb2fdde36403254680546a5c"
        }
      ]
    }
  ]
}
