{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-blp-android",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-blp-android-0.8.14.aar",
          "url": "ble-profile-blp-android-0.8.14.aar",
          "size": 1298,
          "sha512": "47e5160af36c2372ede4c4477d20657d6b52ca2f2bb3a8bd08bddbd388c5757ea4e94bd2d7f1fa434e06036d5e3a7c65a056c9c43bc11048b11bba6576e49c45",
          "sha256": "8feb58611a83dcb20577f44ac5cb0e8273dbd567a72b87981f975a7b403fc380",
          "sha1": "1310258ed9d059bce29d824fbf2819331968df57",
          "md5": "a37e205684c9264337eca4e9a875a18e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-blp-android-0.8.14.aar",
          "url": "ble-profile-blp-android-0.8.14.aar",
          "size": 1298,
          "sha512": "47e5160af36c2372ede4c4477d20657d6b52ca2f2bb3a8bd08bddbd388c5757ea4e94bd2d7f1fa434e06036d5e3a7c65a056c9c43bc11048b11bba6576e49c45",
          "sha256": "8feb58611a83dcb20577f44ac5cb0e8273dbd567a72b87981f975a7b403fc380",
          "sha1": "1310258ed9d059bce29d824fbf2819331968df57",
          "md5": "a37e205684c9264337eca4e9a875a18e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-blp-android-0.8.14-sources.jar",
          "url": "ble-profile-blp-android-0.8.14-sources.jar",
          "size": 1191,
          "sha512": "5335392344b0f93fedb09c6f58b02a3e1877cd0ecfec74292f4d0def82cb9f6d8f690e812fe350c27a8c88b164c122579e905873d2cd287709c1b2bf60376696",
          "sha256": "30dafb0d56a2325f73074f257cce274bda0e7c0fb533f6f16d3a844a10dbe460",
          "sha1": "13eb476d33d731a967591e3a35da406403d27177",
          "md5": "726425a6e1c88b07b3cbcc97b35b028c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-blp-android-0.8.14-javadoc.jar",
          "url": "ble-profile-blp-android-0.8.14-javadoc.jar",
          "size": 259941,
          "sha512": "e2d8a4664f45a28118bc057261ef21c33835b99b2d91dff97c75f804b6103d0dd4935b4901e5dca698efe6b8ccc9187a93b4d528d39bad51471c46c1cfd66813",
          "sha256": "517c60023facc5a97aeffe31a4896c190807da9acbb4e355bc4907cc9be3cf30",
          "sha1": "c49d7a1e6f0e835ab862c2ade8d3be4c2ac75a3b",
          "md5": "544032a62affe9ed288a7c73b6c28c3c"
        }
      ]
    }
  ]
}
