{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2baf",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.5.1.jar",
          "url": "ble-characteristic-u2baf-0.5.1.jar",
          "size": 1558,
          "sha512": "b70ae91fd38895015d6756da252c4ca3eada77947cff5d98e3554f179a8e4e62ad6d7caeea203a4d59f14b9332d33d2391fe1898255c81a9af7fa1a9a014a6bc",
          "sha256": "ddc6f2cc59b5388fb2186dc2648a25824d58567b5a9eb7037939e4c7e65f71e5",
          "sha1": "2310fe85dda09f99c678b24c58232e99e962c0cd",
          "md5": "a74fb2f52ebe48294329bfba765eb4a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.5.1.jar",
          "url": "ble-characteristic-u2baf-0.5.1.jar",
          "size": 1558,
          "sha512": "b70ae91fd38895015d6756da252c4ca3eada77947cff5d98e3554f179a8e4e62ad6d7caeea203a4d59f14b9332d33d2391fe1898255c81a9af7fa1a9a014a6bc",
          "sha256": "ddc6f2cc59b5388fb2186dc2648a25824d58567b5a9eb7037939e4c7e65f71e5",
          "sha1": "2310fe85dda09f99c678b24c58232e99e962c0cd",
          "md5": "a74fb2f52ebe48294329bfba765eb4a3"
        }
      ]
    }
  ]
}
