{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a73-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "sipxf3vz2bcx5mgcg6vcjbnlti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a73",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a73-android-0.2.1.aar",
          "url": "ble-characteristic-u2a73-android-0.2.1.aar",
          "size": 2936,
          "sha512": "ea92a2b36ecd7aa499a6302d72abc8a3e6a7b047cbe09c77adc9150b6f2b34bd6ca882b19521cce8059799fbd34995e2af9b2b7666a196ba6092dec5592ec8a6",
          "sha256": "4e264af7d4d680607e8eab4e7b35b98370a06cf92b741159e0442efba4c4724b",
          "sha1": "8f9f07d42782216576e5de305723563013f267ce",
          "md5": "902283bd245f24e98ce3491bc057a750"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a73",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a73-android-0.2.1.aar",
          "url": "ble-characteristic-u2a73-android-0.2.1.aar",
          "size": 2936,
          "sha512": "ea92a2b36ecd7aa499a6302d72abc8a3e6a7b047cbe09c77adc9150b6f2b34bd6ca882b19521cce8059799fbd34995e2af9b2b7666a196ba6092dec5592ec8a6",
          "sha256": "4e264af7d4d680607e8eab4e7b35b98370a06cf92b741159e0442efba4c4724b",
          "sha1": "8f9f07d42782216576e5de305723563013f267ce",
          "md5": "902283bd245f24e98ce3491bc057a750"
        }
      ]
    }
  ]
}
