{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a2b-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zzwrv7bhbfgvlhoshhgo5ogf5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2b",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2b-android-0.2.3.aar",
          "url": "ble-characteristic-u2a2b-android-0.2.3.aar",
          "size": 3018,
          "sha512": "10b27b2cb20ac2ac0753eff63db5db16a9ab3da8196dbbf60041e6c69b5c5032601ac6b1539466438bd3eb6625ac769a0e261746d027be9aa58e15c5e262721c",
          "sha256": "50ceb1ff23b4f4536274d266e726d975e9a8bf3404bb2aaf1094e77509b11fed",
          "sha1": "302da6dd98fcea8140a0e27e0e2b4975c1512231",
          "md5": "ca3059aa3c37208bd83aaf757e8a0fba"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a2b",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2b-android-0.2.3.aar",
          "url": "ble-characteristic-u2a2b-android-0.2.3.aar",
          "size": 3018,
          "sha512": "10b27b2cb20ac2ac0753eff63db5db16a9ab3da8196dbbf60041e6c69b5c5032601ac6b1539466438bd3eb6625ac769a0e261746d027be9aa58e15c5e262721c",
          "sha256": "50ceb1ff23b4f4536274d266e726d975e9a8bf3404bb2aaf1094e77509b11fed",
          "sha1": "302da6dd98fcea8140a0e27e0e2b4975c1512231",
          "md5": "ca3059aa3c37208bd83aaf757e8a0fba"
        }
      ]
    }
  ]
}
