{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc4-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc4-android-0.8.6.aar",
          "url": "ble-characteristic-u2bc4-android-0.8.6.aar",
          "size": 3026,
          "sha512": "6057ce1583a6c8c49de317bd6126e328a563f99b3191b04823c0a07d07c226e8e229fa1db29b0ce8fd962f11f14ce20b96dade2b591e05a0fec25c09910630c9",
          "sha256": "ae25d786dc5930661dc21319dbed2e69875940d304b95aec2e9eb3e347aec48e",
          "sha1": "96fec2d248122d83774acfe736c4f2c46c5afb4b",
          "md5": "1baf267a83e3b3577f658fbde01ff2eb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bc4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc4-android-0.8.6.aar",
          "url": "ble-characteristic-u2bc4-android-0.8.6.aar",
          "size": 3026,
          "sha512": "6057ce1583a6c8c49de317bd6126e328a563f99b3191b04823c0a07d07c226e8e229fa1db29b0ce8fd962f11f14ce20b96dade2b591e05a0fec25c09910630c9",
          "sha256": "ae25d786dc5930661dc21319dbed2e69875940d304b95aec2e9eb3e347aec48e",
          "sha1": "96fec2d248122d83774acfe736c4f2c46c5afb4b",
          "md5": "1baf267a83e3b3577f658fbde01ff2eb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc4-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bc4-android-0.8.6-sources.jar",
          "size": 2119,
          "sha512": "2c2288840109919c0b34a70f167c15f42c2dd0a4e3f70e80304ec418e99421b131229aac8a0494412f45145856a04b2e3425a83173f5f0fd66c4b1198c50724b",
          "sha256": "d7cbc6344aa43763d2437b892e7372d2232545c8cd00fdb166dc59e6bda6ee42",
          "sha1": "fb5d1306f1f3482a12fa0dcb75de00615b5a9074",
          "md5": "0ff320761d29c1e756e99189340226fa"
        }
      ]
    }
  ]
}
