{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1e",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1e-0.8.5.jar",
          "url": "ble-characteristic-u2b1e-0.8.5.jar",
          "size": 2774,
          "sha512": "f6a867e8c42a86dc764387463c96e01d95da59d4fb1add4706974e0943e43b8f26db25daa4ba64473824e6990c36f19077e792ca5ff1826bc383138171eb7021",
          "sha256": "3251a6431797cca3b15e597ef3c276e2e4be3d4456c2d4ff73e7cff740684faa",
          "sha1": "eca7587b596563c855f8cd8a86d5af526d61dea2",
          "md5": "907c71f9c83a79016b13dbb66e07dc6a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1e-0.8.5.jar",
          "url": "ble-characteristic-u2b1e-0.8.5.jar",
          "size": 2774,
          "sha512": "f6a867e8c42a86dc764387463c96e01d95da59d4fb1add4706974e0943e43b8f26db25daa4ba64473824e6990c36f19077e792ca5ff1826bc383138171eb7021",
          "sha256": "3251a6431797cca3b15e597ef3c276e2e4be3d4456c2d4ff73e7cff740684faa",
          "sha1": "eca7587b596563c855f8cd8a86d5af526d61dea2",
          "md5": "907c71f9c83a79016b13dbb66e07dc6a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1e-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b1e-0.8.5-javadoc.jar",
          "size": 112443,
          "sha512": "f08f5f2f58c19ee041c09b6aaf56cc9af7378c0209b5fa2a5b30ae9fc2b95537b9a98c610d37ecdd6d82f6a9c2bddddffebc38413289437017fac05ffcea1bca",
          "sha256": "4ef2de14241dc5a5806b4d3076e13c921a221d3b043d088b06f5ae3cc754bc0c",
          "sha1": "f68b68ba2ba5a2e89ec6ab5973f9fe51404fcc53",
          "md5": "cbdb7cc4b9673164f0c2a650b9a467dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1e-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b1e-0.8.5-sources.jar",
          "size": 2689,
          "sha512": "afe98a320c19d3c34ae0d38b72256da0e81fe5f49528c389ae6b3edcd5cd225e7a54ef96f5dab9f8727ae84c87d41f42390d34ce19c9e77b20293e0d3e136c90",
          "sha256": "b1ebf23212ce8f6437a840ec59ff36187b397a41af2ec8bc0b5591a317be7d1f",
          "sha1": "32db1eabee95d96808b49fb9d34afbedb993c397",
          "md5": "7a1c2a4906ad7badf132955176bc110a"
        }
      ]
    }
  ]
}
