{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abb",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abb-0.8.11.jar",
          "url": "ble-characteristic-u2abb-0.8.11.jar",
          "size": 1910,
          "sha512": "103469a7fffba70b5d7222c6c5ecee93985e873e0c9773d1ce7119c194d94b7306ffc902dbe3d01c2030de6668f19d839f2980a810641b6fd7851844a5c386b8",
          "sha256": "6f2247e70754c3e29d25ac1ca638bd91bf7c6d3e7bacb3b23bcbb23be7511ea0",
          "sha1": "25b9ffb83096e8b5f67a777e0d312fcf5f9272e7",
          "md5": "c9bc01b0cc394e28aff1258ba1143e12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abb-0.8.11.jar",
          "url": "ble-characteristic-u2abb-0.8.11.jar",
          "size": 1910,
          "sha512": "103469a7fffba70b5d7222c6c5ecee93985e873e0c9773d1ce7119c194d94b7306ffc902dbe3d01c2030de6668f19d839f2980a810641b6fd7851844a5c386b8",
          "sha256": "6f2247e70754c3e29d25ac1ca638bd91bf7c6d3e7bacb3b23bcbb23be7511ea0",
          "sha1": "25b9ffb83096e8b5f67a777e0d312fcf5f9272e7",
          "md5": "c9bc01b0cc394e28aff1258ba1143e12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2abb-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2abb-0.8.11-javadoc.jar",
          "size": 109609,
          "sha512": "53107d678a8691182b60a6759ef30e9c443452fcdb9b7044e3a1db6e10893967fe3d0a18d9cbb636c7c6a2e9e6853f08d600c6c85ba648d22b089885cf36597c",
          "sha256": "620f0762cbe63763e91c0fa61e80d90f9de4ff3a9bb219fb1e1bf39612d9bba4",
          "sha1": "b90c56629bca4b5d68118ba1254716d598b3dc69",
          "md5": "0644283f676e1993c4328942714270e4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2abb-0.8.11-sources.jar",
          "url": "ble-characteristic-u2abb-0.8.11-sources.jar",
          "size": 1748,
          "sha512": "c04c3fa81d6dff6af2d297162f927e8231521b8f91a5d3206c395414e9117592f60faba48c1d11e8a1234a8fd78632b4a2eb825df94edb793cd6517f625ee482",
          "sha256": "14621f3add2dcb5db767433672398f4666d0fb54f7f8351f9673914f92f4b8e9",
          "sha1": "ea209be6ff28b1854c71ccda7cd45cf325f9a6a4",
          "md5": "100cc2ec91096111b786662e0159b618"
        }
      ]
    }
  ]
}
