{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab4-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.4.5.aar",
          "url": "ble-characteristic-u2ab4-android-0.4.5.aar",
          "size": 3092,
          "sha512": "e73600e0037e68f728e2267bb790cc59c1011a70754e493cbcee5984ef50b4207d6b280ea1f2948cee5f2736f877f30e0e22a050688f3600ef7b56142f1a7955",
          "sha256": "b4fd4433a6755af203090b6dfc25031fdd24595cb12af7f1355818a392a51440",
          "sha1": "869b76ad0d084df4fc6eaffd0679aace662ab614",
          "md5": "339674eaba2bb9441f3d3b25d335573f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab4",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab4-android-0.4.5.aar",
          "url": "ble-characteristic-u2ab4-android-0.4.5.aar",
          "size": 3092,
          "sha512": "e73600e0037e68f728e2267bb790cc59c1011a70754e493cbcee5984ef50b4207d6b280ea1f2948cee5f2736f877f30e0e22a050688f3600ef7b56142f1a7955",
          "sha256": "b4fd4433a6755af203090b6dfc25031fdd24595cb12af7f1355818a392a51440",
          "sha1": "869b76ad0d084df4fc6eaffd0679aace662ab614",
          "md5": "339674eaba2bb9441f3d3b25d335573f"
        }
      ]
    }
  ]
}
