{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b94-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b94",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-android-0.8.6.aar",
          "url": "ble-characteristic-u2b94-android-0.8.6.aar",
          "size": 3091,
          "sha512": "526ec78630df68ae5feb3fdc9fb9fd10cc7a643b11d5d981f4681628b3f7f3eb53cd9c56b245b5b462b581d1833b7b47e44624ab3a3511523bdce6eaf7c0a2d5",
          "sha256": "3d589eddfd245e38aa16298cac225bbf88b65976d72e0f7d69d6192a222f6d7e",
          "sha1": "4f2a4924c19d173c44374e81d94a2ad1cf5fb770",
          "md5": "5554449f39cfe840c2d50372f738d14e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b94",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-android-0.8.6.aar",
          "url": "ble-characteristic-u2b94-android-0.8.6.aar",
          "size": 3091,
          "sha512": "526ec78630df68ae5feb3fdc9fb9fd10cc7a643b11d5d981f4681628b3f7f3eb53cd9c56b245b5b462b581d1833b7b47e44624ab3a3511523bdce6eaf7c0a2d5",
          "sha256": "3d589eddfd245e38aa16298cac225bbf88b65976d72e0f7d69d6192a222f6d7e",
          "sha1": "4f2a4924c19d173c44374e81d94a2ad1cf5fb770",
          "md5": "5554449f39cfe840c2d50372f738d14e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b94-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b94-android-0.8.6-sources.jar",
          "size": 2196,
          "sha512": "e905ec38490da9085adc5916753caf40aae0c865f89c5138abb0389580a11d082ce3c44213dafa35e211e6045cfc9aa80251b70419268f714205849204b1f02e",
          "sha256": "31e7c9e5a9bb75c466dadd83d3f7127a11cf36750ae97e8e28178d7f8986523c",
          "sha1": "71d89d69eae12113d9fc62e3fe3554254c77186a",
          "md5": "026694d82218102bb885a4c4f6b1444e"
        }
      ]
    }
  ]
}
