{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bdf-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bdf",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bdf-android-0.8.11.aar",
          "url": "ble-characteristic-u2bdf-android-0.8.11.aar",
          "size": 3192,
          "sha512": "35e300c4ab80d85135f4a31ac72b43ec873551ad63fec3e3a20fd1ae0720f071401e5cf7f224369e785aaad026d8e8569240b9af591e4832c8b5cf030e8c7889",
          "sha256": "e584e877062403b791f5ab479b60ee26e27f4a35f1e844eee44c5efa86c0c988",
          "sha1": "c16aad47f3a9fd4cc6dc38e30d10f8417e44e192",
          "md5": "b8096a5aad8da3e2ebc6e36928467642"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bdf",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bdf-android-0.8.11.aar",
          "url": "ble-characteristic-u2bdf-android-0.8.11.aar",
          "size": 3192,
          "sha512": "35e300c4ab80d85135f4a31ac72b43ec873551ad63fec3e3a20fd1ae0720f071401e5cf7f224369e785aaad026d8e8569240b9af591e4832c8b5cf030e8c7889",
          "sha256": "e584e877062403b791f5ab479b60ee26e27f4a35f1e844eee44c5efa86c0c988",
          "sha1": "c16aad47f3a9fd4cc6dc38e30d10f8417e44e192",
          "md5": "b8096a5aad8da3e2ebc6e36928467642"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bdf-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2bdf-android-0.8.11-sources.jar",
          "size": 2172,
          "sha512": "2f1b885f2e898f65765226f02f168cc51b67c334043e100d9bee60cd86e6872c899e28dc812500aab3228aa1d651fec730e6febc1d098e6292b0ad9faa2862ca",
          "sha256": "74f370f40cb04dab086ad53a3e171821eedc666cb18d80480d4ddfda7c86882b",
          "sha1": "48ef01254d777c958468a6db26b958904ee8f3f2",
          "md5": "8ee06d847ae97180f243ceac0d22e26b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bdf-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2bdf-android-0.8.11-javadoc.jar",
          "size": 272410,
          "sha512": "8ee181fd4bf14ea3f34b5289064a662585b562bc655ab005cdc9602e76bc26030b42e04d1565a9e0c7f5c0f8f894718682ee9f1dac136f485f9fd13048b22950",
          "sha256": "a2d4a1e924c73a7290891585c1708976d2c2114d70b497c834be93dc59b094c6",
          "sha1": "d38f0ee682971767dda757c9895674ad21c1991d",
          "md5": "dc07400e6a960482eb21331c834840f0"
        }
      ]
    }
  ]
}
