{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa6-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6cu2oomv2fb67ivu2iebxgsxbm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa6",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa6-android-0.2.0.aar",
          "url": "ble-characteristic-u2aa6-android-0.2.0.aar",
          "size": 2954,
          "sha512": "47e673b626868598958385fdd4eb8068deadb08b434b82419c07da218f6f4e81264be481bfbc2baeae9840e79201d200b9a52e889280246bdcddb8cd5c309ca6",
          "sha256": "7069d3fd53d0b70c4c31bdeef1e32b60ccaeae35fbac262ff9a2416954308177",
          "sha1": "0d14c8a971c19ce1dd2cafafcd212d6d93471c9e",
          "md5": "29331d4800e1b8fdf293f5fa1a73c932"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa6",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa6-android-0.2.0.aar",
          "url": "ble-characteristic-u2aa6-android-0.2.0.aar",
          "size": 2954,
          "sha512": "47e673b626868598958385fdd4eb8068deadb08b434b82419c07da218f6f4e81264be481bfbc2baeae9840e79201d200b9a52e889280246bdcddb8cd5c309ca6",
          "sha256": "7069d3fd53d0b70c4c31bdeef1e32b60ccaeae35fbac262ff9a2416954308177",
          "sha1": "0d14c8a971c19ce1dd2cafafcd212d6d93471c9e",
          "md5": "29331d4800e1b8fdf293f5fa1a73c932"
        }
      ]
    }
  ]
}
