{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-uds-peripheral-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-uds-peripheral-android-0.1.6.aar",
          "url": "ble-service-uds-peripheral-android-0.1.6.aar",
          "size": 26370,
          "sha512": "4b513e8cdba83c5aeed32c13d61d4a1c931bb39c61562903e4c48529097ffa0cbe68c858f708a1f3ecf13dabce61f49832520904626ac16e9c61c3ca98e99eb4",
          "sha256": "96f4a14f8daac4f78eb082c15cac2a86e576d0a838d6735f4305f15fe26ad87f",
          "sha1": "29ce79dfc09954eb68cd05a4f1528dc595277833",
          "md5": "8ffc0371d5c7d579ffb227cf6fbe7906"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-uds-peripheral-android-0.1.6.aar",
          "url": "ble-service-uds-peripheral-android-0.1.6.aar",
          "size": 26370,
          "sha512": "4b513e8cdba83c5aeed32c13d61d4a1c931bb39c61562903e4c48529097ffa0cbe68c858f708a1f3ecf13dabce61f49832520904626ac16e9c61c3ca98e99eb4",
          "sha256": "96f4a14f8daac4f78eb082c15cac2a86e576d0a838d6735f4305f15fe26ad87f",
          "sha1": "29ce79dfc09954eb68cd05a4f1528dc595277833",
          "md5": "8ffc0371d5c7d579ffb227cf6fbe7906"
        }
      ]
    }
  ]
}
