{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a87",
    "version": "0.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a87-0.6.2.jar",
          "url": "ble-characteristic-u2a87-0.6.2.jar",
          "size": 2301,
          "sha512": "06c0b6c9e15e782e74432d41d4c6472b87c3d264b6cb9b76011ace1cb5961d3581f7d6393cea56f07ce3300a18276cae2ec5f47f91d3610d324f8d92a7cf6776",
          "sha256": "094f5a70bf2404a3f1f4fd875ebe9cba3a68625149d5e5cd4fb5aad449b8446f",
          "sha1": "77be7b8bef369130008d8d9316ba1965f2cd753f",
          "md5": "9482fd65e2459886f5e66881f12e2f27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b37",
          "version": {
            "requires": "0.6.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a87-0.6.2.jar",
          "url": "ble-characteristic-u2a87-0.6.2.jar",
          "size": 2301,
          "sha512": "06c0b6c9e15e782e74432d41d4c6472b87c3d264b6cb9b76011ace1cb5961d3581f7d6393cea56f07ce3300a18276cae2ec5f47f91d3610d324f8d92a7cf6776",
          "sha256": "094f5a70bf2404a3f1f4fd875ebe9cba3a68625149d5e5cd4fb5aad449b8446f",
          "sha1": "77be7b8bef369130008d8d9316ba1965f2cd753f",
          "md5": "9482fd65e2459886f5e66881f12e2f27"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a87-0.6.2-javadoc.jar",
          "url": "ble-characteristic-u2a87-0.6.2-javadoc.jar",
          "size": 110062,
          "sha512": "8b60ed51e5dea58cd3cce883c5636e84c71c4d354d9b5b00784df18553ab4be0d9340cd9fd99af805da88a8bd5380030b8a80b3b65eb0557490a7074c86bd653",
          "sha256": "071968f59971054fdf71887ea2cebb2d412ed4cae4a55d8ab82cd9203e5f680b",
          "sha1": "85b86cd4882d276383e40412aaa6fbcf97130e7d",
          "md5": "a7fae4062bb4316d74298bc502aea8bd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a87-0.6.2-sources.jar",
          "url": "ble-characteristic-u2a87-0.6.2-sources.jar",
          "size": 1792,
          "sha512": "4af7c7965763ea4147c4db5166c9b28eeb45f0497e6a938cb545a008b8b709fa8a53caa9950b5b43be39f3c8b394fb34beaab8c1b047aca76e43f22020b6b1b6",
          "sha256": "a02553bef983eb1e9e1bf15eadeb0711b6ecc0f0ec8a14c2aff9fc20a5940415",
          "sha1": "be31840dfebf8c50c7cc12cbd1fa6ae806bb58b6",
          "md5": "989cfc3911f36918126128ea6b25b4c6"
        }
      ]
    }
  ]
}
