{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-hrs-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-android",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-hrs-android-0.8.8.aar",
          "url": "ble-service-peripheral-hrs-android-0.8.8.aar",
          "size": 6619,
          "sha512": "8642c6261fcd1b30f31922c82c9679575da42c0c5e2d3409e0a2192f635b45a5a68184d5c6e172ec392b22529624b30cb15a596475469200234fb77c916e9985",
          "sha256": "0eab6d18bbdb749b98a3c2444c9a953a7597df40f37d237c9c32888f51bad986",
          "sha1": "601b369184d0d883aa8aa6dfd1fa07b5a671ab5c",
          "md5": "63e127a5543dff1eddfa32355878a7ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hrs-android",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-hrs-android-0.8.8.aar",
          "url": "ble-service-peripheral-hrs-android-0.8.8.aar",
          "size": 6619,
          "sha512": "8642c6261fcd1b30f31922c82c9679575da42c0c5e2d3409e0a2192f635b45a5a68184d5c6e172ec392b22529624b30cb15a596475469200234fb77c916e9985",
          "sha256": "0eab6d18bbdb749b98a3c2444c9a953a7597df40f37d237c9c32888f51bad986",
          "sha1": "601b369184d0d883aa8aa6dfd1fa07b5a671ab5c",
          "md5": "63e127a5543dff1eddfa32355878a7ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-peripheral-hrs-android-0.8.8-sources.jar",
          "url": "ble-service-peripheral-hrs-android-0.8.8-sources.jar",
          "size": 4219,
          "sha512": "0fab324e66c257f59420c9c3d7d8b8d7c149ba0bafa8b158683d002935f54229f4a5a28d782f8a9344545bfc6289db78dfdbc2cf046091dc9052aa1b91594e6a",
          "sha256": "fdd8c7bd4c68d35ca1ad9f5095bd9813fcbf7b8a0d3d0f7ae36bed640dfcd18a",
          "sha1": "e543539a0c8abacf2999ebb98f03dd624c2030b1",
          "md5": "e72e5b30bf42ee7073e310db16cf963e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-peripheral-hrs-android-0.8.8-javadoc.jar",
          "url": "ble-service-peripheral-hrs-android-0.8.8-javadoc.jar",
          "size": 283016,
          "sha512": "f4f3442c5ba1f184163f617c94036ba04ae1ad740ef61c1022d12d5ad621d5606be095352c6169326a07cd64182caf8e1e4ce74393f73fe3688aeb38bc3fdbf7",
          "sha256": "fb92c5abf68b7e8e8901fc07dbee98664050750f5e7ece3d3a2716c549ebc48a",
          "sha1": "f6e71b3ac2f497ec003f4d87e699db4ddd53fdad",
          "md5": "758b07b74aaf276871431fe6cddc7073"
        }
      ]
    }
  ]
}
