{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a92-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.2.1.aar",
          "url": "ble-characteristic-u2a92-android-0.2.1.aar",
          "size": 2911,
          "sha512": "89f4774ee54c9f1a030bf81865617c63fc0a8af442b5d4a5e167ba32ec032b2acc8cc61f6b100eb01ec050afdfab0f83d0d49a551a021e75007004efa3f7dd0d",
          "sha256": "240850eb4f83d687928d305390e79ab4e74f7dfd195c6be9266165984687141c",
          "sha1": "af974da2251598b7433e265b428ecdcce04b9b88",
          "md5": "f8d921bd68a79e94a9d59db89744b94d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.2.1.aar",
          "url": "ble-characteristic-u2a92-android-0.2.1.aar",
          "size": 2911,
          "sha512": "89f4774ee54c9f1a030bf81865617c63fc0a8af442b5d4a5e167ba32ec032b2acc8cc61f6b100eb01ec050afdfab0f83d0d49a551a021e75007004efa3f7dd0d",
          "sha256": "240850eb4f83d687928d305390e79ab4e74f7dfd195c6be9266165984687141c",
          "sha1": "af974da2251598b7433e265b428ecdcce04b9b88",
          "md5": "f8d921bd68a79e94a9d59db89744b94d"
        }
      ]
    }
  ]
}
