{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1c-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1c",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-android-0.8.13.aar",
          "url": "ble-characteristic-u2b1c-android-0.8.13.aar",
          "size": 3147,
          "sha512": "0c9cfd5f6e888bfa65eaefd50711e703c8ca72da60f201d1d7030ac26e9a9fbe79c0066cd3dc0e9bccd256832114b014e5ac3a355616105a660fe4ad562d3823",
          "sha256": "5fa5700e367cd0faa42ca29b158fb2860d225b6739e5a493bb122f874cb26cad",
          "sha1": "a981b0e9355d18428d19d8bf5cab85125179dbd7",
          "md5": "1a468c1b72ea4634e191200ee3080436"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1c",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-android-0.8.13.aar",
          "url": "ble-characteristic-u2b1c-android-0.8.13.aar",
          "size": 3147,
          "sha512": "0c9cfd5f6e888bfa65eaefd50711e703c8ca72da60f201d1d7030ac26e9a9fbe79c0066cd3dc0e9bccd256832114b014e5ac3a355616105a660fe4ad562d3823",
          "sha256": "5fa5700e367cd0faa42ca29b158fb2860d225b6739e5a493bb122f874cb26cad",
          "sha1": "a981b0e9355d18428d19d8bf5cab85125179dbd7",
          "md5": "1a468c1b72ea4634e191200ee3080436"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1c-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2b1c-android-0.8.13-sources.jar",
          "size": 2213,
          "sha512": "2fffeeaa2fe719144d4f3e1bb688b83ef2f394992dd2f1f70da810b59904ee10869c96e32057c4adfd6994e1771b914896dcf757c413756a8cb2fec200353ecc",
          "sha256": "a7f3252c973844de8cc88d054120bae702e68c47657ed2d8ebd50dc3f26a0715",
          "sha1": "120c943110233332fb3970aebd793e96c85e875e",
          "md5": "98a9ca70cf44571d2e9224d4d186467a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1c-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2b1c-android-0.8.13-javadoc.jar",
          "size": 271177,
          "sha512": "53d071162692b3d12c6cb768c6b61702c2aad43364c8973e6c3d580afd7be0911813402a8895fc0ff7e969488fbe25bd49da018ad5b79c6dfd86dc89005e9c60",
          "sha256": "08087a74ede6aedcd63a385031c03790b1812173b1ae8b94d49602e3f0a22066",
          "sha1": "968fc157a6baa8d557a70f4646bf0e1592e6dcb4",
          "md5": "605b6a9cd07924e6e33e696cb4e07b14"
        }
      ]
    }
  ]
}
