{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc5",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc5-0.8.5.jar",
          "url": "ble-characteristic-u2bc5-0.8.5.jar",
          "size": 1438,
          "sha512": "473a861ce8c9871ba7e040ea4960fc0ec4920411488e50e2b0c0a51192b516207f1c3dbc6af627aa43ab0ed268215368ce734bfca65271d4f6bb50c507e47994",
          "sha256": "81e217336bf79aa0c6f6ef4eebf8642fb71d4eb75e2c0723ff2e3e9941b57c18",
          "sha1": "71f93139421690b181ae703b18f2bfcb7452c217",
          "md5": "c0b27698e5f248627a42ed0131708f34"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc5-0.8.5.jar",
          "url": "ble-characteristic-u2bc5-0.8.5.jar",
          "size": 1438,
          "sha512": "473a861ce8c9871ba7e040ea4960fc0ec4920411488e50e2b0c0a51192b516207f1c3dbc6af627aa43ab0ed268215368ce734bfca65271d4f6bb50c507e47994",
          "sha256": "81e217336bf79aa0c6f6ef4eebf8642fb71d4eb75e2c0723ff2e3e9941b57c18",
          "sha1": "71f93139421690b181ae703b18f2bfcb7452c217",
          "md5": "c0b27698e5f248627a42ed0131708f34"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc5-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2bc5-0.8.5-javadoc.jar",
          "size": 107109,
          "sha512": "30df84a99030a8bca4a605a2ea69bcc080e3481ebe7607016a11fd1957ee454aa003ce9c90fea26f39427e50ab88fe05b9934341b1be37c4c5367452aed93bf1",
          "sha256": "c224682f8bd4eeb93aca429ae6480b4ea194842230e9519f649e8adba71044f3",
          "sha1": "560f0ae4aa0ca41735b8f31cc1048785ef470ba8",
          "md5": "f565ee6c73afa4fdd08fddd20f625baf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc5-0.8.5-sources.jar",
          "url": "ble-characteristic-u2bc5-0.8.5-sources.jar",
          "size": 1418,
          "sha512": "1ba0d4aaea8686ba2c486b1fcd9c1b313f9f657510e9cd16e6991dda328d22f576e28bef5015ee8b1f31e24c15a5b66b0f9e452daeb6ef4342af34daab85467f",
          "sha256": "ca3f4c734f7a69ef997f691207e9abdd943597b6987024bdccafe59cfa10b743",
          "sha1": "3b5b57814a38b2cf099e734f9816ad7cfa13d817",
          "md5": "94ae5e91a96279d4b23195a902ff3dab"
        }
      ]
    }
  ]
}
