{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2902-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.4.0.aar",
          "url": "ble-descriptor-u2902-android-0.4.0.aar",
          "size": 3104,
          "sha512": "8d324ca6b14d70d19024dabbe2075229e13830f99877afbe04abad97cb9683df4ad152b06d0d20daebc0d4c90aefa8b05d817927febdc645bbdc8f58d3926f67",
          "sha256": "44ad0cc6b890dde5e425aaf7aa0450d54e18002db32cc4cd20796251ac0b21d2",
          "sha1": "b1086ebebd88e1cf01b816140b9423e92ecfa6f9",
          "md5": "cd0d91f4db3fce3b82eed3d9d9c2e484"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2902-android-0.4.0.aar",
          "url": "ble-descriptor-u2902-android-0.4.0.aar",
          "size": 3104,
          "sha512": "8d324ca6b14d70d19024dabbe2075229e13830f99877afbe04abad97cb9683df4ad152b06d0d20daebc0d4c90aefa8b05d817927febdc645bbdc8f58d3926f67",
          "sha256": "44ad0cc6b890dde5e425aaf7aa0450d54e18002db32cc4cd20796251ac0b21d2",
          "sha1": "b1086ebebd88e1cf01b816140b9423e92ecfa6f9",
          "md5": "cd0d91f4db3fce3b82eed3d9d9c2e484"
        }
      ]
    }
  ]
}
