{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af9",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af9-0.8.5.jar",
          "url": "ble-characteristic-u2af9-0.8.5.jar",
          "size": 1765,
          "sha512": "5fca101a083a4bd44fcc848b8b833ab4dac679f5b90fdab1b90dc843ddb8deb23ed0de8e5a1ad88f0677abbc41e5670b6d2c7dbcd96d31803940247d12313be5",
          "sha256": "92096cbaacf783e2bb688d13467e60c8bb2c3f004b07ccf3591f4ce88fc02f34",
          "sha1": "8223f05d11dd00cdf47282c522c59df29b86bb7c",
          "md5": "95e52a5f71c3409ab132921fdeeceade"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af9-0.8.5.jar",
          "url": "ble-characteristic-u2af9-0.8.5.jar",
          "size": 1765,
          "sha512": "5fca101a083a4bd44fcc848b8b833ab4dac679f5b90fdab1b90dc843ddb8deb23ed0de8e5a1ad88f0677abbc41e5670b6d2c7dbcd96d31803940247d12313be5",
          "sha256": "92096cbaacf783e2bb688d13467e60c8bb2c3f004b07ccf3591f4ce88fc02f34",
          "sha1": "8223f05d11dd00cdf47282c522c59df29b86bb7c",
          "md5": "95e52a5f71c3409ab132921fdeeceade"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af9-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2af9-0.8.5-javadoc.jar",
          "size": 107308,
          "sha512": "443b39f67c68ed8ff129f753a72c5fc53658b0aec2470bd9e815c6184f381923a3bc0572a2c5e441dd75f500bb5626e2e7ea7f938175bfd23c1372b270fe5aef",
          "sha256": "b4f59eb80c9ffd53c9f50db038767b4e1b089dd36e9ea59f82ded4e4ff70c162",
          "sha1": "44db36bc2ba29ce5155e509b5ceb373baa996d74",
          "md5": "80dd3fc03d81e626f3c2e838b5698610"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af9-0.8.5-sources.jar",
          "url": "ble-characteristic-u2af9-0.8.5-sources.jar",
          "size": 1610,
          "sha512": "13af4200ac29499710d8167ed34dff4d83efe5b5c2547dfc0f4030d14b6a09172eb2c2323d400e8af1c68a2507c96fa14e2895dcc3b82fefa1e1e28b78d26699",
          "sha256": "6ec594ed948dbb0a6fdfa6eaa2443308ac1d2e74a5ffc5667f1d7183d64ce2ff",
          "sha1": "7a5a052d1586de8e9d101aee4f63cb116299e174",
          "md5": "dcd6a3b485e004f63d8068540fff808a"
        }
      ]
    }
  ]
}
