{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b78",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.10.jar",
          "url": "ble-characteristic-u2b78-0.8.10.jar",
          "size": 1471,
          "sha512": "f995340165c2608bbb48fa36033d716ec75891c00bf88d7c9b516dc37e5fdf43e8f97872fa3b51bc713cf8d24a7ab8fe947821b7e01cc59e5a4e5fb4180540b9",
          "sha256": "279562c5a88cd20fe26a535fb38881be70543b5e0130d816df8199e49d900473",
          "sha1": "3ec669e4bd341d707906a7c9d979242580352f05",
          "md5": "98efdb314ca2766cc5e1725fd337ed0a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.10.jar",
          "url": "ble-characteristic-u2b78-0.8.10.jar",
          "size": 1471,
          "sha512": "f995340165c2608bbb48fa36033d716ec75891c00bf88d7c9b516dc37e5fdf43e8f97872fa3b51bc713cf8d24a7ab8fe947821b7e01cc59e5a4e5fb4180540b9",
          "sha256": "279562c5a88cd20fe26a535fb38881be70543b5e0130d816df8199e49d900473",
          "sha1": "3ec669e4bd341d707906a7c9d979242580352f05",
          "md5": "98efdb314ca2766cc5e1725fd337ed0a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2b78-0.8.10-javadoc.jar",
          "size": 107203,
          "sha512": "1ec9ab512e59b8ea1171e7075a477f07918e5de15f9a1364fc6e9ebe39da4ee9316a2ec3da0600d72d699805a1f0857f0f1d434d151f8744cac1cffd01bb2067",
          "sha256": "01a6d7ab870fc32a228e7ca12654b894dc9873e6182b09706d27ded30a584a70",
          "sha1": "e4202265c9be040e0ec4865a61db2e8a62f72821",
          "md5": "4f7cd115639f372f027f7df1ebe0cc80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b78-0.8.10-sources.jar",
          "url": "ble-characteristic-u2b78-0.8.10-sources.jar",
          "size": 1478,
          "sha512": "c14fb8595a6a959bedf9661129497020fcf7eebb57665ac4ba6c2fef8a950500ecb8d6a9523479ba1475486d416aed8282a2bfd99fb086aeeedbeff7634d1e0f",
          "sha256": "e5034a6679a3c605c3403bd1c2bca124d22b59426ff86a7c20590cd35cb51d06",
          "sha1": "2f04d5aae6fd84aadc430d433d12305fb3c04f4b",
          "md5": "b6c1b5cf953e2719eb13b198605f4a26"
        }
      ]
    }
  ]
}
