{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-pasp-peripheral-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "x6nyasohnvdrtpp4affpidlfoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pasp-peripheral-android-0.1.1.aar",
          "url": "ble-profile-pasp-peripheral-android-0.1.1.aar",
          "size": 3571,
          "sha512": "d854e1deee03a6d14ae84d7de11b14f8ec5fc7aec68f94c8309ff5788d35a0d90227552f01f6f464f70f7439161722e551ad23e02822caab841e7cde56b6c616",
          "sha256": "818456124511f56bb36fad0f88ec8d6b665770d8618cfb18d5f5634d1b332a33",
          "sha1": "11f7e0c243bb5ef918d355fd6a251fd23e1bd106",
          "md5": "ff4bf575806d718ed5c5385e050784cd"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-peripheral-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-pasp-peripheral-android-0.1.1.aar",
          "url": "ble-profile-pasp-peripheral-android-0.1.1.aar",
          "size": 3571,
          "sha512": "d854e1deee03a6d14ae84d7de11b14f8ec5fc7aec68f94c8309ff5788d35a0d90227552f01f6f464f70f7439161722e551ad23e02822caab841e7cde56b6c616",
          "sha256": "818456124511f56bb36fad0f88ec8d6b665770d8618cfb18d5f5634d1b332a33",
          "sha1": "11f7e0c243bb5ef918d355fd6a251fd23e1bd106",
          "md5": "ff4bf575806d718ed5c5385e050784cd"
        }
      ]
    }
  ]
}
