{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-cpp-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-cpp-android-0.1.2.aar",
          "url": "ble-profile-cpp-android-0.1.2.aar",
          "size": 1201,
          "sha512": "52808e5d277f151575532b823a7e6d2499313549b2f34b593e5c39b06bf424e849801bb023d7823fe8c3b3e0c82035d4fbdb5a5b57cec252ac6ee5ba9aa3e0d3",
          "sha256": "b298e77c6a4725b6825bd3f7eda6a252ebe950d90ac70d3743039f0e518896f1",
          "sha1": "63477f1e2a1e952bff210703aaec1d7520fd7317",
          "md5": "c9970a100f0457f197cffdec0fc5e11a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-cpp-android-0.1.2.aar",
          "url": "ble-profile-cpp-android-0.1.2.aar",
          "size": 1201,
          "sha512": "52808e5d277f151575532b823a7e6d2499313549b2f34b593e5c39b06bf424e849801bb023d7823fe8c3b3e0c82035d4fbdb5a5b57cec252ac6ee5ba9aa3e0d3",
          "sha256": "b298e77c6a4725b6825bd3f7eda6a252ebe950d90ac70d3743039f0e518896f1",
          "sha1": "63477f1e2a1e952bff210703aaec1d7520fd7317",
          "md5": "c9970a100f0457f197cffdec0fc5e11a"
        }
      ]
    }
  ]
}
