{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4e",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.10.jar",
          "url": "ble-characteristic-u2b4e-0.8.10.jar",
          "size": 3373,
          "sha512": "4d5c9b7e8f60b69e9b9b024c121b6d5942c3c7ad8f79625b093f4d506929a2d0edac4c0dd7f5f284d46afdf77431b7b6c7b50137c31b83d12166e411021f1726",
          "sha256": "b749afb56b6cdc7dc235e7aa493a749d8ab2f71249246eb580d7b09603b9ecb6",
          "sha1": "795b74d3b3627223a93d4ba4ab5b21f662f8fd71",
          "md5": "4644216fc8c2f19e94ce7ccb39eec3c1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.10.jar",
          "url": "ble-characteristic-u2b4e-0.8.10.jar",
          "size": 3373,
          "sha512": "4d5c9b7e8f60b69e9b9b024c121b6d5942c3c7ad8f79625b093f4d506929a2d0edac4c0dd7f5f284d46afdf77431b7b6c7b50137c31b83d12166e411021f1726",
          "sha256": "b749afb56b6cdc7dc235e7aa493a749d8ab2f71249246eb580d7b09603b9ecb6",
          "sha1": "795b74d3b3627223a93d4ba4ab5b21f662f8fd71",
          "md5": "4644216fc8c2f19e94ce7ccb39eec3c1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2b4e-0.8.10-javadoc.jar",
          "size": 112877,
          "sha512": "7512593eadcdaacba58909c557d238b02976a7b6ebb02b3ee69909405843c417b3d8a95598965654f999ff690f743b53fdd462ad927ad3f7f83e4a59c8249c08",
          "sha256": "a926a4d8afd0a5d81d331ce3951192ef92bf62ac990e5667597a15808bae3666",
          "sha1": "c2754cda2326a2f07ab74ebf26eb831b04bbbbfc",
          "md5": "e4a0056243360c942c73c02b4cfd9300"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.10-sources.jar",
          "url": "ble-characteristic-u2b4e-0.8.10-sources.jar",
          "size": 3094,
          "sha512": "a24a68a45d80f54285137b70729c9f1e92c47c109e6b648d707bf916ec7d16ea6489c34f59d72f74188c3042918a68a794b0d3ef909769add807bbeb812862f3",
          "sha256": "117ae564a0889e586606db4195c76eeb97f9d61e2ff53216f6d92802bd2fbca2",
          "sha1": "7b2cc9eb5ad8bae6f848cf5c3650955de3bfa4be",
          "md5": "300046ee884878c43da5de7603f30175"
        }
      ]
    }
  ]
}
