{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7f-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.8.10.aar",
          "url": "ble-characteristic-u2a7f-android-0.8.10.aar",
          "size": 3205,
          "sha512": "ee66a2500a0e43357916a8eaebd9c070513c2e957c61d80e1bcdaffaac81bf2bbf499d6ef69f9dba45d61f458f5b8fd5694e455a9c49cbeef748c2c9a0e928ba",
          "sha256": "4e50050ebb414179601ead142cccbd61755b80c8abde19e79954327d10fb657a",
          "sha1": "3ec3a49054eaadb492796822bf8e9ee94bc66869",
          "md5": "116d772c14ad92b80058b0ec600d6922"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.8.10.aar",
          "url": "ble-characteristic-u2a7f-android-0.8.10.aar",
          "size": 3205,
          "sha512": "ee66a2500a0e43357916a8eaebd9c070513c2e957c61d80e1bcdaffaac81bf2bbf499d6ef69f9dba45d61f458f5b8fd5694e455a9c49cbeef748c2c9a0e928ba",
          "sha256": "4e50050ebb414179601ead142cccbd61755b80c8abde19e79954327d10fb657a",
          "sha1": "3ec3a49054eaadb492796822bf8e9ee94bc66869",
          "md5": "116d772c14ad92b80058b0ec600d6922"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2a7f-android-0.8.10-sources.jar",
          "size": 2176,
          "sha512": "07b1f7d9267e5cc43c1b75dd0de5467f44ba74b9556dad11c1a6bfbefcfc5a916a5d0746f6ec497d3570a5b8d887636b390cf1625cba0c63e2146da0010023e4",
          "sha256": "9e7307a0edb89cb3f5e610c2f676ea0650e0e417a3193d0efd731870ccdacc45",
          "sha1": "9da85dbcf1f946264a2a57798ec102b77f14192e",
          "md5": "7fe63e2b9993f6f7c6de1dc24efb548c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2a7f-android-0.8.10-javadoc.jar",
          "size": 270613,
          "sha512": "3bc01211ab8b1e701a1cc3de96b8d3e1a6848b37a96eb3ea65ebf5d2622a56c32567b85b8b3aa6fe216c06b2430883d9cb789f3f7d3b8c49b9ac09f4c7925ecd",
          "sha256": "1ab6ef9ca9c9b768ea05112d2235086f24548caa360bfa2669d9a8d8a6efbf1c",
          "sha1": "aa703bbc75e1dec2432e4de5c44dc441b1772871",
          "md5": "c89b5ad6b8064d3baf6b345c4a338454"
        }
      ]
    }
  ]
}
