{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-anp-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-central-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-anp-central-android-0.1.4.aar",
          "url": "ble-profile-anp-central-android-0.1.4.aar",
          "size": 4799,
          "sha512": "e11f9460446827914dc4a98616da8d2481897f86f1acfa73a0b8c46c4854a3b557a9777a4faf23eaf584bdcbe3e2782b445f42c973146a3db8832b5fdae9d03a",
          "sha256": "6777141301b48f55136aaa043d4cfa8ee8a4d12bb2ace97b5c40123f59506037",
          "sha1": "8a99a1fb49ea429ada7533c6f27b0be62ecf3fe5",
          "md5": "98d48c95d5f80f59bcf33b0fd5d8b981"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-central-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-anp-central-android-0.1.4.aar",
          "url": "ble-profile-anp-central-android-0.1.4.aar",
          "size": 4799,
          "sha512": "e11f9460446827914dc4a98616da8d2481897f86f1acfa73a0b8c46c4854a3b557a9777a4faf23eaf584bdcbe3e2782b445f42c973146a3db8832b5fdae9d03a",
          "sha256": "6777141301b48f55136aaa043d4cfa8ee8a4d12bb2ace97b5c40123f59506037",
          "sha1": "8a99a1fb49ea429ada7533c6f27b0be62ecf3fe5",
          "md5": "98d48c95d5f80f59bcf33b0fd5d8b981"
        }
      ]
    }
  ]
}
