{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a71-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-android-0.2.4.aar",
          "url": "ble-characteristic-u2a71-android-0.2.4.aar",
          "size": 3099,
          "sha512": "4804d875bf32774caeee7456dbb3a18e1219bc86527f56a3aa0749bea2a789c2120667e6ff670db9ac3a716fbb6a0b0e167d3f346ff1c0f7287f15d3235ea9e1",
          "sha256": "5a85046a6125c0f1707d05ac6e0cea2e00c7653888c36eb4350b96539859c150",
          "sha1": "46e4cb946ebb38497184e4da200b18fdbf25b93b",
          "md5": "035bcccf8c9893cb3cc3652189a825d0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a71",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a71-android-0.2.4.aar",
          "url": "ble-characteristic-u2a71-android-0.2.4.aar",
          "size": 3099,
          "sha512": "4804d875bf32774caeee7456dbb3a18e1219bc86527f56a3aa0749bea2a789c2120667e6ff670db9ac3a716fbb6a0b0e167d3f346ff1c0f7287f15d3235ea9e1",
          "sha256": "5a85046a6125c0f1707d05ac6e0cea2e00c7653888c36eb4350b96539859c150",
          "sha1": "46e4cb946ebb38497184e4da200b18fdbf25b93b",
          "md5": "035bcccf8c9893cb3cc3652189a825d0"
        }
      ]
    }
  ]
}
