{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac4-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac4-android-0.8.6.aar",
          "url": "ble-characteristic-u2ac4-android-0.8.6.aar",
          "size": 3236,
          "sha512": "31ea0b52bbd66681f9affd43717d24e846fcd9555fcdc9138cb2db444d4a5ee6f1107c85d838ece61d0a009894c5e22dfe1d69e42c67e3d6853f6f0c7bebcbc9",
          "sha256": "15aaf39c9906313260b6972ed7f9b630b5903162fa0eeb03e936df1e0a0a1f84",
          "sha1": "54c42d94b1c6beded2c0b2219ae1cebc8a8091f6",
          "md5": "0bd90ce82c5dcef736442a970ff2223e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac4",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac4-android-0.8.6.aar",
          "url": "ble-characteristic-u2ac4-android-0.8.6.aar",
          "size": 3236,
          "sha512": "31ea0b52bbd66681f9affd43717d24e846fcd9555fcdc9138cb2db444d4a5ee6f1107c85d838ece61d0a009894c5e22dfe1d69e42c67e3d6853f6f0c7bebcbc9",
          "sha256": "15aaf39c9906313260b6972ed7f9b630b5903162fa0eeb03e936df1e0a0a1f84",
          "sha1": "54c42d94b1c6beded2c0b2219ae1cebc8a8091f6",
          "md5": "0bd90ce82c5dcef736442a970ff2223e"
        }
      ]
    }
  ]
}
