{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a94-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a94",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a94-android-0.4.3.aar",
          "url": "ble-characteristic-u2a94-android-0.4.3.aar",
          "size": 3204,
          "sha512": "e10320125feabe161be8930d2ee8a77940d85fa29c99e4d8b8e53c425eead3f8ae1c96f672014cdbb52feb60743276fc04a7496b5e4f21f317dd1586908c5772",
          "sha256": "b7b8c771a987c1a395f374af91eb9de511444a74c66d60850b13f765c308257f",
          "sha1": "a6ef55e57f92f83f89fd6551b5325e9cf58537b4",
          "md5": "d9c42935e51f3905e41f87fec2669eb6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a94",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a94-android-0.4.3.aar",
          "url": "ble-characteristic-u2a94-android-0.4.3.aar",
          "size": 3204,
          "sha512": "e10320125feabe161be8930d2ee8a77940d85fa29c99e4d8b8e53c425eead3f8ae1c96f672014cdbb52feb60743276fc04a7496b5e4f21f317dd1586908c5772",
          "sha256": "b7b8c771a987c1a395f374af91eb9de511444a74c66d60850b13f765c308257f",
          "sha1": "a6ef55e57f92f83f89fd6551b5325e9cf58537b4",
          "md5": "d9c42935e51f3905e41f87fec2669eb6"
        }
      ]
    }
  ]
}
