{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bad",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.14.jar",
          "url": "ble-characteristic-u2bad-0.8.14.jar",
          "size": 1488,
          "sha512": "efa98d356785619904c14c2c0904062505cca8a4e2c183828c3d49002a8430a22480818d444ec5469ee4d2bb48ce430167e60f2d1f9ce834a0d9bc331911e0c5",
          "sha256": "56c6bf99492c679b8141a3cb7895acff347a80a1fcf13633c2d6f9bcf8e6b767",
          "sha1": "9b5801fde6e1fc1e082258df141b74d4b4741cd4",
          "md5": "3a7de8780f1dfea0d7c00f33fa80ade2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.14.jar",
          "url": "ble-characteristic-u2bad-0.8.14.jar",
          "size": 1488,
          "sha512": "efa98d356785619904c14c2c0904062505cca8a4e2c183828c3d49002a8430a22480818d444ec5469ee4d2bb48ce430167e60f2d1f9ce834a0d9bc331911e0c5",
          "sha256": "56c6bf99492c679b8141a3cb7895acff347a80a1fcf13633c2d6f9bcf8e6b767",
          "sha1": "9b5801fde6e1fc1e082258df141b74d4b4741cd4",
          "md5": "3a7de8780f1dfea0d7c00f33fa80ade2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2bad-0.8.14-javadoc.jar",
          "size": 86076,
          "sha512": "b9eb0541bcee95d64e2514e53f22a9f463101b681f898ed1c53386390d99768b730b37489affe42df2825a5aa455bfb10b3d6f9aac688b23e2b3c6acb0eb65c8",
          "sha256": "61408a05e14a5c9650715e233bdd17b1151dfa72ffe9ac8c325438b44f350861",
          "sha1": "b00b0105d8751baf12acbb5df6ffa77838b3b175",
          "md5": "d04b62dc1d68d9bd681a3fcea064a194"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.14-sources.jar",
          "url": "ble-characteristic-u2bad-0.8.14-sources.jar",
          "size": 1474,
          "sha512": "1bbc2901bf97319fd121ca2ea42f87a98027a08b4b7d102298f26957af1f1093b1a429f8ed3cfb63b6c04334bd3a94c3f725bcadb32a8d5f78c810c58bce5931",
          "sha256": "ee2b12b5b6f20d47fe55c7b5620296842204ae1c83ab9026404f272f1929d527",
          "sha1": "81b21921797be882eac058a5d289cd0d7d031af1",
          "md5": "ad2b96117f095d0f1a958457623c5a6f"
        }
      ]
    }
  ]
}
