{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-rtus-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a16-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-android-0.8.6.aar",
          "url": "ble-service-rtus-android-0.8.6.aar",
          "size": 1226,
          "sha512": "74ce6d3a1f8975cca8abeae82ff8dfbe3110ef38fee85ea7e3a87e450aad682c1079a2a2edc5213f3f9cc212773ee7567820c7d2f78186f63a648caf07b51ac4",
          "sha256": "0cdd04457895c9e1ae52dd267880da1e4e5e0b462415cc069e4e148a179d1e3a",
          "sha1": "861b6c21e473cecca9b4d163bf8cd62ca0b27d72",
          "md5": "e634aa44a71828b7844d9b020ae050a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a16-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-android-0.8.6.aar",
          "url": "ble-service-rtus-android-0.8.6.aar",
          "size": 1226,
          "sha512": "74ce6d3a1f8975cca8abeae82ff8dfbe3110ef38fee85ea7e3a87e450aad682c1079a2a2edc5213f3f9cc212773ee7567820c7d2f78186f63a648caf07b51ac4",
          "sha256": "0cdd04457895c9e1ae52dd267880da1e4e5e0b462415cc069e4e148a179d1e3a",
          "sha1": "861b6c21e473cecca9b4d163bf8cd62ca0b27d72",
          "md5": "e634aa44a71828b7844d9b020ae050a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-rtus-android-0.8.6-sources.jar",
          "url": "ble-service-rtus-android-0.8.6-sources.jar",
          "size": 1198,
          "sha512": "5adb9c116c5d46237269b8ebd20deec1f976f409c954ab63bd8bf18ed1a9c7b50739d639429eed2d7bd0fa18453278f4eed8776888e596daab4fcc610e24bd02",
          "sha256": "ed4e5e34e992a7b930c1b38363ce22efea006cb7a3f8c82cb1d22b7adf1432f6",
          "sha1": "7b3d71f50434569f3075d8716b9969bc95006300",
          "md5": "0b2d6708e8fdf50538bab2af3c6d66d7"
        }
      ]
    }
  ]
}
