{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core-constants-sdo",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.13.jar",
          "url": "ble-core-constants-sdo-0.8.13.jar",
          "size": 2682,
          "sha512": "4da673d03c29463fa67876ed976c62b2b99daab91ca46b3bb58ff5a9d1da28a305a7dbe1e76cf63567704667303b01749cad239ae1dad8e0c9106d5a56071758",
          "sha256": "f4490ad7822df14aa399d2a221bddbe3ea7ac2bd9d5aa74121c0359fd8565b9a",
          "sha1": "c661673a7df31e426f58fe877f5d68411120439a",
          "md5": "cc3fa246fc6c949e8514d4dde4b8d241"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.13.jar",
          "url": "ble-core-constants-sdo-0.8.13.jar",
          "size": 2682,
          "sha512": "4da673d03c29463fa67876ed976c62b2b99daab91ca46b3bb58ff5a9d1da28a305a7dbe1e76cf63567704667303b01749cad239ae1dad8e0c9106d5a56071758",
          "sha256": "f4490ad7822df14aa399d2a221bddbe3ea7ac2bd9d5aa74121c0359fd8565b9a",
          "sha1": "c661673a7df31e426f58fe877f5d68411120439a",
          "md5": "cc3fa246fc6c949e8514d4dde4b8d241"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.13-javadoc.jar",
          "url": "ble-core-constants-sdo-0.8.13-javadoc.jar",
          "size": 85192,
          "sha512": "303ddd8540112d2d584cafe2268eef2a3460af1d9b482af2735eb418c7809d939bede7ebf68afe578414f365fa327d4410769e39ee427235895411db2b8b3434",
          "sha256": "b172b5b78fe033e5fd59ef78ea84f715a07653a54b3acadd86855371b51011d7",
          "sha1": "a28da917cc7833d7b178e612d604ebdcc29625df",
          "md5": "c42f281b73c3f457f03f8c6ca5b4b66d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-constants-sdo-0.8.13-sources.jar",
          "url": "ble-core-constants-sdo-0.8.13-sources.jar",
          "size": 1520,
          "sha512": "c7907d7dc1c30f35dc8b4a5e020b85cb92b91c6db90d3563a4a024d4955363d2befb521894091c58e0ac4884d0135d11eea9dc31ef53727d17f10222b7cc398f",
          "sha256": "d4a91143f0dfa5999fea0fa90490539558768e47c92873c17a4404e6a5e64759",
          "sha1": "6c392ea7e2b87f46fd4771e3d0efb6895dc34fd7",
          "md5": "df883333761e5fb7a16a3f9306916cb8"
        }
      ]
    }
  ]
}
