{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ace-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ace",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ace-android-0.2.1.aar",
          "url": "ble-characteristic-u2ace-android-0.2.1.aar",
          "size": 5297,
          "sha512": "13b8cea6643003d4576473ef5ee5393b8581577768fed6a1c7c764d0aa410af870386457c16c984f05d206ddbf8d79c5aac16d423d882dc89f17f8de7902b50e",
          "sha256": "eff878c691e2776388e1f27e91c618e60bd3f3e1efb0c2d152968bb790cce70e",
          "sha1": "55f033d4a60fa9b729af989a153583a373d24a8b",
          "md5": "ad8e131fe7000cf737a28e12b2e1fb5b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ace",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ace-android-0.2.1.aar",
          "url": "ble-characteristic-u2ace-android-0.2.1.aar",
          "size": 5297,
          "sha512": "13b8cea6643003d4576473ef5ee5393b8581577768fed6a1c7c764d0aa410af870386457c16c984f05d206ddbf8d79c5aac16d423d882dc89f17f8de7902b50e",
          "sha256": "eff878c691e2776388e1f27e91c618e60bd3f3e1efb0c2d152968bb790cce70e",
          "sha1": "55f033d4a60fa9b729af989a153583a373d24a8b",
          "md5": "ad8e131fe7000cf737a28e12b2e1fb5b"
        }
      ]
    }
  ]
}
