{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290c-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290c",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-android-0.2.4.aar",
          "url": "ble-descriptor-u290c-android-0.2.4.aar",
          "size": 3232,
          "sha512": "5dae66bc253a761f168baf18d062637b188e31af9d6c6d67d30f816df1238cc79835b50ea7fa356dc51a4269b234c91eb65e8b3d81b1b03ed93a2aa9e14de98e",
          "sha256": "7b941c5f8bc67bd784d54062fb2ef5cff0d24c0ccb12501ca31db128575e11b8",
          "sha1": "4201082c49f12b6998bce5ec0709aa25ab538440",
          "md5": "958b609b496516b9d1fb3ca1a5e0ef2c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290c",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290c-android-0.2.4.aar",
          "url": "ble-descriptor-u290c-android-0.2.4.aar",
          "size": 3232,
          "sha512": "5dae66bc253a761f168baf18d062637b188e31af9d6c6d67d30f816df1238cc79835b50ea7fa356dc51a4269b234c91eb65e8b3d81b1b03ed93a2aa9e14de98e",
          "sha256": "7b941c5f8bc67bd784d54062fb2ef5cff0d24c0ccb12501ca31db128575e11b8",
          "sha1": "4201082c49f12b6998bce5ec0709aa25ab538440",
          "md5": "958b609b496516b9d1fb3ca1a5e0ef2c"
        }
      ]
    }
  ]
}
