{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ans-android",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48-android",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-android-0.8.0.aar",
          "url": "ble-service-ans-android-0.8.0.aar",
          "size": 1652,
          "sha512": "0f90c6015fa992f7429e6689efed0263fe078938d96f1c26dd3ef5100a748a8ca6153786d1fece391c090872313e26b4e5a96c0d6a80eb4e67414c56fad0261c",
          "sha256": "58f0a2eea13535ce455df9611c3dce95a7d4a12b6f79e00f30eed8dd63268fa8",
          "sha1": "1c9b00ff47ac34f74279e304c7d5da84b691874e",
          "md5": "a4261490387a728e324b6f1f570274e9"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a45-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47-android",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a48-android",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ans-android-0.8.0.aar",
          "url": "ble-service-ans-android-0.8.0.aar",
          "size": 1652,
          "sha512": "0f90c6015fa992f7429e6689efed0263fe078938d96f1c26dd3ef5100a748a8ca6153786d1fece391c090872313e26b4e5a96c0d6a80eb4e67414c56fad0261c",
          "sha256": "58f0a2eea13535ce455df9611c3dce95a7d4a12b6f79e00f30eed8dd63268fa8",
          "sha1": "1c9b00ff47ac34f74279e304c7d5da84b691874e",
          "md5": "a4261490387a728e324b6f1f570274e9"
        }
      ]
    }
  ]
}
