{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a07-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.2.4.aar",
          "url": "ble-characteristic-u2a07-android-0.2.4.aar",
          "size": 3087,
          "sha512": "fdaecc5b59392cd99e7517d74649462320bcfa8d9203cbffb4869c019f0047e3c17b889e28ed9876d9f52e7ef2e5c18212b9dd181c2200d0172a757cbf4b0749",
          "sha256": "3a8cf4e0c98d0db1bd209fe7f7b978b9b81322310762083f9e96caa1242ca0f9",
          "sha1": "16d19967bb3502ca235fa6e49781dc7cf2fc6e49",
          "md5": "c8ac6d80016533416be6e17d7a37c478"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.2.4.aar",
          "url": "ble-characteristic-u2a07-android-0.2.4.aar",
          "size": 3087,
          "sha512": "fdaecc5b59392cd99e7517d74649462320bcfa8d9203cbffb4869c019f0047e3c17b889e28ed9876d9f52e7ef2e5c18212b9dd181c2200d0172a757cbf4b0749",
          "sha256": "3a8cf4e0c98d0db1bd209fe7f7b978b9b81322310762083f9e96caa1242ca0f9",
          "sha1": "16d19967bb3502ca235fa6e49781dc7cf2fc6e49",
          "md5": "c8ac6d80016533416be6e17d7a37c478"
        }
      ]
    }
  ]
}
