{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2baf",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.10.jar",
          "url": "ble-characteristic-u2baf-0.8.10.jar",
          "size": 1558,
          "sha512": "d3d0003e832109e6c259256cd446da325ddc01a27f0e9f5f03767fac9212425b8fc059928508a8950df5abb653ddc82514ca6186b6877c12680e8cba6bd84095",
          "sha256": "0bfae5ed7bdca2567ef1dfaf938fb98d8144771e08f4edeb82407d8f639f3b08",
          "sha1": "aa93b2fd6810d256fd9cace8efd0c40fe2dc8cfa",
          "md5": "65ffc9426f79c2531d42b5867591dac5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.10.jar",
          "url": "ble-characteristic-u2baf-0.8.10.jar",
          "size": 1558,
          "sha512": "d3d0003e832109e6c259256cd446da325ddc01a27f0e9f5f03767fac9212425b8fc059928508a8950df5abb653ddc82514ca6186b6877c12680e8cba6bd84095",
          "sha256": "0bfae5ed7bdca2567ef1dfaf938fb98d8144771e08f4edeb82407d8f639f3b08",
          "sha1": "aa93b2fd6810d256fd9cace8efd0c40fe2dc8cfa",
          "md5": "65ffc9426f79c2531d42b5867591dac5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2baf-0.8.10-javadoc.jar",
          "size": 107521,
          "sha512": "084d816646b38be0d7d5634816c6b9b1efbc6239a48739fb4c03c5ea122b79f2e88b625a71a5c336d297167aeb0e64740e3172d43fd8a8a956fe10060a15bf9a",
          "sha256": "1989b2e1100603e3b28467422a7c38fc7ddd0efd4ed396d758596b633a2c7df8",
          "sha1": "0435b926a21e2fcbcd1cd4e0b27825ae96855482",
          "md5": "7345b5492f91d7eb343dbfa0dafbd132"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2baf-0.8.10-sources.jar",
          "url": "ble-characteristic-u2baf-0.8.10-sources.jar",
          "size": 1553,
          "sha512": "0dca7f50fa3cfd5bbe8e16b3f7071584bafff4a9d3cd670463e9e70442e4d9007b252e326a7365d94de0346632737f286338753af350986e05cc22ffcd91ac6b",
          "sha256": "096ceb1beee155869b3370cb585062931ff56ad0e8c1f72ced0f39d7ebc9b295",
          "sha1": "f1781b6fee6302cda0fa695d68a27e04e873a1ec",
          "md5": "c6ba851e2a420005458fbd6c0b984bfe"
        }
      ]
    }
  ]
}
