{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b90",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.7.jar",
          "url": "ble-characteristic-u2b90-0.8.7.jar",
          "size": 1440,
          "sha512": "f7faa4bbf625d707eba3149fd83eefdc4857027b92274e69e96b8566846d88ed387f5b31d310f230a45fcf6e266e43d267db7c39b537fe2b7488db3708008780",
          "sha256": "09957bbf1d66142e433d34cc13f3e923e74c7c126d924e7d327662d0459ab2b4",
          "sha1": "8972b6d412e836ee9312d07f9f0d17263a2d0aa5",
          "md5": "ee6d1ca019d8a056348be73f69c9e01a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.7.jar",
          "url": "ble-characteristic-u2b90-0.8.7.jar",
          "size": 1440,
          "sha512": "f7faa4bbf625d707eba3149fd83eefdc4857027b92274e69e96b8566846d88ed387f5b31d310f230a45fcf6e266e43d267db7c39b537fe2b7488db3708008780",
          "sha256": "09957bbf1d66142e433d34cc13f3e923e74c7c126d924e7d327662d0459ab2b4",
          "sha1": "8972b6d412e836ee9312d07f9f0d17263a2d0aa5",
          "md5": "ee6d1ca019d8a056348be73f69c9e01a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b90-0.8.7-javadoc.jar",
          "size": 107114,
          "sha512": "ef5e75361da0838a9e0dc6ae414619b18cf5d07a45217351621cda7b5c1859dce70742b04d5b986bae792c86b2fad8bba33054338b419704025a49ef55cc341c",
          "sha256": "797ba0b0aca4129a0837057814cfc98f874e6471be1e6dcdb5c2e9fcc21b3c49",
          "sha1": "094c593c96c3219a4b38551ee8a60e5d8eef4ce4",
          "md5": "4df7ef6962cbe5ef16fd47f94780c980"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b90-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b90-0.8.7-sources.jar",
          "size": 1421,
          "sha512": "5a5cf22cd2074851f37773092a72acb4d7f8d982fb46f9fca1722645038f20ff40d6ce2fd0468a10b9756d551592aa01b527b04921c53d33e9629c33515a9cc5",
          "sha256": "3772a0517f2d60429395c088219490a16673c2e90a0244a7ed14a2aa535d171d",
          "sha1": "aca1f7fa336f940bd8df8b9725e48fde90e589cb",
          "md5": "f61018129d1616673b5e5480cfbd856a"
        }
      ]
    }
  ]
}
