{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-htp-peripheral-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "x6diq4e44bdrdjpss4wisc2rsu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-htp-peripheral-android-0.1.4.aar",
          "url": "ble-profile-htp-peripheral-android-0.1.4.aar",
          "size": 5137,
          "sha512": "9e28c377951d363eaaa61b59497ec98231390610a51f8b07cc5064e3f7e0f4f59d705d7b0a529cc03aa101a9b6e969008c08dbc30653784aedce7de66f22a11c",
          "sha256": "c77441e30ab5b2f410cb131d5d7f911db0153f1ad8450837b5b0d680ae8d55f0",
          "sha1": "7e0e64cc4bad00e24104111059982106794e1a99",
          "md5": "d60f19a8e11fd55d66d241a9dd8359d3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-hts-peripheral-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-htp-peripheral-android-0.1.4.aar",
          "url": "ble-profile-htp-peripheral-android-0.1.4.aar",
          "size": 5137,
          "sha512": "9e28c377951d363eaaa61b59497ec98231390610a51f8b07cc5064e3f7e0f4f59d705d7b0a529cc03aa101a9b6e969008c08dbc30653784aedce7de66f22a11c",
          "sha256": "c77441e30ab5b2f410cb131d5d7f911db0153f1ad8450837b5b0d680ae8d55f0",
          "sha1": "7e0e64cc4bad00e24104111059982106794e1a99",
          "md5": "d60f19a8e11fd55d66d241a9dd8359d3"
        }
      ]
    }
  ]
}
