{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bbc-android",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bbc",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbc-android-0.5.1.aar",
          "url": "ble-characteristic-u2bbc-android-0.5.1.aar",
          "size": 3077,
          "sha512": "7f3ed6bc60c54b2257ffcdc8f0fa74b6e04b6ae507ca8f75bd02c036f33bce8b229ca2614ce9681591bb4755ec7377985f5e0d9b886f1725163f45f6834ee8b7",
          "sha256": "4b08a0ad2adf086f83be5198aba355e9446443d8a43f732602f5a7efe92b92af",
          "sha1": "bef1c6e87aebd2cc376f5d5a8344f96fe98536eb",
          "md5": "557a4a4ae6768dcc848b6f5ded5f08cc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bbc",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbc-android-0.5.1.aar",
          "url": "ble-characteristic-u2bbc-android-0.5.1.aar",
          "size": 3077,
          "sha512": "7f3ed6bc60c54b2257ffcdc8f0fa74b6e04b6ae507ca8f75bd02c036f33bce8b229ca2614ce9681591bb4755ec7377985f5e0d9b886f1725163f45f6834ee8b7",
          "sha256": "4b08a0ad2adf086f83be5198aba355e9446443d8a43f732602f5a7efe92b92af",
          "sha1": "bef1c6e87aebd2cc376f5d5a8344f96fe98536eb",
          "md5": "557a4a4ae6768dcc848b6f5ded5f08cc"
        }
      ]
    }
  ]
}
