{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a02",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a02-0.8.12.jar",
          "url": "ble-characteristic-u2a02-0.8.12.jar",
          "size": 1945,
          "sha512": "f553766b048d381941d54fae7d49f5843fc18cfe65896f114f7e07eb61e7086df9d97dc54618ed3cd57aa9fc8b0194ae7629553f02e7687983cd84027e46ffbd",
          "sha256": "4ea15d991d8f30e91b55455a48454f7fbb6a66ef8a96d4527eb805ffd4e472bd",
          "sha1": "23be80bfb3b53c6681daa80cc0811072aa4ec77f",
          "md5": "9fbc207578a5eaca6058b421f16efbd3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a02-0.8.12.jar",
          "url": "ble-characteristic-u2a02-0.8.12.jar",
          "size": 1945,
          "sha512": "f553766b048d381941d54fae7d49f5843fc18cfe65896f114f7e07eb61e7086df9d97dc54618ed3cd57aa9fc8b0194ae7629553f02e7687983cd84027e46ffbd",
          "sha256": "4ea15d991d8f30e91b55455a48454f7fbb6a66ef8a96d4527eb805ffd4e472bd",
          "sha1": "23be80bfb3b53c6681daa80cc0811072aa4ec77f",
          "md5": "9fbc207578a5eaca6058b421f16efbd3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a02-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a02-0.8.12-javadoc.jar",
          "size": 109742,
          "sha512": "3fceadc237eb289d21406b8c40f74307d710512b6b9ea38eab45a3fd129501e808e30b60042cda2d58a44755d21a3f6c823d84fb193b62e537aac30f070dcf5b",
          "sha256": "b56854d2abf845e94a9a65d8c69d14193d05bcdb6f406768e97a6aa3eea2ce18",
          "sha1": "def36f564fa11dad7270a5ac9e3b5f72fbd5ae98",
          "md5": "9674c5d755fc81e29b8c098884e6822c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a02-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a02-0.8.12-sources.jar",
          "size": 1758,
          "sha512": "5058024da6bcf9062f68fd547afeeeed707c01ceb9e28481d31a57dd8e1425a32a4e55e746fb7b5da3af8fa267785ea0c4f3aa01e5bd98677ef635adeb68a009",
          "sha256": "32f510845f4ab12d970b07ed5df51949653824b51595fface632a10b01fd321a",
          "sha1": "0487433acf87981f250d774216f966d542994784",
          "md5": "75435ab08927d62bba27993634ead1fd"
        }
      ]
    }
  ]
}
