{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-bas-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-bas-android-0.8.12.aar",
          "url": "ble-service-central-bas-android-0.8.12.aar",
          "size": 6917,
          "sha512": "b2f489cc76b28bdb948dbe8d63d18d73b8666dea6846764cf6edd9bef9f07eba131fa634cc09b35f6f5c33932d237aac9b8ad83851f5deb41cb896fff66cebd9",
          "sha256": "111a149eaa95db3e91e310c074da0d9c014a9203527b91e4175ace256a107eb9",
          "sha1": "7a55107cc201632a290d329b26b7451baef905e2",
          "md5": "178d2a163c43f465ad74c0e455fb39c4"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-bas-android-0.8.12.aar",
          "url": "ble-service-central-bas-android-0.8.12.aar",
          "size": 6917,
          "sha512": "b2f489cc76b28bdb948dbe8d63d18d73b8666dea6846764cf6edd9bef9f07eba131fa634cc09b35f6f5c33932d237aac9b8ad83851f5deb41cb896fff66cebd9",
          "sha256": "111a149eaa95db3e91e310c074da0d9c014a9203527b91e4175ace256a107eb9",
          "sha1": "7a55107cc201632a290d329b26b7451baef905e2",
          "md5": "178d2a163c43f465ad74c0e455fb39c4"
        }
      ]
    }
  ]
}
