{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad0-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad0",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad0-android-0.8.13.aar",
          "url": "ble-characteristic-u2ad0-android-0.8.13.aar",
          "size": 5365,
          "sha512": "92cc340979468c1f59219fae24378b37e34c98c16dc6542be72ff0bf6ffffa12bfb599a3da43138a0197ac4e2c1d6feeb74d3b1655dcece75451f0232438cac0",
          "sha256": "f2901e66aa92ba6b442f2d52f00bf8be1cdf5490f7a89d26be27efc06fd58195",
          "sha1": "79011ea1a4442fc39fc0c05043ba472a46cda9e3",
          "md5": "723d722ae2cb46a1d58d5ee51ed6a6ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad0",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad0-android-0.8.13.aar",
          "url": "ble-characteristic-u2ad0-android-0.8.13.aar",
          "size": 5365,
          "sha512": "92cc340979468c1f59219fae24378b37e34c98c16dc6542be72ff0bf6ffffa12bfb599a3da43138a0197ac4e2c1d6feeb74d3b1655dcece75451f0232438cac0",
          "sha256": "f2901e66aa92ba6b442f2d52f00bf8be1cdf5490f7a89d26be27efc06fd58195",
          "sha1": "79011ea1a4442fc39fc0c05043ba472a46cda9e3",
          "md5": "723d722ae2cb46a1d58d5ee51ed6a6ae"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad0-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2ad0-android-0.8.13-sources.jar",
          "size": 3658,
          "sha512": "439c4a4169dcb5163b6339b767f47bb938cd2dda356b7837c71a87e2c0b669566a6a103396d6b24cdd096d0a5956a8fefe9e96c31f0d7d66ac02e89341431aea",
          "sha256": "4ff16b16ba1bcb53ebbbb369639af55171a7f33f6198810462b2f15f76a5b151",
          "sha1": "c2389a53af3e1e04507f8eb72233ef338b52ff74",
          "md5": "87a5a085187f3aa2f674e973abfd8d4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad0-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2ad0-android-0.8.13-javadoc.jar",
          "size": 275885,
          "sha512": "521a307bf1d9f5d1928cd6f28e0218ef806916b2edb42bfb8c415ccbe9a350220aa20981a9bfe87a067983d4537f97ac48c2b3f4517b5f93e5fe147c46608a6a",
          "sha256": "e924affd9934626c1ea798d081ab992c0bc1643c89ecec84be4c5b9bd3d7fe8b",
          "sha1": "e90244d406ebdcf65c11c908e4738332d198fd64",
          "md5": "f49cbba9c578a42f8f5798532758d7cf"
        }
      ]
    }
  ]
}
