{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-tip-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-cts-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ndcs-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-rtus-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-tip-android-0.8.6.aar",
          "url": "ble-profile-peripheral-tip-android-0.8.6.aar",
          "size": 7424,
          "sha512": "2be23b67f95a01e640f39c121bbc92b8651f4626474c6eec3cc9ad511c0d3bdac081662e57f8662c3c227a986648cb0806fe96ff97006317d974ad23dbb67437",
          "sha256": "7c34a6dfd05620d30229a310284e9043ff16329be0d21f10d7aa6b1abd8f985c",
          "sha1": "a59a374ee126296a31883a6c1490014bcc696039",
          "md5": "7e620c4374800a218fe7a780477fc06e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-cts-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-ndcs-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-rtus-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-tip-android-0.8.6.aar",
          "url": "ble-profile-peripheral-tip-android-0.8.6.aar",
          "size": 7424,
          "sha512": "2be23b67f95a01e640f39c121bbc92b8651f4626474c6eec3cc9ad511c0d3bdac081662e57f8662c3c227a986648cb0806fe96ff97006317d974ad23dbb67437",
          "sha256": "7c34a6dfd05620d30229a310284e9043ff16329be0d21f10d7aa6b1abd8f985c",
          "sha1": "a59a374ee126296a31883a6c1490014bcc696039",
          "md5": "7e620c4374800a218fe7a780477fc06e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-tip-android-0.8.6-sources.jar",
          "url": "ble-profile-peripheral-tip-android-0.8.6-sources.jar",
          "size": 4914,
          "sha512": "3d1cea25e6a9f2bf0c5adfa39231fcffd831b8ef51b0bcc2636e5f218d4cad97c727bd2081c1681be4d8bdca947fc14a95e971a1732650208c9f37d81bda4e26",
          "sha256": "7169efe2527e9b496fea00ac5b670cd64066136d4720c7ac58703ccddef8a212",
          "sha1": "16c83e5bfa4cb983cca0db437ba835970544f90a",
          "md5": "2f50ad99a63bb19b1ba28cf704699e0d"
        }
      ]
    }
  ]
}
