{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.7.jar",
          "url": "ble-characteristic-u2a04-0.8.7.jar",
          "size": 2207,
          "sha512": "433fa261da5f90e337d3ce6bd782cd2714b6759a4ceb5d7fa975c878ba7313a8eeb3e0e840c14ac66e83a770fa44c5d32262fae40e55c813bca92f951c179504",
          "sha256": "fc1f3054e8c23150207ac075915f3a1c02b0944f72c8559417d8983c432127a5",
          "sha1": "84c8bdb40577c194e5b24887c8e841a76797affb",
          "md5": "84299add1583d22d035e5021b6ad82ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.7.jar",
          "url": "ble-characteristic-u2a04-0.8.7.jar",
          "size": 2207,
          "sha512": "433fa261da5f90e337d3ce6bd782cd2714b6759a4ceb5d7fa975c878ba7313a8eeb3e0e840c14ac66e83a770fa44c5d32262fae40e55c813bca92f951c179504",
          "sha256": "fc1f3054e8c23150207ac075915f3a1c02b0944f72c8559417d8983c432127a5",
          "sha1": "84c8bdb40577c194e5b24887c8e841a76797affb",
          "md5": "84299add1583d22d035e5021b6ad82ac"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a04-0.8.7-javadoc.jar",
          "size": 110257,
          "sha512": "ecd48403995830f05c2ed2d98dd16b94455f25b9c1d7c5d97fe59cfed9e1171e6fd88b7ea340f6b302fccfdbb247b790f875ebde26a8938291ef97ee1b00e633",
          "sha256": "9efb3fa037a83b85470c6c54c3ac5bb708477ae8902778e7cff2469dc4b3183f",
          "sha1": "1b63bc69fc085ebbfe684a7a8e4be4ffe4257c37",
          "md5": "5dc4a882ff665ccbe0a508523941b0a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a04-0.8.7-sources.jar",
          "size": 2002,
          "sha512": "28fe6f67899730bc06ba137ccb496c5083f207fc67c9cfbaeeebac753533c1a1d390eadf0f9e9c3bad4a0aadddb434429a6eb8a60ffd6865e6b17f2b4196d427",
          "sha256": "c281a0874e36ec5501b2a91d58bbf3b58eb51ecdc830888889e1e178955232f7",
          "sha1": "cb33487511f1d5bd565dc6b60e95c9846e1e0058",
          "md5": "c9357633a768b23f1547012135fc05f8"
        }
      ]
    }
  ]
}
