{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4b",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4b-0.8.14.jar",
          "url": "ble-characteristic-u2a4b-0.8.14.jar",
          "size": 1476,
          "sha512": "c28afa1c4c3c1bff236e00adc0d4aac8b3e227c34b0a4d2c545c383873ba9e2a8eec3e4902db9d8ac1f9f0f1222734c446461c5849057402f2911468e5553586",
          "sha256": "e95e1dcf3ee48998bca06723b0c3f965f96c51251920af1fa57708bf96a8411f",
          "sha1": "1b71f466d21512541d30ae4f3ebf35a3f65496f8",
          "md5": "e3f94f48748dcb0b23b813858a4fee9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4b-0.8.14.jar",
          "url": "ble-characteristic-u2a4b-0.8.14.jar",
          "size": 1476,
          "sha512": "c28afa1c4c3c1bff236e00adc0d4aac8b3e227c34b0a4d2c545c383873ba9e2a8eec3e4902db9d8ac1f9f0f1222734c446461c5849057402f2911468e5553586",
          "sha256": "e95e1dcf3ee48998bca06723b0c3f965f96c51251920af1fa57708bf96a8411f",
          "sha1": "1b71f466d21512541d30ae4f3ebf35a3f65496f8",
          "md5": "e3f94f48748dcb0b23b813858a4fee9c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4b-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2a4b-0.8.14-javadoc.jar",
          "size": 86021,
          "sha512": "ab90219825e1a63c5ace13797388176bd67cbf7330366cea2e47adc823a67c0eadc9fd38c81284302ce82276391e01ed9f53ccffd329c8cd1877318f1dd17eff",
          "sha256": "0a19e48ac227c375b58fe6c1a53cc5f91d8b5bbca9449399ae3ab91e5972b84a",
          "sha1": "07490111b436c564e7d18484d3bd64e8d041e61b",
          "md5": "aab30e68642fb8143ba1ae39c385250d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4b-0.8.14-sources.jar",
          "url": "ble-characteristic-u2a4b-0.8.14-sources.jar",
          "size": 1439,
          "sha512": "a35463f22dbe1da0a068b64f3ee98f3920b75284a4b077465f1ee0ed72442970b21c9b3115e983c693855f543c85b0dd31f9480a060aad3820e8b7d94e8f4ed1",
          "sha256": "982eb4ccdb4b14d274d170a9191286ce728cb6a5a776e519b7feefb619cc1e91",
          "sha1": "06369fb6d4a4b27ef07a781436731bcc54770aea",
          "md5": "684c6685e4fec908bb221dc36b2f0b43"
        }
      ]
    }
  ]
}
