{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-gatt-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a02-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa6-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac9-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-gatt-android-0.8.6.aar",
          "url": "ble-service-gatt-android-0.8.6.aar",
          "size": 1227,
          "sha512": "7707fb3a245a6118d28d55220994b5c04870f23faf617e8900c2446ec44aac8e648c1190402a88c65dc57a5f19679b27d19cdfd5ddb2bd5c1136c9fa8d14b588",
          "sha256": "93d92087d2a3b7edf9105873bf19efe21bef1c05b40f79bc91b9799b7763160c",
          "sha1": "70e046f55a959accee35efed16e557da968e2a78",
          "md5": "cfe97e7bf037974386cd0592bbf1673b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a01-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a02-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa6-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac9-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-gatt-android-0.8.6.aar",
          "url": "ble-service-gatt-android-0.8.6.aar",
          "size": 1227,
          "sha512": "7707fb3a245a6118d28d55220994b5c04870f23faf617e8900c2446ec44aac8e648c1190402a88c65dc57a5f19679b27d19cdfd5ddb2bd5c1136c9fa8d14b588",
          "sha256": "93d92087d2a3b7edf9105873bf19efe21bef1c05b40f79bc91b9799b7763160c",
          "sha1": "70e046f55a959accee35efed16e557da968e2a78",
          "md5": "cfe97e7bf037974386cd0592bbf1673b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-gatt-android-0.8.6-sources.jar",
          "url": "ble-service-gatt-android-0.8.6-sources.jar",
          "size": 1197,
          "sha512": "ee8a1ff5b1bf25c296d9cc2545383ca86f7275c356e5e3ee429c89f06f9063a0c3da045abfb6dff44113b34e563f0d2e9e0d39d9f85ec02ef997222166b70ee9",
          "sha256": "c5a9ee7b5b4e1f9e531007ef6d0c671978746b376035f0af0d0f35976807b9d4",
          "sha1": "1207d08b74ef1c1a051adb6f6f57681689ac2015",
          "md5": "8e7cae501aa572a0be996d8cc6ff1236"
        }
      ]
    }
  ]
}
