{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad8",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.8.jar",
          "url": "ble-characteristic-u2ad8-0.8.8.jar",
          "size": 1935,
          "sha512": "e0b27cb2e6f27714279f729733b351fbbf66b165b3969ce2569060c4c780de3812b49a4e6e7cfa13ae07f7278ecc553ee736c8642d818bf5edb0c9810a07c714",
          "sha256": "633bda5bdafd23b2f04c12b497057fa347ff30d6d8047ad7d59e34629669dc54",
          "sha1": "376cb9a6f906cada4378f84f52925fe9738d18aa",
          "md5": "63dacc3457b67c78811e2ea840e99f94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.8.jar",
          "url": "ble-characteristic-u2ad8-0.8.8.jar",
          "size": 1935,
          "sha512": "e0b27cb2e6f27714279f729733b351fbbf66b165b3969ce2569060c4c780de3812b49a4e6e7cfa13ae07f7278ecc553ee736c8642d818bf5edb0c9810a07c714",
          "sha256": "633bda5bdafd23b2f04c12b497057fa347ff30d6d8047ad7d59e34629669dc54",
          "sha1": "376cb9a6f906cada4378f84f52925fe9738d18aa",
          "md5": "63dacc3457b67c78811e2ea840e99f94"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2ad8-0.8.8-javadoc.jar",
          "size": 107599,
          "sha512": "b2fbdc65c0c2856527aa017001d5f3525a88f74c787cb4f35c72426e63a6cc4fee56aac0d0b2d95dd8a0a46a90e63422b43bb6e0ea6c8c530e9142279584e085",
          "sha256": "28b99ad756e87ad0277d7757e3193f3ab7242a136ef385246ac83d58c655e607",
          "sha1": "3dde06bf42989b43079dea924e938a957551fb60",
          "md5": "d1951ff37b90190533540145654fef33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.8.8-sources.jar",
          "url": "ble-characteristic-u2ad8-0.8.8-sources.jar",
          "size": 1752,
          "sha512": "baf506b0f2394f0efdf335ebdf9103e87da3d21557729c3d372337b747a9eaeaea65c2c6244ecc1dd7d20a9af2ef424e72bda208a2053dd6ac9af18b14920bf9",
          "sha256": "37a7a7bc402739d24bf19754343416ea019319389d66240692092e9bcedeb6e7",
          "sha1": "32d51f9fc0c7aa8bf3e391b33537a379c48dcda3",
          "md5": "14278c774be210b572dd9c2d1034cfc5"
        }
      ]
    }
  ]
}
