{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a69-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ne3pcejtrrhfvmmkle32bx6bti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-android-0.2.5.aar",
          "url": "ble-characteristic-u2a69-android-0.2.5.aar",
          "size": 3044,
          "sha512": "5e843867a0ec94d15edbc11a572b60eddf2f230ace1914c6e52a5aedd57a7a1bc5856870b7613be727698b8fa010bd6f31b348e4c020576377b434aa451d79db",
          "sha256": "b842f37ee4cf52922349a21e1ad0318e483f2726089e41e469ac8fcafed4b055",
          "sha1": "563d9fdd2a005db85c06d372268b47b50f7100b2",
          "md5": "e1a09347661b4736a79b6369799b2e86"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a69",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a69-android-0.2.5.aar",
          "url": "ble-characteristic-u2a69-android-0.2.5.aar",
          "size": 3044,
          "sha512": "5e843867a0ec94d15edbc11a572b60eddf2f230ace1914c6e52a5aedd57a7a1bc5856870b7613be727698b8fa010bd6f31b348e4c020576377b434aa451d79db",
          "sha256": "b842f37ee4cf52922349a21e1ad0318e483f2726089e41e469ac8fcafed4b055",
          "sha1": "563d9fdd2a005db85c06d372268b47b50f7100b2",
          "md5": "e1a09347661b4736a79b6369799b2e86"
        }
      ]
    }
  ]
}
