{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-rcs-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1d-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1e-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1f-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rcs-android-0.4.6.aar",
          "url": "ble-service-rcs-android-0.4.6.aar",
          "size": 1184,
          "sha512": "9bc9bcb2e7e567f17beb1193928fa57000909694b01586c478e181e142551dd30ee74c9b1baba5e43b2b6ec0cb72b551b7e0386aaef6d8ce16845d77ba749ef5",
          "sha256": "8faa078e717263b858b47b68a28936470155d000a0d99545bba7f20c13b48663",
          "sha1": "dd09d2746d10d28b3fcae0ba91820011736d0fdb",
          "md5": "9533c5448a52d27628c7c309898473d5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1d-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1e-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1f-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rcs-android-0.4.6.aar",
          "url": "ble-service-rcs-android-0.4.6.aar",
          "size": 1184,
          "sha512": "9bc9bcb2e7e567f17beb1193928fa57000909694b01586c478e181e142551dd30ee74c9b1baba5e43b2b6ec0cb72b551b7e0386aaef6d8ce16845d77ba749ef5",
          "sha256": "8faa078e717263b858b47b68a28936470155d000a0d99545bba7f20c13b48663",
          "sha1": "dd09d2746d10d28b3fcae0ba91820011736d0fdb",
          "md5": "9533c5448a52d27628c7c309898473d5"
        }
      ]
    }
  ]
}
