{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-lls-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-lls-android-0.8.13.aar",
          "url": "ble-service-central-lls-android-0.8.13.aar",
          "size": 3658,
          "sha512": "5f2970382018d7c564cd00a30369445a4ea20466e6968d5a365d3d32e042621d3423fc8adec6dd6d0959c12c8d33837366e63f64f97fcbcc1cb9837ab1cc876b",
          "sha256": "bf5e02f31578f48f9d523794065e7c9ab84746f73680aef9bdfeb4e3a0a1feb3",
          "sha1": "012f8673c613df5b7d7d26f25f824a699cf91ea7",
          "md5": "73622df05ee63b8f9104b8202d10d5e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-android",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-lls-android-0.8.13.aar",
          "url": "ble-service-central-lls-android-0.8.13.aar",
          "size": 3658,
          "sha512": "5f2970382018d7c564cd00a30369445a4ea20466e6968d5a365d3d32e042621d3423fc8adec6dd6d0959c12c8d33837366e63f64f97fcbcc1cb9837ab1cc876b",
          "sha256": "bf5e02f31578f48f9d523794065e7c9ab84746f73680aef9bdfeb4e3a0a1feb3",
          "sha1": "012f8673c613df5b7d7d26f25f824a699cf91ea7",
          "md5": "73622df05ee63b8f9104b8202d10d5e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-lls-android-0.8.13-sources.jar",
          "url": "ble-service-central-lls-android-0.8.13-sources.jar",
          "size": 3712,
          "sha512": "ca48f5578e6f9bc441a7acbb2aaa9e59912f4e1ce325e5a60012ab916735825ad1fcc18f8dc8e737cd2509ab6f9f607a5ed15637e662ab1dd4cf74d668b6cdb3",
          "sha256": "83b6b3a302fca2a479581eefeabba57526ebb6a6a230281f477ee1302b30ae59",
          "sha1": "ef45a19a3501d69169ceca9e94597750f5b11b53",
          "md5": "cd8877509790a40b1a637e2836a8b485"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-lls-android-0.8.13-javadoc.jar",
          "url": "ble-service-central-lls-android-0.8.13-javadoc.jar",
          "size": 279475,
          "sha512": "eb3ca1c80e531bd9d33b7b6f1dda703243eb019a5bc8db39fbcdefe0d08bb56428725db58e020e49c0d58256df4023041192aeaf09e30ab15223f1b338b2cd37",
          "sha256": "978907c9f1d9d37615231f13008a25e812b470326e6b67b6bc6e3f581e7f2b5f",
          "sha1": "c8107d17ebc44a384d2ae636e5130ef4c9a1ee64",
          "md5": "773bfffff84dcf4c826425b4ffcf5a08"
        }
      ]
    }
  ]
}
