{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b01-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b01",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b01-android-0.8.13.aar",
          "url": "ble-characteristic-u2b01-android-0.8.13.aar",
          "size": 3147,
          "sha512": "16dc0cc697aaa8a7d6522861e7aa2af901091efebe22d6ae329e96da1c7b010b428ac1df8f16aed3ecc81ad255bae131f4d393456bd91abad55dce3d847d4331",
          "sha256": "97a2033fd867e06cef491c81fdaa492b8a37ca3c5ca3695e01fc024be0175bb3",
          "sha1": "eaa75f146093ee1855766926e6e30383fe30a42b",
          "md5": "4be8a0eb0e58060e671dfd37b8a1c8ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b01",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b01-android-0.8.13.aar",
          "url": "ble-characteristic-u2b01-android-0.8.13.aar",
          "size": 3147,
          "sha512": "16dc0cc697aaa8a7d6522861e7aa2af901091efebe22d6ae329e96da1c7b010b428ac1df8f16aed3ecc81ad255bae131f4d393456bd91abad55dce3d847d4331",
          "sha256": "97a2033fd867e06cef491c81fdaa492b8a37ca3c5ca3695e01fc024be0175bb3",
          "sha1": "eaa75f146093ee1855766926e6e30383fe30a42b",
          "md5": "4be8a0eb0e58060e671dfd37b8a1c8ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b01-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2b01-android-0.8.13-sources.jar",
          "size": 2203,
          "sha512": "25a1056a843a5ae1d596571d0b91b9ad80f3817a4023d2ffb997d49bb4d975a6a01d7d09c0ba6dc84cae1c86cf6e5386c89001bb52d7758905b255896379a22e",
          "sha256": "ae4b06966d2ed91b3ca13ed2f8b292890c41a5e3b1a89f1321aa3149c797a6e1",
          "sha1": "104aa903fa484ce6b8a5f3e0aaaf20ca100f8070",
          "md5": "71d19bc0f491f8e81e909b0062086c89"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b01-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2b01-android-0.8.13-javadoc.jar",
          "size": 272882,
          "sha512": "4aff654e692c0bec2b4927bd0c34ac9b87aa13d217f19f8d9c36a602e38ee1b02dd9c74d9727a48cd744a0e1ed5a74af7ba5e80ecf8cd480024e2a2f0ace4af2",
          "sha256": "ca67ecd6d02a4a5cf456c1044a9ac224fdcd2ce74076a62f53c566a1926fc322",
          "sha1": "99e85fb181f80fbac5a5d00110865f02c8acd8fa",
          "md5": "0b3e54b3d13d2a69fffb4ea3e9a4c7c3"
        }
      ]
    }
  ]
}
