{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a92-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.2.6.aar",
          "url": "ble-characteristic-u2a92-android-0.2.6.aar",
          "size": 3091,
          "sha512": "44a11dc12c40ece7d75099b74b0b1205469c866ab9c3e25573e8c3aa7f6ede82d4cf1a1cc4763be5765fee9192857197f83c85da61b6d5ff7337c42f5f42ae80",
          "sha256": "b82644e48e65d73f47f360a6800be3acad35baacb463e2ac0df06e6f1138a5fe",
          "sha1": "dafb675064bf9cb1a3a80e904948e1515bd27168",
          "md5": "99456bd09e90b3eaad4e4d22e1b92234"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a92",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a92-android-0.2.6.aar",
          "url": "ble-characteristic-u2a92-android-0.2.6.aar",
          "size": 3091,
          "sha512": "44a11dc12c40ece7d75099b74b0b1205469c866ab9c3e25573e8c3aa7f6ede82d4cf1a1cc4763be5765fee9192857197f83c85da61b6d5ff7337c42f5f42ae80",
          "sha256": "b82644e48e65d73f47f360a6800be3acad35baacb463e2ac0df06e6f1138a5fe",
          "sha1": "dafb675064bf9cb1a3a80e904948e1515bd27168",
          "md5": "99456bd09e90b3eaad4e4d22e1b92234"
        }
      ]
    }
  ]
}
