{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b46",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b46-0.8.3.jar",
          "url": "ble-characteristic-u2b46-0.8.3.jar",
          "size": 1880,
          "sha512": "0c34ca9a8c74045f5d300e313e23740cfb12e550d49497622d764d5a77dfc60d879596c1e9e9319d1ac42b976c976c21808e80ebab09c1b1e9e6e4560fdbba27",
          "sha256": "ba3f84f1fa4d6ba23f2a13ade728de7f08a5d4a9978701bedcfe901cf6000e21",
          "sha1": "26e46bf3e39f7342726f9b5bc4119558234b0771",
          "md5": "be3fbfdcd6bdcfadb902af17631dcb42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b46-0.8.3.jar",
          "url": "ble-characteristic-u2b46-0.8.3.jar",
          "size": 1880,
          "sha512": "0c34ca9a8c74045f5d300e313e23740cfb12e550d49497622d764d5a77dfc60d879596c1e9e9319d1ac42b976c976c21808e80ebab09c1b1e9e6e4560fdbba27",
          "sha256": "ba3f84f1fa4d6ba23f2a13ade728de7f08a5d4a9978701bedcfe901cf6000e21",
          "sha1": "26e46bf3e39f7342726f9b5bc4119558234b0771",
          "md5": "be3fbfdcd6bdcfadb902af17631dcb42"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b46-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2b46-0.8.3-javadoc.jar",
          "size": 110348,
          "sha512": "702586091cd86248d7024914cb5d28ea6985169e43e530c33fd5ddd54a79c14bdbc334c22aaf7415a3070de0d77edfd11238e4db9592f69c77239cb49f461121",
          "sha256": "7f9528e8fe80ac0bf8c6508e67fcb52946863b672ded2e4f8da81cb6e4e1a6a1",
          "sha1": "f00b6bf0c12d708455306de846dde2f2c52a4e6d",
          "md5": "b5c3592d88e3d9157d4ba538d6da25d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b46-0.8.3-sources.jar",
          "url": "ble-characteristic-u2b46-0.8.3-sources.jar",
          "size": 1699,
          "sha512": "d7fa055b2d577bf335d2faf477b0a8d564faa84b61ad1ba3519d5e90e9ab1c957bcc5bab877d7a7a006c23d2d0f5f84b149a4c9bed2af13f5b3fddb3f0c03d7e",
          "sha256": "e05747733ed43bef91a0db7f0de783460020ebdc979157f25cc5961d2cc05f29",
          "sha1": "e0ca8b3bd6b076c8df20bc6e4b8d96edcf76aa7b",
          "md5": "615a8a34bf8f09fe128a4a1036c5629f"
        }
      ]
    }
  ]
}
