{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5c",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5c-0.8.5.jar",
          "url": "ble-characteristic-u2a5c-0.8.5.jar",
          "size": 2190,
          "sha512": "03425176ed7c40567f24094667039b92e812df0d5e0247fd4e0fea8bb3c6c9bb55fc6171b29ac9f747795440e6b8d4c1db249268f1750c8352bc673b7485caae",
          "sha256": "357604f80c49bd7b7214ac52e3a69caed1cb0c48d5a520cc0320f2e4f3beed9a",
          "sha1": "8c276905e38e938c037e2d1ad1ec1761a8a78748",
          "md5": "0cc852f8f456004c2d41386ef061bab1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5c-0.8.5.jar",
          "url": "ble-characteristic-u2a5c-0.8.5.jar",
          "size": 2190,
          "sha512": "03425176ed7c40567f24094667039b92e812df0d5e0247fd4e0fea8bb3c6c9bb55fc6171b29ac9f747795440e6b8d4c1db249268f1750c8352bc673b7485caae",
          "sha256": "357604f80c49bd7b7214ac52e3a69caed1cb0c48d5a520cc0320f2e4f3beed9a",
          "sha1": "8c276905e38e938c037e2d1ad1ec1761a8a78748",
          "md5": "0cc852f8f456004c2d41386ef061bab1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5c-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a5c-0.8.5-javadoc.jar",
          "size": 110653,
          "sha512": "b98f70fee8f397cc7a46d46778319e6ff8f7b113152e8675fc3876da0f751fd1f1ee84cdfa88f405742ac27bd085f854e3132501d6d303ffc4b78971d24eefc5",
          "sha256": "14181b5e5b63776008db4810a5863298fb595f63e003e7304b649ad091df2518",
          "sha1": "bba378ea17fa8827b75ed761d556b0b0da1d6e8c",
          "md5": "6978dfadf1b128f64be96b9a606623aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5c-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a5c-0.8.5-sources.jar",
          "size": 2153,
          "sha512": "863b9a434a1bd014caac892fd2848f2003bad954a6fbe1f792c7510fc6f97e71761efa2162605c664d10e8c9c8a0bdca21c4ed0143252f98bb1ac19c1c651979",
          "sha256": "c596b39de3efa1522a62bb1ff0ab1292cec19575c46e991e77ec3430f730eeb8",
          "sha1": "cb9b3e1f09eab8d212ef4b560e8ae3804a14e966",
          "md5": "00b804df1155f5210f7a3123469e9820"
        }
      ]
    }
  ]
}
