{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a48",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-0.5.0.jar",
          "url": "ble-characteristic-u2a48-0.5.0.jar",
          "size": 2106,
          "sha512": "4a6ce4cbe3fa9dbd13e3430bbef6f0a3c541b60bedb8edc2ab388a666d64020ba3f6a5a8c10df73e3d473e7453dbafeefe496cefc8143316d7a9e555654e9b27",
          "sha256": "cfc057cd5fdb6a613d0c33cd0b4d2929ee4b5d43713b955b57cd909532b2399c",
          "sha1": "df4287b3b617d935050c1611c5e438044e4046c7",
          "md5": "4165f7d84873ab55deb4a3581721cc73"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a48-0.5.0.jar",
          "url": "ble-characteristic-u2a48-0.5.0.jar",
          "size": 2106,
          "sha512": "4a6ce4cbe3fa9dbd13e3430bbef6f0a3c541b60bedb8edc2ab388a666d64020ba3f6a5a8c10df73e3d473e7453dbafeefe496cefc8143316d7a9e555654e9b27",
          "sha256": "cfc057cd5fdb6a613d0c33cd0b4d2929ee4b5d43713b955b57cd909532b2399c",
          "sha1": "df4287b3b617d935050c1611c5e438044e4046c7",
          "md5": "4165f7d84873ab55deb4a3581721cc73"
        }
      ]
    }
  ]
}
