{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-bls-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-bls-android-0.4.4.aar",
          "url": "ble-service-peripheral-bls-android-0.4.4.aar",
          "size": 4486,
          "sha512": "1d2caa28c7654f1ad96ed896c4e3aabc1d9c63f012ede645b1cb8b3cd128275f8e563fdecb19a1b77becd889ea66fef13e21de570f2fa2463da6981d4ce01183",
          "sha256": "0f29ce23d0cb1a6b59fd3698c421af535366106b5ce2319084ee76c0a046f914",
          "sha1": "c0b4693570110db7fc0ba82ec93cd5a15dcef3e1",
          "md5": "5f92081917b323f93edf3fe1f34e5c35"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-bls-android-0.4.4.aar",
          "url": "ble-service-peripheral-bls-android-0.4.4.aar",
          "size": 4486,
          "sha512": "1d2caa28c7654f1ad96ed896c4e3aabc1d9c63f012ede645b1cb8b3cd128275f8e563fdecb19a1b77becd889ea66fef13e21de570f2fa2463da6981d4ce01183",
          "sha256": "0f29ce23d0cb1a6b59fd3698c421af535366106b5ce2319084ee76c0a046f914",
          "sha1": "c0b4693570110db7fc0ba82ec93cd5a15dcef3e1",
          "md5": "5f92081917b323f93edf3fe1f34e5c35"
        }
      ]
    }
  ]
}
