{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b29",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "e3ikqwiwsbdaddptppumhoyem4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b29-0.1.0.jar",
          "url": "ble-characteristic-u2b29-0.1.0.jar",
          "size": 1900,
          "sha512": "6580798948eff5fdfc81edb09e25f99a69ede8775a0a4ee206c089c4ea398365de787aca81116914475bac7b378df44e3498f28fceb8d741dd320240bbac1a3c",
          "sha256": "b68367db8557e83125a228140a27b5d94fe89386b59cff2a07cff7578f188595",
          "sha1": "9c05175e4d5a229a3f5bd041e928f00cd7a448b5",
          "md5": "8b99ee59b5143e48bcf675ee976b9f28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b29-0.1.0.jar",
          "url": "ble-characteristic-u2b29-0.1.0.jar",
          "size": 1900,
          "sha512": "6580798948eff5fdfc81edb09e25f99a69ede8775a0a4ee206c089c4ea398365de787aca81116914475bac7b378df44e3498f28fceb8d741dd320240bbac1a3c",
          "sha256": "b68367db8557e83125a228140a27b5d94fe89386b59cff2a07cff7578f188595",
          "sha1": "9c05175e4d5a229a3f5bd041e928f00cd7a448b5",
          "md5": "8b99ee59b5143e48bcf675ee976b9f28"
        }
      ]
    }
  ]
}
