{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b11-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b11",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b11-android-0.8.6.aar",
          "url": "ble-characteristic-u2b11-android-0.8.6.aar",
          "size": 3184,
          "sha512": "3164a60e80789abf3dee9f293eadac99fc6e88ff78dca276956dce3a7c398ff7d96a2b212ee47409fedc6cac9ad472677d3f970c1001ccd87d3289742bd83795",
          "sha256": "cb481ff2444bd12c9bdc77a96a4768d421499af8082b4d67b638b44ade0ca2fa",
          "sha1": "d1f3f790b2f07f757dc8ec9b8ccc0e8cc9682b9f",
          "md5": "e7337557e742f1fed71488707ac1204c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b11",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b11-android-0.8.6.aar",
          "url": "ble-characteristic-u2b11-android-0.8.6.aar",
          "size": 3184,
          "sha512": "3164a60e80789abf3dee9f293eadac99fc6e88ff78dca276956dce3a7c398ff7d96a2b212ee47409fedc6cac9ad472677d3f970c1001ccd87d3289742bd83795",
          "sha256": "cb481ff2444bd12c9bdc77a96a4768d421499af8082b4d67b638b44ade0ca2fa",
          "sha1": "d1f3f790b2f07f757dc8ec9b8ccc0e8cc9682b9f",
          "md5": "e7337557e742f1fed71488707ac1204c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b11-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b11-android-0.8.6-sources.jar",
          "size": 2281,
          "sha512": "ca6aadcc4407da323127ee34d154af47f6d8dcc80711626f16f907513ce8f972a1f54cab6d92f448fe72451407415751201e367398c7979f51dcfe94a2071ed6",
          "sha256": "c97b64b11ea2c21813ca799fba7ea365d0aeaffc8e17c690a5c53461fade0be4",
          "sha1": "3f15097fc894227ed6947b7308191daa80bb806a",
          "md5": "bd501a734a7777ec389ae47efa71c48e"
        }
      ]
    }
  ]
}
