{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abc-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6cu2oomv2fb67ivu2iebxgsxbm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abc",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abc-android-0.2.0.aar",
          "url": "ble-characteristic-u2abc-android-0.2.0.aar",
          "size": 4800,
          "sha512": "b9895e6773f5a73a293728f1dabde161c7ea2ce60306f9caaa4332c14f95d3872df277c317025e161492232566bb06db67c740ea1097745cd44e91d603b35c15",
          "sha256": "bd2c6156c995ea44c56dab79d55fa9ada14f3774f77a7e379d52e0fc9958f552",
          "sha1": "db2b08ba90c3354be709d9848ecad802105b695a",
          "md5": "5f67ecb740c8144dafdb3e3a8078c1c7"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abc",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abc-android-0.2.0.aar",
          "url": "ble-characteristic-u2abc-android-0.2.0.aar",
          "size": 4800,
          "sha512": "b9895e6773f5a73a293728f1dabde161c7ea2ce60306f9caaa4332c14f95d3872df277c317025e161492232566bb06db67c740ea1097745cd44e91d603b35c15",
          "sha256": "bd2c6156c995ea44c56dab79d55fa9ada14f3774f77a7e379d52e0fc9958f552",
          "sha1": "db2b08ba90c3354be709d9848ecad802105b695a",
          "md5": "5f67ecb740c8144dafdb3e3a8078c1c7"
        }
      ]
    }
  ]
}
