{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b85",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.5.jar",
          "url": "ble-characteristic-u2b85-0.8.5.jar",
          "size": 1778,
          "sha512": "3f8763ac21cfcb53461f5e082f640237d626ab1f37487f5ae18e97e54ac9f3dc7255f7c40eefec7eef943c3695a9370e800250461c8dd76fff4dbdcdd640cac5",
          "sha256": "cc96a69e640bf06b3c61a0e76bf1cb09de9b83e1ddce5a21b8cce256ea537e0c",
          "sha1": "0855eae08cdddc35dc0f304634a1fd0bf27166bc",
          "md5": "f0ba14eaecf72b40187b6a98d0491425"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.5.jar",
          "url": "ble-characteristic-u2b85-0.8.5.jar",
          "size": 1778,
          "sha512": "3f8763ac21cfcb53461f5e082f640237d626ab1f37487f5ae18e97e54ac9f3dc7255f7c40eefec7eef943c3695a9370e800250461c8dd76fff4dbdcdd640cac5",
          "sha256": "cc96a69e640bf06b3c61a0e76bf1cb09de9b83e1ddce5a21b8cce256ea537e0c",
          "sha1": "0855eae08cdddc35dc0f304634a1fd0bf27166bc",
          "md5": "f0ba14eaecf72b40187b6a98d0491425"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b85-0.8.5-javadoc.jar",
          "size": 107361,
          "sha512": "3cc71ea4ae63035b3308095d29a61c2e66753e9b97557ddb530e86f1ece9d0516e0c7ef8698429354bb9aa704a808451e67982324dede4b253e35700365ce48b",
          "sha256": "0011f4b31a3be120a1f264973e4163416ba78b9fff096fa7d50d34a9254b464f",
          "sha1": "dd1a036c6b7ae0eacf792c5b40e44d84bb78a4a1",
          "md5": "b4ac6d8d192c86a69ccd588a84d92360"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b85-0.8.5-sources.jar",
          "size": 1621,
          "sha512": "7413249cf867db3dc20d909bfafe653e7b7751a070a7997e76215cea587608c9498bf70c72032e84a4ce20eec0d0a75b4a7076bed6c7999a11ec13e53d7cfbe2",
          "sha256": "c793e3bd4a5fa92d65de7a882bb425db16e2451529bb3e206ecdf0e14b6a0815",
          "sha1": "b1becbbdf6fefabdab9ade9f4662528f24605fa5",
          "md5": "1ad03099f5e66fb1b919f493340e4574"
        }
      ]
    }
  ]
}
