{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a51-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a51",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a51-android-0.8.9.aar",
          "url": "ble-characteristic-u2a51-android-0.8.9.aar",
          "size": 3140,
          "sha512": "d04bd0d3d2964dbd2a97c7fc78d2320c1a08a982c8e8bfe1cc97a5e3c5df0d66be523ace8c17e6361158d3edde14e9f92058b6055529fc949fad069cd0c1be3a",
          "sha256": "fc08d35cef806c31c554c78c9214a3e3d31d06d2cf3870f48d969e1f43eab006",
          "sha1": "e7263cc64534c12c9d6ae90bb5d6fdc2f8a7037a",
          "md5": "473cd83ae2acea39140efbcf21f323b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a51",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a51-android-0.8.9.aar",
          "url": "ble-characteristic-u2a51-android-0.8.9.aar",
          "size": 3140,
          "sha512": "d04bd0d3d2964dbd2a97c7fc78d2320c1a08a982c8e8bfe1cc97a5e3c5df0d66be523ace8c17e6361158d3edde14e9f92058b6055529fc949fad069cd0c1be3a",
          "sha256": "fc08d35cef806c31c554c78c9214a3e3d31d06d2cf3870f48d969e1f43eab006",
          "sha1": "e7263cc64534c12c9d6ae90bb5d6fdc2f8a7037a",
          "md5": "473cd83ae2acea39140efbcf21f323b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a51-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2a51-android-0.8.9-sources.jar",
          "size": 2144,
          "sha512": "794b26a78df4186d676b41d94fcd077d016d74c34cbef5f376fecb67635e1f2d9623bffd02c70fa5d7233ff0ee930ff541246c614f3fda22fb3d1126922145c7",
          "sha256": "b4e348c51d6572155695e7844aa503cb7ba4c8a65cea5ea166cfa35f6e5b5aea",
          "sha1": "64946c849724bd2fc3c84a2b3c25fe5642415fa6",
          "md5": "97e1e391af3eff60e9d61ec8a7da394f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a51-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2a51-android-0.8.9-javadoc.jar",
          "size": 268844,
          "sha512": "cf4aba2bb7d12a4d5f33ebb95dd470160e96c7a790de4bf11c6f2c5224e61af7806b59620e99168e2736915cdfc6aa89e5b0f5324de0e1a44939e2bb09d676cd",
          "sha256": "c74e1bc25a997d91d5c7e50dc8c10ca3cf385d476953d9c823c7c163c50c1b7a",
          "sha1": "321d16954501de2389d9a19963f2f80ee66e02ad",
          "md5": "db9e380e6800ffd47d5ad0d289a4a229"
        }
      ]
    }
  ]
}
