{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0c-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0c",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-android-0.8.6.aar",
          "url": "ble-characteristic-u2b0c-android-0.8.6.aar",
          "size": 3190,
          "sha512": "f95e05e6fe20db4ca80d4489f52249a84c9bb76cfb9533dc52f8a437b3494f576c30eb83c7aa896d4cca67ecf05fed08a1364e18332d81244449670a02a7b58d",
          "sha256": "10aa6b0ddc46526ec1de2ed1e0cc09f3e933098a594de9ee78f675f99b623ac1",
          "sha1": "c99c2ed1b0d8976ee894c9a5360d02142a54ea4d",
          "md5": "5e5abeb0140c5c38439e9c8fb1b0d927"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b0c",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0c-android-0.8.6.aar",
          "url": "ble-characteristic-u2b0c-android-0.8.6.aar",
          "size": 3190,
          "sha512": "f95e05e6fe20db4ca80d4489f52249a84c9bb76cfb9533dc52f8a437b3494f576c30eb83c7aa896d4cca67ecf05fed08a1364e18332d81244449670a02a7b58d",
          "sha256": "10aa6b0ddc46526ec1de2ed1e0cc09f3e933098a594de9ee78f675f99b623ac1",
          "sha1": "c99c2ed1b0d8976ee894c9a5360d02142a54ea4d",
          "md5": "5e5abeb0140c5c38439e9c8fb1b0d927"
        }
      ]
    }
  ]
}
