{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abf-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abf",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abf-android-0.4.3.aar",
          "url": "ble-characteristic-u2abf-android-0.4.3.aar",
          "size": 3136,
          "sha512": "64b59c67de72e6c801aacbad39deb7c9443e1387a2a2c20f3b342a5f931583aca35d634b490c757ec39eb18338ad495e7c0fa24819fe8cc4a54677cd7da94f92",
          "sha256": "61de2c0e1977ed91c93fd824055a3535012205b2f2695314c4d73183a4adbc96",
          "sha1": "4aca5f252f9ea4d6c51763a81c2bf9a632a09d7d",
          "md5": "814c9c78e8ee2d4d0d4f35925ae9d793"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abf",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abf-android-0.4.3.aar",
          "url": "ble-characteristic-u2abf-android-0.4.3.aar",
          "size": 3136,
          "sha512": "64b59c67de72e6c801aacbad39deb7c9443e1387a2a2c20f3b342a5f931583aca35d634b490c757ec39eb18338ad495e7c0fa24819fe8cc4a54677cd7da94f92",
          "sha256": "61de2c0e1977ed91c93fd824055a3535012205b2f2695314c4d73183a4adbc96",
          "sha1": "4aca5f252f9ea4d6c51763a81c2bf9a632a09d7d",
          "md5": "814c9c78e8ee2d4d0d4f35925ae9d793"
        }
      ]
    }
  ]
}
