{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-tps-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-tps-android-0.8.12.aar",
          "url": "ble-service-tps-android-0.8.12.aar",
          "size": 1295,
          "sha512": "9133693547c841cbcd9791e7212401502aac8b989ad034ac31b31ad9e4fb2f9bce7b5447d70b200d77d2741807368274c5cd4829c37843f9d468bac786d6f700",
          "sha256": "33101e2a41c6253053cb90f42e3e74e51782ab581a74e3ad1536d3eacd62c82b",
          "sha1": "059d0d2510e474755f176962d30cb8c56d9f60ac",
          "md5": "2f3a85753db9ed5eba938491d676c15e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07-android",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-tps-android-0.8.12.aar",
          "url": "ble-service-tps-android-0.8.12.aar",
          "size": 1295,
          "sha512": "9133693547c841cbcd9791e7212401502aac8b989ad034ac31b31ad9e4fb2f9bce7b5447d70b200d77d2741807368274c5cd4829c37843f9d468bac786d6f700",
          "sha256": "33101e2a41c6253053cb90f42e3e74e51782ab581a74e3ad1536d3eacd62c82b",
          "sha1": "059d0d2510e474755f176962d30cb8c56d9f60ac",
          "md5": "2f3a85753db9ed5eba938491d676c15e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-tps-android-0.8.12-sources.jar",
          "url": "ble-service-tps-android-0.8.12-sources.jar",
          "size": 1193,
          "sha512": "84aa7c49251ad7436ce338f657e58e8f62bdaeec99045cf5009745664336d438ec4195212fcd09ae50f5cb24ef6aa8bfc262944f58e969f6c36356572fcac4ec",
          "sha256": "dd967b7af6a668d775d97f8016e4a74a4b8be84b24208ac64a23b9b50104e4d7",
          "sha1": "eda70169973d59992d5c7705b68726cb357b7712",
          "md5": "79f0a76b4c0df2d593d49323192fad40"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-tps-android-0.8.12-javadoc.jar",
          "url": "ble-service-tps-android-0.8.12-javadoc.jar",
          "size": 259946,
          "sha512": "3504bbd4b15f9a8693c22816cb95b89b31ae94d02bf952e04088fdd217f47d2665a657c98e6cf34664f610ead379052877f8012ea0f9ada585a78176c4bf9331",
          "sha256": "a7b9a363d188d53a4084b4faad47c7ce356840be8c3df47910816f854e740cd3",
          "sha1": "e2df1583e9a296f0696d55d9e9d6420e2eccbbdb",
          "md5": "7529aac74013cc276d20f9006170ce41"
        }
      ]
    }
  ]
}
