{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab5-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab5",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab5-android-0.2.4.aar",
          "url": "ble-characteristic-u2ab5-android-0.2.4.aar",
          "size": 3080,
          "sha512": "a19ab4182e21b45bacdce4959cf6a600f859c5e03913fabe507db24026b66dee5748a259a82aa284e1d67c657aa51d1919558a089a0aef666928fbd3d5d9aff0",
          "sha256": "9d70672c4d5f35eaa2ab887ea480384a983dc6a71263ceeb243bb608557d19b0",
          "sha1": "4f1323f040149e3ec979a45556494ad0884ff91b",
          "md5": "2b70e6b95d211b6022aa25cf8127c4a3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab5",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab5-android-0.2.4.aar",
          "url": "ble-characteristic-u2ab5-android-0.2.4.aar",
          "size": 3080,
          "sha512": "a19ab4182e21b45bacdce4959cf6a600f859c5e03913fabe507db24026b66dee5748a259a82aa284e1d67c657aa51d1919558a089a0aef666928fbd3d5d9aff0",
          "sha256": "9d70672c4d5f35eaa2ab887ea480384a983dc6a71263ceeb243bb608557d19b0",
          "sha1": "4f1323f040149e3ec979a45556494ad0884ff91b",
          "md5": "2b70e6b95d211b6022aa25cf8127c4a3"
        }
      ]
    }
  ]
}
