{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9b-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9b",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9b-android-0.4.5.aar",
          "url": "ble-characteristic-u2b9b-android-0.4.5.aar",
          "size": 3050,
          "sha512": "9e1e1ac2c726fb778d972f1fa1daf7306aeccd75893f49a6a939964f38f1185ee8feb76c7ec7b013378fc506e98f6bc18392737c64248184ae11c20896016ce9",
          "sha256": "6cb82f09c27dd0e082c77159b13dc99a43fa577f55953f82c91fde1a1bccb408",
          "sha1": "1796c307338a487cc51dcf9bc1676d28f9292b82",
          "md5": "339ab210fbde29e4e8d6dc8282e553d5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9b",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9b-android-0.4.5.aar",
          "url": "ble-characteristic-u2b9b-android-0.4.5.aar",
          "size": 3050,
          "sha512": "9e1e1ac2c726fb778d972f1fa1daf7306aeccd75893f49a6a939964f38f1185ee8feb76c7ec7b013378fc506e98f6bc18392737c64248184ae11c20896016ce9",
          "sha256": "6cb82f09c27dd0e082c77159b13dc99a43fa577f55953f82c91fde1a1bccb408",
          "sha1": "1796c307338a487cc51dcf9bc1676d28f9292b82",
          "md5": "339ab210fbde29e4e8d6dc8282e553d5"
        }
      ]
    }
  ]
}
