{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aca-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aca",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aca-android-0.8.6.aar",
          "url": "ble-characteristic-u2aca-android-0.8.6.aar",
          "size": 3028,
          "sha512": "b8b4d2ded07140e94f45ac6f0f9744b888153baeb32980fe995887efe63f34b4e46dfa39e74fe74c8255bf5eb90e7101bb00d6ab0651f5810bd76e1efcfbbb8b",
          "sha256": "18f7d4c337ca8dd107ccfdd5865960453296996fed8a6d51e07117bee36da030",
          "sha1": "da4acdb1bc69416051c1febe74c024e58a5a5f34",
          "md5": "7c20882793ccc9e298cd3ba717284acc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aca",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aca-android-0.8.6.aar",
          "url": "ble-characteristic-u2aca-android-0.8.6.aar",
          "size": 3028,
          "sha512": "b8b4d2ded07140e94f45ac6f0f9744b888153baeb32980fe995887efe63f34b4e46dfa39e74fe74c8255bf5eb90e7101bb00d6ab0651f5810bd76e1efcfbbb8b",
          "sha256": "18f7d4c337ca8dd107ccfdd5865960453296996fed8a6d51e07117bee36da030",
          "sha1": "da4acdb1bc69416051c1febe74c024e58a5a5f34",
          "md5": "7c20882793ccc9e298cd3ba717284acc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aca-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2aca-android-0.8.6-sources.jar",
          "size": 2125,
          "sha512": "80e87fde3e461d5f54009a65db97db59907e08efea7ea1356cca00ea99f2dafeeed02fda7302fe9faca6cfadd35d6b903470697d75621744bc3276fdbb9aa942",
          "sha256": "3b5289b2ccb7035ddf4c3fa46703a4a4308f456efc6d75ad8defdd92aea19b23",
          "sha1": "2bbe80a8c65503da732516a5dbf833f3f91b003c",
          "md5": "9c97c01f78285fcf5211b97a2c1ff9df"
        }
      ]
    }
  ]
}
