{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a14-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "imnihwqv65eu7lrkazou3zhih4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a14",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a14-android-0.2.2.aar",
          "url": "ble-characteristic-u2a14-android-0.2.2.aar",
          "size": 3000,
          "sha512": "b927e4ab74c08ebf5f8f72f57e73f2941fe93e7645dc2350fb5071e48c2d06baa4bb843328e8b745f10f3906b1839266b25673304784eee0fd86a0f1703e822e",
          "sha256": "13de6d340b51d1bf5a99d271d611842f7b3560e21d1121bc18f8307d9b88e95a",
          "sha1": "a564ae4eddb0f757bb471edf41305069dcf2c246",
          "md5": "0b924ac13b6c721558c45edcc98ea724"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a14",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a14-android-0.2.2.aar",
          "url": "ble-characteristic-u2a14-android-0.2.2.aar",
          "size": 3000,
          "sha512": "b927e4ab74c08ebf5f8f72f57e73f2941fe93e7645dc2350fb5071e48c2d06baa4bb843328e8b745f10f3906b1839266b25673304784eee0fd86a0f1703e822e",
          "sha256": "13de6d340b51d1bf5a99d271d611842f7b3560e21d1121bc18f8307d9b88e95a",
          "sha1": "a564ae4eddb0f757bb471edf41305069dcf2c246",
          "md5": "0b924ac13b6c721558c45edcc98ea724"
        }
      ]
    }
  ]
}
