{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa5-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa5-android-0.1.6.aar",
          "url": "ble-characteristic-u2aa5-android-0.1.6.aar",
          "size": 3070,
          "sha512": "e7a30939960ca11c62459d3e7809f332686a2e3f4bfdecd0f80163262e9365523f1a771fddedfe65ecd469fc78f9582f10d97e30b692f8a124ad0ebdbb23014f",
          "sha256": "93e4ec8cd0c29cd621ec920fc95cc2b266a2344b1b27452b81785af1fab3b825",
          "sha1": "81c3a28cf6dc69922f97f8f53a44d28577b4978f",
          "md5": "652e5dcd815db5ceb3ca41d8d210e4d2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa5-android-0.1.6.aar",
          "url": "ble-characteristic-u2aa5-android-0.1.6.aar",
          "size": 3070,
          "sha512": "e7a30939960ca11c62459d3e7809f332686a2e3f4bfdecd0f80163262e9365523f1a771fddedfe65ecd469fc78f9582f10d97e30b692f8a124ad0ebdbb23014f",
          "sha256": "93e4ec8cd0c29cd621ec920fc95cc2b266a2344b1b27452b81785af1fab3b825",
          "sha1": "81c3a28cf6dc69922f97f8f53a44d28577b4978f",
          "md5": "652e5dcd815db5ceb3ca41d8d210e4d2"
        }
      ]
    }
  ]
}
