{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa5-android",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgm5345lfvewjajsd7sfgyhu7u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa5-android-0.1.9.aar",
          "url": "ble-characteristic-u2aa5-android-0.1.9.aar",
          "size": 3102,
          "sha512": "121784e464cf5c88de9b7d343dc1d01dc7b4ecfd9a75ab1e922f9ca926fb50cef070749c1c3d54cc9e75c9de9d9603eee8eee5a3bbf9fff66eb6c5c566377914",
          "sha256": "15f59992175e4adfae1c3282f35aa51caff6e8955ad6065dcd77dc583d8a688d",
          "sha1": "71da8ee3ac3400e383fe2e90d1dc90827f3d1e2a",
          "md5": "5b0d9fb905854939554df5e26677048f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa5",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa5-android-0.1.9.aar",
          "url": "ble-characteristic-u2aa5-android-0.1.9.aar",
          "size": 3102,
          "sha512": "121784e464cf5c88de9b7d343dc1d01dc7b4ecfd9a75ab1e922f9ca926fb50cef070749c1c3d54cc9e75c9de9d9603eee8eee5a3bbf9fff66eb6c5c566377914",
          "sha256": "15f59992175e4adfae1c3282f35aa51caff6e8955ad6065dcd77dc583d8a688d",
          "sha1": "71da8ee3ac3400e383fe2e90d1dc90827f3d1e2a",
          "md5": "5b0d9fb905854939554df5e26677048f"
        }
      ]
    }
  ]
}
