{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2905-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2905",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2905-android-0.1.1.aar",
          "url": "ble-descriptor-u2905-android-0.1.1.aar",
          "size": 2909,
          "sha512": "fe23d4d1e139edf121014e4ca91cc40a5ff03f0a8f2f8960d033ea3f56a40eed3de56f149ac8d914455969b4ca031243d755bed25cc0ec0939fd352b8a5ba373",
          "sha256": "8d0853e13b7de54ee7510bf402e5663d82868eb6ae43a31fa07d6bbadc83e77b",
          "sha1": "f823a616bfcea69f9caa3525baf8593b50627a62",
          "md5": "f5add727f13260b891e9bf790884f86f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2905",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2905-android-0.1.1.aar",
          "url": "ble-descriptor-u2905-android-0.1.1.aar",
          "size": 2909,
          "sha512": "fe23d4d1e139edf121014e4ca91cc40a5ff03f0a8f2f8960d033ea3f56a40eed3de56f149ac8d914455969b4ca031243d755bed25cc0ec0939fd352b8a5ba373",
          "sha256": "8d0853e13b7de54ee7510bf402e5663d82868eb6ae43a31fa07d6bbadc83e77b",
          "sha1": "f823a616bfcea69f9caa3525baf8593b50627a62",
          "md5": "f5add727f13260b891e9bf790884f86f"
        }
      ]
    }
  ]
}
