{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6c-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6c",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6c-android-0.2.4.aar",
          "url": "ble-characteristic-u2a6c-android-0.2.4.aar",
          "size": 3065,
          "sha512": "685671ae78c8c2c51308943a2a4cd1066f59815c7279c0f06b0d875f8e69dc75ae9735adf33a1ab203722fe5959d7b07ea0707e7368ec4c39741e74c698ad423",
          "sha256": "44d45353faa7476a603e848817c2f394efcedd0a4013945cc705b805684482ba",
          "sha1": "64e9f6361e994cbd4f456e5d10bf80da5a82cd48",
          "md5": "64725aa0f393bb01af65554696d42528"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6c",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6c-android-0.2.4.aar",
          "url": "ble-characteristic-u2a6c-android-0.2.4.aar",
          "size": 3065,
          "sha512": "685671ae78c8c2c51308943a2a4cd1066f59815c7279c0f06b0d875f8e69dc75ae9735adf33a1ab203722fe5959d7b07ea0707e7368ec4c39741e74c698ad423",
          "sha256": "44d45353faa7476a603e848817c2f394efcedd0a4013945cc705b805684482ba",
          "sha1": "64e9f6361e994cbd4f456e5d10bf80da5a82cd48",
          "md5": "64725aa0f393bb01af65554696d42528"
        }
      ]
    }
  ]
}
