{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-aiop-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-aios-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-aiop-android-0.4.4.aar",
          "url": "ble-profile-peripheral-aiop-android-0.4.4.aar",
          "size": 4096,
          "sha512": "62abeb54c39eb8d9098cb5818d4c3bc31bd2c25bd7814963f90348c6582dac52772dd4d16404d0ceb7e524cf96d5e54f1ec2e9e78393b902b67d41a1997c4828",
          "sha256": "3f0a93aae12862d9b26e11080bf84208fecd2a6d128b7ec7f21729cade85fcbd",
          "sha1": "2e6d81b803dd598e4aa2be416b66a478bc957c30",
          "md5": "b5153db937d9dcd917dbcc29a4ac9bb2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-aios-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-aiop-android-0.4.4.aar",
          "url": "ble-profile-peripheral-aiop-android-0.4.4.aar",
          "size": 4096,
          "sha512": "62abeb54c39eb8d9098cb5818d4c3bc31bd2c25bd7814963f90348c6582dac52772dd4d16404d0ceb7e524cf96d5e54f1ec2e9e78393b902b67d41a1997c4828",
          "sha256": "3f0a93aae12862d9b26e11080bf84208fecd2a6d128b7ec7f21729cade85fcbd",
          "sha1": "2e6d81b803dd598e4aa2be416b66a478bc957c30",
          "md5": "b5153db937d9dcd917dbcc29a4ac9bb2"
        }
      ]
    }
  ]
}
