{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3f-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-android-0.8.12.aar",
          "url": "ble-characteristic-u2b3f-android-0.8.12.aar",
          "size": 3177,
          "sha512": "58b31a50c980fad151f41bca2065a1f9cf0c66f393a912b23f9716ae129e4646166a272a0dd2701a7da897c55d99f2e9497e76557c93e59d76d3284301f57a1b",
          "sha256": "ee034a1eaae0176160eed8944cc9325b06ea9a2d111e71cec33fea4bb9caa56f",
          "sha1": "210046912a2f182e43c71e8a3a9242ae6ca31681",
          "md5": "bf1306ea2c5a72cf07748ae35d9ca2b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3f-android-0.8.12.aar",
          "url": "ble-characteristic-u2b3f-android-0.8.12.aar",
          "size": 3177,
          "sha512": "58b31a50c980fad151f41bca2065a1f9cf0c66f393a912b23f9716ae129e4646166a272a0dd2701a7da897c55d99f2e9497e76557c93e59d76d3284301f57a1b",
          "sha256": "ee034a1eaae0176160eed8944cc9325b06ea9a2d111e71cec33fea4bb9caa56f",
          "sha1": "210046912a2f182e43c71e8a3a9242ae6ca31681",
          "md5": "bf1306ea2c5a72cf07748ae35d9ca2b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3f-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b3f-android-0.8.12-sources.jar",
          "size": 2242,
          "sha512": "63ce7fac71ca3629e0948d8ecc24aa8335c9945fa105245f9cacba082a779f9d4479a216598ab50850999a5d2c204a72a50780cd4a94938e268332c93cbb9838",
          "sha256": "4753dac056ec0bba8eeddb7837512fe95206f9133dec66cf8973ddc090f65910",
          "sha1": "708c520c0e0f16c7ca2a2aeb85d6e4042b0e4b74",
          "md5": "8fb91d6578b76016e7f6e71ea9ef35c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b3f-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b3f-android-0.8.12-javadoc.jar",
          "size": 271228,
          "sha512": "3b14053494d4b734abe7b8d834cbfbde602f27af1a9a1f19e9ba6e588a6e54430542f43a6c53a2311ced26d506e71d43afe98f54d659077081b65f3c2acfb4a7",
          "sha256": "ecd499afd9007e9211edcf8ebe2c24e02d08893b4d690bb728dac156ce87a48d",
          "sha1": "652dd3c9837e880982da8fbcf875f487cdb5cc1d",
          "md5": "879b634f47d023ed743c3bbbb21cba4f"
        }
      ]
    }
  ]
}
