{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad8",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "o6dnfu2lrvfy5pvyifi2ex2xay"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.2.6.jar",
          "url": "ble-characteristic-u2ad8-0.2.6.jar",
          "size": 1935,
          "sha512": "47f72435e698df6b20800f5a384a91ec1c1b36d2817f6da2ac1ecc18c868167b4b6d71f6ffbd82497dc7ab71e8f2f5df195add0b48af5e91a25e7dd7e6d4c6fe",
          "sha256": "37bf9a53906e30f9aa3213341eee94170ecdb6f37054f0f1838bc4e6aaa78b98",
          "sha1": "8e9073cd29d27e8e8665e767f8beda3497e21fa7",
          "md5": "8d106cabcdf90b3b0e183098a539052e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.2.6.jar",
          "url": "ble-characteristic-u2ad8-0.2.6.jar",
          "size": 1935,
          "sha512": "47f72435e698df6b20800f5a384a91ec1c1b36d2817f6da2ac1ecc18c868167b4b6d71f6ffbd82497dc7ab71e8f2f5df195add0b48af5e91a25e7dd7e6d4c6fe",
          "sha256": "37bf9a53906e30f9aa3213341eee94170ecdb6f37054f0f1838bc4e6aaa78b98",
          "sha1": "8e9073cd29d27e8e8665e767f8beda3497e21fa7",
          "md5": "8d106cabcdf90b3b0e183098a539052e"
        }
      ]
    }
  ]
}
