{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-hts-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1d-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a21-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-android-0.4.4.aar",
          "url": "ble-service-hts-android-0.4.4.aar",
          "size": 1184,
          "sha512": "e591b2f42eea43d34aabee3979cc81864548ceb5a59fddfab99dc3620d4464ae70556f1e34a7a81909a04eb82881656b6719b594b5de10c8253d5b415d7e9c61",
          "sha256": "e14b4e561150b8683936d6c2069924a109434713644cf2d7f365efa784e77415",
          "sha1": "7dee0c0b2a4753a95d3985ea7f5cd18dbdf0448d",
          "md5": "84a840cf0d848fab7d4b081ecd2676de"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1d-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a21-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-android-0.4.4.aar",
          "url": "ble-service-hts-android-0.4.4.aar",
          "size": 1184,
          "sha512": "e591b2f42eea43d34aabee3979cc81864548ceb5a59fddfab99dc3620d4464ae70556f1e34a7a81909a04eb82881656b6719b594b5de10c8253d5b415d7e9c61",
          "sha256": "e14b4e561150b8683936d6c2069924a109434713644cf2d7f365efa784e77415",
          "sha1": "7dee0c0b2a4753a95d3985ea7f5cd18dbdf0448d",
          "md5": "84a840cf0d848fab7d4b081ecd2676de"
        }
      ]
    }
  ]
}
