{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a46-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a46-android-0.2.5.aar",
          "url": "ble-characteristic-u2a46-android-0.2.5.aar",
          "size": 3138,
          "sha512": "1872c3ce5e3802fc2b1d21dc5ba4b768d053b032fbf26b98de6d15bc1168d4911f6769c4bb3fb86a7512133d0900ddc1627f731e5faaf25663c06455e70b081e",
          "sha256": "7fc5ddfdd76c74a974cd6a1477451ca69f4e3ec9b001ce067c60353bbcfe8172",
          "sha1": "b6498253626411dae21b9db7333c191c13baf929",
          "md5": "5db86b1494afa63079ba216342725bc5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a46",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a46-android-0.2.5.aar",
          "url": "ble-characteristic-u2a46-android-0.2.5.aar",
          "size": 3138,
          "sha512": "1872c3ce5e3802fc2b1d21dc5ba4b768d053b032fbf26b98de6d15bc1168d4911f6769c4bb3fb86a7512133d0900ddc1627f731e5faaf25663c06455e70b081e",
          "sha256": "7fc5ddfdd76c74a974cd6a1477451ca69f4e3ec9b001ce067c60353bbcfe8172",
          "sha1": "b6498253626411dae21b9db7333c191c13baf929",
          "md5": "5db86b1494afa63079ba216342725bc5"
        }
      ]
    }
  ]
}
