{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b34",
    "version": "0.8.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b34-0.8.14.jar",
          "url": "ble-characteristic-u2b34-0.8.14.jar",
          "size": 3290,
          "sha512": "3ef9da6134cfdbd0eb49b45f74a2b0c31ca717cbcfbbac30574c5193c8e6ebbf9975e11129886c5b2ca7b4b4a835e8e57522f39212bb863c9570363a2a18c78f",
          "sha256": "214d4d489987be1cb817522b0883d2b7bac82687f690f86ee17ad185f2155926",
          "sha1": "05c88c21d3e7591b604fd81bdf4ac1f11f4fa7f7",
          "md5": "ed8332f08d3b238ae5c55936dd916803"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.14"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.14"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b34-0.8.14.jar",
          "url": "ble-characteristic-u2b34-0.8.14.jar",
          "size": 3290,
          "sha512": "3ef9da6134cfdbd0eb49b45f74a2b0c31ca717cbcfbbac30574c5193c8e6ebbf9975e11129886c5b2ca7b4b4a835e8e57522f39212bb863c9570363a2a18c78f",
          "sha256": "214d4d489987be1cb817522b0883d2b7bac82687f690f86ee17ad185f2155926",
          "sha1": "05c88c21d3e7591b604fd81bdf4ac1f11f4fa7f7",
          "md5": "ed8332f08d3b238ae5c55936dd916803"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b34-0.8.14-javadoc.jar",
          "url": "ble-characteristic-u2b34-0.8.14-javadoc.jar",
          "size": 87657,
          "sha512": "c3d5fce6d390925a54b029f845e0399fefddf55068f227c16a131678d17bcc61edd38612445e1b2bfc0eab9564f40c2a39d808844cf62178444e90d180079c5f",
          "sha256": "2d506f7f0dd9a175575ffe8b39fd456983cff1d65b9824f620fff8543e4b7ea4",
          "sha1": "ddf04e8cf51125bf10d1e9ed868ce2bcd7605c53",
          "md5": "625c480468835005f445fdeaeb94fabb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b34-0.8.14-sources.jar",
          "url": "ble-characteristic-u2b34-0.8.14-sources.jar",
          "size": 2888,
          "sha512": "f2a1c5b211218f609ab74ccc23cae17dc5319bbdb96beece4f63dcc5b0bd69aac74538909010cf817ecb51defdf51bb407f4b39630073ce26cda3dbde9f3d990",
          "sha256": "e25b89b47309e80a492eed1d249b8f560b29443c1add6718648c9f073422e4ed",
          "sha1": "05d063fd2b141aa154f9f0298a889a1ac0897115",
          "md5": "a3b87793692790e371987608a1efe449"
        }
      ]
    }
  ]
}
