{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4d-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.11.aar",
          "url": "ble-characteristic-u2a4d-android-0.8.11.aar",
          "size": 3110,
          "sha512": "e6314e6f765a7d1ff0505c3af4dc9c708c8eb20c287de16d255ecac9bc35746f11d964a3dc4ce545083ff5ac506d600e57eac095c8dd3d3548f6dd52e07dc72b",
          "sha256": "37b75b70b406b6c790f593ecf2b73587d0c03df1b7d8189a008d4a46ac1f15ca",
          "sha1": "8f78e8c9aae6e1dff9391ef0a2062301cbcc9b5f",
          "md5": "110fe67c81ad82ae4bcb6717f2b1ef61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4d",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.11.aar",
          "url": "ble-characteristic-u2a4d-android-0.8.11.aar",
          "size": 3110,
          "sha512": "e6314e6f765a7d1ff0505c3af4dc9c708c8eb20c287de16d255ecac9bc35746f11d964a3dc4ce545083ff5ac506d600e57eac095c8dd3d3548f6dd52e07dc72b",
          "sha256": "37b75b70b406b6c790f593ecf2b73587d0c03df1b7d8189a008d4a46ac1f15ca",
          "sha1": "8f78e8c9aae6e1dff9391ef0a2062301cbcc9b5f",
          "md5": "110fe67c81ad82ae4bcb6717f2b1ef61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2a4d-android-0.8.11-sources.jar",
          "size": 2102,
          "sha512": "ae1d0b235f49ab2617bed836c9575c00f81b1e647b622e9f9bedd46b752cceebcf65c54964cdc4a9a2d7de97db9a0f91d7953380d807409a55731bc0fcbb66b6",
          "sha256": "2f6e85bd58b04d05e02e806644e97bfc9b52d4df3a83d5a000f1ec3172e24525",
          "sha1": "8fd6df4154fb32ce08fd8b503ef2ef3169b25e05",
          "md5": "c1536961b421297b7bff66dcd8c541f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a4d-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2a4d-android-0.8.11-javadoc.jar",
          "size": 270444,
          "sha512": "b41c7659eaba4406e58b99d43d616de7a97f529fcb57209e120dbc6287ce0ebd7e2f4a336f3e7d328155c2c2417fe8008c49ae5e8a481a99f116857d4177dbf4",
          "sha256": "0619017b7089246de134f1002c39de3b00cfc22b66c0d46206e7b86b18ab5fa9",
          "sha1": "6700fa10df2a1db4333049dbb81b909e571c0d6d",
          "md5": "100a80a9ebdb87561dab58a46009111a"
        }
      ]
    }
  ]
}
