{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a47",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-0.8.12.jar",
          "url": "ble-characteristic-u2a47-0.8.12.jar",
          "size": 2097,
          "sha512": "e05914e2f1188b589419603dbc7d70940acb90bd15e05fcf4a36bdb45a40dd25f33f9fa8e55b8d3e62cb7ede3548b58eedbd5d89f62d1d55949ea42e0bbdf88a",
          "sha256": "dd33d6c34d6984340d8da0a26bf1db432cde55d7f31a3dfd2fda7cd7499e303c",
          "sha1": "7bc53ed05b697fabeb0f876d99984d3cdfb33fb7",
          "md5": "ba8dd2ee1613e8b4b3c1e4a3a8f7b966"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-0.8.12.jar",
          "url": "ble-characteristic-u2a47-0.8.12.jar",
          "size": 2097,
          "sha512": "e05914e2f1188b589419603dbc7d70940acb90bd15e05fcf4a36bdb45a40dd25f33f9fa8e55b8d3e62cb7ede3548b58eedbd5d89f62d1d55949ea42e0bbdf88a",
          "sha256": "dd33d6c34d6984340d8da0a26bf1db432cde55d7f31a3dfd2fda7cd7499e303c",
          "sha1": "7bc53ed05b697fabeb0f876d99984d3cdfb33fb7",
          "md5": "ba8dd2ee1613e8b4b3c1e4a3a8f7b966"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a47-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a47-0.8.12-javadoc.jar",
          "size": 107820,
          "sha512": "fcdaf29b72f5dac6ddd95815915eed15cd367a15073f0b626d40b5d94c57cfdb8d9b4b68d453cd9736315b75112783df7595c5268691e9551982bf4c9e153693",
          "sha256": "78409eac6e96783d4b595f2ed7e6822138600da029ad9b3d72e48390a31b7cd1",
          "sha1": "89b1f1448222297b23915596e3ca68e8f3412611",
          "md5": "ab9be696e4c4e8e2c99855160cbe203d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a47-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a47-0.8.12-sources.jar",
          "size": 1889,
          "sha512": "9328a83ebd5a755cf2b42ecc0d03a5219bb91f05ad2b1d166824f12914bc14152889534bafb3bc0b9d3b2829b20ce7e986d1667d233f9dcdb9cee3578e4045cd",
          "sha256": "250fb345a7d7755f4aae5671a76bff11c41afe598e12b6ff11bc570990bbc643",
          "sha1": "18079615197f45011a6ad00b7491666519036214",
          "md5": "926bf1c1665a715b750dc9e428e8ad60"
        }
      ]
    }
  ]
}
