{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b87-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b87",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b87-android-0.4.5.aar",
          "url": "ble-characteristic-u2b87-android-0.4.5.aar",
          "size": 3042,
          "sha512": "2a175723b68f9e2a77d560fc93c64903c075fed3a8fdc53bc52c1d75b9d5f77d372680f041a0d760f05974067d43691548c13cd99fd6ea7e55bc7ec97b48c25e",
          "sha256": "43a39a1a7f53ba1b99bdcb36c261086b2f3689870be00dfc212abf3d8e56d2a5",
          "sha1": "38d4167dd2fb3a84a150371a427174a2660ad369",
          "md5": "64ce692a9bf901faedfac4608529a873"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b87",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b87-android-0.4.5.aar",
          "url": "ble-characteristic-u2b87-android-0.4.5.aar",
          "size": 3042,
          "sha512": "2a175723b68f9e2a77d560fc93c64903c075fed3a8fdc53bc52c1d75b9d5f77d372680f041a0d760f05974067d43691548c13cd99fd6ea7e55bc7ec97b48c25e",
          "sha256": "43a39a1a7f53ba1b99bdcb36c261086b2f3689870be00dfc212abf3d8e56d2a5",
          "sha1": "38d4167dd2fb3a84a150371a427174a2660ad369",
          "md5": "64ce692a9bf901faedfac4608529a873"
        }
      ]
    }
  ]
}
