{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab0-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.2.4.aar",
          "url": "ble-characteristic-u2ab0-android-0.2.4.aar",
          "size": 3113,
          "sha512": "556a57fff2fe4199ecdfa0f3bfd146e92bb51fd1541252911fd8135969bd8e9fc3cf3e59911134e7f2f4927e6e07ed94230bc30abe8d9c84511882e2a6a5adda",
          "sha256": "317ca77bd2c21e720b4a989c64b8f4c6af0b4acee926f97e64e72ecb33af43ff",
          "sha1": "5cd75806952241edccd1963035f1a79751ce634e",
          "md5": "65420080959ae09b2fd6d5a1ad9f4c40"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.2.4.aar",
          "url": "ble-characteristic-u2ab0-android-0.2.4.aar",
          "size": 3113,
          "sha512": "556a57fff2fe4199ecdfa0f3bfd146e92bb51fd1541252911fd8135969bd8e9fc3cf3e59911134e7f2f4927e6e07ed94230bc30abe8d9c84511882e2a6a5adda",
          "sha256": "317ca77bd2c21e720b4a989c64b8f4c6af0b4acee926f97e64e72ecb33af43ff",
          "sha1": "5cd75806952241edccd1963035f1a79751ce634e",
          "md5": "65420080959ae09b2fd6d5a1ad9f4c40"
        }
      ]
    }
  ]
}
