{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a28-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a28",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-android-0.2.2.aar",
          "url": "ble-characteristic-u2a28-android-0.2.2.aar",
          "size": 2951,
          "sha512": "9b23c05fb7887dce820e7f9a81c698b82d64b6965dba7c08563f592ee33a2e065b5df6ca1a6cdba0904c6411c8d26e23b0d4856c7ddf26b0afcc7a954db245d5",
          "sha256": "833a1750c67c961b4cd29bc432dbf835d809b70f2d40e9510b635008bacfabda",
          "sha1": "b1ad17e61d6d61439df427687e7dd85012fa5655",
          "md5": "bcd40f73e999830cdc16ebd49ecc2657"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a28",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a28-android-0.2.2.aar",
          "url": "ble-characteristic-u2a28-android-0.2.2.aar",
          "size": 2951,
          "sha512": "9b23c05fb7887dce820e7f9a81c698b82d64b6965dba7c08563f592ee33a2e065b5df6ca1a6cdba0904c6411c8d26e23b0d4856c7ddf26b0afcc7a954db245d5",
          "sha256": "833a1750c67c961b4cd29bc432dbf835d809b70f2d40e9510b635008bacfabda",
          "sha1": "b1ad17e61d6d61439df427687e7dd85012fa5655",
          "md5": "bcd40f73e999830cdc16ebd49ecc2657"
        }
      ]
    }
  ]
}
