{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b7a",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7a-0.8.12.jar",
          "url": "ble-characteristic-u2b7a-0.8.12.jar",
          "size": 1458,
          "sha512": "7ae6c0e704af12b68bf1f179a8ce444fb229532d0b93b24dc65bbfa5a55ae8d2238ef54b16ad4e8456ad479274b7052fa66bc6b23eaa6e7b062d705ec582de34",
          "sha256": "45b97dd0d6c525e3976178da6765d0f5edff14aa0d101969a4641d91f9dd2d35",
          "sha1": "11e558107a3f9997e9fc7c727a4c333fd79e62c9",
          "md5": "034481a157f2bd74c0057f7188debceb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7a-0.8.12.jar",
          "url": "ble-characteristic-u2b7a-0.8.12.jar",
          "size": 1458,
          "sha512": "7ae6c0e704af12b68bf1f179a8ce444fb229532d0b93b24dc65bbfa5a55ae8d2238ef54b16ad4e8456ad479274b7052fa66bc6b23eaa6e7b062d705ec582de34",
          "sha256": "45b97dd0d6c525e3976178da6765d0f5edff14aa0d101969a4641d91f9dd2d35",
          "sha1": "11e558107a3f9997e9fc7c727a4c333fd79e62c9",
          "md5": "034481a157f2bd74c0057f7188debceb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7a-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b7a-0.8.12-javadoc.jar",
          "size": 107173,
          "sha512": "49b1667620cbfcaf8925046742ad00c1050e628cae64604622d5bf2a173145c2ef79ec4a5a5e672a7dfbfe290cd5b61d215d1f02c1c72be6b3673d9a3721bf82",
          "sha256": "831a05c8f5e4a25f260ee504dc6a8656a7cdb42ea1bb5005c1e33b72d094e069",
          "sha1": "7adb232e3f80db42ae841d96915a4b473eaebac2",
          "md5": "20b5f43c49b0f9719bb56374ca4f0cc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7a-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b7a-0.8.12-sources.jar",
          "size": 1448,
          "sha512": "d3442e82553faf359286cb8274cd400faf8dacb7c2674ce18ebaa5b49f593ac6c4d6103fc62a92acb4abbc76f4cc014b500c03ea6717591c387cbc64d6c198c3",
          "sha256": "28762a6a6104e9ef901dc7d6f7843d348057ebbfff62f2f52a7da7ec90776912",
          "sha1": "27eff8755010eb21458f828642e7ea68ba17da08",
          "md5": "f1eb70d3541f5a70bf8110111085c398"
        }
      ]
    }
  ]
}
