{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a16",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "zntzl6h5ifdqnivyseqzz436ba"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.2.0.jar",
          "url": "ble-characteristic-u2a16-0.2.0.jar",
          "size": 1924,
          "sha512": "b215b6ef747b4a53910f92414f5e782cba21ffd0a7010456fe0ec05ff765866767d6102ff6184ce590780937093c25468fb2bf5d95e77f2928b3fbb0512bec3c",
          "sha256": "3b52d6246ded1803866a7dfc19be682420c5bae1408c37a3d06998a77394fe81",
          "sha1": "e7a8cade947025cde86bf5cc2e4e677f93ad0c43",
          "md5": "eb24c53cf5059fa32f1ac57986f26242"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a16-0.2.0.jar",
          "url": "ble-characteristic-u2a16-0.2.0.jar",
          "size": 1924,
          "sha512": "b215b6ef747b4a53910f92414f5e782cba21ffd0a7010456fe0ec05ff765866767d6102ff6184ce590780937093c25468fb2bf5d95e77f2928b3fbb0512bec3c",
          "sha256": "3b52d6246ded1803866a7dfc19be682420c5bae1408c37a3d06998a77394fe81",
          "sha1": "e7a8cade947025cde86bf5cc2e4e677f93ad0c43",
          "md5": "eb24c53cf5059fa32f1ac57986f26242"
        }
      ]
    }
  ]
}
