{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a47-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "olxdj2q3sjc6parr4kum67jyt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.4.aar",
          "url": "ble-characteristic-u2a47-android-0.2.4.aar",
          "size": 3182,
          "sha512": "68f57e04c917db8c2c9793f1bdbd35a621a78db6b83eccd594312ab7fcaa2e77343009a90041090e2ca25db72e8c0e4b7a5b22769adbf0ada7614937aca29d2e",
          "sha256": "c780372955d170411540d9cb8298f1b8c9d3c659e220e8d8c6eb00bd3138e21b",
          "sha1": "6c42b08cfaa139f89cef01bd6d32f4c7e1ff4e54",
          "md5": "513d9f0d30b09d1ff2d25298f275e529"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.4.aar",
          "url": "ble-characteristic-u2a47-android-0.2.4.aar",
          "size": 3182,
          "sha512": "68f57e04c917db8c2c9793f1bdbd35a621a78db6b83eccd594312ab7fcaa2e77343009a90041090e2ca25db72e8c0e4b7a5b22769adbf0ada7614937aca29d2e",
          "sha256": "c780372955d170411540d9cb8298f1b8c9d3c659e220e8d8c6eb00bd3138e21b",
          "sha1": "6c42b08cfaa139f89cef01bd6d32f4c7e1ff4e54",
          "md5": "513d9f0d30b09d1ff2d25298f275e529"
        }
      ]
    }
  ]
}
