{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a47-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.4.aar",
          "url": "ble-characteristic-u2a47-android-0.2.4.aar",
          "size": 3180,
          "sha512": "07f61ed51cdf2080b95c7422595db434a76a7957574aca804824b89daa6c7ffe4636a5f9e36bce8c5ab27c84b05ae10c320a5a0d018e0afbb1a9decdcb61da89",
          "sha256": "b0b098fb6b5f68e92ad8099a900e2dd77ab6c25c536591be8951a68ebd4f0fc2",
          "sha1": "b399878e166a3c436e90bbd0f191717209a63542",
          "md5": "ec75622e2f0236a5edc2e8c4ee8f8798"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.4.aar",
          "url": "ble-characteristic-u2a47-android-0.2.4.aar",
          "size": 3180,
          "sha512": "07f61ed51cdf2080b95c7422595db434a76a7957574aca804824b89daa6c7ffe4636a5f9e36bce8c5ab27c84b05ae10c320a5a0d018e0afbb1a9decdcb61da89",
          "sha256": "b0b098fb6b5f68e92ad8099a900e2dd77ab6c25c536591be8951a68ebd4f0fc2",
          "sha1": "b399878e166a3c436e90bbd0f191717209a63542",
          "md5": "ec75622e2f0236a5edc2e8c4ee8f8798"
        }
      ]
    }
  ]
}
