{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af8-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af8",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af8-android-0.8.8.aar",
          "url": "ble-characteristic-u2af8-android-0.8.8.aar",
          "size": 3201,
          "sha512": "baae7b3353c0dc71e28a0c0aefdfd7a2c1c9a24c9608e96f3c1d0d2899894433469b041a108b0d06c103d302174e970729c03b19f7327de8c9604134817c0aba",
          "sha256": "66327b2222b1585e546a06dbf939ece8cbbf9770b9bd9118384a850ac840e744",
          "sha1": "6f8448879d72123fac69fdb75b2e2814b7ce84c5",
          "md5": "c2f58c0d367de6f7a6f29e94afaae3ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af8",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af8-android-0.8.8.aar",
          "url": "ble-characteristic-u2af8-android-0.8.8.aar",
          "size": 3201,
          "sha512": "baae7b3353c0dc71e28a0c0aefdfd7a2c1c9a24c9608e96f3c1d0d2899894433469b041a108b0d06c103d302174e970729c03b19f7327de8c9604134817c0aba",
          "sha256": "66327b2222b1585e546a06dbf939ece8cbbf9770b9bd9118384a850ac840e744",
          "sha1": "6f8448879d72123fac69fdb75b2e2814b7ce84c5",
          "md5": "c2f58c0d367de6f7a6f29e94afaae3ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af8-android-0.8.8-sources.jar",
          "url": "ble-characteristic-u2af8-android-0.8.8-sources.jar",
          "size": 2162,
          "sha512": "b11c0ac9b9b7e8973d53ae92adbd597e6a7ffcbea0bfdd38803ab611a866873acc3fc66cdcaee8fe2f19055f5705419472882fe79723c17293659e9260856b37",
          "sha256": "4d54b84f17416e6d31142ad8c6ba96fa4b4dfdc5406f8aaba000985745b44b5f",
          "sha1": "19a61bfb17f2b7331c5634935bf06a0beca6b60b",
          "md5": "485d2741c3c740ec9742956956e05376"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af8-android-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2af8-android-0.8.8-javadoc.jar",
          "size": 270606,
          "sha512": "243089959eb0e964066ead356ab97f4ab1739a04873cf72b090474bc1b2d85f551614b0a1fa44f1ed92328922e76001405f61440a0995570d018fe264254a5f2",
          "sha256": "8d400baba52de42ccedd72473847a58305eb1fa540743dc76a687c7f4a4957e4",
          "sha1": "1cc65a96cf0c1c9444c4e1489103294a5bcc5796",
          "md5": "33596f4424e060317499c90fee49b8d6"
        }
      ]
    }
  ]
}
