{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af4",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af4-0.4.4.jar",
          "url": "ble-characteristic-u2af4-0.4.4.jar",
          "size": 2029,
          "sha512": "cc4c26d81a3f2fdc5e32e5d8dfac986a8877bdb932c482ab437abe246c1245c2fa6ee279d65c022a3f71b0ac6fd5d620fb2fee0e82a42e27398f352ce00ea88a",
          "sha256": "22644dbf707fe0f6ced2f0a016632d818f5a8035a4733476e29211c7f4227c10",
          "sha1": "b5aad37c4624d4147f14e5f802fbca8224c4c113",
          "md5": "c0d1f611f46c2bfc5487a515724756a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af4-0.4.4.jar",
          "url": "ble-characteristic-u2af4-0.4.4.jar",
          "size": 2029,
          "sha512": "cc4c26d81a3f2fdc5e32e5d8dfac986a8877bdb932c482ab437abe246c1245c2fa6ee279d65c022a3f71b0ac6fd5d620fb2fee0e82a42e27398f352ce00ea88a",
          "sha256": "22644dbf707fe0f6ced2f0a016632d818f5a8035a4733476e29211c7f4227c10",
          "sha1": "b5aad37c4624d4147f14e5f802fbca8224c4c113",
          "md5": "c0d1f611f46c2bfc5487a515724756a3"
        }
      ]
    }
  ]
}
