{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-fmp-central-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "imnihwqv65eu7lrkazou3zhih4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-fmp-central-android-0.1.3.aar",
          "url": "ble-profile-fmp-central-android-0.1.3.aar",
          "size": 4479,
          "sha512": "8a4bad710f74750d8533591094809191d6dfb6a056f8918eeada496ba24cccdd54b9c3cf40d0ec4d181d43299ba84b73913412831d4c942a5e5cbb5c199ac832",
          "sha256": "3392de3fe4248589a4ead5fd7fd5795e41d88dac4cac1647bfe843acb0e70ab1",
          "sha1": "9ee4de7ccc3de50854c4c9bd00b5f079ed7717d4",
          "md5": "07a174364ea74aa737941f5636e772f6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-central-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-fmp-central-android-0.1.3.aar",
          "url": "ble-profile-fmp-central-android-0.1.3.aar",
          "size": 4479,
          "sha512": "8a4bad710f74750d8533591094809191d6dfb6a056f8918eeada496ba24cccdd54b9c3cf40d0ec4d181d43299ba84b73913412831d4c942a5e5cbb5c199ac832",
          "sha256": "3392de3fe4248589a4ead5fd7fd5795e41d88dac4cac1647bfe843acb0e70ab1",
          "sha1": "9ee4de7ccc3de50854c4c9bd00b5f079ed7717d4",
          "md5": "07a174364ea74aa737941f5636e772f6"
        }
      ]
    }
  ]
}
