{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad9",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad9-0.8.3.jar",
          "url": "ble-characteristic-u2ad9-0.8.3.jar",
          "size": 6115,
          "sha512": "c8a55a0fba417ebb5e75ca7e558db5a42f31ce2e0e564abeb74cb8d36b7b15b8e8551df604154c9fad5b1362c27d44db91e16cb079b0e15b324847f60ad3aca8",
          "sha256": "6ede03f498cec1afc8ed0535415abddd32823b36ecbee3c1be29be929affd4cc",
          "sha1": "5482205a1ce79f691f1ae293ddebb2ad8ee40954",
          "md5": "51f4b47c84ddf3f9ce78eab6dceb6a52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad9-0.8.3.jar",
          "url": "ble-characteristic-u2ad9-0.8.3.jar",
          "size": 6115,
          "sha512": "c8a55a0fba417ebb5e75ca7e558db5a42f31ce2e0e564abeb74cb8d36b7b15b8e8551df604154c9fad5b1362c27d44db91e16cb079b0e15b324847f60ad3aca8",
          "sha256": "6ede03f498cec1afc8ed0535415abddd32823b36ecbee3c1be29be929affd4cc",
          "sha1": "5482205a1ce79f691f1ae293ddebb2ad8ee40954",
          "md5": "51f4b47c84ddf3f9ce78eab6dceb6a52"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad9-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2ad9-0.8.3-javadoc.jar",
          "size": 122309,
          "sha512": "fbd83b05be1b038c5be94340532f9f7e2366b3ec9b67f4b60ca9fb29b9718f72ebd3dc79143cb2bc22f219ec3b1767031d604d87c013ffc3e61f04710ec31fcf",
          "sha256": "92297abc605c8ecd297d4506b677b49cf619bf31f7ed5b98318e8530a82451e1",
          "sha1": "1b80a524101bcf15ede2aa3a5ae047d5b78c9793",
          "md5": "580a1a3718e21bcff9b34387b0df7bd9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad9-0.8.3-sources.jar",
          "url": "ble-characteristic-u2ad9-0.8.3-sources.jar",
          "size": 5198,
          "sha512": "6794300ee5e90f8459e9c322afa31f906e301386cb081c6c458badab62a5e477e35ca7f148f7fc52828aa974ccd568b5308bade3cf8d1a1530ec77b8aed3f92e",
          "sha256": "1027e96b9b7a4a6aee28f394d68a96d3d5a7bbd9b09f6ab44c3c0b3f8cdad2b7",
          "sha1": "015f71c9ae60109f48c27d896ad73159db025af2",
          "md5": "a3ea7dde00068b23b4df917a10c7e483"
        }
      ]
    }
  ]
}
