{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b45-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b45",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b45-android-0.8.7.aar",
          "url": "ble-characteristic-u2b45-android-0.8.7.aar",
          "size": 3114,
          "sha512": "aa6867e31ec92f7e21a01fe06dda2a38d9e14a2f401d39bc3125c1e10217482b991920bdba15bf32951a96358c782043fc801aa645a681e29fb553b893de3bcf",
          "sha256": "3a5de65ea419c81a696542adf9b197cde1a3593e5033dc0a581761de01ffa9f6",
          "sha1": "a4c6504748dffb13480a0fa81b678c80f1d95ccd",
          "md5": "0eea020266266bd569933117365e1482"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b45",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b45-android-0.8.7.aar",
          "url": "ble-characteristic-u2b45-android-0.8.7.aar",
          "size": 3114,
          "sha512": "aa6867e31ec92f7e21a01fe06dda2a38d9e14a2f401d39bc3125c1e10217482b991920bdba15bf32951a96358c782043fc801aa645a681e29fb553b893de3bcf",
          "sha256": "3a5de65ea419c81a696542adf9b197cde1a3593e5033dc0a581761de01ffa9f6",
          "sha1": "a4c6504748dffb13480a0fa81b678c80f1d95ccd",
          "md5": "0eea020266266bd569933117365e1482"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b45-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b45-android-0.8.7-sources.jar",
          "size": 2115,
          "sha512": "c31a2e7fdfc715fa24293f70642d7f594a01c52e64c8b58fdc8f2942a1bbbd3c5b9bb294ff0c76722b6ee3fec14930317223339045a57d8f6d1722d6a86cb6b0",
          "sha256": "12effeb36662b6bd33efbaa7d2f1b5eb53285991304e5b9675e1b98f858bd65b",
          "sha1": "0052774b1d66b68df89c1e1e75d334a128b5294b",
          "md5": "bed41c989c19d70632805c6074fe3d54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b45-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b45-android-0.8.7-javadoc.jar",
          "size": 270437,
          "sha512": "30527a89ad09e55909700f34480ea2dc3795bd8977b73695e002e8d6bdbb303360a97cfc3043ae2a4a9aa895708c4253bbafd1a84d4c301e54f0dc777d0fa47b",
          "sha256": "8ee6dd0b74a1c7e26dc91daa0de4376bc50ca0e8672fe0068b608c6144ab1609",
          "sha1": "d6b0aacb3912c39e9cbaf119f29055e87ca91f23",
          "md5": "225433565539194e13dc326e05a11cf7"
        }
      ]
    }
  ]
}
