{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae6-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae6",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae6-android-0.4.6.aar",
          "url": "ble-characteristic-u2ae6-android-0.4.6.aar",
          "size": 3135,
          "sha512": "e8af8be7cd4956c637d65316079a14b3351673ec4b6d53cb35273fb2945d033d18bdd163ebda06f643a934bde6fc59d8cad6d8072eb0351e2b2ecd9101eebf07",
          "sha256": "7e7c9db8abead028c629fbc8cb6ab11e20a905577780d5452c30f97ac97f52f7",
          "sha1": "a6bd1d3a27b147f92af0d3fff1c1fa6867589836",
          "md5": "56f3b71bed3377204034a160b503df91"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae6",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae6-android-0.4.6.aar",
          "url": "ble-characteristic-u2ae6-android-0.4.6.aar",
          "size": 3135,
          "sha512": "e8af8be7cd4956c637d65316079a14b3351673ec4b6d53cb35273fb2945d033d18bdd163ebda06f643a934bde6fc59d8cad6d8072eb0351e2b2ecd9101eebf07",
          "sha256": "7e7c9db8abead028c629fbc8cb6ab11e20a905577780d5452c30f97ac97f52f7",
          "sha1": "a6bd1d3a27b147f92af0d3fff1c1fa6867589836",
          "md5": "56f3b71bed3377204034a160b503df91"
        }
      ]
    }
  ]
}
