{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bfc",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bfc-0.8.13.jar",
          "url": "ble-characteristic-u2bfc-0.8.13.jar",
          "size": 1469,
          "sha512": "0bc337f429ac5a077f5baab0889aa29c704507e01d4566af88dc17acfb5f7a2bf07dc59d6fbac831dd3f8aa991256899d6bb37ea7781bb79e08e814ffc36ee10",
          "sha256": "4cd6ec6b2d24374895e407970d9edf27f01f9eaa21bf5e4fc4f24dcd63fa0ad0",
          "sha1": "984265e39c2d89ce84dd45e10953e2a449308a99",
          "md5": "aeed15155bfd5dffebd94c70da2cc337"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bfc-0.8.13.jar",
          "url": "ble-characteristic-u2bfc-0.8.13.jar",
          "size": 1469,
          "sha512": "0bc337f429ac5a077f5baab0889aa29c704507e01d4566af88dc17acfb5f7a2bf07dc59d6fbac831dd3f8aa991256899d6bb37ea7781bb79e08e814ffc36ee10",
          "sha256": "4cd6ec6b2d24374895e407970d9edf27f01f9eaa21bf5e4fc4f24dcd63fa0ad0",
          "sha1": "984265e39c2d89ce84dd45e10953e2a449308a99",
          "md5": "aeed15155bfd5dffebd94c70da2cc337"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bfc-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2bfc-0.8.13-javadoc.jar",
          "size": 86030,
          "sha512": "b83051670c18c8a38be241fa07b3602c559eaaae41556a9fecf007b6cb248daf215ef07d3cf826eb5ca1a090bfa1fbc787d283d6333673c7cfe531165f5075f5",
          "sha256": "fe2240207eac6a4444e607a70654951261a30d85f585fb3673c4c6629f653c35",
          "sha1": "cb906f219abc47aa5b89a65ba203ab60cb2e696d",
          "md5": "09e0a3c1924d402fa97e210e1a1a8178"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bfc-0.8.13-sources.jar",
          "url": "ble-characteristic-u2bfc-0.8.13-sources.jar",
          "size": 1450,
          "sha512": "3f2f240ead836aa00d001a1e50cc375d183ba9391cebcffd12d302254f18c913123b6bf38dc61875a59becbe881b7073628012b1705ec8310fe6fc3feba1d1f1",
          "sha256": "f4460c2d6b8ff6d5c96cd9f16f1c1931e64ed1e93a206f59796b346fd6093ddb",
          "sha1": "a76d446f97355176edd6316eb25a5ade9212ad11",
          "md5": "bdc6250b43a58efd69b8a74eac799d01"
        }
      ]
    }
  ]
}
