{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad0",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad0-0.8.12.jar",
          "url": "ble-characteristic-u2ad0-0.8.12.jar",
          "size": 5947,
          "sha512": "0b37b37135930b6c3df420f55ed12dc81a2cbe417db723178baf8ade94a603a68e31cd9527429361b44202df7a5635379ec4d0fa4d4b97876acb5ecb2b18be35",
          "sha256": "bec63502b9be41efd0b2728b1ef08fbb4df30eb8bb3774d388368147b57611f2",
          "sha1": "e34ea0e57ca322598ef4e6d5bb89ec30513e557f",
          "md5": "010396459b3b2dea389970436b2b113d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad0-0.8.12.jar",
          "url": "ble-characteristic-u2ad0-0.8.12.jar",
          "size": 5947,
          "sha512": "0b37b37135930b6c3df420f55ed12dc81a2cbe417db723178baf8ade94a603a68e31cd9527429361b44202df7a5635379ec4d0fa4d4b97876acb5ecb2b18be35",
          "sha256": "bec63502b9be41efd0b2728b1ef08fbb4df30eb8bb3774d388368147b57611f2",
          "sha1": "e34ea0e57ca322598ef4e6d5bb89ec30513e557f",
          "md5": "010396459b3b2dea389970436b2b113d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad0-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2ad0-0.8.12-javadoc.jar",
          "size": 91519,
          "sha512": "6c066c439d3b714435fabdec0e1b8ec6c382b3be3f1e5629924b7b05947af03afdbc3351e24c1736b83936714ebfdd9faf6bcc28c786e08c73ed49b95937ba7c",
          "sha256": "94668e516091ecd136ccb3529047c60e0ff864df76731083ba83641900f8cf66",
          "sha1": "4bdd402b9c331497dfb4e636fbffb094f2c01432",
          "md5": "9955aa96ddc23f6061489139d6b7f945"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad0-0.8.12-sources.jar",
          "url": "ble-characteristic-u2ad0-0.8.12-sources.jar",
          "size": 4557,
          "sha512": "bf70784e18f5cffb26776530826774c78f8285de15ca443ba8a5211fe5fbc5a6029b7f7480fe151efbe7cbd86a8cac3a72be7aaf5b9899a49b78e3c784aff494",
          "sha256": "3b3bdb21f1894b76a379fe6e411adf61b85af08f89948f683ae5491437eedcfc",
          "sha1": "10b2f15dcb12a17a2ed7d63f59d932c268c68339",
          "md5": "c08deedae2d0e34527466692f99ce98c"
        }
      ]
    }
  ]
}
