{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-rtus-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-rtus-android-0.8.9.aar",
          "url": "ble-service-central-rtus-android-0.8.9.aar",
          "size": 3814,
          "sha512": "4f8f72d0ee840d73d054d9740cc16433290829272b2deb96ed15bbfdfecd33b445f64094e21a68d14b51a48dd07de74b7a2cc51a9e3a35577441507e0b3fefd8",
          "sha256": "5b51f2419fec92d51225265f9841116a4ec8ea3f5f85f5291b64c0823e30022e",
          "sha1": "0501136c07a35f830e9501be281f3cb54e38c810",
          "md5": "6f666298f0e3d41f0b7b4118ef712067"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-rtus-android-0.8.9.aar",
          "url": "ble-service-central-rtus-android-0.8.9.aar",
          "size": 3814,
          "sha512": "4f8f72d0ee840d73d054d9740cc16433290829272b2deb96ed15bbfdfecd33b445f64094e21a68d14b51a48dd07de74b7a2cc51a9e3a35577441507e0b3fefd8",
          "sha256": "5b51f2419fec92d51225265f9841116a4ec8ea3f5f85f5291b64c0823e30022e",
          "sha1": "0501136c07a35f830e9501be281f3cb54e38c810",
          "md5": "6f666298f0e3d41f0b7b4118ef712067"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-rtus-android-0.8.9-sources.jar",
          "url": "ble-service-central-rtus-android-0.8.9-sources.jar",
          "size": 3930,
          "sha512": "205211b3dd8163019d01d298d7a9a8589f7080e68c0ae66e07cf1e3d64fcd12ed90309674997b1d8522d7c495ff7b5fbfd2a8606e983983e5dc923cacc54e048",
          "sha256": "8acac16024f4bdefd818992231e37ed824536f28c505f7225034faafc0d69f06",
          "sha1": "62e02e6f91413dc818056cb195e18bcafd0e9111",
          "md5": "e72dd15cb4c1830ed2f46b94bbb8f0af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-service-central-rtus-android-0.8.9-javadoc.jar",
          "url": "ble-service-central-rtus-android-0.8.9-javadoc.jar",
          "size": 279939,
          "sha512": "56ff7922142cb09467d65c573915787e1c221590c7d3f6a6da3df2480f65fd06168c532ff73c5bdbf7c373857db26dfefbee16e2f894d1f1a14282db3f81e41a",
          "sha256": "a84fe8a68b172aab85406182f07db78b7e7b5f34b60454639a87df97413de4dd",
          "sha1": "dbcb1ae6720206ffb5ee00063449839084887971",
          "md5": "c710db7fe3db27b0eb2a09634514cd71"
        }
      ]
    }
  ]
}
