{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb7",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb7-0.8.7.jar",
          "url": "ble-characteristic-u2bb7-0.8.7.jar",
          "size": 1469,
          "sha512": "2d0fb1fce5455a89532a23dec61434caa76b5923e4ada5c89bb70398065ed0defa2ad413c714533bf8c1b46cbfa85bf9ed599d009e8c287f37f7ec5e53b4ebe4",
          "sha256": "b84ca9feebafaf7fd765579198dbd391717c6ea4c28933ea5635f96eb71a24a2",
          "sha1": "45f6ecea8314ae9122cfda3d0f10e9f9bd539043",
          "md5": "7ffd5861c1444df385676d13b7da6893"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb7-0.8.7.jar",
          "url": "ble-characteristic-u2bb7-0.8.7.jar",
          "size": 1469,
          "sha512": "2d0fb1fce5455a89532a23dec61434caa76b5923e4ada5c89bb70398065ed0defa2ad413c714533bf8c1b46cbfa85bf9ed599d009e8c287f37f7ec5e53b4ebe4",
          "sha256": "b84ca9feebafaf7fd765579198dbd391717c6ea4c28933ea5635f96eb71a24a2",
          "sha1": "45f6ecea8314ae9122cfda3d0f10e9f9bd539043",
          "md5": "7ffd5861c1444df385676d13b7da6893"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb7-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bb7-0.8.7-javadoc.jar",
          "size": 107211,
          "sha512": "73dd6895f8c02387fda5aea44f15d8071f4eb2c8ffd9607da454d4a39472ed0820b5ca22b8b46f12befb840ddfec1e593ba40f7e8222219c1b28334c05a29b87",
          "sha256": "2e97af1488ccb33a85c662edd1f1135593ad7cc486c59f2c068ce3689bff6ec1",
          "sha1": "87751c6884504ff2532ce9c879f5040d7b7709c6",
          "md5": "01ed0f121c6a8da98dc891ec45510362"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb7-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bb7-0.8.7-sources.jar",
          "size": 1461,
          "sha512": "beef53ddae03626a375c2c2fe25b133eb0db8fa91ee1458acab706d510a1a852d04b9f3cc72b97eb27f0208061d719f3b45d34bff94b1f578e7076f18ce77c43",
          "sha256": "ab08486ac2ca2e4ff00bcb85d23b16fee6c8b3b2b5b46dd64b9050a6bcb0bdc5",
          "sha1": "0f8d4c512392a8eec3b488dc64b515374377bc62",
          "md5": "5942e637d31f0c96877998dc48024288"
        }
      ]
    }
  ]
}
