{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5d-android",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fxrmxjl6szatjaovsgygwi5l4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.2.4.aar",
          "url": "ble-characteristic-u2a5d-android-0.2.4.aar",
          "size": 3080,
          "sha512": "cf7c74a7a185fa8afba957760add2f56cd7201bad9fb41665bcf00db9909552e8853ca857c0351c28509e5a1fddf265fe6e0a570970bf81e12cbeab03ffb8aaa",
          "sha256": "aaa072ef4b12c10d497d5cfa7f3f8d6becba14119d3ec2762a8de55345313c72",
          "sha1": "949d709dac34fc0e49d4ece90a49f6607cf60681",
          "md5": "dddf2ec9275ebc62ba4649694f7f40a9"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.2.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.2.4.aar",
          "url": "ble-characteristic-u2a5d-android-0.2.4.aar",
          "size": 3080,
          "sha512": "cf7c74a7a185fa8afba957760add2f56cd7201bad9fb41665bcf00db9909552e8853ca857c0351c28509e5a1fddf265fe6e0a570970bf81e12cbeab03ffb8aaa",
          "sha256": "aaa072ef4b12c10d497d5cfa7f3f8d6becba14119d3ec2762a8de55345313c72",
          "sha1": "949d709dac34fc0e49d4ece90a49f6607cf60681",
          "md5": "dddf2ec9275ebc62ba4649694f7f40a9"
        }
      ]
    }
  ]
}
