{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-hts-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1d-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a21-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-android-0.8.6.aar",
          "url": "ble-service-hts-android-0.8.6.aar",
          "size": 1223,
          "sha512": "9d1d8b03f9be98ce254cf2fa02ab6bbac31d9414a7c8cd22211edce5a36a2382753b57f8809927a3d5072b4c9d4766d772ea073a7be07d71e758853eb33d0762",
          "sha256": "4f7b0c8669f3daa792ddc0531a00d8c90019133c7f51aa0deebac34a4340c02a",
          "sha1": "90f733e77d632a079e7a2069fdfefe7b75c32399",
          "md5": "79ca0259af48a2dfe535ce35c80435cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2906-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1c-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1d-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a21-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-hts-android-0.8.6.aar",
          "url": "ble-service-hts-android-0.8.6.aar",
          "size": 1223,
          "sha512": "9d1d8b03f9be98ce254cf2fa02ab6bbac31d9414a7c8cd22211edce5a36a2382753b57f8809927a3d5072b4c9d4766d772ea073a7be07d71e758853eb33d0762",
          "sha256": "4f7b0c8669f3daa792ddc0531a00d8c90019133c7f51aa0deebac34a4340c02a",
          "sha1": "90f733e77d632a079e7a2069fdfefe7b75c32399",
          "md5": "79ca0259af48a2dfe535ce35c80435cf"
        }
      ]
    }
  ]
}
