{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4d-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4d-android-0.8.6.aar",
          "url": "ble-characteristic-u2b4d-android-0.8.6.aar",
          "size": 3273,
          "sha512": "c33323db30b265ce36833dad70fb40094b797a8ce8881d7339412c7932b2be06fd6c933d2ad68d0f770d6c25daf7e00ac92bc6983da368734c0a1decd6b2191e",
          "sha256": "bb5936babea54b6062d8ce54a98c446bee19d4be99e552316593a9db9902764c",
          "sha1": "813d42131999fc9258897c1bc45ecc7132c68546",
          "md5": "282a6e6a29cc6e39f2b0cf69fe22eedc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4d-android-0.8.6.aar",
          "url": "ble-characteristic-u2b4d-android-0.8.6.aar",
          "size": 3273,
          "sha512": "c33323db30b265ce36833dad70fb40094b797a8ce8881d7339412c7932b2be06fd6c933d2ad68d0f770d6c25daf7e00ac92bc6983da368734c0a1decd6b2191e",
          "sha256": "bb5936babea54b6062d8ce54a98c446bee19d4be99e552316593a9db9902764c",
          "sha1": "813d42131999fc9258897c1bc45ecc7132c68546",
          "md5": "282a6e6a29cc6e39f2b0cf69fe22eedc"
        }
      ]
    }
  ]
}
