{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a22-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a22",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a22-android-0.8.7.aar",
          "url": "ble-characteristic-u2a22-android-0.8.7.aar",
          "size": 3190,
          "sha512": "2595cccfc4427c169b6239dc33247422a78cb7e8a91ef6c2b9d61b7e61614f62cbd633c793cf3748cee9303c81bcae6dfbdb633bcd38bfdda14e37dba2bc3a9c",
          "sha256": "f33ce42ae68b3fe2967ccbb56510e6652dd7d05360d26e881a49e5e19aba2427",
          "sha1": "47f4f1d8aea9d524051f901b69062f2ac92c9cd1",
          "md5": "ea4559dcb2a01619211f1af5a96d75da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a22",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a22-android-0.8.7.aar",
          "url": "ble-characteristic-u2a22-android-0.8.7.aar",
          "size": 3190,
          "sha512": "2595cccfc4427c169b6239dc33247422a78cb7e8a91ef6c2b9d61b7e61614f62cbd633c793cf3748cee9303c81bcae6dfbdb633bcd38bfdda14e37dba2bc3a9c",
          "sha256": "f33ce42ae68b3fe2967ccbb56510e6652dd7d05360d26e881a49e5e19aba2427",
          "sha1": "47f4f1d8aea9d524051f901b69062f2ac92c9cd1",
          "md5": "ea4559dcb2a01619211f1af5a96d75da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a22-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a22-android-0.8.7-sources.jar",
          "size": 2180,
          "sha512": "056950fc9d672a14eac4018e9b0869cc85dbf5e92b9f3adc2570b781a1c1f1060c3c24fcd39fba6f45bf75cde24835b5529ecb41e341bb0e0215850f14e280df",
          "sha256": "4f6c42cf2788559ffa5a0a912f4da05ab0a8cd2495a0e5c02ea60d53d6ff8593",
          "sha1": "e45c506666df84b0a921e6b21ffa40d6cb5d3755",
          "md5": "17cfd5b2d6bf66e61c19f4dd80030e5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a22-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a22-android-0.8.7-javadoc.jar",
          "size": 268977,
          "sha512": "47869ecdc25155e4a353f52e8827246588644580f438689bfd10c85e5399f3a84fb0e8603b33ca53ed18f91a55ac36ff7b40b5133eb62ae3ad505c5fffa1e3ca",
          "sha256": "992fb38cea5321095172fc8304fb83fd18dd1768c4e331d224bb1aa4e39d2f15",
          "sha1": "6bab1c12fa324148888b20e10b0d72c246163e25",
          "md5": "a3000dda100a0ead21be48869e961b08"
        }
      ]
    }
  ]
}
