{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb8-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb8",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb8-android-0.8.6.aar",
          "url": "ble-characteristic-u2bb8-android-0.8.6.aar",
          "size": 3133,
          "sha512": "9c43cc47a8f87bd9991e999eac3442edc0555272164c4018936d64dfe887eb1fa118d19becd357feb7a1b5e70c797105a491ec711a68b072e32e3da79cb6be75",
          "sha256": "ff41a73e1ffed2b29bbdb759886671e99b8ae97c1ad602933e20ce02274fcec0",
          "sha1": "b21d880791c1306cfe58fb1dfc924c5630e6c559",
          "md5": "7b1f0ec0e44d6c6f9626d408ae5349ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb8",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb8-android-0.8.6.aar",
          "url": "ble-characteristic-u2bb8-android-0.8.6.aar",
          "size": 3133,
          "sha512": "9c43cc47a8f87bd9991e999eac3442edc0555272164c4018936d64dfe887eb1fa118d19becd357feb7a1b5e70c797105a491ec711a68b072e32e3da79cb6be75",
          "sha256": "ff41a73e1ffed2b29bbdb759886671e99b8ae97c1ad602933e20ce02274fcec0",
          "sha1": "b21d880791c1306cfe58fb1dfc924c5630e6c559",
          "md5": "7b1f0ec0e44d6c6f9626d408ae5349ee"
        }
      ]
    }
  ]
}
