{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-wss-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-android",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-wss-android-0.4.1.aar",
          "url": "ble-service-peripheral-wss-android-0.4.1.aar",
          "size": 4641,
          "sha512": "b32fd316d2d512910cb2e251367c913154d2c4450e5695470b4fc9d7a3ebe269042b17d8e94df8fb29576b21f94e29946c3a63d9a81bfa837d81782e37badf62",
          "sha256": "79a2fb4a5c74e41f724577625372e3f6a7268da6ed85ea4422ff4edc1d17e7b5",
          "sha1": "c0a68f3fb95317d0b28f6f7f33ff2d9b0036637b",
          "md5": "4479bceb4ba30b238b1af1e14ca7c01a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-android",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-wss-android-0.4.1.aar",
          "url": "ble-service-peripheral-wss-android-0.4.1.aar",
          "size": 4641,
          "sha512": "b32fd316d2d512910cb2e251367c913154d2c4450e5695470b4fc9d7a3ebe269042b17d8e94df8fb29576b21f94e29946c3a63d9a81bfa837d81782e37badf62",
          "sha256": "79a2fb4a5c74e41f724577625372e3f6a7268da6ed85ea4422ff4edc1d17e7b5",
          "sha1": "c0a68f3fb95317d0b28f6f7f33ff2d9b0036637b",
          "md5": "4479bceb4ba30b238b1af1e14ca7c01a"
        }
      ]
    }
  ]
}
