{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a21",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a21-0.8.8.jar",
          "url": "ble-characteristic-u2a21-0.8.8.jar",
          "size": 1914,
          "sha512": "6ba36eea155753321a83b14c407a888a3266042e96faaf1a964f14de3752e52d505a1a7362319fe57b2f7feb81e88174a7bf75d2062edf56659c196f76ea377c",
          "sha256": "5674588326f7a149dcf9d6e54da0f3ceb468c9a355719f242acc156ddb937543",
          "sha1": "c24f3dd2cdf053fd1a9d88967a2b721813841964",
          "md5": "3eede04f934668a3cb089c63e0babc4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a21-0.8.8.jar",
          "url": "ble-characteristic-u2a21-0.8.8.jar",
          "size": 1914,
          "sha512": "6ba36eea155753321a83b14c407a888a3266042e96faaf1a964f14de3752e52d505a1a7362319fe57b2f7feb81e88174a7bf75d2062edf56659c196f76ea377c",
          "sha256": "5674588326f7a149dcf9d6e54da0f3ceb468c9a355719f242acc156ddb937543",
          "sha1": "c24f3dd2cdf053fd1a9d88967a2b721813841964",
          "md5": "3eede04f934668a3cb089c63e0babc4b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a21-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2a21-0.8.8-javadoc.jar",
          "size": 109490,
          "sha512": "1759218b19490596b54e117a45146336ed6b9ecbb86e8801f157192f34fa77bfb4d7a8cba7cfd8a759f38dfcef02877f0d5e499c2e8721d49c460152e3f7aac4",
          "sha256": "7dc656eb9517a8e90828fc035d203d3878704fa56b914a5057b774d0d1bade9b",
          "sha1": "97c799d1fed2f7e393889ce1d114f0dea9e07b26",
          "md5": "5d34ce5cc11508a84f63041c8c18cfe8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a21-0.8.8-sources.jar",
          "url": "ble-characteristic-u2a21-0.8.8-sources.jar",
          "size": 1731,
          "sha512": "c362671ed7142116f6413443efa05e75af2dd37a4b453d40b632fee38746d6d6a74d914455355f5abdfcb97a956b6df0478314012c75746af90331191e8a84b6",
          "sha256": "4c43659cc8af5aad5610c53a5616b2b06bbd99e0fa58ee547e8ca920303b727a",
          "sha1": "61d0dad956ee717c4628752bac0f72313c532c53",
          "md5": "5d10d646651e56e4fdc8c6e23d5f414c"
        }
      ]
    }
  ]
}
