{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba3-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba3",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba3-android-0.8.6.aar",
          "url": "ble-characteristic-u2ba3-android-0.8.6.aar",
          "size": 3028,
          "sha512": "b6ef152361c3e83d8830abca437588384fa260ea38aa0ed9aced1e641359e706df83f48cca7422c17eedb916d1c6d1ea9fdd177753ae1a20cf74852235fc26b7",
          "sha256": "078c69cc0567fef169ef18c4fe3ef8967619240d5eef3511bcac5ae15223bc1b",
          "sha1": "24e67dc520b7844a19b46f6f516684be4c71909b",
          "md5": "740f930bcede00db1909b8d5f3e6858f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba3",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba3-android-0.8.6.aar",
          "url": "ble-characteristic-u2ba3-android-0.8.6.aar",
          "size": 3028,
          "sha512": "b6ef152361c3e83d8830abca437588384fa260ea38aa0ed9aced1e641359e706df83f48cca7422c17eedb916d1c6d1ea9fdd177753ae1a20cf74852235fc26b7",
          "sha256": "078c69cc0567fef169ef18c4fe3ef8967619240d5eef3511bcac5ae15223bc1b",
          "sha1": "24e67dc520b7844a19b46f6f516684be4c71909b",
          "md5": "740f930bcede00db1909b8d5f3e6858f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba3-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ba3-android-0.8.6-sources.jar",
          "size": 2129,
          "sha512": "37cae2bbb365985c5bb25699f2d4ea612525f6ade1b65983265dd3f5bc83d50f793fd49127c87a481b44fe617f76f59e9b88456d030ad8e15bb1b67684116d77",
          "sha256": "c20de2ad561c2566f12b9f78346a251c4768249f68fa323f8a54737e194a862b",
          "sha1": "aae0b64e48e4290800f31e60a1a2f2618b0e52d7",
          "md5": "344a1827bdc11a70123d5eb2f8921faa"
        }
      ]
    }
  ]
}
