{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a85",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "e3ikqwiwsbdaddptppumhoyem4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-0.1.0.jar",
          "url": "ble-characteristic-u2a85-0.1.0.jar",
          "size": 1824,
          "sha512": "f30a4c28e298e05964c6083938834418e3db45908e624f8a115ad792e4c8430dc42e4a8ecdd5698903bee8fb734b4e58c83956c8fc99c48d91268baa6151e1dd",
          "sha256": "ac6d8498b8cafe7e756e63688dac50dc09ec06a8833cf0a993a24065946ecce9",
          "sha1": "dd9ee6b2b66cff4886945cd203c184c0247cc9a0",
          "md5": "a32d398e3a7cd85cc2479ff87b47a3cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a85-0.1.0.jar",
          "url": "ble-characteristic-u2a85-0.1.0.jar",
          "size": 1824,
          "sha512": "f30a4c28e298e05964c6083938834418e3db45908e624f8a115ad792e4c8430dc42e4a8ecdd5698903bee8fb734b4e58c83956c8fc99c48d91268baa6151e1dd",
          "sha256": "ac6d8498b8cafe7e756e63688dac50dc09ec06a8833cf0a993a24065946ecce9",
          "sha1": "dd9ee6b2b66cff4886945cd203c184c0247cc9a0",
          "md5": "a32d398e3a7cd85cc2479ff87b47a3cb"
        }
      ]
    }
  ]
}
