{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bcf-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bcf",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bcf-android-0.8.6.aar",
          "url": "ble-characteristic-u2bcf-android-0.8.6.aar",
          "size": 3152,
          "sha512": "2f32ffb9c8c862fbc775e995b0c928d37d09104886849af09e74bbddd954484ce9441dece432a43be0e005c4b82d8e8a987c44e0dee850ea850ca3ea43195414",
          "sha256": "f16b35d394ab027e94148431552f0bf4964f920d8fc0a87f899aa396977f1b74",
          "sha1": "02f58e58d387455b7318e19e4fcd60fb9b6a868f",
          "md5": "c3fbefaf3af106f560381a0399f63c7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bcf",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bcf-android-0.8.6.aar",
          "url": "ble-characteristic-u2bcf-android-0.8.6.aar",
          "size": 3152,
          "sha512": "2f32ffb9c8c862fbc775e995b0c928d37d09104886849af09e74bbddd954484ce9441dece432a43be0e005c4b82d8e8a987c44e0dee850ea850ca3ea43195414",
          "sha256": "f16b35d394ab027e94148431552f0bf4964f920d8fc0a87f899aa396977f1b74",
          "sha1": "02f58e58d387455b7318e19e4fcd60fb9b6a868f",
          "md5": "c3fbefaf3af106f560381a0399f63c7b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bcf-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2bcf-android-0.8.6-sources.jar",
          "size": 2220,
          "sha512": "8801937a997f2cc78eda1a985b0b88473a8a4febbb4cb427f5de4d21320d035772ab0a943f0d63f852ee600aa810392c3ea35f6cc360aed33526011c6d1668d5",
          "sha256": "1aa8f21a9248389ee5022477d6147cfc9930cffea05ff432bf8fa7fbb3544925",
          "sha1": "19c9a9a72101ab04407d6201c22e4afd9a3f5394",
          "md5": "5b4fef54fc3d87278da2b7fe266658e1"
        }
      ]
    }
  ]
}
