{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad2-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad2-android-0.2.8.aar",
          "url": "ble-characteristic-u2ad2-android-0.2.8.aar",
          "size": 5309,
          "sha512": "77c8248ab4f3ae9ae2d72491afa03c9c0159baedffdcc6cb19c08769efbc2f0d7225c91ab10a2f86e450af2ef66da2ea6a84ab64fe1cc7fb81525276d0da5e3a",
          "sha256": "8cd6767c1410ba1dd63bbc3fa31ad889b8b8b67f72a0b6f03871fdd25bae3e6a",
          "sha1": "a6ed721615e8122930a48be404a045f2d268b929",
          "md5": "dd27c8e6f3cdc8734b4286ee7739ebf3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad2-android-0.2.8.aar",
          "url": "ble-characteristic-u2ad2-android-0.2.8.aar",
          "size": 5309,
          "sha512": "77c8248ab4f3ae9ae2d72491afa03c9c0159baedffdcc6cb19c08769efbc2f0d7225c91ab10a2f86e450af2ef66da2ea6a84ab64fe1cc7fb81525276d0da5e3a",
          "sha256": "8cd6767c1410ba1dd63bbc3fa31ad889b8b8b67f72a0b6f03871fdd25bae3e6a",
          "sha1": "a6ed721615e8122930a48be404a045f2d268b929",
          "md5": "dd27c8e6f3cdc8734b4286ee7739ebf3"
        }
      ]
    }
  ]
}
