{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af3-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af3",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af3-android-0.4.3.aar",
          "url": "ble-characteristic-u2af3-android-0.4.3.aar",
          "size": 3092,
          "sha512": "85d821906d7df24170f99f2b361537d50ed13f6574b4ae1e987b42db3d92d9c2f5ec9785b39a25be757de36e0b1c4a877b0a5a19691eb02f5752d10dedd6c923",
          "sha256": "826780f86d343cca94e476fe5ec5dfa8497d07fa5bdb65706db62bec07aae03e",
          "sha1": "c341850441b5d60fdcea8eeaef682f3584053b29",
          "md5": "d0456404aeb6b8180c06b9c847293b74"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2af3",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af3-android-0.4.3.aar",
          "url": "ble-characteristic-u2af3-android-0.4.3.aar",
          "size": 3092,
          "sha512": "85d821906d7df24170f99f2b361537d50ed13f6574b4ae1e987b42db3d92d9c2f5ec9785b39a25be757de36e0b1c4a877b0a5a19691eb02f5752d10dedd6c923",
          "sha256": "826780f86d343cca94e476fe5ec5dfa8497d07fa5bdb65706db62bec07aae03e",
          "sha1": "c341850441b5d60fdcea8eeaef682f3584053b29",
          "md5": "d0456404aeb6b8180c06b9c847293b74"
        }
      ]
    }
  ]
}
