{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1e-android",
    "version": "0.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qi757wsgp5fjzeruuodhghyjtm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1e",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1e-android-0.4.1.aar",
          "url": "ble-characteristic-u2b1e-android-0.4.1.aar",
          "size": 3129,
          "sha512": "067391fbdcf32879691e05beda4057c82cb073a9254ec4f75cd3a8529e03b3156b2e07ed0b7d2d6cdedf474ff161395c4251558b23d9fd62e9cf2c49d679a7b4",
          "sha256": "ea821aa258b84b9cbe7597a171f1e4c7dc0597c1e4d24964b3dbfb5c0dd135f0",
          "sha1": "a52f6f91bf66278555ffe62030dd195173b2da24",
          "md5": "9716157403b574d419b3030d282daa4e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1e",
          "version": {
            "requires": "0.4.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1e-android-0.4.1.aar",
          "url": "ble-characteristic-u2b1e-android-0.4.1.aar",
          "size": 3129,
          "sha512": "067391fbdcf32879691e05beda4057c82cb073a9254ec4f75cd3a8529e03b3156b2e07ed0b7d2d6cdedf474ff161395c4251558b23d9fd62e9cf2c49d679a7b4",
          "sha256": "ea821aa258b84b9cbe7597a171f1e4c7dc0597c1e4d24964b3dbfb5c0dd135f0",
          "sha1": "a52f6f91bf66278555ffe62030dd195173b2da24",
          "md5": "9716157403b574d419b3030d282daa4e"
        }
      ]
    }
  ]
}
