{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba2-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba2",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba2-android-0.8.6.aar",
          "url": "ble-characteristic-u2ba2-android-0.8.6.aar",
          "size": 3085,
          "sha512": "fd56c39a65e8ef644640f2bfba9041b2232f62f042fdb9d20434b3312c0111ed39f42f6f7ac3de775624d5e7a101112b2fdabc65a790eafa5b6d1a7871a12f71",
          "sha256": "59e6914af47d98fb53841d5e5561a924bace7ca77bccb8f27594a0fa81534048",
          "sha1": "3d12714627ff5a988ddbd75e18409a056c81c595",
          "md5": "94607afa9f3f75f1c1f0ea5dcffb1dd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba2",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba2-android-0.8.6.aar",
          "url": "ble-characteristic-u2ba2-android-0.8.6.aar",
          "size": 3085,
          "sha512": "fd56c39a65e8ef644640f2bfba9041b2232f62f042fdb9d20434b3312c0111ed39f42f6f7ac3de775624d5e7a101112b2fdabc65a790eafa5b6d1a7871a12f71",
          "sha256": "59e6914af47d98fb53841d5e5561a924bace7ca77bccb8f27594a0fa81534048",
          "sha1": "3d12714627ff5a988ddbd75e18409a056c81c595",
          "md5": "94607afa9f3f75f1c1f0ea5dcffb1dd9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ba2-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ba2-android-0.8.6-sources.jar",
          "size": 2178,
          "sha512": "d0db96bce700f271aca52e5fa026e01198e3f126b86ea828eecb484d98928c09ec1f8054a40679a3dc147024bab04192f684594c8106881146bc50dc5263d06f",
          "sha256": "bc756068f4f6bc94f9e565ad0e48f6009b6af7f93f562229976cc2888d4f90aa",
          "sha1": "8ff8d0869ed32166f2cb6c62f84e2ba80dae96e9",
          "md5": "a1b2b636c800b3f976044e4c0522b266"
        }
      ]
    }
  ]
}
