{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc6",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12.jar",
          "url": "ble-characteristic-u2bc6-0.8.12.jar",
          "size": 1456,
          "sha512": "1306ecce0b0f7fd42009a01e3c80e9f07a236a3bf52e711c3eb1438b8b0bfb0185e4606df4eb99d3abf76404c203ca7c828115f59887349db544aeec38ecee5a",
          "sha256": "00ab02644bbd7a8254e6ef4839ef811481eead36dde1a8ad41c4e8c34987a2f1",
          "sha1": "15dd152741ceb097f1501e99c9ca9480ce502330",
          "md5": "5764a7f91a8eb8c12a2aca9e3054266b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12.jar",
          "url": "ble-characteristic-u2bc6-0.8.12.jar",
          "size": 1456,
          "sha512": "1306ecce0b0f7fd42009a01e3c80e9f07a236a3bf52e711c3eb1438b8b0bfb0185e4606df4eb99d3abf76404c203ca7c828115f59887349db544aeec38ecee5a",
          "sha256": "00ab02644bbd7a8254e6ef4839ef811481eead36dde1a8ad41c4e8c34987a2f1",
          "sha1": "15dd152741ceb097f1501e99c9ca9480ce502330",
          "md5": "5764a7f91a8eb8c12a2aca9e3054266b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2bc6-0.8.12-javadoc.jar",
          "size": 85980,
          "sha512": "c37ea69dbd9011b7ca29c5e5a61500fcf371cf69ddb16a0f9044e7ab6a8dd5ef63cde8f3885e248167267611d2009f5900cf7d6ffeffc165a811fff9733239f9",
          "sha256": "bd8437ca009f93add3179e5d8d4cc0dbfb72eeb074b69f456441c63ca6625611",
          "sha1": "9953a3d212b38f6ffd50522a48596a11fcc7b8e3",
          "md5": "d1ef67854e5a791ca21fe289e5ee2fc8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12-sources.jar",
          "url": "ble-characteristic-u2bc6-0.8.12-sources.jar",
          "size": 1435,
          "sha512": "f4d766f34fbf552c8f9c691d8415c8921138bf15ec6aaa1a1f6b09d9aa7402b57404e274871bed23f6784f55b6fac7e329b4d634e513094f7b7ee8dbf40df9b7",
          "sha256": "5e26024b190f9c047fbe69f7275d73c2e7b3e15f53bb5dcbe2c95801c997bcf9",
          "sha1": "058943b4264ae35dde8447f5d7e714d9cb907b80",
          "md5": "db88a7c65b2165008474e3df30c93716"
        }
      ]
    }
  ]
}
