{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bc6",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12.jar",
          "url": "ble-characteristic-u2bc6-0.8.12.jar",
          "size": 1456,
          "sha512": "1306ecce0b0f7fd42009a01e3c80e9f07a236a3bf52e711c3eb1438b8b0bfb0185e4606df4eb99d3abf76404c203ca7c828115f59887349db544aeec38ecee5a",
          "sha256": "00ab02644bbd7a8254e6ef4839ef811481eead36dde1a8ad41c4e8c34987a2f1",
          "sha1": "15dd152741ceb097f1501e99c9ca9480ce502330",
          "md5": "5764a7f91a8eb8c12a2aca9e3054266b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12.jar",
          "url": "ble-characteristic-u2bc6-0.8.12.jar",
          "size": 1456,
          "sha512": "1306ecce0b0f7fd42009a01e3c80e9f07a236a3bf52e711c3eb1438b8b0bfb0185e4606df4eb99d3abf76404c203ca7c828115f59887349db544aeec38ecee5a",
          "sha256": "00ab02644bbd7a8254e6ef4839ef811481eead36dde1a8ad41c4e8c34987a2f1",
          "sha1": "15dd152741ceb097f1501e99c9ca9480ce502330",
          "md5": "5764a7f91a8eb8c12a2aca9e3054266b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2bc6-0.8.12-javadoc.jar",
          "size": 107166,
          "sha512": "86443ec03ebbbbf9b3a399618afa753fc177f85a6c41ae581aabad0252ad29965060f20ee12a2cd3db30255d5193be58b07ae3ea70b4bf2d9eb5c0b09d9b9c8a",
          "sha256": "13c59a65ef9671129195d0e3d9c03914a7f86d23f144bcf9897c32abdf7fa2ad",
          "sha1": "fa24b3b8b35f47e314caa07fb529555057ccd251",
          "md5": "5b269c2d10610547be07f071888c5b4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bc6-0.8.12-sources.jar",
          "url": "ble-characteristic-u2bc6-0.8.12-sources.jar",
          "size": 1435,
          "sha512": "f4d766f34fbf552c8f9c691d8415c8921138bf15ec6aaa1a1f6b09d9aa7402b57404e274871bed23f6784f55b6fac7e329b4d634e513094f7b7ee8dbf40df9b7",
          "sha256": "5e26024b190f9c047fbe69f7275d73c2e7b3e15f53bb5dcbe2c95801c997bcf9",
          "sha1": "058943b4264ae35dde8447f5d7e714d9cb907b80",
          "md5": "db88a7c65b2165008474e3df30c93716"
        }
      ]
    }
  ]
}
