{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-rtus-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-central-android-0.1.4.aar",
          "url": "ble-service-rtus-central-android-0.1.4.aar",
          "size": 3730,
          "sha512": "72a876794692c79dbef11bb4027f419e32eb50f6a541f490c743b7d3f311401364a5c48426b4e7e9a0e970575f428df1c865d8ddb18844974c0c103cbf8fadca",
          "sha256": "5f7ae3abc40028f08a2bd497af395ac5f52ed78665adbdeb6b4dfae65ee129c5",
          "sha1": "f168676b6805853a3858c9c6455bf80a4ac1285a",
          "md5": "9373798f53f7ba717ffe87ae2ff1c455"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-rtus-central-android-0.1.4.aar",
          "url": "ble-service-rtus-central-android-0.1.4.aar",
          "size": 3730,
          "sha512": "72a876794692c79dbef11bb4027f419e32eb50f6a541f490c743b7d3f311401364a5c48426b4e7e9a0e970575f428df1c865d8ddb18844974c0c103cbf8fadca",
          "sha256": "5f7ae3abc40028f08a2bd497af395ac5f52ed78665adbdeb6b4dfae65ee129c5",
          "sha1": "f168676b6805853a3858c9c6455bf80a4ac1285a",
          "md5": "9373798f53f7ba717ffe87ae2ff1c455"
        }
      ]
    }
  ]
}
