{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b77",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b77-0.8.8.jar",
          "url": "ble-characteristic-u2b77-0.8.8.jar",
          "size": 1456,
          "sha512": "8a52dfa74c8cbfb60276c6027dadd061b8202f96ee282f0519dd51c679b6f5e8c6d603db60fa43d7dd5f08db21d7c7c0f093fd20721d46a97e40a0026d85cedf",
          "sha256": "4d714405b4d25e290bfd16319488466bc5829d19ec966b495bec0890403f7c1d",
          "sha1": "8abeb8f65c4d88ddb6ccee5390346a7399c93f72",
          "md5": "9db17b069765776e10e18e863e15f30b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b77-0.8.8.jar",
          "url": "ble-characteristic-u2b77-0.8.8.jar",
          "size": 1456,
          "sha512": "8a52dfa74c8cbfb60276c6027dadd061b8202f96ee282f0519dd51c679b6f5e8c6d603db60fa43d7dd5f08db21d7c7c0f093fd20721d46a97e40a0026d85cedf",
          "sha256": "4d714405b4d25e290bfd16319488466bc5829d19ec966b495bec0890403f7c1d",
          "sha1": "8abeb8f65c4d88ddb6ccee5390346a7399c93f72",
          "md5": "9db17b069765776e10e18e863e15f30b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b77-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2b77-0.8.8-javadoc.jar",
          "size": 107168,
          "sha512": "83d7d320de00b8f7c8c13e804ac4e69f1b868f932bede027168072c1ffed10c7b11335564993247f347a9ca6ed5441d5095103cb4d6e9c294699bdeb5bc4f26c",
          "sha256": "c6e98962b8970e93b4f9466cb8d5fc4843dfb05d7f2dea90b0fd39ae1b9181ad",
          "sha1": "7940442095b317bc26bb12d9d31bde59292b6895",
          "md5": "2330daf16ed0ab2b99ddc8b137113cd4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b77-0.8.8-sources.jar",
          "url": "ble-characteristic-u2b77-0.8.8-sources.jar",
          "size": 1443,
          "sha512": "ec26b6c319b955e464fd3496e806078f0cec0311aaf44dd131acf7f12bac10093c277090f522850769fe498d8c41e899781121ca3f9f61a676a5c62de2191753",
          "sha256": "2f3e8bfdd61c51de02395928e895f8b77dede2cd6bf47a56b28ccc25d631bf3b",
          "sha1": "904d044694bb0a6fc6f66978f347961a82402b4b",
          "md5": "9da4cd8b700aa46a235f663a4919f311"
        }
      ]
    }
  ]
}
