{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-pxp-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-pxp-android-0.8.12.aar",
          "url": "ble-profile-pxp-android-0.8.12.aar",
          "size": 1294,
          "sha512": "2618a9065afaf1a7a851254069610fe81628ad83249cae845d301fe318850a34838b83d4acb61a4a2d8d3f0b20c0136e6c8390e0e10993d39b5b90ce0df9e44e",
          "sha256": "eb8569c3919daa5260d1d88eb1581cb31998d7030810592a2ca344801757cb7d",
          "sha1": "d9cc006b275f99eeec1b5e754acc6e68fd9e247f",
          "md5": "d2f50eb47da1b11bdb5639fa9a0e9fa8"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-pxp-android-0.8.12.aar",
          "url": "ble-profile-pxp-android-0.8.12.aar",
          "size": 1294,
          "sha512": "2618a9065afaf1a7a851254069610fe81628ad83249cae845d301fe318850a34838b83d4acb61a4a2d8d3f0b20c0136e6c8390e0e10993d39b5b90ce0df9e44e",
          "sha256": "eb8569c3919daa5260d1d88eb1581cb31998d7030810592a2ca344801757cb7d",
          "sha1": "d9cc006b275f99eeec1b5e754acc6e68fd9e247f",
          "md5": "d2f50eb47da1b11bdb5639fa9a0e9fa8"
        }
      ]
    }
  ]
}
