{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ias-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a06-android",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-android-0.1.1.aar",
          "url": "ble-service-ias-android-0.1.1.aar",
          "size": 1021,
          "sha512": "2483ef28bfb11874a9666fff94041b3eea608a66b33902d99f4ba1855cbdf8de75cd4a5a3dd241d3f47aa213f43a130571512d6641ee331e355bddb05f482d5e",
          "sha256": "d250a82ed27072e1a689f77ad99e3f68c0e65453a8853285bf5e46166fc1b5b2",
          "sha1": "90c74c32c18cbf3f41d26600f5cd0f6275eec77c",
          "md5": "da2774ecf622c9ee289a10a5d22025a1"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a06-android",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-android-0.1.1.aar",
          "url": "ble-service-ias-android-0.1.1.aar",
          "size": 1021,
          "sha512": "2483ef28bfb11874a9666fff94041b3eea608a66b33902d99f4ba1855cbdf8de75cd4a5a3dd241d3f47aa213f43a130571512d6641ee331e355bddb05f482d5e",
          "sha256": "d250a82ed27072e1a689f77ad99e3f68c0e65453a8853285bf5e46166fc1b5b2",
          "sha1": "90c74c32c18cbf3f41d26600f5cd0f6275eec77c",
          "md5": "da2774ecf622c9ee289a10a5d22025a1"
        }
      ]
    }
  ]
}
