{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-scpp-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-scpp-android-0.4.6.aar",
          "url": "ble-profile-scpp-android-0.4.6.aar",
          "size": 1186,
          "sha512": "5e2b6e1dacd0b9d24e32e5c855d2f130d757c958ce4e4b732d06f2981ad98ff7eac10f0a85de3a5dd03b9a6cd104a540463c17061174ce29669bbc02bd85c371",
          "sha256": "e4cc4daeecf6e9e5ed4c9cf25cfe304be0da469a3b87879e7a6f3c272245c2e9",
          "sha1": "4329dacbed72364b1f349fd970b879f5ebf1a835",
          "md5": "98177c3f457e34b9885cbe3533d6093a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-scpp-android-0.4.6.aar",
          "url": "ble-profile-scpp-android-0.4.6.aar",
          "size": 1186,
          "sha512": "5e2b6e1dacd0b9d24e32e5c855d2f130d757c958ce4e4b732d06f2981ad98ff7eac10f0a85de3a5dd03b9a6cd104a540463c17061174ce29669bbc02bd85c371",
          "sha256": "e4cc4daeecf6e9e5ed4c9cf25cfe304be0da469a3b87879e7a6f3c272245c2e9",
          "sha1": "4329dacbed72364b1f349fd970b879f5ebf1a835",
          "md5": "98177c3f457e34b9885cbe3533d6093a"
        }
      ]
    }
  ]
}
