{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b24-android",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b24",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b24-android-0.8.2.aar",
          "url": "ble-characteristic-u2b24-android-0.8.2.aar",
          "size": 3080,
          "sha512": "f386c706cfbae71140ea7e1029fbe2341e4969ae886473332b0b7b51efed60041197a7948bdc0e2466405820cd86cb217a16ba9b4d6d66d756ab2006f293e3f2",
          "sha256": "aadbf004a64078e98fc9f908921b790d8713da48af6027de97100926d1566e5e",
          "sha1": "088fb7ce7886fdb1e04d39797fae771e561ab3c4",
          "md5": "5c5f47a643e771f61fc051984b5d8106"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b24",
          "version": {
            "requires": "0.8.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b24-android-0.8.2.aar",
          "url": "ble-characteristic-u2b24-android-0.8.2.aar",
          "size": 3080,
          "sha512": "f386c706cfbae71140ea7e1029fbe2341e4969ae886473332b0b7b51efed60041197a7948bdc0e2466405820cd86cb217a16ba9b4d6d66d756ab2006f293e3f2",
          "sha256": "aadbf004a64078e98fc9f908921b790d8713da48af6027de97100926d1566e5e",
          "sha1": "088fb7ce7886fdb1e04d39797fae771e561ab3c4",
          "md5": "5c5f47a643e771f61fc051984b5d8106"
        }
      ]
    }
  ]
}
