{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-pass-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "5gfggryb45gy7pfwli2rnp2p7e"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-pass-android-0.4.4.aar",
          "url": "ble-service-peripheral-pass-android-0.4.4.aar",
          "size": 6319,
          "sha512": "537608b5008a312000c65094e692654f82a3478dfa114986053da8ab4d4a90669e74cd6c080f46ef326863c32d96189457d77ebfffb8243fd1c7a320974399fd",
          "sha256": "e42b1833288b9c487a7f2cc942501cdc62ef3bf80a77433a65fac11b22c5f9bd",
          "sha1": "efb69bd585c332dde7cac674bd62e660a89a3242",
          "md5": "315f1a6eb972c4edb343cc795cf864a6"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-android",
          "version": {
            "requires": "0.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-pass-android-0.4.4.aar",
          "url": "ble-service-peripheral-pass-android-0.4.4.aar",
          "size": 6319,
          "sha512": "537608b5008a312000c65094e692654f82a3478dfa114986053da8ab4d4a90669e74cd6c080f46ef326863c32d96189457d77ebfffb8243fd1c7a320974399fd",
          "sha256": "e42b1833288b9c487a7f2cc942501cdc62ef3bf80a77433a65fac11b22c5f9bd",
          "sha1": "efb69bd585c332dde7cac674bd62e660a89a3242",
          "md5": "315f1a6eb972c4edb343cc795cf864a6"
        }
      ]
    }
  ]
}
