{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-anp-peripheral-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-anp-peripheral-android-0.1.6.aar",
          "url": "ble-profile-anp-peripheral-android-0.1.6.aar",
          "size": 4201,
          "sha512": "10d11e63c7a9ad8f90c19740d332be8dc5cdf6ccf5cd67a06fff84e7895eb75b9ddceef55133631c4243ce9e60fa877382df244294aa5b3ec79f72710fdd20a4",
          "sha256": "d7e432f9b01b9cf7b348abee84ba0bc3608896af1027a9e3cfb20a08868dc254",
          "sha1": "0c78aead6554b7533215ec7d5382e3e4bbbd6518",
          "md5": "13b53e13db28906305b06925c9e28639"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ans-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-anp-peripheral-android-0.1.6.aar",
          "url": "ble-profile-anp-peripheral-android-0.1.6.aar",
          "size": 4201,
          "sha512": "10d11e63c7a9ad8f90c19740d332be8dc5cdf6ccf5cd67a06fff84e7895eb75b9ddceef55133631c4243ce9e60fa877382df244294aa5b3ec79f72710fdd20a4",
          "sha256": "d7e432f9b01b9cf7b348abee84ba0bc3608896af1027a9e3cfb20a08868dc254",
          "sha1": "0c78aead6554b7533215ec7d5382e3e4bbbd6518",
          "md5": "13b53e13db28906305b06925c9e28639"
        }
      ]
    }
  ]
}
