{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bca-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bca",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bca-android-0.8.12.aar",
          "url": "ble-characteristic-u2bca-android-0.8.12.aar",
          "size": 3156,
          "sha512": "d348f33dc0f3944cd713a1212f0d9b293219a057cab0b266f3e9d590e80dedf6f580b5b1d70a23dd101cdc23449ce6f4fcdc8ba1f5ac9a282bd97b140a53f428",
          "sha256": "c24bca1119aa1e9cec6f026ed83c02c34f68b4de2f2ddaec2014d33a764972ee",
          "sha1": "f769ade0618c7940a64a74fd5e33ff54a894b094",
          "md5": "f9cce8c49389411f11a52ae3670b6c4a"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bca",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bca-android-0.8.12.aar",
          "url": "ble-characteristic-u2bca-android-0.8.12.aar",
          "size": 3156,
          "sha512": "d348f33dc0f3944cd713a1212f0d9b293219a057cab0b266f3e9d590e80dedf6f580b5b1d70a23dd101cdc23449ce6f4fcdc8ba1f5ac9a282bd97b140a53f428",
          "sha256": "c24bca1119aa1e9cec6f026ed83c02c34f68b4de2f2ddaec2014d33a764972ee",
          "sha1": "f769ade0618c7940a64a74fd5e33ff54a894b094",
          "md5": "f9cce8c49389411f11a52ae3670b6c4a"
        }
      ]
    }
  ]
}
