{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-cps-peripheral-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-peripheral-android-0.1.4.aar",
          "url": "ble-service-cps-peripheral-android-0.1.4.aar",
          "size": 18399,
          "sha512": "b410dff3e1a9f04ea5146955a020f5c5ce7890c9095cbf3b0b844b38cbca9ed12292ceb00592ea7b85375b471f9063f0005252f122ca50e988de30c4afdd5125",
          "sha256": "47fec0f55c417a683e4a85718626af48be9246148d4511a1317a7421adf28425",
          "sha1": "1c6c072ed1bbae1c954e9758b51ce0eafada4e5a",
          "md5": "058434c2378396ea14369251821a4dc8"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cps-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-cps-peripheral-android-0.1.4.aar",
          "url": "ble-service-cps-peripheral-android-0.1.4.aar",
          "size": 18399,
          "sha512": "b410dff3e1a9f04ea5146955a020f5c5ce7890c9095cbf3b0b844b38cbca9ed12292ceb00592ea7b85375b471f9063f0005252f122ca50e988de30c4afdd5125",
          "sha256": "47fec0f55c417a683e4a85718626af48be9246148d4511a1317a7421adf28425",
          "sha1": "1c6c072ed1bbae1c954e9758b51ce0eafada4e5a",
          "md5": "058434c2378396ea14369251821a4dc8"
        }
      ]
    }
  ]
}
