{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b80-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b80",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b80-android-0.8.7.aar",
          "url": "ble-characteristic-u2b80-android-0.8.7.aar",
          "size": 3135,
          "sha512": "16b19ee3fe35467664b85d2d41b886daf54439ad23252619ea5bc9f87218c3f8b35b4834f44531d52274cdce26ac05c9c421b92c4600b21ac980b796a82a9eef",
          "sha256": "6f06278c2cc76273c3b04bbefc3fb2ad4d63492f3f9a9512c1f55c412c2eccd9",
          "sha1": "c8e9b851e8d454de3e470e068b0bcb5b329cb121",
          "md5": "84f3c0a172ce57a4b7c3b6b53d0e9cd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b80",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b80-android-0.8.7.aar",
          "url": "ble-characteristic-u2b80-android-0.8.7.aar",
          "size": 3135,
          "sha512": "16b19ee3fe35467664b85d2d41b886daf54439ad23252619ea5bc9f87218c3f8b35b4834f44531d52274cdce26ac05c9c421b92c4600b21ac980b796a82a9eef",
          "sha256": "6f06278c2cc76273c3b04bbefc3fb2ad4d63492f3f9a9512c1f55c412c2eccd9",
          "sha1": "c8e9b851e8d454de3e470e068b0bcb5b329cb121",
          "md5": "84f3c0a172ce57a4b7c3b6b53d0e9cd1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b80-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b80-android-0.8.7-sources.jar",
          "size": 2133,
          "sha512": "8df1b19e4d20b66cec286d445b6a6287a6ee62417c62cd4d08aaa10c144d3a83df192f7543ac829ee4bb5f3b25f6ceaa9ea01f1c54022361be882d2ab4510889",
          "sha256": "a4a31675c20cc274466457e56d68f9ae1d543473d4f76cd057f1f3f0375af38a",
          "sha1": "3d22d024d23ea505bfb91f5a5838c7dde1270e97",
          "md5": "669b49f262182911f7820de20128960b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b80-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b80-android-0.8.7-javadoc.jar",
          "size": 268872,
          "sha512": "1b0aad40ba5e2ddf8a20a70f037c6ff4fad11ff7b95739bc2a6b03a680732892cb9df3b671dd8c49d4698468ec7e918074e7c04d9abb109110cd7d2ea5b163d0",
          "sha256": "d539ae7703e39fa36458da309c104c9dfd681faa903fb98d4499d21847baa425",
          "sha1": "a11988a04e3c81d2f5a5970cb52e5c9e812cf1a9",
          "md5": "c51b1fa67cdb86bffb03899f0a855b46"
        }
      ]
    }
  ]
}
