{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a27-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a27",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a27-android-0.8.13.aar",
          "url": "ble-characteristic-u2a27-android-0.8.13.aar",
          "size": 3167,
          "sha512": "c5e8570f8e1a7fd7f64f128540ea400cb5c3819e925a8cdaf74c35b47cb7ae2ac17b44f6005200aa1afa4d56c17a1e96c8dc7af570b1c1a4484187634e1692a4",
          "sha256": "5fa143206af8690befdc7e072dfd0e7d6d7565e3d5f9287689772a1899cee97a",
          "sha1": "959d306025785f387485290512a7ea4f1bc3d823",
          "md5": "a34835d1f70a2b531f984c5d37705e02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a27",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a27-android-0.8.13.aar",
          "url": "ble-characteristic-u2a27-android-0.8.13.aar",
          "size": 3167,
          "sha512": "c5e8570f8e1a7fd7f64f128540ea400cb5c3819e925a8cdaf74c35b47cb7ae2ac17b44f6005200aa1afa4d56c17a1e96c8dc7af570b1c1a4484187634e1692a4",
          "sha256": "5fa143206af8690befdc7e072dfd0e7d6d7565e3d5f9287689772a1899cee97a",
          "sha1": "959d306025785f387485290512a7ea4f1bc3d823",
          "md5": "a34835d1f70a2b531f984c5d37705e02"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a27-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2a27-android-0.8.13-sources.jar",
          "size": 2215,
          "sha512": "6527110f637b206ec3fd59a0cc971eec157a5517043837e7450a78858e6fec297bf5726e9051309b0849f7ab313161d25c985993e879487883ec010448cc133d",
          "sha256": "c68b013c8bb143f673e02c9bef0f40616c699ae4c5f163da72b42d60fa70123f",
          "sha1": "307edef5daf9ac09ec9dcae2e16a02aa680797cd",
          "md5": "d420dfdc8cfe6d49851bd882396c7abd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a27-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2a27-android-0.8.13-javadoc.jar",
          "size": 271210,
          "sha512": "f2790847b77aa10f682a9953692587c464f222fedecadd0c3104c914eeeed826cbaa3b2b8a12c256b187d63b4f5e24fd9c0340e6a4386375323d4a048be0d4d4",
          "sha256": "391236555c6c354d2ba8af30be409b986a746a09648f17312618b51e4672e410",
          "sha1": "0418a27c7ed5a44e1a0252322e7d21a1cd254e20",
          "md5": "87e56204c03028cdd28ca793833bff88"
        }
      ]
    }
  ]
}
