{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6b",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.8.7.jar",
          "url": "ble-characteristic-u2a6b-0.8.7.jar",
          "size": 4305,
          "sha512": "d3ebc91f7d1f28e53c6c519929b1674e6d49f9dbd61b67be408c1638ebe1a1b7619c6dd11b16e3b36b63361ac35dbabb50da22f6160b894b5273295cc472f7f7",
          "sha256": "29e4148a8a711e27a126d1fe5c90a1935f154bfa706250a58a1ef03c65dd7d57",
          "sha1": "afe61b6082d45b37c504adcf4d162f13c3dcd2b6",
          "md5": "ffaebcbb7196c013c3ff9fa180f1bc2e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.8.7.jar",
          "url": "ble-characteristic-u2a6b-0.8.7.jar",
          "size": 4305,
          "sha512": "d3ebc91f7d1f28e53c6c519929b1674e6d49f9dbd61b67be408c1638ebe1a1b7619c6dd11b16e3b36b63361ac35dbabb50da22f6160b894b5273295cc472f7f7",
          "sha256": "29e4148a8a711e27a126d1fe5c90a1935f154bfa706250a58a1ef03c65dd7d57",
          "sha1": "afe61b6082d45b37c504adcf4d162f13c3dcd2b6",
          "md5": "ffaebcbb7196c013c3ff9fa180f1bc2e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a6b-0.8.7-javadoc.jar",
          "size": 117524,
          "sha512": "2ecf38aa82bd4b9d0f7a8bfd92a793a70bc1459d5ba311ebb27af6803f2e8727ae38c034fd0be67fa6ed53c39e8d8dfbf44cb72dc7c759bed04a088c6fc6ff41",
          "sha256": "2840f7b06c29464a5dc415a6a6ff3e679cdf4a86e5802c8084fd2837c36e0dcb",
          "sha1": "557efdbff287567e6b3ad18f5265364c48779b8d",
          "md5": "24097c44c8040af94d1e3acbab3d4e2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a6b-0.8.7-sources.jar",
          "size": 4416,
          "sha512": "490db2bd4e980b6cf18172d6492f1d6e5a9bd8e60408b25d989c756b9e8f048664f9ab06712310b9b890eaf205ca1f22672d9fcd69cfdd7dc0d140fd45d9cbdb",
          "sha256": "6f1166c9a04ca024eb2ebcd5a25edd95a7cbd5150a85ad0ccdfcb0eaed5160ca",
          "sha1": "cf3156176a8bbb37952d576eca7a312ee10b506e",
          "md5": "04a70e62ece4b051879c399dbf8f7a99"
        }
      ]
    }
  ]
}
