{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a38-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vy3zl4h6xba2zmquz65cqxefdu"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a38",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a38-android-0.2.1.aar",
          "url": "ble-characteristic-u2a38-android-0.2.1.aar",
          "size": 2922,
          "sha512": "e1aa0a98655ec8dc99f7519b65dd7ebcaa4f2ef351ce87b5b173bb3925461133f68e5b7ab8f93b5901764391444ec2c387a2e8e905a1743fc7a8d7df8d0e1f16",
          "sha256": "22d1774f3f642a5f40b74525980e90a0218784eb3045a6c553fcb2f9caeb9dfc",
          "sha1": "1bd1e795de70fa46dd6fd48c86b19a43c0a4fe53",
          "md5": "29b725b7dc8725d00e91b8c0f2eff3fb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a38",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a38-android-0.2.1.aar",
          "url": "ble-characteristic-u2a38-android-0.2.1.aar",
          "size": 2922,
          "sha512": "e1aa0a98655ec8dc99f7519b65dd7ebcaa4f2ef351ce87b5b173bb3925461133f68e5b7ab8f93b5901764391444ec2c387a2e8e905a1743fc7a8d7df8d0e1f16",
          "sha256": "22d1774f3f642a5f40b74525980e90a0218784eb3045a6c553fcb2f9caeb9dfc",
          "sha1": "1bd1e795de70fa46dd6fd48c86b19a43c0a4fe53",
          "md5": "29b725b7dc8725d00e91b8c0f2eff3fb"
        }
      ]
    }
  ]
}
