{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b27",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b27-0.8.4.jar",
          "url": "ble-characteristic-u2b27-0.8.4.jar",
          "size": 1490,
          "sha512": "cb4120fbb92bb096907b7ede22404e4977a3a79900a23021d0941b66614ddef96400d4e2217918ee2df351c6674a93896d477f4a6f8dedfa1d33b36d7e11affa",
          "sha256": "999e927260ad538d5bb082643b094f1e0fc6386e18a8ea5cbc3cf9bca18c597a",
          "sha1": "1cf95279e9ba3f58033b409bc92d5f165265ff4d",
          "md5": "b3198a9db3129a62cb0d2d552f2517b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b27-0.8.4.jar",
          "url": "ble-characteristic-u2b27-0.8.4.jar",
          "size": 1490,
          "sha512": "cb4120fbb92bb096907b7ede22404e4977a3a79900a23021d0941b66614ddef96400d4e2217918ee2df351c6674a93896d477f4a6f8dedfa1d33b36d7e11affa",
          "sha256": "999e927260ad538d5bb082643b094f1e0fc6386e18a8ea5cbc3cf9bca18c597a",
          "sha1": "1cf95279e9ba3f58033b409bc92d5f165265ff4d",
          "md5": "b3198a9db3129a62cb0d2d552f2517b9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b27-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2b27-0.8.4-javadoc.jar",
          "size": 110017,
          "sha512": "9c6393b52cc7eee507b18e545edcb9f0ee1317f28145ebf59ff9f4d3fe36c180e37d67f4056e9ac6107185dc621454849c9bd8b2d33e55bfb0369f4439623228",
          "sha256": "9426e07d59d9c31d84b791091b274b2c7f751c3a6b5c7804917323e074248d43",
          "sha1": "207d84c18ba7809f0a3639e2dc0ab61f5f2fd656",
          "md5": "1ba805f7f50fff8dfaf1a5be7df955d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b27-0.8.4-sources.jar",
          "url": "ble-characteristic-u2b27-0.8.4-sources.jar",
          "size": 1485,
          "sha512": "ac2939bc9efbd6f06fc3bf8ef587606a450d5d90b585a0c9a49aa90311d23425486c7b1f7e798dd3067fa058438a8e8cddbe35341dfd9f51a1751f149f45f11e",
          "sha256": "00d77195d2a8c09570beff3a3a2e19b71b7c79062f0584cb1d5cb19693d2f3bc",
          "sha1": "008cbf1b40d9cc79ee9a5a23ec7525652bf3111b",
          "md5": "d294e3887299e364195e62e48e26833c"
        }
      ]
    }
  ]
}
