{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b39",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.12.jar",
          "url": "ble-characteristic-u2b39-0.8.12.jar",
          "size": 1459,
          "sha512": "6405b2edd25b7a42b24095de14329793d86abc29461a4fd4921155fcf11e998add021f027458a9e2234e7f1eb95bc5122bea78839262daf3718b62d8e999ec03",
          "sha256": "daeed6c910bd3138e848ddbbfdc21a95650099e364ec36c5b66d61e5e932d86c",
          "sha1": "e6df92382991e71ef0a0482a6918bcc0ec4ffe4b",
          "md5": "f74eecedc59b9c3174a0f3ff0c64e54f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.12.jar",
          "url": "ble-characteristic-u2b39-0.8.12.jar",
          "size": 1459,
          "sha512": "6405b2edd25b7a42b24095de14329793d86abc29461a4fd4921155fcf11e998add021f027458a9e2234e7f1eb95bc5122bea78839262daf3718b62d8e999ec03",
          "sha256": "daeed6c910bd3138e848ddbbfdc21a95650099e364ec36c5b66d61e5e932d86c",
          "sha1": "e6df92382991e71ef0a0482a6918bcc0ec4ffe4b",
          "md5": "f74eecedc59b9c3174a0f3ff0c64e54f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b39-0.8.12-javadoc.jar",
          "size": 107185,
          "sha512": "2e7f86715afa3de29a7ea5ebb54ba0b86dcd58860d684a8743032b426642060da37dfda6f77233a0a045db59ff6c54e81d98cccd835dc54b5f9af9bf72a34787",
          "sha256": "30a603d9b2f371cb330ba68acba4c15a57dcea903c264b71799161da34ba791d",
          "sha1": "78dc0ae160cfd7c2ce5db4615e51e548d53fa687",
          "md5": "34176b2c689c3b4c3eda040633932fec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b39-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b39-0.8.12-sources.jar",
          "size": 1453,
          "sha512": "f08c794231c29e722197eeb2763a2cfa685e425a7dc5629a912a6cdfeb88eac8f2c93a467fff25dc9a74f80563d1527b325c8af98e1601646e7527c4c4ba0132",
          "sha256": "9bd7f35be6ef0d42d537daf77bb18b66561e0a5cfc856265e8dcfd2e65705c12",
          "sha1": "d4d4d9284d70fe80f3d818edcb6b2bde49a1f8a3",
          "md5": "e84856f2853258dde5b66858a1ae2c16"
        }
      ]
    }
  ]
}
