{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a09",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a09-0.4.2.jar",
          "url": "ble-characteristic-u2a09-0.4.2.jar",
          "size": 1441,
          "sha512": "9a0a2ae7d45610767b028bf777756a35c1d6aa3fbeac2b540e8ff6b3f8fe97df81aa76fa23ca241d6604748773268a50c2b43cdf79963715b8341484dcb8e256",
          "sha256": "d6355c3aca0a461eca099067a992cac803c39b887072c966ebfb0af1d2e4aa83",
          "sha1": "2bd621199aeea9c103c9a6298735bf6850954e5e",
          "md5": "ca792a2e8d9cfc457490b1ed7d944160"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a09-0.4.2.jar",
          "url": "ble-characteristic-u2a09-0.4.2.jar",
          "size": 1441,
          "sha512": "9a0a2ae7d45610767b028bf777756a35c1d6aa3fbeac2b540e8ff6b3f8fe97df81aa76fa23ca241d6604748773268a50c2b43cdf79963715b8341484dcb8e256",
          "sha256": "d6355c3aca0a461eca099067a992cac803c39b887072c966ebfb0af1d2e4aa83",
          "sha1": "2bd621199aeea9c103c9a6298735bf6850954e5e",
          "md5": "ca792a2e8d9cfc457490b1ed7d944160"
        }
      ]
    }
  ]
}
