{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-rscp-central-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kcavfl3jx5emrog66zfgdweqoy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rscs-central-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-rscp-central-android-0.1.3.aar",
          "url": "ble-profile-rscp-central-android-0.1.3.aar",
          "size": 6056,
          "sha512": "169857c6b007f64afdb7f15cfe0e0d4eaa31b75c41c608a21138615d740566230093a48b2748b3f1851db1f08d2095efcb32c4646e84637f72f00fbe6e223330",
          "sha256": "6fe793384e3ebf3e4405b5071a5800cddabab1806ac34c08bed296940f908ef1",
          "sha1": "5f9669a24fedcb98c95a1e8cdf75508f083ae4a9",
          "md5": "c8cd04a74b46c8e0e3b92a60878938c3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rscs-central-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-central-android",
          "version": {
            "requires": "0.1.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-rscp-central-android-0.1.3.aar",
          "url": "ble-profile-rscp-central-android-0.1.3.aar",
          "size": 6056,
          "sha512": "169857c6b007f64afdb7f15cfe0e0d4eaa31b75c41c608a21138615d740566230093a48b2748b3f1851db1f08d2095efcb32c4646e84637f72f00fbe6e223330",
          "sha256": "6fe793384e3ebf3e4405b5071a5800cddabab1806ac34c08bed296940f908ef1",
          "sha1": "5f9669a24fedcb98c95a1e8cdf75508f083ae4a9",
          "md5": "c8cd04a74b46c8e0e3b92a60878938c3"
        }
      ]
    }
  ]
}
