{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb4",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb4-0.8.4.jar",
          "url": "ble-characteristic-u2bb4-0.8.4.jar",
          "size": 1439,
          "sha512": "da0535d18ceedf89eb4ea589b5c3dcb26136a9b446b7124b6bc2ba8aa20245f09f750278515dc7ac446264c6d1c877f469e9d3af0cfd9afaabe71d3bd57ddaa2",
          "sha256": "b317036640752b55665fed513a93571f7c571d003ab43ae6ba30619df6c64310",
          "sha1": "dd789af04e0aa7ba8b5869495e59884c772ab4d3",
          "md5": "20aaaf96f24080c04caa969a4ccd3de0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb4-0.8.4.jar",
          "url": "ble-characteristic-u2bb4-0.8.4.jar",
          "size": 1439,
          "sha512": "da0535d18ceedf89eb4ea589b5c3dcb26136a9b446b7124b6bc2ba8aa20245f09f750278515dc7ac446264c6d1c877f469e9d3af0cfd9afaabe71d3bd57ddaa2",
          "sha256": "b317036640752b55665fed513a93571f7c571d003ab43ae6ba30619df6c64310",
          "sha1": "dd789af04e0aa7ba8b5869495e59884c772ab4d3",
          "md5": "20aaaf96f24080c04caa969a4ccd3de0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb4-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2bb4-0.8.4-javadoc.jar",
          "size": 109839,
          "sha512": "f70700dcbedc0ee67981d4934f66301920a964eb59824e8675b88e3227f3fbbceb0afe51b37cd9bc3672ec54fe40183ed0e15ba9e2da4cc6a56154a3ce01e776",
          "sha256": "23414bf9f52ffecaaa2597e1f0052ba1487af38d39854755a3eb12ea06c6b4a7",
          "sha1": "48a7a828c2c3ca636644527cc006bbf75d6ce349",
          "md5": "5d0f8926bb2a8f5c7d11c20dedf154a0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bb4-0.8.4-sources.jar",
          "url": "ble-characteristic-u2bb4-0.8.4-sources.jar",
          "size": 1431,
          "sha512": "4d668047f5f018e51d10714fb1a78a645a92fb1c58991ba0056094eec7f62b25d29a489744a5c82197c99e69478394e175eb2e3a4c51f18e055a01e1a9af7a77",
          "sha256": "36ca71392264d910175db9a49d69dfee174d2800130ff33e98a64e7ec8038d7d",
          "sha1": "b8bcb29c2d95cf3a579820ff2b4f50d0daa69ca6",
          "md5": "38b8430b812d9f013538a96c145756b4"
        }
      ]
    }
  ]
}
