{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2905-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2905",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2905-android-0.1.3.aar",
          "url": "ble-descriptor-u2905-android-0.1.3.aar",
          "size": 3088,
          "sha512": "76c3ecc8789ec84a27e3ee757b59499cced416873b384c1d59fed3c8b008c1357e50529ce1867cc5cbd4c853c7968cbc0170d1d63fadb0a452b3e378d753e3e3",
          "sha256": "c3a88584276fff7029c806a7b3db5281b6542399d4b7ec21c3ea3caf3b159dce",
          "sha1": "51040a5e9bc5c382a4846da6a3c29a322035302c",
          "md5": "9f75d18cbf149a55bdf96dabf3241139"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2905",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2905-android-0.1.3.aar",
          "url": "ble-descriptor-u2905-android-0.1.3.aar",
          "size": 3088,
          "sha512": "76c3ecc8789ec84a27e3ee757b59499cced416873b384c1d59fed3c8b008c1357e50529ce1867cc5cbd4c853c7968cbc0170d1d63fadb0a452b3e378d753e3e3",
          "sha256": "c3a88584276fff7029c806a7b3db5281b6542399d4b7ec21c3ea3caf3b159dce",
          "sha1": "51040a5e9bc5c382a4846da6a3c29a322035302c",
          "md5": "9f75d18cbf149a55bdf96dabf3241139"
        }
      ]
    }
  ]
}
