{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a90-android",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.8.3.aar",
          "url": "ble-characteristic-u2a90-android-0.8.3.aar",
          "size": 2952,
          "sha512": "4095e39545d1f8559d644093d182cf4ce27abeb94bc92dfcf344d250a46046a119a4562297eeffc12980d5c3331a24a0d3540f089f7286b0dfe0a676a3e671a0",
          "sha256": "7ab445d52b7c8028cc586b55703494972b78237e72f3d7483fa9fd5c8f02dde8",
          "sha1": "c45df20dafd84e98ff2b7f72fcfc5e838faf16b8",
          "md5": "bb81c9f6391a8ede71244589f2a4cca8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a90",
          "version": {
            "requires": "0.8.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a90-android-0.8.3.aar",
          "url": "ble-characteristic-u2a90-android-0.8.3.aar",
          "size": 2952,
          "sha512": "4095e39545d1f8559d644093d182cf4ce27abeb94bc92dfcf344d250a46046a119a4562297eeffc12980d5c3331a24a0d3540f089f7286b0dfe0a676a3e671a0",
          "sha256": "7ab445d52b7c8028cc586b55703494972b78237e72f3d7483fa9fd5c8f02dde8",
          "sha1": "c45df20dafd84e98ff2b7f72fcfc5e838faf16b8",
          "md5": "bb81c9f6391a8ede71244589f2a4cca8"
        }
      ]
    }
  ]
}
