{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a03-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-android-0.4.2.aar",
          "url": "ble-characteristic-u2a03-android-0.4.2.aar",
          "size": 3132,
          "sha512": "910f41f5b3f615a9939f4fb18c0c6b1535b1e69a0e60f5362477c5c43616db5ee2e90ecc61994f64e9388a08174fdcbc88b1220c4e675719b47301e873324ad3",
          "sha256": "a1c6f614cb8455a5696e287e74a046606a895dc409e4395b16a696b398374c42",
          "sha1": "c5527489d9718e2bda5356cf3dfcdae0f79d836d",
          "md5": "5438c47641dae846c5a767512358fb22"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a03",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-android-0.4.2.aar",
          "url": "ble-characteristic-u2a03-android-0.4.2.aar",
          "size": 3132,
          "sha512": "910f41f5b3f615a9939f4fb18c0c6b1535b1e69a0e60f5362477c5c43616db5ee2e90ecc61994f64e9388a08174fdcbc88b1220c4e675719b47301e873324ad3",
          "sha256": "a1c6f614cb8455a5696e287e74a046606a895dc409e4395b16a696b398374c42",
          "sha1": "c5527489d9718e2bda5356cf3dfcdae0f79d836d",
          "md5": "5438c47641dae846c5a767512358fb22"
        }
      ]
    }
  ]
}
