{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-hrp-android",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-hrp-android-0.8.5.aar",
          "url": "ble-profile-hrp-android-0.8.5.aar",
          "size": 1202,
          "sha512": "549bb522e1e732d901a6d18dbae0cba809cdef06b4fc66c6c3e7993095a2c9129fae73590931ac7a72e46999d5278919fdcea548c1bf29a8a75a7ee8999979e2",
          "sha256": "86253555343033972fc2a7b557bad6eab29dcfc60d7dc653dc9791e832e8a44c",
          "sha1": "3e74d0e319f38428256f5b2dc8246e300b12cbc3",
          "md5": "01bc77c4b0ab56d2d98374dd6cc8ea15"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-hrp-android-0.8.5.aar",
          "url": "ble-profile-hrp-android-0.8.5.aar",
          "size": 1202,
          "sha512": "549bb522e1e732d901a6d18dbae0cba809cdef06b4fc66c6c3e7993095a2c9129fae73590931ac7a72e46999d5278919fdcea548c1bf29a8a75a7ee8999979e2",
          "sha256": "86253555343033972fc2a7b557bad6eab29dcfc60d7dc653dc9791e832e8a44c",
          "sha1": "3e74d0e319f38428256f5b2dc8246e300b12cbc3",
          "md5": "01bc77c4b0ab56d2d98374dd6cc8ea15"
        }
      ]
    }
  ]
}
