{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aab",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aab-0.8.5.jar",
          "url": "ble-characteristic-u2aab-0.8.5.jar",
          "size": 1458,
          "sha512": "551b60ebe1c8dd3be8393207752f2ea602c88266c26c48e3da20d526dacdb829004a142fb30c0664798f7ddc35904054c1ef8e77058b35be5af25d56b7aa4b52",
          "sha256": "0d98450b64e0a4a8ffdee47ae4914da93bfce244758d16ebcce4d860d68e2037",
          "sha1": "1efbdb283f274c74a24e91c3b0277b6932e9683b",
          "md5": "d54d7cf1f32d85dfa2f7d9ecf2fdda75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aab-0.8.5.jar",
          "url": "ble-characteristic-u2aab-0.8.5.jar",
          "size": 1458,
          "sha512": "551b60ebe1c8dd3be8393207752f2ea602c88266c26c48e3da20d526dacdb829004a142fb30c0664798f7ddc35904054c1ef8e77058b35be5af25d56b7aa4b52",
          "sha256": "0d98450b64e0a4a8ffdee47ae4914da93bfce244758d16ebcce4d860d68e2037",
          "sha1": "1efbdb283f274c74a24e91c3b0277b6932e9683b",
          "md5": "d54d7cf1f32d85dfa2f7d9ecf2fdda75"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aab-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2aab-0.8.5-javadoc.jar",
          "size": 107192,
          "sha512": "022b0d89abab0b4f54cab46853fc081a43c753260491e7dc9457e89b242ca481203b57bfe97f1754d8e9abaeccb3d56172bcccb17e376b8d1ad3f8e9bdbe8474",
          "sha256": "127037620bf873d5d1cc9f418676fb832ec124734a42ab8c0a58bb0fe374e60b",
          "sha1": "dd25ab72dee48e5b3c1d6e02875d1fffe587c1da",
          "md5": "20c5408a5b4a118bdea1c21210afe448"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aab-0.8.5-sources.jar",
          "url": "ble-characteristic-u2aab-0.8.5-sources.jar",
          "size": 1468,
          "sha512": "5225ee4d0695754f378e6832ad3a4046cdea138ec9386867c88dfef8b3f16a7c413b15367c99770da444cd00d541387e0b251e9d4779a568a4c7bf7fd3d7ae49",
          "sha256": "729112d184f5cf2475e4177bb6090517edc35f2e47c95584c7b977690921928c",
          "sha1": "46d92c3eec950bbbc5b1b67c6462163407827185",
          "md5": "08f2852402ad1d9c7b5804e376f41646"
        }
      ]
    }
  ]
}
