{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab1-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab1",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-android-0.8.6.aar",
          "url": "ble-characteristic-u2ab1-android-0.8.6.aar",
          "size": 3098,
          "sha512": "e81ddcd3c5bbd4f39c26ebd34e2247f6508bf71b3d6419862da7ea6e719726aaaecd4a254687d43955846436c70d1dc47f140680e84b57dd037e28994c966aa9",
          "sha256": "2fcf685df0357ce1c5e85cd5e658c10a2ec460f33b568be76d04649465ef1b6d",
          "sha1": "f96b60385fb07c70ebaf27515868351515abd72f",
          "md5": "f9f8efa2f66b81f0a862b10f9741739e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab1",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-android-0.8.6.aar",
          "url": "ble-characteristic-u2ab1-android-0.8.6.aar",
          "size": 3098,
          "sha512": "e81ddcd3c5bbd4f39c26ebd34e2247f6508bf71b3d6419862da7ea6e719726aaaecd4a254687d43955846436c70d1dc47f140680e84b57dd037e28994c966aa9",
          "sha256": "2fcf685df0357ce1c5e85cd5e658c10a2ec460f33b568be76d04649465ef1b6d",
          "sha1": "f96b60385fb07c70ebaf27515868351515abd72f",
          "md5": "f9f8efa2f66b81f0a862b10f9741739e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab1-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ab1-android-0.8.6-sources.jar",
          "size": 2191,
          "sha512": "58d57a1627b09b1dc1cd39e893be9de4b2e84789618fe727e04791962c0350a70417d6c50c93ecea7a8fa34f92ef469dfded40ca13f458b5c9d52469a6f9c53d",
          "sha256": "ae5e39a40ce3539b072888ec87cb51264ed38e00dd18c95844ee18e6ef2d868e",
          "sha1": "c6c73a623e3bada527f74e320237dae1bf7fd0f2",
          "md5": "04add225e8c01aa0536e1ad692b51857"
        }
      ]
    }
  ]
}
