{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-tps-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-tps-android-0.4.3.aar",
          "url": "ble-service-central-tps-android-0.4.3.aar",
          "size": 3319,
          "sha512": "11e3f11df0e04730bf7caccb9f6861bce2a7825c346a9e5b862aa8e380d8e962429faf068a18222d64b2baf7a3e7d44615d723a8ea7ec377ce6272549865f1ab",
          "sha256": "683efcf14da7ae61320a44e8b71cc2efb7711a85d6c650040fc63530c33b88f0",
          "sha1": "9cd6e8f3c88ab6f218c006690981b1def93b34ad",
          "md5": "f9b5914d0e75a3e4d228a7ba8c7b0d10"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-tps-android",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-tps-android-0.4.3.aar",
          "url": "ble-service-central-tps-android-0.4.3.aar",
          "size": 3319,
          "sha512": "11e3f11df0e04730bf7caccb9f6861bce2a7825c346a9e5b862aa8e380d8e962429faf068a18222d64b2baf7a3e7d44615d723a8ea7ec377ce6272549865f1ab",
          "sha256": "683efcf14da7ae61320a44e8b71cc2efb7711a85d6c650040fc63530c33b88f0",
          "sha1": "9cd6e8f3c88ab6f218c006690981b1def93b34ad",
          "md5": "f9b5914d0e75a3e4d228a7ba8c7b0d10"
        }
      ]
    }
  ]
}
