{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a81-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a81",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-android-0.2.7.aar",
          "url": "ble-characteristic-u2a81-android-0.2.7.aar",
          "size": 3149,
          "sha512": "82721c274595f7b60e23b8a13adfb455ce075cec004e4b12e7fef37e3afb97e1108afb9d97ab9a59088016c35fa42cba8cefa4f09f090a86592f59dc6c8665b9",
          "sha256": "5c8d3603281bf91a15226867f9ea4e270a77ef769d68f20d5a50821e515f9170",
          "sha1": "549506273d600ccbf5c0b26f5c250a56c3d79a35",
          "md5": "2968b06ed1318c1036bfd7cb514c29fb"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a81",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a81-android-0.2.7.aar",
          "url": "ble-characteristic-u2a81-android-0.2.7.aar",
          "size": 3149,
          "sha512": "82721c274595f7b60e23b8a13adfb455ce075cec004e4b12e7fef37e3afb97e1108afb9d97ab9a59088016c35fa42cba8cefa4f09f090a86592f59dc6c8665b9",
          "sha256": "5c8d3603281bf91a15226867f9ea4e270a77ef769d68f20d5a50821e515f9170",
          "sha1": "549506273d600ccbf5c0b26f5c250a56c3d79a35",
          "md5": "2968b06ed1318c1036bfd7cb514c29fb"
        }
      ]
    }
  ]
}
