{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u290d-android",
    "version": "0.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tw7yksuo3jch5jyqfw3o6ilmt4"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-android-0.4.6.aar",
          "url": "ble-descriptor-u290d-android-0.4.6.aar",
          "size": 3163,
          "sha512": "e25c7b2cf9afaf8fe0a2115adffefe8519016a6c0ad17b910b58612f08f88a74e32bd609c7618752dddfb1a9fb9dce7329136deb6fa718fe6da9b040643a233e",
          "sha256": "e326e07535c3ed3009ef9beadbf65f292028088d902c70442b4c285e2bc8f3cb",
          "sha1": "e38c8fedfd8e740898dab1bcb8e42d3f6f050f4c",
          "md5": "1f8b53dd27457c0e6b3b40abd68354da"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u290d",
          "version": {
            "requires": "0.4.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u290d-android-0.4.6.aar",
          "url": "ble-descriptor-u290d-android-0.4.6.aar",
          "size": 3163,
          "sha512": "e25c7b2cf9afaf8fe0a2115adffefe8519016a6c0ad17b910b58612f08f88a74e32bd609c7618752dddfb1a9fb9dce7329136deb6fa718fe6da9b040643a233e",
          "sha256": "e326e07535c3ed3009ef9beadbf65f292028088d902c70442b4c285e2bc8f3cb",
          "sha1": "e38c8fedfd8e740898dab1bcb8e42d3f6f050f4c",
          "md5": "1f8b53dd27457c0e6b3b40abd68354da"
        }
      ]
    }
  ]
}
