{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6a-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "md2hzulcvrbjbp3omyeiu4n5fi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.1.3.aar",
          "url": "ble-characteristic-u2a6a-android-0.1.3.aar",
          "size": 2842,
          "sha512": "c69a3f7793f90fb54e05b84777a7b234704c53d7b28e2d585beafb136eeab6316fd11055988c904077306b48a48f3ec9aae949d23b23a0be6f1be14f25be7b51",
          "sha256": "d66c4efd3f99bc93577e35382678beb0f2244af37a999b0bb1e5cca5c51df646",
          "sha1": "edc7ac5f174e9a3dfe23cce93c4ba3d60d85e506",
          "md5": "242c3d8cdf25d88f3a087fc994b579ef"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.1.3.aar",
          "url": "ble-characteristic-u2a6a-android-0.1.3.aar",
          "size": 2842,
          "sha512": "c69a3f7793f90fb54e05b84777a7b234704c53d7b28e2d585beafb136eeab6316fd11055988c904077306b48a48f3ec9aae949d23b23a0be6f1be14f25be7b51",
          "sha256": "d66c4efd3f99bc93577e35382678beb0f2244af37a999b0bb1e5cca5c51df646",
          "sha1": "edc7ac5f174e9a3dfe23cce93c4ba3d60d85e506",
          "md5": "242c3d8cdf25d88f3a087fc994b579ef"
        }
      ]
    }
  ]
}
