{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a93-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.8.6.aar",
          "url": "ble-characteristic-u2a93-android-0.8.6.aar",
          "size": 3196,
          "sha512": "a23087018816584fadc70945ec53e09a1c57bc7af5e37e778acfac55bc5323eb32aa0b6c98de4ec13571dd6dde475cdab955854be5378a506681fe8aedb54381",
          "sha256": "337f815a5e2d235044f73969bd6003189aea3619cd26c8da293510487b666e07",
          "sha1": "c95c27474d2b020fd3d6b52e2df91c099224fd97",
          "md5": "68ed1b14e4b3eea8362eb414d8cfe819"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a93",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a93-android-0.8.6.aar",
          "url": "ble-characteristic-u2a93-android-0.8.6.aar",
          "size": 3196,
          "sha512": "a23087018816584fadc70945ec53e09a1c57bc7af5e37e778acfac55bc5323eb32aa0b6c98de4ec13571dd6dde475cdab955854be5378a506681fe8aedb54381",
          "sha256": "337f815a5e2d235044f73969bd6003189aea3619cd26c8da293510487b666e07",
          "sha1": "c95c27474d2b020fd3d6b52e2df91c099224fd97",
          "md5": "68ed1b14e4b3eea8362eb414d8cfe819"
        }
      ]
    }
  ]
}
