{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8b-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.8.6.aar",
          "url": "ble-characteristic-u2a8b-android-0.8.6.aar",
          "size": 3209,
          "sha512": "705a8ab861165088394fa8faddc12ac2cdfa24eb27920c843297e22d96acd881f5a38e86101a3a101f64751649dacd823e2d11cb10f31a6a37903ed37482bfc0",
          "sha256": "de65f60323cbeb23c1052a6abfd13175bb1d402cb64ecd2191df32d8d13d2257",
          "sha1": "a3acd7a7dc7e3cc3e5e46584d81379a990fb3e31",
          "md5": "8a50b17742e6ac37fb1f286096885163"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8b",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8b-android-0.8.6.aar",
          "url": "ble-characteristic-u2a8b-android-0.8.6.aar",
          "size": 3209,
          "sha512": "705a8ab861165088394fa8faddc12ac2cdfa24eb27920c843297e22d96acd881f5a38e86101a3a101f64751649dacd823e2d11cb10f31a6a37903ed37482bfc0",
          "sha256": "de65f60323cbeb23c1052a6abfd13175bb1d402cb64ecd2191df32d8d13d2257",
          "sha1": "a3acd7a7dc7e3cc3e5e46584d81379a990fb3e31",
          "md5": "8a50b17742e6ac37fb1f286096885163"
        }
      ]
    }
  ]
}
