{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa1",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.6.jar",
          "url": "ble-characteristic-u2aa1-0.8.6.jar",
          "size": 2081,
          "sha512": "70d8dc27b45268efd35cb28b5f51b85b2cdbff16929fb296c3e8f1efc93610bdd07a7c43ca96174987159072af42df682d827d7d3d892ce92871a5f124dedcc4",
          "sha256": "0e79a2fea38da5226a34a670e3539039176f541d2a9b843971cbafa4de04d48a",
          "sha1": "50fda89f35f1c91c2e9eb14504f33da58f071c89",
          "md5": "16a3eebc81ab4e77dcc302002aae2988"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.6.jar",
          "url": "ble-characteristic-u2aa1-0.8.6.jar",
          "size": 2081,
          "sha512": "70d8dc27b45268efd35cb28b5f51b85b2cdbff16929fb296c3e8f1efc93610bdd07a7c43ca96174987159072af42df682d827d7d3d892ce92871a5f124dedcc4",
          "sha256": "0e79a2fea38da5226a34a670e3539039176f541d2a9b843971cbafa4de04d48a",
          "sha1": "50fda89f35f1c91c2e9eb14504f33da58f071c89",
          "md5": "16a3eebc81ab4e77dcc302002aae2988"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2aa1-0.8.6-javadoc.jar",
          "size": 109989,
          "sha512": "ee025ceda7d17c616af484fbe80d9840fc945fc9378b7f40f440d57844fdfb28713840b9aa824c6aef0f6e41c640e5aca03ee7f56cef1a4e36edfd922ef5f447",
          "sha256": "8cbb189460c93708cb79b055735b5ecc5e2a6af5bf09d43e0bde04c60942a2c1",
          "sha1": "eb0fcc491aa45f77aee2530c26122e8686de33c4",
          "md5": "72b3d442c9f780c5b169c9be0bae3426"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa1-0.8.6-sources.jar",
          "url": "ble-characteristic-u2aa1-0.8.6-sources.jar",
          "size": 1894,
          "sha512": "135279e9a89deb6bfb296854ca221cbb71231cdbedab727fa02ea42fc77c8bac5ec004bfe53528c93d9e668d7d38a2bdfefee9a7a7e6288011f388485b4743f2",
          "sha256": "7e8b7eb6f2adced9e652750b2200d029b5f8fe740b20d3923fd8089d7a871401",
          "sha1": "a32df673f6cd21c6cb0b15382c9f85f34aa781f5",
          "md5": "79328b8b7b6f648973c5e2da43ded300"
        }
      ]
    }
  ]
}
