{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-lls-central-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "swq2gxvgereszma3nz5hc5y3xq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lls-central-android-0.1.6.aar",
          "url": "ble-service-lls-central-android-0.1.6.aar",
          "size": 3561,
          "sha512": "a88159540928856b91f7e4bb5015d3c837f088780795f1e905ab647ec1e50c7d0be54d03296534e3b31f5009f7fcc9bfd714e5954d466577562f4dc8c439e615",
          "sha256": "e9332d0d64f8c91f8468346c09ac510b8c3e94d2928aba155b5ab3ad62f2e47f",
          "sha1": "add2f0e249f160490227552b9fb8c4019b33e01d",
          "md5": "f762b474f96050a6b19f59cbb37d7aad"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-lls-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-lls-central-android-0.1.6.aar",
          "url": "ble-service-lls-central-android-0.1.6.aar",
          "size": 3561,
          "sha512": "a88159540928856b91f7e4bb5015d3c837f088780795f1e905ab647ec1e50c7d0be54d03296534e3b31f5009f7fcc9bfd714e5954d466577562f4dc8c439e615",
          "sha256": "e9332d0d64f8c91f8468346c09ac510b8c3e94d2928aba155b5ab3ad62f2e47f",
          "sha1": "add2f0e249f160490227552b9fb8c4019b33e01d",
          "md5": "f762b474f96050a6b19f59cbb37d7aad"
        }
      ]
    }
  ]
}
