{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a03",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.1.jar",
          "url": "ble-characteristic-u2a03-0.8.1.jar",
          "size": 1813,
          "sha512": "9923bea42b22b4698248354236f8944721a541391cd6536e4d4e1437d58c050dbe9de985fea0d6272ced24968604bb03a2bb848b8caa173b0c751addc3decf74",
          "sha256": "4b68dfa51cbe8e21865741b9a20f84e0c56c7218a776cde4f0b9e032ed530273",
          "sha1": "1e750c746b78cde19d018e33ef7c58d09583f8c8",
          "md5": "3da3b22930c55f26e796973efa44e7b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.1.jar",
          "url": "ble-characteristic-u2a03-0.8.1.jar",
          "size": 1813,
          "sha512": "9923bea42b22b4698248354236f8944721a541391cd6536e4d4e1437d58c050dbe9de985fea0d6272ced24968604bb03a2bb848b8caa173b0c751addc3decf74",
          "sha256": "4b68dfa51cbe8e21865741b9a20f84e0c56c7218a776cde4f0b9e032ed530273",
          "sha1": "1e750c746b78cde19d018e33ef7c58d09583f8c8",
          "md5": "3da3b22930c55f26e796973efa44e7b0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.1-javadoc.jar",
          "url": "ble-characteristic-u2a03-0.8.1-javadoc.jar",
          "size": 110093,
          "sha512": "f4745e6ce47ff4dd5022112f0819d64c2dfdc41a26ce5c33509faf8ae139d88f031ef2c51ab098aa2f7505a6ac4111da70b3d3dd68242996c5e081616aadc3f8",
          "sha256": "1569b3eef1386a403916fb597575e889a7fa0e55681da9162e5936098e4ab6f0",
          "sha1": "94000633939644c85961915584fd71699be25425",
          "md5": "eff14c142068ab2723ce28ed09a9cfc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.1-sources.jar",
          "url": "ble-characteristic-u2a03-0.8.1-sources.jar",
          "size": 1649,
          "sha512": "b7140dae678ecb68d3118f532071b2771407086ef2d7d4575b35b7b56a4a85c60cfb62165cadf3b4652aa4f9b1133004776d9b9b6bc9269188c10b65b44c1836",
          "sha256": "909f695c1b927261ddea871565bb94c54944fb4000b6acad68e4f5c80741c7ac",
          "sha1": "ba12bb06992073e936c3662eab1284cbe78c1b16",
          "md5": "54595cfb9f909befed056d0a937a230d"
        }
      ]
    }
  ]
}
