{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b47-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b47",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b47-android-0.8.6.aar",
          "url": "ble-characteristic-u2b47-android-0.8.6.aar",
          "size": 3108,
          "sha512": "ba5cf80d62e0e07f67a2fc6f8807efaec6f46a8522466651d2f37bdf49f9d4d95217de7a9dee7a000402ede752cc0a7fdae8fef22305fff8a9a45a1597b6cec4",
          "sha256": "c339cf4e28ede2d078717a67405fc64562c8ccbb80376fe724f79f79bd07789b",
          "sha1": "26625607115164276c6ddeb041b14d2688b98277",
          "md5": "7779051f352e4c6e8d73c86f826fc666"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b47",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b47-android-0.8.6.aar",
          "url": "ble-characteristic-u2b47-android-0.8.6.aar",
          "size": 3108,
          "sha512": "ba5cf80d62e0e07f67a2fc6f8807efaec6f46a8522466651d2f37bdf49f9d4d95217de7a9dee7a000402ede752cc0a7fdae8fef22305fff8a9a45a1597b6cec4",
          "sha256": "c339cf4e28ede2d078717a67405fc64562c8ccbb80376fe724f79f79bd07789b",
          "sha1": "26625607115164276c6ddeb041b14d2688b98277",
          "md5": "7779051f352e4c6e8d73c86f826fc666"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b47-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b47-android-0.8.6-sources.jar",
          "size": 2193,
          "sha512": "f389f1aeba35584d271c7952464ff365e67807946bfe7b18ef5c5793885a23b0401db626573902f9db204dce69f9dbcc8b06b3d2f09dfb36aeef088fc4eaab65",
          "sha256": "7cdfe3c912cd543941930da44862e76ee0a8e524351434c5161b723d3a26ff50",
          "sha1": "dbaad275d660b1b6f0c08fa1c4009d9bcad3d9e2",
          "md5": "aad0b8c02b7640633da3c330dd1fab66"
        }
      ]
    }
  ]
}
