{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa1-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa1",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa1-android-0.8.6.aar",
          "size": 3155,
          "sha512": "a72ba33919f8f6c77c9dfc9b94da0115ec72a219f2e4aa622670594ce5b296382f52524eb6fef97e71db68b267e49fbab4561e7b49a473e16764b7eb0c70a53e",
          "sha256": "78bfc487a43f406ddf63820004bbe775964ffb52018c71a420239a6d777af5b3",
          "sha1": "ca25db70c77cddd6affb104fcc7471968b24e3bf",
          "md5": "207c53fc3e5972dcde632e770c7f7a8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa1",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-android-0.8.6.aar",
          "url": "ble-characteristic-u2aa1-android-0.8.6.aar",
          "size": 3155,
          "sha512": "a72ba33919f8f6c77c9dfc9b94da0115ec72a219f2e4aa622670594ce5b296382f52524eb6fef97e71db68b267e49fbab4561e7b49a473e16764b7eb0c70a53e",
          "sha256": "78bfc487a43f406ddf63820004bbe775964ffb52018c71a420239a6d777af5b3",
          "sha1": "ca25db70c77cddd6affb104fcc7471968b24e3bf",
          "md5": "207c53fc3e5972dcde632e770c7f7a8c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa1-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2aa1-android-0.8.6-sources.jar",
          "size": 2245,
          "sha512": "62a52694ff1690407e2af8fcd3cb3f847cb85677f655cf1be6610ef0756c85bf0fb752963ebc2eacee2cd2679f6777aceecd712cd7f55756a9d4eff0b930ffb5",
          "sha256": "3a002a40d8d60e53e0e4d84777931643f8e1d45e0e37f9a9bd37ce685e85b14f",
          "sha1": "cdbfc9300d3d048c5029ab43aea486847bb1d93d",
          "md5": "052c2047e2d9b4bbe76443af71abf78a"
        }
      ]
    }
  ]
}
