{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bb7-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb7",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb7-android-0.4.3.aar",
          "url": "ble-characteristic-u2bb7-android-0.4.3.aar",
          "size": 3076,
          "sha512": "e3a4e33d377ecf0ad30ed0f92767ff27defd0a3dd48f5697f6f4ca7451aba46608f6470442958fb696c141095a19296ec011c210fe47cf8c2e7de1a71e7125be",
          "sha256": "12e854aa947e52acbb9790339a0f71ea5d0f8a0bd5a6e25323f078df555e48d8",
          "sha1": "687560dacd2dabe77a5ea5cf2ce0a3a00b1105a5",
          "md5": "15314ebcf9809088015d421e9a115d11"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2bb7",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bb7-android-0.4.3.aar",
          "url": "ble-characteristic-u2bb7-android-0.4.3.aar",
          "size": 3076,
          "sha512": "e3a4e33d377ecf0ad30ed0f92767ff27defd0a3dd48f5697f6f4ca7451aba46608f6470442958fb696c141095a19296ec011c210fe47cf8c2e7de1a71e7125be",
          "sha256": "12e854aa947e52acbb9790339a0f71ea5d0f8a0bd5a6e25323f078df555e48d8",
          "sha1": "687560dacd2dabe77a5ea5cf2ce0a3a00b1105a5",
          "md5": "15314ebcf9809088015d421e9a115d11"
        }
      ]
    }
  ]
}
