{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.8.6.aar",
          "url": "ble-characteristic-u2a04-android-0.8.6.aar",
          "size": 3251,
          "sha512": "dfe7f5a1b81463ac74d50a00f22f16f4c52046bec947568a75d156bb0d4e9a07a7f2af0857dd23338b3018fac42a19b5799658a5e5f25dd8eb004343dd6aa23c",
          "sha256": "55bf5372aa6d8cabc0ece2cdeefeb1483a9a58a0045b8f8be1b53e8446812947",
          "sha1": "171775803c5e01cd83218fec5d3d28b57a0dee4c",
          "md5": "d3938270c4188ecae0adb7845a82cee7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.8.6.aar",
          "url": "ble-characteristic-u2a04-android-0.8.6.aar",
          "size": 3251,
          "sha512": "dfe7f5a1b81463ac74d50a00f22f16f4c52046bec947568a75d156bb0d4e9a07a7f2af0857dd23338b3018fac42a19b5799658a5e5f25dd8eb004343dd6aa23c",
          "sha256": "55bf5372aa6d8cabc0ece2cdeefeb1483a9a58a0045b8f8be1b53e8446812947",
          "sha1": "171775803c5e01cd83218fec5d3d28b57a0dee4c",
          "md5": "d3938270c4188ecae0adb7845a82cee7"
        }
      ]
    }
  ]
}
