{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-android",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "x6nyasohnvdrtpp4affpidlfoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.1.10.aar",
          "url": "ble-profile-peripheral-android-0.1.10.aar",
          "size": 2357,
          "sha512": "d747ff3fcb866fb07c6bef6c6731c67ed2bfbf69bdb8c015b59a262a99bba45cdd05ce801cffe266c79e9caf9fd70be00da1c44b79e548c257fb71ae7cb2c789",
          "sha256": "dc339dd95202d4d51b5a86f6db7a4e13487af2edcf54f485dc1dfbc5aebb3554",
          "sha1": "fc9e0b558de5d1853500f0c9cbb0f79f9623ed99",
          "md5": "6034d79482d7bbea5a65a2cdbb1b70fa"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-android-0.1.10.aar",
          "url": "ble-profile-peripheral-android-0.1.10.aar",
          "size": 2357,
          "sha512": "d747ff3fcb866fb07c6bef6c6731c67ed2bfbf69bdb8c015b59a262a99bba45cdd05ce801cffe266c79e9caf9fd70be00da1c44b79e548c257fb71ae7cb2c789",
          "sha256": "dc339dd95202d4d51b5a86f6db7a4e13487af2edcf54f485dc1dfbc5aebb3554",
          "sha1": "fc9e0b558de5d1853500f0c9cbb0f79f9623ed99",
          "md5": "6034d79482d7bbea5a65a2cdbb1b70fa"
        }
      ]
    }
  ]
}
