{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abc-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abc",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abc-android-0.8.12.aar",
          "url": "ble-characteristic-u2abc-android-0.8.12.aar",
          "size": 5098,
          "sha512": "f1970a2b9eaee8c825f268c3853209dc959a9083ea24bcbb670af41156b023d6b0db2a6c9577b181a978676e8a4c32b54f05d4f5f5ae03157ab84e09390737ab",
          "sha256": "83ad671ea71fe977b88f3f8ae42c6596b23b5282c50efe6ad49b96a1c7c5e66e",
          "sha1": "ff2fe038d487684a6243fcb372c8e78082ead207",
          "md5": "be711c3d44e317ff14aefa13e9f2e155"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abc",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abc-android-0.8.12.aar",
          "url": "ble-characteristic-u2abc-android-0.8.12.aar",
          "size": 5098,
          "sha512": "f1970a2b9eaee8c825f268c3853209dc959a9083ea24bcbb670af41156b023d6b0db2a6c9577b181a978676e8a4c32b54f05d4f5f5ae03157ab84e09390737ab",
          "sha256": "83ad671ea71fe977b88f3f8ae42c6596b23b5282c50efe6ad49b96a1c7c5e66e",
          "sha1": "ff2fe038d487684a6243fcb372c8e78082ead207",
          "md5": "be711c3d44e317ff14aefa13e9f2e155"
        }
      ]
    }
  ]
}
