{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b80-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b80",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b80-android-0.8.12.aar",
          "url": "ble-characteristic-u2b80-android-0.8.12.aar",
          "size": 3160,
          "sha512": "623d7ee6a5660d2b29292958e0b7f1b79c166707a3d345751e80517b3fc752e8f61bdf541de8aa6af3517258ba23c815a93be9c829db923a45fe8dac30515bb7",
          "sha256": "37a35e03a3cbba05d9c72e721d6c8a45cd87e566c26ff0ba28a725c8bab87be9",
          "sha1": "9fc7378908c631f98b0e5b97e9f7f7439d4d383c",
          "md5": "7b7a8d1576f5bef7c25b523ae907c743"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b80",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b80-android-0.8.12.aar",
          "url": "ble-characteristic-u2b80-android-0.8.12.aar",
          "size": 3160,
          "sha512": "623d7ee6a5660d2b29292958e0b7f1b79c166707a3d345751e80517b3fc752e8f61bdf541de8aa6af3517258ba23c815a93be9c829db923a45fe8dac30515bb7",
          "sha256": "37a35e03a3cbba05d9c72e721d6c8a45cd87e566c26ff0ba28a725c8bab87be9",
          "sha1": "9fc7378908c631f98b0e5b97e9f7f7439d4d383c",
          "md5": "7b7a8d1576f5bef7c25b523ae907c743"
        }
      ]
    }
  ]
}
