{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-core-android",
    "version": "0.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "gylyrjmyl5chpnmjapw4ndvvze"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-core-android-0.1.6.aar",
          "url": "ble-characteristic-core-android-0.1.6.aar",
          "size": 1641,
          "sha512": "38afe7601db6c69e4ee939ada5ae3168db76285df9857901eca3032b6a00a2b1e5bc5d56b69be2186d2572f8052fd6c9117a6fdb78166f4362e8e6727eeb3883",
          "sha256": "2855140ef72f380683e50c172d643e897d8474c56adff582aec7b59389e1d888",
          "sha1": "110955a61fb3d70c6078d7388dd2d1d91ea8b55d",
          "md5": "15e4580fd1e50a45506fddfd708edfbe"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-core-android-0.1.6.aar",
          "url": "ble-characteristic-core-android-0.1.6.aar",
          "size": 1641,
          "sha512": "38afe7601db6c69e4ee939ada5ae3168db76285df9857901eca3032b6a00a2b1e5bc5d56b69be2186d2572f8052fd6c9117a6fdb78166f4362e8e6727eeb3883",
          "sha256": "2855140ef72f380683e50c172d643e897d8474c56adff582aec7b59389e1d888",
          "sha1": "110955a61fb3d70c6078d7388dd2d1d91ea8b55d",
          "md5": "15e4580fd1e50a45506fddfd708edfbe"
        }
      ]
    }
  ]
}
