{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-fmp-android",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zckqgxv52jertg33sctsfjorzm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-fmp-android-0.1.1.aar",
          "url": "ble-profile-fmp-android-0.1.1.aar",
          "size": 1023,
          "sha512": "552499931437f47fb8238d8d613b1c7c784558c2c3d604b0cf3d63e2ca0f771509d2b3bb5be83db7760c81567dbaca22c58c65af9d2db01a40eb65f3c21fd401",
          "sha256": "fe6141d1a2533d559d3d32af81098213b4c10c97cac36cb4a6b4c5290a8bcf96",
          "sha1": "69af92b44a16dc2bfebd19dca7f1cafa5c48662e",
          "md5": "5b55ef9c2a07eecfc95196871f305c4b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-fmp-android-0.1.1.aar",
          "url": "ble-profile-fmp-android-0.1.1.aar",
          "size": 1023,
          "sha512": "552499931437f47fb8238d8d613b1c7c784558c2c3d604b0cf3d63e2ca0f771509d2b3bb5be83db7760c81567dbaca22c58c65af9d2db01a40eb65f3c21fd401",
          "sha256": "fe6141d1a2533d559d3d32af81098213b4c10c97cac36cb4a6b4c5290a8bcf96",
          "sha1": "69af92b44a16dc2bfebd19dca7f1cafa5c48662e",
          "md5": "5b55ef9c2a07eecfc95196871f305c4b"
        }
      ]
    }
  ]
}
