{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b91",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b91-0.8.9.jar",
          "url": "ble-characteristic-u2b91-0.8.9.jar",
          "size": 1475,
          "sha512": "eb7256e070e4ebde76419621918db3d3d638b1feab2820d76d787c3f5a4faa45f250a6fcce40a08406b0a761dfef0d432942b2b4cf420babfe90e8a71e1dca50",
          "sha256": "42ca71e60ea9d394cdcd24581f0cb7a6873b842d8fb8986390868ae4936ae0b2",
          "sha1": "69631b39361e1eb585e109e51ae48f345dc8e257",
          "md5": "6e49b17568d1e7c01a74cb6b2595bb51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b91-0.8.9.jar",
          "url": "ble-characteristic-u2b91-0.8.9.jar",
          "size": 1475,
          "sha512": "eb7256e070e4ebde76419621918db3d3d638b1feab2820d76d787c3f5a4faa45f250a6fcce40a08406b0a761dfef0d432942b2b4cf420babfe90e8a71e1dca50",
          "sha256": "42ca71e60ea9d394cdcd24581f0cb7a6873b842d8fb8986390868ae4936ae0b2",
          "sha1": "69631b39361e1eb585e109e51ae48f345dc8e257",
          "md5": "6e49b17568d1e7c01a74cb6b2595bb51"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b91-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2b91-0.8.9-javadoc.jar",
          "size": 107227,
          "sha512": "b48a36b3ba01b2b78a9bc747cec8f0efe5548e4ecdabdf912c7b24c51770c853fb52399397c88a966f59a6b1d87c45a9f8ed260645f122e2c61e0bccf54ed120",
          "sha256": "43f18bb5bae1235913cb2ca1962d4fb6a01c9745404b043189d531aefb382175",
          "sha1": "f5eded9881f2cc3d135519eba2c234dfd31017f6",
          "md5": "0488faa17aa5aa6710686ccf4942df96"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b91-0.8.9-sources.jar",
          "url": "ble-characteristic-u2b91-0.8.9-sources.jar",
          "size": 1461,
          "sha512": "72859ba52e3dbd2e947ed69f40100d58bf904e5129509fdb10cee89404ee2e0b5cd927fde774497fd0c7b1b959e7f6d5064be85fd2c0891e462e7994cb20ed8c",
          "sha256": "20b9c73a6b9ea73bcab6be28498bedced1dd24e2cd3b6956d8ccaa9558eb9f6f",
          "sha1": "66f848baf56460e2adcead02de0e994d11bb67a4",
          "md5": "04a4ed78de64b9adaeef739853e307bd"
        }
      ]
    }
  ]
}
