{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4e",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.7.jar",
          "url": "ble-characteristic-u2b4e-0.8.7.jar",
          "size": 3373,
          "sha512": "da8429e8d8268662aea464debb50afbe6f9a28adb4630f3691fdb9738d7934e35dd14fb681b18897cdfbe2de0d2ddad22e8b7025f3270861641fae4cde8c45dd",
          "sha256": "eaef8a68d909ce14bee22f656964a8f9ebec3a8a6fb8ca947a23cbf3ecead903",
          "sha1": "05d673b07972cb9c1b3287ebfabe54ba426a0136",
          "md5": "546f726ce03ae42d556b95a4c044cc5f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.7.jar",
          "url": "ble-characteristic-u2b4e-0.8.7.jar",
          "size": 3373,
          "sha512": "da8429e8d8268662aea464debb50afbe6f9a28adb4630f3691fdb9738d7934e35dd14fb681b18897cdfbe2de0d2ddad22e8b7025f3270861641fae4cde8c45dd",
          "sha256": "eaef8a68d909ce14bee22f656964a8f9ebec3a8a6fb8ca947a23cbf3ecead903",
          "sha1": "05d673b07972cb9c1b3287ebfabe54ba426a0136",
          "md5": "546f726ce03ae42d556b95a4c044cc5f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b4e-0.8.7-javadoc.jar",
          "size": 112877,
          "sha512": "ce7e02ce93494e898e3ab855c63621fb2780d1fc6b9a0009ea42dc621c06c3753cce1b2866c724ae1a66018b7b625c97d58d1c09847dee61444c3ac4389cdf1a",
          "sha256": "ca975bd182af8ae4519c6c2fddcf4009a1cf15e993c1ffa915a56a67dd01a5c0",
          "sha1": "ea45de4163f36d0e7d93ca1e3f8b8167b81ca361",
          "md5": "39fd2d4fd4ccdedcc40ebcc877bd2c20"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4e-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b4e-0.8.7-sources.jar",
          "size": 3094,
          "sha512": "53642c4805767300064d336139e3cf92c71b7fa82f0be41407836a43ab785be536b703548096e247e81008d251a43fc9293429b0b3987bf8f0d461882fbc69a2",
          "sha256": "110a1fd18ba7f1ae8e0db843066d6a1f810567f05a02c2396d901486c5972899",
          "sha1": "af59be475dccfc721d2e7f85d43062d71e2add48",
          "md5": "0525a6dfd1fbfb56def0a0df3298fd01"
        }
      ]
    }
  ]
}
