{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2900",
    "version": "0.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-0.8.0.jar",
          "url": "ble-descriptor-u2900-0.8.0.jar",
          "size": 2263,
          "sha512": "e383f506c4d6c1a5a82978f08cf5f486f3344907c51674d840d45ccbade314ec7a8eb104708d162d28b6d4f739dc457aaf462723214f0326123cd5e1c5f163c8",
          "sha256": "6df15203b52e93085e22cf47b074dfcab6ce219471ac117876ee2d63ffe6b39e",
          "sha1": "1ed3c8aed05900091443ac4b00c8fb0f76db1b33",
          "md5": "408cde4e73c687b2972cf05eea0d2f7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-0.8.0.jar",
          "url": "ble-descriptor-u2900-0.8.0.jar",
          "size": 2263,
          "sha512": "e383f506c4d6c1a5a82978f08cf5f486f3344907c51674d840d45ccbade314ec7a8eb104708d162d28b6d4f739dc457aaf462723214f0326123cd5e1c5f163c8",
          "sha256": "6df15203b52e93085e22cf47b074dfcab6ce219471ac117876ee2d63ffe6b39e",
          "sha1": "1ed3c8aed05900091443ac4b00c8fb0f76db1b33",
          "md5": "408cde4e73c687b2972cf05eea0d2f7a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2900-0.8.0-javadoc.jar",
          "url": "ble-descriptor-u2900-0.8.0-javadoc.jar",
          "size": 111763,
          "sha512": "353d0cba483419cb5f87b78f8861716d5140674f44c7cebaf9cd33e8397c1fb4079a43b3f9b392085b1af3084b46db7362d0aa4cea21091ff321c2926d4c3b93",
          "sha256": "adc6f00427341586b8642fd7f78e528d6f549994495f5adf32520868d2a20787",
          "sha1": "b5ee35be5f4c1da0689f43104029a6aa2202f582",
          "md5": "a1e93e8bb199b14abcaf641b2a2bdcb1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2900-0.8.0-sources.jar",
          "url": "ble-descriptor-u2900-0.8.0-sources.jar",
          "size": 2155,
          "sha512": "9502d5a6faf3313db84b0b0fcdbadc1517732180cf8fd6bf45d99f29be5535f4720460c838dda0a44fe86a250cac2eedb38a55a266eda51ee17c1535b62eeefb",
          "sha256": "d15da585dd5a33b9d052a32762d785a8436183cf45f34c3bde5faa31d7446bdb",
          "sha1": "eed868005be4f0f77c5323ab5f43def0be970eb9",
          "md5": "b9c2796c1fa2b4c6e7ff085a984a819f"
        }
      ]
    }
  ]
}
