{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa2",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa2-0.6.1.jar",
          "url": "ble-characteristic-u2aa2-0.6.1.jar",
          "size": 1732,
          "sha512": "af3b7d47293be541cc73e8d1c3bed7d94bec8b9e596a8f08f50a00cfacdaa52797f9a72f3903b7a452be9800f23a0d8685996c6351c9aa11bbb0f09cf7825fd4",
          "sha256": "8324014e14c227725f2d52162db60d93b045e092575a66b5dde09b409c42baa5",
          "sha1": "93c324648f4814707b4c4c5805e0ecb57285eba7",
          "md5": "79d4a053a111ca9ec45601a0ed7f5067"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa2-0.6.1.jar",
          "url": "ble-characteristic-u2aa2-0.6.1.jar",
          "size": 1732,
          "sha512": "af3b7d47293be541cc73e8d1c3bed7d94bec8b9e596a8f08f50a00cfacdaa52797f9a72f3903b7a452be9800f23a0d8685996c6351c9aa11bbb0f09cf7825fd4",
          "sha256": "8324014e14c227725f2d52162db60d93b045e092575a66b5dde09b409c42baa5",
          "sha1": "93c324648f4814707b4c4c5805e0ecb57285eba7",
          "md5": "79d4a053a111ca9ec45601a0ed7f5067"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa2-0.6.1-javadoc.jar",
          "url": "ble-characteristic-u2aa2-0.6.1-javadoc.jar",
          "size": 110009,
          "sha512": "9b4eb1c341af3541e53a37f62b27d59c6d83402424e6c48832cad9349404e95f817e93b0bcc06509bec212a0d4ba703df978d1ead8d9df6f156dacec12741184",
          "sha256": "e02a258309665f623a47f9021d56932bc5e8ea45380225b13b2a2e43329a3bb8",
          "sha1": "e73ad669a5d5da89264034ca811549ec90d71b65",
          "md5": "06227c66a4ab43b296bdc4e7e27d0dc1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa2-0.6.1-sources.jar",
          "url": "ble-characteristic-u2aa2-0.6.1-sources.jar",
          "size": 1565,
          "sha512": "7cf37605fd77188fd7a2ad2201061117f87ebc8deaaec3de4a7866de643430a53232bd81e12d66c0bf74babf9b88a264d6eda36c921c52c5e80b15b037d2b6f3",
          "sha256": "8b392ae9d9bf5d83a5dbbc1284638ae93713c6ebaa8ee127007743ef555b905b",
          "sha1": "a4dca80ccb6d835793b4868c924c2810f7ddbcd3",
          "md5": "654627bfcc90508980695d2ea67a1baa"
        }
      ]
    }
  ]
}
