{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab7-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab7",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-android-0.2.2.aar",
          "url": "ble-characteristic-u2ab7-android-0.2.2.aar",
          "size": 2915,
          "sha512": "fd618f6312cd7ef729bf64c37581a920af8d3710d59c3162a803bb831b1a042a546236178ba0cf52bb1b05e8a4f861ced16aa697f9eae3896cf7ee1c19c21434",
          "sha256": "2a809d7f700a759ce8eb91358dd586a84d24dab888b526a5db3d041590736cc1",
          "sha1": "da4352429adde00bca4e5df35cc1a71cabd2f65e",
          "md5": "1f63efad183a584b816a536e178e08e0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab7",
          "version": {
            "requires": "0.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-android-0.2.2.aar",
          "url": "ble-characteristic-u2ab7-android-0.2.2.aar",
          "size": 2915,
          "sha512": "fd618f6312cd7ef729bf64c37581a920af8d3710d59c3162a803bb831b1a042a546236178ba0cf52bb1b05e8a4f861ced16aa697f9eae3896cf7ee1c19c21434",
          "sha256": "2a809d7f700a759ce8eb91358dd586a84d24dab888b526a5db3d041590736cc1",
          "sha1": "da4352429adde00bca4e5df35cc1a71cabd2f65e",
          "md5": "1f63efad183a584b816a536e178e08e0"
        }
      ]
    }
  ]
}
