{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-peripheral-cpp-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-cps-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-bas-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-cpp-android-0.8.7.aar",
          "url": "ble-profile-peripheral-cpp-android-0.8.7.aar",
          "size": 9166,
          "sha512": "835ae0c6f37413900db8cbff76d2c80d51abaa12d0605113849b60833377fa7dcbc1d7f2d56d8e6165b90faf92f56b922a76324c977168b58677525a599c23ea",
          "sha256": "411ce63b970a57ac0b359a7c5e01cc9375cc1d2604146ba32cb8799cd8ecbec1",
          "sha1": "282dd6db93947a03f8a3de5dba1a31e7ea14f247",
          "md5": "47fe39e426e0881ab209e13beca8bfb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-cps-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-dis-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-bas-android",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-peripheral-cpp-android-0.8.7.aar",
          "url": "ble-profile-peripheral-cpp-android-0.8.7.aar",
          "size": 9166,
          "sha512": "835ae0c6f37413900db8cbff76d2c80d51abaa12d0605113849b60833377fa7dcbc1d7f2d56d8e6165b90faf92f56b922a76324c977168b58677525a599c23ea",
          "sha256": "411ce63b970a57ac0b359a7c5e01cc9375cc1d2604146ba32cb8799cd8ecbec1",
          "sha1": "282dd6db93947a03f8a3de5dba1a31e7ea14f247",
          "md5": "47fe39e426e0881ab209e13beca8bfb0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-cpp-android-0.8.7-sources.jar",
          "url": "ble-profile-peripheral-cpp-android-0.8.7-sources.jar",
          "size": 5396,
          "sha512": "1447156de3a3be85a02fcbdaffe2439ba4c3e38ee6817e107f5fb4618a9f77fd00cc47d3cfcc2a122bec48fed5fb8cb774ccd5c74cb0bc533220814f6b4ead52",
          "sha256": "edd0714c22314f36c9e304d331c09e4503be104826eb2ba6b8350d947ce66094",
          "sha1": "dde1b20bda84074d49166505be9d96ad7e32db5f",
          "md5": "6cbf1204812135ad59b78f95a4a77519"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-peripheral-cpp-android-0.8.7-javadoc.jar",
          "url": "ble-profile-peripheral-cpp-android-0.8.7-javadoc.jar",
          "size": 295521,
          "sha512": "bc4c2c5463b673735f6f61deed6420d6e01cc792d8384863269e36e9a7a9c050b6043afc780acef9e766e99bfe86e7fb23e3c99d962de8b63cae317a3b18134b",
          "sha256": "bf9eb0044e06e50b67c861a26ac40d6fe41f49cf2314fbbed526fa183d3a5554",
          "sha1": "95031fa00d34221239860432ce7dff8a52f5c8ec",
          "md5": "a7e1c1ce870b15e853839fcee532e42b"
        }
      ]
    }
  ]
}
