{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-advertising-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "swq2gxvgereszma3nz5hc5y3xq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "stacklog",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-advertising",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-advertising-android-0.1.5.aar",
          "url": "ble-advertising-android-0.1.5.aar",
          "size": 100471,
          "sha512": "ee9fd5af9e39f14d1bf58efc55e77ac99fa3b6d6abac295fb219f4d0a91b975a1baf63a27f5c5cad8ad21d3c43defed3685cebf0bfc8041f75514e6582a70d85",
          "sha256": "268e364a0597a25214f5d58d73a981bd3b198b86deb3e63eab333ce3074b37fe",
          "sha1": "8bc1daff2e641f7a9e30882e635d802b98c01799",
          "md5": "8551a98315b2e6c71f131abd4f90e510"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "stacklog",
          "version": {
            "requires": "0.0.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-advertising",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-advertising-android-0.1.5.aar",
          "url": "ble-advertising-android-0.1.5.aar",
          "size": 100471,
          "sha512": "ee9fd5af9e39f14d1bf58efc55e77ac99fa3b6d6abac295fb219f4d0a91b975a1baf63a27f5c5cad8ad21d3c43defed3685cebf0bfc8041f75514e6582a70d85",
          "sha256": "268e364a0597a25214f5d58d73a981bd3b198b86deb3e63eab333ce3074b37fe",
          "sha1": "8bc1daff2e641f7a9e30882e635d802b98c01799",
          "md5": "8551a98315b2e6c71f131abd4f90e510"
        }
      ]
    }
  ]
}
