{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a96-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6cu2oomv2fb67ivu2iebxgsxbm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a96",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a96-android-0.2.0.aar",
          "url": "ble-characteristic-u2a96-android-0.2.0.aar",
          "size": 2880,
          "sha512": "7dc532ff3b1e576d6c96b44c3d936f3a616c03df2fac7091b03bb2a65196b3a3edae64d55a56f46162503a9b44781fbdd1eb58b355dc7e1230462d5d99cde54d",
          "sha256": "947d5bee2e295bee9be2bd7f708fa6a13d397b4da39aba31162d51530bd3d99d",
          "sha1": "bf85d29c9c79d7fa21925279d380664f78fd6516",
          "md5": "c1c76c743d9a44b909ab6ecd6cba0400"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a96",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a96-android-0.2.0.aar",
          "url": "ble-characteristic-u2a96-android-0.2.0.aar",
          "size": 2880,
          "sha512": "7dc532ff3b1e576d6c96b44c3d936f3a616c03df2fac7091b03bb2a65196b3a3edae64d55a56f46162503a9b44781fbdd1eb58b355dc7e1230462d5d99cde54d",
          "sha256": "947d5bee2e295bee9be2bd7f708fa6a13d397b4da39aba31162d51530bd3d99d",
          "sha1": "bf85d29c9c79d7fa21925279d380664f78fd6516",
          "md5": "c1c76c743d9a44b909ab6ecd6cba0400"
        }
      ]
    }
  ]
}
