{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad8-android",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-android-0.8.7.aar",
          "url": "ble-characteristic-u2ad8-android-0.8.7.aar",
          "size": 3250,
          "sha512": "01db83a2c863f5d14be46a88488c902c96bfff387cbef1e421c646d03bd335cc4b2bbc899461c8b102ae5f19c6456e5371a4e721f2d6085e5884c2a7f09fe1d4",
          "sha256": "07e43b70afaf4eae42d9b85b1c18603c7bd7b63f9e2d0dc1969d8e1a7680f105",
          "sha1": "7882f223c33f9bb8d40556813bcb6b9775d97c20",
          "md5": "e2ac8a52196ccb7501b8236fc7194912"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-android-0.8.7.aar",
          "url": "ble-characteristic-u2ad8-android-0.8.7.aar",
          "size": 3250,
          "sha512": "01db83a2c863f5d14be46a88488c902c96bfff387cbef1e421c646d03bd335cc4b2bbc899461c8b102ae5f19c6456e5371a4e721f2d6085e5884c2a7f09fe1d4",
          "sha256": "07e43b70afaf4eae42d9b85b1c18603c7bd7b63f9e2d0dc1969d8e1a7680f105",
          "sha1": "7882f223c33f9bb8d40556813bcb6b9775d97c20",
          "md5": "e2ac8a52196ccb7501b8236fc7194912"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad8-android-0.8.7-sources.jar",
          "url": "ble-characteristic-u2ad8-android-0.8.7-sources.jar",
          "size": 2232,
          "sha512": "7f1d65055eb1266a0d3ead86cb9bd4f13034c1458791f7b4a8f53ab1f03303b4a6f69fa428d9ac1f3c9b16b5b9e5511b114b0302e4f2e81c592ac46aa19f4311",
          "sha256": "6cd77f4a629fdb03b61dde3b5ddb01094b608a75cf4df2009558389f6bebd4fc",
          "sha1": "5c4ebf6275df58d3c507e70c52aff526a9e9865f",
          "md5": "3210d56593ec811f02bcb30d46b802d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad8-android-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2ad8-android-0.8.7-javadoc.jar",
          "size": 270772,
          "sha512": "3504f17698d88681ab6c520a853d2fbf41692b1f8aede9514d97e864887f8cba019c4a1cc4bf653da6fe26406bb9b16b66361b3c0e98d1f7ec1742c67aea8ac7",
          "sha256": "ab71d3e1f6afa075fb54b9e00343efe4fb7cfd084e8e0db69b285b0605b5addd",
          "sha1": "cac75ead14d3812ce7efc2b4820b0fbdd16f7915",
          "md5": "e8954de68ae3d52a8cd90720875b450a"
        }
      ]
    }
  ]
}
