{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bad",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.5.jar",
          "url": "ble-characteristic-u2bad-0.8.5.jar",
          "size": 1488,
          "sha512": "ddad9c1710a7ade2800a4ab7940fc142c56b27a05cb41c6313f2ad7c55e9e58547e100225e4eb4d6885c0eeb740d0658febdebd65b062bce302445ec9b799c81",
          "sha256": "fe44e6249b51d1816558aefc5d51382000f04b43addecf036254eca22d0e99f4",
          "sha1": "cf23d3301d3ecfa5cde636c428e8a51c71963b83",
          "md5": "cedc8766d26a604dfedaf45fd9af7649"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.5.jar",
          "url": "ble-characteristic-u2bad-0.8.5.jar",
          "size": 1488,
          "sha512": "ddad9c1710a7ade2800a4ab7940fc142c56b27a05cb41c6313f2ad7c55e9e58547e100225e4eb4d6885c0eeb740d0658febdebd65b062bce302445ec9b799c81",
          "sha256": "fe44e6249b51d1816558aefc5d51382000f04b43addecf036254eca22d0e99f4",
          "sha1": "cf23d3301d3ecfa5cde636c428e8a51c71963b83",
          "md5": "cedc8766d26a604dfedaf45fd9af7649"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2bad-0.8.5-javadoc.jar",
          "size": 107257,
          "sha512": "411bf40eaa6addbf8d7164a64be74efef01feff4f82bd87f6df3f5b24fbc57c70ab01ae3d4b1e7e94fb32325fc9a33d4dcb670aadb42d76dd27962a431500e6b",
          "sha256": "e4fd51c4f1d7bb8d1341cf855c0865f2fb4c408c4699b911693c5d386081043d",
          "sha1": "99520219a6d4263b775e318a47c1c65899c4cbc1",
          "md5": "2c0e409138e76b10133d40b40477c214"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bad-0.8.5-sources.jar",
          "url": "ble-characteristic-u2bad-0.8.5-sources.jar",
          "size": 1474,
          "sha512": "51bf41ef405335489040b1ba51c055ad81b91df0b14aeb482c922a120bc9c255a23d3135ce9a9dfc124437da5c1146cc0d89f22dc91c601703b1290000a674e1",
          "sha256": "ccc9ec878a0eeadae7b99e976d513a096aa61a5bdc78553de8137985ed54b08b",
          "sha1": "e243778ca6ecf2b4ab18b3d1695667ee9ed1cf07",
          "md5": "86696239f9c6c52827e5439e9a33c4f9"
        }
      ]
    }
  ]
}
