{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b3b-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3b",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3b-android-0.4.3.aar",
          "url": "ble-characteristic-u2b3b-android-0.4.3.aar",
          "size": 3118,
          "sha512": "1ed68c022840fb55feef45d7735b6b37253eb73e543d2c80027d550b7458e0f787feb7f4d23593205a4c905f5d4e655d11e477085f080f971b6fe0825577cced",
          "sha256": "b4c90c809a4b075f9a193c8723ce7514317c45c0f7ae82938a0bae61ff37ae84",
          "sha1": "fcd4297faa4a583315fc7a7fb946fdfd40f1b3b6",
          "md5": "61bd84a6df22a6c62cf784163cf56001"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b3b",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b3b-android-0.4.3.aar",
          "url": "ble-characteristic-u2b3b-android-0.4.3.aar",
          "size": 3118,
          "sha512": "1ed68c022840fb55feef45d7735b6b37253eb73e543d2c80027d550b7458e0f787feb7f4d23593205a4c905f5d4e655d11e477085f080f971b6fe0825577cced",
          "sha256": "b4c90c809a4b075f9a193c8723ce7514317c45c0f7ae82938a0bae61ff37ae84",
          "sha1": "fcd4297faa4a583315fc7a7fb946fdfd40f1b3b6",
          "md5": "61bd84a6df22a6c62cf784163cf56001"
        }
      ]
    }
  ]
}
