{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a29-android",
    "version": "0.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "clzwkqu3gjhqdcff5nyjro6boi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.4.5.aar",
          "url": "ble-characteristic-u2a29-android-0.4.5.aar",
          "size": 3145,
          "sha512": "7ead01083190821547ca55a81c01bc97a0f5fbbe24dc4068f73befe1d7296d1a1161d9af2a8449afa60b36d18742ecdc6c4753405cb082cd8a6f21f7bd71775b",
          "sha256": "0a0338075da3270c11b2e44c2eba88ededbdbdbfe85be51ebeec8cae7dc39eec",
          "sha1": "50a9b57970d8fdeac6b712920f9e8cf91105bb6d",
          "md5": "0cbe8c38e715b9650d25cfd95d1b843a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a29",
          "version": {
            "requires": "0.4.5"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a29-android-0.4.5.aar",
          "url": "ble-characteristic-u2a29-android-0.4.5.aar",
          "size": 3145,
          "sha512": "7ead01083190821547ca55a81c01bc97a0f5fbbe24dc4068f73befe1d7296d1a1161d9af2a8449afa60b36d18742ecdc6c4753405cb082cd8a6f21f7bd71775b",
          "sha256": "0a0338075da3270c11b2e44c2eba88ededbdbdbfe85be51ebeec8cae7dc39eec",
          "sha1": "50a9b57970d8fdeac6b712920f9e8cf91105bb6d",
          "md5": "0cbe8c38e715b9650d25cfd95d1b843a"
        }
      ]
    }
  ]
}
