{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad5",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad5-0.8.12.jar",
          "url": "ble-characteristic-u2ad5-0.8.12.jar",
          "size": 2104,
          "sha512": "2e49bf82c770b09b40932465589b05ba41363cb0f71bf9bf852f0249910b13e452d9648cf76f9360512be7399cea82fc8ae26ba9565e5ac2d16facddcb5299a8",
          "sha256": "8c4d39927c3e614558390d905e35100cf3eea315b7df56df8003f305df6c70c0",
          "sha1": "2e860256970e38948e39551e33ace04d96cc79d0",
          "md5": "ca212af8bff76de576d9780e8e1e5f25"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad5-0.8.12.jar",
          "url": "ble-characteristic-u2ad5-0.8.12.jar",
          "size": 2104,
          "sha512": "2e49bf82c770b09b40932465589b05ba41363cb0f71bf9bf852f0249910b13e452d9648cf76f9360512be7399cea82fc8ae26ba9565e5ac2d16facddcb5299a8",
          "sha256": "8c4d39927c3e614558390d905e35100cf3eea315b7df56df8003f305df6c70c0",
          "sha1": "2e860256970e38948e39551e33ace04d96cc79d0",
          "md5": "ca212af8bff76de576d9780e8e1e5f25"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad5-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2ad5-0.8.12-javadoc.jar",
          "size": 110004,
          "sha512": "4f55b65f8fa14af50312f38998b9dc592d90bbc3160fddb94386a887d9d68f88fc7796b8abd096dc5a27b0f7a631a142b651f2429872a582fb885ade40ffed61",
          "sha256": "b1ffd339b5af429f10a200e0c20547feb494ae8c99b61c23b77b02fbeadc127a",
          "sha1": "794cb5b3802240a1ef71e91e37a58de72bab6ae6",
          "md5": "5e0567046887c7227caf6a547f5934cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ad5-0.8.12-sources.jar",
          "url": "ble-characteristic-u2ad5-0.8.12-sources.jar",
          "size": 1895,
          "sha512": "a1c90b8e67c78dd5fb630d27119b69f07b08a049f51658517b8aa7aa53a4d0bead4722253ef2a32aa52d05c9795b767aacdde845453824e0b2e1de018aad5442",
          "sha256": "6e47a40ff32ea701084e718f2114ce8b756bcd9cc4cb01aae7697f1e07b68db1",
          "sha1": "1338866a5ba4c821d275607bf35c337c27f315dc",
          "md5": "f7115d95b3fc9b5b427f62d67c023056"
        }
      ]
    }
  ]
}
