{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-pass-central-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-pass-central-android-0.1.4.aar",
          "url": "ble-service-pass-central-android-0.1.4.aar",
          "size": 6462,
          "sha512": "3826fc7a54a6cca3e186bfe42c3869f44b87062ed45e9885cb197fad76579f16057f92ad3b032219fd0c8bd61996a88ba29036db8e6fd7c6f149e0810f2d5863",
          "sha256": "9884eb8b63683cb009815cb7d926b96b41ea89acbf74f772a8e9efc76a5f9429",
          "sha1": "5843522090c9a2e107044e6c29a3257185d55019",
          "md5": "36e81e8f784ec6924ec95baeac2d3506"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.15"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-pass-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-pass-central-android-0.1.4.aar",
          "url": "ble-service-pass-central-android-0.1.4.aar",
          "size": 6462,
          "sha512": "3826fc7a54a6cca3e186bfe42c3869f44b87062ed45e9885cb197fad76579f16057f92ad3b032219fd0c8bd61996a88ba29036db8e6fd7c6f149e0810f2d5863",
          "sha256": "9884eb8b63683cb009815cb7d926b96b41ea89acbf74f772a8e9efc76a5f9429",
          "sha1": "5843522090c9a2e107044e6c29a3257185d55019",
          "md5": "36e81e8f784ec6924ec95baeac2d3506"
        }
      ]
    }
  ]
}
