{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b4d-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4d",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4d-android-0.8.10.aar",
          "url": "ble-characteristic-u2b4d-android-0.8.10.aar",
          "size": 3366,
          "sha512": "c6275014b67e73e810834987844f64d2419aaa140096f599553b6dc078d1a489ed0ebe0f2c78b01c3ddfa6cd871d200db82fcc08148a655e056f31705b9a6950",
          "sha256": "f6d2b9b0c5ef8700b258d25a2c41275a4d738e7b02ae1324f83a3fb3e073de0c",
          "sha1": "c2b673a37e8a238bcab83071ce50ec6c5da5fed2",
          "md5": "ee9f8ee8369a3f8a2a18b31024a4d92a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b4d",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b4d-android-0.8.10.aar",
          "url": "ble-characteristic-u2b4d-android-0.8.10.aar",
          "size": 3366,
          "sha512": "c6275014b67e73e810834987844f64d2419aaa140096f599553b6dc078d1a489ed0ebe0f2c78b01c3ddfa6cd871d200db82fcc08148a655e056f31705b9a6950",
          "sha256": "f6d2b9b0c5ef8700b258d25a2c41275a4d738e7b02ae1324f83a3fb3e073de0c",
          "sha1": "c2b673a37e8a238bcab83071ce50ec6c5da5fed2",
          "md5": "ee9f8ee8369a3f8a2a18b31024a4d92a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4d-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2b4d-android-0.8.10-sources.jar",
          "size": 2405,
          "sha512": "75b953c37e3763efae0b7e93c1cce5dbb2e9fdcaa27c167ac237fb98f356211542931506703e3d5d02cce7d5871828bbd57a4956625c27066fba62b0e0be5cc7",
          "sha256": "3482cc17171ae392b28496e92e39a249715f3cee8a4f3569d44ca2fe9fa075a4",
          "sha1": "f23de239ed0dbae781862074a3bf95820c17cf91",
          "md5": "8e50b772d901f777fc5336283a730aa6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b4d-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2b4d-android-0.8.10-javadoc.jar",
          "size": 272945,
          "sha512": "ec1b31b47bb9f1ff7d095fd78aac1a3c98466f0d2a147ff9b56ab71419ca5310fe72fd010a26634035fcc1136eda9316fc09fc950940fba31dd90a4590dce375",
          "sha256": "f724c1a6ccbeca97b38397975ee666fda6c5134dd95b95e306617e7519982450",
          "sha1": "1b20e668cf69bc0286252c66723c43b42a4b364d",
          "md5": "808fa6f865b0fee51b32a37845e95a46"
        }
      ]
    }
  ]
}
