{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1e",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-0.5.1.jar",
          "url": "ble-characteristic-u2a1e-0.5.1.jar",
          "size": 3040,
          "sha512": "bd1341b1f9517df1e5c791642dea66e0fa5609a3cb16c03bc2f6165efa2ecfc938e0871a230727175bc3036327be3771f82db7ebc41dc2b08dde99a5529062b9",
          "sha256": "87829a4be0093c3456fb0969df1c61bb37393124a378dfc43d4390d6d08dcf2a",
          "sha1": "fc26deef4508555dacce42e30616ff1445139daa",
          "md5": "c1db0e85ef123a16227463b3421680af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-0.5.1.jar",
          "url": "ble-characteristic-u2a1e-0.5.1.jar",
          "size": 3040,
          "sha512": "bd1341b1f9517df1e5c791642dea66e0fa5609a3cb16c03bc2f6165efa2ecfc938e0871a230727175bc3036327be3771f82db7ebc41dc2b08dde99a5529062b9",
          "sha256": "87829a4be0093c3456fb0969df1c61bb37393124a378dfc43d4390d6d08dcf2a",
          "sha1": "fc26deef4508555dacce42e30616ff1445139daa",
          "md5": "c1db0e85ef123a16227463b3421680af"
        }
      ]
    }
  ]
}
