{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ias-peripheral-android",
    "version": "0.1.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-peripheral-android-0.1.11.aar",
          "url": "ble-service-ias-peripheral-android-0.1.11.aar",
          "size": 4706,
          "sha512": "63efe0bf8372b99b960fb9fcaeedf1a9b4b90ec5e022dc7f380f7e709333c20fb2c7ca0017fc8005b4a6d3a1a69cc84d0a6a4d1a91405f2579e3b25bfce65317",
          "sha256": "d84e8cd1600f5ed89fd451d300c8242bd9326255bec7f62a22387bc8dfa2f36d",
          "sha1": "a8cc8a127afc00e0d0cb8aae1d935e584dd4342d",
          "md5": "2fd6f1de2a9a95830e2af2b53154641b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ias-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ias-peripheral-android-0.1.11.aar",
          "url": "ble-service-ias-peripheral-android-0.1.11.aar",
          "size": 4706,
          "sha512": "63efe0bf8372b99b960fb9fcaeedf1a9b4b90ec5e022dc7f380f7e709333c20fb2c7ca0017fc8005b4a6d3a1a69cc84d0a6a4d1a91405f2579e3b25bfce65317",
          "sha256": "d84e8cd1600f5ed89fd451d300c8242bd9326255bec7f62a22387bc8dfa2f36d",
          "sha1": "a8cc8a127afc00e0d0cb8aae1d935e584dd4342d",
          "md5": "2fd6f1de2a9a95830e2af2b53154641b"
        }
      ]
    }
  ]
}
