{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bd5",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.7.jar",
          "url": "ble-characteristic-u2bd5-0.8.7.jar",
          "size": 1948,
          "sha512": "2ec6304e4cd95ec85bc7fd42fb3b5eff47a5240054b6329927baef4a92e76419298b91cc3ba5bc7ac452362453250e5d8d063db1691e9f9377dcf96e822fdde2",
          "sha256": "8c0bbdd6c17ec1588d6d403a56066b32684e9799585a59dd79fb312d858c5e38",
          "sha1": "c1d5d0c771cec3764c450c4b54744db84404f7c9",
          "md5": "e8d76a865adbf0c819e2620e1360a97f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.7.jar",
          "url": "ble-characteristic-u2bd5-0.8.7.jar",
          "size": 1948,
          "sha512": "2ec6304e4cd95ec85bc7fd42fb3b5eff47a5240054b6329927baef4a92e76419298b91cc3ba5bc7ac452362453250e5d8d063db1691e9f9377dcf96e822fdde2",
          "sha256": "8c0bbdd6c17ec1588d6d403a56066b32684e9799585a59dd79fb312d858c5e38",
          "sha1": "c1d5d0c771cec3764c450c4b54744db84404f7c9",
          "md5": "e8d76a865adbf0c819e2620e1360a97f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2bd5-0.8.7-javadoc.jar",
          "size": 108012,
          "sha512": "083707c8fdc7759fc0afb8c3b1e3c1df8e36fd9984c7dd8757e1e2cfae8735256e5efe9521100982683cb103d9a439f4337d4289841f9eba285ffd82139e967c",
          "sha256": "c3a98bc288971c73de3b13f615324bbb7a090555ffdc35f54a044b72ee058dd9",
          "sha1": "24446b4213016639cf7a31acd9384b030ad88d19",
          "md5": "90905304e1dbbff95674e5f194e38ecd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bd5-0.8.7-sources.jar",
          "url": "ble-characteristic-u2bd5-0.8.7-sources.jar",
          "size": 1970,
          "sha512": "46ee7c30af02013c095fccd5f54cbf5a4554eac2086c27986e68129cc1ead1b6f103d22442479efceaa1e74423ebd55b2d062eb66ef5ece7b6a4e04c58cb0822",
          "sha256": "4f912631dc5dc635f7c2eb103b58b3253cfac9b486b2bf3141e4db7cf204ada4",
          "sha1": "2aa4902dd1419f31cb56498195f79178476cdfbd",
          "md5": "b227d29e400aaed568711d047d4af8b1"
        }
      ]
    }
  ]
}
