{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core",
    "version": "0.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "zhxujrvoxjaihfxvsfrlhylxje"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-core-0.3.2.jar",
          "url": "ble-core-0.3.2.jar",
          "size": 74868,
          "sha512": "7d91d659f15a5f4afd6a842fcb84414f3340340d9f59450ebdae622dec7d179de81ac0079243e5e8fef6a9f1d635a748a3488677d8ee7a72e8ba98d0275e9c2c",
          "sha256": "3c3482ee06766450b3b2f31fa2d37d0ed783d025985ad168fdfe290d56969027",
          "sha1": "e7fd8da2489257e0b36a0d14f34ba36937aa48ab",
          "md5": "98c5051d0c2f62840a0018baded05857"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-0.3.2.jar",
          "url": "ble-core-0.3.2.jar",
          "size": 74868,
          "sha512": "7d91d659f15a5f4afd6a842fcb84414f3340340d9f59450ebdae622dec7d179de81ac0079243e5e8fef6a9f1d635a748a3488677d8ee7a72e8ba98d0275e9c2c",
          "sha256": "3c3482ee06766450b3b2f31fa2d37d0ed783d025985ad168fdfe290d56969027",
          "sha1": "e7fd8da2489257e0b36a0d14f34ba36937aa48ab",
          "md5": "98c5051d0c2f62840a0018baded05857"
        }
      ]
    }
  ]
}
