{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a70",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.12.jar",
          "url": "ble-characteristic-u2a70-0.8.12.jar",
          "size": 1879,
          "sha512": "8555b5fa4bca9773cc29135404bf468b2962aeff00bd581fa0b1da9bed7e1e6d617d843c40fdff134450ed387bee38226ea6670fffe02536b6322f946d6b5880",
          "sha256": "7209fb4c092d835325a00cba0b8abd2b67e01dedb77bd9f80beddf3e29998f09",
          "sha1": "2a76c249b5ca872e5da637ceab4484fd27513b2f",
          "md5": "1c88b703fd23a0443efead492b96d880"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.12.jar",
          "url": "ble-characteristic-u2a70-0.8.12.jar",
          "size": 1879,
          "sha512": "8555b5fa4bca9773cc29135404bf468b2962aeff00bd581fa0b1da9bed7e1e6d617d843c40fdff134450ed387bee38226ea6670fffe02536b6322f946d6b5880",
          "sha256": "7209fb4c092d835325a00cba0b8abd2b67e01dedb77bd9f80beddf3e29998f09",
          "sha1": "2a76c249b5ca872e5da637ceab4484fd27513b2f",
          "md5": "1c88b703fd23a0443efead492b96d880"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a70-0.8.12-javadoc.jar",
          "size": 109403,
          "sha512": "b1229d7e1dce63b35f51739eaccba8226e72178ebb3115f07768473d7bf98c32f5ea19505a4fb87dce5cb7de57f596c885af844fbaaac8623e90a83448019e99",
          "sha256": "5b147f33d1c663181e7848e0e8dff6391779c6a0d55bffd1bc2c3451c3d39e2b",
          "sha1": "ecb215aedb4f1499fdbd68f15549095f211566b3",
          "md5": "9584052b6a6dafa6190254dba84ebb78"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a70-0.8.12-sources.jar",
          "size": 1700,
          "sha512": "8db15d894a9bb27bfecc367b6bae49096ce950b29524246d950706f463ec3d48b1e0f19a4e8fb0a5856fac4b2ac40f6d5e29a1efc9e6ab0056d29425a75a0308",
          "sha256": "31b1aad0a3f0871ea5dbbb6daddac750a3d3250aa1998a464a5974780bb9550a",
          "sha1": "34c3876d573aefbbafc5d02c549b6240e59472af",
          "md5": "19b3934b40ade87cee92a0306b733992"
        }
      ]
    }
  ]
}
