{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac2-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac2",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac2-android-0.8.12.aar",
          "url": "ble-characteristic-u2ac2-android-0.8.12.aar",
          "size": 3271,
          "sha512": "e17857624ee005ad649293e2e0e314f61e405867db439c8741525451712b70d2a200a6e462fe08259e4a8460dab9768cf2aed3683be99630d2df2cbbfb1f0153",
          "sha256": "a04f78563a698c2ae01d25d4ccbfacba049669570f1e72c7e84a40db6cdff214",
          "sha1": "484e2599eec260b0f9cbfde4b278d1f182c8b9d4",
          "md5": "d39a80d0fcf5db6fa46fe23a9a26af86"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac2",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac2-android-0.8.12.aar",
          "url": "ble-characteristic-u2ac2-android-0.8.12.aar",
          "size": 3271,
          "sha512": "e17857624ee005ad649293e2e0e314f61e405867db439c8741525451712b70d2a200a6e462fe08259e4a8460dab9768cf2aed3683be99630d2df2cbbfb1f0153",
          "sha256": "a04f78563a698c2ae01d25d4ccbfacba049669570f1e72c7e84a40db6cdff214",
          "sha1": "484e2599eec260b0f9cbfde4b278d1f182c8b9d4",
          "md5": "d39a80d0fcf5db6fa46fe23a9a26af86"
        }
      ]
    }
  ]
}
