{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab1-android",
    "version": "0.2.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab1",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-android-0.2.9.aar",
          "url": "ble-characteristic-u2ab1-android-0.2.9.aar",
          "size": 3139,
          "sha512": "e7ef96be96e3bd7edfe074057e4d5dc394ac33fa794947070153882cb0dce807489996fbd730e7afcf7cd713952fb458a6f6d1c8a68ba4c69303919e129384e5",
          "sha256": "7addf2709839d3916a39af7e7abfad017a09befd06f1734968114e0cbbb3b340",
          "sha1": "3a9e0f728f3b9c78cad13545ad756953c24557bb",
          "md5": "2175120e0006e8a7b1895f9491b0a05d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab1",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab1-android-0.2.9.aar",
          "url": "ble-characteristic-u2ab1-android-0.2.9.aar",
          "size": 3139,
          "sha512": "e7ef96be96e3bd7edfe074057e4d5dc394ac33fa794947070153882cb0dce807489996fbd730e7afcf7cd713952fb458a6f6d1c8a68ba4c69303919e129384e5",
          "sha256": "7addf2709839d3916a39af7e7abfad017a09befd06f1734968114e0cbbb3b340",
          "sha1": "3a9e0f728f3b9c78cad13545ad756953c24557bb",
          "md5": "2175120e0006e8a7b1895f9491b0a05d"
        }
      ]
    }
  ]
}
