{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aad-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aad",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-android-0.2.6.aar",
          "url": "ble-characteristic-u2aad-android-0.2.6.aar",
          "size": 3139,
          "sha512": "c63d48d5917b23b90e223e0a3b87d8e1a74841461878419c955ee165044aab556749c7c00f42dd2e787a2522a8eb1cb3f36166864e7d4510f2c948ca720a31a5",
          "sha256": "051c2b4c141696729e853a0847e901dabeac4c42f0b53de707bbcce4d080e50e",
          "sha1": "09353a9a65d50b529c51b3f48cb5fe01f638113a",
          "md5": "9553abd1ce55f4d2c18ba3a034cda71a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aad",
          "version": {
            "requires": "0.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aad-android-0.2.6.aar",
          "url": "ble-characteristic-u2aad-android-0.2.6.aar",
          "size": 3139,
          "sha512": "c63d48d5917b23b90e223e0a3b87d8e1a74841461878419c955ee165044aab556749c7c00f42dd2e787a2522a8eb1cb3f36166864e7d4510f2c948ca720a31a5",
          "sha256": "051c2b4c141696729e853a0847e901dabeac4c42f0b53de707bbcce4d080e50e",
          "sha1": "09353a9a65d50b529c51b3f48cb5fe01f638113a",
          "md5": "9553abd1ce55f4d2c18ba3a034cda71a"
        }
      ]
    }
  ]
}
