{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad6",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "xegzxnizybdmbl7ybijgng2e64"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-0.2.0.jar",
          "url": "ble-characteristic-u2ad6-0.2.0.jar",
          "size": 2112,
          "sha512": "d7f954d1a10db7397fb40167c43f50ebc62f2e91ee87e56a7957870a0bbad861657b631bf6dbbdcdce625997725d4100796efddf88f199973df05d663698f0fd",
          "sha256": "6fadf9fb26ee09b28768be2301e1aae6e2b8f6324b9520068bf19028886cde6",
          "sha1": "88feaabf44c30b05cb7c4e2abfbd8237b373028b",
          "md5": "ac8b25eb0f01f45061958e37dd6e87f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad6-0.2.0.jar",
          "url": "ble-characteristic-u2ad6-0.2.0.jar",
          "size": 2112,
          "sha512": "d7f954d1a10db7397fb40167c43f50ebc62f2e91ee87e56a7957870a0bbad861657b631bf6dbbdcdce625997725d4100796efddf88f199973df05d663698f0fd",
          "sha256": "6fadf9fb26ee09b28768be2301e1aae6e2b8f6324b9520068bf19028886cde6",
          "sha1": "88feaabf44c30b05cb7c4e2abfbd8237b373028b",
          "md5": "ac8b25eb0f01f45061958e37dd6e87f9"
        }
      ]
    }
  ]
}
