{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b79",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b79-0.8.10.jar",
          "url": "ble-characteristic-u2b79-0.8.10.jar",
          "size": 1454,
          "sha512": "bfe33933b7c2721600c8c1edb763d817e9498042210ec621c7e5ac626a76da5fcf8897c2049472e893744f7d0b8af5874ae866d2a3fd12b283fe0bdae7c4d2bc",
          "sha256": "dacba1fb4a64cc4401665b9273b707ccc212acec83490cb45d5a358aaccad658",
          "sha1": "cb9f149a4862fc5e886017245cd71138607bb0fe",
          "md5": "7445db89819771307552437fa0504504"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b79-0.8.10.jar",
          "url": "ble-characteristic-u2b79-0.8.10.jar",
          "size": 1454,
          "sha512": "bfe33933b7c2721600c8c1edb763d817e9498042210ec621c7e5ac626a76da5fcf8897c2049472e893744f7d0b8af5874ae866d2a3fd12b283fe0bdae7c4d2bc",
          "sha256": "dacba1fb4a64cc4401665b9273b707ccc212acec83490cb45d5a358aaccad658",
          "sha1": "cb9f149a4862fc5e886017245cd71138607bb0fe",
          "md5": "7445db89819771307552437fa0504504"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b79-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2b79-0.8.10-javadoc.jar",
          "size": 107161,
          "sha512": "1ce5a609fd3d0d3bf85b37a09e58dfbe8cb9b04218f2298e4d0f2b52b407d41153ee1266aedac6b2d2111d49132888343470d8b2da13aca6368170d3d8eec08f",
          "sha256": "bd793f051803d0576439421b1ad502d22ca8fc0ed46c546d3e8a5a9d73843b27",
          "sha1": "0fc231ce9411746a5f8c8f708711affaa8204a25",
          "md5": "1c44639dee462a9f76bf072299a54b08"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b79-0.8.10-sources.jar",
          "url": "ble-characteristic-u2b79-0.8.10-sources.jar",
          "size": 1444,
          "sha512": "64f934db6f6c6d2d750949fd5b7ac98ad123d1f849e96832c6e3a02aaad08757bd4ec680b529585c65c2f4cc44be7fa452ee2eafd7e69a7673be180b73f53af7",
          "sha256": "4067585cd2309ed6951467afed97a2f6872b55dd86ba451516faf1c3b39712d2",
          "sha1": "bc7b597872ce865881f77c0fead78ccacdeb0b2e",
          "md5": "2168a4602d4c21ec522aa7426176e30e"
        }
      ]
    }
  ]
}
