{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a07-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.2.6.aar",
          "url": "ble-characteristic-u2a07-android-0.2.6.aar",
          "size": 3089,
          "sha512": "4b623a1d6fb0e6ec24ad23b6f6eae7b67355ca6d31ba874c5b50f022366c13d5567a682cb955f5f2cadb465ccb7b2782cd49afb3d1ecd0166f92946d9c53ca1a",
          "sha256": "6ae395b5cd8f2c87043740f6290bef525f2cadbd428efdd2aa1ea5e35908d301",
          "sha1": "39ae3373c7087836d414cc7c418dbd381b3ad936",
          "md5": "77815cb31a7182721803919b50caaf3d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a07",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a07-android-0.2.6.aar",
          "url": "ble-characteristic-u2a07-android-0.2.6.aar",
          "size": 3089,
          "sha512": "4b623a1d6fb0e6ec24ad23b6f6eae7b67355ca6d31ba874c5b50f022366c13d5567a682cb955f5f2cadb465ccb7b2782cd49afb3d1ecd0166f92946d9c53ca1a",
          "sha256": "6ae395b5cd8f2c87043740f6290bef525f2cadbd428efdd2aa1ea5e35908d301",
          "sha1": "39ae3373c7087836d414cc7c418dbd381b3ad936",
          "md5": "77815cb31a7182721803919b50caaf3d"
        }
      ]
    }
  ]
}
