{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b95-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b95",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b95-android-0.8.10.aar",
          "url": "ble-characteristic-u2b95-android-0.8.10.aar",
          "size": 3167,
          "sha512": "a540a616dc59bf9787b81737517f86fe059d472f6ec3b3556f44bb2c0455f06a0c54c90f35ee354203b36600b320b21d8e04667c900dcc76a195a2933346b3aa",
          "sha256": "931926e855a29589343fcb238ac1cf412cbaac024b487388f03ffa20e6f316a7",
          "sha1": "9c680dafe7237da7152f3254f9e9b89fa417ccf6",
          "md5": "85f095fd5a6d01afa7683e32129b3233"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b95",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b95-android-0.8.10.aar",
          "url": "ble-characteristic-u2b95-android-0.8.10.aar",
          "size": 3167,
          "sha512": "a540a616dc59bf9787b81737517f86fe059d472f6ec3b3556f44bb2c0455f06a0c54c90f35ee354203b36600b320b21d8e04667c900dcc76a195a2933346b3aa",
          "sha256": "931926e855a29589343fcb238ac1cf412cbaac024b487388f03ffa20e6f316a7",
          "sha1": "9c680dafe7237da7152f3254f9e9b89fa417ccf6",
          "md5": "85f095fd5a6d01afa7683e32129b3233"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b95-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2b95-android-0.8.10-sources.jar",
          "size": 2171,
          "sha512": "81dd298c943e0023bf144d98ad0c10468ee11c655ede44455d264ba2f35e07a9ff53b8fcccf419c3a49d53bb54f5359493c42781b1eca8efa939d84e77138cbc",
          "sha256": "48332c59ad5ae9e8c597d6f09c1aa8971fb86e78162d75dbcb07373903acf41a",
          "sha1": "6d48d8af889208b0acca3f744dda2b90a2344c1b",
          "md5": "21c1c99dfdd9a41515c85d27776a3a3d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b95-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2b95-android-0.8.10-javadoc.jar",
          "size": 270608,
          "sha512": "416582900782e2b89317a7e5510b00e92cced111ac25739355467354838f30922a8c358f38a612e0fab99cf8d033e56918878b1ae12a38d9e155f80d5e828947",
          "sha256": "0514eab0fa1e55dc8099be124638294e36c621c711c7e85bc33085461343240c",
          "sha1": "c6f38731b8288b78b627e04e5ddbb74dad2394a6",
          "md5": "2e2e0e3d97d4491d8978282016167f85"
        }
      ]
    }
  ]
}
