{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6f-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6f-android-0.8.12.aar",
          "url": "ble-characteristic-u2a6f-android-0.8.12.aar",
          "size": 3167,
          "sha512": "81c566dac8dbc9be11348bb2b7a0368501811a6df81d6dde0bfa65dc10788087f2ec85438f5812387bcb66dd590d465340c8746cb2136056cb06ed4c1f2adb2f",
          "sha256": "8f0ea1ab25ec26e11909d7e1542279d55be289c46e0140e8f1ade3281761ec63",
          "sha1": "d53ad495aed4dd2729e34cc14010fe74b6faf81f",
          "md5": "3301a60e770d55714ee0725869a6d67f"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6f",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6f-android-0.8.12.aar",
          "url": "ble-characteristic-u2a6f-android-0.8.12.aar",
          "size": 3167,
          "sha512": "81c566dac8dbc9be11348bb2b7a0368501811a6df81d6dde0bfa65dc10788087f2ec85438f5812387bcb66dd590d465340c8746cb2136056cb06ed4c1f2adb2f",
          "sha256": "8f0ea1ab25ec26e11909d7e1542279d55be289c46e0140e8f1ade3281761ec63",
          "sha1": "d53ad495aed4dd2729e34cc14010fe74b6faf81f",
          "md5": "3301a60e770d55714ee0725869a6d67f"
        }
      ]
    }
  ]
}
