{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6a-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.8.12.aar",
          "url": "ble-characteristic-u2a6a-android-0.8.12.aar",
          "size": 3123,
          "sha512": "cfb592ee8175cbc01c8c9664c375f2febbfd2dab3677e181db5878a421030f3907472115d2a9e7bc908bb4a100a08805653b3ad4592e2dc9636c1afd27ee1dba",
          "sha256": "36e49ed63305afe8d7acf42bae882a638592a0c8f9266d4e3439fd89d0caa234",
          "sha1": "c36225025b50f11fd3ff79bbc60c86d532618472",
          "md5": "6c747029881a3df45bb83e1d57ccd441"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.8.12.aar",
          "url": "ble-characteristic-u2a6a-android-0.8.12.aar",
          "size": 3123,
          "sha512": "cfb592ee8175cbc01c8c9664c375f2febbfd2dab3677e181db5878a421030f3907472115d2a9e7bc908bb4a100a08805653b3ad4592e2dc9636c1afd27ee1dba",
          "sha256": "36e49ed63305afe8d7acf42bae882a638592a0c8f9266d4e3439fd89d0caa234",
          "sha1": "c36225025b50f11fd3ff79bbc60c86d532618472",
          "md5": "6c747029881a3df45bb83e1d57ccd441"
        }
      ]
    }
  ]
}
