{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5f",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.4.jar",
          "url": "ble-characteristic-u2a5f-0.8.4.jar",
          "size": 1480,
          "sha512": "356b4a604e4c2b828221890cc5c492f2908388a5f64d7f9c2b5963d471c40c6f640c62edfc4f95cb75f363f3740a8c6ad4203a2ebf1b88da62b707900c780576",
          "sha256": "ff63e60c9e16d4301ebef02660668119712cd54c28ceb67f861a9e8f4ba69ca9",
          "sha1": "d569cfa4ac038c5d76bfc648b778d92ac019291c",
          "md5": "83ce1e634baa4e307131e19fd7b2451a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.4.jar",
          "url": "ble-characteristic-u2a5f-0.8.4.jar",
          "size": 1480,
          "sha512": "356b4a604e4c2b828221890cc5c492f2908388a5f64d7f9c2b5963d471c40c6f640c62edfc4f95cb75f363f3740a8c6ad4203a2ebf1b88da62b707900c780576",
          "sha256": "ff63e60c9e16d4301ebef02660668119712cd54c28ceb67f861a9e8f4ba69ca9",
          "sha1": "d569cfa4ac038c5d76bfc648b778d92ac019291c",
          "md5": "83ce1e634baa4e307131e19fd7b2451a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2a5f-0.8.4-javadoc.jar",
          "size": 109968,
          "sha512": "7192f9613104fb103645900a8f7a7fac4ca78194ed7797c4dedaaf183f5a80d0bb995d3a52720ed95aa1a96bf837779c077bc32753ca0f7dc36edddcd945b379",
          "sha256": "1242ee0d4da138c1eae6a68b2e416c6d9e7abcb822be89967fd771ea4cc76dfe",
          "sha1": "bb0837781c2dbeb61580712d6c5f07ca1f10c895",
          "md5": "89d4b79ad417318c843e6571010b87db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5f-0.8.4-sources.jar",
          "url": "ble-characteristic-u2a5f-0.8.4-sources.jar",
          "size": 1477,
          "sha512": "a2b3b2344bb71945c14cfe70e0842f7f647abcee3d545dfc39f515112cf1aad5e07a3365dc46364d41ff17ab0d555a31b09e82af01e160178d4620ae561cde0c",
          "sha256": "3d635a87b9442b0394540416707169c59682641f33632cfb8b07f4cef313cfe0",
          "sha1": "e661a64c3a5889103f10ad1c2f79a0d75e9711ca",
          "md5": "f99f25ecf37fb3ae3425c93910f34d0f"
        }
      ]
    }
  ]
}
