{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8d-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a8d-android-0.8.6.aar",
          "size": 3087,
          "sha512": "91bf26be103ebb931fb9ec8c102665af49666123b9a807527d6adbb45df3c5ef8dce58f6a593fccb8d6635f97757eafd390ec11a61f32e27dbbb761be16afd9c",
          "sha256": "34a610c8feb902782a493f977491b3ba2fc356c63eadd6dd9eaa6bc6ae08bc2f",
          "sha1": "772cbdc1c7a12431c4457f18abbaae867b6cbbe2",
          "md5": "86c699ad056829b0a066833c27a171b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8d",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8d-android-0.8.6.aar",
          "url": "ble-characteristic-u2a8d-android-0.8.6.aar",
          "size": 3087,
          "sha512": "91bf26be103ebb931fb9ec8c102665af49666123b9a807527d6adbb45df3c5ef8dce58f6a593fccb8d6635f97757eafd390ec11a61f32e27dbbb761be16afd9c",
          "sha256": "34a610c8feb902782a493f977491b3ba2fc356c63eadd6dd9eaa6bc6ae08bc2f",
          "sha1": "772cbdc1c7a12431c4457f18abbaae867b6cbbe2",
          "md5": "86c699ad056829b0a066833c27a171b4"
        }
      ]
    }
  ]
}
