{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-advertising-android",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "cblvnrxk6jbktigph5ix23dgky"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-advertising",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-advertising-android-0.1.9.aar",
          "url": "ble-advertising-android-0.1.9.aar",
          "size": 103011,
          "sha512": "3b66e4192427770f9760f7897047bac11b7785c837842b2c32aac78f7a068d8f8349a38aaa76511f8261fef1ef953dc43c4ca50fdafb7be24da11b4012a5b625",
          "sha256": "e41bbe9098e08d47c512dcd6d79d9d037db6353c704e4aaf37dc656e24791d2f",
          "sha1": "0026e9e38c3d73b5dbea3bc672ff127341954f87",
          "md5": "00a03f58404153ecea3a831afee45131"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-advertising",
          "version": {
            "requires": "0.2.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-advertising-android-0.1.9.aar",
          "url": "ble-advertising-android-0.1.9.aar",
          "size": 103011,
          "sha512": "3b66e4192427770f9760f7897047bac11b7785c837842b2c32aac78f7a068d8f8349a38aaa76511f8261fef1ef953dc43c4ca50fdafb7be24da11b4012a5b625",
          "sha256": "e41bbe9098e08d47c512dcd6d79d9d037db6353c704e4aaf37dc656e24791d2f",
          "sha1": "0026e9e38c3d73b5dbea3bc672ff127341954f87",
          "md5": "00a03f58404153ecea3a831afee45131"
        }
      ]
    }
  ]
}
