{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a70",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.7.jar",
          "url": "ble-characteristic-u2a70-0.8.7.jar",
          "size": 1879,
          "sha512": "8afa188d37302a5b25202974227876d44aecc3d1a95c5d35f1f089527abb9f2a900fa2cf8f4911417a5cf87127b9d56ecfb1bfa2895d71aaabd98936018e39ef",
          "sha256": "95b59affd5cc97925d86d84c15d604c6bf3249f78e024abf00fa25f07e1deaa9",
          "sha1": "25038cdd8bdb3b8976e45636a57c85e8648f1ee9",
          "md5": "349f17246fee1bd07d2197d02e20ce24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.7.jar",
          "url": "ble-characteristic-u2a70-0.8.7.jar",
          "size": 1879,
          "sha512": "8afa188d37302a5b25202974227876d44aecc3d1a95c5d35f1f089527abb9f2a900fa2cf8f4911417a5cf87127b9d56ecfb1bfa2895d71aaabd98936018e39ef",
          "sha256": "95b59affd5cc97925d86d84c15d604c6bf3249f78e024abf00fa25f07e1deaa9",
          "sha1": "25038cdd8bdb3b8976e45636a57c85e8648f1ee9",
          "md5": "349f17246fee1bd07d2197d02e20ce24"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a70-0.8.7-javadoc.jar",
          "size": 109403,
          "sha512": "0601fac37ee52a03dc39666979c033ba1a98c2dbb9bb5b99489bc588283ec93b16b7e45b7c8d5c99e44a7820301d2a74f8d0aae584409850db05c263e37bd935",
          "sha256": "81edb14487205bb234f85af0ce69edf00969b6dbccefc5da4912ed8159f824bf",
          "sha1": "3ef93ad99d2962bc45b65c1dafa79a389744ec49",
          "md5": "85eec588d24d68c7685680cffd6de3af"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a70-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a70-0.8.7-sources.jar",
          "size": 1700,
          "sha512": "fe932718f6c8490e8096e169cea71edde78ccd585dad6615813cd8e2b474d8d98cf0a0a696fdae0563d5a308de84f1aaee189031a0abc69d6b97754522accf83",
          "sha256": "5d17f3c4217d303b46cf79e41ebfa30d6b9ec2c802c4b6981adabbb6493650a7",
          "sha1": "5c4a4bc747fc9d0bea75ac6abe0eb2441edff568",
          "md5": "d242226f4fb6018d6573234e5e6169d5"
        }
      ]
    }
  ]
}
