{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7f-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.2.7.aar",
          "url": "ble-characteristic-u2a7f-android-0.2.7.aar",
          "size": 3092,
          "sha512": "92bb082cf5eaaada938e9e87b983b896bf64bcbc841629802d0566bf1931016beddd10386a4af59c3665decc94d1ac149335378311ceb62fd4e8f7abaeddeb03",
          "sha256": "06af12b924e5888eaa86323394a0a294a12ecb7e2470e8ede9c5ccaf66759338",
          "sha1": "9ea18d55e4ee2d62eb7f41840241deaca6acd093",
          "md5": "336850a8bc95ced0be1f172254c064c4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.2.7.aar",
          "url": "ble-characteristic-u2a7f-android-0.2.7.aar",
          "size": 3092,
          "sha512": "92bb082cf5eaaada938e9e87b983b896bf64bcbc841629802d0566bf1931016beddd10386a4af59c3665decc94d1ac149335378311ceb62fd4e8f7abaeddeb03",
          "sha256": "06af12b924e5888eaa86323394a0a294a12ecb7e2470e8ede9c5ccaf66759338",
          "sha1": "9ea18d55e4ee2d62eb7f41840241deaca6acd093",
          "md5": "336850a8bc95ced0be1f172254c064c4"
        }
      ]
    }
  ]
}
