{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a80-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a80-android-0.2.5.aar",
          "url": "ble-characteristic-u2a80-android-0.2.5.aar",
          "size": 3038,
          "sha512": "6d60b86fdef90a18d60657cbfa274615e2fd16512c8d3a2455b3e63e508b9ac9f0df014f3cfcbe0d1efc8195f01d74698321b8b635843b275ea3efe27f475e35",
          "sha256": "1c8cc4313e9f9c7aeeb24f50c9a44953ab067af524c520123e69361fa4d221ca",
          "sha1": "ac9d0bae9c60c249746cc93d7192ace597ff8806",
          "md5": "0c8eaabf81081ab53991fac6cbb8bc5f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a80-android-0.2.5.aar",
          "url": "ble-characteristic-u2a80-android-0.2.5.aar",
          "size": 3038,
          "sha512": "6d60b86fdef90a18d60657cbfa274615e2fd16512c8d3a2455b3e63e508b9ac9f0df014f3cfcbe0d1efc8195f01d74698321b8b635843b275ea3efe27f475e35",
          "sha256": "1c8cc4313e9f9c7aeeb24f50c9a44953ab067af524c520123e69361fa4d221ca",
          "sha1": "ac9d0bae9c60c249746cc93d7192ace597ff8806",
          "md5": "0c8eaabf81081ab53991fac6cbb8bc5f"
        }
      ]
    }
  ]
}
