{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2be1-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2be1",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2be1-android-0.8.12.aar",
          "url": "ble-characteristic-u2be1-android-0.8.12.aar",
          "size": 3109,
          "sha512": "69824aa2c08e647d30444d2f5048a0401ef15464ad7ec89476ace82cd172c18fca10909ec55dc9ed9afc616172bf1e5b96e66352e2047d28c1c244b546c30e02",
          "sha256": "8e851ee130af98d4f1287ffcf8cba68df2c3f1f523b48ea726b4a284299e0dda",
          "sha1": "d51b6f227836d6a32e2965602acaf9fa81227e8e",
          "md5": "853d12b72b6cadee57c5d4441ab5c259"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2be1",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2be1-android-0.8.12.aar",
          "url": "ble-characteristic-u2be1-android-0.8.12.aar",
          "size": 3109,
          "sha512": "69824aa2c08e647d30444d2f5048a0401ef15464ad7ec89476ace82cd172c18fca10909ec55dc9ed9afc616172bf1e5b96e66352e2047d28c1c244b546c30e02",
          "sha256": "8e851ee130af98d4f1287ffcf8cba68df2c3f1f523b48ea726b4a284299e0dda",
          "sha1": "d51b6f227836d6a32e2965602acaf9fa81227e8e",
          "md5": "853d12b72b6cadee57c5d4441ab5c259"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2be1-android-0.8.12-sources.jar",
          "url": "ble-characteristic-u2be1-android-0.8.12-sources.jar",
          "size": 2177,
          "sha512": "c6320afcc550ccd9157ebcfbbde10813d53d1dc8a978028ad4afacb7d051d539b5bfbac0180abc2ab219846834c409723fd6392c274d0257103594d3a17f81aa",
          "sha256": "e45e57812d507711a5af8b8b55737117fa44cc32f543186ff3e3e6fc8deedd46",
          "sha1": "1e1dbab173beb65c508c527fd2c8070b61c83b8f",
          "md5": "782d805e5a778e28d2ee5990e8e84196"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2be1-android-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2be1-android-0.8.12-javadoc.jar",
          "size": 271017,
          "sha512": "4c51c6db174aea61646bef3a30413c98e83e5902e3f79e97f23f53619dd43c1099e8a5c183b6a6d05b98e1c967e5bc070d163c38d53145d6b89f94d1e3bfa2ca",
          "sha256": "f4cd56bbf1e8caba3c3ad9edb8598a11bf94b26f41a88f2ccdf85416b038d726",
          "sha1": "2c97417041ca2d64fdd9cd033566c0ceaccf236c",
          "md5": "d337f77fed25402b682d737b3c509636"
        }
      ]
    }
  ]
}
