{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab0-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.8.13.aar",
          "url": "ble-characteristic-u2ab0-android-0.8.13.aar",
          "size": 3140,
          "sha512": "3cb52d578feb99086604a37427da3818106ac675ac1f63c9e5b62d2a8b3d1f191c2c2a0278e4feb6b6d207d5392fb55fd6a304900afd23f6a4b9da99079d648c",
          "sha256": "32366105349376862d346bfccaa7e611f9ac37808ec9e78ac68e154c4f94f037",
          "sha1": "77b8d6198be408476d6cf5b8c94a825366fccb29",
          "md5": "16a6dfda323aac71304da089787e1ce7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab0",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.8.13.aar",
          "url": "ble-characteristic-u2ab0-android-0.8.13.aar",
          "size": 3140,
          "sha512": "3cb52d578feb99086604a37427da3818106ac675ac1f63c9e5b62d2a8b3d1f191c2c2a0278e4feb6b6d207d5392fb55fd6a304900afd23f6a4b9da99079d648c",
          "sha256": "32366105349376862d346bfccaa7e611f9ac37808ec9e78ac68e154c4f94f037",
          "sha1": "77b8d6198be408476d6cf5b8c94a825366fccb29",
          "md5": "16a6dfda323aac71304da089787e1ce7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2ab0-android-0.8.13-sources.jar",
          "size": 2211,
          "sha512": "9b76e9fa8f06dd9ab73b94f22c1d12b5f11535255f436b43dad57cf62a6ba2765989be27a70d59c946f93bb16455577c158913e82dfd5fdaa71abb5fc2a139d9",
          "sha256": "51b3395c6149f04e73991fa9f0274a4454e1da236f59a81d9516e447697b53f0",
          "sha1": "ebb87e87ada4259e51c23a7fcb2256da2ff191bc",
          "md5": "c640485f45c7de52edbfa3d851eb8fe6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab0-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2ab0-android-0.8.13-javadoc.jar",
          "size": 271163,
          "sha512": "225fe032cbcdf2764df2664f979d4bd85574d0bd52f2a63939618ba82e3973aa8edaff79f7dc864a55580347d8664a96a0e90ae048b6a43418b3ca6c9856b31f",
          "sha256": "ea88fc2fef65d137f9fdaddda5db5630dd50b04eb2c6a784cb6d5495e4896f71",
          "sha1": "fafd901c27eb0b2c1182a866cb5773a7cfa08b01",
          "md5": "fa5bd0e6e4bab8f5ca4ef0b6a01b16a9"
        }
      ]
    }
  ]
}
