{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ac4-android",
    "version": "0.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac4",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac4-android-0.5.1.aar",
          "url": "ble-characteristic-u2ac4-android-0.5.1.aar",
          "size": 3030,
          "sha512": "1c50653dc48dc34c3a8e424529dc444256d340828dfc504043e565ea6fc4abb2616c0a695ea188ae44ad53cae3a234619d600a71b41d73c70aa0ba93ea1fcc8b",
          "sha256": "38c44d6c14ebafa48f5f5f32b1381f0aee8f775be0b4ec59a787bb5d3e1e9dae",
          "sha1": "d2700eeb121f94157f274ad61c735aa8a95971d3",
          "md5": "b41f52f4654f17bd4110df5b5b5880b8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ac4",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ac4-android-0.5.1.aar",
          "url": "ble-characteristic-u2ac4-android-0.5.1.aar",
          "size": 3030,
          "sha512": "1c50653dc48dc34c3a8e424529dc444256d340828dfc504043e565ea6fc4abb2616c0a695ea188ae44ad53cae3a234619d600a71b41d73c70aa0ba93ea1fcc8b",
          "sha256": "38c44d6c14ebafa48f5f5f32b1381f0aee8f775be0b4ec59a787bb5d3e1e9dae",
          "sha1": "d2700eeb121f94157f274ad61c735aa8a95971d3",
          "md5": "b41f52f4654f17bd4110df5b5b5880b8"
        }
      ]
    }
  ]
}
