{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a54-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6cu2oomv2fb67ivu2iebxgsxbm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a54",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-android-0.1.0.aar",
          "url": "ble-characteristic-u2a54-android-0.1.0.aar",
          "size": 2851,
          "sha512": "1bb31d1061ff278583899a017b78ddd0cef7fd47f07f2098a6079a33eb4824b7a1fafc3b128190947e46f05a3d267d5dd2525cf339327f973eda8f9c5a368a33",
          "sha256": "2164a99f3674f353bd2c70c7cdb6979d5a6b40f13387e1b5a90d8cc88d25935e",
          "sha1": "948919a91e2b2de770dd0def4ffef0307dfce43d",
          "md5": "a4620c2c5e38810f81b1e0af3dd33d63"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a54",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a54-android-0.1.0.aar",
          "url": "ble-characteristic-u2a54-android-0.1.0.aar",
          "size": 2851,
          "sha512": "1bb31d1061ff278583899a017b78ddd0cef7fd47f07f2098a6079a33eb4824b7a1fafc3b128190947e46f05a3d267d5dd2525cf339327f973eda8f9c5a368a33",
          "sha256": "2164a99f3674f353bd2c70c7cdb6979d5a6b40f13387e1b5a90d8cc88d25935e",
          "sha1": "948919a91e2b2de770dd0def4ffef0307dfce43d",
          "md5": "a4620c2c5e38810f81b1e0af3dd33d63"
        }
      ]
    }
  ]
}
