{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a66-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a66",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a66-android-0.2.8.aar",
          "url": "ble-characteristic-u2a66-android-0.2.8.aar",
          "size": 3212,
          "sha512": "745faf24a723824bc9b6068159e235c5be27c4106474024d4b8a1785d84d66874dbb9578d93e0cfc21a8a9cf38a66570f73927a3a502fa67ccba02af8a5bef18",
          "sha256": "92c66ad5f081382ddde67638ccac6865352278fe57c6a44b3bb9fd714606508c",
          "sha1": "3b5f096d17b2ea7a088760772f29bb9812de38a0",
          "md5": "b7e6effbf0a84cf1879db013b07eba20"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a66",
          "version": {
            "requires": "0.2.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a66-android-0.2.8.aar",
          "url": "ble-characteristic-u2a66-android-0.2.8.aar",
          "size": 3212,
          "sha512": "745faf24a723824bc9b6068159e235c5be27c4106474024d4b8a1785d84d66874dbb9578d93e0cfc21a8a9cf38a66570f73927a3a502fa67ccba02af8a5bef18",
          "sha256": "92c66ad5f081382ddde67638ccac6865352278fe57c6a44b3bb9fd714606508c",
          "sha1": "3b5f096d17b2ea7a088760772f29bb9812de38a0",
          "md5": "b7e6effbf0a84cf1879db013b07eba20"
        }
      ]
    }
  ]
}
