{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a36-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a36",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a36-android-0.2.0.aar",
          "url": "ble-characteristic-u2a36-android-0.2.0.aar",
          "size": 3260,
          "sha512": "45180d74a01c517f501046f1229fa9133e0337b1f5d5a0541179426c664ba84cdc6127f4af63ebb406c7b9a9bc3aaccb2e25c8b4bea57b041914d364667f18b2",
          "sha256": "ed1ef217b278131674fdd5575a4e43d737e5b6d0ee2eecf79331da8e88648b04",
          "sha1": "08cf3d5714f9f471f37c635c9be0713e0b751eaa",
          "md5": "7bb21e530f2223c033a4fb596de2811c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a36",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a36-android-0.2.0.aar",
          "url": "ble-characteristic-u2a36-android-0.2.0.aar",
          "size": 3260,
          "sha512": "45180d74a01c517f501046f1229fa9133e0337b1f5d5a0541179426c664ba84cdc6127f4af63ebb406c7b9a9bc3aaccb2e25c8b4bea57b041914d364667f18b2",
          "sha256": "ed1ef217b278131674fdd5575a4e43d737e5b6d0ee2eecf79331da8e88648b04",
          "sha1": "08cf3d5714f9f471f37c635c9be0713e0b751eaa",
          "md5": "7bb21e530f2223c033a4fb596de2811c"
        }
      ]
    }
  ]
}
