{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a17-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.8.6.aar",
          "url": "ble-characteristic-u2a17-android-0.8.6.aar",
          "size": 3104,
          "sha512": "04abaeee22a327c6985a4c3c1cd3ab85715cfcfe965866afe2dd94d4f8509a3cd85b6857db3b67b35371f71be0265b56a4a43f575b8177a28238c8e053f205e2",
          "sha256": "5722f97fa730e2c75869c0e881c99194dc1619ef40e25594db58a92a294d2680",
          "sha1": "44a457f16d0509963f9459af613534421d76ff2d",
          "md5": "26f14a9a6d446271ee2acba114de3e96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.8.6.aar",
          "url": "ble-characteristic-u2a17-android-0.8.6.aar",
          "size": 3104,
          "sha512": "04abaeee22a327c6985a4c3c1cd3ab85715cfcfe965866afe2dd94d4f8509a3cd85b6857db3b67b35371f71be0265b56a4a43f575b8177a28238c8e053f205e2",
          "sha256": "5722f97fa730e2c75869c0e881c99194dc1619ef40e25594db58a92a294d2680",
          "sha1": "44a457f16d0509963f9459af613534421d76ff2d",
          "md5": "26f14a9a6d446271ee2acba114de3e96"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a17-android-0.8.6-sources.jar",
          "size": 2197,
          "sha512": "d19def0f699b487972f3cb16cdc45cba9215a672f4e8841f907f1bcef192e8a5a01d81aaa33bec3df8c1cb2af4a1e4d489168ebf3452508033011a289ec11087",
          "sha256": "8c909b90d23730fddd880aaffde5476aacf51aa0619cb3f61def564a52739973",
          "sha1": "8b0b3593f276f917ebc16f693a7992502e09d09d",
          "md5": "2f23b297fc5c4275729dfb1cee006247"
        }
      ]
    }
  ]
}
