{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a50-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a50",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a50-android-0.8.9.aar",
          "url": "ble-characteristic-u2a50-android-0.8.9.aar",
          "size": 3216,
          "sha512": "ca5dedefd5d234e6a2528221cebf65cc60bfb74aa03d83281a3fff707d4c8e0db230f89fa040a7306ec3ec0ed80c222951806f329d432d9f93c4310b567d26c8",
          "sha256": "9c491a67aaebb429ac85e8b3938c04dac08d3267137e4474c553a469bd77a2b8",
          "sha1": "0954f81c7586938e0ffc36e6760b01334aeb0277",
          "md5": "a403e8c496205dbe88a20fd1cac5885c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a50",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a50-android-0.8.9.aar",
          "url": "ble-characteristic-u2a50-android-0.8.9.aar",
          "size": 3216,
          "sha512": "ca5dedefd5d234e6a2528221cebf65cc60bfb74aa03d83281a3fff707d4c8e0db230f89fa040a7306ec3ec0ed80c222951806f329d432d9f93c4310b567d26c8",
          "sha256": "9c491a67aaebb429ac85e8b3938c04dac08d3267137e4474c553a469bd77a2b8",
          "sha1": "0954f81c7586938e0ffc36e6760b01334aeb0277",
          "md5": "a403e8c496205dbe88a20fd1cac5885c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a50-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2a50-android-0.8.9-sources.jar",
          "size": 2193,
          "sha512": "21cd28e39b36b0e70f09146007ae3c3f59c320148c81a3430801852361a5b0dda185774c46c4e3469cb261ba715ee98f5d37b6268ed34e7dc4096e8c6de65425",
          "sha256": "4938d7075ae1eb45eba14624ed6ebc4d118d72a8d63dcef4b878e5e412c1b55c",
          "sha1": "fbdd426ce91e9477d47fa20ce6bc5032e05b891f",
          "md5": "fdda7172845353fc2fc2c9aae9132afa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a50-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2a50-android-0.8.9-javadoc.jar",
          "size": 272427,
          "sha512": "75059a5939b18d37ac0f2aa61be3f85a7da44f5d873fce1031ef90332e3b702acd04ea70c672cade4a0e8bf7dfee96ed3805fdeed787397d3c93335acb62e340",
          "sha256": "57b57e09a9f240c5cdfe42a7b4c481776ba381efef271819a25c02fba78f52c2",
          "sha1": "de0554c8be332d7f8e0e475d3925e7c625d67ebd",
          "md5": "81fad644686c067fe46bc679c7073fb0"
        }
      ]
    }
  ]
}
