{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b7e-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7e",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7e-android-0.8.9.aar",
          "url": "ble-characteristic-u2b7e-android-0.8.9.aar",
          "size": 3157,
          "sha512": "ffd0070fd73eaf75b7229b4aad95190953692ae5d746572c4ebd8fe4b8e8430f3e825255e91fee496e7c88f45413feaa9937f1fcb1b2f859bd782f496cf44458",
          "sha256": "cb4124f67369b67f0cc18a8b6c77b7726e4c457b9e1b986e6f769ebc45e60339",
          "sha1": "b5a0ce8f099499a0b3d549be3458aa75c9f0d2dc",
          "md5": "5fc487b0cf53814d66dcc7f0d5368860"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7e",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7e-android-0.8.9.aar",
          "url": "ble-characteristic-u2b7e-android-0.8.9.aar",
          "size": 3157,
          "sha512": "ffd0070fd73eaf75b7229b4aad95190953692ae5d746572c4ebd8fe4b8e8430f3e825255e91fee496e7c88f45413feaa9937f1fcb1b2f859bd782f496cf44458",
          "sha256": "cb4124f67369b67f0cc18a8b6c77b7726e4c457b9e1b986e6f769ebc45e60339",
          "sha1": "b5a0ce8f099499a0b3d549be3458aa75c9f0d2dc",
          "md5": "5fc487b0cf53814d66dcc7f0d5368860"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7e-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2b7e-android-0.8.9-sources.jar",
          "size": 2163,
          "sha512": "85b54575dfac880b5f3b483635026b845fe64d9496d190acd91cf0436f7175c37abf8db6d3304c797d46b1e06b339dd0ffc47d674259c3fac19de52b876c4b7d",
          "sha256": "53fb08be712b404a9834602cb787c886b45ab2b90d87e52a7e7ccfdb905c959e",
          "sha1": "3c7015502293bad3d4ddb77db1d5c9f5bfa44dbb",
          "md5": "eff200c07c0429835314af59435d8a18"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b7e-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2b7e-android-0.8.9-javadoc.jar",
          "size": 270542,
          "sha512": "c806eda9302b16754a84e1d1e47a55b5e22a3d237be03b4864c69877601a482d36334ab5ac003f74003d887ae42e273d2b3b54374cee6f1aec6f8444683f077c",
          "sha256": "c6f9e9f3c82bc8dd0815b1222ad007d6c80072f8c0a79d14ea7353957b6d1830",
          "sha1": "3b64d07bef2f0fe92ac9cba9665893146ab54d2e",
          "md5": "a2dd726aacd1c1e31f7701a42cc948be"
        }
      ]
    }
  ]
}
