{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b25-android",
    "version": "0.8.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b25",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-android-0.8.11.aar",
          "url": "ble-characteristic-u2b25-android-0.8.11.aar",
          "size": 3171,
          "sha512": "2e64f75793872d19d54c111b0256cf9f2f4cbdc3d86379703f8d6730492124d12f8e3825ace1a6e93861dd3959ccb7a06347d467e9f497cf8599f3b6d1dbfb6b",
          "sha256": "dece66b39ce7688474aada34ef3bc38c1006db33392731cab9b7112015bd8f77",
          "sha1": "461dda9950aa28e096039207eb209af7249e61dd",
          "md5": "1bcdbdeda541aeb7d0fd6051411b5f4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b25",
          "version": {
            "requires": "0.8.11"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b25-android-0.8.11.aar",
          "url": "ble-characteristic-u2b25-android-0.8.11.aar",
          "size": 3171,
          "sha512": "2e64f75793872d19d54c111b0256cf9f2f4cbdc3d86379703f8d6730492124d12f8e3825ace1a6e93861dd3959ccb7a06347d467e9f497cf8599f3b6d1dbfb6b",
          "sha256": "dece66b39ce7688474aada34ef3bc38c1006db33392731cab9b7112015bd8f77",
          "sha1": "461dda9950aa28e096039207eb209af7249e61dd",
          "md5": "1bcdbdeda541aeb7d0fd6051411b5f4e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-android-0.8.11-sources.jar",
          "url": "ble-characteristic-u2b25-android-0.8.11-sources.jar",
          "size": 2181,
          "sha512": "3e835b437af7181d262fd66006f753317e7a50cfc42640644d2528fcf53b77a37d2206514af1a8ae9487930a386549345d845d37f0e5d6085de60bc1c88f3df0",
          "sha256": "55be95a23355e4cd5481eedb64b386fc6b638ba2704a4d0ce11c67b703fa13a6",
          "sha1": "3bc15247d85200eeb2313f8c4771c89a6bb2a2f5",
          "md5": "583b1ab894dff92cd442b6981e38dde6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b25-android-0.8.11-javadoc.jar",
          "url": "ble-characteristic-u2b25-android-0.8.11-javadoc.jar",
          "size": 270591,
          "sha512": "35fd9c65130920d7a1210486dca61617de7f6fe78f6b4cd7354f1477d35e98e8da6e8d51bfbf9b85c18250185b49a8fd19aaeb9fe700558b90b6eab4ac37e822",
          "sha256": "f2af986b94ddc4bad2d205ec64e00adb48635197fd4d671df4628d47ac6f3bcf",
          "sha1": "ee657057d59ed5773a1aabdbf780c86c5d3f46a2",
          "md5": "1f2b55701d68ba8f575f6f505b0ba0d1"
        }
      ]
    }
  ]
}
