{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a32-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.8.6.aar",
          "url": "ble-characteristic-u2a32-android-0.8.6.aar",
          "size": 3090,
          "sha512": "3d3229d26189903ee39ca05b19f7bc239536aaade07af99bacffda8949be7862da638475adc9c35a1002d51fe52ccfce07e8ab15416511bb276c9dfd3b369275",
          "sha256": "5c228b914412fc4fdc3c21df72d3cd0fdd9886713d30182bc1464acabfc44a36",
          "sha1": "1ad3969e5ef099d5b32e15b5a9c735fc5382e664",
          "md5": "e4a34793a84ce0b5b21b6a2b4292dee4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a32",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.8.6.aar",
          "url": "ble-characteristic-u2a32-android-0.8.6.aar",
          "size": 3090,
          "sha512": "3d3229d26189903ee39ca05b19f7bc239536aaade07af99bacffda8949be7862da638475adc9c35a1002d51fe52ccfce07e8ab15416511bb276c9dfd3b369275",
          "sha256": "5c228b914412fc4fdc3c21df72d3cd0fdd9886713d30182bc1464acabfc44a36",
          "sha1": "1ad3969e5ef099d5b32e15b5a9c735fc5382e664",
          "md5": "e4a34793a84ce0b5b21b6a2b4292dee4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a32-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a32-android-0.8.6-sources.jar",
          "size": 2186,
          "sha512": "8449c5be75fa124f1f6c23d9bec5182ed52a980cc6214a4aecffe2145b7ce7273670a81382672318daf1690b81aa45aecd31c77e3a3006bae8b470686d92e65a",
          "sha256": "7f159115c5d3ab3a5b3bcea4ab63c33a0f5721c790425bb1d74af201750037cb",
          "sha1": "4162320740059d3db7f965277cc4c426c7521c60",
          "md5": "6f36c603d158b060790d200c919947a0"
        }
      ]
    }
  ]
}
