{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a14-android",
    "version": "0.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "jsltpqucmvdo5cnccfghyrithm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a14",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a14-android-0.2.8.aar",
          "url": "ble-characteristic-u2a14-android-0.2.8.aar",
          "size": 3178,
          "sha512": "8a8fd14b3517d67b016329d21fa8a92fbb736193e63496e453f248b663caab3f5107a5bbc76f45a2a8025ef3b4016aaf4da69e85593b51520f16e3570bc2c4f0",
          "sha256": "226270418a84fab0fb0f8305c9038864aae4282e72991a268e2e77af80f6eaa0",
          "sha1": "24c138f9de0a4f60b73ab71c18ccb817be9411f3",
          "md5": "c766b7cad3a4d9db49b4f4262f87966a"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a14",
          "version": {
            "requires": "0.2.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a14-android-0.2.8.aar",
          "url": "ble-characteristic-u2a14-android-0.2.8.aar",
          "size": 3178,
          "sha512": "8a8fd14b3517d67b016329d21fa8a92fbb736193e63496e453f248b663caab3f5107a5bbc76f45a2a8025ef3b4016aaf4da69e85593b51520f16e3570bc2c4f0",
          "sha256": "226270418a84fab0fb0f8305c9038864aae4282e72991a268e2e77af80f6eaa0",
          "sha1": "24c138f9de0a4f60b73ab71c18ccb817be9411f3",
          "md5": "c766b7cad3a4d9db49b4f4262f87966a"
        }
      ]
    }
  ]
}
