{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5a",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5a-0.8.12.jar",
          "url": "ble-characteristic-u2a5a-0.8.12.jar",
          "size": 1743,
          "sha512": "528f1fcd1b0fe5c053f99d0bda8d168ad2b900934d9b3cacd2acb4dea8cb820533145f9571f434c09e3279152edf7a58026c2d55341b18652ed8bc8059f8c327",
          "sha256": "4690c38188245bf9d87823e8ec84a9677db38517b9bc72806ae76bf31613ee5c",
          "sha1": "3be8ebaa3859e90913e74a5569025d7b1a0ab488",
          "md5": "0ef4951f32ad24a16279dbe84efd0a04"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5a-0.8.12.jar",
          "url": "ble-characteristic-u2a5a-0.8.12.jar",
          "size": 1743,
          "sha512": "528f1fcd1b0fe5c053f99d0bda8d168ad2b900934d9b3cacd2acb4dea8cb820533145f9571f434c09e3279152edf7a58026c2d55341b18652ed8bc8059f8c327",
          "sha256": "4690c38188245bf9d87823e8ec84a9677db38517b9bc72806ae76bf31613ee5c",
          "sha1": "3be8ebaa3859e90913e74a5569025d7b1a0ab488",
          "md5": "0ef4951f32ad24a16279dbe84efd0a04"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5a-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2a5a-0.8.12-javadoc.jar",
          "size": 86140,
          "sha512": "21d012b0eff9c3977e1f250fc2ed44100844c47d4dc2e236ba67865b4361116aa452c0be98972528fa2ff75465f847e7ea393f9cc0dea4e6c97f593161961030",
          "sha256": "7430d98e08be9c7791ff186fd4ea41b4716900cd13896e4d8673e1c1ec86c590",
          "sha1": "f733f3c79d60a78a005fae5e8ab977d8ccb6f3d4",
          "md5": "d953fbd1d575d1fba6521722a515d29b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5a-0.8.12-sources.jar",
          "url": "ble-characteristic-u2a5a-0.8.12-sources.jar",
          "size": 1618,
          "sha512": "70d03406a5c7f99da4cefc374d57884edd2f5d4f887da9a77092f6ae9c44bc2179d46a151ce28393cd29596e935e296e53553ceb7a5e1c4866b1c27c244751e2",
          "sha256": "e6414813b81b952a857edefb0acc869ad8b6ab765f71207eb69bb00b69459904",
          "sha1": "af954dd879d989ca689c22f3fd22483b6266e992",
          "md5": "823c408601acba06e8f130e87c18d379"
        }
      ]
    }
  ]
}
