{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2906",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2906-0.6.0.jar",
          "url": "ble-descriptor-u2906-0.6.0.jar",
          "size": 2136,
          "sha512": "4b0152391ff9a2bbb2475203fbe299adce9b05d28298bed5f29ec3326b144d10592c0a07e6a375db737f89d6e37501c7465f842afbb32f8b0f65687df5279b9e",
          "sha256": "25e1fac7db1dc7176bdd18670d3182659e57ab61e20c5f3eea46cfe1625fc705",
          "sha1": "c4129b286dabfb7c3768c89981d59b1056503f5e",
          "md5": "0e9a9286cad74e4fad095ce26548a9bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2906-0.6.0.jar",
          "url": "ble-descriptor-u2906-0.6.0.jar",
          "size": 2136,
          "sha512": "4b0152391ff9a2bbb2475203fbe299adce9b05d28298bed5f29ec3326b144d10592c0a07e6a375db737f89d6e37501c7465f842afbb32f8b0f65687df5279b9e",
          "sha256": "25e1fac7db1dc7176bdd18670d3182659e57ab61e20c5f3eea46cfe1625fc705",
          "sha1": "c4129b286dabfb7c3768c89981d59b1056503f5e",
          "md5": "0e9a9286cad74e4fad095ce26548a9bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2906-0.6.0-javadoc.jar",
          "url": "ble-descriptor-u2906-0.6.0-javadoc.jar",
          "size": 111455,
          "sha512": "ca869bdad51e2cf9efe8df83d5b8ac6e667d23e45386e8152c063c2cff2ac23ea246f1f4d26a189da93cd67d61159babc940ac6f3e53deeecaa351859ed9435e",
          "sha256": "12287ea85fb15647a6fa8331fdad61fefd50d0b31f6c1c1aea0c2c02dd9cea89",
          "sha1": "7ad44dcd198769dbc39d9141a385f1467d1bdfee",
          "md5": "7b3484335bf3c0aa29c1971df89d9048"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2906-0.6.0-sources.jar",
          "url": "ble-descriptor-u2906-0.6.0-sources.jar",
          "size": 2187,
          "sha512": "4ba2a66cf7f250bfb7f16348869e7c652970357af90d77f9f07ff424ad96d4e5501fa6edbb31671a529a98892a52a918b0e2e4294326ce311bfde4d978200963",
          "sha256": "63acae11929e242a6a78300ae9e50b85f77b9f9fef4219957eacfba4f807e8d5",
          "sha1": "0d42b3c290ba1d80a920915d544929536a7fb55b",
          "md5": "d30f9f6e03f9254d0e63ad1c58fce6ef"
        }
      ]
    }
  ]
}
