{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9b-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "6kbky3qpubflpkzntdywdcsg5q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9b-android-0.1.2.aar",
          "url": "ble-characteristic-u2a9b-android-0.1.2.aar",
          "size": 3071,
          "sha512": "672ce58a4e9fe3f5182af8603e172ffae780b3eeec52a89406ebac009c14edd2ff5075bf68b7cffc1c9743f72ef4e64da360f7ef0fb974902f2fda2631f27861",
          "sha256": "ffffc6a8565ea298a4be5124351f885c006a9c95dd15dcfbebd05608e89f4c45",
          "sha1": "e71c748761e67eec1900d58a279cb38354220c25",
          "md5": "7633c8b7e9fe637ebb0d0feb2a76d598"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9b",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9b-android-0.1.2.aar",
          "url": "ble-characteristic-u2a9b-android-0.1.2.aar",
          "size": 3071,
          "sha512": "672ce58a4e9fe3f5182af8603e172ffae780b3eeec52a89406ebac009c14edd2ff5075bf68b7cffc1c9743f72ef4e64da360f7ef0fb974902f2fda2631f27861",
          "sha256": "ffffc6a8565ea298a4be5124351f885c006a9c95dd15dcfbebd05608e89f4c45",
          "sha1": "e71c748761e67eec1900d58a279cb38354220c25",
          "md5": "7633c8b7e9fe637ebb0d0feb2a76d598"
        }
      ]
    }
  ]
}
