{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ba4-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba4",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba4-android-0.4.4.aar",
          "url": "ble-characteristic-u2ba4-android-0.4.4.aar",
          "size": 3070,
          "sha512": "2913e64d81585e0680c2adc35ed431f3c50cb6ac2875289b1f421e98932687ccf811dcac300c64c35ffb2ca6ff8fe182e2ba90aeb1d6646a6b8e485542032b48",
          "sha256": "a26cfc14bcc0aa9758a1fe38f49a158de2cbcc1381b00ea4342557ba9b4ce903",
          "sha1": "71c7ee43484ebc0eb2a76a11cc591beaa070f8a4",
          "md5": "3d7fbddd98d51540e058d8a69b47bf73"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ba4",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ba4-android-0.4.4.aar",
          "url": "ble-characteristic-u2ba4-android-0.4.4.aar",
          "size": 3070,
          "sha512": "2913e64d81585e0680c2adc35ed431f3c50cb6ac2875289b1f421e98932687ccf811dcac300c64c35ffb2ca6ff8fe182e2ba90aeb1d6646a6b8e485542032b48",
          "sha256": "a26cfc14bcc0aa9758a1fe38f49a158de2cbcc1381b00ea4342557ba9b4ce903",
          "sha1": "71c7ee43484ebc0eb2a76a11cc591beaa070f8a4",
          "md5": "3d7fbddd98d51540e058d8a69b47bf73"
        }
      ]
    }
  ]
}
