{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6b",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "e3ikqwiwsbdaddptppumhoyem4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.1.0.jar",
          "url": "ble-characteristic-u2a6b-0.1.0.jar",
          "size": 4147,
          "sha512": "69b4449c391f5571bcbabd32482a0b222366e2d5f8e1ba47c4b322281edbc190c4679d800454001bfbc391498ec6d2cd9277aceef250320504a85fe366c22013",
          "sha256": "ccbacc76ff96e6fe4de202d0ab242abf27aa34ddc43641e106a10c0c668ef3c6",
          "sha1": "219828577532317854c9bc80f44e1df4411ac2c8",
          "md5": "5f946473f6e01f1974abb3fbed955fbf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6b-0.1.0.jar",
          "url": "ble-characteristic-u2a6b-0.1.0.jar",
          "size": 4147,
          "sha512": "69b4449c391f5571bcbabd32482a0b222366e2d5f8e1ba47c4b322281edbc190c4679d800454001bfbc391498ec6d2cd9277aceef250320504a85fe366c22013",
          "sha256": "ccbacc76ff96e6fe4de202d0ab242abf27aa34ddc43641e106a10c0c668ef3c6",
          "sha1": "219828577532317854c9bc80f44e1df4411ac2c8",
          "md5": "5f946473f6e01f1974abb3fbed955fbf"
        }
      ]
    }
  ]
}
