{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2d",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.7.jar",
          "url": "ble-characteristic-u2b2d-0.8.7.jar",
          "size": 1521,
          "sha512": "8fc172577de4cdab9f6116af9842a31a1eb41be13e74446c16c8f906fea989aa8d717d4287f460d87414cf847da0f940beb834e6717e8eb504a9aef55f96bead",
          "sha256": "43389b193450e3e6e62312a2e21c295fb0a85c6be4cbfe520c550b569d5b4dd5",
          "sha1": "fbf5194bc389955ed856fa03a921dc131e2076e0",
          "md5": "ca30e014d2c998f9fda7a3d30f698741"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.7.jar",
          "url": "ble-characteristic-u2b2d-0.8.7.jar",
          "size": 1521,
          "sha512": "8fc172577de4cdab9f6116af9842a31a1eb41be13e74446c16c8f906fea989aa8d717d4287f460d87414cf847da0f940beb834e6717e8eb504a9aef55f96bead",
          "sha256": "43389b193450e3e6e62312a2e21c295fb0a85c6be4cbfe520c550b569d5b4dd5",
          "sha1": "fbf5194bc389955ed856fa03a921dc131e2076e0",
          "md5": "ca30e014d2c998f9fda7a3d30f698741"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b2d-0.8.7-javadoc.jar",
          "size": 107218,
          "sha512": "7cb342960611a48d65f7c12a7d778d0bbc11fd764832dc699f7c6596e57a8e1733aaa6645fca88088dc7f22a551e55d479fdb1f0edaea3b3e9761c6310ce2a16",
          "sha256": "65489fb6ff89f175fa4743d48b06cdc941ba85a1482bfd3baa5a29e84a6ef7e0",
          "sha1": "d9493aa3eb29e777a93d7900be2214b8dd5ef15e",
          "md5": "1d7af944b2a56bec14d055bdd00c261d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2d-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b2d-0.8.7-sources.jar",
          "size": 1473,
          "sha512": "8e0b54c319f04940c66bf10da0f8db60cbd51cc5430cf05499ec865ca045565f90ddfcfb5f9d1352bad267b44524c7d93faea936629ba1c6011914e6beaa7b74",
          "sha256": "f799273b176e5547fb0ca4fdc1ca511d40637320d45d9d2988777b42c491717e",
          "sha1": "f98cfcb5d547f144215393819cbbcc03145262d2",
          "md5": "a4f62c24af971e9042dce2c0ce3e2748"
        }
      ]
    }
  ]
}
