{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b7b-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7b",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7b-android-0.8.12.aar",
          "url": "ble-characteristic-u2b7b-android-0.8.12.aar",
          "size": 3170,
          "sha512": "38a656be3e01fcca376b05fd2372287d0dbd479b2f4211c59b7e847eeb5192dd70be4981aa912129956cfe1b8d007ba576621a7eca37ec09e91006e35ba1b253",
          "sha256": "c19e83206f767ae58754c7b8d65f1de53ff715901ed496786ee2853e8a0f86cb",
          "sha1": "e532647d16cc8282e4457893f5caae97f92dd201",
          "md5": "8e3e7e9e3b7b29424db34789d12a7d22"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b7b",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b7b-android-0.8.12.aar",
          "url": "ble-characteristic-u2b7b-android-0.8.12.aar",
          "size": 3170,
          "sha512": "38a656be3e01fcca376b05fd2372287d0dbd479b2f4211c59b7e847eeb5192dd70be4981aa912129956cfe1b8d007ba576621a7eca37ec09e91006e35ba1b253",
          "sha256": "c19e83206f767ae58754c7b8d65f1de53ff715901ed496786ee2853e8a0f86cb",
          "sha1": "e532647d16cc8282e4457893f5caae97f92dd201",
          "md5": "8e3e7e9e3b7b29424db34789d12a7d22"
        }
      ]
    }
  ]
}
