{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a8c-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-android-0.8.12.aar",
          "url": "ble-characteristic-u2a8c-android-0.8.12.aar",
          "size": 3152,
          "sha512": "596447546039c0055582800038b296334435c3879360b05dfbeb302587018571ee15786b65d908a563496102af3b188875381178d74ba464e91e8560a30e0ea1",
          "sha256": "a547c38b5b08ebf5443d17ff47682896688227bb1bab43a8a85eee8e77643a3d",
          "sha1": "9dede6bc95e48d8f612ab1a442692f1b11ae7dee",
          "md5": "ae2a2b9930045f1384a82aebd2d2e30e"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a8c",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a8c-android-0.8.12.aar",
          "url": "ble-characteristic-u2a8c-android-0.8.12.aar",
          "size": 3152,
          "sha512": "596447546039c0055582800038b296334435c3879360b05dfbeb302587018571ee15786b65d908a563496102af3b188875381178d74ba464e91e8560a30e0ea1",
          "sha256": "a547c38b5b08ebf5443d17ff47682896688227bb1bab43a8a85eee8e77643a3d",
          "sha1": "9dede6bc95e48d8f612ab1a442692f1b11ae7dee",
          "md5": "ae2a2b9930045f1384a82aebd2d2e30e"
        }
      ]
    }
  ]
}
