{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a25-android",
    "version": "0.2.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "x6nyasohnvdrtpp4affpidlfoi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.6.aar",
          "url": "ble-characteristic-u2a25-android-0.2.6.aar",
          "size": 3108,
          "sha512": "228e9e1b0ffb49cfe07d1639699c90bb8d06e60e58218d19a78b81875fd832d9e27cc4e1baa458cf4e2235829695ea7ac02316d95f0363a3bde407d0fbc1730a",
          "sha256": "6a1875449066338e1e46a8defa14c5ead1648d730bc3138f00c653314a55d37e",
          "sha1": "f91ac4679cc76c3c391ba6a14b164066a5473def",
          "md5": "4d497289c9d27254dcd61af562d4249e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.6.aar",
          "url": "ble-characteristic-u2a25-android-0.2.6.aar",
          "size": 3108,
          "sha512": "228e9e1b0ffb49cfe07d1639699c90bb8d06e60e58218d19a78b81875fd832d9e27cc4e1baa458cf4e2235829695ea7ac02316d95f0363a3bde407d0fbc1730a",
          "sha256": "6a1875449066338e1e46a8defa14c5ead1648d730bc3138f00c653314a55d37e",
          "sha1": "f91ac4679cc76c3c391ba6a14b164066a5473def",
          "md5": "4d497289c9d27254dcd61af562d4249e"
        }
      ]
    }
  ]
}
