{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab7",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-0.8.5.jar",
          "url": "ble-characteristic-u2ab7-0.8.5.jar",
          "size": 1576,
          "sha512": "addb6985ba2dcefb1fbf2c4770ff2d733a2c68a9eb89cfb4c85af3ecc1afe775dbf8ba4ce099102f5c6014343512f05ae183d4cba0d394b9d9cd738b470e5c34",
          "sha256": "30e6a41e97564b12b8edb521e39b45f757bc04ab2ab0d7dcde6ffd2ec586e6a1",
          "sha1": "f12188a829afec96edeef57131bcb407569cf6ec",
          "md5": "6f1cc69e29c053803fefc121d52562e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab7-0.8.5.jar",
          "url": "ble-characteristic-u2ab7-0.8.5.jar",
          "size": 1576,
          "sha512": "addb6985ba2dcefb1fbf2c4770ff2d733a2c68a9eb89cfb4c85af3ecc1afe775dbf8ba4ce099102f5c6014343512f05ae183d4cba0d394b9d9cd738b470e5c34",
          "sha256": "30e6a41e97564b12b8edb521e39b45f757bc04ab2ab0d7dcde6ffd2ec586e6a1",
          "sha1": "f12188a829afec96edeef57131bcb407569cf6ec",
          "md5": "6f1cc69e29c053803fefc121d52562e8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab7-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2ab7-0.8.5-javadoc.jar",
          "size": 107375,
          "sha512": "a14e92dfa5e584689b79048e58422d79f9a42197c2fa79daa31d832c80ed9b9e8cdb4324818c5c3ecf7ff37665b33669ab9336ff65afc98e8317dc585f959b3c",
          "sha256": "89b93ba4d77c8e81aef48c1493fae3a324e643dd1fa375a9f8a1e3a8d0b55b58",
          "sha1": "e940dfa34e806547b30bdb69d2d1806ad0c223bc",
          "md5": "ae88e853409441120e6435e146cabd01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab7-0.8.5-sources.jar",
          "url": "ble-characteristic-u2ab7-0.8.5-sources.jar",
          "size": 1488,
          "sha512": "6325300da59d9c674a33b7efcc2d7b816176e10c03323c1a232b05abbea5f6add260f033db3c7b022a2551366b70a13c1d6a1f60df4d151b24f4c88b873d0b08",
          "sha256": "9e1b3ae1fa542f2bdd2d03816fe776e92fa31dc9b455c982b8b3b303f7d4a200",
          "sha1": "a3826238210e07efcbb16e4a677e76c684ab5533",
          "md5": "9f5d7ef7a39e54d1f7db3f17cc93dbef"
        }
      ]
    }
  ]
}
