{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a34",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.6.jar",
          "url": "ble-characteristic-u2a34-0.8.6.jar",
          "size": 1482,
          "sha512": "53a8c8cf17d666072a3c49659ff4e324178f896947d9927b029078608d4791f6c2b0b832587344af3dd94c257f0462a8d4c97efea8dc4484f6bc8be212036692",
          "sha256": "073e3907ef52acbe7c2ed9224e185840256d8905870cc43b4f4e52b9d185a2b6",
          "sha1": "75acd2704e0b556b41627f17dc8adc38c83f8d39",
          "md5": "49a275861a83010254d7a8481b881104"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.6.jar",
          "url": "ble-characteristic-u2a34-0.8.6.jar",
          "size": 1482,
          "sha512": "53a8c8cf17d666072a3c49659ff4e324178f896947d9927b029078608d4791f6c2b0b832587344af3dd94c257f0462a8d4c97efea8dc4484f6bc8be212036692",
          "sha256": "073e3907ef52acbe7c2ed9224e185840256d8905870cc43b4f4e52b9d185a2b6",
          "sha1": "75acd2704e0b556b41627f17dc8adc38c83f8d39",
          "md5": "49a275861a83010254d7a8481b881104"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a34-0.8.6-javadoc.jar",
          "size": 107226,
          "sha512": "6959a7708a714e1574d3465f71a8a050aca7391aa2293432769d1c1929b91d9c89a3d87cf1cf2cf68ce5d40ac4a87ca6fa1ef5e504f1e5cee71a364f8e6f2a50",
          "sha256": "7aadb757e9cdbf92b460a9ea90072fa9de7807a3f92a7a60e15b299f7b3da978",
          "sha1": "a288118c902bc8d702c348a4fdc89e4ef9c417a7",
          "md5": "43a865249540be41f20617bdc7af811f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a34-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a34-0.8.6-sources.jar",
          "size": 1487,
          "sha512": "fa17bfe3cf71b4aa8f265c2640e534db4cc270ad3b6ceb94ee7ef5d3b382de71305c8b4efed068c71b25862638c8e2984c85b8f7380bdd85ba6fba0b62fa3319",
          "sha256": "cb6102a860bb6eb234811d3ffb7e90c24105090462234a70d563f5aeee00e8d4",
          "sha1": "5e77fe444a1c0a8fe7d87b5a2d58898dee668e96",
          "md5": "fe4ea2f069623fe3ae3c45ed256c0fff"
        }
      ]
    }
  ]
}
