{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae5",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.12.jar",
          "url": "ble-characteristic-u2ae5-0.8.12.jar",
          "size": 1921,
          "sha512": "ceef522efc1277d50f11b660876307b3d95a4b12024dce8e2e41b68771916b031bed4f4bf46e80c5bafc967e1254653da7fc3f1060f0800362e32f720a3fc02b",
          "sha256": "80e5f319c9e364ff8161605135979ebbf2f9d86c4cc2d62c0d794348e8a56db9",
          "sha1": "87cc0d2f06c20016e7f226a268f5434900e088ec",
          "md5": "52a2b2a84834b5add614c0833f5fba1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.12.jar",
          "url": "ble-characteristic-u2ae5-0.8.12.jar",
          "size": 1921,
          "sha512": "ceef522efc1277d50f11b660876307b3d95a4b12024dce8e2e41b68771916b031bed4f4bf46e80c5bafc967e1254653da7fc3f1060f0800362e32f720a3fc02b",
          "sha256": "80e5f319c9e364ff8161605135979ebbf2f9d86c4cc2d62c0d794348e8a56db9",
          "sha1": "87cc0d2f06c20016e7f226a268f5434900e088ec",
          "md5": "52a2b2a84834b5add614c0833f5fba1b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2ae5-0.8.12-javadoc.jar",
          "size": 107737,
          "sha512": "57860c83351dbd585c7698eeafca2574af91ea4cc0659676d293d9ba8defd52bb28b3645221d524fb26de2db0b5d3511a5368ea2c71f2df2461ee95fd950a17a",
          "sha256": "9a535a44777d8d54725847bd62bd6d065a932f0e90ff5d6c84bdc97962c1c0a5",
          "sha1": "f09bb7613a5ca395a541aba49426a6bd8213f769",
          "md5": "05e0b4f72025470ccfed80611f8543a6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae5-0.8.12-sources.jar",
          "url": "ble-characteristic-u2ae5-0.8.12-sources.jar",
          "size": 1764,
          "sha512": "3d768425c85fed35c1ebe4da7340e5eb3145404ff89e0dcf745ecea92173a7ccc62322bb729cf2cef5487d592dffe3efd3ec2d9a4076cfa8c3384024cc2dd6fc",
          "sha256": "e6ac63556a025ebfc93506a2e11e57925fe58c75069af0c3a8f5af3d21a01401",
          "sha1": "8c89b02bd209f80ec2b543b69bb9e0a933671315",
          "md5": "fd4aced9b3b577c47a46eba3f331f5dc"
        }
      ]
    }
  ]
}
