{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a36",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a36-0.8.13.jar",
          "url": "ble-characteristic-u2a36-0.8.13.jar",
          "size": 3329,
          "sha512": "4d53af7ca2a9f4425c0776012e94bd327742e870e6f408b2bd556e67a93a8004ceb1528ecc2b64370e10ed16a26f91c81ca19c99010d3f95739325fe2d08ca84",
          "sha256": "3dba3551789a9f854bed56c56bd554c5233413166e49e20291648f1f60a3f2bd",
          "sha1": "b270af07a2b8f600e9231a8fa788864551b8a9f9",
          "md5": "4239ddfad1e044626576ead02ec0705b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a36-0.8.13.jar",
          "url": "ble-characteristic-u2a36-0.8.13.jar",
          "size": 3329,
          "sha512": "4d53af7ca2a9f4425c0776012e94bd327742e870e6f408b2bd556e67a93a8004ceb1528ecc2b64370e10ed16a26f91c81ca19c99010d3f95739325fe2d08ca84",
          "sha256": "3dba3551789a9f854bed56c56bd554c5233413166e49e20291648f1f60a3f2bd",
          "sha1": "b270af07a2b8f600e9231a8fa788864551b8a9f9",
          "md5": "4239ddfad1e044626576ead02ec0705b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a36-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2a36-0.8.13-javadoc.jar",
          "size": 87694,
          "sha512": "f8e37ccdfd8ce6e7dbcd2394520eb08d4a73699f471ce1f4dedb435c66fd531c378fa10401cbb884941c00fcb2349de9449cb1732e7bb3d8c41f67899eb2e33f",
          "sha256": "87dab6699a05ab9f5244b86394e32150dc7813b0c762388257f968eb945a168f",
          "sha1": "a8ff092044701da2c5286b5ce2ead319fffd2331",
          "md5": "b6767300d91cf53a11224011a24b566b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a36-0.8.13-sources.jar",
          "url": "ble-characteristic-u2a36-0.8.13-sources.jar",
          "size": 2903,
          "sha512": "3da8a8c979540f74298c92cb3038097c8fafc60f7ce24afb18f968fd62a7bf7acc9aadf1a89838ea20609f45ab6905d71fa0d98ff457977588d54d7464ebcfeb",
          "sha256": "61946a8c7f157d49dc79e7837a53804600c9f3e0c5e1aa838ceb76cc2275554b",
          "sha1": "3cc3f55cb9dc7b6064e8833654be7d70564a8c65",
          "md5": "e484e7ef807ac0aefe4c8c5c0f7d015e"
        }
      ]
    }
  ]
}
