{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a78-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a78",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-android-0.8.6.aar",
          "url": "ble-characteristic-u2a78-android-0.8.6.aar",
          "size": 3064,
          "sha512": "ced0513f6523e289f9d2ff67016738d726a193ce8c6f37c2fefdfc119148ef76b54741e29cadbe350e8ab1516774c0f36e7c933821a48cc0839d6a0ab83874f7",
          "sha256": "bd8aaf30dff6388dab30125defa34c616e388b4c5f22f5721362df9a87fc1f2e",
          "sha1": "24c0294878195c7aa35ff632634d2c1b4d91909e",
          "md5": "ee0907de1d9c0ca1c878bf5965f5e110"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a78",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a78-android-0.8.6.aar",
          "url": "ble-characteristic-u2a78-android-0.8.6.aar",
          "size": 3064,
          "sha512": "ced0513f6523e289f9d2ff67016738d726a193ce8c6f37c2fefdfc119148ef76b54741e29cadbe350e8ab1516774c0f36e7c933821a48cc0839d6a0ab83874f7",
          "sha256": "bd8aaf30dff6388dab30125defa34c616e388b4c5f22f5721362df9a87fc1f2e",
          "sha1": "24c0294878195c7aa35ff632634d2c1b4d91909e",
          "md5": "ee0907de1d9c0ca1c878bf5965f5e110"
        }
      ]
    }
  ]
}
