{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2abb-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abb",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abb-android-0.2.3.aar",
          "url": "ble-characteristic-u2abb-android-0.2.3.aar",
          "size": 3092,
          "sha512": "3059e196c75c1ae0daa277dda8f41a2590267c3ba3340ecf405cffe271df3e3fa5a8ec7afbc2243c8248e8ee9cf196ea049f5957e71b38b56be3c266c544b044",
          "sha256": "bc6db15316c1cd50f41874d50a96beac9b70e7db143fca46631789de560d1a0c",
          "sha1": "f5bb7edeb160a1ab9374b90b8a6271a1d1eeeee5",
          "md5": "82cc37d8302d2169f9729a833976e923"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2abb",
          "version": {
            "requires": "0.2.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2abb-android-0.2.3.aar",
          "url": "ble-characteristic-u2abb-android-0.2.3.aar",
          "size": 3092,
          "sha512": "3059e196c75c1ae0daa277dda8f41a2590267c3ba3340ecf405cffe271df3e3fa5a8ec7afbc2243c8248e8ee9cf196ea049f5957e71b38b56be3c266c544b044",
          "sha256": "bc6db15316c1cd50f41874d50a96beac9b70e7db143fca46631789de560d1a0c",
          "sha1": "f5bb7edeb160a1ab9374b90b8a6271a1d1eeeee5",
          "md5": "82cc37d8302d2169f9729a833976e923"
        }
      ]
    }
  ]
}
