{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a17-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.8.9.aar",
          "url": "ble-characteristic-u2a17-android-0.8.9.aar",
          "size": 3209,
          "sha512": "07034f78b2b46585a6c039d7c72ed08bedfed2e84ba4cc5ccf584950900e29a0bd167f1d75382250a36e7c59f25cffeb345ab42e6efb263cbc561243290825b2",
          "sha256": "d159daf3bd4023886bdba86feedc1de03fe038727e067bf5c928e9564382e601",
          "sha1": "b215570b333468c200b5b6484fa3e931efc60704",
          "md5": "5bfddc8bbdd150f6e6258f9e2962cf94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a17",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.8.9.aar",
          "url": "ble-characteristic-u2a17-android-0.8.9.aar",
          "size": 3209,
          "sha512": "07034f78b2b46585a6c039d7c72ed08bedfed2e84ba4cc5ccf584950900e29a0bd167f1d75382250a36e7c59f25cffeb345ab42e6efb263cbc561243290825b2",
          "sha256": "d159daf3bd4023886bdba86feedc1de03fe038727e067bf5c928e9564382e601",
          "sha1": "b215570b333468c200b5b6484fa3e931efc60704",
          "md5": "5bfddc8bbdd150f6e6258f9e2962cf94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2a17-android-0.8.9-sources.jar",
          "size": 2197,
          "sha512": "9274b025b6131995ea44570ee43b2ce7a671f38a63cc315790e84fdea483baa9810d4eeff8da25f929c7f00370a3a887fc2f4acbc820c1eadc736c87299e8533",
          "sha256": "706ed678aaaafa8a974795a97b3c2f1cfda198729cb46adb16e5810aef20c9b3",
          "sha1": "7d2cb907eecc36270ffee70a552f6bf989c3c966",
          "md5": "1d8df8f0812eeabc65df42d89f707f6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a17-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2a17-android-0.8.9-javadoc.jar",
          "size": 272683,
          "sha512": "6d8a1d5b1235d868a69288233f185869b23a4c878a0dfbeaa69d662c6c0005f326483fa33305a0e8e8728590f92940ea7b260c090e2d78be1061645237890df1",
          "sha256": "13a998f5fb93620d4697041388e4e511cc8cb56999a0daa6109d064f140bf54e",
          "sha1": "56aef846b6c8c5428a4fbe759599167d103932c0",
          "md5": "a7b3927239b065f1ac7360f84450964d"
        }
      ]
    }
  ]
}
