{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a0a",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0a-0.8.7.jar",
          "url": "ble-characteristic-u2a0a-0.8.7.jar",
          "size": 2156,
          "sha512": "4ab814ec505363878d16224e3b9e4944aed06aade962a44c125788faa236e9bc8f427172942bd520f42267c0dd4ee36b086d5f1e314f693ffb5589b681e39352",
          "sha256": "43d37a1d9730b5961beb7a722be6b184aedb936566c7a2ff9f57ef97834dfd14",
          "sha1": "5d97642606c9c479b1c80c171e5f50b7a12f0013",
          "md5": "f799db242af1312795a72d40c05073e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a0a-0.8.7.jar",
          "url": "ble-characteristic-u2a0a-0.8.7.jar",
          "size": 2156,
          "sha512": "4ab814ec505363878d16224e3b9e4944aed06aade962a44c125788faa236e9bc8f427172942bd520f42267c0dd4ee36b086d5f1e314f693ffb5589b681e39352",
          "sha256": "43d37a1d9730b5961beb7a722be6b184aedb936566c7a2ff9f57ef97834dfd14",
          "sha1": "5d97642606c9c479b1c80c171e5f50b7a12f0013",
          "md5": "f799db242af1312795a72d40c05073e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a0a-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a0a-0.8.7-javadoc.jar",
          "size": 107841,
          "sha512": "4cce86a071dc9028846e7ef1661382c2e7b1a3ceb68b97d8483a53125476f002355beeb44b11461af59ba0006ec5e92f15daa6072d6cc5dbf2f66ab4f926333b",
          "sha256": "91bc11ddf26fa57f0674307f33197fa26489387dd8f577cbeee59c90390fddb3",
          "sha1": "fb5bf3b521838f559dc28e6491cb1c268ed37d97",
          "md5": "f46438701f8b6153fa4a0b10a1d06053"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a0a-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a0a-0.8.7-sources.jar",
          "size": 1954,
          "sha512": "67cb64ce1e74fdfaf3770254754cb70c67b0f68532869bf90e1cf63c36680a8b88e2714dfeb2927b5d2f7b63cd01ec3517ca7ffac52435e88627afdd6821220b",
          "sha256": "9cb46822cd75dead81a70f8a1bb1037cd2eee02069094b6fd6539dbdcfda8e26",
          "sha1": "c1c8f402e051a535b192c4a26863650ac8d63dbe",
          "md5": "b820e1b6266425e5fab903397fec0e4c"
        }
      ]
    }
  ]
}
