{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a3f-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a3f",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a3f-android-0.8.6.aar",
          "url": "ble-characteristic-u2a3f-android-0.8.6.aar",
          "size": 3074,
          "sha512": "1fa8428a87cc0f2971b0f40d330f1ce26e1a7364f8b324fe09b37a62113ed3a8377855cb129c19ac2f0cc7db5316e2c11a33a02bb96f39be07d6d591dfcf49a1",
          "sha256": "8d72703594b1edc9915f623f21cd4827ac3d3901c78b69b0598cc0a7b7b77ef2",
          "sha1": "9bf7db553ff28d4c88f1480c42397907398dd1fd",
          "md5": "1f293f394a44204f0f3c12a3ff352133"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a3f",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a3f-android-0.8.6.aar",
          "url": "ble-characteristic-u2a3f-android-0.8.6.aar",
          "size": 3074,
          "sha512": "1fa8428a87cc0f2971b0f40d330f1ce26e1a7364f8b324fe09b37a62113ed3a8377855cb129c19ac2f0cc7db5316e2c11a33a02bb96f39be07d6d591dfcf49a1",
          "sha256": "8d72703594b1edc9915f623f21cd4827ac3d3901c78b69b0598cc0a7b7b77ef2",
          "sha1": "9bf7db553ff28d4c88f1480c42397907398dd1fd",
          "md5": "1f293f394a44204f0f3c12a3ff352133"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a3f-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a3f-android-0.8.6-sources.jar",
          "size": 2155,
          "sha512": "547c3768157cec1593ddff9c418c6712ccf6a2cd0965ef4d2a849df48fd11970d9ff9dc0bc64d5c995cfac49e628eb4019fbb4bb9ca890b719a6e494f8c8c04d",
          "sha256": "5c4bf8862ea03237fd7eecf3e263f6da8bff220673f26ceaa0ee5e095e1b7f43",
          "sha1": "f05239bd2b5ffa1269eb59f779cc443c7fbc496d",
          "md5": "77735ee72df5591ba4d95a345e4e3df3"
        }
      ]
    }
  ]
}
