{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a83-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kupq6qdcq5dovle6dw5m7myoyy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a83",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a83-android-0.2.3.aar",
          "url": "ble-characteristic-u2a83-android-0.2.3.aar",
          "size": 3106,
          "sha512": "ace80541987eab77975e8f7bce226539cbf390613037d6baeca3aaedaebe79005553b599eac3ab01f915a1212f60d3af2d92b334654ee72e1cb09333d5386149",
          "sha256": "467efdbef69896ead805d2f0fe2ee50f7da512140444e58f94d725f5e183ce5c",
          "sha1": "9c4edbc6663687613e5abc4d761d40939b54d134",
          "md5": "dea182112baf0b16a5c1a0318ff7ba7b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a83",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a83-android-0.2.3.aar",
          "url": "ble-characteristic-u2a83-android-0.2.3.aar",
          "size": 3106,
          "sha512": "ace80541987eab77975e8f7bce226539cbf390613037d6baeca3aaedaebe79005553b599eac3ab01f915a1212f60d3af2d92b334654ee72e1cb09333d5386149",
          "sha256": "467efdbef69896ead805d2f0fe2ee50f7da512140444e58f94d725f5e183ce5c",
          "sha1": "9c4edbc6663687613e5abc4d761d40939b54d134",
          "md5": "dea182112baf0b16a5c1a0318ff7ba7b"
        }
      ]
    }
  ]
}
