{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b94",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12.jar",
          "url": "ble-characteristic-u2b94-0.8.12.jar",
          "size": 1477,
          "sha512": "116001bfaf54d4397193a64448c08921d6ce959abeb77bf2691a38e1114375a4dad40979e8f80196ba145e7a2f37708bfaf76dc607c504c21228a12e31ff7657",
          "sha256": "3c6418a5f4a6c59accfce44002f964f6983ea1cca48ed6da2e6d0a748c46057e",
          "sha1": "390d1fb79994ab383e5ae041e669a28b6fcc94e4",
          "md5": "610c9de6be0a8c3fd86ba1a953cd8524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12.jar",
          "url": "ble-characteristic-u2b94-0.8.12.jar",
          "size": 1477,
          "sha512": "116001bfaf54d4397193a64448c08921d6ce959abeb77bf2691a38e1114375a4dad40979e8f80196ba145e7a2f37708bfaf76dc607c504c21228a12e31ff7657",
          "sha256": "3c6418a5f4a6c59accfce44002f964f6983ea1cca48ed6da2e6d0a748c46057e",
          "sha1": "390d1fb79994ab383e5ae041e669a28b6fcc94e4",
          "md5": "610c9de6be0a8c3fd86ba1a953cd8524"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b94-0.8.12-javadoc.jar",
          "size": 107259,
          "sha512": "d736a5f432d8b76b45b92bd942f7729c49cd16fa504dd770d4c4dc339d10966959f20004c1778fecad051581b60056d050bd22d74e432239446788c32e44a1b1",
          "sha256": "f0576cc58ea6cc2e6a5721fe7edbe26c2e4edadd179651fdfd72a3d6d055616f",
          "sha1": "7a603595c5ccc1acb0e350429ac8d5f3a8c65dcd",
          "md5": "0f3a06b38e0aee15a1f70efaec4d172c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b94-0.8.12-sources.jar",
          "size": 1475,
          "sha512": "36e3e2356ddcfcb8c98fb81da55052f46b6c6a63129630023776cc74afefe2ea21273b22b59ae9a11bd4fe9727ca02f7ea41d9ef3dd8a4f6c6910e308b717249",
          "sha256": "fd9a5adc744b530e0a24336669bfb0bb5c48dd064da1dddc894c9c3343d1fda7",
          "sha1": "53e407da057b066d7c0e2d227c9033fbc93e6a89",
          "md5": "56254bb462fe6cf82d07a4b2ba4dceb8"
        }
      ]
    }
  ]
}
