{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b94",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12.jar",
          "url": "ble-characteristic-u2b94-0.8.12.jar",
          "size": 1477,
          "sha512": "116001bfaf54d4397193a64448c08921d6ce959abeb77bf2691a38e1114375a4dad40979e8f80196ba145e7a2f37708bfaf76dc607c504c21228a12e31ff7657",
          "sha256": "3c6418a5f4a6c59accfce44002f964f6983ea1cca48ed6da2e6d0a748c46057e",
          "sha1": "390d1fb79994ab383e5ae041e669a28b6fcc94e4",
          "md5": "610c9de6be0a8c3fd86ba1a953cd8524"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12.jar",
          "url": "ble-characteristic-u2b94-0.8.12.jar",
          "size": 1477,
          "sha512": "116001bfaf54d4397193a64448c08921d6ce959abeb77bf2691a38e1114375a4dad40979e8f80196ba145e7a2f37708bfaf76dc607c504c21228a12e31ff7657",
          "sha256": "3c6418a5f4a6c59accfce44002f964f6983ea1cca48ed6da2e6d0a748c46057e",
          "sha1": "390d1fb79994ab383e5ae041e669a28b6fcc94e4",
          "md5": "610c9de6be0a8c3fd86ba1a953cd8524"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b94-0.8.12-javadoc.jar",
          "size": 86086,
          "sha512": "dc61ae0b1a0f65974f7ce50780db909b05a0210d9cb62341bb1361ca4edc60f1ec3cf4048e6f80b6556abb2ec083811f28acd6b7f3b6808c9f3062b1abfab3e6",
          "sha256": "454f4c77bf0422682b2a3f38c2f909362d5b8260dac7bc7641a1d7b0db45d096",
          "sha1": "f35c5fc12b4df365458463ce7dc9087daef0dad9",
          "md5": "0ba07a2c6ed2a204ede60a275c49fee5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b94-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b94-0.8.12-sources.jar",
          "size": 1475,
          "sha512": "36e3e2356ddcfcb8c98fb81da55052f46b6c6a63129630023776cc74afefe2ea21273b22b59ae9a11bd4fe9727ca02f7ea41d9ef3dd8a4f6c6910e308b717249",
          "sha256": "fd9a5adc744b530e0a24336669bfb0bb5c48dd064da1dddc894c9c3343d1fda7",
          "sha1": "53e407da057b066d7c0e2d227c9033fbc93e6a89",
          "md5": "56254bb462fe6cf82d07a4b2ba4dceb8"
        }
      ]
    }
  ]
}
