{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2901-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2901-android-0.1.0.aar",
          "url": "ble-descriptor-u2901-android-0.1.0.aar",
          "size": 2886,
          "sha512": "f7dd2dcecdeebee2b6e1e9f9568b0de45dfa3aa0fc85725d27b776a70cbb827ac8ed0d6267e82fd7b4be7be0598c235b9e4128494ef8344c7cb6f4d2de3359b4",
          "sha256": "1b87142a16e34b10db7f208abc49c79aedc74fc302b2b5460c11138ec170b7fb",
          "sha1": "5ef0cbb2c0b502c046b5e8105d8246e6e3d7d676",
          "md5": "45efc1fe2e0fab14f119aabc5405730c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2901",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2901-android-0.1.0.aar",
          "url": "ble-descriptor-u2901-android-0.1.0.aar",
          "size": 2886,
          "sha512": "f7dd2dcecdeebee2b6e1e9f9568b0de45dfa3aa0fc85725d27b776a70cbb827ac8ed0d6267e82fd7b4be7be0598c235b9e4128494ef8344c7cb6f4d2de3359b4",
          "sha256": "1b87142a16e34b10db7f208abc49c79aedc74fc302b2b5460c11138ec170b7fb",
          "sha1": "5ef0cbb2c0b502c046b5e8105d8246e6e3d7d676",
          "md5": "45efc1fe2e0fab14f119aabc5405730c"
        }
      ]
    }
  ]
}
