{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a25-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zckqgxv52jertg33sctsfjorzm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.2.aar",
          "url": "ble-characteristic-u2a25-android-0.2.2.aar",
          "size": 2930,
          "sha512": "c266217271dddca5fa789c51378996df68c2ad613450af5a6466078968147c40203805b01b014ab2075838b2e15428905d226f0749e9a36a954357433284c4ec",
          "sha256": "36ca13848c54c491bb75bafc0f54397bf36c5374a8492961dafc30c39d995a99",
          "sha1": "24b805403c27886b65de142ccaa4f5df46d6d389",
          "md5": "b1d8e5da72eab7ed42e120c39991f604"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a25",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a25-android-0.2.2.aar",
          "url": "ble-characteristic-u2a25-android-0.2.2.aar",
          "size": 2930,
          "sha512": "c266217271dddca5fa789c51378996df68c2ad613450af5a6466078968147c40203805b01b014ab2075838b2e15428905d226f0749e9a36a954357433284c4ec",
          "sha256": "36ca13848c54c491bb75bafc0f54397bf36c5374a8492961dafc30c39d995a99",
          "sha1": "24b805403c27886b65de142ccaa4f5df46d6d389",
          "md5": "b1d8e5da72eab7ed42e120c39991f604"
        }
      ]
    }
  ]
}
