{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad8",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "imjjj3zqlvehtmyigxnbhig5hq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.2.1.jar",
          "url": "ble-characteristic-u2ad8-0.2.1.jar",
          "size": 1922,
          "sha512": "d97b363b0c20b6ab7d1aa4bce0efc8c6c3bd383bff4e58502ea3484da822ec1bfde1851766aabedeb35186a42024ed275352bd9296764c78e79611e1c948dec1",
          "sha256": "37fae3f0d78a58ac6fb98b24e4e3fe6961fa221591c9d5cc495feb78b81c32ac",
          "sha1": "2c60f498b912f760e20ea0cf3a707344520a144d",
          "md5": "a189cf14a671be4b06ab9f045c6e3308"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad8-0.2.1.jar",
          "url": "ble-characteristic-u2ad8-0.2.1.jar",
          "size": 1922,
          "sha512": "d97b363b0c20b6ab7d1aa4bce0efc8c6c3bd383bff4e58502ea3484da822ec1bfde1851766aabedeb35186a42024ed275352bd9296764c78e79611e1c948dec1",
          "sha256": "37fae3f0d78a58ac6fb98b24e4e3fe6961fa221591c9d5cc495feb78b81c32ac",
          "sha1": "2c60f498b912f760e20ea0cf3a707344520a144d",
          "md5": "a189cf14a671be4b06ab9f045c6e3308"
        }
      ]
    }
  ]
}
