{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae9-android",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae9",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae9-android-0.8.1.aar",
          "url": "ble-characteristic-u2ae9-android-0.8.1.aar",
          "size": 3115,
          "sha512": "e10f4134757796ff423c5575c639bb3c1b8dfbe68cdb726104e8ce682cb3d48303f6c4dba46fdc7332f68d0532d041faeb9b821c135c8d5cbc95ab929ab712eb",
          "sha256": "8ba9506d0696ab32a9025dc3fca816d5c9206cef6c72de592369e5f26ec2334a",
          "sha1": "db835e7b12af586deb146f347b150dc0e5a3cae2",
          "md5": "8b116f2b8a44ad15e7601fc5b82f9703"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ae9",
          "version": {
            "requires": "0.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae9-android-0.8.1.aar",
          "url": "ble-characteristic-u2ae9-android-0.8.1.aar",
          "size": 3115,
          "sha512": "e10f4134757796ff423c5575c639bb3c1b8dfbe68cdb726104e8ce682cb3d48303f6c4dba46fdc7332f68d0532d041faeb9b821c135c8d5cbc95ab929ab712eb",
          "sha256": "8ba9506d0696ab32a9025dc3fca816d5c9206cef6c72de592369e5f26ec2334a",
          "sha1": "db835e7b12af586deb146f347b150dc0e5a3cae2",
          "md5": "8b116f2b8a44ad15e7601fc5b82f9703"
        }
      ]
    }
  ]
}
