{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b18",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b18-0.4.3.jar",
          "url": "ble-characteristic-u2b18-0.4.3.jar",
          "size": 1753,
          "sha512": "d6702fa97e12fae7a08c44af8234bc1e215acacf49bc74ac211341352d10bf9326375e658e723cd2a19e8e8c2634dc7bcca74038221818ef1adfa8b9cc8e4f27",
          "sha256": "93a06f63e112c26bf6dde75aea2b2cd35b4d9eb62d2161f1cce6f1d986a992e3",
          "sha1": "90b99088f9e5131f0c6724059a8f69704e72b048",
          "md5": "983680d89f097b19aea069d283ce6059"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b18-0.4.3.jar",
          "url": "ble-characteristic-u2b18-0.4.3.jar",
          "size": 1753,
          "sha512": "d6702fa97e12fae7a08c44af8234bc1e215acacf49bc74ac211341352d10bf9326375e658e723cd2a19e8e8c2634dc7bcca74038221818ef1adfa8b9cc8e4f27",
          "sha256": "93a06f63e112c26bf6dde75aea2b2cd35b4d9eb62d2161f1cce6f1d986a992e3",
          "sha1": "90b99088f9e5131f0c6724059a8f69704e72b048",
          "md5": "983680d89f097b19aea069d283ce6059"
        }
      ]
    }
  ]
}
