{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a37-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "lo7jzvr3sfdrrlxv6obizupava"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a37",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a37-android-0.2.1.aar",
          "url": "ble-characteristic-u2a37-android-0.2.1.aar",
          "size": 3018,
          "sha512": "123ffff73fa35c4ddb6c0311c9c8b7fbec897e2d59786fa06fe2bf6e728436dff311e49972c883b399678c25eb1ddfc8d07e8fbc59e86ccfe241923238033e49",
          "sha256": "f414f6642cfe9db8435312174c13cd264854ea5dc00eea8b4326108be47a264f",
          "sha1": "ba03075832a8e3c3f246c41c822812c5732f0897",
          "md5": "ca17fb80455f86fddd7c1c0f56363fa0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a37",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a37-android-0.2.1.aar",
          "url": "ble-characteristic-u2a37-android-0.2.1.aar",
          "size": 3018,
          "sha512": "123ffff73fa35c4ddb6c0311c9c8b7fbec897e2d59786fa06fe2bf6e728436dff311e49972c883b399678c25eb1ddfc8d07e8fbc59e86ccfe241923238033e49",
          "sha256": "f414f6642cfe9db8435312174c13cd264854ea5dc00eea8b4326108be47a264f",
          "sha1": "ba03075832a8e3c3f246c41c822812c5732f0897",
          "md5": "ca17fb80455f86fddd7c1c0f56363fa0"
        }
      ]
    }
  ]
}
