{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab3-android",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab3",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab3-android-0.8.13.aar",
          "url": "ble-characteristic-u2ab3-android-0.8.13.aar",
          "size": 3111,
          "sha512": "8f84adcc042287fe3cb85a860fff88c67ce9577226b5a1d6a86df677351c266d19410a7515afd5d1330e62d887526f0b893627bc0475f1a36b2bcedda2399db8",
          "sha256": "95d332df734c56c622a3fd1ec4e37c5fd7a7ed9f8e4c160d1117652a371985ed",
          "sha1": "a59e9bb09a97995c94e960b7b51dc47d555931d4",
          "md5": "89a597983a13109994f590d7af8f1cce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab3",
          "version": {
            "requires": "0.8.13"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab3-android-0.8.13.aar",
          "url": "ble-characteristic-u2ab3-android-0.8.13.aar",
          "size": 3111,
          "sha512": "8f84adcc042287fe3cb85a860fff88c67ce9577226b5a1d6a86df677351c266d19410a7515afd5d1330e62d887526f0b893627bc0475f1a36b2bcedda2399db8",
          "sha256": "95d332df734c56c622a3fd1ec4e37c5fd7a7ed9f8e4c160d1117652a371985ed",
          "sha1": "a59e9bb09a97995c94e960b7b51dc47d555931d4",
          "md5": "89a597983a13109994f590d7af8f1cce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab3-android-0.8.13-sources.jar",
          "url": "ble-characteristic-u2ab3-android-0.8.13-sources.jar",
          "size": 2167,
          "sha512": "913c9a974a7d0a09d59cc33b0699650d1a61556391dd364989b11020c4667e2a02e35a8eb60345d98b197be0827d5dd407c55a2c4683ce1aef8dd158e5d1aa0a",
          "sha256": "27d048fd9a092b495bd9ceb63b1043039014dda6d279e97d7736bed71c8c6109",
          "sha1": "d3359d74cb36d3f66c4c30f2d4bacb343d9a4ffa",
          "md5": "09eafa419268d3d06476ae155c881f40"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ab3-android-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2ab3-android-0.8.13-javadoc.jar",
          "size": 271034,
          "sha512": "2f3c97c80d604ad69ea5cb29a0a9ac59096fa8cdb46ddaf0062090d4f0653bd8cc17265669c92dc45eee4bf1ddd6667ce240879afc8344a5418f421907772899",
          "sha256": "1ffb68a7e174caae0c700817eed6b20c593736fbda90062723f1fefb145f8820",
          "sha1": "32ec658d54e6a28dd40198ee9dac7b0203936518",
          "md5": "d91c5fea0ba50c1f7a32df76797ddc2c"
        }
      ]
    }
  ]
}
