{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-ftms-android",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "gpzmini6r5dspflf7xc6fjjaba"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acc-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ace-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acf-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad0-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad4-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad5-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad7-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ada-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ftms-android-0.4.2.aar",
          "url": "ble-service-ftms-android-0.4.2.aar",
          "size": 1188,
          "sha512": "f528ffc81837b07de1f24dcb8c11a9cfc621793e2af7a60b937951693f417e2bfaed7e148400f53fe5c152b9b5e644700a2939dfd27ebf0e087c6e0309ba5e2d",
          "sha256": "29f963a2eff6aff30848ebaffd4989283c18b6ab25b87bca73bd0b0e141b4e32",
          "sha1": "93953543c7f88e10d29f245a5b23b35d2c13a7c5",
          "md5": "d0ed5e540f2eabce069adbda97152b3d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2902-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acc-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acd-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ace-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acf-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad0-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad2-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad3-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad4-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad5-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad6-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad7-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad8-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad9-android",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ada-android",
          "version": {
            "requires": "0.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-ftms-android-0.4.2.aar",
          "url": "ble-service-ftms-android-0.4.2.aar",
          "size": 1188,
          "sha512": "f528ffc81837b07de1f24dcb8c11a9cfc621793e2af7a60b937951693f417e2bfaed7e148400f53fe5c152b9b5e644700a2939dfd27ebf0e087c6e0309ba5e2d",
          "sha256": "29f963a2eff6aff30848ebaffd4989283c18b6ab25b87bca73bd0b0e141b4e32",
          "sha1": "93953543c7f88e10d29f245a5b23b35d2c13a7c5",
          "md5": "d0ed5e540f2eabce069adbda97152b3d"
        }
      ]
    }
  ]
}
