{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a97-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a97",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a97-android-0.2.2.aar",
          "url": "ble-characteristic-u2a97-android-0.2.2.aar",
          "size": 2922,
          "sha512": "8069e04985664c029f36fb425702a0c1d4dc59fc32cfbc626ef9b3a264557355f921f8631a59be9c600b7eed69d43fcf09c16da5f482c9d32b2f52913b95188c",
          "sha256": "9c23194c90bd3351e149203f22ea8e7265125f934cee01c85c37cc1b03c61d48",
          "sha1": "fa101b721f31458cfb23e2814dc441d9eee06ac6",
          "md5": "fd593b8b991a10747cdb463ccce7dcda"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a97",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a97-android-0.2.2.aar",
          "url": "ble-characteristic-u2a97-android-0.2.2.aar",
          "size": 2922,
          "sha512": "8069e04985664c029f36fb425702a0c1d4dc59fc32cfbc626ef9b3a264557355f921f8631a59be9c600b7eed69d43fcf09c16da5f482c9d32b2f52913b95188c",
          "sha256": "9c23194c90bd3351e149203f22ea8e7265125f934cee01c85c37cc1b03c61d48",
          "sha1": "fa101b721f31458cfb23e2814dc441d9eee06ac6",
          "md5": "fd593b8b991a10747cdb463ccce7dcda"
        }
      ]
    }
  ]
}
