{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab6-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ne3pcejtrrhfvmmkle32bx6bti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab6",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab6-android-0.2.5.aar",
          "url": "ble-characteristic-u2ab6-android-0.2.5.aar",
          "size": 3046,
          "sha512": "2130cc42ffc78394de5bfbd64a2be4a3019eaba372e22c0689a90f6642be2aadc2071b8a329ca0b5cdfaf602c7141bba9d618929608b1660bd566a10cfbbdc38",
          "sha256": "94ae6e6dac5b0d5ab75d8bdd8c612290bb5b5ed7335c35504e3032ee4ae8e209",
          "sha1": "a21a53fea4716c0eeef856998ac2a6122faf5b05",
          "md5": "a7331978a8c9a13cabb0cc2581a8a18e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ab6",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab6-android-0.2.5.aar",
          "url": "ble-characteristic-u2ab6-android-0.2.5.aar",
          "size": 3046,
          "sha512": "2130cc42ffc78394de5bfbd64a2be4a3019eaba372e22c0689a90f6642be2aadc2071b8a329ca0b5cdfaf602c7141bba9d618929608b1660bd566a10cfbbdc38",
          "sha256": "94ae6e6dac5b0d5ab75d8bdd8c612290bb5b5ed7335c35504e3032ee4ae8e209",
          "sha1": "a21a53fea4716c0eeef856998ac2a6122faf5b05",
          "md5": "a7331978a8c9a13cabb0cc2581a8a18e"
        }
      ]
    }
  ]
}
