{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2af8",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af8-0.8.5.jar",
          "url": "ble-characteristic-u2af8-0.8.5.jar",
          "size": 1585,
          "sha512": "04a4014c325deb292ec5e1a251816dac5a47baae0b5363e1534e2ca733df51895f03a26244159dafeea4770914ce57b1491da3df142fd62622fcbe1430b5b962",
          "sha256": "887549f81c777f8e4ce5fa7751d1e4c368a3c3535842d11f7b7eacc80667ca37",
          "sha1": "375efbdd0126aedb12a7e47d34a134cff39527f1",
          "md5": "30cc7f84476d67179a57168585553973"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2af8-0.8.5.jar",
          "url": "ble-characteristic-u2af8-0.8.5.jar",
          "size": 1585,
          "sha512": "04a4014c325deb292ec5e1a251816dac5a47baae0b5363e1534e2ca733df51895f03a26244159dafeea4770914ce57b1491da3df142fd62622fcbe1430b5b962",
          "sha256": "887549f81c777f8e4ce5fa7751d1e4c368a3c3535842d11f7b7eacc80667ca37",
          "sha1": "375efbdd0126aedb12a7e47d34a134cff39527f1",
          "md5": "30cc7f84476d67179a57168585553973"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af8-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2af8-0.8.5-javadoc.jar",
          "size": 107383,
          "sha512": "d52f79aa0cd62e07dedbfcd262ec618d40d9a5487bdc00287c2d7292b41a4b96511459d8194670d78e42b24d660cad742a10e5043174895ed3859bde856b067a",
          "sha256": "8b384554a39e883ced59c165a37b463d9164190e03c9175329defe092719c287",
          "sha1": "5e040092520886a598ca755d663e7937c569d479",
          "md5": "81a059e4b799daa29e68e25fa03f04b0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2af8-0.8.5-sources.jar",
          "url": "ble-characteristic-u2af8-0.8.5-sources.jar",
          "size": 1497,
          "sha512": "5fa5856dfb8b6aa38ea678e421218e858031ffed51a9bb5b1f69bfdb9249c2d187560068dde1538af49a80ff36998099da9936f72e5de8850d9bd205c2338d64",
          "sha256": "be3fbfdf053d90cad480ed91db0e7061224d646f573a3a70f620ca22635a27fc",
          "sha1": "e08ad1eeb6b17edec8cdf04d48318fa6cc71ddca",
          "md5": "e4b35a2d4bc4175c05e6e0759a5963b9"
        }
      ]
    }
  ]
}
