{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a82-android",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a82",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a82-android-0.8.8.aar",
          "url": "ble-characteristic-u2a82-android-0.8.8.aar",
          "size": 3252,
          "sha512": "cf60b172ebb82836cb686b9df74648000d2ddca3ccd00019192f452f5435ce4b1eacddc7d93bc58cae844dad57a4feb8d2c42ce778fcb01043aee16a2d38b536",
          "sha256": "52134f9934a27855fafa415e85190c93f7cd8036e363f5c40756f5b83e7fff46",
          "sha1": "76a6bf56ca1d12f732249ac8ba8b4116a57a0598",
          "md5": "739a63a5e05d6600bc19bd736cedd68b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a82",
          "version": {
            "requires": "0.8.8"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a82-android-0.8.8.aar",
          "url": "ble-characteristic-u2a82-android-0.8.8.aar",
          "size": 3252,
          "sha512": "cf60b172ebb82836cb686b9df74648000d2ddca3ccd00019192f452f5435ce4b1eacddc7d93bc58cae844dad57a4feb8d2c42ce778fcb01043aee16a2d38b536",
          "sha256": "52134f9934a27855fafa415e85190c93f7cd8036e363f5c40756f5b83e7fff46",
          "sha1": "76a6bf56ca1d12f732249ac8ba8b4116a57a0598",
          "md5": "739a63a5e05d6600bc19bd736cedd68b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a82-android-0.8.8-sources.jar",
          "url": "ble-characteristic-u2a82-android-0.8.8-sources.jar",
          "size": 2243,
          "sha512": "d94b1f2314cf85f9d19326792b0f5f23a44fd850914d31ce31e955b287bbad7245dba8162faec6bb5d489d195367fe9172388f41201986d7751314184f166bea",
          "sha256": "c3e12d0713737d8c6273f43316d88e3c94c5cb50dde01b7b3a26eb8522e56426",
          "sha1": "dc467079b267a89d14aa888ea6940b1efecc6b83",
          "md5": "8cd8e47326b5e04d69d40f9a3dd61fd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a82-android-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2a82-android-0.8.8-javadoc.jar",
          "size": 270780,
          "sha512": "4a4fe7866618daa0a59cc94bcb8046b07aea65eeba0d66dd585d6cc21e374044db6eb171985c11b4d93ba624e524b78ef4bc1145b6effd5b05724332fe10e90e",
          "sha256": "73b40f92fb5fc0451e5a003c6af90abcd3cf789be7d1ad6d0a6befd6a6f98ff6",
          "sha1": "21d4b81a985455c00b1fe2df02ab83fd02b999e9",
          "md5": "923c045d61ef25c885ce0a96e5fa28ee"
        }
      ]
    }
  ]
}
