{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b2a",
    "version": "0.8.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.13.jar",
          "url": "ble-characteristic-u2b2a-0.8.13.jar",
          "size": 1749,
          "sha512": "6a3f169726e36aacb5e6d4c1c07ea23764036914d17ec822706abb7fc5e9d34d7f997b82de50bf7255bbe99f378091445f2f8181afcc334bcf24c3ee2e9a2f41",
          "sha256": "dbb242f44d1cca8f4514482485840aa17828505214a61ab948b512936128bd7f",
          "sha1": "402364729cf69ca6980fd3daac1de59c8c4f1bc5",
          "md5": "d367a5f079066538165bb95b12c46d8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.13"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.13.jar",
          "url": "ble-characteristic-u2b2a-0.8.13.jar",
          "size": 1749,
          "sha512": "6a3f169726e36aacb5e6d4c1c07ea23764036914d17ec822706abb7fc5e9d34d7f997b82de50bf7255bbe99f378091445f2f8181afcc334bcf24c3ee2e9a2f41",
          "sha256": "dbb242f44d1cca8f4514482485840aa17828505214a61ab948b512936128bd7f",
          "sha1": "402364729cf69ca6980fd3daac1de59c8c4f1bc5",
          "md5": "d367a5f079066538165bb95b12c46d8b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.13-javadoc.jar",
          "url": "ble-characteristic-u2b2a-0.8.13-javadoc.jar",
          "size": 86148,
          "sha512": "09babaa52719fc43a4e80a0bc1c3b6bab3fa060e96b67d60f5f3f5a672b521d59edcd16fa235878513b4bf351b8a22d2bc53f9546f31cc82595f409b2e4397e0",
          "sha256": "150c3f010a0cd09409f8dbdf1458438e0bb73dca0ff6d0971092bdf0a496caab",
          "sha1": "b53f4490fefa00bf393c08d39ab5086d4e56a133",
          "md5": "8dffa28a74443cc40e8c9b9d4339bdbb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b2a-0.8.13-sources.jar",
          "url": "ble-characteristic-u2b2a-0.8.13-sources.jar",
          "size": 1603,
          "sha512": "d26ee82f32e31382f2131d936577976b0972217ed3f9bedf89e6cbbe1ef8747fbf71d5aed876fe6df9c446f3bef2489ac26aa6d7cc8af2af744bcf445771557f",
          "sha256": "265e42fe2eed854424280b5b262b0e6059f33045e05d70d132dca6d9d74cc7eb",
          "sha1": "516a4b51d5342b2a9875a2a2b9afce89c1911efb",
          "md5": "1e454ef3728d090ff1b4ccee4c86f7dd"
        }
      ]
    }
  ]
}
