{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5d-android",
    "version": "0.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "65dk36codbhptk2x3a7et6bxjm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.4.3.aar",
          "url": "ble-characteristic-u2a5d-android-0.4.3.aar",
          "size": 3099,
          "sha512": "4fea15417d0a899605ad5350101aa60cc5c5d9ed505e8135f19b7893ecdf862eb32947e900a51f488ddc5f5dd85f614cef3a1a7729f00332a8c7d1f897e8519f",
          "sha256": "4a092e00a6eb531e75f3c86e18b956aae38a292f14f5066cfb27b1f5822e9367",
          "sha1": "76aeb28def7d3625c04d2585bba5e084362295d0",
          "md5": "43562b963d79effd4f73e8f93ab83c84"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5d",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5d-android-0.4.3.aar",
          "url": "ble-characteristic-u2a5d-android-0.4.3.aar",
          "size": 3099,
          "sha512": "4fea15417d0a899605ad5350101aa60cc5c5d9ed505e8135f19b7893ecdf862eb32947e900a51f488ddc5f5dd85f614cef3a1a7729f00332a8c7d1f897e8519f",
          "sha256": "4a092e00a6eb531e75f3c86e18b956aae38a292f14f5066cfb27b1f5822e9367",
          "sha1": "76aeb28def7d3625c04d2585bba5e084362295d0",
          "md5": "43562b963d79effd4f73e8f93ab83c84"
        }
      ]
    }
  ]
}
