{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a7f-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "mkrq4h7cm5efncarhazctggxni"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.2.2.aar",
          "url": "ble-characteristic-u2a7f-android-0.2.2.aar",
          "size": 2915,
          "sha512": "1060ba093824ef922da2ab3b2e0a2af2018e349776000c76eea1852965329e45082017386a36aa68f9032320678df9badfe5d0ad2ba9763bb00fc6b6d88afa85",
          "sha256": "a52b45f4a7525633e2c94962870176698ea301a149e241ce641cab9f68b6f0b7",
          "sha1": "86308503213a9e3f6e117d4f869e469b1a67fe19",
          "md5": "8ea7c201c740fd5dc8934ed43224301c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a7f",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a7f-android-0.2.2.aar",
          "url": "ble-characteristic-u2a7f-android-0.2.2.aar",
          "size": 2915,
          "sha512": "1060ba093824ef922da2ab3b2e0a2af2018e349776000c76eea1852965329e45082017386a36aa68f9032320678df9badfe5d0ad2ba9763bb00fc6b6d88afa85",
          "sha256": "a52b45f4a7525633e2c94962870176698ea301a149e241ce641cab9f68b6f0b7",
          "sha1": "86308503213a9e3f6e117d4f869e469b1a67fe19",
          "md5": "8ea7c201c740fd5dc8934ed43224301c"
        }
      ]
    }
  ]
}
