{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2aa1-android",
    "version": "0.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa1",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-android-0.8.9.aar",
          "url": "ble-characteristic-u2aa1-android-0.8.9.aar",
          "size": 3249,
          "sha512": "f870138f885a0cde2d778ab07bd05900613a5be296649218039d4a4dbf88bf5f5b380210e2860d367c63d071cd9a558f7113fe1f93ba76ea6fc871142252aafb",
          "sha256": "12aa7faa96927caab47d015298d9ea309221a49d06e69a8fe96af0c29dbea7a6",
          "sha1": "ac7374afc26ed40b65822762300a19bc31c140b6",
          "md5": "a46e91a8602315fedfa799d2e1fa5f81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2aa1",
          "version": {
            "requires": "0.8.9"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2aa1-android-0.8.9.aar",
          "url": "ble-characteristic-u2aa1-android-0.8.9.aar",
          "size": 3249,
          "sha512": "f870138f885a0cde2d778ab07bd05900613a5be296649218039d4a4dbf88bf5f5b380210e2860d367c63d071cd9a558f7113fe1f93ba76ea6fc871142252aafb",
          "sha256": "12aa7faa96927caab47d015298d9ea309221a49d06e69a8fe96af0c29dbea7a6",
          "sha1": "ac7374afc26ed40b65822762300a19bc31c140b6",
          "md5": "a46e91a8602315fedfa799d2e1fa5f81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa1-android-0.8.9-sources.jar",
          "url": "ble-characteristic-u2aa1-android-0.8.9-sources.jar",
          "size": 2245,
          "sha512": "796662dcbb896e84f2eb94cbddfd4e6971f927a66531dcd443dcedef47f6fc827605562d86a2f83f63144df762dd7468c52a374f327100dc2014b5f5e61daaf4",
          "sha256": "2b9866c9e6560fbc1e747407ae451501c6c92e04d41b1a42c74cea432b5a7e43",
          "sha1": "55d8930a045165cfad3a93076d2a8715e416e41b",
          "md5": "fd32e433d785000014a7f653301cd116"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2aa1-android-0.8.9-javadoc.jar",
          "url": "ble-characteristic-u2aa1-android-0.8.9-javadoc.jar",
          "size": 270846,
          "sha512": "146719c1f60a1621c330319b798d79ce2a6a2feb0be56ae6a70ce31797c63a98a4db101fb1aaf007118d34fd6f0df86e5273aacc54a0f4831520889017ee3093",
          "sha256": "30c21db9095ab1fbb25c69dd1973f15fd9209682f617b29759f903a7fe483ab4",
          "sha1": "741ee366fc25aa8595f349944a9534f418612fa3",
          "md5": "80a446f884f28009c3070d701268c96b"
        }
      ]
    }
  ]
}
