{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-hrp-android",
    "version": "0.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "m2s6xof35bbzxi2ribny6p3xti"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-hrp-android-0.1.2.aar",
          "url": "ble-profile-hrp-android-0.1.2.aar",
          "size": 1205,
          "sha512": "52e20bf7e539705dde17f01381d740aa638e73b7b328a132f13711f2a93da8fa75cf5a4543c05a938ff72b6f5fe59dc1d40f312d32de7ba28b775fe63456730a",
          "sha256": "970d0aaf779210bc33511fa7ecc663b487241044c1648052a0fde5a2d323ca3a",
          "sha1": "03acd6a84b1267a47c129499295a652f8d57ac1e",
          "md5": "1e7d0f3f4f9b80992680e2d42f97461e"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-hrp-android-0.1.2.aar",
          "url": "ble-profile-hrp-android-0.1.2.aar",
          "size": 1205,
          "sha512": "52e20bf7e539705dde17f01381d740aa638e73b7b328a132f13711f2a93da8fa75cf5a4543c05a938ff72b6f5fe59dc1d40f312d32de7ba28b775fe63456730a",
          "sha256": "970d0aaf779210bc33511fa7ecc663b487241044c1648052a0fde5a2d323ca3a",
          "sha1": "03acd6a84b1267a47c129499295a652f8d57ac1e",
          "md5": "1e7d0f3f4f9b80992680e2d42f97461e"
        }
      ]
    }
  ]
}
