{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2acf-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acf",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acf-android-0.2.3.aar",
          "url": "ble-characteristic-u2acf-android-0.2.3.aar",
          "size": 5226,
          "sha512": "07b2869461bf2e73e00e6399640d9d91f972109bacb7d02cab70ac5fd855cc2b8afab3d81c7ade6498299a264966fc03e5ceedc9939eb350ba9702b786e96de9",
          "sha256": "69f163a8a6e0a08f760490ef5b8067fab147d2c764189ca3599491de233c3516",
          "sha1": "8315d153fa4ca66b60391364e42fe04897fac6dc",
          "md5": "0d1b6047d57df6d85650c368a60f74c2"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2acf",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2acf-android-0.2.3.aar",
          "url": "ble-characteristic-u2acf-android-0.2.3.aar",
          "size": 5226,
          "sha512": "07b2869461bf2e73e00e6399640d9d91f972109bacb7d02cab70ac5fd855cc2b8afab3d81c7ade6498299a264966fc03e5ceedc9939eb350ba9702b786e96de9",
          "sha256": "69f163a8a6e0a08f760490ef5b8067fab147d2c764189ca3599491de233c3516",
          "sha1": "8315d153fa4ca66b60391364e42fe04897fac6dc",
          "md5": "0d1b6047d57df6d85650c368a60f74c2"
        }
      ]
    }
  ]
}
