{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a9e-android",
    "version": "0.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "z6dqbrqplrdxrnoy47ggumszqi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.5.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.5.aar",
          "size": 3204,
          "sha512": "e0ccd646453b12f0852ad09cef9ad0d9ca4aa5c837621e34e1ea2a42511a28d27e16a7cd752f4ebcf1903b2479f2890b8e490eec737ee7b37b48751edad11174",
          "sha256": "2aa06c3d101ea797a896b256e071e53c6dee2cf7e9f686b1e409b0ee690d3cc2",
          "sha1": "87f4bcaa26ee39078277bf0b55907c2c4797731e",
          "md5": "2992d5f11b42c20c003bd91a02268f9f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a9e",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a9e-android-0.1.5.aar",
          "url": "ble-characteristic-u2a9e-android-0.1.5.aar",
          "size": 3204,
          "sha512": "e0ccd646453b12f0852ad09cef9ad0d9ca4aa5c837621e34e1ea2a42511a28d27e16a7cd752f4ebcf1903b2479f2890b8e490eec737ee7b37b48751edad11174",
          "sha256": "2aa06c3d101ea797a896b256e071e53c6dee2cf7e9f686b1e409b0ee690d3cc2",
          "sha1": "87f4bcaa26ee39078277bf0b55907c2c4797731e",
          "md5": "2992d5f11b42c20c003bd91a02268f9f"
        }
      ]
    }
  ]
}
