{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2908-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2908",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2908-android-0.2.0.aar",
          "url": "ble-descriptor-u2908-android-0.2.0.aar",
          "size": 2912,
          "sha512": "d0266634ccad360a89c2ffd4eacf4e74e1a8af20ee317de92ab15d060a041cd8a5c2bad90fc0c566d0ae85810022c35c2c63846f139dab52a1a7d16403e69dd6",
          "sha256": "43cd320d89aa419c83cc23707f4e625e323f1b571c65784ad45f714c79730844",
          "sha1": "a5509971480403acf2f5d2fc3730f95b157c115c",
          "md5": "10af8c43388f93195eac1444a7e073fe"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2908",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2908-android-0.2.0.aar",
          "url": "ble-descriptor-u2908-android-0.2.0.aar",
          "size": 2912,
          "sha512": "d0266634ccad360a89c2ffd4eacf4e74e1a8af20ee317de92ab15d060a041cd8a5c2bad90fc0c566d0ae85810022c35c2c63846f139dab52a1a7d16403e69dd6",
          "sha256": "43cd320d89aa419c83cc23707f4e625e323f1b571c65784ad45f714c79730844",
          "sha1": "a5509971480403acf2f5d2fc3730f95b157c115c",
          "md5": "10af8c43388f93195eac1444a7e073fe"
        }
      ]
    }
  ]
}
