{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b35-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b35",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b35-android-0.8.6.aar",
          "url": "ble-characteristic-u2b35-android-0.8.6.aar",
          "size": 3347,
          "sha512": "d6ac79ad6982d35b578b0dd0145dbf984e32fb398056c73ec2862e54455f674cd740a185779fc350659dd637ca9a49cf64c3bc31224869d981f87c5bd409b9f2",
          "sha256": "3889d7a0c1f39a3688daeff1443f70aa80d40c3880ac462443e1d9db8f9c5cb1",
          "sha1": "780ceb2cc2d09658c0263bc598459a464b446fcc",
          "md5": "64d1fb6ceb7f84e18dc479a71e564d30"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b35",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b35-android-0.8.6.aar",
          "url": "ble-characteristic-u2b35-android-0.8.6.aar",
          "size": 3347,
          "sha512": "d6ac79ad6982d35b578b0dd0145dbf984e32fb398056c73ec2862e54455f674cd740a185779fc350659dd637ca9a49cf64c3bc31224869d981f87c5bd409b9f2",
          "sha256": "3889d7a0c1f39a3688daeff1443f70aa80d40c3880ac462443e1d9db8f9c5cb1",
          "sha1": "780ceb2cc2d09658c0263bc598459a464b446fcc",
          "md5": "64d1fb6ceb7f84e18dc479a71e564d30"
        }
      ]
    }
  ]
}
