{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b26",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.5.jar",
          "url": "ble-characteristic-u2b26-0.8.5.jar",
          "size": 1454,
          "sha512": "925dd1da75675c797f2e2374f0edf556cfc3dfcd2b69b4a065b8f17b94236993ff8360c47f48f4ce73ab6c7248296068d449f13167885442ef78cb6dab3957b3",
          "sha256": "a4d0a8045918940c93131ae664b90cb46d38c564eefd41967c6d39a2b9b5f51e",
          "sha1": "d4bd8812d26c432831e8ee299f407f412f7a6878",
          "md5": "6a70e98d772ac677079c6f93fc269982"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.5.jar",
          "url": "ble-characteristic-u2b26-0.8.5.jar",
          "size": 1454,
          "sha512": "925dd1da75675c797f2e2374f0edf556cfc3dfcd2b69b4a065b8f17b94236993ff8360c47f48f4ce73ab6c7248296068d449f13167885442ef78cb6dab3957b3",
          "sha256": "a4d0a8045918940c93131ae664b90cb46d38c564eefd41967c6d39a2b9b5f51e",
          "sha1": "d4bd8812d26c432831e8ee299f407f412f7a6878",
          "md5": "6a70e98d772ac677079c6f93fc269982"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2b26-0.8.5-javadoc.jar",
          "size": 107172,
          "sha512": "b797564d2897fe6e1e5a0e7bcf0eb887e5a5fa8d1ea6cecbe1044c4bdbaa32f4c62e0a1970bcae87dce5a228fac037b838cb4e03b98c6ad2a97ad1d63b7eff10",
          "sha256": "01609e0345fed33fb43bcb043319ced9b72df67b19d48578e0aa373916118e10",
          "sha1": "13e4ba887c63196711b4066bd1df774668cc8b7a",
          "md5": "dfcb01b0d86c03d3ee2004c01e9c1041"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b26-0.8.5-sources.jar",
          "url": "ble-characteristic-u2b26-0.8.5-sources.jar",
          "size": 1445,
          "sha512": "a44767be9b3249dd0b4d39daccf7efafc752fc87cf90a0995072bc18914690337325fa6de9bbad5bd1e2226c6105a8e435950c97118c28c08f4c8e02f84d6ac6",
          "sha256": "a083b9cbc2efc15188a247319721206a258774cc139561741dfa7c3ac759c726",
          "sha1": "eeebb21b2925b5fca53d4d4cbba3a714461ceb1e",
          "md5": "a9ec5b70c56df28129d7d586420b8a56"
        }
      ]
    }
  ]
}
