{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a65-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "xkebjxa6jvctjdek5g2bz3ghum"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.0.aar",
          "url": "ble-characteristic-u2a65-android-0.1.0.aar",
          "size": 2879,
          "sha512": "beb3aabca4fce592630ba5c8fa8239a6e5998357cd6cb741dc5aeeb6ea0122caf4a123ab99bd7b73c203deed864100d79e4e5b1b03dd3709c4b4829b8701a8e8",
          "sha256": "8d6ed95f20373c01b9168333b92141aa3d279c839dd2c40ec6fb8fae727f0d7d",
          "sha1": "ab8a05310e2333c4176d4698f806b80594a7b0be",
          "md5": "c7cc76d6ebbdb89910d734c1c3f5a5f0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.0.aar",
          "url": "ble-characteristic-u2a65-android-0.1.0.aar",
          "size": 2879,
          "sha512": "beb3aabca4fce592630ba5c8fa8239a6e5998357cd6cb741dc5aeeb6ea0122caf4a123ab99bd7b73c203deed864100d79e4e5b1b03dd3709c4b4829b8701a8e8",
          "sha256": "8d6ed95f20373c01b9168333b92141aa3d279c839dd2c40ec6fb8fae727f0d7d",
          "sha1": "ab8a05310e2333c4176d4698f806b80594a7b0be",
          "md5": "c7cc76d6ebbdb89910d734c1c3f5a5f0"
        }
      ]
    }
  ]
}
