{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0b",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0b-0.8.12.jar",
          "url": "ble-characteristic-u2b0b-0.8.12.jar",
          "size": 1937,
          "sha512": "cc79b601209b40a65b4f1079566dbad4dc9f75569226e937cd10b4810174a0a8adad9f3295ea0636a5a8b24a747794d7594c5885b62017080ab63f5fc75b9a97",
          "sha256": "c5e597fe63395280699c27a69109277d93ea6b16a073b7bb552cd660e5c757b2",
          "sha1": "7453c9b20022dc3674fa29b77be979f86cc32734",
          "md5": "2204720ff6d1e44b3a04c9a00358a3e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0b-0.8.12.jar",
          "url": "ble-characteristic-u2b0b-0.8.12.jar",
          "size": 1937,
          "sha512": "cc79b601209b40a65b4f1079566dbad4dc9f75569226e937cd10b4810174a0a8adad9f3295ea0636a5a8b24a747794d7594c5885b62017080ab63f5fc75b9a97",
          "sha256": "c5e597fe63395280699c27a69109277d93ea6b16a073b7bb552cd660e5c757b2",
          "sha1": "7453c9b20022dc3674fa29b77be979f86cc32734",
          "md5": "2204720ff6d1e44b3a04c9a00358a3e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0b-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b0b-0.8.12-javadoc.jar",
          "size": 107712,
          "sha512": "2304df78752b80eece50d4279ffe6e05a9a2440dc154de02c27fa9c098ab322f2f62f21ecfb9fc7700da569d918a4babe6862730c67b3311b6b23075b966ba2e",
          "sha256": "c204deee3dfc37501e0ccca44170a1210bc3307977c3004bc5705cd8e9b99230",
          "sha1": "67990a3dad4d2249e3c67001fd3500b7b7a8d769",
          "md5": "9eb406e4738127b01168cff48319f35a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0b-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b0b-0.8.12-sources.jar",
          "size": 1763,
          "sha512": "0ecd1b6c3f8a1bc1ce8fce26f8c8273be4c9467826d09b7ceb6568de0ef76fda701f3bb215659027d84bb6bb117758072c097b1d58fb65a4c146a349f741e0f4",
          "sha256": "4ac6d8b398d2e45df6dd3b6f9dbf1d706c1f86192649fce93ee8e5d70c275f60",
          "sha1": "0f57fc754d7d889d7da43aec9a5f6fe65d34f87a",
          "md5": "8a88bb2fbe9b8e255dc2dbdde9b5eabe"
        }
      ]
    }
  ]
}
