{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1c",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.6.jar",
          "url": "ble-characteristic-u2b1c-0.8.6.jar",
          "size": 1791,
          "sha512": "f9b975cb5310431aea350aedcfe0c82567862552fb0016c5b5af0e48f1438863adfadb097e16ff2947f964df9699ee0c1bb70fa8f6aa6d09343fb72288a9fd4d",
          "sha256": "8d831a4d02721d08b2f7336bc26c54ebe7e5fe570e271313e601b07107d91dd8",
          "sha1": "71ec3016f2f6ea34deb8f24e0e37aa9601856101",
          "md5": "69189d9d762cedaa43cac66f9e18132b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.6.jar",
          "url": "ble-characteristic-u2b1c-0.8.6.jar",
          "size": 1791,
          "sha512": "f9b975cb5310431aea350aedcfe0c82567862552fb0016c5b5af0e48f1438863adfadb097e16ff2947f964df9699ee0c1bb70fa8f6aa6d09343fb72288a9fd4d",
          "sha256": "8d831a4d02721d08b2f7336bc26c54ebe7e5fe570e271313e601b07107d91dd8",
          "sha1": "71ec3016f2f6ea34deb8f24e0e37aa9601856101",
          "md5": "69189d9d762cedaa43cac66f9e18132b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2b1c-0.8.6-javadoc.jar",
          "size": 107414,
          "sha512": "01f3141a0dad5967e16ea0947d809ac716c8690a9cfbcfa5e99d3350335b2b9b78f770b2c125db9f321aed8a57adc866bc4767724b715f983cff3b7bf23cce1a",
          "sha256": "74d3a73be4d07c5a4c6b29819b158d4eb9c45092ad9895613e2a1a3d66ffbaaa",
          "sha1": "9443b5834a29ff9ab4fdef4ec8483815d03cabdb",
          "md5": "9c6745aa9eda88b2113cdced4bbe1a21"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b1c-0.8.6-sources.jar",
          "url": "ble-characteristic-u2b1c-0.8.6-sources.jar",
          "size": 1632,
          "sha512": "68a4c493c9516c2d8b86925411de46044bdb3151cf1397d3932791be8513d96ec23ca1d104e79636a50fcebbf69ea07acb8cd2907425800b2d9254ef07367010",
          "sha256": "91d091b556094dc088fc04e03b491e8cb71fec1e3021593a29a35972726ef83e",
          "sha1": "890b408d59e6efa6e9aad9e623664c2b941a8e24",
          "md5": "a1062da15e09c4ed395f8ab7d887253b"
        }
      ]
    }
  ]
}
