{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b8f",
    "version": "0.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-0.8.4.jar",
          "url": "ble-characteristic-u2b8f-0.8.4.jar",
          "size": 1464,
          "sha512": "572aa2d5e2677d4961d087674ad00063d21ffef19667d433ebbdca90d58b5770b2e36c7c627850493a943da2890cdad92522458921b336e6c4b596d58594f822",
          "sha256": "4cc04c1e8cb75c3bc9966e952add2bf1807d9e2f27e5b857b17bc56344c64921",
          "sha1": "cfda42f05984099887851abc05dee435ea138f64",
          "md5": "7e717dbe08144a5afe8a32126040cbc3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b8f-0.8.4.jar",
          "url": "ble-characteristic-u2b8f-0.8.4.jar",
          "size": 1464,
          "sha512": "572aa2d5e2677d4961d087674ad00063d21ffef19667d433ebbdca90d58b5770b2e36c7c627850493a943da2890cdad92522458921b336e6c4b596d58594f822",
          "sha256": "4cc04c1e8cb75c3bc9966e952add2bf1807d9e2f27e5b857b17bc56344c64921",
          "sha1": "cfda42f05984099887851abc05dee435ea138f64",
          "md5": "7e717dbe08144a5afe8a32126040cbc3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8f-0.8.4-javadoc.jar",
          "url": "ble-characteristic-u2b8f-0.8.4-javadoc.jar",
          "size": 109928,
          "sha512": "1bac9c4d964ab4f25ba17d9697c976f488eefa95d5d8975829cab800d0af402d667ab9a012bb97748839b7c912b1e70cf31cdb8ea45adf6ccd03a7017ead7284",
          "sha256": "4c34cea2247fe43afeca4cf9784ec32dc9a61e56dbb815bc9932c30a549c5bf5",
          "sha1": "42144a8c9476d887b1aa246718f57f46815ae578",
          "md5": "9b06e3e72fd09d3caf9591751d81ade3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b8f-0.8.4-sources.jar",
          "url": "ble-characteristic-u2b8f-0.8.4-sources.jar",
          "size": 1452,
          "sha512": "110f08033d70c42f83d32cd94c43632b19515bb79eb0e20e4af10c24cf18229cc5631ba6b6df7ab3ac57732b40ddd2ebf7e6d50b34be08adbc0102fd5a47371e",
          "sha256": "4e1f40a94f284fb5f55c82315b91a4f39bd61a569cf703fadd56fdc4178a5abb",
          "sha1": "86bd78b7f3dc80e3f8b4e2cc5be3ba689e3c74b5",
          "md5": "669602f4a50d7ae6866b802498da382c"
        }
      ]
    }
  ]
}
