{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-peripheral-android",
    "version": "0.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "o3bwqdsevncm5oph662yyt44ja"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-peripheral",
          "version": {
            "requires": "0.2.28"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-android-0.1.10.aar",
          "url": "ble-service-peripheral-android-0.1.10.aar",
          "size": 2191,
          "sha512": "c9e07b0fd2034eb11a6f33f6458a511aeb9ae5ea81625ddfe7689056bec714451aedf682bfc9b3131dec108187c0e25c86c8c2db87931d057137c557946aaf9a",
          "sha256": "91a1dac0859fb2c781ac844e4080cfc38b88a5e61ec27b058d647cb79cfac597",
          "sha1": "83b48e88bc98a350363754aca75841e750b1cb35",
          "md5": "d116feac519e304cfe2363ebf2b1b3c0"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-peripheral",
          "version": {
            "requires": "0.2.28"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-peripheral-android-0.1.10.aar",
          "url": "ble-service-peripheral-android-0.1.10.aar",
          "size": 2191,
          "sha512": "c9e07b0fd2034eb11a6f33f6458a511aeb9ae5ea81625ddfe7689056bec714451aedf682bfc9b3131dec108187c0e25c86c8c2db87931d057137c557946aaf9a",
          "sha256": "91a1dac0859fb2c781ac844e4080cfc38b88a5e61ec27b058d647cb79cfac597",
          "sha1": "83b48e88bc98a350363754aca75841e750b1cb35",
          "md5": "d116feac519e304cfe2363ebf2b1b3c0"
        }
      ]
    }
  ]
}
