{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b0e",
    "version": "0.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0e-0.8.2.jar",
          "url": "ble-characteristic-u2b0e-0.8.2.jar",
          "size": 1950,
          "sha512": "471e2679fce231d41d6bfc392abac685e16fc39942340a553b5d21a3d751945c4f7f557610247a6a6708bf136907b14ce7cb1674bc74c249441d3de3351100bf",
          "sha256": "d5e4073c9f0e80345e26095f6f71ba07c2b4d9dd4f195aec2a6567f757bb6b93",
          "sha1": "371f5fd8ca448a8e599571ade896b922129fa411",
          "md5": "8cc467807b4e4ea0bc39cc4a39c41af6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b0e-0.8.2.jar",
          "url": "ble-characteristic-u2b0e-0.8.2.jar",
          "size": 1950,
          "sha512": "471e2679fce231d41d6bfc392abac685e16fc39942340a553b5d21a3d751945c4f7f557610247a6a6708bf136907b14ce7cb1674bc74c249441d3de3351100bf",
          "sha256": "d5e4073c9f0e80345e26095f6f71ba07c2b4d9dd4f195aec2a6567f757bb6b93",
          "sha1": "371f5fd8ca448a8e599571ade896b922129fa411",
          "md5": "8cc467807b4e4ea0bc39cc4a39c41af6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0e-0.8.2-javadoc.jar",
          "url": "ble-characteristic-u2b0e-0.8.2-javadoc.jar",
          "size": 110410,
          "sha512": "bef1cd77bf70a82bffa9b819b235dce0a06597a2786f4a0586be27f2ab55165b5828f83f703751ea6f16bc8add0d47b76c8905d61fc7422f7487614e86dcac2b",
          "sha256": "5452fcfbcc7ed8a36034d3982b62e054607166f66b8eb1b86c089e0365825780",
          "sha1": "136c095bc190d6b86cae260f2ddf4cbd786d66eb",
          "md5": "7b07720e5df0df3ec3a439e18f69296d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b0e-0.8.2-sources.jar",
          "url": "ble-characteristic-u2b0e-0.8.2-sources.jar",
          "size": 1762,
          "sha512": "834c51b851768b0a13b7b94d75b556ad4622c9fd17e663fa1a6afb24c0d5b06e1a1eee09b11f442b0dc54581ebb87bde74958599d39b7bee560638736cd2dcab",
          "sha256": "7a7011b99be5b09da32f9e6e5aefb2d7311a6f98e7a9e9141bf6f0f9eafaed41",
          "sha1": "129cb9050d119045a5dab7cc12eb21fc8b04bd67",
          "md5": "fe0955dc37955b04c54e85e9cee6cd37"
        }
      ]
    }
  ]
}
