{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4e",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "e3ikqwiwsbdaddptppumhoyem4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-0.1.0.jar",
          "url": "ble-characteristic-u2a4e-0.1.0.jar",
          "size": 1836,
          "sha512": "184e7a42ea430c06f62fca8e50f9733a26c9c12b4d6e45e431f85e65ba635c58d5d0ab55eb48b0dd7e39dfb31656a1a418dc4bc24eadb78e855e676c493933ed",
          "sha256": "2637fe52c88fd835c18e2c63459952ac733ca2e9f781ddf6490caa615485f165",
          "sha1": "a911d731e2d357cbf9d3fbd2156a45e3992dd8e0",
          "md5": "53d5c73f9e9208b362115fdca2d0ca95"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4e-0.1.0.jar",
          "url": "ble-characteristic-u2a4e-0.1.0.jar",
          "size": 1836,
          "sha512": "184e7a42ea430c06f62fca8e50f9733a26c9c12b4d6e45e431f85e65ba635c58d5d0ab55eb48b0dd7e39dfb31656a1a418dc4bc24eadb78e855e676c493933ed",
          "sha256": "2637fe52c88fd835c18e2c63459952ac733ca2e9f781ddf6490caa615485f165",
          "sha1": "a911d731e2d357cbf9d3fbd2156a45e3992dd8e0",
          "md5": "53d5c73f9e9208b362115fdca2d0ca95"
        }
      ]
    }
  ]
}
