{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2900-android",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vdshvfksofcw3psi6e37oosvcq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-android-0.1.0.aar",
          "url": "ble-descriptor-u2900-android-0.1.0.aar",
          "size": 2916,
          "sha512": "4809f3f11bb6b42c9d2335290fd5fe3b857fe8923d29cb27670731b5e2aaa435ce53b02ce525cf2a1f96c3b945c08b37504fe5586a9d471ba13cd2183e6aee02",
          "sha256": "9452af88e79ef22ffb825fae0a34bbb4165284c2e622f3b682dc9f63197a289e",
          "sha1": "ff040d30462333358cdd13ced1966fab8fdb9df1",
          "md5": "dd85a93e42f70546c8a3c60ffef66c6c"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-android-0.1.0.aar",
          "url": "ble-descriptor-u2900-android-0.1.0.aar",
          "size": 2916,
          "sha512": "4809f3f11bb6b42c9d2335290fd5fe3b857fe8923d29cb27670731b5e2aaa435ce53b02ce525cf2a1f96c3b945c08b37504fe5586a9d471ba13cd2183e6aee02",
          "sha256": "9452af88e79ef22ffb825fae0a34bbb4165284c2e622f3b682dc9f63197a289e",
          "sha1": "ff040d30462333358cdd13ced1966fab8fdb9df1",
          "md5": "dd85a93e42f70546c8a3c60ffef66c6c"
        }
      ]
    }
  ]
}
