{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-wsp-peripheral-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-wsp-peripheral-android-0.1.4.aar",
          "url": "ble-profile-wsp-peripheral-android-0.1.4.aar",
          "size": 13692,
          "sha512": "a147e47f7152d919afcc2e68bcc3ab524253710aa19b46b039a3ab4f25ee4b7dd3fb67d3aaf0ccd1422db74b331ffc5833b8f6301a3016579ad4db702c3c535d",
          "sha256": "2dafaf94649ec16c83f2b07890b75324593d0228dc76e1f31d0020e2a7f339fd",
          "sha1": "19cd5700edca98eee5aaa55a19d910295221287b",
          "md5": "cf1722cf5fb84fcf3b51eab1dc236f84"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-peripheral-android",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-wss-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-uds-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bas-peripheral-android",
          "version": {
            "requires": "0.1.11"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-peripheral-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-wsp-peripheral-android-0.1.4.aar",
          "url": "ble-profile-wsp-peripheral-android-0.1.4.aar",
          "size": 13692,
          "sha512": "a147e47f7152d919afcc2e68bcc3ab524253710aa19b46b039a3ab4f25ee4b7dd3fb67d3aaf0ccd1422db74b331ffc5833b8f6301a3016579ad4db702c3c535d",
          "sha256": "2dafaf94649ec16c83f2b07890b75324593d0228dc76e1f31d0020e2a7f339fd",
          "sha1": "19cd5700edca98eee5aaa55a19d910295221287b",
          "md5": "cf1722cf5fb84fcf3b51eab1dc236f84"
        }
      ]
    }
  ]
}
