{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a44-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "swq2gxvgereszma3nz5hc5y3xq"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.2.5.aar",
          "url": "ble-characteristic-u2a44-android-0.2.5.aar",
          "size": 3170,
          "sha512": "8b5430e027fcfba3445669a226ac246e71e3861ea35be1563708023181f05f461e9f572d6b26cc16b2e9935da975ce7a925074c99c49a45e34036f83aa697550",
          "sha256": "0872c3f117dd959b2f1429c916d51bf87b2745785b962e9131bf8c4472528a10",
          "sha1": "c789e3b87665a998b2392102d73100c34d3948d1",
          "md5": "2cdef5461b6cf6992e9d502f04568849"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a44",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a44-android-0.2.5.aar",
          "url": "ble-characteristic-u2a44-android-0.2.5.aar",
          "size": 3170,
          "sha512": "8b5430e027fcfba3445669a226ac246e71e3861ea35be1563708023181f05f461e9f572d6b26cc16b2e9935da975ce7a925074c99c49a45e34036f83aa697550",
          "sha256": "0872c3f117dd959b2f1429c916d51bf87b2745785b962e9131bf8c4472528a10",
          "sha1": "c789e3b87665a998b2392102d73100c34d3948d1",
          "md5": "2cdef5461b6cf6992e9d502f04568849"
        }
      ]
    }
  ]
}
