{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b9e-android",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "344npnyoa5ayjkbynljtch2rwy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9e",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9e-android-0.4.4.aar",
          "url": "ble-characteristic-u2b9e-android-0.4.4.aar",
          "size": 3069,
          "sha512": "159c875dd027dbbe68dae401869c203e053908bf333d21c321878139bc75d2e0c24de2807559da5f4248c32126ccfe54e82c3cf32a9d5843c4af9fcc41f0d91b",
          "sha256": "1b510cdf18fb7c98d936b23e09939045319db1ac76acb745136e7c7eb630de9f",
          "sha1": "2ab4cbcb46d964f1bcd9e871e6603828d5e546ce",
          "md5": "c183a803d9d997f1763e9d67c3fb698d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b9e",
          "version": {
            "requires": "0.4.4"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b9e-android-0.4.4.aar",
          "url": "ble-characteristic-u2b9e-android-0.4.4.aar",
          "size": 3069,
          "sha512": "159c875dd027dbbe68dae401869c203e053908bf333d21c321878139bc75d2e0c24de2807559da5f4248c32126ccfe54e82c3cf32a9d5843c4af9fcc41f0d91b",
          "sha256": "1b510cdf18fb7c98d936b23e09939045319db1ac76acb745136e7c7eb630de9f",
          "sha1": "2ab4cbcb46d964f1bcd9e871e6603828d5e546ce",
          "md5": "c183a803d9d997f1763e9d67c3fb698d"
        }
      ]
    }
  ]
}
