{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae9",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae9-0.8.6.jar",
          "url": "ble-characteristic-u2ae9-0.8.6.jar",
          "size": 1803,
          "sha512": "859b775b63ca8691cbf12ba689a3dd9cd5a759bce7f5782ac7d3a89bc6d41245b4d2809d6a53596cc29335f60f2920a47ac8dba676e2682406b99b8b77cdb996",
          "sha256": "f14a219081ee91f41efe1eabeae1e5a113a96bfca7e524e35be72a3ed04f8c2c",
          "sha1": "7e86ea7ace418b2bd657f60d497a263bcfb4a17a",
          "md5": "4f01963a74b0aedc9b12ef5e54a616c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae9-0.8.6.jar",
          "url": "ble-characteristic-u2ae9-0.8.6.jar",
          "size": 1803,
          "sha512": "859b775b63ca8691cbf12ba689a3dd9cd5a759bce7f5782ac7d3a89bc6d41245b4d2809d6a53596cc29335f60f2920a47ac8dba676e2682406b99b8b77cdb996",
          "sha256": "f14a219081ee91f41efe1eabeae1e5a113a96bfca7e524e35be72a3ed04f8c2c",
          "sha1": "7e86ea7ace418b2bd657f60d497a263bcfb4a17a",
          "md5": "4f01963a74b0aedc9b12ef5e54a616c3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae9-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2ae9-0.8.6-javadoc.jar",
          "size": 107448,
          "sha512": "dd2db578cb2455a6a9dcda92245e86df4b48435ee279cc0b4e8b15ef2d5b466cc1512040aec77edf39d73abe11c318113a74bf8c3034d25dca2c9ce249055cd6",
          "sha256": "b2da7e6bb6f070472bba61869b03437bfdfcee8c547e688f64fd009309e8d724",
          "sha1": "256bcffab0df38e9bce4233a45a07480a42ca492",
          "md5": "0cb3af964a14eb346751035659cf4b0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae9-0.8.6-sources.jar",
          "url": "ble-characteristic-u2ae9-0.8.6-sources.jar",
          "size": 1645,
          "sha512": "e658082d4056812cc64d92f73f37858d5603ba218d90d97e742db5babb483182d7afcd04f5e361c074c7876a571a10cb85106cb3c42a4a9448af86ee680d1d7b",
          "sha256": "f90d9802db8668ffa3603ca75cc80e5762e5d1ff14355ecf9a726b8ba37be74f",
          "sha1": "7c62ddf277145d6c3350f135be3ba0643cbb9c8c",
          "md5": "580821a1e9c4c44a12667b132b5798ff"
        }
      ]
    }
  ]
}
