{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a6a-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "fxrmxjl6szatjaovsgygwi5l4m"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.1.4.aar",
          "url": "ble-characteristic-u2a6a-android-0.1.4.aar",
          "size": 3017,
          "sha512": "b6832b51312439207ecb527cafd1b3a63d6a3ca70ca1ed7db28e92d417da13d2aa999d0b47b9aa006c35637bc449d43dcbf3fd391addf1230512330f74620e7d",
          "sha256": "63d67e051eb8315ac36d77a61e2909de8923a04eed075f375ea179c0e0bc6a80",
          "sha1": "72ee0a32f8a525f14f5ef837fcec0a67ab70207e",
          "md5": "91e4712112b3161f37d4ec8c55e25a6d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a6a",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a6a-android-0.1.4.aar",
          "url": "ble-characteristic-u2a6a-android-0.1.4.aar",
          "size": 3017,
          "sha512": "b6832b51312439207ecb527cafd1b3a63d6a3ca70ca1ed7db28e92d417da13d2aa999d0b47b9aa006c35637bc449d43dcbf3fd391addf1230512330f74620e7d",
          "sha256": "63d67e051eb8315ac36d77a61e2909de8923a04eed075f375ea179c0e0bc6a80",
          "sha1": "72ee0a32f8a525f14f5ef837fcec0a67ab70207e",
          "md5": "91e4712112b3161f37d4ec8c55e25a6d"
        }
      ]
    }
  ]
}
