{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a00-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.8.6.aar",
          "url": "ble-characteristic-u2a00-android-0.8.6.aar",
          "size": 3087,
          "sha512": "7a9e5832ba72656998e490be9aaaf14389a1c5c4c2025334f4b324ae6b047d221daba2ccac11dd29259c8c82cd92b02c3e54bda86a4d7c513a7cec94534bf8e2",
          "sha256": "5bdd894de67384535f3d5fa0fe34ee659c7c2848bc29b287d26c7b51b033f257",
          "sha1": "a3adef469addd47e2cebf45998ecd244bf1c6957",
          "md5": "3d43c7809c50439ba14ee98a39034e8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a00",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.8.6.aar",
          "url": "ble-characteristic-u2a00-android-0.8.6.aar",
          "size": 3087,
          "sha512": "7a9e5832ba72656998e490be9aaaf14389a1c5c4c2025334f4b324ae6b047d221daba2ccac11dd29259c8c82cd92b02c3e54bda86a4d7c513a7cec94534bf8e2",
          "sha256": "5bdd894de67384535f3d5fa0fe34ee659c7c2848bc29b287d26c7b51b033f257",
          "sha1": "a3adef469addd47e2cebf45998ecd244bf1c6957",
          "md5": "3d43c7809c50439ba14ee98a39034e8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a00-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a00-android-0.8.6-sources.jar",
          "size": 2151,
          "sha512": "36009ef03a87db195b09b8db3383dee207b47f371c7814a8bb3929d5ac9a85ab9c9c7d47234bb0a0de9440fb91ec5d7ff6063ed0dde30019fb7c3c6661a08fe4",
          "sha256": "3dddb5a7ed30acf866987f05d1bf1d6459df65d9e644d880183343550a798e60",
          "sha1": "92c29f1d99f6198a41a4f3fca0634ceee9f53745",
          "md5": "2a680045104903353565009886a80d8a"
        }
      ]
    }
  ]
}
