{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b85",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.12.jar",
          "url": "ble-characteristic-u2b85-0.8.12.jar",
          "size": 1774,
          "sha512": "6b31d8a57adc95aa66faea51a44c7cd0ce2c5520e15f3016987727447c61eaa392dc704e90ac9d8be1e157c209222a83d9ead16cf32e741d5319b386ba05d609",
          "sha256": "52e8dd0c72e53de5cd1c1b4e61dc526365bfdcad76ca57dc8575527f42b85555",
          "sha1": "d20fe5600ff9d9926f328925c5b0fa47fdec37e5",
          "md5": "84ce7f977b3bb29115cbd44f4db43937"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.12.jar",
          "url": "ble-characteristic-u2b85-0.8.12.jar",
          "size": 1774,
          "sha512": "6b31d8a57adc95aa66faea51a44c7cd0ce2c5520e15f3016987727447c61eaa392dc704e90ac9d8be1e157c209222a83d9ead16cf32e741d5319b386ba05d609",
          "sha256": "52e8dd0c72e53de5cd1c1b4e61dc526365bfdcad76ca57dc8575527f42b85555",
          "sha1": "d20fe5600ff9d9926f328925c5b0fa47fdec37e5",
          "md5": "84ce7f977b3bb29115cbd44f4db43937"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2b85-0.8.12-javadoc.jar",
          "size": 107398,
          "sha512": "e7ac8d6da8dcc42bfe86f81b965e14dce95744215d9e5539a6062de06ddb0df1bbfc2fcf1ec5f5eb58d2ea286390e23eaf5f53cb4735d72edfa37a460e1af91c",
          "sha256": "a18e890fac28f68a7810c93c1a9d3ad1013b9f690d542a7e6c1984822567fb1d",
          "sha1": "e00ffa2a7e3053ce2cfe9ac731d80e330b619764",
          "md5": "1b9535f4841efb4354eab031e7ae28f2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b85-0.8.12-sources.jar",
          "url": "ble-characteristic-u2b85-0.8.12-sources.jar",
          "size": 1618,
          "sha512": "e3ee192260f3ca5de1e77d602776364b481b5128de0ecd9c1553a637bfc64ad1cd78092dd8a6008e636d61ad872152328aebc9acb5c514f0daa9e6c98891c0c8",
          "sha256": "d01b33659aec85efae12d9f5cea0657151c559e0e4842c67de65cc4f0d0e9131",
          "sha1": "c99586381985bf975b48b96b18f7225a5be71e2b",
          "md5": "1b152fd17f5917eee76ecf901542c0ac"
        }
      ]
    }
  ]
}
