{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b1d-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bs3no43zwfeutmivy5vh5lgffe"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1d",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1d-android-0.2.5.aar",
          "url": "ble-characteristic-u2b1d-android-0.2.5.aar",
          "size": 3087,
          "sha512": "a0c9567598adeb0c8d6cafe7e52fd219aa7024567d2acc11e1792279417dea9bafaca5333fd9b015fc233492e4de3715d1e6f71a13a9741119474e4f29e0c7e1",
          "sha256": "a459d611a40383e566e528123789baac6924ad811aa3dc15b0c1326f1128c721",
          "sha1": "a62366fa1de3d2c64106b752a6d58c58bc40be80",
          "md5": "76cb5b972657ab44917d2af47e78827d"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2b1d",
          "version": {
            "requires": "0.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b1d-android-0.2.5.aar",
          "url": "ble-characteristic-u2b1d-android-0.2.5.aar",
          "size": 3087,
          "sha512": "a0c9567598adeb0c8d6cafe7e52fd219aa7024567d2acc11e1792279417dea9bafaca5333fd9b015fc233492e4de3715d1e6f71a13a9741119474e4f29e0c7e1",
          "sha256": "a459d611a40383e566e528123789baac6924ad811aa3dc15b0c1326f1128c721",
          "sha1": "a62366fa1de3d2c64106b752a6d58c58bc40be80",
          "md5": "76cb5b972657ab44917d2af47e78827d"
        }
      ]
    }
  ]
}
