{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b16",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b16-0.8.10.jar",
          "url": "ble-characteristic-u2b16-0.8.10.jar",
          "size": 1766,
          "sha512": "375f515540c66f39f6905042f13219a28182d111bf38b2d58a4a91003038d31bbf8df60e55d9fb99201c9755d762ca4b835e320b2c7bbb7debb2651d733c3f68",
          "sha256": "5297087ff928fd825a67d354ef8d02d1d82f558a9e418b97d8a661f7ebdcb63a",
          "sha1": "8d505eb7718cf0ae340b12db2baa33e7c8e719c0",
          "md5": "bf26f2cd6ef1c42297f4ed55a04403b7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b16-0.8.10.jar",
          "url": "ble-characteristic-u2b16-0.8.10.jar",
          "size": 1766,
          "sha512": "375f515540c66f39f6905042f13219a28182d111bf38b2d58a4a91003038d31bbf8df60e55d9fb99201c9755d762ca4b835e320b2c7bbb7debb2651d733c3f68",
          "sha256": "5297087ff928fd825a67d354ef8d02d1d82f558a9e418b97d8a661f7ebdcb63a",
          "sha1": "8d505eb7718cf0ae340b12db2baa33e7c8e719c0",
          "md5": "bf26f2cd6ef1c42297f4ed55a04403b7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b16-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2b16-0.8.10-javadoc.jar",
          "size": 107333,
          "sha512": "ff29f6992bb624a039b5617ccd40533a8c9148e871ed31eb7ec1b6d6146d499d537d5d6147a5d6585f6a044a29238e180f6747baec287c515c7cdbbf79ada68f",
          "sha256": "5cd46a73294b10360ce2fb16fda9a655e128d0f6428fc06831f6ce12abef5cc5",
          "sha1": "53c1deed94c02ff118bbbc512f67db11a2d4086e",
          "md5": "b4dd817d0a42b21661edf809fbef4d04"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b16-0.8.10-sources.jar",
          "url": "ble-characteristic-u2b16-0.8.10-sources.jar",
          "size": 1611,
          "sha512": "1342f7d0d0c6ef3fe9bea8e01ce0545e0c20bbfe88d460b565a5f3e5c4d8c4312d85ac3b6f0c1c6df41376b8bda6b688c1987805843cd5b54d346bdb5ac4f944",
          "sha256": "295a991e453a8e75a34aecb79302f74c11db090f49adda0f4d443d5fd0a30c24",
          "sha1": "835b50af362f8e0d9c63b352c34eda9f16736f7e",
          "md5": "69f8ddb3bc00564f88bf4f79d2e9a2bb"
        }
      ]
    }
  ]
}
