{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a5b-android",
    "version": "0.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.8.10.aar",
          "url": "ble-characteristic-u2a5b-android-0.8.10.aar",
          "size": 3267,
          "sha512": "74e8e33c3ef7c40107260227cc40dc4d8878aa2a785f84f6763ec543e7790b235979facebc92afcda8a5dd5b87c936dbc45cb517e1df9738ec9c347b39fe4aba",
          "sha256": "93e379ac391ce7dba18c8f25a8a6bfb7966efea82db008786ac687f9c1ca9c7e",
          "sha1": "e246e9d72ad0fd707bc27d873e50fe7a319a7983",
          "md5": "0860f56262d29e67569a2a696b56e3a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a5b",
          "version": {
            "requires": "0.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.8.10.aar",
          "url": "ble-characteristic-u2a5b-android-0.8.10.aar",
          "size": 3267,
          "sha512": "74e8e33c3ef7c40107260227cc40dc4d8878aa2a785f84f6763ec543e7790b235979facebc92afcda8a5dd5b87c936dbc45cb517e1df9738ec9c347b39fe4aba",
          "sha256": "93e379ac391ce7dba18c8f25a8a6bfb7966efea82db008786ac687f9c1ca9c7e",
          "sha1": "e246e9d72ad0fd707bc27d873e50fe7a319a7983",
          "md5": "0860f56262d29e67569a2a696b56e3a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.8.10-sources.jar",
          "url": "ble-characteristic-u2a5b-android-0.8.10-sources.jar",
          "size": 2271,
          "sha512": "073ceac42e54536842deb7381ee9578c02c9e1352a792af4103fa935acdfe6328fe266b7c8c68e5a7bd808a6693912cfb559cf193bfeb2602ef5a541fb25b2d5",
          "sha256": "e673000591667fcb4cea57b6016815b81c35cedad053b4b9a37350226d2fb09f",
          "sha1": "eb1f5ec71f90c05bb0320e888abe13c112c672ef",
          "md5": "9e45336c324192e9593794fadc045973"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a5b-android-0.8.10-javadoc.jar",
          "url": "ble-characteristic-u2a5b-android-0.8.10-javadoc.jar",
          "size": 272680,
          "sha512": "91494c56bb03ebd4ed61081205f7d8e1e01e37432f5bf616adf1838d6c82a27bc26adb591a8f75c1d8b3ac1381ac234353da4ccad885ab13b6a5a6287971eda8",
          "sha256": "b6df4ada04373c079cf674d83aa831f4ed9254182a9a0dca956fd4558cafa1c5",
          "sha1": "f0c6a30451c4d4f8425390169e961ef5ee1bd941",
          "md5": "1e3d557a7c862b761e9d6db5235aacb7"
        }
      ]
    }
  ]
}
