{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1e-android",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "stagingVariantStagingApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-android-0.8.12.aar",
          "url": "ble-characteristic-u2a1e-android-0.8.12.aar",
          "size": 3520,
          "sha512": "161315055bb69213f8eedf633d461a661e5d3a33975ed33fbb1b632eda7bfae31bbce11973dcf61c2f3270f145a8d6dfd11cf9ec84dce1f77db933ca4b48775c",
          "sha256": "62fe33efc7cebe4bf1cd48e330963662034d4cf9bab79ae6794c098365f3cbc9",
          "sha1": "9efa0bd92d1314cf42e3ab9c1e993ba15d4c21f1",
          "md5": "66627a8e5e9e91ecdc073a44d2f1459b"
        }
      ]
    },
    {
      "name": "stagingVariantStagingRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e",
          "version": {
            "requires": "0.8.12"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-android-0.8.12.aar",
          "url": "ble-characteristic-u2a1e-android-0.8.12.aar",
          "size": 3520,
          "sha512": "161315055bb69213f8eedf633d461a661e5d3a33975ed33fbb1b632eda7bfae31bbce11973dcf61c2f3270f145a8d6dfd11cf9ec84dce1f77db933ca4b48775c",
          "sha256": "62fe33efc7cebe4bf1cd48e330963662034d4cf9bab79ae6794c098365f3cbc9",
          "sha1": "9efa0bd92d1314cf42e3ab9c1e993ba15d4c21f1",
          "md5": "66627a8e5e9e91ecdc073a44d2f1459b"
        }
      ]
    }
  ]
}
