{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-dis-cental-android",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6qzyj4vz6fc4vcyskbqyrpmi7i"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-dis-cental-android-0.1.4.aar",
          "url": "ble-service-dis-cental-android-0.1.4.aar",
          "size": 5569,
          "sha512": "3484908984d64caf3cf5a66763ecf6c201d4a44da1fa1a3afe9df0b66d41f10693d98c76d2577d2cdb63e5a33efde4999861079eae29da622e345f162727026b",
          "sha256": "ccbb119301cb8b5c14bea2260d406854d6fa30fc8189d00b16d7d9d5d5d441d4",
          "sha1": "9e0be4c8e15e1bbe9cdad01df7414c9a685c4118",
          "md5": "c1fd623c21bf58f3a97b87c673ac9462"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-dis-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-dis-cental-android-0.1.4.aar",
          "url": "ble-service-dis-cental-android-0.1.4.aar",
          "size": 5569,
          "sha512": "3484908984d64caf3cf5a66763ecf6c201d4a44da1fa1a3afe9df0b66d41f10693d98c76d2577d2cdb63e5a33efde4999861079eae29da622e345f162727026b",
          "sha256": "ccbb119301cb8b5c14bea2260d406854d6fa30fc8189d00b16d7d9d5d5d441d4",
          "sha1": "9e0be4c8e15e1bbe9cdad01df7414c9a685c4118",
          "md5": "c1fd623c21bf58f3a97b87c673ac9462"
        }
      ]
    }
  ]
}
