{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ad1-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "rwz5w2a4ijg27poploejtwndhi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad1-android-0.2.0.aar",
          "url": "ble-characteristic-u2ad1-android-0.2.0.aar",
          "size": 5112,
          "sha512": "fe7e0b4510054cbf5f98093df9481b91b4394cb5a9dc6d23f47326c1e82c4b449af44534010926c82567dbc6d294399b3482ec7052558093e822da78c82ce5b9",
          "sha256": "3b18012b9e2aa97f2ef641aa818c32f3a497548ce5ded1e9e1ebe2a71c97310c",
          "sha1": "400b6c830512db24349c146f4a07a8421b46c497",
          "md5": "5a7dd5f9b4435583a5804f345a3f2c55"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2ad1",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ad1-android-0.2.0.aar",
          "url": "ble-characteristic-u2ad1-android-0.2.0.aar",
          "size": 5112,
          "sha512": "fe7e0b4510054cbf5f98093df9481b91b4394cb5a9dc6d23f47326c1e82c4b449af44534010926c82567dbc6d294399b3482ec7052558093e822da78c82ce5b9",
          "sha256": "3b18012b9e2aa97f2ef641aa818c32f3a497548ce5ded1e9e1ebe2a71c97310c",
          "sha1": "400b6c830512db24349c146f4a07a8421b46c497",
          "md5": "5a7dd5f9b4435583a5804f345a3f2c55"
        }
      ]
    }
  ]
}
