{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bbb",
    "version": "0.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbb-0.8.8.jar",
          "url": "ble-characteristic-u2bbb-0.8.8.jar",
          "size": 1446,
          "sha512": "0a4ac0cdb3a6ffa65543e815c81e427be63aeac5967287cd5c98c3501306374ef5e135860d36705ce7163ce6145ca48872604b5e9bbe106d55e17e863af20ee6",
          "sha256": "a8d6f92c8c83015c4928c073abb9be103978cf057dd477b1d8f5d769b49c5153",
          "sha1": "918174c77f25567ed4203f3f6e10b7fa2fece339",
          "md5": "9a25e9927df643ff0b42bdca0206fc5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bbb-0.8.8.jar",
          "url": "ble-characteristic-u2bbb-0.8.8.jar",
          "size": 1446,
          "sha512": "0a4ac0cdb3a6ffa65543e815c81e427be63aeac5967287cd5c98c3501306374ef5e135860d36705ce7163ce6145ca48872604b5e9bbe106d55e17e863af20ee6",
          "sha256": "a8d6f92c8c83015c4928c073abb9be103978cf057dd477b1d8f5d769b49c5153",
          "sha1": "918174c77f25567ed4203f3f6e10b7fa2fece339",
          "md5": "9a25e9927df643ff0b42bdca0206fc5a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbb-0.8.8-javadoc.jar",
          "url": "ble-characteristic-u2bbb-0.8.8-javadoc.jar",
          "size": 107119,
          "sha512": "7faa44137d1f3faeb88940242a7652fce775f4eacbc4bd7291fdf795b836bcd87dca97eb0099071ba93f1e29a0cc70c11d8d08f1f494fa90779966e4e962e9bb",
          "sha256": "892fb9c6a6f61e2719ca73a3f764c7f0086826048e55d47e9b4264880d13c48e",
          "sha1": "0d02e3dfb519a75d8a1b0d353525aa594ddee2e0",
          "md5": "268b025cc342b2395c3eedbcaefb5d01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bbb-0.8.8-sources.jar",
          "url": "ble-characteristic-u2bbb-0.8.8-sources.jar",
          "size": 1437,
          "sha512": "d12c323f22c08581559300329b2962608f5a8b99f267a0bbc0811516150e0a32738c7926241776ffd0470c9f81a280dc731d4cd40811dca2ae84a20c5703fe8a",
          "sha256": "7e6b1831f61073e348d6a1157efc6d65b224a3173218cebc73ffec9b16bf8c7d",
          "sha1": "2c218aaceaea435e6ce7e3c7f0b844e2d002eb98",
          "md5": "2cac978d92abb22e3dc80bd49905af03"
        }
      ]
    }
  ]
}
