{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a80-android",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "kupq6qdcq5dovle6dw5m7myoyy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a80-android-0.2.3.aar",
          "url": "ble-characteristic-u2a80-android-0.2.3.aar",
          "size": 3038,
          "sha512": "2a225be1a95b065c8cd0a6fd5e9096da2405259173c691feb8a6b0854b4917b872599620b2172e6f37f39ac1b772b8131b8fa990c25a165bbaa817a5968e7ebb",
          "sha256": "3132b2e7e62475e8c1fe5f01fb71b75b77eb90efc7ff962438647bd93df5e111",
          "sha1": "8571cc5dee92e618b86037c822ad72685be1ae26",
          "md5": "ad60a27f12c1de823eddffda7fd1bd97"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a80",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a80-android-0.2.3.aar",
          "url": "ble-characteristic-u2a80-android-0.2.3.aar",
          "size": 3038,
          "sha512": "2a225be1a95b065c8cd0a6fd5e9096da2405259173c691feb8a6b0854b4917b872599620b2172e6f37f39ac1b772b8131b8fa990c25a165bbaa817a5968e7ebb",
          "sha256": "3132b2e7e62475e8c1fe5f01fb71b75b77eb90efc7ff962438647bd93df5e111",
          "sha1": "8571cc5dee92e618b86037c822ad72685be1ae26",
          "md5": "ad60a27f12c1de823eddffda7fd1bd97"
        }
      ]
    }
  ]
}
