{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-core",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-0.8.5.jar",
          "url": "ble-core-0.8.5.jar",
          "size": 261,
          "sha512": "8c1d1984993841287308bd40bf00d9593bd7f0562ee0fa5a483832daab67b5038d1fd3965111984eb0e7f516d2e64aea07ed1f46cb35f9da99e6e7d7a47f2c97",
          "sha256": "57fff2c0b7a548646844bbbd4410c148086b563f07c9dbcfe2ae227ccaf693a0",
          "sha1": "51bce4b4f3120973607ea618d2154236172eddc3",
          "md5": "b602ae69564962ff1be43a44c6a59f55"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-constants",
          "version": {
            "requires": "0.8.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-core-0.8.5.jar",
          "url": "ble-core-0.8.5.jar",
          "size": 261,
          "sha512": "8c1d1984993841287308bd40bf00d9593bd7f0562ee0fa5a483832daab67b5038d1fd3965111984eb0e7f516d2e64aea07ed1f46cb35f9da99e6e7d7a47f2c97",
          "sha256": "57fff2c0b7a548646844bbbd4410c148086b563f07c9dbcfe2ae227ccaf693a0",
          "sha1": "51bce4b4f3120973607ea618d2154236172eddc3",
          "md5": "b602ae69564962ff1be43a44c6a59f55"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-0.8.5-javadoc.jar",
          "url": "ble-core-0.8.5-javadoc.jar",
          "size": 261,
          "sha512": "3e90f48ee6d4a3e4e77d1a4af585d8ab721f0a1e8aeca7813762df2de6c92f2a715977150887272d0fbf099de07a8e79168fd2f46d8f771581b4d4e3a7a5ed25",
          "sha256": "b717653b3c494c6fd68b2eb8ad971ed6234fd4a74b329c068c55dbba6a9541e5",
          "sha1": "2ab6274aee8a9428c114f65f3649b5ab4a08244a",
          "md5": "5a6c1ec00a8c00a1563a6c62a52037ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-core-0.8.5-sources.jar",
          "url": "ble-core-0.8.5-sources.jar",
          "size": 261,
          "sha512": "3e90f48ee6d4a3e4e77d1a4af585d8ab721f0a1e8aeca7813762df2de6c92f2a715977150887272d0fbf099de07a8e79168fd2f46d8f771581b4d4e3a7a5ed25",
          "sha256": "b717653b3c494c6fd68b2eb8ad971ed6234fd4a74b329c068c55dbba6a9541e5",
          "sha1": "2ab6274aee8a9428c114f65f3649b5ab4a08244a",
          "md5": "5a6c1ec00a8c00a1563a6c62a52037ef"
        }
      ]
    }
  ]
}
