{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ab6",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "jy7ixesazfhqnmjb55547uywfu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab6-0.1.0.jar",
          "url": "ble-characteristic-u2ab6-0.1.0.jar",
          "size": 1501,
          "sha512": "7077a250d1e734e6a2527d8e9b5869f85dcfff713f08a36615fc20642ea150ff745b5d318ccc10466c9da6e2a3528acb55e9706f5999348fe925db97d459dc36",
          "sha256": "2bb9eadef8d395da9b1137c48c04d503ecefbb4410265168e9079b313213a482",
          "sha1": "cb88d1dc1f81bda31ad4978a748016ad1b7d5b88",
          "md5": "e381f2f7b62b2f5f75f0d2e309d370f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ab6-0.1.0.jar",
          "url": "ble-characteristic-u2ab6-0.1.0.jar",
          "size": 1501,
          "sha512": "7077a250d1e734e6a2527d8e9b5869f85dcfff713f08a36615fc20642ea150ff745b5d318ccc10466c9da6e2a3528acb55e9706f5999348fe925db97d459dc36",
          "sha256": "2bb9eadef8d395da9b1137c48c04d503ecefbb4410265168e9079b313213a482",
          "sha1": "cb88d1dc1f81bda31ad4978a748016ad1b7d5b88",
          "md5": "e381f2f7b62b2f5f75f0d2e309d370f0"
        }
      ]
    }
  ]
}
