{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a32",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0",
      "buildId": "bo2m2bzyvfgbjfmoy4levvs3tm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-0.1.1.jar",
          "url": "ble-characteristic-u2a32-0.1.1.jar",
          "size": 1519,
          "sha512": "9cbdd5e828ed0063c6a56735f3ea503f40059a46882a662afb06127b50b7ca2b71794820f73c927555deddbfbabeb502c5398db281b1c2e9e376716f160affa8",
          "sha256": "27304f979a055522d584fd6e7c34aa7ec6e1cb25c5d84c3b56eada2db6095aa8",
          "sha1": "9d440666da86cb022032b81142aa9780eaaead2",
          "md5": "fdd74819d450b4d181deb80e4a71a4fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core",
          "version": {
            "requires": "0.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a32-0.1.1.jar",
          "url": "ble-characteristic-u2a32-0.1.1.jar",
          "size": 1519,
          "sha512": "9cbdd5e828ed0063c6a56735f3ea503f40059a46882a662afb06127b50b7ca2b71794820f73c927555deddbfbabeb502c5398db281b1c2e9e376716f160affa8",
          "sha256": "27304f979a055522d584fd6e7c34aa7ec6e1cb25c5d84c3b56eada2db6095aa8",
          "sha1": "9d440666da86cb022032b81142aa9780eaaead2",
          "md5": "fdd74819d450b4d181deb80e4a71a4fb"
        }
      ]
    }
  ]
}
