{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-descriptor-u2900-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-android-0.8.6.aar",
          "url": "ble-descriptor-u2900-android-0.8.6.aar",
          "size": 3181,
          "sha512": "514d2099fc55929956d30019669bcb769c7e20ac7499521eccb1e4e0b8b0903fe593eda1a1d0972f8fd2c0c3b27070c7e0a8dfead7cbcd224ca83e79d021f559",
          "sha256": "749f2c129c034338cabc8dce35144eca8c377f08a38f5c434f89f0695945c983",
          "sha1": "91db98ca98fff112f71358ad1fc9798df6cfb03c",
          "md5": "cd308e08bfa06ebffcb6fec8760f0662"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-descriptor",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-descriptor-u2900",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-descriptor-u2900-android-0.8.6.aar",
          "url": "ble-descriptor-u2900-android-0.8.6.aar",
          "size": 3181,
          "sha512": "514d2099fc55929956d30019669bcb769c7e20ac7499521eccb1e4e0b8b0903fe593eda1a1d0972f8fd2c0c3b27070c7e0a8dfead7cbcd224ca83e79d021f559",
          "sha256": "749f2c129c034338cabc8dce35144eca8c377f08a38f5c434f89f0695945c983",
          "sha1": "91db98ca98fff112f71358ad1fc9798df6cfb03c",
          "md5": "cd308e08bfa06ebffcb6fec8760f0662"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-descriptor-u2900-android-0.8.6-sources.jar",
          "url": "ble-descriptor-u2900-android-0.8.6-sources.jar",
          "size": 2297,
          "sha512": "5c2b632c8d14f39331f3c429cbb265f060ea81d68cdb1cae8fd299e0d6d7f882535ffb73825ba982cd1e1586015e039f423401865d57da76ee482b05dd77754e",
          "sha256": "942b1b85f8168a50c76c440fa649d637c779fb53fe26f158130b3301be795ba1",
          "sha1": "f200b83b89aac8958f3691a7259c6c077c351cb2",
          "md5": "b65d5714e4386d814faa4acf8820d157"
        }
      ]
    }
  ]
}
