{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a91-android",
    "version": "0.2.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "ca433b4lujfgjg3mh73jvir65q"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a91-android-0.2.7.aar",
          "url": "ble-characteristic-u2a91-android-0.2.7.aar",
          "size": 3144,
          "sha512": "93d35153b4cde1a05f321a5397960d08a60e9ad3c0a13556f8038bc384aa1eb567467d457dfefa3c36b5edfdba077e9e98301bb63f129861085c22c8efa700ec",
          "sha256": "83a049e39abdf2e0ad28c10f0b0ae818fb01d5160c353fd0ef4593781be9d4f1",
          "sha1": "e24a1f1298efd103b9f0a5329d02be8fd66157d7",
          "md5": "d3abaa7a546e2e5182d08d4941b7051f"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.7"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a91",
          "version": {
            "requires": "0.2.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a91-android-0.2.7.aar",
          "url": "ble-characteristic-u2a91-android-0.2.7.aar",
          "size": 3144,
          "sha512": "93d35153b4cde1a05f321a5397960d08a60e9ad3c0a13556f8038bc384aa1eb567467d457dfefa3c36b5edfdba077e9e98301bb63f129861085c22c8efa700ec",
          "sha256": "83a049e39abdf2e0ad28c10f0b0ae818fb01d5160c353fd0ef4593781be9d4f1",
          "sha1": "e24a1f1298efd103b9f0a5329d02be8fd66157d7",
          "md5": "d3abaa7a546e2e5182d08d4941b7051f"
        }
      ]
    }
  ]
}
