{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a40-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2kquscs33vaubks6hlnwqdrbne"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a40",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a40-android-0.2.2.aar",
          "url": "ble-characteristic-u2a40-android-0.2.2.aar",
          "size": 2929,
          "sha512": "f52d795ec97055c5a85f6dda6a9b8cde0b76501e2853f169f6864ffc26204f364dcd0e00dc8dc0773b1a8b0e6111c1f97d450c78217edd6ccde0a6381e15a4d4",
          "sha256": "77d6a2702a1a62f37170490bbbca0520dccf80e50d6ab3e2ad60fdc579720013",
          "sha1": "838d45fa7f0f826a3b3d7114e0bd66660e5afdcf",
          "md5": "4dcdc8131c84d99d15a8b5d3d9fa47c5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a40",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a40-android-0.2.2.aar",
          "url": "ble-characteristic-u2a40-android-0.2.2.aar",
          "size": 2929,
          "sha512": "f52d795ec97055c5a85f6dda6a9b8cde0b76501e2853f169f6864ffc26204f364dcd0e00dc8dc0773b1a8b0e6111c1f97d450c78217edd6ccde0a6381e15a4d4",
          "sha256": "77d6a2702a1a62f37170490bbbca0520dccf80e50d6ab3e2ad60fdc579720013",
          "sha1": "838d45fa7f0f826a3b3d7114e0bd66660e5afdcf",
          "md5": "4dcdc8131c84d99d15a8b5d3d9fa47c5"
        }
      ]
    }
  ]
}
