{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a2a",
    "version": "0.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2a-0.8.3.jar",
          "url": "ble-characteristic-u2a2a-0.8.3.jar",
          "size": 1553,
          "sha512": "f51c987d30f30d9790559e79fb7ad43e4e37539caf66b95b3d12c953047640b90a21067add7cd4645907e0848898948e33fcda6aa487d4352347a62e8de3e082",
          "sha256": "604383bb2f201b4bb49e7251bac754090f87cb3cd4a8f8d0bd06c58d0586d9cf",
          "sha1": "de5e6ab3fbbdbfa2088af550fdb2d359b4f70ca9",
          "md5": "4bdd1a5da78bc85b128ba331b916f046"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a2a-0.8.3.jar",
          "url": "ble-characteristic-u2a2a-0.8.3.jar",
          "size": 1553,
          "sha512": "f51c987d30f30d9790559e79fb7ad43e4e37539caf66b95b3d12c953047640b90a21067add7cd4645907e0848898948e33fcda6aa487d4352347a62e8de3e082",
          "sha256": "604383bb2f201b4bb49e7251bac754090f87cb3cd4a8f8d0bd06c58d0586d9cf",
          "sha1": "de5e6ab3fbbdbfa2088af550fdb2d359b4f70ca9",
          "md5": "4bdd1a5da78bc85b128ba331b916f046"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a2a-0.8.3-javadoc.jar",
          "url": "ble-characteristic-u2a2a-0.8.3-javadoc.jar",
          "size": 110230,
          "sha512": "604abaf2b07ec6a53f6482cf4d4cad057be1eab1e7c9d20b476ad3f6cbff9566d08f218f909cd126c05247bae2b2a9d2c8ade27e3baff13ec9d63080cb9cc02b",
          "sha256": "a6bbefdc55dcbcd2befa6cac0155d353291dae462bd6f27f70d010ffa1d1697e",
          "sha1": "55f5e854460ea5811e1efd379ea5b4b0ab787f16",
          "md5": "bc5a0e8ca2936b495d484dc428d17c11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a2a-0.8.3-sources.jar",
          "url": "ble-characteristic-u2a2a-0.8.3-sources.jar",
          "size": 1564,
          "sha512": "9c2662a509f1d270f122c9216d8722424220041ee61fb30b9d89b40fb6ff677777b8d72eaa9905a8371781dcba4b2a881b6b75f599b288f68fb10e94b4df2f56",
          "sha256": "e6d479657e8f7a6dda6602ec1b8f2e1440de6ca5a2b84340dca47bf67670a906",
          "sha1": "1708989945baf430ae63bdcb9b7fa45c675cbfe1",
          "md5": "81eb5b3e5b318839742329735ba62763"
        }
      ]
    }
  ]
}
