{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04-android",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "kwhi4jkvdrgozbrzbba6x42kvm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.2.aar",
          "url": "ble-characteristic-u2a04-android-0.2.2.aar",
          "size": 3069,
          "sha512": "cf7483df43566750dbbfa86e3aa84af4fd09b94d7bb7f43e2d1b8675661a12fc7feeac4b03e30c7acc1a6dc374e8c6163ebd5f7aab89727f597e1a0e4302ef7a",
          "sha256": "832de6597e3d64a0f9c44169cc1fd2a385f2009c866d6d8adc0fe02bca74c59f",
          "sha1": "31537f3f04f275223ad4dbd40fa3705577985f81",
          "md5": "7c431669381abf9fc3eb2e1ac1bd8225"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a04",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-android-0.2.2.aar",
          "url": "ble-characteristic-u2a04-android-0.2.2.aar",
          "size": 3069,
          "sha512": "cf7483df43566750dbbfa86e3aa84af4fd09b94d7bb7f43e2d1b8675661a12fc7feeac4b03e30c7acc1a6dc374e8c6163ebd5f7aab89727f597e1a0e4302ef7a",
          "sha256": "832de6597e3d64a0f9c44169cc1fd2a385f2009c866d6d8adc0fe02bca74c59f",
          "sha1": "31537f3f04f275223ad4dbd40fa3705577985f81",
          "md5": "7c431669381abf9fc3eb2e1ac1bd8225"
        }
      ]
    }
  ]
}
