{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a47-android",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6cu2oomv2fb67ivu2iebxgsxbm"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.0.aar",
          "url": "ble-characteristic-u2a47-android-0.2.0.aar",
          "size": 3000,
          "sha512": "1cbac5197f5882ecdd1a33bb36476880b3425ae8edd8b91d331c19de297b0509707513175f78ca42214a06eb98718fcba2d9787614c8da07751bc0a3a8311f9f",
          "sha256": "bc5713bcca1bdda7b9857fa528a5c2f22b3c4a6b2b0cd8fc7107f08ea332db0b",
          "sha1": "e2403ea60b683d9e196a93f604186831be9340d7",
          "md5": "076bd3e2b68195669a5f5b5ec7779aae"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a47",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a47-android-0.2.0.aar",
          "url": "ble-characteristic-u2a47-android-0.2.0.aar",
          "size": 3000,
          "sha512": "1cbac5197f5882ecdd1a33bb36476880b3425ae8edd8b91d331c19de297b0509707513175f78ca42214a06eb98718fcba2d9787614c8da07751bc0a3a8311f9f",
          "sha256": "bc5713bcca1bdda7b9857fa528a5c2f22b3c4a6b2b0cd8fc7107f08ea332db0b",
          "sha1": "e2403ea60b683d9e196a93f604186831be9340d7",
          "md5": "076bd3e2b68195669a5f5b5ec7779aae"
        }
      ]
    }
  ]
}
