{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a51",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.7.jar",
          "url": "ble-characteristic-u2a51-0.8.7.jar",
          "size": 1455,
          "sha512": "9cb7771c7ed623938b6c4329e8f382283c4256d14ff7517d1c0e84225f8bbb277b015dfacd6c187e4da9ada7ae78982e48a51d15b78f9030c040eb34edc6c687",
          "sha256": "7457b8b7709d01676e5197b2c7f4fbb5efccd48a8323df84d854347f4c519a18",
          "sha1": "6ad9e057f61c222a2bb060e0c86b5ff3bbc1247b",
          "md5": "a370e59ccf3a31fc68f9e5f65cc56130"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.7.jar",
          "url": "ble-characteristic-u2a51-0.8.7.jar",
          "size": 1455,
          "sha512": "9cb7771c7ed623938b6c4329e8f382283c4256d14ff7517d1c0e84225f8bbb277b015dfacd6c187e4da9ada7ae78982e48a51d15b78f9030c040eb34edc6c687",
          "sha256": "7457b8b7709d01676e5197b2c7f4fbb5efccd48a8323df84d854347f4c519a18",
          "sha1": "6ad9e057f61c222a2bb060e0c86b5ff3bbc1247b",
          "md5": "a370e59ccf3a31fc68f9e5f65cc56130"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2a51-0.8.7-javadoc.jar",
          "size": 107128,
          "sha512": "d8b7167c13ef2b11dffdd9529108f6207d2836dc1e4211fc7bf6c13f9e4c83c8be6cdb2af9659d8ad6f68d7a7ed2deb07e215f986b15a6a45208abeecbf9f59a",
          "sha256": "30b4a9b15cf43af9c387c22336aab271e690fba1b2942f5d6456fb6af1d30218",
          "sha1": "215f348c90802c267624cd663d97c0c2d7e9d2df",
          "md5": "fd39208e27b9174ac53df874a0db86e0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a51-0.8.7-sources.jar",
          "url": "ble-characteristic-u2a51-0.8.7-sources.jar",
          "size": 1454,
          "sha512": "d55ad8c68fdf41b4240d827149f072609b1b5371e7970dacfb0df162e07462a8dcaf3ae528c8702afde73394ff94d8b91fc44600e7a58172e6f7b5808c937fcf",
          "sha256": "ce36255044a1b3a8b0ae1abb099b7228519f9a1408643f22cb97dc90df6a0799",
          "sha1": "53bc59e6d53602fe8fb8ce536516bce5b0f14d44",
          "md5": "4a5e752fddb2835df6c2d3469f61e6e6"
        }
      ]
    }
  ]
}
