{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4c-android",
    "version": "0.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "vpvpsxvhqfejjenwlcsmdw6ire"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4c",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4c-android-0.2.5.aar",
          "url": "ble-characteristic-u2a4c-android-0.2.5.aar",
          "size": 3097,
          "sha512": "a86735abde7c2799cf47f60a88e8f7ae899b17d211015576e956cd55dc3fb7c6b6e9657b234a8d534028419492996dbfd189440ae25b77c1a4213e649b6fee23",
          "sha256": "e3c4a3a15d537c2e17e2c0b6aa769591c09d651578429902dc3f1d3fc2e99b8e",
          "sha1": "2bff72d484ac9e39e7b5fb5d40be8585e526b0a0",
          "md5": "dd89db5ee54f3a2806b30dddd7ee9ff4"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.5"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4c",
          "version": {
            "requires": "0.2.4"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4c-android-0.2.5.aar",
          "url": "ble-characteristic-u2a4c-android-0.2.5.aar",
          "size": 3097,
          "sha512": "a86735abde7c2799cf47f60a88e8f7ae899b17d211015576e956cd55dc3fb7c6b6e9657b234a8d534028419492996dbfd189440ae25b77c1a4213e649b6fee23",
          "sha256": "e3c4a3a15d537c2e17e2c0b6aa769591c09d651578429902dc3f1d3fc2e99b8e",
          "sha1": "2bff72d484ac9e39e7b5fb5d40be8585e526b0a0",
          "md5": "dd89db5ee54f3a2806b30dddd7ee9ff4"
        }
      ]
    }
  ]
}
