{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a4a-android",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "6qzyj4vz6fc4vcyskbqyrpmi7i"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4a",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4a-android-0.2.1.aar",
          "url": "ble-characteristic-u2a4a-android-0.2.1.aar",
          "size": 2930,
          "sha512": "c165b1d6ead7399cefedb595ef0f7ab37fadc8b0d8fff98c46e3ca7b5160c4a63a8df203c797cfd467fa9d74c5b859eb5f0d266f4c6fbed3ece7a52c44b19980",
          "sha256": "c12a4c92b49d133b83208552d09bf2e9cdc9a6ea0f90d737e204119633914ab7",
          "sha1": "4a8774d5186a513f20a55c2a132978d3a30b35a2",
          "md5": "800e5157ddfb0998d6068249c4e72a32"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a4a",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core-android",
          "version": {
            "requires": "0.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a4a-android-0.2.1.aar",
          "url": "ble-characteristic-u2a4a-android-0.2.1.aar",
          "size": 2930,
          "sha512": "c165b1d6ead7399cefedb595ef0f7ab37fadc8b0d8fff98c46e3ca7b5160c4a63a8df203c797cfd467fa9d74c5b859eb5f0d266f4c6fbed3ece7a52c44b19980",
          "sha256": "c12a4c92b49d133b83208552d09bf2e9cdc9a6ea0f90d737e204119633914ab7",
          "sha1": "4a8774d5186a513f20a55c2a132978d3a30b35a2",
          "md5": "800e5157ddfb0998d6068249c4e72a32"
        }
      ]
    }
  ]
}
