{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2b82",
    "version": "0.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b82-0.8.7.jar",
          "url": "ble-characteristic-u2b82-0.8.7.jar",
          "size": 1482,
          "sha512": "0e5fdae7b1f4be9d1ac366a4ff19209c06d7fd636bb3583c4f8ee0c12e25f39a0f77dfd6874a909996502876d279b6fcc96eb0b1fb75401840c1fe51e32cff61",
          "sha256": "878cf915e5ef99d27848607133d71df2321a38cc124011b5f793011bea3be3be",
          "sha1": "8cad0005574030d9ab57bbb3d14f12862f9d4e58",
          "md5": "e8c4e2afb5e1c597ddfef3fb9ec5f8ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2b82-0.8.7.jar",
          "url": "ble-characteristic-u2b82-0.8.7.jar",
          "size": 1482,
          "sha512": "0e5fdae7b1f4be9d1ac366a4ff19209c06d7fd636bb3583c4f8ee0c12e25f39a0f77dfd6874a909996502876d279b6fcc96eb0b1fb75401840c1fe51e32cff61",
          "sha256": "878cf915e5ef99d27848607133d71df2321a38cc124011b5f793011bea3be3be",
          "sha1": "8cad0005574030d9ab57bbb3d14f12862f9d4e58",
          "md5": "e8c4e2afb5e1c597ddfef3fb9ec5f8ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b82-0.8.7-javadoc.jar",
          "url": "ble-characteristic-u2b82-0.8.7-javadoc.jar",
          "size": 107261,
          "sha512": "fd805f36e1cf7b9181f479d27a6339e0438dbe97e21d152173200cc25d00aee2327f54ca0c79a762ecd83bdfb73ec87b971e7c12756dfed4d679b2c29362cb82",
          "sha256": "dbd557ab1da812a264fc82190ff955a8e3c612a84496c2e5e36d673ce17d70e4",
          "sha1": "f97a0d04f0958a69e258dc6bbdca3db4018eb455",
          "md5": "a3e3bfc5fb6b27f68ff87e6ebb50db48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2b82-0.8.7-sources.jar",
          "url": "ble-characteristic-u2b82-0.8.7-sources.jar",
          "size": 1469,
          "sha512": "c1303e2fb1ff134173a88216c760dcc88a04b0f97851dd470dc246a071c24eed1b9f30e019f2e0519d1b543a8862f095b1dc16c624a29e7dbcd5862696f80a72",
          "sha256": "e74d54c0d1dbd558af5553b91537c615fd38ee8d2e6a8ec5aed172a5c02bac1b",
          "sha1": "372f270912014b36db4cba086d4cedadc4d01826",
          "md5": "3dfa8ea8ff243577b0f65a3c2256d607"
        }
      ]
    }
  ]
}
