{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a53-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a53",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a53-android-0.8.6.aar",
          "url": "ble-characteristic-u2a53-android-0.8.6.aar",
          "size": 3174,
          "sha512": "5d70a40141c77ca650169aac4e0d1272261cd3b1cd01cd712efba102ec2717095094b53f0a5dcf3d71f6743b06c9a409603efdee8ea3fea7cb45d16a709074d5",
          "sha256": "d7d735dae6452c5444ce3414ce66723db1836a8cf7736960309d43ad9c855d20",
          "sha1": "87ab9cdf3ea92905522a9345ef7a0b86fce5b45c",
          "md5": "1fa31744d2028146f73837365a17cdf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a53",
          "version": {
            "requires": "0.8.6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a53-android-0.8.6.aar",
          "url": "ble-characteristic-u2a53-android-0.8.6.aar",
          "size": 3174,
          "sha512": "5d70a40141c77ca650169aac4e0d1272261cd3b1cd01cd712efba102ec2717095094b53f0a5dcf3d71f6743b06c9a409603efdee8ea3fea7cb45d16a709074d5",
          "sha256": "d7d735dae6452c5444ce3414ce66723db1836a8cf7736960309d43ad9c855d20",
          "sha1": "87ab9cdf3ea92905522a9345ef7a0b86fce5b45c",
          "md5": "1fa31744d2028146f73837365a17cdf1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a53-android-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a53-android-0.8.6-sources.jar",
          "size": 2262,
          "sha512": "60e5dc3244dbbcbf85e8e7d232c64808ee89889c759fc7bcf25dc9b7b519d68ec5365334dc95e93839e320f9edc4f3f315a957f66abcfa788acbeca4d11dcaf9",
          "sha256": "b5fb5bd2cbba5fea811cc7a920f9cf618ccaa65135d956ec6e36915d0067841f",
          "sha1": "c50f1d9258b4b190930a16dc9cfe7365b0efdb8b",
          "md5": "07612c604d23a3d28f7b8ae15f73dd51"
        }
      ]
    }
  ]
}
