{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-anp-android",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ble-profile-anp-android-0.8.6.aar",
          "url": "ble-profile-anp-android-0.8.6.aar",
          "size": 1223,
          "sha512": "6668363aa1803592a16cee999bee5ca24909afec924b0ba2add52cf3613e7293b0f67a18fb2dd041fcf6eb8bd5f7556e55fae69b6cc235d64cd725087b973b1a",
          "sha256": "0e70942751e44ea40b6e2775c2d79b1ef8de8f3f5cce5b2650a2d0684c8a1cc4",
          "sha1": "16d2700dbc58af77e7d8115da137bbeed021183f",
          "md5": "078b9c45ea985d5505f84ec9a18277cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-profile-anp-android-0.8.6.aar",
          "url": "ble-profile-anp-android-0.8.6.aar",
          "size": 1223,
          "sha512": "6668363aa1803592a16cee999bee5ca24909afec924b0ba2add52cf3613e7293b0f67a18fb2dd041fcf6eb8bd5f7556e55fae69b6cc235d64cd725087b973b1a",
          "sha256": "0e70942751e44ea40b6e2775c2d79b1ef8de8f3f5cce5b2650a2d0684c8a1cc4",
          "sha1": "16d2700dbc58af77e7d8115da137bbeed021183f",
          "md5": "078b9c45ea985d5505f84ec9a18277cb"
        }
      ]
    }
  ]
}
