{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-profile-tip-central-android",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "xray4c7snfb4pa73mi5j7qohly"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-central-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-tip-central-android-0.1.3.aar",
          "url": "ble-profile-tip-central-android-0.1.3.aar",
          "size": 6256,
          "sha512": "07173427bb5ed341b29c9419a66faebfaa11be53a91e2f85933e938a8171550dedabee9a0a18fca337ed9c6d46962c8c8ce323f123f8f0d9e7564e211f38783a",
          "sha256": "8336c08bb96caf101a6a1ce3ff9122f640b91a83a55d0551422f4a1023514931",
          "sha1": "869fbde4aefe39e28b06af8dd08696a8f1bc4203",
          "md5": "e8768fcfa0cc4c03b93a590dc1bead84"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-profile-central-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-cts-central-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ndcs-central-android",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-rtus-central-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-profile-tip-central-android-0.1.3.aar",
          "url": "ble-profile-tip-central-android-0.1.3.aar",
          "size": 6256,
          "sha512": "07173427bb5ed341b29c9419a66faebfaa11be53a91e2f85933e938a8171550dedabee9a0a18fca337ed9c6d46962c8c8ce323f123f8f0d9e7564e211f38783a",
          "sha256": "8336c08bb96caf101a6a1ce3ff9122f640b91a83a55d0551422f4a1023514931",
          "sha1": "869fbde4aefe39e28b06af8dd08696a8f1bc4203",
          "md5": "e8768fcfa0cc4c03b93a590dc1bead84"
        }
      ]
    }
  ]
}
