{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-bls-peripheral-android",
    "version": "0.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "37p2fovnzbf6dakjarwobjlw5y"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bls-peripheral-android-0.1.7.aar",
          "url": "ble-service-bls-peripheral-android-0.1.7.aar",
          "size": 4433,
          "sha512": "f8c416e617d649ec80646f083cb1e426a10a8865763fe1426ee1d394114ab384fc697a634f938fcbc019677f63faff330cce9cc9cfd243ea80afd928b2f2b9dc",
          "sha256": "15e067e7bc5fcaae984bf721cbbf81765205961c9e63555b8c25efb16a41420e",
          "sha1": "52003fbc832bc0d5562c6630423d41cbbfb6c604",
          "md5": "039425d5fefa225596ef9be5d633d4a3"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-peripheral-android",
          "version": {
            "requires": "0.1.6"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-bls-android",
          "version": {
            "requires": "0.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-bls-peripheral-android-0.1.7.aar",
          "url": "ble-service-bls-peripheral-android-0.1.7.aar",
          "size": 4433,
          "sha512": "f8c416e617d649ec80646f083cb1e426a10a8865763fe1426ee1d394114ab384fc697a634f938fcbc019677f63faff330cce9cc9cfd243ea80afd928b2f2b9dc",
          "sha256": "15e067e7bc5fcaae984bf721cbbf81765205961c9e63555b8c25efb16a41420e",
          "sha1": "52003fbc832bc0d5562c6630423d41cbbfb6c604",
          "md5": "039425d5fefa225596ef9be5d633d4a3"
        }
      ]
    }
  ]
}
