{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2ae3",
    "version": "0.8.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae3-0.8.12.jar",
          "url": "ble-characteristic-u2ae3-0.8.12.jar",
          "size": 1811,
          "sha512": "7eb3fcd0db47225360eab307a53443338351a6617c70204a53a7547e00b249b7faa69f19164d299ca5536b8248994caf99f878b50c5acf7761a65e4d24a8ec73",
          "sha256": "70cd93063007dd751e506b3fd3abc7a8911bd25182bf52dc0a22a7795987e86d",
          "sha1": "27f3a8815b30fed287129692eef10112755864c5",
          "md5": "77943f804e15263f39a4a2367b285950"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.12"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2ae3-0.8.12.jar",
          "url": "ble-characteristic-u2ae3-0.8.12.jar",
          "size": 1811,
          "sha512": "7eb3fcd0db47225360eab307a53443338351a6617c70204a53a7547e00b249b7faa69f19164d299ca5536b8248994caf99f878b50c5acf7761a65e4d24a8ec73",
          "sha256": "70cd93063007dd751e506b3fd3abc7a8911bd25182bf52dc0a22a7795987e86d",
          "sha1": "27f3a8815b30fed287129692eef10112755864c5",
          "md5": "77943f804e15263f39a4a2367b285950"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae3-0.8.12-javadoc.jar",
          "url": "ble-characteristic-u2ae3-0.8.12-javadoc.jar",
          "size": 107503,
          "sha512": "916235d6fbab6b56ff781557137d005aa1dc3aee95c372c0076aba2c29fad323e70826bf23cbc7b68f2adbaa6f08e1e9c9e81a59108b1c82adcf77ca240e4950",
          "sha256": "af06248ef84519934a44220ea4fd2276bfe8c451b48de26d64ed5b8501060d2b",
          "sha1": "2bd1985889a07d2228a85bc52a91cb4bb3a5c144",
          "md5": "15da6ad9be282500b114e6280097d72c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2ae3-0.8.12-sources.jar",
          "url": "ble-characteristic-u2ae3-0.8.12-sources.jar",
          "size": 1660,
          "sha512": "a242e0b3634ac1f5ea4f58b1e586b6b8c82638f1737593d57a6965285acba82838c3ce18ee9c516afcd95bae9675097a1f83f5e75422a6f80e4947a6fd46d12e",
          "sha256": "32371e35b1a28d92df588d48f6694064f08fd72543a38a69d0b94e156a442fe1",
          "sha1": "9605e2a649b405abb6bbfbca3f0bae9a4fe59260",
          "md5": "135772186ff5202b4ca95eb1a85ffffa"
        }
      ]
    }
  ]
}
