{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a65-android",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qgm5345lfvewjajsd7sfgyhu7u"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.9.aar",
          "url": "ble-characteristic-u2a65-android-0.1.9.aar",
          "size": 3093,
          "sha512": "2cb8273c100893ea806cc9724ceb64833d0bf5d8ffc16576947cf597eaf4fecb677a162cc7f5b52931fb2058663fffc9c30e4e8bc703f003baf40a89a55605f5",
          "sha256": "e5a8690939dc1a662cf2530b42d1d30d5d58fb60eed56ae284b838f11b5a276f",
          "sha1": "e9d8cf8f0e6f055eb56e8659d95048aab24f74e2",
          "md5": "32239d55c3c5c445be73d2d3714ac4de"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-android",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a65",
          "version": {
            "requires": "0.1.7"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a65-android-0.1.9.aar",
          "url": "ble-characteristic-u2a65-android-0.1.9.aar",
          "size": 3093,
          "sha512": "2cb8273c100893ea806cc9724ceb64833d0bf5d8ffc16576947cf597eaf4fecb677a162cc7f5b52931fb2058663fffc9c30e4e8bc703f003baf40a89a55605f5",
          "sha256": "e5a8690939dc1a662cf2530b42d1d30d5d58fb60eed56ae284b838f11b5a276f",
          "sha1": "e9d8cf8f0e6f055eb56e8659d95048aab24f74e2",
          "md5": "32239d55c3c5c445be73d2d3714ac4de"
        }
      ]
    }
  ]
}
