{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a04",
    "version": "0.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.6.jar",
          "url": "ble-characteristic-u2a04-0.8.6.jar",
          "size": 2207,
          "sha512": "ca2e5a3952ffc606a80d8533a3ce1ad725259d9c2a6709e36b35dd43bc9a7a35ba64df43856579a3657f2660091ad84a6b032fa17ee8a2be218407e739ab075f",
          "sha256": "4bbce9d0b4a1f260c1412af2da41ba88179db10a14b46f32e215f0006fabb4bc",
          "sha1": "72ce9915edb1c3ac77e42e6b8b779c9e0e05dd33",
          "md5": "33efda881ff2194dfba7156d50de7bfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.6"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.6.jar",
          "url": "ble-characteristic-u2a04-0.8.6.jar",
          "size": 2207,
          "sha512": "ca2e5a3952ffc606a80d8533a3ce1ad725259d9c2a6709e36b35dd43bc9a7a35ba64df43856579a3657f2660091ad84a6b032fa17ee8a2be218407e739ab075f",
          "sha256": "4bbce9d0b4a1f260c1412af2da41ba88179db10a14b46f32e215f0006fabb4bc",
          "sha1": "72ce9915edb1c3ac77e42e6b8b779c9e0e05dd33",
          "md5": "33efda881ff2194dfba7156d50de7bfc"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.6-javadoc.jar",
          "url": "ble-characteristic-u2a04-0.8.6-javadoc.jar",
          "size": 110257,
          "sha512": "716c1529404586205d5f5f27f88ba71fda4e5ef1de2da6e3610c48c238d93aa7e49cf124bf17003c9bb801e2a50f1a9435db7fa4980cec1bc5c6e8b481d2b6c8",
          "sha256": "bf544ca7b7e5d6360fff1f4ecf3b5cc02be22c35d6fd6d348f01a5fdfcb82acf",
          "sha1": "a9e3bb190d5a816f463cef758f7dd2b6605948fd",
          "md5": "788c749b4543141b819eb9efe9e893df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a04-0.8.6-sources.jar",
          "url": "ble-characteristic-u2a04-0.8.6-sources.jar",
          "size": 2002,
          "sha512": "634787dd42a162eeeb383b1e61e7c0246ca41ab7d6763deacc1e24da027b6556bab6af40a5de936834f65ffe1d70c59dd4cea7a384a3be0edce1464d5b97579c",
          "sha256": "5fc82d9c5ba9858bf5c7f996a78c3079d72fe84bbf940add89a0a021174927bc",
          "sha1": "4eee34aacec23d3566b9080fab76202ee17a463a",
          "md5": "5a110de0db994331421aeaddc2fb5477"
        }
      ]
    }
  ]
}
