{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2bcc",
    "version": "0.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bcc-0.8.1.jar",
          "url": "ble-characteristic-u2bcc-0.8.1.jar",
          "size": 1463,
          "sha512": "8adc52e225a679ce902ea53c8721a995c52557b6cd09df0cd8f2d59ca30d4626ae6f8e5a34b0bfe6c858ce79a8ad282eed1f75739d364b0acae510c62680a2ca",
          "sha256": "b803275d1fa4bfb814e073175d7bfe0f1de1caaf3df1abbd1c639755d59050d2",
          "sha1": "81398471b698911119e76884daac16540e95a5cd",
          "md5": "9bb3f2f698d2772e27cce0f575570105"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2bcc-0.8.1.jar",
          "url": "ble-characteristic-u2bcc-0.8.1.jar",
          "size": 1463,
          "sha512": "8adc52e225a679ce902ea53c8721a995c52557b6cd09df0cd8f2d59ca30d4626ae6f8e5a34b0bfe6c858ce79a8ad282eed1f75739d364b0acae510c62680a2ca",
          "sha256": "b803275d1fa4bfb814e073175d7bfe0f1de1caaf3df1abbd1c639755d59050d2",
          "sha1": "81398471b698911119e76884daac16540e95a5cd",
          "md5": "9bb3f2f698d2772e27cce0f575570105"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bcc-0.8.1-javadoc.jar",
          "url": "ble-characteristic-u2bcc-0.8.1-javadoc.jar",
          "size": 109925,
          "sha512": "935c894fb14790b9cdd9482fd43223680c49b6ef2feaf33b9637c80f42aa4cb9943e4bf06327299e6f2d48006ca7ca261d5eca46a9457156f788352b942bc4e9",
          "sha256": "1f9f0789a4e036499d31f4bb5f99bf93d37a9336ffeeaabd79a62d5e6064c183",
          "sha1": "e4b1100cc7997562b7b3446b58813858dc60b504",
          "md5": "19bae7e1f80c1eb86b688bc6e5c75d3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2bcc-0.8.1-sources.jar",
          "url": "ble-characteristic-u2bcc-0.8.1-sources.jar",
          "size": 1446,
          "sha512": "b4b75dd3685141f24709fb877077047f0d9fbb9f2bafb50cc5639c7a68ee3076f767c6ac241e47f6f6f13619cf381a4e00d11b401c396e3f15d976bc63b19b43",
          "sha256": "cba3a2a184c4d2ce2a4d93e88c36dab5049363bbf320c4c96c3767d6a28709f2",
          "sha1": "91f08f0cd494d606831bba66ecb07fff01040075",
          "md5": "d0660cc89449a6190379c50845b87fd5"
        }
      ]
    }
  ]
}
