{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-service-central-ftms-android",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qljg5tp4s5fhlcf7t6elb774ui"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ftms-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-ftms-android-0.4.0.aar",
          "url": "ble-service-central-ftms-android-0.4.0.aar",
          "size": 13012,
          "sha512": "81cf661a1017abbdecfeeeba85f7e4fab556b372603feaeb206b0d5c073d4065fef868d8e3d22b8d2edab9a80c12d8c8132fec3b824bb2781eca8fdda72abcfe",
          "sha256": "5419399d4887a6a3feb1d2828ac1e91c1337a9ece444cd1755cdb57ea9ace228",
          "sha1": "3a91e42a5ac0c2f3eb9933473f7f5af558d52ad1",
          "md5": "e86150719a3f43fbc4a2c28b6ef5a940"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-service-central-android",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-service-ftms-android",
          "version": {
            "requires": "0.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-service-central-ftms-android-0.4.0.aar",
          "url": "ble-service-central-ftms-android-0.4.0.aar",
          "size": 13012,
          "sha512": "81cf661a1017abbdecfeeeba85f7e4fab556b372603feaeb206b0d5c073d4065fef868d8e3d22b8d2edab9a80c12d8c8132fec3b824bb2781eca8fdda72abcfe",
          "sha256": "5419399d4887a6a3feb1d2828ac1e91c1337a9ece444cd1755cdb57ea9ace228",
          "sha1": "3a91e42a5ac0c2f3eb9933473f7f5af558d52ad1",
          "md5": "e86150719a3f43fbc4a2c28b6ef5a940"
        }
      ]
    }
  ]
}
