{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a1e-android",
    "version": "0.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-android-0.6.1.aar",
          "url": "ble-characteristic-u2a1e-android-0.6.1.aar",
          "size": 3392,
          "sha512": "d800d7124d830ab4c5d1e1238dc7dc2a026528414196696adb52237b0666b633ad768edc778ac8a88f7286531d0230adc47d2d59f2f569c3e31845ed6b09111d",
          "sha256": "0860ce4c56261b2819d1cef231266ef4f83703e999471a920bdc43d740c2a85a",
          "sha1": "0162b906ea71e0260ca9be07c1d2c41364fd5a3d",
          "md5": "06605898a3098ec0256c82aec29b2fe4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-constants-characteristic",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-core",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils-android",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-characteristic-u2a1e",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a1e-android-0.6.1.aar",
          "url": "ble-characteristic-u2a1e-android-0.6.1.aar",
          "size": 3392,
          "sha512": "d800d7124d830ab4c5d1e1238dc7dc2a026528414196696adb52237b0666b633ad768edc778ac8a88f7286531d0230adc47d2d59f2f569c3e31845ed6b09111d",
          "sha256": "0860ce4c56261b2819d1cef231266ef4f83703e999471a920bdc43d740c2a85a",
          "sha1": "0162b906ea71e0260ca9be07c1d2c41364fd5a3d",
          "md5": "06605898a3098ec0256c82aec29b2fe4"
        }
      ]
    }
  ]
}
