{
  "formatVersion": "1.1",
  "component": {
    "group": "org.im97mori",
    "module": "ble-characteristic-u2a03",
    "version": "0.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.5.jar",
          "url": "ble-characteristic-u2a03-0.8.5.jar",
          "size": 1813,
          "sha512": "613525603b686774e50d3b27a07e564a3346e288a50cce17aae314aea9a8014397d70c0ceea3ad04894f6a0fd1844ce3b6ed8bbb6727928f6e04a192cf274588",
          "sha256": "1c334a3305de495b93e1491ed590ff46cc8cfc4c119315c880fe8b16d24efcc1",
          "sha1": "45453a48431e4f74ca11a8559cab2ebebe69259a",
          "md5": "ea5ac1a97c2cc2982f42a6a8018d7695"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.im97mori",
          "module": "ble-core-utils",
          "version": {
            "requires": "0.8.5"
          }
        }
      ],
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.5.jar",
          "url": "ble-characteristic-u2a03-0.8.5.jar",
          "size": 1813,
          "sha512": "613525603b686774e50d3b27a07e564a3346e288a50cce17aae314aea9a8014397d70c0ceea3ad04894f6a0fd1844ce3b6ed8bbb6727928f6e04a192cf274588",
          "sha256": "1c334a3305de495b93e1491ed590ff46cc8cfc4c119315c880fe8b16d24efcc1",
          "sha1": "45453a48431e4f74ca11a8559cab2ebebe69259a",
          "md5": "ea5ac1a97c2cc2982f42a6a8018d7695"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.5-javadoc.jar",
          "url": "ble-characteristic-u2a03-0.8.5-javadoc.jar",
          "size": 107380,
          "sha512": "90cb55afb7367a6bb0c6aadd9a64ea3e38dc6c9350525b878983290d3115020182edbd56c08b267305ac5d155a100e083a79e45fbfb2d0067c0c201445fbefa3",
          "sha256": "f7bf420f84b17cf8e75f5c49f279b8aa045d34deccc6915530472d5582c7f71b",
          "sha1": "b77072bc0bc7158455f6f557ac433a888f52249d",
          "md5": "7b65537de092e44ae81e8cc9c391d043"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ble-characteristic-u2a03-0.8.5-sources.jar",
          "url": "ble-characteristic-u2a03-0.8.5-sources.jar",
          "size": 1649,
          "sha512": "85defec03c904ef7aa2982348b3673d956a714b5a49f8167b1c6462c18a4a1101e499dbe6326282d526036a07cca64609e9f57e0b410fc341c5e858951f6c91e",
          "sha256": "ea0677fecd91291d45973c2f5a1ebe3e383ae7b9ee4657902cc5231b515acd27",
          "sha1": "5f9af497ec7a9c115e2bcbae57ee52e2c84cff00",
          "md5": "6b2eb20563af190881da9250c923f741"
        }
      ]
    }
  ]
}
